ankidroid/Anki-Android

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/CollectionTest.kt, AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/Shared.kt
Kotlin CleanUp CollectionTest.kt and Shared.kt
=> [Kotlin CleanUp] CollectionTest.kt,Shared.kt

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
Kotlin Cleanup in ContentProviderTest.kt
=> Kotlin Cleanup in ContentProviderTest.kt

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
Cleanup in [AbstractFlashcardViewer]
=> Cleanup in [AbstractFlashcardViewer]

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
=> Kotlin Cleanup [Reviewer.kt]

AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
=> [KotlinCleanup] NavigationDrawerActivity

AnkiDroid/src/test/java/com/ichi2/async/ForegroundTaskManager.kt, AnkiDroid/src/test/java/com/ichi2/libanki/TextCardExporterTest.kt
Kotlin CleanUp of TextCardExporterTest.kt,ForegroundTaskManager.kt
=> [Kotlin CleanUp] TextCardExporterTest.kt,ForegroundTaskManager.kt

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/java/com/ichi2/async/Connection.kt
=> Kotlin code clean up

.github/workflows/tests_emulator.yml
failed in testing because directories we deleted were not present (of course)
Unlogged, just that working on workflows themselves means you have the worst dev experience ever
Untested until merged and I run it manually with optional clearCaches set to true
=> test(emulator): make sure optional cache clean is tolerant

AnkiDroid/build.gradle, build.gradle
Standard dependency updates, couldn't get desugar in yet but moving forward...
=> Dependency updates 20221029

AnkiDroid/src/main/java/com/ichi2/utils/IntentUtil.kt
Shows snackbar instead of toast
=> show snackbar instead of toast

AnkiDroid/build.gradle
trying this on a different branch as it *appears* there is cache corruption somewhere
This is speculative, may work may not. Works locally
Related #12164 
Ran all the tests that fail on related PR locally, trying it in CI
Nothing learned yet
=> build(deps): desugar library to 1.2.2

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/res/values/02-strings.xml
You can test it by ensuring that `userMigrationIsInProgress()` return true.
This will probably not be the definitive URL, but it's the best I can find right now, and that's easy to change later
=> Dont sync in migration

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
For Scoped-Storage, I'm trying to improve notification to be able to use it outside of the app. In the mean-time, I want to add some non-nullability request. And this nullable message was in my path.
=> Kotlin cleanup, improving nullability

.idea/dictionaries/usernames.xml, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ScopedStorageMigrationDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/Utils.kt
Code by @Oakkitten. Tested in #12650
=> NF: introduce makeLinksClickableAndShow

AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.kt, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt, AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt, AnkiDroid/src/main/java/com/ichi2/utils/SyncStatus.kt, AnkiDroid/src/main/res/values/02-strings.xml
You can test it by calling `offerToMigrate` in `onCreate()`
Drafted until #12649 and #12671 are merged
But you can already review second commit if you want
=> Add window to Offer to migrate

api/src/main/java/com/ichi2/anki/api/AddContentApi.kt, api/src/main/java/com/ichi2/anki/api/NoteInfo.kt
Ran through the public api methods of the API module and checked the nullability of the methods and made some changes. Each commit features a method change with some comments in the commit message.
The last commit removes the todo about nullability, but I can remove it if anyone else wants a go at checking the nullability.
Fixes? #12310 
Ran all checks.
=> Improve nullability for methods in the api module

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/res/values/03-dialogs.xml
=> Accept Manual back-up

AnkiDroid/src/main/java/com/ichi2/widget/WidgetStatus.kt
Change the type of a function parameter to a non-nullable version of the same type, as indicated by a `@KotlinCleanup` tag.
Related to #10489
Within `com.ichi2.widget.WidgetStatus`, both `fetchSmall` and `fetchDue` accept a nullable `context` parameter of type `Context` which they use once with a non-null assertion operator. Because of this, they were each marked to have `context` made non-null.
I checked for usages of these functions in the codebase and found that each has one usage - `fetchDue` is called in `com.ichi.anki.services.NotificationService` and `fetchSmall` in `com.ichi2.widget.AnkiDroidWidgetSmall`. In both cases, the object that is passed in for `context` is always non-null, as the object that the calling functions are passing in is one that the functions themselves …
=> Kotlin Cleanup: Changed function parameters to non-nullable types

AnkiDroid/src/test/java/com/ichi2/anki/CardTemplatePreviewerTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerCheckDatabaseListenerTest.kt
Kotlin CleanUp of CardTemplatePreviewerTest.kt,DeckPickerCheckDataBaseListener.kt
=> [Kotlin CleanUp ] CardTemplatePreviewerTest.kt,DeckPickerCheckDataBaseListener.kt

AnkiDroid/build.gradle
standard dependency updates PR, mostly seeing if this will work on crop crash issues
=> Dependency updates 20221105

AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt
=> fix: IDE lint in MyAccount.kt

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/ImportTest.kt
=> NF: IDE lint in ImportTest.kt

AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/TypeAnswer.kt
=> NF: remove extra `if` block in TypeAnswerTest.kt

AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerCommandTest.kt
Kotlin CleanUp of AbstractFlashcardViewerCommandTest.kt
Tested on a physical device
=> [Kotlin CleanUp] AbstractFlashcardViewerCommandTest

AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt, AnkiDroid/src/test/java/com/ichi2/testutils/JsonUtils.kt, AnkiDroid/src/test/java/com/ichi2/utils/ResourceLoader.kt
Used val instead of var
Bug #11450 
Note: edited by @Arthur-Milchior, because it's not a fix
=> Used val instead of var

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt, AnkiDroid/src/main/java/com/ichi2/anki/Previewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt, AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Utils.kt, AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.kt
=> [KotlinCleanup] Utils

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
=> scope function

AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt, AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.kt
KotlinCleanup 
Using scope function
used apply for scope function
=> kotlin cleanup scope function

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Changed `var` to `val`
Bug #11450
=> Changed var to val

AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.kt
KotlinCleanup
Scope function at desired places
=> scope function on sched.kt kotlincleanup

AnkiDroid/build.gradle, AnkiDroid/robolectricDownloader.gradle, AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt, api/build.gradle, build.gradle
Mostly standard dependency update however robolectric continues it's trend of breaking changes in the minor version slot (semver violation in my book, but I don't believe they commit to semver, so, fine as far as it goes)
Requisite forward-ports to make that work have been done
=> Dependency updates 20221115

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.kt, AnkiDroid/src/main/res/values/03-dialogs.xml, AnkiDroid/src/main/res/values/16-multimedia-editor.xml
Move string to 03-dialogs.xml
Refactor string 
=> Rearrange string and move to `03-dialogs.xml`

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt, AnkiDroid/src/main/java/com/ichi2/libanki/TextNoteExporter.kt, AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/MissingImageHandlerTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/AnkiPackageExporterTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.kt, AnkiDroid/src/test/java/com/ichi2/testutils/IntentAssert.kt
Changed String.format to String template
Kotlin CleanUp #11449 
=> Changed String.format to String template

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt, AnkiDroid/src/test/java/com/ichi2/anki/dialogs/DeckPickerContextMenuTest.kt
Migrates the LoadDeckCounts CollectionTask to coroutines. Part of #7108 . Each commit has more info about what was done inside.
Ran the tests, checked the app.
=> Migrate the LoadDeckCounts task to coroutine

AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardHtml.kt, AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/TypeAnswer.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt, AnkiDroid/src/main/java/com/ichi2/utils/DiffEngine.kt, AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserNonAndroidTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/StudyOptionsFragmentTest.kt
Used `"""` instead of `"` to avoid `\"`
Bug #11451 
=> Used """ instead of " to avoid \"

AnkiDroid/src/test/java/com/ichi2/anki/ReviewerKeyboardInputTest.kt
kotlinCleanUp of ReviewerKeyboardInputTest.kt
=> [KotlinCleanUp ] ReviewerKeyboardInputTest.kt

AnkiDroid/src/test/java/com/ichi2/anki/ProductionCrashReportingTreeTest.kt
Kotlin CleanUp of ProductionCrashReportingTreeTest.kt
=> [kotlinCleanUp]  ProductionCrashReportingTreeTest.kt

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
=> refactor code in MultimediaEditFieldActivity.kt

AnkiDroid/src/main/java/com/ichi2/ui/FixedTextView.kt
Fix crash when editing note and adding audio
Fixes #12865
https://user-images.githubusercontent.com/76740999/202966195-1b4308ed-fc80-47a1-82f2-fdcd7e9c03a6.mp4
https://user-images.githubusercontent.com/76740999/202966207-f730d33b-3597-430b-afc2-00beebb6c2be.mp4
=> Fix crash when editing note and adding audio

AnkiDroid/src/main/java/com/ichi2/anki/services/BootService.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Media.kt
=> kotlin code cleanup

AnkiDroid/src/test/java/com/ichi2/libanki/UndoTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/sync/HttpSyncerTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/sync/RemoteMediaServerTest.kt, AnkiDroid/src/test/java/com/ichi2/utils/ImportUtilsTest.kt, AnkiDroid/src/test/java/com/ichi2/utils/JSONObjectTest.kt
kotlinCleanUp of HttpSyncerTest.kt,RemoteMediaServerTest.kt,UndoTest
.kt,ImportUtilsTest.kt,JSONObjectTest.kt
=> [kotlinCleanUp ] HttpSyncerTest.kt,RemoteMediaServerTest.kt,UndoTest .kt,ImportUtilsTest.kt,JSONObjectTest.kt

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/java/com/ichi2/libanki/sched/TreeNode.kt
- Removes unsafeCastToType and its instances
- Tests
=> [KotlinCleanup] TreeNode

AnkiDroid/src/main/java/com/ichi2/anki/DeckOptionsActivity.kt
crash fixing arising due to NPE
Fixes #12874
placed ```?```  (a null pref was set at non null)
=> crash fix due to null pointer exception

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Removed neutral button from dialog as it is no longer needed
=> Remove neutral button from dialog (no longer needed)

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Deck.kt, AnkiDroid/src/main/java/com/ichi2/libanki/DecksV16.kt
=> Fix Deck Options with new backend

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
KotlinCleanUp of ContentProviderTest.kt
=> [KotlinCleanUp] ContentProviderTest.kt

AnkiDroid/build.gradle, build.gradle
Standard dependency update PR - nothing really interesting just a bunch of patch vers
=> Dependency updates 20221203

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/AsyncDialogFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportCompleteDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.kt
Fixes #12448
Use fragment resources instead of Application resources
> Have AnkiDroid in system language
Change language to a different one (in this case English)
Language is changed for the most of the app but some dialogs remain in the original language.
Affected dialogs:
Check database
Check media
Restore from backup
Interval in Card Browser
=> Fix dialog language bug

AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.kt
TODO - Use string template and remove neutral button
=> TODO - Use string template and remove neutral button

api/src/main/java/com/ichi2/anki/api/Utils.kt
TODO : Add contract for null -> null and non-null to non-null.
todo
Locally tested on google emulator and compiled successfully 
Debug : 
AnkiDroid Version = 2.16alpha91
Android Version = 12
Manufacturer = Google
Model = sdk_gphone64_x86_64
Webview User Agent = Mozilla/5.0 (Linux; Android 12; sdk_gphone64_x86_64 Build/SE1A.220630.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.114 Mobile Safari/537.36
ACRA UUID = 45057c15-5541-46b3-8da6-3dadf1cea65c
New schema = false
Scheduler = std2
Crash Reports Enabled = false
DatabaseV2 Enabled = true
_Please, go through …
=> Added contract for null -> null and non-null to non-null.

AnkiDroid/src/main/java/com/ichi2/libanki/template/MathJax.kt
NF: fix IDE lint in MathJax.kt
=> NF: fix IDE lint in MathJax.kt

AnkiDroid/src/main/res/layout/about_layout.xml
Duplicated xml ids cause trouble when one wants to add view binding in the future.
Rename id
When view binding will be applied to the project, there is one problem less beforehand
Start app with Google Pixel 4XL, Android 12, then navigate to settings/about.
Tried to implement view binding within forked project, ran into compiler problems
=> fix id duplicate

AnkiDroid/src/main/java/com/ichi2/libanki/sync/HttpSyncer.kt
NF: fix IDE lint in HttpSyncer.kt
=> NF: fix IDE lint in HttpSyncer.kt

AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/OnRenderProcessGoneDelegateTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/dialogs/utils/FragmentTestActivity.kt, AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.kt
Koltin CleanUp of OnRenderProcessGoneDelegateTest,SchedTest.kt,FragmentTestActivity.kt
=> [KotlinCleanUp] OnRenderProcessGoneDelegateTest,SchedTest.kt,FragmentTestActivity.kt

AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV3.kt, AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/ClozeTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/MathJaxClozeTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.kt, build.gradle
Pending https://github.com/ankidroid/Anki-Android-Backend/pull/246
Obsoletes #11963
=> Update to Anki 2.1.55

AnkiDroid/build.gradle, build.gradle
Standard dependency updates. Nothing notable here.
=> Dependency updates 20221221

AnkiDroid/src/main/java/com/ichi2/anki/pages/CardInfo.kt
=> Update card info initializer for 2.1.55

AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTest.kt
Kotlin cleanup of NoteEditorTest.kt
=> Kotlin cleanup of NoteEditorTest.kt

AnkiDroid/src/test/java/com/ichi2/libanki/ExportingTest.kt, AnkiDroid/src/test/java/com/ichi2/testutils/AnkiAssert.kt, AnkiDroid/src/test/java/com/ichi2/testutils/libanki/CollectionAssert.kt
Kotlin Cleanup of  AnkiAssert.kt,CollectionAssert.kt,ExportingTest.kt
=> [Kotlin cleanup] AnkiAssert.kt,CollectionAssert.kt,ExportingTest.kt

AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckDueTreeNode.kt
=> Renamed name to fullDeckName

AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
=> [KotlinCleanup] FieldEditText

AnkiDroid/src/main/res/layout/reviewer_answer_buttons.xml
Added fits window system to adjust the layout
Fixes the issue arising due to the window system fir
Fixes #13028
Closes #13028
Test on google emulator and works fine
=> fixed windows keyboard layout frame position

AnkiDroid/src/test/java/com/ichi2/testutils/MockTime.kt
some IDE lint and comment update
=> minor changes in MockTime.kt

AnkiDroid/src/main/java/com/wildplot/android/parsing/AtomTypes/MathFunctionAtom.kt
=> [KotlinCleanup] MathFunctionAtom

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
=> Uses showDialogThatOffersToMigrateStorage

AnkiDroid/src/main/AndroidManifest.xml
https://developer.android.com/guide/topics/manifest/application-element#fragileuserdata
After scoped storage it is better to warn the user before uninstalling to avoid losing their collection
Add the corresponding tag to the manifest
https://developer.android.com/guide/topics/manifest/application-element#fragileuserdata
On my phone, Android 13:
- Tried to uninstall the app and see if the message to keep data appears
https://developer.android.com/guide/topics/manifest/application-element#fragileuserdata
=> Ask to keep data when uninstalling

AnkiDroid/build.gradle
added version code suffix
Fixes #13101
tested on oneplus nord ce
=> added version code suffix

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
As discussin in Discord. Dialog is not shown if migration takes less than 800ms
=> STOR-07: Dont show the essential migration snackbar if it was too short

AnkiDroid/build.gradle, AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.kt
To ease scoped storage migration testing
=> Add a BuildConfig option to use legacy storage

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
the snackbar disappear after moving the deck.
Change snackbar duration from length_undefined to length_short
- Tests
=> Fixed Snackbar not disappearing after changing the deck path in CardBrowser

AnkiDroid/build.gradle, build.gradle, lint-release.xml
Mostly-standard dependency updates PR - been a while since I did one so quite a few are pending
=> Dependency updates 20220205

AnkiDroid/build.gradle, build.gradle, lint-rules/build.gradle
Standard dependency updates, with one tweak from luktsbit to get the lint change through
With this we are caught up on all the dependency updates that can easily go through, I think
=> Dependency updates 20230206

AnkiDroid/src/main/AndroidManifest.xml, AnkiDroid/src/main/res/layout-land/introduction_layout.xml
FIXME : locked orientation issue
allows horizontal screen on intro screen
Tested on oneplus nord ce
https://user-images.githubusercontent.com/48384865/211105290-3f0879d7-561b-43fc-ad4a-e8a165bf4806.mp4
=> fixed landscape screen issue with intro screen

AnkiDroid/src/main/java/com/ichi2/anki/DeckOptionsActivity.kt
=> Kotlin Cleanup#10489 changed variable res to resources

AnkiDroid/src/main/java/com/ichi2/async/Connection.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
=> Fix all cards being moved to default deck

AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt, AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt
IDE lint issues increase the time to commit as a confirmation is needed
* unused method
* invalid reference
* low-warnings: methods can be made private
=> lint: IDE Lint

AnkiDroid/src/main/java/com/ichi2/anki/ReadText.kt, AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/UIUtils.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/pages/PageChromeClient.kt, AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
Nad a NRE in test code, and these calls looked dodgy.
They weren't the issue, but let's fix them to make it easier for the next dev.
Used conventions from the surrounding code when handing `context == null`
=> kotlin cleanups: nullability

AnkiDroid/src/main/res/values/theme_black.xml
The Application has a black theme, while adding a new card or task the two buttons "Tags" and "Cards" background doesn't look pretty good.
adityarai004:#12476
Changed the color of background as per given in the issue and i just picked up a bit higher contrast color from the color picker android studio.
The approach is pretty simple, just find the corresponding color file in the android studio "project" tab and do a hit and trial of different colors as per requirement.
Just downloaded the source code of ankidroid and cloned it using git desktop and loaded the whole application code in my PC's android studio. Run the app and yeah its done.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your …
=> Changed contrast as per given in issue 12476

AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.kt, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt, AnkiDroid/src/main/res/values/03-dialogs.xml
Fixed #13168 
There was already method for database error but was not implemented so added functionality for it .
=> Added function for database error

AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt, AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt
To be used in https://github.com/ankidroid/Anki-Android/pull/13261 to fix unit tests
=> refactor: extract 'isRobolectric'

AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt, AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldControllerTest.kt
Couple of commits split from https://github.com/ankidroid/Anki-Android/pull/13261
=> Fix Unit Tests for API 30

AnkiDroid/src/test/java/com/ichi2/anki/dialogs/DeckPickerContextMenuTest.kt
These tests will break if the permission dialog is removed, as will be done in https://github.com/ankidroid/Anki-Android/pull/13261
Three flakes: 
* "show space" dialog appeared
* A looper update was required before the dialog was shown
* `updateDeckList()`called `unbury()`
=> Fix Test Flake (after permission dialog removal)

AnkiDroid/src/main/java/com/ichi2/widget/AddNoteWidget.kt
Change introduced in https://github.com/ankidroid/Anki-Android/commit/c53a97fd384d88d34676daa730edcca69e2a6fec#diff-2387c994d5f4b8f50f3169836d46eb502755273ad99b99f934f82607227fad3dR41
Copy/Paste Bug
=> fix: AddNoteWidget - wrong method called

AnkiDroid/src/main/java/com/ichi2/anki/preferences/AppearanceSettingsFragment.kt, AnkiDroid/src/main/res/values/10-preferences.xml
Showing snackbar isn't useful because we can even review card using controller/external keyboard
Closes #12986
Fixes #12940
Closes #12995 
Fixes #13002 
Virtual Emulator ( Pixel 6 Pro API 29 )
=> Removed Snackbar

build.gradle
Requires https://github.com/ankidroid/Anki-Android-Backend/pull/272
=> Update to 2.1.58 backend

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
The menu item is updated to make use of correct singular/plural form.
Fixes  `TODO: currently forcing plural use. This should be changed to use the correct singular/plural form`
Updated the menu item with correct singular/plural form when in multiselect mode.
https://user-images.githubusercontent.com/76740999/211152506-6ae1ad36-7012-4ab8-ac41-d919a49ae118.mp4
https://user-images.githubusercontent.com/76740999/211152515-75d8d1ae-bfd0-42f5-8461-049a46e99c85.mp4
=> Removed forceful plural use with correct singular/plural form

AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.kt
Kotlin cleanup of SchedV2Test.kt
=> Kotlin cleanup of SchedV2Test.kt

AnkiDroid/src/test/java/com/ichi2/utils/JSONArrayTest.kt, AnkiDroid/src/test/java/com/ichi2/utils/JSONObjectTest.kt
Reverts ankidroid/Anki-Android#13290
Broke the build on CI: macOS
Fixes: https://github.com/ankidroid/Anki-Android/issues/13298
=> Revert "remove JSON tests"

AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt, AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt, AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.kt, AnkiDroid/src/main/java/com/ichi2/compat/CompatV33.kt, AnkiDroid/src/main/java/com/ichi2/compat/ResolveInfoCompat.kt, AnkiDroid/src/main/java/com/ichi2/compat/customtabs/CustomTabsHelper.kt
Fix resolveService deprecation
Fixes part of #12364 
Bases myself on #12422 and added a method to compat
I didn't know how to test it
=> Fix resolveService deprecation

AnkiDroid/src/main/java/com/ichi2/anki/FieldEditLine.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.kt, AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt, AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt, AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.kt, AnkiDroid/src/main/java/com/ichi2/compat/CompatV33.kt
part of #12364
Opened the help menu on 21 and 33 emulators
=> fix readSerializable deprecation

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/RecursivePictureMenu.kt, AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt, AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt, AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.kt, AnkiDroid/src/main/java/com/ichi2/compat/CompatV33.kt
part of #12364
Opened the help menu on 21 and 33 emulators
=> Fix readList deprecation

.github/workflows/lint.yml
Fixes a bug in 4.2: https://github.com/creyD/prettier_action/releases/tag/v4.3
Reverts aca72c19588ca682139a321a2883559f77de1dfc
Fixes #13296
=> build(deps): Bump prettier_action to 4.3

AnkiDroid/src/main/java/com/ichi2/preferences/NumberRangePreferenceCompat.kt
https://github.com/ankidroid/Anki-Android/issues/13283#issuecomment-1435222750
> @NeedsTest("removing JvmOverloads should fail"). Removing JvmOverloads is not behavior of the app or user, but of the programmer. What would the test be like? Can we make a test that would somehow recompile the app, removing JvmOverloads, and then run it in an emulator and verify that it crashes? Suppose this test fails, how does this help us?
#13283
Removed the annotation
=> Remove @NeedsTest from a file

AnkiDroid/src/test/java/com/ichi2/anki/ReviewerNoParamTest.kt
https://github.com/ankidroid/Anki-Android/actions/runs/4228301328/jobs/7343616028
=> build(ci): mark 'drawerConflictsIfDown' as flaky

AnkiDroid/build.gradle, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
If a user is not logged in, we risk losing their data
Issue #5304
=> Only offer to migrate storage if logged in

AnkiDroid/src/test/java/com/ichi2/anki/ReviewerNoParamTest.kt
https://github.com/ankidroid/Anki-Android/actions/runs/4229407797/jobs/7345754795
=> flaky test: drawerConflictsIfUp

AnkiDroid/src/main/java/com/ichi2/anki/BackendImporting.kt, AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateBrowserAppearanceEditor.kt, AnkiDroid/src/main/java/com/ichi2/anki/IntroductionActivity.kt, AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt
Related #13315
use AlertDialogBuilder
I opened the dialogs I edited. But I didn't know how to test the dialog on IntroductionActivity
CardTemplateBrowserAppearanceEditor
BackendImporting
=> Use AlertDialog

AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractDeckTreeNode.kt
=> Changed Var to Val in AbstractDeckTreeNode.kt

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/res/drawable/ic_sync_lock_24.xml
Fixes #13129
tested on oneplus nord ce
=> added sync disabled icon to be shown during migration

build.gradle
Imports were fine but showed as errors
- `org.jetbrains.kotlin.gradle.tasks.KotlinCompile`
- `org.jetbrains.kotlin.gradle.tasks.KotlinCompilerExecutionStrategy`
A few new users mentioned this in Discord
Potentially impacts onboarding
inline imports
CI
=> lint: fix 'errors' in build.gradle

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/res/drawable/ic_migration_progress.xml, AnkiDroid/src/main/res/drawable/ic_sync_lock_24.xml, AnkiDroid/src/main/res/layout/migration_progress_menu_layout.xml, AnkiDroid/src/main/res/menu/deck_picker.xml
Added migration progress icon in the menu
Puts the migration icon while we migrate and hides the sync icon
follow up for #13130
=> updated sync icon and migration progress

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Added a refresh call as migration starts
Fixes #13360
Tested on OnePlus Nord ce
=> added `refreshState` call as soon as migration is started

AnkiDroid/build.gradle, api/build.gradle, build.gradle
Pretty standard - just rebased the branch from main and CI should go green, then good to merge
=> Dependency updates 20220228

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/java/com/ichi2/utils/SyncStatus.kt
Minor refactoring
Related: #13356
=> remove unused SyncStatus: 'INCONCLUSIVE'

build.gradle
PR does what the title says...
Related https://github.com/ankidroid/Anki-Android-Backend/pull/273
=> fix(deps): bump anki upstream to 2.1.60

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt
Dialog was showing too often
Fixes #13370
Incorrect conditional (dunce cap emoji)
API 32 emulator
Start questioning slowing down: bugs slipped into alpha
=> fix: "Backup Dialog" for users who sync

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DialogHandler.kt, AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt, AnkiDroid/src/test/java/com/ichi2/testutils/Hamcrest.kt
Minor refactoring. I want to add another dialog for 'user uninstalled', and this improves things by strongly typing a parameter
=> refactor: DeckPicker -  DatabaseErrorDialogType

AnkiDroid/build.gradle
applicationId resValue weren't updated with the customSuffix on parallel builds
Fixes #13398
Add the customSuffix to the applicationId resValue
**HAVEN'T**. I didn't have the time to properly figure out what commands/configurations I had to do to build a release version.
=> Fix opening AnkiWeb account preference

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Replace toast with snackbar.
Tested on Google emulator.
=> fix: Replace toast with snackbar and format code

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
=> refactor in Reviewer.kt

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
Rename `performPermissionRequest` .
Fixes #13413 
Rename the method name.
=> fix: Rename performPermissionRequest

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Related #13315
Replaced AlertDialog instead of MaterialDialog
=> Used AlertDialog instead of MaterialDialog in DeckPicker.kt

AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt
Replaces usages of MaterialDialog with AlertDialog in ManageNotetypes
=> Changed Material Dialog with Alert Dialog for ManageNotetypes.kt.kt

AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
Replaces usages of MaterialDialog with AlertDialog in CoroutineHelpers.kt
=> Changed Material Dialog with Alert Dialog for CoroutineHelpers.kt

AnkiDroid/src/main/java/com/ichi2/anki/preferences/CustomButtonsSettingsFragment.kt, AnkiDroid/src/main/res/values/10-preferences.xml
Fixes #13174 
[default.webm](https://user-images.githubusercontent.com/65113071/227170029-4f54d37e-7dce-4410-a508-5b5e4030a5ea.webm)
=> Showing Warning on Reset to Default button in App bar buttons

AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.kt
Follow up for #13433
Fixes #13429
Tested on one plus nord ce
=> Fixed a conditional check for schedV2

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
Fixes #5024
Checked with Android Studio if the method was used somewhere else
=> Remove unused method

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
part of #8602
used the debugger to see if the deck options launcher worked. I didn't test the previewer fix because I think that it isn't necessary
=> Fix some activityResult deprecations

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
#12364
Use compat methods
I didn't think it was necessary
=> fix deprecation and unchecked cast

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt
A review comment of mine on #13475 which wasn't worth blocking the PR over. 
Close this PR if there are review issues - not worth spending nontrivial time on.
=> refactor: toggleStylus - Kotlin Cleanup

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/WhiteBoardWidthDialog.kt
#13315
use the whiteboard stroke dialog
=> Replace MaterialDialog with AlertDialog

AnkiDroid/src/main/java/com/ichi2/anki/introduction/SetupCollectionFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicTextFieldController.kt, AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/FieldState.kt, AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt, AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt, AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.kt, AnkiDroid/src/main/java/com/ichi2/compat/CompatV33.kt
Fixes part of #12364 
Replace usages with new methods
I don't know how to test this
=> Fix bundle.get deprecation

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
Used Snackbar instead of Toast
Related #13411
=> Showing Snackbar instead of Toast in Reviewer.kt

AnkiDroid/src/main/java/com/ichi2/anki/DeckOptionsActivity.kt
Cleanup @KotlinCleanup("IDE lint")
=> Kotlincleanup DeckOptionsActivity

AnkiDroid/build.gradle, AnkiDroid/jacoco.gradle, build.gradle
Standard dependency updates PR - these have all marinated on the dependency-updates branch already
=> Dependency updates 20230406

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
Replaced Toast with Snackbar
Related #13411 
=> Replaced Toast with Snackbar in CardTemplateEditor.kt

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt, AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt, AnkiDroid/src/main/res/layout/note_editor_toolbar_add_custom_item.xml, AnkiDroid/src/main/res/layout/note_editor_toolbar_edit_custom_item.xml
=> Used AlertDialog instead of MaterialDialog in NoteEditor.kt

AnkiDroid/src/main/java/com/ichi2/anki/IntroductionActivity.kt, AnkiDroid/src/main/res/layout/introduction_layout.xml
Removed done button and bottom separator in Intro screen
Fixes #13380
Changed the visibility.
=> fix: Removed done button and bottom separator in Intro screen

tools/release.sh
First change is to have `<br/>` instead of `\n`. For the sake of the consistency. (And also because I imagine \n would be ignored)
Second change is to add actual new line at the end of HTML new line. Text become more readable.
=> NF: clean  the release message

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt, AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt, AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt, AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.kt, AnkiDroid/src/main/java/com/ichi2/compat/CompatV33.kt, AnkiDroid/src/main/java/com/ichi2/compat/customtabs/CustomTabsHelper.kt
Part of #12364 
use the compat methods
Didn't
=> Fix resolveActivity deprecation

AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt, AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionsCheckResult.kt
A lateinit callback wasn't defined
- Fixes #13527
- Fixes #13529
Define the callback
=> fix: crash on Check Media

AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DebugInfoService.kt
Added product flavor to debug info
Fixes #13584 
Used  BuildConfig.FLAVOR
https://user-images.githubusercontent.com/76740999/230773965-ac503250-5504-4e13-9a1f-a057624b7aa1.mp4
=> fix: Added product flavor to debug info

AnkiDroid/build.gradle, build.gradle
standard dependency updates - nothing controversial in here this time
=> Dependency updates 20230421

AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.kt
It's good to have a cancel button in the dialog
Fixes #13647 
Added negative button in the dialog 
[cancel_video.webm](https://user-images.githubusercontent.com/65113071/233763857-3e8a376f-ef86-4949-b9ac-df1f545c297e.webm)
=> Added cancel button in add note type dialog

AnkiDroid/src/main/java/com/ichi2/anki/ReadText.kt
Replaces usages of MaterialDialog with AlertDialog in ReadText.kt
=> Changed Material Dialog with Alert Dialog for ReadText.kt

AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ScopedStorageService.kt, AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt
#13658 was accidentally merged with pending review comments
Related: #13658 (fixups for this PC)
Related: #13634
=> fixup: MigrationService: Progress is incorrect after service restart

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardSideSelectionDialog.kt
Replaces usages of MaterialDialog with AlertDialog in CardSideSelectionDialog.kt
=> Changed Material Dialog with Alert Dialog for CardSideSelectionDialog.kt

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
Slight code simplification while trying to debug why auto-sync causes crash
=> NF: refactor close

tools/release.sh
Turn on play store upload in release script again
- will abort (like before) if play store rejects us or play build fails
- will only commit/push build tag if play store works
- universal builds happen after play upload so universal doesn't upload
No way to test it but to run it, buckle up...
=> re-enable play store upload attempts

AnkiDroid/build.gradle, build.gradle
All appears non-controversial.
=> Dependency updates 20230425

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt, AnkiDroid/src/main/java/com/ichi2/async/Connection.kt
Thread safety issues when syncing
Fixes #13429
* `withCol` all the things!!!
This is a sloppy fix and needs work
Tested myself and provided Arthur with a series of patch. He says the bug is fixed
I left a TODO here: "synchronous col access. I should have fixed this when it was less vital, but it seemed like a hard problem: d385361a25611cd7ba4e1eedc6a43e635d1e0a93 (#13356)
=> fix: automated sync leads to "collection not open"

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
fix: Custom study dialog language bug
Fixes #13766 
Used `resources`
=> fix: Custom study dialog language bug

AnkiDroid/build.gradle, build.gradle
Standard dependency updates PR, nothing controversial I can see.
Play publishing plugin moved but it seems like it should not impact us, either way I'd like to do this earlier in the beta cycle vs later to make sure publishing still works.
=> Dependency updates 20230503

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Not very important, but I'm trying to debug my auto-sync error and saw this misleading constant name
=> NF: clarify a constant name

AnkiDroid/build.gradle, build.gradle
Everything *seems* okay, these are pretty minor, hopefully not famous last words given the recent revert of lint and material deps
=> Dependency updates 20231305

AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.kt, AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Storage.kt, AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.kt
It was not clear to me, while reading through code, that it's the path to the db and not the folder. So adding it everywhere to not have to follow code to find it
=> NF: add documentation for Path

AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt
Orientation lock for gesture picker dialog 
Related #13432
Tested on google emulator API31
=> orientation lock for gesture picker dialog

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.kt
This is equivalent (at least as long as `when (selectedoption)` is exhaustive), and more readable.
=> NF: Refactor `as DeckPicker`

AnkiDroid/src/main/java/com/ichi2/anki/Info.kt, AnkiDroid/src/main/java/com/ichi2/anki/stats/OverviewStatsBuilder.kt, AnkiDroid/src/main/java/com/ichi2/utils/Colour.kt
Extracted from #13823  ; simple code that makes code slightly more readable
=> NF: refactor Creating hexadecimal string

AnkiDroid/src/main/res/layout/about_layout.xml, AnkiDroid/src/main/res/values/styles.xml
Fixes #13873 
add a button style with feedback
press the about buttons
=> add feedback to about buttons

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
Used Snackbar instead of Toast
Related #13411 
=> Replaced Toast with Snackbar in AnkiDroidJSAPI.kt

AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
#13869 was a null pointer exception on rebuildUi method, so I cleaned some nulls
I don't know #13869 will be fixed by this PR, but cleaning is always good
#13869 was a null pointer exception on rebuildUi method, so I cleaned some nulls
I don't know how to test this
=> NF: clean study options nulls

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
CrashReportService reporting resolving a past TODO
If code throws a error then a report would be send to ACRA
=> send exception report if exception in saveCollectionInBackground

AnkiDroid/src/main/java/com/ichi2/libanki/sched/CardQueue.kt, AnkiDroid/src/main/java/com/ichi2/libanki/sched/LrnCardQueue.kt, AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.kt, AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.kt, AnkiDroid/src/main/java/com/ichi2/libanki/sched/SimpleCardQueue.kt
Some cleaning done during debugging a nullptrexception
=> Makes non-nullable values Queue in sched

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/ImportTest.kt, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt, AnkiDroid/src/main/java/com/ichi2/libanki/CollectionV16.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Models.kt, AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.kt, AnkiDroid/src/main/res/values/03-dialogs.xml, AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/CardTest.kt
#7108
I tried to do something like @lukstbit did in #12787 and used backend methods to do this
I stopped using ConfirmationDialog because it throw a error about context not being attached
[device-2023-06-09-195419.webm](https://github.com/ankidroid/Anki-Android/assets/65715921/ea859a65-3598-4f82-982a-ec59735b3a25)
=> Migrate the FindEmptyCards task to coroutines

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
This function uses the collection; so it would crash if collection was not loaded.
=> NF: move selectDeckFomExtra to onCollectionLoaded

AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.kt
A few changes that I personally thought would be good on top of #12280 
[device-2023-06-10-152148.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/a656f255-93fb-41b8-be5e-07f8b6e629d4)
[device-2023-06-10-151626.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/16d7a507-626b-407b-b9d5-252c9dd141d7)
=> Remove FAB rotation and change duration

AnkiDroid/build.gradle, build.gradle
These are all pretty non-controversial (I've blocked the ones that are...), just catching up with the bot
=> Dependency updates 20230622

AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt, AnkiDroid/src/main/java/com/ichi2/libanki/sync/FullSyncer.kt, AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.kt
Fixes: #13867 
How to test:
* force full sync
* download from ankiweb
* cut internet connection
* check the error message mention internet
Admittedly, it's not perfect message, but still better than the one stating that it's a SD card issue
=> Full Download lost connection show relevant error message

AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/FileUtils.kt
Fixes #14027
Catch the exception and skip the volume. There might be a way to obtain a valid UUID from these strings but if there is I couldn't find anything concrete.
Can't really test since can't reproduce the crash
=> Fix crash when encountering bad storage volume UUID strings

tools/test-commits.sh
https://github.com/ankidroid/Anki-Android/issues/14048#issuecomment-1613923181
=> Run jacoco separately to work around errors; use debug variant only

AnkiDroid/build.gradle, AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.kt, AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt, AnkiDroid/src/main/java/com/ichi2/anki/Info.kt, AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt, AnkiDroid/src/main/java/com/ichi2/libanki/UndoAction.kt, AnkiDroid/src/main/java/com/ichi2/preferences/HeaderPreference.kt, AnkiDroid/src/main/java/com/ichi2/preferences/NumberRangePreferenceCompat.kt, AnkiDroid/src/main/java/com/ichi2/preferences/SliderPreference.kt, AnkiDroid/src/main/java/com/ichi2/ui/RtlCompliantActionProvider.kt, AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/dialogs/DeckPickerContextMenuAndroidTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/dialogs/DeckPickerContextMenuTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogTest.kt, api/build.gradle, build.gradle, gradle.properties
Not your standard dependency updates for the second time - I'm pushing through some relatively large changes now before we cut the branch so that it is easier to straddle the 2.16 vs main divide after (making 2.16 hotfixes easier to do...)
I think these changes are low risk though despite their being in the fundamental toolchains (JDK earlier, gradle plugin now) because they mostly are the "it builds or it doesn't build" kind of changes and they are in such wide adoption + on their current versions that if there are problems the whole world should notice and fix them and we may access the fixes easily
So here we go
Lots and lots and lots of local test runs of jacocoTestReport, lots of CI runs, mutliple working on them etc etc.
The R class is now transitive, it is not a constant and it is …
=> Dependency updates 20230630

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
emulator 13
[backupfail.webm](https://github.com/ankidroid/Anki-Android/assets/65715921/d01d7d5b-7ea0-48e6-b009-0cb8ca753da7)
=> Migrate one of the database error dialogs to AlertDialog

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerConfirmDeleteDeckDialog.kt
emulator 13
[deleteDeck.webm](https://github.com/ankidroid/Anki-Android/assets/65715921/2f1b2257-fd76-4d2a-b199-9369870ae45f)
=> Migrate ConfirmDeleteDeck to AlertDialog

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt
emulator 13
[media1.webm](https://github.com/ankidroid/Anki-Android/assets/65715921/58a5bbbd-e307-4776-87c2-5b7d3590497d)
[media2.webm](https://github.com/ankidroid/Anki-Android/assets/65715921/1698e07e-b377-4d5d-bc66-8c09c44ac606)
=> Migrate MediaCheck to AlertDialog

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/LocaleSelectionDialog.kt
emulator android 13
Before
After
=> Migrate LocaleSelectionDialog to AlertDialog

AnkiDroid/src/main/java/com/ichi2/anki/BackendImporting.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportCompleteDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportReadyDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt, AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogsFactory.kt, AnkiDroid/src/main/res/values/02-strings.xml
1. The title of ”Collection exported successfully” in the middle of exporting process is misleading for users, so this commit will replace it with "Export ready". 
1. Incidentally, 
- The labels of the button of this dialog will be changed. 
- The dialog message will be removed.
- The text of the in-progress message before the dialog will be changed.
- The filenames and the class names related to this dialog will be changed. (`ExportCompleteDialog` -> `ExportReadyDialog`)
- MaterialDialog for this dialog will be replaced with AlertDialog. 
Fixes #13920
Fixes one of  #13315
|  Before  |  After  |
| ---- | ---- |
|**In current backend**![image](https://github.com/ankidroid/Anki-Android/assets/10436072/c32c8b95-3f10-496d-a3f0-fc1e91408f6b) | …
=> Rename the strings related to "Collection exported successfully" to the ones for "Export ready"

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.kt
=> Migrate SyncError to AlertDialog

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt, AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt, AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt, AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/java/com/ichi2/anki/Info.kt, AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt, AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt, AnkiDroid/src/main/java/com/ichi2/anki/Previewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/Statistics.kt, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/VideoPlayer.kt, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
Use ActivityLifecycleCallbacks to log the current lifecycle state: this is better than doing it at `AnkiActivity` because it applies to all activities, not only the ones that subclass AnkiActivity and call the "super" method
On the commits
Open some screens in the app and if the new logs appear
=> Improve activity lifecycle logging

.gitignore
Dont allow the local log files to be added to the git commit so adding them to git ignore because while committing the log files were getting added to the git commit and these are the local files which get generated when we have our local system issue like out of memory so there is no point in allowing them to be added to the commit 
would ignore log files
=> ignore local .log files in git commit

AnkiDroid/src/main/java/com/ichi2/anki/DrawingActivity.kt
Wrong icon tint
Fixes #13838
Created new drawable
=> WhiteBoard Editor item tint color to white

.idea/dictionaries/davidallison.xml, AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/DevOptionsFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/PreferenceUtils.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/SettingsFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/SyncSettingsFragment.kt, AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/analytics/PreferencesAnalyticsTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/preferences/PreferenceTestUtils.kt, AnkiDroid/src/test/java/com/ichi2/anki/preferences/PreferencesTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/reviewer/ActionButtonStatusTest.kt
Fixes #11642 
In the commits. Up to discussion which preferences should/shouldn't be reported.
Most of the PR are changes in `test`, so it shouldn't be too hard to review
API 33 emulator: Tapped and changed some settings to see in logcat if the analytics events are being sent
=> feat: Individual preferences analytics

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt, AnkiDroid/src/main/java/com/ichi2/anki/CardInfo.kt, AnkiDroid/src/main/java/com/ichi2/anki/DeckOptionsActivity.kt, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/java/com/ichi2/anki/FieldEditLine.kt, AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/RecursivePictureMenu.kt, AnkiDroid/src/main/java/com/ichi2/anki/introduction/SetupCollectionFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt, AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/FieldState.kt, AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt, AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionsRequestResults.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/AppearanceSettingsFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/NotificationsSettingsFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/services/BootService.kt, AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt, AnkiDroid/src/main/java/com/ichi2/anki/services/NotificationService.kt, AnkiDroid/src/main/java/com/ichi2/anki/services/ReminderService.kt, AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt, AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt, AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.kt, AnkiDroid/src/main/java/com/ichi2/compat/CompatV23.kt, AnkiDroid/src/main/java/com/ichi2/compat/CompatV33.kt, AnkiDroid/src/main/java/com/ichi2/widget/AddNoteWidget.kt, AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt, AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
Utilize compatibility functions available in AndroidX Core:
- [BundleCompat](https://developer.android.com/reference/androidx/core/os/BundleCompat)
- [IntentCompat](https://developer.android.com/reference/androidx/core/content/IntentCompat)
- [ParcelCompat](https://developer.android.com/reference/androidx/core/os/ParcelCompat)
- [ShortcutInfoCompat](https://developer.android.com/reference/androidx/core/content/pm/ShortcutInfoCompat.Builder)
- [ShortcutManagerCompat](https://developer.android.com/reference/androidx/core/content/pm/ShortcutManagerCompat)
- [IconCompat](https://developer.android.com/reference/androidx/core/graphics/drawable/IconCompat)
- [ActivityCompat](https://developer.android.com/reference/androidx/core/app/ActivityCompat)
- …
=> Utilize AndroidX Compat functions

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt, AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.kt, AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt, AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/ViewerCommandTest.kt
Fixes #14179 
Tested on Android Studio Emulator
=> Added gesture for rescheduling

AnkiDroid/src/main/java/com/ichi2/anki/preferences/CustomButtonsSettingsFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/SettingsFragment.kt
Fixes #14160
Set isSingleLineTitle to false in every pref
change phone font size to maximum and language to japanese
=> fix preferences in single line

README.md
This is my first open source contribution therefore I made a small change in the readme file.
=> fixed README.md file

AnkiDroid/src/main/res/drawable/add_shortcut.xml, AnkiDroid/src/main/res/drawable/browse_shortcut.xml, AnkiDroid/src/main/res/drawable/review_shortcut.xml
Updated the shortcut icon's vector files to adhere with the new UI making it consistent with the other shortcuts in the android following the guidelines 
Fixes #14251
=> shortcut icons updated to be consistent with the UI

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt, AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt, AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt, AnkiDroid/src/main/res/values/10-preferences.xml, AnkiDroid/src/main/res/values/preferences.xml, AnkiDroid/src/main/res/xml/preferences_advanced.xml
Fixes #14277 
I removed the setting and related stuff
the app runned fine on the emulator
=> remove scroll setting

AnkiDroid/src/main/java/com/ichi2/anki/FlagToDisplay.kt, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt, AnkiDroid/src/test/java/com/ichi2/anki/FlagToDisplayTest.kt
I chose a few @NeedsTest Annotations and covered the behaviour with Unit Tests
#13283
I separated the logic-related code from the view-related code in the FlagToDisplay class and covered it with tests.
I ran './gradlew jacocoTestReport' and made sure that my the code is covered in the report
=> #13283 Resolve @NeedsTest Issues for flagToDisplay in Reviewer.kt

.idea/dictionaries/Cath.xml, AnkiDroid/src/main/assets/scripts/card.js
This is a typo fix in comments of %root/assets/scripts/card.js file
spelling mistakes at 2 places in comments/documentation
- Line 11: JavasSript 
- Line 237: middleground
JavasSript -> JavaScript
middleground -> middle-ground
only comments have changed. No breaking changes. Ran and tested on my physical device.
=> Fix typo errors

AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
Multiple failures on Windows, and I want to keep CI green
* Issue #14308
=> tests: mark flaky test

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt
Replaces usages of MaterialDialog with AlertDialog in CardBrowserMySearchesDialog.kt
=> Changed Material Dialog with Alert Dialog for CardBrowserMySearchesDialog.kt

AnkiDroid/build.gradle, build.gradle
Huge batch now that #14171 is in and I won't perturb it by merging these in
=> Dependency updates 20220831

.github/pull_request_template.md
Removed the extra Header at it is clear that this is a PR template and added a comment asking the contributor to fill out the details as a lot of people don't and reviewers have to ask them to do so
=> remove the extra header from the PR template

.github/workflows/milestone.yml
Use the id of the milestone 2.17 in the milestone workflow:
Milestone 2.16 => [https://github.com/ankidroid/Anki-Android/milestone/42](https://github.com/ankidroid/Anki-Android/milestone/42)
Milestone 2.17 => [https://github.com/ankidroid/Anki-Android/milestone/51](https://github.com/ankidroid/Anki-Android/milestone/51)
Closes #14371
=> Assign pull requests and associated issues to milestone 2.17

AnkiDroid/src/main/res/xml/preferences_general.xml
Fixes #14386
made the preference false
saw if the default is false
=> reset preference default to false

AnkiDroid/src/main/res/xml/preferences_appearance.xml
Fixes #14374
add a pref dependency
in the emulator i toggled the dependency false
=> add pref dependency

AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.kt, AnkiDroid/src/main/java/com/ichi2/anki/exception/UnknownDatabaseVersionException.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Storage.kt, AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
Part of #14320 . Remove the Context reference by inlining the method. Also some cleanups for the same class. 
Ran the tests.
=> Refactor the Storage code in libanki

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/Undo.kt, AnkiDroid/src/test/java/com/ichi2/anki/ReviewerKeyboardInputTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
People were annoyed by it showing snackbars over their reviewer for a long time (including me)
Fixes #14278 
Fixes #14359
In the commits
https://github.com/ankidroid/Anki-Android/assets/69634269/3da664f0-15c7-4a53-84fd-cd478e0127a1
=> fix: Reduce reviewer's snackbar time

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
Remniscent of the process of reverting #7061 at f027ef306c75e63f013f209cc7b2f8fe4124f4f9. Didn't want to do it back then because I preferred a quick fix
Emulator 13: bury, suspend and schedule a card and note individually on the reviewer
=> nf: remove setupSubMenu and SubMenuProvider

.idea/dictionaries/anki.xml, AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/Shared.kt, AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt, AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/HtmlGenerator.kt, AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt, AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.kt, AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ScopedStorageService.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Utils.kt, AnkiDroid/src/main/java/com/ichi2/utils/FileUtil.kt, AnkiDroid/src/test/java/com/ichi2/libanki/UtilsTest.kt, AnkiDroid/src/test/java/com/ichi2/utils/ResourceLoader.kt
A cleanup for the utilities file Utils in libanki. Mostly move methods around as those methods didn't really belong to the libanki package and they also had in general only one usage. Also fixes IDE issues and kotlin cleanups(if the libanki package is to be moved to a module we need to remove kotlin cleanups).
I recommend each commit to be reviewed one by one. 
Ran the tests.
=> Cleanup libanki Utils file

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
=> Fix bury note action

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/CardUtils.kt, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/CustomToolbarButton.kt, AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtonStatus.kt, AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ReviewerCustomFonts.kt, AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt, AnkiDroid/src/main/java/com/ichi2/libanki/NotetypeJson.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Notetypes.kt, AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt, AnkiDroid/src/main/java/com/ichi2/themes/HtmlColors.kt, AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt, AnkiDroid/src/main/java/com/ichi2/utils/HashUtil.kt, AnkiDroid/src/test/java/com/ichi2/anki/servicemodel/PreferenceUpgradeServiceTest.kt
> **Note**
> This is my first PR as I am trying to contribute to interesting open-source projects I find. So for any mistake or misunderstanding of any rule, please advise me so I can avoid it in this PR and for next time. Thank you for giving us the opportunity to contribute.
In this PR, I contributed to cleaning the project's Warnings that show up when inspecting the code. This exact PR consists of **renaming Kotlin function names** to match the correct code design standards.
Partially Fixes #13282 
Using the Android Studio Code inspection feature, I identified the warnings and chose to fix the warnings related to the Functions naming.
I have used the refactor option when renaming the functions in order to replace every occurrence of the function name with the new name.
There are no …
=> [Clean up]: Fix Kotlin Function name conventions

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
"Delete note" on the reviewer causes crash 
#14460
Added a Snackbar to show the note deleted
- [✔️] You have a descriptive commit message with a short title (first line, max 50 chars).
- [✔️] You have performed a self-review of your own code
=> Delete Note Bug Fixed on Reviewer

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt, README.md
Broken link for open collective backers
Fixes #14441
=> ammened backers in readme.md

AnkiDroid/src/main/java/com/ichi2/anki/DatabaseCheck.kt, AnkiDroid/src/main/java/com/ichi2/anki/Onboarding.kt, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt, AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/OnRenderProcessGoneDelegate.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialogListener.kt, AnkiDroid/src/main/java/com/ichi2/anki/model/Directory.kt, AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/CustomToolbarButton.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/SyncSettingsFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtonStatus.kt, AnkiDroid/src/main/java/com/ichi2/anki/reviewer/PreviousAnswerIndicator.kt, AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DebugInfoService.kt, AnkiDroid/src/main/java/com/ichi2/anki/services/BootService.kt, AnkiDroid/src/main/java/com/ichi2/anki/services/NotificationService.kt, AnkiDroid/src/main/java/com/ichi2/compat/CompatV31.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt, AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckNode.kt, AnkiDroid/src/main/java/com/ichi2/ui/OnGestureListener.kt, AnkiDroid/src/main/java/com/ichi2/utils/AssetHelper.kt, AnkiDroid/src/main/java/com/ichi2/utils/BitmapUtil.kt, AnkiDroid/src/main/java/com/ichi2/utils/DeckNameComparator.kt, AnkiDroid/src/main/java/com/ichi2/utils/ExifUtil.kt, AnkiDroid/src/main/java/com/ichi2/utils/HashUtil.kt, AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt, AnkiDroid/src/main/java/com/ichi2/utils/MaterialBuilderUtil.kt, AnkiDroid/src/main/java/com/ichi2/utils/NoteFieldDecorator.kt, api/src/main/java/com/ichi2/anki/api/Utils.kt
Clean up Android Studio warnings.
Relates to #13282 
I ran `Inspect code` on Android studio to check for warnings/errors. I refactored the code with the help of IDE to fix the warnings. 
<details>
<summary>Before:</summary>
<br>
</details>
<details>
<summary>After:</summary>
<br>
</details>
I have run `./gradlew test` to test these changes and make sure everything is working fine with no funny errors caused by this. Also relying on the pipeline to show any errors.
=> [Clean up]: Fix Android studio warnings

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt, AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt, AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/java/com/ichi2/anki/ReviewerServer.kt, AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt, AnkiDroid/src/main/java/com/ichi2/anki/pages/AnkiServer.kt, AnkiDroid/src/main/java/com/ichi2/anki/pages/PageChromeClient.kt, AnkiDroid/src/main/java/com/ichi2/libanki/BackendImportExport.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Sync.kt, AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt, AnkiDroid/src/test/java/com/ichi2/testutils/BackendEmulatingOpenConflict.kt, build.gradle
Depends on https://github.com/ankidroid/Anki-Android-Backend/pull/307
=> Update to Anki 23.10

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
- Displaying messages, including error messages, in a snackbar instead of a toast. This covers messages for renaming a deck, as well as creating a deck/subdeck.
We want to display a Snackbar message instead of a Toast when the user renames the deck, or creates a subdeck
Related #13411
I ran unit tests and I manually tested the functionality on an emulator. 
The CreateDeckDialog class has a context object property, so in order to access the Activity.showSnackbar extension function I check if context is an Activity instance first. If it is I can generate the Snackbar message, if not then I fall back to a Toast message.
=> Issue #13411-ShowSnackbarInsteadOfToast,

AnkiDroid/src/main/assets/card_template.html
In the future we should update AnkiDroidBackend to automatically extract this text as part of the bundling process.
Closes #14576
=> Fix misaligned masks in image occlusion

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt, AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/DBTest.kt, AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/MediaTest.kt, AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.kt, AnkiDroid/src/main/java/com/ichi2/anki/MetaDB.kt, AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt, AnkiDroid/src/main/java/com/ichi2/anki/web/HttpFetcher.kt, AnkiDroid/src/main/java/com/ichi2/libanki/DB.kt, AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt, AnkiDroid/src/main/java/com/ichi2/utils/BitmapUtil.kt, AnkiDroid/src/test/java/com/ichi2/compat/CompatCopyFileTest.kt, AnkiDroid/src/test/java/com/ichi2/compat/CompatDirectoryContentTest.kt
=> NF: `use` instead of `close`

.github/workflows/opencollective_notices.yml
=> docs: update opencollective notice to remove GSoC reference

AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt
'Error' severity was too severe and it was a distraction
N/A
=> chore(logs): 'blocked main thread' => warning

AnkiDroid/src/main/java/com/ichi2/libanki/Notetypes.kt, AnkiDroid/src/main/java/com/ichi2/libanki/StdModels.kt, AnkiDroid/src/test/java/com/ichi2/libanki/StorageRustTest.kt, build.gradle
Requires https://github.com/ankidroid/Anki-Android-Backend/pull/314
=> Update to stable 23.10 backend version

AnkiDroid/src/main/assets/card_template.html, AnkiDroid/src/main/java/com/ichi2/anki/ReviewerServer.kt
Should ease future maintenance.
=> Use the bundled I/O styling

.github/pull_request_template.md
A list marker before a issue link expands it to its whole name
e.g.
#10000 
* #10000
=> Add a list marker before `Fixes` in the PR template

AnkiDroid/build.gradle, build.gradle
Mostly standard dependency updates although one I'm particularly happy with as it fixes our currently-irritating new developer onboarding process is the downgrade from an android-gradle-plugin RC to the latest stable release, as spotted by lukstbit
=> Dependency updates 2023108

.github/dependabot.yml, AnkiDroid/build.gradle, AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt, build.gradle
Nothing vital here - just a set of pretty low key dependency updates, with one good clean up + unpin / move forward on the apache commons compress library
I've rebased dependency-updates to main and repushed so this CI run should be indicative of everything ready to go or not
=> Dependency updates 20231117

AnkiDroid/src/test/java/com/ichi2/anki/CardTemplatePreviewerTest.kt
* Regression cover for issue #14694
=> tests: Previewer Ordinal handling: failing tests

AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt, AnkiDroid/src/main/java/com/ichi2/anki/export/ExportType.kt, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt, AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ScopedStorageService.kt, AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt, AnkiDroid/src/main/java/com/ichi2/anki/ui/dialogs/tools/AsyncDialogs.kt, AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt, lint-rules/src/main/java/com/ichi2/anki/lint/utils/Aapt2Util.kt
Resolved weak warnings: converted objects into data objects
Related to #13282 
=> Resolved weak warnings: converted objects into data objects

AnkiDroid/src/main/java/androidx/drawerlayout/widget/ClosableDrawerLayout.kt, AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtons.kt, AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/migrateuserdata/MigrateUserData.kt, AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt, AnkiDroid/src/main/java/com/ichi2/libanki/NotetypeJson.kt, AnkiDroid/src/main/java/com/ichi2/ui/CardBrowserSearchView.kt, AnkiDroid/src/main/java/com/ichi2/ui/CheckBoxTriStates.kt, AnkiDroid/src/main/java/com/ichi2/ui/TextInputEditField.kt, AnkiDroid/src/main/java/com/ichi2/utils/ExtendedFragmentFactory.kt, AnkiDroid/src/test/java/com/ichi2/libanki/CollectionTest.kt, AnkiDroid/src/test/java/com/ichi2/utils/ExtendedFragmentFactoryTest.kt
Resolved warnings: redundant constructs
* Removed warnings
=> Resolved warnings: redundant constructs

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt, AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt, AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardHtml.kt, AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/TTS.kt, AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/TypeAnswer.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt, AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Media.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt, AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/CardTemplatePreviewerTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/PreviewerTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/CollectionTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/FlagTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/MathJaxClozeTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/SchedulerTest.kt
Bunch of preparatory refactors for #14378 
CI + went around clicking things in the app to see if anything crashes
=> refactor: update some libanki methods and clean some things to prepare for the previewer port

AnkiDroid/src/main/java/com/ichi2/anki/preferences/ReviewingSettingsFragment.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt, AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt, AnkiDroid/src/test/java/com/ichi2/libanki/SchedulerTest.kt
fix warning of function naming conversion
issue #13282
emulator
=> [Clean Up] : function naming conversion Warning 

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/res/drawable/ic_pause_circle_filled.xml, AnkiDroid/src/main/res/menu/card_browser_multiselect.xml, AnkiDroid/src/main/res/values/07-cardbrowser.xml
Correct string according to the number of cards
* Fixes #14752
=> browser menu plural update

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
* #14821
* Fixes #14821
This restores previous behaviour
Changed in 7a65160e0e23e20080091a30abdd4c05fc610e06 non-squashed: [48467111a129809db8e2b762383b62635a50427f]
=> fix(CardBrowser): `toggleMark`: mark all if mixed selection of marked/unmarked

build.gradle
=> build(deps): adopt Anki-Android-Backend 0.1.30-anki23.10.1

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardHtml.kt, AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogsFactory.kt, AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt, AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt
fix warning of property naming conversion
issue #13282
emulator
=> [Clean Up] : property naming conversion Warning 

AnkiDroid/build.gradle, build.gradle
Some trivial updates, just syncing up as I head towards an alpha release
=> Dependency updates 20231128

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
* #14839
* Fixes #14839
* Same as #14822
Untested, I'll be adding regression cover to the class in a refactoring
=> fix: suspend all cards if mixed selection

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
=> refactor: remove unused method

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
flagTask -> updateFlagForSelectedRows
small refactoring split out from #14843
* Comment: https://github.com/ankidroid/Anki-Android/pull/14843#discussion_r1410000112
=> refactor(CardBrowser): rename method

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt, AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BrowserOptionsDialog.kt, AnkiDroid/src/main/res/values/02-strings.xml, AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
* Splitting out changes from #14843
Each commit should tell a story: rely on the ViewModel as source of truth for the state of the Activity, then extract a method at a time
Unit tests + briefly tested 'truncate'
=> refactor: some of CardBrowser -> ViewModel

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BrowserOptionsDialog.kt, AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
* Splits out work from #14843
Happy to squash this one
Unit tests + tested briefly on an emulator
=> CardBrowser: refactor 'cardsOrNotes' to Flow

AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
CI was broken by not rebasing #14892 after merging #14859
=> fix broken CI: checkDisplayOrderAfterTogglingCardsToNotes

AnkiDroid/src/main/java/com/ichi2/anki/ReadText.kt
Replaced Toast with Snackbar in ReadText.kt
Related to #13411 
Tested on Android Device 
For Initializing TTS
https://github.com/ankidroid/Anki-Android/assets/65972015/8a8fdd8d-616f-4736-a9c7-8c41ca0cf896
For No text-to-speech language available
https://github.com/ankidroid/Anki-Android/assets/65972015/9f5757c1-7e4f-42db-9432-7ef1e3e5d56b
=> Replaced Toast with Snackbar in ReadText.kt

AnkiDroid/src/main/res/values/02-strings.xml
fix a typo
I believe this doesn't need a key change as it doesn't require a re-translation. We'll see
=> fix: TTS comment

AnkiDroid/build.gradle
Trivial dependency updates, merging in for alpha release
=> Dependency updates 20231208

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt, AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
Further work on
* https://github.com/ankidroid/Anki-Android/pull/14843
⚠️ only unit tests
=> Browser: extract methods

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt, AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
* Fixes #14918 
removed the title
checked the title
=> remove reviewer deck title

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt, AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt, AnkiDroid/src/main/java/com/ichi2/anki/utils/Time.kt, AnkiDroid/src/main/res/values/01-core.xml, AnkiDroid/src/main/res/values/10-preferences.xml, AnkiDroid/src/main/res/values/preferences.xml, AnkiDroid/src/main/res/xml/preferences_appearance.xml
* Fixes #14917 
I removed the eta code
I opened the reviewer
=> remove reviewer ETA

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt
Dismissed  the backup prompt on "never show again"
Fixes https://github.com/ankidroid/Anki-Android/issues/14732
https://github.com/ankidroid/Anki-Android/assets/101629190/9402ee60-9472-4970-af4d-48b5f65ed03a
set ONE_DAY_IN_MS=1 (for frequent popup to test)
=> Dismissed the BackupDialog on never show again selected

build.gradle
=> Update backend version to 0.1.32-anki23.10.1

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt, AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt
=> chore: extract test methods to tests

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/AndroidTtsPlayer.kt, AnkiDroid/src/main/java/com/ichi2/anki/TtsVoices.kt, AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardSoundConfig.kt, AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/SoundPlayer.kt, AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/CardSoundConfigTest.kt, AnkiDroid/src/test/java/com/ichi2/testutils/AndroidTest.kt, AnkiDroid/src/test/java/com/ichi2/testutils/JvmTest.kt, AnkiDroid/src/test/java/com/ichi2/testutils/TestClass.kt
I have a PR to resolve  #14358 which is almost completed. These refactors were included and can be handled beforehand. Please let me know if this is too much for one PR and I'll split further
* #14358
Review focus should be on: [feat: AndroidTtsPlayer.play - handle cancellation](https://github.com/ankidroid/Anki-Android/pull/14967/commits/dcaab5fc79373aed38178da3d21ace8d1c6105f9)
* Split out common methods in `JvmTest` & `RobolectricTest`
* Add comments
* Add cancellation support
* Extract `CardSoundConfig`, add tests + optimize
Unit tests added
=> refactor: Sound/TTS & tests

AnkiDroid/src/main/res/drawable/ic_card_answer.xml, AnkiDroid/src/main/res/drawable/ic_card_question.xml, AnkiDroid/src/main/res/drawable/ic_mode_edit_white.xml
To be consistent
Part of #14949
=> style: change some icons' tint to colorControlNormal

AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt, AnkiDroid/src/main/java/com/ichi2/anki/FlagToDisplay.kt, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/reviewer/CardMarker.kt, AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerCommandTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/FlagToDisplayTest.kt
=> refactor: create Flag Enum

AnkiDroid/src/main/java/com/ichi2/anki/ReviewerServer.kt, AnkiDroid/src/main/java/com/ichi2/anki/pages/AnkiServer.kt
=> refactor: create a constant and move a method at AnkiServer

AnkiDroid/src/main/AndroidManifest.xml, AnkiDroid/src/main/java/com/ichi2/anki/SingleFragmentActivity.kt, AnkiDroid/src/main/res/layout/single_fragment_activity.xml, AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupUnderBackupTest.kt, AnkiDroid/src/test/java/com/ichi2/testutils/ActivityList.kt
=> refactor: add SingleFragmentActivity class

AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt, AnkiDroid/src/main/java/com/ichi2/libanki/SoundKt.kt
=> libanki: add `addPlayButtons()` and rename `addPlayIcons()`

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt, AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/browser/CardBrowserViewModelTest.kt, AnkiDroid/src/test/java/com/ichi2/testutils/JvmTest.kt
* high priority compared to my other `CardBrowser` refactorings
* #14989
* Fixes #14989
* test the problem
* fix the problem
* refactor the problem
* Fix a bug encountered while testing a pure `JvmTest` and explain why it occurred
Unit tests added, one manual test
I actually wasn't planning on refactoring this aspect of the CardBrowser
=> fix: Card Browser Search History removals

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
This is my introduction fix to get to know the projekt. Btw this is a really nice way to welcome new contributors, as the main task is not fixing the warning but setting up your IDE to be able to code. Thanks!
I renamed the variables as my IDE suggested
Just renamed two variables in a small scope, I don't think it needs to have a test written.
The main takeaway here was setting up my IDE. E.g. when I tried to commit my changes I had to update my Java version.
=> Fixed two naming convention issues in CardBrowser.kt

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt, AnkiDroid/src/main/java/com/ichi2/utils/TimeUtil.kt
both within a method, and between two methods
Used to determine whether GZip makes sense
Used for 
* #14926
=> feat: print elapsed time of methods

AnkiDroid/build.gradle
Standard dependency updates - nothing specifically interesting for us in my humble opinion
Hopefully not famous last words
rebased dependency-updates to main so this is fresh + valid even without the merge queue
=> Dependency updates 20231216

AnkiDroid/src/main/res/color/drawer_item_text_light.xml, AnkiDroid/src/main/res/color/faded_primary.xml, AnkiDroid/src/main/res/color/text_color_secondary_light.xml, AnkiDroid/src/main/res/drawable/intro_gradient.xml, AnkiDroid/src/main/res/values/colors.xml, AnkiDroid/src/main/res/values/theme_dark.xml, AnkiDroid/src/main/res/values/theme_light.xml
Things became purple after the 1.11.0 update of the material library because of their new tonal system
Patch some colors to the new tonal system. Note that these won't be final and I intend to change them and finish #13878 after 2.17 is out
Emulator 31
The new tonal system seems like an improvement IMO. Easier to understand and configure
https://github.com/material-components/material-components-android/commit/2114a11378fd801b32cd7431bb8a2c94de4f462c
https://material.io/blog/tone-based-surface-color-m3
=> fix: navigation drawer and settings being purple

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt, AnkiDroid/src/main/java/com/ichi2/anki/CustomMaterialTapTargetPromptBuilder.kt, AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.kt, AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.kt, AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.kt, AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
Hi I used the app for some time and I'd like to contribute. I tried to fix some ide issues to get used with the codebase
* Fixes some of #13282
fix the issues
I built the app in Android 14 emulator 
Nothing
=> fix ide issues

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt, AnkiDroid/src/main/java/com/ichi2/anki/browser/ReverseDirection.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserOrderDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/model/SortType.kt
* more changes from https://github.com/ankidroid/Anki-Android/pull/14843
* merging (not reviewing) is blocked on https://github.com/ankidroid/Anki-Android/pull/14897
Extract method, add helper enum for return value, inline properties and use ViewModel in Dialog
Tests & manually
=> refactor: Browser sort order + direction

AnkiDroid/build.gradle, AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/Gesture.kt, AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/GestureProcessor.kt, AnkiDroid/src/main/res/values/10-preferences.xml
Add shake detection. This paves the way to use the shake gesture to skip a card.
The issue description and comments were very informative.
* Begins to address #14270 
As suggested, this adds the [Seismic](https://github.com/square/seismic/) dependency and implements ``ShakeDetector`` on ``LinkDetectingGestureDetector``. The approach philosophy is "minimal change" where extending current functionality is chosen over big refactors.
Unit/Integration Tests: N/A. This is a proof of concept. I hope someone else can take it from here.
- Android 14 Emulator. Android 13 Physical Device. …
=> feat: add device shake gesture detection

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt, AnkiDroid/src/main/java/com/ichi2/anki/pages/AnkiServer.kt, AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerServer.kt, AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt, AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt, AnkiDroid/src/main/res/drawable/ic_star.xml, AnkiDroid/src/main/res/drawable/ic_star_border_white.xml, AnkiDroid/src/main/res/layout/previewer.xml, AnkiDroid/src/main/res/menu/previewer2.xml, AnkiDroid/src/main/res/values/preferences.xml, AnkiDroid/src/main/res/xml/preferences_dev_options.xml
Currently under a developer option
the pending issue to solve before releasing to the public is handling audio
since right now there are a bunch of TTS work in progress, I'll defer audio handling to later
In the commits.
[prev2.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/f826590e-934d-4484-a252-c516e3a9e189)
=> Port Anki Desktop previewer

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserColumn.kt, AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
Don't have much time today - wanted a quick refactor to keep the commits moving
* Semi-split from https://github.com/ankidroid/Anki-Android/pull/14843
In the large refactor, this was in the ViewModel. I extracted it to a separate file here
=> refactor: extract CardBrowserColumn

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt, AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt, AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
* Split from https://github.com/ankidroid/Anki-Android/pull/14843
* Manually tested searching, filtering by flag + tags. All continued to work
=> Browser: Refactor filters (flag, suspend, marked, tags)

AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt
#13315 
* Fixes some of #13315 
* Fixes #11785
I tested in an android 14 pixel 3a emulator in Android Studio. Here are the screenshots
MaterialDialog library is an archived library to build dialogs
=> Use AlertDialog in control preferences

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt, AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
* More from https://github.com/ankidroid/Anki-Android/pull/14843
=> refactor: Card Browser - Preview

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt, AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
* More from https://github.com/ankidroid/Anki-Android/pull/14843, another ~20 lines down
Manually on API 33 emulator, awaiting CI for other tests
=> refactor: Browser multi select

AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt
fix : Placeholders in delete note type dialog.
Replace strings.
=> fix : Placeholders in delete note type dialog

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
* Part of https://github.com/ankidroid/Anki-Android/pull/14843 which wouldn't fit into a larger PR
=> refactor: updateSelectedCardsFlag

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
* A couple refactors pulled from https://github.com/ankidroid/Anki-Android/pull/14843
Unrelated, should rebase merge. Changes mostly designed to remove 'diff noise' from the above PR before I tackle fixing the final property: `searchTerms`
=> refactor: CardBrowser

AnkiDroid/src/main/assets/scripts/card.js, AnkiDroid/src/main/assets/scripts/js-api.js, AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt, AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt, AnkiDroid/src/main/res/values/02-strings.xml
We have upgraded js api. So, it better to upgrade api from card.js to js-api.js.
* Fixes _Link to the issues._
Removed the implementation from card.js and Abstract card viewer and moved to js-api.js and AnkiDroidJSApi.kt
https://github.com/ankidroid/Anki-Android/blob/main/AnkiDroid/src/main/assets/scripts/js-api.js
=> api upgrade from card.js to js-api.js

AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt, AnkiDroid/src/main/res/values/attrs.xml, AnkiDroid/src/main/res/values/styles.xml, AnkiDroid/src/main/res/values/theme_black.xml, AnkiDroid/src/main/res/values/theme_dark.xml, AnkiDroid/src/main/res/values/theme_light.xml, AnkiDroid/src/main/res/values/theme_plain.xml
The color of the progress bar does not match the App's theme.
* Fixes #14963 
Create a custom dialog
=> Changed color of ProgressBar

.github/workflows/conflict.yaml
Scan PR in current repo and add label to conflicting PR after other PR merged to main branch.
* Fixes #13264
Using https://github.com/actions/github-script
Get all opened pr in current repo, get pr from list then get mergeable state of the pr, also added delay 1 second becuase on merge of other pr to main branch the mergeable state are unknown so after delay, the state may be dirty or clean, if dirty add `Has Conflicts`
Tested on temp repo
https://octokit.github.io/rest.js/v20
https://github.com/actions/github-script
=> github action to check conflict in pr and add label

AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt
* Fixes #15098 
* Added sleep
* Fixed lint
Test-only
=> test: maybe fix flaky test: typedLanguageIsSet

.idea/dictionaries/README.md, .idea/dictionaries/usernames.xml
The typos appear was warning which can be avoided by adding the words to the dictionary, so creating a proper README file to guide the contributors 
=> added README.md file for project dictionaries

AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt, AnkiDroid/src/main/res/values/04-network.xml
Title missing in ProgressDialog
* Fixes #15113
set dialog title
https://github.com/ankidroid/Anki-Android/assets/65113071/c64b46c9-b407-4ecd-98a2-eaeafd9fd759
=> Title in progress dialog

AnkiDroid/src/main/java/com/ichi2/anki/BackendBackups.kt, AnkiDroid/src/main/java/com/ichi2/anki/IntroductionActivity.kt, AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/TypeAnswer.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsList.kt, AnkiDroid/src/main/java/com/ichi2/anki/exception/StorageAccessException.kt, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/MediaPlayer.kt, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/CustomButtonsSettingsFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt, AnkiDroid/src/main/java/com/ichi2/anki/reviewer/PeripheralKeymap.kt, AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/migrateuserdata/MigrateUserData.kt, AnkiDroid/src/main/java/com/ichi2/anki/services/ServiceUtils.kt, AnkiDroid/src/main/java/com/ichi2/anki/workarounds/FullDraggableContainerFix.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt, AnkiDroid/src/main/java/com/ichi2/libanki/BackendImportExport.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Tags.kt, AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt, AnkiDroid/src/main/java/com/ichi2/libanki/backend/model/SortOrderUtil.kt, AnkiDroid/src/main/java/com/ichi2/libanki/sched/Counts.kt, AnkiDroid/src/main/java/com/ichi2/preferences/IncrementerNumberRangePreferenceCompat.kt, AnkiDroid/src/main/java/com/ichi2/ui/ButtonItemAdapter.kt, AnkiDroid/src/main/java/com/ichi2/ui/GesturePicker.kt, AnkiDroid/src/main/java/com/ichi2/ui/RtlCompliantActionProvider.kt, AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt, AnkiDroid/src/main/java/com/ichi2/utils/NetworkUtils.kt, api/src/main/java/com/ichi2/anki/api/AddContentApi.kt
This PR has the changes from #14881 which is now closed. There I tried to fix the conflicts but I missed one issue and because the contributor used the main branch I can't push other changes to that PR. I saved the commit + resolved the review requests regarding comments.
=> Follow-up: Fix Android Studio warnings for redundant constructors

.idea/dictionaries/davidallison.xml, AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
=> refactor: Browser current query text

.github/workflows/label.yml
remove strings label if no changes to i18n files
* Fixes #14776
Added check if no changes then remove strings label.
- https://github.com/actions/github-script
- https://octokit.github.io/rest.js/v20/
=> ci: remove strings label if no changes to i18n files

AnkiDroid/src/main/assets/card_template.html, AnkiDroid/src/main/java/com/ichi2/anki/BackendImporting.kt, AnkiDroid/src/main/java/com/ichi2/anki/ViewerAssetLoader.kt, AnkiDroid/src/main/java/com/ichi2/anki/pages/AnkiPackageImporterFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/pages/AnkiServer.kt, AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt, AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt, AnkiDroid/src/main/java/com/ichi2/libanki/BackendImportExport.kt, AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/SchedulerTest.kt, build.gradle
Requires https://github.com/ankidroid/Anki-Android-Backend/pull/339
The apkg import page has been fixed. Some remaining todos:
- deck config option in export dialog
- https://github.com/ankidroid/Anki-Android/issues/15083#issuecomment-1869911711
Fixes:
- FIxes #15083 
Please squash when merging.
=> Anki 23.12.1

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/AbstractSchedTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/CollectionTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/LaTeXTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/SchedulerTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/TagsTest.kt
* Recovering https://github.com/ankidroid/Anki-Android/pull/13936/commits/56ad53aea1073a5524bea7d8099941d4a9890be5 from https://github.com/ankidroid/Anki-Android/pull/13936/
----
* Imported the patch
* only 2 of the files were conflict-free
* Searched for the codebase and removed usages in tests
=> NF: remove col = col

AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
Fix #15192
* Fixes #15192
Add the same title of the desktop version
=> add stats button title

AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/introduction/SetupCollectionFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/pages/AnkiPackageImporterFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/pages/AnkiServer.kt, AnkiDroid/src/main/java/com/ichi2/anki/pages/CardInfo.kt, AnkiDroid/src/main/java/com/ichi2/anki/pages/CongratsPage.kt, AnkiDroid/src/main/java/com/ichi2/anki/pages/CsvImporter.kt, AnkiDroid/src/main/java/com/ichi2/anki/pages/DeckOptions.kt, AnkiDroid/src/main/java/com/ichi2/anki/pages/ImageOcclusion.kt, AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/pages/PageWebViewClient.kt, AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt, AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt
In the commits.
In the commits. 
Emulator 31: Open the statistics and card info pages to see if things are still loading
=> refactor: Anki pages WebViewClient creation and asset loading

AnkiDroid/src/main/AndroidManifest.xml, AnkiDroid/src/main/assets/scripts/card.js, AnkiDroid/src/main/assets/scripts/js-api.js, AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt, AnkiDroid/src/main/java/com/ichi2/anki/JavaScriptSTT.kt
Option to practice speech for language learning, this feature will be very helpful. Also this feature is not cross platform so it will be better to implement it in JS API, then in JS Addons.
* Fixes #1754
The speech to text is asynchronous so a callback method used to get the result from SpeechRecognizer. Hook added to get result and parse the result. Option to set language, start and stop SpeechRecognizer.
- https://developer.android.com/reference/android/speech/RecognizerIntent
- https://developer.android.com/reference/android/speech/SpeechRecognizer#startListening(android.content.Intent)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. …
=> speech to text js api

AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
I was frustrated that it was difficult to know where errors came from when calling `launchCatchingTask`
I tried https://dev.to/theplebdev/how-to-debug-kotlin-coroutines-in-android-jc, found it didn't work, so just grabbed the stack trace and filtered it to be useful. We really only have this method which we care about currently, and I felt the outcome was clean enough to not look back
API 33 emulator, a log now reads as:
* Note: `runCatchingTask` is not included
```diff
CoroutineHelpersKt E  com.ichi2.anki.exception.StorageAccessException: No write access to AnkiDroid directory /storage/emulated/0/AnkiDroid
at com.ichi2.anki.CollectionHelper$Companion.initializeAnkiDroidDirectory(CollectionHelper.kt:307)
at com.ichi2.anki.CollectionManager.collectionPathInValidFolder(CollectionManager.kt:2 …
```
=> chore: log pre-coroutine stack trace when in DEBUG mode

AnkiDroid/src/main/AndroidManifest.xml, AnkiDroid/src/main/java/com/ichi2/anki/Import.kt, AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt, AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt, AnkiDroid/src/test/java/com/ichi2/anki/IntentHandlerTest.kt
Allow AnkiDroid itself to register for tsv/csv files via intent
* Fixes #15185
Create an intent with meme type csv/tsv
Tested on Google emulator  API33/24/23
=> Allow AnkiDroid to register itself to open tsv/csv files

AnkiDroid/src/main/res/layout/media_check_dialog_body.xml, AnkiDroid/src/main/res/values/attrs.xml, AnkiDroid/src/main/res/values/theme_dark.xml, AnkiDroid/src/main/res/values/theme_light.xml
* Fixes #15263
<details>
<summary>old</summary>
</details>
=> fix: Media check file list dark mode appearance

tools/localization/package.json, tools/localization/yarn.lock
All minor or patch updates, should be fine
=> build(deps): update all javascript deps

AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt, AnkiDroid/src/main/res/layout/my_account.xml, AnkiDroid/src/main/res/values/02-strings.xml, AnkiDroid/src/test/java/com/ichi2/anki/MyAccountTest.kt
AnkiWeb allows login/signup through email only and M3 provides us a method to add error- [Adding errors to a text field](https://github.com/material-components/material-components-android/blob/master/docs/components/TextField.md#adding-errors-to-a-text-field) to a text field and an end icon - [Adding a trailing icon to a text field](https://github.com/material-components/material-components-android/blob/master/docs/components/TextField.md#adding-a-trailing-icon-to-a-text-field) to clear the text or toggle password, so updating that and removing the current method to set the error. Also updating the login logic so that the login button is only enabled if the email and password are filled by the user. (Other option is to keep the login button enabled and set the errors to password field too …
=> Use the new M3 adding errors & end mode icon to clear text field

AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
cause: https://github.com/ankidroid/Anki-Android/commit/2fb2e5ee817f179bc60bb0b65e471f9175430a90
* Fixes #15281
=> fix: stats not appearing

AnkiDroid/build.gradle, tools/localization/package.json, tools/localization/yarn.lock
=> 20240120 Dependency updates

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
from a code review comment, we shouldn't be doing this
=> refactor: remove `getColUnsafe` calls

AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt, AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt, AnkiDroid/src/main/res/values/styles.xml
Add cancel button in sync progress dialog 
* Fixes #12613
Oneplus nord ce
https://github.com/ankidroid/Anki-Android/assets/48384865/aaebe4ab-71f3-4799-89fc-ce4fa385c98a
=> Enhancement: added cancel sync button in sync progress dialog

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt, AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
This makes videos of the screens look better as there's no white bar at the bottom
=> NoteEditor/CardTemplateEditor: Color Nav bar 

AnkiDroid/src/androidTest/java/com/ichi2/anki/PagesTest.kt, AnkiDroid/src/androidTest/java/com/ichi2/anki/ReviewerTest.kt, AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt, AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt, AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt, AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt, AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt, AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt, AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Note.kt, AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt, AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.kt, AnkiDroid/src/test/java/com/ichi2/testutils/TestClass.kt
Revived from 
* https://github.com/ankidroid/Anki-Android/pull/13936/
* https://github.com/ankidroid/Anki-Android/pull/13936/commits/44b5f1b78db1e7d18ebbd257865621407f12133b
This completes the merging of #13936
* Fixes #13936
* Apply patch
* Fix compile errors
* Remove 'test' changes, included in `TestClass`
Unit tests + quick manual runthrough of note editor, card browser and reviewing
I could churn a few less files with a context receiver. I'll introduce this next so we don't have the "introduction of a new concept within a refactor"  problem again for receivers.
=> chore: remove `col` from Note

.github/workflows/tests_unit.yml
```diff
- JUnit Tests (ubuntu-latest
+ JUnit Tests (ubuntu-latest)
```
=> typo: action name (tests)

AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
These two tests are absolutely killing my merge / merge queue productivity
=> ci: add flaky annotation to two really flaky reviewer tests

AnkiDroid/src/main/java/com/ichi2/anki/AndroidTtsPlayer.kt, AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/SoundPlayer.kt, AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/SoundTagPlayer.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Tts.kt
refactor things so it's easier to use them in other contexts (i.e. new previewer/reviewer)
In the commits
Android 31: open [this deck](https://ankiweb.net/shared/info/1243388349) and see if audio and TTS still works correctly
=> refactor + fix: TTSplayer

AnkiDroid/src/main/res/values/10-preferences.xml, AnkiDroid/src/main/res/values/constants.xml
fix : remove Fonts from Appearance summary
* Fixes #15413
Remove suitable strings.
=> fix : remove `Fonts` from Appearance summary

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.kt
This was not intentional, many are broken
* Fixes #15391
Remove implementation
Untested
=> disable gestures on CardTemplatePreviewer

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.kt
the FAB was obscured
* Fixes #14470
* Fixes #14648
added a callback to get a reference so it can be dismissed
here's the video in emulator 31
[test.webm](https://github.com/ankidroid/Anki-Android/assets/65715921/929160d1-685e-4a64-8b23-bc6a07682675)
=> fix snackbar dismiss with FAB

AnkiDroid/build.gradle, build.gradle, gradle/wrapper/gradle-wrapper.properties, gradlew.bat, tools/localization/package.json, tools/localization/yarn.lock
Haven't merged deps through in a while
- junit
- json
- gradle
All look pretty boring
javascript stuff looks really boring
Should be good? Just rebased it to main so this is a clean test I think in CI
=> Dependency updates 20240206

AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/SoundPlayer.kt, AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/SoundTagPlayer.kt, AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt, AnkiDroid/src/main/res/layout/previewer.xml
* Part of #14378 
In the commits
[Screen_recording_20240207_185720.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/0cbca9ce-a642-4455-b13c-0ef4e2d78457)
=> feat: add audio support to the new previewer

AnkiDroid/src/play/AndroidManifest.xml
A link will save time when explaining the issue
=> docs: Google Play Storage restrictions

AnkiDroid/src/main/AndroidManifest.xml, AnkiDroid/src/main/assets/ankidroid.css, AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt, AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerActivity.kt, AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerHelpers.kt, AnkiDroid/src/test/java/com/ichi2/testutils/ActivityList.kt
* Fixes #14378 🎉
In the commits
[Screen_recording_20240207_220617.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/ac437ac7-9663-4222-b136-762283a166df)
[vid.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/b4abc58a-9ad7-4313-ae9e-437ab1593d8e)
=> feat: handle fullscreen videos in the new previewer and warn if media isn't found

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt, AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt, AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt, AnkiDroid/src/main/java/com/ichi2/anki/utils/ext/Long.kt, AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Note.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Notetypes.kt, AnkiDroid/src/main/java/com/ichi2/libanki/StdModels.kt, AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/CardTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/CollectionTest.kt, AnkiDroid/src/test/java/com/ichi2/testutils/TestClass.kt
These were easy and needed to be done someday
In the commits
Trusting CI
=> cleanup: solve some rust cleanups

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt, AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt, AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardHtml.kt, AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Note.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Notetypes.kt, AnkiDroid/src/main/java/com/ichi2/libanki/utils/PythonExtensions.kt, AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.kt
prep for porting the template previewer
In the commits
Unit tests + Did the same steps of #14692 to be sure it wasn't created again.
=> update some libanki stuff related to notes and notetypes

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt, AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt, AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Note.kt, AnkiDroid/src/main/java/com/ichi2/libanki/utils/NotInLibAnki.kt, AnkiDroid/src/test/java/com/ichi2/libanki/CollectionTest.kt, AnkiDroid/src/test/java/com/ichi2/testutils/TestClass.kt
On top of #15476 
In the commits
I'm gonna trust CI
=> libanki: more updates

AnkiDroid/src/main/java/com/ichi2/anki/ReadText.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt, AnkiDroid/src/main/res/values/03-dialogs.xml, AnkiDroid/src/main/res/values/10-preferences.xml, AnkiDroid/src/main/res/values/constants.xml, AnkiDroid/src/main/res/xml/preferences_advanced.xml
* part of #15475
In the commit description
[tts.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/01767f92-00ea-4aa4-bd28-9c6a3d64cb24)
=> start ReadText deprecation process

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
cause:
* method: `onSelectedTags`
* code: `runBlocking { undoableOp { updateNote(note) } }`
* Issue 15477
* ef36c8dfc231c6ae7b92329e164c54f02d51bec4
* da62d3036f2033c70c42407dfd29a9f3e2c9a4b3
* Fixes #15528
Fixed by converting to coroutine
=> fix: onSelectedTags does not hang

.github/workflows/label.yml
added in dc75687938aacaada2d8f529352d9440dfefcae8
* Issue #15453
=> ci: add 'strings' label for SearchPreferences

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/java/com/ichi2/anki/Import.kt
NetworkOnMainThreadException
* Fixes [Bug] copyFileToCache: NetworkOnMainThreadException [#15446](https://github.com/ankidroid/Anki-Android/issues/15446)
Move the execution from the main thread
=> fix: copyFileToCache NetworkOnMainThreadException

AnkiDroid/src/main/res/values/10-preferences.xml, AnkiDroid/src/main/res/xml/preferences_controls.xml, AnkiDroid/src/main/res/xml/preferences_custom_buttons.xml
Discussed on Discord
```diff
- user_action
+ user_actions
```
```diff
- User action
+ User actions
```
Needs @BrayanDSO's approval
=> chore: 'User action' category title: make plural

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
If you had two 'image occlusion' note types, adding a note always went to one
We passed in 0, which was incorrect if the note type was explicitly selected in the editor
This led to the incorrect note type being selected
If there is a note type, use it
API 33 emulator: adding a note, then adding via the 'share' menu
=> fix(note-editor): adding a note goes to selected image occlusion type

AnkiDroid/src/main/java/com/ichi2/anki/deckpicker/BackgroundImage.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/AppearanceSettingsFragment.kt, AnkiDroid/src/main/res/drawable/wallpaper_icon.xml, AnkiDroid/src/main/res/values/02-strings.xml, AnkiDroid/src/main/res/values/03-dialogs.xml, AnkiDroid/src/main/res/xml/preferences_appearance.xml
Toggle button not working in SwitchPreferenceCompat ( Select Image )
* Fixes #15036 
use `setOnPreferenceChangeListener` instead `onPreferenceClickLlistner`
https://github.com/ankidroid/Anki-Android/assets/65113071/2019dc16-bd28-419a-a619-7d870b1156da
=> fix: "Background" toggle not working

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Note.kt, AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt
Part of the #13936 initiative
In the commits
I opened some cards and I am trusting CI
=> chore: remove `col` from TemplateRenderContext

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt, AnkiDroid/src/main/java/com/ichi2/anki/notetype/RenameCardTemplateDialog.kt, AnkiDroid/src/main/res/menu/card_template_editor.xml
=> feat: rename card templates 

AnkiDroid/src/main/assets/ankidroid.css, AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerViewModel.kt, AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerActivity.kt, AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Note.kt
Prep for porting the template previewer
In the commits
Checked some notes in the new previewer to see if it still worked correctly
=> fix + refactor: Generify the new previewer card viewing functionality

AnkiDroid/src/main/java/com/ichi2/anki/pages/PageChromeClient.kt
* Fixes #15658
Use a toast to show the dialog instead
* ⚠️ Untested
`"$url: $message"` -> `http://127.0.0.1:46161/backend/web/deck-options.html: hello world`
=> fix: 'window count is over max!!' 

AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/PermissionItem.kt, AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/PermissionsFragment.kt
=> docs: showManageAllFilesScreen - Timber logs

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt
* Fixes #15651
* no longer crashes due to try..catch
* handle 'msf'
* handle 'raw'
* MSF images now import
* ⚠️ Couldn't test the others
=> fix: obtaining image name from images

AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt
* Fixes  #15623 
The fix would be to return null if an exception is thrown
=> fix: no such column: _display_name

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
Useful for  https://github.com/ankidroid/Anki-Android/issues/14423
=> refactor: move exit() to AnkiActivity

AnkiDroid/build.gradle, api/build.gradle.kts
In this Explicit API mode , the Kotlin compiler does additional checks to ensure more explicit public API definitions. Test files are ignored as they aren’t part of the public API; the explicit API mode only applies to production code.
* Fixes #15705 
Update api/build.gradle.kts
android studio emulator
https://www.baeldung.com/kotlin/explicit-api-mode
=> Update api build.gradle to enable explicitApi()

annotations/README.md
fix warning of property naming conversion
* Changes towards #13282 
emulator
emulator
=> [Clean Up] : unexpected end of file

AnkiDroid/src/androidTest/java/com/ichi2/anki/TestUtils.kt, AnkiDroid/src/main/res/values-sw600dp/bools.xml, AnkiDroid/src/main/res/values/bools.xml
* Fixes part of #9333
i created a resource boolean
it is used in unit tests
=> fix isScreenSw600dp deprecation

.github/pull_request_template.md
A number of new users were filling out the template incorrectly
I feel the `#` and comment makes it more obvious what is expected
=> chore(pr-template): make 'Fixes' more intuitive

AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt, AnkiDroid/src/main/res/values/02-strings.xml
Review follow up from PR #15764: updated key
* #15764
=> chore: update first-run-needed string

AnkiDroid/src/main/res/values/10-preferences.xml, AnkiDroid/src/main/res/xml/preferences_accessibility.xml
* Fixes #15725 
* Fixes #15725 
I did what the issue asked
=> turn preference into SliderPreference

AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
The logs helps with diagnostics when the collection is inaccessible
=> chore(log): CardBrowserViewModel

.github/workflows/sync_translations.yml
=> chore(ci): translation sync: link activity stream

.github/ISSUE_TEMPLATE/config.yml
This is to reduce the number of upstream issues we receive
A discussion on issue 15810 caused this suggestion
* #15810
https://github.com/david-allison/Anki-Android/issues/new/choose
=> chore(issue-template): Add link to Anki Forums

AnkiDroid/src/test/java/com/ichi2/anki/ReviewerNoParamTest.kt
Likely cause:
* https://github.com/ankidroid/Anki-Android/pull/15728
* ~ 35f475ff97c5ceaaef45462094bcd826ffa89eed
=> tests: 'showingCardHidesFullScreen' - flaky on Windows

AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt
For some reason, `extractAvTags` doesn't handle `<>` inside attribute values appropriately, although it is valid HTML, and needs it to be escaped, and the HTML parsing of `parseSourcesToFileScheme` unescaped them automatically (since they don't need to be escaped), and there isn't an way to disable the auto-unescaping.
* Fixes #15826
* Fixes #15851
Using `parseSourcesToFileScheme` after the tags are extracted solves the issue
With the deck provided in #15826, which now speaks `Lyme disease? Blank`
[Screen_recording_20240310_101920.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/bed86663-5d6c-4a01-87d3-c4981b58a58b)
I need to make a report for Anki desktop about the root issue
=> fix: bad av tags extracting

AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt, AnkiDroid/src/main/res/values/02-strings.xml, AnkiDroid/src/main/res/values/10-preferences.xml, AnkiDroid/src/main/res/xml/preferences_dev_options.xml
* Issue #15755
After this goes in, we'll lint this
=> fix: Capitalization of JavaScript

AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/utils/Resources.kt, AnkiDroid/src/main/java/com/ichi2/anki/utils/ext/Fragment.kt, AnkiDroid/src/main/res/layout/previewer.xml, AnkiDroid/src/main/res/layout/template_previewer.xml, AnkiDroid/src/main/res/values/attrs.xml, AnkiDroid/src/main/res/values/styles.xml, AnkiDroid/src/main/res/values/theme_black.xml, AnkiDroid/src/main/res/values/theme_dark.xml, AnkiDroid/src/main/res/values/theme_light.xml
Make things prettier
Emulator 34:
[prev light black.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/09026cd3-035c-4ff0-9460-1716c0b9eef9)
[plain dark.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/2ec6e2dd-13e5-4fbc-84b0-5525ed37bac3)
sometimes with a transparent navigationBarColor, a scrim will be applied to better visualize the buttons
=> UI: add card design to the previewers

AnkiDroid/build.gradle, AnkiDroid/src/main/AndroidManifest.xml, AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt, AnkiDroid/src/main/java/com/ichi2/anki/notifications/NotificationId.kt, AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncMediaWorker.kt, AnkiDroid/src/main/java/com/ichi2/anki/worker/UniqueWorkNames.kt, AnkiDroid/src/main/res/values/01-core.xml
I'm using WorkManager as the persistent job solution for the issue since it was more versatile and backwards compatible than the other option that Android proposes for data sync, that is [user initiated data jobs](https://developer.android.com/about/versions/14/changes/user-initiated-data-transfers)
Also, it has a variety of APIs for setting the work in different conditions, like internet connection and battery level, which are relevant to syncing
note: this doesn't handle the previous MediaSyncListener call that resumed the scoped storage migration process, since the migration apparatus should be removed relatively soon and therefore it isn't worth my time (nor anyone's else IMO)
So, if this is deemed as necessary for merging, consider this as `Needs a new dev` or wait for the migration …
=> feat: sync media in the background

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt, AnkiDroid/src/test/java/com/ichi2/anki/AnkiDroidJsAPITest.kt
The JS API should return value with correct data types. The JS API return the value with types as it is used in the app.
* Fixes #15925
The JSONObject changed to put value into with correct data types.
Tested on device with this deck, [AnkiDroid JS API Test Deck
](https://ankiweb.net/shared/info/1045118423)
=> return value from js-api with correct datatype

AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt, AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/SoundPlayer.kt, AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/SoundTagPlayer.kt, AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerViewModel.kt, AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt, AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerViewModel.kt, AnkiDroid/src/test/java/com/ichi2/anki/previewer/TemplatePreviewerViewModelTest.kt, AnkiDroid/src/test/java/com/ichi2/testutils/TestClass.kt
In the commits
Unit tested :)
I should procrastinate less in doing tests
=> fixes in the template previewer

AnkiDroid/src/main/java/com/ichi2/utils/SyncStatus.kt
* hasBeenMarkedAsChangedInMemory
* markDataAsChanged
* sPauseCheckingDatabase
* sMarkedInMemory
=> refactor: remove unused code [SyncStatus]

AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt, AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DialogHandler.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/SyncSettingsFragment.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt, AnkiDroid/src/main/java/com/ichi2/utils/SyncStatus.kt, AnkiDroid/src/main/res/values/04-network.xml, AnkiDroid/src/main/res/values/09-backup.xml, AnkiDroid/src/main/res/values/preferences.xml, AnkiDroid/src/main/res/xml/preferences_sync.xml
* Fixes #15831
"full sync" -> "one-way sync"
=> Unify the expression of "Full Sync"

AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmUtils.kt, AnkiDroid/src/test/java/com/ichi2/libanki/ConfigTest.kt
Getting Familiar with Project and to sort out weak warnings .#13282
* https://github.com/ankidroid/Anki-Android/issues/13282
1. Changed Value of Var to Val 
2. Replaced the `if (!isValidScopeName) return isValidScopeName` with `if (!isValidScopeName) return false` as it was always false .
Removal of warnings, to maintain the clean code practice
Was not able to inspect code with `Code -> Inspect Code`  had to do as follows :
=> [Cleanup]: Fix Android Studio Warnings {regarding Constant Conditions} #13282

AnkiDroid/src/main/java/com/ichi2/anki/notifications/NotificationId.kt, AnkiDroid/src/main/java/com/ichi2/anki/worker/UniqueWorkNames.kt, AnkiDroid/src/test/java/com/ichi2/anki/ConstantUniquenessTest.kt
Resolves `@NeedsTest("constant values are unique")`
Use Kotlin reflection to check uniqueness for all `public const` values in objects.
1. Create a `public const` property with duplicate values, say `const val TEST = "syncMedia"` in `UniqueWorkNames`
2. The unit test fails
https://youtrack.jetbrains.com/issue/KT-55449/Reflection-IllegalArgumentException-Callable-expects-0-arguments-but-1-were-provided-on-getting-const-property-value-of-Object
=> test: ensure constant uniqueness

AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
notify StudyOptionsFragment when deck deleted on tablet
* Fixes #15921
=> notify StudyOptionsFragment when deck deleted on tablet 

AnkiDroid/src/main/AndroidManifest.xml, AnkiDroid/src/main/java/com/ichi2/anki/Ease.kt, AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerActivity.kt, AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerViewModel.kt, AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt, AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerViewModel.kt, AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/previewer/PreviewerFragmentTest.kt, AnkiDroid/src/test/java/com/ichi2/testutils/ActivityList.kt
In the commits
---
Trusting CI as tests
=> refactor: some prep for starting the reviewer port

AnkiDroid/src/main/assets/scripts/js-api.js, AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt, AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPIConstants.kt, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonData.kt, AnkiDroid/src/test/java/com/ichi2/anki/AnkiDroidJsAPITest.kt, AnkiDroid/src/test/java/com/ichi2/anki/jsaddons/AddonModelTest.kt, AnkiDroid/src/test/resources/test-js-addon.json, AnkiDroid/src/test/resources/valid-ankidroid-js-addon-test.json
* Fixes ReviewerTest::TestMultipleCards failure
In the commits
Unit tests
=> make js api's new/lrn/rev counts integers 

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt, AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupMetaTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/reviewer/BindingTest.kt
* #13282
fixed by basic conventions first I scanned the warnings and then fixed some of the warnings under kotlin hood
=> [Cleanup]: Fix Android Studio Warnings #13282

AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerFragment.kt
Same issue of #16015, but in the previewers
use the deprecated method
I haven't
=> fix(previewers): url loading in API 23

AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt, AnkiDroid/src/main/res/layout/statistics.xml
* Fixes #14991 
* Because of old stale PR created this new PR for historic reference of old refer PR #15068 
1. Open the Hamburger Menu
2. Open the Statistic tab
3. Perform Vertical Scroll and check the toolbar visiblity.
=> feat(Statistics): Hide Toolbar on Scroll

AnkiDroid/src/main/res/layout-sw600dp/preferences.xml
* Fixes #15740
I added a root_layout tag
In the emulator tablet I added showSnackbar manually into AboutFragment to check it
=> fix snackbar in tablet

AnkiDroid/src/main/java/com/ichi2/anki/preferences/HeaderFragment.kt, AnkiDroid/src/main/res/values/preferences.xml, AnkiDroid/src/main/res/xml/preferences_controls.xml, AnkiDroid/src/test/java/com/ichi2/anki/analytics/PreferencesAnalyticsTest.kt
* Fixes #16069
I added the key that was lacking
in the emulator I did the issue reproduction steps
=> fix user actions crash

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt, AnkiDroid/src/main/res/layout/reviewer_answer_buttons.xml
No longer used
Briefly viewed a card for testing
=> chore: remove 'preview_buttons_layout'

AnkiDroid/src/androidTest/java/com/ichi2/anki/reviewer/PeripheralKeymapTest.kt, AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/MetaDB.kt, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt, AnkiDroid/src/main/java/com/ichi2/anki/ReadText.kt, AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/FieldState.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Notetypes.kt, AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt, AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/ScopedStorageAnkiDroidTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MigrateEssentialFilesTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/OperationTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/ScopedStorageMigrationIntegrationTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/SchedulerTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/UtilsTest.kt, AnkiDroid/src/test/java/com/ichi2/testutils/JvmTest.kt, AnkiDroid/src/test/java/com/ichi2/utils/JSONObjectTest.kt, AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilsTest.kt, AnkiDroid/src/test/java/com/ichi2/utils/TagsUtilTest.kt, api/src/main/java/com/ichi2/anki/api/AddContentApi.kt
Cleaning Android Studio Warnings in various Kotlin files
* Related to #13282 
Removed unused imports, changed some java functions to kotlin ones and fixed some code style issues
Ran ./gradlew jacocoUnitTestReport and ./gradlew jacocoAndroidTestReport
- [ X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ X] You have commented your code, particularly in hard-to-understand areas
- [X ] You have performed a self-review of your own code
=> [Cleanup]: Fix Android Studio Warnings in various Kotlin files #13282

AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/ReviewingSettingsFragment.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt, AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt, AnkiDroid/src/main/res/values/10-preferences.xml, AnkiDroid/src/main/res/values/preferences.xml, AnkiDroid/src/main/res/xml/preferences_reviewing.xml, AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/SchedulerTest.kt
fixes 15746
* Fixes #15746
I did like dae said and set it in _loadScheduler() like Anki does
I don't know how to test this
=> remove new timezone handling

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/reviewer/Binding.kt, AnkiDroid/src/main/java/com/ichi2/anki/utils/ext/Int.kt
we want to remove the dependency
```diff
- import com.afollestad.materialdialogs.utils.MDUtil.ifNotZero
+ import com.ichi2.anki.utils.ext.ifNotZero
```
=> chore: extract 'ifNotZero' from materialdialogs

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Try to fix #16061
* Fixes #16061 
Wrap `showSnackbar()` in a `view.post()` call for these snackbars shown from `onCreate()`
- Emulator - Pixel XL (API 31)
- https://stackoverflow.com/questions/66111612/snackbars-setanchorview-does-not-consistently-work-after-launching-an-activity
- https://stackoverflow.com/a/7735122
=> fix: Snackbar is misaligned during startup

AnkiDroid/src/main/res/layout/homescreen.xml
Remove the duplicate background imageView.
* Fixes #
Remove the duplicate background imageView from the layout file.
Tested on:
- Emulator - Pixel XL (API 31)
- Vivo V2238A (API 34)
=> chore: remove the duplicate background imageView

AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
time should be reset before the note is added to avoid rollover issues
* Fixes #16129
I set rollover manually to near my timezone so I could reproduce the issue. Then I tested it after the fix
=> fix flaky tests

AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt, AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
most of the time, we do not expect `showError` in tests
=> chore: showError test diagnostics

AnkiDroid/src/main/res/layout/tags_dialog.xml, AnkiDroid/src/main/res/layout/tags_item_list_dialog.xml
Caught while looking into #15205
Before & After:
=> chore: tags dialog XML layout preview

AnkiDroid/src/main/res/drawable/ic_baseline_check_box_24_inset.xml, AnkiDroid/src/main/res/drawable/ic_baseline_check_box_outline_blank_24_inset.xml, AnkiDroid/src/main/res/drawable/ic_baseline_indeterminate_check_box_24_inset.xml
* Fixes #15205 
Replaced insetLeft with PaddingLeft
=> #15205 Replace inset with padding

AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
The log gives only the status code not the reason, I added the reason too in the log
`Status code -> 16, reason 1008`
=> chore: improve SharedDeckDownloadFragment logging

AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt, AnkiDroid/src/main/java/com/ichi2/anki/utils/ext/CoroutineWorker.kt, AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncMediaWorker.kt
Trying to make sync less sufferable.
#15624 is next
In the commits
Emulator 34.
1. Try syncing with no changed media and fetch media enabled, and likely the notification won't appear
2. Enable autosync and open the app after 10 minutes with no changes to sync → you shouldn't get blocked by the sync dialog
=> feat: sync improvements

AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/PermissionsActivity.kt, AnkiDroid/src/test/java/com/ichi2/anki/ui/windows/permissions/PermissionsActivityTest.kt
```kotlin
@NeedsTest("activity can only be closed by tapping the continue button")
``` 
Unit Test
=> test: close activity by continue button

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerRefresh.kt, AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerCommandTest.kt
Added Unit test to function with @NeedsTest.
* Adds test for fun refreshIfRequired, which was tagged with @NeedsTest("if opExecuted is called while activity is in the background, audio plays onResume").
- Making refreshIfRequired public so it is available for testing.
- Create a companion object for testing.
- Unit test with multiple cases to test for edge cases.
Ran the Unit test multiple times, and ensured it is passing.
=> Created Unit Test for fun refreshIfRequired

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Stack traces in `CardBrowser` were hard to debug
* Related to #16217
* use named functions
* 
```patch
kotlin.NotImplementedError: An operation is not implemented.
+	at com.ichi2.anki.CardBrowser.setupFlows$isInMultiSelectModeChanged(CardBrowser.kt:458)
+	at com.ichi2.anki.CardBrowser.setupFlows$isInMultiSelectModeChanged$15(CardBrowser.kt:475)
+	at com.ichi2.anki.CardBrowser.access$setupFlows$isInMultiSelectModeChanged$15(CardBrowser.kt:110)
+	at com.ichi2.anki.CardBrowser$setupFlows$11.invoke(CardBrowser.kt:475)
+	at com.ichi2.anki.CardBrowser$setupFlows$11.invoke(CardBrowser.kt:475)
-	at com.ichi2.anki.CardBrowser$onCreate$12.invokeSuspend(CardBrowser.kt:468)
-	at com.ichi2.anki.CardBrowser$onCreate$12.invoke(CardBrowser.kt)
at …
```
=> refactor: name viewModel functions

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/scheduling/ForgetCardsDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/scheduling/ForgetCardsViewModel.kt, AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/SchedulerService.kt, AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt, AnkiDroid/src/main/res/layout/dialog_forget_cards.xml, AnkiDroid/src/main/res/values/03-dialogs.xml, AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
* Fixes #14155
* Convert to a dialog
Manually
=> feat: forget cards dialog

AnkiDroid/src/main/assets/flashcard.css
https://github.com/ankitects/anki/blob/00248665d70fad5bf3c1679db0871ae7418d399f/ts/reviewer/reviewer.scss#L13
* Fixes #16236
* Fixes #16227
=> CSS: Match Anki Desktop

AnkiDroid/src/main/assets/scripts/js-api.js
The post base url changed, so it needs to modify for js api also.
`ankidroid.postBaseUrl` added to js base url.
Tested on device with this deck, [AnkiDroid JS API Test Deck](https://ankiweb.net/shared/info/1045118423)
https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-Javascript-API
=> change base url in js-api

AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.kt, AnkiDroid/src/androidTest/java/com/ichi2/anki/ReviewerTest.kt
=> Refactor : createDeckWithCard to support AlertDialog

AnkiDroid/src/main/res/values/02-strings.xml, AnkiDroid/src/main/res/values/03-dialogs.xml
* Fixes #16270
Replace a string
=> chore: replace '...' with '…'

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt, AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt, AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/browser/CardBrowserViewModelTest.kt, AnkiDroid/src/test/java/com/ichi2/testutils/MockUtils.kt, AnkiDroid/src/test/java/com/ichi2/testutils/TestClass.kt
Further extraction of CardBrowser logic into a ViewModel, to enable unit testing
* Partial execution of #14843
Unit tests & brief test
=> refactor: extract search to CardBrowserViewModel

AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt
On Robolectric Windows: `withContext(queue)` is insufficient for serial execution
* also appeared in `withCol` and `withQueue`
This is due to `blockForQueue` being unable to run under `runBlocking`
This initially caused timeouts, then exceptions due to concurrent collection init
* Fixes #16253
A reentrant lock
https://github.com/david-allison/Anki-Android/actions/runs/8867926036 @ https://github.com/david-allison/Anki-Android/commit/3ba4f9a9f51290fa166f63070094b3b5b627bda7
Thanks to Mike for the anti-flake script
=> test: fix serial execution [Windows Robolectric]

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt, AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerCommandTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
Added Unit test to function with @NeedsTest.
* Created test for onSelectedTags to address "14656: adding tags does not flip the card", and "does not hang and can be called twice".
- Unit test with multiple cases to test for edge cases.
- Ran the Unit test multiple times, and ensured it is passing.
- Verified that Logcat messages are logged.
=> Created test for onSelectedTags.

AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerViewModel.kt
Don't keep activities calls `onPageFinished(isAfterRecreation)`, but the ViewModel has not been initialized previously
* Fixes #16322
Initialize the ViewModel
S21 with 'don't keep activities'
* no longer crashes
* Card is flipped, as `SavedStateHandle` has not been implemented
=> fix(template-previewer): 'currentCard' has not been initialized

AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt
* Fixes #15905
Add the shorctuts
Enable "Hardware input" in the emulator and press the buttons in the reviewer
=> add keyboard shortcuts to flag and mark in previewer

AnkiDroid/src/main/java/com/ichi2/anki/pages/DeckOptions.kt
* Fixes #16238
add a progress dialog
[Screen_recording_20240504_070944.webm](https://github.com/ankidroid/Anki-Android/assets/65715921/1148d721-3e62-4e82-802f-0cfa082a468a)
=> add progress dialog to deck options

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt, AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt, AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
I just looked into a method and started updating it like a robot. When the spell was gone, I stopped it.
I haven't
=> chore: update a part of libanki

AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt, AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
* Fixes #16331
uses qout and aout values correctly
with the unit test that David provided
=> fix tts in browser

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt, AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt, AnkiDroid/src/main/res/menu/card_browser_multiselect.xml, AnkiDroid/src/main/res/values/02-strings.xml, AnkiDroid/src/main/res/values/sentence-case.xml, AnkiDroid/src/test/java/com/ichi2/anki/browser/CardBrowserViewModelTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/ui/internationalization/SentenceCaseTest.kt
* Fixes #14163
Basically the same as 'suspend', but with a snackbar as feedback
Unit tested
<details>
<summary>Screenshots</summary>
</details>
=> feat: Toggle bury

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateNotetype.kt, AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
* Fixes #15878
I adapted the patch that @BrayanDSO supplied in the issue
I opened the previewer in emulator 25 and it worked
=> fix class not found issue in API 25

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
* Fixes #13211
Add the shortcut
I pressed slash with and without the search icon being shown
=> add search keyboard shortcut

.github/ISSUE_TEMPLATE/config.yml
There are now subcategories for AnkiDroid
=> Update forums links

AnkiDroid/src/main/res/layout/extended_category.xml
* Fixes #16412 
* Fixes #16412 
Remove the lines limit
See the screen
=> fix summary overflow

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt, AnkiDroid/src/test/java/com/ichi2/anki/browser/CardBrowserViewModelTest.kt
Final extraction from #14843 before testing
* #14843
~~Please don't merge this until we cut for 2.19~~
=> refactor(card-browser): extract 'launchOptions'

AnkiDroid/src/main/assets/scripts/js-api.js, AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
Adds a JS API function to add a specific tag as requested in #16210 
* #16210 
-  Went through Ankidroid backend, and created function in AnkiDroidJsAPI.kt, and added the function to js-api.js
Compiles and builds.
=> Created JS API function to add a specific tag

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt
Similar issue that we had with other dialogs. This should be the last dialog with this problem.
* Fixes #16478
Ran the tests, checked the dialog.
=> Fix keyboard not appearing for toolbar in TagsDialog

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt, AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt
Unit Test for note editor
Tested locally all tests passed
=> UnitTest : String null test for note editor

AnkiDroid/src/main/AndroidManifest.xml, AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt, AnkiDroid/src/main/java/com/ichi2/themes/Themes.kt, AnkiDroid/src/main/res/layout/activity_instant_note_editor.xml, AnkiDroid/src/main/res/values/01-core.xml, AnkiDroid/src/main/res/values/styles.xml, AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupUnderBackupTest.kt, AnkiDroid/src/test/java/com/ichi2/testutils/ActivityList.kt
Setting up the instant note editor activity
Serves as base for
* #16393
Using single instance attribute in manifest to clear it from recent task
No task affinity to separate from other tasks
creating custom style for this activity
Activity unit test pass
=> [GSoC'24] Init: Instant Note Editor Activity

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/utils/ext/JSONObject.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Config.kt, AnkiDroid/src/main/res/menu/card_browser.xml, AnkiDroid/src/main/res/menu/card_browser_multiselect.xml, AnkiDroid/src/main/res/menu/previewer.xml, AnkiDroid/src/main/res/menu/reviewer.xml
AnkiDroid to use flag  names from col i.e. if user renames it then that name should be visible instead of hardcoding the string.
This PR intends to commit the changes that were reverted which were originally made in #16218
* Fixes #16204
Google emulator 
=> feat: Display custom flag names

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt, AnkiDroid/src/main/java/com/ichi2/libanki/ChangeManager.kt, AnkiDroid/src/test/java/com/ichi2/anki/browser/CardBrowserViewModelTest.kt, AnkiDroid/src/test/java/com/ichi2/testutils/TestChangeSubscriber.kt
Increase test coverage before we refactor
⚠️ Tests only
`undoableOp` inside `launch` was problematic
=> tests(card-browser-view-model): sorting & suspend

AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorIntentTest.kt, AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportFileSelectionFragment.kt, AnkiDroid/src/main/java/com/ichi2/utils/AssetHelper.kt
Extracting 'text/plain' as constant and replacing it in the 
* Fixes #16508 
Tested locally and project build successfully
=> refactor: extract text/plain as constant

AnkiDroid/src/main/java/com/ichi2/anki/ViewerResourceHandler.kt
This appears to be due to us handling HTTP 206 incorrectly ('Partial Content')
`net::ERR_FAILED` was returned from subsequent calls - this appears to be because we were pre-truncating the stream to be the correct length
Although this worked in NanoHTTPD, returning the full file stream provided a correct `Content-Length` header implying that somewhere in the framework, truncation was occurring
* Fixes #16513
Approach
* provide the file stream rather than truncating it
* (non-fatal): fix 'Accept-Ranges' header
* remove: File.toInputStream
API 34 emulator and the audio provided in the issue
This is one of those issues that makes me lose confidence as a dev: nothing seemed to be working. No errors, and nothing  useful in the Chrome Dev Tools
=> fix: `<audio>` elements didn't play

AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt, AnkiDroid/src/main/java/com/ichi2/libanki/ChangeManager.kt, AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/browser/CardBrowserViewModelTest.kt, AnkiDroid/src/test/java/com/ichi2/testutils/JvmTest.kt, AnkiDroid/src/test/java/com/ichi2/testutils/TestChangeSubscriber.kt
* moved setup higher in setUp to capture more
* More diagnostics for https://github.com/ankidroid/Anki-Android/issues/16541
=> chore(card-browser): more logs

AnkiDroid/src/test/java/com/ichi2/testutils/TestChangeSubscriber.kt
This was caused because a WeakReference to the lambda was used, which went out of scope.
This meant `changes` was not incremented
Issues with `CardBrowserViewModel`:
* suspend - notes - some cards suspended
* suspend - notes - all suspended
* etc...
* Fixes #16541
Use a class instead of a lambda
https://github.com/david-allison/Anki-Android/actions/runs/9382123592
=> fix(tests): change subscription - flaky

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt, AnkiDroid/src/main/res/values/03-dialogs.xml, AnkiDroid/src/main/res/values/constants.xml
* Fixes #15855
* Fixes #15855
* Fixes #15876
Show a dialog with a link to the wiki if the webview version is < 77
In the emulator with API 25
=> Productionise webview ≥ 77 check

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
=> lint(collection): make non-open

AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt, AnkiDroid/src/main/res/values/04-network.xml
* Fixes #15933
* Fixes #15933
Add the new message
[Screen_recording_20240607_112939.webm](https://github.com/ankidroid/Anki-Android/assets/65715921/873cf4bd-dd54-4109-aa58-9fb8ed732b65)
[Screen_recording_20240607_113028.webm](https://github.com/ankidroid/Anki-Android/assets/65715921/f2c8259d-5208-491e-97bb-1872b1ac07ba)
=> improve media sync message

AnkiDroid/src/main/java/com/ichi2/libanki/BrowserConfig.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt, AnkiDroid/src/test/java/com/ichi2/libanki/CollectionTest.kt
https://github.com/ankitects/anki/blob/33a923797afc9655c3b4f79847e1705a1f998d03/pylib/anki/collection.py
https://github.com/ankitects/anki/blob/33a923797afc9655c3b4f79847e1705a1f998d03/pylib/anki/browser.py
* Prep for #11889
Unit tests & non-functional change
=> feat(col): expose browser table methods

AnkiDroid/build.gradle, api/build.gradle.kts, common/build.gradle.kts, gradle/libs.versions.toml, testlib/build.gradle.kts
extract magic numbers from gradle and share them between modules 
* Fixes #16517
=> extract magic numbers to version catalog #16517

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
After Custom Study the undo shows and after undo toast show for nothing to undo
- Fixes #16390
https://github.com/ankidroid/Anki-Android/assets/101629190/279b2268-d599-409d-b2c8-015ad0ae6cdd
=> Fixed Undo Options after Custom Study

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt, AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt, AnkiDroid/src/main/java/com/ichi2/anki/browser/BrowserColumnCollection.kt, AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt, common/src/main/java/com/ichi2/anki/common/utils/ext/Float.kt, common/src/main/java/com/ichi2/anki/utils/android/ColorUtils.kt, common/src/test/java/com/ichi2/anki/common/utils/ext/FloatTest.kt
* Implement various non-functional refactors and add new functionality to the `common` module
Unit tests
⚠️ Common unit tests do not run in CI - needs an issue
=> refactor: prep for using backend to render browser

AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerViewModel.kt, AnkiDroid/src/main/res/layout/reviewer2.xml
Add counts to the new reviewer
[Who's bad.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/c05ddd82-955f-45ff-a369-9f0eb275b8a7)
[Screen_recording_20240622_054009.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/5374849f-ee23-4b5d-8617-624b45cb77a6)
=> feat(new reviewer): counts

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
Removed in
301f0a152a3e17bc5664eaa08ea54ed9df26998a
But 'Builder' is ambiguous
=> improvement: re-add import qualifier

AnkiDroid/build.gradle, AnkiDroid/jacoco.gradle, AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorIntentTest.kt, AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt, AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/InstrumentedTest.kt, AnkiDroid/src/androidTest/java/com/ichi2/testutils/common/.gitignore, AnkiDroid/src/androidTest/java/com/ichi2/testutils/common/DO_NOT_EDIT_HERE.txt, AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/ReviewerNoParamTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/ExecutorTest.kt, testlib/src/main/java/com/ichi2/testutils/common/AnkiAssert.kt, testlib/src/main/java/com/ichi2/testutils/common/FailOnUnhandledExceptionRule.kt, testlib/src/main/java/com/ichi2/testutils/common/IgnoreFlakyTestsInCIRule.kt
Emulator tests currently run, but they generate zero coverage stats despite seemingly succeeding
Root cause is an incompatibility between android gradle plugin >= 8.3.0 *and* a common gradle lib that is used as a dependency in both testImplementation and androidTestImplementation
tracked upstream in https://issuetracker.google.com/issues/332746900
* Fixes #16640
- we don't want to back down android gradle plugin versions, so we need to work around this
- we don't want to actually duplicate common testlib code
- so...use a gradle copy task to copy in the common testlib code at build time (after de-conflicting path)
- ...now we have the common code in androidTest as well and can remove the androidTestImplementation dep
- ...then use a gradle finalization task that verifies coverage actually …
=> Fix android test coverage

.github/workflows/publish.yml
Changes from https://github.com/ankidroid/Anki-Android/pull/16637 broke the publish workflow. Should be alright now.
=> Fix publish workflow after recent changes

AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/AnswerButtonsNextTime.kt, AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerViewModel.kt, AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt
Emulator 34. Disabling the preference also works
[sequencia.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/b88dc432-e50a-4817-85b9-08e7508ba101)
=> feat(new reviewer): answer buttons next time display

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DiscardChangesDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt, AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt, AnkiDroid/src/main/java/com/ichi2/utils/ViewUtils.kt, AnkiDroid/src/main/res/layout/instant_editor_dialog.xml
On top of:
*  #16534
- Cloze number to increment only in Increment mode
- Show discard change dialog if there are any changes 
- Share latest text to the note editor 
Tested on Oneplus nord ce
=> [GSoC'24] Enhacement: Instant Editor UX improvements

.idea/dictionaries/usernames.xml
This way it won't be shown as typo by Intelli-J
=> NF: add Sargam to usernames

AnkiDroid/src/main/java/com/ichi2/anki/notetype/AddNewNotesType.kt, AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt, AnkiDroid/src/main/java/com/ichi2/anki/notetype/NotetypeAdapter.kt, AnkiDroid/src/main/java/com/ichi2/anki/notetype/NotetypeUiModel.kt
I found the code slightly unclear and tried to improve it.
* NotetypeBasicUiModel was not related to basic note types
* isStandard and useCount did not seem to me to have a clear meaning in anki lexicon, so must be document
* toUiModel can't be appled to a standard entry as far as I understand it, and is in any case never applied to a standard note type currently, so we can remove the argument.
=> Clarify note type ui model

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateNotetype.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Deck.kt, AnkiDroid/src/main/java/com/ichi2/libanki/NotetypeJson.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Notetypes.kt, AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
While investigating #16730 I found a few things to clean.
As I'm not certain you agree with all those commits, I preferred to separate this PR to the actual solution of the bug.
=> Cleaning note editor related code

AnkiDroid/src/main/java/com/ichi2/anki/pages/DeckOptions.kt
* Fixes #16715
Restrict the view to the manual
[deckoptions.webm](https://github.com/user-attachments/assets/3330b62b-4fb0-43f0-ad4f-ff5bdde9f99f)
=> restrict deck option links

AnkiDroid/src/main/java/com/ichi2/anki/preferences/ControlsSettingsFragment.kt, AnkiDroid/src/main/res/values/sentence-case.xml
=> Dynamicaly set in sentence case... Flag,Toggle Witeboard,Abort Learning

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
* Fixes #16691
What https://github.com/ankidroid/Anki-Android/issues/16691#issuecomment-2212336806 asked
Emulator with API 35
=> improve deleted deck message

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt, AnkiDroid/src/main/java/com/ichi2/anki/scheduling/SetDueDateDialog.kt, AnkiDroid/src/main/res/layout/card_template_editor_activity.xml, AnkiDroid/src/main/res/layout/dialog_set_due_date.xml
Renaming these two pager ids so that android-studio should know both are different pager
https://github.com/ankidroid/Anki-Android/pull/16529#discussion_r1690531761
=> [GSoC'24] rename pager

gradle/libs.versions.toml
Prompted by no changelog on: https://github.com/ankidroid/Anki-Android/pull/16852
* https://github.com/ankidroid/Anki-Android/pull/16852
=> docs: dependencies - changelogs (Apache Commons)

AnkiDroid/src/test/java/com/ichi2/utils/BundleUtilsTest.kt
Improve the test coverage of Ankidroid codebase.
Added test cases for the 'requireLong()' extension function.
Added test cases for the `requireLong()` extension function in the `BundleUtils.kt` file.
=> test: Added test case for requireLong() method at BundleUtils.kt

gradle/libs.versions.toml
Due to:
* https://github.com/ankidroid/Anki-Android/pull/16853
=> docs: dependencies - changelogs (AGP)

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt, AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt
Resolving a TODO: `  @NeedsTest("Ensure bottom sheet fragment is shown")`
Tested Locally 
=> [UnitTest]: Ensure MultimediaBottomSheet is shown

AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
This PR introduces improvements to the common compression process and adds a fail-fast check to handle cases where the number of files exceeds the allowed limit.
* Fixes #16856
=>  refactor: Commons Compress Improvements

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
Implement keyboard shortcuts to enhance the user experience by providing quick access to commonly used functionalities within the application. This will improve the overall usability, especially for power users who prefer using the keyboard over the mouse.
The shortcuts are implemented by adding event listeners for keypress events and mapping them to the respective functions. The approach ensures that the shortcuts are intuitive and do not conflict with existing shortcuts.
| Action | Shortcut in AnkiDroid | Shortcut in Anki |
|--------|--------|--------|
| Add Tags | Ctrl+Shift+A | Ctrl+Shift+A |
| Export selected cards | Ctrl+Shift+E | Ctrl+Shift+E |
| Reset card progress | Ctrl+Alt+N | Ctrl+Alt+N |
| Toggle cards/notes  | Ctrl+Alt+T | Ctrl+Alt+T | 
| Show filter by tags | T | **n/a**  | …
=> [GSoC'24] CardBrowser: Implementation of Keyboard Shortcuts

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt, AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.kt, AnkiDroid/src/main/java/com/ichi2/anki/reviewer/AutomaticAnswer.kt, AnkiDroid/src/main/res/values/10-preferences.xml, AnkiDroid/src/main/res/values/preferences.xml, AnkiDroid/src/main/res/xml/preferences_controls.xml, AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/ViewerCommandTest.kt
* Fixes #15545
* Fixes #15519
Add a toggle advance method
I assigned a gesture to it and tested it disabling auto advance and enabling it back
=> add toggle auto advance command

README.md
_Link was outdated and needed to change_
* Isuue found myself not raised yet#
_Went to README.md and updated the link from https://twitter.com/ankidroid to https://x.com/ankidroid_
- [ x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)
=> Twitter Link changed to X

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
Timer keeps running even the timebox was shown
* Fixes https://github.com/ankidroid/Anki-Android/issues/15500
https://github.com/user-attachments/assets/818e4391-4dbb-4d8f-847e-e95f3b99c62a
=> Fixed the timebox

AnkiDroid/src/main/java/com/ichi2/anki/web/HttpFetcher.kt
Remaining code used in `AddonData`
=> refactor: remove dead code

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
aabd99dc4ea1044ef77ff1f57fa79e59ad8b6881 broke the export menu item
* Fixes export menu item not working
add the removed code back
By exporting a deck
=> fix export menu item

.github/workflows/opencollective_notices.yml
people should re-read it, update comment to say same
https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process/_compare/89803528a2ea9c4db75ae2a2dd267931c97ffeed...08ec2a85d18304b7ef3599218327c1d1ace59c20
=> docs(opencollective): note that the payment process has been updated

.github/workflows/compare_apk_size.yml
I hope the output will be easier to read this way
=> Improve apk size comparison tool

AnkiDroid/src/main/res/values-cs/01-core.xml, AnkiDroid/src/main/res/values-cs/02-strings.xml, AnkiDroid/src/main/res/values-cs/03-dialogs.xml, AnkiDroid/src/main/res/values-cs/08-widget.xml, AnkiDroid/src/main/res/values-gu/01-core.xml, AnkiDroid/src/main/res/values-gu/02-strings.xml, AnkiDroid/src/main/res/values-gu/03-dialogs.xml, AnkiDroid/src/main/res/values-gu/06-statistics.xml, AnkiDroid/src/main/res/values-gu/07-cardbrowser.xml, AnkiDroid/src/main/res/values-gu/08-widget.xml, AnkiDroid/src/main/res/values-gu/09-backup.xml, AnkiDroid/src/main/res/values-gu/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-ml/03-dialogs.xml, AnkiDroid/src/main/res/values-ml/10-preferences.xml, AnkiDroid/src/main/res/values-ml/11-arrays.xml, AnkiDroid/src/main/res/values-ml/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-ml/17-model-manager.xml, AnkiDroid/src/main/res/values-ml/20-search-preference.xml, AnkiDroid/src/main/res/values-ta/05-feedback.xml, AnkiDroid/src/main/res/values-ta/06-statistics.xml, AnkiDroid/src/main/res/values-ta/07-cardbrowser.xml, AnkiDroid/src/main/res/values-ta/08-widget.xml, AnkiDroid/src/main/res/values-ta/10-preferences.xml, AnkiDroid/src/main/res/values-ta/17-model-manager.xml, AnkiDroid/src/main/res/values-ta/18-standard-models.xml, AnkiDroid/src/main/res/values-ta/20-search-preference.xml, AnkiDroid/src/main/res/values-zh-rCN/11-arrays.xml
=> Updated strings from Crowdin 2024/09/30 13:15

AnkiDroid/src/main/res/values-cs/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-eo/08-widget.xml, AnkiDroid/src/main/res/values-ru/01-core.xml, AnkiDroid/src/main/res/values-ru/02-strings.xml, AnkiDroid/src/main/res/values-zh-rCN/07-cardbrowser.xml, AnkiDroid/src/main/res/values-zh-rCN/08-widget.xml
=> Updated strings from Crowdin 2024/10/05 16:33

AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt
I tried to solve #15611 by doing [what David asked](https://github.com/ankidroid/Anki-Android/issues/15611#issuecomment-1985742924):
> This issue will be closed when the following method is updated to use the backend:
https://github.com/ankidroid/Anki-Android/blob/3775853baabe202f9d2c975a10754f229b89bf9c/AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt#L96-L114
I updated the methods to match Anki and use the backend, but I still see the `(end)` message. Despite of the fact that I didn't manage to completely fix the issue, I'm posting this PR because it updates libanki and can help someone else
* Fixes part of #15611
=> Help solving "All card options show (end)"

AnkiDroid/src/main/res/values-zh-rCN/02-strings.xml
=> Updated strings from Crowdin 2024/10/12 13:28

AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/TypeAnswer.kt, AnkiDroid/src/main/res/values/02-strings.xml
* Fixes #17132
Replace string with the backend version
=> replace string with backend version

AnkiDroid/src/main/java/com/ichi2/anki/SingleFragmentActivity.kt, AnkiDroid/src/main/java/com/ichi2/compat/CompatV24.kt
We potentially have an issue with `onCreate` & `onKeyUp`
It's hard to find a good point to add logs without spamming logcat.
These logs may elucidate the problem
Issue #17246
=> docs: SingleFragmentActivity & key events

AnkiDroid/src/main/res/values-kk/01-core.xml, AnkiDroid/src/main/res/values-ml/03-dialogs.xml, AnkiDroid/src/main/res/values-ml/04-network.xml, AnkiDroid/src/main/res/values-ml/06-statistics.xml, AnkiDroid/src/main/res/values-ml/07-cardbrowser.xml, AnkiDroid/src/main/res/values-ml/08-widget.xml, AnkiDroid/src/main/res/values-ml/09-backup.xml, AnkiDroid/src/main/res/values-ml/10-preferences.xml, AnkiDroid/src/main/res/values-ml/11-arrays.xml, AnkiDroid/src/main/res/values-sat/01-core.xml, AnkiDroid/src/main/res/values-sat/04-network.xml, AnkiDroid/src/main/res/values-ta/07-cardbrowser.xml, AnkiDroid/src/main/res/values-ta/10-preferences.xml, AnkiDroid/src/main/res/values-ta/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-ta/17-model-manager.xml, AnkiDroid/src/main/res/values-ta/18-standard-models.xml, AnkiDroid/src/main/res/values-uk/01-core.xml, AnkiDroid/src/main/res/values-uk/02-strings.xml, AnkiDroid/src/main/res/values-uk/03-dialogs.xml, AnkiDroid/src/main/res/values-uk/07-cardbrowser.xml, AnkiDroid/src/main/res/values-uk/08-widget.xml, AnkiDroid/src/main/res/values-uk/10-preferences.xml, AnkiDroid/src/main/res/values-uk/11-arrays.xml, AnkiDroid/src/main/res/values-uk/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-vi/01-core.xml
=> Updated strings from Crowdin 2024/10/15 04:25

AnkiDroid/src/main/java/com/ichi2/anki/preferences/ReviewingSettingsFragment.kt
Bug reproduction:
- have the _learn ahead limit_ set to a value that is below the good step value(below 10 min default)
- create a deck with one card to see the behavior more clearly
- review the card -> press good -> deck has 0 counts  and a toast that you can learn again in  x amount is displayed
- change the _learn ahead limit_ to a value that is above the good step, ex 15 minutes
- try to review -> app attempts to go to reviewer but goes back to DeckPicker immediately with a toast being displayed that you need to wait a minute
Changing the setting works ok and the changed value is seen. The issue is that the scheduler is partially updated with the new limit. For example, the deckDueTree() is updated(in DeckPicker the counts are changed based on the updated learn ahead limit) but the …
=> Fix learn ahead limit not working after updating setting

AnkiDroid/src/main/res/values-fa/02-strings.xml, AnkiDroid/src/main/res/values-sc/02-strings.xml, AnkiDroid/src/main/res/values-sc/03-dialogs.xml, AnkiDroid/src/main/res/values-sc/07-cardbrowser.xml, AnkiDroid/src/main/res/values-sc/08-widget.xml, AnkiDroid/src/main/res/values-sc/09-backup.xml, AnkiDroid/src/main/res/values-sc/10-preferences.xml, AnkiDroid/src/main/res/values-sc/11-arrays.xml, AnkiDroid/src/main/res/values-sc/16-multimedia-editor.xml
=> Updated strings from Crowdin 2024/10/20 18:00

README.md
Add the app certificate fingerprint to the README file, enabling apps and users to check the integrity of apk installed from github.
The main purpose is to enable subsequent verification of the app through [AppVerifier](https://github.com/soupslurpr/AppVerifier), including adding the fingerprint to its internal database.
Not modified application code: only modifies the README file.
=> Added SHA256 & SHA1 application certificate fingerprints to README

AnkiDroid/src/main/assets/flashcard.css, AnkiDroid/src/main/assets/scripts/card.js
This reverts commit 4a90cd6b939de5da3d49137d9c4ba2bcdde8c330.
Apparently this was doing more than making sure images were zoomable etc and needs further thought
See:
- #17318
=> Revert "fix: remove ancient image fill-while-zoomable hack"

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt, AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserColumn.kt, AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/TypeAnswer.kt, AnkiDroid/src/main/java/com/ichi2/anki/pages/DeckOptions.kt, AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt, AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt, AnkiDroid/src/test/java/com/ichi2/anki/browser/CardBrowserColumnTest.kt, gradle/libs.versions.toml
See title.
Related PRs:
* https://github.com/ankidroid/Anki-Android/pull/17170
For anyone who wants to test the build: https://github.com/voczi/Anki-Android/releases/tag/2.19rc1
=> Anki 24.10rc2 support

AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt
methods were no longer called
* https://github.com/ankidroid/Anki-Android/pull/17371
=> fix: PostRequestHandler

.github/ISSUE_TEMPLATE/config.yml
We occasionally get reports for bad translations
Provide information to allow users to resolve their own issues
https://github.com/ankidroid/Anki-Android/wiki/Reporting-Translation-Issues
* Prompted by https://github.com/ankidroid/Anki-Android/issues/17438
=> improvement: self-service - fix translation issues

AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
Attempting to test:
- #17035
Reproduced and fixed: 
- #17378
Noticed that the number format on the "image too large, want to crop?" dialog was mathematically incorrect and formatted wrong.
Also noticed that if the image was too large you really just couldn't save it at all even if you were a grown adult and you knew what you were doing
Finally noticed that if you have an image file that is finally large enough (I needed a really really big image) then you'll crash both when adding via shortcut and from image picker. Same line of code though, so I handled that and it should work now.
Fixes:
- #17378
Carefully catch the exception thrown, but also clear out the dirty intermediate state in the image widget so we recover
I manually verified that when I add a really large image it has the size …
=> Fix huge image crashes, allow adding large images, fixup large image size formatting

AnkiDroid/src/main/java/com/ichi2/anki/preferences/AppearanceSettingsFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/ReviewingSettingsFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerViewModel.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt, AnkiDroid/src/test/java/com/ichi2/anki/preferences/PreferencesTest.kt
I tried doing something similar to #17277 to other preferences so they can get undoable like the desktop version
Tested if all the changed preferences work the same way
=> Use backend for preferences

AnkiDroid/src/main/res/values-es-rAR/01-core.xml, AnkiDroid/src/main/res/values-es-rAR/02-strings.xml, AnkiDroid/src/main/res/values-es-rAR/03-dialogs.xml, AnkiDroid/src/main/res/values-es-rAR/04-network.xml, AnkiDroid/src/main/res/values-es-rAR/06-statistics.xml, AnkiDroid/src/main/res/values-es-rAR/07-cardbrowser.xml, AnkiDroid/src/main/res/values-es-rAR/08-widget.xml, AnkiDroid/src/main/res/values-es-rAR/10-preferences.xml, AnkiDroid/src/main/res/values-es-rAR/11-arrays.xml, AnkiDroid/src/main/res/values-es-rAR/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-es-rES/01-core.xml, AnkiDroid/src/main/res/values-es-rES/02-strings.xml, AnkiDroid/src/main/res/values-es-rES/03-dialogs.xml, AnkiDroid/src/main/res/values-es-rES/04-network.xml, AnkiDroid/src/main/res/values-es-rES/06-statistics.xml, AnkiDroid/src/main/res/values-es-rES/07-cardbrowser.xml, AnkiDroid/src/main/res/values-es-rES/08-widget.xml, AnkiDroid/src/main/res/values-es-rES/10-preferences.xml, AnkiDroid/src/main/res/values-es-rES/11-arrays.xml, AnkiDroid/src/main/res/values-es-rES/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-hy/07-cardbrowser.xml
=> Updated strings from Crowdin 2024/11/22 16:30

AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.kt
Avoid a crash seen in ACRA by the evil use of `lateinit` which is just the sleeper NullPointerException of modern Kotlin times
https://ankidroid.org/acra/app/1/bug/260934/report/c4097fac-9c67-460b-986c-017cc1a98313
```
com.ichi2.anki.exception.UserSubmittedException: lateinit property dropDownDecks has not been initialized
at com.ichi2.anki.DeckSpinnerSelection.selectDeck(DeckSpinnerSelection.kt:201)
at com.ichi2.anki.DeckSpinnerSelection.selectDeckById(DeckSpinnerSelection.kt:190)
at com.ichi2.anki.CardBrowser.setupFlows$onDeckIdChanged(CardBrowser.kt:465)
at com.ichi2.anki.CardBrowser.access$setupFlows$onDeckIdChanged(CardBrowser.kt:155)
at com.ichi2.anki.CardBrowser$setupFlows$7.invoke(CardBrowser.kt:570)
at com.ichi2.anki.CardBrowser$setupFlows$7.invoke(CardBrowser.kt:570)
at …
```
=> fix: avoid crash by converting lateinit to nullable

AnkiDroid/src/main/res/values-de/02-strings.xml, AnkiDroid/src/main/res/values-ml/08-widget.xml, AnkiDroid/src/main/res/values-tr/11-arrays.xml
=> Updated strings from Crowdin 2024/11/26 15:27

gradle/libs.versions.toml
Does exactly what the title says (anki24.11rc1 --> anki24.11rc2)
=> build(deps): adopt anki24.11rc2

AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt, AnkiDroid/src/main/java/com/ichi2/anki/scheduling/ForgetCardsDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/scheduling/SetDueDateDialog.kt
* Addresses comment: https://github.com/ankidroid/Anki-Android/pull/17510#discussion_r1861086167
The comment listed methods which were not actually affected by the PR, but it called out the fact that I was bundling in a separately scoped refactor into a PR
⚠️ CI only
=> refactor: add/use default params for `withProgress`

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
These helped when diagnosing test issues
=> logs: CustomStudyDialog

AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.kt
=> Reenable DeckPickerTest

AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt, AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt, AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncMediaWorker.kt
I wrote these while looking into 
* #17551
=> logs: syncing

AnkiDroid/src/main/java/com/ichi2/anki/SingleFragmentActivity.kt
this is handled in the base class
=> fix: startActivity

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/IntegerDialog.kt
we use
> requireArguments().getString("title")!!
=> refactor(integer-dialog): make title non-null

AnkiDroid/src/main/res/values-de/07-cardbrowser.xml, AnkiDroid/src/main/res/values-de/10-preferences.xml, AnkiDroid/src/main/res/values-de/11-arrays.xml, AnkiDroid/src/main/res/values-es-rAR/01-core.xml, AnkiDroid/src/main/res/values-es-rAR/02-strings.xml, AnkiDroid/src/main/res/values-fr/08-widget.xml, AnkiDroid/src/main/res/values-ko/02-strings.xml, AnkiDroid/src/main/res/values-nn/01-core.xml, AnkiDroid/src/main/res/values-no/01-core.xml, AnkiDroid/src/main/res/values-uk/02-strings.xml, AnkiDroid/src/main/res/values-ur/03-dialogs.xml
=> Updated strings from Crowdin 2024/12/05 23:05

.github/workflows/sync_translations.yml
`[Re-sync translations](https://github.com/ankidroid/Anki-Android/actions/workflows/sync_translations.yml)` => [Re-sync translations](https://github.com/ankidroid/Anki-Android/actions/workflows/sync_translations.yml)
Should save a few clicks
⚠️ Untested
=> improvement(i18n): link 'Re-sync translations'

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.kt, AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/CardSoundConfigTest.kt
#17399 is almost a thousand lines long and get regular conflict.
I offer those small commits first, which hopefully should be non controversial, easy to review, and could be merged fast, ultimately reducing the work that is still required for the review of the feature change
Those commit introduce function and constant. The functions not only reduce code dupliaction, but, more importantly, will reduce the quantity of code changes in the feature implementation, as we'll only have to change the function implementation.
=> Cleanup in preparation for adding sync in reviewers

AnkiDroid/src/main/res/values-de/11-arrays.xml, AnkiDroid/src/main/res/values-heb/02-strings.xml, AnkiDroid/src/main/res/values-heb/03-dialogs.xml, AnkiDroid/src/main/res/values-iw/02-strings.xml, AnkiDroid/src/main/res/values-iw/03-dialogs.xml, AnkiDroid/src/main/res/values-ja/02-strings.xml, AnkiDroid/src/main/res/values-ko/02-strings.xml, AnkiDroid/src/main/res/values-ko/03-dialogs.xml
=> Updated strings from Crowdin 2024/12/17 18:10

AnkiDroid/src/main/res/values-de/06-statistics.xml, AnkiDroid/src/main/res/values-es-rAR/03-dialogs.xml, AnkiDroid/src/main/res/values-es-rAR/11-arrays.xml, AnkiDroid/src/main/res/values-es-rES/03-dialogs.xml, AnkiDroid/src/main/res/values-es-rES/11-arrays.xml, AnkiDroid/src/main/res/values-uk/02-strings.xml, AnkiDroid/src/main/res/values-uk/03-dialogs.xml, AnkiDroid/src/main/res/values-uk/10-preferences.xml, AnkiDroid/src/main/res/values-uk/11-arrays.xml
=> Updated strings from Crowdin 2024/12/20 18:28

tools/release-description.md
Removed extra horizontal rules on the description which were not needed.
Extra horizontal rules
Checked preview on markdown previewer
=> Minor fixup for release-description.md

AnkiDroid/src/main/java/com/ichi2/anki/reviewer/MappableBinding.kt
unused. And until there is a second version, it has no utility
=> refactor: remove MappableBinding.Version

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
I need to admit that @vvs Aditya13s in https://github.com/ankidroid/Anki-Android/issues/17665#issuecomment-2563862406 has a point. The implementation of the inner functions such as `customStudy` is slightly hard to understand.
The goal of the block, taking a custom study request's dsl and returning nothing is not immediately clear, until you read the implementation of the blocks that are sent to it and realize that this is just supposed to create the request, except for the DID part.
It's not even clear when looking at the block why they are ignoring the did.
Given that the only difference between the customStudy and the limit extension different is only the listener's call, this can clearly be simplified.
Also, I think it's nice to explain at the end why there is no reason to save …
=> Simplify CustomStudyDialog

.github/workflows/opencollective_notices.yml
syntax error in 4681294ec9cfe71fc95010cfd7e170066fe3bd9b and a few typos
```
SyntaxError: Unexpected token '{'
at new AsyncFunction (<anonymous>)
at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v7/dist/index.js:35424:16)
at main (/home/runner/work/_actions/actions/github-script/v7/dist/index.js:35522:26)
at /home/runner/work/_actions/actions/github-script/v7/dist/index.js:35497:1
at /home/runner/work/_actions/actions/github-script/v7/dist/index.js:35553:3
at Object.<anonymous> (/home/runner/work/_actions/actions/github-script/v7/dist/index.js:35556:12)
at Module._compile (node:internal/modules/cjs/loader:1469:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
at Module.load (node:internal/modules/cjs/loader:1288:32)
at Module._load …
```
=> fix: open collective notices

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Notetypes.kt, AnkiDroid/src/test/java/com/ichi2/libanki/CardTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/CollectionTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/SchedulerTest.kt, AnkiDroid/src/test/java/com/ichi2/utils/NoteTypeTest.kt
And `mm` to noteTypes.
As first part of #17598 as David requested the PR to be split.
=> Rename `m` to noteType

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt, AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/DeckUtils.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/NoteEditorLauncher.kt, AnkiDroid/src/main/java/com/ichi2/anki/notetype/NotetypeUiModel.kt, AnkiDroid/src/main/java/com/ichi2/anki/pages/DeckOptions.kt, AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerViewModel.kt, AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt, AnkiDroid/src/main/java/com/ichi2/anki/services/ReminderService.kt, AnkiDroid/src/main/java/com/ichi2/anki/utils/CardTemplateJson.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Note.kt, AnkiDroid/src/main/java/com/ichi2/libanki/NotetypeJson.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Notetypes.kt, AnkiDroid/src/main/java/com/ichi2/widget/WidgetConfigScreenAdapter.kt, AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.kt, AnkiDroid/src/test/java/com/ichi2/testutils/libanki/CollectionAssert.kt
A recent review made me realize plenty of `id: Long` should be more specific.
Exceptions are in the AddContentApi as it can't depends on the type definition of the code.
=> NF: Use type Id

AnkiDroid/src/main/res/values-sv/02-strings.xml, AnkiDroid/src/main/res/values-sv/17-model-manager.xml
=> Updated strings from Crowdin 2025/01/04 16:41

AnkiDroid/src/main/res/values-ko/10-preferences.xml, AnkiDroid/src/main/res/values-ko/11-arrays.xml, AnkiDroid/src/main/res/values-ko/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-ko/17-model-manager.xml, AnkiDroid/src/main/res/values-ko/20-search-preference.xml, AnkiDroid/src/main/res/values-tr/05-feedback.xml
=> Updated strings from Crowdin 2025/01/05 19:57

AnkiDroid/src/main/res/values-ko/01-core.xml, AnkiDroid/src/main/res/values-ko/10-preferences.xml
=> Updated strings from Crowdin 2025/01/07 09:25

.github/FUNDING.yml
https://github.com/sponsors/ankidroid/
* Fixes #17197
=> funding: add GitHub Sponsors

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/AudioRecordingField.kt, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/MediaClipField.kt
I consider this code to be trivial
Given the codebase is GPL, additional contributions should also be GPL unless explicitly stated otherwise
* Issue #8659
=> lint: add copyright (John Dematis)

AnkiDroid/src/main/res/values-af/02-strings.xml, AnkiDroid/src/main/res/values-cs/01-core.xml, AnkiDroid/src/main/res/values-fa/01-core.xml, AnkiDroid/src/main/res/values-fa/02-strings.xml, AnkiDroid/src/main/res/values-fa/10-preferences.xml, AnkiDroid/src/main/res/values-ja/01-core.xml, AnkiDroid/src/main/res/values-ja/02-strings.xml, AnkiDroid/src/main/res/values-ja/10-preferences.xml, AnkiDroid/src/main/res/values-zh-rCN/01-core.xml, AnkiDroid/src/main/res/values-zh-rCN/02-strings.xml
=> Updated strings from Crowdin 2025/01/11 14:53

AnkiDroid/src/main/res/values-fr/02-strings.xml, AnkiDroid/src/main/res/values-fr/08-widget.xml, AnkiDroid/src/main/res/values-fr/10-preferences.xml, AnkiDroid/src/main/res/values-fr/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-ug/01-core.xml, AnkiDroid/src/main/res/values-ug/02-strings.xml, AnkiDroid/src/main/res/values-ug/10-preferences.xml
=> Updated strings from Crowdin 2025/01/14 11:01

AnkiDroid/src/main/java/com/ichi2/anki/utils/CardTemplateJson.kt
Thanks to Ashish who already did the big part of the work!
=> NF: transform CardTemplateJson into a value class

AnkiDroid/src/main/java/com/ichi2/libanki/Note.kt
I was fixing up #17771 and this felt useful, but out of scope for the PR
* Add LibAnkiAlias annotations
* Reorder methods
* Remove deleted methods upstream
Untested, other than CI
=> improvement(note): libAnki compat

AnkiDroid/src/main/res/values-pt-rPT/01-core.xml, AnkiDroid/src/main/res/values-pt-rPT/02-strings.xml, AnkiDroid/src/main/res/values-pt-rPT/10-preferences.xml, AnkiDroid/src/main/res/values-sv/01-core.xml, AnkiDroid/src/main/res/values-sv/02-strings.xml, AnkiDroid/src/main/res/values-sv/03-dialogs.xml, AnkiDroid/src/main/res/values-sv/06-statistics.xml, AnkiDroid/src/main/res/values-sv/07-cardbrowser.xml, AnkiDroid/src/main/res/values-sv/08-widget.xml, AnkiDroid/src/main/res/values-sv/10-preferences.xml, AnkiDroid/src/main/res/values-sv/11-arrays.xml, AnkiDroid/src/main/res/values-sv/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-ug/02-strings.xml
=> Updated strings from Crowdin 2025/01/21 06:22

AnkiDroid/src/main/res/values-hu/01-core.xml, AnkiDroid/src/main/res/values-hu/02-strings.xml, AnkiDroid/src/main/res/values-hu/06-statistics.xml, AnkiDroid/src/main/res/values-hu/07-cardbrowser.xml, AnkiDroid/src/main/res/values-hu/10-preferences.xml, AnkiDroid/src/main/res/values-hu/11-arrays.xml, AnkiDroid/src/main/res/values-pt-rPT/07-cardbrowser.xml, AnkiDroid/src/main/res/values-tr/01-core.xml, AnkiDroid/src/main/res/values-tr/02-strings.xml, AnkiDroid/src/main/res/values-tr/07-cardbrowser.xml, AnkiDroid/src/main/res/values-tr/10-preferences.xml, AnkiDroid/src/main/res/values-zh-rCN/07-cardbrowser.xml, docs/marketing/localized_description/marketdescription-tr.txt
=> Updated strings from Crowdin 2025/01/26 14:22

README.md
Quoting Obtainium's description:
> Obtainium allows you to install and update apps directly from their releases pages, and receive notifications when new releases are made available.
It is a relatively popular app and allows people to update their AnkiDroid APK from Github in an easier way
The result is visible on my [branch](https://github.com/BrayanDSO/Anki-Android/tree/obtain?tab=readme-ov-file#install).
I clicked the link with an Android device with obtainium installed and it works.
=> docs: add `Get it on Obtainium` to README

AnkiDroid/src/main/res/values-eo/01-core.xml, AnkiDroid/src/main/res/values-eo/02-strings.xml, AnkiDroid/src/main/res/values-eo/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-fil/01-core.xml, AnkiDroid/src/main/res/values-fil/02-strings.xml
=> Updated strings from Crowdin 2025/02/07 09:16

AnkiDroid/src/main/res/values-eo/01-core.xml, AnkiDroid/src/main/res/values-eo/02-strings.xml
=> Updated strings from Crowdin 2025/02/08 09:07

AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncMediaWorker.kt, AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncWorker.kt
cancel it after the work is done in case it wasn't dismissed
* Fixes #17639
* Fixes #17719
Emulator 35: Same steps of the original issue
=> fix(sync): notification getting stuck

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt, AnkiDroid/src/main/java/com/ichi2/anki/SingleFragmentActivity.kt, AnkiDroid/src/main/java/com/ichi2/anki/pages/CsvImporter.kt, AnkiDroid/src/main/java/com/ichi2/anki/pages/ImageOcclusion.kt, AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
Also make transparent the default color for the status bar in SingleFragmentActivity
* Fixes #17931
Checked if the status bar follows the toolbar color in the settings screen
=> fix(preferences): status bar color

AnkiDroid/src/main/res/values-ar/01-core.xml, AnkiDroid/src/main/res/values-ar/02-strings.xml, AnkiDroid/src/main/res/values-ar/06-statistics.xml, AnkiDroid/src/main/res/values-ar/07-cardbrowser.xml, AnkiDroid/src/main/res/values-ar/16-multimedia-editor.xml
=> Updated strings from Crowdin 2025/02/09 13:24

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Media.kt, AnkiDroid/src/main/res/layout/media_check_dialog_body.xml, AnkiDroid/src/main/res/values/03-dialogs.xml, AnkiDroid/src/main/res/values/sentence-case.xml
Make the media check dialog consistent with Anki, and allow tagging missing media file notes
* Fixes #17822
More about the Anki codebase 
=> feat: Improve Check Media dialog

AnkiDroid/src/main/res/values-es-rAR/01-core.xml, AnkiDroid/src/main/res/values-es-rAR/02-strings.xml, AnkiDroid/src/main/res/values-es-rAR/10-preferences.xml, AnkiDroid/src/main/res/values-es-rES/01-core.xml, AnkiDroid/src/main/res/values-es-rES/02-strings.xml, AnkiDroid/src/main/res/values-es-rES/07-cardbrowser.xml, AnkiDroid/src/main/res/values-es-rES/10-preferences.xml, AnkiDroid/src/main/res/values-ja/02-strings.xml, AnkiDroid/src/main/res/values-ja/10-preferences.xml, AnkiDroid/src/main/res/values-pt-rBR/01-core.xml, AnkiDroid/src/main/res/values-pt-rBR/02-strings.xml, AnkiDroid/src/main/res/values-pt-rBR/03-dialogs.xml, AnkiDroid/src/main/res/values-pt-rPT/10-preferences.xml
=> Updated strings from Crowdin 2025/02/13 22:55

gradle/libs.versions.toml
=> build(deps): anki25.02

AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/GestureProcessor.kt, AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.kt, AnkiDroid/src/main/java/com/ichi2/anki/reviewer/MappableBinding.kt, AnkiDroid/src/main/java/com/ichi2/anki/reviewer/MotionEventHandler.kt, AnkiDroid/src/main/java/com/ichi2/anki/reviewer/PeripheralKeymap.kt, AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ReviewerBinding.kt, AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt, AnkiDroid/src/main/java/com/ichi2/preferences/ReviewerControlPreference.kt, AnkiDroid/src/test/java/com/ichi2/anki/ReviewerKeyboardInputTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/ReviewerNoParamTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/servicemodel/UpgradeGesturesToControlsTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/utils/ext/ViewerCommand.kt, AnkiDroid/src/test/java/com/ichi2/ui/BindingPreferenceTest.kt
Preparation for adding keybinds to the new reviewer and the reviewer
In the commits
Emulator 35: go to the reviewer and press some default keyboard shortcut like `Space` to see if it still works
=> refactor: clean Binding classes

gradle/libs.versions.toml
Get current batch of dependency updates in, also ideal before we start a beta cycle
=> Dependency updates 20250216

AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/PermissionsFragment.kt
Documentation only
Link for the lazy: https://issuetracker.google.com/issues/299174252
=> docs: showManageAllFilesScreen error case

AnkiDroid/src/main/res/values-de/11-arrays.xml, AnkiDroid/src/main/res/values-fr/01-core.xml, AnkiDroid/src/main/res/values-fr/02-strings.xml, AnkiDroid/src/main/res/values-fr/07-cardbrowser.xml, AnkiDroid/src/main/res/values-fr/11-arrays.xml, AnkiDroid/src/main/res/values-km/01-core.xml, AnkiDroid/src/main/res/values-km/02-strings.xml, AnkiDroid/src/main/res/values-km/03-dialogs.xml, AnkiDroid/src/main/res/values-km/04-network.xml, AnkiDroid/src/main/res/values-km/05-feedback.xml, AnkiDroid/src/main/res/values-km/07-cardbrowser.xml, AnkiDroid/src/main/res/values-km/08-widget.xml, AnkiDroid/src/main/res/values-km/09-backup.xml, AnkiDroid/src/main/res/values-km/10-preferences.xml, AnkiDroid/src/main/res/values-km/11-arrays.xml, AnkiDroid/src/main/res/values-pt-rBR/02-strings.xml, AnkiDroid/src/main/res/values-pt-rBR/07-cardbrowser.xml, AnkiDroid/src/main/res/values-pt-rBR/10-preferences.xml, AnkiDroid/src/main/res/values-ug/10-preferences.xml, AnkiDroid/src/main/res/values-uk/10-preferences.xml
=> Updated strings from Crowdin 2025/02/25 14:13

AnkiDroid/src/main/res/values-ar/08-widget.xml, AnkiDroid/src/main/res/values-fr/10-preferences.xml, AnkiDroid/src/main/res/values-ka/01-core.xml, AnkiDroid/src/main/res/values-ka/02-strings.xml, AnkiDroid/src/main/res/values-ka/03-dialogs.xml, AnkiDroid/src/main/res/values-ka/04-network.xml, AnkiDroid/src/main/res/values-ka/07-cardbrowser.xml, AnkiDroid/src/main/res/values-ka/08-widget.xml, AnkiDroid/src/main/res/values-ka/09-backup.xml, AnkiDroid/src/main/res/values-ka/10-preferences.xml, AnkiDroid/src/main/res/values-ka/11-arrays.xml, AnkiDroid/src/main/res/values-ka/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-ka/17-model-manager.xml, AnkiDroid/src/main/res/values-ko/01-core.xml, AnkiDroid/src/main/res/values-ko/02-strings.xml, AnkiDroid/src/main/res/values-ko/03-dialogs.xml, AnkiDroid/src/main/res/values-ko/04-network.xml, AnkiDroid/src/main/res/values-ko/05-feedback.xml, AnkiDroid/src/main/res/values-ko/07-cardbrowser.xml, AnkiDroid/src/main/res/values-ko/08-widget.xml, AnkiDroid/src/main/res/values-ko/09-backup.xml, AnkiDroid/src/main/res/values-ko/10-preferences.xml, AnkiDroid/src/main/res/values-ko/11-arrays.xml, AnkiDroid/src/main/res/values-ko/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-ko/17-model-manager.xml, AnkiDroid/src/main/res/values-ko/18-standard-models.xml, AnkiDroid/src/main/res/values-ko/20-search-preference.xml, AnkiDroid/src/main/res/values-uk/10-preferences.xml
=> Updated strings from Crowdin 2025/03/02 08:32

AnkiDroid/src/main/java/com/ichi2/utils/VersionUtils.kt, AnkiDroid/src/test/java/com/ichi2/libanki/FieldTest.kt
This PR addresses the issue where local variables declared with var were not being modified, suggesting a change to val for immutability. This improves code quality and prevents unintended side effects.
* Fixes part of #13282 
The changes involve updating local variable declarations from var to val in the affected files. This ensures the variables are immutable and helps prevent unintended side effects.
=> fix: change local variables from var to val

AnkiDroid/src/main/res/values-de/01-core.xml, AnkiDroid/src/main/res/values-de/02-strings.xml, AnkiDroid/src/main/res/values-de/07-cardbrowser.xml, AnkiDroid/src/main/res/values-de/10-preferences.xml, AnkiDroid/src/main/res/values-es-rES/01-core.xml, AnkiDroid/src/main/res/values-or/07-cardbrowser.xml, AnkiDroid/src/main/res/values-or/08-widget.xml, AnkiDroid/src/main/res/values-or/10-preferences.xml
=> Updated strings from Crowdin 2025/03/07 17:47

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
This PR addresses a TODO by replacing the usage of getColUnsafe with withCol in the deleteCardTemplate function. Migrating to withCol ensures safer access to the Collection
Replaces getColUnsafe with withCol as suggested in the TODO comment in CardTempleteEditor
The change modifies the deleteCardTemplate function to utilize withCol for structured and safe access to the Collection. This approach helps prevent unsafe collection handling and improves code safety and readability
Tested by running JUnit tests
=> Replace getColUnsafe with withCol 

AnkiDroid/src/main/res/values-cs/02-strings.xml, AnkiDroid/src/main/res/values-cs/03-dialogs.xml, AnkiDroid/src/main/res/values-pt-rPT/02-strings.xml, AnkiDroid/src/main/res/values-pt-rPT/07-cardbrowser.xml, AnkiDroid/src/main/res/values-zh-rCN/02-strings.xml
=> Updated strings from Crowdin 2025/03/12 23:38

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt, AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt, AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt, AnkiDroid/src/test/java/com/ichi2/testutils/ActivityList.kt
As this key is used inside the app and not to save any data, it's safe to change it
Some more part of https://github.com/ankidroid/Anki-Android/pull/17598
=> NF: rename `modelId` key to `noteTypeId`

AnkiDroid/src/main/res/values/12-dont-translate.xml
This will allow to check whether it appears as modified in crowdin
=> NF: testing changing the string

AnkiDroid/src/main/res/values/12-dont-translate.xml
This is a test to ensure that it does not require a new translation!
=> NF: changing order of strings

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt, AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateNotetype.kt, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/impl/MultimediaEditableNote.kt, AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Notetypes.kt, api/src/main/java/com/ichi2/anki/api/AddContentApi.kt
It's done everywhere except in the key of intents
Some more part of https://github.com/ankidroid/Anki-Android/pull/17598
=> NF: rename `modelId` to `noteTypeId`

AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.kt, AnkiDroid/src/androidTest/java/com/ichi2/anki/PagesTest.kt, AnkiDroid/src/androidTest/java/com/ichi2/anki/ReviewerFragmentTest.kt, AnkiDroid/src/androidTest/java/com/ichi2/anki/ReviewerTest.kt, AnkiDroid/src/androidTest/java/com/ichi2/anki/dialogs/NoteTypeEditorContextMenuTest.kt, AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt, AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/InstrumentedTest.kt, AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/NotetypeTest.kt, AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/NoteTypeEditorContextMenu.kt
=> NF: Rename model to note type in android tests

AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
To move the file deletion operation to  background thread
Fixes the issue where file deletion was not happening on  background thread
Moved the file deletion operation to a background thread using coroutines
Tested by JUnit tests.
=> Move file deletion on background thread

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/MediaTest.kt, AnkiDroid/src/test/java/com/ichi2/utils/UniqueArrayListTest.kt
Fixed small problems in android studio
* Fixes #13282
Changed toSet as recommended by android studio due to performance reasons
Ran the code
=> Fixed android studio warning, converting toSet for performance

AnkiDroid/src/main/res/values-de/02-strings.xml, AnkiDroid/src/main/res/values-de/03-dialogs.xml, AnkiDroid/src/main/res/values-heb/02-strings.xml, AnkiDroid/src/main/res/values-heb/03-dialogs.xml, AnkiDroid/src/main/res/values-heb/07-cardbrowser.xml, AnkiDroid/src/main/res/values-heb/10-preferences.xml, AnkiDroid/src/main/res/values-heb/17-model-manager.xml, AnkiDroid/src/main/res/values-iw/02-strings.xml, AnkiDroid/src/main/res/values-iw/03-dialogs.xml, AnkiDroid/src/main/res/values-iw/07-cardbrowser.xml, AnkiDroid/src/main/res/values-iw/10-preferences.xml, AnkiDroid/src/main/res/values-iw/17-model-manager.xml, AnkiDroid/src/main/res/values-ja/02-strings.xml, AnkiDroid/src/main/res/values-ja/03-dialogs.xml, AnkiDroid/src/main/res/values-ko/02-strings.xml, AnkiDroid/src/main/res/values-ko/07-cardbrowser.xml, AnkiDroid/src/main/res/values-ko/10-preferences.xml, AnkiDroid/src/main/res/values-pt-rPT/02-strings.xml, AnkiDroid/src/main/res/values-tr/02-strings.xml, AnkiDroid/src/main/res/values-tr/03-dialogs.xml, AnkiDroid/src/main/res/values-tr/07-cardbrowser.xml, AnkiDroid/src/main/res/values-tr/10-preferences.xml, AnkiDroid/src/main/res/values-tr/17-model-manager.xml
=> Updated strings from Crowdin 2025/03/23 17:42

AnkiDroid/src/main/res/values-pl/01-core.xml, AnkiDroid/src/main/res/values-pl/02-strings.xml, AnkiDroid/src/main/res/values-pl/03-dialogs.xml, AnkiDroid/src/main/res/values-pl/08-widget.xml
=> Updated strings from Crowdin 2025/03/24 17:54

AnkiDroid/src/main/res/layout/reviewer2.xml
I added while testing some stuff, but the line wasn't necessary (sw-600dp/reviewer2.xml doesn't have it and still works perfectly)
Forgot to remove it before pushing
I am straight merging this one, because I don't think that it's worth a review
=> fix: remove unused line in reviewer2.xml

AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportFileSelectionFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/utils/MimeTypeUtils.kt
Refactored .csv/.tsv values both in IntentHandler and in ImportFileSelectionFragment.
- Fixes #17875
Refactored the code to remove duplication by centralizing the .csv and .tsv MIME type definitions into a shared utility class (MimeTypeUtils).
=> Refactored de-duplicate .csv/.tsv values both in IntentHandler and in ImportFileSelectionFragment.

AnkiDroid/src/main/res/values-cs/01-core.xml, AnkiDroid/src/main/res/values-eo/02-strings.xml, AnkiDroid/src/main/res/values-eo/03-dialogs.xml, AnkiDroid/src/main/res/values-eo/07-cardbrowser.xml, AnkiDroid/src/main/res/values-eo/10-preferences.xml, AnkiDroid/src/main/res/values-eo/17-model-manager.xml, AnkiDroid/src/main/res/values-gu/01-core.xml, AnkiDroid/src/main/res/values-gu/02-strings.xml, AnkiDroid/src/main/res/values-gu/06-statistics.xml, AnkiDroid/src/main/res/values-ja/10-preferences.xml, AnkiDroid/src/main/res/values-pl/01-core.xml, AnkiDroid/src/main/res/values-pl/02-strings.xml, AnkiDroid/src/main/res/values-pl/03-dialogs.xml, AnkiDroid/src/main/res/values-pl/06-statistics.xml, AnkiDroid/src/main/res/values-pl/07-cardbrowser.xml, AnkiDroid/src/main/res/values-pl/08-widget.xml, AnkiDroid/src/main/res/values-pl/10-preferences.xml, AnkiDroid/src/main/res/values-pl/11-arrays.xml, AnkiDroid/src/main/res/values-pl/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-pl/17-model-manager.xml, AnkiDroid/src/main/res/values-pt-rPT/03-dialogs.xml, AnkiDroid/src/main/res/values-tr/03-dialogs.xml, AnkiDroid/src/main/res/values-ug/02-strings.xml, AnkiDroid/src/main/res/values-ug/03-dialogs.xml, AnkiDroid/src/main/res/values-ug/07-cardbrowser.xml, AnkiDroid/src/main/res/values-ug/10-preferences.xml, AnkiDroid/src/main/res/values-ug/17-model-manager.xml, AnkiDroid/src/main/res/values-zh-rCN/03-dialogs.xml, docs/marketing/localized_description/marketdescription-pl.txt
=> Updated strings from Crowdin 2025/04/02 11:51

AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
- Made vals punctuationAtStart, capturedWord and punctuationAtEnd not-nullable.
- Replaced unnecessary safe calls with dot calls.
- Replaced "get" calls with indexing operator.
* Fixes #13282
Used Inspect Code feature in Android Studio to detect existing warnings in the project and used suggested by Android Studio fixes for the issues in the InstantEditorViewModel file.
Tested the changes on emulator in Android Studio.
- SDK version - API level 34
Official emulation guide is helpful for testing code changes. Please refer to this page https://developer.android.com/studio/run/emulator.
=> Fix Android Studio Warnings in InstantEditorViewModel.kt

AnkiDroid/src/main/res/values-cs/02-strings.xml, AnkiDroid/src/main/res/values-cs/03-dialogs.xml, AnkiDroid/src/main/res/values-cs/06-statistics.xml, AnkiDroid/src/main/res/values-cs/07-cardbrowser.xml, AnkiDroid/src/main/res/values-cs/08-widget.xml, AnkiDroid/src/main/res/values-cs/10-preferences.xml, AnkiDroid/src/main/res/values-cs/17-model-manager.xml, AnkiDroid/src/main/res/values-de/02-strings.xml, AnkiDroid/src/main/res/values-de/03-dialogs.xml, AnkiDroid/src/main/res/values-de/07-cardbrowser.xml, AnkiDroid/src/main/res/values-de/10-preferences.xml, AnkiDroid/src/main/res/values-de/17-model-manager.xml, AnkiDroid/src/main/res/values-es-rAR/02-strings.xml, AnkiDroid/src/main/res/values-es-rAR/03-dialogs.xml, AnkiDroid/src/main/res/values-es-rAR/07-cardbrowser.xml, AnkiDroid/src/main/res/values-es-rAR/17-model-manager.xml, AnkiDroid/src/main/res/values-es-rES/02-strings.xml, AnkiDroid/src/main/res/values-es-rES/03-dialogs.xml, AnkiDroid/src/main/res/values-es-rES/07-cardbrowser.xml, AnkiDroid/src/main/res/values-es-rES/17-model-manager.xml, AnkiDroid/src/main/res/values-gl/01-core.xml, AnkiDroid/src/main/res/values-gl/02-strings.xml, AnkiDroid/src/main/res/values-zh-rCN/02-strings.xml, AnkiDroid/src/main/res/values-zh-rCN/03-dialogs.xml, AnkiDroid/src/main/res/values-zh-rCN/10-preferences.xml
=> Updated strings from Crowdin 2025/04/06 08:45

AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt
before, the dialog would be kept open
this also uses a dialog instead of a toast to alert about the binding being already used
that way, the user can see that the control is already being used before confirming
https://github.com/user-attachments/assets/4dacc255-d993-4c6d-a83c-edb73afa7ee7
edit: added the binding name to the title and replaced the positive button text from `Continue` with `Replace`
=> fix: dismiss axis dialog after selecting

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
Some more part of https://github.com/ankidroid/Anki-Android/pull/17598
* https://github.com/ankidroid/Anki-Android/pull/17598
=> NF: rename `m` to `noteType`

AnkiDroid/src/main/res/values-gl/01-core.xml, AnkiDroid/src/main/res/values-gl/02-strings.xml, AnkiDroid/src/main/res/values-gl/03-dialogs.xml, AnkiDroid/src/main/res/values-gl/04-network.xml, AnkiDroid/src/main/res/values-gl/05-feedback.xml, AnkiDroid/src/main/res/values-gl/06-statistics.xml, AnkiDroid/src/main/res/values-gl/10-preferences.xml, AnkiDroid/src/main/res/values-gl/20-search-preference.xml, AnkiDroid/src/main/res/values-zh-rCN/02-strings.xml, AnkiDroid/src/main/res/values-zh-rCN/10-preferences.xml
=> Updated strings from Crowdin 2025/04/13 08:57

AnkiDroid/src/main/res/values-de/02-strings.xml, AnkiDroid/src/main/res/values-gl/02-strings.xml, AnkiDroid/src/main/res/values-gl/03-dialogs.xml, AnkiDroid/src/main/res/values-gl/07-cardbrowser.xml, AnkiDroid/src/main/res/values-gl/18-standard-models.xml, AnkiDroid/src/main/res/values-lv/01-core.xml, AnkiDroid/src/main/res/values-lv/02-strings.xml, AnkiDroid/src/main/res/values-lv/03-dialogs.xml, AnkiDroid/src/main/res/values-lv/04-network.xml, AnkiDroid/src/main/res/values-lv/05-feedback.xml, AnkiDroid/src/main/res/values-lv/06-statistics.xml, AnkiDroid/src/main/res/values-lv/07-cardbrowser.xml, AnkiDroid/src/main/res/values-lv/08-widget.xml, AnkiDroid/src/main/res/values-lv/09-backup.xml, AnkiDroid/src/main/res/values-lv/10-preferences.xml, AnkiDroid/src/main/res/values-lv/11-arrays.xml, AnkiDroid/src/main/res/values-lv/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-lv/17-model-manager.xml, AnkiDroid/src/main/res/values-lv/18-standard-models.xml, AnkiDroid/src/main/res/values-lv/20-search-preference.xml, AnkiDroid/src/main/res/values-pt-rPT/02-strings.xml, AnkiDroid/src/main/res/values-pt-rPT/03-dialogs.xml, AnkiDroid/src/main/res/values-pt-rPT/10-preferences.xml, AnkiDroid/src/main/res/values-th/01-core.xml, AnkiDroid/src/main/res/values-th/02-strings.xml, AnkiDroid/src/main/res/values-tr/02-strings.xml, AnkiDroid/src/main/res/values-tr/10-preferences.xml, AnkiDroid/src/main/res/values-ug/02-strings.xml, AnkiDroid/src/main/res/values-ug/03-dialogs.xml, AnkiDroid/src/main/res/values-ug/10-preferences.xml
=> Updated strings from Crowdin 2025/04/19 05:41

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt, AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateNotetype.kt, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt, AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateNotetypeTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt
More part of #17598, renaming model to note type
=> NF: rename model in files related to editors

AnkiDroid/src/main/res/values-eo/02-strings.xml, AnkiDroid/src/main/res/values-eo/03-dialogs.xml, AnkiDroid/src/main/res/values-eo/10-preferences.xml, AnkiDroid/src/main/res/values-eo/11-arrays.xml, AnkiDroid/src/main/res/values-fr/02-strings.xml, AnkiDroid/src/main/res/values-fr/17-model-manager.xml, AnkiDroid/src/main/res/values-ka/01-core.xml, AnkiDroid/src/main/res/values-ka/02-strings.xml, AnkiDroid/src/main/res/values-ka/03-dialogs.xml, AnkiDroid/src/main/res/values-ka/07-cardbrowser.xml, AnkiDroid/src/main/res/values-ka/10-preferences.xml, AnkiDroid/src/main/res/values-lv/01-core.xml, AnkiDroid/src/main/res/values-lv/02-strings.xml, AnkiDroid/src/main/res/values-lv/03-dialogs.xml, AnkiDroid/src/main/res/values-lv/04-network.xml, AnkiDroid/src/main/res/values-lv/07-cardbrowser.xml, AnkiDroid/src/main/res/values-lv/08-widget.xml, AnkiDroid/src/main/res/values-lv/10-preferences.xml, AnkiDroid/src/main/res/values-lv/11-arrays.xml, AnkiDroid/src/main/res/values-lv/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-pt-rBR/17-model-manager.xml, AnkiDroid/src/main/res/values-ro/01-core.xml, AnkiDroid/src/main/res/values-ro/03-dialogs.xml, docs/marketing/localized_description/marketdescription-lv.txt
=> Updated strings from Crowdin 2025/04/27 09:34

README.md, docs/marketing/localized_description/marketdescription.txt
Our README still referenced the supermemo algorithm
I altered that to a slightly more buzzword-y (README is a "marketing" type area...) mention of FSRS
=> docs: supermemo -> FSRS

.github/workflows/lint.yml, AnkiDroid/jacoco.gradle, gradle/libs.versions.toml, tools/localization/package.json, tools/localization/yarn.lock
Standard dependency updates but there is quite a queue at the moment
I added one commit outside dependabot - jacoco 0.8.12 -> 0.8.13, CI should check it here then okay to squash
=> Dependency updates 20250509

gradle/libs.versions.toml
=> build(deps): adopt anki upstream 25.02.4

AnkiDroid/src/main/res/values-eo/07-cardbrowser.xml, AnkiDroid/src/main/res/values-fr/03-dialogs.xml, AnkiDroid/src/main/res/values-fr/07-cardbrowser.xml, AnkiDroid/src/main/res/values-fr/10-preferences.xml, AnkiDroid/src/main/res/values-gl/07-cardbrowser.xml, AnkiDroid/src/main/res/values-gl/08-widget.xml, AnkiDroid/src/main/res/values-gl/10-preferences.xml, AnkiDroid/src/main/res/values-gl/11-arrays.xml, AnkiDroid/src/main/res/values-gl/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-lv/02-strings.xml, AnkiDroid/src/main/res/values-lv/03-dialogs.xml, AnkiDroid/src/main/res/values-nl/01-core.xml, AnkiDroid/src/main/res/values-tr/07-cardbrowser.xml, docs/marketing/localized_description/marketdescription-eo.txt, docs/marketing/localized_description/marketdescription-fr.txt, docs/marketing/localized_description/marketdescription-gl.txt, docs/marketing/localized_description/marketdescription-tr.txt
=> Updated strings from Crowdin 2025/05/17 07:26

AnkiDroid/src/main/java/com/ichi2/libanki/Tags.kt, AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.kt
Not sure yet if I'll need those methods for #16473. but updated anyway
In the commits
CI
=> chore(libanki): update Tags methods

AnkiDroid/src/main/java/com/ichi2/anki/browser/RepositionCardFragment.kt
The start input field will now automatically be focused, its default "0" value will be auto-selected, and the keyboard will be shown when the reposition dialog appears.
* Fixes #18281 
The start input field will now automatically be focused, its default "0" value will be auto-selected, and the keyboard will be shown when the reposition dialog appears.
In the dialog, we are now:
- Setting focus on this input field.
- Selecting all text within the input field so it can be easily overwritten (default text is "0").
- Configuring the dialog's window to show the soft keyboard automatically.
Manually.
[Screen_recording_20250511_012317.webm](https://github.com/user-attachments/assets/bbc61e54-afdb-4e11-9fc5-bf20442f6754)
=> Focus on start input field with selected text while repositioning, and show keyboard

AnkiDroid/src/main/res/values-gl/04-network.xml, AnkiDroid/src/main/res/values-gl/10-preferences.xml, AnkiDroid/src/main/res/values-gl/11-arrays.xml, AnkiDroid/src/main/res/values-ru/02-strings.xml, AnkiDroid/src/main/res/values-ru/03-dialogs.xml, AnkiDroid/src/main/res/values-ru/07-cardbrowser.xml, AnkiDroid/src/main/res/values-ru/10-preferences.xml
=> Updated strings from Crowdin 2025/05/18 23:01

gradle/libs.versions.toml, gradle/wrapper/gradle-wrapper.properties
Small batch of updates.
Mostly interested in the androix.webkit new stuff
=> Dependency updates 20250606

AnkiDroid/src/main/res/values-eo/07-cardbrowser.xml, AnkiDroid/src/main/res/values-eo/10-preferences.xml, AnkiDroid/src/main/res/values-eo/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-fil/02-strings.xml, AnkiDroid/src/main/res/values-fil/03-dialogs.xml, AnkiDroid/src/main/res/values-lv/07-cardbrowser.xml, AnkiDroid/src/main/res/values-lv/10-preferences.xml, AnkiDroid/src/main/res/values-lv/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-zh-rCN/07-cardbrowser.xml, docs/marketing/localized_description/marketdescription-lv.txt
=> Updated strings from Crowdin 2025/06/06 15:30

AnkiDroid/src/main/java/com/ichi2/preferences/ReviewerControlPreference.kt
=> fix: crash after selecting a reviewer command

AnkiDroid/src/main/res/values-cs/02-strings.xml, AnkiDroid/src/main/res/values-cs/03-dialogs.xml, AnkiDroid/src/main/res/values-cs/07-cardbrowser.xml, AnkiDroid/src/main/res/values-cs/09-backup.xml, AnkiDroid/src/main/res/values-cs/10-preferences.xml, AnkiDroid/src/main/res/values-de/03-dialogs.xml, AnkiDroid/src/main/res/values-de/07-cardbrowser.xml, AnkiDroid/src/main/res/values-de/08-widget.xml, AnkiDroid/src/main/res/values-es-rAR/10-preferences.xml, AnkiDroid/src/main/res/values-es-rAR/11-arrays.xml, AnkiDroid/src/main/res/values-es-rAR/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-es-rES/10-preferences.xml, AnkiDroid/src/main/res/values-es-rES/11-arrays.xml, AnkiDroid/src/main/res/values-es-rES/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-lv/10-preferences.xml, AnkiDroid/src/main/res/values-tr/01-core.xml, AnkiDroid/src/main/res/values-tr/02-strings.xml, AnkiDroid/src/main/res/values-tr/07-cardbrowser.xml, AnkiDroid/src/main/res/values-tr/10-preferences.xml, AnkiDroid/src/main/res/values-tr/11-arrays.xml, AnkiDroid/src/main/res/values-zh-rCN/10-preferences.xml
=> Updated strings from Crowdin 2025/06/09 13:23

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
on RESUME, StateFlows emitted the last value even if they were unchanged
This caused a search to be performed again
* Fixes #16007
Re-check StateFlows for duplicate values
Manual test on my Google Pixel 9 Pro 
* an edit still displays an updated card
* an edit no longer scrolls to the top of the list
Cause: e35b5b996e7f548ad6f10f871784b2174c521fbc
=> fix(browser): keep scroll position after editing note

AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
* split out onBackPressedCallback
* stop calling requireActivity().finish()
=> improvement(preferences): add 'close' animation

AnkiDroid/src/main/res/values-gl/08-widget.xml, AnkiDroid/src/main/res/values-gl/09-backup.xml, AnkiDroid/src/main/res/values-gl/10-preferences.xml, AnkiDroid/src/main/res/values-pt-rBR/07-cardbrowser.xml, AnkiDroid/src/main/res/values-zh-rCN/03-dialogs.xml, docs/marketing/localized_description/marketdescription-lv.txt
=> Updated strings from Crowdin 2025/06/10 16:46

AnkiDroid/src/main/assets/scripts/ankidroid.js, AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerHelpers.kt, AnkiDroid/src/main/java/com/ichi2/anki/reviewer/BindingMap.kt, AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/GestureParser.kt, AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerViewModel.kt, AnkiDroid/src/test/java/com/ichi2/anki/ui/windows/reviewer/GestureParserTest.kt
The tap and swipe detection is done in JavaScript so we can avoid triggering the gesture when tapping buttons, links, etc
I haven't used a library for that because it seemed overkill just to handle taps and swipes.
The `isInteractable` method was shared by Damien (I can't find the original link) https://github.com/ankidroid/Anki-Android/issues/14303#issuecomment-1693696444
Only the `9 point touch mode` is supported because I think that the 4 points mode became unnecessary after the interactable gesture selection. If the general opinion wants the 4-touch mode, other person can implement it.
* Fixes #14303
Emulator 35:
1. Enable 9 point touch mode and the new reviewer
2. Assign some tap and swipe gestures
3. Tap the screen to trigger the gestures
- also with the screen zoomed in
4. Swipe …
=> feat(new reviewer): gestures

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt, AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
Prep for updating the Browser spinner
* -> prep for #18462
=> refactor(card-browser): move 'available decks' to ViewModel

AnkiDroid/src/main/res/values-gl/02-strings.xml, AnkiDroid/src/main/res/values-gl/03-dialogs.xml, AnkiDroid/src/main/res/values-gl/04-network.xml, AnkiDroid/src/main/res/values-gl/07-cardbrowser.xml, AnkiDroid/src/main/res/values-gl/08-widget.xml, AnkiDroid/src/main/res/values-gl/11-arrays.xml, AnkiDroid/src/main/res/values-gl/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-ja/03-dialogs.xml, AnkiDroid/src/main/res/values-ja/10-preferences.xml
=> Updated strings from Crowdin 2025/06/13 03:52

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/IntegerDialog.kt
Handle problematic IMEs
Likely on an emulator, so I don't mind a suboptimal UX
* Fixes #18504
try...catch
```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/IntegerDialog.kt
<+>UTF-8
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/IntegerDialog.kt b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/IntegerDialog.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/IntegerDialog.kt	(revision 55a4ae51bdace92c6809e97680b009cf12f93692)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/IntegerDialog.kt	(date 1749839292250)
@@ -75,7 +75,7 @@
// #18504: IME bugs can allow a user to send in a non-integer
val input =
try {
- …
```
=> fix(integer-dialog): additional validation

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/res/drawable/divider_handle_background.xml, AnkiDroid/src/main/res/layout-xlarge/card_template_editor.xml, AnkiDroid/src/main/res/layout-xlarge/homescreen.xml, AnkiDroid/src/main/res/values/colors.xml
- Minor refactors for resizable implementation of DeckPicker screen
- Making CardTemplateEditor screen resizable when fragmented.
This PR consists of 2 Commits:
1. The first commit contains minor refactors:
- All color codes are transferred to `colors.xml`.
- Rename android:id for `homescreen.xml` divider.
- Resizable divider of `homescreen.xml` has better dp ratio and higher color contrast
2. The second commit Refactors the CardTemplateEditor Screen:
- Introduce a View inside a FrameLayout in `xlarge\card_template_editor.xml` to house the new divider.
- Implement `ResizablePaneManager` helper class in `CardTemplateEditor.kt` to handle resizing.
Tested on the following Android Emulators:
Pixel Tablet API 35
Large Desktop API 34
Screenshots of …
=> Refactor DeckPicker resizable implementation, and make CardTemplateEditor resizable

AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
follow-up 11d21be8ae4dfdd3e9ed3829c855bc4a2f83b3ac
The invalid gesture now becomes an `UnknownBinding`. So, filter by that and remove the invalid gesture.
Emulator API 35:
1. Build/install any commit before 11d21be8ae4dfdd3e9ed3829c855bc4a2f83b3ac
2. Assing `Long touch` to any command
3. Build/install this PR
4. See if the long touch gesture was removed
=> fix: remove long gesture remnant after upgrade

AnkiDroid/src/main/res/values-de/01-core.xml, AnkiDroid/src/main/res/values-eo/01-core.xml, AnkiDroid/src/main/res/values-eo/02-strings.xml, AnkiDroid/src/main/res/values-eo/03-dialogs.xml, AnkiDroid/src/main/res/values-eo/07-cardbrowser.xml, AnkiDroid/src/main/res/values-eo/17-model-manager.xml, AnkiDroid/src/main/res/values-pl/02-strings.xml, AnkiDroid/src/main/res/values-pl/03-dialogs.xml, AnkiDroid/src/main/res/values-pl/07-cardbrowser.xml, AnkiDroid/src/main/res/values-pl/08-widget.xml, AnkiDroid/src/main/res/values-pl/09-backup.xml, AnkiDroid/src/main/res/values-pl/10-preferences.xml, AnkiDroid/src/main/res/values-pl/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-zh-rCN/02-strings.xml, AnkiDroid/src/main/res/values-zh-rCN/17-model-manager.xml
=> Updated strings from Crowdin 2025/06/18 20:22

AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/GestureParser.kt
- #18559 is stranger than I thought
=> chore: improve more the logging of invalid index issue in new reviewer

AnkiDroid/src/main/res/layout/floating_add_button.xml
Fixes a few issues flagged by Google Play
=> improvement(accessibility): FAB

AnkiDroid/src/main/res/values-cs/02-strings.xml, AnkiDroid/src/main/res/values-hu/01-core.xml, AnkiDroid/src/main/res/values-hu/02-strings.xml, AnkiDroid/src/main/res/values-hu/03-dialogs.xml, AnkiDroid/src/main/res/values-hu/04-network.xml, AnkiDroid/src/main/res/values-hu/10-preferences.xml, AnkiDroid/src/main/res/values-pl/03-dialogs.xml, AnkiDroid/src/main/res/values-pl/10-preferences.xml, AnkiDroid/src/main/res/values-pl/11-arrays.xml, AnkiDroid/src/main/res/values-pl/17-model-manager.xml, AnkiDroid/src/main/res/values-pt-rPT/02-strings.xml, AnkiDroid/src/main/res/values-pt-rPT/03-dialogs.xml, AnkiDroid/src/main/res/values-pt-rPT/07-cardbrowser.xml, AnkiDroid/src/main/res/values-pt-rPT/10-preferences.xml, AnkiDroid/src/main/res/values-pt-rPT/11-arrays.xml, AnkiDroid/src/main/res/values-pt-rPT/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-pt-rPT/17-model-manager.xml, AnkiDroid/src/main/res/values-ug/02-strings.xml, AnkiDroid/src/main/res/values-ug/03-dialogs.xml, AnkiDroid/src/main/res/values-ug/10-preferences.xml, AnkiDroid/src/main/res/values-ug/17-model-manager.xml, AnkiDroid/src/main/res/values-zh-rCN/01-core.xml, docs/marketing/localized_description/marketdescription-pl.txt
=> Updated strings from Crowdin 2025/06/22 07:11

AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt, common/src/main/java/com/ichi2/anki/common/utils/ext/Long.kt, common/src/test/java/com/ichi2/anki/common/utils/ext/LongTest.kt
* Issue #18015
* https://github.com/ankidroid/Anki-Android/pull/18565
=> refactor: move `ifZero` to `common` module

AnkiDroid/src/main/java/com/ichi2/preferences/ReviewerControlPreference.kt
the Show answer should be restricted to the question side, not the answer side.
Untested
=> fix: show answer command side

AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BrowserOptionsDialog.kt, AnkiDroid/src/main/res/layout/browser_options_dialog.xml
Isn't working right, and it'll be easier to redo for 2.22
* Fixes #18616
Partial revert of 2ffad67b07a9cc13d3d7b6def6eeeeec14f05db2
=> fix(card-browser): remove 'default search'

AnkiDroid/build.gradle, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/java/com/ichi2/anki/FieldEditLine.kt, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/SyncActionProvider.kt, AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt, api/build.gradle.kts, common/build.gradle.kts, testlib/build.gradle.kts
Prep for https://github.com/ankidroid/Anki-Android/pull/18630
* https://github.com/ankidroid/Anki-Android/pull/18630
Trusting CI on this one
=> Kotlin 2.2 prep

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt, AnkiDroid/src/main/java/com/ichi2/anki/ui/NoteTypeSpinnerUtils.kt, AnkiDroid/src/main/java/com/ichi2/libanki/CardTemplate.kt, AnkiDroid/src/main/java/com/ichi2/libanki/CardTemplates.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Deck.kt, AnkiDroid/src/main/java/com/ichi2/libanki/DeckConfig.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Field.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Fields.kt, AnkiDroid/src/main/java/com/ichi2/libanki/NotetypeJson.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Notetypes.kt, AnkiDroid/src/main/java/com/ichi2/libanki/backend/BackendUtils.kt, AnkiDroid/src/main/java/com/ichi2/libanki/utils/PythonExtensions.kt, AnkiDroid/src/test/java/com/ichi2/testutils/JsonUtils.kt, AnkiDroid/src/test/java/com/ichi2/utils/JSONObjectTest.kt, common/build.gradle.kts, common/src/main/java/com/ichi2/anki/common/json/JSONContainer.kt, common/src/main/java/com/ichi2/anki/common/json/NamedJSONComparator.kt, common/src/main/java/com/ichi2/anki/common/utils/ext/JSONArray.kt, common/src/main/java/com/ichi2/anki/common/utils/ext/JSONObject.kt, common/src/test/java/com/ichi2/anki/common/json/NamedJSONComparatorTest.kt
* NamedObject
* NamedJSONComparator
* JSONObjectHolder
* JSONContainer 
* #18015
* #18565
=> refactor: move JSON helpers into common

build.gradle.kts
looks like:
```
Gradle Test Run :AnkiDroid:testPlayDebugUnitTest returned SUCCESS in 5m 52.091s
Tests	Passed	Failed	Skipped
1224	1160	0	64
```
Only for Unit Tests
---
I want to be sure that `common` and `libanki` tests are running in CI, and knowing the total tests per suite makes this easier
See the 'Summary' of unit tests in CI
⚠️ This isn't sent to text logs via `println`, but I could do this if requested
=> build(ci): Github Actions Summary: Unit Test Results

AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt
Request by `bilolbekn` on Discord
=> i18n: update Uzbek language name

AnkiDroid/src/main/java/com/ichi2/libanki/NotetypeJson.kt
=> refactor(libanki): use correct const

AnkiDroid/src/main/java/com/ichi2/anki/preferences/AppearanceSettingsFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/ReviewerOptionsFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/ReviewingSettingsFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerViewModel.kt, AnkiDroid/src/main/java/com/ichi2/anki/utils/CollectionPreferences.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt, AnkiDroid/src/test/java/com/ichi2/anki/preferences/PreferencesTest.kt
Extracts some methods so they can be used in other places
Trusting CI
=> refactor: extract collection preference methods

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Notetypes.kt, AnkiDroid/src/test/java/com/ichi2/libanki/NotetypesTest.kt
Co-authored-by: David Allison
Brings across changes from https://github.com/ankitects/anki/blob/630bdd31893d5113b81cd60612cef3ebf146d5b4/pylib/anki/models.py
David asked me to YOLO this as part of work for #14134 
* #14134
=> libanki: add notetype change methods and tests

AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt, AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt, AnkiDroid/src/test/java/com/ichi2/libanki/SchedulerTest.kt, gradle/libs.versions.toml
This is a draft for feasibility check of the new release
Some interesting issues that seem persistent in local testing:
1. something changed about scheduling ? We have a violated date expectation
```
SchedulerTest > test_nextIvlV2 FAILED
java.lang.AssertionError: 
Expected: "10.8mo"
but: was "10.7mo"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
at com.ichi2.libanki.SchedulerTest.test_nextIvlV2(SchedulerTest.kt:627)
```
2. there appears to be a new typescript function we need a handler for (what an excellent test!)
```
PostRequestHandlerTest > All backend typescript functions should be handled FAILED
java.lang.AssertionError: Mapping exists for every TS backend function call
Expected: iterable with items …
```
=> build(deps): adopt anki upstream 25.06betas

AnkiDroid/src/main/java/com/ichi2/anki/BackendExporting.kt, AnkiDroid/src/main/java/com/ichi2/libanki/BackendImportExport.kt
=> dev(export): no crash report if 'check media' required

AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerViewModel.kt, AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/autoadvance/AutoAdvance.kt
Emulator 35:
- Open the reviewer to see if it can still be initialized
=> refactor(new reviewer): misc refactors

AnkiDroid/src/main/res/layout-sw600dp/reviewer2.xml, AnkiDroid/src/main/res/layout/reviewer2.xml, AnkiDroid/src/main/res/values-night/colors.xml, AnkiDroid/src/main/res/values/attrs.xml, AnkiDroid/src/main/res/values/colors.xml, AnkiDroid/src/main/res/values/theme_black.xml, AnkiDroid/src/main/res/values/theme_dark.xml, AnkiDroid/src/main/res/values/theme_light.xml, AnkiDroid/src/main/res/values/theme_plain.xml
Incremental work
In the commits
Emulator 35
<details>
</details>
=> feat(new reviewer): tweak `black` and `plain` colors

AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/GestureParser.kt, AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt, AnkiDroid/src/test/java/com/ichi2/anki/ui/windows/reviewer/GestureParserTest.kt
Keeps compatible with the old reviewer settings.
It's simpler to configure and more ergonomic in some scenarios
Emulator 35 (resizable) in tablet and phone modes.
Also tested in cards with content enough to demand vertical scrolling
=> feat(new reviewer): four points tap mode

AnkiDroid/src/main/java/com/ichi2/anki/preferences/ReviewerOptionsFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt, AnkiDroid/src/main/res/layout-sw600dp/reviewer2.xml, AnkiDroid/src/main/res/layout/reviewer2.xml, AnkiDroid/src/main/res/xml/preferences_reviewer.xml
Implements an Anki (collection) setting
Emulator 35
<details>
</details>
ConstraintLayout Flows are quite handy https://developer.android.com/reference/androidx/constraintlayout/helper/widget/Flow
=> feat(new reviewer): show remaining card count setting

AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt, AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncMediaWorker.kt, AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncWorker.kt
* Fixes #18776
Properly show the error in the notification
Use this patch to trigger the error:
```patch
Subject: [PATCH] improvement(sync): include error message in notification
---
Index: AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncMediaWorker.kt
<+>UTF-8
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncMediaWorker.kt b/AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncMediaWorker.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncMediaWorker.kt	(revision 3a6ae8b8ae276226f9a397452cee51f0e36c4929)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncMediaWorker.kt	(date 1751726537550)
@@ -66,9 +66,7 @@
val auth …
```
=> fix(sync): invalid endpoint

AnkiDroid/src/main/java/com/ichi2/anki/settings/Prefs.kt, AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/GestureParser.kt, AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt, AnkiDroid/src/main/res/xml/preferences_controls.xml, AnkiDroid/src/test/java/com/ichi2/anki/ui/windows/reviewer/GestureParserTest.kt
Implements support for one of the old reviewer settings in the new reviewer
In the commits
Unit tests.
Also, emulator API 35:
1. Change `Settings > Controls > Swipe sensitivty` to a low value
2. Check if a bigger swipe is necessary to trigger a gesture
3. Change `Settings > Controls > Swipe sensitivty` to a high value
4. Check if a smaller swipe is necessary to trigger a gesture
Also, here's how the setting looks now with the percentage display format:
=> feat(new reviewer): swipe sensitivity

AnkiDroid/src/main/java/com/ichi2/anki/settings/Prefs.kt, AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt
Implements a feature present in the old reviewer
Emulator API 35:
https://github.com/user-attachments/assets/2b26c8e1-da4d-4318-a83c-e99c45758e1a
=> feat(new reviewer): card zoom

AnkiDroid/src/main/java/com/ichi2/anki/preferences/AboutFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/HeaderFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/ReviewerOptionsFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/SettingsFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/reviewer/ReviewerMenuSettingsFragment.kt, AnkiDroid/src/main/res/layout-sw600dp/preferences.xml, AnkiDroid/src/main/res/layout/about_layout.xml, AnkiDroid/src/main/res/layout/preferences.xml, AnkiDroid/src/main/res/layout/preferences_reviewer_menu.xml, AnkiDroid/src/main/res/layout/settings_fragment.xml, AnkiDroid/src/main/res/xml/preference_headers.xml, AnkiDroid/src/test/java/com/ichi2/anki/analytics/PreferencesAnalyticsTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/preferences/PreferencesTest.kt
Key differences:
1. The fragments now contain their own toolbar and title, which fixed the delay of setting the title when changing the fragment
2. Big screens: each page has its tile above it instead of modifying the `headers page` title
3. Big screens: Reviewer Menu options now works as a fragment instead of an activity
Emulator API 35:
<details> <summary>First three commits</summary>
https://github.com/user-attachments/assets/ca3dbda6-cf42-4bfd-bb0f-68cf05114ea6
https://github.com/user-attachments/assets/b3f8c299-35ca-4be4-bfe4-ebc2448e4752
</details>
<details> <summary>Last two commits</summary>
https://github.com/user-attachments/assets/3c885cf5-b0ac-47ff-b1e1-5fd84515a89d
</details>
=> improvement(settings): make fragments more independent

AnkiDroid/src/main/assets/scripts/ankidroid.js, AnkiDroid/src/main/java/com/ichi2/anki/previewer/TypeAnswer.kt, AnkiDroid/src/main/java/com/ichi2/anki/settings/Prefs.kt, AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerViewModel.kt
note: The "Auto focus" setting doesn't work with it at the moment. I couldn't get it working on my first couple tries, so I prioritized other stuff. It works on the old reviewer, so someone can try looking there. I'll add an issue after this is merged.
Emulator API 35
<details>
https://github.com/user-attachments/assets/b05dba10-ed79-4d83-9ac0-2af96bd31dd0
</details>
=> feat(new reviewer): html type in answer

AnkiDroid/src/main/assets/scripts/ankidroid.js, AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/Gesture.kt, AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/GestureProcessor.kt, AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/GestureParser.kt, AnkiDroid/src/main/java/com/ichi2/ui/GestureDisplay.kt, AnkiDroid/src/main/res/values/10-preferences.xml, AnkiDroid/src/test/java/com/ichi2/anki/ui/windows/reviewer/GestureParserTest.kt
i.e. two, three and four-finger tap gestures
Specially useful on tablets, where:
- it's easier to do multi-finger gestures because of the extra space. It's also easier if you have free hands if the device is on a table
- using geographical taps is harder due to more hand movement being necessary
Also useful on phones if holding with two hands.
- Detect the multi touch taps in javascript
- Pass the touch count and pressed time to Kotlin through URL query parameters
- Invoke the gestures
Emulator API 36
https://github.com/user-attachments/assets/44ec0972-a182-4ab1-9604-f23eb84e9a44
Android 15, Galaxy S23
https://github.com/user-attachments/assets/702560d1-43ba-4bb7-aa57-283042948bff
https://developer.android.com/reference/android/view/ViewConfiguration#getMultiPressTimeout()
_Please, go …
=> feat(new reviewer): multi-finger gestures

AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorIntentTest.kt, AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTabOrderTest.kt, AnkiDroid/src/androidTest/java/com/ichi2/anki/testutil/NoteEditorFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.kt, AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionIntentBuilder.kt, AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler2.kt, AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/FieldState.kt, AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/NoteEditorLauncher.kt, AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.kt, AnkiDroid/src/main/java/com/ichi2/anki/pages/ImageOcclusion.kt, AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt, AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/browser/CardBrowserViewModelTest.kt
- Prep for transitioning NoteEditor to Activity
- Splintered from #18724 
=> Rename NoteEditor to NoteEditorFragment

.github/workflows/milestone.yml
https://github.com/ankidroid/Anki-Android/milestone/69 => 2.22
* Part of #18830 (past issues/PRs aren't fixed, future ones will be)
See f84a1bc963745d52151e7bc5c6e020cbe8747ba0 for 2.21 bump
=> chore: use 2.22 milestone labels

AnkiDroid/src/main/res/values-ar/01-core.xml
=> Updated strings from Crowdin 2025/07/12 14:34

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt
* Was for #18716. Will be useful in future.
=> logs: diagnostics for collectionLoadError

.github/workflows/tests_emulator.yml
this is the same idea from the unit test workflow that lets us dynamically expand our matrix based on manual workflow input from GitHub web UI
Trimmed out of:
* #17851
=> test(ci): dynamic iteration control for emulator tests

AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncWorker.kt
* Fixes #18890 (I hope)
Avoid sending an empty endpoint to the sync media. Similar to 02deb0a0a5905f1cca91aa20cedf67c80cc1bc83
I haven't
=> fix(sync): invalid sync server

AnkiDroid/src/main/res/drawable/ic_add_bell.xml, AnkiDroid/src/main/res/layout/fragment_schedule_reminders.xml, AnkiDroid/src/main/res/layout/schedule_reminders_list_item.xml, AnkiDroid/src/main/res/values/10-preferences.xml
- Adds FAB to ScheduleReminders; clicking on the icon will create a new review reminder
- Removes column headings as per discussions with David on Discord -- we will make the time have greater visual focus rather than creating a strict table with headings and rows
- Adds schedule_reminders_list_item
- Adds ic_add_bell icon
* For GSoC 2025: Review Reminders
- A new icon, updating XML files
- Tested on a physical Samsung S23, API 34.
=> feat(reminders): RecyclerView XML

AnkiDroid/src/main/java/com/ichi2/anki/BackendBackups.kt, AnkiDroid/src/main/java/com/ichi2/anki/BackendImporting.kt, AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt, libanki/src/main/java/com/ichi2/anki/libanki/BackendImportExport.kt, libanki/src/main/java/com/ichi2/anki/libanki/Collection.kt
Partially implements this file:
https://github.com/ankitects/anki/blob/5cb191d624ce8ea1f8bc8578cd2414df8a54904d/pylib/anki/collection.py
* Split out from #18552
Partially implements this file:
https://github.com/ankitects/anki/blob/5cb191d624ce8ea1f8bc8578cd2414df8a54904d/pylib/anki/collection.py
⚠️ I intended to not make functional changes, so did not test this
The original PR led to the push for the `libanki` split, but the PR itself probably needs to be trashed
=> libanki Compat: Collection.kt (sched/DB/Import/Export)

AnkiDroid/src/androidTest/java/com/ichi2/anki/ReviewerFragmentTest.kt, AnkiDroid/src/androidTest/java/com/ichi2/anki/ReviewerTest.kt, AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt, AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.kt, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt, AnkiDroid/src/main/java/com/ichi2/anki/deckpicker/DeckPickerViewModel.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/EditDeckDescriptionDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/pages/CongratsPage.kt, AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt, AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt, AnkiDroid/src/main/java/com/ichi2/anki/services/ReminderService.kt, AnkiDroid/src/main/java/com/ichi2/anki/utils/ext/Deck.kt, AnkiDroid/src/main/java/com/ichi2/widget/WidgetConfigScreenAdapter.kt, AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CreateDeckDialogTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/libanki/DecksTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/libanki/SchedulerTest.kt, AnkiDroid/src/test/java/com/ichi2/testutils/TestClass.kt, libanki/src/main/java/com/ichi2/anki/libanki/Decks.kt, libanki/src/main/java/com/ichi2/anki/libanki/sched/Scheduler.kt
This is a collection of minor fixups/libanki compat changes I extracted from a branch where I was improving `CreateDeckDialog` 
* #18875
=> Decks: various fixups

libanki/src/main/java/com/ichi2/anki/libanki/PythonTypes.kt
=> docs(libanki): Link ID to main class

AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt, AnkiDroid/src/test/java/com/ichi2/anki/IntentHandlerTest.kt
This fixes the issue where sharing text to AnkiDroid was being treated as a CSV import and hence it was failing.
* Fixes #18772 
Added `handleSharedText` which will be used for the new `LaunchType.SHARED_TEXT`.
_Before Fix:_
Share text → `ACTION_SEND` → `TEXT_IMPORT` → CSV import fails → App closes
_After Fix:_
Share text → `ACTION_SEND` + `EXTRA_TEXT` → `SHARED_TEXT` → NoteEditor opens with shared text
Manual testing + unit tests.
=> Text share to AnkiDroid should launch note editor

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt, AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/MediaTest.kt, AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/DevOptionsFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt, AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerViewModel.kt, AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogTest.kt, libanki/src/main/java/com/ichi2/anki/libanki/Collection.kt
Partially implements this file:
https://github.com/ankitects/anki/blob/5cb191d624ce8ea1f8bc8578cd2414df8a54904d/pylib/anki/collection.py
* Split out from #18552
Partially implements this file:
https://github.com/ankitects/anki/blob/5cb191d624ce8ea1f8bc8578cd2414df8a54904d/pylib/anki/collection.py
⚠️ I intended to not make functional changes, so did not test this
The original PR led to the push for the `libanki` split, but the PR itself probably needs to be trashed
=> libanki compat: Collection Part 2 (Image Occlusion/Object Helpers/Utils/Notes)

AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/AnkiDroidJsAPITest.kt, AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/libanki/CollectionTest.kt, AnkiDroid/src/test/java/com/ichi2/utils/NoteTypeTest.kt, libanki/testutils/src/main/java/com/ichi2/anki/libanki/testutils/ext/Collection.kt
I split this out the 'final' refactor for:
* https://github.com/ankidroid/Anki-Android/issues/18015
=> refactor(tests): extract utils from NoteTypeTest

AnkiDroid/src/main/res/values-ar/03-dialogs.xml, AnkiDroid/src/main/res/values-ar/04-network.xml, AnkiDroid/src/main/res/values-ar/07-cardbrowser.xml, AnkiDroid/src/main/res/values-ar/08-widget.xml, AnkiDroid/src/main/res/values-ar/10-preferences.xml, AnkiDroid/src/main/res/values-cs/10-preferences.xml, AnkiDroid/src/main/res/values-eo/02-strings.xml, AnkiDroid/src/main/res/values-eo/10-preferences.xml, AnkiDroid/src/main/res/values-gl/01-core.xml, AnkiDroid/src/main/res/values-gl/02-strings.xml, AnkiDroid/src/main/res/values-gl/03-dialogs.xml, AnkiDroid/src/main/res/values-gl/10-preferences.xml, AnkiDroid/src/main/res/values-gl/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-tr/10-preferences.xml, AnkiDroid/src/main/res/values-ug/02-strings.xml, AnkiDroid/src/main/res/values-ug/10-preferences.xml, AnkiDroid/src/main/res/values-vi/01-core.xml, AnkiDroid/src/main/res/values-vi/02-strings.xml, AnkiDroid/src/main/res/values-zh-rCN/02-strings.xml, AnkiDroid/src/main/res/values-zh-rCN/10-preferences.xml
=> Updated strings from Crowdin 2025/07/21 15:33

AnkiDroid/src/test/java/com/ichi2/anki/libanki/DeckConfigTest.kt, common/src/main/java/com/ichi2/anki/common/json/JSONContainer.kt, libanki/src/main/java/com/ichi2/anki/libanki/CardTemplate.kt, libanki/src/main/java/com/ichi2/anki/libanki/DeckConfig.kt, libanki/src/main/java/com/ichi2/anki/libanki/Field.kt, libanki/src/main/java/com/ichi2/anki/libanki/NotetypeJson.kt
I pointed someone towards our code (because I believed it was the best documentation of the JSON)
It looked verbose on GitHub, so I improved it
* define delegated properties and use them: `val name by jsonString("name")`
⚠️ Trusting CI
https://kotlinlang.org/docs/delegated-properties.html
Can't be used on value classes
(I hope Arthur loves this :D)
=> refactor(libanki): use delegated JSON Properties to improve documentation

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/MediaTest.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/DevOptionsFragment.kt, AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/libanki/NoteTypeTest.kt, libanki/src/main/java/com/ichi2/anki/libanki/Collection.kt, libanki/src/test/java/com/ichi2/anki/libanki/AbstractSchedTest.kt, libanki/src/test/java/com/ichi2/anki/libanki/CardTest.kt, libanki/src/test/java/com/ichi2/anki/libanki/CollectionTest.kt, libanki/src/test/java/com/ichi2/anki/libanki/DecksTest.kt, libanki/src/test/java/com/ichi2/anki/libanki/FinderTest.kt, libanki/src/test/java/com/ichi2/anki/libanki/FlagTest.kt, libanki/src/test/java/com/ichi2/anki/libanki/NoteWithColTest.kt, libanki/src/test/java/com/ichi2/anki/libanki/SchedulerTest.kt, libanki/testutils/src/main/java/com/ichi2/anki/libanki/testutils/ext/Collection.kt
Partially implements this file:
https://github.com/ankitects/anki/blob/5cb191d624ce8ea1f8bc8578cd2414df8a54904d/pylib/anki/collection.py
* Split out from #18552
Partially implements this file:
https://github.com/ankitects/anki/blob/5cb191d624ce8ea1f8bc8578cd2414df8a54904d/pylib/anki/collection.py
⚠️ I intended to not make functional changes, so did not test this
The original PR led to the push for the `libanki` split, but the PR itself probably needs to be trashed
=> libanki compat: Collection Part 4 (refactorings & Timebox)

gradle/libs.versions.toml
=> build(deps): anki25.07.5 backend

tools/localization/src/download.ts
Adds some logging to check the language ids so they can be used for fixing #18980. I'm pretty sure the languages ids are the languages codes but we also have dialects and I don't want to fiddle with that. The steps I want to take are:
- find out the used language ids after merging this
- decide what languages to eliminate. 0% langauges(note that some do have a few words translated) as shown by Crowdin are  bambara(bam), icelandic(is), igbo(ig), kyrgyz(ky), manx(gv), maori(mi), swahili(swa), swati(ss), tajik(tg), tsonga(ts), tswana(tn), venda(ve), wolof(wo), xhosa(xh), zulu(zu). We could include even more by bumping the allowed percent a bit higher to 3-4%.
- build an array of allowed languages and pass it to the [buildProject()](https://crowdin.github.io/crowdin-api-client-js/classes/Trans …
=> Add logging for crowdin project languages

tools/localization/src/download.ts
Fixes the previous PR( #19024) about logging the languages, I was accessing the incorrect api endpoint. Hopefully it works now.
=> Fix crowdin languages access

AnkiDroid/src/main/assets/scripts/ankidroid.js, AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/Gesture.kt, AnkiDroid/src/main/java/com/ichi2/anki/settings/Prefs.kt, AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/GestureParser.kt, AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt, AnkiDroid/src/test/java/com/ichi2/anki/ui/windows/reviewer/GestureParserTest.kt
Previously, gestures waited for the double tap timeout to confirm that the user did or did not intend to make a double tap
Multi-finger gestures didn't do that because they were considered as always intentional
The first change this commit does is prioritizing detecting swipes as well, considering them as always intentional
The second change is avoid waiting the timeout if the `Double tap` gesture isn't assigned, making single taps more responsive. A second single tap below the double tap timeout is ignored to avoid wrong taps.
If the `Double tap` gesture is enabled, wait for confirmation only with single taps
In the commits
Emulator 34:
[no double tap.webm](https://github.com/user-attachments/assets/9e595de4-a116-4996-9611-544a056a9db4)
[with double …
=> feat(new study screen): make gestures more responsive

libanki/src/main/java/com/ichi2/anki/libanki/Collection.kt
* Split out from #18552
Partially implements this file:
https://github.com/ankitects/anki/blob/44f3bbbbc96160f33e0798f82080aa0ef61e0df2/pylib/anki/collection.py#L1089-L1109
⚠️ I intended to not make functional changes, so did not test this other than unit tests
=> improvement(libanki-collection): upstream DB maintenance code

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialogViewModel.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/ControlsTabPreference.kt, AnkiDroid/src/main/java/com/ichi2/anki/settings/enums/ShouldFetchMedia.kt, AnkiDroid/src/main/java/com/ichi2/anki/settings/enums/ToolbarPosition.kt, AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/AnswerButton.kt, AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/AnswerFeedbackView.kt, AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/AnswerTimer.kt, AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/AnswerTimerStatus.kt, AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/GestureParser.kt, AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerMenu.kt, AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/StudyScreenRepository.kt, AnkiDroid/src/main/java/com/ichi2/anki/utils/CollectionPreferences.kt, AnkiDroid/src/main/java/com/ichi2/anki/utils/ext/Context.kt, AnkiDroid/src/main/java/com/ichi2/anki/utils/ext/SavedStateHandle.kt, AnkiDroid/src/test/java/com/ichi2/anki/ui/windows/reviewer/GestureParserTest.kt
=> chore: fix my copyright headers

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt, AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt, AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt, AnkiDroid/src/main/java/com/ichi2/anki/Info.kt, AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/ReadText.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportFileSelectionFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SchedulerUpgradeDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TtsPlaybackErrorDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TtsVoicesDialogFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/help/HelpDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/help/HelpItemActionsDispatcher.kt, AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/AboutFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/scheduling/ForgetCardsDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/utils/AndroidUtils.kt, AnkiDroid/src/main/java/com/ichi2/utils/WebViewUtils.kt
Small code cleanup I wanted to do while reviewing other PR
=> Require activity

AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
- BootService and NotificationService will sometimes need to run suspending methods when sending review reminders because they need to access the collection. However, a BroadcastReceiver does not have a coroutine scope. The generally recommended alternative from my research is to run on the global scope, since that's what a BroadcastReceiver onReceive method is doing already. However, running on the global scope is dangerous because if the thread hangs, then a memory leak will occur. Hence, I created a `runGloballyWithTimeout` helper method and put it in CoroutineHelpers to ensure uses of the global scope are safe. If the process runs for longer than a provided timeout, then it auto-cancels and avoids a memory leak. Theoretically we could also use an expedited Worker, but AnkiDroid is …
=> feat(reminders): create global scope helper

AnkiDroid/src/main/res/values-eo/10-preferences.xml, AnkiDroid/src/main/res/values-fa/10-preferences.xml, AnkiDroid/src/main/res/values-ru/02-strings.xml, AnkiDroid/src/main/res/values-ru/03-dialogs.xml, AnkiDroid/src/main/res/values-ru/10-preferences.xml
=> Updated strings from Crowdin 2025/08/28 13:17

AnkiDroid/src/main/java/com/ichi2/anki/multimedia/audio/AudioRecordingController.kt, AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/audiorecord/AudioRecordView.kt, AnkiDroid/src/main/java/com/ichi2/compat/BaseCompat.kt, AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt, AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.kt, AnkiDroid/src/main/java/com/ichi2/compat/CompatV31.kt, AnkiDroid/src/main/java/com/ichi2/compat/CompatV33.kt, AnkiDroid/src/main/java/com/ichi2/compat/VibrationAttributesCompat.kt
added support for vibration USAGE
* Fixes #19129
made it similar to ResolveInfoCompat
I don't know how to test this. It should be an additive change
=> chore: add support for vibration USAGE

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt, AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.kt, AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserFragmentViewModel.kt, AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt, AnkiDroid/src/main/java/com/ichi2/anki/model/SelectableDeck.kt, AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt, AnkiDroid/src/main/java/com/ichi2/anki/reviewreminders/ScheduleReminders.kt, AnkiDroid/src/main/java/com/ichi2/anki/settings/Prefs.kt, AnkiDroid/src/main/java/com/ichi2/widget/WidgetConfigScreenAdapter.kt, AnkiDroid/src/main/java/com/ichi2/widget/cardanalysis/CardAnalysisWidgetConfig.kt, AnkiDroid/src/main/java/com/ichi2/widget/deckpicker/DeckPickerWidgetConfig.kt, AnkiDroid/src/main/res/drawable/ic_menu_24.xml, AnkiDroid/src/main/res/layout/card_browser_searchview.xml, AnkiDroid/src/main/res/layout/cardbrowser_searchview.xml, AnkiDroid/src/main/res/values/03-dialogs.xml, AnkiDroid/src/main/res/values/preferences.xml, AnkiDroid/src/main/res/xml/preferences_dev_options.xml, AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/browser/CardBrowserViewModelTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/dialogs/DeckSelectionDialogTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/widget/cardanalysis/CardAnalysisWidgetConfigTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/widget/deckpicker/DeckPickerWidgetConfigTest.kt
* Setup for #18709
I had a mostly working `SearchView` in a branch, and wanted to start working on implementing this in main
It felt best to put it behind a debug flag. Especially as we need to decide whether the fragmented Card Browser is more important than this.
----
1. I duplicated the layouts
2. I implemented the navigation button
3. I wanted 'open deck selection dialog' properly, so I improved `SelectableDeck`
3, Finally, I implemented the 'Deck' Chip
I felt this was sufficient for a PR
Search, SearchView, and Menu are not yet implemented
Unit tests
Tested on tablet and Pixel 9 Pro
* Opening nav sidebar works
* Selecting a deck works
* Selecting all decks works
* Previous screen continues to work
* Scrolling hides the SearchView
=> dev: introduce non-functional Card Browser SearchView

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/EmptyCardsDialogFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt, AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt, AnkiDroid/src/main/java/com/ichi2/widget/AddNoteWidget.kt, AnkiDroid/src/main/java/com/ichi2/widget/AnalyticsWidgetProvider.kt, AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt, AnkiDroid/src/main/java/com/ichi2/widget/Id.kt, AnkiDroid/src/main/java/com/ichi2/widget/WidgetAlarm.kt, AnkiDroid/src/main/java/com/ichi2/widget/WidgetPermissionReceiver.kt, AnkiDroid/src/main/java/com/ichi2/widget/cardanalysis/CardAnalysisWidget.kt, AnkiDroid/src/main/java/com/ichi2/widget/cardanalysis/CardAnalysisWidgetConfig.kt, AnkiDroid/src/main/java/com/ichi2/widget/cardanalysis/CardAnalysisWidgetPreferences.kt, AnkiDroid/src/main/java/com/ichi2/widget/deckpicker/DeckPickerWidget.kt, AnkiDroid/src/main/java/com/ichi2/widget/deckpicker/DeckPickerWidgetConfig.kt, AnkiDroid/src/main/java/com/ichi2/widget/deckpicker/DeckPickerWidgetPreferences.kt, AnkiDroid/src/test/java/com/ichi2/anki/widget/AnalyticalWidgetProviderTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/widget/cardanalysis/CardAnalysisWidgetConfigTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/widget/deckpicker/DeckPickerWidgetConfigTest.kt
I got some changes from the linked PR over the finish line
* Fixes #18393
* Fix conflicts
* Drop a fair number of changes I didn't feel added enough value to review
* Improved the `AppWidgetId` change: added docs and additional extension methods
⚠️ CI only, trusting original implementation
=> refactor: strongly type some IDs

AnkiDroid/src/main/res/values-cs/02-strings.xml, AnkiDroid/src/main/res/values-ja/01-core.xml, AnkiDroid/src/main/res/values-ja/02-strings.xml, AnkiDroid/src/main/res/values-ja/07-cardbrowser.xml, AnkiDroid/src/main/res/values-ja/10-preferences.xml, AnkiDroid/src/main/res/values-pl/01-core.xml, AnkiDroid/src/main/res/values-pl/03-dialogs.xml, AnkiDroid/src/main/res/values-pl/07-cardbrowser.xml, AnkiDroid/src/main/res/values-zh-rTW/01-core.xml, AnkiDroid/src/main/res/values-zh-rTW/02-strings.xml, AnkiDroid/src/main/res/values-zh-rTW/03-dialogs.xml
=> Updated strings from Crowdin 2025/09/21 16:32
