ankidroid/Anki-Android

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt

Fix custom study deck appearance with no delay.
It happens with other options too.
Fixes #12975
Running the coroutine on the activity scope so it doesn't get cancelled.
Tested on Google Emulator

Fix custom study deck appearance with no delay

---

AnkiDroid/src/main/res/values/theme_black.xml
AnkiDroid/src/main/res/values/theme_dark.xml

In dark and black mode the count zero wasn't visible.
Fixes #12952
Changed the color of the zero count in the dark and black mode.
SDK: Android Tiramisu
Emulator: Pixel 6
Dark mode:
Black mode:

Changed the color of the zero count

---

AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt

This PR fixes the export deck bug
Fixes #12966
Closes #12966
Select the exact deck before calling the export method
1. Long press a deck other than the default deck you were studying 
2. Press export deck
3. This particular deck will be exported

bug fix for deck export

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt

String false space fixed
This PR fixes the unwanted white space that was occurring before the param (string) inside the main string
used `.trimMargin()` 
Tested on google emulator
BEFORE : 
AFTER
Add a pipe character and use trim margin. The pipe means there aren't any leading spaces before the input text
(https://stackoverflow.com/questions/53229432/string-with-triple-quote-inside-of-string-with-triple-quote)

string intent fix

---

.github/workflows/label.yml

Adds a new label to make it easier for reviewers to spot PRs made by new developers. In the original issue the request was made for `New developer`, I choose `New contributor` as a more(maybe) inclusive label(but I can revert this no issues). The code is basically a copy of an example from the `actions/github-script` [documentation](https://github.com/actions/github-script#welcome-a-first-time-contributor) with the end changed to add the desired label instead of creating a comment.
Fixes #12944 
As mentioned above, should work but I wasn't able to test it, I'll keep a look out for this in future PRs.

Add CI job to append a special label to PRs made by new contributors

---

.github/workflows/label.yml

Embarrassing but I missed a comma, hopefully there's nothing else currently crashing this workflow.
Reviewed again the previous code.

Fix typo in  new contributor label workflow

---

build.gradle

Should fix noted issue of inability to sync with new backend 
Related https://github.com/ankidroid/Anki-Android-Backend/pull/249
Build and release new backend (done), use it here
`./gradlew installPlayDebug` locally and a sync with new backend enabled and it works

build(deps): use backend 0.1.17-2.1.55 now with TLS

---

tools/update-localizations.py

The localizations update script was in python2, needed a forward port to 3
Fixes the currently broken i18n sync process, after updating the github workflow to use python 3
Fixes #12930 
- print "" to print ("") https://stackoverflow.com/a/41341191/9910298
- urllib use to urllib.request https://stackoverflow.com/a/3969809/9910298
- use "yourstring".replace() directly, not the object-level string.replace https://stackoverflow.com/a/9452122/9910298
- file() use to open() use, minding the binary/string differences https://stackoverflow.com/a/27177607/9910298
- this required a decode on one byte item https://stackoverflow.com/a/7585619/9910298 / https://stackoverflow.com/a/33054552/9910298
Local testing, appeared to generate the correct commit
That I still don't like python :shrug: 
Would have …

fix(i18n): forward port to python3

---

AnkiDroid/build.gradle
AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt

Leak canary can be pretty annoying while testing some things, so this adds an option to disable it with local.properties
Add a local property to disable leak canary
Install the app and see if LeakCanary shows up

Make possible to disable leak canary on local.properties

---

build.gradle

Another day, another backend release :-(
Requires https://github.com/ankidroid/Anki-Android-Backend/pull/251
Closes #13022
You can test before/after with the new schema by logging the determined timezone:
```diff
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.kt b/AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.kt
index 06c6c7339e..da8b3b5777 100644
--- a/AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.kt
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.kt
@@ -132,6 +132,7 @@ class AnkiStatsTaskHandler private constructor(
var cards: Int
var minutes: Int
/* cards, excludes rescheduled cards https://github.com/ankidroid/Anki-Android/issues/8592 */
+            Timber.e("cutoff is %d", …
```

Fix incorrect timezone in new schema

---

AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt

Invisible expanders are unnecessarily clickable and prevent decks from opening.
Fixes #13034
Tested on a physical device (The debug info is written in #13034)
https://user-images.githubusercontent.com/10436072/209548750-2733cdcb-b65a-4d46-915c-d5c2ea653798.mp4

Make invisible expanders unclickable

---

AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt

Fix compress format and extension.
When the image is imported from gallery, it is imported as JPEG with extension jpg, but when imported as drawing it is imported as JPEG, but to my surprise with extension PNG, so I think TODO is added to fix this inconsistency in compress format and extension.
Fixed this inconsistency by changing the extension to JPG when imported from drawing.
Tested on google emulator
https://user-images.githubusercontent.com/76740999/210334748-babbf6d2-175a-4ff6-96d9-9baa3ea98c88.mp4
https://user-images.githubusercontent.com/76740999/210334753-c70d98a4-a7ef-44a3-9400-aecfacafe605.mp4 …

Fix compress format and extension format.

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SimpleMessageDialog.kt

FIXME
onCreate(savedInstanceState: Bundle?) function is called to perform other initialization tasks for the Fragment and should not be called from the onCreateDialog function.
Tested on google emulator (API 28)

fixes the super. call with correct one

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.kt
AnkiDroid/src/main/res/values/02-strings.xml

regarding the deck shortcut removal on the deck deletion, we can't remove the shortcut ourself google as restricted https://issuetracker.google.com/issues/68949561?pli=1#comment4 that on purpose we can only disable them so I updating the proper method for now
Shortcut handling
##Debug Info
AnkiDroid Version = 2.16alpha91
Android Version = 12
Manufacturer = Google
Model = sdk_gphone64_x86_64
Webview User Agent = Mozilla/5.0 (Linux; Android 12; sdk_gphone64_x86_64 Build/SE1A.220630.001; …

Disable shortcut if corresponding deck is deleted

---

lint-rules/src/test/java/com/ichi2/anki/lint/rules/DuplicateTextInPreferencesXmlTest.kt

Update unit test inside DuplicateTextInPreferencesXmlTest.kt
Removed Java Strings and added Kotlin Multi-line strings. 
Updated the expected result with actual result in case of invalid .xml file because of Duplicate Text In Prefereneces.

update: unit test in DuplicateTextInPreferencesXmlTest.kt

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/DevOptionsFragment.kt
AnkiDroid/src/main/res/values/preferences.xml
AnkiDroid/src/main/res/xml/preferences_dev_options.xml
AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/ScopedStorageAnkiDroidTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MigrateEssentialFilesIntegrationTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/ScopedStorageMigrationIntegrationTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/Utils.kt

Fixes #13093
On the commits
I haven't changed the javadoc of `getDefaultAnkiDroidDirectory` because it is too long and spending time on it isn't the priority
1. Create a fresh install
2. Go to settings > Advanced
3. See if the folder is app-specific
4. See on the file manager as well if the legacy storage were not created and if the files are at the app-specific folder
And did the same thing with a parallel build created by running `./tools/parallel-package-name.sh com.ichi2.anki.a AnkiDroid.A`

Default new users to a writable folder

---

.github/workflows/sync_translations.yml

Creates a PR for strings changes. I added an extra step which verifies that there are changes before actually creating the PR to better separate the work. @BrayanDSO The format of the date is `2023/01/13 08:38` (so UTC time), let me know if this is ok(I assumed that _YYYYMMDDHHmm_ is a placeholder for a date format and not the actual format requested). I added basic strings for title and body, these of course, can be changed as needed.
Fixes #13102 
Tested it on my fork and it does create the requested PR(couldn't test the no strings changes scenario, but I don't see why this wouldn't work).

Enable creating a PR when running the Crowdin translation sync workflow

---

AnkiDroid/src/main/java/com/ichi2/anki/FieldEditLine.kt
AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt
AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.kt
AnkiDroid/src/main/java/com/ichi2/compat/CompatV33.kt

Fix readSparseArray deprecation
Fixes part of #12364
Add it to compat
Opened the note editor to see if it crashed on 33 emulator

Fix readSparseArray deprecation

---

AnkiDroid/build.gradle
AnkiDroid/src/main/AndroidManifest.xml
AnkiDroid/src/main/res/xml/preferences_sync.xml
api/build.gradle
api/src/debug/AndroidManifest.xml
api/src/main/java/com/ichi2/anki/FlashCardsContract.kt
tools/parallel-package-name.sh

Since we're moving to scoped storage, uninstalling the app will very likely delete user data.
In Debug/Dev, we want this to impact the dev's workflow as little as possible So we change the applicationId. This relays the expectation that a 'stable' anki should be using 'com.ichi2.anki' and an 'unstable/dev' AnkiDroid should be 'com.ichi2.anki.debug'. A developer should have two copies of the app, each with their own storage location.
* I had a bug with `@string/applicationId` being marked as an IDE error. The code ran after a rebuild. I believe this is fine, but is a priority for review
* The perl regexes have been tested manually, and seemed fine
* Security review of API Logic
As previously, define the API permissions/authority using the applicationId:
permission: …

ci: debug identifier -> 'com.ichi2.anki.debug'

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/RecursivePictureMenu.kt
AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt
AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.kt
AnkiDroid/src/main/java/com/ichi2/compat/CompatV33.kt

Fix getParcelableArrayList deprecation
Fixes part of #12364
Added it to compat
Opened the browser and selected a deck

Fix getParcelableArrayList deprecation

---

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioRecordingFieldController.kt
AnkiDroid/src/main/res/layout/multimedia_edit_field_activity.xml

Move recording buttons outside scroll view as it should always be on the screen.
Fixes   `// FIXME: We should move this outside the scrollview as it should always be on the screen.`
Fix layout issue.
https://user-images.githubusercontent.com/76740999/211755265-9e5f2d5b-a406-493a-9170-000fde8693eb.mp4
https://user-images.githubusercontent.com/76740999/211755281-2d9557d6-dce2-4857-9a8a-929dbc3d14af.mp4

Moved recording buttons outside the scroll view as it should always be on the screen.

---

AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.kt

`[Settings]->[Controls]->[Bury]` sets the command (key, gesture) for the action of "Bury card", but its title is just `Bury` (in contrast to the titles of the similar actions, that is, `Bury note`, `Suspend card`, `Suspend note`). This commit changes the title to `Bury card`.
n/a
Replace the current string with the other existing string

Fix the command title for "Bury card" action

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
AnkiDroid/src/main/res/values/10-preferences.xml
AnkiDroid/src/main/res/values/11-arrays.xml
AnkiDroid/src/main/res/values/constants.xml
AnkiDroid/src/main/res/values/preferences.xml
AnkiDroid/src/main/res/xml/preferences_sync.xml
AnkiDroid/src/test/java/com/ichi2/anki/servicemodel/PreferenceUpgradeServiceTest.kt

This converts the Fetch media on sync SwitchPreference to a ListPreference with the options "Always, "Only on Wi-Fi" and "Never"
Fixes #12932
This converts the Fetch media on sync SwitchPreference to a ListPreference with the options "Always, "Only on Wi-Fi" and "Never"
Unit test. And by installing an old version of the app then installing this new one
Mostly I tried to understand the code by reading other PRs after using git blame on `preferences_sync.xml`. 

Add option to sync media only on unmetered connections

---

AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt

Correcting unexpected link breaks in sync message
Fixes #13040 
Made string uniform 
Manually tested

Line Break in sync message corrected

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsList.kt

- Removed stream() & replaced it with kotlin iterators in markAncestorsIndeterminate()
- Using lambda for comparator in sort()
- Fixed double documentation of check()
- Refactored the 2 duplicate init documentations into one class documentation.
- Tests

[KotlinCleanup] TagsList

---

AnkiDroid/build.gradle

This was my fault previously on a dependency updates run, I let it slip into a version range with a known incompatibility that I even left a comment for!
Unlogged - I chatted about it on discord quite a while back and at least one other person reproduced though. Finally getting around to fixing it
Just reverts the version pin to the one in place before I incorrectly moved it to a version that requires minSdkVersion 26+
Start an API21 emulator and run `./gradlew jacocoAndroidTestReport` - that is enough to trigger the issue and to show it works with commons-compress at 1.12 again
Even if I leave a comment for myself I sometimes just don't see it and make a mistake

build(deps): revert apache commons-compress to API21-compatible version

---

AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveFile.kt
AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveFileTest.kt

Bug occurred with a test of a migration of the AnKing deck.
Likely due to a reset of the phone, an empty file was produced and the 'real' file went to the 'conflict' file in the source directory. This issue was theorised about, and was a personal TODO, let's get it fixed.
This fixes one part of #13170, and gets the logic in place for the remainder of the fix
```
DEST
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  paste-178541790495174.jpg
-rw-rw---- 1 u0_a148 ext_data_rw 0 2023-01-30 22:58 paste-178541790495174.jpg
SOURCE
c429ab2472c70d11254d4834bf4addc311447fe33c629ca07b7068eb6039d87d  paste-178541790495174.jpg
-rw-rw---- 1 u0_a141 media_rw 13052 2023-01-30 22:58 paste-178541790495174.jpg
```
Unit test added

fix(ScopedStorage): destination has empty file

---

AnkiDroid/src/main/java/com/ichi2/ui/GesturePicker.kt
AnkiDroid/src/main/res/values/10-preferences.xml

Currently, it is impossible to replace "None" in the gesture list with other languages.
(`Settings` -> `Controls` -> (`Enable gestures`) -> one of the items of `Command mapping` -> `Add gesture`　-> Open the dropdown list)
https://github.com/ankidroid/Anki-Android/blob/3c379007d2e7a8905808df3bd589e10ef39a08d2/AnkiDroid/src/main/java/com/ichi2/ui/GesturePicker.kt#L89-L91
This commit enables translating it  into other languages.
n/a
- Add a new string for "None" in the gesture list, in 10-preferences.xml
- Use the translatable string instead of current untranslatable code, in GesturePicker.kt
Tested on a physical device
Checked that the new string is surely reflected on the screen

Enable "None" in the gesture list to be translated

---

AnkiDroid/src/main/AndroidManifest.xml

Fixes #12953
Set the absolute path on the Manifest for the manage space activity
1. Install one of the parallel builds (can be found at the releases page or by running ./tools/parallel-package-name.sh com.ichi2.anki.a AnkiDroid.A then installing the app)
2. Go to the app settings > Storage

Fix manage space activity on parallel and debug builds

---

AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.kt

Fixes #13169
Change the `getDefaultAnkiDroidDirectory` method
1. Installed the app
2. Check if the collection is on a subfolder of `files/` at the AnkIDroid directory preference

Default path to a `files/` subfolder

---

AnkiDroid/src/main/AndroidManifest.xml
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ScopedStorageService.kt
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MigrateEssentialFiles.kt
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectory.kt
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveFile.kt
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/migrateuserdata/MigrateUserData.kt
AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt
AnkiDroid/src/main/java/com/ichi2/anki/services/ServiceConnection.kt
AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.kt
AnkiDroid/src/main/java/com/ichi2/utils/FileUtil.kt
AnkiDroid/src/main/java/com/ichi2/utils/HandlerUtils.kt
AnkiDroid/src/main/java/com/ichi2/utils/Repeater.kt
AnkiDroid/src/main/res/values/01-core.xml
AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/ScopedStorageMigrationIntegrationTest.kt

This Pull Request implements the foreground service which performs the Scoped Storage Migration, and hooks it up to the Deck Picker
* Ensure alpha users will not be placed in a bad position by this. This PR moves us to 'developers can test the migration', I'd rather keep this as too unstable for alpha, despite the amount of testing, given the impact.
* Question the `onStartCommand` isStarted logic
* Determine the TODOs which need to be moved to the Plan
This also contains a couple refactorings which could be split out if requested in the review.
Related #5304
* Define a Service
* Define code to run a repeated task
* Define a Service Binder to abstract out the intricacies from DeckPicker
* Define an API which determines the state of the migration
⚠️ This needs more thorough testing. I'm …

feat: Scoped Storage Migration Service, Notification & Deck Picker Implementation

---

.github/ISSUE_TEMPLATE/bug_report_form.yml

See form at: https://github.com/david-allison/Anki-Android/issues/new?assignees=&labels=Bug&template=bug_reprot_form.yml&title=%5BBUG%5D%3A+
See: #12214. It was proposed that the repo had a bug template. At the very least, the checkboxes are less confusing, and we can 'require' some input in the Debug Info
- Fixes: #12214
- Fixes: #12248 (Superseded)
Based off `issue_template.md` with additional copy changes.
For now, we don't disable the previous template
See: https://github.com/david-allison/Anki-Android/issues/new?assignees=&labels=Bug&template=bug_reprot_form.yml&title=%5BBUG%5D%3A+
See: #12248 for discussion
* `required` is currently the only available validation on forms

GitHub: Implement Bug Reporting Form

---

AnkiDroid/src/main/java/com/ichi2/async/Connection.kt

This reverts commit 72acb72c1af78b2118ca5afedc8e6ec6ca6e5cef.
The afterFullSync path was intended for use with the new backend, where the backend automatically reopens the collection. I've added a comment as part of the revert.
My mistake - I tested the main fix in that PR quite thoroughly, and only added this change at the last minute.
Closes #13255

Revert "Scheduler should be reloaded on full sync"

---

lint-release.xml

Lint no longer fails
partial revert of 0ca2e6c204aef9ae16242d932b87988f3c5a237f
Fixes #13197

lint: enable 'MonochromeLauncherIcon'

---

AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt
AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.kt
AnkiDroid/src/main/java/com/ichi2/compat/CompatV33.kt
AnkiDroid/src/main/java/com/ichi2/compat/PackageManagerCompat.kt
AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt
AnkiDroid/src/main/java/com/ichi2/utils/CheckCameraPermission.kt
AnkiDroid/src/main/java/com/ichi2/utils/VersionUtils.kt
AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupMetaTest.kt

Deprecated in API 33: https://developer.android.com/reference/android/content/pm/PackageManager#getPackageInfo(java.lang.String,%20int) 
I'm going to use this functionality in Scoped Storage, so I've prioritised fixing this deprecation. 
Fixes https://github.com/ankidroid/Anki-Android/pull/12548 (superseded)
* Sincere & profuse apologies to @n1snt - I'm marking a concerted effort to get back into both maintenance and development to ensure this doesn't occur again.
Related https://github.com/ankidroid/Anki-Android/issues/12364
⚠️ I'm unsure on this approach, and welcome alternate suggestions
`flags: Integer` was replaced with `flags: PackageInfoFlags` in API 33. This is likely because the `int` flags were expanded to be `long` flags.
In addition to this, an interface with a `@LongDef` was …

fix getPackageInfo deprecation

---

AnkiDroid/build.gradle
AnkiDroid/src/main/java/com/ichi2/libanki/DB.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Finder.kt
AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.kt
AnkiDroid/src/main/java/com/ichi2/utils/DatabaseChangeDecorator.kt
api/build.gradle
build.gradle
lint-rules/build.gradle

This is not quite a standard dependency update PR - reviewer notes:
- yes, we're adopting an appcompat alpha, $deity help us
- pay close attention to the last commit - there is quite a bit of trouble harmonizing the build compatibility targets, I *think* this way is okay but I'm not sure if the spec of a jvmToolchain in the lint-rules repo will fail people that don't have JDK8 installed? If not then doing the source/target compatibility stuff is better if more verbose
I linked relevant sources online in the commit
This is rebased against main as of just now when I create this PR

Dependency updates 20220216

---

.idea/dictionaries/android.xml
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerNoParamTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
AnkiDroid/src/test/java/com/ichi2/testutils/IgnoreFlakyTestsInCIRule.kt

We lose a lot of time due to flaky tests, this is also a bad experience for new users
Allow us to mark tests as flaky, these are skipped with a message. This may be for a single OS, or for all of them.
❗️Ignoring tests only on CI may be the wrong move, open to discussion here, but wanted the skeleton of the code in
Unit test

`@Flaky`: block flaky tests from CI 

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt

Empty card issue
Placed a check to not allow empty cards from getting saved by checking the first edit text field and showing a toast respectively
Fixes #13240
Placed a check
Tested on OnePlus Nord CE

added check which rejects new notes with empty first field

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTabOrderTest.kt

- Replaced if statement for wrapped.get() with ?.let
- Tests

[KotlinCleanup] NoteEditorTabOrderTest 

---

AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt

To solve the following warning
> PreferenceFragment      com.ichi2.anki.debug                 W  onPreferenceStartFragment is not implemented in the parent activity - attempting to use a fallback implementation. You should implement this method so that you can configure the new fragment that will be displayed, and set a transition between the fragments.
Add `onPreferenceStartFragment` to `Preferences` activity, following https://developer.android.com/develop/ui/views/components/settings/organize-your-settings
- Go to settings
- Start opening the preference screens
https://developer.android.com/develop/ui/views/components/settings/organize-your-settings

Solve `onPreferenceStartFragment` warning

---

AnkiDroid/src/main/java/com/ichi2/anki/preferences/GeneralSettingsFragment.kt
AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt
AnkiDroid/src/test/java/com/ichi2/anki/LocaleLinting.kt
AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilsTest.kt

Fixes #13259
1. Make the `System language` string to be translated to the system language
2. Retrieve language names from constants instead of building them dinamically with java methods
SDK 25 emulator
https://user-images.githubusercontent.com/69634269/219368631-8d3dfece-acd1-4e42-a664-73ad8c5ca0fb.mp4

Use manually translated language names instead of getting them from java libraries

---

.github/workflows/lint.yml

The action is currently broken. We don't use it often.
To be reinstated when upstream has fixed the issue.
Issue #13296

ci: temporarily remove `creyD/prettier_action`

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.kt
AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTest.kt
AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ACRATest.kt
AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/CollectionTest.kt
AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/NotificationChannelTest.kt
AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/DBTest.kt
AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/HttpTest.kt
AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/ImportTest.kt
AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/MediaTest.kt
AnkiDroid/src/androidTest/java/com/ichi2/anki/testutil/GrantPermissions.kt

I bumped the emulator version for tests in https://github.com/ankidroid/Anki-Android/pull/13261. It got problematic as `WRITE_EXTERNAL_STORAGE` was denied, so the `GrantPermissionRule` rule failed
* Define permission strings which may be null on certain APIs
* Define grantPermissions() which filters out these null strings
Tested on emulators: API 32 and 21
* `GrantPermissionRule.grant` fails if strings are null or empty, but not if the list is empty
* And if the permission is denied (not unreasonable)

tests: fix emulator tests on API 30

---

AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt
AnkiDroid/src/main/java/com/ichi2/utils/StringUtil.kt
AnkiDroid/src/test/java/com/ichi2/utils/StringUtilTest.kt

same as Kotlin's trimEnd
Made `trimRight` be like the below snippet and saw if it passed the tests the same way
```kotlin
fun trimRight(s: String?): String? {
return s?.trimEnd()
}
```

NF: remove trimRight method

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.kt
AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.kt
AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.kt
AnkiDroid/src/main/res/layout/note_editor_toolbar.xml

The toolbar buttons have some styling and accessibility inconsistencies:
- They have no tooltips for new users to understand their purpose
- Custom buttons added by insertItem have no click animation and have a smaller clickable area
- As briefly mentioned in #13244, the "Add toolbar item" button does not have a contentDescription set
I could not find any open issue for these problems.
- Add tooltips to all buttons with the exception of custom toolbar buttons since they already have a long click action
- Add contentDescription to all buttons for accessibility. For custom toolbar buttons, the button text is used.
- Resize the layout of insertItem buttons to match the other buttons (see Before screenshot)
- Add background animation on insertItem buttons
Tested on physical Pixel 2 SDK 30 …

Improve accessibility and styling of note editor toolbar

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.kt
AnkiDroid/src/test/java/com/ichi2/anki/dialogs/DeckPickerContextMenuTest.kt

This adds the Add-Card option to the DeckPickerContextMenu
Fixes #12962 
SDK: Android Tiramisu
Emulator: Pixel 6

Added Add-Card Option in DeckPickerContextMenu

---

AnkiDroid/src/main/java/com/ichi2/anki/preferences/AboutFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/DevOptionsFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/SyncSettingsFragment.kt
AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt

Fixes #12669
Related #13315
Replaces most usages of `MaterialDialog` with `AlertDialog` on preferences classes, except Custom sync server preferences as they are handled on #12367
`Controls` screen preferences haven't been changed

Replaces usages of `MaterialDialog` with `AlertDialog` on most preferences classes

---

AnkiDroid/src/main/AndroidManifest.xml
AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnkiDroidCrashReportDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/GeneralSettingsFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt
AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt
AnkiDroid/src/test/java/com/ichi2/anki/preferences/PreferencesTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/servicemodel/PreferenceUpgradeServiceTest.kt
AnkiDroid/src/test/java/com/ichi2/testutils/ReflectionUtils.kt
AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilsTest.kt

Adds support to SDK ≥ 33 new language settings configuration and simplifies language change handling
Fixes #7173
Fixes #8865
Fixes #13046
The commits splitting is only to help reviewers and myself. This probably needs to be squashed
1. Stop handling language changes manually (#12832) by removing it from the manifest
- `locale` manual handling was added ~10 years ago and Android's API has changed a lot since then 
2. Upgrade the previous language scheme of `locale.toString()` to `locale.toLanguageTag` because the new API takes languageTags
3. Use Android's new API for setting and storing locales (reference: https://developer.android.com/guide/topics/resources/app-languages)
4. Refactor a part of `LanguageUtil`
Run on SDK 33 emulator and on my phone (Android 12, Samsung One UI 4.1)
1. Go to …

Stop handling language changes manually

---

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt
AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt
AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.kt
AnkiDroid/src/main/java/com/ichi2/compat/CompatV33.kt

part of https://github.com/ankidroid/Anki-Android/issues/12364
I don't know how to test this

fix getParcelable deprecation

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt

Deprecate MaterialDialog and use AlertDialog instead #13315
Replaced MaterialDialog with AlertDialog.Builder under two functions, showDeleteNoteDialog() and dealWithTimeBox() of NextCardHandler inner class.
Imported AlertDialogFacade.kt
Tested on my physical device for showDeleteNoteDialog() but didn't know how to test it for dialog under dealWithTimeBox() 
https://user-images.githubusercontent.com/60137237/220864119-41d0f4e3-f4f5-4a35-bb6e-3d50850928fb.mp4

#13315 replaced MaterialDialog with AlertDialog in AbstractFlashcardViewer class

---

AnkiDroid/src/test/java/com/ichi2/anki/ReviewerNoParamTest.kt

Also had `drawerConflictsIfRight` on macOS flake - all seem flaky

test: mark drawerConflict tests as flaky

---

AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/AboutFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/migrateuserdata/MigrateUserData.kt
AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt
AnkiDroid/src/main/java/com/ichi2/exceptions/AggregateException.kt
AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt
AnkiDroid/src/main/java/com/ichi2/utils/StringUtil.kt

Handles a few TODOs. Previously a crash would have occurred
Issue #5304
* Show a notification with a 'copy debug info'
* Copies Exception + Stack trace to clipboard
* Submits a Crash Report
<details>
<summary>Manually by having `MoveFile` throw - debug info included</summary>
```
Migration failed
java.lang.IllegalStateException: Testing
at com.ichi2.anki.servicelayer.scopedstorage.MoveFile.execute(MoveFile.kt:42)
at com.ichi2.anki.servicelayer.scopedstorage.migrateuserdata.MigrateUserData$Executor.executeOperationInternal$AnkiDroid_playDebug(MigrateUserData.kt:344)
at com.ichi2.anki.servicelayer.scopedstorage.migrateuserdata.MigrateUserData$Executor$execute$1.invoke(MigrateUserData.kt:334)
at com.ichi2.anki.servicelayer.scopedstorage.migrateuserdata.MigrateUserData$Executor$execute$1.invok …
```

Storage Migration: Notification to handle failure

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/pages/PageChromeClient.kt

Replaces usages of MaterialDialog with AlertDialog in NoteEditor.kt,PageChromeClient.kt

Replaces usages of MaterialDialog with AlertDialog

---

AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt

- `com.ichi2.anki.ReviewerTest.baseDeckName[SchedV2]`
- `NullPointerException`
- `com.ichi2.anki.ReviewerTest.exitCommandWorksAfterControlsAreBlocked[SchedV2]`
- `CollectionAlreadyOpen`
https://github.com/ankidroid/Anki-Android/actions/runs/4265822001/jobs/7425612801
```
ReviewerTest > [SchedV2] > com.ichi2.anki.ReviewerTest.exitCommandWorksAfterControlsAreBlocked[SchedV2] FAILED
net.ankiweb.rsdroid.exceptions.BackendInvalidInputException$BackendCollectionAlreadyOpenException: CollectionAlreadyOpen
at net.ankiweb.rsdroid.exceptions.BackendInvalidInputException$Companion.fromInvalidInputError(BackendInvalidInputException.kt:34)
at net.ankiweb.rsdroid.BackendException$Companion.fromError(BackendException.kt:114)
at net.ankiweb.rsdroid.BackendKt.unpackResult(Backend.kt:323)
at …
```

test: mark flaky windows tests

---

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt
AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt

Replaces usages of MaterialDialog with AlertDialog in BasicImageFieldController.kt,ImportUtils.kt

Replaces usages of MaterialDialog with AlertDialog for BasicImageFieldController.kt,ImportUtils.kt

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckOptionsActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/OnRenderProcessGoneDelegate.kt
AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt

Replaces usages of MaterialDialog with AlertDialog in DeckoptionsActivity.kt,ControlPreference.kt,onRenderProcessGoneDelegate.kt

Replaces usages of MaterialDialog with AlertDialog for DeckoptionsActivity.kt,ControlPreference.kt,onRenderProcessGoneDelegate.kt

---

AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt
AnkiDroid/src/main/res/values/02-strings.xml

Migrating storage is a high-risk operation as it involves copying the user's media
Disable:
* AnkiDroid Directory
* Corruption: Media from the one collection is moved to the other
* V3 Migration
* High Risk: Disabling defensively
- #5304
- #13094
Grey the preference and set a summary
Manually: API 33 emulator
**Unused n this PR**
* If a preference is not disabled, the `click` handler won't stop the change/dialog event
* If disabled, the `click` handler doesn't fire
But we can handle the dialog event separately to catch this
On switch/checkbox preferences, all we need to do is override `setOnPreferenceChangeListener` AFTER it's been set conditionally

Disable some advanced settings if migrating storage

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DialogHandler.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
AnkiDroid/src/main/java/com/ichi2/anki/export/ExportType.kt
AnkiDroid/src/main/java/com/ichi2/utils/BundleUtils.kt
AnkiDroid/src/main/res/drawable/ic_baseline_backup_24.xml
AnkiDroid/src/main/res/values/03-dialogs.xml
AnkiDroid/src/test/java/com/ichi2/anki/export/ExportDialogParamsTest.kt
AnkiDroid/src/test/java/com/ichi2/utils/BundleUtilsTest.kt

Add a dialog to remind users to sync
This exists to:
* Ensure that users are aware their data is at risk after API 30 and the collection folder may be deleted on uninstall
* Encourage users to sync
Firstly, refactor 'ExportDialog',  we want to add 'include media' functionality here and it needed work. This also fixes a bug in the `include scheduling` flag defaults
Then, implement a dialog
This is shown:
* If the user is NOT new to AnkiDroid
* And the collection is unsafe. Either:
* Not syncing and collection is unsafe
* Syncing and has not synced recently
This dialog is shown once every 13-16 days.
Manually

feat: Add "Backup Prompt" Dialog

---

.github/workflows/stale.yml

Changes:
days-before-pr-stale: 30 -> 21
The agreed figure was 14, but reduce to this incrementally to provide users with appropriate time to fix their PRs without overburdening them
Large numeric jump: '3 weeks' reads better than a numeric number of days, and '4 weeks' wouldn't be a significant change from 30 days

build(ci): reduce PR stale timeout to 21 days

---

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt
AnkiDroid/src/main/res/values/01-core.xml

"Undo" item's title isn't switched to one for whiteboard mode though its action itself and its icon are done.
Fixes #12960
Make a new string for "Undo" item's title for whiteboard mode
https://user-images.githubusercontent.com/10436072/206904451-9fa0ca93-1b34-43e3-bbe7-a089d3039cbc.mp4

Make "Undo" item's title for whiteboard mode

---

.idea/dictionaries/davidallison.xml
AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/migrateuserdata/MigrateUserData.kt
AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt
AnkiDroid/src/main/java/com/ichi2/anki/services/ServiceConnection.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt

During a storage migration, we have some media in an old folder and others in the collection media folder.
Instead of handling the possibility of 2 folders, we immediately migrate requested files when requested by the reviewer/previewers
- Related: #5304
When an image/sound file is requested, and is:
* not found
* inside the collection
* available for migration
Add a new task to prioritise it in the storage migration
Image migration: needs to be performed in `shouldInterceptRequest` as WebClient error handlers do not provide enough control to recover from
Sound: performed in the error handler to avoid impacting the fast path
API 31/33 emulator.
The migration performance hit is not noticeable in my testing
Using `CountDownLatch` - constructor is very light

Reviewer: migrate requested files immediately

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt

Lots of noise in test logs
Comment: https://github.com/ankidroid/Anki-Android/pull/13345#issuecomment-1445219437
* Avoid 'Op on UI Thread'
* Stop logging this one under Robolectric - embedded in `Anki-Android-Backend`
* Avoid 'Don't know what to do with dataSource..'
* Answer from GitHub `https://github.com/robolectric/robolectric/issues/4673`
Test only
Note: One gotcha with this shadow is that you need to either configure an exception or a [ShadowMediaPlayer.MediaInfo](https://robolectric.org/javadoc/3.8/org/robolectric/shadows/ShadowMediaPlayer.MediaInfo.html) instance for that data source (using [addException(DataSource, IOException)](https://robolectric.org/javadoc/3.8/org/robolectric/shadows/ShadowMediaPlayer.html#addException-org.robolectric.shadows.util.DataSource-java.io.IOExceptio …

test: Reduce noise in test logging

---

AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt

`browserIsInMultiSelectModeWhenSelectingAll`
```
CardBrowserTest > browserIsInMultiSelectModeWhenSelectingAll FAILED
java.lang.AssertionError:
Expected: <true>
but: was <false>
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
at com.ichi2.anki.CardBrowserTest.browserIsInMultiSelectModeWhenSelectingAll(CardBrowserTest.kt:118)
```
https://github.com/ankidroid/Anki-Android/actions/runs/4297184207/jobs/7489838069

test: mark flaky tests

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/MediaService.kt

A subset of functionality may be problematic while we are migrating storage.
- Related: https://github.com/ankidroid/Anki-Android/issues/13094
- Related: #5304
* Show a snackbar when selected functionality is active
* Do not disable 'restore from backup' functionality
* ⚠️ DO not grey out the menu items
* If they can be disabled with an explanation when clicked on, I'd support this - haven't looked into it
Manually: API 31 AOSP emulator

DeckPicker: disable functionality during storage migration

---

.idea/dictionaries/android.xml
.idea/dictionaries/anki.xml
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.kt
AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/SyncTest.kt
AnkiDroid/src/test/java/com/ichi2/testutils/AndroidTest.kt

A lot of `DeckPicker` was legacy sync related code. This extracts it.
If there's a "no", or a likelihood that this won't go through quickly, then I'll close this and rework #13356 - in the linked PR, I wanted the changes on the `DeckPicker` related to storage migrations to be obvious, but this isn't a 'must'.
* **Note:** This is 'legacy backend' refactoring - if there are immediate issues, let's close this.
* Speeds up a couple of tests
* Makes `DeckPicker` a little easier to navigate
Reduces code churn on #13356, isolates changes in `DeckPicker` to being `DeckPicker` related, rather than including syncing-related code
* Extract `createSyncListener`, then extract associated functionality
* Speed up tests as they no longer need a `DeckPicker`
Manually

Refactor: Legacy syncing

---

.github/ISSUE_TEMPLATE/bug_report_form.yml

Render debug info as block text
[Tested on cloned repo](https://github.com/doozan/Anki-Android/issues/new?assignees=&labels=Bug%2CNeeds+Triage&template=bug_report_form.yml&title=%5BBUG%5D%3A+)
[Sample issue](https://github.com/doozan/Anki-Android/issues/4)
https://gh-community.github.io/issue-template-feedback/structured/#codeblock-rendering-for-contributor-submitted-text

Issue template: Use "render: text" for debug info

---

AnkiDroid/src/main/java/com/ichi2/anki/preferences/SyncSettingsFragment.kt

Disabled "force full sync" preference when user is not logged in.
Fixes #13374 
First checked if the user is logged in or not and enabled/disabled the preference accordingly.
https://user-images.githubusercontent.com/76740999/222242830-ca0e7a55-ce50-47aa-a1de-bc7a5fff981e.mp4
https://user-images.githubusercontent.com/76740999/222242855-9e45aded-4261-401c-af71-45bc9dabd0c0.mp4

fix: Disable "force full sync" preference when user is not logged in

---

AnkiDroid/src/main/res/values/theme_dark.xml

Set iconColor in theme_dark.xml.
Fixes #13383
Fixes #13372
Closes #13373
Added an attribute iconColor in theme_dark.xml .

fix: Set iconColor in theme_dark.xml

---

AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt

```
CardBrowserTest > previewWorksAfterSort FAILED
java.lang.IllegalStateException: Card '1596783600440' not found
at com.ichi2.anki.CardBrowser.getPropertiesForCardId(CardBrowser.kt:2662)
at com.ichi2.anki.CardBrowserTest.previewWorksAfterSort(CardBrowserTest.kt:358)
```
https://github.com/ankidroid/Anki-Android/actions/runs/4318941121/jobs/7537826151

test(Windows): previewWorksAfterSort is flaky

---

tools/storage/set_scoped_storage.sh

A script to enable/disable scoped storage without the need to uninstall/upgrade from `targetSdkVersion 29`
Makes testing of the disable/enable routine quicker
Issue #5304
Cherry-picked from https://github.com/ankidroid/Anki-Android/pull/13396

add tool: enable/disable scoped storage

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/AsyncDialogFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DialogHandler.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.kt
AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt
AnkiDroid/src/test/java/com/ichi2/anki/dialogs/DatabaseErrorDialogTest.kt

Move serialisation + handling to classes instead of being spread around the codebase
Keep enum: `WhichDialogHandler` to ensure that we do not reuse int values
* Our DialogHandler implementation split our two aspects of handling `Message`s (which isn't the easiest code to follow):
* Serialisation around the codebase
* Deserialisation + logic in `DialogHandler`  
* Makes #13356 easier to understand, as we add another handler (without a dialog) here
* #5075
* Split out each `DialogHandler` into a class: containing the method and the serde of its parameters
* Document the class a little better
* Use an enum to ensure that no items have duplicated `what` integers, and all cases are handled
Unit test only
Finally documenting our use of `Message`: The implicit assumption is that we launch all of …

refactor: DialogHandler

---

.idea/dictionaries/davidallison.xml
AnkiDroid/src/main/java/com/ichi2/anki/BackendBackups.kt
AnkiDroid/src/main/java/com/ichi2/anki/BackendImporting.kt
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/Import.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportFileSelectionFragment.kt

For the final 'functional' PR of scoped storage, we allow a colpkg 'import' from the Deck Picker to allow restoring from a backup.
This refactoring helps get this over the finish line
* Extract & generify methods
* Add `ImportOptions` class to allow limiting the dialog options (we can hide: [apkg, colpkg, csv] from the import selection dialog)
Tested in #13396
I'm pretty backlogged with PRs, prioritising this one will help keep velocity, but there will be multiple PRs with different implementations of this for now.

Refactor: Extract & generify 'import'

---

AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/ExecutorTest.kt

A preempted element is executed before a regular element
flaked on Windows
```
ExecutorTest > A preempted element is executed before a regular element FAILED
java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
at java.base/java.util.Objects.checkIndex(Objects.java:372)
at java.base/java.util.ArrayList.get(ArrayList.java:459)
at com.ichi2.anki.servicelayer.scopedstorage.ExecutorTest.A preempted element is executed before a regular element(ExecutorTest.kt:110)
```
https://github.com/ankidroid/Anki-Android/actions/runs/43499294 …

test: mark flaky test

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/res/layout/card_browser.xml

_Hide Card Browser Filter Sheet_
Fixes _Visibility of filter_sheet_fab set to gone and functionality of the button is commented and the functionality is already added in CardBrowser.kt menu named as filter by flag_
Fixes #13341
_Commented the functionality of the button in the CardBrowser.kt and set Visibility of the filter_sheet_fab to gone_

Hide the Floating Action Button

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt

Fixes the bug mentioned in #13210 
Fixes  #13210
mToolbarSearchView was used to check if the SearchView is in focus but mToolbarSearchView was never initialized so it always returned null
Physical Device (Android 13) & Tests 
https://developer.android.com/reference/kotlin/androidx/compose/ui/focus/FocusState

Fixed hardware keyboard search bug.

---

AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
AnkiDroid/src/main/java/com/ichi2/libanki/sync/BackendSync.kt

Fixes #13420 
During login, only username and password passed, but it needs to pass endpoint also.
1. Run syncserver using Anki desktop
```
Anki> $env:SYNC_USER2="user: pass"
Anki> .\anki-console.bat --syncserver
```
2. Connect both Ank Desktop and AnkiDroid to same network in sync prefs
3. Login using `user: pass` on AnkiDroid
4. Then sync
5. The files are synchronised with desktop
6. Logout, turn of custom sync and Login to ankiweb.net
7. Then sync
8. The files are synchronised with web

use endpoint for custom sync server

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt

Search box is filled with required query of filter marked and filter suspended.
Fixes #13415
`searchWithFilterQuery()` is called to fill the search view.
https://user-images.githubusercontent.com/76740999/223359600-c3f2b2c3-73df-47c3-8bfd-b8008e967f57.mp4
https://user-images.githubusercontent.com/76740999/223359612-dc33789d-a65b-473a-9cbe-801716193122.mp4

fix: Search box is filled with required query of filter marked and filter suspended

---

AnkiDroid/src/main/java/com/ichi2/libanki/Media.kt

The Logcat for the issue 
```
java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.ichi2.anki.debug/files/AnkiDroid42/collection.media/sound drone.ogg: open failed: ENOENT (No such file or directory)
at libcore.io.IoBridge.open(IoBridge.java:574)
at java.io.FileInputStream.<init>(FileInputStream.java:160)
at com.ichi2.libanki.Media.mediaChangesZip(Media.kt:784)
at com.ichi2.libanki.sync.MediaSyncer.sync(MediaSyncer.kt:172)
at com.ichi2.async.Connection.doInBackgroundSync(Connection.kt:379)
at com.ichi2.async.Connection.doOneInBackground(Connection.kt:127)
at com.ichi2.async.Connection.doInBackground(Connection.kt:121)
at com.ichi2.async.Connection.doInBackground(Connection.kt:51)
```
csum null error due to improper check introduced in …

fixed NPE for csum by fixing the check

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.kt

It was defined twice in the same way. 
Somehow I pushed it on ankidroid/main by accident. Since I can't delete commit, I instead force pushed a revert on top of it, so it can be reviewed properly
Related to #12280 , since this function is something I assume we'd need for fab

NF: refactor "animationEnabled"

---

lint-rules/build.gradle

If the developer doesn't have JDK 11 set on the computer the compilation in lint-rules will fail with the mentioned no toolchain found error. It should download missing toolchains but I think in newer versions of Gradle we have to setup this manually(I haven't tested it however). This PR should fix this by manually setting the compatibility to JVM 11. Later, when issues related to jvmToolchain are fixed, we can look again into using this property.
Note that, for running gradle tasks from the terminal, I had to configure the JavaCompile as well because it would fail with an error related to compileJava and compileKotlin tasks using different jvm targets(for example JDK 17 being installed(and compileJava using it) and the kotlin compile task was configured against 11).
Fixes #13414 
Fixes …

Set kotlin related task in lint-rules module to use JVM 11

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.kt
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt

The CardBrowser based its list of decks used for changing a card's deck on the DeckSpinnerSelection.dropDownDecks property. That property isn't updated unless the deck selection dialog is used(or the activity recreated) so CardBrowser wasn't seeing immediately the changes to the available decks. The fix connects CardBrowser to the method that DeckSpinnerSelection actually uses to update its list of decks.
Fixes #13391 
Ran the tests and also manually verified the expected behavior.

Fix newly created deck not showing when changing card's deck in CardBrowser

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/VideoPlayer.kt
AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardHtml.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt
AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerSoundRenderTest.kt

Summary: splits out sound playing + sound listing of sound files.
Splits out video
* Remove logic for only creating a list containing `QUESTION_AND_ANSWER` if requested
* Instead, concat the two QUESTION and ANSWER lists when requested
* Split out 'playing' code into 'SoundPlayer'
* Split out video-related code into `VideoPlayer`
* remove 'videoView' parameter
* remove 'mBaseUrl' parameter
* define `SoundPlayer` interface + delegate to parameter
* remove legacy "tts" code
* extract `playAnotherSound()`
* cleanup VideoPlayer `null` path handling
* remove videoPlayer.onStop
* SingleSoundSide: ensures the wrong parameter can't be provided, cleaning up code paths
I was going to build on this for scoped storage, but consider this to be optional and only if it feels like there's an improvement …

refactor: Sound/Video

---

AnkiDroid/src/main/java/com/ichi2/anki/reviewer/AnswerTimer.kt

This fixes AnswerTimer not showing during reviews regardless of deck options.
Fixes #13456
Since #13029 `android:textColor` is a `selector`. The code in `AnswerTimer.resetTimerUI()` was not ready for that, and it resulted in the AnswerTimer being invisible regardless of settings. This PR sets the color correctly and updates adjacent code for consistency.
Trivially, by reviewing any deck.

Fix AnswerTimer.resetTimerUI() not seting color correctly

---

AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt
AnkiDroid/src/main/res/values/01-core.xml

Changed the toast message on Android >= R .
Fixes #13462 
Created a string and changed the toast message.

fix: Changed startup permission toast message in Android >= R

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt
AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt
AnkiDroid/src/main/res/layout/alert_dialog_checkbox.xml

If a user doesn't migrate:
* Storage is slow
* They permanently lose access to their collection on uninstall
If the user does migrate:
* Storage is fast
* Data is deleted on uninstall (unless a user opts out)
We have a subset of users who are safe to migrate (syncing)
and want them to migrate ASAP so they get the speed benefits
while syncing
Display the dialog from `showDialogThatOffersToMigrateStorage`
Add a 'do not show again' checkbox if the user dismisses the dialog twice
Related: #5304
Same usage as with `BackupPromptDialog`: bcb9d69bdde1d4b4682855f53a82c81d0e9ac975
* Two improvements to `AlertDialogFacade`, these can be extracted if this review is likely to take long
* this will appear the second time an upgraded, syncing user views the DeckPicker. Is this too soon?
API 29 emulator, …

Add automatic reminder to migrate storage (if migration is available)

---

AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.kt

Replaces usages of MaterialDialog with AlertDialog in Toolbar.kt

Changed Material Dialog with Alert Dialog for Toolbar.kt

---

.idea/dictionaries/android.xml
AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DialogHandler.kt
AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
AnkiDroid/src/main/java/com/ichi2/async/AsyncOperation.kt
AnkiDroid/src/main/res/values/02-strings.xml

If a user is going to perform a migration, they should be fully synced to ensure no data loss. We can't easily know if they're fully synced on the media side of things, so perform a sync and see.
When the user has performed a media sync, migrate.
The sync may complete while the user has the app closed.
In this case, `withProgress` may not execute (no window), so we conservatively pause the start of the migration until the AnkiDroid window has called `onResume`.
Also handle the case where the media sync cannot occur (via `AlertDialog` + migrate anyway). 
- Related: #5304
- Fixes #13382
Define an `AsyncOperation`: similar to an `AsyncDialogFragment`, but not necessarily with a dialog
Define a `MigrateStorageAfterSync`
It passes this into `sync`, which calls it at the end of the operation …

Storage Migration: Sync before starting storage migration

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.kt
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/Import.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportFileSelectionFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ScopedStorageService.kt
AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
AnkiDroid/src/main/res/values/01-core.xml
AnkiDroid/src/main/res/values/constants.xml

If a user uninstalls and selects 'keep data', the user retains access to their preferences, so we retain `deckPath` and can use it to determine if their collection is no longer accessible
If a user uninstalls AnkiDroid, `preserveLegacyExternalStorage` no longer works.
This means they have a deckPath of `/storage/emulated/0/AnkiDroid` which can no longer be accessed.
Their data exists, but cannot be accessed unless:
* They restore from AnkiWeb
* They have a colpkg
* They manually copy the folder over
* They install a non-Google-Play copy
Provide a dialog with options:
* Restore from AnkiWeb
* Restore folder access
(https://github.com/ankidroid/Anki-Android/wiki/Full-Storage-Access)
* Restore backup (⚠️ Hidden - Not Implemented)
* Get Help (Link to: Google Group)
* Delete collection and …

Scoped Storage: Handle storage being revoked

---

AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
AnkiDroid/src/main/res/values/10-preferences.xml

Used shared pref to recreate the deck picker activity as soon as the collections are cleared using app settings
This Activity actually needed a recreation on clearing the collection as if not it was frozen until we visit the other activity and come back to it. Refresh or InvalidateOptionMenu would not work here 
Fixes #13477
Used Shared Prefs
Tested on Oneplus Nord CE

recreate DeckPicker activity on Deleting collection from app settings

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/AboutFragment.kt
AnkiDroid/src/main/res/values/02-strings.xml

Anki Desktop uses the following word order pattern on some toast messages, for example, `Card suspended.`,
1. Subject
2. omission of be Verb
3. Past participle
but it isn't used on some strings of AnkiDroid, for example, `Suspended card`.
It is probably appropriate to use Anki Desktop's word order pattern on AnkiDroid as well.
n/a
Change the strings on 02-strings.xml
on my physical device
n/a

Change the word order of some of the toast messages

---

AnkiDroid/build.gradle

A default build ('play') is not allowed `MANAGE_EXTERNAL_STORAGE`
We want a build with this permission so we can distribute it.
`amazon` removes the camera permission, so it is not appropriate
So add a new flavor: 'full' which has BOTH camera & storage permissions.
This may optionally be used by developers. TBC if we want this as the default as it's not representative of a real user experience.
- Related: #13431 
- needs a follow up to `release.sh` and `parallel-package-release.sh`
- needs an update to the F-Droid release script to use 'full' as the default
* add a 'full' dimension
API 33 Emulator

build: 'full' build with no manifest restrictions

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt

As @oakkitten noted, the name is misleading, since the function does not handle anything.

NF: Rename handleStoragePermissionsCheckForCheckMedia

---

tools/parallel-package-release.sh
tools/release.sh

Fixes #13431
Change the assemble type on the script
Runned `./gradlew assembleFullRelease` to check if the command was okay. Didn't run the script because of the credentials.

Use "full" flavor on parallel builds

---

tools/release.sh

Temporarily disable the attempt to publish an alpha to google - now that we are API30+ google would probably accept it, but we would like at least one more github-only alpha before that happens
Simply commenting out the google play store related lines. This will be (should be?) simple to revert and has `API30` near it in comments as well, for future adventurers in case I meet an untimely demise and don't handle it myself ;-)
It has not. Running the workflow will test it. There could be problems. I stand ready with mop and bucket to janitor the problems away
I have learned nothing from this PR. Sometimes PRs are like that.

temporarily disable publish of alpha to google

---

AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt
AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt

Finishing the activity is bad UX and unnecessary
Fixes #13463
SDK 33 emulator
https://user-images.githubusercontent.com/69634269/228090454-ebf8ee92-f096-4dc6-9c59-6fb0801df4d8.mp4
Couldn't get to use https://developer.android.com/reference/androidx/activity/result/contract/ActivityResultContracts.RequestPermission

Don't finish activity after requesting all files access permission

---

AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.kt
AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
AnkiDroid/src/test/java/com/ichi2/anki/InitialActivityTest.kt

As noted in
https://github.com/ankidroid/Anki-Android/pull/13261/files#r1133165143 , "DeleteOnUninstall", while true, is not a description of a kind of folder. Renaming it make it easier to grasp.

NF: rename DeleteOnUninstall

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/BackendUndo.kt
AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt

The snackbar that show when a card becomes a leech would overlap with the answer buttons.
This PR fixes the issue by showing the snackbar above the answer buttons.
Fixes #12606
Use a variation of the approach suggested by @oakkitten in the issue.
`showSnackbar` is an extension function, so we can't override it, but we can make an interface that an Activity can implement to specify default configuration for a snackbar and `showSnackbar` can take this configuration into account.
Instead of specifying an anchor view as originally suggested, I've opted to use a `SnackbarBuilder` instead so that we can have more flexibility without really increasing the complexity.
I've also removed code for explicitly setting the snackbar above the answer buttons, since a regular `showSnackbar` will do the …

Fix leech snackbar overlapping answer buttons

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt

`finishActivityWithFade(this)` is written twice in CardBrowser.kt. I don't think writing twice is worth it 
Tested on Emulator working fine

finishActivityWithFade(this) is written twice in CardBrowser.kt

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt

Fix Android Studio code inspection warnings.
Related to #13282 
Android Studio code inspection suggested the following functions and fields in `DeckSelectionDialog.kt` could be made private.
Ran unit tests locally.

Fix IDE Warnings: Make eligible functions and fields private

---

tools/release.sh

this should help storage migration testing as a play build will now be available despite a general policy of "full builds on github releases"
This is related to a great comment from @Arthur-Milchior here https://github.com/ankidroid/Anki-Android/pull/13514#issuecomment-1487792345
- generate universal APKs for *all* flavors
- split the APK copy step into ABI and FLAVOR chunks so we copy universals for all flavors
- split the APK github release push into ABI and FLAVOR chunks so we upload universals for all flavors
- updated related comments / release copy
I'm going to test the build but not the uploads locally but there is really no way to test this well other than to run the script and burn an alpha version number 🙈 
🤷 

release: include universal build for each flavor in github releases

---

AnkiDroid/src/main/assets/scripts/card.js
AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt

Adds the rest of the declared colors to the js `ankiToggleFlag()` method and makes AbstractFlashcardViewer to use them.
Fixes #13526 
Ran the tests, used the target js function in a card.

Make all colors available to the JS API consumers

---

build.gradle

Does what it says on the tin - bumps the backend dependency, which itself has as its only change that it ingests the 2.1.61 anki version from upstream
Related: https://github.com/ankidroid/Anki-Android-Backend/pull/280

fix(deps): bump underlying backend to use anki 2.1.61 from upstream

---

AnkiDroid/jacoco.gradle

Jacoco 0.8.9 is out, let's use it.
Passes full suite of tests locally

build(deps): bump jacoco to 0.8.9

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt

Replaced toast with Snackbar in NoteEditor
Related to #13411 
Tested on Realme 6

Replaced toast with Snackbar in NoteEditor.kt

---

tools/release.sh

Unfortunately the release process just broke and I was able to reproduce it locally (out of memory)
https://github.com/ankidroid/Anki-Android/actions/runs/4633209039/jobs/8198171270#step:10:230
> ERROR:R8: java.lang.OutOfMemoryError: Java heap space
I was also able to get it to work locally if I built one flavor at a time, so I'm going to go with that
In the process I added a change that will hopefully burn fewer unreleased version numbers in the future and fixed a copy-pasta error in my last work on the release script
Local execution of the related commands from `./tools/release.sh`
Java+Kotlin is obscenely RAM hungry. Something to continuously learn.

Fix release process for full flavor builds

---

AnkiDroid/src/main/AndroidManifest.xml

"Third Party Apps" says we don't have a browser
Cause
https://github.com/ankidroid/Anki-Android/blob/490493792b45f73ecaa7267a5fa1548e1b36fab6/AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt#L75-L77
Broken in 56a195bf466c57e5a848e6ba8796a529816d5cab
- Fixes #13567
- Fixes #13571
State that we want the ability to query apps which handle HTTPS URLs
API 30: `queryIntentActivitiesCompat` requires `<queries>` to stop app enumeration.
https://developer.android.com/about/versions/11/privacy/package-visibility
https://developer.android.com/training/package-visibility/use-cases#open-urls

fix: Can't open "Third Party Apps"

---

AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt

1. When the user was logged in and switched to the horizontal mode they could not access the Logout button 
2. The email and password section had a yellow tint that came when the user clicked autofill (autofill in our case is not necessary)
Fixes #13549
I have made the AnkiDroid logo for the logged-in screen consistent to that to login screen i.e. the AnkiDroid logo is not visible in horizontal mode
And the marked the edit text fields as not important for autofill 

fixes the horizontal logged in UI

---

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DiscardChangesDialog.kt
AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt

Based on https://github.com/ankidroid/Anki-Android/issues/13315, we would like to replace all instances of `MaterialDialog` with `AlertDialog`.
I started with `CardTemplateEditor` and realize that that would mean changing `DiscardChangesDialog` which was also used in 2 other locations (`NoteEditor` and `CardTemplateBrowserAppearanceEditor`). I made the change, along with some Robolectric tests (`CardTemplateEditorTest`) that required some changes in how we access underlying Robolectric `ShadowDialog`s.
Apologies that this PR became a bit involved, but hopefully should read fairly straightforwardly.
Fixes https://github.com/ankidroid/Anki-Android/issues/13315
I started with a simple replace, and then modified and cleaned up things as I went along. 
* There was a situation where a method …

Replace MaterialDialog with AlertDialog

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SimpleMessageDialog.kt
AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt
AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt

https://github.com/ankidroid/Anki-Android/issues/13315
- Replace MaterialDialog with AlertDialog
- Create helper for AlertDialog test in RobolectricTest.kt and adjust the existing test
Tested on Emulator API 33 
**Before** 
**After**

Replace MaterialDialog with AlertDialog in SimpleMessageDialog.kt

---

AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
AnkiDroid/src/main/res/values/02-strings.xml

Changed title and action names of cancel share deck download dialog
Fixes #13386
Changed title and action names of cancel share deck download dialog

fix: Changed title and action names of cancel share deck download dialog

---

tools/storage/set_scoped_storage.sh

Otherwise, bash is not used. Instead, I get
> ./tools/storage/set_scoped_storage.sh: 5: Syntax error: "(" unexpected
because `function` is not basic shell I guess.

Use shebang in set_scoped_storage

---

tools/storage/set_scoped_storage.sh
tools/translation-rates.sh

On my desktop, running `./tools/storage/set_scopde_storage.sh` led to
> Alienware% ./tools/storage/set_scoped_storage.sh
> First argument missing.
> \nPossible arguments:
> limited\t\tEquivalent to a fresh install. /AnkiDroid/ is inaccessible
> full\t\tEquivalent to an upgrade from targetSdkVersion 29 to 30. /AnkiDroid/ is accessible\n
Adding `-e` ensures the characters are printed as expected.

ensure scripts prints escaped character

---

AnkiDroid/jacoco.gradle

has caused spurious errors from other runners as well and from individual contributors. Feels like the global maven central CDN is not in sync but that is also not in our control, so revert
https://github.com/ankidroid/Anki-Android/actions/workflows/tests_unit.yml?query=is%3Afailure
Investigate as much as I can locally, I never 404 for the pom.xml from repo1.maven.org but if the runner 404s sometimes and contributors do, there is not much I can do about the artifact resolution.
CI will have to pass.
The internet is not reliable.

revert jacoco from 0.8.9 to 0.8.8 - macOS runner cannot find it

---

AnkiDroid/src/main/java/com/ichi2/anki/IntroductionActivity.kt
AnkiDroid/src/main/res/layout-land/introduction_layout.xml
AnkiDroid/src/main/res/layout/introduction_layout.xml

This PR fixes two issues for IntroductionActivity:
- a dialog which was not setup correctly(a placeholder string wasn't properly used) 
- it fixes the landscape UI to not have it mostly broken on bigger phones/tablets in landscape(see images below)
**UI before the changes in this PR:**
- Phones
- Foldables, when unfolded(when folded they are a phone)
width="520px" height="640px" />
width="640px" height="520px" />
- Tablet
width="480px" height="720px" />
width="720px" height="480px" />
**UI after the changes in this PR:**
- Phones
width="640px" height="320px" />
- Foldables, when unfolded(folded they are a phone)
- Tablets
Ran the application on various types of devices.

Fix some issues related to IntroductionActivity

---

AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt

I am allowing the user to only see the search text for the deck and properties they selected which I think is the right thing to do as the text if altered and not matched with the required one causes an issue as I said on Discord 
There is another but that would require to creation of two new fields one for the deck and one for the property, deck field would be fine but the property field would be a mess as there are lists and limits or even text which are accepted as properties.
Fixes #13581
Tested on oneplus nord ce

Crash fix due to `EditTextPreference` search field in CustomStudyDeck

---

AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
AnkiDroid/src/test/java/com/ichi2/anki/InitialActivityTest.kt

selectAnkiDroidFolder() didn't handle the case of the user keeping the legacy storage permissions on an Android 11+ device
Fixes #13598 
Check if the user has the legacy storage permissions on selectAnkiDroidFolder(). I'd refactor the method a little bit more, but got some problems fixing the tests if I refactored, perhaps because of a problem between mockkito and JUnit, and didn't think that it was worth the time
On a SDK 33 emulator
1. Build and install Ankidroid 2.15.6 (ensure that its applicationId is com.ichi2.anki.debug if you are using a debug version, or use com.ichi2.anki as your applicationId on the 3rd step)
2. Open the app and give the storage permission
3. Build and install this PR (`play` flavor)
4. Tested if the access denied errors persist:
- Start a migration
- Add a …

Fix "Access denied" errors after upgrading from 2.15.6

---

.github/workflows/tests_emulator.yml
AnkiDroid/build.gradle
api/build.gradle

Standard SDK update. 
Ran unit tests, ran lint. Using CI for emulator tests.
`OldTargetApi` is still valid - disabled in `lint-release.xml`

build: update `targetSdkVersion` to 31

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt

Added Ctrl+F shortcut to open search view when an external keyboard is attached to the device specified in the case of tablets.
- Fixes #13566.
I used the function `fun onKeyDown(keyCode: Int, event: KeyEvent)`.
I have tested it on my physical device for searching the card and it was working fine. On pressing Ctrl+F the `mSearchItem?.expandActionView()` is triggered and then we can search for the cards. 
https://developer.android.com/develop/ui/views/touch-and-input/keyboard-input/commands

Find Key Shortcut for Card Browser

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ScopedStorageService.kt
AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt

- Fixes #13612
- Fixes #13620
We were using the condition `allFileAccessPermissionGranted` 
But this returns false before API 30  Instead define and use `collectionWillBeMadeInaccessibleAfterUninstall` which takes this condition into account  
* Unit Tests
* Tested on API 27 emulator

Fix: storage migration shown on < API 30 & Amazon Builds

---

AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveFile.kt
AnkiDroid/src/main/java/com/ichi2/utils/FileUtil.kt
AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveFileTest.kt
AnkiDroid/src/test/java/com/ichi2/utils/FileUtilTest.kt

I added a method to detect prefix of files.
As I found the code quite confusing to read, I rewrote it to split in three cases:
* source does not exists
* destination exists
* move can occur as expected
Fixed: #13170

Move file consider destinations which are prefix of the source

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt
AnkiDroid/src/main/res/drawable/ic_backup_restore.xml

(Use a not-cloud design for the icon of the backup suggestion dialog box if the user doesn't use the sync feature)
The current icon with an upward arrow in a cloud alludes uploading data to cloud (AnkiWeb). Its design is misleading for encouraging backup to those who don't use the sync feature.
Left: logged in state /  Right: logged out state
Fixes #13645
- Add a new icon. Its resource is [the "File Copy" icon on Google Fonts](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Afile_copy%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048).
- Replace the current icon with it if the user hasn't logged in to their AnkiWeb account.
- Checked on a physical device (Android 11) with logged out state
Left: After change  /  Right: Before change
Left: After change  /  Right: Before …

Use a not-cloud icon for suggesting backup if no sync

---

AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ScopedStorageService.kt

Fixes issues I introduced: 
- 9fdfbe0b12e343738208a4df0763896aafeb53bd - 
- moved from a 'permission' check to a 'file' check. This should have had lower priority than reporting the migration was in progress
- Implementation of `collectionWillBeMadeInaccessibleAfterUninstall` didn't match spec
API 30 emulator: Storage migration now works
Regression tests would have caught these

fix: Storage Migration not being offered

---

AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.kt
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ScopedStorageService.kt
AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt
AnkiDroid/src/main/java/com/ichi2/preferences/PreferenceExtensions.kt
AnkiDroid/src/test/java/com/ichi2/preferences/PreferenceExtensionsTest.kt

After restarting the phone, Storage Migration Progress should be preserved
Fixes #13634
* Save a variable to Shared Preferences
* Restore & use it while converting
* API 30 emulator, with commit rebased on https://github.com/ankidroid/Anki-Android/pull/13657
* Loaded AnKing. Started a migration. Turned off the emulated phone. Progress (total + files copied) were restored when emulated phone was turned on

fix: MigrationService: Progress is incorrect after service restart

---

AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt

Deprecate MaterialDialog and use AlertDialog instead https://github.com/ankidroid/Anki-Android/issues/13315
Replaced MaterialDialog with AlertDialog in the function showCancelConfirmationDialog()

Replace MaterialDialog with AlertDialog in SharedDecksDownloadFragment class

---

AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
AnkiDroid/src/test/java/com/ichi2/anki/InitialActivityTest.kt

Scenario:
* The user can request 'MANAGE_EXTERNAL_STORAGE' (non-Play build)
* The collection path is `/storage/emulated/0/AnkiDroid`
* The user is on API 30
* The user reinstalled & kept data
Expected Result:
* We require 'MANAGE_EXTERNAL_STORAGE' to continue to access data
Previously:
1. We requested READ/WRITE_EXTERNAL_STORAGE
2. When accepted: 'StorageAccessException': User no longer had access to legacy storage.
This splits `hasLegacyStoragePermissions` into two concepts:
1. Do we have a legacy collection
2. Does Android allow us to use legacy folders
Previously we only checked for (1) whereas we needed both
Unit tests + on API 30 emulators (`[amazon/Play]Debug` split)
This builds on PR #13630: (ce0b0dc9ff6cfad16060e90e5e2f7316a8d478b0). Designed to fix …

Fix: `StorageAccessException` shown after reinstall (API 30, non-Play Store build)

---

AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.kt

`getDefaultAnkiDroidDirectory` caused recursion. This recursion is normally gated on the existence of PREF_COLLECTION_PATH But we didn't take this into account when in INSTRUMENTATION_TEST mode
- Fixes #13644
Only get the AnkiDroid directory when the default doesn't exist
Tested by rebasing onto d88ad6251c7358359e0dcca36c10f08ff543c4db and running tests on `playDebug` (API 32 emulator)
⚠️ Tests now fail due to an alternate setup issue (I suspect this is due to the emulator lacking permissions to access storage).
```
java.lang.NullPointerException
at com.ichi2.anki.TestUtils.isScreenSw600dp(TestUtils.kt:78)
at com.ichi2.anki.DeckPickerTest.checkIfStudyOptionsIsDisplayedOnTablet(DeckPickerTest.kt:91)
```
This is fixed incidentally  by …

fix: StackOverflowException in androidTest

---

.github/workflows/tests_emulator.yml

API 31 was unstable in CI.
Related: #13695

build: revert emulator to API 30

---

AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ScopedStorageService.kt

Fixed warnings in ScopedStorageService.kt.
issue: #13282
Fix AndroidStudio warnings #13282
Fixes part of #13282, specifically warnings in ScopedStorageService.kt
Removes the warnings
Tested on physical device (Pixel 5)

Fix Warnings in ScopedStorageService.kt

---

AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt

A number of crash reports were received.
- Fixes #13686
- Fixes #13688
- Fixes #13690
- Related #13689
Two issues:
* 5b0a690790c75c6b32a6250c60beafb3733efbbd caused an issue with the dialog button colors being invisible
* Revert and look for a solution
* We had a validation step, but we continued processing the file on a failed validation  
Revert was tested visually, buttons appeared
* Tested with a valid download, still passed

Fix issues with 'Shared Deck Download'

---

AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt

I've never used the information, and it makes navigation of the crash log more difficult than it should be
I'll face the consequences if I'm incorrect here.

chore: remove 'MEDIA_CODEC_LIST' from crash reports

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
AnkiDroid/src/main/java/com/ichi2/libanki/utils/NotInLibAnki.kt

A user saw 'Failed to load deck '<DeckId'> when selecting a deck.
If the user was using the V1 scheduler then `schedVer` is not set
`get_config_int` threw an exception if this was the case.
- Fixes #13003
- Fixes #13692
* Default to V1 if `schedVer` is not found
I was provided with a test collection. 
It now shows:
The issue and fix was obvious once config was obtained (posted to #13003)
I love 'Past David'
https://github.com/ankidroid/Anki-Android/blob/a06e727f6094541b763e2dc18a300edb3e17fd26/AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedUpgradeTest.kt#L49-L51

fix: "Failed to load deck '<DeckId>' error when selecting any deck if on SchedV1

---

AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt

IntentHandler didn't set a theme, so it used the default one set on the manifest, which is translucent and doesn't follow AppCompat
Fixes #13689
Fixes #13704 
Simply set the theme to the current app theme
33 emulator:
https://user-images.githubusercontent.com/69634269/234257945-6675f492-2df7-4f62-ae88-922c6cbd4032.mp4
https://user-images.githubusercontent.com/69634269/234257961-12b3c9ae-b61f-4729-ac0a-1d97effee5f5.mp4

Fix IntentHandler not having a theme

---

AnkiDroid/src/main/res/layout/preferences.xml

In order to enable snackbar animations
Supersedes and closes #13701
Add a CoordinatorLayout to the preferences screen layout
Settings > About > Copy debug info > See if the snackbar is dismissable

fix: Make the settings screen use a Coordinator layout

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt

1. `full` build: Previously imports via clicking a deck in 'Files' failed with `intent_handler_failed_no_storage_permission`: "Missing required storage permission. Please grant storage permission then retry your action"
- Fixes (probably) #13699
-  Notified `criticalAY` of this. Almost certain that it'll be fixed
1. Define & use isExternalStorageManagerCompat
* A deck can be tapped on from 'files' and is imported
* ⚠️ The Dialog on tapping an `.anki2` looks funky
* Logged as #13704
We need more testing + videos from new contributors testing their changes

fix: storage permission checks on 'full' builds & broken Dialog

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.kt
AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/InstrumentedTest.kt
AnkiDroid/src/androidTest/java/com/ichi2/anki/testutil/GrantPermissions.kt
AnkiDroid/src/androidTest/java/com/ichi2/anki/utils/GrantAllFilesAccessRule.kt

We previously had 'unknown' failures
Fixes #13677
Throw an 'obvious' exception instead
My API 32 emulator now fails tests with 'obvious' errors (`amazonDebug`), it passes with `playDebug`
The code to grant 'All Files' access in instrumented tests is linked, but needs some quality work (removing a dependency + looking into deprecated methods)

docs: Android Tests: fail if 'All files' is needed and not granted

---

AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.kt

Fixes an error when exporting a deck
Fixes #13717
Prepared Statements
Tested on API 30 Emulator. 
* Exported
* Deleted Deck
* Imported
* Card was imported

fix: crash if exporting deck name containing "'"

---

AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.kt
AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/ScopedStorageAndroidTest.kt

The documentation on `getExternalFilesDirs` states:
> Some individual paths may be {@code null} if that
> shared storage is not currently available
A crash was reported
- Fixes #13705
* Remove the null elements from the list
Untested (sans unit tests). Fix was obvious
Android APIs need better nullability annotations.

fix: NullPointerException on `isLegacyStorage()` call

---

AnkiDroid/build.gradle

Fixes #13583
- Build a parallel build
- Settings > Sync > AnkiWeb Account
- see if is able to login
This is actually my fault. The "applicationIdSuffix" command adds an initial dot to the suffix, but its value keeps without it.

fix: not being open to open the login screen from settings on a parallel build

---

AnkiDroid/build.gradle
AnkiDroid/src/main/java/com/ichi2/libanki/importer/AnkiPackageImporter.kt

Deck imports crashed on low SDK versions
- Fixes #13729
jackson-databind incompatibility: Downgrade dependency
* Tested on SDK 21 and SDK 24. No longer crashes
https://github.com/FasterXML/jackson-databind#compatibility
> Android
> 2.13: Android SDK 24+
> 2.14: Android SDK 26+

fix: crash importing decks on SDK 24 and below

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt

`IndexOutOfBoundsException` when moving from 'Basic (optional reversed card)' to 'Basic (and reversed card)' after setting 'Toggle Sticky' for all fields
- Fixes #13719 
This is due to 'toggle sticky' being present on this additional field
Quick fix to stop a crash. Needs more thought and testing
Tested manually on API 31 emulator. No longer crashes
Need more automated testing

fix: moving to note type with fewer sticky fields

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsList.kt

Use `toList` first on `mAllTags` then sort it to avoid crashing then use clear and add the tags to the collection
Fixes #12471
Tested on API24/31/27

Use `toList` first on `mAllTags`  for collections tag

---

AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt

The current code schedules a Runnable to update the download progress and because it didn't properly handle the fragment's lifecycle it kept a reference to the old fragment when sent to the background. This PR also increases the DownloadManager query rate from 100ms to each second.
Fixes #13687 
Ran the tests and then manually checked if the exception still occurs.z

Fix SharedDecksDownloadFragment being leaked when app is sent to background

---

AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/FileUtils.kt

Uses a number of methods which are documented to maybe return `null`, and we have a crash here saying `java.lang.NullPointerException: it must not be null`
- Fixes #13734
⚠️ Untested
* Probably the first user that we've lost due to the storage migration, given the comment in ACRA :/

fix: nullability issues in FileUtils

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.kt

Added A dismiss() which closes DeckPickerMenuOption..
Fixes #13740
Tested on Redmi note 8 pro..
https://user-images.githubusercontent.com/91174350/234815622-f9bb84d4-79c4-4c4f-8a91-ec3f131dcbdb.mp4

DeckPickerMenuOption Bug fix

---

AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt

> TODO BEFORE-RELEASE! Between this call and the subsequent migration the contents of the folder can change. This can lead to inconsistent readings in the UI.
Simply coerce transferred size into 0 .. estimated transfer size. Add a note about this to the doc. Plus a few more notes. The result is that the progress might appear stuck near the end. Alternatively we could be updating the total size, or only coercing the ratio into 0f .. 1f, or not doing anything.
**Note**: if extra media files are added to the source while migration is ongoing, the migration will fail with `com.ichi2.anki.servicelayer.scopedstorage.migrateuserdata.MigrateUserData.DirectoryNotEmptyException` ("directory was not empty").

Resolve TODO regarding migration transferring more bytes than initially calculated

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/res/menu/deck_picker.xml
AnkiDroid/src/main/res/values/02-strings.xml

> TODO: add a title for this action
> TODO BEFORE-RELEASE Add tooltip text to the image button. Menu items normally have titles that are shown on long tap. As this menu item delegates the UI to the action view, it is up to that to handle presses. When we decide on the text, use `TooltipCompat.setTooltipText` on the button to set it.
Supersedes #13531 
Do what the TODOs say

Resolve TODOs regarding ongoing migration button title

---

AnkiDroid/build.gradle

`package="com.ichi2.anki" found in source AndroidManifest.xml: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/build/intermediates/merged_manifest/playRelease/AndroidManifest.xml. Setting the namespace via a source AndroidManifest.xml's package attribute is deprecated`
Fixes #13682 
Using the namespace code snippet as suggested by google [here](https://developer.android.com/build/configure-app-module#set-namespace)

Setting the namespace via a source

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt

There is no vertical padding in some CustomStudyDialog
Fixes #13763
Set noVerticalPadding to false

Set noVerticalPadding to false in CustomStudyDialog.kt

---

AnkiDroid/src/main/java/com/ichi2/anki/preferences/PreferencesSearchView.kt

SearchBox failed to appear when clicked for atleast second time. It's become inconvenient for the user to click two times on search icon
Fixes #13771
set isIconified to false in onActionViewExpanded()
Tested on Physical Device (Realme 9)
https://user-images.githubusercontent.com/65113071/235350907-ec4d032c-efbb-41ac-b242-60ea8b323843.mp4

SearchBox is appearing when clicking on the search icon

---

AnkiDroid/src/main/res/xml/cram_deck_options.xml

The keyboard is not showing automatically
Fixes #13775
Replaced EditTextPreference with AutoFocusEditTextPreference
https://user-images.githubusercontent.com/65113071/235426272-75ae47ff-e142-45cb-888a-c45737ec9829.mp4

Used AutoFocusEditTextPreference instead of EditTextPreference

---

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.kt

this was causing noise in the logs which may be a source of confusion in our pre-launch reports on play store
Analyze logcat from play store auto-test runs pre-launch in combination with stack trace and captured video of the test session
It appears there is no problem with the app continuing and calling code for `getDummyCard` has to handle null returns anyway, so reducing log noise:
- should be okay technically / from correctness perspective
- may fix pre-launch report spurious errors flagged for IndexOutOfBoundsException
The exception was logged but caused no problems, it was tested in the auto-test lab and I have the logcat + video of session where the exception was thrown and it was fine
We need to always enforce correct log levels, apparently we are sometimes lax
- error is only for …

style: log template preview dummy card error as d not e

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt

A map(mToggleStickyText) was being iterated on and changed at the same time which trigger the ConcurrentModificationException. I made a copy of the original map and used that to iterate over the content.
Fixes #13784 
Ran the tests and then manually verified the scenario where I was previously able to replicate the issue.

Fix ConcurrentModificationException in NoteEditor.saveToggleStickyMap()

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/AsyncDialogFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportCompleteDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt

- Multiple crashes, see: https://github.com/ankidroid/Anki-Android/issues/13795
- Fixes #13795
- Reopens #12448
* Automated revert of https://github.com/ankidroid/Anki-Android/commit/385afba7a5242dd3195554845a1e9e764697cd7c
* Then manual revert of https://github.com/ankidroid/Anki-Android/commit/6ea36860a8e9fddadff0bf484746248fd843eb53
⚠️ Untested (besides unit tests)
We need more tests here

manual revert: "Use fragments resources on AsyncDialogFragment"

---

AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/FileUtils.kt
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MigrateEssentialFiles.kt

* The error message: `files not equal` was not sufficient
* I can't reproduce the issue, but we can do better with diagnostics
- Related: #13807 
* Take `org.apache.commons.io.FileUtils.contentEquals`, vendor and modify the code to improve the error message
⚠️ Untested

Improve Diagnostics for issue 13807 (files not equal: `.nomedia`)

---

AnkiDroid/src/main/AndroidManifest.xml

Custom text selection actions from 3rd party apps stopped appearing in alpha95 but worked fine in alpha94 and below.
This is because in alpha95 we updated the target API version to 30 (Android 11).
Android 11 introduced changes to the package visibility behavior and made it so that 3rd party apps by default do not show up for many intent queries, including the text selection one.
I know that we target API 31 now, but the package visibility changes from 30 should still be there.
Fixes #13530
Add the `PROCESS_TEXT` intent action to the `<queries>` element in the manifest as suggested in the Android documentation that I link to below in the Learnings section, so that 3rd party apps are not filtered away for the text selection action.
Please describe the tests that you ran to verify your …

Re-enable support for custom text selection actions

---

AnkiDroid/src/main/java/com/ichi2/preferences/NumberRangePreferenceCompat.kt

It's become inconvenient for the user to relocate the cursor to end every time
Fixes #13799
called `setFocusAndOpenKeyboard()` function which is already there in AndroidUiUtils
https://user-images.githubusercontent.com/65113071/236374491-d1ae3dce-4821-4abd-952c-687f86d5c8b8.mp4

Moved cursor to end in NumberRangePreferenceCompat

---

AnkiDroid/src/main/java/com/ichi2/anki/LoginActivity.kt
AnkiDroid/src/test/java/com/ichi2/anki/LoginActivityTest.kt

This is my first contribution, so I'm looking forward to getting some feedback before getting deeper into the codebase!
This is a clone of https://github.com/ankidroid/Anki-Android/pull/13759 (see also comment history there) because I wanted to move these changes off of my main branch.
Tests flow as follows:
* mock isLoggedIn() (we have mockk mockStatic I think) to return true
* start LoginActivity
* assert that the Lifecycle state of LoginActivity is finished/destroyed(as there's no reason to show this activity when the user is logged in). Also test the Activity result codes.

Resolve NeedsTests annotations in LoginActivity.kt

---

build.gradle

lint was updated in 8e4b6d17a5b2765ce2f27f35be86ef6360a54dfd
But this stopped lint checks running via 'gradlew'
https://github.com/ankidroid/Anki-Android/issues/13786#issuecomment-1534189784
Fixes #13786
reverts lint to `30.4.2`
* Deleted a copyright header in a test. Lint now fails (previously: passed)
tested with `/gradlew lintFullRelease`
Many thanks to lukstbit for the investigation https://github.com/ankidroid/Anki-Android/issues/13786#issuecomment-1534189784

fix: make lint run in CI/gradle

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/res/values/02-strings.xml

Adding a remember settings button in the metered connection dialog
Fixes #13785
tested on one plus nord ce

Added remember settings to your connection is metered dialog

---

AnkiDroid/build.gradle

This issue was introduced due to #13198
Fixes #13818
Fixes #13375 
Changed `com.google.android.material:material` to 1.7.0
Physical Device
https://github.com/ankidroid/Anki-Android/assets/65113071/81b9c3b2-fb72-4dc4-8498-41a6896ebe95

CardBrowser is not getting bold

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ScopedStorageService.kt

Fixes a TODO I left in the code. Feels over-documented for an ancillary feature.
Fixes #13663 
This PR skips the 'Are you sure?' warning to dismiss the dialog if the user is syncing and their collection is safe
This is primarily documentation, the previous code has one minor bug in that a user could be preserving legacy storage AND not syncing AND had the ability to `MANAGE_EXTERNAL_STORAGE` then the 'backup' dialog was shown when it was not necessary
Mostly making use of newer documented methods in `ScopedStorageService`
Fixes #13663
⚠️ Untested - was for a backup dialog. Unit tests still pass, but this says little

BackupPrompt: Fix TODOs/conditionally skip confirmation dialog

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt

The DiscardChangesDialog is showing again when clicking on `cancel` button
Fixes #13834 
The `show()` function in Dialog is called twice. So, I removed one `show()` function
Tested on Pixel API 21
https://github.com/ankidroid/Anki-Android/assets/65113071/72ade13f-1410-4a7a-9d01-99170189e9ef

DiscardChangesDialog is closed in one click in NoteEditor

---

AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt

This bug was introduced between alpha94 and alpha95. Because the parameter passed in `CompatHelper.compat.hasVideoThumbnail()` this function is `soundPath`, but we need to pass `soundUriPath`. Therefore the method returns false instead of true
Fixes #13837 
Changed soundPath to soundUriPath
https://github.com/ankidroid/Anki-Android/assets/65113071/0ea4a0be-e3ee-46cb-ba42-7d81976d4da5

VideoPlayer is showing in Reviewer Screen

---

AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt

While adding an advanced setting, I found confusing that the code appears in an order that is not related to the order in the actual presentation. So I reorder it.
Actual change will appear in a distinct PR.

NF: Advanced Fragment code follow appearance order

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
AnkiDroid/src/main/java/com/ichi2/libanki/sched/TreeNode.kt

Noticed while trying to reproduce another issue
* `hasSubdecks` adds padding to the `DeckAdapter`'s ViewHolder
* It was set if a single deck exists in the new backend. This shouldn't happen
- Fixes #13794
* Understand the code
* Fix 'hasSubdecks'
* Realise code can be simplified further
I then saw an opportunity to perform cleanup for 70151c563e92029956fe0c8ee19de075347db599 which added a number of unnecessary `suspend` calls to the code. This handles most of the cleanup
Since `processNodes` was simplified, I then made it pure, and finally made `m[Current]DeckList` immutable lists, which should resolve #13794
Briefly, manually on an API33 emulator
Tested against Arthur's collection on an API 33 emulator

fix: 'hasSubdecks' [new backend] & refactor DeckAdapter & fix IndexOutOfBoundsException

---

AnkiDroid/src/main/res/xml/cram_deck_options.xml

The keyboard is not showing automatically
Fixes #13775 
Replaced EditTextPreference with AutoFocusEditTextPreference

EditTextPreference -> AutoFocusEditTextPreference

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt

The cursor is at start of input text. The user has to move the cursor to end manually.
Fixes #13841
called `setFocusandOpenKeyboard()` method

Moved cursor to end in TagsDialog

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/LocaleSelectionDialog.kt

Although not available from `Locale.getAvailableLocales()`(the source we use for building the list of languages) "und-fonipa" seems to register as a language code for IPA(will appear as "_IPA Phonetics_" in the dialog). GBoard will use it when set as a language hint.
See https://en.wikipedia.org/wiki/International_Phonetic_Alphabet#IETF_language_tags 
Fixes #13883
Ran the tests and verified that the new language is being used as a language hint and that it does influence the keyboard(GBoard).

Add International Phonetic Alphabet as a note field language hint option

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/res/values/02-strings.xml

The current label of the negative button of "Timebox reached" dialog is "Close", but it misleads as if it merely closes the dialog. (It actually finishes the review session and shows the deck picker screen.)
This commit will replace the label with "Finish", which is used on the counterpart dialog in Anki Desktop.
N/A
- ~~Add a new string~~ Reuse the "Finish" string from Anki Desktop
- ~~Replace the current string with the new one in the dialog~~
~~Checked on an emulator (Pixel 2 / API 30)~~

Use "Finish" as Timebox negative button label

---

AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt

` android:authorities="${applicationId}.apkgfileprovider"
`
This change gets the authority for debug version with `.debug` before the apkgfileprovider which caused an exception in the codebase. So using 
`val authority = "${activity.packageName}.apkgfileprovider"`
fixes the mismatch in the code
tested on google emulator

using `activity.packageName` to fix the authority issue while exporting collection

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/IntegerDialog.kt

keyboard is not shown when IntegerDialog is visible
Fixes #13895
Now  `dispalykeyboard()` is called after IntegerDialog is shown
Tested on emulator (Pixel 5 API 33)
https://github.com/ankidroid/Anki-Android/assets/119813120/983022f9-6e82-4427-ac49-4da0219217f5

IntegerDialog is showing keyboard automatically

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ModelEditorContextMenu.kt

Replaces usages of MaterialDialog with AlertDialog in ModelEditorContextMenu.kt

Changed Material Dialog with Alert Dialog for ModelEditorContextMenu.kt

---

AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.kt

While adding a note type from manage note types, I am supposed to choose the note type, and after choosing I again need to press the Ok button and then it opens a new dialog for naming the note type
Obviously, if I chose note type, I meant to add note type.
Fixes #13914
1. Remove the positive button
2. set `waitForPositiveButton = false` in `listItemSingleChoice() `so that I do not wait for the OK button to be clicked
Tested on Physical Device ( Realme 9 )
https://github.com/ankidroid/Anki-Android/assets/65113071/967f444e-a74a-4a7f-838a-de246d9ea6f2

immediate dialog after selecting note type

---

AnkiDroid/src/main/res/layout/deck_item.xml

The deck name is shown in only 2 lines and if its lengthy then there is no hint that it is continued or not.
Minor change for better UI

ellipsize the deck name if lengthy

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckOptionsActivity.kt

The code iterated over the child decks to set the new configuration from the parent but it used the parent deck as the target so child decks kept their current deck configuration.
Fixes #13933 
Manually verified that the parent deck configuration will be applied on child decks when requested.

Fix parent config not being applied on child decks in deck options

---

AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/AppearanceSettingsFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/GeneralSettingsFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/ReviewingSettingsFragment.kt

Code inside a withCol() block should not modify the UI, as it runs on a background thread. withCol() should fetch and/or mutate collection data, and then UI operations/program state changes should be performed outside the withCol block, so they're serialized on the main thread and the risk of race conditions is minimized. Recently mentioned on https://github.com/ankidroid/Anki-Android/pull/13886#issuecomment-1555407973
launchWithCol() makes it a bit too easy to accidentally run UI code in the background thread, as it provides both an async context and a collection at the same time, and the user will be tempted to do both fetch-from-col and update-UI steps inside the block. Removing it means a few extra characters at each call site, but I think it's a bit less error-prone.
@BrayanDSO I …

Remove launchWithCol()

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
AnkiDroid/src/main/java/com/ichi2/libanki/ConfigManager.kt
AnkiDroid/src/main/java/com/ichi2/libanki/DB.kt
AnkiDroid/src/main/java/com/ichi2/libanki/DeckManager.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Media.kt
AnkiDroid/src/main/java/com/ichi2/libanki/ModelManager.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Tags.kt
AnkiDroid/src/main/java/com/ichi2/libanki/sched/BaseSched.kt
lint-release.xml

If detected, shows an IDE lint.
- Catches calls to col.* inside AnkiActivity contexts.
- Catches calls to methods of classes derived from AnkiActivity, eg
```
withCol {
someDeckPickerMethod()
}
```
- UI classes that don't inherit from AnkiActivity are not caught unless they are also annotated with @UiThread. Eg SetNotetypeListener in NoteEditor references col, but is not caught without an extra annotation.
It might be best to wait until 2.16 is out (and any quick follow-up releases to address the inevitable regressions) before we start addressing these issues in bulk; for now the code might be better left as-is unless it's to address a known bug someone has reported.
Related: #13944, #13942, #13936

Catch some attempts to access UI inside withCol, and col within UI thread

---

AnkiDroid/src/main/java/com/ichi2/preferences/IncrementerNumberRangePreference.kt

The cursor should be at end while increment or decrement integers
Fixes #13954 
set cursor to end
Tested on Emulator (Pixel 5 API 33)
https://github.com/ankidroid/Anki-Android/assets/65113071/4201fc4d-1d48-4fa8-855a-a5594903d5c6

Moved cursor to end while incrementing/decrementing values

---

AnkiDroid/src/main/res/values/theme_black.xml
AnkiDroid/src/main/res/values/theme_dark.xml
AnkiDroid/src/main/res/values/theme_light.xml
AnkiDroid/src/main/res/values/theme_plain.xml

The dark shade it had wasn't very attractive
Contrast ratio of new text is over 4.5, i.e. good enough
used the specific attr for preference category titles

Change preference category title color on the light theme

---

AnkiDroid/src/main/java/com/ichi2/anki/preferences/DevOptionsFragment.kt
AnkiDroid/src/main/res/values/preferences.xml
AnkiDroid/src/main/res/xml/preferences_dev_options.xml

This will add to manually test migration of media.
Bug: #13480 from @oakkitten

Adding develepor options to add fake media

---

AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/Import.kt
AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.kt
AnkiDroid/src/main/java/com/ichi2/libanki/importer/Importer.kt

Part of https://github.com/ankidroid/Anki-Android/issues/7108. The minimum amount of work to migrate this task to coroutine to remove it from CollectionTask. There's no need for extra refactoring or TODOs as the changed code is on the legacy pathway and will be removed when the new backend becomes the default..
Ran the tests, manually verified the import feature.

Migrate the ImportAdd task to coroutine

---

AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt

I had some doubt about which function moves to IO dispatcher, whether it was launch method or withCol. I expect this documentation may save a minute to other devs too.

NF: document that `withCol` and `withQueue` executes in IO

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ModelBrowserContextMenu.kt

Replaces usages of MaterialDialog with AlertDialog in ModelBrowserContextMenu.kt

Changed Material Dialog with Alert Dialog for ModelBrowserContextMenu.kt

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserOrderDialog.kt
AnkiDroid/src/main/res/values/07-cardbrowser.xml

#13315
AlertDialog can't have both a message and items, so I removed the message
[pr (2).webm](https://github.com/ankidroid/Anki-Android/assets/65715921/2debfe7c-6d3d-4fdf-95e9-fbd39f8e233a)

Migrate CardBrowserOrderDialog to AlertDialog

---

AnkiDroid/src/main/java/com/ichi2/utils/TypedFilter.kt

The results parameter is declared as nullable (FilterResults?), but we are force unwrapping it (!!) without checking for null. If results is null, a NullPointerException will be thrown.
Fixes  #13974
To fix this issue, we should perform a null check before accessing the values property. 
NPE would be avoided by the check hence avoiding the crash

checking for null result to avoid class cast exception

---

AnkiDroid/build.gradle
build.gradle

Update the fragments library to the new stable version using the new artifacts, see the [release page](https://developer.android.com/jetpack/androidx/releases/fragment#1.6.0) for more info.
Fixes #12904 
Ran the  tests, both unit and instrumented.

Update androidx fragments library to 1.6.0

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/res/layout/deck_picker.xml
AnkiDroid/src/main/res/layout/homescreen.xml

Setting the image as background didn't offer the same customization features as when used in an ImageView(which has the option to apply a scaleType. See images below for a phone:
Note that on xlarge screen(has dedicated layout) like tablets(landscape) the background isn't currently applied full screen but I think it's good as it is now:
Fixes #13907
Ran tests and manually verified the image.

Fix background image distort for DeckPicker

---

AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt
AnkiDroid/src/main/java/com/ichi2/ui/GestureDisplay.kt
AnkiDroid/src/main/res/layout/gesture_display.xml
AnkiDroid/src/main/res/layout/gesture_picker.xml

Fixes #13432
Properly use the ConstraintLayout attributes to be more responsive.
This fix is more helpful for tablets which are commonly used in landscape mode. The dialog don't look very good in phones because of the lack of vertical space, but probably the best way to gain some vertical space is doing a whole custom fragment
[device-2023-06-11-153833.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/eefa00e4-eb29-4a1c-b30c-35e2b7fcc597)
On a Nexus 9 tablet emulator:

Fix gestures selection in landscape mode

---

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.kt

IntelliJ keeps removing `import java.util.*`. Which changes `ArrayList` from java to kotlin and creates compilation error due to nullable string typing.
I'd wish this to be merged just so that I don't have to fight with IntelliJ.

NF: Correct typing of getBundleEditFields

---

AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt

Fixes #13995 
Check if the collection is open before doing that operation
Nexus 9, API 29 emulator. Sorry for the backwards video, idk why Android studio recorded it that way
[after.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/4c4775ab-fd79-4c22-bca5-b959723ce141)

fix: StudyOptionsFragment showing "Failed to create directory" message

---

.github/dependabot.yml
AnkiDroid/build.gradle
AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
build.gradle

Staying up to date in general on dependencies, but also very importantly this fixes API < 24 failures on main right now by reverting an incorrect update to jackson-databind
API < 24 as mentioned in description
revert the databind change and alter dependabot config to stop prompting for it with a note we need API>=24
Locally with `./gradlew jacocoTesstReport` against an API24 emulator, CI will check API30

Dependency updates 20230621

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.kt
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
AnkiDroid/src/main/res/menu/reviewer.xml
AnkiDroid/src/main/res/values/02-strings.xml
AnkiDroid/src/main/res/values/11-arrays.xml
AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/ViewerCommandTest.kt

1. Changed menu name 'Enable/Disable stylus mode' to 'Enable/Disable stylus writing'
2. Changed the menu order 'Enable/Disable stylus writing' to make a group of stylus functions.
3. Added 2 control functions 'Clear whiteboard' and 'Change whiteboard pen color'.
none
Nothing special
Emulator

Improve stylus related functions(menu, controls)

---

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt

Fixes #13450
This can be achieved by adding answerField!!.focusWithKeyboard() in onResume()
https://user-images.githubusercontent.com/65113071/226091366-19107112-12fa-419c-9760-8833937aba62.mp4

Show keyboard in onResume state of Reviewer.kt

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
AnkiDroid/src/main/java/com/ichi2/async/Connection.kt
AnkiDroid/src/main/java/com/ichi2/libanki/sync/MediaSyncer.kt
AnkiDroid/src/main/res/values/03-dialogs.xml
AnkiDroid/src/main/res/values/04-network.xml

#12451 Issue: Replace string with plurals

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/ReviewingSettingsFragment.kt

Diable `keep screen on` when disabling `automatic display answer`
Fixes #13951
set isChecked to false when disabling "automatic display answer"

Disable keep screen on while disabling automatic show answer

---

build.gradle

Update the amazon publish plugin to current master, and override one of it's dependencies to one that has not vanished off the face of the internet
Fixes the build which is currently broken on main
Carefully override the one group/artifact/version combo that vanished to one that exists, and add the maven repository required to find a current master build of the plugin
I have not tried to publish to amazon (no one has in forever...) but the build works for me locally with these fixes applied
Entropy and chaos.
It's always entropy and chaos.
Things work fine, and then something unrelated happens and things break.

fix build related to vanished transitive dependency of amazon publish plugin

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/Previewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerCommandTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerKeyboardInputTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerKeyboardInputTest.kt

It probably should not be `NF`, but here it is. Because each time that `setTitle` is called, `updateActionBar` is called immediately after and change the title anyway.
In practice `setTitle` was setting a wrong title in the Reviewer, as it was using current deck instead of the name of the current card.
Worse, while moving access to `col` to coroutine, I realized that this created a race condition, where the title changed. That was catched by automated test, so that's great actually.
We can also decide that actually, we wanted to keep `Preview` as title all the time, and current behavior is a bug. In which case I suggest we move `updateActionBar` to `Reviewer` and ensure it does not deal with title anymore.

NF: Remove setTitle in AbstractFlashCardViewer

---

.gitignore
AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt

Bitmap size check to avoid the condition where bitmap size <0
Fixes #13972
condition is suffice to avoid the exception but I would like to have an opinion if we should have a default bitmap size i.e `500x500` in case this case arises. @BrayanDSO 

checking for bitmap size to avoid `illegalArgumentException`

---

AnkiDroid/src/main/java/com/ichi2/anki/preferences/GeneralSettingsFragment.kt
AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt

Changing to another language then back to the system language didn't work for the new backend unless the user restarts the app
Fixes #13813 (I can't reproduce the exact reproduced issue, but fixed https://github.com/ankidroid/Anki-Android/issues/13813#issuecomment-1537457393 while at it)
Use `getSystemLocale()` instead of `Locale.getDefault()`
On a SDK **29** emulator:
1. Enable the new backend
2. Change language to any other than the system language
3. Check if the statistics screen use the new language
4. Change app language to "System language"
5. Check if the statistics screen use the system language
Note that there is a known issue of the Android methods returning the app's language instead of system's on SDK 33 specifically. As we are using an alpha appcompat version, I don't think …

Fix new backend language not being changed into the system language

---

AnkiDroid/src/main/java/com/ichi2/preferences/IncrementerNumberRangePreferenceCompat.kt

The cursor should be at the end while increment or decrement integers
Related #13954 
set cursor to the end

Moved cursor to end in IncrementerNumberRangePreferenceCompat

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/utils/AssetHelperTest.kt
AnkiDroid/src/main/java/com/ichi2/utils/AssetHelper.kt

JS modules must have `text/javascript` MIME, otherwise they won't load: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules.
Fixes #9311.
`guessMimeType()` works on Android 10+. MIME type must be set explicitly on older Androids.
Android 8.0 and 13.0 in emulator.
Android 8 on Samsung T585.

JS module loading for older Androids (fixes #9311)

---

AnkiDroid/src/main/java/com/ichi2/ui/SeekBarPreference.kt

See https://ankidroid.org/acra/app/1/bug/56002/report/ab7e3ae1-2d0e-4ea1-9da5-b0118b3e06f4
The class SeekBarPreference was deleted in e426fd9599aa79307adf4ad135a223ae6c443e0b. Although the IDE shows the class as not being used, it's actually used inside DeckOptionsActivity. This PR reverts the deletion commit and also adds a comment on the "unused" suppression.
Manually verified that the path of the code with the changes works.

Fix SeekBarPreference not found in DeckOptionsActivity

---

AnkiDroid/src/main/java/com/ichi2/libanki/template/TemplateError.kt

On (the back side of) card templates in the current backend, if you input an incorrect closing tag, for example, "{{#Tags}}blah{{/**Ta**}}", its preview says 
`Found '{/Tags}}', but expected '{{/Ta}}'`.
This commit will fix the inappropriate reversal.
In other words, by this commit the preview will say 
`Found '{/Ta}}', but expected '{{/Tags}}'` 
as in Anki Desktop and in the advanced "new backend".
**In Anki Desktop**
**In the new backend**
Swap the first parameter and the second parameter of `WrongConditionalClosed()`
https://github.com/ankidroid/Anki-Android/blob/c1dcf40a2f41decf926ce944573daf450f62558f/AnkiDroid/src/main/java/com/ichi2/libanki/template/TemplateError.kt#L37-L41
**Relevant part 1**
https://github.com/ankidroid/Anki-Android/blob/c1dcf40a2f41decf926ce944573daf450f62558f/An …

Fix the reversal of correct/incorrect closing tag in the error message of the card template preview

---

AnkiDroid/src/main/java/com/ichi2/utils/MenuUtils.kt

Please test on device before approving.
As per the documentation,
> By default, all drawables instances loaded from the same resource
share a common state; if you modify the state of one instance, all the other instances will receive the same modification.
In reviewer, tint is applied to the icons of overflow menu items. Previously, the icons were not mutated, which lead to these icons appearing dark when used in other activities.
Fixes #13921, closes #13925
Mutate icons

Fix card browser add icon appearing dark

---

AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/AppearanceSettingsFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/DevOptionsFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/GeneralSettingsFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/NotificationsSettingsFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/ReviewingSettingsFragment.kt
AnkiDroid/src/main/res/color/slider_active_track_color.xml
AnkiDroid/src/main/res/color/slider_halo_color.xml
AnkiDroid/src/main/res/color/slider_thumb_color.xml
AnkiDroid/src/main/res/color/switch_thumb_tint.xml
AnkiDroid/src/main/res/color/switch_track_tint.xml
AnkiDroid/src/main/res/values/attrs.xml
AnkiDroid/src/main/res/values/theme_black.xml
AnkiDroid/src/main/res/values/theme_dark.xml
AnkiDroid/src/main/res/values/theme_light.xml
AnkiDroid/src/main/res/values/theme_plain.xml
AnkiDroid/src/main/res/xml/preferences_accessibility.xml
AnkiDroid/src/main/res/xml/preferences_advanced.xml
AnkiDroid/src/main/res/xml/preferences_advanced_statistics.xml
AnkiDroid/src/main/res/xml/preferences_appearance.xml
AnkiDroid/src/main/res/xml/preferences_controls.xml
AnkiDroid/src/main/res/xml/preferences_dev_options.xml
AnkiDroid/src/main/res/xml/preferences_general.xml
AnkiDroid/src/main/res/xml/preferences_notifications.xml
AnkiDroid/src/main/res/xml/preferences_reviewing.xml
AnkiDroid/src/main/res/xml/preferences_sync.xml

Changing colorControlActivated value originally had the purpose of tinting the preferences switches (49a880bca6bc422bcebbaf32555042f32e1e648c)
Since this caused the problem of the text selector being the same color of the app bar on the light theme (#12337), using a more specific color selector should be preferred
Fixes #12337 and closes #13503
On the commits
API 25 emulator
https://github.com/ankidroid/Anki-Android/assets/69634269/cb4ac0ad-5dc9-4032-bfdc-c44da1ed2e7c
Appcompat has a lot of attributes. Try searching deep if you haven't found an attribute to change something

fix: Cursor color being the same of the app bar on the light theme

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt

In this commit, I fix the issue that allowed modifying the field 'front' of a card to an empty value. When adding a card, the user can't leave the 'front' field empty. By resolving this problem, I have ensured a more consistent user experience.
Fixes #14043 
When editing a card, it was possible to leave the "Front" field empty, which is not expected behavior according to the app, as this is blocked when adding a new card.
Tested Pixel 3a API 33 (Emulador) and Motorola Moto G7 (Real device)
The fix has been tested by following these steps:
1. Opened the Anki app.
2. Navigated to the Card Browser screen.
3. Selected an existing card and clicked on "Edit Note".
4. Modified the "Front" field to be empty.
5. Pressed the save button.
6. Verified that an SnackBar with an error message (the same …

Fix empty front card

---

AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt

It's better to have a horizontal padding and show a warning on FixedEditText rather than Toast
Related #13639 
Implementing a warning message on FixedEditText when user didn't enter anything in FixedEditText or the value is invalid
Adding horizontalPadding to FixedEditText
Tested on Physical Device (Realme 9)
https://user-images.githubusercontent.com/65113071/233353502-a0e6ab95-8e81-41f9-977a-86aa9fc084a7.mp4

horizontalPadding to FixedEditText and showing warning instead of Toast 

---

.github/workflows/update-gradle-wrapper.yml

the gradle wrapper update action was targeting our default branch but I like to stage all these things through the dependency-updates branch to reduce noise on main branch
Use the available configuration items `base-branch` and `target-branch`: https://github.com/gradle-update/update-gradle-wrapper-action#base-branch
Can't really test it, but when gradle releases version >8.1.1 we shall see...

build(deps): gradle wrapper update PRs should target dependency-updates branch

---

.github/workflows/lint.yml
.github/workflows/publish.yml
.github/workflows/tests_emulator.yml
.github/workflows/tests_unit.yml
.github/workflows/update-gradle-wrapper.yml
AnkiDroid/build.gradle
build.gradle

Non-trivial dependency updates - important changes:
- JDK11 is dropped, minimum supported JDK for AnkiDroid is now JDK17
- compilation source/target JVM level is bumped from 8 to 11
These are required to keep up with transitive dependencies and I would like to get them in before we branch 2.16 off for release / support fixes, as straddling the JDK toolchain version is painful
Carefully work through dependency update PRs, they all have related commits with explanations
Carefully test on API21 emulator while checking that JVM11 source/target and JDK17-compiled artifacts work correctly. They all seem to work
I rarely learn much from dependency updates, except that staying up to date takes effort

Dependency updates 20230628

---

AnkiDroid/src/main/java/com/ichi2/anki/Info.kt

If you tapped the link for the development version commits in the changelog, instead of opening it in an external browser, it would open it inside the changelog webview, which had the problem of the links being red and didn't offer the full power of a real browser.
Excludes the commits link from the links to be opened inside the changelog webview
API 25 emulator
[device-2023-06-26-182023.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/aa773755-4e52-46d6-92fd-f325dfe09447)

fix: Open changelog's link to development commits in an external browser

---

AnkiDroid/src/main/res/drawable/ic_language_black_24dp.xml

Translate icon tint color is not in blue color
Fixes #14040
set tint color to holo blue dark 
Tested on Physical Device (Realme 9)
**Light**
**Black**
**Plain**
**Dark**

Set translate icon tint color to blue

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.kt

Replaced MaterialDialog with AlertDialog as mentioned here https://github.com/ankidroid/Anki-Android/issues/13315
https://github.com/ankidroid/Anki-Android/issues/13315
Tested on Physical Device running Android 13.
Before             |  After
:-------------------------:|:-------------------------:
https://github.com/ankidroid/Anki-Android/assets/46300244/dffdb9e4-b0f9-4bb4-9cef-9da318986999
https://github.com/ankidroid/Anki-Android/assets/46300244/f650ccf1-c149-45a1-8e6a-59f30eeb2852

Replaced MaterialDialog with AlertDialog in ImportDialog.

---

AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt

Related to [#13315](https://github.com/ankidroid/Anki-Android/issues/13315)
I tried following previous pull requests related to this issue as much as possible. When I noticed that no other previous pull request adapting a Material dialog that had an EditText inside, I added a new "customView" function to the Alert dialog facade to achieve a similar UI Design. 
Tested all the modified dialogs by inputting, canceling or making changes.
While trying to work on this problem, I noticed that there was no alternative to the customView function from the materialDialog library in the AlertDialog library. While trying to inflate an EditText it was actually hard to find a solution to add a margin to the InputField to make it look like its materialDialog version (I wanted to avoid making an xml …

Replace MaterialDialog with Alertdialog for ModelFieldEditor.kt 

---

AnkiDroid/src/main/java/com/ichi2/libanki/sched/CardQueue.kt

Fundamentally reverts https://github.com/ankidroid/Anki-Android/commit/614b31434e987523ae3220f409fc1b5721f8b0eb#diff-dc3d0158a31e3414efd9b630b24220cbdb75
Fixes #14066 
Hasn't

fix: avoid concurrent change exception when removing card from queue

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsArrayAdapter.kt

theoretically, it should avoid #14068.
I'm not sure if there is a chance to generate a misbehavior here instead of crashing, but since I can't reproduce it, I can't tell.
For now, not crashing is better than crashing
Fixes #14068
hasn't

fix: handle TagsArrayAdapter::checkBoxState null values

---

AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MigrationProgressDialogFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/dialogs/ActivityAgnosticDialogs.kt
AnkiDroid/src/main/res/values/01-core.xml

See commit messages (no, really). Note the new TODO. Note string changes in the notification.
Below are the new error dialog shown when there's an error while migrating essential files, and the altered media migration error dialog.
A demo with a few activity recreations. Note that at the end of the video there's a rogue dialog offering to resume migration under the migration dialog, that's a result of the problem described in the TODO.
https://github.com/ankidroid/Anki-Android/assets/1710718/7ef4ca82-bad5-4c3d-ae25-c44fcfbae0fc
Thanks to @snowtimeglass for help with strings.
Fixes #13970, hopefully fixes #13868 and closes #13918 as obsolete

Move essential file migration into the service

---

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt

optString fallbacks to "" if the string wasn't found, which is the default bqfmt and bafmt value if the user hasn't set one
Fixes #14073
Hasn't

fix: make bqfmt and bafmt not crash if not found

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt

Whenever a menu item was selected in the DeckPicker the FAB was closed with an animation.
Fixes #14093 
Manually verified the application.

Remove animation of DeckPicker FAB when selecting menu item

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt

Place a NPE check and replace with a empty array list if the values are null to avoid NPE
Fixes  #14047
Google emulators and ```?:``` ensures the safe use 

NPE in handleAsyncMessage of MediaCheckDialog

---

AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt
AnkiDroid/src/main/java/com/ichi2/anki/utils/AndroidUtils.kt
AnkiDroid/src/main/java/com/ichi2/async/Connection.kt

Prevent storage migration from pausing when screen is off/device is sleeping. Fixes #13728
Use a wake lock unconditionally. **NOTE: I haven't added any warnings to the user as I couldn't come up with text I liked.**
Now the code runs on my device/emu and I see the wake lock in the wake lock log:
```
07-09 10:37:09.755 - 10183 - ACQ com.ichi2.anki.debug:MigrationService (partial,on-after-release)
07-09 10:37:10.776 - 10183 - REL com.ichi2.anki.debug:MigrationService
```
But I couldn't verify that it fixes the issue because I could reproduce the issue. Somehow no matter what I tried I couldn't get the device to stop copying files. Real device, emulator, force idle in adb. Verified that there were no other wake locks. ¯\\\_(ツ)_/¯

Use wake lock while migrating storage

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/LocaleSelectionDialog.kt

Keyboard input not visible on SearchIcon click in LocaleSelectionDialog
Fixes #14121
reverted #14061 
Tested on Realme 9

revert #14061

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/res/values/02-strings.xml

Simplify 'Dont ask again string' in metered connection dialog.
Fixes #14091 
Resused string and removed unused string.

fix: Simplify 'Dont ask again string' in metered connection dialog

---

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt

Small PR to fix a bug until that part of the code is refactored. See issue on acra: https://ankidroid.org/acra/app/1/bug/61331/report/745e50d4-67c2-45ac-87bf-48ba22a3ba53 :
```
java.lang.RuntimeException: Unable to destroy activity {com.ichi2.anki/com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivity}: kotlin.UninitializedPropertyAccessException: lateinit property mCropButton has not been initialized
at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5427)
at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5460)
at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
at …
```

Fix crash in BasicImageFieldController due to uninitialized properties

---

AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.kt

This was reported in https://github.com/ankidroid/Anki-Android/issues/14150. Here's a fix for it if it's determined that this is something that should be changed.
The purpose is to provide consistency across the Anki desktop and mobile versions. The desktop version uses `<i>` to make text italic, whereas AnkiDroid uses `<em>`.
Fixes #14150
The note editor toolbar has a helper function that attaches an `onClickListener` to the toolbar buttons with the strings the text should be wrapped in. This just updates the prefix/suffix text from `<em>...</em>` to `<i>...</i>`.
I edited a note and confirmed that highlighted text was wrapped in `<i>...</i>`.
Searched for usages of `<em>` in the app :smile: 
- There are some issues reported regarding the editable `TextView`s having an …

fix: Use <i> instead of <em>

---

AnkiDroid/src/main/res/layout/card_browser_item_my_searches_dialog.xml

no padding to saved search dialog and also there is some unused FixedTextView in layout
Fixes #14167 
set padding and remove FixedTextView

Improved CardBrowserMySearchesDialog

---

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt

One of the whiteboard menu item(that appears after the whiteboard is enabled by the user) used a theme attribute(`?attr/iconColor`) in its vector drawable(`ic_color_lens_white_24dp`). This vector drawable was inflated through `VectorDrawableCompat.create()` without passing a theme so the custom theme attribute couldn't be resolved. See stacktrace below:
```
java.lang.UnsupportedOperationException: Failed to resolve attribute at index 1: TypedValue{t=0x2/d=0x7f04026b a=-1}
at androidx.core.content.res.TypedArrayUtils.getNamedColorStateList(TypedArrayUtils.java:172)
at androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateStateFromTypedArray(VectorDrawableCompat.java:765)
at androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.inflate(VectorDrawableCompat.java:719) …
```

Fix attribute not found in vector drawable of Reviewer menu item

---

AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt

A fix for one of the issues on acra where the individual export of a deck(from the deck context menu) that has a name containing a unix path separator crashes(example deck name: `Deck1 2023/8/6`). The fix replaces the path separators with underscores.
Acra issue: https://ankidroid.org/acra/app/1/bug/63092/report/95b05d5d-1109-44f3-9eda-7ed3a6811ca4
Manually exported a deck with a path separator in its name.

Fix crash when exporting a deck with a name containing a path separator

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt

The desktop version of Anki allows third-party cookies by default. However, this is not the case for Ankidroid.
This PR enables third-party cookies in the webview
This will allow you to login from within an iframe. If the website allows cross-site cookies.
None.
https://developer.android.com/reference/android/webkit/CookieManager#setAcceptThirdPartyCookies(android.webkit.WebView,%20boolean)
Device: Emulator(Pixel_3A_API_33)
Login test(cross-site): Python flask(https://github.com/app-generator/sample-flask-auth-session) + nginx(https connection)
modified `config.py`
```python
SESSION_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SECURE = True
```

Enable third-party cookies in the webview

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerNoSpaceLeftDialog.kt

Replaces usages of MaterialDialog with AlertDialog in DeckPickerNoSpaceLeftDialog.kt

Changed Material Dialog with Alert Dialog for DeckPickerNoSpaceLeftDialog.kt

---

AnkiDroid/src/main/res/drawable/add_shortcut.xml

* Icon was added in (#14136)
When creating a shortcut in the launcher, the icon resolution was low
* Fixes #14246
* New => Vector Asset
* Replace the existing drawable
* Fixed the tints + property ordering to match the existing
* This didn't work, upped size to 96x96dp
* Worked
S21 using OneUI
Before
After

fix: resolution of 'add_shortcut' launcher icon

---

tools/release.sh

amazon publish is not working at the moment, and it stops the upload of parallel builds
related: #14161 (but does not fix it)
Temporarily disable it
No way to test without running the release script

fix: disable amazon publish

---

AnkiDroid/src/main/java/com/ichi2/ui/BadgeDrawableBuilder.kt

After a sync on the legacy schema, the badge did not go away
Fixes #14225
* Added logs and the call was made correctly
* Added `removeBadge` after the calls to add a badge, and the badge still appeared
* Fixed
* Tested
* API 24 emulator
* S21 (Android 13)

fix: 'Sync required' indicator doesn't go away

---

.github/workflows/update-gradle-wrapper.yml

Run fails with
```
ERROR: AnkiDroid builds with JVM version 17 or 18.
Incompatible major version detected: '11'
```
* Fixes #14232
* update the CI script
* Realise I can't run the script, so update the script again
* ⚠️ I tried to test, but couldn't reproduce our failure due to my repo setup. ⚠️ Untested ⚠️
* https://github.com/david-allison/Anki-Android/actions/workflows/update-gradle-wrapper.yml

fix: use supported JDK with "Update Gradle Wrapper"

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/res/values/disable-fullscreen-keyboard-highlight.xml

The Reviewer window was fully highlighted if using the keyboard to answer a card using 'space'
* Fixes #14142
We use `android:colorControlHighlight` to remove this
Briefly tested on my S21 and I saw no UI regressions (Standard reviewer configuration)
⚠️ This is high risk for UI regressions
Also tested in dark mode
Learning for others: themes are additive

fix: unexpected reviewer highlights with keyboard

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/reviewer/PeripheralKeymap.kt
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerKeyboardInputTest.kt

When a user had a bluetooth/physical keyboard, and pressed 'space' when the card was in the 'answer' state AND gestures were enabled, a 'double tap' would occur:
* The gesture processor would process the command on `onKeyDown`
* Answer the card   
* Code in `AbstractFlashvardViewer.onKeyUp` would execute 
* Flip the card 
* Fixes #14214
* Refactor for tests
* Move the code to handle for 'space' etc.. to `onKeyDown`
* If the command processor is used, `super.onKeyDown` isn't called.
* Unit Tested
* Tested on my S21 (Android 13)
* Getting back into AnkiDroid, things feel really sluggish from an DevEx/Android Studio perspective, I'll see what we can do going forwards

fix: double tap when answering a card using keyboard

---

AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt

My guess is that the issue ocurred because the isChecked task were computed after or while the changeListener was set, so I'm setting the change listener only after the value is configured
found another occurrence in ACRA
Fixes #13216 
I couldn't reproduce the issue, so I only opened the Advanced settings to see if I got an error message (emulator 33)

fix: error at advanced settings

---

AnkiDroid/src/main/AndroidManifest.xml
AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt
AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt
AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivityTestBase.kt
AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldControllerTest.kt

if only the image taken by the camera app is necessary, there is no need for the permission
thought about removing it after seeing the play console message about less than 1% of the similar apps having the permission
simply remove the permission. The current code didn't need it
In a SDK 23 and a 33 emulators, in a Android 29 phone
1. Press the FAB >> Add
2. Tap the attachment clip icon > `Select image` > `Camera`
3. Take a picture
4. See if it is added to a card
https://stackoverflow.com/questions/32462725/capture-image-without-permission-with-android-6-0

fix: remove camera permission

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt

Highlighting wrong deck in tablet
Fixes #14057
updated DeckList when it is in tablet mode.
Tested on Tablet Emulator ( Pixel C API 33 )
[highlight.webm](https://github.com/ankidroid/Anki-Android/assets/65113071/b59126be-d15f-45eb-aaa3-cd1d7e7f4f72)

Highlighted Correct Deck

---

AnkiDroid/build.gradle
AnkiDroid/robolectricDownloader.gradle
api/build.gradle

Android 12L (API level 32) is a minor release that makes Android 12 even better on large screens.
There are no breaking changes. Since we have removed support for TVs, this is primarily relevant for foldable phones and Chromebooks
Changes: https://developer.android.com/about/versions/12/12L/summary
* Partially: #14129
update `targetSdkVersion` to 32
* Unit Tests
Since Google has imposed a hard deadline in a couple of weeks, only tested on:
* Large Desktop API 32
Never used a Desktop Emulator before. Easy process

build: update `targetSdkVersion` to 32

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt

While looking at fixing the bugs related to importing decks I noticed that it could be helpful to see lifecycle information for fragments like we implemented for the activities we use. This can be done through [FragmentLifecycleCallbacks](https://developer.android.com/reference/androidx/fragment/app/FragmentManager.FragmentLifecycleCallbacks).
The format I used is: _"activity_name"::"fragment_name"::"lifeycle_method_name"_ in order to group the fragments under an activity name.
Open for changes on what lifecycle methods to log and the actual logcat text to use.
Checked logcat for fragment lifecycle related events.

Use FragmentLifecycleCallbacks to log fragments lifecycles

---

AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt
AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionsCheckResult.kt
AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionsRequestResults.kt

While testing #14259, it wasn't feasible to test by passing an empty collection of permissions to PermissionManager.
I did this change to allow testing, the test worked, and we'll want this in so we can unblock #14259
This is a quick fix, as the code will go away very soon in Brayan's permission dialog change.
* Remove dead code so I don't need to refactor it
* Add a differentiating flag
S21, Android 13 on top of my patch for #14259
Closing the permission dialog also returns an empty set of results

fix: requesting no permissions succeeds 

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt

* Fixes #14220
* Reset the scroll position in a case where it previously wasn't handled
* API 33 emulator
I spent too much time trying to red/greed this test via Robolectric. Should have left it to Espresso

fix: restore scroll position after editing card 

---

AnkiDroid/build.gradle
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/test/resources/robolectric.properties

Use API33 as our target, to comply with Play Store guidelines
* Fixes #14129 
* Fixes #14120
- bumps the targetSdkVersion
- temporarily clamps robolectric to API32 until they fix an upstream issue (as noted in separate commit)
I tested these things, as indicated in related issue:
- system follows theme with light and dark in system, and app-specific them in AnkiDroid prefs with light and dark both checked
- changelog loading (followed theme)
- Anki manual, Github FAQ (followed theme)
- AnkiDroid manual (did not follow theme, because there is no theming on AnkiDroid.org - this is actually correct app behavior...)
- acquisition of audio, image, video without specifying new API33 granular permissions, both when directly creating them during card creation and when using the picker to choose …

build: bump to API33

---

AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
AnkiDroid/src/main/res/layout/activity_shared_decks.xml
AnkiDroid/src/main/res/values/02-strings.xml
AnkiDroid/src/main/res/xml/filepaths.xml

Attempts to fix some reported issues related to FileNotFoundExceptions when importing shared decks(for example https://ankidroid.org/acra/app/1/bug/63087/report/cca29061-dec2-416f-bbf1-a0e5bb864aa2 ). See commit message for extra info.
See documentation for [FileProvider](https://developer.android.com/reference/androidx/core/content/FileProvider), especially the section **Specifying Available Files**. Notice the mappings between the paths in filepaths.xml and the specific system directories the documentation specifies.
Manually imported a shared deck, however I don't know how relevant is this as I wasn't able to replicate the crashes from acra.

Fix importing a shared deck by providing a dedicated download path

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt

This was changed in #8781 to add 'pause' functionality But, this was not the default, the default was 'replay'
* Reopens #6774
* Fixes #14221
Revert a subset of this change + inline the function
Unit tests + on my Android 13 S21
Need more tests

fix: 'playsound' should replay the sound

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.kt

* Fixes #14285 
⚠️ For reviewers: I don't understand /why/ this one worked. Possibly the context of `launchCatchingTask` being the activity rather than the Fragment?
* add logs to diagnose
* determine  `updateDeckList` isn't called
* move `updateDeckList` outside `withProgress` to match `emptyFiltered` (no effect)
* move `launchCatchingTask` inside the method `rebuildFiltered`
* outcome of the above: rewrite `rebuildFiltered` to be the same as `emptyFiltered` 
Android 13 emulator

fix: 'rebuild' did not update the deck UI 

---

AnkiDroid/build.gradle
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DebugInfoService.kt

While I have a development build on my Android emulator, sometimes
I encounter a bug, this makes the build much more visible to help
with diagnostics
Define the hash in `BuildConfig`
API 33 emulator, displays:
`AnkiDroid Version = 2.16.3-debug (edf739d95bad7b370a6ed4398d46723f8219b3cd)`

dev: add git commit hash to debug info

---

AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt

I bought the `STAEDTLER Noris digital jumbo stylus pen` for my Galaxy Tab S7+.
It has a soft digital eraser at the end of the stylus. However, Ankidroid doesn't support digital eraser yet.
So I decided to make it support this feature.
None.
https://developer.android.com/reference/android/view/MotionEvent#TOOL_TYPE_ERASER
Stylus Pen: STAEDTLER Noris digital jumbo (https://www.staedtler.com/intl/en/discover/noris-digital-jumbo-tradition-meets-innovation/)
Device: Samsung Galaxy Tab S7+(SM-T970)

Add digital eraser support in the Whiteboard

---

AnkiDroid/build.gradle
api/build.gradle
build.gradle
lint-rules/build.gradle
settings.gradle
settings.gradle.kts

This is the first in a series of PRs(if accepted) to refactor the project's build system. This includes refactoring to use [modern practices](https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_management), cleaning up(with some performance improvements), [moving to kotlin dsl](https://android-developers.googleblog.com/2023/04/kotlin-dsl-is-now-default-for-new-gradle-builds.html), moving to using [versions catalog](https://developer.android.com/build/migrate-to-catalogs) and hopefully culminating with resolving the [move to renovate](https://github.com/ankidroid/Anki-Android/issues/11101) for handing dependencies.
More info can be found on each commit(I would recommend that they are reviewed independently(they are quite small) and not squashed merged). It's low priority, I …

Improve plugins usage in build files

---

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioRecordingFieldController.kt

'Field Contents' was designed to make it easier to read the content of a note while recording audio
But sometimes a user will want an audio-only note
In this case: the note's fields are all empty, and showing the 'Field Contents' heading doesn't make sense
Hide the label if there's no content
API 33: hidden if no text, displayed if text
**Before**
**After**

audio recording: hide 'contents' label if empty

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt
AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.kt
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
AnkiDroid/src/main/res/values/11-arrays.xml
AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/ViewerCommandTest.kt

Fixes #14265
I did what #14625 asked
> Remove the Answer recommended (green) and Answer better than recomended commands
Move their default commands to Answer button 3 and Answer button 4 respectively
Upgrade their preference assigned commands to Answer button 3 and Answer button 4 respectively
I increased the app version manually and ran the app to see if the commands were moved in the emulator

Remove answer recommended commands

---

AnkiDroid/src/main/res/values/theme_black.xml
AnkiDroid/src/main/res/values/theme_dark.xml

The previous PR #12971 made the color of the zero counts in the main screen brighter, in order to make it more visible. However, as a result of this, the contrast between the light gray and the other count colors (blue, red, green) becomes a bit too minimal to differentiate easily at a glance.
This commit will re-adjust the color of the zero. It will make the color dimmer. The aim of the dimmed zero is to not call attention, so it doesn't so matter if it can't be easily seen.
Fixes #13889
* Black theme: revert to the color used in 2.15.6
* Dark theme: adjust the color to be a bit lighter than the background, as in the black theme

Make the zero counts dimmer in black and dark themes

---

build.gradle

Bumps `acra_version` from 5.11.1 to 5.11.2.
Fixes #14348 
This is a startup crash that is unavoidable if it hits people so merging it here for a 2.17alpha2 release, plus going to cherry-pick the corresponding change to release-2.16 branch

build(deps): bump acra_version from 5.11.1 to 5.11.2

---

AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt

This was getting annoying so I marked the test as flacky. I used `Os.All` but I've only seen it fail on Mac and Windows.
Fixes #14383

Mark CardBrowserTest.flagsAreShownInBigDecksTest as flacky

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt

The type answer input field was hidden because the view is placed in the `reviewer_answer_buttons` layout which will be hidden if the user sets the "Answer buttons position" to "none" in settings. Ideally that layout would be refactored to exclude the type answer field which doesn't really belong there. 
Fixes #14419 
Ran the tests, manually verified the UI in various scenarios.

Show type answer field in reviewer when answer buttons are hidden

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/Info.kt
AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt
AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/Previewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/OnRenderProcessGoneDelegate.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerBackupNoSpaceLeftDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt
AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/OnRenderProcessGoneDelegateTest.kt

Historically, finishWithoutAnimation() was mostly used as a replacement for finish(), since it was deprecated by previous AnkiDroid devs in favor of using finishWithoutAnimation() and finishWithAnimation().
The issue was that it was common to see contributors, especially new ones (including myself), using finishWithoutAnimation() because only because finish() wasn't available and finishWithAnimation() was harder to use
Since there is no reason for wanting for a screen to finish without animation, which is unnatural, and now that finish() is undeprecated, it should be the default way of closing a screen.
There is no concern about devices with animation, since the behavior will be the same with finish()
Same for `launchForResultWIthoutAnimation()`. `startActivityForResultWithoutAnimation` …

Stop using finishWithoutAnimation() and launchForResultWIthoutAnimation()

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.kt
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt

When initializing DeckSpinnerSelection in NoteEditor the available deck ids weren't added to the `mAllDeckIds` list and later the selection was not registered.
I also fixed another regression from #14171. Reproduction:
_Click deck spinner in NoteEditor -> note that the default(empty) deck is being shown -> try to select it -> the first deck is chosen instead_
This was happening because there was a mismatch between what decks were shown in `DeckSelectionDialog`(was including the empty default deck) and the list of decks that were used to handle the deck selection(didn't include the empty default deck selection).
Note: with the changes from the second commit CardBrowser will also show the default deck.
Fixes #14354 
Manually verified the deck selection UI.

Fix note editor deck selection related issues

---

api/build.gradle
api/src/main/java/com/ichi2/anki/FlashCardsContract.kt
build.gradle

At the moment the `androidJavadocs` task in api module fails complaining about an invalid file `/FlashcardContract.kt`(and the others as well), probably because we switched to kotlin. In order to fix this I removed the previous gradle tasks that created the javadocs and switched to using kotlin's documentation engine [dokka](https://kotlinlang.org/docs/dokka-introduction.html).
Dokka can output in various formats including javadocs(in alpha state but I didn't see any issues) but also kotlin's own style of documentation. The added tasks are taken straight from the [documentation](https://kotlinlang.org/docs/dokka-gradle.html#build-javadoc-jar). 
If agreed I can also add the changes/switch to create documentation in kotlin's style(see for example the [documentation for …

Switch to use dokka for generating documentation in api module

---

AnkiDroid/robolectricDownloader.gradle

The problem is explained on #14350. The minimum SDK version was updated to 23 in #14171, which means these versions need to be updated, as they are tied into the SDK versions.
Fixes #14350.
I followed the steps suggested on #14350. The resulting folders that were downloaded to my local filesystem when running the unit tests were:
- ~/.m2/repository/org/robolectric/android-all-instrumented/10-robolectric-5803371-i4
- ~/.m2/repository/org/robolectric/android-all-instrumented/11-robolectric-6757853-i4
- ~/.m2/repository/org/robolectric/android-all-instrumented/12.1-robolectric-8229987-i4
- ~/.m2/repository/org/robolectric/android-all-instrumented/13-robolectric-9030017-i4
- ~/.m2/repository/org/robolectric/android-all-instrumented/9-robolectric-4913185-2-i4
Therefore I updated the …

Update downloaded robolectric versions

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt
AnkiDroid/src/main/res/values/10-preferences.xml
AnkiDroid/src/main/res/values/preferences.xml
AnkiDroid/src/main/res/xml/preferences_accessibility.xml

The user can define the minimum touch time for the show answer button as to avoid accidental touches and revealing the answer, this would allow the button to be clickable only after the certain time
min time : 0
max time : 2 s
Fixes #14229 
Tested on google emualtor 
https://github.com/ankidroid/Anki-Android/assets/48384865/fa7e1eae-2769-49b5-bde9-5779040f3c24

feature : minimal screen touch time to reveal answer

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt

Hello :) I have been an Android developer for the last three years and have been using ankidroid for the last five years, I decided this would be a good project to attempt to contribute to for improving my Android skills. 
Adds tests for checking the animations in the AbstractCardViewer are correctly inverted when added the intent.
https://github.com/ankidroid/Anki-Android/issues/13283
By overriding the test implementations onActivityStarted I can assign a value to a new top level intent and check, by extracting the parcelable animation, that the intent has correctly been assigned the correct inverse animation value when going through the editCard flow.
This loops it for 3 separate cases:
```
val gestures = listOf(Gesture.SWIPE_LEFT, Gesture.SWIPE_UP, Gesture.LONG_TAP)
```
This applies no …

Tests for inverse animation

---

AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt
api/src/main/java/com/ichi2/anki/api/AddContentApi.kt

Since Anki-Android now has minSdkVersion= 23, so checking whether API <= 23 is unnecessary.
Fixes #14338
This removes any unnecessary checks for API level 23.

Removes unnecessary API <= 23 checks

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/res/values/02-strings.xml

after we started using a internal server for serving the reviewer html, the whole card is replaced by `External page link in card is not supported.` if there isn't a browser installed
The original reason for checking browser was to adapt to educational devices that don't have a browser (efc9cec05884826a875cdfb446102b9a5c6d8e91), but the check isn't necessary in pratical terms, since there is already a message if the user taps a link without having a browser, i.e. `The system does not have an app installed that can perform this action.`
Fixes #14462 
Remove the check
Android 33 emulator:
1. Don't have a browser installed in the device
2. Open a card and see if it renders normally

fix: don't invalidate card if device doesn't have a browser

---

lint-rules/src/main/java/com/ichi2/anki/lint/rules/InvalidStringFormatDetector.kt
lint-rules/src/test/java/com/ichi2/anki/lint/rules/InvalidStringFormatDetectorTest.kt

See below
[Fixes _Link to the issues._](https://github.com/ankidroid/Anki-Android/issues/14079)
This addresses the problem of detecting formatting specifiers being capitalized accidently, leading to crashes.
Eg. $1%D instead of $1%d
./gradlew lint
Running the above command should run the detection
Added tests to InvalidStringFormatDetectorTest
You can run the tests as you normally would
https://www.developer.com/java/java-string-format-method/
Provides a chart of the Format Specifiers
I used the following regex:
(?<!%)%[^%a-zA-Z]*[DFNOGC].*
(?<!%)% => should match %, but does not match if there's another % immediately to the left
[^%a-zA-Z]* => should match any characters (zero or more) that are not %, alphabetical or whitespace
[DFNOGC] => should match any of the capital characters that …

Detect invalid capital letters

---

AnkiDroid/src/main/java/com/ichi2/anki/Info.kt

1. The url loading was not set to handle the local file correctly.
2. The access would be denied in case API>=30
Fixes #14499
https://developer.android.com/reference/kotlin/android/webkit/WebSettings#getallowcontentaccess
Tested on Google Emulator

url loading from assets

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt

Stop playing sound file when the action of "bury" or "suspend" is done.
Fixes #14494
Stop sound player before the feedback snackbar of the action is shown.
Checked in a physical device (Android 11) about the following actions.
- Bury
- Bury card
- Bury note
- Suspend
- Suspend card
- Suspend note
Checked both cases when "Don't play automatically" is enabled and disabled.

Stop sound when card/note is buried or suspended

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt

After trying to add a card and write something in any of the text fields if the user erased the text written in those fields although not having anything written, the program would save the state when the text was written and would pop an alert box.
Fixes #13821 
```
if (isFieldEdited) {
for (value in mEditFields!!) {
if (value?.text.toString() != "") {
return true
}
}
return false
```
After modifying the text and before going back to the homepage, the program is going to check if there is anything written in any of the text fields of the card, in case that it is the alert box would pop  and in the other case it wouldn't
Thanks to this change the program will save the state correctly without something unnecesary alert boxes
Do the same thing i wrote in the description and check that the …

 "lose current input" even when there is no input solved (#13821) 

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/res/layout/note_editor.xml

Anchored the Snackbar on top of  bottom tool bar.
Fixes #14506
https://github.com/ankidroid/Anki-Android/assets/91668590/25f86ec4-94ca-42fd-890f-05cdccfbbeef
Tested on Realme 6  API (30)

Anchored SnackBar on top of NoteEditor

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt

if the sharedPref hasn't been set yet, i.e. the user hasn't checked/uncheck the `Show toolbar` checkbox at least once, the snackbar was shown on top of the toolbar
Hasn't

fix: show snackbar above toolbar if setting hasn't been set

---

.github/workflows/sync_translations.yml

Currently the `sync_translation` workflow will fail if it's run again while a PR with strings translations already exists([example](https://github.com/ankidroid/Anki-Android/actions/runs/6339312113)). This is a common scenario when there are incorrect strings that need to be reverted so the workflow shouldn't fail for this. This PR fixes this issue by try/catching the call to create the PR and logging a message when the PR is available(and the workflow will not be marked as failed).
The same fix is present in [`update_js_libs`](https://github.com/ankidroid/Anki-Android/blob/main/.github/workflows/update_js_libs.yml) workflow.
Hard to test these workflows changes but any issue will be obvious pretty soon.

Handle the PR already existing when running the sync_translations workflow

---

AnkiDroid/src/main/java/com/ichi2/anki/Undo.kt

An empty snackbar is shown even without anything to undo as described in the linked issue.
Fixes #14471
This checks if the changes were empty, then shows a message accordingly.

Adds nothing to undo message

---

AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt

Crash when replacing gestures that have the binding assigned to other preference
Reproduction steps:
1. Assign an already used key/gesture to a preference
2. Confirm → Crash
Cause: Now that the ControlPreferences aren't all in the same PreferenceGroup, it can't be used anymore
Use PreferenceManager instead of PreferenceGroup and add a safeguard `continue` to avoid future crashes
Emulator 33, same reproduction steps

fix: don't crash when replacing controls

---

AnkiDroid/build.gradle
build.gradle
lint-release.xml

This will mostly supercede #14158 by avoiding all the issues associated with going to unreleased gradle versions (8.2+ betas and 8.3+ alphas)
It will unblock a stack of dependencies that are blocked waiting for AGP 8.1+
Related #14158
I move the var we use to create ABI splits to a wider scope then disable it in debug builds so as not to tickle https://issuetracker.google.com/issues/302961829
I am leaving #14158 open though, as it contains a couple commits that will be useful when we go to android gradle plugin 8.2+ with regard to dynamically registered context receivers. Note that the commits don't work yet but they appear correct and close to working so it is work worth preserving
`./gradlew jacocoTestReport` locally (which was always enough to trigger …

Update to android gradle plugin 8.1.2

---

AnkiDroid/build.gradle
AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTabOrderTest.kt
AnkiDroid/src/main/java/com/ichi2/anim/ActivityTransitionAnimation.kt
AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/SettingsFragment.kt
AnkiDroid/src/main/java/com/ichi2/compat/CompatV29.kt
AnkiDroid/src/main/java/com/ichi2/ui/OnGestureListener.kt
AnkiDroid/src/main/java/com/ichi2/utils/ReflectionUtils.kt
AnkiDroid/src/main/java/com/ichi2/utils/TextViewUtil.kt
AnkiDroid/src/test/java/com/ichi2/anki/servicemodel/UpgradeGesturesToControlsTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/servicemodel/UpgradeGesturesToControlsTestNoParam.kt
api/build.gradle.kts

Bump our compileSdk to 34 so we can process our growing stack of API34-dependent dependency bumps
Nothing fixed, but will unblock lots of dependency tag merges
Most of the deprecations were quite straightforward, I split each class into a separate commit with description
There is one about transition animations that I did not handle as it will be very intrusive, that one will need a tracking issue
Lots of runs locally of `jacocoTestReport` target and lint targets
Takes a lot of effort to fight bitrot

Bump compileSdk to 34, handle new deprecations

---

.github/dependabot.yml
AnkiDroid/build.gradle
AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTabOrderTest.kt
AnkiDroid/src/main/java/com/ichi2/anim/ActivityTransitionAnimation.kt
AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateBrowserAppearanceEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/NotificationsSettingsFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/SettingsFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/services/BootService.kt
AnkiDroid/src/main/java/com/ichi2/anki/services/ReminderService.kt
AnkiDroid/src/main/java/com/ichi2/compat/CompatV29.kt
AnkiDroid/src/main/java/com/ichi2/ui/OnGestureListener.kt
AnkiDroid/src/main/java/com/ichi2/utils/ReflectionUtils.kt
AnkiDroid/src/main/java/com/ichi2/utils/TextViewUtil.kt
AnkiDroid/src/test/java/com/ichi2/anki/servicemodel/UpgradeGesturesToControlsTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/servicemodel/UpgradeGesturesToControlsTestNoParam.kt
api/build.gradle.kts
build.gradle
gradle/wrapper/gradle-wrapper.properties
gradlew
lint-release.xml

Unwinding the stack of "needs API34" dependencies that had piled up
Squash merge, each of these was examined independently while rolling them up into dependency-updates branch, I'm pretty comfortable with them, going to merge when CI goes green
Fixes all of the API34 target stuff *except*:
1- predictive back needs better handling (it is "okay" now but some of the handling is just deprecation suppresison which is not great, there is a tracking issue)
2- dynamic context receivers being exported or not is *not* handled and we cannot update targetSdk to 34 until they are handled. This has preliminary work in #14557 and a cross-linked PR from that one - with some commits that get things close and some discussion on what's left
Bumping to compileSdk 34 and handling the fallout dependency by …

Dependency updates 20231019

---

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt

fix: replace "ok" with "yes" in crop image dialog to make it meaningful.
Replace strings.

fix: replace "ok" with "yes" in crop image dialog

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt

fix: opens keyboard when focus is on input text box in card view.
Fixes #14546 
use `typeAnswer!!.autoFocus` in `isFocusableInTouchMode` in web view.
https://github.com/ankidroid/Anki-Android/assets/76740999/a25bfcc2-af6e-4d7a-baaa-956d80f83c3a

fix: opens keyboard when focus is on input text box

---

AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.kt
AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/BackupLimitsSettingsFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/preferences/screens/BackupLimitsPresenter.kt
AnkiDroid/src/main/res/values/10-preferences.xml
AnkiDroid/src/main/res/values/constants.xml
AnkiDroid/src/main/res/values/preferences.xml
AnkiDroid/src/main/res/xml/preference_headers.xml
AnkiDroid/src/main/res/xml/preferences_advanced.xml
AnkiDroid/src/main/res/xml/preferences_backup_limits.xml
AnkiDroid/src/test/java/com/ichi2/anki/BackupManagerSimpleTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/BackupManagerTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/analytics/PreferencesAnalyticsTest.kt

This PR creates an UI for backup options and binds it to the logic in BackupLimitsPresenter. Note that the backup options were set to be observed by analytics(the informational backup help preference was excluded), these can't be used to identify the user and would be useful to observe to set better defaults. To discuss the strings and icon used(placement?), see images below:
Fixes #14366 
Ran the tests, used the options.

Enable new backend backup options in settings

---

AnkiDroid/src/main/java/com/ichi2/anki/IntroductionActivity.kt

The status bar is automatically hidden and it makes the black bar remain In UI which looks really weird.
Fixes #14432
This PR enables status bar on the intro page. It was previously disabled by default by the [App Intro](https://github.com/AppIntro/AppIntro) library.
[App Intro](https://github.com/AppIntro/AppIntro) library disables the status bar by default as mentioned [here](https://github.com/AppIntro/AppIntro/blob/db24d333e0c3e9c52bd763900552ef606461622e/appintro/src/main/java/com/github/appintro/AppIntroBase.kt#L389).

Enables Status Bar on App Intro

---

AnkiDroid/src/main/res/layout/note_editor.xml

I have removed the hardcoded height for the buttons as the text was not visible in case we selected too many tags, the text simply got underflowed. I am just fixing the issue but would like to get the code shifted to MaterialCardview and fixing the max heights and add scroll functionality to this portion.
Tested on oneplus nord ce

wrap content tags and cards button's height

---

AnkiDroid/src/main/res/menu/deck_picker.xml

I incorrectly added it to the "Checks" menu in #14463 so I reverted the change and now it appears again in the main toolbar menu.
Checked the undo functionality of DeckPicker.

Restore position of "Undo" in the toolbar menu of DeckPicker

---

AnkiDroid/src/main/res/drawable/ic_backup_restore.xml
AnkiDroid/src/main/res/drawable/ic_baseline_backup_24.xml

In order to be consistent with the other icons in the app
Backup icon color was different than the other ones in the preferences home page
Set the icon colors to `colorControlNormal`, which is what we use for most icons and what most apps use too for their icons
See if the color was changed in the XML preview

fix: set icon colors to colorControlNormal

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt

- Don't block the main thread in onStop() and onResume()
- Suppress multiple progress windows, so that the deck refresh that happens on onResume() doesn't cover sync progress
Closes #14197

Fix backgrounding freezing app until sync finishes

---

AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt

I mistakenly assumed answerTimer.setupForCard(currentCard!!) was already doing this
Closes #14586

Ensure card timer started

---

AnkiDroid/build.gradle
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/contextmenu/SystemContextMenu.kt
AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldControllerTest.kt
build.gradle

- 2 minor easy bumps
- 1 actual change where I pull in android gradle plugin 8.2.0-rc01 so we get ABI splits while resources are included again (which is our unit test configuration...). This reverted the change which broke release builds, so we should have release builds *and* have unit tests running
Fixes #14571 
Check to see if recent updates to android gradle plugin as they approach 8.2.0 final release finally cherry-picked the fix for https://issuetracker.google.com/issues/302961829
They did!
- revert my busted release / no-abi-split patch
- bump to new android gradle plugin
- profit
`./gradlew jacocoUnitTestReport` has always been the reproducer for the android gradle plugin bug when my workaround patch was reverted, so I reverted my patch and sure enough it failed
Then I bumped to …

Dependency updates 20231026 / unblock releases

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt

Day Reviewed cards count was not displayed at the bottom of the home screen
#14600 

review count in deck picker

---

api/build.gradle.kts

Exactly what the title says :-) - api targetSdk had trailed other modules for no reason I could determine
This bumps it to match Ankidroid module

build(deps): API module should have same targetApi as others

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/compat/CompatNormalizeTest.kt
AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt
AnkiDroid/src/main/java/com/ichi2/compat/CompatV23.kt
AnkiDroid/src/main/java/com/ichi2/compat/CompatV24.kt
AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.kt

We need this for TTS compatibility with Anki Desktop. We want `{{tts es_MX ...}}` to work (as used in Anki), but a `android.speech.tts.Voice` may have a locale which is serialised to `spa_MEX`.
* Related: #14358
* `ULocale` on API 24+
* Match locales using `language` and `country` on API 23
Tested on API 23 and my Samsung S21 (Android 13)
https://developer.android.com/reference/android/icu/util/ULocale

compat: Normalise locale to two letter code

---

AnkiDroid/robolectricDownloader.gradle
AnkiDroid/src/test/java/com/ichi2/anki/servicemodel/PreferenceUpgradeServiceTest.kt
AnkiDroid/src/test/java/com/ichi2/utils/ContentResolverUtilTest.kt
AnkiDroid/src/test/resources/robolectric.properties
build.gradle

Fresh dependencies - robolectric allowing use of API34 is the interesting one, it was vetted independently so should just be a "waits for CI to go green" deal here

Dependency updates 20231031

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckNode.kt
AnkiDroid/src/main/res/values/02-strings.xml

* #14608
* Perform refactorings as I see them to move towards more `suspend` functionality
* Fixes #14608
* extract `queryCompletedDeckCustomStudyAction`
* use `launchCatchingTask` to execute the functionality
* move `getColUnsafe.decks.select(did)` into a `withCol`
* move `getColUnsafe.config.get("schedVer")` into `withCol`
* replace usages of `getColUnsafe.deck.selected()` with `did`
* Further reactorings for readability:
* extract snackbar methods to inner functions
* remove duplicated `updateUi`  method
S21, Android 13 & ran unit tests

Fix: All decks show the same number of total cards and total new cards

---

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt

* #14623
* Fixes #14623
Temporary fix to return the card with the lowest `ord`
quick fix: We should modify CardBrowser to allow the display of notes, rather than continue this pattern
Unit Test. Imported Arthur's collection and tried it on a subset of cards

fix(Card Browser): notes-only mode

---

AnkiDroid/src/main/res/layout/deck_picker_dialog.xml
AnkiDroid/src/main/res/layout/studyoptions_fragment.xml

Forgot about those screens in dark mode
Fixes #14642 
Also fixes the same issue in the deck picker layout
use `appBarColor` instead of `colorPrimary`
saw the XML previews in Android studio

Fix app bar colors in deck info activity

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.kt

* I came across a confusing `KotlinCleanup` and want to ensure others don't spend time on it
Afterwards, I investigated a use of `vibrate` and found that it was never called
⚠️ Untested

cleanups: Kotlin Cleanup & mLongClickTestRunnable

---

AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/PermissionsActivity.kt

This was the initial behavior of #14130, but was changed by mistake when trying to deal with the onBackPressed deprecation
This fixes it and actually avoids the deprecation
Emulator 33:
1. New install with the `full` flavor
2. Press back in the permission screen → See that it doesn't go back to the reviewer

fix: only close the permissions screen by tapping the continue button

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt

Making AnkiDroid consistent with Anki - allowing the first field to be empty in edit note
* Fixes #14664 
Took off the condition 
Tested on OnePlus Nord CE

Allow first field to be empty in edit note

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt

After a note is saved, 'first field must not be empty' does not apply
* Issue #14664
* Follow up to review comment on #14665

 docs(NoteEditor): NeedsTest - After a note is saved, 'first field must not be empty' does not apply

---

AnkiDroid/src/main/java/com/ichi2/anki/preferences/SettingsFragment.kt
AnkiDroid/src/main/res/values/styles.xml
AnkiDroid/src/main/res/values/theme_dark.xml
AnkiDroid/src/main/res/values/theme_light.xml

So IDE previews are more precise and fragments that don't inherit from SettingsFragment also use the same style
Use japanese as app language and see if the preferences at the `General` section don't ellipsize

refactor: Set preferences single line title statically

---

build.gradle

This is a more comfortable development experience as it does not force developers to use the developer preview of android studio to sync correctly, and 8.1.3 (vs 8.1.2...) appears to have the upstream issue we had with split ABI and include resources in tests fixed
Local run of `./gradlew jacocoTestReport` which is always sufficient to trigger the previous "ABI split + tests include resources" compile failure in the past. Works now
@lukstbit has an eagle eye for android gradle plugin releases 🧐 😆 

build(deps): adopt android gradle plugin 8.1.3 vs 8.2.0-rc series

---

AnkiDroid/src/main/java/com/ichi2/anki/Info.kt
AnkiDroid/src/main/res/layout/info.xml

Replaces the Button with material button and fixed padding/margin in the Info page
Added a Divider to differentiate button layout from the webview
OnePlus Norde CE
AFTER:
BEFORE:
this is from google emulator so the rating button is not there but you get the basic idea

improve Info page UI

---

AnkiDroid/src/main/java/com/ichi2/anki/Info.kt
AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/Previewer.kt

Implemented predictive back navigation for Info.kt, ModelFieldEditor.kt and Previewer.kt. These are the simplest screens to change, with a note on Info.kt if we really need to handle the WebView.canGoBack() as we start an outside browser for any url.
Info.kt: 
https://github.com/ankidroid/Anki-Android/assets/52494258/ad45c1cd-8b45-4211-848d-f3b200926bdd
Previewer.kt:
https://github.com/ankidroid/Anki-Android/assets/52494258/4efe1dcb-633d-4f57-a7c2-9fab9ab8ede7
ModelFieldEditor.kt:
https://github.com/ankidroid/Anki-Android/assets/52494258/a3e0da17-dfd3-482c-afc9-e03efd08d8a8
Related to #14558 
Enabled the predictive back navigation and manually tested the changed screens

Implemented predictive back navigation for some screens

---

AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt

Just adds the previous code that was executed on deck selection which updated the active decks config.
* Fixes #14538 
* Probably also fixes #14548 
Checked the screen that called through the col.decks.active() method. Didn't run tests.

Fix active decks config not being updated on deck selection

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Media.kt

In 7a65160e0e23e20080091a30abdd4c05fc610e06 multiple error were timbered on what seems to be the normal successful path. I remove them to have a verbose timber instead, so they do not clutter the error space when trying to debug an actual error.

Replace Timber.e by Timber.v

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt

Search text is in hint text instead of normal text while filtering by tags
Fixes #14175 
use searchWithFilterQuery function in filterByTags function

Search text is in normal instead hint text

---

AnkiDroid/src/main/java/com/ichi2/utils/AssetHelper.kt
AnkiDroid/src/main/java/com/ichi2/utils/ContentResolverUtil.kt
AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt

I wanted to unit test it. But unit test failes when `Uri` is used. I can mock `Uri`, but this would remove most of the interest of the test. If I control that `Uri` returns what I expect, then I don't get any information from the test.
I corrected all uses of MimeTypeMap.getFileExtensionFromUrl even if I don't know of any bug at other places caused by incorrect extension identification.
Fixes #14696

Ensure media are detected correctly even with space in their name

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/utils/AssetHelperTest.kt
AnkiDroid/src/main/java/com/ichi2/utils/AssetHelper.kt

* #14700 wanted to add tests, but couldn't
* Add a test for #14696
----
* Use the debugger to determine the bad input
* Check test fails before #14700
* Ensure test passes after #14700
API 33 and API 24 emulator

Test: Ensure media are detected correctly even with space in their name

---

AnkiDroid/src/main/java/com/ichi2/anki/utils/Resources.kt
AnkiDroid/src/main/java/com/ichi2/preferences/SliderPreference.kt
AnkiDroid/src/main/res/values/10-preferences.xml
AnkiDroid/src/main/res/values/attrs.xml
AnkiDroid/src/main/res/xml/preferences_reviewing.xml

SliderPreference summaries didn't handle plurals
* Fixes #14572 
* Closes #14701
Upgrade `summaryFormat` attribute to handle both `string` and `plurals` resources
Emulator 34
[Screen_recording_20231111_152907.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/d37470f1-dbcd-4bd1-a56d-8e1b756d8ad5)
getResourceTypeName can be used to differentiate resource types. Source: ChatGPT

fix: handle plural strings in SliderPreference

---

AnkiDroid/src/main/java/com/ichi2/anki/pages/PageChromeClient.kt

The affected deck option was showing an alert in js which was translated  by the backend supporting code into a native  AlertDialog. This dialog handled only the happy path to communicate with the underlying js code, if the user cancelled the dialog in any other way the js code would never receive the expected call so the app hanged.
Also fixed a(most likely) issue with the other type of js dialog, the confirm call. I could have used the same listener as above, but I opted instead to make the native dialog as not cancellable to enforce the user to make a clear choice when asked for confirmation.
* Fixes #14687 
Manually verified the affected deck option.

Handle android dialog cancellation when used as frontend for js dialogs

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt

The deprecated onBackPressed() did the correct checks when user hit BACK. It also called the super.onBackPressed() which closed the activity although it was suposed to show an AlertDialog asking the user for action about his changes. In the Logcat you can see the window token exception being thrown when a dialog is shown using a bad activity context.
I replaced it with a OnBackPressedCallback as this doesn't have the issue with the super call. Note that this callback doesn't handle the predictive back navigation as it is always on.
* Fixes #14678 
Manually checked the bug scenario also tried adding a note and hitting BACK. Ran the tests.

Fix NoteEditor discarding changes on BACK when editing

---

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Note.kt

* #14692
If the 'Read Text' option is enabled, then opening a card preview (from the note editor) caused a crash
`readCardTts` tried to access `card.q(reload = true)`, which failed as the card was a preview with unsaved text.
* Fixes #14692
First I overrode the `readCardTts` function to no longer call `.q(reload = true)`, but then decided that it would be cleaner to subclass the `Card` class, as is done above for `PreviewerCard`
This was because there was additional AnkiDroid TTS Logic which didn't feel appropriate to replicate inside the previewer (selecting `pureAnswer`)
`Note.ephemeralCard` was only used once, so was an easy candidate to bring into the `EphemeralCard` class
After that, fix the class to handle `render_output` without crashing.
API 33 emulator: no more crashes. The …

14692: Fix crash in Note Editor Preview when 'Read Text' is enabled

---

AnkiDroid/src/test/java/com/ichi2/anki/CardTemplatePreviewerTest.kt

This was disabled in 7a65160e0e23e20080091a30abdd4c05fc610e06
Fixes up the tests, with 1 real breakage, and 1 fix
Test-only

tests: re-enable CardTemplatePreviewerTest

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.kt
AnkiDroid/src/test/java/com/ichi2/anki/CardTemplatePreviewerTest.kt

~~⚠️ Blocked on https://github.com/ankidroid/Anki-Android/pull/14716, needs a rebase before merge~~
Follow up to fix a `@NeedsTest` added in:
* PR #14714
* Commit 170c2d1ee5a354b42395e8c0de4363a1e1fc367b
Not the best test, but it fails before and passes after

tests: add - 'Read Text' + Note Editor Preview

---

AnkiDroid/src/main/java/com/ichi2/preferences/NumberRangePreferenceCompat.kt
AnkiDroid/src/main/res/values/10-preferences.xml
AnkiDroid/src/main/res/xml/preferences_reviewing.xml

* I was looking at the 'learn ahead' preference and two things bothered me:
* (unfixed) 0 mins == disabled, but the user is not notified
* (fixed) 1 min is shown as 1 mins
Use a summaryProvider, similar to:
* 55ee1d7f333feb8ffc126fbdadd5c795a2762fc9 
* #14704
* #14572

Preferences: add plurals for learn ahead/timebox

---

AnkiDroid/build.gradle
AnkiDroid/src/main/java/com/ichi2/anki/preferences/AboutFragment.kt
AnkiDroid/src/main/res/layout/about_layout.xml

Add apk build date in About Fragment near version number
* Fixes #14691 
Manually tested on emulator Pixel 3a

Add apk build date in About Fragment

---

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Note.kt
AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt
AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/NoteWithColTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/SchedulerTest.kt

Used the IDE inline functionality
Untested, unit tests should do

chore: inline note.model() => note.notetype

---

AnkiDroid/src/main/res/layout/permission_item.xml

Fixes #14653
I used the same padding of preferences switches as asked
I could not reproduce the issue, but I trust what I did and looks okay in the preview see

fix permission margin

---

AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/PermissionsActivity.kt
AnkiDroid/src/main/java/com/ichi2/themes/Themes.kt
AnkiDroid/src/main/res/layout/preferences.xml
AnkiDroid/src/main/res/values/theme_dark.xml

The status bar color didn't match the app bar in the new settings layout and in the permissions activity
* Part of #13878 
In the commits
[Screen_recording_20231115_060947.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/3752abf4-89f1-4df4-9aa8-d5ff3c7a4259)

Match `Settings` and `Permissions screen` app bar and status bar colors 

---

AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceActivity.kt
AnkiDroid/src/main/res/layout/activity_manage_space.xml

Making the app more beautiful
* Part of #13878 
Similar to what I did at #14603. Note that I don't want every toolbar in the app to be collapsible, but this one made sense, since this is a screen that use `Preference`s just like the Settings' one. Plus also it looked good IMO.
Emulator 24
[manage.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/3db03154-f105-410b-929b-7e75fff1b304)

feat: use material toolbar at manage space activity

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DialogHandler.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportReadyDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogsFactory.kt

The app has a system for restoring dialogs which appeared when the DeckPicker was not in focus, but it wasn't implemented for ExportReadyDialog. This fix copies the implementation of other dialogs that get restored. 
The code around DialogHandlerMessage needs to be refactored to handle the situation when the user doesn't enter the DeckPicker when a dialog is scheduled to be restored(like when using the widget)
Video with the fixed behavior:
https://github.com/ankidroid/Anki-Android/assets/52494258/85ef15c9-13bf-424c-86c3-ce2dd3bdbcd3
* Fixes #14734
Ran the tests, manually verified the bug scenario.

Fix ExportReadyDialog not being restored from notification

---

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/Undo.kt
AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt
AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/CustomButtonsSettingsFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtonStatus.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
AnkiDroid/src/main/java/com/ichi2/ui/RtlCompliantActionProvider.kt
AnkiDroid/src/main/res/drawable/ic_redo.xml
AnkiDroid/src/main/res/menu/reviewer.xml
AnkiDroid/src/main/res/values/01-core.xml
AnkiDroid/src/main/res/values/preferences.xml
AnkiDroid/src/main/res/xml/preferences_controls.xml
AnkiDroid/src/main/res/xml/preferences_custom_buttons.xml
AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/ViewerCommandTest.kt

Added option to redo card
* Fixes #14030 
In emulator 34, I undid a card answered then tapped the redo button. I did that with the control with ctrl+shift+z too

add redo button and control

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt

No longer necessary: we're API 23
* Replace the `const val` with a value-getter property
* Use the IDE to inline the value

chore: remove ACTION_PROCESS_TEXT compat

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/dialogs/ModelEditorContextMenuTest.kt
AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/NotificationChannelTest.kt
AnkiDroid/src/main/java/com/ichi2/anki/NotificationChannels.kt
AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/GestureProcessor.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DialogHandler.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ModelEditorContextMenu.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/ControlsSettingsFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/reviewer/MappableBinding.kt
AnkiDroid/src/main/java/com/ichi2/anki/reviewer/PeripheralKeymap.kt
AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt
AnkiDroid/src/main/java/com/ichi2/ui/CheckBoxTriStates.kt
AnkiDroid/src/main/java/com/ichi2/ui/GestureDisplay.kt
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerNoParamTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/ViewerCommandTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/ui/windows/permissions/PermissionsActivityTest.kt

- This uses a new language feature that was made stable in Kotlin 1.9. This was missed because of dependabot (which I don't like for precisely this reason).
- See here for details: https://kotlinlang.org/docs/whatsnew19.html#stable-replacement-of-the-enum-class-values-function
- Also I replaced Joiner in ViewerCommandTest with Kotlin's joinToString.
This doesn't fix or change any approach to anything.
- [N/A] You have commented your code, particularly in hard-to-understand areas
- [N/A] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [N/A] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

Replace values() function with entries property

---

AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt

- Use ServiceCompat.stopForeground, which does the version checks internally. You can see it [here](https://androidx.tech/artifacts/core/core/1.12.0-source/androidx/core/app/ServiceCompat.java.html#:~:text=public%20static%20void-,stopForeground,-(%40NonNull%20Service). It just does the same thing, but it's nicer to look at.
I made this change in another well-used and well-tested app over two years ago, and no user issue has been opened that has to do with my change. Which makes sense, because functionality didn't change. It'll be the same here, too.
- [N/A] You have commented your code, particularly in hard-to-understand areas
- [N/A] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [N/A] UI Changes: You have tested your change …

Use ServiceCompat.stopForeground

---

AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
AnkiDroid/src/main/res/drawable/ic_export_file.xml
AnkiDroid/src/main/res/menu/statistics.xml

Allow the stats web view to be exported as PDF or printed just like Anki
* Fixes #14689
Tested on google emulator 

feat: allow printing or exporting stats

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DialogHandler.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/ScopedStorageMigrationIntegrationTest.kt
AnkiDroid/src/test/java/com/ichi2/testutils/FilterLogStream.kt

I was a little frustrated with one repeated line of log spam in unit tests, then I cleaned up things a little more
* Define a filter to remove `Log` calls
* Disable collection log
* Disable `LifecycleMonitor` as we already have: https://github.com/ankidroid/Anki-Android/blob/8cf3cc306e405c5a4f54ef58c9e80eed1d542f87/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt#L194-L203
*  Hide a few more lines using `RobolectricDebugTree`
```diff
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/davidallison/.gradle/caches/transforms-3/e5c1eae594943ab3cbc66dbcbaedd199/transformed/slf4j-timber-3.1-runtime.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/davidallison/.gradle/caches/transforms-3/05ba5ab9b8ca946a61743b2d …
```

tests: reduce log spam

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt

`startActivityForResult` is deprecated. We want to replace these calls using the new Register  For Activity Result APIs. 
I removed all instances of `AnkiActivity.startActivityForResultWithAnimation`, and
`AnkiActivity.startActivityForResultWithoutAnimation` in DeckPicker.kt, and replaced them with calls to `AnkiActivity.launchActivityForResultWithAnimation`, which utilized the new API underneath. (The function name could be changed, because it does handle non-animations too)
Related: #8602 
I ran unit tests and I manually tested the functionality on an emulator.
In `onActivityResult`, there is a specific result code check that's used for every launched activity result. In order to capture this for every new `ActivityResultLauncher` I created a `DeckPickerActivityResultCallback` inner …

8602 start activity for result new api

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt

The old code was only suspending cards with QUEUE_TYPE_NEW, QUEUE_TYPE_LRN, QUEUE_TYPE_REV, QUEUE_TYPE_DAY_LEARN_RELEARN or QUEUE_TYPE_PREVIEW. The code was changed to suspend any cards that weren't already suspended, otherwise it will unsuspend previously suspended cards.
* Fixes #14751
Ran the tests, manually verified the bug scenario in the app.

Fix card not being suspended after first being buried

---

build.gradle

Just heading towards a release, and I like to get all the possible things in there - so getting the backend bump in as well even though it is nominally dev-only

build(deps): bump backend to 0.1.29-anki23.10.1

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/Previewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/pages/CardInfo.kt
AnkiDroid/src/test/java/com/ichi2/anki/PreviewerTest.kt

I've got a pending PR to convert the `CardBrowser` to a ViewModel style architecture.
This is going to be a squash merge job, but there are a number of 'obvious' commits which can be split out, these mean that fewer files are affected in the merge
* We don't want the ViewModel to have knowledge of the `Context` class
* So build a context-agnostic helper class, and define an extension method in the activity which accepts a `Context`
* use `bundleOf` 

refactor: intents

---

AnkiDroid/build.gradle
AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/LayoutValidationTest.kt
AnkiDroid/src/main/java/com/ichi2/anki/IntroductionActivity.kt
AnkiDroid/src/main/res/layout/introduction_activity.xml

It didn't have any special use that we couldn't deal with ease without it
Emulator 24. Haven't tested CI because I'm leaving home right now
[intro.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/607ba15d-d609-4b22-9eec-1b0c0931e271)

refactor: remove appIntro dependency

---

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt

This PR provides the implementation for the new `stopTimerOnAnswer` deck config option.
Note: from my testing it seems that if the user clicks show answer and then goes to the main screen and the app is destroyed while in background, when coming back the reviewer will show again the question so I didn't do anything to save the new property "stopTimerOnAnswer" and the timer will start running from the beginning.
* Fixes #14588 
Ran the tests, manually verified the timer behavior in Reviewer.

Add implementation for "stopTimerOnAnswer" deck configuration option

---

.github/workflows/publish.yml
api/build.gradle.kts
jitpack.yml

jitpack uses it's own JDK version to build things, and they lag behind sometimes
Since we started checking JDK versions and requiring newer JDKs to build in jitpack, our builds have been unreliable there
This uses jitpack's ability to configure a build via jitpack.yml and jitpack's config powers of sdkman to install and use a JDK we can build with
* Related #14787 - I don't think it fixes the whole issue but hopefully it builds
create a config file sort of like: https://docs.jitpack.io/building/#java-version
...however it is not always guaranteed that jitpack will have what we want as a named version. So the approach I take is more like: https://github.com/19MisterX98/SeedcrackerX/blob/master/jitpack.yml
Instead of relying on a named version I use [sdkman ](https://sdkman.io/usage) (which …

build(api): pin JDK in jitpack, fix publish tasks

---

AnkiDroid/src/main/java/com/ichi2/anki/ReviewerServer.kt

I believe that a value not found should be an error. Simply because that's what one may look for when debugging.
And also, it's important to state when the value is found. Otherwise, when looking at log, it's not clear that the silence mean the value was actually found without looking at the codebase.
In the bug I was trying to debug right now, I wanted to check whether it was a problem with unfound media, or an issue with a media that android does not render properly. This saved me time.

NF: more timbers for getting data from http server

---

AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt
AnkiDroid/src/main/res/layout/reviewer_whiteboard_editor.xml

Using Background Tint to apply color to the background in the whiteboard this issue/bug was introduced after Brayan switched to material3, anyways `backgroundTint` applies the color.
The background attribute directly changes what's displayed in the background, while backgroundTint applies a color modification on top of the background drawable.
* Fixes #14802
Google emulator 

use backgroundTint to apply color

---

AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/ConfigTest.kt

Proving that #14096 is fixed
* Fixes #14096
Already fixed in
* #14171
* 7a65160e0e23e20080091a30abdd4c05fc610e06
* unsquashed: (a6dce65ab5ac2c43783bfc0b96ee7ec00393121e)
This adds regression cover for Issue 14096
Test-only

regression tests: corrupt 'curDeck' value (Issue 14096)

---

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/reviewer/CardMarker.kt
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt

* #14656
* Partially #14656
`AbstractFlashCardViewer::opExecuted` performs `updateCardAndRedraw` unless `handler === this`
`updateCardAndRedraw` flips the card to the question
Since we handle the state change: `onMark` -> `onMarkChanged` we don't need the call to `updateCardAndRedraw`
Added a couple unit tests, tested briefly on device

fix: 'mark' should not flip card to question

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserOrderDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/model/SortType.kt
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt

I'm about to perform a large refactoring on CardBrowse, this large change will be squash merged
This change reduces the impact of this squash, allows a more thorough review and reduces the number of files changed
* Extracting methods to a class, then looking through the logic and seeing what can be simplified

refactor: extract SortType

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialogListener.kt
AnkiDroid/src/main/java/com/ichi2/anki/model/CardStateFilter.kt
AnkiDroid/src/main/res/layout/tags_dialog.xml
AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogTest.kt

TagsDialog contains a confusing 'option' parameter
This maps to `[All Cards, New, Due]`: The card state 
Anki has moved to a much larger collection of states so there is also expected extension here
Now, this probably doesn't belong in TagsDialog:
* Not used in Note Editor/CardViewer
but for now, refactor to explain 'option':
This is part of a larger CardBrowser refactoring 
After CardBrowser is completed, there will likely be opportunity to fix this use case of TagsDialog as it will be used in one place
* Introduce `CardStateFilter` class
* Fix too many API breakages
Unit test + briefly on an API33 emulator

refactor: Extract 'CardStateFilter'

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BrowserOptionsDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/model/CardsOrNotes.kt
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt

I have a pending large refactoring of `CardBrowser` which will be squashed, this extracts a few changes to preserve the history of functional changes, primarily the classes outside `CardBrowser`
* Commit 1: Change a `CardCollection` to a `List` - primarily for #11889 to churn less code
* Commit 2:
* Move from Preference to Config Variable so cards/notes will sync (note: the Config is reversed)
* Convert to an enum for better documentation
* Remove from `restoreInstanceState`, as it's defined by the collection config.
CI only

refactor: CardBrowser

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerRefresh.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt

* Fixes #14414
* Fixes #14616
* Fixes #14496
* Fixes #14788
* Probably Fixes #14480
* code to stop sounds from playing if the activity is in the wrong state
* I suspect this occurs after a WebView OOM in the background 
* defer `opChanges` handling to after `onResume()`
* fix `Sounds.kt` breakage
* Add audio to a note
* Change to the answer
* Audio now stops playing
----
* switch to card browser
* switch back
No audio is played
----
* switch to card browser
* mark a note
* audio is played after returning to card viewer

fix: issues with sound playing unexpectedly

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportFileSelectionFragment.kt

`startActivityForResult` is deprecated. We want to replace these calls using the new Register For Activity Result APIs.
- removed the last remaining request code dependencies in DeckPicker (`PICK_APKG_FILE`, `PICK_CSV_FILE`), and replaced with their equivalent `ActivityResultLaunchers` 
- removed deprecated `onActivityResult` function from `DeckPicker` 
- `ImportFileSelectionFragment.openImportFilePicker` needed a way to grab the `ActivityResultLauncher` from the activity, so I created 2 interfaces fetch the launcher, one for APKG imports and one for CSV imports. 
- Created `ImportFileType` enum to signal to `ImportFileSelectionFragment.openImportFilePicker` which launcher it should look for
Related: #8602 
I ran unit tests and I manually tested the functionality on an emulator.
Ideally, …

8602 - Finished fully migrating DeckPicker over to using registerForActivityResults API instead of the deprecated startActivityForResult

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/utils/SyncStatus.kt

* #14355 
* Fixes #14355 
* Fixes #14828
* remove code from a `withCol` block
* take dae's suggestion and move to `CollectionManager.getBackend().syncStatus(auth)`, understanding that it can throw
Briefly tested on an API 33 emulator

fix: Loading the deck count and toolbar takes more time if internet is enabled

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt

We needed a call to `System.loadLibrary("rsdroid")`
* Fixes #14621
* Fixes #14829
```
java.lang.UnsatisfiedLinkError: No implementation found for byte[][] net.ankiweb.rsdroid.NativeMethods.openBackend(byte[]) (tried Java_net_ankiweb_rsdroid_NativeMethods_openBackend and Java_net_ankiweb_rsdroid_NativeMethods_openBackend___3B) - is the library loaded, e.g. System.loadLibrary?
at net.ankiweb.rsdroid.NativeMethods.openBackend(Native Method)
```
* Uninstall AnkiDroid 'stable' from my 'stable' slot
* Install AnkiDroid 'alpha'
* Figure out getting the API tested
* Verify it was just not loading `rsdroid`
Apply the following and comment/uncomment the line in the ContentProvider
```patch
Subject: [PATCH] fix: API crashes with UnsatisfiedLinkError
Enables testing API
---
Index: …
```

fix: API crashes with UnsatisfiedLinkError

---

lint.gradle

'WrongThread' output 100+ lines of 'Information' which obscured the error
* Fixes #14853
Remove these in CI
<details><summary>Before</summary>
```
davidallison@Davids-MBP Anki-Android % ./gradlew lint
> Task :AnkiDroid:lintReportAmazonDebug
Wrote HTML report to file:///Users/davidallison/StudioProjects/Anki-Android/AnkiDroid/build/reports/lint-results-amazonDebug.html
> Task :AnkiDroid:lintAmazonDebug FAILED
/Users/davidallison/StudioProjects/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt:2541: Information: Method all must be called from the worker thread, currently inferred thread is UI thread [WrongThread]
val tags = ArrayList(getColUnsafe.tags.all())
~~~~~~~~~~~~~~~~~~~~~~~
/Users/davidallison/StudioProjects/Anki-Android/AnkiDroid/src/main/java/com/ichi2/ …
```

chore(lint): cleanup CI output on failure

---

AnkiDroid/src/main/java/com/ichi2/anki/NotificationChannels.kt
AnkiDroid/src/main/java/com/ichi2/anki/TtsParser.kt
AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnkiDroidCrashReportDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/TTS.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsArrayAdapter.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsList.kt
AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt
AnkiDroid/src/main/java/com/ichi2/compat/customtabs/CustomTabActivityHelper.kt
AnkiDroid/src/main/java/com/ichi2/libanki/backend/exception/DeckRenameException.kt
AnkiDroid/src/main/java/com/ichi2/ui/ButtonItemAdapter.kt
AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
api/src/main/java/com/ichi2/anki/FlashCardsContract.kt
api/src/main/java/com/ichi2/anki/api/AddContentApi.kt
lint-rules/src/main/java/com/ichi2/anki/lint/rules/CopyrightHeaderExists.kt

I saw one instance of this and it was distracting. Fixed all to stop future distractions 
* Search for:
* `{@`
* `<pre>`
* `&lt;` and `&gt;` 
* Change to KDoc equivalents
* Fixup issues found
* 4 spaces before a line removes KDoc links: `[ClassName]` 
* Added a few missing links
* 4 spaces before a line removes KDoc links: `[ClassName]` 
* KDoc doesn't support liking a specific overload

Kotlin Cleanup: KDocs

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/SharedPreferencesProvider.kt

For use in ViewModels to abstract out `AnkiDroidApp.instance`
Suggested in:
* https://github.com/ankidroid/Anki-Android/pull/14843#discussion_r1412322760

chore: add SharedPreferencesProvider

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt

`startActivityForResult` is deprecated. We want to replace these calls using the new `registerForActivityResult` APIs.
- Created common NoteEditorActivityResultCallback inner class to pass to registerForActivityResult function. This will capture the common result code check behavior that was being done in onActivityResult and apply it to every ActivityResultLauncher when using the new registerForActivityResult API.
- Replaced startActivityForResult for REQUEST_ADD with registerForActivityResult API implementation.
- Replaced startActivityForResult for REQUEST_MULTIMEDIA_EDIT request code with registerForActivityResult API implementation.
- Replaced startActivityForResult for REQUEST_TEMPLATE_EDIT request code with registerForActivityResult API implementation.
- Removed onActivityResult, …

8602 - NoteEditor startActivityForResult Migration

---

AnkiDroid/build.gradle
AnkiDroid/src/androidTest/java/com/ichi2/anki/ReviewerTest.kt
AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/InstrumentedTest.kt
AnkiDroid/src/main/java/com/ichi2/anki/ReviewerServer.kt
AnkiDroid/src/main/java/com/ichi2/annotations/DuplicatedCode.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt

Currently, the `customData` that gets passed into the custom scheduler when [runStateMutationHook](https://github.com/ankidroid/Anki-Android/blob/v2.17alpha8/AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt#L1087) is called is always empty.
According to the [SchedulingState](https://github.com/ankitects/anki/blob/23.10.1/proto/anki/scheduler.proto#L115-L118) protobuf message in Anki 23.10.1, it says
```protobuf
message SchedulingState {
// ...
oneof kind {
Normal normal = 1;
Filtered filtered = 2;
}
// The backend does not populate this field in GetQueuedCards; the front-end
// is expected to populate it based on the provided Card. If it's not set when
// answering a card, the existing custom data will not be updated.
optional string custom_data = 3;
}
```
Hence, we need to populate …

fix(ReviewerServer): return scheduling states with customData

---

AnkiDroid/src/main/java/com/ichi2/anki/Import.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportFileSelectionFragment.kt

Refactors and simplifies the dialog used for choosing the type of import, the previous implementation was using RecursivePictureMenu which is too complex for this dialog.
The goal is to remove RecursivePictureMenu(will also remove its tests that extend RobolectricTest).
See the images below, before and after. Note that I removed the icons, I think they are pretty useless especially as one is duplicated. Will add them back if requested.
Verified the dialog, ran the tests.

Refactor ImportFileSelectionFragment as a standalone DialogFragment

---

.github/workflows/tests_emulator.yml
AnkiDroid/build.gradle
AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.kt
AnkiDroid/src/androidTest/java/com/ichi2/anki/dialogs/ModelEditorContextMenuTest.kt
AnkiDroid/src/androidTest/java/com/ichi2/anki/reviewer/PeripheralKeymapTest.kt
AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/InstrumentedTest.kt
build.gradle

Record the screen for emulator tests to help debug flaky tests in CI
N/A
According to the Emulator screen record [docs](https://developer.android.com/studio/run/emulator-record-screen), we can run `adb emu screenrecord start --time-limit 10 [path to save video]/sample_video.webm`
N/A
N/A

ci: record screen for emulator tests

---

AnkiDroid/src/main/res/layout/tags_dialog_title.xml
AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogTest.kt

The tags dialog has a blue bar in Black theme, which looks ugly.
Similar to https://github.com/ankidroid/Anki-Android/issues/14642
* Fixes _Link to the issues._
Similar to https://github.com/ankidroid/Anki-Android/pull/14644
Untested
Well, I am not a dev. But, I still made this PR because it took almost the same effort as creating an issue.

Fix app bar color in tags dialog

---

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt

Timer still counts when when app resume after user have seen the answer , and timer didn't start when answer was not shown after resuming app
* Fixes https://github.com/ankidroid/Anki-Android/issues/14874
https://github.com/ankidroid/Anki-Android/assets/101629190/9406a3f3-c665-4d22-af97-54995d75d12b

stop timer on resuming the app after ans

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt

`startActivityForResult` is deprecated. We want to replace these calls using the new `registerForActivityResult` APIs.
- In `AbstractFlashcardViewer`, 
- Created common `FlashCardViewerResultCallback` inner class to pass to `registerForActivityResult` function. This will capture the common result code check behavior that was being done in `onActivityResult` and apply it to every `ActivityResultLauncher` when using the new `registerForActivityResult` API. There was only one request code being processed, but the pattern is consistent with the other classes that were updated. 
- In `FlashCardViewerResultCallback`, gave the lambda a default do-nothing implementation. The ADD_NOTE request code used in Reviewer doesn't specifically do anything with a result, but the common checks that …

Issue 8602, Reviewer startActivityForResult Migration

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/AndroidTtsPlayer.kt
AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
AnkiDroid/src/main/java/com/ichi2/anki/ReadText.kt
AnkiDroid/src/main/java/com/ichi2/anki/TtsVoices.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TtsVoicesDialogFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/viewmodel/TtsVoicesViewModel.kt
AnkiDroid/src/main/java/com/ichi2/compat/UtteranceProgressListenerCompat.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Tts.kt
AnkiDroid/src/main/java/com/ichi2/utils/UiUtil.kt
AnkiDroid/src/main/res/color/mtrl_list_item_tint.xml
AnkiDroid/src/main/res/color/text_input_background.xml
AnkiDroid/src/main/res/drawable/baseline_content_copy_24.xml
AnkiDroid/src/main/res/drawable/baseline_download_for_offline_24.xml
AnkiDroid/src/main/res/drawable/baseline_offline_pin_24.xml
AnkiDroid/src/main/res/drawable/baseline_wifi_24.xml
AnkiDroid/src/main/res/layout/dialog_tts_voices.xml
AnkiDroid/src/main/res/layout/dialog_tts_voices_voice.xml
AnkiDroid/src/main/res/values/02-strings.xml

* Handles `{{tts-voices:}}`
* Partially #14358
* I wanted `{{tts-voices:}}`, but since retrieving voices required a `suspend` function, it was better to open a new window rather than do as Anki does and list them on the Card
* Also, Android has a LOT more voices: can be over 400 
* So make a dialog, and design it well, special thanks to emma on Dicord, along with the usual suspects
* Tap a voice to listen + change the spoken text
* Chips to filter online/uninstalled voices
* Typically, we want to discourage online, and enforce installing uninstalled voices 
* But since Android is terrible, give users an option to 'copy' if feasible
* Error dialog if a voice fails to play
* + link to our manual section
* Refreshing the list every 2 seconds
* Tapping an uninstalled voice should start a …

feat: TTS Support ({{tts-voices}})

---

AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Notetypes.kt

After a sync, styling is not updated if the card was viewed beforehand
* #14827
* Fixes #14827
The notetype cache needed to be cleared after a sync
API 33 emulator & Anki Desktop
https://github.com/ankidroid/Anki-Android/issues/14827#issuecomment-1828979515

fix: Syncing handles notetype style changes

---

.github/workflows/lint.yml
.github/workflows/tests_emulator.yml
.github/workflows/tests_unit.yml

Merge queues are available to everyone now and may fit us well as a workflow change as we semi-frequently have non-rebased PRs go into main that break main after some intermediate PR made an incompatible change
- ref #14895 
- ref [`@MikeHardy time to try out Merge Queues?`](https://discord.com/channels/368267295601983490/701922522836369498/1182345774772785202)
- simplify our CI  - maybe controversial - but it really bothers me that i18n_sync changes require a manual close/reopen. That's just ridiculous. I don't think our "CI avoidance" optimization is worth it
- add the [new `merge_group` event](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue) as a workflow trigger
It is CI so testing is …

Enable merge queue trigger / remove CI-avoidance optimization event filters

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardHtml.kt
AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/HtmlGenerator.kt

* #14656
* Part of #14656
* Add a method: `reloadWebViewContent`
* remove 'reload' parameter and follow through
API 30 emulator

fix: adding tags should not unflip card

---

AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/GestureProcessor.kt
AnkiDroid/src/main/java/com/ichi2/anki/reviewer/Binding.kt
AnkiDroid/src/main/java/com/ichi2/anki/reviewer/MappableBinding.kt
AnkiDroid/src/main/java/com/ichi2/anki/reviewer/PeripheralKeymap.kt
AnkiDroid/src/main/java/com/ichi2/ui/KeyPicker.kt
AnkiDroid/src/main/java/com/ichi2/utils/StringUtil.kt
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerNoParamTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/reviewer/BindingTest.kt

* It's easier to reason about 3 classes with 1/2 parameters than 1 with 4 optional parameters
* I'm /probably/ going to need to add another subclass to handle #14282, we haven't transformed joysticks into buttons yet
* We will probably want to support bluetooth headphones, also through this interface
Move the class to a `sealed interface`, then fix failures, a few obvious refactorings in the mix
This area of code is well unit-tested
`buildString { }` is awesome

refactor: Key Bindings

---

AnkiDroid/build.gradle
AnkiDroid/src/androidTest/java/com/ichi2/anki/ReviewerTest.kt
AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/InstrumentedTest.kt
AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/ReviewerServer.kt

Previously, we did not wait for the `webView.evaluateJavascript()` call to complete and allow enough time for the messages to be passed in and out of the webview before showing the ease buttons
Now, we show the ease buttons only after the custom scheduler has completed its execution. If the custom scheduler is not set, then it will behave as before and show the ease buttons immediately
N/A
Hide the ease buttons until the custom scheduler has completed its execution. I have used Anki Desktop 23.10.1 as a reference https://github.com/ankitects/anki/blob/23.10.1/qt/aqt/reviewer.py#L707
`./gradlew jacocoUnitTestReport` and `./gradlew jacocoAndroidTestReport` has passed on my machine with the emulator `Pixel_3a_API_34_extension_level_7_x86_64`
N/A

fix: show card answer after custom scheduler completes

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTest.kt
AnkiDroid/src/androidTest/java/com/ichi2/anki/TestUtils.kt
AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Media.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Note.kt
AnkiDroid/src/main/java/com/ichi2/libanki/NotetypeJson.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Notetypes.kt
AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt
AnkiDroid/src/main/java/com/ichi2/utils/StringUtil.kt
AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/AbstractSchedTest.kt

13 less usages of `@KotlinCleanup` (202 -> 189)
~~## Blocked On~~
* I don't want this to affect users by adding conflicts 
* ~~https://github.com/ankidroid/Anki-Android/pull/14881~~ This now has a conflict, ignoring
Unit tests

Kotlin Cleanup: libAnki & androidTest

---

AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DebugInfoService.kt

* Improves #14909 - pending discussion
* Expose Build Config we already have
* remove a constant value from the output
New result:
```
AnkiDroid Version = 2.17alpha8-debug (792f444c0529495d07dbc4b055b20e3188010e36)
Backend Version = 0.1.30-anki23.10.1
Android Version = 13 (SDK 33)
ProductFlavor = amazon
Manufacturer = Google
Model = sdk_gphone64_arm64
Webview User Agent = Mozilla/5.0 (Linux; Android 13; sdk_gphone64_arm64 Build/TE1A.220922.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.71 Mobile Safari/537.36
ACRA UUID = 3c6c2b16-05dd-48a7-81e2-7667f5a7eeaa
Crash Reports Enabled = false
```

feat: add backend version to debug info & cleanup

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
AnkiDroid/src/main/java/com/ichi2/libanki/SoundKt.kt

* Fixes #14866
The new backend returned `[anki:play:q:0]`
We added a new method as  `browser = true` wasn't appropriate as this either strips the tags, or removes `[sound:]`
Added a unit test
safe calls: `toIntOrNull()`, `getOrNull(index)`

fix(api): render [sound:] tags

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/pages/AnkiServer.kt
AnkiDroid/src/main/java/com/ichi2/anki/pages/CongratsPage.kt
AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/pages/PageWebViewClient.kt
AnkiDroid/src/main/java/com/ichi2/anki/pages/PagesActivity.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt
AnkiDroid/src/main/res/layout/studyoptions_fragment.xml
AnkiDroid/src/main/res/values/01-core.xml
AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/SchedulerTest.kt

* Fixes #14361 
* Fixes https://github.com/ankidroid/Anki-Android/issues/14662
Add the congrats screen from Anki Desktop.
Note that a part of the original screen isn't shown because we don't support (and [ideally shouldn't](https://github.com/ankidroid/Anki-Android/issues/14361#issuecomment-1701946364)) `bridgeCommand`, which is a legacy python-javascript bridge used in the desktop version.
I actually tried to do replace it with POST requests in the desktop's repo, but got some trouble when trying to build the string with a link calling the backend method in Svelte, which is probably due to my limited knowledge about Js/Svelte/How Anki Desktop works
So I left a TODO, which sould suffice for now
Emulator 31 …

feat: use the backend's congrats screen

---

AnkiDroid/src/main/java/com/ichi2/anki/pages/PageChromeClient.kt

```
Test run failed to complete. Instrumentation run failed due to Process crashed.
Logcat of last crash:
Process: com.ichi2.anki.debug, PID: 3649
android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@4a73095 is not valid; is your activity running?
at android.view.ViewRootImpl.setView(ViewRootImpl.java:1068)
at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:409)
at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:109)
at android.app.Dialog.show(Dialog.java:340)
at androidx.appcompat.app.AlertDialog$Builder.show(AlertDialog.java:1008)
at com.ichi2.anki.pages.PageChromeClient.onJsAlert(PageChromeClient.kt:63)
at ms.run(chromium-TrichromeWebViewGoogle.apk-stable-410410686:8)
at …
```

HACK: fix CI: BadWindowTokenException

---

AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt

Currently, the first time you sync with ankiweb it will typically redirect you to one of it's farm of servers with different hostnames
That endpoint change wasn't handled gracefully before resulting in a 400 error "missing original size"
* Fixes #14651
Take @dae advice and if the endpoint is different, create a new sync auth object then use that for syncing
You can trigger the problem / simulate a first-login/first-sync by clearing all AnkiDroid data then logging in to AnkiWeb and attempting to sync. It will trigger the error without this patch
After applying this patch, it works the first time
Sometimes I do not feel like I learned anything.

fix: 400 error on first sync as sync endpoint is moved

---

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/ReviewerServer.kt

* Fixes #14928
handle class inheritors better
Open the previewer and don't crash

fix: previewer crash when cast to CardTemplatePreviewer

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt

* split out from https://github.com/ankidroid/Anki-Android/pull/14843
* rename 'check' -> 'select'
* rename card -> rows: although we currently use cards, we're not going to in the new world
Unit tests, briefly tested selection on API 33 emulator

Browser: refactor selected rows

---

AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt

Our acralyzer crash database is pretty full of backend sync exceptions.
They fall largely into 3 categories:
- some sort of HTTP / network error -> BackendNetworkException
- account needs to be reconfirmed error -> BackendSyncException
- a grab bag category that has things like "only one copy of anki may sync at a time, come back later" etc -> frequently BackendSyncException
* Fixes no issue was logged but it was discussed - sync errors in general shouldn't generate a crash report and they are a *huge* percentage of our crash reports
**UPDATED from original push**
1- refactor exception handler in `launchCatchingTask` for multi-exception-type + same-handling-block ability
2- add ability for CoroutineHelpers existing error display to only send crash reports optionally, but default to old …

fix: show sync errors to user but no crash report

---

AnkiDroid/src/main/java/com/ichi2/anki/preferences/AboutFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DebugInfoService.kt
AnkiDroid/src/main/res/layout/about_layout.xml
build.gradle

@user1823 asserted that it can be a little confusing trying to figure out which backend version was in use inside AnkiDroid, even to the point of the user-visible name of the version (e.g. "23.10.1") being ambiguous as that name changed a couple times during the alpha series such that the commit hash was the only *true* disambiguator
I'm inclined to agree, and also agree with the separate point that including it on debug information only (which has to be pasted somewhere so it is visible) is not that helpful as users cannot easily see it, so they cannot easily reason about it or use the information for user-to-user help or self-help
This is important because there *are* incompatibilities across other parts of anki ecosystem when the versions don't match so determining backend version is …

feat: add backend version info in useful places

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/ReviewerTest.kt

Sometimes, after adding a card to the database, the deck that gets created takes awhile to load when in the Deck Picker screen. We should wait and check to make sure that the deck is there before clicking on it
Hence, we sometimes see the failure:
```
com.ichi2.anki.ReviewerTest > testCustomSchedulerWithCustomData[test(AVD) - 11] FAILED 
androidx.test.espresso.PerformException: Error performing 'performing ViewAction: single click on item matching: holder with view: (view is an instance of android.view.ViewGroup and has descendant matching an instance of android.widget.TextView and view.getText() with or without transformation to match: is "Default")' on view 'view.getId() is <2131296705/com.ichi2.anki.debug:id/files>'.
at androidx.test.espresso.PerformException$Builder.build(PerformExcept …
```

test: wait for deck to load before clicking on it

---

.github/workflows/lint.yml
.github/workflows/tests_emulator.yml
.github/workflows/tests_unit.yml

otherwise the concurrency gate means the push events and merge_group events enter into a race which results in merge queue failure at times
Issue noted on Discord by @BrayanDSO 
Investigate the "checkout" step of workflow runs from both the push event and the merge_group event, notice that they have the same "github_ref" value, which implies the concurrency key will evaluate to the same value
Deduce that there is a concurrency race between the runs from the two events, decide to ignore merge_group branches from the push event so there is no longer a race
It has not been tested, just deduced - we'll see how it works in practice. Hopefully it works
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-branches …

test(ci): ignore merge queue branch push events

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTest.kt
AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/InstrumentedTest.kt

Sometimes the emulator tests are failing because the application gets forcibly killed by Android. In the logs, we are seeing
JNI critical lock held for 33.004ms on
Thread[1,tid=3832,Runnable,Thread*=0x741a9345dbe0,peer=0x71cf55b8,"main"]
which seem to indicate that the Rust backend and database connections to the collection are leaking across tests and are causing a deadlock. To fix this, we make sure to discard the Rust backend and close the collection after each test
* https://github.com/ankidroid/Anki-Android/issues/14940
Using the setup/teardown code from RobolectricTest as a reference: https://github.com/ankidroid/Anki-Android/blob/0f8bfbd7fde9640343093615182abb6f43b9763a/AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt#L94-L177 we close the collection and rust backend after …

test: fix JNI critical lock held error in instrumentation tests

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt

* split from https://github.com/ankidroid/Anki-Android/pull/14843/
* This removes a number of references to `mCards`
* We'll be changing this to type `CardOrNoteId` later, so combining reference methods is useful in reducing breakages  
* Reviewable, not mergeable as it's blocked on https://github.com/ankidroid/Anki-Android/pull/14900
* After this goes in, some more `mCards` references may be removed
Unit test only

Browser: refactor `mCards` partially

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt

Alert the developer when the WebView version is too old to support Anki HTML pages.
* Fixes #14702 
Show a Snackbar with a warning if the Android WebView version is detected to be older than the oldest supported version (currently version 77).
I tried it with two separate emulators, one with a WebView version <77, one emulator with a newer version and a physical phone, and the warning appears as it should.
I also ran the gradlew jacocoTestReport. It keeps failing for a few tests but they're always different ones and I can't find the connection to the code I added, so if anyone knows why tests are failing, please tell me, and I will fix it. I'm using the Medium Phone Emulator in Android Studio with API version 24 (Android 7) to test.
It's not possible to update the WebView version on …

Warning when WebView (<77) is outdated

---

AnkiDroid/src/test/java/com/ichi2/anki/analytics/PreferencesAnalyticsTest.kt

to avoid additional work of adding the key of dev options
Part of #14949

tests: remove dev options from PreferencesAnalyticsTest

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/Gamepad.kt

* #14975
* button presses were not passed to the WebView
* `navigator.getGamepads()` requires seeing a button press before returning results
* therefore the array was `[null, null, null, null]`
* Fixes #14975
To fix this, pass through unhandled gamepad inputs to the WebView
> To mitigate fingerprinting, getGamepads() returns an empty list before a gamepad user gesture has been seen. [FINGERPRINTING-GUIDANCE]
https://w3c.github.io/gamepad/#dom-navigator-getgamepads

fix: navigator.getGamepads() does not work

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt
AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicMediaClipFieldController.kt
AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicTextFieldController.kt
AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/IFieldController.kt
AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt

After #14912 and #14915 were merged, some dead code was created around the deprecated `startActivityForResult` functionality.
- In `CustomStudyListener`, changed `startActivityForResultWithoutAnimation` to just `startActivityWithoutAnimation`. The only instance of this being used was in `CustomStudyDialog::onLimitsExtended`, and the request code (`AnkiActivity.REQUEST_REVIEW`) was not being used anywhere else, i.e., the result if there ever was one was not getting captured for processing.
- From the `CustomStudyListener` change, this allowed for the removal of `startActivityForResult`, `startActivityForResultWithoutAnimation`, and `startActivityForResultWithAnimation` from AnkiActivity
- Removed the `IFieldController::onActivityResult` function. All the controllers that implemented the …

8602 remove dead code from start activity for result migration

---

.idea/dictionaries/davidallison.xml
AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/reviewer/Binding.kt
AnkiDroid/src/main/java/com/ichi2/anki/reviewer/MappableBinding.kt
AnkiDroid/src/main/java/com/ichi2/anki/reviewer/MotionEventHandler.kt
AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt
AnkiDroid/src/main/java/com/ichi2/compat/CompatV23.kt
AnkiDroid/src/main/java/com/ichi2/compat/CompatV24.kt
AnkiDroid/src/main/java/com/ichi2/compat/CompatV34.kt
AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt
AnkiDroid/src/main/java/com/ichi2/ui/AxisPicker.kt
AnkiDroid/src/main/java/com/ichi2/ui/AxisSelector.kt
AnkiDroid/src/main/java/com/ichi2/ui/AxisValueDisplay.kt
AnkiDroid/src/main/java/com/ichi2/utils/DisplayUtils.kt
AnkiDroid/src/main/java/com/ichi2/utils/HashUtil.kt
AnkiDroid/src/main/res/layout/axis_display.xml
AnkiDroid/src/main/res/layout/dialog_axis_picker.xml
AnkiDroid/src/main/res/values/10-preferences.xml
AnkiDroid/src/test/java/com/ichi2/anki/reviewer/BindingAndroidTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/reviewer/BindingTest.kt

We want to be able to map joystick/trigger inputs to commands
This only handles them as button presses, not allowing scrolling
* Fixes #14282
* Fixes #14965
1) Define a screen which listens for motion events and adds a visual selector to the screen if these are detected
2) Define an Axis: the Android MotionEvent works on a historical basis allowing us to specify an axis and obtain the historical values of the MotionEvent
3) Define a threshold: some MotionEvents are unidirectional (pedals/triggers), others are bidirectional X-Axis on a joystick  this can either be -1.0 or 1.0 (displayed as `[+]` or `[-]`)
4) An AxisButtonBinding is defined as the tuple (Axis, Threshold)
5) Ensure the listener screen only allows selecting an Axis if
the threshold has been reached (to stop a user selecting …

feat: Joystick/Trigger/MotionEvent handling

---

AnkiDroid/src/main/java/com/ichi2/anki/pages/AnkiServer.kt

I was frustrated by 10 new warnings per card flip on a standard 'Basic' card. There were no nice solutions, so this was a hack. It's also faster
```diff
- 02:31:01.890  System 	W  A resource failed to call close. 
- 02:31:01.892  System 	W  A resource failed to call end. 
- 02:31:01.893  System 	W  A resource failed to call end. 
- 02:31:01.893  System 	W  A resource failed to call end. 
- 02:31:01.893  System 	W  A resource failed to call end. 
- 02:31:01.893  System 	W  A resource failed to call end. 
- 02:31:01.893  System 	W  A resource failed to call end. 
- 02:31:01.893  System 	W  A resource failed to call end. 
- 02:31:01.893  System 	W  A resource failed to call end. 
- 02:31:01.893  System 	W  A resource failed to call end. 
```
* Fixes #14924
* Perf test
* disable GZip, as it's …

chore: speed up server & fix log spam

---

AnkiDroid/src/main/java/com/ichi2/libanki/SoundKt.kt

avRefsToPlayIcons was modified to match the desktop code, which works well in the new previewer because it also uses the desktop code.
The issue is that I tested if there were regressions in the reviewer with a deck that has a custom `.replayButton` style and I didn't know that. This way, I caused these big black circles
* Closes #15001
Add back `fill` to the play button SVG, since our current reviewer don't handle that by itself, and add back a `<span>` tag inside the button because `flashcard.css` needs that
Emulator 31: open a card with an audio file
Check the css style of the decks you download

fix: play buttons being shown as big black buttons

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/PagesActivityTest.kt
AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/InstrumentedTest.kt
AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/pages/PagesActivity.kt

* #15009
* Fixes #15009
* `supportFragmentManager.addFragmentOnAttachListener`
Unit tested
Still need regression tests, but this is at least a little better

fix: 'Statistics' crashes on open 

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/GestureProcessor.kt

Tap gestures were slow because they were waiting for a double tap. If no double tap was mapped, this was an easy optimisation
Check for a double tap gesture
My S21
Our gesture processing code is still awful. Kotlin might be able to help this, but the problem is that we have multiple components which need to interact and potentially handle the gesture
This is made more complicated by FullScreen mode

Speed up tap gestures

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt

This reverts commit 02a022a107831dc5414acbd23f5568fb5a4f5f67.
This broke clicking links in the Viewer
I've spent a bit of time and it will be difficult to get it working correctly, so reverting
* Fixes #15015

Revert "feat: speed up single tap gestures"

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt

Remove the lateinit var and use shared pref and nullable string to avoid crash in case the developer's option is turned on
Fixes #14795 
google emulator
[Screen_recording_20231124_152918.webm](https://github.com/ankidroid/Anki-Android/assets/48384865/1aa91e06-7686-425b-b674-044d768accb0)

use `SaveInstanceState` to avoid crash in export file when Activity is recreated

---

AnkiDroid/src/main/java/com/ichi2/anki/ReviewerServer.kt
AnkiDroid/src/main/java/com/ichi2/anki/pages/RangeHeader.kt

* Fixes #14490
This implements HTTP 206 partial content responses
We accept a range header, determine the start/end that the client would like, and return that subset of the file
https://github.com/ankidroid/Anki-Android/assets/62114487/4f7c20df-e5a6-42de-9119-af09eacae9ad

fix: allow seeking videos

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/testutil/MockReviewerUi.kt
AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtonStatus.kt
AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtons.kt
AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ReviewerUi.kt
AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerCommandTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerKeyboardInputTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/reviewer/ActionButtonStatusTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/reviewer/PeripheralKeymapTest.kt

No longer used in the new backend + `suspend` functions.
No calls were made to `blockControls`, and everything else passed through this
I suspect unrelated to https://github.com/ankidroid/Anki-Android/issues/14708
But it'll provide a small speedup anyway
Flipped a card on an API 33 emulator, and trusting CI

cleanup: FlashardViewer - remove 'controlBlocked'

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/IntroductionActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/LoginActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
AnkiDroid/src/main/java/com/ichi2/anki/introduction/CollectionPermissionScreenLauncher.kt
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt

* #14650
* Fix follow-on issues + add more logs
*  Not moving from `Register -> Deck Picker`
* Not automatically syncing
* 'Card Browser' not working 
* Fixes #14650
* Extract startup functionality to an interface
* Fix follow-on issues + add more logs
* Fix follow-up with `hasShownAppIntro`
* I knew there was a problem with 'Card Browser', so also fix this
Manually on a `full` build
* We need many more tests here
`every { any<AnkiActivity>().hasCollectionStoragePermissions() }` in `mockk`
A callback to an ActivityLaunch wasn't fired at all as there was no call to `setResult(RESULT_OK)`

fix: various startup issues

---

AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/ControlsSettingsFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/reviewer/MappableBinding.kt
AnkiDroid/src/main/java/com/ichi2/anki/reviewer/PeripheralKeymap.kt
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerNoParamTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/GestureProcessorTest.kt

* Prep to merge PR #12882
Our gesture system was set up to work with the Reviewer
The problem with this is that when we have two screens, a conflicting gesture between the screens doesn't matter
This extracts the Reviewer from most parts of the gesture implementation, so we can replace it with the Previewer when necessary
Note: The Previewer is a special case, other screens won't have a concept of a 'CardSide'
* define a function: `(CardSide) -> Screen` and use that
* This still assumes a `Viewer`
* or accept a `Screen` parameter 
The area is unit tested

refactor(gestures): generalise 'Screen' 

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserLaunchOptions.kt

Handling will be moved into the ViewModel at a later time in which case the class is useful
* extract the concept from https://github.com/ankidroid/Anki-Android/pull/14843 
Tests, then opened the card browser and it still launched

refactor: extract 'CardBrowserLaunchOptions'

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
AnkiDroid/src/main/java/com/ichi2/anki/browser/LastDeckIdRepository.kt
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/browser/CardBrowserViewModelTest.kt

* Split from https://github.com/ankidroid/Anki-Android/pull/14843, partially, partially rewritten
⚠️ One of the more risky refactors
* We want to start moving `searchCards` into an output of the flows
* Once these are all outputs of the flows, we can move it to a combined flow inside the ViewModel
----
* Extract repository
* Extract lastDeckId to viewmodel
* Extract to flow
* Continue to extract
* Extract `mRestrictOnDeck`
Unit tests + manual testing on API 33 emulator

refactor: Browser lastDeckId/restrictOnDeck

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt
AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
AnkiDroid/src/test/java/com/ichi2/testutils/TestClass.kt
AnkiDroid/src/test/java/com/ichi2/testutils/libanki/DeckConfig.kt

* #15050
* Fixes #15050
Select the deck + refresh the UI
Unit tested + tested with API 33 emulator
We need more tests & our alpha testers are fantastic

fix: 'Unbury' unavailable on Deck Menu

---

AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt

Crash when sharing an export collection
* Fixes  #15058
This bug was introduced due to #14797  PR
https://github.com/ankidroid/Anki-Android/assets/65113071/e7c6b97e-0dd7-43d1-bc24-dcf6973ec705

fix crash when sharing Export Collection

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/ReviewerTest.kt
AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt

* our custom scheduling code handled syntax error, but not runtime errors
* Cause: https://github.com/ankidroid/Anki-Android/pull/14899
* Fixes #15035
* define a URL
* access the URL via: `window.location.href = "state-mutation-error:"`
* set `statesMutated` if the URL is accessed
API 33 emulator, and tests added
* https://faqs.ankiweb.net/the-2021-scheduler.html#add-ons-and-custom-scheduling
* Custom Study defines a different set of properties, hence the failure
* Python escaping: https://stackoverflow.com/q/5466451/

fix: runtime error handling in custom scheduling 

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
AnkiDroid/src/main/java/com/ichi2/libanki/NotetypeJson.kt
AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupMetaTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/CardTemplatePreviewerTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/StudyOptionsFragmentTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/MathJaxClozeTest.kt
AnkiDroid/src/test/java/com/ichi2/testutils/MockTime.kt
AnkiDroid/src/test/java/com/ichi2/testutils/TestClass.kt

Mentioned that we should eventually get `KotlinCleanup` down to 0 refs in Discord.
Hadn't done proper cleanup work on it in a while, so did some easy changes. 185 -> 167 references.
Learning:
* `@Language("mustache")` is almost good for displaying cloze templates
* `@Language("json")` works much better with `"""` strings
* Linkage: https://github.com/ankidroid/Anki-Android/pull/14883

Kotlin Cleanup

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
AnkiDroid/src/test/java/com/ichi2/testutils/TestClass.kt

* #15072
`restrictOnDeck` was sometimes set AFTER a search had occurred
Therefore the UI a deck but the search was for 'All Decks'
* Fixes #15072
* Add a no-op test which will work once we've fully moved to the ViewModel
* set `restrictOnDeck` + `deckId` inside `viewmodel.init{}`
API 33 emulator, using steps in the issue.
The unit test passed BEFORE the fix was in place
We're in the awkward position where we're not fully in the ViewModel, so there are some orderings of `suspend` operations which are close to untestable. This will be resolved at a later basis when everything occurs in one task in `ViewModel.init { }`

fix(cardbrowser): deck restriction not set

---

AnkiDroid/src/main/res/layout/card_template_editor_item.xml
AnkiDroid/src/main/res/values/styles.xml

Material 1.11 or maybe I broke the card template editor colors
Emulator 30: open the card template editor
TabLayout have some specific attributes (ref: https://github.com/material-components/material-components-android/blob/master/docs/components/Tabs.md)

fix: Card template editor colors

---

AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt
AnkiDroid/src/test/java/com/ichi2/testutils/TestClass.kt

Issue was with typedLanguageIsSet on Ubuntu: `"A default model should have no preference"`
This was caused by `showNextCard` not completing
Because `waitForAsyncTasksToComplete` had no effect if `@RunInBackground` was not set
* Fixes #15098
* I modified `runTest` to accept a `times` parameter
* Fixed the code to handle multiple runs
* Diagnosed, then fixed the issue
CI only
`viewer.executeCommand(ViewerCommand.FLIP_OR_ANSWER_EASE4)` does not block

fix: typedLanguageIsSet

---

AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt

Fix #15127
* Fixes #15127 
allow zoom in the pages webview
With Android 31 emulator I opened the statistics screen and did a pinch gesture

Enable zoom in anki pages

---

AnkiDroid/src/main/java/com/ichi2/anki/BackendImporting.kt
AnkiDroid/src/main/java/com/ichi2/anki/pages/AnkiServer.kt
AnkiDroid/src/main/java/com/ichi2/anki/pages/CsvImporter.kt

This improves(I think) the csv importing feature with the same changes that I did in [AnkiPackageImporterFragment](https://github.com/ankidroid/Anki-Android/blob/178732eca7c5ed2378bcc897c7d05c43d5c13b8c/AnkiDroid/src/main/java/com/ichi2/anki/pages/AnkiPackageImporterFragment.kt#L26). Changes:
- disables the "Show" button in final import page of csv/text file to avoid the user trying to start the CardBrowser with a search query containing thousands of the imported notes ids
- handles the predictive back navigation
- slightly optimizes the csv import process by using OpChangesOnly
See the before and after flow in the videos below(after first starting importing there's a BACK action so you can see how the UI behaves when the user hits back/ home while the import is running, this is followed …

Improve text/csv importer functionality

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt

When in image occlusion mode hide the save button as the note is already saved when adding the image and the user is notified 
* Fixes #15025
tested on google emulator 

Disable the save button and previewer button if note type is `Image occlusion`

---

AnkiDroid/src/main/res/layout/card_multimedia_editline.xml

* Fixes #15135
* Fixes #15135
go to the text field after the expand button and remove it from the text field to avoid cycling
Android 34 emulator

fix editor shift tab

---

AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt

Deprecate MaterialDialog and use AlertDialog instead https://github.com/ankidroid/Anki-Android/issues/13315
Replaced MaterialDialog with AlertDialog.Builder under one function showCancelConfirmationDialog() of SharedDecksDownloadFragment.kt.
Used AlertDialog 
I tested on my physical device by going inside "get shared decks" choosing any shared decks downloading it and clicking cancel to see the alert dialog which I changed. Changes are done as mentioned there is no difference in the dialog but changed the code to MaterialDilog to AlertDialog.
Googled the official documentary for the AlertDialog.
https://developer.android.com/reference/android/app/AlertDialog.Builder

Updated MaterialDialog to AlertDialog in SharedDecksDownloadFragment.kt

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ConfirmationDialog.kt
AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt

* Fixes part of #13315 
use AlertDialog
In Android 12 emulator I opened some confirmation dialogs like the regress progress and the add card in card template editor

move ConfirmationDialog to material

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerBackupNoSpaceLeftDialog.kt
AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt

* Fixes part of #13315 
move to AlertDialog. I couldn't fix the cancel listener not working, so I disabled cancelling with outside touches. I think that this is a good idea because it avoids closing the app by accident
I tested in Android 12 emulator by adding this line to the app startup:
showDialogFragment(DeckPickerBackupNoSpaceLeftDialog.newInstance())

move DeckPickerBackupNoSpaceLeftDialog to alert dialog

---

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt

* Fixes #14404 
This issue was introduced due to #13451 . 
Check whether the field is autoFocus EditText or not

Autofocus keyboard in Resume State only when "type in answer" checked ✅

---

AnkiDroid/src/main/res/values/theme_dark.xml
AnkiDroid/src/main/res/values/theme_light.xml

It was purple
* Fixes the color issue
When I tried to search for an existing issue I find #15014 and so I followed its approach
I opened the dialog in the Android 12 emulator
here's the dialog background attribute
https://github.com/material-components/material-components-android/blob/master/docs/components/Dialog.md#container-attributes

fix Browser Options dialog color

---

AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt
AnkiDroid/src/main/res/layout/previewer.xml

In the commits
Emulator 31
[Screen_recording_20240102_223124.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/efc74297-f850-4eb9-9021-857bb3146a32)
[he.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/206cd7d0-08b9-42b4-bbdf-67becf1454bb)
Views vanish if their constraints are gone

fix: new previewer not showing when only one card is previewed + change buttons behavior to match Anki Desktop

---

AnkiDroid/src/main/assets/mathjax/conf.js
AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardHtml.kt

I broke it
Map mathjax back to android asset loading
Android 34 emulator:
- add mathjax to a card
- open it in the reviewer

fix: mathjax render

---

AnkiDroid/src/main/java/com/ichi2/anki/AndroidTtsPlayer.kt
AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/SoundPlayer.kt
AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/SoundTagPlayer.kt

* #15103
* I then found that after fixing it, I could get two sounds playing at the same time
* I then found that after transient errors, sounds didn't play
* Fixes #15103
* Fixes #15133
* Gate `resume` calls with a check on the completion status of the continuation
* Check the active status of the continuation before executing slow operations
* set `playSoundsJob` correctly
* use `RETRY_AUDIO` as a crutch
* maintain a list of `currentUtterance/cancelledUtterances` in the TTS class
The Previewer is a GREAT stress test of the workings of the Sound Player
* Obvious, but `resumeWithException` can't be called if `resume()` was called
* There is a lot of nuance to the MediaPlayer - `RETRY_AUDIO` is a crutch which completely fixes the issues
* TTS: `speak()`, then `stop()` won't …

fix: crash & overlapping sounds if quickly changing cards in Previewer 

---

AnkiDroid/src/main/java/com/ichi2/anki/pages/DeckOptions.kt
AnkiDroid/src/main/java/com/ichi2/anki/pages/PageWebViewClient.kt

There were two flickers:
1. The screen flickered white
2. The screen flickered the wrong shade of black
* Fixes #14194
1. was easy: move the code to set the background color to `onPageStarted`
2. More difficult: I made the screen wait for `anki.setupDeckOptions` to return
Samsung S21, Android 14. I also tested in light mode, and that we didn't break stats

fix: Deck Options screen flickers in dark mode

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/OnPageFinishedCallback.kt
AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/pages/DeckOptions.kt
AnkiDroid/src/main/java/com/ichi2/anki/pages/PageWebViewClient.kt

* #15130
* Fixes #15130
* onBackPressedDispatcher
API 33 emulator:
* Manage Note Types + Reviewer to ensure no breakage
* Deck Options - pressing back goes back
* Deck Options - pressing back when on manual goes back to options
[15130.webm](https://github.com/ankidroid/Anki-Android/assets/62114487/099c585b-f411-44b2-ba59-601190c53f5b)

fix: Deck Options: "Back" works incorrectly if the manual is open

---

AnkiDroid/src/test/java/com/ichi2/anki/AnkiDroidJsAPITest.kt
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/PreviewerTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/CollectionTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/FlagTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/SchedulerTest.kt
AnkiDroid/src/test/java/com/ichi2/testutils/TestClass.kt

I added these to the CardBrowser refactor and generally found them useful
* `addDeck("", setAsSelected = )`
* `Card.update`
* `Note.updateCards`
Test-only

cleanup: add test method helpers

---

AnkiDroid/build.gradle
AnkiDroid/src/test/java/com/ichi2/anki/AnalyticsTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/reviewer/ActionButtonStatusTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/reviewer/PeripheralKeymapTest.kt
AnkiDroid/src/test/java/com/ichi2/preferences/PreferenceExtensionsTest.kt

Shaves a second off test execution
API is much easier to use.
I cut this out from the Card Browser refactor, but this might not get used here

tests: use shared-preferences-mock

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
AnkiDroid/src/main/res/values/10-preferences.xml
AnkiDroid/src/main/res/values/preferences.xml
AnkiDroid/src/main/res/xml/preferences_appearance.xml

#15147 
* Fixes #15147 
Add a setting
Android 34 emulator: I upgraded the app to see if the setting defaulted to true and reinstalled to see if it defaulted to false
Then I looked if the deck title was showing correctly when enabled and not showing when disabled

add deck title back

---

AnkiDroid/src/main/java/com/ichi2/anki/BackendExporting.kt
AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt
AnkiDroid/src/main/java/com/ichi2/libanki/BackendImportExport.kt
AnkiDroid/src/main/res/layout/dialog_export_options.xml

Implements one of the requested followups from #15167:
_The apkg export screen should expose an option to control whether deck configs are exported_
Not that much testing, but the changes are pretty small.

Enable "Include deck configs" option when exporting an apkg

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardHtml.kt
AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/TTS.kt
AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Note.kt
AnkiDroid/src/test/java/com/ichi2/libanki/CardTest.kt
AnkiDroid/src/test/java/com/ichi2/testutils/CollectionDBCorruption.kt

* Extracted from https://github.com/ankidroid/Anki-Android/pull/13936/
* I didn't want to see the effort go to waste 
Up to https://github.com/ankidroid/Anki-Android/pull/13936/commits/5f01180be25f13eae46aad1fc78caf122a620f8a
A large number of commits were no longer applicable. A number of commits were not selected, as they affected classes which would retain a `col` parameter, such as `sched`
Each commit is linked to the 'original'
The aim of these commits is primarily to convert `val` -> `fun`. This is prep work to remove `col` as a variable from the non-manager classes in `libAnki`, such as `Card` and `Note`: we may retain a reference to these classes after `withCol` has completed

New Dev: Extract non-functional refactors

---

build.gradle

Not sure why dependabot did not propose this one, will investigate that separately
note that the android gradle plugin 8.2-stable series has a defect that does not allow setting the jacoco version, and pins it at 0.8.8
that is fine in all cases except where you want to use JDK21, which requires jacoco 0.8.11+.
this will be resolved in android gradle plugin 8.3-stable

build(deps): adopt android gradle plugin 8.2.1

---

AnkiDroid/build.gradle
AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
build.gradle
tools/localization/yarn.lock

Mostly standard dependency updates except the last three:
1- manual PR of android gradle plugin from 8.1.4 to 8.2.1 because dependabot wasn't doing them, I believe we confused it earlier with PR closes on other android-gradle-plugin work. I believe that will self-resolve in future
2- deprecation fixup for the semver package to get it in
3- altered dependabot configuration for `/tools/localization` javascript package so it PRs against dependency-updates branch but only after I noticed it was PRing to main. Manually fixed this one up

Dependency updates 20240111

---

.github/dependabot.yml

Noticed that our new javascript crowdin system is getting dependabot PRs to main branch vs dependency-updates, see #15198
Make a new configuration stanza for the "npm" ecosystem (even though we use yarn, this is the key to use per docs: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem)
Can't really test dependabot but the next time it proposes something for `/tools/localization` it should be against the correct branch

chore(deps): alter dependabot to propose javascript PRs on dependency-updates branch

---

AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/AboutFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/Full30and31PermissionsFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/PermissionsFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/PermissionsUntil29Fragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/TiramisuPermissionsFragment.kt

As the docs of [onCreateView](https://developer.android.com/reference/androidx/fragment/app/Fragment.html#onCreateView(android.view.LayoutInflater,android.view.ViewGroup,android.os.Bundle)) says:
> It is recommended to only inflate the layout in this method and move logic that operates on the returned View to [onViewCreated](https://developer.android.com/reference/androidx/fragment/app/Fragment#onViewCreated(android.view.View,android.os.Bundle)).
Most of the other fragments are handled in #15218 
so I did some cleaning
34 emulator:
check if statistics, about and permissions screen still appear
Fragment has a constructor which accepts a layout resource to automatically inflate it (thanks to lukstbit for pointing it out) [source](https://developer.android.com/reference/androidx/fragment/app/ …

refactor: move onCreateView content to onViewCreated on some fragments

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportReadyDialog.kt

Small PR to fix one issue with restoring an async set ExportReadyDialog. In order to restore the dialog it needs a path as a String, but the code was trying to retrieve the path as a Parcelable which produced a null path.
I've tested the restore scenario.

Fix ExportReadyDialog restore from Bundle

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt

On the DeckPicker, under a 'full' build, on startup with no permissions
* later APIs: a dialog briefly appeared
* earlier APIs: a dialog blocked usage of the screen
* ⚠️ I couldn't find a specific bug
* https://github.com/ankidroid/Anki-Android/pull/15258
* Isolate stack trace
* Fix the bug
* https://github.com/ankidroid/Anki-Android/pull/15258
* we can't use `isFinishing`, as showing the permissions screen does not finish the activity
```
* onResume -> refreshState -> updateDeckList
* -> performBackupInBackground -> withCol
* -> val deckData = withCol ...
```

fix: DeckPicker storage error on first run

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt

Non-functional, caught after code was merged
* PR #15061

chore: early return in `filterUrl`

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/ReviewingSettingsFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/reviewer/AutomaticAnswer.kt
AnkiDroid/src/main/res/values/10-preferences.xml
AnkiDroid/src/main/res/values/11-arrays.xml
AnkiDroid/src/main/res/values/constants.xml
AnkiDroid/src/main/res/values/preferences.xml
AnkiDroid/src/main/res/xml/preferences_reviewing.xml
AnkiDroid/src/test/java/com/ichi2/anki/reviewer/AutomaticAnswerActionTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/reviewer/AutomaticAnswerAndroidTest.kt

This switches the auto advance feature to use the shared settings in the deck options.
* Ref: #15167
- The code was changed to use the `secondsToShowQuestion` and `secondsToShowAnswer` deck config properties. AnkiDroid-specific preference/config values are no longer used, except for the `timeoutAnswer` preference used to toggle the feature (The computer version requires the user to explicitly toggle it on in every review session - see https://github.com/ankitects/anki/pull/2765#pullrequestreview-1696007452).
- The preferences to set the timeouts and answer action were removed.
- The "Wait for audio" option didn't exist in the AnkiDroid implementation (the default was to always wait), so it was added.
Manual testing in the emulator.
Refer to https://github.com/ankitects/anki/pull/2765 …

Switch the auto advance feature to use the settings in the deck options

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt

Undo Delete deck action in snackbar
* Fixes #15273 
setAction in snackbar
https://github.com/ankidroid/Anki-Android/assets/65113071/735b4e24-7eb3-463b-8f01-d00021f50c75

fix: undo delete deck action in snackbar

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/LocaleSelectionDialog.kt
AnkiDroid/src/main/res/layout/locale_selection_dialog.xml
AnkiDroid/src/main/res/values/03-dialogs.xml

MaterialDialog refactor, followed by a few more to make the screen nicer. Compare screenshots
* Issue #13315
* Convert to `DialogFragment:onCreateView`
<details>
<summary>
Old
</summary>
</details>
<details>
<summary>new</summary>
</details>

refactor: Locale selection

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt

We weren't calling searchCards() after viewModel.launch
* Fixes #15072

fix(CardBrowser): Wrong deck selected on open

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/InsertFieldDialog.kt
AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt
AnkiDroid/src/main/res/layout/dialog_generic_recycler_view.xml

* Issue #13315
This involved handling `customListAdapter()`, this was done via
* setView + R.id.dialog_generic_recycler_view
* and AlertDialogFacade.customListAdapter()
<details>
<summary>before</summary>
</details>
<details>
<summary>after</summary>
</details>

chore: convert InsertFieldDialog to AlertDialog

---

AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Note.kt
AnkiDroid/src/test/java/com/ichi2/anki/previewer/PreviewerViewModelTest.kt

the desktop previewer doesn't show type-in answer previews (https://docs.ankiweb.net/templates/fields.html#checking-your-answer), neither AnkiMobile does
AnkiDroid currently has a TextInput to insert the answer and check it when the answer is shown
For the new previewer, I'm going with a midterm of not showing the type box in the question like Anki Desktop/Mobile, since the previewer goal should only be previewing stuff, but showing the result in the answer so the user can preview what they want
On the commits
Emulator 31:
[type answer.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/c116467e-e05a-4a38-b83b-dddd5f024a85)
Part of the desktop reviewer's code is 11 years old 😯.
Also, I should be less lazy and write more tests, but the Android Studio slowness make me lazier …

feat: handle type-in answers in the new previewer 

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/pages/CongratsPage.kt
AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt
AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt
AnkiDroid/src/main/res/menu/congrats.xml
AnkiDroid/src/test/java/com/ichi2/libanki/SchedulerTest.kt

* Fixes most of #14955. 
Only pending thing is the button leading to the deck description. I haven't added the `Unbury` and `Custom study` buttons because I think that the links are sufficient
In the commits
Emulator 31:
[Screen_recording_20240112_213816.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/25fa0a7d-a068-4f85-bd09-4b099f2444b8)

feat: implement  Congrats screen links and deck options button

---

AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
AnkiDroid/src/main/res/values/preferences.xml
AnkiDroid/src/test/java/com/ichi2/anki/analytics/PreferencesAnalyticsTest.kt

Opening preferences opted users in to analytics in 2.16 due to an oversight
Despite the fact that analytics were broken at the time due to Google's migration from Universal Analytics to Google Analytics 4, we want analytics to STRICTLY be opt-in
So we stated that we would opt everyone out: https://ankidroid.org/docs/changelog.html#_version_2_16_5_20230906
* Related 
* #14569 
* This issue now no longer blocks 2.17 
* #14386
* removing the old preference key ("analyticsOptIn")
* ensures the default (false) is used
* removes a deprecated key from preferences
* renaming the preference key ("analytics_opt_in")
* ensures that the legacy value is never used going forwards
Only CI
* Discussion on how we handle this https://github.com/ankidroid/ankidroiddocs/pull/115

chore: reset analytics opt-in

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt

* Fixes #14950
* allow ViewModel operations to be handled in CardBrowser
* reload the individual cards so `forceRefreshSearch` is not required
* then just a call to `cardsAdapter.notifyDataSetChanged()`
Unit Tested

fix(CardBrowser): retain selection when toggling 'mark'

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/AsyncDialogFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.kt
AnkiDroid/src/test/java/com/ichi2/anki/dialogs/AsyncDialogFragmentsTest.kt

* Fixes #13795
Determine that we have two problems:
1. We're using `AnkiDroidApp` resources as default from `res()`, this does not handle language changes well
2. We sometimes use `context.resources` inside `notificationMessage` or `notificationTitle`, this crashes when called in
https://github.com/ankidroid/Anki-Android/blob/08b6a0feeb634a70e99d3ec0887c003cbd81e238/AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt#L413-L417
To fix (2), use `res()` throughout
To fix (1), prefer `resources` over `AnkiDroidApp.resources`
Unit tests
modify `sync` to always show the error dialog after a delay, and see the crashes
I haven't tested this thoroughly, I trusted the unit tests

fix: crash on Async dialog not being attached to a context

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt

cause: https://github.com/ankidroid/Anki-Android/commit/65c9f9197ef31e223e5ced4950c366883c94205b#diff-6d9f7ea7bba9cc72513b5078633cee9bdbbd1ea7646114869679f302ad607459R974
Android 31: Enable the new previewer in dev options -> Tap edit note -> Edit the note -> Confirm

fix: eternal load when editing a note from the new previewer

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/Previewer.kt
AnkiDroid/src/main/java/com/ichi2/utils/ViewUtils.kt

* Requested by @sudomain
* could not test Ctrl+Shift+P in an emulator, but shift+P worked
* Previewer: left+ right worked, including holding + mashing the button
* We still have the issue with darkening the window when using keyboard commands

feat: additional keyboard events

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt
AnkiDroid/src/main/java/com/ichi2/utils/EditTextUtils.kt
AnkiDroid/src/main/res/layout/dialog_generic_text_input.xml
AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CreateDeckDialogTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/dialogs/utils/AlertDialogUtils.kt

First one I saw, was "not fun", especially unit test changes
* Issue #13315
This involved handling `input()`, this was done via
* `setView(R.id.dialog_generic_text_input.xml)`
* and `AlertDialog.input()`
⚠️ padding is a little different, I feel it's better, but encourage a hard comparison between both images.
The text selection is at the end of the input, as it is in 2.16.5
<details>
<summary>before (2.16.5)</summary>
</details>
<details>
<summary>after</summary>
</details>

chore: convert `CreateDeckDialog` to `AlertDialog`

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.kt
AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateNotetype.kt
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardSoundConfig.kt
AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/SoundPlayer.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CreateCustomStudySessionListener.kt
AnkiDroid/src/main/java/com/ichi2/anki/model/CardsOrNotes.kt
AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt
AnkiDroid/src/main/java/com/ichi2/anki/reviewer/AnswerTimer.kt
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/CardService.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt
AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/CardSoundConfigTest.kt
build.gradle

Removes usages of `this` in `withCol`/`undoableOp` calls
Context receivers allow `this` as an implicit parameter to a method if `this` is in scope (typically due to a `with` call)
This means that:
* methods are only usable if `Collection` is scoped
*  you can't easily call these methods outside `withCol`
* methods can effectively accept multiple context receivers
*  in the below, both `Card` and `Collection` are scoped to `this`
```kotlin
context(Collection)
fun Card.note() = this.note(this@Collection)
```
allows the transformation
```diff
- val note = withCol { card.note(this) }
+ val note = withCol { card.note() }
```
Which is much more readable, as `this` was confusingly named
* Related + logical follow-up to https://github.com/ankidroid/Anki-Android/pull/13936
* enable context …

refactor: use Context receivers to remove `this` within `withCol` [Experimental API]

---

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
AnkiDroid/src/main/res/values/attrs.xml
AnkiDroid/src/main/res/values/theme_black.xml
AnkiDroid/src/main/res/values/theme_dark.xml
AnkiDroid/src/main/res/values/theme_light.xml
AnkiDroid/src/main/res/values/theme_plain.xml

* Fixes #14209
1. Change the theme of the app from (Hamburger Menu ---> Settings ---> Appearance ---> Select Theme)
2. Choose the theme (Light, Plain, Black, Dark)
3. Go to home. 
4. Open any card and then check the show answer button color matches the theme of the app.
5. Repeat step 1 till you test all theme (Light, Plain, Black, Dark)
This has been tested on physical device(Realme 3i) and on emulator (Google Pixel 3)
**App Theme**
<br>
| Black Mode | Dark Mode | Light Mode | Plain Mode |
|------------|-----------|------------|------------|
| ![Black_Mode](https://github.com/ankidroid/Anki-Android/assets/60827173/0bb5c24f-c475-45f0-a417-c9151eb1e929) | ![Dark_Mode](https://github.com/ankidroid/Anki-Android/assets/60827173/6a9f193e-c2ec-4974-9d66-9c397902daf4) | …

Color of Bottom Window changes based on the theme of the app.

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/MissingImageHandler.kt
AnkiDroid/src/main/res/values/02-strings.xml
AnkiDroid/src/main/res/values/constants.xml
AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/MissingImageHandlerTest.kt

since we stopped using the media directory as base URL of the reviewer in 7a65160e0e23e20080091a30abdd4c05fc610e06, urls without a explicit protocol default back to http
Remove the URL protocol handling
Android 31:
[rem inefficient.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/c21c4c88-686c-40a5-98e9-f5b8bc629eb8)

chore: remove `processInefficientImage`

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ACRATest.kt
AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
AnkiDroid/src/main/java/com/ichi2/anki/logging/FragmentLifecycleLogger.kt
AnkiDroid/src/main/java/com/ichi2/anki/logging/LogType.kt
AnkiDroid/src/main/java/com/ichi2/anki/logging/ProductionCrashReportingTree.kt
AnkiDroid/src/main/java/com/ichi2/anki/logging/RobolectricDebugTree.kt
AnkiDroid/src/test/java/com/ichi2/anki/ProductionCrashReportingTreeTest.kt

I believed that Instrumented tests on CI may be using production logging, as the amount of logs coming from AnkiDroid was minimal, it was difficult to confirm (I now believe they use `DEBUG/ROBOLECTRIC`), but this makes it certain
* Extract `LogType` and log the value
* Refactor other classes into `logging` package
Untested

refactor: logging

---

AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.kt
AnkiDroid/src/main/res/values/10-preferences.xml
AnkiDroid/src/main/res/values/filtered_deck_options.xml
AnkiDroid/src/main/res/xml/cram_deck_options.xml

This makes it possible to customize the preview delays of the Again, Hard, Good buttons in filtered decks. Supported in Anki 23.12+.
Fixes the last task and closes #15167
When the rescheduling option is disabled, the new Preview delays section is enabled. 
Manually tested in the emulator.
See https://github.com/ankitects/anki/issues/2858
The old `previewDelay` deck config key used for the single delay doesn't appear to be handled in AnkiDroid, so it wasn't possible to customize any delay anyway?

Support customizing preview delays for Again, Hard, and Good buttons

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Utils.kt
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserNonAndroidTest.kt

`[sound:foo.mp3]` is now `[anki:play:a:0]`, CardBrowser needed further handling of this
* Fixes #14353
* Define `replaceAvRefsWith` to enable replacements
* pass in TemplateRenderContext so we have a reference to the AvTag
* allow `stripAvRefs` to accept a formatter override
Unit tests changed and tested on my S21
<details>
<summary>hide names</summary>
</details>
<details>
<summary>show names</summary>
</details>
I'll be glad when we kill this code in the CardBrowser, it'll be the last to go though

fix: play tags shown in card browser

---

.github/workflows/lint.yml
.github/workflows/publish.yml
.github/workflows/tests_emulator.yml
.github/workflows/tests_unit.yml
.github/workflows/update-gradle-wrapper.yml
build.gradle

I think JDK21 will work now that AGP 8.2.2 is out, it appears to work for me locally.
Success criteria is nothing different in the logs then the JDK17 logs - this should be undetectable by anyone basically

build(deps): AGP 8.2.2 w/JDK21 compatibility, switch CI to JDK21

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt

Add fullscreen to `<video>` tags in Android
Not adding it to the new previewer yet because I want to think if there is a way of doing it without using `configChanges="orientation"` and all of my ideas are complex and I'm not sure if any of them is going to work. 
Also, it's not gonna be in 2.17 anyway, so better hurry this one
* Fixes #14568 
Use [onShowCustomView](https://developer.android.com/reference/android/webkit/WebChromeClient#onShowCustomView(android.view.View,%20android.webkit.WebChromeClient.CustomViewCallback))
note: leaving fullscreen after rotating back to portrait mode is Android's default behavior and since apps like YouTube do that, I didn't want to fight Android
[fs.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/e63b709c-4ba4-4f5c-bc1e-770291d7fe1d) …

feat: enable fullscreen in <video> tags

---

.github/workflows/sync_translations.yml
tools/localization/package.json
tools/localization/yarn.lock

our i18n infrastructure used to rely on some macOS-specific behavior,
but now that it is all javascript I don't think the runner OS actually
matters
if it does not matter, then ubuntu is preferred as macos has limited
concurrency on free accounts
It isn't easy to test these, I plan on running a sync as soon as it merges to determine if it works or not, will rollback immediately if it fails of course

i18n sync workflow on ubuntu / bump javascript deps

---

.github/workflows/sync_translations.yml

this appears to work fine in local testing, and it is the current active release, node 18 is maintenance only
not sure how to handle this PR-merge-workflow wise other than to just merge it and pay attention 🤷

chore(deps): switch i18n workflow to use node 20

---

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt
AnkiDroid/src/main/res/layout/activity_audio_recording.xml

There were few TODOs I left for myself when I created the previous PRs, so this PR further improves the audio recorder logic and functionality (UX)
- Stop the audio recorder or player in case the user presses back while in multimedia activity or exits the activity. As of now the audio recorder keeps going on and same for the player the audio is played even if the user leaves the screen 
- Same for the reviewer 
- When the user goes to next card the audio recorder UI gets reset to its initial state (was suggested by David)
- When in reviewer the save icon(disk) does not makes sense so replacing it with done icon in case of reviewer 
* Fixes https://github.com/ankidroid/Anki-Android/issues/15300
Tested on Google emulator 
- Pressed back while playing audio
- Pressed back while recording 
- …

audio recorder functionality improvement

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/SoundPlayer.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt
AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/SoundPlayerTest.kt

Different activities may have different lifecycle behaviors depending on how well they deal with configuration changes or if they have a ViewModel or not
So now the SoundPlayer will get its own scope, which means that callers need to remember to close() it, and it can be enabled/disabled with a property
this also makes removes the Robolectric dependency from SoundPlayerTest, which should make things faster
Additionally, it prepares for handling audios in the new previewer
In the commits
Unit tests (should be non functional) + opened some cards with audio in 31 emulator

refactor: remove lifecycle dependency from SoundPlayer

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/utils/OnlyOnce.kt
AnkiDroid/src/test/java/com/ichi2/anki/utils/OnlyOnceTest.kt

Cause: answering the card too quickly, which caused two executions of `answerCard()`
* Fixes #12946
Define and use `preventSimultaneousExecutions`
* calling `answerCard(EASE_4)` twice and ensuring no error
* throwing an exception inside the method and ensuring it's unlocked
* technically not perfect due to `launchCatchingTask`
* adding a log statement afterwards and ensuring the call is not blocking
* Unit tests

fix: "Invalid input: card was modified"

---

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/reviewer/AnswerTimer.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
AnkiDroid/src/test/java/com/ichi2/anki/reviewer/AnswerTimerTest.kt
AnkiDroid/src/test/java/com/ichi2/testutils/rules/MockitoCollectionRule.kt

"Show Answer Timer" must be enabled
* background + foreground AnkiDroid
* Error dialog appears
* Fixes #15317 
* make `resume() ` a suspend function
Manually + Added `@MainThread`
`Chronometer.base` must be called on main thread

fix: Error dialog: due to "show timer" on resume 

---

.github/dependabot.yml

the npm package ecosystem releases all the time and it clutters up the PR queue for mostly meaningless dependency updates
dependabot has a new "groups" feature to group dependency update PRs together in to one PR based on either name globs, update types, or dependency type
this should allow us to get all non-breaking changes through in single PRs, while breaking (semver-major) changes will get individual PRs for more detailed consideration
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
* Fixes _Link to the issues._
Please describe the tests that you ran to verify your changes. Provide instructions so we can …

chore(deps): keep npm dependency updates to one PR if non-breaking

---

AnkiDroid/src/main/res/values/attrs.xml
AnkiDroid/src/main/res/values/styles.xml
AnkiDroid/src/main/res/values/theme_black.xml
AnkiDroid/src/main/res/values/theme_dark.xml
AnkiDroid/src/main/res/values/theme_light.xml
AnkiDroid/src/main/res/values/theme_plain.xml

The styles for the Alert dialog was not set properly and #15333 introduced a theme bug, hence updating the style and the themes to handle it properly. When I added the cancel button in the sync progress dialog it worked fine with all themes except light where it was not visible so I have changed that too
* Fixes #15346
Black : 
Dark: 
Light : 
Progress dialog  - 
Plain : 

Theme issue with Alert Dialog and color of button in Progress Dialog

---

.github/workflows/tests_emulator.yml
.github/workflows/tests_unit.yml

This is a beta, we are currently on `macos-12`
https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
> The macos-latest workflow label currently uses the macOS 12 runner image.
> `macos-14` [beta]
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
This reduces the available RAM from 14 to 7GB
This is the test 
https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
Virtual …

test(ci): upgrade macOS runner to M1 & macOS 14

---

AnkiDroid/src/main/java/com/ichi2/anki/TtsVoices.kt

As I mentioned this in the issue it happens only for API30 and no other API, I have tested it for other API i.e. 24 and 33 and its works fine. It might be related to emulator only as it was reported under emulator category but still fixing it so that it doesn't break in API30 emualtor.
* Fixes #15364
Tested on API30 (emulator) / API24 / API 33(physical and emulator both)
https://issuetracker.google.com/issues/199606758

Fix: API30 tts `availableVoices` to return empty set to avoid crash

---

README.md

I've added a link to the LGPL (Lesser General Public License) file in the README of the repository. This helps users and developers easily access the license terms and understand the permissions and obligations associated with the AnkiDroid API.
* Fixes #15337

Add AnkiDroid API LGPL License to Readme 

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.kt
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
AnkiDroid/src/main/java/com/ichi2/utils/FragmentManagerSupplier.kt
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt

* #15247
* Fixes some of #15247
* Fixes some of https://github.com/ankidroid/Anki-Android/issues/15197
* Refactor
* Switch `AnkiActivity` for `AppCompatActivity`
* migrate some methods to `withCol` and the initialisation methods to accept a `col`
Unit tests + physical test on API 33 emulator: add a note + Card Browser - switching decks
Testing found issues with calling `initializeActionBarDeckSpinner` inside a task, I added a `@MainThread` annotation and added an explicit `col` parameter to resolve this
* initializeActionBarDeckSpinner

Generify deck selection dialog, for use in `Statistics`

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerAnalyticsOptInDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/IntegerDialog.kt
AnkiDroid/src/main/java/com/ichi2/preferences/NumberRangePreference.kt
AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt
AnkiDroid/src/main/java/com/ichi2/utils/MaterialBuilderUtil.kt

* Part of #13315
API 33 emulator: Reposition Dialog dialog
* waitForPositiveButton matches the material dialog UI, but is questionable
* `.show()` is required for `.input()`
* `allowEmpty` potentially has a bug if called alongside `waitForPositiveButton`

refactor: convert IntegerDialog to AlertDialog 

---

.github/workflows/tests_unit.yml

We don't want the name of the job to be changed when changing the OS of runners
* Fixes #15371
use `include` to expand the `os` matrix to include the name
then use the variable as a job name
https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#example-expanding-configurations
https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#example-expanding-configurations

build(ci): use stable job names

---

build.gradle

Added in f5ecb05efc3117238cbd42935542176d4436ee5f
Related: 655516582cbee7dffb70a3be6318103731f9b9a0
but CI runners now have 16GB RAM, so this is not necessary any more
* Part of #15368
* Reverts change added in https://github.com/ankidroid/Anki-Android/pull/11341
*  https://github.com/ankidroid/Anki-Android/commit/f5ecb05efc3117238cbd42935542176d4436ee5f 
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
> discovered you can eliminate the standalone (multi-gigabyte, persists after compile) kotlin compiler daemon by having it run in process, and just ensuring main process is sufficient (it is, determined by GC logging). I think this might be the final set, allowing …

build(ci): remove `IN_PROCESS` compiler execution strategy

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/InstrumentedTest.kt
testlib/src/main/java/com/ichi2/testutils/IgnoreFlakyTestsInCIRule.kt

0c238ed9bbf783708fdcf7eb5125c1a9cc8a8d64 broke with
```
com.ichi2.anki.ReviewerTest > testCustomSchedulerWithRuntimeError[test(AVD) - 11] FAILED
java.lang.AssertionError: View assertion was not true within 30000 milliseconds
at org.junit.Assert.fail(Assert.java:89)
E0201 20:37:37.824023 bcf7000 FrameBuffer.cpp:3765] Failed to find ColorBuffer:314
com.ichi2.anki.ReviewerTest > testCustomSchedulerWithCustomData[test(AVD) - 11] FAILED
java.lang.AssertionError: View assertion was not true within 30000 milliseconds
at org.junit.Assert.fail(Assert.java:89)
```
But only when run on `main`, not on the pull request
The "CI" parameter appeared to not passed to the emulator
So we should use BuildConfig, rather than getenv
* ref: https://github.com/ankidroid/Anki-Android/pull/15381#issuecomment-192225 …

fix: emulator tests (🎉)

---

.github/workflows/tests_emulator.yml
build.gradle

The new github actions runners have about 2x the vCPU and they have nested virt enabled
* Fixes #15368 
- one commit doubles the max test forks, based on the throughput benchmarks Azure posts that seems right
- one commit switches to ubuntu, and fiddles with permissions a little bit so it works
The PR is made of tests
- https://github.com/actions/runner-images/issues/183#issuecomment-1442154492 (which now applies to public repos too)
- https://stackoverflow.com/questions/37300811/android-studio-dev-kvm-device-permission-denied/61984745#61984745
- https://github.com/reactivecircus/android-emulator-runner?tab=readme-ov-file#running-hardware-accelerated-emulators-on-linux-runners

test(ci): take advantage of new public repo action runner capabilities

---

.github/workflows/tests_unit.yml

- use new v1.4 tag that updates action to node 20 to quiet warning
- use C: drive since D: has issues (#15372)
proof it works will be examination of CI log to make sure the step has sane output on the windows runner
- Fixes #15372

test(ci, unit): configure windows pagefile correctly

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt

A quick fix for the linked bug. The refactored CardBrowser uses LastDeckIdRepository to get the last selected deck id but this wasn't updated when selecting the browse option in the context menu in DeckPicker. I extracted the SharedPreferencesLastDeckIdRepository to the application class so it is available to both components CardBrowser and DeckPicker. Should be safe as the class just reads a preference and handles a missing id.
Edit: I'm not sure we need the LastDeckIdRepository abstraction, SharedPreferencesLastDeckIdRepository could be an object.
* Fixes #15386 
Ran the tests, manually checked the bug steps.

Fix browser displayed deck when selected from DeckPicker's context menu

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt

`opChanges` needs to return changes
* Fixes #15400

fix: crash changing note type

---

AnkiDroid/src/main/java/com/ichi2/anki/pages/AnkiServer.kt

* Fixes #15353 
I followed https://github.com/ankidroid/Anki-Android/issues/15353#issuecomment-1915618519 that said that the error wasn't received but it worked in the previewer, so after hours I discovered that the server was sending a OK message in the reviewer, while the previewer don't use a server
Opened the reviewer in Emulator 14 with a non existing file and the snack bar appeared

fix: media not found message

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/Previewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/PreviewerTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/browser/CardBrowserViewModelTest.kt

Fixes #15380 
* Fixes #15380 
I wrote the ids in a file like suggested by Mike Hardy
I don't have a deck that big, but in a small one the previewer still works
File.createTempFile can be used to create a temporary file

fix Crash on opening Previewer in a large deck

---

AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt

OneUI 6 changed how the S Pen sent MotionEvents, which broke 'erase'
* Fixes #14767
Handle `BUTTON_STYLUS_PRIMARY`
Tested-by: @mmarlo-hassio on a physical device with an S Pen
`buttonState == BUTTON_STYLUS_PRIMARY` is how the events are now sent
I reverse engineered the S Pen Remote SDK, nothing relevant here

feat(whiteboard): S Pen eraser on OneUI 6

---

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/Previewer.kt

matches the navigation bar color with 'show answer'
* uses `setNavigationBarColor`

previewers: improve nav bar color

---

AnkiDroid/src/main/AndroidManifest.xml
AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/SingleFragmentActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/pages/ImageOcclusion.kt
AnkiDroid/src/test/java/com/ichi2/testutils/ActivityList.kt

Allow `SingleFragmentActivity` to survive config changes
* Fixes #15392
Google Pixel 8 emualtor 
Posting emulator ss itself

fix: Image Occlusion webView being recreated in orientation changes

---

AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
AnkiDroid/src/main/java/com/ichi2/anki/pages/CongratsPage.kt
AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerHelpers.kt
AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt

I'm sorry if there were too much churn of changes in the new previewer instead of reviewing just one final piece, but I was trying to do things in a incremental way and sometimes I get new ideas on how to organize stuff (and I likely will refactor more stuff when I generify the code to be reused in the CardTemplatePreviewer rewrite)
The last task is handling audios, which I already finished locally, so it shouldn't take long before it can be made the default one
In the commits
Android 31:
[teste.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/91d89718-6acf-4c62-a237-637734bd116a)

fix some bugs in the new previewer + some refactors

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerBackupNoSpaceLeftDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/help/HelpDialog.kt
AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt

I've renamed the current _create{}_ extension method to _createAndApply{}_ to avoid confusion with a basic _create{}_ extension that works on the _AlertDialog.Builder_ instance. Feel free to comment on the naming.
Also added a getter for the prompt CheckBox that can be used in  #15376

Improve the extension methods available in AlertDialogFacade

---

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt

Make the undo icon "grayed out" appearance when there is no action to undo.
* Fixes #15455
https://github.com/ankidroid/Anki-Android/assets/10436072/e424948d-4e1e-41e3-a23e-cd8056e7a159

Make undo icon gray when the icon is unavailable

---

AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt

`withProgress` dialog might throw IllegalArgumentException if the dialog is not shown and dismiss is called.
Stracktrace pointed at DeckPicker which was calling with progress having context from DeckPicker,
```View=DecorView@1caa981[DeckPicker] not attached to window manager: ```
This message indicates that the DecorView with the identifier 1caa981 (associated with a DeckPicker) is not currently attached to the window manager.
* Fixes #15445 
Adding a condition to check whether the dialog is showing before dismissing it  fixes the issue.

Fix: IllegalArgumentException on with progress dialog dimiss

---

AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BackupPromptDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ConfirmationDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerBackupNoSpaceLeftDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerNoSpaceLeftDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/InsertFieldDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ModelEditorContextMenu.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SimpleMessageDialog.kt

Related: 1fd0147afd954d802932efa710b7b0730322cc97 (added `.create` with the wrong receiver: `AlertDialog` instead of `AlertDialog.Builder`)
Fixed in bcc4df072eccdb12887a7626ad2770a95989148e
This left a large number of dialogs using `.apply { }.create()`
A large number of dialogs could be transitioned to this pattern. For now we replace all instances of `.apply { }.create()` to ensure this is a refactor-only commit
* Related: #13315

chore: use AlertDialog.Builder.create()

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
AnkiDroid/src/main/java/com/ichi2/anki/DayRolloverHandler.kt
AnkiDroid/src/main/java/com/ichi2/anki/pages/CongratsPage.kt
AnkiDroid/src/main/java/com/ichi2/libanki/PythonTypes.kt
AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt
AnkiDroid/src/main/java/com/ichi2/utils/TimeUtil.kt

See: https://github.com/ankitects/anki/blob/edd38ca06730d7fc16804f52ce10f6bc54c3d145/qt/aqt/main.py#L508-L528
AnkiDroid needs to perform certain operations after a day rollover, otherwise the backend throws InvalidInputException when reviewing
* Fixes #14090
* ⚠️ This is a hack, please suggest a better method, happy to rewrite
Due to complexities of Android scheduling a timer at a given time, we use a hack:
* Every time change, or every minute (when the clock changes), run a function
We care about:
* Reviewer - a new card may be seen
* DeckPicker - counts will be updated
* CongratsScreen - bury status will change
I changed code to perform a 'day rollover' every second, and ensured that the change was fired

feat: day rollover handling

---

AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/TypeAnswer.kt

In the preference it was true
https://github.com/ankidroid/Anki-Android/blob/4711b4c89a9a45da10781c93e7480d541860ad02/AnkiDroid/src/main/res/xml/preferences_advanced.xml#L92-L93
In the code it was false
Make it `true`
Untested
At some point we need to look again at making preference defaults consistent. I had a try a long time ago in Java, and it would be much cleaner in Kotlin

fix: 'auto focus type in answer' default

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerAnalyticsOptInDialog.kt

Replaces usages of Deprecated MaterialDialog and adds the Native AlertDialog For Deck Picker Analytics.

Removed the Material Dialog Box and Added Alert Box from DeckPickerAnalyticsOption

---

AnkiDroid/src/main/java/com/ichi2/anki/preferences/HeaderFragment.kt
AnkiDroid/src/main/res/values/10-preferences.xml
AnkiDroid/src/main/res/values/20-search-preference.xml
AnkiDroid/src/main/res/xml/preference_headers.xml
tools/localization/src/constants.ts

* FIxes #15453
extract & use strings from `com.github.ByteHamster:SearchPreference` which our translators wish to translate
The repo states:
> If you want to translate the texts shown by the library together
> with your app's other strings, you can just override the strings
> defined in lib/src/main/res/values/strings.xml in your own application
> by copying those lines to your app's strings.xml.
https://github.com/ByteHamster/SearchPreference?tab=readme-ov-file#translations
We license the strings as MIT in a separate file so we may contribute them upstream (20-search-preference.xml)
Add this file to the list of translatable resources
~~I renamed the strings from `searchpreference` to `search_preference` to allow for testing in English: upstream defines '_en' which overrides our …

chore: allow translation of SearchPreference

---

AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/SoundPlayer.kt

Issue introduced in: ee5e267
Cause: mis-abstraction, and didn't stop the legacy TTS in the new TTS Player
https://github.com/ankidroid/Anki-Android/commit/ee5e26702ff55cd83a8dad5bbdab3550c27b26de#diff-7cd4e14b716b1bcd35f3cb3318da36eb706289a8e79658266d1f37d4ff8df796L178
* Fixes #15423
Re-add the missing line
https://github.com/ankidroid/Anki-Android/issues/15423#issuecomment-1942817771
Then testing on API 33 emulator

fix: legacy TTS should stop on card flip

---

AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/viewmodel/TtsVoicesViewModel.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/AboutFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/dialogs/ActivityAgnosticDialogs.kt
AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt
AnkiDroid/src/main/res/values/02-strings.xml

In Android 12L (API level 32) and lower, users might be unsure whether they successfully copied content or what they copied. 
* Fixes  #14992
Tested on Google emulator for API 12 and lower and API 33

enhancement: show copied to clipboard toast for API ≤ 32

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt

This causes an exception report toast
* Defers #15441 to 2.18
We've diagnosed the problem and it's nonfatal so ignore it temporarily
Unnecessay

chore: ignore 'CardBrowser Scroll Issue 8821'

---

AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/PermissionsActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/PermissionsFragment.kt
AnkiDroid/src/main/res/drawable/ic_save_white.xml

**Before**
In dark mode, the 'save' icon didn't appear
**After**

fix: theme for PermissionsFragment

---

AnkiDroid/src/main/java/com/ichi2/anki/pages/DeckOptions.kt

* Fixes #14438 
* ⚠️ Add unconditional back confirmation, as we can't know if changes are made
* Add functionality to save, to be implemented later

Deck Options: add unconditional 'back' confirmation and duplicate save icon

---

AnkiDroid/src/main/java/com/ichi2/anim/ActivityTransitionAnimation.kt
AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/Previewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/EditCardDestination.kt
AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/PreviewerTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt

If a card deck is edited, the previous card was shown but new scheduling was displayed
This was because we used `editorCard`, and `editorCard` was no longer in the correct deck
* Fixes #15402
`undoableOp` handles this all, so trust `updateCardAndRedraw` to do its job
and a few cleanups / logging

fix: editing card deck shows wrong card 

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt

Allow a user to edit notes again
* Fixes #15526
* make the condition on which we call `undoableOp {` more clear
* accept `CALLER_REVIEWER_EDIT`
API 33 & S21
* editing a note from the reviewer edits the note
`undoableOp` was used in REVIEWER, but not sent
Cause: 74487d39f3900e3448d8e8ad1220bacd51fa0a83
* https://github.com/ankidroid/Anki-Android/pull/15496 -> https://github.com/ankidroid/Anki-Android/issues/15402
`updateNote` was removed from the CardViewer and the tests were updated to assume that NoteEditor did this.
I did not realise that `undoableOp` was ONLY sent if the receiver was the Previewer
and falsely presumed testing in the Previewer was testing AbstractFlashcardViewer

fix: unable to edit note in the Reviewer

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/res/values/02-strings.xml

```diff
- Unavailable in ‘Notes Only’ mode
+ Unavailable in ‘Notes’ mode
```
```diff
- card_browser_unavailable_when_notes_only
+ card_browser_unavailable_when_notes_mode
```
And add an 'options' action
review comment on PR #15509
Follow up to #15444
Thank you @snowtimeglass!

chore: improve 'Unavailable in ‘Notes Only’ mode'

---

AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CreateDeckDialogTest.kt

on macos:
```
at com.ichi2.anki.dialogs.CreateDeckDialogTest.setUp(CreateDeckDialogTest.kt:52)
Caused by:
java.lang.OutOfMemoryError: Java heap space
at java.desktop/java.awt.image.DataBufferInt.<init>(DataBufferInt.java:77)
at java.desktop/java.awt.image.Raster.createPackedRaster(Raster.java:538)
at java.desktop/java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1032)
at java.desktop/java.awt.image.BufferedImage.<init>(BufferedImage.java:333)
at org.robolectric.shadows.ShadowBitmapFactory.create(ShadowBitmapFactory.java:287)
at org.robolectric.shadows.ShadowBitmapFactory.decodeStream(ShadowBitmapFactory.java:189)
at org.robolectric.shadows.ShadowBitmapFactory.decodeStream(ShadowBitmapFactory.java:153)
```
* …

test: fix OutOfMemoryError: Java heap space

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt

Looks like there is no need to hide the "Show answer" button
* Fixes https://github.com/ankidroid/Anki-Android/issues/15487
Lets just dont hide button when soft keyboard shows up
manually

fix: no need to hide the "show answer" button

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/utils/WebViewUtils.kt

"No Android System WebView found" was caused because `com.google.android.webview` was searched for, but `com.android.webview` was used.
* also search for `com.android.webview`
API 24 emulator, the actual version of the WebView (52) is now shown
See commit, https://issues.chromium.org/issues/40419837#comment10

chore(debug): fix API 24: 'No Android WebView'

---

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt

the goal of changing the navbar color was to match the answer buttons color that are above it.
If the buttons aren't in the bottom, the color change is dissonant
Emulator 31:
[foo.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/28f291a4-2614-4337-97ad-f43a22874e21)

fix: navbar color if answer buttons aren't in the bottom

---

AnkiDroid/src/main/assets/scripts/card.js
AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/TypeAnswer.kt
AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt

We handled onBlur and pressing enter, but, typing into the field, then pressing 'show answer' did not have the latest value, so `input` was null and a comparison wasn't made
* Fixes #15552
To fix this, we update the typed input on each text change, rather than onBlur
API 24 emulator
* `oninput` rather than `onchange`: `onchange` is similar to `onblur`

fix: wrong input to "type answer into the card" 

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/FilteredDeckOptionsTest.kt
AnkiDroid/src/main/res/values-v29/theme_dark.xml
AnkiDroid/src/main/res/values-v29/theme_light.xml
AnkiDroid/src/main/res/values-v29/theme_plain.xml
AnkiDroid/src/main/res/values/theme_dark.xml
AnkiDroid/src/main/res/values/theme_light.xml
AnkiDroid/src/main/res/values/theme_plain.xml

`android.content.res.Resources$NotFoundException: File res/color/faded_primary.xml from drawable resource ID #0x7f06007d`
`Binary XML file line https://github.com/ankidroid/Anki-Android/pull/17: <item> tag requires a 'drawable' attribute or child tag defining a drawable`
* Fixes #15536
We fix the XML issue by hardcoding the colors
0.06 * 256 = 15.36, so use an alpha of 15/256 (#0FXXXXXX)
API 24 emulator
Samsung S21 (API 34)
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>

hack: [API28] fix crash on 'Filtered Deck Options'

---

AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt
AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/TypeAnswer.kt
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
AnkiDroid/src/main/res/values/10-preferences.xml
AnkiDroid/src/main/res/values/preferences.xml
AnkiDroid/src/main/res/xml/preferences_advanced.xml
AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/TypeAnswerTest.kt

Remove noCodeFormatting preference
* Fixes #15556 
I removed it
I opened the settings and it was gone

remove noCodeFormatting preference

---

AnkiDroid/src/main/java/com/ichi2/anki/Previewer.kt

* Fixes  #15565
the value was never retrieved from the `savedInstanceState`, so it was a no-op
I haven't

fix: crash when leaving previewer if deck is too big

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorIntentTest.kt
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt

it would be greatly appreciated if you could follow up with a regression test in `androidTest`
_Originally posted by @david-allison in https://github.com/ankidroid/Anki-Android/issues/15566#issuecomment-1950966979_
* https://github.com/ankidroid/Anki-Android/issues/15566#issuecomment-1950966979_
Google emualtor and ran test locally 

Test: instrumented test for NoteEditor when text is sent

---

AnkiDroid/src/main/res/layout/gesture_display.xml

This one was a nightmare to diagnose
Introduced in 15333 (a20284e)
* Fixes #15588

fix: gesture display in dark mode

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.kt
AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.kt
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckDropDownAdapter.kt
AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CreateDeckDialogTest.kt

* Fixes #15577
Define `DeckSelectionDialog.deckCreationListener` and handle the change internally so the adapter doesn't need an external rebuild
Selected a deck, double selected a deck, selected a different deck
created a deck
Everything about this is eww

fix(browser): update title on deck creation

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/res/values/02-strings.xml

Can't share to AnkiDroid if an image occlusion note type is selected 
* Fixes #15584
Change the note type to basic when adding an image or text via share intent  
Google emulator - API 34

fix: NPE when adding note via intent

---

AnkiDroid/src/main/java/com/ichi2/anki/AndroidTtsPlayer.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt
AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt

The Anki backend sends `speed` as a non-nullable float The default is '1'
But, using `setSpeechRate(1)` overrides the android system speech rate
* Fixes #15598
So we ignore all values of '1' coming from the backend and treat them as 'use system'
API 33 emulator: 
* No parameter: use system
* `1`: use system
* `0.5`: half speed
* `-1`: error `SPEECH_RATE_FAILED`
* https://github.com/ankidroid/Anki-Android/issues/15598#issuecomment-1953653639
* https://github.com/ankitects/anki/blob/9642a69b88a4cf631af23d49e08df9b918deee8b/proto/anki/card_rendering.proto#L60-L66

hack(tts): treat 'speed = 1' as 'use system'

---

AnkiDroid/src/main/java/com/ichi2/anki/ReadText.kt
AnkiDroid/src/main/res/values/10-preferences.xml

We want to remove legacy TTS, but the migration process is not sufficiently documented.
While we get 2.17 out, remove the nag so we don't get review-bombed more than necessary
This will be reverted once we have a better process
* Fixes #15475 (technically, deferred to 2.18)

temp: remove TTS Nag in Reviewer

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/help/HelpDialog.kt
AnkiDroid/src/main/res/layout/fragment_help_page.xml
AnkiDroid/src/main/res/layout/item_help_entry.xml
AnkiDroid/src/test/java/com/ichi2/anki/dialogs/help/HelpDialogTest.kt

Replaced the original implementation using a ListView with manually adding the "rows" to a layout. This seems to better handle some languages with longer words where the dialog wasn't calculating correctly the row height.
* Fixes #15568
Tried the original scenario which showed the padding issue.

Fix bottom padding issues in HelpDialog

---

AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt
AnkiDroid/src/main/res/layout/my_account.xml

The error space was not blocked resulting in misalignement of edit fields
* Fixes  #15620
Oneplus nord ce

Fix: Block error space for TextInputLayout

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt

This completes the Hungarian Notation removal
* Note Editor
* NavigationDrawerActivity
* AnkiDroidJsAPI
* CardBrowser
<details>
<summary>patch</summary>
```patch
Subject: [PATCH] chore: remove hungarian notation
* Note Editor
* NavigationDrawerActivity
* AnkiDroidJsAPI
* CardBrowser
This completes the removal
tested via `NonPublicNonStaticFieldDetector`
---
Index: lint-rules/src/main/java/com/ichi2/anki/lint/rules/FieldNamingPatternDetector.kt
<+>UTF-8
diff --git a/lint-rules/src/main/java/com/ichi2/anki/lint/rules/FieldNamingPatternDetector.kt b/lint-rules/src/main/java/com/ichi2/anki/lint/rules/FieldNamingPatternDetector.kt
new file mode …
```

chore: remove hungarian notation

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/res/values/03-dialogs.xml

```diff
- metered_sync_warning
+ metered_sync_data_warning
```
```diff
- Your connection is metered. Data transfer may cost money
+ Your internet provider may charge money for data use
```
A user was confused, I feel this makes it more clear
buttons are `[Ignore] [Continue]`

chore: improve 'metered' connection string

---

AnkiDroid/src/main/java/com/ichi2/anki/Import.kt

`onResume` was expected to be called, but wasn't
This meant the `Message` was stored, but not executed.
When a user went to import again, there were two `Messages` to import
Both of these were executed, as finishing the import called `onResume` One executed successfully, showing the dialog
the second executed after the `Import` screen was opened and crashed due to issue 5075
* Fixes #15635
* Closes https://github.com/ankidroid/Anki-Android/pull/15636
Execute the message after it's posted

hack: fix deck import crash

---

AnkiDroid/src/main/res/values/styles.xml

In the black theme, the checkbox had a black tint
* Fixes #15638
This had no contrast with the background, so change it to white

fix: checkbox style in black theme

---

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt

~~Gonna need it to fix a bug~~ Actually, it already fixes the bug of the card browser not being updated after card changes in the new previewer
match the desktop code and return opChanges in setUserFlagForCards
[el fuego.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/83f105e5-322f-4d18-8e9b-0b36ddccdd27)

return opChanges in setUserFlagForCards

---

AnkiDroid/src/main/java/com/ichi2/themes/Themes.kt

the system needs to now the default night mode of the app to get `-night` resources
Emulator 31:
1. create a colors.xml file in `values-night/`
2. override some `@color` resource
3. check out the result in night mode

make possible to use `-night` resources

---

.github/workflows/milestone.yml

As 2.17 is released I think we could change the target milestone to 2.18. See the number at the end of the milestones url https://github.com/ankidroid/Anki-Android/milestone/52

Change milestone target for PRs and issues to 2.18

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt

If a user can't get to the `About` screen, we want this in logcat
```
AnkiDroid Version = 2.18alpha1-debug (f145def4c4ee9b944bcb1df6cd04a636a5cc8bd3)
Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)
Android Version = 13 (SDK 33)
ProductFlavor = amazon
Manufacturer = Google
Model = sdk_gphone64_arm64
Webview User Agent = Mozilla/5.0 (Linux; Android 13; sdk_gphone64_arm64 Build/TE1A.220922.034; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.71 Mobile Safari/537.36
ACRA UUID = 43e6af5c-4182-4226-8933-c5cdda5b2203
Crash Reports Enabled = false
```

chore: log debug info on startup

---

.github/workflows/tests_unit.yml

cache is corrupt on both macOS and Ubuntu. Disable it so CI works again
follow-on from 6768519cbbfab9be604ccf1f5393ed529364fd22
issue:
```
* What went wrong:
Execution failed for task ':AnkiDroid:testPlayDebugUnitTest'.
> A build operation failed.
Immutable workspace contents have been modified: /home/runner/.gradle/caches/transforms-4/f46cf63d0a549c8bc814e25133f449eb. These workspace directories are not supposed to be modified once they are created. Deleting the directory in question can allow the content to be recreated.
> Immutable workspace contents have been modified: /home/runner/.gradle/caches/transforms-4/f46cf63d0a549c8bc814e25133f449eb. These workspace directories are not supposed to be modified once they are created. Deleting the directory in question can allow the content to …
```

fix(ci): disable cache on all runners

---

AnkiDroid/src/main/res/values/styles.xml

Tint for check box in dark theme was poor
* Fixes #15680
Override the `checkBoxStyle` in styles 
Dark:
Black: 
Plain: 
Light: 

Fix: checkbox color tint issue for dark theme

---

AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt
AnkiDroid/src/test/java/com/ichi2/libanki/TemplateManagerTest.kt

To be able to use a server to intercept POST requests in the reviewer, the base url of the reviewer isn't the media directory anymore, so files aren't automatically using the `file:///` protocol
* Fixes #15631
It uses the `file:///` scheme in the tag sources, which allow seeking and has a better performance than using HTTP partial content (I tried https://github.com/ankidroid/Anki-Android/compare/main...BrayanDSO:Anki-Android:fix_audio_seeking)
Emulator 31:
[yeah-boy_3drhy0gn.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/7cb784c8-a3a8-402b-b431-e998d7e182e4)

fix + perf: use file scheme in `<img>` `<audio>`, `<video>` and `<object>`

---

AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt

There is no extension function for listItem in AlertDialogFacade for displaying list in AlertDialog. Currently there are two places ( [Database Error Dialog](https://github.com/ankidroid/Anki-Android/blob/579eb0f0a28be1e095243d753d282af56c489aea/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt#L152)  & [CustomStudyDialog](https://github.com/ankidroid/Anki-Android/blob/579eb0f0a28be1e095243d753d282af56c489aea/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt#L110))its used.
Tested this extension on CustomStudyDialog (#15459). 
[customstudy.webm](https://github.com/ankidroid/Anki-Android/assets/60827173/e78f0065-b857-4842-ae01-450a7a14eac9)

Extension function for listItem in AlertDialog

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt

the fields need to be passed for the card to be previewed, but they weren't built in IO so they couldn't have their values taken
Fixes:
- #15359
The new template previewer showed that there were missing fields in the IO preview, so the rest was easy (good, ain't it? review at #15554)
[oi tudo bem.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/46c7f333-1ebc-497c-a35c-120bb7c5e637)

fix: image occlusion cards couldn't be previewed in the note editor

---

AnkiDroid/src/main/AndroidManifest.xml
AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/PermissionsActivity.kt

* Don't enable the shortcuts unless file access is given
* Keep the widgets disabled until the application has storage access
* Fixes #15686
* Fixes #13518
Keeping the widgets and shortcuts disabled at install and as soon as file access is granted we can enable them, if storage is cleared the shortcuts will be disabled again but widgets, as they won't through NPE in this case
Tested on Google emulator API 34
Fresh install:
After giving out required permissions:

Fix: Keep the widgets & shortcuts disabled until storage permission is granted 

---

AnkiDroid/src/main/java/com/ichi2/anki/pages/AnkiServer.kt
AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt

If a screen is backgrounded, `requireActivity()` throws `IllegalStateException("Fragment " + this + " not attached to an activity.")`
The request which caused this was `/_anki/congratsInfo` which occurred every minute
This was returned to the screen and caused a messagebox to appear
And one messagebox per minute eventually exceeded the system window limit
Causing
* #15659
* Fixes #15679
* Fixes #15659
Allow a `null` activity
⚠️ I can no loner reproduce this, but feel the reasoning is locally sonud

fix: error on POST request if app is backgrounded

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
AnkiDroid/src/main/java/com/ichi2/anki/IntroductionActivity.kt
AnkiDroid/src/main/res/values/02-strings.xml

Fixes the linked issues by notifying the user through a toast(suggestions for the notice message of course welcome) and aborting the import that he must start the app at least once before he can import. At first I tried to be more precise in DeckPicker to try to remove the import dialog message from the handler and then show the toast, this didn't worked at all so I moved the check in IntentHandler.
* Fixes #15672
Ran the tests(but hit some OutOfMemoryErrors) and manually installed debug apks(play and full) to first reproduce and then check the patch.
I dislike the handler system used for async dialogs.

Show toast when importing without the app being started at least once

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorIntentTest.kt

We've got a new flake in CI, caused 2 PRs to eject from merge queue
* Related but not fixing #15707
* seen on #15692 
Mark as flaky, this works in androidTest now, and worked locally
`./gradlew jacocoAndroidTestReport` locally, CI should pass
ENTROPY

test: ignore NoteEditorIntentTest in CI

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt
AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt
AnkiDroid/src/main/res/layout/card_browser_item_my_searches_dialog.xml

Replaces usages of Deprecated MaterialDialog and adds the Native AlertDialog For CardBrowserMySearchesDialog.
https://github.com/ankidroid/Anki-Android/assets/60827173/e94a9360-9d12-462e-9b32-d75a9dcbeed5
~~1. Are we okay with removing the divider lines in My searches which were there in Material Dialog? As in our extension method of Alert Dialog we don't have it. 
2. Padding seems uneven for `(-)`in my searches compared to Material dialog not sure its it good to go or we need to set padding for `(-)` explicitly .~~
1. On closer look when we open save search the keyboard doesn't seems to work it needs a tap at the input and the input opens agains and works fine. I am not able to fix this issue. Need help in this.
2. Can we add prefill for save search? As the user who …

Removed the Material Dialog Box and Added Alert Box from CardBrowserMySearchesDialog

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateNotetype.kt
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerViewModel.kt
AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt
AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerViewModel.kt
AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
AnkiDroid/src/main/java/com/ichi2/anki/utils/ext/String.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Note.kt
AnkiDroid/src/main/res/layout/template_previewer.xml
AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.kt

I wasn't that motivated to port the template previewer, but did it because 1. it was easy after porting the previewer; 2. serves as a proof of concept of generifying the "card viewing" functionality, so it can be reused in the Reviewer port; 3. it is necessary for being able to replace `AbstractFlashcardViewer` completely (and I like diff red lines)
* On top of #15546
In the commits. It is under the new previewer dev option, since I didn't see the need to create a new one for this
Emulator 31:
I changed the `previous/next` button approach to a TabLayout with the templates (which was not only better looking, but simpler to implement), so the three last videos are a bit outdated, but still serve to show the rendering functionality in different scenarios …

feat: port Anki template previewer

---

AnkiDroid/src/main/res/values/10-preferences.xml
AnkiDroid/src/main/res/xml/preferences_accessibility.xml

The advice was incorrect (we should use `%%`, not `\%%`), and the string was duplicated
We had a problem with the Turkish string `\%%%s`
`%%%s` worked
But:
`%%%s` is detected as having 1 format string
`\%%%s` is detected as having 0
and this broke lint
* Fixes #15727
* Unblocks #15726
Remove the bad string, encourage our translator to fix `percentage`
`%s%%`
`%%%s`
and lint passes
```
➜  Anki-Android git:(remove-percentage-summary) ✗ ./gradlew lint
warn: removing resource com.ichi2.anki.debug:string/pref_summary_percentage without required default value.
warn: removing resource com.ichi2.anki.debug:string/pref_summary_percentage without required default value.
warn: removing resource com.ichi2.anki.debug:string/pref_summary_percentage without required default value.
warn: removing …
```

fix: remove pref_summary_percentage

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/GestureSelectionDialogUtils.kt
AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt
AnkiDroid/src/main/java/com/ichi2/ui/GesturePicker.kt
AnkiDroid/src/main/java/com/ichi2/ui/KeyPicker.kt
AnkiDroid/src/main/res/layout/dialog_key_picker.xml
AnkiDroid/src/main/res/layout/gesture_picker.xml
AnkiDroid/src/test/java/com/ichi2/ui/KeyPickerTest.kt

* Fixes #15724
* Fixes #15724
I added the warning inside the dialog like asked but I wasn't able to do it in the joystick dialog

show warning inside control dialog

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt

* Fixes #12364
I used the compat method
I went to the note editor and nothing crashed

fix NoteEditor deprecation

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/NotificationChannelTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/OnRenderProcessGoneDelegateTest.kt

This is a lint failure in android_gradle_plugin 8.3.0
* See PR #15733
`minSdkVersion` is inclusive

chore: replace `@RequiresApi` with `@SdkSuppress`

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt

Replaces usages of Deprecated MaterialDialog and adds the Native AlertDialog For DatabaseErrorDialog
**Restore Backup**
| Material Dialog | Alert Dialog |
|-----------------|--------------|
| ![Material Dialog](https://github.com/ankidroid/Anki-Android/assets/60827173/4182ed26-32f8-4d0c-9a67-393898d7d4ee) | ![Alert Dialog](https://github.com/ankidroid/Anki-Android/assets/60827173/d553ee91-fa43-4795-aa60-22293b6a55b5) |
| Material Dialog | Alert Dialog |
|-----------------|--------------|
| ![Material Dialog](https://github.com/ankidroid/Anki-Android/assets/60827173/7e790e23-9042-4ee7-8dda-5f355e5fbfc8) | ![Alert Dialog](https://github.com/ankidroid/Anki-Android/assets/60827173/787d025e-56d2-4560-baf0-cf1286af05d1) |
_Please, go through these checks before submitting the …

Some Dialogs of DatabaseErrorDialog Converted to AlertDialog

---

.github/workflows/lint.yml

`lintVitalFullRelease` is run on publish, and can fail
So it should also be run on a normal lint check
* Issue #15741
Tested locally.
The fix has not been applied yet, so if lint fails, this works
* https://github.com/ankidroid/Anki-Android/pull/15742

build(ci): add `lintVitalFullRelease` to lint

---

AnkiDroid/src/main/AndroidManifest.xml
AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/PermissionsActivity.kt

* AnkiDroid introduces this bug in #15698 as a fix for #13518 and permanently disabled widgets for users on Android 10 and lower
This Pull Request reverts the above PR, re-enables widgets, and re-introduces a bug with widgets if storage permission is not granted.
As a follow-up, an alternate fix will be applied: widgets will be modified to handle the collection being inaccessible without crashing 
* Fixes #15745
API29 after reverting 
Google issue https://issuetracker.google.com/issues/36914010

revert: disable widget if no storage access

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt
AnkiDroid/src/main/res/values-night/colors.xml
AnkiDroid/src/main/res/values/attrs.xml
AnkiDroid/src/main/res/values/colors.xml
AnkiDroid/src/main/res/values/theme_black.xml
AnkiDroid/src/main/res/values/theme_dark.xml
AnkiDroid/src/main/res/values/theme_light.xml

organize a little the mess that the themes are
[colors.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/e5d25f72-f16d-45ea-a31d-9f19c2c1145f)

refactor: use `-night` to deduplicate browser flag colors

---

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/notetype/RepositionCardTemplateDialog.kt
AnkiDroid/src/main/res/menu/card_template_editor.xml
AnkiDroid/src/main/res/values/02-strings.xml

Just the UI
Not yet implemented due to the logical complexity: the CardTemplateNotetype keeps an in memory log of changes, and a reposition + delete would need to be thoroughly tested to be sure it does not delete incorrect templates
* #6017
Non-functional, just adding the dialog class

NF: Reposition Card Template Dialog

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/AboutFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DebugInfoService.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Config.kt

Added FSRS status to getDebugInfo as a coroutine and converted getDebugInfo into a suspend function and converted it's callers to applicationScopeLaunch.
* Fixes #15447
- Adds info to the debug about weather the user is using FSRS or not, by creating a suspend fun getFSRSStatus(), which uses config.get() to get the FSRS status. 
- Converted getDebugInfo() to a suspend function.
- Wrapped all the relevant getDebugInfo() with a coroutine. 
When through compilation, tested by using a fresh install and running cases the following cases: 
- With no decks (Fresh Install). (FSRS = null)
- One deck with no cards. (FSRS = null)
- One deck with Cards but FSRS has never been enabled. (FSRS = null)
- One deck with Cards and FSRS has been enabled. (FSRS = True)
- One deck with Card and FSRS has been …

Added FSRS info to getDebugInfo

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt

Edit image occlusion fields in the note editor
* Fixes #15610 
* Fixes #15702
The fields aren't hidden anymore and the previews were fixed
Repositioning the fields work too

fix: edit Comments field in Image Occlusion note

---

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
AnkiDroid/src/main/res/menu/card_template_editor.xml
AnkiDroid/src/main/res/values/02-strings.xml
AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt

A number of users post their templates on Anki Forums/Reddit/Discord/GitHub and these are often badly formatted
Providing a Markdown-friendly option seems sensible
* Fixes #15748
* Provide a Markdown formatted template
* updates to the text field are included
**Front template**
```html
{{Front}}
<div id="result"></div>
<div class="result">
</div>
<script>
var jsApi = { "version": "0.0.2", "developer":  "" };
var api = AnkiDroidJS.init(jsApi)
api.ankiGetETA().then(response => console.log(response));
(async function() {
let eta = await api.ankiGetETA();
console.log("2aa" + eta.value);
})();
</script>
```
**Back template**
```html
{{FrontSide}}
<hr id=answer>
{{Back}}
```
**Styling**
```css
.card {
font-family: arial;
font-size: 20px;
text-align: center;
color: black;
background-color: …
```

feat: copy card template to clipboard as Markdown

---

AnkiDroid/build.gradle

as part of the release pipeline failure previously, the build version commit did not land on main, so our version in source on main is stale vs the version already out in alpha channel, causing all releases to fail as the version has been used
Read through the failed release workflow logs and realize the `AnkIDroid/build.gradle` file was still showing alpha3 but alpha4 was rolled out to alpha channel and that explains why the release workflow log failure indicates the build code is too low or already in use...

fix: Play store already has 2.18alpha4, bump version

---

AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt
AnkiDroid/src/test/java/com/ichi2/libanki/TemplateManagerTest.kt

* Fixes #15773
31:
[Screen_recording_20240305_104701.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/57cbc663-7006-41ac-8b01-a8906909783c)
https://jsoup.org/cookbook/input/parse-body-fragment

fix: assets loading with mixed `<script>` tags

---

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/viewmodel/TtsVoicesViewModel.kt
AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt

The success string was default param but failure. Hence making `R.string.failed_to_copy` as default 
I did comment on a PR regarding this but was not resolved 
Google emulator API 34 build successfully 

chore: Failure string as default in `copyToClipboard` method

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt

* Fixes #15787
API 33 emulator with `New Previewer` setting enabled

fix: new previewer - newline handling

---

AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt
AnkiDroid/src/test/java/com/ichi2/libanki/TemplateManagerTest.kt

AVI isn't supported by default in Android's WebView (nor in general [Android](https://developer.android.com/media/platform/supported-formats)), while `.webm` is
* Fixes #15772
In the commits
Emulator 31
1. Add videos [from this site](https://filesamples.com/categories/video) with `webm` and `avi` files
Result: webm videos are played and nothing happens with avi files

Remove `.avi` from supported video extensions, and add `.webm`

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
AnkiDroid/src/main/java/com/ichi2/themes/Theme.kt

In this PR, I tried to update the code using enum.values() instead of the recommended enum.entries 
* Issue #13282 
Using the Android Studio's Inspect Code Option , I found out the files still using the older method and changed them to the recommended method of enum.entries.
I ran `./gradlew jacocoTestReport` to test these changes 

[Clean Up] : Replacing enum.values() by enum.entries

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt
AnkiDroid/src/main/res/layout/dialog_generic_text_input.xml
AnkiDroid/src/main/res/values/03-dialogs.xml

The purpose of this change is to check if the deck name already exists before creating a new deck. This ensures that no deck with the same name exists.
* Fixes https://github.com/ankidroid/Anki-Android/issues/15678
* Fixes https://github.com/ankidroid/Anki-Android/issues/15759
Created a function which takes the input deck name as parameter and checks whether it is present in the Collection or not.
If it is present, user is not allowed to add the deck.
The changes have been tested thoroughly to ensure functionality and compatibility across different devices and screen sizes. The following steps were taken to verify the changes:
1. Opened the "Create deck" section
2. Entered "Default" as the first deck. It didn't create since "Default" deck already exists.
3. Created "test" deck.
4. Tried …

fix: can't create first deck if named 'default'

---

AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionActivity.kt

The purpose of this change is to implement an exit confirmation dialog that appears when the back button is pressed accidentally. This feature aims to prevent users from losing their work accidentally.
* Fixes #15753
The approach taken to address this issue was to add an on `onBackPressedDispatcher` in `ImageOcclusionActivity.kt` and call the method named `showExitConfirmationDialog()` when back button was pressed
Tested the app on Realme Narzo 50 Pro Device

Exit confirmation in IO Editor

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
AnkiDroid/src/main/java/com/ichi2/widget/AddNoteWidget.kt
AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt

* #15698 PR tried to fix the widget issue but it introduced a bug in lower API (Android<=10) which I revert in   #15747
Here in this PR instead of disabling the widgets from manifest file, I updated the flow which is
* The shortcuts are not enabled until the storage access is granted using a return statement in the same function
* Widgets are enabled by default but if user tries to access the widget i.e. open it without storage permission then they are taken to storage permission screen. For existing user having the widgets(we can't update the existing widget that are already added) placing a check in the respective activities to handle the cases and showing a relevant toast that storage permission is missing 
* No existing widget is deleted 
* Not bound to any API level 
* Fixes #13518
* …

Fix: Widget - Missing storage permission causing NPE and crashing app

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TtsVoicesDialogFragment.kt
AnkiDroid/src/main/java/com/ichi2/libanki/DB.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Notetypes.kt
AnkiDroid/src/main/java/com/ichi2/libanki/backend/model/NoteUtil.kt
AnkiDroid/src/test/java/com/ichi2/anki/reviewer/AutomaticAnswerAndroidTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MockMigrationContext.kt
AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.kt
AnkiDroid/src/test/java/com/ichi2/testutils/BackendEmulatingOpenConflict.kt
AnkiDroid/src/test/java/com/ichi2/utils/FileOperation.kt

This PR aims to address the feedback provided by the reviewer in PR #15704. It incorporates necessary changes to meet the review comments and enhance the code quality accordingly.
In this PR, the Android Studio warnings have been resolved to enhance the codebase's cleanliness.
I tested these changes on Level 30 (Android 11).
For additional details, refer to PR #15704

#13282 #15704: Fixes Android Studio Warnings under Kotlin Header

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt

Split from #15840
* we want to run javascript to play a video 
* we needed to access the `WebViewClient` for this
* But the `webView.webViewClient` accessor is API 26+
API 33 emulator for #15840
`onPageStarted` may be called after `evaluateJavascript` is called, therefore `evaluateJavascript` would be executing with the `WebViewClient` state of the previous page

allow access to webViewClient on API 23

---

AnkiDroid/src/main/java/com/ichi2/anki/utils/AndroidUtils.kt

Added Copy to clipboard as a option when openUrl does not have a browser to open a link with.
* Fixes #15671 
- Adds a show snackbar which allows you to copy to clipboard 
When through compilation, tested by using a fresh install and running cases the following cases: 
- Clicking on  help icon with a browser available. Result: Opens as normal
- Clicking on help icon with no browser available. Result: Shows snackbar with copy URL option. (Look below for screenshot)
- [-] You have a descriptive commit message with a short title (first line, max 50 chars).
- [-] You have commented your code, particularly in hard-to-understand areas
- [-] You have performed a self-review of your own code
- [-] UI changes: include screenshots of all affected screens (in particular showing any new or changed …

Added CopyURL function to openUrl fun.

---

AnkiDroid/src/main/java/com/ichi2/themes/Themes.kt

cause f145def4c4ee9b944bcb1df6cd04a636a5cc8bd3
reproduction steps:
1. Disable system dark mode
2. Set theme to `Follow system`
3. Set theme to `Dark` or `Black`
4. Set theme back to `Follow system`
expected result: theme should be light
actual result: theme is dark
API 31, same reproduction steps
AppCompatDelegate.setDefaultNightMode interferes with checking the current night mode

fix: theme follow system configuration

---

lint-rules/src/main/java/com/ichi2/anki/lint/IssueRegistry.kt
lint-rules/src/main/java/com/ichi2/anki/lint/rules/TranslationTypo.kt
lint-rules/src/test/java/com/ichi2/anki/lint/rules/TranslationTypoTest.kt
lint-rules/src/test/java/com/ichi2/anki/lint/testutils/LintAssert.kt

not "javascript" or "Javascript"
* Fixes #15755
Lint
Unit tests

lint: "JavaScript" capitalization

---

AnkiDroid/src/main/AndroidManifest.xml
AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
AnkiDroid/src/main/java/com/ichi2/widget/AddNoteWidget.kt
AnkiDroid/src/main/java/com/ichi2/widget/WidgetPermissionReceiver.kt

* #15765 Aimed to fix the widget NPE issue in case of no storage permission but when the widget is added before allowing file access the widget intent is not updated or set due to returning early, the PR aims to resolve that by using a broadcast receiver and updating the intent as soon as permission are granted, it is usually preferred to use broadcast receivers in case of widget rather than directly accessing the methods. 
Google emulator API 34

Fix: Widget intent not updated if added before storage permission

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/AndroidPermanentlyRevokedPermissionsDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/PermissionsUntil29Fragment.kt
AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt
AnkiDroid/src/main/res/values/01-core.xml

After a period of time with an inactive app, Android 13+ will remove `WRITE_EXTERNAL_STORAGE` if AnkiDroid is unused.
This causes `PermissionsUntil29Fragment` to be shown.
Android does not allow `WRITE_EXTERNAL_STORAGE` to be re-granted (excluding via `adb`)
So we link a user to the same options as we did in `DIALOG_STORAGE_UNAVAILABLE_AFTER_UNINSTALL`
* Fixes #14423
* rewrite https://github.com/ankidroid/Anki-Android/wiki/Full%20Storage%20Access
* Show a dialog providing options
```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
<+>UTF-8
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt …
```

feat: inform users collection is no longer accessible [Android13+ & WRITE_EXTERNAL_STORAGE]

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/pages/CongratsPage.kt
AnkiDroid/src/main/res/values/01-core.xml
AnkiDroid/src/main/res/values/preferences.xml
AnkiDroid/src/main/res/xml/preferences_dev_options.xml

* A large number of users do not like the screen
* I personally feel that it currently has negative utility, but it can be improved
* But users have spoken: hide the page for now and revert to the snackbars we used to use
* Later, we'll improve the screen so it's useful
* Fixes #15349
* Partial revert of 3193cc2174ff443fbb3eccf91da390781c11fb4c
* move the reverted code to `CongratsPage` so we can remove it in future
* Add a development-only preference and gate the new congrats page on it
API 33: snackbars appear. Defaults to 'false' for showing the screen, and the development-only preference works
One more thing for users to look forward to in 2.18

feat: make 'CongratsPage' developer-only

---

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt

fix: change context to match application theme of close icon and white board icon.
* Fixes https://github.com/ankidroid/Anki-Android/issues/15457
* Closes #15858
Replace `this` with `applicationContext` to match application theme, since `ContextCompat()` requires a suitable context.
Before (Light)
After (Light)
Before (Plain)
After (Plain)
Before(Black)
After(Black)
Before(Dark)
After(Dark)
Before (Light)
After (Light)
Before (Plain)
After (Plain)
Before(Black)
After(Black)
Before(Dark)
After(Dark)

fix: change context to match application theme

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/ReadText.kt

Getting Familiar with Project.
* #13282
[AbstractFlashCardViewer]  - Kotlin 1.3 and above supports omission of paranthesis , if constructor is empty , 
[AnkiActivity] - CustomTabsIntent qualifier name is not needed externally, 
[NavigationDrawerActivity] - By default open classes are public in kotlin, 
[ReadText] - unused import directive and also (.*) can be avoided for clean code
Removal of warnings, to maintain the clean code practice

[Cleanup]: Fix Android Studio Warnings #13282

---

AnkiDroid/src/main/java/com/ichi2/anki/SingleFragmentActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerActivity.kt
AnkiDroid/src/test/java/com/ichi2/anki/previewer/PreviewerFragmentTest.kt

* Fixes #15884
handle the key event
Unit tested
Our testers are awesome

fix: Can't exit previewer through Android back button 

---

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/ImageField.kt

* Fixes #15844
Import an image with `%20` in its name

fix: image name with unescaped chars

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/FilteredDeckOptionsTest.kt
AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardSoundConfig.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/pages/CongratsPage.kt
AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
AnkiDroid/src/main/java/com/ichi2/anki/reviewer/AutomaticAnswer.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt
AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt
AnkiDroid/src/main/java/com/ichi2/libanki/utils/LibAnkiAlias.kt
AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/reviewer/AutomaticAnswerAndroidTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/AbstractSchedTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/CardTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/SchedulerTest.kt
AnkiDroid/src/test/java/com/ichi2/testutils/TestClass.kt

`Decks` was pretty badly out of sync with `decks.py`
https://github.com/ankitects/anki/blob/main/pylib/anki/decks.py
I want to get back in sync, as https://github.com/ankidroid/Anki-Android/issues/15611 has shown that we still have issues.
* https://github.com/ankidroid/Anki-Android/issues/15611#issuecomment-1985742924
This will also allow us to more easily deprecate the `legacy` methods, rather than using a combination of new and legacy methods
```python
DeckManager.register_deprecated_aliases(
confForDid=DeckManager.config_dict_for_deck_id,
setConf=DeckManager.set_config_id_for_deck_dict,
allConf=DeckManager.all_config,
getConf=DeckManager.get_config,
confId=DeckManager.add_config_returning_id,
newDyn=DeckManager.new_filtered,
isDyn=DeckManager.is_filtered,
)
```
As a long-term stretch …

non-functional: sync `Decks` with libAnki

---

AnkiDroid/src/main/AndroidManifest.xml
AnkiDroid/src/test/java/com/ichi2/anki/IntentHandlerTest.kt

Working on  #15264 we enabled the images to be shared with AnkiDroid, similarly enabling the application to register itself for the share intent which is not enabled as of now, I originally included it in the PR I mentioned but since it was not part of that was removed for later
* Fixes #15618
Tested on Google emualtor API 34

Enhacement: allow the apkg packages to be shared with AnkiDroid

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt

SharedDecks's SearchView cancel icon is misaligned in landscape mode
* Fixes #15950
By setting searchView width to max, close icon moves to end

Align search view close icon align to end

---

.idea/dictionaries/davidallison.xml
AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt
AnkiDroid/src/test/java/com/ichi2/libanki/TemplateManagerTest.kt

For "legacy reasons" (https://forums.ankiweb.net/t/ankiweb-and-ankidroid-do-not-display-images-containing-pound-hashtag-sharp-symbol/42444/5), anki accepts unencoded `#` in file paths, although that is an URL syntax breakage.
* Fixes #15963
I broke the URL syntax by adding the URL fragment as well while parsing the file source
Emulator 34: opened this deck https://ankiweb.net/shared/info/789434294
Anki sometimes complicates its life more than it should.

fix: handle unencoded `#` in file paths

---

.github/ISSUE_TEMPLATE/bug_report_form.yml

Tested in my branch. I haven't made it `required` because some people don't have a desktop or don't use Anki in their PCs.
I know that the `Anki forums` option exist when selecting a template, but I want to reinforce that the user should check it
I'm very open to the words' choice.

Ask to check if a bug exists in Anki desktop on the bug report template

---

AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CreateDeckDialogTest.kt

In the test there was unused material dialog which was not being used. 
* Fixes #

Refactor : Unused Material Dialog Import

---

AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt

We are getting encoded path when we get the cached copy of the IO image file which caused issue with image rendering 
* Fixes #15908
Use absolute path 

fix: IO - use absolute path for cached copy

---

AnkiDroid/src/main/java/com/ichi2/anki/pages/PageWebViewClient.kt

URL was changed to `page-fully-loaded:` which caused a failure
Massive thank you to our backers for this one!
* Fixes #15790
* Handle `page-fully-loaded:`
* Huawei P8 Lite - Android 6.0 (ALE-L21)

fix: DeckOptions on API 23

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.kt
AnkiDroid/src/androidTest/java/com/ichi2/anki/TestUtils.kt
AnkiDroid/src/androidTest/res/values-sw600dp/bools.xml
AnkiDroid/src/androidTest/res/values/bools.xml

this tablet-detection test started failing on newer/larger emulators that I'm probing locally, and it appears the root cause is that our tablet layout is triggered by the xlarge resource configuration but the test utility was based sw600dp resource configuration overlay
The lack of fidelity resulted in test failures locally
This is just a tangential yak-shave as I'm trying to figure out why gradle internally deadlocks on the dependency-updates branch failing the build so that I can get the gradle plugin update in so that @lukstbit doesn't have the annoying error message about needing to update 😆 
1- Figure out how we actually determine whether to display tablet layout or not (appears to be values-xlarge ?)
2- Determine how test utility is determining tablet layout (bools in values vs …

test: tablet layout is based on xlarge not sw600dp values overlay

---

.github/workflows/tests_emulator.yml
.github/workflows/tests_unit.yml
jitpack.yml

When I bumped the e2e and unit test github runners to 21 I did not also bump the jitpack build, but I believe it is best to have them all using the same build toolchain
I checked to make sure 21.0.2-tem existed, and I added a bunch of documentation on how exactly to figure out what string you use to specify a JDK and how to verify things etc
It's not easy to test these, you need a commit to exist and then you have to verify the commit
Now that the commit exists, I can do that, the URL will look like:
https://jitpack.io/com/github/mikehardy/Anki-Android/e907eb7e3ec365e52557ae896d63a3c141f50530/build.log
(that is: `https://jitpack.io/com/github/<USERNAME>/Anki-Android/<COMMIT SHA>/build.log`)
...and we have to wait to make sure it built - which it did, it worked ✅  …

build: update jitpack JDK used for build to 21

---

.idea/dictionaries/usernames.xml

Noticed we'd missed off Akshay when doing a PR, then roughly audited the list
Search:
```
Copyright \(c\) \d\d2\d (?!(David|Brayan|Shridhar|Mike|Mark|Akshay|Norbert|Timothy|Ankitects|Andrew|Nicola|Nicolas|Mani|Ashish|Tushar|Kostas|mikunimaru|Oakkitten|Shai|Brian Da|Akshit|Divyansh|Arthur|Paul|Tim|Edu|Dorrin|Tarek|The|Square|Anish|Vaibhavi|Kael|lukstbit|krmanik|Nicolai|Mrudul))
```

lint: fix typos - usernames

---

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicMediaClipFieldController.kt

The previous code was blindly splitting after "." which meant that a filename containing extra "." was displayed just as the before and after parts of the first "." char encountered(discarding everything else).
The new code will consider the last "."  encountered of the filename( which should be the "." delimiter for the extension) and split on that if the filename contains extra "." .
* Fixes #16045
Manually tested the code with normal and faulty filenames.

Fix displayed name of attached file when name contains extra points characters

---

AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt

Deleting the deck was triggering a _ChangeManager.opExecuted_ call for _StudyOptionsFragment_ which crashed as it wasn't attached to the activity anymore.
* Fixes #16042
Manually tested the bug scenario.

Fix crash with custom study(with preview cards) when deleting parent deck

---

.github/workflows/label.yml

A small fix to use the proper case for the _Strings_ label in the associated workflow file(where it's compared with what comes from the API). 
Not tested, it doesn't work now so it can't get any worse.

Fix "Strings" label case in label workflow

---

AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt

Sync time is never set so autosync always run when I open the app, or come back to the deck picker
* Fixes the interval bug
I set the interval after syncing
I reopened the app before 10 minutes to see if autosync would happen

fix autosync interval

---

AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/SoundPlayer.kt
AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/SoundTagPlayer.kt
AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerViewModel.kt

web audios couldn't be played with sound:
* Fixes #16041
I passed the whole url if it already had a scheme
I used the provided deck in #16041 and it worked
setDataSource accepts uri strings directly

fix: play web audios

---

.github/dependabot.yml
gradle/libs.versions.toml

and bump version to `0.1.35-anki23.12.1`
Updates: dependencies
https://github.com/ankidroid/Anki-Android-Backend/compare/357abc2d08f49b5b9308bd19bb7e844263517833...70674f6a2a455886af2ec04f327387e5ad3088b0
This PR ensures the mechanism is working so we can upgrade to `-anki24.04`
`io.github.david-allison-1` was burned by a security researcher and it was easier to republish
https://repo1.maven.org/maven2/io/github/david-allison/anki-android-backend/0.1.35-anki23.12.1/
See the following for why we changed the `groupId`:
* https://redirect.github.com/ankidroid/Anki-Android-Backend/issues/347
* https://redirect.github.com/ankidroid/Anki-Android-Backend/pull/361
* https://github.com/ankidroid/Anki-Android-Backend/commit/70674f6a2a455886af2ec04f327387e5ad3088b0
* Part of Issue #16064
YOLOing …

build(deps): update backend to `io.github.david-allison` (v0.1.35)

---

AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt
AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Storage.kt
AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/ScopedStorageMigrationIntegrationTest.kt

Removed in Anki Desktop
> If you wanted to, you could remove collection logging completely - it was removed from pylib a while back.
dae
Replaced log calls with Timber.d
Removed methods/variables:
**Collection**
* debugLog
* logHnd
* fun log
* fun writeLog
* fun _openLog
* fun _closeLog
**CollectionManager**
* disableLogFile
**RobolectricTest**
* disableCollectionLogFile
**Removed Call**
`log(path, VersionUtils.pkgVersionName)`
* Fixes #14777

chore: remove collection.log

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CreateDeckDialogTest.kt

The purpose of this change is to not show Deck already exits error message initially.
* Fixes #15944
* Closes #16030
Added a check in which current test sequence of dialog box is matched with initial deck name
`text.toString() != initialDeckName`
Tested on multiple decks and working fine.

Rename Deck not show error initially.

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
AnkiDroid/src/main/res/values/03-dialogs.xml
AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CreateDeckDialogTest.kt

A regular complaint is that '10' is between '1' and '2' in the deck list
`['1', '10', '2']`
If a user renames a deck, the ordering is correct:
`['01', '02', '10']`
We should inform the user that this is the solution
* Fixes #16036
Unit tests

feat: propose renaming decks to '01' to reorder

---

AnkiDroid/src/main/java/com/ichi2/anki/pages/ImageOcclusion.kt
AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
AnkiDroid/src/main/res/drawable/ic_done.xml
AnkiDroid/src/main/res/layout/image_occlusion.xml
AnkiDroid/src/main/res/menu/image_occlusion.xml

Blocked by https://github.com/ankidroid/Anki-Android-Backend/pull/358 and a backend upgrade
* Fixes #15838
Emulator 34:
[io.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/c888d464-7de1-4e2c-bdc5-6e0b5d8f6ea9)
Updated icon to `Save`:

feat: move IO add button to toolbar

---

AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MigrateEssentialFiles.kt
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/migrateuserdata/MigrateUserData.kt
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/migrateuserdata/MoveDirectory.kt

Get to know the project. Fixed some android studio warnings and weak warnings as per #13282.
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MigrateEssentialFiles.kt: fixed typos in references to functions and constants.
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectory.kt: fixed import paths and made a function private.
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveFileOrDirectory.kt: removed unused import.
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/migrateuserdata/MigrateUserData.kt: made relevant functions private.
- [X ] You have a descriptive commit message with a short title (first line, max 50 chars).

[Cleanup] Fix Android Studio java warnings in anki/servicelayer #13282

---

AnkiDroid/build.gradle

* Exposed by issue #16077
* Fixes #16079
Call `.get()`
> [!WARNING]
> I didn't feel a unit test was of value here, as there's no required format of our dependency version
Checked `BuildConfig.java`
previously: `provider(?)`
now: `0.1.36-anki24.04`
* Cause: bb0c4a85bf71f442170cf7626a60bd6892c35649
* PR: #15966

fix: `BACKEND_VERSION` build field

---

AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DebugInfoService.kt

Cause
* 4506cb4d09376b3da5d4476e5d3cd8a6edc1dfd0
* #15749
`getDebugInfo` was made `suspend`, which meant that `getWebviewUserAgent` was run on `Dispatchers.IO`
* Fixes #16077
* `withContext(Dispatcher.Main)`
* `@MainThread`
API 33 Emulator
```diff
- Webview User Agent = null
+ Webview User Agent = Mozilla/5.0 (Linux; Android 13; sdk_gphone64_arm64 Build/TE1A.220922.034; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.71 Mobile Safari/537.36
ACRA UUID = 31776800-d1f6-4bdd-837e-0266faf77e9c
```
The things which Android should lint but doesn't grows day by day

fix: `getWebviewUserAgent` executes on Main Thread

---

AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
AnkiDroid/src/main/res/layout/statistics.xml

The purpose of this is to match the color of status bar with the statistics toolbar.
* Fixes #16034 
I added a scroll listener which changes the color of the status bar according to the Material toolbar which changes it's color when user scrolls.
I tested the app by scrolling the screen.

Match the color of status bar with Statistic toolbar

---

README.md

Add alt text to images in README for accessibility.
The alt text of the logo banner at the top of README is intentionally set to null. This is because AnkiDroid title text is right below (on line 16) so there is no useful alt text.
Partially fixes issue #13282
Sets alt text image
Inspected webpage in chrome dev tools.
Skipped commenting and screenshots since they are not applicable for a straightforward addition of alt text.

Add alt text to images

---

AnkiDroid/src/main/AndroidManifest.xml
AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt

When the keyboard appears, we cannot scroll to the Bottom in Card Template Editor, making it hard to read and edit the end of the template's text once it reaches a certain length. This happens because the keyboard covers that part of the screen. 
* Fixes #16044
In _CardTemplateEditor_'s activity in _AndroidManifest.xml_, `android:windowSoftInputMode` was `adjustPan` and not `adjustResize`. This change wasn't enough because it caused the _BottomNavigation_ bar to then became taller than expected and covered the editable text, allowing us to view only 1-2 lines of text. To solve this problem, I added code to function _onCreateView_ in _CardTemplateEditor.kt_ to detect when the keyboard appears and consequently change the visibility of _BottomNavigation_ bar. 
Now the _BottomNavigation_ bar …

Fix #16044: Cannot Scroll to End of TemplateEditor

---

AnkiDroid/src/main/res/layout/my_account.xml
AnkiDroid/src/main/res/values/dimens.xml

Minor change:
Removing unnecessary padding from the edit field layout, the input layout already have vertical padding and if we observe closely there is too much padding between the fields, also the errors are enabled which provide padding to the fields
Google emulator
Before: 
After: 
I was working on the notification permission and discovered it, I enabled the error option when migrated the layout to M3, I should have removed it that PR only but over looked it at that time

Fix: unnecessary padding in my_account input layout

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt

* Split from #14843
This completes the move of a sufficient subset of state to the ViewModel. This also starts restructuring search such that it is driven by the ViewModel, rather than driven by the UI
* Blocked on #15077
* Blocked on #15094

refactor: CardBrowser - searchTerms

---

AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
AnkiDroid/src/main/java/com/ichi2/preferences/SliderPreference.kt
AnkiDroid/src/main/res/values/tags.xml

Each move of the slider, another listener was added
This was because `onBindViewHolder` was called multiple times leading to multiple calls of `addOnSliderTouchListener`
* Fixes #16111
Define `setOnSliderTouchListenerOnce` and a tag, only set the listener once.
The listener did not use any holder-specific variables, `slider.value` was fine to use
Logcat output change
```diff
set day offset: '5'
set day offset: '4'
- set day offset: '4'
```
**Learning**
never used `setTag` before; it needs a `R.id`
**Other Considerations**
Since in future a user may decide to use view.addOnSliderTouchListener, we didn't want to call `clearOnSliderTouchListeners()`;
`removeOnSliderTouchListener()` could be used, but it seemed wasteful to remove and then re-add the same listener instance.
Plus, if the …

fix: SliderPreference - listener added many times

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTabOrderTest.kt
AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/InstrumentedTest.kt
AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.kt
AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.kt
AnkiDroid/src/main/java/com/ichi2/anki/CollectionIntegrityStorageCheck.kt
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.kt
AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/SoundPlayer.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
AnkiDroid/src/main/java/com/ichi2/anki/receiver/SdCardReceiver.kt
AnkiDroid/src/main/java/com/ichi2/anki/services/BootService.kt
AnkiDroid/src/main/java/com/ichi2/anki/services/ReminderService.kt
AnkiDroid/src/main/java/com/ichi2/async/CollectionLoader.kt
AnkiDroid/src/main/java/com/ichi2/libanki/DB.kt
AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt
AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MigrateEssentialFilesTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/services/ReminderServiceTest.kt
AnkiDroid/src/test/java/com/ichi2/testutils/BackendEmulatingOpenConflictTest.kt
AnkiDroid/src/test/java/com/ichi2/testutils/CollectionDBCorruption.kt
AnkiDroid/src/test/java/com/ichi2/testutils/rules/MockitoCollectionRule.kt

The commits should be simple. Most of the diff is due to alignment after converting `CollectionHelper` into an `object`.
I didn't plan to do this refactor, nor I actually need it. I was just trying to debug something then ended up cleaning all of `CollectionHelper`
In the commits
CI + With a corrupt collection by renaming any file to `collection.anki2` in an Android 34 emulator: 
[Screen_recording_20240328_134350.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/4900cd2b-feb6-407b-a98f-dd514a3dc319)

refactor: make `CollectionHelper` an `object`

---

AnkiDroid/src/main/assets/flashcard.css

A specific user complaint about white-space, but there was also other inconsistencies
* Fixes #16100
Sync from:
https://github.com/ankitects/anki/blob/97efd49cd8db15a84d2ae2701d21b8283e37bc8c/ts/reviewer/reviewer.scss#L76-L79
I haven't changed colors to match Anki Desktop, as I felt this would require more discussion
⚠️ Briefly.
Visually, no change seemed to occur

fix: sync Anki Desktop `typeans` CSS

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt

DeckPicker SearchView cancel icon is misaligned in landscape mode
* Related #15950 
By setting searchView width to max, close icon moves to end
Physical Device (Realme 9)

Align search view close icon align to end [DeckPicker]

---

AnkiDroid/src/main/java/com/ichi2/anki/notetype/AddNewNotesType.kt
AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt

Replaces usages of Deprecated MaterialDialog and adds the Native AlertDialog For ManageNoteTypes.
| Material Dialog | Alert Dialog |
|-----------------|--------------|
| ![Material Dialog](https://github.com/ankidroid/Anki-Android/assets/60827173/39aaa319-ec81-4507-b6b0-37e0c1a0a8d7) | ![Alert Dialog](https://github.com/ankidroid/Anki-Android/assets/60827173/3f17950c-b33c-4ab5-83e0-4bea20b67f71) |
| ![Material Dialog](https://github.com/ankidroid/Anki-Android/assets/60827173/c4faa5a6-f162-43c9-8c2c-2c128062b1dc) | ![Alert Dialog](https://github.com/ankidroid/Anki-Android/assets/60827173/0d53de72-399f-46aa-aaa9-250996de20ca) |

ManageNoteTypes uses AlertDialog

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt

Dont reset scroll state after deletion
* Fixes #15442 
When user deletes a deck, state of the currently selected deck is reset to 1, while `focusedDeck` variable still holds
deck id of deleted deck, consequently when `renderPage()` is called it executes 
`if (focusedDeck != current) {
scrollDecklistToDeck(current)
focusedDeck = current
}`
resetting the scroll state.
If we change `focusedDeck` to 1, then above if statement is skipped
manually

fix: dont reset scroll state

---

AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerViewModel.kt
AnkiDroid/src/test/java/com/ichi2/anki/previewer/TemplatePreviewerViewModelTest.kt

* Fixes #16155
update currentCard if ord is changed
With the issue steps in emulator 34. Also unit tested

fix(previewer): cards' ord couldn't be changed

---

.github/workflows/tests_unit.yml

Changes requested for issue diagnostics in https://redirect.github.com/gradle/actions/issues/167#issuecomment-2052352341
* Related: #16161
Reverts f9b7ee6818b680e9a97fd57c01e25626520578e0
* temporarily disable `gradle-home-cache-cleanup`
* remove `cache-disabled`
CI only

test(ci): re-enable gradle cache on Windows

---

AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/Full30and31PermissionsFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/PermissionsFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/TiramisuPermissionsFragment.kt

I noticed that I had to do an extra tap after giving the all files permission, so I thought to autoclose the permissions' screen to continue into the app
I thought to directly do the PR instead of doing an issue
I finish the activity if all permissions were granted
I tested in the emulator by giving the all files permissions after it was asked
Nothing

autoclose permission screen after all files permission (i.e. only in `full` builds)

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt

Split out from https://github.com/ankidroid/Anki-Android/pull/16128/ - was very frustrating to track down
Unit tested and had a brief test manually

chore/fix: remove runOnUiThread in CardBrowser

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
AnkiDroid/src/main/java/com/ichi2/anki/notifications/NotificationId.kt
AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncWorker.kt
AnkiDroid/src/main/java/com/ichi2/anki/worker/UniqueWorkNames.kt

Autosync is quite annoying since forever. 
You open the app, with nothing to sync, but you have to wait a dialog the same way
You want to leave the app and do something else, but you have to wait a dialog while everything could be done in the background.
This PR tries to bring decency into that.
* Fixes #15624
In the commits (please read their descriptions)
~~On top of #16056. Only the last two are new~~
I've been using this in my personal build in the last week, and work wonders. Quite a QOL improvement to me. 
Do I fully trust it? No, since some kind of bad internet, bad phone, huge collection may cause a problem that I didn't predict. But maybe it won't. I need people using it to assess it.
Emulator 34:
[alice.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/b1143bbf-979b …

feat: autosync collection in the background when leaving the app

---

AnkiDroid/src/main/res/xml/preferences_accessibility.xml

Step size of 100 causes issue for existing user using the feature as they might not have the current value set to multiple of 100
hence it will be best to remove the step size
* Fixes #16028
Tested on Google Emulator API 34

Fix: remove step size from slider pref

---

.github/workflows/lint.yml
.github/workflows/tests_unit.yml

This was a missing second half of the forward port from "gradle-build-action" to "setup-gradle" - now that we call setup-gradle, for future gradle-related tasks in the workflow you just call the wrapper directly
Nothing documented, just saw a warning in the CI log file while working on #14434 
https://github.com/ankidroid/Anki-Android/actions/runs/8727634201/job/23945575470?pr=14434#step:19:3
Read the docs
Implemented the recommended style for running gradle
Can't test it locally but if CI runs the tests, it worked
https://github.com/gradle/actions/blob/main/docs/deprecation-upgrade-guide.md#using-the-action-to-execute-gradle-via-the-arguments-parameter-is-deprecated

fix(test, ci): call gradle wrapper directly now that setup-gradle is used

---

AnkiDroid/src/main/java/com/ichi2/anki/scheduling/SetDueDateDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/scheduling/SetDueDateViewModel.kt
AnkiDroid/src/main/res/layout-w340dp/set_due_date_range.xml
AnkiDroid/src/main/res/values/03-dialogs.xml

* Fixes #16200
* Define `layout-w340dp` where the EditTexts are stacked vertically
320dp was insufficient, 340 seems fine

fix(set-due-date): small phone layout 

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt
AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/utils/ext/JSONObject.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Config.kt
AnkiDroid/src/main/res/menu/card_browser.xml
AnkiDroid/src/main/res/menu/card_browser_multiselect.xml
AnkiDroid/src/main/res/menu/previewer.xml
AnkiDroid/src/main/res/menu/reviewer.xml
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt

* Display Renamed Flags #16204 
This PR removes the static menu item - flags, from the menu and dynamically load the flag data which allow the user to access the renamed flags if they did rename them in Anki desktop 
* Fixes #16204
Loaded flag from col
Anki ->
AnkiDroid -> 

fix: Use flags from col, dynamically loading them into the menu

---

AnkiDroid/src/main/java/com/ichi2/libanki/ChangeManager.kt

* Note: accidentally closed #16223
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.Reference.get()' on a null object reference
at com.ichi2.libanki.ChangeManager.notifySubscribers(SourceFile:24)
at com.ichi2.libanki.ChangeManager.notifySubscribers$AnkiDroid_fullRelease(SourceFile:65)
at com.ichi2.libanki.ChangeManagerKt$undoableOp$3$1.invokeSuspend(SourceFile:17)
at com.ichi2.libanki.ChangeManagerKt$undoableOp$3$1.invoke(SourceFile:2)
at com.ichi2.libanki.ChangeManagerKt$undoableOp$3$1.invoke(SourceFile:1)
at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(SourceFile:8)
at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(SourceFile:54)
at kotlinx.coroutines.BuildersKt.withContext(SourceFile:1)
at …
```

fix: [maybe] NullPointerException on subscriber.get()

---

.github/workflows/stale.yml

Anki Ecosystem Compatibility issues should all be fixed
* Fixes #16221
Ignore the label
⚠️ needs CI to run for this one
> Comma separated list of labels that can be assigned to pull requests to exclude them from being marked as stale (e.g: need-help,WIP)
docs: https://github.com/actions/stale?tab=readme-ov-file#exempt-pr-labels

build(ci): 'Anki Ecosystem Compatibility' should not go stale
