ankidroid/Anki-Android

AnkiDroid/src/main/java/com/ichi2/anki/scheduling/SetDueDateDialog.kt
AnkiDroid/src/main/res/layout/set_due_date_single.xml
AnkiDroid/src/main/res/values/07-cardbrowser.xml

It would be helpful to add hint text to the "Set due date" field, clarifying that "0 days" indicates today, as it does in the desktop version.
* Fixes #16199
On Realme 6 & Emulator 

Added hint text on "Set due date"

---

.github/workflows/tests_unit.yml

A timeout can cancel tests, which blocks log uploads
⚠️ Untested
* For Issue #16253
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif
https://docs.github.com/en/actions/learn-github-actions/expressions#cancelled

build(ci): upload logs on timeout

---

AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/help/HelpDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/pages/RemoveAccountFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/utils/ext/FragmentManager.kt
AnkiDroid/src/main/res/layout/my_account.xml
AnkiDroid/src/main/res/layout/my_account_logged_in.xml
AnkiDroid/src/main/res/values/01-core.xml
AnkiDroid/src/main/res/values/constants.xml

Google require that we more prominently display 'Delete Account'
* Some of #16256
----
* A 'remove account' button opens AnkiWeb
* A user must log in to AnkiWeb if they did not already do so in 'Shared Decks'
* We perform an internal redirect back to the 'remove account' functionality
* A user must enter their password
* A user must type 'remove'
* with non-validated account
* with validated account
Google 🤷‍♂️ ... happily let copycats into the store, still make us jump through hoops

feat: initial 'Remove account' implementation

---

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt

CI fails giving col already open 
Many solutions were tried the only thing that worked *for the moment* was a revert of the commit that started it
- adding `= runTest` to all reviewer touches in, this causes problems as some tests require GestureHandler to initialize which requires a valid Looper on the thread and `runTest` context is a non-main-thread / no-Looper context
- simply ignoring some tests - this would require ignoring a *lot* of tests
A real solution will involve:
- altering collection exception handling behavior when running in Robolectric context such that backend already open exception is re-thrown as an Error and thus converts the failure from a slow-hang to a fail-fast
- looking at thread affinity rules for collection handling in windows context so that it is really …

fix: handle backend-col already open to fix CI failure

---

.github/workflows/sync_translations.yml

we need to handle the asynchronous nature of the call that might throw an error, otherwise we can never actually catch the error if the PR already exists, and the workflow appears to fail even though it's fine
No issue logged but this has been low-level bugging me forever, and I've been low-level looking at it periodically forever
Finally realized what the problem was
Apologies for just pasting a graphic in but this is what I'm trying to avoid / fix:
("Unhandled" because even though a try/catch should handle any thrown thing, it's async and the error isn't thrown until we're out of the try/catch scope 💡 ! )
Stew on it, then add an await to the call since it is async
Testing shmesting who needs it (kidding, but can only test easily once it's merged and then we run sync translations script …

fix(i18n): sync_translations PR creation is async, await it

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/dialogs/utils/AlertDialogUtils.kt

Replaces usages of Deprecated MaterialDialog and adds the Native AlertDialog For CustomStudyDialog.
| Material Dialog | Alert Dialog |
| --------------- | ------------ |
| ![Material Dialog Image](https://github.com/ankidroid/Anki-Android/assets/60827173/c8039065-b97f-4f27-9b33-9f03ec13809e) | ![Alert Dialog Image](https://github.com/ankidroid/Anki-Android/assets/60827173/2a433b3c-f5f5-4d0b-adb3-32b8eafdfb80) |
| Material Dialog | Alert Dialog |
| --------------- | ------------ |
| ![Material Dialog Image](https://github.com/ankidroid/Anki-Android/assets/60827173/e7a3ce46-60a8-47e1-8485-babe395221bb) | ![Alert Dialog Image](https://github.com/ankidroid/Anki-Android/assets/60827173/c8221b76-8584-42f3-9e7c-c54fa887b861) |
Addition Consideration :
```
.listItems(items = …
```

CustomStudyDialog uses Alert Dialog

---

AnkiDroid/src/main/res/layout/reviewer.xml
AnkiDroid/src/main/res/layout/reviewer_topbar.xml

`tools:menu` isn't working for us.
We include a toolbar, but that requires `app:menu`

docs: fix XML Layout preview for reviewer.xml

---

AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
testlib/build.gradle.kts
testlib/src/main/java/com/ichi2/testutils/FailOnUnhandledExceptionRule.kt

Previously, an unhandled exception would hang, now it fails
* Issue #16253
Assert no unhandled exceptions are thrown
https://github.com/ankidroid/Anki-Android/actions/runs/8859797884
```
WhiteboardDefaultForegroundColorTest > [1] > testDefaultForegroundColor[1] FAILED
java.lang.IllegalStateException: unhandled exception
at com.ichi2.testutils.FailOnUnhandledExceptionRule$apply$1.evaluate(FailOnUnhandledExceptionRule.kt:64)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:588)
at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:290)
at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:101)
at …
```

test: fail on unhandled exception

---

.github/workflows/tests_unit.yml

We had a hard time with windows unit test flake reproduction.
I threw in a crude hack on the workflow as a temporary commit that iterated over windows a lot of times, and that allowed for reproduction confidence
This is an attempt to make that a general feature - so you can select either all 3 operating systems we run or focus on one of them, and you can run an arbitrary number of iterations of unit tests on it (okay, 255 limit, but that's a lot)
* Related #16197 
- first make our matrix generation dynamic
- second make operating system default to all 3 like normal but allow selection if desired
- third add idea of iterations to unit tests, and allow specification of more than 1 if desired
On my separate fork: https://github.com/mikehardy/Anki-Android/actions/workflows/tests_unit.yml
- I …

Ci flake finder for unit tests

---

AnkiDroid/src/main/res/values/10-preferences.xml
AnkiDroid/src/main/res/xml/preferences_accessibility.xml

The original summary for the Show answer long-press time is too lengthy, so it has been shortened to convey only what is necessary.
* Fixes #16081 
On Realme 6 & Emulator
https://github.com/ankidroid/Anki-Android/assets/91668590/20d09386-3b63-4c74-b9e8-f83f0c815b3f

Summarizes show answer long-press time title & summary

---

lint-rules/src/main/java/com/ichi2/anki/lint/rules/TranslationTypo.kt
lint-rules/src/main/java/com/ichi2/anki/lint/utils/ext/XmlContext.kt

This PR addresses a lint improvement in which `...` is replaced with unicode `&#8230;`.
* Fixes #16269
Added a function in `TranslationTypo.visitElement()`  to check if the text contains `...` or not.
I test by running lint test and it shows 
`Error: should use unicode '&#8230;' instead of three dots for ellipsis [TranslationTypo from com.ichi2.anki:lint-rules]
<string name="dialog_processing">Processing...</string>`

Unicode character instead of three dots for ellipsis

---

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt
AnkiDroid/src/main/java/com/ichi2/audio/AudioWaveform.kt
AnkiDroid/src/main/res/drawable/bg_rounded_drop_shadow.xml
AnkiDroid/src/main/res/drawable/ic_play.xml
AnkiDroid/src/main/res/drawable/ic_record.xml
AnkiDroid/src/main/res/drawable/ic_skip_next.xml
AnkiDroid/src/main/res/drawable/ic_stop.xml
AnkiDroid/src/main/res/layout/activity_audio_recording_reviewer.xml
AnkiDroid/src/main/res/values/attrs.xml
AnkiDroid/src/main/res/values/colors.xml
AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivityTestBase.kt
AnkiDroid/src/test/java/com/ichi2/audio/AudioRecordingControllerTest.kt

A few issues/suggestions were raised in #16185 about the audio recorder changes introduced for #13043
* takes up too much space vertically
* increased number of touches required
* ❓ stops working after a while
* ❌ move the recorder to the bottom of the screen
* ✅ A long-press should start, releasing the long-press should stop
* Fixes #16185
1) Major refactor to improve the state handling logic
2) Simplify the Reviewer state to the following, add a new layout and changes to the Waveform control:
```mermaid
stateDiagram-v2
direction LR
[*] --> Empty
Empty --> Recording : ⏺️
Recording --> Empty : ❎
Recording --> Playback : ⏹️
Playback --> Empty : ❎
state Playback {
[*]  --> p1
p1: Paused
p2: Playing
p1 --> p2 : ▶️
p2 --> p1 : ↩️
}
```
3) Add 'on hold' logic for long presses …

feat(check-pronunciation): Streamline UX

---

.github/workflows/conflict.yaml
.github/workflows/tests_unit.yml

We are still seeing some hanging issues and I want to passively detect them now and forever
Related
- #16197 
- #16279 
Idea is: once a day run 15 iterations on each OS
Limitation is: github has scheduling latency, so do not expect it to run at *exactly* the time, but it should run daily
Extra credit: only run this job on main repo, not on forks, and also fix the conflict scan so it only runs on main repo not forks
Testing: https://github.com/mikehardy/Anki-Android/actions/workflows/tests_unit.yml

Scheduled flake hammer

---

AnkiDroid/src/main/java/com/ichi2/anki/DrawingActivity.kt
AnkiDroid/src/main/res/drawable/eraser.xml
AnkiDroid/src/main/res/menu/drawing_menu.xml

The drawing editor did not have any way of undoing a stroke so it was proposed to add an undo button.
Even before this change, when the whiteboard is enabled during a card review, there is an eraser menu icon which undos strokes:
Therefore the same implementation was used for the drawing editor and the same eraser icon was used for consistency. However, its possible the icon could be mistaken for an eraser drawing tool, therefore the undo icon could be a good alternative.
With eraser icon (as implemented in this PR):
Undo icon as alterntive option:
Lastly when there are no strokes to erase, the icon is disabled but remains visible.
* Fixes #16241
[undo_tool_demo.webm](https://github.com/ankidroid/Anki-Android/assets/28263886/37d6f846-f99a-428e-82fd-8337fcad9fe3)

Undo stroke in drawing editor

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt

Before the new collection import, the current collection is closed. After the collection import succeeds DeckPicker runs code to update its UI but that code encounters a closed collection. The fix introduces an empty call to _withCol {}_ to make sure the collection is open and available before any of the code that updates the UI in DeckPicker runs.
* Fixes #16325
* Fixes #16257
Manually tested a new collection import + ran the tests.

Fix refresh of DeckPicker UI after a new collection import

---

tools/localization/src/update.ts

Some devices rely on hebrew translations being in the `values-heb` resource directory and others rely on the translations being in `values-iw`. The solution seems to be to have those values duplicated into `values-iw` in addition to `values-heb`.
* Fixes #9451 
This change reuses the same algorithm used for updating localization resources, with the addition of writing the contents of `values-he` to both `values-heb` and `values-iw`. The only difference now is that `androidLanguage` becomes an array of `androidLanguages`. `androidLanguage` originally represents the destination to copy to, so we iterate through this array to copy the current languages source files to the destinations we set. What this _should_ do is provide the necessary …

fix: localizations not being added to values-iw

---

.github/workflows/tests_unit.yml

Our longest unit test runner is Windows (~18 mins)
We are currently having timeout issues with this runner, hitting this 40 min timeout.
This saves about 7x10 minutes of CI time per day for failed runners
Save the trees

build(ci): decrease unit test timeout to 30 minutes

---

lint-rules/src/main/java/com/ichi2/anki/lint/utils/ext/XmlContext.kt

Alias for Hebrew, Android needs both 'iw' and 'heb'
cause: 0f795cea363ace67bd55ec56775c5beae73c7c9e
* https://github.com/ankidroid/Anki-Android/issues/9451
* https://github.com/ankidroid/Anki-Android/pull/16316
----
* Unblocks https://github.com/ankidroid/Anki-Android/pull/16339

fix: 'iw' is a RTL language

---

AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt

` if (isRecording || isRecordingPaused) {` returned true
so `clearRecording` was called even though `stop()` has been called
which crashed.
```
Done -> stopAndSaveRecording()
then -> done() -> onViewFocusChanged()
```
Cause: cad603ef08a3a0d7ef4f54a8260e3cc7409c3d27
I missed that `stopAndSaveRecording` was public
* Fixes #16321
We fix this by setting the state to CLEARED after stopAndSaveRecording
S21

fix(audio-recorder): crash if saving immediately

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/SyncActionProvider.kt
AnkiDroid/src/main/res/layout/sync_progress_layout.xml

* Fixes #16343
set the tooltip programatically. It requires Android O, so in Android N and lower it will show just Sync
I long pressed the icon to see if the tooltip is shown

fix sync tooltip text

---

AnkiDroid/src/main/res/values/disable-fullscreen-keyboard-highlight.xml

This PR will fix the highlight issue described in #14142 by again adjusting the resource XML configuration, eliminating the persistent dark highlight issue.
Ref PR: https://github.com/ankidroid/Anki-Android/pull/14231
Ref Issues: https://github.com/ankidroid/Anki-Android/issues/15164; https://github.com/ankidroid/Anki-Android/issues/14411
* Fixes #14262
The correction involves modifying the XML definitions for highlight behavior. This change ensures the item highlight remains transparent, addressing the issue directly.
Tested on a physical Android device (OnePlus 8 Pro) with a Bluetooth controller. Without the change, the screen highlights; with the change, it does not.
This was my first contribution to the codebase. I still have much to learn but heavily utilized ChatGPT for guidance.

fix: prevent highlight with bluetooth controller

---

AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt
AnkiDroid/src/main/res/layout/activity_audio_recording.xml
AnkiDroid/src/main/res/layout/activity_audio_recording_reviewer.xml
AnkiDroid/src/main/res/values/02-strings.xml

The purpose of this pr is to add content descripton for record button which help partially sighted users.
* Fixes #16320
Approach is to add `android:contentDescription`  in both the xmls
Tested the app using google talkback

Added ContentDescription for check pronunciation

---

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt

`onCollectionLoaded` is not guaranteed to be called synchronously
* Fixes #16301
init the variable in `onCreate`
⚠️ Only opened the screen, felt it was obvious and low-risk

fix: lateinit property viewPager has not been initialized

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/ViewerResourceHandler.kt
AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerFragment.kt

* Fixes #16352
* Fixes #16373
Add `Access-Control-Allow-Origin = *`, like 2.15.6 had
Emulator 34:
With the deck provided at https://github.com/ankidroid/Anki-Android/issues/16352#issuecomment-2094254299.
If everything is alright, `Testing` is added to the front side.

fix: CORS issue with JS loading

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt

* Fixes #16319
Grant the audio capture permission
With the deck provided in the issue. Now the permission is granted.
https://developer.android.com/reference/android/webkit/WebChromeClient#onPermissionRequest(android.webkit.PermissionRequest)

grant audio capture permission to webview

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsArrayAdapter.kt

The problem was that despite the state within `CheckBoxTriStates.kt` getting updated when the tag list item was clicked (and the icon correctly changing), the `drawableState` would stay the same. As the button tint is linked to the drawableState, whatever was the current color of the checkbox, it would stay that way despite the icon changing.
The solution was to forcibly refresh the `drawableState` when the checkbox state is changed indirectly, either when clicking on the tag list item or when a parents tag state changes due to a child tag.
What I couldn't figure out is why the `drawableState` updates when the checkbox is clicked directly but not when the list item is clicked. The same `onClickListener` for the `checkBoxView` and other methods in `CheckBoxTriStates.kt` are hit in both …

fix: Inconsistent tag checkbox color

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt

Added Unit test to function with @NeedsTest.
* Created test for onDeckSelected to address "15448: double-selecting deck does nothing".
- Unit test completed.
- Ran the Unit test multiple times, and ensured it is passing.

Added test for OnDeckSelected.

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt

Removed code from NoteEditor which was causing #16389 and also removed its fun from Collection.kt
* Fixes #16389 
- Removed the lines mentioned in https://github.com/ankidroid/Anki-Android/pull/14884#discussion_r1420413957
- Also removed it's relevant fun in Collection.kt 
Compiles and builds, and bug squashed.

fix: IO type reappears when card is added

---

AnkiDroid/src/main/java/com/ichi2/anki/CustomActionModeCallback.kt
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt

Extracting the ActionMode Callback from note editor so that it can be reused in instant note editor 

[GSoC'24] chore: extract `ActionMode.Callback` from NoteEditor

---

AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt
AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilRobolectricTest.kt

* Fixes #16183
Use language tag isntead of language
I set my device language to chinese (taiwan) and opened the statistics page to see if it the issue was fixed:
And it was alrgiht

fix language country with system default

---

AnkiDroid/src/main/java/com/ichi2/anki/pages/DeckOptions.kt

* Fixes #16354
I followed this code
I added a delay(3000) in the operation so I could see the dialog because it is too fast

improve optimizing presets message

---

AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt
AnkiDroid/src/main/res/menu/search.xml

* Fixes #16420
Create a new menu
In emulator 31 I checked if the tooltip was correct

fix manage notetypes menu

---

AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerViewModel.kt

https://forums.ankiweb.net/t/what-does-this-error-mean/44915
Initialize the variable instead of depending of lateinit
Opened the templatePreviewer with `Don't keep activities on` + the current unit tests
Don't trust any lateinit
- [X ] You have performed a self-review of your own code

fix: currentCard not initialized

---

AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/utils/ext/Fragment.kt
AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt

Readd a feature
* Fixes #16405
Implements the feature
Tapped the link provided in the issue on the previewer
Nothing

handle android app links in previewer

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt
AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt
AnkiDroid/src/main/res/menu/card_browser.xml
AnkiDroid/src/main/res/menu/card_browser_multiselect.xml
AnkiDroid/src/main/res/menu/previewer.xml
AnkiDroid/src/main/res/menu/reviewer.xml
AnkiDroid/src/main/res/values/01-core.xml

AnkiDroid to use Flag names like Anki 
* Fixes #16222 
On Realme 6 & Emulator
https://github.com/ankidroid/Anki-Android/assets/91668590/67718564-a5d6-44c6-b6cb-7f6b2ae89f30

AnkiDroid to use flag names like anki

---

AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/AndroidPermanentlyRevokedPermissionsDialog.kt

* Related : https://github.com/ankidroid/Anki-Android/issues/13315
| Before (Material Dialog) | After (Alert Dialog |
|--------|--------|
| ![screenshot](https://github.com/ankidroid/Anki-Android/assets/60827173/378feaf2-136e-49c4-997d-b7c8e8decd36) | ![screenshot](https://github.com/ankidroid/Anki-Android/assets/60827173/39bc1c0c-8971-4d48-bf74-6ce3573dcece) |

Migrated AndroidPermanentlyRevokedPermissionsDialog to AlertDialog

---

AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogTest.kt
testlib/src/main/java/com/ichi2/testutils/IgnoreFlakyTestsInCIRule.kt

* Fixes #16404
```patch
Index: build.gradle
<+>UTF-8
diff --git a/build.gradle b/build.gradle
--- a/build.gradle	(revision 7853f54d4bd1d3144b4922defbf98570fe578847)
+++ b/build.gradle	(revision 35e7f8fc0aa0d707c0908e3c47e86a9dc9c84320)
@@ -43,10 +43,10 @@
project.android.testOptions.unitTests.all {
// tell backend to avoid rollover time, and disable interval fuzzing
environment "ANKI_TEST_MODE", "1"
-
useJUnitPlatform()
testLogging {
-                    events "failed", "skipped"
+                    // logging "started" helps us catch timeouts
+                    events "started", "passed", "failed", "skipped"
showStackTraces = true …
```

test(ci): fix windows timeout

---

AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.kt

Quick MaterialDialog -> AlertDialog migration.
* Related to #13315
Ran the tests.

Migrate MaterialDialog to AlertDialog in ModelFieldEditorTest

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt
AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt
AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogTest.kt

Replaces usages of Deprecated MaterialDialog and adds the Native AlertDialog For TagsDialog.
https://github.com/ankidroid/Anki-Android/assets/60827173/a4c14e6e-5cd2-4740-a6fa-ef25207eb4d9
https://github.com/ankidroid/Anki-Android/assets/60827173/e17afcf3-0f1e-427c-9587-7be35fbd6810
https://github.com/ankidroid/Anki-Android/assets/60827173/4539bf8b-7739-420f-9435-ea5277561a0f

Removed the Material Dialog Box and Added Alert Box from TagsDialog

---

AnkiDroid/src/main/AndroidManifest.xml

* Fixes #16410
Rotating statistics and it doesnt vanish

fix stats orientation change

---

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt

Added Unit test to function with @NeedsTest.
* Created test for AddNote() to address "Starting animation from swipe is inverse to the finishing one".
- Unit test completed.
- Ran the Unit test multiple times, and ensured it is passing.

Added Unit test for Reviewer.kt.

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt

* If a note is edited from the Reviewer
* And the note is in a filtered deck
The 'current deck' should show the home deck
Before this change it showed the first deck
* Fixes #15919
Use the home deck
Unit test

fix(note-editor): display 'home' deck if filtered

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/pages/PageWebViewClient.kt
AnkiDroid/src/main/java/com/ichi2/preferences/AutoFocusEditTextPreference.kt
AnkiDroid/src/main/java/com/ichi2/preferences/IncrementerNumberRangePreference.kt
AnkiDroid/src/main/java/com/ichi2/preferences/NumberRangePreference.kt
AnkiDroid/src/main/java/com/ichi2/preferences/StepsPreference.kt
AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt
lint-rules/build.gradle.kts

I wanted this in as a separate refactor, rather than squashing in with the dependency upgrade
We want to ignore these commits in `git blame`
❓ reviewers: I would mildly prefer if you squashed this
I felt the split-out commits were useful for review, but don't provide value in the history
* Unblocks https://github.com/ankidroid/Anki-Android/pull/16440
⚠️ Untested, all should be non-functional
After these changes, I checked for Kotlin 2.0 compatibility:
```
Code inspection did not find anything to report. 19,698 files processed in 'Project 'Anki-Android
```

refactor: Kotlin 2.0 deprecations

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogTest.kt

* Fix a `TransactionTooLargeException` and an `OutOfMemoryError`
This is a tradeoff of stability vs performance. We **should** do much better here in a follow-up 
* Fixes #16226
* Fixes #16351
* Serialize to a file, rather than use Args
* Use `asSequence` to fix an OOM
* This makes the dialog process 2x slower: we need to iterate the selected notes twice 
* This may actually be faster after the PR on some collection, as we perform `select distinct nid` BEFORE loading the notes
* Add a progress dialog to help the user 
My S21, AnKing deck (31479 cards)
No longer crashes on AnKing
⚠️ It is still FAR too slow, needing to individually load 31k cards. This requires a follow-up issue

fix: TagsDialog crashes

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt

If a user went in and out of the 'add note' widget, the value was not persisted. It was only in the cache
* Fixes #13931
* save the note type
Unit tested, brief test in the UI
* `notetype` has a cache, and now should be saved

fix(note-editor): deck for new cards was not saved

---

AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt

Parcelables tend to be faster than Serializables. Not sure if it matters for the 23-25 crash fix merged recently.
Opened the previewer

refactor: use Parcelable for PreviewerIdsFile

---

AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt

The generic needs to apply to both `EmptyApplication` and `AnkiDroidApp`
```
java.lang.ClassCastException: class com.ichi2.anki.AnkiDroidApp cannot be cast to class java.lang.Void (com.ichi2.anki.AnkiDroidApp is in unnamed module of loader org.robolectric.internal.AndroidSandbox$SdkSandboxClassLoader @29f72685; java.lang.Void is in module java.base of loader 'bootstrap')
at com.ichi2.anki.RobolectricTest.validateRunWithAnnotationPresent(RobolectricTest.kt:439)
at com.ichi2.anki.RobolectricTest.setUp(RobolectricTest.kt:105)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at com.ichi2.testutils.FailOnUnhandledExceptionRule$apply$1.evaluate(FailOnUnhandledExceptionRule.kt:57)
at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:489)
at …
```

tests: fix for Kotlin 2.0

---

AnkiDroid/src/main/assets/scripts/js-api.js
AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/ViewerResourceHandler.kt
AnkiDroid/src/main/java/com/ichi2/anki/pages/AnkiServer.kt
AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerFragment.kt

#16140 was an experiment to return to the 2.16.5 way of loading media, which worked by using the `collection.media` directory as base url. The pros were that files load faster and the URL is constant, so localStorage works. The cons were that it needs to accept CORS requests and doesn't work with JS `fetch` and `XMLHttpRequest`
For now my goal is just to restore compatibility with all decks. The new performance is still quite good, just ain't the best one anymore. Some ways to improve performance can be investigated later, *if necessary*, but now compatibility is the priority.
* Fixes #16456
* Fixes #16426
Revert #16140
Doesn't need a backend upgrade
- Seek works on videos
- JS's `fetch` works
- The JS api still works
[loading.webm](https://github.com/ankidroid/Anki-Android/assets/69634269 …

fix: reviewer `fetch` and `XMLHttpRequest` issues

---

AnkiDroid/src/main/java/com/ichi2/anki/preferences/HeaderFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
AnkiDroid/src/main/java/com/ichi2/preferences/HeaderPreference.kt
AnkiDroid/src/main/res/xml/preference_headers.xml

In tablet mode, the selected settings preference category is not highlighted. It would be better if we highlight the preference to have better user experience.
Highlight GeneralSettings preference as default
use onPreferenceTreeClick function and remove highlight from previously selected preference and highlight the current preference
Emulator
https://github.com/ankidroid/Anki-Android/assets/65113071/5a73461b-b068-4cd4-acae-bb3c4949a2bc
Chromebook
[Screen recording 2024-05-19 11.47.35.webm](https://github.com/ankidroid/Anki-Android/assets/65113071/6afbe134-97b8-4ad8-9710-32618ac869e8)

[GSoC'24] Highlight selected preference setting

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.kt

Search icon does not shows immediately when deck length is atleast 10
* Fixes #16452 
update options menu when new deck is created by calling `invalidateOptionsMenu()`
https://github.com/ankidroid/Anki-Android/assets/119813120/ed7c65b6-12f3-4ba8-a136-f98a163a46d1

fix: show search icon instantly

---

AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
AnkiDroid/src/test/java/com/ichi2/testutils/JvmTest.kt

The purpose of the PR is to add a 20s timeout in `JvmTest` and `RobolectricTest`
* Fixes #16435
Added TimeoutRule from this linked commit https://github.com/robolectric/robolectric/commit/5554acdd9c35f15381b0289e0c94f1a08aa39826
Tested this by running it on my local device.

20s Timeout in JvmTest and RobolectricTest

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt
AnkiDroid/src/main/res/values/02-strings.xml
AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt

AnkiDroid used custom made check on field but since Anki already has a method to do so, this PR updates that issue of manual check and check the field content via the Anki method.
* Fixes #16419
Use method from backend
When first field is empty:
When content has no cloze:
Wrong cloze field:

Fix: use field check from backend and display error accordingly

---

AnkiDroid/src/main/java/com/ichi2/anki/utils/CardTemplateJson.kt
AnkiDroid/src/main/java/com/ichi2/anki/utils/ext/NoteType.kt
AnkiDroid/src/main/java/com/ichi2/libanki/NotetypeJson.kt
AnkiDroid/src/test/java/com/ichi2/utils/NoteTypeTest.kt

Anki allows cloze in only the cloze field which is in `qfmt` under `tmpls` here in below screenshot
I am creating this extension method so that I can use it in instant note editor to put text and also the bug in NoteEditor i.e. 
* #16419 can be fixed to check for cloze text in this field along with cloze number >1

[GSoC'24] Chore: extension method to get cloze field name

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt
AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogTest.kt

When deserializing, we called the wrong method so there was an unknown byte as a prefix
`convertToString` was our method, not intended to be used on a `DataStream`
This then failed the string -> JSON conversion
* Fixes #16476
* encode as UTF8 instead
Unit test
* Tested provided collection [see issue]
* Tested personal collection

fix(tags-dialog): crash handling unicode tags

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/ReviewerFragmentTest.kt
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerViewModel.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerViewModel.kt
AnkiDroid/src/main/java/com/ichi2/anki/utils/ext/Flow.kt
AnkiDroid/src/main/res/layout/reviewer2.xml
AnkiDroid/src/main/res/menu/reviewer2.xml
AnkiDroid/src/main/res/values/colors.xml
AnkiDroid/src/main/res/values/preferences.xml
AnkiDroid/src/main/res/values/styles.xml
AnkiDroid/src/main/res/xml/preferences_dev_options.xml

I was going to finish it locally before pushing to avoid churn if I decide to refactor something, but I ended up procrastinating because of it. So, done is better than perfect.
It is currently a developer option. The design features are going to be implemented incrementally to ease the reviewing process and discussion.
When enough features are implemented, my plan is to move it into `Settings > Advanced > Experimental`
Right now it rate cards and exits when finished. Awesome, isn't it?
* Part of #14302 
In the commits
Emulator 34:
<details>
<summary>Light theme screenshot</summary>
</details>
[reviewer.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/bad6b158-0b6a-4d75-9d6f-42e1729be4cd)
_Links to blog posts, patterns, libraries or addons used …

feat: start Reviewer port

---

AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
AnkiDroid/src/main/java/com/ichi2/anki/model/SortType.kt
AnkiDroid/src/test/java/com/ichi2/anki/browser/CardBrowserViewModelTest.kt

* Fixes #16514
* fix a bug in tests (`manualInit`)
* Obtain the sort type from `noteSortType` config if notes are desired
Unit tests + tested on-device with user's collection
* When cards & notes were introduced, we did not test thoroughly, there've been a number of bugs here

fix(card-browser): incorrect 'notes' sort order

---

AnkiDroid/build.gradle
AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
AnkiDroid/src/test/java/com/ichi2/anki/browser/CardBrowserViewModelTest.kt
gradle/libs.versions.toml

Improving code coverage on `CardBrowserViewModel`, this was the first reasonable place to start adding tests
If successful, this will turn a number of partially covered paths greeen
I was surprised with how high the test coverage of the ViewModel is already, but I'd like to make an example of it before I go and refactor the `CardBrowser`
Test Only
⚠️ Due to the implementation, the collection returned from each `emit` is currently the same. This is subject to change in the future
This introduces Turbine, a Google-recommended library for testing flows
https://github.com/cashapp/turbine - last commit two weeks ago
https://developer.android.com/kotlin/flow/test

test(card-browser-view-model): increase code coverage

---

tools/localization/src/constants.ts
tools/localization/src/update.ts
tools/localization/src/upload.ts

Related to PR 16348 - the file is no longer needed as it was for the special (now defunct) ChromeOS store. We stopped processing it, but we were still uploading it for translation (and the file was still up in crowdin so being downloaded...)
* Completes the work I did not realize still needed to happen from #16348
* Unblocks #16526
1. try to figure out where 15-markettitle.xml is coming from, since we no longer handle it specially
2. realize it *used* to be handled by pulling the xml from the download from crowdin and moving it so the resources didn't have invalid XML
3. realize that the file was still up on crowdin even though we no longer need it! Delete it there
4. think you're done, re-run translation sync
5. realize that it failed for same reason because we still create / upload the …

fix(i18n): file 15-markettitle.txt is gone, remove remnants

---

AnkiDroid/src/main/AndroidManifest.xml
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/TextSurroundHelper.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/DevOptionsFragment.kt
AnkiDroid/src/main/res/drawable/ic_round_open_in_new.xml
AnkiDroid/src/main/res/layout/instant_editor_dialog.xml
AnkiDroid/src/main/res/layout/instant_editor_field_layout.xml
AnkiDroid/src/main/res/values/03-dialogs.xml
AnkiDroid/src/main/res/values/constants.xml
AnkiDroid/src/main/res/values/preferences.xml
AnkiDroid/src/main/res/xml/preferences_dev_options.xml
AnkiDroid/src/test/java/com/ichi2/anki/instanteditor/InstantEditorViewModelTest.kt

On top of: 
* #16497
This PR aims to provide basic functionality for the instant note editor i.e. allowing the user to add cloze card without actually opening AnkiDroid application, to achieve this we utilize a transparent activity with custom theme.
* The activity has intent filter to register and receive text when user taps share button after selecting text
*  `Instant card` label used for the activity
* `EditTextGestureHelper` allows user to single tap and turn words to cloze
* User can also long press and select multiple words/text and turn it to cloze
* Deck spinner allows user to change deck
* User can tap in/out manual mode if wanted
* Cloze increment button allows user to increment cloze number
OnePlus Nord CE:
Current UI: …

[GSoC'24] Feature: Instant Note Editor to allow adding cloze card

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/ReviewerFragmentTest.kt
AnkiDroid/src/androidTest/java/com/ichi2/anki/ReviewerTest.kt

After implementing the reviewer fragment thing in the new reviewer with #16455 the custom scheduler test was failing for me on the command line so my customary / frequent `./gradlew jacocoTestReport` did not pass
I believe others did not notice it because:
1- it is not executed in CI because of a Flaky annotation
2- I suppose people developing locally either don't run tests or run them from Android Studio? I use the command line
I need that to pass, so I looked into it, and this or something like this will fix it
* Fixes regression from  #16455
1- realize by view hierarchy inspection that the hierarchies are different from the command line and from Android Studio. I have no idea. They are though. So...allow either name for the the layout flip or ease 3 button view resource to match 🤷 
2- …

test(custom-scheduler): stabilize custom scheduler testing

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt

If a card in a filtered deck was edited, it was returned home
* Fixes #16522
* Cause: https://github.com/ankidroid/Anki-Android/commit/b455b7b135a8eb003efd862412013ccdbf8196c4 
Unit tested
In Emulator:
* Card in filtered deck
* Tested editing the content -> same deck
* Tested editing the deck -> changed deck

fix(note-editor): filtered card sent home after edit

---

AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt
AnkiDroid/src/test/java/com/ichi2/testutils/JvmTest.kt
AnkiDroid/src/test/java/com/ichi2/testutils/TestChangeSubscriber.kt

* Diagnostics for https://github.com/ankidroid/Anki-Android/issues/16541
```
-- executing test "suspend - notes - some notes suspended"
Backend: Opening rust backend with lang=[en-US]
Media: dir /var/folders/ym/nqynp93d4j74dpzw20sq4wq00000gn/T/robolectric-CardBrowserViewModelTest_suspend_-_notes_-_some_notes_suspended5512359334772938846/external-files/Android/data/com.ichi2.anki.debug/AnkiDroid/collection.media
Collection: (Re)opening Database: /var/folders/ym/nqynp93d4j74dpzw20sq4wq00000gn/T/robolectric-CardBrowserViewModelTest_suspend_-_notes_-_some_notes_suspended5512359334772938846/external-files/Android/data/com.ichi2.anki.debug/AnkiDroid/collection.anki2
CollectionManager: blocked main thread for 174ms:
com.ichi2.testutils.JvmTest.getCol(JvmTest.kt:55)
CardBrowserViewModel: …
```

chore(card-browser): logs

---

AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt

Previously this resulted in a `NullPointerException`
Seen in https://redirect.github.com/ankidroid/Anki-Android/pull/16529
before:
```
java.lang.NullPointerException: null cannot be cast to non-null type androidx.appcompat.app.AlertDialog
```
after:
```
org.opentest4j.AssertionFailedError: A dialog should be displayed ==> expected: not <null>
```

test: improve 'getLatestAlertDialog' error

---

AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
AnkiDroid/src/test/java/com/ichi2/anki/browser/CardBrowserViewModelTest.kt

Another step in getting good coverage on the ViewModel before a rewrite

tests(card-browser-view-model): `getSelectionExportData`

---

AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnkiDroidCrashReportDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MigrationProgressDialogFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TtsVoicesDialogFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/PickStringDialogFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/dialogs/tools/AsyncDialogs.kt

I noticed that some dialogs were using android.AlertDialog instead of appcompat so I updated them
* Fixes #15174 after my other PR is merged as well
Update the dialog library
In an Android 14 emulator by checking the Manage space dialogs

use appcompat AlertDialog

---

lint-rules/src/main/java/com/ichi2/anki/lint/IssueRegistry.kt
lint-rules/src/main/java/com/ichi2/anki/lint/rules/AvoidAlertDialogUsage.kt

This PR contain a custom lint rule aimed at flagging the use of android.app.AlertDialog. It encourages developers to switch to androidx.appcompat.app.AlertDialog for improved compatibility and features, promoting better coding practices and adherence to modern Android standards.
Fixes #16554 
Locally on Android Studio

Fix: Lint to avoid using android.app.AlertDialog

---

AnkiDroid/src/main/java/com/ichi2/anki/notetype/AddNewNotesType.kt
AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt

Focus keyboard on AddNewNotesType and renameNoteType.
`requestFocus()`
https://github.com/ankidroid/Anki-Android/assets/119813120/a4e832a6-f11d-4133-95a3-4675f4230be4

Focus keyboard

---

AnkiDroid/src/main/java/com/ichi2/libanki/ChangeManager.kt

Documented that lambdas should not be used

docs: ChangeManager.Subscriber - lambdas

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt

I was looking into `updateSelectedCardsFlag` and realized that `Collection.load()` was called in a loop, instead of `Card.load()`
Broken in https://github.com/ankidroid/Anki-Android/commit/0d69cacde9886feba40b98e19f851e62d5a29fcd
* I removed the obviously broken code, and simplified the caller
No additional tests, I'll unit test this in a later commit
EDIT: Tested manually as this method had no coverage

refactor(card-browser): updateSelectedCardsFlag

---

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt

* Fixes #15912
* Fixes #15912
only apply the style if on gestures mode
<details>
</details>
<details>
</details>
I researched a lot but didn't discover how to check how to scrim.
After reading some PRs is that I found the navBarNeedsScrim property in the repo

fix navbar color in reviewer

---

AnkiDroid/src/main/java/com/ichi2/anki/ui/OnHoldListener.kt
AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt

This PR implements the "hold to record" functionality for the Pronunciation Check feature, as proposed in issue #16282. 
* Fixes #16282 
On Realme 6 & Emulator
https://github.com/ankidroid/Anki-Android/assets/91668590/af570332-98d6-4dcf-acb7-eef184f1d4d9

Implement 'Hold to Record' Functionality

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/browser/CardBrowserViewModelTest.kt

CardBrowser will move to render using either the card id or the note id
Our data is currently ALWAYS CardIds, which may be transformed into NoteIds
We had code assuming that the CardId was always used which needed to be modified to handle the case that a DB call is needed to map NoteId <-> CardId
* Starts work on #11889
* selectedRowIds
* allCardIds
* Now needs to be `suspend`
* get[Selected]CardIdAtPosition
* Now needs to be `suspend`
Unit tests + brief physical test

refactor(card-browser): remove rowId references

---

AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt
AnkiDroid/src/main/java/com/ichi2/widget/WidgetPermissionReceiver.kt
AnkiDroid/src/main/java/com/ichi2/widget/WidgetUtils.kt
AnkiDroid/src/test/java/com/ichi2/widget/WidgetUtilsIntegrationTest.kt

On a Supernote A5X, `AppWidgetManager.getInstance(context)` returns `null`
https://www.reddit.com/r/Supernote/comments/1dcqk47/comment/l7znpix/
Brief unit test

fix: AppWidgetManager can be null

---

AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
AnkiDroid/src/test/java/com/ichi2/anki/preferences/PreferencesTest.kt

After finishing all cards for a day, changing Start of Next Day to the past and trying to access that same deck would result in a message saying that all cards were finished for the day.
This was due to the fact that the scheduler did not update after the rollover change
Previously, this issue would require restarting anki.
* Fixes #15553
`config.set("rollover", hours)` only updates the database, this change will eventually propagate, however the scheduler will not update what cards to show. This is caused by the transaction of config.set not requiring a queue rebuild (as it's only DeckConfig)
By calling `setPreferences(newPrefs)` this will reset scheduler_info as well as a transaction that will require a study queue rebuild.
By following …

Fix #15553: Start of Next Day Not Working

---

AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BrowserOptionsDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/FlagAdapter.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/FlagRenameDialog.kt
AnkiDroid/src/main/res/layout/browser_options_dialog.xml
AnkiDroid/src/main/res/layout/edit_flag_item.xml
AnkiDroid/src/main/res/layout/rename_flag_layout.xml
AnkiDroid/src/main/res/values/01-core.xml
AnkiDroid/src/main/res/values/03-dialogs.xml

* #16205, Anki allows flag to be renamed from card browser so replicating that this PR provides a menu option through which we can rename the flag and after sync the same is reflected in Anki desktop 
* Fixes #16205
AnkiDroid: (orange flag)
Anki after sync:

Enhancement: allow renaming flag from CardBrowser menu

---

AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt

Hide the back button in StudyOptionsFragment when fragmented
set toolbar navigation icon to null
Physical Device ( ChromeBook )

remove back button if fragmented

---

AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnkiDroidCrashReportDialog.kt
lint-rules/src/main/java/com/ichi2/anki/lint/rules/AvoidAlertDialogUsage.kt

use android import for crash report dialog instead of androidx as crash report acitivity is a external dependecy activity and using androidx requires theme.appCompat
* Fixes #16604 
Locally tested on emulator

fix: use android import for crash report dialog

---

AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
AnkiDroid/src/test/java/com/ichi2/anki/browser/CardBrowserViewModelTest.kt

I think this is the last one - I want to get code coverage up on this
**Later intentions**
Firstly I'm going to change the Browser to use Anki Desktop for the searching and rendering, which modifies how the class handles 'notes' mode, so I want decent coverage here
Currently the class is keyed on `CardId`, after the backend, it will be keyed on `CardId | NoteId`, and the backend will handle rendering
Afterwards, I will rewrite the search process to enable a multitude of filters using chips, modifying the state of the class from:
* no search
* searched/deck selected - nothing selected
* selected
into:
* rows selected
* nothing selected
where searching is a separate dimension of state
Unit Tests

test(card-browser-view-model): increase coverage

---

AnkiDroid/src/main/java/com/ichi2/anki/MetaDB.kt
AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
AnkiDroid/src/main/res/menu/reviewer.xml
AnkiDroid/src/main/res/values/01-core.xml
AnkiDroid/src/main/res/xml/preferences_custom_buttons.xml
AnkiDroid/src/test/java/com/ichi2/audio/AudioRecordingControllerTest.kt

Currently the 'Check pronunciation' menu item needs to be selected every time a new review session starts. Now with this feature, the enabled state persists between review sessions and is specific to each deck. Additionally the menu item has be renamed to reflect the enabled state of the feature (i.e. whether it will be enabled or disabled when the menu item is clicked).
[Toggle voice playback.webm](https://github.com/ankidroid/Anki-Android/assets/28263886/4c45fe0a-9522-428c-b29d-317487f753de)
* Fixes #16288

feat: Toggle check pronunciation feature

---

.github/workflows/compare_apk_size.yml

There was a question on PR #16601 about the size effect of the change
I've wanted to have objective data for this question on any PR for a while, and it's relatively easy to do
The only complication is that you want to do a release build (to make sure minimization happens etc), but to do that you need a keystore etc
Not too hard to handle though, so I've given a minimum-viable-product attempt here
- setup tools
- setup test keystore
- do a main release build and get the size
- do a PR release build and get the size
If this works in a basic mode like this I will likely extend it immediately so that it posts a comment on the PR with the size difference
I should test this in my fork, but hopefully it runs on the PR here as well ?
- stackoverflow still has all the answers (this time, how to …

feat(ci): apk size comparison workflow

---

.gitignore

This appears to be a 'session-is-alive' file which appears when compiling
https://github.com/JetBrains/kotlin/blob/ca34e5d2fd255ed0501bae4fae3d3691dc40d375/libraries/tools/kotlin-gradle-plugin/src/common/kotlin/org/jetbrains/kotlin/compilerRunner/GradleKotlinCompilerRunner.kt#L458
Example:
`.kotlin/sessions/kotlin-compiler-9293527262404664068.salive`

chore: ignore Kotlin 2 `.salive` files

---

common/build.gradle.kts
common/proguard-rules.pro

I think this is a proguard related issue as the code works in debug and fails in release.
Running `./gradlew  :common:assembleRelease` shows no classes /proguard mapping is produced and this is verified by adding -`printusage [filename]` in the proguard rules which lists the classes in the common module as unused and a target for removal. See the documentation for the -dontshrink rule https://www.guardsquare.com/manual/configuration/usage .
To fix this I copied the rules we have in the main module.
I also added a second commit to change the compatibility in common module  to Java 11 which is used by all other modules.
* Fixes #16619
Not that much testing.

Fix missing class errors for classes in common module

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/FlagRenameDialog.kt
AnkiDroid/src/main/res/values/03-dialogs.xml

* This made it more obvious that the 'tick' should be pressed
* Cancel didn't work as expected
* OK didn't perform saves
* Prompted by https://github.com/ankidroid/Anki-Android/pull/16244#issuecomment-2180497998
* Related: #16205
Emulator - 
I can still edit flag names

improvement(rename-flag): remove 'ok/cancel'

---

AnkiDroid/build.gradle

Robolectric test dependencies have been included in builds since release 2.18alpha7 (https://github.com/ankidroid/Anki-Android/compare/v2.18alpha6...v2.18alpha7). This PR aims to fix that and restore the original behavior of Gradle builds, resulting in smaller output APKs.
Related: https://github.com/ankidroid/Anki-Android/issues/16626

Exclude robolectric deps from release

---

AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncMediaWorker.kt

Change the media sync negative button's label in terms of its role and consistency with Anki Desktop
---
AnkiDroid
_ _ 
---
Anki Desktop
* Related: #16631 
Reuse Anki Desktop string
Tested on physical device (Android 11)

Rename "Cancel" of Media Sync to "Abort"

---

.github/workflows/compare_apk_size.yml
.github/workflows/publish.yml
AnkiDroid/build.gradle
tools/check-keystore.sh
tools/local-release.sh
tools/parallel-package-release.sh
tools/release.sh

Keystore variables are (partially) hardcoded right now. It is better if we switch to using environment variables for all of it.
Makes easier for devs to source their signing keys in the way they wish (e.g., custom keystore path, key alias).
N/A
Use environment variables for all of signingConfig in build.gradle. Change relevant workflows and scripts to adapt.
tools/local-release.sh ran locally (until my laptop turned into a jet, then I settled with ./gradlew assemblePlayRelease)
I have adapted most of the things to match build.gradle, but not sure if e.g. the publish workflow still functions as it should after these changes. Needs to be tested.
N/A

Switch from hardcoded signing config

---

AnkiDroid/jacoco.gradle

The new zero coverage assertion added in #16643 tries to warn you if there is zero coverage of a certain type
But, it doesn't look like string format works in logger.warn, use concat
Saw this when trying to carry all this coverage work over to react-native-firebase and wanted to cross-pollinate the fix here
Even the tests you run on your tests need tests
Turtles all the way down

test: fixup warning message when no coverage of type is found

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.kt

`ViewActions.closeSoftKeyboard` became `@CheckResult`
`androidx.test.espresso.Espresso.closeSoftKeyboard` is not
* Unblocks #16657
Checked out 16657 and applied the patch. No red underline in the IDE

fix(tests): allow update to espresso 3.6.1

---

AnkiDroid/src/main/java/com/ichi2/libanki/ChangeManager.kt

No point in logging a no-op in `@Before`
removes log: `D/ChangeManager: clearing 0 subscribers`

tests: reduce log spam in `ChangeManager`

---

AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt
AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/CustomSyncServerSettingsFragment.kt
AnkiDroid/src/main/res/values/03-dialogs.xml
AnkiDroid/src/main/res/values/10-preferences.xml
AnkiDroid/src/main/res/values/preferences.xml
AnkiDroid/src/main/res/xml/preferences_custom_sync_server.xml
AnkiDroid/src/test/java/com/ichi2/anki/analytics/PreferencesAnalyticsTest.kt

Copied from https://github.com/ankidroid/Anki-Android/pull/15996
Since the new backend is forced on the newer Ankidroid releases, Android users cannot connect to their self-hosted sync server if it uses a self-signed certificate. The problem should be fixed with this PR. More than willing to accept any changes made to the UI part of this feature, it ain't that pretty.
* https://github.com/ankidroid/Anki-Android/labels/Blocked%20by%20dependency https://github.com/ankidroid/Anki-Android-Backend/pull/381. 
* Fixes #14686 
Allow users to specify a custom root certificate to trust (in PEM format) and feed this through the backend.
Took the PEM-formatted root certificate I use for my local servers, and then copied the contents of it into the text field in the custom sync server section. After …

Add support for custom certificate

---

AnkiDroid/src/main/java/com/ichi2/anki/notetype/AddNewNotesType.kt

The previous code verified the name entered by the user against all notetpes names, existing names + names of the standard notetypes. Changed to check only against existing notetype names.
* Fixes #15643
Tried to add a notetype with a standard name(after deleting that notetype).

Fix adding a notetype when using the name of a standard notetype

---

AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt
AnkiDroid/src/main/res/drawable/ic_flag_lightgrey.xml

Fixes #16622 
**No Flag Icon not showing on light theme**
I have changed the icon color to light grey.

No Flag Icon not showing on light theme, Fixed #16622

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
AnkiDroid/src/main/res/menu/deck_picker.xml
AnkiDroid/src/main/res/menu/study_options_fragment.xml
AnkiDroid/src/main/res/values/01-core.xml

This PR aims to 
1. Convert deckpicker to have single menu
2. Remove StudyOptionsFragment when collection is empty
3. Remove back button when fragmented
Moved menu items from DeckPicker screen to StudyOptionsFragment
Emulator
https://github.com/ankidroid/Anki-Android/assets/65113071/78a26dbf-eb91-4bef-ac08-9b01eb3b6bc9
Chromebook
[Screen recording 2024-05-22 11.08.56.webm](https://github.com/ankidroid/Anki-Android/assets/65113071/4723287c-5c48-4b97-94cd-319699dbacd9)

[GSoC'24] Refactor DeckPicker to Single Menu Layout

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt
AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt
AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt
gradle/libs.versions.toml

In API 34, `registerReceiver` needs to either accept `RECEIVER_EXPORTED` or `RECEIVER_NOT_EXPORTED`,
otherwise an exception is thrown
* Fixes #16713
* Fixed #16711
So, introduce `Context.registerReceiverCompat` to avoid code churn, and use it
I opened AnkiDroid using `targetSdk 34`. It opened, I then tried to download a deck and it seemed to work
https://developer.android.com/about/versions/14/behavior-changes-14#runtime-receivers-exported

fix(broadcast-receivers): specify export behavior (API 34)

---

AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardMediaPlayer.kt
AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt
AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerViewModel.kt

Video demonstration of the card preview only auto playing the audio when the setting is on:
[preview_audio_autoplay_fix.webm](https://github.com/ankidroid/Anki-Android/assets/28263886/c31d166a-06a7-4a93-a4c8-e7197e904d5b)
* Fixes #16519

Fix: Autoplay audio on card previews only when setting is enabled

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
AnkiDroid/src/main/res/layout/dialog_generic_text_input.xml

Pressing ImeAction button on keyboard during Deck Creation resulted in new line in TextField
Defining a Done button click listener from the keyboard inside the input callback of the AlertDialog fixed this issue
on android 14 samsung f23 physical device
https://github.com/ankidroid/Anki-Android/assets/116078997/5d330151-1756-425f-8c0e-e08883762df9

Fixed keyboard done button during creation or renaming of deck

---

AnkiDroid/src/main/java/com/ichi2/preferences/SliderPreference.kt
AnkiDroid/src/main/res/layout/preference_slider.xml

I tried a different approach to fix #15738 that I think will work better than what the issue proposed
* Fixes #15738
I moved the value display to the top-end of the preference
[access.webm](https://github.com/user-attachments/assets/4a46a322-0edc-4e1e-b804-173a92232e71)

Improve SliderPreference value display

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/test/java/com/ichi2/utils/KeyUtilsTest.kt

I don't expect it was causing a bug, but `onKeyUp` almost always returned false, even when the key press was handled.
This is now corrected.
I had trouble understanding the `selectFieldIndex` part. I hope I improved it. Also added a unit test, given the simplicity of this part of the code.
I wanted to test the remaining of KeyUtils, but got error messages, telling me
java.lang.RuntimeException: Method getUnicodeChar in android.view.KeyEvent not mocked. See https://developer.android.com/r/studio-ui/build/not-mocked for details.
at android.view.KeyEvent.getUnicodeChar(KeyEvent.java)
at com.ichi2.utils.KeyUtils.getDigit(KeyUtils.kt:30)
I'd be interested in help if it's quick to do. But otherwise, it's not worth losing time on it.
This should hopefully not conflict much with …

NF: NoteEditor onKeyUp return true

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/ReadText.kt
AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/TtsVoices.kt

Fix Android Studio code inspection warnings.
* Fixes #13282
Followed the suggestion of android studio 
Ran unit tests locally.

Fix Android Studio Warnings

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt

After reproducing https://github.com/ankidroid/Anki-Android/issues/16702, I discovered that actually, the part of the
code where the NPE occurred should not have been reached.
newModel and oldModel are two distinct objects representing the same
note type. And JSonObject's equality is defined as pointer
equality. Using id instead of actual note type repair the bug.
Since, in AnkiDroid, editing the note type through the reviewer, can't
lead to adding or removing field, this is safe to consider that if the
id is equal, the objects are equal as far as the list of field is concerned.
I fear I don't see how to test it easily. It seems it require
AndroidTest and not unit tests, and I can't find example of note editor
test. Furthermore note editor will be replaced soon, so I don't expect
it's …

Fixe NPE in note editor

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/IntegerDialog.kt

This PR refactor IntegerDialog class to handle use case in
*  #16735
We want to allow the current cloze number to be displayed in the dialog input box
Locally

[GSoC'24] Refactor: use prefill value in integer dialog

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
AnkiDroid/src/main/res/values/02-strings.xml

This PR:
- moves the last part in the export process(where the exported collection is written to the file chosen by the user) in a coroutine on a background thread
- improves the UX around importing by showing a progress dialog for the first part of importing where the imported collection file is first copied
* Fixes #16694 I marked this as fixed because it should fix some of the complaints(the screen going black). 
However the issue is more complex and would require quite a large refactoring to improve things further which is not going to be done any time soon so I would prefer to not have the issue lingering.
* Fixes #12950 
Tried exporting and importing collections and ran the tests.

Refactor code and improve UX around exporting and importing collections

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt

for `startMultimediaFieldEditor`
Kotlin Cleanup - parameter should not have been nullable
Split out from a review comment on:
* https://github.com/ankidroid/Anki-Android/pull/16673/
* make param non-null
Compile-only change. If it compiles, it works

refactor(note-editor): improve nullability

---

.github/workflows/conflict.yaml

Was preparing to merge #16685 but then I saw that it had conflicts although it didn't had the expected label. Looking though the workflow's logs it seemed the workflow didn't consider all opened pull requests as it was relying on the default page value(which is 30) when fetching the open pull requests. So the workflow checked just the oldest 30 opened pull requests.
I increased the per page value to 100 so the workflow now fetches the oldest 100 opened pull requests.
See [documentation for api used](https://octokit.github.io/rest.js/v20#pulls-list).

Change conflicts workflow to allow more PRs to be checked

---

AnkiDroid/src/main/java/com/ichi2/anki/preferences/ReviewerOptionsFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/HideSystemBars.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt
AnkiDroid/src/main/res/layout/reviewer2.xml
AnkiDroid/src/main/res/values/10-preferences.xml
AnkiDroid/src/main/res/values/constants.xml
AnkiDroid/src/main/res/values/preferences.xml
AnkiDroid/src/main/res/xml/preferences_dev_options.xml
AnkiDroid/src/main/res/xml/preferences_reviewer.xml

In the commits
Emulator 34 and in my phone (Galaxy S23, Android 14):
<details>
<summary>Hide all bars + ignore cutout</summary>
</details>
<details>
<summary>Hide status bar + ignore cutout</summary>
</details>
<details>
<summary>Hide status bar </summary>
</details>
<details>
<summary>Hide navigation bar</summary>
</details>
<details>
<summary>Hide answer buttons</summary>
</details>
https://developer.android.com/develop/ui/views/layout/immersive
https://developer.android.com/develop/ui/views/layout/edge-to-edge#cutout-insets

feat(new reviewer): 'Hide system bars', 'Ignore display cutout' and 'Hide answer buttons'

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Notetypes.kt

First, I wanted to replace
`isEmpty` by `containsNoCard`. It seems interesting to note that this may still contains non-default note-type and decks, and still consider the collection empty.
This makes me look at Pairs, and found that, often, destructing the Pair seems more readable to me than using `.first` and `.second`. Especially when it eiher allows to have a single non-null assertion, or allows to have name value instead.

Small cleaning of codes

---

AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
AnkiDroid/src/test/java/com/ichi2/anki/instanteditor/InstantEditorViewModelTest.kt

This PR handles the issue that arises when there is a hyphen when the words i.e. `Hello-World`. 
In this updated pattern allows for matching words that include punctuation.
Tested on Oneplus Nord CE

[GSoC'24] Refactor: cloze builder pattern for words

---

AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/EditorChips.kt
AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
AnkiDroid/src/main/res/values/03-dialogs.xml

This PR further improvise the instant editor by allowing user to manually edit the cloze number by long pressing the cloze number button in the dialog 
Tested on OnePlus Nord CE:
https://github.com/user-attachments/assets/62f532cf-8fd6-42ba-a665-26b0201c128d

[GSoC'24] Enhancement: add long press listener on cloze button

---

AnkiDroid/build.gradle
build.gradle.kts
gradle/libs.versions.toml
settings.gradle.kts

As discussed in Discord, this PR removes the amazon publishing plugin.
The plugin hasn't been update for quite a long time , it doesn't curently work for publising and it also breaks the build.

Remove "app.brant.amazonappstorepublisher" plugin

---

lint-release.xml

The `MissingDefaultResource` lint should only be checked on `/values`
Added in 0f795cea363ace67bd55ec56775c5beae73c7c9e
`iw` = Hebrew
Hebrew was added to the app in a nonstandard manner:
* https://github.com/ankidroid/Anki-Android/pull/16316
* https://github.com/ankidroid/Anki-Android/issues/9451
But the results were not added to be ignored in our lint checks
* Unblocks https://github.com/ankidroid/Anki-Android/pull/16738

fix: "MissingDefaultResource" lint: `iw`

---

AnkiDroid/src/main/java/com/ichi2/anki/scheduling/SetDueDateDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/SchedulerService.kt
AnkiDroid/src/main/res/values/03-dialogs.xml

This pull request fixes the snackbar message in AnkiDroid when setting a card's due date. The current message says "1 card rescheduled," which is incorrect. The update changes it to "Set due date of 1 card" to accurately reflect the action taken by the user.
* Fixes #16732 

Fix: update set due date card snackbar

---

AnkiDroid/src/main/AndroidManifest.xml
AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaBottomSheet.kt
AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaUtils.kt
AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaViewModel.kt
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
AnkiDroid/src/main/res/drawable/ic_add_photo.xml
AnkiDroid/src/main/res/drawable/ic_crop.xml
AnkiDroid/src/main/res/drawable/ic_restart.xml
AnkiDroid/src/main/res/drawable/ic_rounded_draw.xml
AnkiDroid/src/main/res/layout/activity_multimedia.xml
AnkiDroid/src/main/res/layout/bottomsheet_multimedia.xml
AnkiDroid/src/main/res/layout/fragment_multimedia_image.xml
AnkiDroid/src/main/res/menu/multimedia_menu.xml
AnkiDroid/src/main/res/values/16-multimedia-editor.xml
AnkiDroid/src/main/res/values/constants.xml
AnkiDroid/src/main/res/values/preferences.xml
AnkiDroid/src/main/res/xml/preferences_dev_options.xml
AnkiDroid/src/test/java/com/ichi2/testutils/ActivityList.kt

This PR sets the new multimedia UI as developer option and handles the image options - Gallery and Camera
* Partially #13064
Tested on Oneplus Nord CE

[GSoC'24] New Multimedia UI

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt

8e0b537b1d9fe464a82dad68e8bc744c1cbced4c introduced a call to `updateMenuState()` at the loadDeckCounts job to update the undo label state when the deck is reloaded.
Following the method name, the whole menu is updated instead of only the undo label, which includes checking if there are changes to sync remotely, and that takes time, so it shouldn't be done if not necessary.
* Fixes #16693
* Fixes #16768
Update only undo when decks are changed
With the same steps of #16390 in the emulator with API 34

fix: `Processing...` popup in app startup

---

AnkiDroid/src/main/AndroidManifest.xml
AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/DevOptionsFragment.kt
AnkiDroid/src/main/res/values/constants.xml
AnkiDroid/src/main/res/values/preferences.xml
AnkiDroid/src/main/res/xml/preferences_dev_options.xml

This PR lift off instant editor from dev settings and set it for public use
Remove Instant editor from dev setting and enable the intent filters and set exported to true
Tested locally/ Oneplus Nord ce:

[GSoC'24] Feature: enable instant editor for public use

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/AudioField.kt
AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt
AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicMediaClipFieldController.kt
AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/IField.kt
AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/ImageField.kt
AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/TextField.kt
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
AnkiDroid/src/main/java/com/ichi2/audio/AudioRecordingController.kt
AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldControllerTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/fields/MediaClipTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.kt

This PR introduces a refactor to consolidate the media paths into a single variable `mediaPath` for better code maintainability and clarity.
Realme 9 ( Physical Device )

[GSoC'24] Refactor: Consolidate media paths into a single variable

---

AnkiDroid/src/main/res/layout/bottomsheet_multimedia.xml
AnkiDroid/src/main/res/layout/image_occlusion_options_layout.xml

Make the following "Gallery" labels translatable like other labels
- the "Gallery" option label in the menu of "Select image" in "Image Occlusion" note type
- the "Gallery" option label in the menu of multimedia file attachment in the note editor
**Samples** (Traditional Chinese)
N/A
Use the existing "Gallery" string which is translatable from Crowdin
Tested in physical device (Android 11)

Make newer "Gallery" labels translatable from Crowdin

---

AnkiDroid/src/main/java/com/ichi2/widget/AddNoteWidget.kt
AnkiDroid/src/main/java/com/ichi2/widget/AnalyticsWidgetProvider.kt
AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt
AnkiDroid/src/test/java/com/ichi2/anki/widget/AnalyticalWidgetProviderTest.kt

Adding Up Analytical widget provider class for Widgets in AnkiDroid .
[[GSoC'24] Implementation of Deck Picker Widget . #16450 ](https://github.com/ankidroid/Anki-Android/pull/16450)
Preview of affected UI areas after code changes [Functioning as Expected ]
https://github.com/user-attachments/assets/88e038c5-d52d-4ffb-a0f6-cd943dd99d6f

[GSoC'24] Introducing AnalyticsWidgetProvider as ancestor of all widget classes.

---

AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
AnkiDroid/src/test/java/com/ichi2/anki/instanteditor/InstantEditorViewModelTest.kt

Cloze number is reset to 1 or the current cloze number is max of the close number list
* Fixes #16778
Oneplus nord ce

[GSoC'24] Fix: cloze number incorrect on undo

---

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt

Implement keyboard shortcuts to enhance the user experience by providing quick access to commonly used functionalities within the application. This will improve the overall usability, especially for power users who prefer using the keyboard over the mouse.
The shortcuts are implemented by adding event listeners for keypress events and mapping them to the respective functions. The approach ensures that the shortcuts are intuitive and do not conflict with existing shortcuts.
HP Chromebook

[GSoC'24] CardTemplateEditor: Implementation of Keyboard Shortcuts

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/OnContextAndLongClickListener.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsArrayAdapter.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt

This PR introduces functionality to support right-click actions wherever long click listeners are implemented in the application. This enhancement aims to improve user experience by providing additional interaction capabilities on devices that support right-click actions.
```kotlin
yourView.setOnContextClickListener {
showContextMenu()
true
}
``` 
HP Chromebook

[GSoC'24] Add Right-Click Support to Long Click Listeners

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.kt
AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerConfirmDeleteDeckDialog.kt
AnkiDroid/src/main/res/values/03-dialogs.xml

Implement keyboard shortcuts to enhance the user experience by providing quick access to commonly used functionalities within the application. This will improve the overall usability, especially for power users who prefer using the keyboard over the mouse.
The shortcuts are implemented by adding event listeners for keypress events and mapping them to the respective functions. The approach ensures that the shortcuts are intuitive and do not conflict with existing shortcuts.
| Action | Shortcut in AnkiDroid | Shortcut in Anki |
|--------|--------|--------|
| Open Statistics | T | T |
| Create Deck | D | **n/a**  |
| Check Database | C | C |
| Create Filtered Deck | F | F |
| Deck deck with confirmation  | Del | **n/a** | 
| Delete deck without confirmation | Shift+Del | **n/a**  |
| Rename …

[GSoC'24] DeckPicker: Implementation of Keyboard Shortcuts

---

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/multimedia/audio/AudioRecordingController.kt
AnkiDroid/src/main/java/com/ichi2/anki/multimedia/audio/AudioTimer.kt
AnkiDroid/src/main/java/com/ichi2/anki/multimedia/audio/AudioWaveform.kt
AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
AnkiDroid/src/main/res/layout/activity_audio_recording.xml
AnkiDroid/src/main/res/layout/activity_audio_recording_reviewer.xml
AnkiDroid/src/test/java/com/ichi2/audio/AudioRecordingControllerTest.kt

Refactor the audio package to be inside the multimedia package
Locally, build successful 

[GSoC'24] Refactor: move audio package to multimedia package

---

AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
AnkiDroid/src/test/java/com/ichi2/anki/instanteditor/InstantEditorViewModelParameterizedTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/instanteditor/InstantEditorViewModelTest.kt

The previous regex pattern for building cloze text ignores all punctuations except for underscores and dashes. As a result, for some texts like `Student's` or `Note(s)`, it only considered the text up to the first punctuation mark.
* Fixes #16784
I changed the regex pattern to consider apostrophe and parentheses characters as part of the main cloze text.
To ensure the new code works correctly, I wrote some unit tests. Additionally, I provided a screenshot demonstrating these changes.

Change the instance cloze builder Regex pattern

---

AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt

pulled from 
* https://github.com/ankidroid/Anki-Android/pull/16714#issuecomment-2262325965

refactor: Hungarian Notation rename

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
AnkiDroid/src/main/java/com/ichi2/anki/notetype/AddNewNotesType.kt
AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Notetypes.kt
AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt
AnkiDroid/src/main/java/com/ichi2/libanki/backend/BackendUtils.kt
AnkiDroid/src/main/java/com/ichi2/libanki/sched/Counts.kt
AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/CardTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.kt
AnkiDroid/src/test/java/com/ichi2/testutils/TestClass.kt
AnkiDroid/src/test/java/com/ichi2/utils/NoteTypeTest.kt

It was agreed we use camelCase consistently and that `snake_case` was to be applied via `@LibAnkiAlias`
* Fixes #11582
* search for `fun.*_` inside `libAnki`
* rename
* A few methods would have conflicted. Either inline them if they're aliases, or handle them in a second commit
CI-only: refactor

refactor:  idiomatic capitalization in libAnki

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/res/values/07-cardbrowser.xml

This PR is a part of #16795 
* https://github.com/ankidroid/Anki-Android/pull/16795
HP Chromebook

[GSoC'24] CardBrowser: Shortcut E

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiFragment.kt

This PR fixes the status bar for ground color issue
* Fixes #16770 
Status Bar transparent API is called just like note editor does
Google Emulator

fix: deckpicker to use transparent status bar

---

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerViewModel.kt
AnkiDroid/src/main/res/layout-xlarge/card_template_editor.xml
AnkiDroid/src/main/res/layout/card_template_editor.xml
AnkiDroid/src/main/res/layout/card_template_editor_item.xml
AnkiDroid/src/main/res/layout/template_previewer.xml
AnkiDroid/src/main/res/values/attrs.xml
AnkiDroid/src/main/res/values/styles.xml
AnkiDroid/src/main/res/values/theme_black.xml
AnkiDroid/src/main/res/values/theme_dark.xml
AnkiDroid/src/main/res/values/theme_light.xml
AnkiDroid/src/main/res/values/theme_plain.xml

This feature aims to enhance the CardTemplateEditor by adding a TemplatePreviewerFragment. This will allow users to preview card templates in real-time, improving the usability and efficiency of template editing.
Steps
1. Attach fragment to activity
2. Load fragment on preview button, performing actions and tab change
3. Remove back button when fragmented
4. Move menu contents to fragment
5. Customize UI
Emulator
https://github.com/ankidroid/Anki-Android/assets/65113071/8a410f3a-4da5-420e-ab6f-1dd5c459c541

[GSoC'24] Add TemplatePreviewerFragment to CardTemplateEditor

---

AnkiDroid/build.gradle
AnkiDroid/src/main/AndroidManifest.xml
AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.kt
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
AnkiDroid/src/main/java/com/ichi2/compat/CompatV23.kt
AnkiDroid/src/main/java/com/ichi2/compat/CompatV24.kt
AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt
AnkiDroid/src/main/res/values/02-strings.xml
AnkiDroid/src/test/java/com/ichi2/utils/ClipboardUtilTest.kt
gradle/libs.versions.toml
testlib/src/main/AndroidManifest.xml

This PR enhances the existing functionality of dropping media files in the NoteEditor (FixedEditText). Previously, only photos could be dropped. With this enhancement, users can now also drop video and audio files into the FixedEditText.
To implement this feature, I utilized the `DropHelper` class instead of the traditional drag-and-drop mechanisms.
**Why DropHelper?**
Simplified Implementation: DropHelper provides a straightforward and high-level API for managing drop actions, reducing the complexity of handling multiple types of media.
HP Chromebook
[Screen recording 2024-07-17 10.30.17 PM.webm](https://github.com/user-attachments/assets/1695385d-1f65-427f-8c4c-7cc531ec0ec4)
https://medium.com/androiddevelopers/simplifying-drag-and-drop-3713d6ef526e …

[GSoC'24] Enhancement of Media Drop Feature in NoteEditor

---

tools/discord/format-for-discord.sh
tools/discord/macos-clipboard-to-discord.sh

Scratching my own itch with this one
**Result:**
Links to the repo are unpleasant to see:
* Link previews are too large & distracting
* Links without a preview give no context
I want Discord output which both gives context, and is compact
`macos-clipboard-to-discord` converts an issue link: `https://github.com/ankidroid/Anki-Android/pull/16804`
into:
* A link with text: `#16804: refactor/docs: `libs.versions.toml` changelogs/renames`
* Without a preview
* Redirecting to the correct PR
`./format-for-discord` performs this formatting: accepting a PR/Issue number: 16804 and outputting the above to stdout

feat(tool): format issue/PR links in Discord

---

AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/SettingsFragment.kt
AnkiDroid/src/main/java/com/ichi2/preferences/ListPreferenceTrait.kt
AnkiDroid/src/main/java/com/ichi2/preferences/PreferenceUtil.kt

`onDisplayPreferenceDialog`: If a call to super is requested, `null` may be returned In this case, `super` would be called
This is useful if you would optionally want to inherit from a class (say `EditTextPreference`), but also allow conditionally return a different fragment
* Prep for #3114 : 
* We'll want a `ListPreference` if the user is on `play`
* An `EditTextPreference` if the user is on `full`
* Preferences screens don't expect two preferences for the same key
* So we need one preference which will change implementations  
----
One refactoring to `CollectonManager`
----
A new trait which allows a list preference to **optionally** be displayed when a preference is clicked

chore: cleanups to allow List-based input of collection path 

---

AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt
AnkiDroid/src/main/res/values/10-preferences.xml
AnkiDroid/src/main/res/values/preferences.xml
AnkiDroid/src/main/res/xml/preferences_reviewer.xml

It is a frequently requested feature, helps a big number of users that only use two buttons, and it is quite simple to implement.
Apparently, Damien don't want to implement it in Anki for some kind of reason, but it takes a lot of less time to implement it than to read the more than 100 comments in the corresponding page at the forums to still reach to the same conclusion.
About the PR, if any string related changes are required, please push them or do them in another PR, because I don't have time to bikeshedding and won't do them.
Emulator 35:
<details><summary>Screenshot</summary>
</details>

feat: Hide 'Hard' and 'Easy' buttons setting in the new reviewer

---

AnkiDroid/src/main/java/com/ichi2/anki/multimedia/audio/AudioRecordingController.kt

Fixes the audio player in wrong state when trying to initialise from the gestures
* Fixes #16873
Google emulator API 35

fix: IllegalStateException in audio player

---

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
AnkiDroid/src/main/res/values/01-core.xml
AnkiDroid/src/main/res/values/02-strings.xml
AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt

To show a dialog when the user tries to delete a card type that would orphan note.
* Fixes #16789 
The issue fix involves creating a AlertDialog that is shown when the user tries to delete a card type that would  orphan note.
Device: Realme 10 pro+
Model: RMX3686
API Level: 34-ext12

Fix: Tell the users why card type deletion fails when this would orphan note.

---

AnkiDroid/src/main/res/layout/instant_editor_dialog.xml
AnkiDroid/src/main/res/values/03-dialogs.xml

Added tooltip text for buttons in instant note editor
* Fixes #16893
Google emualtor API35

chore: add tooltip text in instant note editor buttons

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorIntentTest.kt

this test is marked flaky so it won't ever run in CI but it was failing locally for me every time as it was comparing the first char of the string it pulled to a string, instead of string vs string
Going to do the very rare / not normally recommended YOLO-merge on this because it meets some strict criteria:
- it changes test code only
- it is obviously correct on visual inspection
- it is not code that runs in CI ever so there is nothing CI could tell us that would inform whether to merge or not
- it definitely broke locally every time and definitely works afterwards
failure message wsa "expected 'sample text' / actual 's'" which is kind of obvious...

test: compare whole string not first char in NoteEditor test

---

AnkiDroid/src/main/aidl/android/content/pm/IPackageStatsObserver.aidl

I dislike seeing this build-time deprecation warning every build, and investigated if we could remove this. We can't but I was able to see when, so I wrote it out in order to not forget and spend the time researching again
The comment I left should show up in standard searches for removable code based on VERSION_CODES / minSdk when we bump versions
This was added by David so if he can remember the code enough to say the comment is good, should be good...

docs: add comment on when deprecated code may be removed

---

AnkiDroid/src/main/AndroidManifest.xml
AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt
AnkiDroid/src/main/res/values/03-dialogs.xml

We use camera as feature in the manifest file and not as `<uses-permission android:name="android.permission.CAMERA" />` so the current check always returns false and the user is unable to open the camera options, the PR fixes that
We don't have camera permission in the manifest file, We are using it as a feature
The current code won't allow the camera to be launched since it is not having the permission neither have we declared it.
It was removed earlier by Brayan
* #14162
the check was not their originally in the new code but was introduced in
https://github.com/ankidroid/Anki-Android/pull/16798/commits/cd037564b47c9feb55c3f5bcbfd1117319e126ac
Google emualtor API 24 & API35

fix: unnecessary camera permission check

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt

* Fixes #16903
I used the new MenuProvider Android class to build it correctly
In an Android 15 emulator by trying to reproduce the issue
https://developer.android.com/reference/androidx/core/view/MenuProvider

fix: check sign in note editor

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt

I discover that each time an action occur in the reviewer, the deck picker is updated. This is uselessly costly.
I tested and when going back to the deck picker, I still get the up to date data immediately.

NF: Don't update the deck list when the deck picker is hidden

---

AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt

I had some trouble integrating the AnkiDroid API in my app, mainly because some confusion on my part with the `CONTENT_URI` of `ReviewInfo` which `deckID` and `limit` aren't query parameters, not following the pattern of the others availables URIs. 
So I created the another URI to use the deck id as an appended path and passing limit as an optional query parameter, e.g. `/schedule/123456789?limit=5` leaving the existing one to not break any app that already uses it.
Also I found out that the `limit` parameter doesn't work in the existing schedule URI, returning the same card data N times and fixed this in this PR.
* Fixes #16772
Creation of new URI in `CardContentProvider` and creation of `getQueuedCards()` function to solve the limit parameter issue.
Querying the …

fix: limit parameter of schedule URI returns the same data

---

gradle/libs.versions.toml

Agreed that the following are released in lockstep, so should be combined:
https://discord.com/channels/368267295601983490/701922522836369498/1276149849430954024
* [#16926: chore(deps): bump kotlinTest from 2.0.10 to 2.0.20](<https://github.com/ankidroid/Anki-Android/issues/16926>)
* [#16927: chore(deps): bump kotlin from 2.0.10 to 2.0.20](<https://github.com/ankidroid/Anki-Android/issues/16927>)
* [#16928: chore(deps): bump org.jetbrains.kotlin:kotlin-reflect from 2.0.10 to 2.0.20](<https://github.com/ankidroid/Anki-Android/issues/16928>)
----
* https://github.com/JetBrains/kotlin/releases/

build(deps): document & consolidate 'kotlin' dependency

---

AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt

I was very surprised to see we used dynamic and not static one. I tried to transform them into static shortcut, which seems cleaner. And realized that we can't for a very absurd technical reason.
So I document it here, hoping nobody else will lose time on it.

Document the reason for dynamic shortcuts

---

AnkiDroid/src/main/res/values/10-preferences.xml
AnkiDroid/src/main/res/xml/preferences_appearance.xml

Update the description of the "Show top bar" setting to include a mention of the answer timer. This change clarifies that the answer timer will be displayed when the top bar is enabled, addressing user confusion about the functionality.
* Fixes #16698
Modified the string resource for the "Show top bar" setting to mention the answer timer explicitly.
Realme 6 and Emulator

Update top bar setting description

---

AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt
AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.kt
AnkiDroid/src/test/java/com/ichi2/testutils/TestClass.kt

For potential use in the DeckPicker widget GSoC project
Sourced from
https://github.com/ankitects/anki/blob/a179da382759b9c7f8265faf37efdcbb47d8ee08/pylib/anki/decks.py#L225
```python
def card_count(
self, dids: DeckId | Iterable[DeckId], include_subdecks: bool
) -> Any:
if isinstance(dids, int):
dids = {dids}
else:
dids = set(dids)
if include_subdecks:
dids.update([child[1] for did in dids for child in self.children(did)])
str_ids = ids2str(dids)
count = self.col.db.scalar(
f"select count() from cards where did in {str_ids} or odid in {str_ids}"
)
return count
```
Unit tested 
I took a little more time to ensure the `odid` case was handled

feat(libAnki): implement decks.cardCount()

---

AnkiDroid/build.gradle

Let's ship 2.19!
Normally I just do this on main and push it, but I thought it would be instructive to have it in the PR history so anyone could use it as reference for how to do it.
Note that we set the version code and string initially to zero / zeros, the release script will increment by one to make it 2.19beta1 / version code with beta 1
Next step after this is merged: anyone can hit the publish button - it's not a formal release so it doesn't require the release notes up to date yet or anything. Beta releases work similar to alpha releases in that sense.

release: switch 2.19 to beta version series, beta play store track

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
AnkiDroid/src/main/java/com/ichi2/compat/CompatV23.kt
AnkiDroid/src/main/java/com/ichi2/compat/CompatV24.kt
AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt
AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt

This PR enhances functionality of dropping files in the DeckPicker. With this enhancement, users can now drop files and import directly.
HP CHROMEBOOK
https://github.com/user-attachments/assets/be765b56-d3e4-4dcc-8077-f0ce4f98d29b

[GSoC'24] : Enhancement of Files Drop Feature in DeckPicker

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/SingleFragmentActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/pages/CsvImporter.kt
AnkiDroid/src/main/java/com/ichi2/anki/pages/ImageOcclusion.kt
AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt

SingleFragmentActivity called setTransparentStatusBar() which worked great for the page fragments that came from the backend. However it didn't worked so well when used with other fragments, most notable the NoteEditor which was recently transformed into a fragment. To fix this, I removed the call to setTransparentStatusBar() in the activity and manually added it to the fragments that should have it. I also reverted the previous attempt at fixing this.
See images with the affected screens, before & after:
_NoteEditor:_
_Statistics:_
_Preview:_
_Image occlusion:_
_Csv import:_
_Card info:_
* Fixes #16770
Verified the UI of the affected screens.

Fix status bar foreground colors

---

gradle/libs.versions.toml

I don't like the name 'triplet' instead of 'tripleT[PlayPublisher]]', but that's a bikeshed for another day

docs: dependencies - changelogs (Triple-T Publisher)

---

AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt
AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt
AnkiDroid/src/main/res/layout/studyoptions_fragment.xml
AnkiDroid/src/main/res/values/01-core.xml
AnkiDroid/src/main/res/values/attrs.xml
AnkiDroid/src/main/res/values/colors.xml
AnkiDroid/src/main/res/values/theme_black.xml
AnkiDroid/src/main/res/values/theme_dark.xml
AnkiDroid/src/main/res/values/theme_light.xml

While working towards fixing #14793 I got sidetracked and implemented this so StudyOptionsFragment follows the desktop ui + it shows the bury counts(which weren't being shown) if the related deck options are enabled.
Some notes on the changes:
- the previous code showed the total cards count in the deck. As the desktop screen didn't show this I removed it. Can be brought back with ease if requested using the cardCount() method which was just added to out codebase.
- the previous code showed the total new cards count in the deck. As the desktop screen didn't show this I removed it. This can also be brought back for normal decks, however the related backend method doesn't work for filtered decks so we would need to either don't show this count for filtered decks or use the old code(which …

Implement the desktop UI in StudyOptionsFragment

---

AnkiDroid/src/main/res/values/preferences.xml
AnkiDroid/src/main/res/xml/preferences_dev_options.xml

Common users are using the "New reviewer" **developer option** as it's something aimed at them.
As the name say, it's a **developer option** aimed to devs so they can test the feature, but people misunderstand that and are creating issues in GitHub
Add a written warning explaining that
If this doesn't work and people insist on creating issues in GitHub, next step will be to restrict the WIP features to DEBUG builds.
- X ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)

Add warning to WIP dev options

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt

During creation of new deck after entering the name of deck pressing enter on the physical keyboard was changing focus to the cancel button 
* #16872
adding a enter key listener along with IMEACTION done button listener 
This has been tested on API level 34 and as well as physical device samsung galaxy F23
- [*] You have a descriptive commit message with a short title (first line, max 50 chars).
- [*] You have …

pressing enter on physical keyboard change creates a new deck

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt

This PR fixes the linked issues + one more(edit note screen is shown on every E event) by properly following the contract of the onKeyUp method of returning true only if the event is handled there and using a modifier to not trigger on simple key events/checking the state of the search box to see if it's regular input.
In CardBrowser I introduced two new shortcuts by using the modifier that was not used in that when selection clause:
old: _T -> Show filter by tags dialog_ vs. new: _Ctrl+T: Show filter by tags dialog_
Feel free to propose other shortcuts.
@SanjaySargam I've made this PR to help seeing that you still have work on the Gsoc front.
* Fixes  #16955
* Fixes #16984
* Fixes #16983
I don't see the previous behavior.

Fix incorrect key handling in some screens

---

AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt

The issue addressed in this PR involves an incorrect message being displayed when media sync is canceled. Instead of showing "Media sync aborted," the system often shows "Media sync complete." This issue was observed when tapping "Cancel" in the "Media Sync Log" dialog box.
* Fixes #16631 

Fix: Ensure "Media Sync Aborted" Message Displays Correctly After Canceling Media Sync

---

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
AnkiDroid/src/main/res/layout-xlarge/card_template_editor.xml
AnkiDroid/src/main/res/layout/card_template_editor.xml
AnkiDroid/src/main/res/layout/card_template_editor_top.xml

this was very hard to do because CardTemplateEditor is tightly coupled with CardTemplateFragment, so most changes break something even if not related
* Fixes #16992
The menu shows up in a tablet emulator

fix menu in template editor

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.kt
AnkiDroid/src/main/res/menu/card_browser.xml

* Fixes #12444
I implemented the create filtered deck option feature
[filtered.webm](https://github.com/user-attachments/assets/3e68ae3d-beea-4511-8b4a-b1ec0f4ee473)

add filtered deck option to browser

---

AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
AnkiDroid/src/main/java/com/ichi2/libanki/ChangeManager.kt
AnkiDroid/src/test/java/com/ichi2/libanki/ChangeManagerTest.kt

In this case, I really don't think it's realistic to expect an OpChange from the backend. The backend already sends informations that are relevant for the sync process. Given that "sync" does not uses the processes uses for undoable change (indeed, it should not be undoable), no OpChange is generated.
It seems reasonable in this place at least to directly notify the observers.
Given that the observers expect an OpChanges, I create one, and simply assume everything may be changed. This seems reasonable in case of sync, and it's sufficiently rare that the cost won't be prohibitive anyway.
* Fixes #16943
* Fixes #16942

Notify the UI that a sync was done

---

.github/ISSUE_TEMPLATE/bug_report_form.yml

A user only searched open issues
We also want them to check the closed issues
See comment:
* https://github.com/ankidroid/Anki-Android/issues/17040#issuecomment-2336790319
Sample link: https://github.com/ankidroid/Anki-Android/issues?q=is%3Aissue

docs(bug-report): improve link to issues

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.kt

Filtered decks did not appear in the browser
* Fixes filtered decks not appearing in the card browser deck selection dialog
Respect the `showFilteredDecks` parameter that was removed in 7a65160e0e23e20080091a30abdd4c05fc610e06
In an Android 15 emulator

fix filtered decks not appearing in browser deck selection dialog

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/res/values/01-core.xml

https://forums.ankiweb.net/t/remove-total-number-of-cards-from-main-menu/48972
> When no cards are due, AnkiDroid shows the total number of cards in the main menu.
>
> IMO, this doesn’t solve any purpose and is just a distraction. So, I suggest removing it.
* Fixes this request in the forums https://forums.ankiweb.net/t/remove-total-number-of-cards-from-main-menu/48972
remove the subtitle if there aren't any cards due
In an Android 14 emulator by finishing all cards so there aren't any cards due

remove all cards count  subtitle

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt

The sticky fields don't force the user to confirm when they tap the back button.
Also some slight cleaning.
I refrained from doing bigger cleaning because I know this code will go. But the nullability was trivial to check. And this bug was honestly frustrating me, and since it's quick to fix, I preferred not to wait for the new editor
Fixed: #16949

Note editor back button request confirmation only in case of change

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/impl/MultimediaEditableNote.kt
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt

The NPE was caused due to the `getCurrentMultimediaEditableNote` method being called when showing the bottom sheet but to test the bottom sheet we dont need that, so separating the logic to show the media sheet and then testing it.
* Fixes #16886
Locally tested, test successful 

fix: NoteEditor flaky test

---

AnkiDroid/src/main/res/drawable/ic_warning.xml
AnkiDroid/src/main/res/values/styles.xml
AnkiDroid/src/main/res/values/theme_black.xml
AnkiDroid/src/main/res/values/theme_dark.xml
AnkiDroid/src/main/res/values/theme_light.xml

The dialogs didn't look much like material dialogs, so I applied the overlay theme to get animations, round corners and material style
* Fixes #15174
I used Material Dialog Theme Overlay and did a fix with the text color
I was going to remove AlertDialogStyle as well but someone else is doing something with it
[dialog.webm](https://github.com/ankidroid/Anki-Android/assets/154519856/8a7fb87f-19a2-4ce2-9583-7f660049033e)
[light.webm](https://github.com/ankidroid/Anki-Android/assets/154519856/37b77b5a-bfe8-489d-8dd9-374870e752df)
[API 25.webm](https://github.com/ankidroid/Anki-Android/assets/154519856/4a83c01c-fae9-4cf1-b43b-bd507788bab8)

Improve alert dialog style

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/widget/deckpicker/DeckPickerWidget.kt

* Fixes #16956
This fixes the issue where the error message "Not at top of the queue" appears when a review is in progress and the user opens another deck through the deck picker widget or a deck shortcut. The message appears when attempting to review a card after using the back button on the first deck which takes the user to a deck 'underneath' it. There should not be multiple review activity instances and so restricting there to be only a single review instance on the activity stack removes the possiblity of the "Not at top of the queue" error message occuring.
[Intent.FLAG_ACTIVITY_CLEAR_TOP docs:](https://developer.android.com/reference/android/content/Intent#FLAG_ACTIVITY_CLEAR_TOP)
> If set, and the activity being launched is already running in the current task, then instead of …

fix: Single review activity instance

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
AnkiDroid/src/main/res/layout/item_stats_deck.xml
AnkiDroid/src/main/res/layout/statistics.xml

Reintroduce Deck Selector to the Statistics Page
* Fixes #15197
Use M3 button to allow user to change deck, not using the spinner here as the deck name is already displayed in the text field 
Google emulator  API 34
Tested the orientation change too
[test-stats.webm](https://github.com/ankidroid/Anki-Android/assets/48384865/886da4fc-b279-4ac0-9ac7-3e1ea18b8cea)

Feature: Allow changing deck name in statistics screen

---

AnkiDroid/src/main/java/com/ichi2/widget/cardanalysis/CardAnalysisWidgetConfig.kt
AnkiDroid/src/main/java/com/ichi2/widget/deckpicker/DeckPickerWidgetConfig.kt
AnkiDroid/src/test/java/com/ichi2/anki/widget/cardanalysis/CardAnalysisWidgetConfigTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/widget/deckpicker/DeckPickerWidgetConfigTest.kt
AnkiDroid/src/test/java/com/ichi2/testutils/TestClass.kt

* Fixes #17010
This may not completely fix the issue, there is still an 'uncompleted' task run inside `lifecycleScope`.
This may or may not be fixed by calling `finish()` on the activity (step 1)
EDIT: I ran 15x3 unit tests and none failed. marking the above issue as fixed
1. Fix activity cleanup - didn't happen in `DeckPickerWidgetConfigTest`
2. Add logs
3. Wait for `updateViewWithSavedPreferences` properly, make it `suspend`
4. ensure the collection is set up before performing tests
* `finish()` is no longer called 
Unit tested, ran the widgets in an emulator and they continued to function

partial fix for flaky test: `testLoadSavedPreferences`

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/SyncActionProvider.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/LocaleSelectionDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt
AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt
AnkiDroid/src/main/java/com/ichi2/ui/AccessibleSearchView.kt
AnkiDroid/src/main/java/com/ichi2/ui/CardBrowserSearchView.kt
AnkiDroid/src/main/java/com/ichi2/ui/RtlCompliantActionProvider.kt
AnkiDroid/src/main/res/menu/deck_picker.xml
AnkiDroid/src/main/res/menu/deck_picker_dialog_menu.xml
AnkiDroid/src/main/res/menu/download_shared_decks_menu.xml
AnkiDroid/src/main/res/menu/locale_dialog_search_bar.xml
AnkiDroid/src/main/res/menu/search.xml
AnkiDroid/src/main/res/menu/tags_dialog_menu.xml
AnkiDroid/src/main/res/values/07-cardbrowser.xml
AnkiDroid/src/main/res/values/10-preferences.xml

Fixed: #15308
The first commit clean some code, using TooltipCompats when possible, instead of checking the API version in code
The second does some more cleaning.
The third split a string in two strings, because it should not be the same in French, and probably not in other languages too. In English, the noun and the verb "search" are the same. Not in French at least.
The fourth add a "Discard" tooltip on the "x" button near the search view that discard the content of the search field.

Solves a few little issues with tooltip

---

AnkiDroid/src/main/res/layout/dialog_export_options.xml

export option dialog have text overlapping issue and last checkbox is not visible in landscope mode
* Fixes #17060 
make layout scrollview
physical android device

fix: export option dialog have text overlapping issue and last checkbox is not visible in landscope mode

---

AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt

Reducing the amount of warnings given within android studio.
Contributes towards #13282 `[Cleanup]: Fix Android Studio Warnings`
There was a broken reference in one of the comments. The configureSearchBar function had previously been moved from the HeaderFragment class to the Preferences class, but recently it was moved back and the comments describing it had not been updated.
Only comments have been changed so testing does not apply.
I looked back in previous commits to see when that comment came to be, and investigated where the broken reference was meant to be pointing to.

Fix android studio warnings - AdvancedSettingsFragment.kt

---

AnkiDroid/src/main/res/values/01-core.xml

"1 day 2" seems really strange to me. "1 day 2 hours" would be too long for most smartphone. But "1 day 2h" seems reasonable to me
Also, "plural" does not allow for two parameters, and it would have been complex to consider both words if they are singular or plural.
Regarding "1 hour 5" I preferred to not change it. "1 hour 5 min" woud add far too many character. "1 hour 5m" sounds strange. And stating "1 hour 5" is far more standard than "1 day 5".
It seems I was the one who introduced this string in 2020. I have no idea why I had not put the "h" at the time. And I can't easily find the PR to see whether it was discussed at the time

Clarify the reviewer window title

---

AnkiDroid/src/main/res/values/10-preferences.xml

The way the menu looked was wrong. With all options with upper case except for the title.

Upper case to "cards selected by"

---

AnkiDroid/src/main/res/xml/preferences_controls.xml

Match the label for tag control to the actual action (opening "Tags" dialog box, not "Add tag" dialog box)
[Current label]
`Add tag`
[Action]
Opening "Tags" dialog box. It is the same result of selecting "Edit tags" in the menu of Reviewer screen:
N/A
Replace the string with another existing string
Checked in physical device (Android 11):

fix: match tag control label to actual action

---

AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/SoundTagPlayer.kt
AnkiDroid/src/main/java/com/ichi2/anki/multimedia/AudioVideoFragment.kt

Android 15+ apps have audio focus restrictions applied
See: https://developer.android.com/about/versions/15/behavior-changes-15#audio-focus
> Apps that target Android 15 (API level 35) must be the top app or running a
> foreground service in order to request audio focus. If an app attempts to request
> focus when it does not meet one of these requirements, the call returns AUDIOFOCUS_REQUEST_FAILED
It is recommended, if you are using ExoPlayer (which the new AV fragment in #16769 does), to allow the platform to handle audio focus, and this PR also includes a commit to enable that.
The SoundTagPlayer should be refactored to use ExoPlayer in my opinion, now that we have that as a dependency, then audio focus code should be removed from SoundTagPlayer. That is out of scope for this PR though …

Handle Android 15+ audio focus changes / allow platform to handle focus in AV fragment

---

AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt

Previously all 429 errors redirected a user to the login page, even if they were already logged in
Now it shows "Daily limit exceeded, please try again tomorrow"
* Fixes #17135
* Determine the cookies which AnkiWeb uses for login
* Check to see if the user is logged into AnkIWeb
* If they are, skip the code to handle "user is not logged in" rate limits
* Refactors/documentation
* A non-logged in user is still redirected to signup/login
* A logged in user is no longer redirected
* AnkiWeb has two cookies:
*  `ankiweb` (base64 encoded JSON, not quite a JWT)
* `has_auth=1`

fix(deck-download): handle "Daily limit exceeded; please try again tomorrow." correctly

---

AnkiDroid/src/main/res/values/11-arrays.xml

Those two strings appears as actions to which you can associate a gesture or a shortcut.
I must admit that I've no idea what "Abort learning" mean, until I looked at the code.
I hesitated to use "Close the Deck", because, after all, from the user point of view, we were opening a deck. The name "reviewer" is rarely used. But that's already the name used in our documentation and in other settings string, so I decided to keep it.
Admittedly, I'm not a native English speaker, so it's hard for me to know whether a native would understand directly what it means.

Rephrase "Abort learning"

---

AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
AnkiDroid/src/main/res/values/01-core.xml
AnkiDroid/src/main/res/values/02-strings.xml

In French, at least, the preterit differs depending on whether there is 1 or other value. So this need to be `plurals`.
By the way, I'm not clear why this is considered core.

"+n buried" becomes `plurals`

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt

This ensure there is no change in behaviour.
I checked whether we could try to not export the download of decks, but it does not works.
The app does not crash on api 24 on simulator.
There was a slight problem, with variables that could potentially be null. To ensure the type checker agreed with the code, without using `!!`, I had to rewrite some of the logic.
I also ensured that some of the code that was copy/pasted in various activity now entirely belong to AnkiActivity. As a side effect, all activities that used to listen to the "unmount" notification and finished, will now also show a toast when the card gets unmounted. Currently it was only the deck picker.
* Fixes #16713

refactor: mount receivers

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
AnkiDroid/src/main/java/com/ichi2/anki/services/BootService.kt
AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt

* Fixes #17153
Don't use a legacy check
On my S21 (Android 14), logs now show the Boot Service executing
Need more tests

fix(boot-service): execute on later Android versions 

---

AnkiDroid/src/main/java/com/ichi2/anki/preferences/HeaderFragment.kt
AnkiDroid/src/main/res/values/preferences.xml
AnkiDroid/src/main/res/xml/preferences_backup_limits.xml
AnkiDroid/src/test/java/com/ichi2/anki/analytics/PreferencesAnalyticsTest.kt

I didn't make the backups settings searchable when I created them. Added the proper calls for our SearchConfiguration. One of the backups setting that was used purely as a helper text was removed from the search results.
* Fixes #17123
Search settings for the term "backup".

Enable searching for backups related settings

---

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerFragment.kt
AnkiDroid/src/main/java/com/ichi2/utils/BundleUtils.kt

This PR fixes the following bug:
_Have the emulator in an orientation that would result in a multi panel layout in CardTemplateEditor_ -> _Go to Manage notetypes screen_ -> _Click on **Edit cards** option for one of the notetypes_ -> _CardTemplateEditor is opened and a dialog is showing an IllegalStateException + there's a visual glitch(background color) for the previewer on the right part_
The fix consists of passing a background override color when creating the TemplatePreviewerFragment and then having the fragment set the background itself in one of its lifecycle methods were the view is surely available. I didn't add this color to the arguments already passed in as I didn't really consider it a part of the required data.
For consistency I also added a new helper method in BundleUtils …

Fix IllegalStateException being thrown in multipanel CardTemplateEditor

---

AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt

Added missing call to save() to register the change in sort field.
* Fixes #16649
Ran the tests, manually checked the behavior.

Fix notetype field not being used as sort field

---

AnkiDroid/src/main/java/com/ichi2/widget/WidgetAlarm.kt
AnkiDroid/src/main/java/com/ichi2/widget/cardanalysis/CardAnalysisWidget.kt
AnkiDroid/src/main/java/com/ichi2/widget/deckpicker/DeckPickerWidget.kt

* Fixes #17151
* `null` is not handled - needs a new issue for investigation
* Ignore one action
* Fix the action name for one
* Error no longer occurs in logcat
* Note: Difficult to test due to #17152

fix(widgets): Unexpected action received: `ACTION_UPDATE_WIDGET` & `APPWIDGET_UPDATE_OPTIONS`

---

AnkiDroid/src/main/res/layout/locale_selection_dialog.xml

The toolbar background color should not be blue, it should be black in Black/Dark theme
* Fixes #17145 
Fix inconsistent Toolbar background by replacing `colorPrimary` with `appBarColor`

Fix inconsistent Toolbar background color

---

AnkiDroid/src/main/res/layout/item_manage_note_type.xml

Currently, when text is big for accessibility, and text is long, such as French localization, some button overlaps.
This commit correct it by ensuring that text follow the Material Dialog. It stay horizontal normally. But can become vertical when there is not enough horizontal room.
Thanks to @david-allison for the tip of using the material dialog implementation.
I admit I'm not a fan of the result. This is a lot of real estate and will require to scroll potentially a lot.
Also, it's really not clear how to:
* copy a note type (you should tap on the plus symbol)
* edit the list of fiels (tap anywhere on the note type except on the buttons)
So in my opinion, it'd be better to just remove all buttons, and when a user tap on a card, we open a standard menu that allows to do:
* Edit cards
* …

Improve Manage note type with big text

---

AnkiDroid/src/main/res/values/styles.xml
AnkiDroid/src/main/res/values/theme_dark.xml
AnkiDroid/src/main/res/values/theme_light.xml

It was pointed out by @david-allison when the bottom sheet code was merged as non blocker, hence I am resolving it now, this PR makes the nav bar color transparent.
Google emulator API 35:
Resources used: Google M3 [docs](https://github.com/material-components/material-components-android/blob/master/docs/components/BottomSheet.md)

fix: multimedia bottomsheet nav bar color transparency

---

lint-rules/src/main/java/com/ichi2/anki/lint/rules/TranslationTypo.kt
lint-rules/src/main/java/com/ichi2/anki/lint/utils/Crowdin.kt
lint-rules/src/test/java/com/ichi2/anki/lint/rules/TranslationTypoTest.kt
lint-rules/src/test/java/com/ichi2/anki/lint/testutils/LintAssert.kt
lint-rules/src/test/java/com/ichi2/anki/lint/utils/CrowdinLanguageTagTest.kt
tools/localization/src/update.ts

A discussion on https://github.com/ankidroid/Anki-Android/pull/17160 prompted the fact that we can save time by linking directly to Crowdin if errors occur
Sample link: https://crowdin.com/editor/ankidroid/7290/en-af#q=create_subdeck
* obtain a 'file' on Crowdin:
* map from `01-core.xml` to `7290`
* map languages: `zh-rCN` to `zhcn`
* query the string in the file: `#search_string` in the URL fragment works
Manual/unit tests

improvement(lint): 'TranslationTypo' - link to Crowdin 

---

AnkiDroid/src/main/res/layout/browser_options_dialog.xml

This PR ensures the browser options remain accessible and user-friendly when larger text sizes are used by making the layout scrollable. This enhances usability, particularly for users with accessibility needs or custom font settings.
* Fixes #17100
https://github.com/user-attachments/assets/03d681cc-facb-430b-ae24-1298dab7d2a8

Make browser options scrollable for larger text size.

---

AnkiDroid/src/main/java/com/ichi2/anki/multimedia/AudioRecordingFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/multimedia/AudioVideoFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt

This PR completes a `TODO` shows a discard dialog in case there are changes i.e. user selects a media file
Google emulator 

feat: show discard dialog in case multimedia changes

---

AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt

Language name starts with a upper case
The menu provided to the users to select their languages is not yet
perfect. It's hard to know for certain what is the correct way to
display the languages to the users. The function provided by Android
was buggy, and so, a year and a half ago, the language names were
hard-coded in #13275. Except that nobody speaks the 93 languages in
which we have translations available.
On the long term, I hope that 92 translators will provide 92 language
string to use. #17120 should start the process to eventually fix this
error.
On the short term, there is one change that we can make that will
probably be, on average, an improvement. Using upper case for the
first letter of each name.
If I understand correctly Brayan's comment, this change would be
correct for …

Language name starts with a upper case

---

lint-rules/src/main/java/com/ichi2/anki/lint/rules/TranslationTypo.kt

A url was added in ad847571f6612eb428f33c0ae31244fbccbbb6e7
The URL is the most important aspect, but it's inconveniently placed due to the line length
So put it on a newline
```diff
- values-bn/01-core.xml:124: Error: should be 'JavaScript'; https://crowdin.com/editor/ankidroid/7290/en-bn#q=create_subdeck [TranslationTypo from com.ichi2.anki:lint-rules]
+ values-bn/01-core.xml:124: Error: should be 'JavaScript'
+ https://crowdin.com/editor/ankidroid/7290/en-bn#q=create_subdeck [TranslationTypo from com.ichi2.anki:lint-rules]
```

lint: better link to Crowdin

---

AnkiDroid/src/main/java/com/ichi2/widget/cardanalysis/CardAnalysisWidgetConfig.kt
AnkiDroid/src/main/java/com/ichi2/widget/deckpicker/DeckPickerWidgetConfig.kt

The widgets are updated after the UIs are built asynchronously so there's no need for those sendBroadcast calls.
* Fixes #17157
The widgets function as before the removals.

Remove manual broadcasts for DeckPickerWidget and CardAnalysisWidget

---

AnkiDroid/src/main/java/com/ichi2/compat/CompatV24.kt
AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.kt
AnkiDroid/src/main/java/com/ichi2/compat/CompatV29.kt
AnkiDroid/src/main/java/com/ichi2/compat/CompatV31.kt
AnkiDroid/src/main/java/com/ichi2/compat/CompatV34.kt

`class CompatV23 : Compat {`, so the additional inheritance was unnecessary

refactor(compat): remove unnecessary inheritance

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
AnkiDroid/src/main/res/values/03-dialogs.xml

Ensure that pressing the "Enter" key does not create a deck when the deck name already exists, providing a snackbar notification and keeping the dialog open for user correction.
* Fixes #17044 
https://github.com/user-attachments/assets/cc83a20c-6def-4a39-90bd-a185c37b6e27

fix: Prevent deck creation on 'Enter' key when deck name already exists

---

AnkiDroid/src/test/java/com/ichi2/anki/EaseTest.kt
api/src/main/java/com/ichi2/anki/FlashCardsContract.kt
api/src/main/java/com/ichi2/anki/api/Ease.kt

Updates the documentation in `api/src/main/java/com/ichi2/anki/FlashCardsContract.kt` that referenced `AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt` which is not accessible from maven API package. The references were to the 4 `Ease` constants which are now copied into a new enum class in the `api` module.
* Fixes #17021
This change copies the existing 4 Ease constants into the `api` module as a new `Ease` enum class and add a comment in the previously existing `Ease` enum as a reminder that the 2 should stay in sync if either is modified.
I added a unit test to assert that the constants in this new `Ease` enum match the previously existing `Ease` enum class's values.

Create copy of `Ease` constants in `api` module and Update `FlashCardsContract` docs

---

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt

Due to how CardTemplateEditor accesses the collection it seems it doesn't "see" the renames done in ManageNotetypes so when it saves any changes to the template it also saves the last name it "saw". I just called load() on the collection to initialize again the components, especially _Notetypes_. This should be ok, I don't think there are other side effects on calling load().
There's a warning for worker method being called on the main thread but I think it's safe as that method just initializes again several objects, it doesn't seem to do anything heavy.
We should probably move CardTemplateEditor to use CollectionManager.
* Fixes #16630
Ran the tests, manually tried(and failed) to replicate the issue again.

Fix notetype name being reverted when going to CardTemplateEditor

---

AnkiDroid/src/main/java/com/ichi2/widget/deckpicker/DeckPickerWidget.kt
AnkiDroid/src/main/res/layout/widget_card_analysis.xml
AnkiDroid/src/main/res/layout/widget_deck_picker_large.xml
AnkiDroid/src/main/res/values/08-widget.xml

Handle empty state visibility, allowing users to reconfigure the widget by clicking the empty state message in the Deck Picker Widget.
Handled similar to that Card Analysis Widget.
https://github.com/user-attachments/assets/862c78ec-868c-4831-8272-0f5d6a492ffe

Refactored `DeckPickerWidget` to handle empty state visibility.

---

AnkiDroid/src/main/java/com/ichi2/anki/preferences/ControlsSettingsFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/CustomButtonsSettingsFragment.kt

The Set Due Date dialog box is missing its title .
* Fixes #17124 
##Screenshot
settings-> controls->set due date
settings-> appearance->app bar button-> set due date

[BUG]:The Set Due Date dialog box is missing its title 

---

AnkiDroid/src/main/java/com/ichi2/anki/multimedia/audio/AudioRecordingController.kt

There were 2 Android Lint errors and 1 warning in `AudioRecordingController.kt` that are fixed in this PR.
* Addresses #13282
I just picked the first errors after a code inspection and fixed the warning in the file too.
No testing is necessary for the changes to parameter ordering.
I added the exception parameter to the one `Timber.d` call where it was missing. I believe this call will be a no-op for non-debug builds.

Fix Android Studio lint errors in `AudioRecordingController.kt`

---

AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/PermissionItem.kt
AnkiDroid/src/main/res/layout/permission_item.xml

In PermissionActivity, the permission item is not fully touchable, unlike in the settings.
setOnClickListener on root layout.
https://github.com/ankidroid/Anki-Android/assets/119813120/b256bfce-0b05-4121-9ab6-d705c24b5514

Make permission item fully touchable

---

AnkiDroid/src/main/res/layout/dialog_key_picker.xml

Key Labels Not Displaying in Landscape Mode
* Fixes #16935 
use linear layout 
Tested on Android Device 

fix:[BUG] Key Labels Not Displaying in Landscape Mode

---

AnkiDroid/src/main/res/layout/dialog_axis_picker.xml

The layout of the Axis Picker screen is not displaying correctly in landscape mode
* Fixes #17026 
Physical android device
##Screenshot

fix : [Bug] The layout of the Axis Picker screen is not displaying correctly in landscape mode

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/AnkiFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/SingleFragmentActivity.kt
AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
AnkiDroid/src/main/java/com/ichi2/compat/CompatV23.kt
AnkiDroid/src/main/java/com/ichi2/compat/CompatV24.kt
AnkiDroid/src/main/res/values/02-strings.xml
AnkiDroid/src/main/res/values/06-statistics.xml
AnkiDroid/src/main/res/values/07-cardbrowser.xml
AnkiDroid/src/main/res/values/08-widget.xml
AnkiDroid/src/main/res/values/10-preferences.xml

Keyboard shortcuts for Chromebook users are important because they make it easier and faster to use AnkiDroid.  `Alt + K` shortcut will show keyboard shortcuts dialog
HP CHROMEBOOK
[Screen recording 2024-08-16 11.38.57 AM.webm](https://github.com/user-attachments/assets/ba741764-6d64-4842-b6fc-1e8419a5b128)
_Links to blog posts, patterns, libraries or addons used to solve this problem
https://developer.android.com/develop/ui/compose/touch-input/keyboard-input/keyboard-shortcuts-helper

[GSoC'24]: Implement Keyboard Shortcuts Helper

---

AnkiDroid/src/main/java/com/ichi2/widget/cardanalysis/CardAnalysisWidget.kt
AnkiDroid/src/main/res/layout/widget_card_analysis.xml

Aligned empty state visibility logic with `DeckPickerWidget` for a more unified behavior across widgets.
Enabled the widget to reconfigure by a direct tap, when the collection transit from a state of being empty collection to a non-empty collection.
https://github.com/user-attachments/assets/2eb8f92a-d615-425b-a487-fb3f4acf0e55

Refactored `CardAnalysisWidget` to handle empty state visibility in similar way to `DeckPickerWidget`.

---

AnkiDroid/robolectricDownloader.gradle

Our robolectric pre-downloader script that operates with retries in order to deflake CI when there are network failures has regressed and is not downloading the correct artifacts currently
robolectric appears to have bumped the suffix a couple times (from `-i4` through 5 and now `-i6`:
https://mvnrepository.com/artifact/org.robolectric/android-all-instrumented
...and we no longer appear to be using android 13 artifact, update list and download artifact construction to match, shown by results of following the process of clearing `~/.m2` then re-running `./gradlew jacocoUnitTestReport` then searching for the artifacts we actually use:
```
mike@isabela:~/work/ankidroid/Anki-Android (main *) % find /Users/mike/.m2/ -type d -name '*-robolectric-*' …
```

test: update robolectric artifact list / suffix to match current

---

AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt

This PR addresses an issue where the note types list would reset to display all items after a note type was deleted or renamed, even if a search filter was applied.
* Fixes #17101 
`filterNoteTypes` after deleting or renaming note
Oppo F21 Pro 5G
https://github.com/user-attachments/assets/534943e8-729c-4061-9190-ba3c44088841

Fix: Retain Search Filter After Deleting or Renaming Note Type in ManageNotetypes

---

AnkiDroid/src/main/res/layout/navigation_drawer.xml

To Purpose of this PR is to fix the issue in which long text is not fully show in navigation drawer.
* Fixes #17100
The Approach is to add property named `itemMaxLines`  with value `2` in `NavigationView`.
This change has been tested using different font size and languages.

Multi-Line Support in NavigationDrawer Added

---

AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/multimedia/audio/AudioRecordingController.kt

* Fixes #17227
Set `anchorView`
**Before**
**After**

fix(record-audio): saving audio snackbar obscured 'done'  

---

AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardMediaPlayer.kt

Don't play audio automatically" is not respected
* Fixes #16890 
https://github.com/user-attachments/assets/6d396b50-d648-470e-b490-0744a5c03943

Fixed TTS Autoplay

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/InstrumentedTest.kt
AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DebugInfoService.kt
AnkiDroid/src/main/java/com/ichi2/anki/services/BootService.kt
AnkiDroid/src/test/java/com/ichi2/anki/AnkiDroidAppFailureTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
AnkiDroid/src/test/java/com/ichi2/testutils/AnkiDroidAppWithFatalError.kt

* Fixes #16963
* catch `Throwable` rather than `Error`
Unit tested
```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt
<+>UTF-8
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt b/AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt	(revision dcf07cefcfff05fbe54615400a6e419b6f72c86d)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt	(date 1728647924463)
@@ -64,7 +64,7 @@
* @see [CollectionOpenFailure]
*/
@VisibleForTesting
-    var emulatedOpenFailure: CollectionOpenFailure? = null
+    var …
```

fix: handle `BackendException$BackendFatalError` on startup

---

AnkiDroid/src/main/assets/scripts/card.js
AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/res/values/02-strings.xml

JS User actions don't have a feedback if the user tries to use them without setting them up first, so issues like #17171 can get reported
* Fixes #17171
Add a feedback message if an user action isn't set

add missing user action message

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt

This pull request adds tooltip functionality to the supportActionBar subtitle in the application. By utilizing TooltipCompat, users can now easily view the full subtitle text when it exceeds the visible space. 
* Referencing #17100 
https://github.com/user-attachments/assets/ff418ffb-507a-42c2-9305-1db0f2736b6e

Enable Tooltip on ActionBar Subtitle for Overflow Text Visibility

---

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt

* Fixes part of #14320
I did the first commit because I thought that was necessary to properly remove the leech() method
But then I noticed that leech() wasn't used at all. I left the first commit there because it's still an useful update to libanki

Remove leech() method in Scheduler to avoid Android usages in libanki

---

AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.kt
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerKeyboardInputTest.kt

I noticed that the Undo control default shortcut is just Z, not Ctrl+Z like other apps, so I tried to fix it. I don't know if there is a reason to use just Z, but I can close this if there is one.
Add a Ctrl modificer
I reinstalled the app to see the new shortcut

Change undo default shortcut to Ctrl+Z

---

AnkiDroid/src/main/java/com/ichi2/anki/multimedia/AudioRecordingFragment.kt

The audio recorder UI was initialised twice at times, this PR fixes the behaviour 
* Fixes #17201
Tested locally on Google emulator API35

fix: audio recorder UI init twice

---

.github/workflows/compare_apk_size.yml

I wanted to see the size effect of the upstream jquery/mathjax usage from #17233 and tried it here:
https://github.com/ankidroid/Anki-Android/pull/17233#issuecomment-2409081070
That's insufficient now though: after the PR is merged. And in fact it was always unstable. Because the previous workflow always compared against "current main", instead of "main before the PR started adding commits"
I did a fair bit of learning on git and after looking at cat-file, rev-parse, `gh pr view --json commits,baseRefName |jq -r '.commits | length'` and a few other styles that worked or didn't work, this is the best way to find the base SHA I think
idea from https://stackoverflow.com/a/64510906/9910298

Apk size isolated analysis

---

AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
AnkiDroid/src/main/java/com/ichi2/anki/workarounds/NestedScrollingWebView.kt
AnkiDroid/src/main/res/layout/statistics.xml

Fixes the bug where zooming in causes infinitely scrollable page, also fixes unreliable zooming behavior. 🐞🔍
* Fixes #16135 
* Also fixes unreliable zoom behavior as the result. [(comment)](https://github.com/ankidroid/Anki-Android/issues/16135#issuecomment-2060684695)
The issue is fixed by a custom `WebView` that implements `NestedScrollingChild` to properly handle:
1. Scroll
2. Zoom
3. Nested Scrolling (to hide the toolbar)
The bug was caused because `NestedScrollView` interferes with the scale events, hence not allowing the `WebView` to properly handle them.
Device (Physical): Pixel 6a, Android 14, SDK 34
**Location:** Hamburger Menu -> Statistics
1. Scroll down: toolbar hides
2. Scroll up: toolbar reappears.
3. Zoom in -> Scroll to bottom: no infinite scrolling
4. Zoom in -> Zoom Out …

Bug: Statistics Zoom Issue#16135

---

AnkiDroid/src/main/java/com/ichi2/anki/SingleFragmentActivity.kt

* Fixes #17246
Fixed by re-initializing `fragment`
* On an API 34 tablet, the app no longer crashes after a user types

fix: SingleFragmentActivity: fragment has not been initialized 

---

AnkiDroid/build.gradle
tools/release.sh

Now that we are minifying release builds, we may have problems. A quick way to tell for sure if it is related to minification is to have a user try a non-minified build. This is very difficult unless you have one already available for the same commit the minified builds are on, so build them and upload them at the same time
This will also provide a way for users to self-help if it was a minification problem, as they can run unminified until fixed
Does not fix, but may help focus effort for a fix on:
* Related #17256
There is no way to control the `minifyEnabled` gradle buildType DSL property except in the block - it isn't possible to use gradle build config logic to do it in any other place dynamically
But you can operate conditionally right in the property assignment, and you can work of …

feat: create and upload un-minified release during publish

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/res/values/02-strings.xml
AnkiDroid/src/main/res/values/constants.xml

Instead of the previous toast plus going automatically to settings, the code now shows a dialog with an action to go to settings plus a link to the wiki related to full storage access. Of course suggest changes to the actual info text, additional link etc
* Fixes #16987
Checked how the dialog is looking, couldn't reproduce the actual situation when the dialog is being shown.

Improve info shown when collection directory is not accessible

---

AnkiDroid/proguard-rules.pro

This reverts commit aa271f93d3ce9d399da8983c849650261c696477.
`-dontobfuscate` appears to cause problems, and there were crashes in 2.19beta4-6 that appear to be related to it
It should work, and the failure has not been characterized yet
* Fixes #17256
A lot of detailed investigation and reading on my part, but really it was just a bisect and then a one-line change on an alternate release pathway (#17259) that allowed me to zero in on the `-dontobfuscate` change to proguard config
Diff indicated that proguard was only thing between beta3 and beta4 that should have caused this, and disabling it worked for user. So I *assume* that reverting that change will then work.
There is a slight chance it will not work.
`-dontobfuscate` must have some interaction between app code and library code …

Revert "fix: preserve debuggability even in minimized release mode"

---

AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt

Not sure what happened here but after the changes to use the WebView for preview images, it was no longer possible to preview images from the camera
Nothing logged but reproduction was done on an Android 14 emulator
- add new card
- click paperclip
- choose camera
- snap picture
- click check mark to accept the picture
Actual: a default graphic indicating that the image was not loaded into preview, and a toast
Expected: image loaded into preview and dialog to crop or not
Look at other places where the multimedia loads image information for viewing and do what those other places did
After making the change I follow my reproduction steps and I see my camera photo in the preview
No issue reproduction is so small that you won't find some other issue you need to fix before you can get back to …

fix: image preview was not shown after taking picture

---

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt

Fixes the bug where activity recreation causes `CardTemplateEditor` to set the view to `front` regardless of the previous state.
* Fixes #14086
<details><summary>This decides what would be view (front/back/style) of the template editor initially (or after activity restart)</summary>
<p>
https://github.com/ankidroid/Anki-Android/blob/8d626d1593b4364f1fb29b21925447d305b83bf2/AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt#L497
</p>
</details> 
<details><summary>But <code>EDITOR_VIEW_ID_KEY</code> is always <code>R.id.front_edit</code>,</summary>
<p>
https://github.com/ankidroid/Anki-Android/blob/8d626d1593b4364f1fb29b21925447d305b83bf2/AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt#L410
</p>
</details> 
<details><summary>as this is the initial value for …

fix: CardTemplateEditor restores wrong editor view

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt

After going to CardTemplateEditor the current card being edited is fetched again from the collection(this makes the card to have a null Note). After making changes and attempting to save, in the saveNote() method the card's note is being accessed and because it's null a call to note(collection) is done. This call fetches the previous stored fields values and those values end up being saved instead of the changed ones. 
* Fixes #17282
Ran the tests, manually verified the bug behavior. Also verified the normal save.

Fix saving changes in NoteEditor after CardTemplateEditor visit

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt
AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
AnkiDroid/src/test/java/com/ichi2/anki/instanteditor/InstantEditorViewModelTest.kt

Completes a TODO to keep ViewModel context free
Locally Google emulator API35

refactor: remove context from `InstantEditorViewModel`

---

funding.json

Initiative by Zerodha: potential funding from $10k-100k/year and a listing on https://dir.floss.fund/
**Announcement:**
https://floss.fund/blog/announcing-floss-fund/
**Manifest/schema:**
https://floss.fund/funding-manifest/
**Generated partially with**
https://vishnukvmd.github.io/funding.json/
⚠️ I am using the repo URL as ankidroid.org does not entice people to donate
I am not using the Play Store link as that did not pass the `.well-known` validation
* Part of Issue #17268
**Validated with:**
https://dir.floss.fund/validate
uri: https://github.com/ankidroid/Anki-Android/blob/main/funding.json
See a sample: https://dir.floss.fund/view/funding/@ziglang.org
* ⚠️ This document proposes a 'end' goal of funding two part-time maintainers. This seems reasonable to me, but I haven't discussed …

chore: add funding.json for FLOSS/fund

---

AnkiDroid/src/main/res/values/01-core.xml
AnkiDroid/src/main/res/values/02-strings.xml
AnkiDroid/src/main/res/values/03-dialogs.xml
AnkiDroid/src/main/res/values/04-network.xml
AnkiDroid/src/main/res/values/05-feedback.xml
AnkiDroid/src/main/res/values/07-cardbrowser.xml
AnkiDroid/src/main/res/values/09-backup.xml
AnkiDroid/src/main/res/values/10-preferences.xml
AnkiDroid/src/main/res/values/11-arrays.xml
AnkiDroid/src/main/res/values/16-multimedia-editor.xml
AnkiDroid/src/main/res/values/17-model-manager.xml
AnkiDroid/src/main/res/values/18-standard-models.xml
lint-rules/src/main/java/com/ichi2/anki/lint/IssueRegistry.kt
lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.kt
lint-rules/src/test/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLengthTest.kt

I tried to remove a `maxLength="41"` and lint was still succesful.
I finally took the time to learn how the linter works, after having years where it is a mystery.
Given that the code was not very clear to me, I added comments, and rewrote part of it.
I then realized that the issue was that, if the string was not found, no error was recorded. Strings may be missing either:
* because the string is hard coded in English (developer options), in which case I explicitly decided to ignore the strings, or
* because the string is defined outside of 10-preferences.xml
As far as I can tell, even if the string is not purely a preference, the max length constraint should still be present outside of preferences.
I also updated the string so that, with maxLength less than 41, the lint still works. This …

Fix FixedPreferencesTitleLength

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/ReviewerTest.kt
AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/InstrumentedTest.kt

For some reason the beta reviewer was being used
* Fixes some of #17298
* Leaving it open for a more permanent fix
Disable it to get CI working again
CI should tell

fix: emulator tests: testCustomSchedulerWithCustomData

---

AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt

Improvise the logs in StudyOptionsFragment to find the exact cause of NPE in study option fragment
* Related https://github.com/ankidroid/Anki-Android/issues/17284
Local build

refactor: improve logs related to deckPicker in StudyOptionsFragment

---

.idea/dictionaries/anki.xml
AnkiDroid/src/main/java/com/ichi2/anki/preferences/AboutFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DebugInfoService.kt
AnkiDroid/src/main/res/layout/about_layout.xml

Adds the fsrs version to the debug info. In a separate commit I also added the version to the about settings screen so it can be removed if not wanted(or maybe combine the backend and fsrs info):
Towards #17236
Looked at the debug info, looked at the settings screen

Add fsrs version to debug info

---

AnkiDroid/src/main/java/com/ichi2/anki/pages/DeckOptions.kt
AnkiDroid/src/test/java/com/ichi2/anki/pages/DeckOptionsTest.kt

Hello, I'm mostly a TypeScript dev who is really rusty with Android and trying to get back into Android development. Forgive my Android newbie-ness.
Implemented test case for `DeckOptions`, ensures that on pressing the system-level back button and back navigation icon finishes the activity. 
* Fixes part of #13283
2 tests have been written: 1 that does a system-level back press and 1 that simulates the icon button back press. For both tests, it passes as long as the deck options fragment activity is finishing.
I understand that the test annotation description was to verify that it returned to the previous screen, does checking if the activity is finishing sufficient in determining that going back works as intended?
I assume it's related to this other test case: `@NeedsTest("15130: …

test: deck options on back press

---

AnkiDroid/src/main/java/com/ichi2/compat/PackageManagerCompat.kt
AnkiDroid/src/main/java/com/ichi2/compat/ResolveInfoCompat.kt
AnkiDroid/src/main/java/com/ichi2/compat/customtabs/CustomTabsHelper.kt
AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt

We're now on AGP 8.7.1 and this is fixed:
https://issuetracker.google.com/issues/367752734
* remove `open = true`
* fix error
Reverts part of 7db4ea983b127812fcb9c6a34f0cd325a0f9f91d
* androidGradlePlugin 8.6.1 broke lint if using `.toLong()` in a `@LongDef`
https://issuetracker.google.com/issues/367752734 was been raised and `open = true` was temporarily added on broken `@LongDef` instances
* Broken/added in #17086
* Fixed in #17263
* Fixes #17265
`./gradlew lint` now passes

fix: revert workaround for broken AGP [8.6.1]

---

AnkiDroid/src/main/java/com/ichi2/widget/deckpicker/DeckPickerWidgetConfig.kt

This change allows users to access filtered decks directly from the homescreen widget, enhancing usability and quick access to specific decks.
* Fixes #17323
The change involves modifying the `DeckPickerWidgetConfig.kt` file by updating the `SelectableDeck.fromCollection()` function. Specifically, the `includeFiltered` parameter was changed from `false` to `true`, allowing filtered decks to be included in the widget selection options.
Tested by adding filtered decks to the widget and confirming they appear correctly.

Enable filtered decks in widget

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/AnkiFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt
AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt
AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerActivity.kt
AnkiDroid/src/main/java/com/ichi2/themes/Themes.kt
AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt
AnkiDroid/src/main/java/com/ichi2/utils/VersionUtils.kt
AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupMetaTest.kt
gradle/libs.versions.toml

Unblock new dependencies that rely on compileSdk 35
most of the changes performed at same time are nullability-related
there are two specific things deferred via suppression annotation:
- all the targetSdk 35 edge-to-edge behavior changes - this is a big one
- one compute bounds thing for graphics, minor but API change is confusing
No fixes but:
- Related: #17327 
- Related: #17329 
Nullability stuff was easy to handle as the null case was already contemplated in the codepaths as either "okay" or already an error. So that was just syntactic chore
Suppression of two other things was different and related issues have been logged:
- #17334 
- #17335 
Ran the lint gradle command line locally as well as `./gradlew jacocoTestReport` until everything compiled well and tested okay
Same ol' same …

chore: forward-port to compileSdk 35

---

AnkiDroid/build.gradle
AnkiDroid/jacoco.gradle
AnkiDroid/src/amazon/AndroidManifest.xml

When there's too much noise I can't see the signal, so took a pass at quieting our build down
Also, we're ready for gradle 9 now
Nothing logged - but the final result is that there are zero gradle warnings except about tools:replace not replacing anything
Ran all the main build targets with --warning-mode=all and fixed them, also looked at the manifest merger warnings
By re-running the tasks, and checking file perms on pre-commit hook
It is not possible to quiet the build warning from a `tools:replace` manifest merger when there was nothing to replace
It seems that the merger happens in priority order, and since it comes from a library, my attempt to define a dummy entry in our app manifest (that would be replaced, quietly) did not work as the replace warning already happened when the …

Gradle lintage

---

.github/workflows/milestone.yml

2.19.1 is released and I think it makes sense now to update the milestone targets to [2.20 ](https://github.com/ankidroid/Anki-Android/milestone/64)
No tests for this.

Update milestone targets to 2.20

---

AnkiDroid/src/main/res/layout-land/introduction_layout.xml
AnkiDroid/src/main/res/layout/introduction_layout.xml

This PR ensures the introduction screen remain accessible and user-friendly when larger text sizes are used by making the layout scrollable. This enhances usability, particularly for users with accessibility needs or custom font settings.
* Towards #17100 
https://github.com/user-attachments/assets/96ccfcd2-7f39-43b4-9777-29f0c466aa87
https://github.com/user-attachments/assets/85416477-5550-450e-8928-7e621bb801b0

Make Introduction Screen Adaptable for Larger Text Sizes

---

.gitignore

At least on my device, I get plenty of warning that files are created. It seems to be generated by bug in tests system.
As I don't expect it'll be useful to anyone, I allow myself to request a change in gitignore

NF: Add `.attach_pid*` to gitignore

---

AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt

Whilst looking through logcat, it was not obvious when an error dialog was displayed

logs: `showError`

---

gradle/libs.versions.toml

Need the new `SYNC_SERVER_MESSAGE` for an upcoming PR.
See: https://github.com/ankidroid/Anki-Android-Backend/pull/439

Update Anki to 24.11rc1

---

AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt

- https://github.com/ankidroid/Anki-Android/issues/17376
* Fixes #17376
Use try-catch and show snackbar to the user
Local build, API35

Fix: Activity Not found exception

---

AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt

- https://github.com/ankidroid/Anki-Android/issues/17388
When some invalid or corrupted file is being pasted in the field then it might cause the issue, though I tried to reproduce it with various types of  files such as pdf but can not get it, so putting a try catch and send report to ACRA
* Fixes #17388
Local build, try-catch should do the work

fix: invalid file issue on pasting file

---

.idea/dictionaries/android.xml
AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt
AnkiDroid/src/main/java/com/ichi2/libanki/BackendDeckOptions.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
AnkiDroid/src/test/java/com/ichi2/anki/pages/PostRequestHandlerTest.kt

Make sure that we do not update to newer Anki backend versions where the names of TS functions do not correlate to the mappings we have set in PostRequestHandler. Otherwise, we would have to manually go and check for any such change in the Anki repo. If we don't do this, then functionality in some of the Svelte pages might be straight up unsupported, and we wouldn't know about this until we actually test the affected component.
N/A.
Refactor PostRequestHandler so the switch-statement takes the form of a hash map instead. Then, in PostRequestHandlerTest, use list of TS functions generated from the AnkiDroid backend (https://github.com/ankidroid/Anki-Android-Backend/pull/434) to find out what function mappings we are supposed to have.
Just made sure that the tests passed and made sure we …

Test that all TS backend functions are handled

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/pages/ImageOcclusion.kt

_NoteEditor_ keeps its own reference to the selected deck through _deckId_, see the _onDeckSelected()_ method where on deck change the code doesn't update the deck selected in the backend:
https://github.com/ankidroid/Anki-Android/blob/1107816ffc5c1a9395d70a48a62a3ccf1c64746d/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt#L392-L396
The problem for image occlusion cards is we use the backend page which will use as a target for the new cards the deck that the backend currently sees as selected, see:
https://github.com/ankitects/anki/blob/763712c69697cbfca6f758ec0602714e2c90c2a8/rslib/src/image_occlusion/imagedata.rs#L49
So image occlusion cards will always be added to the deck that was selected when NoteEditor was created. The fix I used passes the deckId from NoteEditor and then …

Fix image occlusion cards being added to wrong deck

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
AnkiDroid/src/main/java/com/ichi2/widget/cardanalysis/CardAnalysisWidget.kt
AnkiDroid/src/main/java/com/ichi2/widget/deckpicker/DeckPickerWidget.kt

This also cause shortcuts, reminder and widget to use the IntentHandler instead of directly opening the Reviewer.
I should note that the reminders that were created before this commit will break when the Reviewer class will be removed. Unless we specifically keep the Reviewer to cause it to redirect to the new Reviewer.
Given that the reminder is quite broken anyway, must be redone from scratch, at this point, I think it's an acceptable loss. Trying to correct it while the reminder does not work properly will be a nightmare.
There are still plenty of places in the code that use the previous reviewer inconditionally. I'm not touching them, because I don't need them to unblock my sync in reviewer issue
Test: I tested shortcut and deck picker widget. I've not tested notification as they are …

IntentHandler decides which reviewer is used.

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/ReviewerFragmentTest.kt
AnkiDroid/src/androidTest/java/com/ichi2/anki/ReviewerTest.kt
common/build.gradle.kts
gradle/libs.versions.toml
testlib/build.gradle.kts
testlib/src/test/java/com/ichi2/testutils/common/AnkiAssertTest.kt

Much to my annoyance I continue to see gradle 9 deprecation warnings in Android Studio
I hunted down a couple more with generic "./gradlew test" or "./gradlew build" type targets
None of this is really important.
Nothing logged, but I don't want unexpected build errors when gradle 9 comes out, and it should be shortly
The gradle deprecation warnings are at least very informative, they contain links to the page describing what to do
These changes were basically all test-related, so, testing was pretty obviously to keep running the test targets
just handling deprecation in toolchains is a significant chunk of my life
Also, it seems like there might be some internal chunk of Android Studio that contains deprecation itself, as one final target seems to continue triggering things - …

More gradle lint

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.kt
AnkiDroid/src/androidTest/java/com/ichi2/anki/FilteredDeckOptionsTest.kt
AnkiDroid/src/androidTest/java/com/ichi2/anki/ReviewerFragmentTest.kt
AnkiDroid/src/androidTest/java/com/ichi2/anki/ReviewerTest.kt
AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/InstrumentedTest.kt
AnkiDroid/src/androidTest/java/com/ichi2/anki/testutil/DeckPicker.kt
AnkiDroid/src/androidTest/java/com/ichi2/anki/testutil/IntroductionSlide.kt
AnkiDroid/src/androidTest/java/com/ichi2/anki/testutil/StudyOptionsFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/IntroductionActivity.kt

This PR move some code so that it can easily be reused. Multiple PR are going to be based on them, and use the method the current PR introduce.

NF: Move instrumented test functions

---

AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt
AnkiDroid/src/test/java/com/ichi2/utils/ImportUtilsTest.kt

We have a lot of reports in the form of:
```
java.lang.RuntimeException: Error importing apkg file
at com.ichi2.utils.ImportUtils$FileImporter.handleContentProviderFile(ImportUtils.java:211)
at com.ichi2.utils.ImportUtils$FileImporter.handleFileImportInternal(ImportUtils.java:128)
at com.ichi2.utils.ImportUtils$FileImporter.handleFileImport(ImportUtils.java:117)
at com.ichi2.utils.ImportUtils.handleFileImport(ImportUtils.java:61)
```
coming from:
https://github.com/ankidroid/Anki-Android/blob/f4b08261418fca31293629a55d341b861c0fbb73/AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt#L203-L211
which are a front for problems in the ImportUtils.copyToCache() method:
https://github.com/ankidroid/Anki-Android/blob/f4b08261418fca31293629a55d341b861c0fbb73/AnkiDroid/src/main/java/com/ichi2/ut …

Expose exceptions thrown during caching of imported files

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/pages/CongratsPage.kt
AnkiDroid/src/main/res/values/02-strings.xml
AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.kt

My main problem was with the typing of the ID. Using an integer seemed strange while we have `entries` that work as well.
I realized that some enum values were not used anymore. So I just remove them. This means that the dialog is either Standard or a `ContextMenuOption`.
I assume we can squash if you want. But I hope this list of commit makes reviewing simple

Simplify Custom Study Dialog

---

AnkiDroid/src/main/AndroidManifest.xml
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
AnkiDroid/src/main/res/drawable/ic_arrow_back_white.xml
AnkiDroid/src/main/res/layout-xlarge/homescreen.xml
AnkiDroid/src/main/res/layout/deck_picker.xml
AnkiDroid/src/main/res/layout/homescreen.xml
AnkiDroid/src/main/res/layout/studyoptions.xml
AnkiDroid/src/main/res/layout/studyoptions_fragment.xml
AnkiDroid/src/main/res/menu-xlarge/deck_picker.xml
AnkiDroid/src/main/res/menu/activity_study_options.xml
AnkiDroid/src/main/res/menu/study_options_fragment.xml

Introduces changes to improve the handling of menus around StudyOptionsFragment which is used both in single and multi pane layouts in multiple activities. More info in the commits details.
Other notes:
- the undo menu item was moved out of StudyOptionsFragment, I think this is a global action and shouldn't be handled manually at fragment level
- the previous code used an option on tablets to export the current selected deck. I don't feel this is a menu option that should be present as we already have a menu item that does this at the cost of an extra touch. Also doesn't seem this would have the use frequency to have its own menu item.
- as the second commit introduces breaking changes(fixed later) the last 4 commits should probably be squashed.
- the label _"StudyOptions"_ was deleted …

Fix study options related menus

---

AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
AnkiDroid/src/main/java/com/ichi2/utils/WebViewUtils.kt

There are several reports in acra about crashes in _checkWebviewVersion()_ when parsing the system WebView version. It seems some of those versions appear as _"Developer Build"_ and not a simple number like we expect.
https://ankidroid.org/acra/app/1/bug/256775/report/e8bb99dc-2cb8-4a73-ab66-3491c1e2752f
https://ankidroid.org/acra/app/1/bug/253230/report/6d761065-e7d6-498a-9323-84a68f7fbfd4
Stacktrace:
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.DeckPicker}: java.lang.NumberFormatException: For input string: "Developer Build"
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2683)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2744)
at …
```

Handle failures to parse system WebView version

---

AnkiDroid/src/main/AndroidManifest.xml
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
lint-release.xml
testlib/src/main/AndroidManifest.xml

*   #17425
The lint build fails with the following error: "Error: For locale "ca" (Catalan) the following quantity should also be defined: many "[MissingQuantity] to solve this error I Revert lint rule changes [UnusedQuantity, MissingQuantity] from fatal to ignore 
*  Fixes #17425 
I made modifications to two AndroidManifest.xml
*AnkiDroid/src/main/AndroidManifest.xml
*testlib/src/main/AndroidManifest.xml
in lint-release.xml I changed thes two line from
```xml
<issue id="UnusedQuantity" severity="fatal" />
<issue id="MissingQuantity" severity="fatal" />
```
to
```xml
<issue id="UnusedQuantity" severity="ignore" />
<issue id="MissingQuantity" severity="ignore" />
```
These changes fix the lint build failure, making the build successful
tested on emulator Google HPE device
_Describe the …

Revert lint rule changes

---

AnkiDroid/robolectricDownloader.gradle
gradle/libs.versions.toml

#17445 contained new robolectric and I suspected we'd need the android 15 artifact
Turns out the artifact build number had changed, as had the preinstrumented number (which I documented this time)
Updated both
Nothing logged but without this, we're sure to get random unit test flakes
Follow the directions in the file (and update the directions where a chunk was missing)
This is what it looks like after `\rm -fr ~/.m2` before this patch when you run `./gradlew jacocoUnitTestReport` then:
```
mike@isabela:~/work/ankidroid/Anki-Android (dependency-updates *) % find ~/.m2 -type d -name '*-robolectric-*'
/Users/mike/.m2/repository/org/robolectric/android-all-instrumented/14-robolectric-10818077-i7
/Users/mike/.m2/repository/org/robolectric/android-all-instrumented/15-robolectric-12650502-i7 …
```

Update robolectric downloads

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/res/layout/note_editor.xml

_AnkiFragment_ was using _CollectionManager.getColUnsafe()_ and also set up a loading mechanism similar with the _CollectionLoader_ used by _AnkiActivity_ returning the same _CollectionManager.getColUnsafe()_. This PR removes the loading mechanism and lets NoteEditor to only use _CollectionManager.getColUnsafe()_. This way, the setup that was done in onCollectionLoaded() is inserted in the fragment lifecycle and should prevent bugs from the bad timing around onCollectionLoaded().
The progress bar in the layout was removed because it was only used for the collection loading mechanism.
I was kind of able to reproduce the error in #17380 by using the same steps from #17407(modify the collection loading in ANkiFragment) and opening NoteEditor -> attach image. I said kind of because there's a …

Remove legacy collection loading code from AnkiFragment

---

AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt

- https://github.com/ankidroid/Anki-Android/issues/17361
The image when shared to AnkiDroid directly doesn't grant Uri permission as the photo is coming from other app, so we internalise the URI and then use the image, hence fixing the crop issue as it needs Uri with correct permission to edit it
* Fixes #17361
Tested on Google Emulator API 35

fix: unable to crop shared images

---

AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt

* Fixes #17075
Get the input box with its new ID
By changing the deck in statistics with its deck spinner

Use ID for getting input box in statistics

---

AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt

I tried to find some TODO in the project and fixed these in libanki. I hope it helps
Followed upstream's implementation
https://github.com/ankitects/anki/blob/edf59c2bb2a3dad36115af7518cdcbb3ee397089/pylib/anki/decks.py
I don't know how to test it

Implemented some libanki TODOs

---

AnkiDroid/src/main/java/com/ichi2/anki/LanguageUtils.kt

Fixes a recent [acra report](https://ankidroid.org/acra/app/1/bug/259385/report/f8483a5e-4e0f-438a-9630-e1720e7aa380) where the device locale was not available. This crashes the preferences code because we query the displayName of the locale to determine if the app language is rtl or not:
```
Caused by: java.lang.StringIndexOutOfBoundsException: length=0; index=0
at java.lang.String.charAt(Native Method)
at com.ichi2.anki.LanguageUtils.appLanguageIsRTL(LanguageUtils.java:46)
at com.ichi2.preferences.HeaderPreference$Companion.buildHeaderSummary(HeaderPreference.kt:69)
at com.ichi2.preferences.HeaderPreference.<init>(HeaderPreference.kt:45)
at com.ichi2.preferences.HeaderPreference.<init>(HeaderPreference.kt:31)
at com.ichi2.preferences.HeaderPreference.<init>(HeaderPreference.kt)
... 35 …
```

Handle locale name being empty in preferences

---

AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.kt

Looking at acrarium, there was a pretty odd crash with a NullPointerException.
Those are usually pretty easy to fix but I couldn't really figure out why on this one:
https://ankidroid.org/acra/app/1/bug/260065/report/ec131296-dcf2-44e3-bd7f-3aa8f34678f6
```
11-22 07:38:50.977 W/AnkiDroid( 7692): Activity/ java.lang.NullPointerException
11-22 07:38:50.977 W/AnkiDroid( 7692): 	at com.ichi2.anki.CollectionHelper.getAppSpecificExternalAnkiDroidDirectory(CollectionHelper.kt:225)
11-22 07:38:50.977 W/AnkiDroid( 7692): 	at com.ichi2.anki.CollectionHelper.getDefaultAnkiDroidDirectory(CollectionHelper.kt:189)
11-22 07:38:50.977 W/AnkiDroid( 7692): 	at com.ichi2.anki.CollectionHelper.getCurrentAnkiDroidDirectoryOptionalContext$lambda$2(CollectionHelper.kt:295)
11-22 07:38:50.977 W/AnkiDroid( 7692): …
```

chore: add triage information for unexplained startup crash

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/AppearanceSettingsFragment.kt

Fixes one more acra crash report about an app not being available to handle a _Intent.ACTION_CREATE_DOCUMENT_ request. To avoid these in the future I went and verified other places where an _ActivityNotFoundException_ might be thrown and handled those as well. Can squash if asked.

Fix more potential ActivityNotFoundExceptions

---

AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler2.kt

Avoid a crash seen in Acrarium when user sent bad data into AnkiDroid via Intent
https://ankidroid.org/acra/app/1/bug/258530/report/9c451938-ee66-4852-b2ff-2b1c2204d51b
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.IntentHandler2}: java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4169)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at …
```

fix: avoid crash if intent sent with no extras

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt

Fix a crash where the shared deck download state is such that the WebView is attempting to instantiate our shared fragment download listener, but activity/fragment lifecycle state is already saved during teardown process
ACRA crash https://ankidroid.org/acra/app/1/bug/260938/report/667f6607-e575-4499-8860-2bb61b5db51b
```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1861)
at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1901)
at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:342)
at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:306)
at com.ichi2.anki.SharedDecksActivity.onCreate$lambda$1(SharedDecksA …
```

fix: ignore shared deck download and dialog dismissal at inappropriate lifecycle states

---

AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt

these no longer generate useful reports
* Fixes #17373
This stops reporting one specific error in coroutine handler and in startup
Ran it manually and watched logcat, using the test-trigger-patch from linked issue
```
11-20 20:21:36.137 15236 15236 D DeckPicker: handleStartup: Continuing after permission granted
11-20 20:21:36.143  1595  9078 E MediaProvider: Creating or writing to a non-default top level directory is not allowed!
11-20 20:21:36.144  1595 12530 E MediaProvider: Creating or writing to a non-default top level directory is not allowed!
11-20 20:21:36.146 15236 15236 W InitialActivity: com.ichi2.anki.exception.StorageAccessException: Failed to create AnkiDroid directory /storage/emulated/0/AnkiDroid
11-20 20:21:36.146 15236 15236 W InitialActivity: 	at …
```

fix: stop reporting storage access exceptions to acrarium

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BrowserOptionsDialog.kt

this allows Fragment lifecycle save/restore to work seemlessly and that fixes crashes on Activity restarts
~~**NOTE THAT IF THIS STYLE IS OKAY - A FEW OTHER DIALOGS NEED FIXES IN SAME STYLE**~~
[edit: turns out this was the only easy one like this - so just one commit]
* Fixes #17381
Used the approach mentioned here https://stackoverflow.com/a/51831137/9910298
- Stop providing params to constructor, so there is a default constructor as required by default Fragment factory
- Start providing params as a Bundle set in to Fragment.arguments via a static newInstance method
- Access all params via Fragment.arguments
- Handle optionally missing arguments with warnings+defaults
- Enable developer option Don't Keep Activities
- Go to Card Browser, open Actions Menu "Options"
- Background …

fix: use default constructor / factory + Arguments init style

---

AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
AnkiDroid/src/main/res/layout/studyoptions_fragment.xml
AnkiDroid/src/main/res/values/02-strings.xml

Shows again the total number of cards and the total new cards in the study options screen by switching to the old code. See images:
* Fixes #17489
Ran the tests, checked the study options screen.

Restore info related to cards counts in study options

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DebugInfoService.kt
AnkiDroid/src/main/java/com/ichi2/utils/WebViewUtils.kt
AnkiDroid/src/test/java/com/ichi2/utils/WebViewUtilsTest.kt

Apparently the webview package on some devices can have a version code and version name that indicate they will not be compatible, but they work fine.
Inspection of the User-Agent string from the WebView indicates it advertises a Chrome version that is more than adequate.
This PR adds a fallback WebView version detection mode that will believe the User-Agent if it says it's compatible, even if the versionCode says it isn't
* Fixes #17498
Most of the work: refactoring and adding a test:
- Start by refactoring all the WebView stuff in to one spot
- Continue by refactoring the gathering of information from the processing of information, so it is testable
- Add some test cases that behave how 2.19.2 currently behaves
Actual work:
Add logic to check User-Agent and verify that our confusing …

Fix webview version fix

---

AnkiDroid/src/main/java/com/ichi2/anki/SingleFragmentActivity.kt

There were two Activities that attached the custom factory for custom study dialog in onCreate, but there were *three* that needed it (SinglePageActivity hosting CongratsPage fragment hosting study options was missing)
If you didn't attach in onCreate then you would crash if the fragment/activity lifecycle had done a cycle on you due to background kill or don't keep activities on
https://ankidroid.org/acra/app/1/bug/237277/report/ecbf20ba-e077-4952-ae40-14d56647ad99
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.SingleFragmentActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.ichi2.anki.dialogs.customstudy.CustomStudyDialog: could not …
```

fix: attach custom study dialog fragment factory in SinglePageActivity to avoid crash

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt

Fixes NullPointerException in onQueryTextChange by safely casting the adapter to Filterable before calling the filter method, preventing crashes when the adapter is null or not of the correct type.
* Fixes #17391 
Realme 6 and Emulator

Fix: DeckPicker-NullPointerException in onQueryTextChange

---

gradle/libs.versions.toml

Won't build until Maven Central has it:
https://mvnrepository.com/artifact/io.github.david-allison/anki-android-backend

build(deps): adopt anki24.11 release plus deck options z-index fix

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/FilteredDeckOptionsTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/pages/DeckOptionsTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/preferences/PreferencesTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/ui/windows/permissions/PermissionsActivityTest.kt

* https://github.com/ankidroid/Anki-Android/pull/17495 failed with
```
CreateDeckDialogTest > searchDecksIconVisibilityDeckCreationTest FAILED
java.lang.OutOfMemoryError: Java heap space
at org.robolectric.res.android.CppAssetManager2$Theme.SetTo(CppAssetManager2.java:1700)
at org.robolectric.shadows.ShadowArscAssetManager10.nativeThemeCopy(ShadowArscAssetManager10.java:1657)
...
```
This is similar to: https://github.com/ankidroid/Anki-Android/commit/1113858df6a6b8c8c93afac0e1f788942db70c9f. We likely have a few more leaks, but this is a quick one to scan for and fix
*  https://github.com/ankidroid/Anki-Android/pull/15532
Call `.use { }`
Ran tests and they continued to pass

test: close Scenarios after use to reduce memory pressure

---

.idea/dictionaries/usernames.xml
AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ACRATest.kt
AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt
AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ThrowableFilterService.kt
AnkiDroid/src/test/java/com/ichi2/anki/CrashReportServiceTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/ThrowableFilterServiceTest.kt
build.gradle.kts

See title. Related:
https://github.com/ankidroid/Anki-Android/issues/17392
https://github.com/ankidroid/Anki-Android-Backend/pull/439
https://github.com/ankitects/anki/commit/ba1f5f4
Preemptive "may lord have mercy".

Block reports sent to ACRA

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/android/input/Shortcut.kt
AnkiDroid/src/test/java/com/ichi2/anki/ShortcutTest.kt

"Press Alt+K to show keyboard shortcuts" pops up on Numpad 1
Previously the code was incorrectly handled which it only checks isNumKey pressed then condition getting true which is not expected. I group isNumKey condition with isModifierKey it will be true when both modifier and num key pressed.
* Fixes #17490
Chromebook 

fix: don't show warning on numpad

---

AnkiDroid/src/main/AndroidManifest.xml
AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.kt
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/SingleFragmentActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/AboutFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/CustomButtonsSettingsFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/DevOptionsFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/HeaderFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/NotificationsSettingsFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/SettingsFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/SyncSettingsFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/services/BootService.kt
AnkiDroid/src/main/java/com/ichi2/anki/services/NotificationService.kt
AnkiDroid/src/main/java/com/ichi2/anki/utils/Resources.kt
AnkiDroid/src/main/java/com/ichi2/preferences/HeaderPreference.kt
AnkiDroid/src/main/java/com/ichi2/widget/WidgetStatus.kt
AnkiDroid/src/main/res/layout-sw600dp/preferences.xml
AnkiDroid/src/main/res/layout/preferences.xml
AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupUnderBackupTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/preferences/PreferenceTestUtils.kt
AnkiDroid/src/test/java/com/ichi2/anki/preferences/PreferencesTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/preferences/SettingsSearchBarTest.kt
AnkiDroid/src/test/java/com/ichi2/testutils/ActivityList.kt

I want to create a preferences screen for the new reviewer toolbar menu buttons, but the Preferences activity is not flexible enough for what I want to do, so I went on and refactored a good chunk of it to reduce the dependency on `Preferences` and have a bigger fragment modularity.
* Fixes #17414
* Closes #17447 
In the commits
Emulator 34
[uno.webm](https://github.com/user-attachments/assets/afa136bb-7365-4e45-ba47-f6d7d3408475)
[developers developers developers.webm](https://github.com/user-attachments/assets/a5ec58ac-9ea8-4d4d-a03e-52dd622df38e)
[tablets.webm](https://github.com/user-attachments/assets/da7fc5db-f64d-4a4c-aef8-3ac3867f7093)
[highlight.webm](https://github.com/user-attachments/assets/f925939e-771c-4115-b2db-eda930affd4b) …

refactor: move most of the Preferences activity into a fragment

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
AnkiDroid/src/main/java/com/ichi2/anki/Ease.kt
AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
AnkiDroid/src/main/java/com/ichi2/anki/reviewer/EaseButton.kt
AnkiDroid/src/main/java/com/ichi2/anki/reviewer/PreviousAnswerIndicator.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerViewModel.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt
AnkiDroid/src/main/java/com/ichi2/libanki/sched/DummyScheduler.kt
AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt
AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerKeyboardInputTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerNoParamTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/AbstractSchedTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/CardTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/SchedulerTest.kt
api/src/main/java/com/ichi2/anki/api/Ease.kt

This allows to remove else in `when` case, and generally improve typing. Also, allows to remove some constant that were duplicate of the enum entries.

NF: Use com.ichi2.anki.Ease as much as possible

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt
AnkiDroid/src/main/java/com/ichi2/anki/FlagToDisplay.kt
AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/FlagAdapter.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/FlagRenameDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerViewModel.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerCommandTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/AnkiDroidJsAPITest.kt
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/FlagToDisplayTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/FlagTest.kt

It should be added that there is some ambiguity for the value of the flag. A flag could be either between 0 and 7, or an arbitrary int whose first 3 digits are the displayed flags.
Actually, the only time a number greater than 7 is generated, it's stored into the card's `flags` field, and never leave this object. So it's okay to use `Flag` object everywhere else.

NF: Use enum for flag everywhere possible

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler2.kt
AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/NoteEditorLauncher.kt
AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt

Those commits add some enum for the sake of code clarity

refactor: int constants => enum

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/MediaTest.kt

The MediaTest.kt contained actual.retainAll(expected). Its performance was bit slower.
It improved by using actual.retainAll(expected.toSet()).

Fixed a weak warning of "The argument can be converted to 'Set' to improve performance" in MediaTest.kt file in Line 131.

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt

No longer exists
Part of a goal to eliminate `deckLimit()` -> `decks.active()`

refactor: remove 'sched.totalCards'

---

.github/workflows/conflict.yaml

Looked at other workflows where we catch api calls errors and added a try-catch for 404 failures while still failing for any other errors.
* Fixes #17548
Not really testable.

Fix workflow failure when (Has Conflicts) label is already removed

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt

Root Cause of the issue was:
- Persistent Flow Subscription: Each time handleMultimediaActions is called, a new subscription to the multimediaAction flow is created, leading to multiple active observers.
- Race Condition: When an action is emitted, all active subscriptions are notified, causing the action to be handled multiple times.
* Fixes #17453
Keep track of the job 
Tested on Google emulator API35

fix: multimedia options opening more than once

---

AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/utils/ext/BitmapDrawable.kt
AnkiDroid/src/main/res/layout/fragment_multimedia_image.xml
AnkiDroid/src/main/res/values/16-multimedia-editor.xml

Render SVG instead of showing a warning text.
Blocked by
* #17014
* Fixes #17029
Use a webview to render an SVG in it
Tested on OnePlus Nord CE:

Feat[Multimedia]: render `svg` using webview

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt
AnkiDroid/src/main/java/com/ichi2/anki/reviewer/AutomaticAnswer.kt
AnkiDroid/src/main/res/values/10-preferences.xml
AnkiDroid/src/main/res/values/constants.xml
AnkiDroid/src/main/res/values/preferences.xml
AnkiDroid/src/main/res/xml/preferences_reviewing.xml
AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/reviewer/AutomaticAnswerAndroidTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/reviewer/AutomaticAnswerTest.kt

People get confused when they enable Auto Advance but it doesn't work. The preference had an use when Anki didn't have Auto advance, but now it doesn't have a purpose because everything can be configured from deck options
Example: https://forums.ankiweb.net/t/auto-advance-in-deck-options/51898
* Fixes #17463
Removed the global setting
Tested if auto advance still works

Remove Automatic Display Answer global setting

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/InitialActivityWithConflictTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomExceptionDataTest.kt

The purpose of this pr is to add a button in Error Dialog to copy stack track and debug info.
* Fixes #17232
The approach is to first pass the exception from `InitialActivity` to `DeckPicker` by converting the `StartupFailure` enum into a sealed class and adding an exception parameter to each class inside the `StartupFailure` sealed class. Then, in the `DeckPicker` class, a companion object is created to store the exception. Finally, in the `DatabaseErrorDialog`, the companion object is accessed and used in the `copyStackTraceAndDebugInfo` function.
This change has been tested for database errors.

feat(error-dialog): copy stack trace & debug info

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
AnkiDroid/src/test/java/com/ichi2/anki/AnkiDroidJsAPITest.kt

I had a bug because I sent it an enum, and it didn't know how to read it again. By ensuring it only takes known value, any dev can find really quickly where the bug comes from

NF: APIResult takes known type only

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/DownloadFileTest.kt
AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.kt
AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
AnkiDroid/src/main/java/com/ichi2/utils/FileUtil.kt
AnkiDroid/src/test/java/com/ichi2/utils/FileUtilTest.kt

[API 35] `URLUtil.guessFileName`: regression guessing file extension [selects '.bin' when better alternatives exist] - https://issuetracker.google.com/issues/382864232
AnkiDroid fails to open `Goethe_Institute_A1_Wordlist.bin`
* Fixes #17573
* repurpose `getFileNameAndExtension` to return a class
* Use this to handle updating the extension of the file to `apkg`
* Unit tests
* Instrumented tests:
* API 35 emulator
* API 34 emulator 
https://issuetracker.google.com/issues/382864232
Android 15 is out
@thedroiddiv is awesome (I knew this already, so I guess this wasn't learning and I just wanted to say thank you!)
* `File.createTempFile("ok", ".computer")` fails: the length of the first string must be `>= 3`
* ⚠️ this is now a URL, maybe we want another test value?

fix(shared-decks): can't download decks on Android 15

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt

While working on #17399 I realized that similar cleaning could occur to the nullable deck picker that can't actually be null.

Some cleaning of Database error dialog

---

AnkiDroid/src/main/java/com/ichi2/anim/ActivityTransitionAnimation.kt
AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardMediaPlayer.kt
AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/GestureProcessor.kt
AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/MediaPlayer.kt
AnkiDroid/src/main/java/com/ichi2/anki/reviewer/AutomaticAnswer.kt
AnkiDroid/src/main/java/com/ichi2/anki/reviewer/MappableBinding.kt
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt
AnkiDroid/src/main/java/com/ichi2/ui/CheckBoxTriStates.kt

#17352 duplicated. For some reason I can't re-open it
When `when` is used on an enum, the `else ->` can always be transformed into a complete enumeration of the enum's entries.
This ensure that each time a new entry is added, there is a warning and the developer must decide whether or not a change is needed. While the `else` may hide some required change.
So, for the sake of future developement, I removed `else ->` when it makes sense.
I should note that I kept some `else ->` when the `when` consider only a very small part of all possible enum value, in order to reduce the size of the code.

NF: Remove `else ->` when possible

---

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateBrowserAppearanceEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.kt

Replace some usages of onBackPressed() with specific OnBackPressedCallbacks that are enabled/disabled ahead of time(of BACK action). More info in the commits messages. Four more usages of onBackPressed() left but those are more difficult to fix. See some videos with the new behavior(must add _android:enableOnBackInvokedCallback="true"_ for the _application_ tag in the manifest):
https://github.com/user-attachments/assets/2fb01930-7629-41ca-b065-c5cea7ea5ec9
https://github.com/user-attachments/assets/5abb8642-1aa7-497e-aa07-dff581fc86d5
https://github.com/user-attachments/assets/96f048be-feb8-4ca1-a8d4-caccdc1ac915
https://github.com/user-attachments/assets/d276cc57-732d-42b6-9801-e21917b97428
https://github.com/user-attachments/assets/52294cab-007a-4e69-ab15-5e5b1f59fc30
* For #14558
Used …

Fix more onBackPressed() deprecations

---

AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt

I noticed that other apps had animation in their settings but AnkiDroid didn't. So I researched how to add animations
In the learning secion below
[transition.webm](https://github.com/user-attachments/assets/25380db6-9468-4fd1-a022-9d532932d298)
I initially thought that I had to create a custom animation with [setCustomAnimation](https://developer.android.com/reference/androidx/fragment/app/FragmentTransaction.html#setCustomAnimations(int,int)) so I created some animations and experimented with them and making reverse animations
After some time, I didn't manage to look like Android's default animations, so I researched more and found [setTransition](https://developer.android.com/reference/androidx/fragment/app/FragmentTransaction.html#setTransition(int)), which made things a lot simpler …

add transitions to preferences fragments

---

AnkiDroid/src/main/res/drawable/ic_double_arrow_down.xml
AnkiDroid/src/main/res/drawable/ic_double_arrow_up.xml
AnkiDroid/src/main/res/drawable/ic_fast_forward.xml
AnkiDroid/src/main/res/drawable/ic_lightbulb.xml
AnkiDroid/src/main/res/drawable/ic_lightbulb_stars.xml
AnkiDroid/src/main/res/xml/preferences_controls.xml

* Fixes most of #14243. The only pending icons are Show answer and the Answer button 1/2/3/4
Got the icons from [material icons](https://fonts.google.com/icons) and set them.
Some of them were already in the app resources
https://github.com/user-attachments/assets/d49a8423-a2ae-4017-8141-35b4dbbdc4fe

add controls icons

---

AnkiDroid/src/main/assets/scripts/ankidroid.js
AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerFragment.kt

I noticed that I didn't add this to the new reviewer in my earlier PR
* Fixes #17171
Did the same of #17235
https://github.com/user-attachments/assets/5637e3fc-c717-476d-b5e2-710a6ae16080

warn if user action is not set in new reviewer

---

AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt

* Fixes https://github.com/ankidroid/Anki-Android/pull/17584#discussion_r1878868490
Check if display mode is active
I enabled the setting then tested if the animation showed up and it didn't

disable fragment animation in safe display mode

---

.git-blame-ignore-revs

Follow-up from 
* #17581
* #17577
refs:
26df248a0cafad6ee1e5624b9ed86d8f17bf363c  
aff1bb87900f420ac5a717146d52c6df7b0d76b3  
5904c8a2119351c1e7d93dbd73ab88577a27ca30  
**manual**  
d7f67ad091b76f83ac5dce0939656fd43d729e40  
cd444112f5098baf9899cd6a1349c1c29c56783f  
f86bf55c4063e0804cc1336dc0b8a54a5cef8a5f

dev: ignore lint fixes in git blame

---

AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Note.kt
AnkiDroid/src/main/java/com/ichi2/libanki/backend/model/SortOrderUtil.kt
AnkiDroid/src/test/java/com/ichi2/anki/BackupManagerSimpleTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/ThrowableFilterServiceTest.kt

While touching code related to card's protobuf, I saw the use the code that is too verbose and decided to improve it

Clean protobuf related code

---

AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/FieldState.kt

Now Note Editor is a fragment, it no longer receives `android:viewHierarchyState`. This is now handled by the Activity
But, we did not need to handle this manually. Recreating the fields, with the same `id` value restores the text
Note: I could have done a lot more refactoring here, but since this is being cherry-picked, I wanted a minimal line change
* Fixes #17521
* Maybe #17476 (couldn't reproduce)
* Assign the Ids
* Don't clobber the Ids with new values
Samsung S21 with "Don't keep activities"
* Add Card
* Edit Card
* Change Card Type
This fix does not handle the loss of focus for dynamic elements
During testing, this lack of focus coming back from 'Drawing' was jarring. In Production this will have minimal impact as the user will have lost context by the time the activity is restored …

fix(note-editor): restore instance state

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTabOrderTest.kt
AnkiDroid/src/main/java/com/ichi2/anki/Info.kt
AnkiDroid/src/main/java/com/ichi2/anki/MetaDB.kt
AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Notetypes.kt
AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt
AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.kt

Specifically, the ones that represents json, sql or js. I found they used to be hard to read, and I expect to lower this issue.

NF: improve the readability of some strings

---

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt

fix onBackPressed  deprecation of CardTemplateEditor
* Fixes #14558
Physical Device

fix onBackPressed  deprecation of CardTemplateEditor

---

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Notetypes.kt
AnkiDroid/src/main/res/menu/card_template_editor.xml

* Fixes #16788
Implemented these methods
https://github.com/ankitects/anki/blob/3c20b49ccac4da63a85bf65b89af845d1f4851fb/pylib/anki/stdmodels.py#L23-L59
Then made the equivalent dialogs
[1.webm](https://github.com/user-attachments/assets/0baf861a-7ddd-4ac9-b9b6-0667248f6bc9)
[2.webm](https://github.com/user-attachments/assets/deddee1e-d0e7-4767-b8a4-b19e877564e1)

Add Restore to Default feature

---

AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt

In a58b4c10ed2f1db7dab9a3b7244cbf957b6915c7, `currentDeckId` was updated to use a Kotlin-based builder, but `[this.]did` was coming from `DeckIdKt.Dsl` rather than from `[this@Card.]did`, so 0 was returned.
* Cause #17591
* Fixes #17604 (Note Editor issues)
* Bisect the bad commit
* Figure out the issue
* Fix forward
API 34 emulator, editing a note now shows the correct deck
⚠️: I also made a mistake with the implementation, I don't particularly like the Dsl

fix: currentDeckId broken

---

pre-commit

I expect first commit to be sufficient. Commit three is probably overkill. But I don't want to lose hours of work anymore. And the slight risk that, if we stop overwritting the same file all the time, we save data seems quite nicer than risking a repeat.
Fixed: #17591

Improve pre commit hook

---

tools/release-description.md
tools/release-notes.md
tools/release.sh

Changes the order and file names in the releases page to push less used ABI variants lower down the fold, and made the description of the releases page better formatted.
* Fixes #15927 
Uses basic if checks to see weather or not to use the prefix or not.
N/A
Not much but did reference markdown formatting, and a bit about shell scripting.

Changed Release order and description of releases page

---

.github/ISSUE_TEMPLATE/bug_report_form.yml

This is part of the 'GitHub Issue Types' beta
**Implementation** 
https://redirect.github.com/orgs/community/discussions/139933#:~:text=Issue%20form%20with%20%60type%60%20field
**Announcement**
https://github.blog/changelog/2024-10-01-evolving-github-issues-public-beta/
**Before**
**After (expected)**
⚠️ Untested

dev(github): use 'Bug' type for new issues

---

.github/workflows/tests_emulator.yml
.github/workflows/tests_unit.yml

with the move to codecov action v5, upload tokens are either strictly required, *or* you have to have a public repository *and* go into your codecov settings on their website and allow uploads with no tokens
We allow uploads with no token on the main repository, but that was a specific setting change and there is no expectation that forks will do this, so uploads will fail for folks in the general case
We want the coverage fail signal on the main repo so I had set coverage upload failures to fail the build, but that's not a great experience for forks.
So now we only fail the build on coverage uploads if you are in the main repo
* Related #17443
* Build failures like https://github.com/mikehardy/Anki-Android/actions/runs/12394439234/job/34597894494#step:16:323
use workflow templating and …

test(coverage): only fail CI on main repo

---

api/build.gradle.kts
build.gradle.kts
gradle/libs.versions.toml

It doesn't appear that we actually *use* dokka anymore, remove the dependency
- Closes #17612 
Remove all references to dokka in our build files
We use jitpack.io to publish the API artifacts, and in our `jitpack.yml` we run `./gradlew :api:publishToMavenLocal`
https://github.com/ankidroid/Anki-Android/blob/ff607b3f4411e47f403f671861435ab29eca4327/jitpack.yml#L15
So I ran that then checked the javadoc artifact (attached) - it does generate (which is job number one) and it appears fine.
To be clear though, I'm not that interested in the output, it's mainly generated at all because some publishers (maven at least, jitpack unknown) require you to have a javadoc jar.
But we also publish the *actual sources* of the API module since we are open source, and most (all?) IDEs will auto-pull those …

build(deps): remove dokka, no longer in use

---

tools/release.sh

Fixes the naming conventions of files, and issue of file duplication
The hot mess caused by #17616 
Uses stricter pathing, and fixed the release line of each loop. 
N/A
The pain of dealing with workflows teaches oneself about patience, and avoiding the art of careless Ctrl+C, Ctrl+V and its consequences.

Hotfix for release.sh & stricter pathing

---

AnkiDroid/src/main/java/com/ichi2/anki/BackendExporting.kt
AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt
AnkiDroid/src/main/java/com/ichi2/libanki/BackendImportExport.kt
AnkiDroid/src/main/res/layout/dialog_export_options.xml

* Fixes #17536 
Adds a checkbox and uses the common string to interop with Anki Desktop
Did visual confirmation along with a screen recording of the changes and checked the sizes of the exports to confirm that legacy is being triggered properly.
[Screen_recording_20241218_215818.webm](https://github.com/user-attachments/assets/bed6730d-9a20-42c8-84bd-594bd0a3df9c)
Had to play around with the XML for a bit to get it to align, and other than that nothing much

feat(export): Added checkbox for colpkg and apkg exports to match Anki desktop

---

AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt
AnkiDroid/src/main/java/com/ichi2/utils/EditTextUtils.kt
AnkiDroid/src/main/res/values/02-strings.xml
AnkiDroid/src/main/res/values/03-dialogs.xml
AnkiDroid/src/main/res/values/sentence-case.xml
AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/dialogs/utils/AlertDialogUtils.kt
AnkiDroid/src/test/java/com/ichi2/anki/ui/internationalization/SentenceCaseTest.kt
AnkiDroid/src/test/java/com/ichi2/testutils/AndroidTest.kt
AnkiDroid/src/test/java/com/ichi2/utils/EditTextUtilsTest.kt

This removes some custom business logic, and instead uses the Anki Backend for the default values in Custom Study
It then goes to fix a bug: we could 'increase review limits' of a deck with no pending reviews
See commits
Unit tests fixed up & written

feat: use Backend for Custom Study Dialog & a few bugfixes

---

AnkiDroid/src/main/res/values/constants.xml

We'll move the manual away from ankidroid.org/index.html soon

fix: link to docs.ankidroid.org

---

build.gradle.kts
gradle/libs.versions.toml

Fixes a TODO and bumps `minSdk` to the correct version
After this, I noticed that some of the 'JDK' error was shown when it wasn't relevant
As this message is a common onboarding snag, I felt it was worthwhile to reduce the bulk of the error message
Especially as most new users won't be interested in such an involved change as their first issue

refactor: build.gradle.kts => use build.versions.toml & improve JVM error

---

AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt

* Fixes #17609 
Physical Device

fix: Navigate Up versus Close

---

AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerViewModel.kt
AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt
AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerViewModel.kt
AnkiDroid/src/main/java/com/ichi2/anki/previewer/TypeAnswer.kt
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/LanguageHintService.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerViewModel.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/autoadvance/AutoAdvance.kt
AnkiDroid/src/main/java/com/ichi2/anki/utils/ext/Fragment.kt
AnkiDroid/src/main/res/layout/fragment_audio_recording.xml
AnkiDroid/src/main/res/layout/fragment_audio_video.xml
AnkiDroid/src/main/res/layout/fragment_multimedia_image.xml
AnkiDroid/src/main/res/layout/previewer.xml
AnkiDroid/src/main/res/layout/reviewer2.xml
AnkiDroid/src/main/res/layout/template_previewer.xml
AnkiDroid/src/main/res/layout/template_previewer_container.xml
AnkiDroid/src/main/res/values/dimens.xml
AnkiDroid/src/main/res/values/styles.xml
AnkiDroid/src/test/java/com/ichi2/anki/previewer/PreviewerViewModelTest.kt

Implements type in the answer cards in the new reviewer natively. I don't know when/if I will implement the HTML version
* Fixes part of #14302 
In the commits
Emulator 34
https://github.com/user-attachments/assets/9cd18075-393b-440e-b927-536e9e9f9e6a
https://github.com/user-attachments/assets/d99ca820-740e-40a6-8d69-6b0ab8969f46
* InputMethodManager.restartInput can be used to restart the IME language hint immediately (it's on the javadoc of imeHintLocales)
* WindowInsetsControllerCompat can be used to reliably show the IME ([source](https://developer.android.com/develop/ui/views/touch-and-input/keyboard-input/visibility#ShowReliably))
I should learn more about Android MVVM and flow, specially to better handle configuration changes. Also, `ReviewerFragment` is getting big. Not sure if I …

feat(new reviewer): type in the answer (native)

---

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateBrowserAppearanceEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateNotetype.kt
AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.kt
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt
AnkiDroid/src/main/java/com/ichi2/ui/RtlCompliantActionProvider.kt

Reducing Android Studio warnings by cleaning up unused code and fixing initialization.
* Contributes towards #13282 ``[Cleanup]: Fix Android Studio Warnings``
- Made the unmountReceiver property private in `AppCompatPreferenceActivity.kt`.
- Removed the unused import **(import androidx.activity.addCallback)** in `CardTemplateBrowserAppearanceEditor.kt`.
- Removed the unused **property editedModelFileName** in `CardTemplateNotetype.kt`.
- Fixed the unresolved reference to **BuildConfig** in `CardTemplateNotetype.kt`.
- Made the **legacyAnkiDroidDirectory property** private in `CollectionHelper.kt`.
- Removed the unused **property fieldsAsBundleForPreview** in `NoteEditor.kt`.
- Fixed the initialization of `activity` in `RtlCompliantActionProvider.kt` **by assigning it immediately during …

[Cleanup]: Resolve Android Studio Warnings (#13282)

---

pre-commit

I forgot $ in the exit variable.
When `ktlin` failed this caused a strange error message in my log.

Pre commit hook typo correction

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/Import.kt
AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.kt
AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt
AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerImportTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/dialogs/AsyncDialogFragmentsTest.kt

Introduce enums in Dialog

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
api/src/main/java/com/ichi2/anki/FlashCardsContract.kt

In this case, I only renamed private values and local variables,as the content provider is used to provide content to external entities, its API should not be changed. I also added some documentation to explain why we have those old names.
We could consider duplicating "model" to "note type" in the entire API, and noting "model" as deprecated. But I really don't think that's it's worth deprecating anything. And if we don't plan to deprecate, I don't think it's worth having duplicate API either.

Rename model to note type in content provider

---

AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DebugInfoService.kt

And reduce the amount of vertical space used
We want this for e-ink identification:
* Issue #17618
This is the same fingerprint as used in https://github.com/koreader/android-luajit-launcher/blob/6bba3f4bb4da8073d0f4ea4f270828c8603aa54d/app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt#L134-L139
```diff
AnkiDroid Version = 2.21alpha4-debug (6ce39e2b9d6c64462986953f7f502be7e4c509c1)
-
Backend Version = 0.1.48-anki24.11 (24.11 c47638ca36f99dd4f3b81ae82d964aec66e392e0)
-
Android Version = 14 (SDK 34)
-
ProductFlavor = full
-
+ Device Info = samsung | samsung | o1s | o1sxeea | SM-G991B | exynos2100
- Manufacturer = samsung
-
- Model = SM-G991B
-
- Hardware = exynos2100
-
Webview User Agent = Mozilla/5.0 (Linux; Android 14; SM-G991B Build/UP1A.231005.007; wv) AppleWebKit/537.36 …
```

feat(debug-info): log more device info & reduce vertical space used

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/autoadvance/AutoAdvance.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt

The function was only used with `currentDeckId().did`. So no need to add `did` to a protobuf structure.

NF: Simplify `currentDeckId`

---

AnkiDroid/build.gradle
AnkiDroid/jacoco.gradle
build.gradle.kts

To ensure that GitHub Actions runs ./gradlew :testlib:assemblePlayDebugAndroidTest at some point to ensure that testlib compiles
* Fixes #17520 
By adding a dependency on this task from AnkiDroid's androidTest in build.gradle
By building it locally on my PC.

Fixes #Issue-17520   Ensures testlib is built

---

.idea/dictionaries/anki.xml
AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateBrowserAppearanceEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateNotetype.kt
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
AnkiDroid/src/main/java/com/ichi2/libanki/CardTemplate.kt
AnkiDroid/src/main/java/com/ichi2/libanki/CardTemplates.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Field.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Note.kt
AnkiDroid/src/main/java/com/ichi2/libanki/NotetypeJson.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Notetypes.kt
AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt
AnkiDroid/src/main/java/com/ichi2/utils/JSONContainer.kt
AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/CardTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/CollectionTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/FieldTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/SchedulerTest.kt
AnkiDroid/src/test/java/com/ichi2/testutils/TestClass.kt
AnkiDroid/src/test/java/com/ichi2/utils/NoteTypeTest.kt

It felt like https://github.com/ankidroid/Anki-Android/pull/17649 was well received, and I have capacity for a small mechanical change
* https://github.com/ankidroid/Anki-Android/pull/17649
* Generate `CardTemplates` and define collection accessors
* Generate `CardTemplate` and define accessors
* Update `NotetypeJson.tmpls` and fix breakages
* Update all uses of `getJsonObject("tmpls")`
Unit tested only
* I explained `NotetypeJson.req`
* 🐞 value classes do not have the same string representation as their wrapped class
* I don't particularly like what the new linter did to my `apply` calls in the tests
* I forgot about `bfont` and `bsize` properties

refactor(libanki): extract & document 'CardTemplate[s]'

---

AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
AnkiDroid/src/main/java/com/ichi2/imagecropper/ImageCropper.kt
AnkiDroid/src/main/res/layout/fragment_image_cropper.xml
AnkiDroid/src/main/res/values/16-multimedia-editor.xml

Adds minor refactorings to improve the image cropping fragment and at the end removes the dependency on AnkiFragment. Did a bunch of smaller commits so it's easier to review, I'll squash when it's time to merge.
Before and after:
Ran the tests and manually tested the screen.

Refactor image cropping fragment and remove dependency on AnkiFragment

---

AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt
AnkiDroid/src/test/java/com/ichi2/anki/export/ExportDialogFragmentTest.kt

Added unit test to check the visibility and default checked status for the Apkg and Collection exports
* Added tests for initializeApkgExportUi() and initializeCollectionExportUi() both tagged with @NeedsTest("Checkbox is only available on two selections "), and @NeedsTest("Checkbox defaults to false").
* Launching a fragment with the configs for each
* Using Espresso to do UI testing
Ran the unit tests multiple times to avoid flaky tests
* How to create fragment tests with AnkiFragmentScenario which extends on AndroidX testing lib.
* How to use Espresso.

Unit Tests for initializeApkgExportUi and initializeNotesExportUi

---

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateNotetype.kt
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/services/ReminderService.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Config.kt
AnkiDroid/src/main/java/com/ichi2/utils/JSONObject.kt
AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateNotetypeTest.kt

Some of them could be replaced by more specific type, or just the type could be inferred from context

NF: Remove some `JSONObject`

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/InstrumentedTest.kt
AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Note.kt
AnkiDroid/src/main/java/com/ichi2/libanki/NotetypeJson.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Notetypes.kt
AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt
AnkiDroid/src/test/java/com/ichi2/anki/AnkiDroidJsAPITest.kt
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/browser/CardBrowserViewModelTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/SchedulerTest.kt
AnkiDroid/src/test/java/com/ichi2/testutils/TestClass.kt
AnkiDroid/src/test/java/com/ichi2/testutils/libanki/CollectionAssert.kt

This PR should be merged after #17430. It contains #17430 and removing #17430 would create a ton of merge conflict.
It transforms IntDef of Consts.kt into enum
* https://github.com/ankidroid/Anki-Android/labels/Blocked%20by%20dependency https://github.com/ankidroid/Anki-Android/pull/17430

refactor(libanki): convert Consts to enums

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt

Keyboard is not opening on adding tags (TagsDialog).
Set `displayKeyboard` to true
Physical device (OPPO F21 Pro 5G).
https://github.com/user-attachments/assets/eedb754a-be65-402e-9a5e-49a3a8b49e37

fix:focus keyboard

---

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/scheduling/SetDueDateDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/scheduling/SetDueDateViewModel.kt
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DebugInfoService.kt
AnkiDroid/src/main/java/com/ichi2/utils/BundleUtils.kt
AnkiDroid/src/test/java/com/ichi2/anki/scheduling/SetDueDateDialogTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/scheduling/SetDueDateViewModelTest.kt
AnkiDroid/src/test/java/com/ichi2/utils/BundleUtilsTest.kt
testlib/src/main/java/com/ichi2/testutils/common/AnkiAssert.kt

I wanted to simplify the dialog, especially explaining what "set interval to same value" due to user feedback.
But, it didn't make sense to me for FSRS.
After a sufficiently long discussion with Expertium & Jarrett, we discovered:
* Expertium previously wasn't aware of the `!` option
* This was raised as an issue previously: https://forums.ankiweb.net/t/set-due-date-doesnt-update-the-interval-of-card/52646
* Fixes #17707
When FSRS is enabled, there is no reason for due date to be inconsistent with interval
So, hide 'set interval to same value' and use `true`
Confirmed by Jarrett and Expertium, paraphrased:
> Expertium: when FSRS is enabled, is there any reason for keeping `ivl` not consistent with due date? Because I'm pretty sure there isn't
> Jarrett: Yeah, there isn’t. …

improvement(set-due-date): simplify for FSRS by removing "set interval to same value"

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt

Dont open the webview in case no network is detected and show a snackbar instead
Locally API 35

feat: show snackbar if no data connection in shared deck download

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt

* Fixes #17714
* Search for Reviewer::class.java uses
* Replace most of them (the only one left defaults to the new reviewer as well)
* Open the study options screen
* Tap study
* The new reviewer shows up (before this fix, the old reviewer was shown)

fix: study options opening old reviewer

---

AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt

As requested by David in a recent PR adding enum in consts. I looked for all obejcts in sealed class/interface. I didn't touch object, even if named, that are not part of a sealed class/interface, as it's not clear that it's a big deal if `toString` does not show their name.

NF: transform object to data object

---

AnkiDroid/src/main/res/drawable/ic_done_white.xml

I found it hard to find, so added some greppable strings
It also was not tintable, which made it invisible in any Material3 dialogs using it
**Testing: unchanged**
**Testing: now working**

fix: allow tinting 'tick' icon

---

AnkiDroid/src/main/res/drawable/ic_flag_transparent.xml

**Description**
1. The `SrokeWidth` of default flag has been increased to `1.6` to match other material icons.
2. The `pathData` of the flag has been changed to make pole wider.
- Type of change: Bug fix (non-breaking change which fixes an issue)
* Fixes #16252 
**Approach**
The following parameters have been changed in the `ic_flag_transparent.xml` file.
1. `pathData="M14.4,6L14,4H5v17h3v-7h5.6l0.4,2h7V6z`
2. `strokeWidth="1.6"`
**How Has This Been Tested?**
**Before:**
**After:**
**Before:**
**After:**

fix: Thickness of Default Flag icon has been increased to match other material icons

---

AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt

In new reviewer, zoom should reset on card flip
* Fixes #17706
The solution is to toggle the `loadWithOverviewMode ` setting off and then back on. This forces the WebView to loads its content and apply the correct scaling.
Physical device (OPPO F21 Pro 5G).
https://github.com/user-attachments/assets/3dcff8ad-8083-4ed4-858e-7e7392acbd06
https://stackoverflow.com/a/61627280/22445612

Reset zoom on card flip in ReviewerFragment

---

AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerViewModel.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Note.kt

* Fixes #17693
libanki's ephemeralCard() method always used the default deck id (the desktop version has the same issue).
That leads to using the default deck config for the template previews.
This fixes the issue by adding an optional deckId argument
1. Add a new deck type
2. Set `Don't play audios automatically` of the new deck type to true
3. Set `Don't play audios automatically` of the `Default` to false
4. Assign the new deck type to a card with audio
5. Open the card

fix: audio autoplay in template previewer

---

AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardMediaPlayer.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/reviewer/ViewerAction.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerViewModel.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/autoadvance/AutoAdvance.kt
AnkiDroid/src/main/res/values/ids.xml

it also changes the behavior to match the desktop code, so auto advance only starts after the user toggles it
* Fixes part of #17701
[Nothing.webm](https://github.com/user-attachments/assets/9f66b666-08a7-4354-9bc6-8bfea26aa0e6)
[more.webm](https://github.com/user-attachments/assets/7d1370de-09ec-4429-b21c-d90d26c77bcc)

feat: toggle auto advance in new reviewer

---

AnkiDroid/src/main/java/com/ichi2/anki/browser/BrowserMultiColumnAdapter.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/FlagAdapter.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsArrayAdapter.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/reviewer/ReviewerMenuSettingsAdapter.kt
AnkiDroid/src/main/java/com/ichi2/anki/utils/ext/RecyclerView.kt
AnkiDroid/src/main/java/com/ichi2/ui/ButtonItemAdapter.kt
AnkiDroid/src/main/java/com/ichi2/widget/WidgetConfigScreenAdapter.kt
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt

Working through the browser column selection feature, the verbosity felt needless here, and led to line wrapping
API 34 emulator - primarily 'My Searches', which used the `ButtonItemAdapter`

refactor: reduce verbosity of 'findViewById'

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/SingleFragmentActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialogFactory.kt
AnkiDroid/src/main/java/com/ichi2/anki/pages/CongratsPage.kt
AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.kt

Replace `CustomStudyListener` with the `FragmentResultApi` to improve fragment communication.
* Fixes #17665
Replaces the `CustomStudyListener` functions with `setFragmentResult` to pass `CustomStudyAction` inside a bundle. The result is then listened inside `DeckPicker` using `supportFragmentManager.setFragmentResultListener`.
Tested on Android 12

Replaced CustomStudyListener with FragmentResultApi in CustomStudyDialog

---

AnkiDroid/src/main/java/com/ichi2/anki/browser/BrowserMultiColumnAdapter.kt
common/src/main/java/com/ichi2/anki/utils/android/ColorUtils.kt

We had an assertion that the `pressed color != color`, and this failed if the color was black
In this case, we lighten the color by 25%
* Fixes #17731
As above

fix(card-browser): crashed in Dark Mode

---

AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/utils/Layout.kt
AnkiDroid/src/main/res/layout/reviewer2.xml
AnkiDroid/src/main/res/values/10-preferences.xml
AnkiDroid/src/main/res/values/constants.xml
AnkiDroid/src/main/res/values/preferences.xml
AnkiDroid/src/main/res/xml/preferences_reviewer.xml

Anki's Webview frame is a rectangle stretched to the window borders, while the new reviewer has a nice `Card` like frame, which is more aesthetical.
Given that many card templates were created based on Anki's default frame, the `Card` style may not suit them well (e.g. by using a card template on the card frame, so the style ends up duplicated).
So, this PR gives an option to switch to the old frame, used by Anki and the old reviewer.
<details><summary>Screenshots</summary>
</details>

feat(new reviewer): box frame style

---

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt

For some reason, the flag menu items used their code/order as ID before (that may lead to conflicts, so it isn't a good practice).
After 1a96697e6391647c0aecfc1b472400b00b846f32 they use proper IDs, but those IDs weren't handled at onOptionsItemSelected
* Fixes #17748
Issue reproduction steps

fix: flag not being set in old reviewer

---

AnkiDroid/src/main/res/values/01-core.xml

After https://github.com/ankidroid/Anki-Android/pull/16566, the string `studyoptions_congrats_finished` is used only when there are no cards due later in the day. The previous wording was "You have finished for now." This might suggest that some cards may be due later in the day (it was indeed supposed to imply that before the above-mentioned PR). The changed text makes the meaning clearer.
* Fixes None
Not tested

Improve congrats message when no cards due later in day

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/res/drawable/browser_divider.xml
AnkiDroid/src/main/res/layout/card_browser.xml
AnkiDroid/src/main/res/values/theme_light.xml
AnkiDroid/src/main/res/values/theme_plain.xml

* Fixes #17751
Use `DividerItemDecoration`
API 34 emulator

fix(browse): fix regression showing borders

---

AnkiDroid/src/main/res/values/02-strings.xml

improvement(browser-options): fix casing of title

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/deckpicker/DeckPickerViewModel.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt
AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CreateDeckDialogTest.kt

We want more ViewModels in 2025. Let it start
* Extract launchCollectionInLifecycleScope
* Document `remove`
* Create class
* Bring method across
Deleted a deck in the UI of an API 34 emulator via context menu

improvement: introduce DeckPickerViewModel

---

AnkiDroid/src/main/res/layout/reviewer2.xml

Fixes the issue where answer buttons in the new reviewer UI were being clipped when large font sizes were applied. The fix ensures the buttons resize dynamically to accommodate larger text
* Fixes https://github.com/ankidroid/Anki-Android/issues/17734
Changed the ``FrameLayout`` containing the answer buttons in the new reviewer UI to ``android:layout_height="wrap_content"`` to prevent vertical clipping when large font sizes are applied.
The issue was tested by increasing the system font size and verifying that the answer buttons in the new reviewer UI resize properly without clipping.  Physical Device (Samsung Galaxy A6+)
Video:
https://github.com/user-attachments/assets/d7807e84-849f-427c-aa56-89911e5d46a7

Fix: button resizing issue for large font sizes in new reviewer UI

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt

Refactors the code for DeckAdapter to improve it and fix a kotlin cleanup + rust cleanup. More info on the commits messages. If the last commit seem too bold I can remove it.
Ran the tests, manually verified the decks screen.

Improve decks adapter code

---

AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerViewModel.kt
AnkiDroid/src/main/res/layout/reviewer2.xml

* Fixes #17734
1. Fix an issue with #17777, that leads to the `Show answer` being smaller than the answer buttons (it can be seen in the PR video)
2. Implement the `Answer buttons size` feature of the old reviewer
<details><summary>Consistent height</summary>
</details>
<details><summary>Answer buttons size</summary>
</details>

feat(new reviewer): answer buttons height setting

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt

For performance, this does not match upstream:
https://github.com/ankitects/anki/blob/1fb1cbbf85c48a54c05cb4442b1b424a529cac60/pylib/anki/collection.py#L869-L881
* Fixes some TODOS completed in #16620
Refactoring broken out of a 'many column support' PR

improvement(collection): implement browserRowForId

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/InstrumentedTest.kt
AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/MediaTest.kt
AnkiDroid/src/androidTest/java/com/ichi2/anki/testutil/CollectionUtils.kt
AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/AbstractSchedTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/CardTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/CollectionTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/FlagTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/SchedulerTest.kt
AnkiDroid/src/test/java/com/ichi2/testutils/TestClass.kt
AnkiDroid/src/test/java/com/ichi2/testutils/ext/Collection.kt

Fixed a RustCleanup
The method is moved to tests, and duplicated between `androidTest` and `test`

refactor(collection): addNote

---

AnkiDroid/build.gradle
gradle/libs.versions.toml

We discovered, much to our surprise, that with the split ABIs we've been running for years the Play Store does not automatically retain old builds from previous minSdk changes
* Fixes #17791 
Investigated manual changes to retain builds on the play store, and re-released a build from release-2.19 (2.19.4) to investigate what was possible
Investigated our auto-publisher for Play Store and discovered they have a `retain` feature that should work - using that here
It isn't possible to test this manually other than seeing on Play Store that it is possible to retain old builds manually (it is!)
The test here will be to build a new alpha post-merge and see what APKs were included in it
Just learned how incredibly long a latent bug can exist before noticing - these old minSdk versions have been …

release: retain old minSdk artifacts when publishing new releases

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
AnkiDroid/src/main/res/values/03-dialogs.xml
AnkiDroid/src/test/java/com/ichi2/anki/browser/CardBrowserViewModelTest.kt
AnkiDroid/src/test/java/com/ichi2/testutils/TestClass.kt

Requested a long time ago in https://github.com/ankidroid/Anki-Android/issues/9458
* Fixes part of https://github.com/ankidroid/Anki-Android/issues/9458
* Use query from Anki Desktop

feat(reposition): show queue top & bottom

---

AnkiDroid/build.gradle

auto-naming doesn't work if you have APKs in a release with different versions, as we do with our new retain settings for older minSdk support
* Fixes #17800 
RTFM on the Triple-T publish, auto-complete in Android Studio to get the variable
Can't test it other than to make sure builds still work local and CI so I don't break anything
Real test is when we do 2.21alpha7 to see if the release name is meaningful vs 2025-01-17 or whatever date we build it
There are always follow-on effects for any positive change. Yaks to be shaved. Progress to be made, slowly.

release: set release name explicitly

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/res/layout/deck_picker.xml
AnkiDroid/src/main/res/layout/floating_add_button.xml

The purpose of this change is to allow the footer of the deck picker to display multiple lines of text.
* Part of #17100
* Maybe a fix for https://github.com/ankidroid/Anki-Android/issues/14641
The `setSingleLine` method has been removed from the `DeckPicker.kt` file to allow the footer text to display across multiple lines. Additionally, a `.replace` function was implemented to ensure that newline characters in the text from `sched.studiedToday()` are replaced with spaces, preventing any text from being hidden.
This change has been tested using different font sizes and languages.

Fix: Enable multi-line support for the deck picker footer

---

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt

Leech toasts have switched messages with each other
* Fixes #17806
Replace strings for leech toasts with each other
Checked on physical device (Android 11)
↓
-----
↓
https://github.com/user-attachments/assets/daaf0569-c3fd-42c6-9fe9-cd43573fb18e

fix: Leech toasts have switched with each other

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt
AnkiDroid/src/main/java/com/ichi2/libanki/DB.kt
AnkiDroid/src/test/java/com/ichi2/anki/browser/CardBrowserViewModelTest.kt

Fixes a few IDE lint warnings (`.isEmpty()` needed a [Mutable]Map, rather than a HashMap)
I did a very quick test of the saved searched functionality, and trusting CI for the rest

refactor(browse): lint

---

AnkiDroid/src/main/java/com/ichi2/anki/pages/DeckOptions.kt
AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt

* Fixes #16642
* move to a UI backend method
* Fix a bug in percentage calculation
* Use the same progress extraction method as `updateDeckConfigsRaw`
<details>
<summary>old</summary>
</details>

feat(deck-options): progress dialog for Optimize

---

AnkiDroid/src/main/res/layout/browser_options_dialog.xml

Previously, tapping to the right of a checkbox/radio button did not toggle it

fix(browse-options): better touch targets

---

AnkiDroid/jacoco.gradle

if you do the task registration "bare" without assigning to a variable, Android Studio will recognize your tasks as run targets for UI usage
Nothing logged, was question from Arthur in Discord
refactoring post-definition configuration into the task definition itself, so no local variable is needed and it's just a "bare" task creation
We have the play icon next to the targets now:
Meh, IDEs are weird. Should have recognized the task registration without this change

test: fix studio task recognition for jacoco test tasks

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt

Non-functional keyboard shortcuts were removed from the list in the deck picker when the screen is not fragmented.
* Fixes #17634
Modified the shortcuts list to conditionally include the "DEL", "Shift+DEL", and "R" shortcuts based on the `fragmented` flag. These shortcuts are only included if `fragmented `is true, while others remain unchanged.
Chromebook

Fix Keyboard Shortcuts Behavior in Deck Picker (Fragmented)

---

AnkiDroid/src/main/res/layout/my_account_logged_in.xml

On Landscape the images look weird and text truncate issue
`solved the problem
<h3>AnkiWeb account</h3>
previous problem 
Solved 
Added Scroll view in landscape mode also modified layouts and text distorted part 
* Fixes #17312
As you can see the above screenshots I have added scroll view layouts also modified some part of code so that on landscape it looks better and scrollable
It is tested both by emulator with 34 level and hardware in realme 6 Android 11
- [yes ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ yes] You have commented …

my_account_logged_in.xml weird landscape text truncate

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/deckpicker/DeckPickerViewModel.kt
AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt
AnkiDroid/src/test/java/com/ichi2/anki/deckpicker/DeckPickerViewModelTest.kt

* Part of the ViewModel move
S21: emptying a deck and testing undo, deck counts are updated on both
+ unit tests
* https://github.com/ankidroid/Anki-Android/issues/17832

feat(deck-picker): make "empty filtered deck" undoable

---

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt

Whiteboard editor icon is dark gray on App bar
N/A
- Use `ContextCompat` instead of `VectorDrawableCompat` (as in `whiteboardIcon` and `stylusIcon`)
https://github.com/ankidroid/Anki-Android/blob/cbebed62b90d3bc4079dbf4b807bd957a17ad61c/AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt#L819-L820
- Use `applicationContext`, as in `whiteboardIcon`, and as the approach in #15894
Checked in physical device (Android 11)
Before | After
--- | --- 
-- | ![image](https://github.com/user-attachments/assets/94c36795-f876-4009-89ea-4af4364734e7) (No adverse effects in the icon in the menu)
-- | ![image](https://github.com/user-attachments/assets/c706c3ee-0e59-4b02-8d4a-66cc93ddb5d6) (No adverse effects in Settings screen)
-- | ![image](https://github.com/user-attachments/assets/0443e700-b814-4e59-9cf …

fix: whiteboard editor icon is glay on App bar

---

AnkiDroid/src/test/java/com/ichi2/anki/browser/CardBrowserViewModelTest.kt
AnkiDroid/src/test/java/com/ichi2/testutils/TestClass.kt

Fixed in 3ea835e21d96b3ad7f681995b6cffc2e3f775b1c
* Issue #17367
----
Realized this was a ViewModel test which I'd missed.

test(card-browser): handle language changes

---

tools/release-description.md

When I looked at the page, `Assets` was collapsed and had the same section styles as the other h2s so it was hard to distinguish what "Install `arm64-v8a`" meant
Note: Please close this PR immediately on any disagreements, this is a very quick 'nice to have'

improvement(release): clarify files are under 'Assets'

---

AnkiDroid/src/main/AndroidManifest.xml
AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportFileSelectionFragment.kt
AnkiDroid/src/test/java/com/ichi2/anki/IntentHandlerTest.kt

CSV files from Gmail on my S21 (Android 14) are `text/csv`
`text/tsv` is also used when coming from Gmail
* Fixes #17866 (maybe)
* handle `text/csv`
* handle `text/tsv`
S21 on Android 14: I can see the Android Dev Build as an import option a few more times for CSVs

fix(import): import CSV/TSV files

---

AnkiDroid/src/main/java/com/ichi2/imagecropper/ImageCropper.kt

Fixes PNG to JPG conversion issue during image cropping, preserving the original format (PNG) for transparency and quality retention. Ensures the cropping process doesn't alter the image format unintentionally.
* #17817
This change checks the original image format (PNG) before cropping and preserves it during the process. It ensures that PNG images are cropped without being converted to JPG, maintaining transparency and quality.
Samsung F23 5G 

fix: prevent PNG to JPG conversion on image crop

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt

Blocked on 
* #17835 
Fixes two bugs related to custom study by tags:
- an IllegalStateException due to sending fragment results after the dialog was dimissed
- custom study by tags not actually working after a previous change around this code
Built on top of #17835 the last two commits are the fixes. This should go in before releasing as custom study by tags doesn't work otherwise. More info in the commits messages.
Ran the tests, manually checked custom study by tags.

Fix two bugs related to custom study by tags

---

AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt

This test disabled in CI but failed for me every time locally
It worked until the only other user of the test required a change that broke this one - git bisect indicates it was in commit:
56ec7096262ec5d5f2c53499b24ea002bdc84013
There was no real reason I could see that the test I modified need a card specifically due today though? So the change seems reasonable, and it definitely fixes it for me in local testing
> ./gradlew :AnkiDroid:testPlayDebug --tests "*testLrnQueueAfterUndo*"
I learned how to drive git bisect slightly better

fix: reviewer test fix for local failures

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/deckpicker/DeckPickerViewModel.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/EmptyCardsDialogFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/EmptyCardsViewModel.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
AnkiDroid/src/main/res/layout/dialog_empty_cards.xml
AnkiDroid/src/main/res/values/sentence-case.xml
AnkiDroid/src/test/java/com/ichi2/anki/deckpicker/DeckPickerViewModelTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/ui/internationalization/SentenceCaseTest.kt

> Hey all, I found a possible improvement to avoid some data loss as of 2.20.0.
>
> In Anki desktop, the Empty Cards feature asks if it should not only delete cards that are empty, but also associated notes that would remain without any valid cards.
>
> On AnkiDroid, this is on by default. Notes with no valid cards get deleted when I press the Empty Cards.
> 
> I noticed because I made blank placeholder notes that I wanted to later fill in with questions & answers.
>
> It'd be nice if the mobile version also asked first
* Issue #17213
* Extract to a DialogFragment
* Implement the feature using a custom layout and a checkbox
* Fixup the dialog a bit (Material theme + fix title)
Unit tested, somewhat
* A custom view is needed if you want a message AND checkboxes

feat(empty-cards): Add 'keep notes' checkbox

---

AnkiDroid/src/main/java/com/ichi2/anki/model/CardsOrNotes.kt

Implement Parcelable for the CardsOrNotes enum to ensure compatibility with getParcelable() on API <= 33, where the method validates if the class implements Parcelable.
- Fixes #17881
Used the `@Parcelize` annotation to implement the Parcelable interface for the CardsOrNotes enum. This ensures the enum is recognized as Parcelable on API < =33 when getParcelable() is called, addressing compatibility issues without requiring manual implementation of Parcelable methods.
```
AnkiDroid Version = 2.21alpha9-debug (85f96484cf03c287508b6b5d92285dfd583d2107)
Backend Version = 0.1.48-anki24.11 (24.11 c47638ca36f99dd4f3b81ae82d964aec66e392e0)
Android Version = 13 (SDK 33)
ProductFlavor = amazon
Device Info = Google | google | emu64x | sdk_gphone64_x86_64 | sdk_gphone64_x86_64 | ranchu
Webview User …
```

Implemented `CardsOrNotes` as `Parcelable`.

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt

Fix a crash on FAB margin adjustment for multi-line "review summary" adjustment, that surfaced when the layout of the FAB changed slightly
* Fixes #17882
The original FAB multi-line adjustment code only ran sometimes. It can run all the time though, with no harm.
Running all the time means that problems with the adjustment will show up immediately in the future instead of remaining latent unless specifically triggered.
That allowed for easy reproduction of the issue, even if you only review one card in a test deck in English, which would never trigger the issue otherwise.
The fix then is to cast to the widest type possible that has the needed Margins methods so that layout changes are less touchy as they may return different `MarginLayoutParams` sub-types, but they are all …

fix: FAB multi-line layout margin adjust always cast to super-type

---

AnkiDroid/src/main/java/com/ichi2/anki/SingleFragmentActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/pages/PageChromeClient.kt

The changes required for https://github.com/ankidroid/Anki-Android/issues/17845 will need to be squashed so we do not break the code when we bump the backend
This is the first of a series of 3 pull requests:
* **we are here** refactors which can go in before the backend bump
* bump the backend and fix Deck Options
* use the new backend functionality to fix Deck Options loading
The purpose of logs is to make debugging deck options easier
The fragment will be accessed in a later commit
* Start of #17845
The final commit of the series works, manually on my S21

refactors: logging/fragments: prep for Anki 25.01

---

AnkiDroid/src/main/AndroidManifest.xml
AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt

This PR adds the necessary intent-filter configuration to the AndroidManifest.xml to enable AnkiDroid to handle .txt files shared from the file manager for import
* Fixes #17873
Added intent-filter for text/plain MIME type to support .txt file sharing and import
Physical Device (Redmi Note 13)
https://github.com/user-attachments/assets/aa18f9f4-a20d-4329-b332-928442642e3c

Fix: Enable sharing .txt files for import in AnkiDroid

---

AnkiDroid/src/main/java/com/ichi2/anki/utils/AndroidUtils.kt
AnkiDroid/src/main/java/com/ichi2/compat/customtabs/CustomTabActivityHelper.kt

In both the shared decks screen and the account login the user could trigger an ACTION_VIEW(ex. mailto link) which went through our custom tabs implementation which finally tried to start and activity(and failed if no app to handle it was present). 
Example bug report: https://ankidroid.org/acra/app/1/bug/280476/report/003eb5ab-bb37-484a-a3f7-0ec9bda1767c
Example stacktrace:
```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://ankiweb.net/... pkg=com.power.browser (has extras) }
at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2100)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1747)
at android.app.Activity.startActivityForResult(Activity.java:5473)
at …
```

Fix more ActivityNotFoundExceptions

---

AnkiDroid/src/main/java/com/ichi2/anki/pages/DeckOptions.kt

Currently, if you try to close the Deck Options before it's loaded, the request `anki.deckOptionsPendingChanges()` can't be executed and the deck options remain open.
With this change, the deck options is automatically closed. Indeed, if the webview is not loaded, there was no change to save.
This is similar to Anki's implementation.
Thanks David for fixing most of the actual issue

DeckOption become closable if it's not loaded

---

AnkiDroid/src/main/res/values/02-strings.xml
AnkiDroid/src/main/res/xml/preferences_custom_buttons.xml

Fix discrepancy in the labels for "Whiteboard editor" option
* N/A
- Use the same string with Reviewer, in App bar settings page
- Remove the unused string, `Whiteboard pen color`
Checked in physical device (Android 11)
https://github.com/user-attachments/assets/9fea3794-50e8-4d58-9f43-02e59864dab3

fix: use consistent label for Whiteboard editor in "App bar buttons" page

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/FlagAdapter.kt

Fixes the issue where a flag could be renamed to an empty value in the Card Browser. Now, empty flag names are not allowed.
* Fixes #17854
If user tries to save empty flag name then set it back to the default name which was used.
Physical device (OPPO F21 Pro 5G)
https://github.com/user-attachments/assets/96e85978-83e1-422d-864e-25b2d6c60e5c

Don't allow empty name in flag

---

AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.kt
AnkiDroid/src/main/java/com/ichi2/utils/DisplayUtils.kt

Replaced deprecated methods Display.getMetrics() and Display.getSize(Point) with WindowManager.getCurrentWindowMetrics().getBounds() for Android R (API 30+) to obtain screen dimensions. Additionally, used Configuration.densityDpi for retrieving screen density. For backward compatibility, retained the use of Display.getMetrics() and Display.getSize(Point) on older Android versions
* Fixes #9333
The changes were tested using Logcat by logging the values obtained from WindowMetrics.getBounds() and comparing them with the values from Display.getSize(Point) and Display.getMetrics(). The results were consistent across devices running Android 30+ and older versions.
- getmetrix() 
- getSize()
1st log is of getSize() used by UsageAnalitics
2nd , 3rd log is of getSize() used by whiteboard …

Fix getsize() and getMetrics deprecations

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt

Fixes the missing auto-scroll functionality when switching to multi-select mode in RecyclerView, ensuring a smoother user experience.
* Fixes #17747
This change adds the missing auto-scroll functionality, ensuring that the RecyclerView scrolls smoothly when entering multi-select mode, improving usability.
Samsung F23 5G
https://github.com/user-attachments/assets/9b2dc926-2fbc-4a4c-b4df-7c44a461fc6f

Add Auto-Scroll Support for RecyclerView in Multiselect View

---

AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
AnkiDroid/src/main/res/values/17-model-manager.xml

Anki prefill the current position of the field and allow user to update it if they want to, this PR makes the dialog consistent with Anki reposition dialog 
Current UI:
Google emulator API 31
New UI:
I found this out when I was trying to reproduce some other bug, so just pushing this simple improvement 

enhancement: improve reposition field dialog

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/EmptyCardsDialogFragment.kt
AnkiDroid/src/main/res/layout/dialog_empty_cards.xml
AnkiDroid/src/main/res/values/03-dialogs.xml

Adds the required changes to make the empty cards dialog show the same report that desktop does about empty cards. Also makes the relevant ids clickable to open the card browser with a query on that id for easy access. Also shows a notice text when there are no empty cards. 
Note: I had serious issues in making the WebView with the report appearing properly between configurations.
Some images:
phone-portrait/phone-empty
phone-landscape
tablet
* Fixes #17213
Ran the tests and opened the dialog in various configurations.

Enable full report about empty cards

---

AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt

The note editor mode from view model was not used instead a var from the activity class was used, this PR handles the editor mode via ViewModel and sets the views
Use mode from view model only
before:
[Screen_recording_20250208_032036.webm](https://github.com/user-attachments/assets/0775dd01-9695-4f25-9938-b05f115b94c8)
after:
[Screen_recording_20250208_031955.webm](https://github.com/user-attachments/assets/cfddf08b-60b1-4fd2-82df-e18d82e902d6)

fix: instant note editor tap mode inconsistency

---

AnkiDroid/src/main/java/com/ichi2/anki/preferences/ReviewerOptionsFragment.kt

`Ignore display cutout` is only useful if `Hide system bars` is set to something other than `None`
Emulator 35
https://github.com/user-attachments/assets/8974a546-7b09-42a6-b239-70049b3cd342

fix(settings): disable ignoreDisplayCutout when necessary

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorIntentTest.kt
AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTest.kt
AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionIntentBuilder.kt
AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler2.kt
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/NoteEditorLauncher.kt
AnkiDroid/src/main/java/com/ichi2/anki/pages/CardInfoDestination.kt
AnkiDroid/src/main/java/com/ichi2/anki/pages/CongratsPage.kt
AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/utils/Destination.kt
AnkiDroid/src/main/java/com/ichi2/widget/AddNoteWidget.kt
AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt

it can be used to something like a `Destination` flow
It's part of a refactor in the new reviewer to get keybinds working
I haven't. This should be non-functional

refactor: add `Destination` interface

---

AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt

The instant note editor re-init the view model cloze text to the raw text in case of orientation change and we want to avoid it and populate the fields/chips with the original text, hence save and restore the cloze text in case its changed
Use `savedInstanceState`
Before: 
[Screen_recording_20250208_021505.webm](https://github.com/user-attachments/assets/40b28204-30fb-4ceb-8d49-53617c2124ed)
After: 
[Screen_recording_20250208_021425.webm](https://github.com/user-attachments/assets/32829c70-ce7c-4dca-960e-2f6f41d74ea3)

fix: instant note editor to restore text when orientation changes

---

AnkiDroid/proguard-rules.pro

.utils.ext.MenuItemImpl methods use reflection, and proguard obfuscated the names in `release` builds.
* Fixes #17950 
Build a `release` build, then do the issue reproduction steps

fix(new reviewer): suspend/bury submenus

---

AnkiDroid/src/main/java/com/ichi2/anki/preferences/reviewer/ReviewerMenuView.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt
AnkiDroid/src/main/res/layout-sw600dp/reviewer2.xml
AnkiDroid/src/main/res/layout/reviewer_menu_view.xml
AnkiDroid/src/main/res/values-sw600dp/dimens.xml
AnkiDroid/src/main/res/values/dimens.xml
AnkiDroid/src/main/res/values/styles.xml
AnkiDroid/src/test/java/com/ichi2/anki/ui/windows/reviewer/ReviewerBigScreenTest.kt

Improve the new reviewer style in tablets and make it more similar to Anki
Move the toolbar to the bottom of the screen and put the answer buttons there
Emulator 35 in a lot of scenarios with the new reviewer settings (hide system bars; ignore display cutout; frame style; hide answer buttons; menu)
<details>
</details>

feat(new reviewer): tablet layout

---

AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.kt
AnkiDroid/src/test/java/com/ichi2/testutils/JsonUtils.kt

`expectedMap` used to associated the keys of the `expectedValue` to the values of `actualValue`.
As `differtKeys` also looked at the values in `actualValue`, it means the values of `expectedValues` were always ignored.
I hope that this new writting, checking for the equality of the set of keys, and then for the equalities of value, will be more readable and hence improve the test suite.
Luckily enough we only had one failing test. I corrected the expected value in the test. As we use the default filtered deck provided by the back-end I don't expect the implementation to be buggy here.

Correct matchesJsonValue

---

AnkiDroid/src/main/java/com/ichi2/anki/reviewer/Binding.kt
AnkiDroid/src/main/java/com/ichi2/anki/reviewer/MappableBinding.kt
AnkiDroid/src/test/java/com/ichi2/anki/reviewer/BindingTest.kt

so it's possible to compare bindings without a MappableBinding
I'm trusting the unit tests. Went around and tested some keybinds and gestures and they still work.
I couldn't test some keybinds like `*` (mark default) and `!` (suspend default) even before these changes. They are only recognized as `Shift+1` and `Shift+8` here

refactor: extract Binding equality to original classes

---

AnkiDroid/src/main/java/com/ichi2/anki/pages/CongratsPage.kt

This PR introduces a dialog in CongratsPage with the options to execute a more granular unbury if possible.
See https://github.com/ankitects/anki/blob/acaeee91fa853e4a7a78dcddbb832d009ec3529a/qt/aqt/overview.py#L151-L174
The dialog(uses standard AlertDialogFacade.kt methods):
* Fixes #17632
Ran the tests, manually tested the situation when the dialog needs to be shown to the user.

feat: Allow fine tuning of the unbury action in congrats screen

---

AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt

In the deck picker, arrow doesn't rotate on expanding or collapsing the deck.
* Fixes #17915
`deckExpander` (the dropdown arrow) visibility and click behavior depend on `node.children.isNotEmpty()`. When the user toggles the expansion state (by clicking `deckExpander`), the dataset changes, but without `notifyItemChanged(position)`, the UI does not get updated.
[android7.webm](https://github.com/user-attachments/assets/10667db4-57fe-4330-b7b4-ef361fe474fb)
[androidapi35.webm](https://github.com/user-attachments/assets/6e500c7f-21df-4a08-9e67-90571e5b5f12)

Fix : Deck Picker Arrow doesn't rotate on expanding and collapsing the deck.

---

AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BrowserOptionsDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/utils/ext/String.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Config.kt
AnkiDroid/src/main/res/layout/browser_options_dialog.xml
AnkiDroid/src/test/java/com/ichi2/anki/browser/StringNormalizationTest.kt

- Allows user to set default search text like Anki
- User can opt in for ignoring accents in string
Create new preference category and handle the searching in cardbrowser, the way I did it can be seen in commits as they are clear
Google emulator API35:
[Screen_recording_20250203_020641.webm](https://github.com/user-attachments/assets/44619318-0e0f-4972-851b-df9e65e42ef9)

feat(card-browser): default search text & ignore accents in search

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
AnkiDroid/src/main/java/com/ichi2/anki/browser/RepositionCardFragment.kt
AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt
AnkiDroid/src/main/res/layout/fragment_reposition_card.xml
AnkiDroid/src/main/res/values/03-dialogs.xml
AnkiDroid/src/main/res/values/sentence-case.xml
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt

Shows a dialog very similar to desktop with the options to reposition new cards. 
How it looks:
* Fixes #9458
* Hopefully, also fixes #9457
Ran the tests. Manually verified the dialog.

Enable feature complete repositioning of new cards

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt

To improve user experience
* Fixes #17970 
Just pass the deck id to make sure correct deck is selected
Manual testing

Fixes #17970 - Pass DeckId to NoteEditor From Snackbar

---

gradle/libs.versions.toml

Fixes #17967 , keyboard closes on IME_DONE clicked
Fixes #17967 
Solved in the library by adding IME action callback
Tested manually

bump: update searchpreference version to 2.7.1 and fix#17967

---

AnkiDroid/build.gradle
AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
gradle/libs.versions.toml

See Issue 
- #17821
This one is messing up my merge queue, driving me crazy.
Marking flaky
Had to de-conflict the "OS" symbol because something else appears to have been marked flaky, perhaps before we had a good annotation? Anyway, we have a good annotation now so I converted the previous windows cutout to a Flaky annotation

test: mark DeckPicker context menu test flaky on windows

---

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt

`reps` used to have a different meaning than today. I'd actually love to rename this variable, but it's the name used in upstream, so I guess it would not be accepted.
I considered adding more information, such as the fact that in practice, it mostly means that this value is reset when ankidroid restart, with maybe some exceptions. Or that we should only care about the difference between values at different point in time and not about the actual value of this variable. But actually it does not matter. It's only used for timebox and has 3 occurrences in the codebase. Any more documentation would be overkill.
Fixed #6830. Well actually, it was fixed in
7a65160e0e23e20080091a30abdd4c05fc610e06 long ago, but the documen tation did not reflect that. So let's claim I just fixed a 5 yo bug!

NF: Correct `reps` documentation

---

gradle/libs.versions.toml

Keeping it brief: does exactly what the title says
I would like to get this in before we start betas, so it gets wide testing. Can always revert, but wide testing is the only way to know if we need to in my humble opinion

build(deps): adopt backend 1.51-anki25.02

---

.idea/dictionaries/android.xml
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/EmptyCardsDialogFragment.kt
AnkiDroid/src/main/res/layout/dialog_empty_cards.xml
AnkiDroid/src/test/java/com/ichi2/anki/dialogs/EmptyCardsReportTest.kt

Replaced the previous implementation using an _WebView_ with a _TextView_ using _HtmlCompat_ and text spans for the click behavior. Also added a test to prevent unexpected backend changes to the html report structure that we expect.
<details>
<summary>How it looks with the fix</summary>
</details>
* Fixes #17982
Ran the tests, checked all themes, checked the expected behavior.

Fix color scheme for empty cards report dialog

---

AnkiDroid/src/main/res/values-night/colors.xml
AnkiDroid/src/main/res/values/colors.xml

Many people don't know what `Work in progress` means and nag about colors of a developer option.
Tested some variants of material colors until I got something I liked. The contrast had to be enough to pass accessibility scanners, but not too high to avoid eye strain/halo effect (like every app without much thought, and AnkiDroid with its black theme, do with white on pure black)
"But I want the black theme to have pure black buttttonssss". That kind of change doesn't conflict with this PR, so please discuss this somewhere else and do another PR if you want. I'm against it, so please do not try blocking this PR because of that.
Emulator 35, and Samsung Android 14 phone and tablet
<details>
</details>
Android Studio has material colors embedded on its color picker …

feat(new reviewer): buttons night mode colors

---

AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt

Resolves a TODO and uses state flow for deck id in Instant Editor 
~~Use stateFlow()~~
POCO API 33

NF: remove TODO comment

---

AnkiDroid/src/main/res/layout/widget_card_analysis.xml
AnkiDroid/src/main/res/layout/widget_card_analysis_drawable_v31.xml
AnkiDroid/src/main/res/xml/widget_provider_card_analysis.xml

The Card Analysis Widget appears larger than necessary for its content, resulting in wasted space.
* https://github.com/ankidroid/Anki-Android/issues/17968

Refactor: Card Analysis Widget for more clean look.

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/EditDeckDescriptionDialog.kt

Keyboard does not appear automatically when opening the EditDeckDescriptionDialog.
Request focus on deckDescriptionInput
Use postDelayed() to show the keyboard after layout rendering
OPPO CPH2341
https://github.com/user-attachments/assets/1d1be482-14f5-42a4-8b11-ec17dbfb3e21

fix:focus keyboard on edit description dialog

---

AnkiDroid/src/main/assets/flashcard.css

When "Center align" is enabled and the content of the card is so long that cannot be shown entirely without scrolling, the top side of the content is trimmed.
* Fixes #17998
Use `min-height: 100%` instead of `height: 100%` in `vertically_centered` class
Checked in physical device (Android 11)
**Pattern A**  (front: short, back: short)
-- | Start | Scroll to Top | Show Answer | Scroll to Top
---|---|---|---|----
**Before**| OK![Image](https://github.com/user-attachments/assets/75a01406-b763-4f28-9db2-303bdc33bb95) | OK (No need) ![Image](https://github.com/user-attachments/assets/75a01406-b763-4f28-9db2-303bdc33bb95) | OK ![Image](https://github.com/user-attachments/assets/4d8796ab-c551-4534-96d7-0acd70b06380) | OK (No need) ![Image](https://github.com/user-attachments/assets/4d8796ab-c551- …

fix: Top side of card is cut off when "Center align" enabled & content is long

---

AnkiDroid/src/main/assets/scripts/js-api.js
AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
AnkiDroid/src/test/java/com/ichi2/anki/AnkiDroidJsAPITest.kt
AnkiDroid/src/test/java/com/ichi2/testutils/TestClass.kt

Adds two JS API functions [set/replace]NoteTags and getTagsFromNote which act similar to PUT and GET from a REST API
* Fixes #17716 
Adds two methods to allow the caller to get Tags and update/set tags.
Added two unit tests both verified and passing.

JS function to setTags and getTags

---

AnkiDroid/src/main/res/layout/activity_shared_decks.xml

Saw this when I fixed the empty cards report appearance in dark themes.
Light and plain, no change:
Before/after:
Black:
Dark:
Verified the toolbar's appearance in all themes.

Fix SharedDecksActivity toolbar color for dark themes

---

AnkiDroid/src/test/java/com/ichi2/utils/UniqueArrayListTest.kt

Optimizing function calls by converting arguments to `Set` for improved performance and reducing warnings.  
- Contributes towards #13282  
- Converted `Iterable<T>` and `Array<T>` arguments to `Set<T>` to enhance efficiency in `minus` and `intersect` operations.  
- Updated `UniqueArrayList.kt` to improve `removeAll` and `retainAll` performance.  
- Modified `test_retainAll()` in `UniqueArrayListTest.kt` to use `setOf()` for better efficiency.  
Please, go through these checks before submitting the PR.

[Cleanup]: Remove Android Studio Warning

---

AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt
AnkiDroid/src/main/res/layout-sw600dp/reviewer2.xml
AnkiDroid/src/main/res/layout/reviewer2.xml

If there were no type answer box nor answer buttons, the snackbar wouldn't show up in the new reviewer
Add a ConstraintLayout Barrier
Emulator 35: Undo stuff in the new reviewer with `Hide answer buttons` enabled/disabled and in type-in-answer notetypes. Also tested in a tablet emulator

fix(new reviewer): snackbar position if answer buttons are hidden

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
AnkiDroid/src/main/java/com/ichi2/anki/browser/FindAndReplaceDialogFragment.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Tags.kt
AnkiDroid/src/main/res/layout/fragment_find_replace.xml
AnkiDroid/src/main/res/menu/card_browser.xml
AnkiDroid/src/main/res/menu/card_browser_multiselect.xml
AnkiDroid/src/main/res/values/07-cardbrowser.xml
AnkiDroid/src/main/res/values/constants.xml
AnkiDroid/src/main/res/values/preferences.xml
AnkiDroid/src/main/res/values/sentence-case.xml
AnkiDroid/src/main/res/xml/preferences_dev_options.xml
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.kt

Enables desktop's find and replace menu option(implemented as a dialog). The line count is big but it's mostly tests and code verbosity, the actual feature is small. Some notes:
- decided against a viewmodel in the new dialog fragment, we should probably make these dialogs as simple as possible
- added some tests, the tests related to the fragment's ui should probably be on their own but it would require extra work to make the activity viewmodel replaceable(and I didn't see it worth it to modify the production code for easier testing)
- browser also allows find and replace on a field directly, see documentation on the new dialog fragment
How it looks:
https://github.com/user-attachments/assets/988fee01-5e54-4133-abdf-680ba4e6ca60
* Fixes #16386 
Manually tested the new dialog in various …

feat: Add developer option for find and replace

---

AnkiDroid/build.gradle

This will ensure that new contributors can run androidTest on emulators without having to change the variant.
Syntax found on
https://stackoverflow.com/posts/60197203/revisions
Tested by using the "Re-import with defaults" button in the variant setting.

NF: set "play" variant as default

---

AnkiDroid/src/main/assets/scripts/js-api.js
AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
AnkiDroid/src/main/res/layout/activity_shared_decks.xml
AnkiDroid/src/main/res/layout/gesture_display.xml
AnkiDroid/src/test/java/com/ichi2/anki/AnkiDroidJsAPITest.kt
AnkiDroid/src/test/java/com/ichi2/testutils/TestClass.kt

The issue occurred due to a fixed **16dp margin** around the outer circles, while the central arrow image scaled dynamically based on available space. This caused **misalignment in smaller gesture picker sizes**.
- The outer circles' margins are now dynamically adjusted using constraint ratios (`0.047` and `0.953`), ensuring proportional scaling.
- This change maintains visual consistency across different screen sizes and orientations.
* Fixes #17348
- Outer circle margins were hardcoded to `16dp`.
- The central arrow image scaled dynamically, causing layout issues on smaller screens.
- Instead of a fixed margin, outer circles now follow a constraint ratio:
- `0.047` (4.7%) for the top margin.
- `0.953` (95.3%) for the bottom margin.
- This ensures proportional spacing, adapting to …

Fix gesture picker misalignment by using constraint ratios

---

AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/AppearanceSettingsFragment.kt
AnkiDroid/src/main/res/values/02-strings.xml
AnkiDroid/src/main/res/values/preferences.xml
AnkiDroid/src/main/res/xml/preferences_appearance.xml

This PR fixes the issue of not having an explicit background removal option. Without this, users may be confused about how to remove the background. Adding an explicit removal option improves clarity and enhances the user experience.
* Adds an explicit background removal option to improve user experience.  
_This change addresses the problem by:_  
- Providing a clear and accessible way for users to remove backgrounds.  
- Ensuring a more intuitive UI to avoid confusion.  
**ScreenShot**
- **ScreenRecording**
https://github.com/user-attachments/assets/d257086e-ba13-4104-ac36-600226032551
- Tested in **portrait** and **landscape** modes.  
- Used **Google Accessibility Scanner** to verify UI improvements.  
- **Device Used:** Redmi Note 8 Pro.  
_Please go through these checks before …

Added Background Remove Option

---

AnkiDroid/src/main/res/xml/preferences_controls.xml

[Approach has been updated] 
"Toggle whiteboard" control icon does not match the label and the actual action.
---
---
* Fixes #18026
- Change the icon for "Toggle whiteboard" item in Controls settings page
Checked on physical device (Android 11)

fix: "Toggle whiteboard" control icon & label do not match

---

AnkiDroid/src/main/res/values/02-strings.xml

Remove an extra space in a recently added string for https://github.com/ankidroid/Anki-Android/pull/18071
N/A
Remove the space in the source file
Test omitted

minor fix: remove extra space in newer string

---

AnkiDroid/src/main/res/values/02-strings.xml
AnkiDroid/src/main/res/values/03-dialogs.xml
AnkiDroid/src/main/res/values/10-preferences.xml
AnkiDroid/src/main/res/values/17-model-manager.xml
lint-rules/src/main/java/com/ichi2/anki/lint/rules/TranslationTypo.kt
lint-rules/src/test/java/com/ichi2/anki/lint/rules/TranslationTypoTest.kt
lint-rules/src/test/java/com/ichi2/anki/lint/testutils/LintAssert.kt

* Part of #14903 
* Add a lint rule
* Attempt the autofix, and fail: converting an `Element` back to the actual XML as it appeared on screen is difficult
* Only apply the lint rule to `/values` for now, fix the remainder on Crowdin
Unit tested

lint: fix trailing spaces in /values 

---

AnkiDroid/src/main/java/com/ichi2/anki/preferences/HeaderFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt

While reviewing a PR, I found unclear why we checked whether the window is compact. Admittedly, figuring out it means that the view is split in two was not hard, still, I believe it's best to put it behind a more descriptive value. This also ensure that if we decide to change the criteria we use to decide whether to split or not, we will have to change a single place.

NF: Introduce `isPrefererenceViewSplit`

---

AnkiDroid/src/test/java/com/ichi2/preferences/PreferenceExtensionsTest.kt

Adds missing test coverage for `PreferenceExtensions`:
- Verifies existing Long preference retrieval
- Tests new Long value persistence
- Tests edge cases (empty strings, zero/negative longs)
- All unit tests pass (`./gradlew AnkiDroid:testPlayDebugUnitTest --tests com.ichi2.preferences.PreferenceExtensionsTest`)
- 100% coverage for modified files (`./gradlew jacocoUnitTestReport`)
- Lint/formatting checks passed

test(preferences): add unit tests for getOrSetLong logic

---

pre-commit

Fix pre-commit hook creating empty `.diff` files by removing empty `.diff` during ktlint formatting.
* Fixes #18003 
- Remove the `.diff` file when there are no unstaged changes.
- Fixed syntax: `if [apply_exit_code -ne 0]` -> `if [ $apply_exit_code -ne 0 ]`
- Ran pre-commit hook with Kotlin files.

fix(pre-commit-hook): update pre-commit hook to correctly handle `.diff` file 

---

AnkiDroid/src/main/java/com/ichi2/anki/preferences/HeaderFragment.kt
AnkiDroid/src/main/res/values/10-preferences.xml

**Issue**: The "Anki Card" menu does not appear in the settings search results when users type "anki" or "context".  
**Root Cause**:  
- The preference used `tools:title` and `tools:summary` (design-time attributes) instead of `android:title` and `android:summary` (runtime attributes).  
- Search indexing relied on runtime attributes, which were missing.  
Resolves missing search results for "Anki Card" menu. Resolve part of #18050.  
1. **Replace `tools:` with `android:` attributes**:  
- Use `android:title` and `android:summary` to ensure the text is available at runtime.  
- Link to string resources containing searchable keywords like "Anki" and "context".  
2. **Update string resources**:  
- Define `anki_card_menu_title` and `anki_card_menu_summary` in `strings.xml` with relevant …

fixed the The anki card menu can't be found from the search bar..

---

AnkiDroid/src/main/res/values/12-dont-translate.xml

I experimented and found that adding a new line at start/stop plus spaces cause the string to be noted as untranslated.
So I add this note to this logical place to keep track of this information.

NF: add a note in 12-dont-translate

---

AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
AnkiDroid/src/main/res/layout/fragment_shared_decks_download.xml
AnkiDroid/src/main/res/values/02-strings.xml
AnkiDroid/src/main/res/values/constants.xml
AnkiDroid/src/test/java/com/ichi2/anki/SharedDecksDownloadFragmentTest.kt

The user can download the deck manually if  download fails.
* Fixes #17178 
This change allows users to manually download decks from AnkiWeb through an external browser if the download fails in the in-app WebView. By using an Intent, we redirect users to their preferred browser.
Once the download is initiated, the app pops the fragment stack.
1 : Comment out the downloadFile() function call in the onViewCreated method.
2 : Instead, call checkDownloadStatusAndUnregisterReceiver(false, false).
(https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

Manual-Download-link

---

AnkiDroid/src/main/res/values/12-dont-translate.xml

This is here only to ensure that adding a tag comment don't cause a need for translation.

NF: adding a comment to 12-dont-translate

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportReadyDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt

* 'when' is exhaustive so 'else' is redundant here.
* The resulting type of this 'javaClass' call is 'Class<DeckPicker.Companion>' and not 'Class<DeckPicker>'. Use '::class.java' to access type 'Class<DeckPicker>'.
* See PR #18140
Just checked if it built, none of the changes were scary

fix: Kotlin 2.1.20 Upgrade Errors

---

lint-rules/src/main/java/com/ichi2/anki/lint/utils/Crowdin.kt

This makes it easier to resolve lint errors. URLs were not provided, now:
* https://crowdin.com/editor/ankidroid/8170/en-uk#q=card_browser_order_labels
* https://crowdin.com/editor/ankidroid/8232/en-sat#q=back_field_name
* fix a filename
* link the parent element if `<string-array><item>` is detected
```sh
./gradlew buildPlayDebug && ./gradlew lintPlayDebug
```
```patch
Index: lint-rules/src/main/java/com/ichi2/anki/lint/rules/TranslationTypo.kt
<+>UTF-8
diff --git a/lint-rules/src/main/java/com/ichi2/anki/lint/rules/TranslationTypo.kt b/lint-rules/src/main/java/com/ichi2/anki/lint/rules/TranslationTypo.kt
--- …
```

fix(lint-crowdin): more links to translations

---

AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckNode.kt
AnkiDroid/src/main/java/com/ichi2/ui/AxisValueDisplay.kt
AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt
AnkiDroid/src/main/java/com/ichi2/utils/AssetHelper.kt
AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt
lint-release.xml
lint-rules/src/main/java/com/ichi2/anki/lint/IssueRegistry.kt
lint-rules/src/main/java/com/ichi2/anki/lint/rules/LocaleRootDetector.kt
lint-rules/src/test/java/com/ichi2/anki/lint/rules/LocaleRootDetectorTest.kt

User-facing text formatting sometimes uses Locale.ROOT or lacks explicit locale, leading to incorrect number/date formats 
* Fixes #8917
- Created LocaleRootDetector to flag Locale.ROOT in user-facing formatting methods (ie., String.format(), NumberFormat).
- Activated DefaultLocale lint rule to enforce explicit Locale parameters.
- Updated violations to use Locale.getDefault() where appropriate.
./gradlew clean lint 
[Android custom lint rules](https://googlesamples.github.io/android-custom-lint-rules/)
Used existing custom lint rules as a template
- [NA] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [NA] UI Changes: You have tested your change using the [Google Accessibility …

Enforce user-facing locale checks via lint; fixes #8917

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt
AnkiDroid/src/main/res/values/sentence-case.xml
lint-rules/src/main/java/com/ichi2/anki/lint/IssueRegistry.kt
lint-rules/src/main/java/com/ichi2/anki/lint/rules/SentenceCaseConventions.kt
lint-rules/src/test/java/com/ichi2/anki/lint/rules/SentenceCaseConventionsTest.kt

* https://github.com/ankidroid/Anki-Android/labels/Blocked%20by%20dependency #17943
I made a bad review comment, and wasted time checking if `"Tag Missing"` was a duplicate string in the Anki Backend:
https://redirect.github.com/ankidroid/Anki-Android/pull/17943#discussion_r2002135876
* Add a lint check, and fix a string:
* `tag_missing` => `sentence_tag_missing`
Unit tests added

lint: enforce 'sentence_' prefix in `sentence_case.xml`

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt

Issue: When starting the app, sometimes you can get a Backup reminder dialog at the same time that autosync kicks in.
https://github.com/user-attachments/assets/5b2eefaa-c1fd-4d02-a0fe-4a0d3f15d909
I didn't make an issue as this problem was mentioned in a comment in [this issue ](https://github.com/ankidroid/Anki-Android/issues/13934#issuecomment-1774594805). But I think that issue is broader than what is fixed in this PR.
Not showing the backup reminder dialog if one-way sync dialog should be shown or if AutoSync triggered a sync.
This issue can be simulated by:
1. Enabling AutoSync
2. Set BackupPromptDialog.shouldShowDialog() to always return true.
3. Set DeckPicker.syncIntervalPassed() to always true
4. review a card 
5. Open the app again.
Tested by restarting the app with and without …

Only show Backup prompt dialog if there is no one-way or auto sync at startup

---

AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerPage.kt
AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerViewModel.kt
AnkiDroid/src/test/java/com/ichi2/anki/previewer/TemplatePreviewerViewModelTest.kt

There is currently no way of telling at a glance whether a card's front is blank via the previewer screen for a card (found by navigating to the Add Note editor and then pressing the eye in the top right corner).
* Fixes #18107
I could not find a way to determine if a card was empty directly from the previewer fragment screen's arguments. It seems code for checking whether a card's front is empty is located in the main Anki repository rather than AnkiDroid. See [here](https://github.com/ankitects/anki/blob/d52889f45c3f7999a45fd2dde367f79f3bc3bad4/ftl/core/card-template-rendering.ftl#L4) and [here](https://github.com/ankitects/anki/blob/d52889f45c3f7999a45fd2dde367f79f3bc3bad4/rslib/src/notetype/mod.rs#L410) in particular, if I am not mistaken. As such, the approach taken here is to check …

Showing Badge for Blank Card Fronts in Previewer

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/analytics/AcraAnalyticsInteraction.kt
AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt
AnkiDroid/src/main/java/com/ichi2/anki/browser/BrowserColumnCollection.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/help/HelpDialog.kt
AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt

Purpose / Description
Reducing Android Studio warnings by cleaning up unused code and fixing initialization.
Fixes
Contributes towards [Cleanup](https://github.com/ankidroid/Anki-Android/issues/13282)  Fix Android Studio Warnings
Approach
By using android studio suggestions and deleting never used variables or using suppression
I run my code after change on emulator android 11 it runs as previous
Checklist
Please, go through these checks before submitting the PR.
You have a descriptive commit message with a short title (first line, max 50 chars).
You have performed a self-review of your own code

Remove warning

---

gradle/libs.versions.toml

Does exactly what it says in the commit, nothing more
There is nothing too special about the new backend artifact, it represents the same upstream anki as before, but packaged with locally updated direct dependencies. So this is just to make sure all those dependency updates work, which is why I'm starting on the dependency-updates branch

build(deps): adopt latest Anki-Android-Backend 0.1.52-anki25.02

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/IntroductionActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/SingleFragmentActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/browser/FindAndReplaceDialogFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/introduction/SetupCollectionFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/scheduling/ForgetCardsDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/utils/ext/FragmentResult.kt

Adds a method to simplify setting a fragment result listener in a FragmentActtivity. Similar with the [Fragment.setFragmentResultListener()](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:fragment/fragment-ktx/src/main/java/androidx/fragment/app/Fragment.kt?q=file:androidx%2Ffragment%2Fapp%2FFragment.kt%20function:setFragmentResultListener) platform method.
Feel free to disagree with this and I can close it.
Also, I looked into creating an extension to return a result class in the listener but I don't think it's worth the effort and it doesn't simplify things at all.
Ran the tests.

Add utility method for setting a fragment result listener in a FragmentActivity

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/IncludedExcludedTagsAdapter.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/TagLimitFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt
AnkiDroid/src/main/res/drawable/list_border.xml
AnkiDroid/src/main/res/layout-land/fragment_tag_limit.xml
AnkiDroid/src/main/res/layout/fragment_tag_limit.xml
AnkiDroid/src/main/res/layout/item_require_exclude_tag.xml
AnkiDroid/src/main/res/layout/styled_custom_study_details_dialog.xml
AnkiDroid/src/main/res/values/01-core.xml
AnkiDroid/src/main/res/values/02-strings.xml
AnkiDroid/src/main/res/values/03-dialogs.xml
AnkiDroid/src/main/res/values/sentence-case.xml
AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogTest.kt

Enables for the app the full desktop functionality related to custom study by tags. Some notes related to the implementation:
- follows the  desktop flow with "Choose tags" button showing a new dialog and on ok on that dialog returning to the previous dialog to do the actual setup of the custom study
- uses different layouts for portrait/landscape but the transition between them doesn't work because DeckPicker is set(although it shouldn't) to handle the configuration manually
- I added a border for both lists because the middle label was kind of blending with the lists IMO
<details>
<summary>How it looks on mobile</summary>
</details>
<details>
<summary>How it looks on desktop</summary>
</details>
* Fixes #17583
* Fixes #17984
Ran the tests, manually verified the new dialogs/code paths.

Add functionality to custom study by tags or card state

---

AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt

This pull request addresses a memory leak that occurred when using the `AnkiServer` in conjunction with `PageFragment`. The memory leak was solved by explicitly shutting down the AnkiServer instance in the onDestroyView()
* Fixes Im not sure?
The primary cause of the leak was that the `AnkiServer` held a direct reference to the `PageFragment` through the `postHandler`. The server, intended to run in the background, could outlive the fragment, when it was not shutdown.
To fix this, we took the following steps:
1. **Using `onDestroy`**: In the `AnkiPackageImporterFragment`, the `onDestroy` function is used to remove the `OnBackPressedCallback`.
These changes ensure that the `PageFragment` is no longer kept alive by the `AnkiServer`, allowing the garbage collector to reclaim the memory.
1. …

Fix memory leak by stopping server in pageFragment by onDestroy

---

AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.kt
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/res/values/10-preferences.xml
AnkiDroid/src/main/res/values/preferences.xml
AnkiDroid/src/main/res/xml/preferences_general.xml

Anki preserves the image format unless `Paste as png` is turned on, this PR allow the user to preserve the image format unless the option is turned on
* Fixes #17841
Tested on API 35 -> Google Emulator
- MediaRegistration class was context dependent which is not a good practice hence converted it to `Object`
- `onPaste` ran a check to see if we want to convert a image to JPG or not, but Anki doesn't do that and preserves the image extension and in case paste as PNG is turned on then pastes the images as png, hence I updated the code to remove these JPG checks and proceed with original extension unless the paste as PNG is turned on
- fetch the boolean from `col` to see if we want to paste the image as PNG in NoteEditor 
- finally proceed to paste the image
_Please, go through these checks …

feat: allow pasting images as png

---

AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt

CardBrowserTest > FindReplace - replaces text based on regular expression FAILED
androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: an instance of android.widget.TextView and view.getText() with or without transformation to match: is "⁨1⁩ note updated."
If the target view is not part of the view hierarchy, you may need to use Espresso.onData to load it from one of the following AdapterViews:androidx.appcompat.widget.AppCompatSpinner{37dd5091 VFED..CL. ......ID 56,0-232,64 #7f0a04e6 app:id/toolbar_spinner}
Follow on from 
* 4c5bf718a7c8f170f741553b5e9d5a8b7ff6d80e => PR #18093 
* Cause: https://github.com/ankidroid/Anki-Android/pull/17897

test: ignore flaky tests

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/NotificationChannels.kt
AnkiDroid/src/main/java/com/ichi2/compat/BaseCompat.kt
AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.kt

We want to remove dependency for notification channel creation from compact module as we will be extracting it out as module, hence I am lifting the old code off and using the new code from androidx
Use new `NotificationChannelCompat.Builder`

feat: use `NotificationChannelCompat.Builder` for channel creation 

---

AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt

- Remove unnecessary `orEmpty` call.
- Replace `java.lang.Object` to the Kotlin equivalent `kotlin.Any`
* Fixes #13282 
Removed unnecessary calls and replaced Java code with Kotlin equivalent as recommended by Android Studio.
By running the code on a physical device.

Fix Android Studio warnings in `PageFragment.kt`

---

AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncMediaWorker.kt
AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncWorker.kt
AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt

In Android 13+, it's necessary to get the user permission in order to send notifications.
The issue is that we use foreground services for syncing, and they use notifications.
* Fixes #17493 
Make the NotificationManager of the workers `null` if the app can't post notifications, so no notifications are sent
Emulator 35:
1. Log-in into some account
2. Add some fake media in Dev options
3. Sync
(couldn't reproduce the original issue, but these steps test that sync is still working)

fix: freeze when syncing when notifications permission is missing

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/reviewer/PeripheralKeymapTest.kt
AnkiDroid/src/main/assets/scripts/ankidroid.js
AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/reviewer/ViewerAction.kt
AnkiDroid/src/main/java/com/ichi2/anki/reviewer/MappableBinding.kt
AnkiDroid/src/main/java/com/ichi2/anki/reviewer/PeripheralKeymap.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerViewModel.kt
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerKeyboardInputTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/reviewer/PeripheralKeymapTest.kt

1. Generify the old reviewer keymap
2. Implement the keybindings
3. Implement the  `Show answer`, `Answer Again/Hard/Good/Easy`, `Toggle flag`, `Show hint`, `Show all hints` and `Close` bindable actions to ease the testing process of the PR and for general use
Emulator 35 (imagine I'm using keyboard keys to do the actions below)
https://github.com/user-attachments/assets/ca9ee69d-135e-47a2-bef3-98b9f1c5f159

feat(new reviewer): Keybinds

---

.github/workflows/publish.yml
tools/release.sh

Refactored github-releases in favor of gh cli and fixed a minor SC2088 violation in export PATH.
* Fixes #18110 
Refactored to use gh cli, updated the publish.yml to use gh cli.
Will have to test on the fly.
Checked the github cli documentation:
https://cli.github.com/manual/gh_release_create
Also went through usages of gh cli in code search because documentation is spotty.

Refactor $PRE_RELEASE to $RELEASE_TYPE & fix SC2088

---

AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.kt

Adding mathjax block and mathjax chemistry options by showing a menu dialog
* Fixes #18174 

Add mathjax block and mathjax chemistry

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/preferences/PreferencesNavigationTest.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt

- Issue: The Settings screen closes when searching and the Back button or the Navigation icon is pressed, causing the user to restart their search.
- Why it Matters: This issue creates a significant usability barrier, hindering users' ability to effectively use the settings. Addressing it will make the settings experience more efficient and less frustrating.
* Fixes  https://github.com/ankidroid/Anki-Android/issues/18051#issue-2892805733
- Before: Child fragments were effectively managed within the handleOnBackPressed() method. However, this method did not manage the back stack for the parent fragment, which is directly hosted by the activity.
- After the changes: Now, the method also manages the parent fragment's back stack, ensuring it remains on the screen when the user is searching …

Managed back stack for parent fragments in the app settings

---

AnkiDroid/src/main/java/com/ichi2/anki/browser/BrowserColumnCollection.kt
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt

The columns sometimes were not distinct in CardBrowser.
* Fixes #17892
I modified `BrowserColumnCollection::load` to return only distinct columns.
I wrote a unit test to override the CardBrowser columns in SharedPreferences so it has duplicate values and checked its distinctness afterward.

Duplicate Due column Fix

---

AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerPage.kt
AnkiDroid/src/main/res/values/02-strings.xml

Addresses @user1823's concerns at #18147 by implementing @BrayanDSO's suggestion. When a card's front is empty, the previewer tab now indicates this by appending (empty) to the tab title rather than using an overly-urgent looking red badge. Creates a new string resource and appends it in [TemplatePreviewerPage].
Continues fixing #18107.
Adds a new string resource and appends it onto the tab title.
Text displays properly on my end!

Converted previewer empty front indicator to text

---

AnkiDroid/src/main/res/layout/dialog_axis_picker.xml

The axis picker is broken since 2.19beta5 (nobody noticing it reveals that it isn't popular). Noticed after working on adding the joystick controller detection to the new reviewer
* Fixes #17026
1. Find the cause with git blame -> 3d6ac834
2. Revert it
3. Fix back the original issue (#17026)
1. Check in Android Studio layout preview if the picker works in landscape mode (#17026)
Android 14 tablet with a Dualshock 4 controller:
1. Settings > Controls > Add joystick/motion controller
2. Move the joyticks

fix: axis picker

---

AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt

> [!IMPORTANT]
> I copied the description from #18098, as the user deleted their account
> * #18098
- Problem: The Study Options screen incorrectly displays "+0 buried" for New, Learning, and/or Review card categories even when those categories have no buried cards.
- Impact: This misleadingly suggests there are buried cards when there aren't, confusing users about their study status.
- Problem: When there are buried cards in the review category, the value displayed is "+0" instead of the correct one. To improve the accuracy and clarity of the Study Options screen, providing users with correct information about their buried cards.
* Fixes https://github.com/ankidroid/Anki-Android/issues/18094#issue-2919291007
Uploading solved18094.mp4…
- Modified the **rebuildUi** function in …

fix: Updated visibility for buried card counts in Study Options

---

AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
AnkiDroid/src/test/java/com/ichi2/anki/AnkiDroidJsAPITest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/CardTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/CollectionTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/SchedulerTest.kt
AnkiDroid/src/test/java/com/ichi2/testutils/TestClass.kt

David noted that `val noteTypes = col.notetypes` is useless in #18113. I find it simpler to just go over all of them and replace them instead of having to do it everywhere.
This is low priority, don't review if you don't have time for it

NF: remove variables which are simply `col.notetypes`

---

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Notetypes.kt
AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/AnkiDroidJsAPITest.kt
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateNotetypeTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/CollectionTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/StorageRustTest.kt
AnkiDroid/src/test/java/com/ichi2/utils/NoteTypeTest.kt

This also change the name of some methods that are tested.
This is not changing all instance of the word "model"  that represents a note type, this commit is already big enough to let more changes for a future PR
Some more part of https://github.com/ankidroid/Anki-Android/pull/17598

NF: rename `model` into `noteType` in unit tests

---

AnkiDroid/src/main/java/com/ichi2/anki/model/SortType.kt
AnkiDroid/src/main/res/values/07-cardbrowser.xml

There was a feature request for a "Deck name" option in the sort options in CardBrowser
* Fixes #18169
I added a sort option for "deck" in `com/ichi2/anki/model/SortType.kt` and also a string in `res/values/07-cardbrowser.xml::card_browser_order_labels` with the value "By deck name" which will be displayed in the dialog.
Manually Tested on physical device (Video showing the descending and ascending orders below).
https://github.com/user-attachments/assets/7650caee-526e-42fd-aa6c-e7088723fa4d

Add sorting by deck name to card browser

---

AnkiDroid/src/main/java/com/ichi2/anki/preferences/HeaderFragment.kt
AnkiDroid/src/main/res/xml/preferences_appearance.xml
AnkiDroid/src/main/res/xml/preferences_custom_sync_server.xml
AnkiDroid/src/main/res/xml/preferences_sync.xml

I had to ensure tha the "one-way sync" entry has not `android:` content. Otherwise, it would appear twice in the search result when its title was searched.
This is not ideal, but currently the search library we use don't allow to edit a preference entry (and its not a trivial change to allow such edit; I tried to look whether it can be done or not, it seems it require to change the way files are processed in the library)

Add missing setting entries to the setting search

---

AnkiDroid/src/main/res/values/theme_black.xml

The fix consists in extending the style that was used for AlertDialogs and update it with a new color just for the black theme. This shouldn't produce changes outside of the black theme(I looked at dialogs in other themes). Feel free to propose a different color.
See images below(before/after) for some AlertDialogs:
* Fixes #15241
Checked some dialogs in black theme.
We need to stop using MaterialAlertDialogBuilder as it has a distinct look.

Fix AlertDialog background color for black theme

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt

Ensures that when the keyboard is open, pressing back first closes the keyboard instead of collapsing the search view, using robust keyboard visibility detection with WindowInsetsCompat
* Fixes #17913 
Implemented WindowInsetsCompat to accurately detect keyboard visibility. On back press, if the keyboard is open, it is hidden first instead of collapsing the search view..
Samsun Galaxy F23 5G
https://github.com/user-attachments/assets/cc33384c-768f-4bf3-b82b-935c2019f68c

Fix: Added robust keyboard visibility detection using WindowInsetsCompat.

---

AnkiDroid/src/main/java/com/ichi2/anki/preferences/DevOptionsFragment.kt
AnkiDroid/src/main/res/values/preferences.xml
AnkiDroid/src/main/res/xml/preferences_dev_options.xml

This way, if I start a fresh collection to test AnkiDroid, I can ensure it's not empty. Especially useful if I want to fill the card browser and the deck browser
To be specific, I wanted it to test #18165 with a deck with many cards and easy to remember card content

Add a dev option to add useless note

---

AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
AnkiDroid/src/test/java/com/ichi2/anki/browser/CardBrowserViewModelTest.kt

This ensures that quotes in the deck name for card browser's search syntax are escaped before they are used.
Fixes #18265 
- This modifies the `setDeckId` method in `CardBrowserViewModel` to escape quotes in deck names when constructing the search query.
- The fix replaces all double quotes with escaped double quotes (\") in the deck name.
Manually and added a new unit test.

Escape quotes in the deck name for card browser's search syntax

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CreateDeckDialogTest.kt

Fixes the handling of quotes while renaming a deck.
Fixes #18266
There was an unnecessary removal of `"` happening before the renaming logic. This was also inconsistent with the deck creation logic.
Manual testing + unit tests.

Fix the handling of quotes while renaming a deck

---

AnkiDroid/src/main/java/com/ichi2/anki/preferences/reviewer/ViewerAction.kt

default keybinds like *, ! and @, which needs a combination of shift+another key in most keyboards, weren't working in the new reviewer
this fixes it by using `allowShift()` like the old reviewer does
With an Android 14 tablet, by testing if the mentioned keybinds work in a new installation of AnkiDroid

fix(new reviewer): default keybinds

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/UIUtils.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/help/HelpDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.kt
AnkiDroid/src/main/java/com/ichi2/anki/scheduling/SetDueDateDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/snackbar/SensibleSwipeDismissBehavior.kt
AnkiDroid/src/main/java/com/ichi2/ui/AxisValueDisplay.kt
AnkiDroid/src/main/java/com/ichi2/utils/DisplayUtils.kt
AnkiDroid/src/main/java/com/ichi2/utils/MenuUtils.kt
AnkiDroid/src/main/java/com/ichi2/utils/ViewUtils.kt

Removes two utility methods to convert dp units and replaces them with the _Dp_ class that we recently introduced.
Checked the dialogs where the utilities were used. Didn't checked AxisValueDisplay in settings.

Replace dp conversion utilities with Dp class

---

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt

Bottom Alignment Issue `Show answer`
set bottom `show answer` height to `80dp`
Medium Tablet API 33

fix:bottom alignment

---

AnkiDroid/src/main/java/com/ichi2/preferences/ReviewerControlPreference.kt

This ensure the behavior is consistent with other bindings. More importantly for me, it'll allow to ensure that the "answer XXX" gesture does not also trigger a flip, which is a problem I currently have when I need to scroll to see the entire card and ends up flipping the card by accident.

Cause gesture to ask on which side it is executed

---

AnkiDroid/src/main/res/layout/fragment_reposition_card.xml

Allows scrolling in Reposition dialog especially useful for split screen 
* Fixes #18317 
Wraps the the layout with ScrollView
- Physical device: Pixel 7 pro

fix(reposition-dialog): adds ScrollView to dialog

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/MediaTest.kt
AnkiDroid/src/main/java/com/ichi2/anki/mediacheck/MediaCheckFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/mediacheck/MediaCheckViewModel.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Media.kt

Remove the custom data class that we created for media result and use the result given by backend directly as I am working on the feature to show trash count and then empty or restore trash if needed just like Anki desktop, hence this PR removes the extra step needed to add the val in data class and then use it
* Sets things up for #17993
Use the `CheckMediaResponse` type instead of the custom data class we created
Tested on API 31 and POCO API 35, and ran the tests locally

 refactor: use `CheckMediaResponse` instead of custom data class

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
AnkiDroid/src/main/java/com/ichi2/anki/browser/ColumnSelectionDialogFragment.kt
AnkiDroid/src/main/res/layout/item_column_selection.xml
AnkiDroid/src/main/res/values/07-cardbrowser.xml

> [!WARNING]
> This is a fixup of the following PR, I've briefly tested and reviewed the code, but copy/pasted the PR message with brief changes
> * https://github.com/ankidroid/Anki-Android/pull/17920 
Added dialog on single-click of column name to show available columns for change, as mentioned in the issue.
* Fixes https://github.com/ankidroid/Anki-Android/issues/17910
- **Added a single-tap listener** to each column heading (`TextView` inside `browser_column_headings`) to open a dialog.  
- **Dialog now displays:**
- The **title** with the name of the currently selected column.
- **A list of available columns** (those not currently in use).
- **On column selection:**
- Calls `updateActiveColumns()` from `CardBrowserViewModel.kt` to apply the change **without reloading all columns**. …

feat(card-browser): two-taps to change columns

---

AnkiDroid/src/main/java/com/ichi2/anki/preferences/AboutFragment.kt
AnkiDroid/src/main/res/values/10-preferences.xml
AnkiDroid/src/main/res/values/constants.xml

Created wiki page for AnkiDroid license and its dependencies, and added the link in the about section
- [wiki](https://github.com/ankidroid/Anki-Android/wiki/Licences)
* Fixes #11825

feat: add licenses wiki page link

---

AnkiDroid/src/main/res/values/preferences.xml
AnkiDroid/src/main/res/xml/preferences_dev_options.xml

- Created a "New notifications" developer toggle in settings
- For GSoC 2025: Review Reminders
- This is a simple toggle to facilitate further development on this project. New notification features (such as [this PR](https://github.com/ankidroid/Anki-Android/pull/18318)) will be locked behind this toggle until the system is stable by the end of August.
- The developer setting can be toggled on and off. The state persists between app sessions.
- Tested on a physical Samsung S23, API 34.
- This is a subchange of [this PR](https://github.com/ankidroid/Anki-Android/pull/18318).

Developer option for review reminders

---

AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardSideSelectionDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/reviewer/ViewerAction.kt
AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerAction.kt
AnkiDroid/src/main/java/com/ichi2/anki/reviewer/MappableBinding.kt
AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ReviewerBinding.kt
AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt
AnkiDroid/src/main/java/com/ichi2/preferences/ReviewerControlPreference.kt
AnkiDroid/src/main/res/values/10-preferences.xml

It seemed absurd to ask the user which side "show answer" binding should be applied to, while only the question side makes sense. Reciprocally, "answer XXX" should only be used on answer side.
The user can set the same binding to multiple action, so in particular, they can set a binding to both "Show answer" and "answer XXX" if they want, which would allow to control whether the answer binding also cause a flip.

Bindings for "show answer" and "answer XXX" are single side only

---

AnkiDroid/src/main/java/com/ichi2/anki/FieldEditLine.kt
AnkiDroid/src/main/res/layout/card_multimedia_editline.xml
AnkiDroid/src/main/res/values/16-multimedia-editor.xml

This was missing. And the sticky was really not clear. Admittedly, still not clear if you don't know what "sticky" mean but it helps and can be searched online.

Add tooltip in note editor

---

AnkiDroid/src/main/java/com/ichi2/libanki/Notetypes.kt

There was no reason:
* to have as input a int, while the ID is a long
* initialize the HashMap twice
* have a name starting with _ while we can use LibAnkiAlias
Admittedly, this is a purely theoretical concern. The chance of two distinct id having the same int value would be 1 over 2^32 (assuming that time is correctly counted in milisecond.), that is, one over 4 billion. And I am too lazy to apply the birthday paradox formula to find the risk of actual collision in one collection and over all collections

NF: Correct NoteType cache

---

AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt

Handle changes with opExecuted instead of using an activity result
Similar to https://github.com/ankidroid/Anki-Android/pull/18273/commits/ad778b9f02042acc92b076231b1d9af2ec3301a4
* Fixes #18405
Emulator 35:
1. Have an Image Occlusion Note
2. Go to the Browser and preview an Image occlusion note
3. Edit the note
4. See the changes

fix(previewer): update after IO changes

---

gradle/libs.versions.toml

Update outdated Apache changelog URLs in `gradle/libs.versions.toml` to reflect the new structure (`changes-report.html` → `changes.html`).
* Fixes AnkiDroid/Anki-Android#18368
Replaced Apache changelog URLs ending in `changes-report.html` with `changes.html` wherever required in the `toml` file.
- This is a metadata-only change.

chore: Update Apache changelog URLs to new structure

---

AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckNode.kt
AnkiDroid/src/test/java/com/ichi2/libanki/DeckNodeTest.kt

This addresses a bug where searching for a sub-deck in the deck picker would fail to return the expected deck if one of its ancestor decks was collapsed. For example, if a user has the deck structure `Science::Math::Algebra::Group` and the Math deck is collapsed, searching for "Group" would not yield the `Science::Math::Algebra::Group` deck. This is not ideal, as users should not need to remember the collapsed state of parent decks when searching for a specific sub-deck.
* Fixes #18287 
When searching, we'll ignore collapsed state and always search sub-decks.
Manual testing + unit tests.
[Screen_recording_20250511_010042.webm](https://github.com/user-attachments/assets/86415584-6675-487d-917b-70ef18704b98)

Allow search to show subdecks if they match the searched term

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt

The exception was happening because the user started the study process using the keyboard shortcut when the collection was empty. With the fix applied studying will be allowed only when decks are present(the decks adapter is not empty).
* Fixes #18234
Used the _S_ keyboard shortcut to start studying on a empty/non-empty collection. Also, checked other shortcuts with an empty collection.

Fix crash when using the study keyboard shortcut on an empty collection

---

AnkiDroid/src/main/java/com/ichi2/anki/AndroidTtsPlayer.kt
AnkiDroid/src/main/java/com/ichi2/anki/TtsVoices.kt
AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardMediaPlayer.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/viewmodel/TtsVoicesViewModel.kt

LeakCanary reported that the TextToSpeech (TTS) instance was retaining a reference to the Context and causing it to outlive its intended lifecycle.
* Fixes a memory Leak caused be TTS Instances in Reviewer instances (more accurately CardMediaPlayer)
To prevent context leaks, TTS should be initialized with a Context that has the longest possible lifetime — typically the application context. Fortunately, the createTts function already defaults to using the application context, so we can fix the leak simply by no longer explicitly passing a shorter-lived context.
Before
https://drive.google.com/file/d/1McuB-l8J3NvxyE7sziTffac5yVwuUJkg/view?usp=sharing
After
https://drive.google.com/file/d/1MNfin0v-G3gcgbIUmPO2XTU0LuPmWSIt/view?usp=sharing
This can be verified by adding {{tts en_US:Front}} to …

Avoid context leak in TTS Player by using ApplicationContext

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt

When editing a card in the CardBrowser, after scrolling down and selecting a card at the bottom of the list, the scroll position is lost when returning to the CardBrowser.
https://github.com/user-attachments/assets/4728dc4d-6032-4d28-aa27-3e151b8c7e44
* Fixes #15993 
I added several breakpoints in the code and debugged the process of editing a card in the CardBrowser. After scrolling down, selecting a card at the end of the list, and saving it, I noticed that the scroll position was not being correctly stored when clicking on the card. As a result, when returning to the CardBrowser after the edit, the scroll would not maintain the expected position and would return inconsistently.
I now save the position of the first visible item when clicking on a card (onTap()), and when returning to …

Fix #15993: Scroll position wrong after editing

---

AnkiDroid/src/main/res/values/01-core.xml

The main goal of this PR is to ensure that all strings get a comment. While I used to naively think that most string were clear, and that translators would be able to figure out what they were translating, I realized, looking at the French translation, that it's not actually the case.
Instead of just fixing the French translation, I prefer to improve the process so that AnkiDroid can be correctly translated in all languages.
In particular, some strings are used in multiple context. E.g. as a button and the title of the dialog/view opened by this button. In English, it's certainly correct. In French it usually is too. I have no idea whether it's correct in all other languages. By letting the translators know that the strings is used in both context, they can provide feedback if ever they …

Add comment to core

---

AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt

When an alert dialog appears after entering incorrect credentials in the sync page, pressing the Enter key only selects the "OK" button instead of triggering it. This PR modifies the behavior so that pressing Enter directly triggers the positive button action, making the user experience more intuitive.
* Fixes #18340
Added an extension function setupEnterKeyHandler() to handle Enter key presses in AlertDialogs
Modified the existing show() extension function to apply this handler to all dialogs created through the builder pattern
The handler detects Enter key presses and simulates a click on the positive button if it exists and is enabled
Manually verified with the following steps:
Without an AnkiWeb account on AnkiDroid
Attempted to sync
From the sync page, entered an email and wrong …

Fix: Enter triggers OK without extra press

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/browser/BrowserMultiColumnAdapter.kt
AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DiscardChangesDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/NoteEditorLauncher.kt
AnkiDroid/src/main/res/layout-xlarge/card_browser.xml
AnkiDroid/src/main/res/layout/card_browser.xml
AnkiDroid/src/main/res/layout/cardbrowser.xml
AnkiDroid/src/main/res/values/07-cardbrowser.xml
AnkiDroid/src/main/res/values/attrs.xml
AnkiDroid/src/main/res/values/theme_black.xml
AnkiDroid/src/main/res/values/theme_dark.xml
AnkiDroid/src/main/res/values/theme_light.xml
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/browser/CardBrowserViewModelTest.kt

This feature aims to enhance the CardBrowser by adding a NoteEditor. This will allow users to edit card side by side on large screens
1. Attach NoteEditor to CardBrowser
2. Move NoteEditor menu to CardBrowser menu
3. Hide fragment when deck is empty
Medium Tablet API 34
https://github.com/user-attachments/assets/78ada4c3-906a-402b-9432-a9e8691de71b

[GSoC'24] Add NoteEditor to CardBrowser

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.kt

Speeds up dialog appearance
This takes > 100ms on my phone, and was reported to take >1s on larger collections
* Fixes #18416
* load 'defaults' async
* if it loads before we build the initial dialog, no change
* if it loads after the initial dialog, if appropriate, update the UI to disable 'increase limit' options
* if a 'increase limit' option is clicked
* wait for defaults to load, and inform the user if unavailable
Tested with `delay(5_000)` inside loadCustomStudyDefaults
* menu items were made unavailable
* Clicking the item worked if valid
* Clicking the item showed a snackbar if invalid, dialog was still usable
Issue introduced in caadde7034cd4bc559f5e424e8a786f7ba1ecca1

fix(custom-study): defer loading of 'customStudyDefaults'

---

AnkiDroid/src/main/java/com/ichi2/libanki/ChangeManager.kt
AnkiDroid/src/main/res/values/01-core.xml
AnkiDroid/src/main/res/values/02-strings.xml
AnkiDroid/src/main/res/values/10-preferences.xml
AnkiDroid/src/main/res/values/11-arrays.xml
AnkiDroid/src/main/res/values/attrs.xml
AnkiDroid/src/main/res/values/preferences.xml
AnkiDroid/src/main/res/values/theme_black.xml
AnkiDroid/src/main/res/values/theme_dark.xml
AnkiDroid/src/main/res/values/theme_light.xml
AnkiDroid/src/main/res/values/theme_plain.xml
AnkiDroid/src/main/res/xml/preferences_dev_options.xml

Those strings were found by looking for "reviewer" (case insensitive) in the values folder. And also trying to look at experimental settings for the new reviewer.
This is consistent with Anki documentation. And more consistent with English it seems.
It may be worth waiting for
https://github.com/ankitects/anki-manual/issues/341 to be resolved by Dae in case we want to rename the screen to Study screen.
I must note that changing a string comment don't require a new translation. So the translators will only have to retranslate the strings that actually changed.
Also, given how badly "reviewer" was translated in French, (And I suspect in other language) a new translation will certainly be an improvement.

Replace "reviewer" by "Study screen" in string

---

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/NoteTypeFieldEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsArrayAdapter.kt
AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
AnkiDroid/src/main/java/com/ichi2/libanki/DB.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt
AnkiDroid/src/main/java/com/ichi2/libanki/NotetypeJson.kt
AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckNode.kt
AnkiDroid/src/main/java/com/ichi2/preferences/StepsPreference.kt
AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt
api/src/main/java/com/ichi2/anki/api/Utils.kt
lint-rules/src/main/java/com/ichi2/anki/lint/utils/StringFormatDetector.kt

Small fix for a lint warning related to the usage of the trim() function. I did this mostly because when the code quality action fails these warnings appear and I have to scroll through all of them to see the actual errors(ex. strings issues). See a [failed action run](https://github.com/ankidroid/Anki-Android/actions/runs/15511609111/job/43673269978).
Ran the tests.

Fix lint warnings related to trim() function

---

AnkiDroid/src/main/res/layout/cardbrowser.xml

Added in f0e4ceb6237002ed3c9ab21b99081fc744b930fd for flags 
This was reverted, but the padding remained
This caused blank space after scrolling to the bottom of the list in the Browse window

improvement(browse): remove bottom padding

---

AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/Gesture.kt

Maracas emoji showed a tofu on API 30
* Fixes #17090
* Don't show the emoji if unavailable
API 30
⚠️ EmojiCompat bundle was tested and adds 9.8MB to the app size

fix: Remove 'shake device' maracas emoji [<= API 30]

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/RecyclerFastScroller.kt
AnkiDroid/src/main/java/com/ichi2/anki/utils/Time.kt
AnkiDroid/src/main/java/com/ichi2/utils/ViewUtils.kt
AnkiDroid/src/main/res/layout/cardbrowser.xml

Cause: #16620 (https://github.com/ankidroid/Anki-Android/commit/da72986f354022cb1ac3cc6245a81c2994e512b9) changed from a ListView to a RecyclerView and scrollbars were not included
NOTE: commit above message is incorrect due to a bad fixup
* Fixes #17786
`recycler-fast-scroll` [Apache 2.0] was unmaintained but seemed like a reasonable solution.
So it was vendored, refactored and used
https://github.com/pluscubed/recycler-fast-scroll/tree/master
S21. Colors are the same in night and light mode. Performance appears to be GREAT, but we can probably improve further.
I could not get  `fastScrollEnabled` to work on a RecyclerView, and the visual indicator without allowing a user to scroll quickly was insufficient
I tried `com.simplecityapps.recyclerview_fastscroll.views`
* Rendering was slow
* …

improvement(browse): re-implement scrolling 

---

AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt

the default 'open' transition is too quick in some devices
* Fixes #18324
Replace the old transition with the Android's standard `Fade` transition
Emulator API 35
https://github.com/user-attachments/assets/bf8e503c-2008-4f3e-acba-4b4d9d18cd0b

feat(settings): change fragment transition

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/deckpicker/DisplayDeckNode.kt
AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckNode.kt
AnkiDroid/src/test/java/com/ichi2/anki/DeckAdapterFilterTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/DeckNodeTest.kt

When searching for decks in the main menu, parents of matching decks are also rendered but their expand/collapse toggles were unnecessary as the toggles don't work during a search. This PR aims to not render those toggles at all.
Note that toggles for matching decks and their children are still active and functional.
* Fixes #18278
* Fixes #18379 
Created a new property for `DeckNode`, namely `var matchingSearchOrChild: Boolean`. This is set to `true` for all decks matching the search query or having an ancestor which matches the query. Only these decks have active and functioning toggles. The other visible decks will not have their toggles rendered. This requires updating the diff checker for the list adapter to also check for update in the `matchingSearchOrChild` property. Since both …

Deck toggles should not show when inapplicable in a search

---

AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt

I haven't paid attention to the interaction with `type-in answer` when I implemented keybinds for the new reviewer. 
Reproduction steps
1. Start reviewing a `type-in answer` card
2. While focusing the type answer input, type a letter assigned to a keybind (e.g. the default `E` shortcut for editting a note)
This doesn't affect the old reviewer
Check if the type answer container is focused when a key is captured, like the old reviewer does
Emulator API 35 with the steps above

fix(new reviewer): keybinds triggered when using type answer

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/browser/BrowserMultiColumnAdapter.kt
AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
AnkiDroid/src/main/res/layout-xlarge/card_browser.xml
AnkiDroid/src/main/res/layout/card_browser.xml
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/browser/CardBrowserViewModelTest.kt

Requested by @BrayanDSO
* Fixes #17901
See commits:
1. Create fragment and move UI elements there
2. define accessors for UI elements via `cardBrowserFragment`
3. Go through each usage of accessors and move inside fragment
4. finally, remove the `cardBrowserFragment`, it became test only
----
* fix: maintain selection after selecting flag
* fix: don't show focused row if non-fragmented
* Unit tests
* Google Pixel 9 Pro
* API 34 tablet
* One bug, also present in `main` : https://github.com/ankidroid/Anki-Android/issues/18462
Easier than expected. There's more rounds if we want to tackle the menu 
I feel I did something wrong....

refactor(card-browser): Convert to fragment (and fix a few issues)

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsArrayAdapter.kt

the tags:
```
#AK_Step1_v12::#Pixorize::03_Pharmacology::22_Cardiovascular_(New)::01_Ivabradine
#AK_Step1_V12::#Pixorize::03_Pharmacology::22_Cardiovascular_(New)::02_Nitroprusside
```
Caused `02_Nitroprusside` to be a top level deck, and corrupted the stack calculations
* Fixes #18481
Tags are case insensitive, and we forgot a check
Note the two parent tags with different 'v' casing above
```diff
- _v12
+ _V12
```
Use case insensitive compare
API 34 Tablet emulator

fix(tags): nesting broken if casing differed

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteTypeFieldEditor.kt

If a user tried to make a change after setting the hint, it failed
* Fixes #18501
The other methods call `initialize()`, so do it here
* Google Pixel 9 Pro, Android 15
* Add note type (Clone Basic)
* set language hint on field
* Delete Field
No crash
This class is very weird, needs rewrite.

fix(field-editor): changes after languageHint crashed

---

AnkiDroid/src/main/java/com/ichi2/anki/preferences/ControlsSettingsFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/ControlsTabPreference.kt
AnkiDroid/src/main/res/layout/controls_tab_layout.xml
AnkiDroid/src/main/res/layout/tab_layout.xml
AnkiDroid/src/main/res/xml/preferences_controls.xml

since Preferences are RecyclerView items, if the tab layout isn't visible when the view is created, its view won't exist and that leads to a crash.
to configure a preference view dynamically, the alternative is to create an individual preference class
* Fixes #18498
Emulator 35
https://github.com/user-attachments/assets/14452e58-74f2-4d02-84e4-ce9cf9004ae6

fix: controls settings crash in landscape mode

---

AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/TagLimitFragment.kt

A custom study error returned a backend error, but the error should not have been reported to ACRA
* Fixes #18500
* Fixes #18505
* define and use `skipCrashReport`
* ⚠️ on all `BackendException`s for now: backend could provide more granularity, but doesn't
* Pass in ArrayList to fragment result to fix 18505
A log was added for a pending crash report
* new collection
* add a card
* custom study: study ahead
* no cards found
----
For 18505, errors are no longer in logcat

fix: Custom study error caused crash report & logcat issues with TagFragment

---

gradle/libs.versions.toml

When you see this, please:
* replicate a panic in the emulator
* merge + publish an alpha 
* Fixes #18512
* https://github.com/ankidroid/Anki-Android-Backend/pull/530
```
2025-06-14 23:26:57.589  6629-6914  rsdroid::logging        com.ichi2.anki.debug                 E  Panic at anki/rslib/src/storage/note/mod.rs:73: assertion `left == right` failed
left: 1749940017552
right: 0
2025-06-14 23:26:57.591  6629-6914  rsdroid::logging        com.ichi2.anki.debug                 E  Panic at anki/rslib/src/backend/mod.rs:122: called `Result::unwrap()` on an `Err` value: PoisonError { .. }
2025-06-14 23:26:57.593  6629-6629  rsdroid::logging        com.ichi2.anki.debug                 E  Panic at anki/rslib/src/backend/mod.rs:122: called `Result::unwrap()` on an `Err` value: PoisonError { .. } …
```

build(deps): 0.1.53-anki25.02.7 / display panics in ACRA

---

AnkiDroid/src/main/res/drawable/black_round_alert_dialog_background.xml
AnkiDroid/src/main/res/values/theme_black.xml

Besides the linked issue this(first commit) also fixes a ui issue in manage notetypes. See images below:
Manage notetypes issue in black theme:
<details>
<summary>
Before the fix
</summary>
</details>
<details>
<summary>
After the fix
</summary>
</details>
How some of the alert dialogs look after applying the fix:
<details>
<summary>
New dialogs images
</summary>
</details>
* Fixes #18535
Checked the app dialogs.

Fix two ui issues when using the black theme

---

AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DebugInfoService.kt

In Markdown, a line break is 2 spaces followed by a newline
This makes them look a little better if a user doesn't add a code fence
AnkiDroid Version = 2.21alpha20-debug (b734b2aee0df6da15dbca001768e4e5de0cdaeec)  
Backend Version = 0.1.54-anki25.02.7 (25.02.7 98253c81cb3c4d203acec48d6eae6b488bf484d0)  
Android Version = 15 (SDK 35)  
ProductFlavor = play  
Device Info = Google | google | caiman | caiman | Pixel 9 Pro | caiman  
Webview User Agent = Mozilla/5.0 (Linux; Android 15; Pixel 9 Pro Build/BP1A.250505.005.A1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/137.0.7151.88 Mobile Safari/537.36  
ACRA UUID = 5ae2ce0e-ed23-43f7-9219-b2a8050e754e  
FSRS = 2.0.3 (Enabled: true)  
Crash Reports Enabled = false

improvement(debug-info): improve newlines

---

AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncMediaWorker.kt
AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt
AnkiDroid/src/main/java/com/ichi2/utils/HandlerUtils.kt
AnkiDroid/src/main/res/values/sentence-case.xml
AnkiDroid/src/test/java/com/ichi2/anki/ui/internationalization/SentenceCaseTest.kt

Special thanks to [Enchantable](https://www.reddit.com/user/Enchantable/) on Reddit for the diagnostic help!
If a media sync is attempted with a closed collection, it raises:
```
Panic at anki/rslib/src/backend/sync.rs:249: called Option::unwrap() on a None
```
Which poisons the collection for all future accesses
```
Result::unwrap() on an Err value: PoisonError { .. }
```
* Fixes #17382
* Fixes #18542
* Fixes Part of #15760
Our fix ensures an open collection, and throws if this is not the case, but does NOT use `withCol { }`, as this blocks the queue of operations to the backend until it's completed (even if done in a background thread)
* Dismiss a dialog safely
*  Fix by a try...catch, which needed to be on the main thread  
* Fix a title
* Standard `sentence-case` stuff …

Fix: Media Sync PoisonError, and a couple of media sync issues

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SchedulerUpgradeDialog.kt
AnkiDroid/src/main/res/values/11-arrays.xml
AnkiDroid/src/main/res/values/constants.xml

and updated key `scheduler_upgrade_faq_url` => `link_scheduler_upgrade_faq`
* Unblocks #18548
⚠️ Untested; android studio refactor for the rename + a cut/paste

chore: move link to constants.xml

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/AsyncDialogFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
AnkiDroid/src/test/java/com/ichi2/anki/servicemodel/PreferenceUpgradeServiceTest.kt

* Fixes #18527
use `AnkiDroidApp.context`
* Tested copy debug info
* Tested with the following, still copies
```patch
Subject: [PATCH] fix(copy-debug-info): crash if Context is null
Fixes 18527
---
Index: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/AsyncDialogFragment.kt
<+>UTF-8
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/AsyncDialogFragment.kt b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/AsyncDialogFragment.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/AsyncDialogFragment.kt	(revision bdf1b3eb5a1c5eeec293fa67380476ede1d73d18)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/AsyncDialogFragment.kt	(date …
```

fix(copy-debug-info): crash if Context is null 

---

AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/GestureParser.kt

* Fixes part of #18559
I suspect that getting an index of `4` in an scenario where only `0, 1 or 2` should be returned is caused by the `WebView` scale initial value not being set.
To avoid deeper bugs (like a gesture mapped incorrectly), and also taking advantage of the fact that the new reviewer is a developer option, I'm keeping the offensive programming approach of failing fast, but now with improved logging.

chore: improve logging of invalid index issue in new reviewer

---

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
AnkiDroid/src/main/res/layout/card_template_editor_item.xml
AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt

- Deprecate the editor title
- Wrap `CardTemplateEditor` screen inside a MaterialCardView when fragmented.
- Launch focus when `CardTemplateEditor` is opened.
* #18511 
* #18560
This PR consists of 3 Commits:
1. The first commit contains deprecates the editor title in `CardTemplateEditor`:
- Removed from setCurrentEditorView
- Updated all instances of setCurrentEditorView being called from both `CardTemplateEditor.kt` and `CardTemplateEditorTest.kt` 
- Removed title_edit FixedTextView from `card_template_editor_item.xml` and all references to it.
2. The second commit Wraps the `CardTemplateEditor` edit area in a MaterialCardView:
- Checks if editor is fragmented, and injects the edit area ScrollView into a MaterialCardView
- Sets the top margin of …

Refactoring Card editor [Deprecate editorTitle, wrap in CardView, show focus]

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt

... Should not suggest that a user adds cards
* Fixes #18586
* Pixel 9 Pro Emulator, API 36
* Clicking an empty filtered deck now shows the Congrats Screen and allows a user to select options

fix(deck-picker): clicking on an empty filtered deck

---

AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt

the backPressed callbacks are disabled when the fragment is created, and get enabled when the backstack changes with the backstack listeners
The issue was that after an activity recreation, the callbacks weren't being enabled because there was no backstack change
So, enabling them manually when the view is created fix that
* Fixes #18580
Same steps of the issue in an SDK 35 emulator

fix(preferences): fragment back stack being reset

---

AnkiDroid/src/main/assets/scripts/ankidroid.js
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/GestureParser.kt

* Fixes part of #18559
- some traces still haven't been diagnosed. 562788464650b4391ad6e254fc7b6e974f49b598 should shed a light after it goes to a beta
Use pageX/Y instead of clientX/Y to handle the scrolling
Galaxy S23, Android 15
1. Have a deck with content enough to demand being scrolled down
2. Scroll down
3. Tap in the bottom row
Also checked the same thing with the screen zoomed in

fix(new reviewer): gestures crash when scrolled

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.kt

We have user feedback that our logic is incorrect
I have not looked into this deeply, and the outcome was unintuitive, so disable it for now
https://forums.ankiweb.net/t/ankidroid-2-21-beta-feedback/62992/2
Minimal: trivial change; Briefly opened to ensure the screen still worked and items were no longer disabled on a new deck with 1 due card

fix(custom-study): stop disabling 'extend' options

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/settings/Prefs.kt
AnkiDroid/src/main/res/layout-xlarge/card_browser.xml

- Make cardBrowser Resizable
Consists of two commits:-
1. The first commit makes cardBrowser Resizable:
- Implements the ResizablePaneManager util class similar to other resizable screens
2. The second commit refactors all resizable screens:
- Uses seperate shared prefrences for all resizable screens called 'dev-ui' to avoid crowding existing shared pref.
Tested on the following Android Emulators:
Pixel Tablet API 35
Large Desktop API 34
Screenshots of affected screen in different themes:
1. Black Theme:
2. Plain Theme:
3. Default Light Theme:
4. Default Dark Theme:
Commit 2 Test:
[sharedperf.webm](https://github.com/user-attachments/assets/a5644816-f106-481f-8615-d5db3a560807)

Make cardBrowser Resizable and refactor shared pref of resizable screens into seperate shared pref

---

AnkiDroid/src/main/assets/scripts/js-api.js
AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
AnkiDroid/src/test/java/com/ichi2/anki/AnkiDroidJsAPITest.kt
AnkiDroid/src/test/java/com/ichi2/testutils/JsonUtils.kt

- get and set NoteTags does not need a noteId var anymore
* Fixes #17716
Fixed UnitTests

Deprecate noteId var from getNoteTags in Js-API

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Notetypes.kt
AnkiDroid/src/test/java/com/ichi2/testutils/TestClass.kt

Since we moved to Kotlin, we no longer need to worry about `@throws`, therefore can inline:
* addTemplateInNewNoteType -> addTemplate
* addFieldInNewNoteType -> addFieldLegacy
* Issue #18015
* https://github.com/ankidroid/Anki-Android/pull/18565

refactor(libanki): inline unnecessary methods

---

AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/AnswerTimer.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/AnswerTimerStatus.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerViewModel.kt
AnkiDroid/src/main/res/layout-sw600dp/reviewer2.xml
AnkiDroid/src/main/res/layout/reviewer2.xml

localized below the Count numbers to avoid losing screen space
1. Add an improved subclass of `Chronometer` to handle configuration changes properly
2. Add the Timer below the Count numbers
3. Setup the timer
Emulator SDK 35:
https://github.com/user-attachments/assets/9a2a7f1c-00cc-4fe3-bafd-85ce80480e19
Android 15 phone (Galaxy S23):
https://github.com/user-attachments/assets/5aae8232-eec6-47fd-ad79-1980f6f119f2
1. Had heard before about ConstraintLayout [Flow](https://developer.android.com/reference/kotlin/androidx/constraintlayout/helper/widget/Flow), but never used it until now
2. You can force the emission of the same value in MutableStateFlow by overriding equals() and hashCode() https://stackoverflow.com/questions/62331931/mutablestateflow-is-not-emitting-values-after-1st-emit-kotli …

feat(new reviewer): answer timer

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
AnkiDroid/src/main/java/com/ichi2/anki/reviewer/Binding.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Note.kt
common/build.gradle.kts
common/src/main/java/com/ichi2/anki/common/utils/StringUtils.kt
common/src/test/java/com/ichi2/anki/common/utils/StringUtilsTest.kt

primarily for:
* emptyStringArray
* Issue #18015
*  #18565

refactor: move `StringUtil` to `common` module

---

AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt

No longer blocks the collection
Noticed while looking into https://github.com/ankidroid/Anki-Android/issues/18660
* https://github.com/ankidroid/Anki-Android/issues/18660
Briefly opened Image Occlusion, added a logcat entry to prove the call was made and still works

perf: speed up i18nResourcesRaw

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt

This is experimental:
I believe this is a race condition between `saveEditedCard` and `forceRefreshSearch` - `saveEditedCard` performs `updateList` -> `notifyDataSetChanged()`
If we refresh the search, then the results may be cleared while this is occurring via `clearCardsList()`
* Fixes #17759 (hopefully)
Updating the search is now lightning-fast, so just rerun it
Pixel 9 Pro
* edited a note in cards mode by tapping the row
* edited a note in cards mode by long pressing -> edit note  
* edited a note: filled in a field, and more cards were added to the list

fix(browser): maybe fix crash after editing note

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
AnkiDroid/src/main/java/com/ichi2/anki/reviewer/EaseButton.kt
AnkiDroid/src/main/java/com/ichi2/anki/reviewer/PreviousAnswerIndicator.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerViewModel.kt
AnkiDroid/src/main/java/com/ichi2/libanki/sched/DummyScheduler.kt
AnkiDroid/src/main/java/com/ichi2/libanki/sched/Ease.kt
AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt
AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/EaseTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerKeyboardInputTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerNoParamTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/AbstractSchedTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/CardTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.kt
AnkiDroid/src/test/java/com/ichi2/libanki/SchedulerTest.kt

Better than moving to `CardAnswer.Rating` due to
`CardAnswer.Rating.UNRECOGNIZED`
* #18015
* https://github.com/ankidroid/Anki-Android/pull/18565

refactor: move `Ease` to `libAnki` module

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/BackendImporting.kt
AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/Undo.kt
AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
AnkiDroid/src/main/java/com/ichi2/anki/deckpicker/DeckPickerViewModel.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
AnkiDroid/src/main/java/com/ichi2/anki/mediacheck/MediaCheckViewModel.kt
AnkiDroid/src/main/java/com/ichi2/anki/observability/OpChangesNotifier.kt
AnkiDroid/src/main/java/com/ichi2/anki/pages/CongratsPage.kt
AnkiDroid/src/main/java/com/ichi2/anki/pages/DeckOptions.kt
AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/AppearanceSettingsFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/ReviewingSettingsFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt
AnkiDroid/src/main/java/com/ichi2/anki/scheduling/ForgetCardsDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/scheduling/SetDueDateViewModel.kt
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/SchedulerService.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerViewModel.kt
AnkiDroid/src/main/java/com/ichi2/libanki/ChangeManager.kt
AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
AnkiDroid/src/test/java/com/ichi2/testutils/TestChangeSubscriber.kt

* due to withCol dependency
* Issue #18015
* #18565

refactor: move `undoableOp` to `AnkiDroid` module

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/Shared.kt
AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.kt
AnkiDroid/src/main/java/com/ichi2/anki/CollectionManager.kt
AnkiDroid/src/main/java/com/ichi2/libanki/BackendImportExport.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
AnkiDroid/src/main/java/com/ichi2/libanki/CollectionFiles.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Storage.kt

refactor: move `CollectionFiles` to `libAnki` module

---

AnkiDroid/src/test/java/com/ichi2/anki/browser/CardBrowserViewModelTest.kt

Post-commit analysis did not like methods named 'suspend'

dev: improve commit speed

---

AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/VideoPlayer.kt
AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt
AnkiDroid/src/main/java/com/ichi2/utils/HtmlUtils.kt
common/src/main/java/com/ichi2/anki/common/utils/StringUtils.kt

Removes an Android dependency from libAnki
`androidx.core.text.htmlEncode => android.text.TextUtils.htmlEncode`
* Issue #18015
* #18565

refactor: reimplement 'htmlEncode' in `common`

---

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt

In card template editor, set the cursor at the start
Before: when opening the template editor, the cursor is at the end of
the template. If the template is too big, the cursor don't happen and
the user don't see this is an editable field.
https://github.com/user-attachments/assets/e49829f9-af85-4523-b0de-cda1403bd2bf
After: the cursor is at character 0, so its always seen by the user.
https://github.com/user-attachments/assets/137a17eb-f1b4-427a-a9a1-4e00c17789c0
Testing on simulator, it seems that `setSelection` was ignored unless
the view already had the focus.
Fixes #18637

In card template editor, set the cursor at the start

---

AnkiDroid/src/main/res/xml/preferences_custom_buttons.xml

'always show' -> 'menu only'
I missed that 0 was the value, and not the index
I believed the index and the value matched
* Follow up from #18645
* Issue #17701
Fix the default value
Pixel 9 Pro: uninstalled the app, reinstalled and `Menu Only` was the default in app bar buttons
I'd refactor the control to make it obvious, but we'll be getting rid of it soon

improvement: 'auto advance' menu visibility

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt

When app like WhatsApp shares a file using an Intent, it typically passes a content:// URI (from its ContentProvider) and grants temporary URI permissions for:
- The specific component receiving the intent.
- Only during that activity's lifecycle — not globally or across app components like fragments in our case the MultimediaImageFragment
Its(Whatsapp) MediaProvider is not exported — meaning no other app can directly query it unless explicitly granted permission via intent.
So to fix this we needed to immediately internalizing the URI  in the Activity that received the intent.
* Fixes  #18660
By copying the image to internal storage (file://), we ensure persistent access without permission issues across fragments and then in fragment(MultimediaImageFragment) we check if we need to …

fix: multimedia URI `SecurityException`

---

AnkiDroid/src/main/res/layout/controls_tab_layout.xml

There was feedback stating that the tabs weren't very noticeable.
I don't think that matters much, they don't need any kind of special attention.
But I thought that adding icons to them would be okay
Emulator API 35

improvement(settings): add icons to controls tabs

---

AnkiDroid/proguard-rules.pro

Pending: https://github.com/ankidroid/Anki-Android/actions/workflows/compare_apk_size.yml
----
We got the following truncated stack trace due to proguard/minify
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.multimedia.MultimediaActivity}: android.os.BadParcelableException: Parcelable encountered IOException reading a Serializable object (name = com.ichi2.anki.multimedia.f)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4377)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4574)
...
at android.os.Looper.loop(Looper.java:393)
at android.app.ActivityThread.main(ActivityThread.java:9549)
at java.lang.reflect.Method.invoke(Native Method)
at …
```

fix(release): Unable to start activity: MultimediaActivity

---

AnkiDroid/src/main/java/com/ichi2/anki/reviewreminders/ReviewReminder.kt
AnkiDroid/src/main/java/com/ichi2/anki/reviewreminders/ReviewRemindersDatabase.kt
AnkiDroid/src/main/java/com/ichi2/anki/settings/Prefs.kt
AnkiDroid/src/main/res/values/preferences.xml
AnkiDroid/src/test/java/com/ichi2/anki/reviewreminders/ReviewReminderTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/reviewreminders/ReviewRemindersDatabaseTest.kt

Review Reminders database system.
- Created `ReviewRemindersDatabase`, which contains methods for reading and writing to a Preferences Datastore instance for storing review reminder data
- Created `ReviewReminder`, which defines the review reminder data class
- Created Robolectric unit tests for `ReviewRemindersDatabase` and `ReviewReminder`
- For GSoC 2025: Review Reminders
Using Preferences Datastore was the original method I proposed for storing review reminder data in my original project proposal: see [[1]](https://docs.google.com/document/d/1KMjnm6ol1M_VMAsg9V5Qb4XRZnEON-39gkzLkFe8q2Y/edit?tab=t.0#heading=h.o472euuadswv)
Why did I initially choose Preferences Datastore for storing review reminder data?
1. Google recommends using it over Shared Preferences: see …

Created ReviewRemindersDatabase and ReviewReminder

---

AnkiDroid/src/main/java/com/ichi2/anki/settings/Prefs.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt
AnkiDroid/src/main/res/values/preferences.xml
AnkiDroid/src/main/res/xml/preferences_reviewer.xml
AnkiDroid/src/test/java/com/ichi2/anki/analytics/PreferencesAnalyticsTest.kt

it doesn't make sense to go below the minimum value
for now, the setting becomes distinct from the one in `Accessibility` to avoid changes in the old reviewer
1. Go to settings
2. Check if `Answer button size` from the "Acessibility" and "New study screen" are independent
3. Check if the new study screen answer buttons size setting is reflected in the new reviewer

fix(new reviewer): answer button size

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CreateDeckDialogTest.kt

In Anki Desktop, creating a filtered deck suffixes a "+" if the deck name is already found.
Before this change, AnkiDroid edited the provided deck, rather than creating a new one
We now perform the same operation
* Fixes #18761
Tested via unit tests

fix(filtered-decks): handle duplicate name on creation

---

AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt

On API 33+, `onKeyDown(KEY_BACK)` was no longer fired, so `tryCloseWithResult `was not called
`onKeyDown(KEY_BACK)` was still called on API 32
* Fixes #18627
* Related to https://github.com/ankidroid/Anki-Android/issues/14558
To fix this, add API 33+ specific code to handle the
Android back button/swipe gestures
We won't keep the activity around forever, so it wasn't worthwhile rewriting it
Emulators: Pixel 6 Pro: SDK 32 and 33
* Add card with content: 'd' 
* Make filtered deck
* search: 'd'
* Physical back button
----
* Broken on SDK 33 before patch
* Passed on SDK 32 before patch
----
* Passed on SDK 33 after patch
* Passed on SDK 32 after patch
Broken in 0657cdb8deb45cc3f8e63ea25e97011c5829c84e enableOnBackInvokedCallback
https://developer.android.com/guide/navigation/custom-back/predic …

fix(filtered-decks): [API33+] rebuild after 'back' press

---

AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt
AnkiDroid/src/main/java/com/ichi2/anki/settings/Prefs.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/AnswerFeedbackView.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerViewModel.kt
AnkiDroid/src/main/res/drawable/ic_ease_again.xml
AnkiDroid/src/main/res/drawable/ic_ease_easy.xml
AnkiDroid/src/main/res/drawable/ic_ease_good.xml
AnkiDroid/src/main/res/drawable/ic_ease_hard.xml
AnkiDroid/src/main/res/layout-sw600dp/reviewer2.xml
AnkiDroid/src/main/res/layout/reviewer2.xml
AnkiDroid/src/main/res/values/10-preferences.xml
AnkiDroid/src/main/res/values/preferences.xml
AnkiDroid/src/main/res/xml/preferences_reviewer.xml
AnkiDroid/src/main/res/xml/preferences_reviewer_controls.xml

Adds grade feedback after answering a card, similar to what AnkiMobile does.
Differences from the old reviewer:
1. It uses different icons for each grade instead of dots.
- they are still small and non intrusive.
- different icons help understanding the grades' meaning, like `Hard` being a correct answer (depicted by using a small check icon)
2. They are at the screen bottom
- so they don't overlap with the `Mark` and `Flag` icons (AnkiMobile puts them at the top right corner)
- so they are better connected with the answer buttons
3. `Again` is in the left corner and the rest is in the right corner
- another way to differentiate correct answers from wrong one (some people in the anki community are really passionate about avoiding `Hard` misuse).
4. They are toggled with fadein/fadeout
- …

feat(new reviewer): answer feedback

---

AnkiDroid/src/main/java/com/ichi2/anki/pages/DeckOptions.kt

Softlock in the deck options when trying to view the manual offline
* Fixes #18526
I added a check inside `webView.evaluateJavascript("anki.deckOptionsPendingChanges()")` that calls `actuallyClose()` if the page could not be loaded
For testing I used my Android 16 phone. To reproduce the issue, the instructions from the linked issue can be used

Potential fix for Softlock in the deck options when trying to view the manual offline

---

AnkiDroid/src/main/assets/ankidroid.css

* Fixes a report from the forums https://forums.ankiweb.net/t/new-study-screen/63230/17 (also applies to the previewers)
Android 15, Galaxy S23:
<details>
</details>

fix: img max width in previewers and new reviewer

---

AnkiDroid/src/main/java/com/ichi2/anki/browser/ColumnSelectionDialogFragment.kt

Browser: 'Change Column' does not restore state correctly when 'Don't keep Activities' is turned on
* Fixes #18584
I used an onSaveInstanceState function to properly save the state of the List of available columns. This list is later on retrieved in the onCreateDialog function
For testing I used my Android 16 phone. To reproduce the issue, the instructions from the linked issue can be used

Fixed 'Change Column' does not restore state correctly

---

AnkiDroid/src/main/assets/scripts/ankidroid.js

Some cards may have tappable elements that were factored in an unusual way that `isInteractable` isn't able to catch (nor it is supposed to).
One example is the notetype created by this [addon](https://ankiweb.net/shared/info/1990296174), which seems to be popular
After some thought, I believe that `event.preventDefault();` may not be necessary here (although AnkiMobile has it).
After the fix, the unusually factored tappable elements now work, despite also triggering gestures (which needs the notetypes devs to add the [`tappable` class](https://docs.ankimobile.net/more.html#javascript) to make it mobile friendly)
Emulator API 35:
https://github.com/user-attachments/assets/27b3f3c6-f367-4fe1-bdb6-42155f385375
https://github.com/user-attachments/assets/29d22feb-2aec-4ee6-98c4-31ea6ce44602 …

fix(new reviewer): don't discard touches

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
AnkiDroid/src/test/java/com/ichi2/testutils/TestClass.kt

If an action was performed which did not update `studyQueues` then it would still update the undo status
* Fixes #18762
Unit test + brief manual test

fix(deck-picker): 'undo' menu item not updated

---

AnkiDroid/src/main/res/values/preferences.xml
AnkiDroid/src/main/res/xml/preferences_controls.xml
AnkiDroid/src/test/java/com/ichi2/anki/analytics/PreferencesAnalyticsTest.kt

somewhat unnecessary, didn't look good and took vertical space
Emulator API 36

tweak(preferences): remove general from 'Controls'

---

AnkiDroid/src/main/res/xml/preferences_previewer_controls.xml

use same icon for 'Replay media' in the `Reviews` and `Previews` tabs of Controls
Saw the layout previews in Android Studio

chore: use same icon for 'Replay media'

---

AnkiDroid/src/main/res/xml/preferences_controls.xml
AnkiDroid/src/main/res/xml/preferences_general.xml

from 'Controls' to 'General'
It made sense to be in 'Controls', when it was called 'Gestures', there were no key or joystick support, and there were no support for other screens like the previewer.
Now, it feel displaced in the 'Controls' category because it isn't related to any control.
Also, the dependency to 'Enable gestures' is soft, because disabling 'Enable gestures' doesn't remove the full screen navigation drawer behavior.
So, that dependency ends up being unnecessary.
<details><summary>Emulator API 36</summary>
https://github.com/user-attachments/assets/0917fe98-8940-4813-b7fd-3ac1127b6b94
</details>

move 'Full screen navigation drawer' setting

---

AnkiDroid/src/main/java/com/ichi2/anki/preferences/ControlsSettingsFragment.kt

this issue happened after I removed the `General` settings category on `Controls`
https://github.com/user-attachments/assets/b7b247b5-6f8c-4d19-b126-575df3f123b5
Remove only the items after the ControlTabsPreference. I tried to make a test for it, but had some trouble getting a reference to the TabLayout
Emulator API 36:
https://github.com/user-attachments/assets/1ac96aea-523a-4cd8-b17b-28c5d4e2d22f

fix: controls settings being removed after selecting tab

---

AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/deckpicker/DeckPickerViewModel.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/HeaderFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
AnkiDroid/src/main/java/com/ichi2/anki/reviewreminders/ScheduleReminders.kt
AnkiDroid/src/main/java/com/ichi2/anki/reviewreminders/ScheduleRemindersDestination.kt

- Refactored ScheduleReminders to take a ReviewReminderScope as an argument in `getIntent` to better enforce that callers should either trigger ScheduleReminders in deck-specific or global mode rather than leaving open the possibility of passing an incorrect deckId, etc. This was recommended by David.
- Made toolbar title use ReviewReminderScope to follow the above change
- Modified review reminder entry points to pass a ReviewReminderScope rather than the old `getIntent` arguments
* For GSoC 2025: Review Reminders
- I'm actually quite happy with this change, it feels very elegant. Both ReviewReminder and ScheduleReminders are now using the same sealed class to communicate a "scope", whereas previously they were each using slightly different methods to accomplish the same "scoping" …

ReviewRemindersScope for ScheduleReminders entry

---

AnkiDroid/src/main/java/com/ichi2/anki/reviewreminders/ReviewRemindersDatabase.kt

- Cleaned up docstrings in ReviewRemindersDatabase
- For GSoC 2025: Review Reminders
- Requested by Arthur
- Fixed typos and clarified wording
- Only comment changes

Improve ReviewRemindersDatabase docstrings

---

AnkiDroid/build.gradle

this keeps minSdk 23 APKs available for folks
Part of the release work today

build: retain latest 2.19 release when doing new releases

---

AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
AnkiDroid/src/test/java/com/ichi2/testutils/JvmTest.kt
AnkiDroid/src/test/java/com/ichi2/testutils/TestClass.kt
AnkiDroid/src/test/java/com/ichi2/testutils/ext/AnkiActivity.kt
build.gradle.kts
common/src/main/java/com/ichi2/anki/common/time/MockTime.kt
common/src/test/java/com/ichi2/anki/common/time/MockTimeTest.kt

I split this out from https://github.com/ankidroid/Anki-Android/pull/18813 to make it an easier review
* https://github.com/ankidroid/Anki-Android/pull/18813

refactor(libanki): begin removing AnkiDroid dependencies from `TestClass` 

---

AnkiDroid/src/main/java/com/ichi2/anki/preferences/AboutFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/scheduling/Fsrs.kt
AnkiDroid/src/test/java/com/ichi2/anki/scheduling/FsrsTest.kt

This was causing confusion for users
* Fixes #18825

feat: display user-facing FSRS version

---

AnkiDroid/src/main/java/com/ichi2/imagecropper/ImageCropper.kt
AnkiDroid/src/main/res/drawable/ic_flip_horizontal.xml
AnkiDroid/src/main/res/drawable/ic_rotate_right.xml
AnkiDroid/src/main/res/layout/fragment_image_cropper.xml
AnkiDroid/src/main/res/menu/image_cropper_menu.xml
AnkiDroid/src/main/res/values/02-strings.xml
AnkiDroid/src/main/res/values/16-multimedia-editor.xml

The image clopper screen's action bar color is inconsistent with the color of the status bar and the preceding screen ("Add image"). This PR intends to fix the inconsistency.
* Fixes #18832
- Remove the codes regarding the action bar color
- Change the icon references from the current icons (hard-coded in white color) managed in CanHub repository to the new icons managed in AnkiDroid repository.
- Use Google Material Icons for the new icons
- [Rotate](https://fonts.google.com/icons?selected=Material+Icons+Outlined:rotate_right:&icon.set=Material+Icons&icon.size=24&icon.color=%235f6368&icon.query=rotate)
- [Flip](https://fonts.google.com/icons?selected=Material+Icons+Outlined:flip:&icon.set=Material+Icons&icon.size=24&icon.color=%235f6368&icon.query=rotate)
Checked in a physical device …

fix: Image cropper screen action bar color is inconsistent with the preceding screen's one

---

AnkiDroid/src/main/java/com/ichi2/anki/reviewreminders/ReviewReminder.kt
AnkiDroid/src/test/java/com/ichi2/anki/reviewreminders/ReviewReminderTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/reviewreminders/ReviewRemindersDatabaseTest.kt

- Removed `ReviewReminderSnoozeAmount` as we will now be providing snooze settings at the app-wide level rather than the reminder-specific level; this reduces the complexity of the review reminders system for the user -- it is unlikely that a user will need to customize snoozing on a per-reminder basis
- Updated unit tests to adhere to this change
* For GSoC 2025: Review Reminders.
- Deletion!
- Tested on a physical Samsung S23, API 34.
- Unit tests pass.

refactor: remove granular snooze settings

---

AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt

If I open the study shortcut and the deck has no pending cards, the screen closes without any warning nor try to check if there are other decks to review
* Fixes the issue above
It adds the deck picker to the task stack in the Study shorcut like the deck specific shortcuts already do
https://github.com/user-attachments/assets/2e0c00e0-4f8d-4837-b27e-655ad22f3141
https://github.com/user-attachments/assets/67400ad2-a8ee-42f2-8ad6-0457ca196dd7

improve study shortcut

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt
AnkiDroid/src/main/res/values/02-strings.xml

Add a toast message ("Note saved") when the user saves a note and the app was launched via an external intent (e.g. from Chrome or Aedict).  
This improves the user experience by confirming the action before the activity closes.
* Fixes #18773 
- Checked for `NOTEEDITOR_INTENT_ADD` or `aedictIntent` in `onNoteAdded()`.
- Called `showThemedToast()` before `closeNoteEditor()` to ensure the toast appears before the activity is destroyed.
- Ensured the toast is shown only for externally-triggered note adds (not for standard app usage).
- Manually tested on a physical Android device:
- Opened Chrome, selected text, shared to AnkiDroid.
- Verified toast appears when note is saved and app closes.
- Also tested adding a note within the app to confirm toast does not appear in that flow.
- Used …

Added a toast message when a card is created

---

AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt

The cloze number should be incremented only in the increment mode, so when undoing it was incremented this PR fixes that behaviour 
* Fixes  #18811
NA
Pixel fold API35
[Screen_recording_20250710_000607.webm](https://github.com/user-attachments/assets/1df8d216-bea9-4e71-b684-57ff0124c8f2)
NA

fix: instant editor cloze number incrementing on undo

---

gradle/libs.versions.toml

Per [discussion here ](https://github.com/ankidroid/Anki-Android-Backend/pull/551#issuecomment-3066000871)- plan is:
- adopt this so we have current anki which will likely go live
- start pushing betas from main with a 2.22.0 release goal
(close and reopen once 0.1.58-anki25.07.2 is available [on maven here](https://repo1.maven.org/maven2/io/github/david-allison/anki-android-backend/))

build(deps): adopt Anki-Android-Backend 0.1.58-anki25.07.2

---

AnkiDroid/src/main/java/com/ichi2/anki/reviewreminders/ReviewReminder.kt

- Makes `ReviewReminderScope.DeckSpecific.getDeckName()` more readable
- Adds a logger for debugging purposes
* For GSoC 2025: Review Reminders
- It's a little refactor! Didn't really belong with any of the other atomic PRs I'm planning. Might as well get it in quickly.
- Tested on a physical Samsung S23, API 34.

refactor: clean up ReviewReminderScope.DeckSpecific.getDeckName

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt

"X cards shown" snackbar in the card browser stayed open indefinitely.
* Fixes #18686
Changed the snackbar duration from `LENGTH_INDEFINITE` to `LENGTH_SHORT`. Similar to the other snackbars. 
Emulator API 35

fix: "x cards shown" snackbar isn't automatically dismissed

---

AnkiDroid/src/main/java/com/ichi2/anki/deckpicker/DisplayDeckNode.kt

`TrimLambda` inspection
https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-main:lint/libs/lint-checks/src/main/java/com/android/tools/lint/checks/TrimDetector.kt
The Kotlin standard library `trim()` call takes an optional lambda \ to specify which characters are considered whitespace.
When converting Java code to Kotlin code, the converter will convert \ calls for Java's `s.trim()` into `s.trim() { it <= ' ' }`. This \ preserves the exact semantics of the Java code, but is likely not \ what you want: the default in Kotlin uses a better definition of what \ constitutes a whitespace character (`Char::isWhitespace`) and also \ results in less bytecode at the call-site.

lint: better trim() usage

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.kt

- When initializing the deck spinner in AddEditReminderDialog, I wanted to use initializeNoteEditorDeckSpinner, but it was annotated with MainThread which meant I couldn’t use withCol and would have had to use getColUnsafe, which I think we’re not supposed to use anymore? I wasn’t sure if I was allowed to refactor everything, so I created a new method that calls withCol internally and tried to copy-paste the format of the other initialization methods. Are these methods supposed to be annotated with MainThread? There’s an annotation at the top of the file marked “this class is a mess…” so I assume it’s due for a refactoring?
* For GSoC 2025: Review Reminders
- Adds a new method. Basically a copy-paste of other methods in this class. Attempts to conform to the existing code style rather …

feat(reminders): add ScheduleReminders DeckSpinner init method

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/LayoutValidationTest.kt
AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt
AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt
AnkiDroid/src/main/java/com/ichi2/widget/WidgetUtils.kt
AnkiDroid/src/main/res/drawable-v31/ic_anki_unthemed.xml
AnkiDroid/src/main/res/drawable-v31/ic_anki_unthemed_finish.xml
AnkiDroid/src/main/res/layout-v31/widget_small_unthemed.xml

MIUI doesn't support Material You well - the color is based on the system background color, with no means to disable it.
https://www.reddit.com/r/Xiaomi/comments/y6zclf/material_you_on_miui_13/
Since we are using a widget, we can't use custom themes as a fix
* Fixes #18869
Duplicate the assets/layout as unthemed and fix them there
Use the new layout for `miui` phones
`AdaptionUtil` code copied from 43151b618758c80b2bd4b7134f498a56f5b27170 and converted to Kotlin
Pixel 9 Pro (Android 15):
**after the PR**
**with `isMiui` enabled**
`circle_background` did not need to be duplicated as the background was tintable, just tinting the star was not possible
* Our emulator tests are running on a fairly old version of Android
**Duplicate unthemed widget icons:**
`@android:color/system_neutral1_100` …

fix(widget): disable "material you" if using MIUI

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
AnkiDroid/src/main/res/drawable/ic_deselect_white.xml
AnkiDroid/src/main/res/drawable/ic_select_all_white.xml
AnkiDroid/src/main/res/layout/cardbrowser.xml
AnkiDroid/src/main/res/menu/card_browser_multiselect.xml
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/browser/CardBrowserViewModelTest.kt

There was blank space, it made sense, and it meant we can remove two menu items
* Fixes #18572
I first added the toggle and removed 'select all' and 'select none' menu items if the user was in 'multi-select' mode
I was then frustrated that 'select none' disabled selection mode: the 'back' button was so close which did the same, so I changed the Card Browser to allow a user to be in selection mode with 0 rows selected.
This then meant a number of menu items were unusable, so I hid them. Only 'preview' remains
Unit tests were added
I have tested on a Google Pixel 9 Pro, and an Emulator 34 tablet
* Focused row functionality feels unchanged on the tablet
* Keyboard shortcuts did nothing (as expected)
* Menu items were removed if 0 items were selected
* Only 'preview' remains 
* Tested in …

feat(card-browser): add select all/none toggle in header 

---

.github/workflows/tests_emulator.yml

@david-allison noted in #18871 that our emulator tests were running on a pretty old emulator
This is true, and one of the reasons was a fear-inducing comment that the emulator one API over the one in use was flaky
Hard to test that except wait! We just merged the emulator test "flake hammer" so we can run a big batch on this API to make sure it's not flaky
I'll do that on my fork --> https://github.com/mikehardy/Anki-Android/actions/runs/16280413858

test: use api36 emulator for tests

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt

- Moving the toolbar implementation to the activity
- Cleanup warnings in NoteEditorFragment

Move mainToolbar to NoteEditorActivity and NoteEditorFragment NF cleanup

---

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt

Even when Undo is available (i.e., Undo action has its target), the undo action's tooltip just shows `Undo`
in contrast to the label in the overflow menu:
e.g.,
- `Undo Answer Card`
- `Undo Bury`
- `Undo Change Deck`
- `Undo Update Note` 
-  and `Undo Stroke` on whiteboard mode
This PR aims to resolve the inconvenience/inconsistency.
* Fixes #18904
Set the the undo action's title to the tooltip after the title is determined.
https://github.com/user-attachments/assets/dbb29889-8fd5-4be3-996a-d7ca61d70703
- Additionally checked the same operations with placing the undo action in the overflow menu. No unexpected results occurred.

fix: "Undo" tooltip doesn't show its target

---

AnkiDroid/src/main/java/com/ichi2/anki/reviewreminders/ReviewRemindersDatabase.kt
AnkiDroid/src/test/java/com/ichi2/anki/reviewreminders/ReviewReminderTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/reviewreminders/ReviewRemindersDatabaseTest.kt

- Since we are removing bulk-deletion functionality, we can delete the database methods that were added to facilitate it: `getAllDeckSpecificRemindersGrouped` and `editAllDeckSpecificReminders`
- Rewrote `getAllDeckSpecificReminders` to not rely on helper methods and be a little more functional in style
- Removed related tests
- Stops writing to the default SharedPreferences when storing review reminders, instead uses a new file
- Cleans up logic for backing up review reminders in the Database file into three methods: `getAllReviewReminderSharedPrefsAsMap`, `deleteAllReviewReminderSharedPrefs`, and `writeAllReviewReminderSharedPrefsFromMap`; these methods will be used by ScheduleReminders when the schema migration code is pushed
- Refactored tests to comply with the above changes
* For …

refactor: delete bulk deletion, use separate prefs file

---

AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/libanki/AbstractSchedTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/libanki/CardTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/libanki/CollectionTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/libanki/DecksTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/libanki/FinderTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/libanki/FlagTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/libanki/NoteTypeTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/libanki/SchedulerTest.kt
AnkiDroid/src/test/java/com/ichi2/testutils/JvmTest.kt
AnkiDroid/src/test/java/com/ichi2/testutils/TestClass.kt
libanki/testutils/src/main/java/com/ichi2/anki/libanki/testutils/ext/Collection.kt

I split this out from https://github.com/ankidroid/Anki-Android/pull/18813 to make it an easier review
* https://github.com/ankidroid/Anki-Android/pull/18813

refactor(libanki): finish removing AnkiDroid dependencies from TestClass

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsArrayAdapter.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialogViewModel.kt
libanki/src/main/java/com/ichi2/anki/libanki/Lang.kt

Switch to use the old tags dialog when selecting tags for custom studying to offer a better UX when selecting from a large amount of tags. The dialog was modified a bit to show only the tags for the study target deck.
Note I thought about adding a neutral button in the current _Study by tags_ option called _Legacy_ to have both the current and old tags options, but this felt confusing to the user as they are not identical in behavior and functionality.
Related to #18885 as a temporary ux improvement. The proper fix would be a new UI which I'm going to do later.
Checked the old tags dialog used when custom studying.

Use legacy tags dialog when selecting tags for custom studying

---

AnkiDroid/src/main/java/com/ichi2/anki/services/BootService.kt
common/src/main/java/com/ichi2/anki/common/annotations/LegacyNotifications.kt

This is the class that runs when the phone initially starts up. It listens to the system boot-completed intent and was previously used for the old studying notification system. However, it is messy and needs to be refactored. Most of its functionality will be replaced by my code. Here, I'm cleaning up the code I plan to keep and marking the code I plan to eventually delete.
- Add missing docstring and proper attribution for file creation to BootService -- I checked who created the file using `git blame`
- Use conditionals to gate where new review reminder code will be run
- Made it so that old notification code will only run if review reminders are disabled
- Renamed `sWasRun` Hungarian notation variable to be `wasRun`
- Used Intent constant instead of hard-coding `BOOT_COMPLETED_INTENT` …

refactor: prepare BootService for review reminders

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
AnkiDroid/src/main/res/layout/multiline_spinner_item.xml

Some labels in `Study by card state or tag` dropdown menu labels are relatively long, so they are prone to overflow on a single line.
This PR aims to resolve the issue.
* Fixes #18953
Use the existing `multiline_spinner_item.xml` instead of `simple_spinner_item` for layout
Before | After
---|---

fix: `Study by card state or tag` dropdown menu is prone to overflow

---

AnkiDroid/src/main/java/com/ichi2/anki/ui/ResizablePaneManager.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/ResizingDivider.kt
AnkiDroid/src/main/res/layout-xlarge/card_browser.xml
AnkiDroid/src/main/res/layout-xlarge/card_template_editor.xml
AnkiDroid/src/main/res/layout-xlarge/homescreen.xml
AnkiDroid/src/main/res/layout/resizing_divider_internal.xml

- Resizable divider onHover changes PointerIcon to a resizing indicator and sets divider to dragColor
- As suggested by @SanjaySargam this will add a onHoverListner to the `ResizablePaneManager` to show users that it is resizable
Tested on Chromebook emulator - API 34
[hover.webm](https://github.com/user-attachments/assets/07cb0549-ab77-460a-be58-03a3b18dee88)

feat: add hover effects to divider in ResizablePaneManager

---

AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncMediaWorker.kt
AnkiDroid/src/main/java/com/ichi2/utils/SyncStatus.kt

* Fixes #18937 (I hope)
Similar to #18893 and https://github.com/ankidroid/Anki-Android/commit/02deb0a0a5905f1cca91aa20cedf67c80cc1bc83 -> Check if the endpoint is empty before setting it (I didn't see these call sites before)
Emulator 34:
I can still sync the collection and media

fix(sync): empty endpoint

---

AnkiDroid/src/main/res/values/theme_black.xml
AnkiDroid/src/main/res/values/theme_light.xml

There was some accessibility warnings in the counts so I fixed them
Changed the colors to material colors that pass the accessibility scan

improve count color contrast to pass accessibility scanner

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt

Minor refactors on Resizable screens involving:
- Clean up unnecessary null checks for ResizablePaneManager, since fragmented check is only true when panes are non-null
- Clearer naming for leftPane and rightPane variables in ResizablePaneManager Calls

NF: Resizable Screens

---

AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt

* Fixes #18963
Remove backstack subscreens after opening a new primary section in big screens
https://github.com/user-attachments/assets/f99984e1-a7b4-48aa-a024-13cee1119f23
this was tough to figure out because of the backstack listener, search bar and the navigation itself
https://developer.android.com/reference/android/app/FragmentManager#POP_BACK_STACK_INCLUSIVE

fix: preferences panels overlaying each other on large screens

---

libanki/src/main/java/com/ichi2/anki/libanki/Media.kt
libanki/src/test/java/com/ichi2/anki/libanki/CollectionOnDiskTest.kt

'Create Collection', then 'Export' did not access `Media.dir`, which caused the export to fail
* Fixes #18990
* Broken in #18924 (3bbf49832b0a60758ef8d0b5264eee04eca9cc88)
This moved `collection.media` creation to `Media.dir:get`
past code was
```kotlin
val dir = col.collectionFiles.mediaFolder
init {
Timber.v("dir %s", dir)
val file = dir
if (!file.exists()) {
file.mkdirs()
}
}
```
Only unit tested

fix(libanki): create `collection.media` on collection init

---

AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt

* Fixes #18899 (I hope)
Check if the WorkManager is initialized before trying to cancel the work
I don't have a reproduction case, so I just tested opening the app, and the app still opens up

fix: sync worker not initialized crash

---

AnkiDroid/proguard-test-rules.pro
gradle/libs.versions.toml

required one proguard fixup since test dependencies don't test release mode often or well upstream and they forget things sometimes
This will obsolete these, but dependabot will pick that up once it is merged and auto-close them. If we close them dependabot will track that as meaning something about what to update or ignore, and best not to mess with that
- #18998 
- #18999 
- #19001 
Tested locally with:
> TEST_RELEASE_BUILD=true ./gradlew uninstallAll jacocoAndroidTestReport

build(deps): bump test dependencies in a group

---

AnkiDroid/src/main/java/com/ichi2/anki/preferences/reviewer/ReviewerMenuSettingsFragment.kt
AnkiDroid/src/main/res/layout/preferences_reviewer_menu.xml
AnkiDroid/src/main/res/layout/reviewer_menu_item.xml

I wanted to make more evident that the items were draggable, and also make the dragging less clunky.
I don't love the colors, but they are okay, and should be defined properly in #18767
https://github.com/user-attachments/assets/604e5490-ca24-4f66-9910-16797fb23b8a

feat: use card style in new reviewer toolbar actions preferences 

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt

Disable 'E' edit shortcut in CardBrowser split mode to prevent unwanted save dialog
* Fixes #18713
Modified the 'E' key handler in `CardBrowser.kt` to:
1. Check if the browser is in split (`fragmented`) mode
2. If in split mode, ignore the 'E' key press completely
Medium Tablet API 35 (Emulator)

 Fix: Disable 'E' edit shortcut in CardBrowser split mode to prevent unwanted save dialog

---

AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerMenu.kt

The ReviewerFragment.kt file has become too big, so I'm trying to encapsulate what I can
This also makes easier to test just the menu
Emulator 34: the new study screen menu works the same way, e.g.:
- flag icon padding doesn't change when changing flags
- Bury/Suspend text is updated if it is only possible to bury/suspend a card
- etc

refactor(new study screen): extract menu setup

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/Undo.kt
AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserFragmentViewModel.kt
AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
AnkiDroid/src/main/java/com/ichi2/anki/utils/ext/FragmentActivity.kt
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt

When I was looking into 
* https://github.com/ankidroid/Anki-Android/issues/18709
I found that I wanted to:
1. Move the menu state to a ViewModel
2. Split the ViewModel into a Fragment-level, and an Activity-level ViewModel
* When we added the NoteEditor (https://github.com/ankidroid/Anki-Android/pull/16764 ), a lot of bugs were introduced due to the complexity
* The panes are an activity-level concern, and would be easier to focus on with a smaller class
* Most of the rest of the logic is CardBrowserFragment-based
3. Introduce the `SearchBar`/`SearchView` 
These changes have been done on a branch for (1) and (3), but it feels like a 'huge' functional chance that I'll struggle to get reviewed with the Browser in its current state.
This PR moves us closer to (2), and closer to:
* a …

refactor: Move most CardBrowser methods to CardBrowserFragment

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt

- Hides the save button from `NoteEditorFragment` in cardBrowser to prevent duplication
* Fixes #18921 
- The cardBrowser already has a 'save_note' being added, and noteEditorFragment adds another one. 
- Here we introduce a check to prevent additional 'save_note' buttons from being added.
- This occurred after the NoteEditor was separated into the NoteEditorActivity.
- Since NoteEditorFragment is a MenuProvider we do not need onCreateMenu anymore.

fix: hide save button in fragmented activity to prevent duplication

---

AnkiDroid/src/main/res/layout/note_type_field_editor.xml

I noticed this when reviewing the following, but didn't want to expand the scope
* https://github.com/ankidroid/Anki-Android/pull/19046

chore(field-editor): add layout preview

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt

Continuing to mark old legacy review reminder code for deletion, preparing the existing codebase for the new review reminder code.
- `showSimpleNotification` is used to send general notifications and sync notifications. However, for some reason, the old code didn't send general and sync notifications if legacy review alerts weren't set, which was a weird coupling. This change removes that `if` condition and just runs the code immediately. After all, whether the user has enabled legacy review alerts should not affect whether they receive sync notifications. If the user wants to disable sync notifications, they can turn off notifications in the OS settings menu.
- Gated the vibration and blink settings behind a legacy review reminders conditional. We no longer support these settings in the …

refactor: prepare AnkiActivity for review reminders

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/deckpicker/DeckPickerViewModel.kt

- Hides the resizing divider when there or no decks/ collection is empty.
* Fixes #19053 
- adds a check to onCollectionStatusChanged to weather the divider should be visible or not.
No decks:
Empty deck:
Deck with cards:

fix(deck-picker): hide resizing divider when collection is empty

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt

* Add utility method to change the app intro shown pref
Implement `@NeedsTest("On a new startup, the App Intro is displayed")` 
* Part of #13283
* Check if IntroductionActivity intent was started after the DeckPicker.
* Add test for when the App Intro should be shown 
* Add test for when it shouldn't be shown

Add tests for showing App Intro

---

AnkiDroid/src/main/java/com/ichi2/anki/BackendBackups.kt
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/deckpicker/DeckPickerViewModel.kt

* slow progress on #18886
* The goal is to move startup into the ViewModel
* From there, we can move launching 'updateDeckList' from `onResume` to startup
* This avoids either a race condition, or blocking the main thread/collection on knowing whether the collection is usable
* We can /probably/ do this now,  but I want to move all of `showStartupScreensAndDialogs` before I tackle it
CI still passes, and briefly tested the Deck Picker
⚠️ Please suggest unit tests, I'm happy to block this for a round of feedback
I thought I had more time, this isn't a huge change, but is forward progress

refactor(deck-picker): move some of startup to ViewModel

---

AnkiDroid/src/main/java/com/ichi2/anki/DayRolloverHandler.kt
AnkiDroid/src/main/java/com/ichi2/anki/MetaDB.kt
AnkiDroid/src/main/java/com/ichi2/widget/AnalyticsWidgetProvider.kt
AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt
AnkiDroid/src/main/java/com/ichi2/widget/WidgetStatus.kt
AnkiDroid/src/main/java/com/ichi2/widget/cardanalysis/CardAnalysisWidget.kt
AnkiDroid/src/main/java/com/ichi2/widget/deckpicker/DeckPickerWidget.kt

I said I'd look into #14372, I did a few refactorings and fixed some bugs
* #14372
The icon appeared twice incorrectly on < API 31: 
From a user report, we weren't handling the day rollover event, so add a widget update on this event
⚠️ This probably doesn't work if the app is closed. The 'Day Rollover' broadcast was designed for in-app use, rather than use when the app is closed.
Various logical refactorings (see commits)
API 31 widget still works (tested with cards, no ETA, and an ETA)

Refactor & fix bug: small widget

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/browser/BrowserRowCollection.kt
AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerViewModel.kt
libanki/src/main/java/com/ichi2/anki/libanki/Collection.kt

Implements `collection.py` - there are some `@RustCleanup` annotations, but the structure of the file now matches upstream
* as-of commit: https://github.com/ankitects/anki/blob/f94d05bcbe17c8d1eacad3178c77f58c9fb3c3bd/pylib/anki/collection.py
* last commit implemented: https://github.com/ankitects/anki/blob/5cb191d624ce8ea1f8bc8578cd2414df8a54904d/pylib/anki/collection.py
* Fixes https://github.com/ankidroid/Anki-Android/pull/18552 🥳
See commits for lines matched
https://github.com/ankitects/anki/blob/5cb191d624ce8ea1f8bc8578cd2414df8a54904d/pylib/anki/collection.py
⚠️ I intended to not make functional changes, so did not test this
Hardest part is splitting the PRs to the level where I didn't need 20 of them, but they weren't too much of a slog to review.
Thank you all! `collection.py` …

refactor(libanki): bring Collection.kt up to date with upstream

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
AnkiDroid/src/test/java/com/ichi2/anki/browser/CardBrowserViewModelTest.kt

I want to move saved searches to the SearchView in issue #18709
* #18709
Added unit tests
* API 36 Google Pixel 9 Pro
* Saved a search, dialog still appeared and search still worked
* Closed the SearchActionView and did the same

refactor(card-browser): extract 'save search' to ViewModel

---

AnkiDroid/src/main/java/com/ichi2/anki/ui/ResizablePaneManager.kt

- Fixes the bug caused when resizing panes when Full screen navigation drawer setting is enabled
* Fixes #19105 
- Uses `requestDisallowInterceptTouchEvent` to stop the drag event being intercepted.
- Physical Acer Chromebook API 34
- Tablet Emulator API 35
[nav.webm](https://github.com/user-attachments/assets/2459bf25-125b-40fb-8fbb-2b594d41398c)

fix(resizable-pane): prevent parent from intercepting touch events during resizing drag

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/deckpicker/DeckPickerViewModel.kt
AnkiDroid/src/test/java/com/ichi2/anki/deckpicker/DeckPickerViewModelTest.kt

DeckPickerViewModel was initialized with the "fragmented" status of DeckPicker but as it was never updated during the viewmodel's lifetime there could be situations when it would be inconsistent with the actual fragmented state of DeckPicker. One of this situations is when in split mode because the activity is recreated bu the viewmodel is preserved.
The fix removes the fragmented property and the only flow it was used in. DeckPicker was changed to use the backing flow for the removed flow and the collect lambda was updated with the previous logic from the ViewModel that used fragmented.
* Fixes #19131
Ran the tests, verified the scenario on a resizable emulator.

Remove fragmented parameter from DeckPickerViewModel

---

libanki/src/main/java/com/ichi2/anki/libanki/Media.kt

Attempting to diagnose
```
net.ankiweb.rsdroid.BackendException$BackendCardTypeException: Cross-device link (os error 18)
at net.ankiweb.rsdroid.exceptions.BackendIoException.<init>(BackendIoException.java:23)
```
* Issue #19134
Checked logcat:
> Deleting 1 file(s) from /storage/emulated/0/Android/data/com.ichi2.anki.debug/files/AnkiDroid/collection.media

logs: trashFiles

---

AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt
AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt

* Part of #19136
```
AbstractFlashcardViewerTest > noAutomaticAnswerAfterRenderProcessGoneAndPaused_issue9632 FAILED
java.lang.AssertionError: messages after flipping card
Expected: <true>
but: was <false>
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at com.ichi2.anki.AbstractFlashcardViewerTest$noAutomaticAnswerAfterRenderProcessGoneAndPaused_issue9632$1.invokeSuspend(AbstractFlashcardViewerTest.kt:297)
at com.ichi2.anki.AbstractFlashcardViewerTest$noAutomaticAnswerAfterRenderProcessGoneAndPaused_issue9632$1.invoke(AbstractFlashcardViewerTest.kt)
at com.ichi2.anki.AbstractFlashcardViewerTest$noAutomaticAnswerAfterRenderProcessGoneAndPaused_issue9632$1.invoke(AbstractFlashcardViewerTest.kt)
at com.ichi2.anki.RobolectricTest.runTestInner$suspendImpl(RobolectricTest.kt:446 …
```

fix(tests): flaky test

---

AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerViewModel.kt
AnkiDroid/src/main/java/com/ichi2/anki/utils/ext/Scheduler.kt

In the commits
Galaxy Tab S9, Android 15
- Set timebox limit to 1 minute
- Open the new study screen
- Answer some cards
- Wait 1 minute
- Answer another card
- See the timebox dialog

feat(new study screen): timebox

---

AnkiDroid/src/main/java/com/ichi2/anki/reviewreminders/ReviewReminder.kt
AnkiDroid/src/main/java/com/ichi2/anki/reviewreminders/ReviewRemindersDatabase.kt
AnkiDroid/src/main/java/com/ichi2/anki/reviewreminders/ScheduleReminders.kt
AnkiDroid/src/test/java/com/ichi2/anki/reviewreminders/ReviewRemindersDatabaseTest.kt

Added review reminder schema migration handling. If a future developer updates `ReviewReminder`, so long as they also update the schema migration code, data should be transferred safely on all user devices from the old schema to the new system. Without this code, that data transfer would result in SerializationExceptions and IllegalArgumentExceptions.
**Changes, grouped by file:**
ReviewReminder:
- Fixed up a docstring explaining the migration process.
- Made the ReviewReminder class implement the ReviewReminderSchema interface. This allows it to also be stored in the oldReviewReminderSchemasForMigration map. This also means ID now needs to become an override field; see ReviewReminderSchema in ReviewReminderMigrationSettings.
ReviewRemindersDatabase:
- Converted it into an object. There …

feat(reminders): ReviewReminder schema migration

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt

Fixes the linked issue by making StudyOptionsFragment to delegate(through a fragment result) the interaction with the reviewer to its parent activity. This way  DeckPicker can use its own code to handle the study finish when in fragmented mode.
Note: I plan to make more changes to StudyOptionsFragment, it's too complicated for what it's doing.
* Fixes #19126
Ran the tests, checked the behavior in portrait and tablet mode.

Fix study finish snackbar not appearing in tablet mode

---

AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
AnkiDroid/src/main/java/com/ichi2/anki/settings/Prefs.kt

I swapped currentSyncUri with customSyncUri in https://github.com/ankidroid/Anki-Android/pull/19010/commits/5cf509b2e49aa73879a380b054222b4a51fe5dcb
then again, on a different way, in https://github.com/ankidroid/Anki-Android/pull/19102
* Fixes #19164
AnkiWeb sync still works
AnkiDroid tries to use the Custom sync server if set

fix: custom sync

---

libanki/src/main/java/com/ichi2/anki/libanki/Decks.kt
libanki/src/main/java/com/ichi2/anki/libanki/sched/Scheduler.kt

This PR adds methods from the backend and updates current methods related to active decks. As a side effect it fixes the linked bug:
_After the initial build of a custom study session, the study options fragment used _Scheduler.totalNewForCurrentDeck()_ to get the problematic number of "Total new cards". This method ended up using the incorrect deck(the deck being the target of the custom study request) through deckLimit() due to incorrect active decks methods code._ 
There are no side effects of the changes as the other usages of the changed methods are in previously used methods, currently unused(which probably should be deleted).
Before this PR(1038 cards in deck):
[Screen1.webm](https://github.com/user-attachments/assets/6845befa-89d5-4787-a0bc-806a544ddf42)
After this PR: …

Update active decks related methods with backend code

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/ReviewerTest.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/DevOptionsFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/HeaderFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/settings/Prefs.kt
AnkiDroid/src/main/res/values/constants.xml
AnkiDroid/src/main/res/values/preferences.xml
AnkiDroid/src/main/res/xml/preference_headers.xml
AnkiDroid/src/main/res/xml/preferences_dev_options.xml
AnkiDroid/src/main/res/xml/preferences_reviewer.xml

the last big features of the new study screen already have PRs, so it's time to promote it to public testing
* Closes #14302
* Remove the dev option
* Put the new study screen settings section more at the top
Emulator 34
https://github.com/user-attachments/assets/03f43d9b-9fe1-4c57-985f-d6181ac221c3
last commit:

feat: promote new study screen to public testing

---

AnkiDroid/src/main/java/com/ichi2/anki/pages/StatisticsDestination.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/ControlsSettingsFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/reviewer/ViewerAction.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerViewModel.kt
AnkiDroid/src/main/res/drawable/ic_bar_chart_black.xml
AnkiDroid/src/main/res/values/ids.xml
AnkiDroid/src/main/res/values/preferences.xml
AnkiDroid/src/main/res/xml/preferences_reviewer_controls.xml

It improves the ecosystem compatibility, since they are actions that can be triggered in the study screen top bar or with a keybind.
It also reduces any kind of complaints related to the new study screen not using a navigation drawer like the old one did
Emulator 34
https://github.com/user-attachments/assets/1bf600ad-ecd0-4029-88a4-3d23d84c4ccf

feat(new study screen): 'Browse' and 'Statistics' commands / menu actions

---

AnkiDroid/src/main/java/com/ichi2/anki/preferences/reviewer/ViewerAction.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerViewModel.kt
AnkiDroid/src/main/res/values/ids.xml

Implements the "Replay media" command and menu action in the new study screen
Emulator 34
[Screen_recording_20250908_164250.webm](https://github.com/user-attachments/assets/05d2df03-7ebf-4ae0-9036-18bf0630ea0f)

feat(new study screen): replay media command/menu action

---

AnkiDroid/src/main/java/com/ichi2/anki/preferences/ControlsSettingsFragment.kt

The previews tab in ControlSettinsFragment "required" the two browse/statistics controls introduced in  #19181 although it didn't show/use these controls. Use findPreference() instead to gracefully handle the preferences not being available.
```
ACRA caught a IllegalStateException for com.ichi2.anki.debug
java.lang.IllegalStateException: missing preference: 'binding_BROWSE'
at com.ichi2.anki.preferences.ControlsSettingsFragment.setupNewStudyScreenSettings(ControlsSettingsFragment.kt:229)
at com.ichi2.anki.preferences.ControlsSettingsFragment.onTabSelected(ControlsSettingsFragment.kt:80)
```
Opened both tabs in controls settings.

Fix crash in ControlSettingsFragment due to required browse/statistics preferences

---

AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt

* Fixes #19227
Use zoom instead of scale
Emulator 34
[Screen_recording_20250912_183925.webm](https://github.com/user-attachments/assets/7b74b21b-c641-4245-8d4e-58d043e3da12)

fix(study screen): zoom

---

AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserFragment.kt

Small typo created a lambda from the code that was supposed to be executed when changing the deck.
* Fixes #19231
Verified changing the deck.

Fix changing the deck of cards in browser

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/PagesTest.kt
AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt
AnkiDroid/src/main/java/com/ichi2/anki/pages/CardInfoDestination.kt
AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerViewModel.kt
AnkiDroid/src/main/res/values/sentence-case.xml

Switch to use the backend string for the card info page which offers the user some context about the caller(currently study/browse). The second commit adds sentence case support for the string.
This will also be useful for the previous card info functionality.
Checked the title in the card info page in english and other languages. Ran the tests.

Use the backend string for the title of the card info page

---

AnkiDroid/src/main/java/com/ichi2/anki/preferences/ControlsSettingsFragment.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/PreferenceUtils.kt
AnkiDroid/src/main/java/com/ichi2/preferences/ReviewerControlPreference.kt
AnkiDroid/src/main/res/xml/preferences_controls.xml

In the old study screen, the setting is useful if a note type has interactable elements that collide with gestures.
Since the new study screen solves that issue, its usefulness is almost non existent.
* Fixes #19250
Emulator 34
[Screen_recording_20250920_161403.webm](https://github.com/user-attachments/assets/302b3c04-3886-42d0-807a-f27de7901c4a)

chore: hide 'Enable gestures' if new study screen is enabled

---

AnkiDroid/src/main/res/layout/fragment_schedule_reminders.xml

Adds padding to the bottom of the ScheduleReminders RecyclerView to stop the "Add reminder" FAB from covering a review reminder. Otherwise, the user will sometimes be unable to toggle whether their latest review reminder is enabled or not.
Builds and runs on a physical Samsung S23, API 34. Switching languages, changing the 12h/24h setting works, etc.

fix: stop FAB from covering review reminders

---

AnkiDroid/src/main/java/com/ichi2/anki/reviewreminders/ReviewReminder.kt
AnkiDroid/src/main/java/com/ichi2/anki/reviewreminders/ScheduleRemindersAdapter.kt

Fixed an issue where the time displayed for ReviewReminders did not respect the OS setting for whether to use 12h or 24h time.
Accomplished by simply utilizing a Context.
Builds and runs on a physical Samsung S23, API 34. Switching languages, changing the 12h/24h setting works, etc.

fix: respect 24h time display preference

---

AnkiDroid/src/main/res/layout/schedule_reminders_list_item.xml

Minor change. Per a poll on Discord, we've decided to lower the font size of the ScheduleReminders time TextView from 32sp to 28sp. Perhaps we'll revise it again before review reminders go public.
- Builds and runs on a physical Samsung S23, API 34.

style: decrease ScheduleReminders font size

---

AnkiDroid/src/main/java/com/ichi2/anki/reviewreminders/ReviewRemindersDatabase.kt
AnkiDroid/src/test/java/com/ichi2/anki/reviewreminders/ReviewRemindersDatabaseTest.kt

Currently, if a deck with review reminders has all its review reminders deleted, the code will leave a blank entry in the review reminders SharedPrefs file. However, it's safe to completely delete the SharedPrefs entry. This change implements this, and also adds tests.
- Tests pass.
- Builds and runs on a physical Samsung S23, API 34.

refactor: clear empty review reminder maps

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckUtils.kt
libanki/src/main/java/com/ichi2/anki/libanki/Decks.kt

Adds a helper method in DeckUtils to check if the user can access a deck. This block of code is used by a lot of my code which handles deck deletion, so I've decided to pull it out into a separate utility function.
- Builds and runs on a physical Samsung S23, API 34.

feat(reminders): canUserAccessDeck

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.kt
AnkiDroid/src/main/java/com/ichi2/anki/reviewreminders/AddEditReminderDialog.kt
AnkiDroid/src/main/java/com/ichi2/anki/reviewreminders/AddEditReminderDialogViewModel.kt
AnkiDroid/src/main/java/com/ichi2/anki/reviewreminders/ReviewReminder.kt
AnkiDroid/src/main/java/com/ichi2/anki/reviewreminders/ScheduleReminders.kt
AnkiDroid/src/main/java/com/ichi2/anki/reviewreminders/ScheduleRemindersAdapter.kt
AnkiDroid/src/main/res/layout/add_edit_reminder_dialog.xml
AnkiDroid/src/main/res/values/10-preferences.xml
AnkiDroid/src/main/res/values/styles.xml

Allows users to add and edit review reminders.
**All commit messages, together:**
- `initializeScheduleRemindersDeckSpinner` doesn't properly handle what happens if showAllDecks is true. This makes pressing on a deck select the wrong deck. This commit fixes this.
- Added TimePicker styling, used when users edit the time of a review reminder.
- The AddEditReminderDialog displays the current time in the TimePicker when a review reminder is being created. Adds a utility function to ReviewReminderTime's companion object to calculate this time. I decided to put this function within ReviewReminderTime so it can be accessed by both AddEditReminderDialog and AddEditReminderDialogViewModel.
- XML file for AddEditReminderDialog. Allows time and deck modification. Also has a dropdown for advanced …

feat(reminders): AddEditReminderDialog
