ankidroid/Anki-Android

AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.java
AnkiDroid/src/test/java/com/ichi2/utils/ImportUtilsTest.java

This is caused by a bug in the storage library, duplicate files have their extension changed.
Fixes #6259
Check the extension, and use `.startsWith(extension + " ")`
Unit tested only
https://stackoverflow.com/questions/32849387/how-to-handle-file-extension-correctly-in-saf-storage-access-framework

Importer - allow import of "collection.apkg (1)"

---

AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.java
AnkiDroid/src/main/res/values/02-strings.xml

I feel it's likely users are trying to import anki2 files. They likely shouldn't, as anki2 files don't contain media and require a full replacement of the database.
I've added an entry in the manual, so this will hopefully reduce some of our support work.
Additional error message, and linked PR for the manual
Deemed this to be a risk-free change as it's only textual

Improve anki2 import experience

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
AnkiDroid/src/main/java/com/ichi2/anki/reviewer/PeripheralCommand.java
AnkiDroid/src/main/java/com/ichi2/anki/reviewer/PeripheralKeymap.java
AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ReviewerUi.java
AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerKeyboardInputTest.java
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerKeyboardInputTest.java
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.java

Prep for #6052, as soon as we define our key input in config rather than code, we can later move to defining them in preferences via a serialisation mechanism. This will later allow a user to redefine these mappings
Unit tested, slightly tested with my bluetooth keyboard
Really nice to get to a stage where you can trust the tests to act as regression cover. 
It'd be useful to get a toast on some actions to confirm to the user what happened (for example: was suspend/bury pressed).

Convert Keyboard Input Map Code to Config

---

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java

The cloze template can't have cards added to it or deleted from it, so we should block that in the CardTemplateEditor
Fixes #6015 
During options menu inflate, set those options to invisible for cloze type
API28 emulator with this branch on it, I attempted to edit a cloze template pre-patch and I could (an error) then with the patch I could no longer add/delete (fixed!) but I could add/delete on other template types.

 Hide card template add/delete for cloze model 

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java

This allows a user to take action to correct an invalid DeckPicker background image through intuitive actions without knowledge of the filesystem.
We hopefully stopped crashing by enforcing a file size limit, but this allows the user to have even more control. Both via clear data and reinstall
Fixes (partially) #6184
We use the DeckPicker preference and don't set the background if it's not set, it defaults to false, and will be reset if the user clears data or uninstall
On my phone:
* Set Image
* Clear Data
* Image no longer shows
* Tick Box & Press Back
* Image is shown

'Clear Data' removes DeckPicker background

---

AnkiDroid/src/test/java/com/ichi2/libanki/template/TemplateTest.java

Should be fixed in the rust conversion, but regression cover will be useful.

Add ignored regression test for #6284

---

AnkiDroid/src/main/AndroidManifest.xml
AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateBrowserAppearanceEditor.java
AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
AnkiDroid/src/main/res/drawable/ic_view_list_white_24dp.xml
AnkiDroid/src/main/res/layout/card_browser_appearance.xml
AnkiDroid/src/main/res/menu/card_template_browser_appearance_editor.xml
AnkiDroid/src/main/res/menu/card_template_editor.xml
AnkiDroid/src/main/res/values/01-core.xml
AnkiDroid/src/main/res/values/02-strings.xml
AnkiDroid/src/main/res/values/03-dialogs.xml
AnkiDroid/src/main/res/values/17-model-manager.xml

As defined in Anki Desktop: A user can edit the format string which is used in the Card Browser to render a card template.
This allows them to mark the reverse side in a card, for example without it appearing in the UI, or removing JavaScript or media fields to reduce rendering time.
This adds:
* UI with 2 textboxes
* Reset to Default button
* Save/Cancel buttons with logic
Fixes #5158
⛔ Manually, not unit tested, please provide a few tests if you think they'd be useful.

Add "Browser Appearance" Screen

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.java
AnkiDroid/src/main/java/com/ichi2/compat/CompatV16.java
AnkiDroid/src/main/java/com/ichi2/compat/CompatV28.java
AnkiDroid/src/main/java/com/ichi2/utils/VersionUtils.java
AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java

#5018 
Extracts method to `getPreviousVersion`, which supports other types (`int`, `String`) previously stored in shared preferences, as well as the new one `long`.
Created new class `CompatV28.java`
Added few unit tests.

Deprecation: SharedPreferences Version code from int to long

---

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java
AnkiDroid/src/main/res/values/03-dialogs.xml

Someone runs an automated testing tool, and these crashes come up in ACRA. Might as well fix the low-hanging (if impossible) fruit to clean up.
None
Should have done this a while back

Multimedia Editor: fix Automated Testing Crash

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java
AnkiDroid/src/main/java/com/ichi2/libanki/utils/TimeUtils.java
AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.java
AnkiDroid/src/test/java/com/ichi2/utils/ImportUtilsTest.java

We shouldn't be more permissive with file imports, as this leaves an incompatibility between AnkiDroid and Anki imports, where AnkiDroid is more permissive of bad values.
Fixes #6259 (take 2)
Revert the previous commit
Add a timestamp to the filename
On my device, tested all 3 imports:
* Full Collection with scheduling
* Full collection without scheduling
* Deck
Think more about breaking compatibility when self-reviewing.

File Export: Add timestamps to ensure uniqueness

---

AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java

Here is a bug, fixed by this commit.
In sched v2, create a basic card. Put the deck option so that there is
four steps for new card, "1 1 1 1"
Review the card, press "again" twice. Undo.
You'll see that the nuber of step for cards in learning is "-3". It
should be "1".
The reason is that `decrementCounts` is used only for undoing. More
precisely, when the numbers are reset, the number of the current card
should be decremented; this is done by this method. The trouble being
that the method was directly copied from Sched instead of being
changed to fit with Sched V2 counts of card in learning.
----
_Edit by @david-allison-1_ 
Fixes #6085

Correct count for undo of learning card V2

---

.travis.yml

This gets rid of Gradle Progress bars, which don't work as Travis' log is write-only. Not sure if you'd prefer we prefixed each gradle instruction with this.

Travis: Set TERM=dumb to reduce log output

---

AnkiDroid/build.gradle
AnkiDroid/src/androidTest/java/androidx/test/internal/runner/MultiDexClassPathScanner.java
AnkiDroid/src/androidTest/java/androidx/test/internal/runner/MultiDexTestRequestBuilder.java
AnkiDroid/src/androidTest/java/androidx/test/runner/MultiDexJUnitRunner.java
AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java
AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.java
AnkiDroid/src/test/java/com/ichi2/utils/JSONObjectTest.java

Adds more regression cover.
Fragment testing is much more complex than I'd expected, especially as we use the containing activity to access the collection.
At some point in the future:tm: we should move to a more self-contained and testable model.
Fixes #6289

Regression tests for CustomStudyDialog JSON output

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.java

This is discussed in https://github.com/ankidroid/Anki-Android/pull/6026/files/63f493482d69b9aee5a0594838d05707d5df6eba#r432866396 and can be considered as a separate PR.
Essentially, tests are wrong, but work by accident. In theory, you should reset each time a deck is selected. It was not done, but didn't create any trouble.
I noticed the problem when testing another PR, where reset became mandatory.
Anyway, this make the test close to ankidroid's code, since in non-test code, reset is called often
As @david-allison-1 asked, I also factorized some code

Reset in test

---

AnkiDroid/src/androidTest/java/androidx/test/internal/runner/MultiDexClassPathScanner.java

This removes the need to instantiate the DexFile class.
Addendum: I don't know if this is actually faster, but logically it should be since `getClassPathEntries` calls `getDexEntries`
Follow-on from #6293
Built on Travis.

Optimise MultiDexClassPathScanner

---

AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.java
AnkiDroid/src/main/java/com/ichi2/anki/services/ReminderService.java
AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.java
AnkiDroid/src/test/java/com/ichi2/anki/IntentHandlerTest.java

Smart Launcher performs an empty `ACTION_VIEW` on a double tap, this seems unusual, but the development documents say "make your best judgement" for an `ACTION_VIEW`. In this case, I feel the best action is to launch the app if it isn't launched.
Fixes #6312
Don't try to import the file 
Double tap now opens the app
https://developer.android.com/reference/android/content/Intent#ACTION_VIEW

Empty ACTION_VIEW opens app

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.java

Now, AnkiDroid can return to deck browser successfully when visit "Restore From Backup" Dialog while the previous version will return to the confirmation dialog.
Fixes #5833
For MaterialDialog, adding a Listener by setOnKeyListener() can moniter system's back key. Rewrite system back key operation by method dismissAllDialogFragments() which make its function same as button "Cancel".
1. Open Deck Browser
2. Select "Restore From Backup"
3. Accept the confirmation
4. Press the physical "Back" button on the device.

Correct Device "Back" Button in Restore From Backup

---

AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java

This was discussed here https://github.com/ankidroid/Anki-Android/pull/6026#discussion_r432868155
The method _burySibling leads to code duplication. Four copies of the same code occurs. This is especially a problem because other PR I created deal with this part of _burySibling. So factorizing this code is going to be even more useful if my other PR are accepted.
@david-allison-1 didn't like my first factorization, because the code I wrote introduced a method, which took a collection (the queue of card id) and removed elements from it.
I decided that, what was the most natural thing to do is to create an inner class for queue of card ids, and add a method _burySibling in it which simply deal with burying the sibling. This way, it is clear that the code is changing the collection content. …

NF: Factorize bury sibling

---

AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java

Currently, if you try to rename Default to DEFAULT, it will be
rejected because the deck already exists. This code allow this kind of
change to occur.
If the deck already exists because it's the same deck than the one renamed, renaming can still go on.
Trying to rename a deck by changing its case.
Anki recently solved that while moving to rust. Probably in f592672fa952260655881a75a2e3c921b2e23857
I don't understand rust

Allow changing the case of a deck name

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
AnkiDroid/src/main/java/com/ichi2/compat/CompatV19.java

This fixes two issues, both when Fullscreen (No Buttons) is active.
Firstly: A swipe down from the status bar first triggered the Anki UI, and then was registered as a fling. This fling assumes "I'm a fling when the Anki UI is active, I should close the Anki UI and process a gesture".
Secondly: When drawing from the top and the whiteboard, the Anki UI is shown. The Reviewer logic assumes "I'm handling a touch event when the Anki UI is shown", this stops the draw event, and starts a fling from wherever the cursor is at the current moment, which closes the Anki UI and performs a gesture.
Fixes #5741
* We define a margin, and assume it's not a gesture if it's within the margin of the edge of the screen.
* A whiteboard draw event continues after it shows the Anki UI.
On my Android
* Grill me …

Fix Fullscreen (No Answer Buttons) Reviewer Gestures

---

AnkiDroid/src/main/java/com/ichi2/anki/services/BootService.java
AnkiDroid/src/main/res/values/03-dialogs.xml

This is typically caused by having alarms on over 500 decks.
Mostly occurs on Samsung phones.
I'm setting this to high priority as it's more likely to affect med students, and means they can't review, so I'd like to see this out more than my normal fixes.
Fixes #6332
Try...catch...Toast
On my phone - brief graphical ghosting of the Toast as it's performed with the Application Context and activities are switched.
https://stackoverflow.com/questions/29344971/java-lang-securityexception-too-many-alarms-500-registered-from-pid-10790-u
This occurred on Android 9, so it's more prevalent than just Lolipop.

Fix "Too many alarms (500) registered"

---

AnkiDroid/src/main/java/com/ichi2/libanki/Card.java
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java

LaTeX is usually compiled to image, and images are stripped in Card Browser. This mean that LaTeX does not appear in Card Browser. This PR wants to avoid it.
It's based on https://github.com/ankidroid/Anki-Android/pull/6269 , so it should not be accepted until the question of hook is resolved. The goal here is only to show what was my points with hook first.
Of course, now that hooks related to language are removed, this is less interesting than when I started considering hooks, since we can also decide not to apply any hook in the browser. This seems more acceptable for Chess than for language with non-latin character

No tex in browser

---

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
AnkiDroid/src/main/java/com/ichi2/anki/workarounds/FirefoxSnackbarWorkaround.java
AnkiDroid/src/main/res/values/03-dialogs.xml

* Should we limit this to certain browsers?
* Is there a chance that a browser will actually want to call `ACTION_VIEW` on the Reviewer intent?
* Probably needs some "nicer UI" fixes on the display string.
Clicking "Open" with the download snackbar in firefox just opens the reviewer. Notify the user that they should do something else to open the file.
Seems like a bug in Firefox.
Fixes #5374
Show a toast and close the app
Reviewer still works, toast is displayed.
It's a nightmare to submit bugs to Firefox without knowing the process.

Improve opening deck package from Firefox

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TagsDialog.java

**Please wait for Travis before review**
Reverts #6175 (manually)
The above commit is a bugfix for an issue which appeared to be from automated testing.
In doing so, this adds a parameter to the fragment constructor, which I didn't realise shouldn't be done.
----
> All `Fragment` classes you create **must** have a public, no-arg constructor.
Saw a crash on ACRA due to "Could not find Fragment constructor"
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/990db3a6-6ea8-44da-96dd-0e6e41db7769
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.NoteEditor}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.ichi2.anki.dialogs.TagsDialog: could not find Fragment …
```

Revert "Remove possibility of TagsDialog NullPointerException"

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java

Realised that "Search All" makes little sense without explaining that a deck was searched.
Already requested by 2 users since it went into the alpha - seems like a great improvement got even better
Fixes #6344
Just refactor the logic and remove the need for `cards == 0`
On my device
Lovely to get feedback from Alpha testers

Card Browser: Always show 'Search All'

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java

I learned my lesson. Before doing an actual PR with any effect, I'm doing the cleaning first.
The card browser has a member mDecks which seems quite useless, as it has the same content as the deck manager. Removing it and removing the few places where it is used allow to make code slightly smaller. It will also allows eventually to make card browser faster

NF: Avoid mdecks

---

AnkiDroid/build.gradle
api/build.gradle

Fixes #5955 
⚠️ It compiles, and I believe it's unit tested. I ran the connected tests and they all pass on API 16 - we do the same in `AnkiDroid`, but `api` still supports `minSdkVersion 8`

Upgrade API to Java 1.8 to allow JDK 14 compilation

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserOrderDialog.java

[Fixed] Wrong symbol for ascending/descending sorting in card browser #5802

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/java/com/ichi2/async/Connection.java

Probably not possible - but a non string error was not shown.
Null previously crashed.
Null may have been possible from a badly localised exception
Fixes #6398
On my phone - an exception with an null message now shows a sync error dialog

Handle null/non string sync error

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.java
AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java

Anki Desktop made a change between 2.1.26 and 2.1.28 which corrupted the model deck ID, setting it to null.
This made the API practically unusable as getting all models crashed.
Since it's occurred for a fair time, it's best to fix this in the source.
Fixes #6378
Use the default deck if the Id is not found
Unit tests on API 23 emultaor

API: Allow null model deck ID

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java

When there are no card to review immediately in a deck, a full reset was done (uselessly) just to check whether there are cards in learning due later today. I introduce a method which simply check whether there are cards in learning due the same day. This means that it gets quicker to decide what to do in this case.
Note that this method is not in upstream. Mostly because upstream always open the reviewer, and just close it if there is nothing to review. Since we do thing very differently anyway, at least, let's do them quickly.

handleDeckSelection uses a function for cards in learning instead of reset

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java

`hasSelectedSingleNoteId` assumed that `mCards` and `checkedPositions` were in sync. This turned out to be an incorrect assumption.
Fixes #6384
Try..catch..ignore. and perform a local copy to reduce the chance of this happening.
None

hasSelectedSingleNoteId: Handle concurrency issue

---

AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java

Anki's code
https://github.com/ankitects/anki/blob/master/pylib/anki/exporting.py#L198
put the flag are put to 0 while exporting. However, this exporter
seems to never be used directly, and children redefine it. I tested,
flags are exported when deck/collection are exported. So I remove the
line removing flags. This corrects #6382

Export flags

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java

Users requested that Copy Note included tags.
Fixes #5165
On my phone:
* Copy Note With Tags - copied
* Copy Note with no tags - works, no tags
* Copy note with no tags, but one added - takes the current state
It's great for the soul to make users happy in 15 lines of code

NoteEditor: "Copy Note" Copies Tags

---

AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java

As I've added multiple tasks in other PR, I wanted to clean them slightly.
I find it more clear to avoid sending/returning a parameter when it's useless. And to allow tasks which return no data to have void type. In particular I expect to uses it in other PR if it gets accepted.
There are also some constructor, paramater... which are never used and that I remove. And some inconsistency in number of line that I correct

NF: Clean tasks

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java

There are Anki addon for getting cards info (Review, Lapses, Interval, Due, Queue). But on AnkiDroid that can not works so this is implementation for getting info in WebView.
Fixes #4676
Added JavascriptInterface to pass value from Java code to WebView
Add following to front/back side of cards to get the values (Review, Lapses, Interval, Due, Queue)
```
<script>
console.log(AnkiDroidJS.ankiGetCardReps());
console.log(AnkiDroidJS.ankiGetCardLapses());
console.log(AnkiDroidJS.ankiGetCardInterval());
console.log(AnkiDroidJS.ankiGetCardDue());
console.log(AnkiDroidJS.ankiGetCardQueue());
</script>
```
https://developer.android.com/reference/android/webkit/WebView.html#addJavascriptInterface(java.lang.Object,%20java.lang.String) …

Get Cards info (Review, Lapses, Interval, Due, Queue) in WebView

---

build.gradle

It was possible to use unsupported JDKs as a developer, leading to very obscure problems in robolectric when you ran the test harness
Part of a good developer experience is determining invalid environment states as quickly as possible, then refusing to go further, ideally with a nice message explaining the problem
Fixes #6428
Use some groovy to detect the JVM major version, and abort with message if the JVM isn't one of the ones we support
I don't have an unsupported JVM but when I falsified the test (by overriding the current JVM variable to 9) I get a nice message now
Groovy is pretty groovy, if you know Java.

Refuse to compile with unsupported JDKs

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java

Two bugs (sorry):
* The ActionItem should only have been visible if selecting cards from a single note. I was using `NOTE` to ensure uniqueness. `NOTE` was the name of the note type, not the `NoteId`.
* This did not cause bugs, as only one card ID was sent to the note editor, but it was confusing.
* Now, we only show "Edit Note" if a single card is active.
* There is currently a bug that a result from the NoteEditor will cause a crash if the CardBrowser is in multiselect mode.
* We move to single-select mode just before we show the Note Editor, this change is visible on the screen for a fraction of a second
I would personally like to keep this functionality, as it makes "Edit Note" more discoverable.
Fixes #6432 
On my Android Device - new collection. Can now edit a note's note type via …

Fix Browser "Edit Note" Multiselect crash when changing Note Type

---

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java

Eh, I do a PR which is not NF. I missed it ! 
When you block all buttons because a slow action is occurring, the undo button light keep turned on. I was actually pretty sure I already fixed it, but can't find any PR, anything in git history, in my merge branch.... 
Actually, I believe that there is never a reason to turn the light
on. By default it's usually on, except when buttons are blocked, and
we don't want to turn-it on when buttons are blocked.
So
```
if (!undoEnabled) {
menu.findItem(R.id.action_undo).setAlpha(Themes.ALPHA_ICON_DISABLED_LIGHT);
}
```
may be slightly simpler and quicker. I'm not confident enough to be
sure that I get nothing wrong here, so I keep the most secure version
of the code.
I just use disabled light if it is disabled by a slow action or if there is nothing …

Turn off undo during slow control block

---

AnkiDroid/build.gradle
AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java
AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java
AnkiDroid/src/main/java/com/ichi2/libanki/importer/AnkiPackageImporter.java
AnkiDroid/src/test/java/com/ichi2/libanki/UtilsTest.java

Since this is a library change, I wouldn't feel totally comfortable in putting this in a point release. Not sure how this works with semver.
* Check the constructor to ensure that there's no nastiness in the change.
Allows import of apkg >2GB.
`new java.util.zip.ZipFile()` failed with:
`java.util.zip.ZipException: error in opening zip file`
This was also performed in the export side to keep library use consistent
Sadly, syncing uses `ZipFile.OPEN_READ | ZipFile.OPEN_DELETE`, and there does not seem to be a direct replacement in the library so I've kept this as using `java.util.zip` for now.
Fixes #6419
Switch to commons-compress for import/export of apkg/colpkg files.
Tested on an API 27 emulator, which failed, and now handles a 2.4GB file
Tested on my device (Android 9) via in …

Convert import/export zip file usage to library: commons-compress - Allows >2GB imports

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java

`loadDataWithBaseURL` throws a `NullPointerException` if called after onDestroy
https://stackoverflow.com/questions/28856883/java-nullpointer-exception-from-webview-in-android-webkit-webviewclassic-loaddat
Fixes #6446
Detect if `onDestroy()` was called, and stop rendering if that happeend,
API 16 emulator (hit the `Timber.w` with no crashes) and Android 9 device.
⚠️ Please read: https://developer.android.com/reference/android/app/Activity#isDestroyed() - mentions "final onDestroy" - This goes against my knowledge of the lifecycle.

CardViewer - Fix crash viewing card after close

---

AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.java
AnkiDroid/src/main/res/values/02-strings.xml

String wasn't localised.
Added in f8b721bbaefe7e205fb50333dc7cdf05a98426e2
Untested 🤠

Extract resource: import_error_copy_file_to_cache

---

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
AnkiDroid/src/main/java/com/ichi2/libanki/Consts.java

ℹ️ Happy for this to be rejected/taken to the drawing board as a "let's get to the root cause rather than work around it", I feel it's more likely that this was caused by Anki Desktop, as it's a syncing issue. 
A user had invalid "conf" values when syncing from Anki Desktop
This meant that they could sync from Anki Desktop, but their collection was reported as corrupt in AnkiDroid, as the deck list could not be displayed
Fixes #6454
Check Database
Tested on my phone - supplied collection no longer crashes after check database. My main collection showed no problems

Add Database check for decks with invalid config

---

AnkiDroid/src/main/res/values/04-network.xml

One is the correct unit, one is not. We were using the one that is not.
Fixes #6456
Thanks to @gaul :-)

Display sync data in KB not kB

---

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java
AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.java
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TagsDialog.java
AnkiDroid/src/main/java/com/ichi2/libanki/Note.java
AnkiDroid/src/main/java/com/ichi2/libanki/Tags.java
AnkiDroid/src/main/res/menu/note_editor.xml
AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.java

The Note Editor did not allow preview, a heavily requested feature
Fixes #5644 / Obsoletes #5705 
Fixes #3819
I re-use the CardTemplatePreviewer which is good for ephemeral data, with extensions to it's functionality where it can take a bundle from NoteEditor and use that to populate the card it shows with the unsaved note editor contents
API28 emulator, editing a note and hitting the new preview button to see that my edits are now shown in a preview screen. When you cancel the note edit session the edits go away. Seems to work
CardTemplateEditor preview still works as well on same API28 emulator

Allow preview of note edits

---

AnkiDroid/build.gradle
AnkiDroid/src/main/AndroidManifest.xml
tools/local-release.sh
tools/parallel-package-release.sh
tools/release.sh

We include native code now and that will only continue with Rust
We must implement a 64-bit native build by Play store guidelines but we still have devices that use ARM and x86.
The only way to include 64-bit binaries and support all the users without bloating the APK as it is currently is to split via ABI
So this PR does binary ABI splits so platforms only get the binary code they need from our libraries.
That takes it from 10.5MB to 7.5MB or so
I cribbed the style used by react-native, which I have used successfully for a couple years, and adapted the ABI-versionCode-ranges to match our versioning style
Unfortunately this is the sort of thing that you test by releasing, so this is already released as 2.12alpha7 and 2.12alpha8 to make sure it was working :fearful: 
I put links in the …

Shrink published APK by ~3MB w/ABI splits

---

AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
AnkiDroid/src/main/java/com/ichi2/compat/CompatV16.java
AnkiDroid/src/main/java/com/ichi2/compat/CompatV18.java
AnkiDroid/src/test/java/com/ichi2/compat/CompatV16Test.java

Should we throw an `IllegalArgumentException` if either of the ints are negative. `getFreeDiskSpace` handles this and returns a default value
`getAvailableBytes` had an overflow bug, we fix this for most inputs.
Fixes #6442 
Fixes #6441
Fixes #5777
int * int = int
long * long = long
Unit Tested

Fix overflow in getAvailableBytes (API 16)

---

AnkiDroid/build.gradle
build.gradle
tools/local-release.sh
tools/parallel-package-release.sh
tools/release.sh

@david-allison-1 here is the mop-up after the unexpected need to merge my ABI splits change post-haste yesterday #6464 
This re-enables universal APK in debug, makes it possible in release, and "uses it where appropriate"
Appropriate is: when posting to github or when building local or parallel releases
Further, this automates the publish of parallel releases so we will always post an 'A' parallel build (for drive-by testers to just download and try) and on public release it will automatically post the 5 instead of me manually posting
Fixes #6472 
Command-line gradle toggle to `-Duniversal-apk=true` that takes effect in release builds, with debug just having universal apk on all the time
Quite a few local builds, but the real testing will happen with 2.12alpha9 once this has a look
I …

Publish universal apk

---

AnkiDroid/build.gradle
gradle/wrapper/gradle-wrapper.properties

Bumps fragment-testing from 1.2.4 to 1.2.5.
Signed-off-by: dependabot-preview[bot] <support@dependabot.com>

Dependency updates 20200615

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/res/values/01-core.xml

When a user has no permissions, they were shown "AnkiDroid directory is inaccessible" and taken to the app info screen. They now have a call to action
Untested

Improve "AnkiDroid directory is inaccessible" when permissions are denied

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java

When adding some function / text eg. ```showAnswer();``` then user have to turn on full screen.
But if user turn off full screen then for hiding that buttons / text, there is way to know if full screen or not in JavaScript. 
Using ```JavascriptInterface```, passing ```Action Bar isShowing``` 
Tested on emulator 
```false``` when ```Action Bar``` showing
```true``` when ```Action Bar``` not showing
- [ x ] Your code …

Get value of fullscreen status in JavaScript

---

AnkiDroid/src/main/java/com/ichi2/libanki/Card.java
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
AnkiDroid/src/main/java/com/ichi2/libanki/Models.java

In order to deal with LaTeX in browser, having a cleaner _renderQA seems nice.
This should be NF, with simple to follow commits

string consisting only of whitespace does not generate card (Previously NF: clean _renderQA)

---

AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.java

- what hardware are we running on?
- what operating system version?
- what screen size?
This came about when I realized the analytics currently did not answer
the question, how many users are using Amazon devices?
While I was in there I added the other hardware bits I thought could
focus development effort allocation
Add a method to the initializer for the default analytics request to set device data
Setting User-Agent correctly let's google auto-segment devices to a large degree, I used custom dimensions as well to make sure
API29 emulator, used advanced preferences to turn on debug analytics and watched the analytics console as well as adb logcat to check the request parameters and see their effect on reporting
The User-Agent style is working code from another project I maintain, so I …

Augment analytics so we can answer hardware questions

---

.travis.yml

Fixes the Travis Build
Note: We should likely enable `requestLegacyExternalStorage`
⚠️  https://developer.android.com/preview/behavior-changes-11
https://developer.android.com/preview/setup-sdk - now shows to use `30` instead of `R`
> Sometime later this year, we will be able to switch to using targetSdkVersion 30, at which point normal behavior returns with respect to minSdkVersion.
https://stackoverflow.com/a/61027613/13121290

Travis: Rename API R to API 30

---

AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
AnkiDroid/src/main/java/com/ichi2/libanki/sync/HttpSyncer.java
AnkiDroid/src/main/java/com/ichi2/libanki/sync/RemoteMediaServer.java
AnkiDroid/src/main/res/values/10-preferences.xml
AnkiDroid/src/test/java/com/ichi2/libanki/sync/RemoteMediaServerTest.java

Prevent duplicated slashes in the media sync url
If my Media sync url under **Settings** -> **Advanced** -> **Custom sync server**  ends with a slash, I get a 404 on synchronization because of a duplicate slash (`/`) in the url. 
This PR adds a check, that prevents the duplicate slash.
Fixes #6436
I add a check to [`RemoteMediaServer::syncURL`][remotemediaserver] that prevents the second slash from being added to the url if it already ends with an slash.
I installed [ankicommunity/anki-sync-server][ankisyncserver] locally.
Then I added my custom sync server under **Settings** -> **Advanced** -> **Custom sync server**.
My _Media sync url_  ends with a slash (`\`).
When I tap the sync button in the main activity everything synchronizes without an error.
[ankisyncserver]: …

sync: fix media sync with trailing slash on media sync url

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/main/res/menu/popupmenu_multimedia_options.xml

We have been getting terrible reviews, all focused on cloze deletion, from Vietnam.
I just couldn't figure it out.
Finally it turns out it's Xiaomi devices! They apparently just don't do action mode callbacks well.
Also we didn't set action mode callbacks for lower APIs so anything below API23 was out of luck too.
This PR adds cloze as an option on the paperclip menu so it's usable everywhere now.
Fixes #6494 
If it's a cloze type card, make a cloze menu item visible on the paperclip menu, and hook that to all the existing cloze insertion code
For both cloze and non-cloze card types, on an API29 and API22 emulator, verify that cloze deletion is visible when it should be on the paperclip menu, and that it works.
I will note there is some crap behavior on API22 where your text selection …

Note editor cloze more available

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java

I noticed this in response to editing a note for the sole purpose
of removing leech tags in my own collection. Upon return to card
browser it was not fully in sync visually with the updated tags
unlogged, fixed it in less time than logging an issue takes because I happened to know about 'mReloadRequired' and how it operated from my work on CardTemplateEditor
Minimal intervention. It's possible mChanged has no effect - my quick inspection indicated it did not - but better not to change it without testing. Removing it or altering might introduce a bug.
Adding mReloadRequired however just requests the CardBrowser do an idempotent operation, to re-execute the search that resulted in it's current list. And if tags or fields change you definitely want it to reload so that highlighting on marked …

Reload card browser when tags/fields change in note edit

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java

fixes #3213
Only set soft input mode to always hidden when not adding a note (`setSoftInputMode`). Normally it would open on focus because of AndroidManifest's `adjustResize` option.
1. Add note and edit existing note
2. See whether keyboard opens automatically
https://developer.android.com/training/keyboard-input/visibility

Show keyboard when adding note in NoteEditor

---

AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java

Starting with 2.1.28, anki strip deck's name. I imitate it. I don't
use the same code as they do it in rust and we don't have rust yet.
However, since this create compatibility problems between anki and
ankidroid during some sync ( see
https://forums.ankiweb.net/t/decks-with-trailing-spaces/89/4?u=arthurmilchior
) I believe it should be considered without waiting for
rust. Especially since it's a small change in term of code.
The spaces are stripped in two places: when checking for deck
integrity, and when changing deck name (i.e. through `id` which
creates deck, and through `rename`). No need currently to use it in
byName, since it is only called with names already stripped and with
the constant "Custom study session".
This was tested by:
* creating a deck name " A B :: C D:: E" and …

Strip spaces in deck name

---

AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java

Anki is changing the way it deals with deck name in case of trouble. 
* "" is replaced by "blank"
* "::::" is replaced by "::blank::"
* duplicate name just replace a name `n` by `n+` (actually, it now allows to rename deck to give it the name of an already existing deck. It seems quite strange and probably an accident, so I won't port this feature yet)
I made the first two changes before looking for duplicate name, otherwise it would make little sens.
Tested:
* Deck with "::::::"
* deck ""
I didn't test duplicate name, mostly because there is no easy way to create duplicate name in ankidroid

Automated deck renaming

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.java

Reported in #6507  - Copy Note does not copy to the correct deck.
Fixes #6507 
Place the DeckId in the intent, and restore to this. `mCurrentDid` overrides anything set in the model in `NoteEditor.setDid`
Tested on my phone, then added a unit test

Copy DeckID when copying/adding note

---

AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.java

Previously, we performed the check inside either `AnkiPackageImporter`/`doInBackgroundReplace`. This caused exception reports to be thrown when zip files were invalid, which wasn't a great UX
Fixes #6489
We move to `ImportUtil` to validate the import, which displays an error and does not raise an exception report.
On my phone:
* Empty file - no exception report, "Failed to unzip apkg: archive is not a ZIP archive"
* Corrupt file - no exception report, "Failed to unzip apkg: central directory is empty ..."
* Good file - imports as normal

Deck import: Pre-validate zip file

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TagsDialog.java

I often find that it's much easier to search for "chinese" to list potential tags, rather than needing to know the tag beforehand
If I knew the name, I wouldn't need to search.
Tested on my phone, works as expected

Filter tags by "contains" instead of "startswith"

---

AnkiDroid/src/main/assets/scripts/card.js
AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java

As sometime it needed to toast in AnkiDroid. This will create native toast of message passed by card developer
This is continuation of #6307
Added signal for calling function
In card.js
```
ankiShowToast(msg)
```
Tested on emulator,
The function accept string for showing toast message
In front side of card template add it in ```<script>``` tag
```
ankiShowToast("Showing native toast using javascript");
```
https://developer.android.com/guide/topics/ui/notifiers/toasts
- [ x ] Your code follows the style of the project (e.g. …

Show Toast using JavaScript function in WebView

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java

Under a certain complex set of steps, the card browser did not dismiss its progress dialog
Fixes #6500
We stop the browser from unnecessarily searching after `supportInvalidateOptionsMenu` and allow the user to search again if for some reason they can still trigger this.
On my device, no longer spins infinitely
We need a ViewModel, this is an extremely complex class

Fix Card Browser Infinite Loading after edit

---

AnkiDroid/src/main/res/layout/reviewer_fullscreen.xml
AnkiDroid/src/main/res/layout/reviewer_fullscreen_noanswers.xml

This is a fix proposal for the bug report #6504 
Fixes #6504 
The definition of reviewer_mic_tool_bar layout was missing into reviewer_fullscreen.xml
and reviewer_fullscreen_noanswers.xml
It leads to null pointer exception when activating the pronunciation checker in full screen modes.
I try to reproduce on my HUAWEI P10 Lite.
So I was able to test the fix on it.
The reproduction process was easy : try to activate the pronunciation checker in a full screen mode.
N/A
- [X ] You have not changed whitespace unnecessarily (it makes diffs hard to read)

Bugfix #6504 add mic tool bar in full screen mode

---

AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java

This is a commit in https://github.com/ankidroid/Anki-Android/pull/6522 that can easily be moved outside of it. By itself it present almost no interest, it only remove some access to a hashmap when the value is not used.

NF: deckDueList only if required (performance)

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.java

This test could be run on real devices. Will not impact users (as the bug was fixed), but still shouldn't be done. This setting will be fixed via use of the app.
This requires #6025 to go in before we start mutating collections for the content provider tests
We should have an automated warning on changes to the `androidTest` directory. That, or a review checklist

Ignore content provider test until we can change collections in instrumented tests.

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java

This is once again a part of the huge commit https://github.com/ankidroid/Anki-Android/pull/6010
It contains a commit in common with https://github.com/ankidroid/Anki-Android/pull/6032/commits/81134cfcf17803f5113035aa1a6aa614e3a8ec92 , a method to defer resetting.
In each commit, I explain why resetting is actually not important immediately, and why we may defer.
I want to emphasize that if you look at anki's code, it almost never reset the scheduler, unless it actually needs to. The only exception to this rule is when a note type is modified.

Defer resets (performance)

---

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java

This change has a single goal, making https://github.com/ankidroid/Anki-Android/pull/6049 smaller. I believe that https://github.com/ankidroid/Anki-Android/pull/6049 is my most important opened PR, it can help ankidroid starts faster, and a big reason while it seems to be a big commit is because it requires to uses a getter instead of using a direct access to the member element. So I hope that if this commit gets merged in ankidroid, the other commit will appear to be quite simpler

NF: replace mModels by getModels()

---

AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java

NF: _groupChildrenMain simplificitation
This use the fact that _groupChildrenMain is called only after the
deck collection is checked, so there is no duplicate and each nested
deck has a parent.
Currently what occurs is that, if you have the list of deck ["A",
"A::B", "A::C", "A::C::D", "E"], the function will first process the
sublist ["A", "A::B", "A::C", "A::C::D"] and then the sublist
["E"] (this is because it looks only as the first component of the
name)
Then, in the first sublist, it will look for the parent "A" and the
children ["A::B", "A::C", "A::C::D"], by looking at which deck has
depth 0... that is useles, because, thanks to the sorting, we know the
parent exists and is the first element of the list. Therefore, I
removing the condition dealing with the first element of the …

NF: _groupChildrenMain simplification

---

AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java

This is a simple refactor, extracted from https://github.com/ankidroid/Anki-Android/pull/5935 which hopefully will make https://github.com/ankidroid/Anki-Android/pull/5935 simpler.
The main reason is that "get" check whether the deck with this id exists, and return null otherwise. So instead of checking and if it does exists getting it, we directly get the deck, and check whether it's null. It's one less search and factorize the code.
It's tested by running on my phone for months

Decks.rem factorize get deck

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java

I added a test which should have detected this bug (by having multiple children of a deck at the same depth)
Previously, `tail` contained both "A" and all of its descendants. Then `tail` was used to compute `children` which contains all descendants of "A" but not "A" itself. I've changed it so that we directly compute "children". What I forgot to cherry pick in the previous PR is : stop adding elements to "children" when it is already constructed. Now, it is done, I removed the line which iterated over children and added its elements to children.
I would like to note that this bug did not occur in the big PR, because this line was removed in another commit. My main problem here was simply that my PR could not be as easily cut in multiple independant sub PR as what I thought. 
This use the …

NF: _groupChildrenMain simplificitation

---

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtonStatus.java

Drawables from a shared source share "constant state". One mutation to an icon will mutate all other uses of the icon.
This means any other uses of undo may obtain a disabled alpha level.
Discovered in the Visual Editor - Alpha values of the undo icon were saved from the card viewer.
call `.mutate()`
On my phone - alpha levels are no longer copied.
http://web.archive.org/web/20100302003802/http://www.curious-creature.org/2009/05/02/drawable-mutations/

Mutate Drawables before mutating alpha

---

AnkiDroid/build.gradle

Bumps swiperefreshlayout from 1.0.0 to 1.1.0.
Signed-off-by: dependabot-preview[bot] <support@dependabot.com>

Dependency updates 20200625

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
AnkiDroid/src/main/res/values/10-preferences.xml
AnkiDroid/src/main/res/xml/preferences_gestures.xml

This commit adds the volume buttons to the gestures as discussed in #3021. Since this is unexpected behavior for most users, it's turned off by default. I realize buttons are not gestures, but it seemed like the most sensible place to put this, mainly because you can configure them for any action.
Perhaps it makes sense to add more gestures using the volume buttons and maybe even the wakup/standby button. Things like double press and press and hold could allow for more actions to be used with hardware buttons.
An interesting continuation of this would also be to make the Reviewer work with the screen turned off and TTS as output. Useful on the go and for blind people. Maybe I'll look into that.
Simply added volume buttons to existing gestures. `AbstractFlashcardViewer.dispatchKeyEvent` …

Add volume buttons to gestures

---

AnkiDroid/src/main/res/values/01-core.xml

All other items are in sentence case.
If there's a good way to stop this propagating to CrowdIn, it'd be good to know

NF: Reviewer App Bar item casing

---

.travis.yml

Travis CI continues to have flakiness issues and the JDK install is one of the largest sources of failure
This takes the JDK install process and extracts it to a script that is a lot more patient about retrying the install
Related to #5605 and #6186 
travis_retry could not wrap the JDK install for various reasons so this is a custom script to implement retry logic and exponential backup for the JDK install
On my own travis instance, I built the script slowly such that basically every failure mode was tested while constructing - all the retries etc. Seems to work? Definitely works on the happy path right now which is as good as current at least, and if it has errors in the failure mode handling we can get them over time
The Android Studio shellcheck extension is a nice aide when writing …

Carefully install JDKs, sensitive to transient failure

---

.travis.yml

This may be reverted if/when the upstream PR is merged:
https://github.com/DanySK/Gravis-CI/pull/16
We are still seeing lots of transient CI failures
https://travis-ci.org/github/ankidroid/Anki-Android/builds/702330392
I was in the area so I got to work in the upstream repo to make it more resilient
- prefix all Gravis-CI echos so we can tell what's going on
- re-use local resources (jabba.sh install, installed JDK) where ever possible
- hit github softer with curl via bigger initial retry delay
- use github's CDN URLs
It's my guess based on jabba being our predominant failure mode that since these changes cut jabba's remote resource usage down from 5 to 3 in most cases and 4 remote calls only on our allow-failure cases that it decreases our transient failures by 2/5ths at least and more …

Use fork of Gravis-CI to test resilient features

---

AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java
AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java

The whole story is https://github.com/ankidroid/Anki-Android/pull/6481
The short story of this PR is that `mName` makes NO sens. For a deck "A::B::C", it's value is `{"A::B::C"}`, then `{"A", "B", "C"}` then `{"B", "C"}`, and finally `{"C"}`.
Instead of giving multiple meaning to the same parameter, I just:
* put a variable `mName`, which is final and set to `"A::B::C"`
* put a variable `mSplittedName` which is final and set to `{"A::B::C"}`
* use method with proper name (as suggested in https://github.com/ankidroid/Anki-Android/pull/6522#discussion_r444348710 ) to get the part of the name we want, i.e. last part of the name to display in the deck picker, full name in the card content provider.
* Confusing method `getName` which returns very different result depending on which function …

Deck name in node

---

AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java

Improving ankidroid speed by doing small efficient changes.
As discussed in https://github.com/ankidroid/Anki-Android/pull/5928 (and it would make
this other PR useless)
Accessing a deck by is name is done quite often. Being able to do it
in constant time consists in part of seconds win in a lot of actions,
allowing ankidroid to be faster.
In this particular case, a little difference from upstream anki makes
sens. Anki need to deals with a lot of add-ons, and add-ons may do
whathever they want to add-on. As we don't have this problem, …

Cache nameMap (performance)

---

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java
AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java
AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/FieldControllerBase.java
AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/IFieldController.java
AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.java
AnkiDroid/src/main/res/values/03-dialogs.xml
AnkiDroid/src/main/res/values/16-multimedia-editor.xml
AnkiDroid/src/main/res/xml/filepaths.xml
AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldControllerTest.java

There was no way to crop images previously, but cameras especially are generating very large images these days
This allows the advanced editor's image field component to crop images, and prompts users to do so for photos or if the image is large
This is entirely based on the work from @NightXlt - everything about how to do the Intent correctly, to the URI / File path conversion is their work
I took the PR contents of #5301 and re-factored them to fit better with the work done since @NightXlt originally submitted the work, then I tested, tested, and tested some more with little fixes related to preview handling and button visibility added in.
Finally, I deconstructed the work into chunks as small as I could so review would be easier.
**Please understand the commit separation was done after …

Add Crop functionality

---

AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java

This is the next step in order to load names before numbers: https://github.com/ankidroid/Anki-Android/pull/6522 
By itself, it would be nice to factorize code.
However, the main reason to do it is that it allows to create a second class, DeckTreeNode, which has no number. The tree can be created the same way in both class. In the class with numbers, numbers are added, limits are respected, while in the simpler class, setChildren simply change the value of mChildren.
In order to ease readability, I keep this PR small

Factorize main children

---

AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java
AnkiDroid/src/main/java/com/ichi2/anki/exception/StorageAccessException.java

I noticed while testing API30 emulator for another reason that it
still has problems with it's sdcard mounting (frequently starts unmounted),
and that secondarily we lose a lot of potentially useful information in
our exception handling in that case

NF: add path and root exception to StorageAccessException

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java

While developing card we may need to know AnkiDroid night mode status so we can switch css class property according to night mode status.
Return the value ```isInNightMode()```
1. Add to front/back side of card 
```
var isNightMode = AnkiDroidJS.ankiIsInNightMode();
console.log(isNightMode);
``` 
- [ x ] You have performed a self-review …

Night mode status in Card 

---

AnkiDroid/src/main/java/com/ichi2/ui/AutoSizeCheckBoxPreference.java
AnkiDroid/src/main/java/com/ichi2/utils/ViewGroupUtils.java
AnkiDroid/src/main/res/xml/deck_options.xml

Reminder CheckBox was truncated
Fixes #6576
Make all TextViews in the given preference AutoSize
* On my phone
* On an API 16 emulator:
https://stackoverflow.com/q/4267939/13121290
Have confirmed in source code that `TextView.mEllipsize` sometimes has `== null` checks
So much code for such a small change

Add AutoSizeCheckBoxPreference

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.java
AnkiDroid/src/main/java/com/ichi2/anki/services/BootService.java
AnkiDroid/src/main/java/com/ichi2/anki/services/ReminderService.java

Hopefully partially solving https://github.com/ankidroid/Anki-Android/issues/6524
AnkiDroid planifies reminder for specific deck option and not for specific deck. When the reminder is executed, it loops over decks to check which one has the correct type and have cards to review.
It is still slightly silly that the reminders run while anki starts, however that's still an improvement because instead of doing the action once by deck, it is done one by deck option, and the number of deck option is necessarily smaller than the number of deck.
I tested it by adding a reminder on my phone, seeing it working, and still being able to use ankidroid

Reminder becomes quicker

---

AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java

Their only difference is a single boolean. Useless to keep two copies
Currently tested on my phone

NF: remove one _groupChildrenMain

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java

There was an issue where certain note edits (tag changes etc) were not reflected in the card browser after returning from the note editor, an initial fix attempt used mReloadRequired to trigger that
But if you pass mReloadRequired back to flaschard reviewer you might get unexpected behavior, 
Partially fixes #6556 
Use the mChanged toggle to do trigger addition of "noteChanged" intent extra boolean in place of mReloadRequired
API29 emulator, reverting the previous change should fix the issue, and the noteChanged toggle is additive so should have predictable results - only consumed in the new place I added it in the card browser, which I tested and worked
@david-allison-1 and @Anthropos888  did the research on the related issue (thank you!) …

Reload CardBrowser but not reviewer when note edited

---

AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java

This allow in future commit to precompute the next card without
changing the count; the counts being changed only when getCard
actually return a card.
This would also avoid the code duplication of
```
card.getLeft() / 1000;
```
Except that instead we get comment duplication.
This is a commit from https://github.com/ankidroid/Anki-Android/pull/6026 ; the idea as usual is to ensure that https://github.com/ankidroid/Anki-Android/pull/6026 gets simpler to review. 
It has been tested on my phone for weeks (month ?)

NF: Decrement moved to decrementCount

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.java
AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/InstrumentedTest.java

This parameterizes the ContentProviderTest across the two scheduler versions, in an attempt to get us a bit more coverage across v2 scheduler which I don't think was being exercised much
@david-allison-1 you'll notice I added an "isEmulator" check and removed your `@Ignore` on the content provider test - this implies the assertion: if you are running the instrumented tests on an emulator you accept corruption may occur. I believe that's a valid assertion. Feel free to disagree! We can change it back
I also use the isEmulator check to only toggle the scheduler change on the collection if it is an emulator: same assertion applies.
@Arthur-Milchior two tests fail on SchedV2 - can you essentially take over this branch and investigate? I only made the PR as a convenient way to show how to …

Schedv2 testing

---

AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java

One of the reason loading a lot of deck takes time at startup is long is that we must do a lot of operations to check the deck collection. This is less computationally expensive than computing numbers, but still takes seconds. So this PR allows the method to take a parameter warning it that the deck is not yet checked, and that it should Timber in case of problem and just ignore the faulty deck. 
Right now, this feature si never used. It is of course a part of my bigger PR for improving starting time. I expect to use this new feature to make starting faster. And the few cases where the collection start with duplicate name or missing parents, the faulty deck will take a few seconds to appear while everything else will appear correctly immediately

NF: _groupChildrenMain deal with unchecked deck collection (performance)

---

.travis.yml

My PR for increased resilience in JDK installation was merged upstream,
this moves us back to using upstream vs my local branch
Related https://github.com/DanySK/Gravis-CI/pull/16
Just re-point the git repo we use
Travis will work or not

Use upstream JDK install scripts for CI again

---

AnkiDroid/src/main/res/drawable/ic_flag_blue.xml

The new blue flag `#77AAFF` had little contrast against the app bar.
But, `#0000FF` was too blue.
Fixes #6591
Compromise: `#1976d2`

Improved blue flag contrast against blue app bar

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java
AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
AnkiDroid/src/main/res/values/01-core.xml

For some reason we used to allow almost anything as a deck name. Even nulls (!?)
Upstream seems to silently disallow empty decknames, and I think we can reasonably go further and say deck names that don't have at least one non-whitespace character are nonsense
Fixes #6590
Create a quick valid deck name method, use it everywhere that Decks.id or Decks.rename is called to pre-validate
Toast with a new invalid deck name message if it's invalid
emulator, create a blank-named deck, rename a deck to blank name, create a filtered deck and try an empty name
Can't do any of those now
String.trim().isEmpty() (once you have null-checked) is efficient and "good enough" for non-whitespace checking. You can do a regex on `\\w+` or similar, and maybe there are UTF-16 or HTML people can get through but …

Disallow invalid (null || only whitespace) deck names

---

AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java
AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java

This should solve
Fixes #6587 while still
doing resets only when they are required.
The main problem is that "counts" mean "number of cards to see today, ignoring current card if any".
The trouble here is that "current card" was not something the scheduler new about. So instead we have ad-hoc code to ignore the current card. Essentially, when "getCard" is called, it is assumed it is giving the current card. When "undo" is called, it reset the scheduler twice and manually change the count of the current card.
The good news is that https://github.com/ankidroid/Anki-Android/pull/6585 is already dealing with saving current card. So this can be easily used to correct the counting. When counting is reset, we take current card into account to know what to change. 
Of course, we may just consider …

Counts reset if required

---

AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java

This require to recreate string from an array of string, it is
uselessly long, and caching it should win fraction of seconds when
creating deckDueList and checking the set of decks, by allowing to
access parents faster
I added it into my "merge" branch and tries it on my phone

NF: cache the result of "parent"

---

AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtonStatus.java
AnkiDroid/src/main/res/menu/reviewer.xml
AnkiDroid/src/main/res/values/02-strings.xml
AnkiDroid/src/main/res/xml/preferences_custom_buttons.xml

Changes were requested for the `Pen Color` feature:
* Set as `ifRoom`
* Add Pen Color Preference to "App Bar Buttons" in Reviewer
I also made the following change to make the app bar text consistent
* Rename the menu item to be consistent
Fixes #6601 
On my device - no longer in the app bar, and the preference works.
⚠️ Didn't want to block the PR, but two issues. Happy to have the PR blocked on me fixing them:
* Clicking the app bar icon again doesn't dismiss the color picker. A color needs to be selected
* The white swatch only has a shadow on a white background - worse for dark on dark

Improve Whiteboard Pen Color - App Bar Position, Settings and Text

---

AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java

_fill... does not change the count, so the deleted conditional was
always true. This change simplifies the code.
Tested on my phone now

NF: simplify _fill

---

AnkiDroid/src/main/res/values/02-strings.xml
AnkiDroid/src/main/res/values/07-cardbrowser.xml

The card browser has two columns "Edited" and "Changed" which refer to the Note and Card modification time respectively. This change was just recently adopted by Anki desktop (see the linked PR in #6519 which was closed instead of merged due to translations).
Edit by Arthur: upstream commit is https://github.com/ankitects/anki/commit/f3febea4b059116abf30006853974091a2998890
Fixes #6519 
Changes labels XML
On device
Android 5.1.1 device (Model A571VL)

Clarify two columns of card browser

---

AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java

Actually, it would be a bad idea to use it ever. If we want to allow
multiple background tasks simultaneously, we certainly don't want to
ever have this static access
As required here https://github.com/ankidroid/Anki-Android/pull/6609#discussion_r449800784

NF: remove a method unused

---

AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.java
AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.java
AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.java

Uses normalize name for nameMap and ensure it is impossible not to do so
Hopefully
* Fixes #6612 
* Fixes #6613 
Hidding the hash map in a data structure, so that it can be accessed only in the expected ways.
Running on my phone
I can't test that #6612 and #6613 won't occur again, as I don't know how it did occur, even if I would expect that in this case, there is a deck "A" with a child "a::B" and the change in case (or any other normalization process) may have created the problem in the first place

Synchronize deck name

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/res/values/03-dialogs.xml

This should be recoverable assuming no other threads crashed.
I would hope that this is fine, as it should be a large allocation which fails
Fixes #6608
Untested

DeckPicker Background - Catch OutOfMemoryError

---

AnkiDroid/src/main/java/com/ichi2/libanki/Media.java
AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java
AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
AnkiDroid/src/main/java/com/ichi2/libanki/importer/AnkiPackageImporter.java
AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.java

This is a pure guess about fixing an issue: #6606. When importing, I saw lots of warnings about files not being closed.
We close the files
A few large and small imports on my phone.

Use Try With Resources on Import (close streams)

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java

#6026
It let the scheduler knows which card is in the reviewer.
By itself, it is useless, but it should let #6026 become smaller
It is a prerequisite to https://github.com/ankidroid/Anki-Android/pull/6594 too

Save current card

---

AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java

If the exception is catched, the method returns false. If it is the case, mLoadingModelsHandler will throw a new run
time exception without any context.
I believe in this case, it's better to avoid doing try/catch, because if the app crash anyway, at least, the error
message will have slightly more context.
It's on my phone, but I don't expect to ever have a note type without id, so this case should not present itself anyway. Furthermore, since the only difference is going to be that the error message should get more information, it would be hard to test

NF: remove a try catch

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java

Since it's called again on onResume, it's useless to keep computing it in background.
No reason to use `tasksToCancelOnClose` since it does the same job as CancelAllTasks
Running it on my phone

Cancel load deck count on pause

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java

For consistency with remaining of the code

Avoid fully qualified name

---

AnkiDroid/src/main/java/com/ichi2/async/BaseAsyncTask.java

This should never occur according to Android's documentation. But it was requested in
https://github.com/ankidroid/Anki-Android/pull/6610#discussion_r449897060

NF: Warns if onPostExecute is done after cancellation

---

AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.java
AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java

Model count task was uselessly inefficient. And was still running even when the activity gets killed. this PR corrects that.
Running on my phone

Optimize model count (performance)

---

AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.java
AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java

doing a second search can take time if a search is still processing. Cancelling task had no effect if the task was already started. this is now changed
Testing on my phone

NF: card search: cancelling checked more often

---

AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.java

Noticed a non-standard import while picking 2.12 items from master
Replaced non-standard import with standard one
It's a unit test so I ran `./gradlew jacocoUnitTestReport` afterwards and it worked

Use standard Arrays import in SchedV2Test

---

AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.java

Fun fact, did you know in Java, ".trim" remove only the ' ' character https://docs.oracle.com/javase/7/docs/api/java/lang/String.html#trim() https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java#L851
while in rust, it removes all "Unicode Derived Core Property White_Space."
https://doc.rust-lang.org/std/string/struct.String.html
https://github.com/ankitects/anki/blob/master/rslib/src/decks/mod.rs#L128
So I'm moving the "strip" function so that it deals with all whitespace.
Not sure it will solve https://github.com/ankidroid/Anki-Android/issues/6383 but it should be a way forward at least. 
The main trouble with https://github.com/ankidroid/Anki-Android/issues/6383 being that I have no clue where we did remove some new line symbol, it …

Decks: Strip whitespace in children as well as parents

---

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java

Apparently it is possible for the model and the preview bundle to
be out of sync, unsure how it came about but now we won't populate off
the end of the field array and we will carefully clean up after
CardTemplatePreviewer where before no cleanup was done
Fixes #6644
I harden the array access that caused the crash so that is not possible at all, so we shouldn't crash
Why did we get there though? I'm not 100% sure and don't have the time to run it to ground completely unfortunately
What I did add was cleanup though - perhaps the fields and model were out of sync because no cleanup was done? So now I do a start-for-result to open the card template previewer and I close it carefully while cleaning up the TemporaryModel file which had been orphaned before
API29 testing - I could not replicate …

Protect against stale field info in CardTemplatePreviewer

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java

FileProvider can throw unchecked exceptions
Not a fan of system APIs throwing RuntimeExceptions, they catch me out like this too frequently
Fixes #6628 
Pokemon error handling, fall back to non-FileProvider URI, consumers of the method already have hardening against the image still being non-existent in case fallback / non-FileProvider style results in invalid URI
Difficult to test unfortunately but when I feed bad data as image references into the image field editor I can't make it crash. I couldn't make it crash before though unfortunately and there is no good test infrastructure here yet
Always always always check underlying APIs to see if they can throw RuntimeExceptions

Handle Exception from FileProvider in crop

---

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java

Fix a crash loading SVGs on Android API levels that don't natively support them
Fixes #6665
Note there are two ways to successfully use SVGs, one is to do:
AppCompatDelegate.setCompatVectorFromResourcesEnabled(true)
...but they warn there that if you change Configuration it is not recommended.
I believe we might be doing that for our language handling, so I chose the
other method, directly using the VectorCompatDrawable class, which works fine
#6665 was easily reproduced by setting AppBar Buttons to always show the whiteboard color pallete and opening the reviewer in an API16 emulator
Both methods mentioned above solved the crash independently, but one appears safer so I chose that.
It no longer crashes
Be really careful with vector icons, this will be important to do correctly in #5134 …

Load SVG in compat mode for lower APIs

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.java
AnkiDroid/src/main/java/com/ichi2/utils/WebViewDebugging.java

Fixes error: "Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377"
This is caused by the following factors:
* The ACRA process (:acra) does not terminate if an error dialog is shown
* We want analytics in :acra
* UsageAnalytics gives much better data if using the WebView user agent
* WebSettings.getDefaultUserAgent now creates the WebView process
Fixes #5502
We do have an API to fix this >= API 28: WebView.setDataDirectorySuffix
< API 28, we use an imprecise user agent.
I did not unit test this, as instrumented tests use AnkiDroidApp, and `WebSettings.getDefaultUserAgent` does not create WebView under Robolectric
Instead, commented out the Debug Timber code, and tested on my device. Can no longer cause a crash.

ACRA: Fix crash when restarting app

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java

We want to send exception reports sometimes only if silent
I believe I was accessing the incorrect prefs values to do that, this attempts to use the prefs values we use to toggle the ACRA dialog or not for silent sending
Related #6662 - where we add telemetry on crop URI errors but only if silent
scanning AnkiDroidApp I noticed the keys were different in how we set ACRA to send or not, I followed existing pref key usage
Admittedly I have not :cowboy_hat_face: but.....seems self-explanatory? Default pref value of "ask" (so we won't think we are good to go) then a safe string comparison with the always key...looks legit
Always read code 4 times, especially related code.

Use AnkiDroid-specific ACRA pref for always send

---

AnkiDroid/build.gradle
AnkiDroid/src/test/java/com/ichi2/anki/AnalyticsTest.java
AnkiDroid/src/test/java/com/ichi2/anki/ProductionCrashReportingTreeTest.java
AnkiDroid/src/test/java/com/ichi2/preferences/PreferenceExtensionsTest.java
AnkiDroid/src/test/java/com/wildplot/android/rendering/PieChartParameterizedTest.java
AnkiDroid/src/test/java/com/wildplot/android/rendering/PieChartTest.java
AnkiDroid/src/test/java/com/wildplot/android/rendering/PieChartTestParametersBuilder.java
build.gradle

Keep track of upstream dependencies, slowly pulling in external change as we can vs as we have to
This is kind of a big one:
1. The jetbrains-annotations one was blocked by an external transitive dependency, which I use gradle to force (tested, working)
1. Mockito 3.4.0 has static mocking capabilities (yay!) so I converted away from PowerMock for everything
1. A gradle plugin update always sort of implies we all should upgrade Android Studio, so yeah get on that
Fixes #6672 
1. I used a gradle resolutionStrategy to force our jetbrains-annotations version after an upstream PR looks like it's going nowhere
1. I used `Mockito.mockStatic()`to re-implement our unit tests that mocked static things
It's literally all tests and lint, so I was testing and linting all the time to do it :-)
1. …

Dependency updates 20200716

---

AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java

Getting an array, changing its value, and putting the array back is useless. So I remove the `.put`.
Similarly, creating a new array is useless, editing the old one is clearly sufficient since the objects/arrays are not shared.

NF: Remove useless code

---

AnkiDroid/src/main/java/com/ichi2/utils/JSONObject.java

While trying to port upstream test, I found a bug. I realized that I was unable to copy object, they always ended
empty. I've now found why.
This method is not used anywhere in the code, so it did not lead to any real bug.

Correcting copy of JSONObject

---

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java

Previewer was not copying fields from the Note Editor. 
See 184effd4d1c47fb3308b26bd308bcce36ccdb7e4 for original change
Fixes #6684
Fix obvious bug
⛔ Not tested well enough, trivial test on my phone - happy to delay for further testing
We need more testing in this area of the code

Fix: Previewer Now Displays NoteEditor Fields

---

AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java
AnkiDroid/src/main/java/com/ichi2/utils/StringUtil.java
AnkiDroid/src/test/java/com/ichi2/utils/StringUtilTest.java

In Anki, whitespace before a filename matters, whereas whitespace after a file is ignored.
This is visible in the following decks:
https://ankiweb.net/shared/info/1616679068
"GENKI I Grammar Deck with native speaker audio and images"
https://ankiweb.net/shared/info/1833515795
"GENKI II Grammar Deck with native speaker audio and images"
One defines "5.mp3", and the other defines " 5.mp3".
This works in Anki Desktop.
Fixes #6693
We fix this by only performing a trim on the right hand side, and only if the string is not a URI
Tested on my phone:
* With the above decks
* Added trailing whitespace, both passed.
See #6693

Fix Audio Whitespace Handling

---

AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java

While porting upstream test, I realized a method's name was badly ported. I also change its type because the method always return two elements, so an array is less precise than a Pair

Scheduler: _fuzzIvlRange - Return Pair instead of Array

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/main/java/com/ichi2/libanki/Note.java

I expect it to make upstream tests more clear. The actual unit test just tests whether dupeorempty return a truthy value, but since Java does not allow `if (n)` for `n` an integer, at least, test will be readable

NF: dupeOrEmpty returns an enum

---

AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java

this is the way it's done upstream.
NF because this method is never called (but I will call it in upstream test)

NF: deleting a deck delete it's card

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.java
AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/main/java/com/ichi2/libanki/Note.java
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java
AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java
AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.java
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.java
AnkiDroid/src/test/java/com/ichi2/libanki/ClozeTest.java
AnkiDroid/src/test/java/com/ichi2/libanki/MathJaxClozeTest.java
AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.java

While porting upstream test, I did realize that sometime I only needed ids of cards of a note and not the cards itself. I added the method; I then realized that this method could be used in a lot of place. While replacing this method, I then realized that, often, either we only take the first card, or we take the size, so I created method to do it more efficiently and with less code

Optimize obtaining card metadata from Note

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.java

On my phone, tests break, because the schedVersion is checked even if the sched version was not actually changed. So I
used real test instead.
I believe that what would be even better would be to run the tests only once if we are on phone, but I don't know how to
do it
I tried to follow https://github.com/ankidroid/Anki-Android/pull/6712#pullrequestreview-453227021 but it does not work for reason I don't really understand. Probably because setup halts but teardown is still executed

Correcting test on phone

---

AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
AnkiDroid/src/main/java/com/ichi2/libanki/Undoable.java

Porting upstream undo test is complex, because they are not really the same thing. E.g. "save()" does not deal with undo in AnkiDroid.  In order to try to simplify it, I wanted to simplify the undoing code. I hope you'll find it more clear.
I'll put it in my merge branch and test it

Undo class

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/ImportTest.java
AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/MediaTest.java
AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
AnkiDroid/src/main/java/com/ichi2/libanki/DB.java
AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
AnkiDroid/src/main/java/com/ichi2/libanki/Models.java
AnkiDroid/src/main/java/com/ichi2/libanki/Note.java
AnkiDroid/src/main/java/com/ichi2/libanki/Tags.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java

Upstream has a method `list` to get a list of elements from the database. This is really similar to our method `queryColumn`.
I then realized that `queryColumn` is always called with `column` 0, so I removed this parameter. I renamed to be consistent with upstream. And since we only query for long and string, I created two methods for String and for Long, so that we can simplify the remaining of the code. This is consistent with `queryLongScalar` for example.
Once again, this is to help me port upstream unit test, by having them as close as possible to upstream.

Database: Replace "queryColumn" with "list" methods

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java

Tests throughout the whole code, even if the only problem known to date is in:
```
if (!mEditorNote.cids().contains(mCurrentEditedCard.getId())) {
```
This should solve #6719
Testing it on my merge branch and trying to reproduce the bug

Tests whether mCurrentEditedCard is null

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java

While creating https://github.com/ankidroid/Anki-Android/pull/6721 , I realized that some background tasks received task data that are never actually used. This PR remove them.
I'm sorry, in this case, I can't prove to you that this PR is okay, you'll need to go and check that Import does not uses the boolean, Rebuild_cram and Empty_cram does not uses any task data.
I'm testing it on my phone, in my Merge branch

Remove useless task data

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/java/com/ichi2/anki/UIUtils.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java
AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java

This ensure that, whatever the choice we made later for tasks, the caller will remain simple to change. 
This is the biggest problem I have now when I try to create macro to automatize change in CollectionTasks

NF: Move `new Listener` outside of function

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.java
AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/ImportTest.java
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
AnkiDroid/src/main/java/com/ichi2/libanki/Models.java
AnkiDroid/src/main/java/com/ichi2/libanki/Tags.java
AnkiDroid/src/main/java/com/ichi2/libanki/Undoable.java
AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java
AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.java
AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java

Upstream did rename `remCards` to `remove_cards_and_orphaned_notes`. I follow the name change; mainly because it's far easier to port upstream test if I can stay as close as possible to them and uses the same function name.
While looking at this method, I realized that it was inefficient, and led to a lot of useless code written. The main problem is that it used to take an array of long, and that we essentially do not uses array in this code. So I changed it to uses a list of long, which allows to removes a 18 conversions from list to array. 
I renamed `arrayList2array` to `collectionOfLong2array`, because the method can work on any collection, and I actually wanted to apply it to a collection which is not a list. Similarly ids2str accepts any iterable and not only list.

NF: remCards follow upstream and simplified

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/java/com/ichi2/anki/UIUtils.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java
AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java

This reverts 72c701db2662af07f7ce82b1841efa7b32314f48. In 2013, if I understand correctly, it was thought that some
listener will eventually uses the Tasks. This led to two similar type, Listener and TaskListener. This never occurred in
7 years, I believe that we can remove this code duplication and keep using TaskListener.
This will ensure that no more people, like me, lose time trying to understand why we have a class and an interface
This will improve, I believe, the result of https://github.com/ankidroid/Anki-Android/pull/6721

NF: Single Listener

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DialogHandler.java
AnkiDroid/src/main/res/values/03-dialogs.xml

We have a rate limit of 2 minutes per automated sync (Tasker/ADB)
The error previously showed "Server busy. Try again later."
Fixes #6733
Now it shows "Sync Error: An automatic sync may be triggered in %d seconds."
Used: `PS C:\Users\David> adb shell am start -a com.ichi2.anki.DO_SYNC`
Tested on my phone - looks good
Slightly incorrect error messages lead to a lot of debugging

Improve automated sync rate limit error

---

AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java

This is related to https://github.com/ankidroid/Anki-Android/issues/6383
I add an assertion, so that if the bug occurs again, we get more interesting informations: e.g. the name of the deck whose parent is not seen. 
Normally, checkIntegrity has added the parent of all decks. The sorting function should ensure that parents are seen before the children. So either it's a problem related to normalization or something similar, in which case it may help understand it (assuming at least that Acra does not break unnormalized unicode)
If, as I suspect, it's a problem related to the fact that the set of deck was changed while the method is executed, i.e. because of sync or renaming... then this will occur so rarely that I don't expect to see many bug reports, and I don't really see how to get …

Assertion to try to debug https://github.com/ankidroid/Anki-Android/issues/6383

---

AnkiDroid/src/main/res/values/03-dialogs.xml

* We don't end single sentences with a full stop
* We don't need superfluous translations as CrowdIn handles them
From Review: #6735
https://github.com/ankidroid/Anki-Android/pull/6735#discussion_r460383795

NF: AutoSync error - Fix plural translations

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java

It helps in dynamically show / hide ```deckname, card count and time``` at top using status of ```topbar``` and ```fullscreen``` like in image below. 
```javascript
<script>
if (!AnkiDroidJS.ankiIsTopbarShown() && AnkiDroidJS.ankiIsInFullscreen()) {
showCustomTopDesign();
} 
// else hidden
function showCustomTopDesign() {
...
...
}
</script>
```
Using ```JavascriptInterface```
Testes on emulator.
1. Add to front/back side of card
```javascript
<script>
console.log(AnkiDroidJS.ankiIsTopbarShown());
</script>
```
- [ x ] You have not changed whitespace …

Get Topbar shown status in card

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java

onPostExecute can't get null. It's not returned by doInBackgroundDeleteDeck, and if the task is cancelled, then
onPostExecute is not called.
This avoid useless code

NF: doInBackgroundDeleteDeck don't return

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java

Currently, it takes an array, and we never use it, we always use it's first element. It's even more confusing because
this first element is a task data which contains any type. Sometime it contains an array of object. I strongly believe
it will make update slightly less confusing. At least for the few time when we actually use it

NF: listener's onProgressUpdate take a single element

---

AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java
AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
AnkiDroid/src/main/java/com/ichi2/libanki/importer/AnkiPackageImporter.java
AnkiDroid/src/main/res/values/02-strings.xml

Copies the following changes to allow imports of a apkg containing a collection.anki21 file without crashing when importing media
----
ankitects/anki@9d6523e
ankitects/anki@b9280ca
----
Fixes #6764
* A few import regression tests on my device. The test deck provided by the affected user now imports with no error
* ⚠️ I feel this needs better testing still, it's a fairly involved change, and I'm not the most familiar with the code
* Exporting the single deck now works

Allow import of SchedV1 collection.anki21 files

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/main/res/values/02-strings.xml

* Clozes crashed if selecting from right to left then inserting
* Clozes could not be added by Ctrl+Shift+C like they could on PC
* Fixes #6762 
* Fixes #6014 
For the bug: enforce start <= end
Added the keyboard shortcut
Tested on my phone with bluetooth keyboard attached
You can't test most Ctrl+Shift commands on an emulator: https://issuetracker.google.com/issues/37142228

Note Editor: Improve Cloze handling (Ctrl+Shift+C shortcut & crash fix)

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java

Field did not need to be static.
Fixed in 0033ac17616d2accb8cdc1ab8cb301fc6cd3477b - null safety
Reset to null in onCollectionLoaded at cd6a9e6b2d8dbc6eee584823d7e3323742a82f1c
Fixes #6728
Make field non-static
On my personal device - no crashes. 
We may want to lint variables to see if they meet the naming conventions

NoteEditor: Made mCurrentEditedCard non-static

---

AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtonStatus.java
AnkiDroid/src/main/res/menu/reviewer.xml
AnkiDroid/src/main/res/xml/preferences_custom_buttons.xml
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.java
AnkiDroid/src/test/java/com/ichi2/anki/reviewer/ActionButtonStatusTest.java
AnkiDroid/src/test/java/com/ichi2/testutils/PreferenceUtils.java

* Previously, a user could not hide "Edit Tags" as the key was set incorrectly
* Users could not hide "Enable Whiteboard" as there were no preferences
* Users could not hide "Whiteboard pen color" and "Save Whiteboard" as they were re-enabled after being disabled
* Disable Whiteboard still appears - this is intentional
Fixes #6717
* Fix the key for tags
* Conditionally enable whiteboard preferences
* Add Enable Whiteboard to the preferences screen
Unit tested, and tested on my mobile, no buttons appear if all are disabled
The first unit test is always the hardest - getting preference keys was complex

Reviewer App Bar: Allowed all items to be disabled

---

AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
AnkiDroid/src/main/java/com/ichi2/libanki/Undoable.java

Thinking again about recent change, I realized I didn't really like it. I still believe that 1b3d8f59b9bf51557697e3485fd31132276ad46b is an improvement, however, it is not enough. The code should not be in a single class, neither CollectionTask nor Undoable. It should be where it makes sens, where its variables already exists, where the action to undone is done. This allow to read and compare the doing and the undoing far more easily.
Furthermore, it seems that all Undoable class but one are used a single time. So really, there is no problem in moving the class definition where it is used.

Better undo

---

AnkiDroid/build.gradle

They released rc02 of appcompat 1.2.0 we were on 1.2.0-rc01, should be okay to update?
They're iterating quickly after the major functionality release in 3.4.x, might as well track them since we are using their new MockStatic feature
They've slowed down a touch as they have gotten past the 3.4.0 release, 3.4.6 is out now and it seems as good a time as any to merge them in now

Dependency updates 20200730

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java

Allows for deck developers to stop loading heavy assets such as videos on LTE
Fixes #6783
Add relevant JS API
* Tested on my mobile - returns false when I'm on WiFi
* Using https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection
* `AnkiDroidJS.ankiIsActiveNetworkMetered() //false;`
* 🛑 Could a reviewer please test this on LTE. I'm paying £0.20/MB, and can't realistically use 4G (probably a good use-case for this API, but it'll cost me quite a lot of money to test this).
* JS API opens exciting possibilities
* https://developer.android.com/reference/android/net/ConnectivityManagerCompat#isActiveNetworkMetered() - doesn't say much
* https://stackoverflow.com/a/23879816
* https://developer.android.com/reference/androidx/core/net/ConnectivityManagerCompat#is …

Javascript API: Add ankiIsActiveNetworkMetered

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java

Improves the user experience of adding more than one note
Fixes #4788
Show the keyboard when save is pressed if the user is adding multiple notes
On my phone, works as expected
Tested on my bluetooth keyboard - the on-screen keyboard is immediately shown when focusing a field, so keeping it open did not seem problematic
* https://stackoverflow.com/a/7784904 . The accepted solution did not work

NoteEditor: On Add - Keep Keyboard Open

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java

This solves https://github.com/ankidroid/Anki-Android/issues/6670
I've just tested on my table, there is nothing ugly occurring when the screen loading. AnkiDroid image still takes the
whole screen. Then instead of having one white page with a loading symbol, there are two of thems. Which means that the
toolbar buttons does not move anymore. So when I press on sync, I know that the button won't be replaced by another
button such as "empty filtered deck" in the next second.

Split big screen when starting

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/java/com/ichi2/anki/UIUtils.java
AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
AnkiDroid/src/main/java/com/ichi2/libanki/DB.java
AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
AnkiDroid/src/main/java/com/ichi2/ui/BadgeDrawable.java
AnkiDroid/src/main/java/com/ichi2/ui/BadgeDrawableBuilder.java
AnkiDroid/src/main/java/com/ichi2/utils/DatabaseChangeDecorator.java
AnkiDroid/src/main/java/com/ichi2/utils/SyncStatus.java
AnkiDroid/src/main/res/drawable/badge_drawable.xml
AnkiDroid/src/main/res/menu/deck_picker.xml
AnkiDroid/src/main/res/values/04-network.xml
AnkiDroid/src/main/res/values/colors.xml

Users currently do not know if they have pending changes. We add a badge to fix this.
API 23+ due to DrawableWrapper
Fixes #3524
* Add a badge to the sync icon
* If the user does not have an account (clicking sync takes them to logon).
* If the changes require a full sync
* If the changes require a regular sync
* On each database query, check if the query starts with "
This badge is not set when changing decks - as it would be more annoying than helpful (even though changing decks is internally a change when syncing).
On my phone - Statistics and Browse do not trigger the icon, reviewing and adding notes do.
* Not listing false starts  - see the issue
* Android Drawables need a `.setBounds()` call if they're not
* `setBounds()` can be negative and still work
* UI is hard
* …

Indicator for unsynced local changes

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerKeyboardInputTest.java

Previously we were unfocusing the currently focused answer, we still do this but with a barely visible pause to indicate the correct answer.
Fixes #5683
Add a 20ms delay - enough for visual feedback, but not enough to slow reviews
On my phone with a bluetooth keyboard

CardViewer - Key Input - Highlight Pressed Answer

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.java

Sticky fields converted newline -> `<br>` after clicking Add. We don't want this while adding cards
Fixes #6795 
Use the UI values rather than the note values
On my phone, and via unit test
Still harder to test automatically then manually

Note Editor: Don't convert newlines on "Add" 

---

AnkiDroid/src/main/java/com/ichi2/ui/BadgeDrawable.java
AnkiDroid/src/main/res/values/colors.xml

The badge without a text item was reported to be too large.
* Issue #3524/
* Related #6804
Made the color more orange `#ff5e13`
Scaled the badge down if there's no text
On my phone

Improve Non-full Sync Badge UI

---

AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.java

Fixes #5143 by letting IntentHandler just finish, if it specifies an animation
it actually clobbers whatever system launcher animation is specified.
Piexel Launcher seems to override the override but Nova Launcher respects it,
meaning you don't get the Nova Launcher animation you configure
I used an API29 Google Play version emulator so I could install Nova, then I alternated launching the app with Google Pixel launcher (always does the zoom-type launch) and Nova (started as described in the linked issue, but now will do whatever animation you configure Nova to launch)
AnkiDroid has a surprising amount of Activity transition animation infrastructure, and we should probably use it more, in a consistent way, to signal to the user where they are (like, always slide in from right when going …

Preserve launcher animation by not animating IntentHandler finish

---

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java

Brought to light by 86a0f16886b128b90a0a54a8aa5489ea04085790. Both values are the same

NF: Fix lint errors

---

AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
AnkiDroid/src/main/java/com/ichi2/ui/TextInputEditField.java
AnkiDroid/src/main/res/layout/my_account.xml

`app:passwordToggleEnabled="true"` will reveal the field, even if data is obtained from AutoFill
Added in 5a677a4b73d25f7a8731b582c3b03ae8c7c17a68
This fixes the issue. I'll be reporting this to Google.
Also adds an auto-login if an auto-fill entry is clicked, 
Add a handler for an autofill event, disable the "show password", and attempt a logon if performed on the password field.
On my Android 9 device, and on an API 16 emulator (no autofill)
Google ಠ_ಠ

Improve Login Autofill Behaviour - Don't Show Password & Auto Logon

---

AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java

#6770 
I added a comment explaining what exactly `count()` is doing. I.e. Returning the number of cards to see today in each category, not counting the card sent to the reviewer.  This means that, by considering `mCurrentCard` I was over correcting because the counter already considered current card. I thus removed this over correction and added explanations about what exactly counts are and what they means in a normal use of the scheduler.
Trying to reproduce #6770 and also trying to to undo reviews/burying when the number of cards is limited by the set of cards and not by the deck's limit.
`counts` and various counts make really no sens; but I was supposed to know it already.

Fixes 6770

---

AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java

`ConcurrentModificationException` occurred when cancelling all tasks. Heaviest crash of the 2.13.x alpha series
Fixes #6653
`sTasks` was modified in the iteration, which shouldn't occur.
We didn't need a synchronized block as it's a concurrent structure.
⚠️  Only conceptually - doesn't crash on my device, but I can't guarantee I triggered the issue

Fix ConcurrentModificationException: task cancel

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java

It seems there's currently a state inconsistency which sets the badge even if there's no changes. This lets us revert to a good state
So: if no changes - remove the badge
Related: #3524
⚠️ Couldn't reproduce the conditions to test this.

Sync Status: Remove badge when no changes

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java

When saving a note, we convert a newline to `<br>`
We should do the same for Previewing
Fixes #6834
Fixes #6460
Convert newline to `<br>`
Tested on my phone - now shows as it would in reviewer.
Trivial fix, probably was a misstep to let it through as a defect, as defects are rarely looked back at.

NoteEditor: Fix newlines when previewing

---

AnkiDroid/src/main/java/com/ichi2/libanki/DB.java
AnkiDroid/src/main/java/com/ichi2/libanki/Note.java
AnkiDroid/src/main/java/com/ichi2/libanki/importer/NoteImporter.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java

For some reason, some new Object[] remained. There was actually a really simple way to remove them and clean the code

NF: remove "new Object[]" in queries

---

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java

The Card Template Previewer showed Front/Back rather than the currently edited note.
Fixes ???
This shows the edited note instead of "Front/Back"
BUT: This does not pass through the current values of the field and instead
returns the database values
Slight improvement, but we're not there yet
Tested:
* No Note - Front/Back
* Edit Note - Note
* Add Note - Front/Back

Card Template Preview: Preview Edited Note

---

AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java

All of those methods are not upstream, and are duplicated in both scheduler. Removing them ensure that it's clear that there is no difference between them

NF: remove methods not in libanki duplicated

---

AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java

This is a first part of https://github.com/ankidroid/Anki-Android/pull/6035
It splits reset in two: counts and queues. In cases where it is obvious, the counts only is used.
This is mostly going to be useful in future PR, where we get the first card without doing the costly operation of computing counts

Split reset

---

AnkiDroid/build.gradle

Took forever but it's finally stable. Last commit for them
was just the version bump so this should be a no-op

Bump appcompat from 1.2.0-rc02 to 1.2.0

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java

We were manually clearing the limiter on new versions or
when user toggled crash report preferences, but upstream added
the necessary APIs to do so, port to those
Fixes #4968
Propose a change to upstream when you find yourself poking a hole in an abstraction, then port to the APIs upstream when implemented
I wrote an instrumented test that verified the behavior long ago, and it still does -> yay automated testing
I don't believe I learned a thing here currently. In the original upstream PR I learned how receptive most projects are to good ideas, which was formative in how I participate in the development of my dependency network

Use new ACRA APIs to clear AcraLimiter

---

AnkiDroid/src/main/java/com/ichi2/anki/Info.java
AnkiDroid/src/main/res/values/02-strings.xml

I once had a user ask what to do once they clicked the button, I remembered this when accessing the screen, I hope this will mean it won't happen again
Add toast to both success and failure case.
I don't expect the failure case to happen
On my device
Make everything as obvious as possible

Added toast on debug info copy

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/java/com/ichi2/utils/SyncStatus.java
AnkiDroid/src/main/res/values/10-preferences.xml
AnkiDroid/src/main/res/xml/preferences_general.xml

User requested that the badge should be disabled
Fixes #6856
Via a preference - default to true
On my phone - disabled and enabled as expected
YAGNI isn't always right

Allow the user to disable the Sync Status Badge

---

AnkiDroid/src/main/res/values/02-strings.xml

Caught the warning while looking at build logs.
> /home/travis/build/ankidroid/Anki-Android/AnkiDroid/build/intermediates/incremental/mergeReleaseResources/merged.dir/values-af/values-af.xml:375: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.
After a quick google, I can't determine how to turn this into an error. It's a C++ check, rather than a regular lint check. Maybe we can fail if warnings are returned from compileLint?
https://cs.android.com/search?q=%20%22multiple%20substitutions%20specified%20in%20non-positional%20format%22&sq=&ss=android
Fixes #6868

Fix: Use positional format strings

---

AnkiDroid/src/main/java/com/ichi2/libanki/Card.java
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java

I realized the Card Cache from https://github.com/ankidroid/Anki-Android/pull/6372 can be useful for other purpose too. So I extracted its core in a distinct PR and put the Cache in Card.java. Currently this is NF because this class is not used. I would still like that you confirm that it's a nice way to save card without loading them until needed, but still loading only once. I expect that it will save loading time from database. 
There is a cost however, because if the card is loaded in advance and the card content changed, the new question/answer may or may not be already computed. So it should not be used in every circonstances

NF: add a class CardCache

---

AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java
AnkiDroid/src/test/java/com/ichi2/libanki/UtilsIntegrationTest.java
AnkiDroid/src/test/java/com/ichi2/testutils/NullApplication.java

1h30 currently renders as 2h30
Fixes  #6894
Use math.floor instead of math.round
Unit Tested

Fix time rounding errors

---

AnkiDroid/src/test/java/com/ichi2/libanki/CardTest.java

I'm adding tests related to change in anki 2.1.28. This port succesfull test I created in https://github.com/ankitects/anki/pull/733
It's only "assume" because I've not yet ported those change. I don't speak rust well enough to know how it is implemented and whether Damien found an easier way to code it than just checking manually whether a field value is used in the process.

NF: Add test for card generation

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
AnkiDroid/src/main/java/com/ichi2/async/TaskData.java
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java

The main speed gain here is that we don't compute question/answer unless they are asked by the user.
I find code more elegant, because we don't just deal with a map String->String but uses standard well typed Card object and its methods. 
To test it, I opened the browser, selected cards, marked them, flagged them. Ensured that all was still working, those updates were still correctly shown in the GUI

Browser: Don't compute question/answer unless they are required

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java

Fixes #6887
If a card is added, it states to reload the reviewer
trying steps as in https://github.com/ankidroid/Anki-Android/issues/6887#issuecomment-672990200
There still is a problem if editing a card lead to generating new cards. I don't see where the edited card is flushed, so I don't know where to check whether the edition generates new card. I'd need help to solve this similar bug

Adding a new card reload reviewer

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java

This is a new version of https://github.com/ankidroid/Anki-Android/pull/6026 
I believe the code is quite simpler. Instead of having a list of ID, I have a list of CardCache. That is, essentially, it's an ID, with potentially one more data, the card loaded and even the question preloaded. Thanks to this, I can preload the card content without needing to actually change anything about the content of the queue.
I actually usually preload two cards, because I do not know in advance whether the next card will be a card in learning or not. 
This also means that if for some unknown reason I got the next card wrong, the worst that will occur is that the next card will need to be loaded before being displayed instead of being preloaded.  I don't expect to get the next card wrong, but at this …

Pre compute the next card's question

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/ModelTest.java
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
AnkiDroid/src/main/java/com/ichi2/utils/DatabaseChangeDecorator.java

I want to look into requery's code to find the actual size of their
window.
I sent them a PR https://github.com/requery/sqlite-android/pull/129 in order to add a getter which returns this window
size to us. Ideally, it would allow to remove those constants from
AnkiDroid code which are here only to copy their constants.
Note that, as I expected, we can't use a chunk whose size is the
window (I tested); that's because the window contains extra
informations. So I decreased the window size slightly in order to have
something reasonable.
P.S.
Since Tim does not like github link in the code, I didn't put it in the code or commit message and just put it in the PR.
Even if, honestly, in this case, I believe that a github link in our comment would be good, as it would allow to link directly to …

Uses requery's window size

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/ModelTest.java

I can't test on my computer because it's a travis specific problem that .29 fails regularly. So I'll need to see how travis act if i change the way to create the big string

NF: bigQuery - optimize memory usage to avoid OOM in tests

---

AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/CardQueue.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/LrnCard.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/LrnCardQueue.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/SimpleCardQueue.java
AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java
AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java

Fixes #6903
Seems that in this case, the overriding of `remove` was not detected, because for a `List<>`; it thought I used
`remove(Object)` instead of the expected `remove(long)`
The second interesting thing here is that the class CardQueue was added last minute, and not tested in my merge branch
as the remaining of the PR.

Fixes #6903

---

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java

I do not know what changed, but the alpha is not changed anymore for bury/suspend. The icon is changed after the alpha,
so previous alpha is ignored. I set back correct alpha after changing the icon.
I suspect that onCreateOptionsMenu was called before invalidateOptionsMenu, which would explain this change, but I may
be wrong.

During slow operation, bury/suspend/flag/marked get correct alpha

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
AnkiDroid/src/main/java/com/ichi2/anki/MetaDB.java
AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java
AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java
AnkiDroid/src/test/java/com/ichi2/anki/ReadTextTest.java

My goal is to preload card as much as possible. This mean pre rendering html before actually needing to show it, in particular mathjax and loading media. This also mean that I need to deal with sound outside of the AbstractFlashCard Viewer. I believe that doing simple cleaning is a good first step to attain this goal easily. 
My point is that I'm not just doing refactoring for the sake of cleaning. I am doing it because I've got a goal in mind and that I expect that this will help reach it.
In this case, the cleaning is simply replacing int by an enum since there are only three valid values and that the value is never saved anywhere else, it is entirely NF

NF: uses enum for Sound side

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.java
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.java
AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java
AnkiDroid/src/main/java/com/ichi2/async/TaskListenerWithContext.java

David did mention in another PR that some background tasks were leaking activities. My first reaction was "and so ? All tasks listener leaks activities, and they have the same life duration"... 
Then I realized that actually this was probably a problem. Not a big problem as I've never heard of it creating any bug, but still, that's a useless risk.
So I transformed each anonymous listener into a static class. Since the listener still needs to have access to the UI in order to change it, I kept the access to the UI, however, I only use a weak reference. This way, if the activity can be freed, it will be freed.
That is, currently, if we start a background task and ends it, we are still updating the UI, even if the UI is not displayed anymore. With this change, the background task still …

NF: Listeners do not leak contexts

---

AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.java
AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/LocaleSelectionDialog.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ModelEditorContextMenu.java
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
AnkiDroid/src/main/java/com/ichi2/libanki/Models.java
AnkiDroid/src/main/java/com/ichi2/libanki/Note.java
AnkiDroid/src/main/java/com/ichi2/ui/RecyclerSingleTouchAdapter.java
AnkiDroid/src/main/res/layout/locale_dialog_fragment_textview.xml
AnkiDroid/src/main/res/layout/locale_selection_dialog.xml
AnkiDroid/src/main/res/menu/locale_dialog_search_bar.xml
AnkiDroid/src/main/res/values/02-strings.xml
AnkiDroid/src/main/res/values/03-dialogs.xml
AnkiDroid/src/main/res/values/17-model-manager.xml

I've removed the draft flag - I'd like to get this in and refactor if it gets traction and then refactor (if feasible)
----
This needs investigation as to whether this can be simplified via 
```java
InputMethodSubtype ims = InputMethodManager.getCurrentInputMethodSubtype().getLocale();
```
If this works (50/50 - Android IME options are flaky), then the field editor fragment and locale selection screen can be removed and this feature is much smaller.
* This does not handle an "unset" - I don't feel this is necessary, but that's borderline.
* We use `Locale.getAvailableLocales()` for the locale list, we currently use the system language. Do we want to use the AnkiDroid language here?
* Does this need to be split up further to make it reviewable? Where are the pain points currently?
Feature …

Allow user to set Language Hints for Note Editor fields

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java

According to documentation " If you override this method you must call through to the superclass implementation."
https://developer.android.com/reference/android/app/Application#onTrimMemory(int)
I'm still on current version of ankidroid to see whether I can reproduce a bug, so I've not yet tested it.

onTrimMemory call super

---

.idea/codeStyles/Project.xml

This change started coming in persistently after the Android-Studio-recommended update to the new kotlin plugin
The file doesn't change much (maybe once a year or so) so previous bet that leaving it committed still seems sane

Ingest kotlin-plugin changes w/plugin 1.40+

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/ModelTest.java

For some reason API29 is flaky on StringBuilder->String conversions.
Tried hard to track it down for real but for now I'll just de-flake the test as it seems to work 100% everywhere else and there are no reported user problems with the code
https://github.com/ankidroid/Anki-Android/pull/6901#issuecomment-675020993 
Check the API of the device running the test, skip if it's API29
Visual inspection of the test run on API29 and API30 emus at the same time, it was skipped on API29 but ran on API30, as expected
Strings in java and memory management are very difficult. This is actually one of the first tough problems I hit with Java, like, 20 years ago when XML was the range (DOM vs SAX parsing anyone...? anyone?)

Ignore big model test on API29, flaky

---

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java

The plan is to add a revlog entry when previewing in the future; this
is just a temporary fix.
NF: Porting https://github.com/ankitects/anki/commit/d266f9a80a289012e46051af023008e8ab9dc7bb
Fixes #6916

revlog entry should not be deleted when undoing preview card

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java

My goal is to preload card as much as possible. This mean pre rendering html before actually needing to show it, in particular mathjax and loading media. This also mean that I need to deal with sound outside of the AbstractFlashCard Viewer. I believe that doing simple cleaning is a good first step to attain this goal easily.
My point is that I'm not just doing refactoring for the sake of cleaning. I am doing it because I've got a goal in mind and that I expect that this will help reach it.
In this case, the cleaning is simply avoiding a constructor / toString when it is never useful

NF: remove Spannable from a string where it is never used

---

AnkiDroid/src/main/java/com/ichi2/anki/MetaDB.java
AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java
AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java
AnkiDroid/src/test/java/com/ichi2/anki/ReadTextTest.java

I missed that the SoundSides were saved in database. I only checked when the variables where created and didn't think
that they may only be used to create query.
I'm still surprised that this break anything. I would have expect that, at worst, it would reset all TTS saving (which
would already be a problem in itself), since the same QA representation value would be saved each time the database is
queried (and sql would have no problem saving anything in any column of a database)
----
Fixes #6919

BUGFIX: Correctly persist TTS data (Fixes #6919)

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.java

`super.onSaveInstanceState` was called too early which caused a crash from `dismissAllDialogFragments` when called from `onPause`
Fixes #6923
* Extract `performPreview` to allow testing
* Extract the method to add to bundle without calling `super.onSaveInstanceState`
Tested on my phone, no longer crashes
I'll prioritise getting the monkey set up for 2.14, this would have caught it before release. Unit Tests weren't helpful in this situation as Robolectric did not mirror real life.

Note Editor Preview: Fix Crash

---

AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java

This tries to deal with #6769 by reproducing the bug I understood and other similar feature
It also shows how propagating limit and daily increase may have strange behaviour that are still what is expected (but
we can't expect user to understand that without a good knowledge of datastructure)

Unit test for daily increase

---

.travis.yml
AnkiDroid/build.gradle
AnkiDroid/robolectricDownloader.gradle

The periodic CI-deflake PR
The API27 flakiness is semi-new and not expected. Has caused lots of false negatives in the last few days though.
The robolectric jar thing doesn't happen often but has happened since we started using robolectric, and just had some sort of network flare up this morning which reminded me about it
Disables API27, so that won't be a problem.
Stole a robolectric SDK jar pre-downloader from a gist, it just stuffs them in the expected place if they were downloaded to begin with so should be pretty transparent except now it is a separate step so we may use travis_retry with it
Local testing during development, and now in Travis - the whole thing is tests...
There is a robolectric gradle task in development which may supercede this when I researched best practices, but …

Travis CI API27 disable / Robolectric jar pre download w/retry

---

AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java

`_fillLrn` should have been replaced by `_preloadLrnCard` everywhere. This was not actually creating an error, but the
correct card was not actually preloaded. So this lead to useless computation

Correct _fillNextCard.

---

AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java
AnkiDroid/src/main/java/com/ichi2/libanki/Card.java
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
AnkiDroid/src/main/java/com/ichi2/libanki/stats/AdvancedStatistics.java
AnkiDroid/src/main/java/com/ichi2/libanki/utils/SystemTime.java
AnkiDroid/src/main/java/com/ichi2/libanki/utils/Time.java
AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.java
AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.java
AnkiDroid/src/test/java/com/ichi2/testutils/MockTime.java

This does a lot of related work together.
`now()` does not exists upstream. I remove it and replace it by `intTime`. I checked each line, there is not a single time where I see a reason to use a float. No multiplication that create number big enough that long can't represent them. And we would not want to add float in the database. Furthermore, in multiple case, we cast a number to (int). 
Crt is a time stamp, number of seconds since epoch. Should not be cast to an int (even if, with 32 bits, we should still be safe)
setDue was getting an int instead of a long in `_answerLrnCard`. On the one hand, it seems suspicious because it's the right function to consider to search for a bug related to reviewing a card in learning. On the other hand, for 32 bit ints, this should not actually have …

Time is long

---

AnkiDroid/src/main/java/com/ichi2/libanki/template/Template.java
AnkiDroid/src/test/java/com/ichi2/libanki/template/TemplateTest.java

This is a rewrite of https://github.com/ankidroid/Anki-Android/pull/6851 which correct the code and a test.
The result of the test is the same as upstream (I just tested)
Fixes #6295
@mikehardy, I think you mentioned keeping a special case; maybe if a field A has {{type:B}} or {{B}} then B gets reinterpreted as another field if it actually exists and is ignored otherwise. We are not going in this direction. That's fine by me, but there is at least one user for which this change of behavior will be a problem

Colin p hill templates

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.java
AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractDeckTreeNode.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckDueTreeNode.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckTreeNode.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java

As David requested some time ago, I use the type system to determines whether deck nodes have numbers or not. I first compute deck nodes without numbers in order to be quick, and then with numbers. 
This lead to ![Screenshot_20200808-004202_AnkiDroid.jpg](https://user-images.githubusercontent.com/357361/89693896-2f085200-d910-11ea-8264-363b0f617521.jpg) almost immediately instead of waiting 10 seconds to get all numbers.
It has been tested on my phone for months now

Load deck tree before number on start

---

AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.java

The bug was caused by d694006 .
Essentially, the bug is due to the fact that I called reset while there is a card in the reviewer, without actually
taking the card in the reviewer into account. Which is something I corrected later thanks to considering mHaveCounts and
mHaveQueue separately.
This would explain #6898 and #6768
The idea here is that:
* the learn queue gets emptied during reset
* when the card is answered, it is added in the learn queue. But since the queue was empty and not yet refilled, it is
added in a dirty queue. Normally, it's not a problem when the queue is dirty and empty, because _fillLrn will simply
fill the queue again. However, as soon as there is an element in the queue, it is assumed that it is not dirty. This is
corrected thanks to mHaveQueue which simply state …

Regression test for #6966

---

AnkiDroid/src/main/res/values/12-dont-translate.xml
tools/manage-crowdin.sh

According to https://support.crowdin.com/api/update-file/ , currently, if a string is changed in english, it'll be
marked as needing review everywhere. This is a problem because we either want to add meta-clarification (for translator)
or correct typo. This change ensure that we have the behaviour we want; strings as never seen as changed. If we want to
really change a string, it'll be a new id
This can't be tested until it is actually merged in github.

NF: Change of string are not reflected in crowdin

---

AnkiDroid/src/main/java/com/ichi2/compat/CompatV19.java
lint.gradle

LinearLayout had changed to a FrameLayout
This caused a crash
Fixes #6977
Fix the cast
Also add a lint check to ensure this doesn't happen in the future
* API 16 emulator - ❌ #6984
* API 30 emulator - ✔️

Fix invalid cast: onSystemUiVisibilityChange

---

AnkiDroid/src/main/java/com/ichi2/compat/CompatV16.java
AnkiDroid/src/main/res/drawable-v21/footer_button_again.xml
AnkiDroid/src/main/res/drawable-v21/footer_button_again_dark.xml
AnkiDroid/src/main/res/drawable-v21/footer_button_all_black.xml
AnkiDroid/src/main/res/drawable-v21/footer_button_all_plain.xml
AnkiDroid/src/main/res/drawable-v21/footer_button_easy.xml
AnkiDroid/src/main/res/drawable-v21/footer_button_easy_dark.xml
AnkiDroid/src/main/res/drawable-v21/footer_button_good.xml
AnkiDroid/src/main/res/drawable-v21/footer_button_good_dark.xml
AnkiDroid/src/main/res/drawable-v21/footer_button_hard.xml
AnkiDroid/src/main/res/drawable-v21/footer_button_hard_dark.xml
AnkiDroid/src/main/res/drawable-v21/item_background_light_selectable.xml
AnkiDroid/src/main/res/drawable-v21/item_background_light_selectable_borderless.xml
AnkiDroid/src/main/res/drawable/item_background_light_selectable.xml
AnkiDroid/src/main/res/drawable/item_background_light_selectable_borderless.xml
AnkiDroid/src/main/res/values/attrs.xml
AnkiDroid/src/main/res/values/colors.xml
AnkiDroid/src/main/res/values/theme_dark.xml
AnkiDroid/src/main/res/values/theme_light.xml

Remove color attribute references from drawables to fix the crash on API < 21
Fixes #6984 
Tested in API 16 and 29 emulators

Remove color attribute references from drawables

---

AnkiDroid/build.gradle

Move all the testing dependencies to match the new release
There's a painful cross-dependency between fragment-testing running in-app and the androidx.test things that mostly run in the separate instrumentation APK, so we had to slip a transitive dependency but it's documented working in the documented (code, commit) link
The whole thing is literally tests, but API16 and API30 emus local, and now Travis will chew through them
Managing the Android ecosystem, even the testing library subset, and all it's cross-dependencies must be a nightmare, because they messed this one up.

Dependency updates 20200829

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java

In 8f3628f0fda73538b3a8e8739411d34b07239716 I removed one line by accident. The conditional was always false, the line
before was good. I add back this line.
Because of this, the browser had to be closed and reopen to work

Second column of browser repaired

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/LayoutValidationTest.java

We had a problem with layouts not working on API 16, this instantiates all layouts on all API levels
Related: #6991 
Load all fields from `R.layout`, and see if they can be inflated
API 16 and 30 emulators - likely needs a rebase to master to pass, but will be interesting to get an initial failure
* `R.layout` has hidden members, which are public, but hidden by the IDE
* You can't assign `R.layout` to a variable
* Some layouts need to be loaded on the UI thread

Add Test: Ensure layouts can be used on all APIs

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java

Fixes #6970
When a card was deleted, it was removed from the list of card. Its siblings was not. To reproduce, it suffices to try to delete a card without selecting one of its sibling.
I follow Mike idea in https://github.com/ankidroid/Anki-Android/pull/6611#issuecomment-653815157 to simply invalidate in case of danger.
Trying to reproduce the bug by deleting a single card of a note with multiple cards
You know what. Tests of the UI would be nice.

Correct 6970

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.java
AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.java
AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java
AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.java
AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.java

There are multiple things here.
I split undo in two, so that I get access to the actual background part without creating a background task nad having to deal with UI part. This is useful to entirely tests undo, since there are some parts of undo not done in col.undo.
Then, I add a test that bugs and should not bug. Thanks to David for explaining how to create it. Because of it, a card undone which becomes a learning card is not added to the learning queue. The problem is that `mCardNotToFetch` was not set to null even when it is not relevant anymore.
This was relevant for prefetching a card. Except that I forgot to tell the `preLoadCard` method to reset counts and queues if required, which made the method useless after a reset. (Actually, in the first version, preLoadCard was calling …

Bug: Undo and card in learning.

---

AnkiDroid/src/main/java/com/ichi2/compat/CompatV16.java
AnkiDroid/src/main/java/com/ichi2/compat/CompatV17.java
AnkiDroid/src/main/java/com/ichi2/compat/CompatV18.java
AnkiDroid/src/main/java/com/ichi2/compat/CompatV19.java
AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.java
AnkiDroid/src/main/java/com/ichi2/compat/CompatV23.java
AnkiDroid/src/main/java/com/ichi2/compat/CompatV24.java
AnkiDroid/src/main/java/com/ichi2/compat/CompatV28.java

The compat objects were missing copyright
Per request from @david-allison-1 
I just looked through git log on each object and attributed it to the original author

Add copyright to compat implementations

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
lint-release.xml

We can now start to enable lint warnings now 018c1db is in. 
Related: #5026
Enable warning
Ensure build still passes

LINT: Fix & Enable 'WrongConstant'

---

AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java
AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
AnkiDroid/src/main/java/com/ichi2/libanki/Undoable.java

Undo is slow. One of the reason is that it gets the card from the database. This is actually useless, we usually could as easily save the card than the ID. This lead to saving 20 card object instead of 20 long, this is not a huge cost in term of memory. 
Sending the card directly to the reviewer ensure that it can be displayed almost immediately. It removes one of the last slow operation I had on my phone. (There remains bury/suspend... but I've no idea how to improve this more at this time)
On my phone, doing undo and ensuring that it appears almost without delay.
When you spent dozen of hours working on background tasks and then some on the Undoable, and then on the list of undo, you can still miss this obvious optimization... and I don't know why it took me so much time to see it !
I …

Reviewer: undo gets faster (performance)

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
AnkiDroid/src/main/java/com/ichi2/anki/UIUtils.java
AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/MissingImageHandler.java
AnkiDroid/src/main/res/values/02-strings.xml
AnkiDroid/src/main/res/values/constants.xml
AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/MissingImageHandlerTest.java

Many users had problems with missing images due to a media sync not completing
This gives them advice, and hopefully reduces the support load
Fixes #7009
* Nothing on API 16 (as expected)  `onReceivedError` is not called. 
* Nothing (unexpected) - `onReceivedError` is not called. 
* Reviewer, Previewer and Card Template Previewer work
* Link has been tested
* Unit Tested
* Moving a snackbar is hard. I used https://stackoverflow.com/a/48472087
* https://github.com/ankidroid/Anki-Android/wiki/FAQ#why-doesnt-my-sound-or-image-work-on-ankidroid

CardViewer: Add Help for missing images

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/RescheduleDialog.java
lint-rules/src/main/java/com/ichi2/anki/lint/IssueRegistry.java
lint-rules/src/main/java/com/ichi2/anki/lint/rules/InconsistentAnnotationUsage.java
lint-rules/src/main/java/com/ichi2/anki/lint/utils/ImportStatementDetector.java
lint-rules/src/test/java/com/ichi2/anki/lint/rules/InconsistentAnnotationUsageTest.java

A common issue for new users is not using `androidx.annotation.NonNull` and instead using `org.jetbrains.annotations.NotNull`
This adds a lint error to the IDE, which also explains the setting to change to stop the error, reducing friction for code review.
#5026
Add a lint check for `org.jetbrains.annotations.NotNull` and `org.jetbrains.annotations.Nullable`
* Previously failed on a class I made, now passes.
* Unit tested
* Custom lint errors appear in the IDE
* The `explanation` field for the lint error is hard to find, so there is a CTA in the description
* Custom lint errors are awesome

Add Lint check: Use of JetBrains annotations

---

AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java
AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java
AnkiDroid/src/test/java/com/ichi2/libanki/AnkiPackageExporterTest.java

Anki Desktop has the same behaviour.
Previously threw a FileNotFound
Fixes #7023
Check the files exist, and skip if they don't
Integration test and tested on my Android 9 phone
This one had been live for a long time, still need more tests

Deck Export with media: Skip missing files

---

lint-release.xml

We've had many crashes due to translation/format string issues. This will hopefully them being merged without a fix.
Fixes root cause of 5026
Enable lint errors
This fails ❌, but I don't know how to format RTL percentages to fix it
<details>
```
C:\GitHub\Anki-Android-Git\Anki-Android\AnkiDroid\src\main\java\com\ichi2\anki\dialogs\RescheduleDialog.java:71: Error: Wrong argument count, format string reschedule_card_dialog_warning_ease_reset requires 0 but format call supplies 1 [StringFormatMatches]
String message = resources.getString(R.string.reschedule_card_dialog_warning_ease_reset, SchedV2.RESCHEDULE_FACTOR / 10);
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\GitHub\Anki-Android-Git\Anki-Android\AnkiDroid\src\main\res\values- …
```

Converted translation issues into lint errors

---

AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java

Related: #3524
Ignore `unburyCards`
Untested
There's likely still some cases where we can do better.

Don't mark unburying cards as a pending sync

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/ImportTest.java
AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
AnkiDroid/src/main/java/com/ichi2/libanki/Models.java
AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java
AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.java
AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java
AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java

Was unnecessary (test-only) and added a lot of compiler warnings
Untested (outside unit tests still passing)

NF: Remove generic time from Collection

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java

Fullscreen caused the answer buttons to be shown twice after #6975/#6961.
It didn't make sense in the previewer to me, so I removed it.
Fixes #7027
Only show fullscreen in the reviewer
On my device - as expected
We need to eventually perform a better split between `AbstractFlashCardViewer` and `Reviewer`

Disable fullscreen in Previewer

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java
AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java
AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
AnkiDroid/src/main/res/menu/previewer.xml
AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerCommandTest.java
AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerKeyboardInputTest.java
AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.java

It's a good idea to provide "Edit Note" functionality to the preview/card browser as it's easier to determine what to edit than the Card Browser window.
Fixes #7026 
* Add "edit"
* If a note has been edited:
* Flag to the Browser that a reload is required
* Show the new card
* If a Note Type is edited:
* Rebuild the list of valid cards
* Flag to the Browser that a reload is required
On my phone: deleting card types, and edits.
Note that the Card Browser is a little buggy due to #7017
I didn't know that if one card is selected in the previewer, then the previewer selects all cards to preview: dba68944a46b5ad68a2ee46ea55adc8bf5d4c540

Previewer: Enable "Edit Note"

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java

There is currently the following problem in ankidroid:
* Search for a big number of card
* quickly change app on android. The window should not be displayed anymore
* wait some time
* come back to AnkiDroid
It should show the list of card, or being processing. Instead it shows
there are 0 card found.
This is because, when the app change, onStop is called, and this
cancel the search. Instead, the cancellation should occur in
onDestroy, whene there the search is not used anymore.
I also allow to cancel another background task if it is not useful anymore.
Testing it on my phone
Fixes #7017

Card browser show even on close

---

AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java
AnkiDroid/src/main/res/values/01-core.xml

Currently, from deck picker, you can "create filtered deck" and then "rebuilding cram deck". This is not consistent. If
I believe upstream, you can cram using filtered deck, but there is no notion of "cram deck". Or at least, there is not
such a notion anymore.
In this case, I believe changing the string name is useful, because if in foreign language cram and filtered had been
translated differently, then their translation is not what we actually want.

cram->filtered

---

AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java

It seems to be a problem dating at least from 2.9. If there was a deck FOO with a child foo::BAR, the cache would
believe the parent is missing because it would not detect that it has cached values for "foo". 
Note that having both FOO and foo::BAR is not something that should normally occur in the first place. It is not clear
what caused it. I can imagine that it can be done by:
* creating FOO
* syncing
* renaming FOO to foo
* on another device, syncing
* creating FOO::BAR
* syncing on both device
as "foo" will be more recent than "FOO" it will be kept, without renaming its children
Fixes #6383 
Using normalized name in cache ensure this problem disappear.
Opening the collection given in the bug report on this version and seeing it works
_Please, go through these checks before submitting …

Normalize name in deckDueList's cache

---

AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java
AnkiDroid/src/test/java/com/ichi2/testutils/AnkiAssert.java

This corrupt data came from AnkiWeb - don't quite know how, but we can't assume that decks will be added via addDeck which validates the input. This crashed the deckPicker/syncing
Regression test for #6383 - fixed in #7033
<details><summary>Fails against 2.12.1</summary>
```
java.lang.Exception: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(getMainLooper()).idle() call.
at org.robolectric.android.internal.AndroidTestEnvironment.checkStateAfterTestFailure(AndroidTestEnvironment.java:470)
at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:548)
at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
at …
```

TEST: Handle corrupt deck name casing

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.java

Currently, previewer does not display counts, but still compute it. The trouble is that counts takes current card into consideration, assuming it's a card sent to the reviewer, so in one of the three queue. 
This ensure that the counts (and ETA) are only computed when we actually need them. This save computation time and avoid the problem #7039.
If you accept this design, I'd also suggest to move all members related to the four buttons to Reviewer, since they are never shown in the previewer
Note that this lead to a question: what should we send to JS in the previewer. After all, there is no count, no eta, no list of new card to see... So it's not easy to know what we should send if we ask it. Currently, I return "" and 0, but this may easily be changed
Fixes #7039
Ensuring that counts is …

No counts in abstract flash card viewer

---

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java

We attempt to dynamically set the database cursor window chunk size we use for large text loading from sqlite, for performance reasons, but we were accessing the wrong field when attempting to do so
Fixes #7031 
I use the correct field name when reflecting, exactly as @david-allison-1 pointed out with no change really, but with actual testing to make 100% sure :-)
The emulator was able to reproduce the problem, and now reproduces correct behavior:
> 2020-09-07 11:17:13.819 5569-5569/com.ichi2.anki D/Collection: Reflectively discovered database default cursor window size 2097152
Even the simplest things can be screwed up! Haha - seriously though, I swear I tested this and saw it work, but here we are. Even Android Studio highlighted that it was a problem. An easy fix at least.

Access correct cursor window size when configuring collection chunk size

---

AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java

the modified methods does not exists upstream anymore.
This is the first commit of https://github.com/ankidroid/Anki-Android/pull/6573 and I don't recall why I never posted it alone. I believe it allows names to be more easy to understood

NF: better var name than grps

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.java
AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.java
AnkiDroid/src/main/res/values/02-strings.xml

A user didn't understand "archive is not a ZIP archive" meant the file is corrupt. We improve this error message, and perform more silent exception logging to help diagnose these unknown issues in the future.
Fixes #7050 
* Change the dialog
* Send a silent exception report if the exception type is unknown
* Return a class so we can better handle displaying a string to the user.
We can always do better with exception reports

Improve File Import: Error Handling for Zip Validation 

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/java/com/ichi2/libanki/sync/CustomSyncServerUrlException.java
AnkiDroid/src/main/java/com/ichi2/libanki/sync/HttpSyncer.java
AnkiDroid/src/main/res/values/04-network.xml

This won't occur for new users, as there's now validation in the preferences, but some existing users have this issue and it would be useful to fix it for them.
Adding because it's the first error of the 2.13 beta, and it's hopefully caused by a user, rather than a bot.
Fixes #5843
Return a custom exception and explain what it means
```java
getSharedPrefs(this).edit().putString("syncBaseUrl", "<see image>").commit();
```
Tested on my Android 9 device

Improve custom sync server URL error

---

AnkiDroid/src/main/java/com/ichi2/themes/HtmlColors.java
AnkiDroid/src/test/java/com/ichi2/themes/HtmlColorsTest.java

The input: " color:DLE " was changed to " color:dle ", this was unintentional
Fixes #7059
Use the input value if nothing was matched
Unit test only
We need more work on color inversion

Inversion: Stop lowercasing invalid color codes

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java

A search for a tag with brackets failed
The tag search for filtered decks already used this code, so no changes necessary
Fixes #7070
Quote the string
Unit test and on my phone

[Bugfix] Allow searches on tags containing brackets

---

AnkiDroid/src/main/java/com/ichi2/themes/HtmlColors.java

Previously handled in be25ea084fa88b87c712d58a0e6b5938fd08cfba (#7067)
But, this implementation feels cleaner

NF: improve nameToHex

---

AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
AnkiDroid/src/main/java/com/ichi2/libanki/Media.java

This is used in anti-corruption procedures, so should not require a valid collection for it to work.
Fixes #7073
Stop using `getCol()` and ensure the method does not require an open col
On my device - a corrupt database (v15) can now use restore from backup

IMPORT_REPLACE: run when collection corrupt

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java
AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.java

When I split updateScreenCounts in two, in 08bb0597601de2995c81e16ee6b187b68a60a49a, I forgot to call super. So of
course the part of the method which is general to all reviewer was not called.
Tested by running an emulator, adding cards in a new deck A::B, reviewing A and seeing that the title shown is "B"
Edit:
* The previewer show deck but no count
Fixes #7076

Correct #7076

---

AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
AnkiDroid/src/test/java/com/ichi2/anki/BackupManagerIntegrationTest.java
AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java

App crashed after a database write if backups were restored from
Fixes #7083 
Simple 1-line fix to move time acquisition to before database locking
🛑 Manually, sadly, I could not get the test to fail on Windows
By default, Robolectric assigns you 0 disk space

[BugFix]: Restore backups as writable database

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/main/java/com/ichi2/utils/NoteFieldDecorator.java

There are some cases of Note Editing, specifically if you have a 2 field card, and the second field is empty, where you should apply special decoration to the card based on the first field
Special attention was paid to backwards compatibility, specifically that the unicode characters accessed were available on Android API16, as this is a potential source of error that I have personally experienced when accessing this range of the unicode set
Some effort was spent making sure that the Spanish language in particular was supported and that when considering a 26-letter alphabet, the desired decorations could readily be converted between our chosen storage mechanism and their regular representation with an easily reversible storage encoding by dividing the 26 letters into two 13-letter spaces …

Implement special field decoration mode

---

AnkiDroid/build.gradle
AnkiDroid/src/androidTest/java/com/ichi2/anki/utils/DiffEngineTest.java
AnkiDroid/src/main/java/com/ichi2/utils/DiffEngine.java

The currently-active diffutils Java library unfortunately uses some Java8 features that D8/R8 cannot desugar appropriately for Android's older than API24, so it caused runtime crashes on API23 and below.
This adds a regression test that runs on device and helped a) point out the API break which helped investigate the exact API support line and that it was not salvageable and b) makes sure I don't accidentally do it again
This reverts #6858 
Then this alters the test output slightly as I discovered during the revert I had inadvertently altered the diff presentation at the same time (unexpected, unwanted change!)
I reopened the related deprecation issue #6537 to track this until we have `minSdkVersion 24`
Fixes #7091
Test and revert
API16, API22, API23, API24, API29 emulators
Android Studio …

Revert diffutils library update, add test

---

AnkiDroid/src/main/res/values/02-strings.xml

People were saying that the missing media error was an AnkiDroid error, it's not an AnkiDroid error
Also fixed text: 
https://github.com/ankidroid/Anki-Android/wiki/FAQ#why-doesnt-my-sound-or-image-work-on-ankidroid

Missing Media Error: Not Our Fault

---

AnkiDroid/src/main/java/androidx/drawerlayout/widget/ClosableDrawerLayout.java
AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
AnkiDroid/src/main/res/layout-xlarge/homescreen.xml
AnkiDroid/src/main/res/layout/activity_anki_stats.xml
AnkiDroid/src/main/res/layout/card_browser.xml
AnkiDroid/src/main/res/layout/homescreen.xml
AnkiDroid/src/main/res/layout/reviewer.xml
AnkiDroid/src/main/res/layout/reviewer_fullscreen.xml
AnkiDroid/src/main/res/layout/reviewer_fullscreen_noanswers.xml
AnkiDroid/src/main/res/layout/studyoptions.xml

Safe Display did not disable the nav drawer
Fixes some of #7119
Related: #7114
* Override a class (in namespace `androidx.drawerlayout.widget`)
* Override the package-protected `closeDrawers(boolean)` which uses animations
* Call openDrawer(Gravity, boolean), where the boolean is whether to animate
Tested on my Android 9 with `Safe Display` on and off.
UI sucks

Navigation: Allow Safe Display (No Animation)

---

AnkiDroid/src/main/res/layout/deck_picker.xml

Was a regression - This ensures that it's not obscured by the decks with the same color
Fixes #7121
`android:layout_above`
Android 9 device - tested visually, same as 1.12.1
We might need automated visual UI regression tests in the future, which are a lot of work

Deck Picker: Make bottom bar opaque

---

AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.java
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.java
AnkiDroid/src/main/res/values/10-preferences.xml
AnkiDroid/src/main/res/xml/preferences_advanced.xml

NOTE: Defaults to true 
MIUI users can't use Cloze due to the OS being a pain.
We've had a lot of 5* ratings and support queries about this, let's send some love back to these users.
We add the selected value to the clipboard surrounded by cloze marks
This allows MIUI users with GBoard to paste it in immediately (and other keyboards to use Paste)
HACK before #7124 obsoletes this
Android 9: I returned false for `hasContextMenu` and it worked
* Preference is not visible normally
* Only work with Cloze
* Preference is enabled by default and handles this case
* Preference can be disabled
* Works
https://stackoverflow.com/questions/47610456/how-to-detect-miui-rom-programmatically-in-android

HACK - Use Clipboard to allow MIUI Cloze

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/res/values/02-strings.xml

Selecting a deck after a sync completes, but before the UI is refreshed caused this error. We can probably do better, but this should fix it without needing to delve into nitty-gritty UI timing issues.
Fixes #6280
Warn and log if the collection is not open
Try..catch, warn and log. If we still get an exception
Untested failure case, can still click decks on Android 9.

Fix failing to load deck after sync

---

AnkiDroid/src/main/java/com/ichi2/anki/Info.java

Maybe the changelog crashed for #7135, if it did then we wouldn't get 
This ensures that we won't get into a crash loop if the changelog crashes
Maybe fixes #7135
Only show the changelog once
Doesn't crash

Only show Changelog/Info once

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ACRATest.java
AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java

All WebViews crashed on API 19 after 2.13.0. 
I believe 85b3ff0 is the change which causes it
Fixes #7135 
Don't init a WebView in `attachBaseContext`
Untestable - needs to be released to alpha to be tested

(Hopefully) Fix #7135 WebView Crash

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java

A crash occurred
`mCards` was set `onCollectionLoaded`, which hadn't been called
Fixes #7145
Set the variable to an empty list
Quick check on Android 9 - seems fine

Fix NullPointerException on invalidate()

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java

Fixes #7141
Tested on my Android 9 device. Menu is still above system-added values, but after "Share/Paste as Plain Text"

Move Set Field Language after "Share"

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SimpleMessageDialog.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.java
AnkiDroid/src/main/res/values/04-network.xml
AnkiDroid/src/main/res/values/constants.xml

* Failing the basic check showed a "Corrupt" message instead of a "Check Database" message
* On corrupt database, the link was dead
* There was no help button, instead a link needed to be typed into the browser
Fixes #7151
Make a "basicCheckFailed" error
Tested on my Android 9 via changing the result type to "basicCheckFailed"
Question everything

Improve Corrupt Collection/Basic Check Failed Dialog

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java

User reported seeing this error constantly - could have been corruption, but I doubt it.
Maybe I was mistaken and the operation can succeed if `colIsOpen` returns false.
This will increase error report volume, but the error has better diagnostics
Maybe later we won't error report if the collection is not open
Fixes #7149
Untested

Stop calling displayFailedToOpenDeck unless error

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.java
AnkiDroid/src/main/java/com/ichi2/async/Connection.java

During Sync, we uses a lot of strings to passe informations that would be better in enums. In this PR, I propose to change one string, the one which states whether we should do a full download/upload. Currently "null" is used to mean "do a normal sync or ask the user".

Conflict resolution as enum

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java

My goal is to preload card as much as possible. This mean pre rendering html before actually needing to show it, in particular mathjax and loading media. This also mean that I need to deal with sound outside of the AbstractFlashCard Viewer. I believe that doing simple cleaning is a good first step to attain this goal easily. 
My point is that I'm not just doing refactoring for the sake of cleaning. I am doing it because I've got a goal in mind and that I expect that this will help reach it.
In this case, what I want is to get the display string without having to directly show it.
As a side note, it ensures that if the card is empty, set answer field is set to Gone

Don't offer to type answer if there is no front

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java

The test `mModelChangeCardMap.containsKey(null)` can't succeed since null is never added to this map as a key.
However, it's added as a value, and that's probably what was supposed to be tested in
a4ecc3bc646a0e386ce017cc165c922e718442ec. This means that the warning will be shown if some card is mapped to nothing.
Note that containsValue is slower than containsKey. Howevre, since it loops over the number of cards, that's acceptable.
Note also that this test is currently useless. Indeed, the map contains the value null iff it contains the value null at
creation. This occurs iff the image has less element than the source. I.e. iff mModelChangeCardMap.size() <
mEditorNote.numberOfCards()
This still seems a relevant correction in case one day the map may be changed.
Or we can just delete the …

NF: Check whether a card is mapped to nothing

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java

This correct partially https://github.com/ankidroid/Anki-Android/issues/7162#issuecomment-695347169 (in the sens that it corrects the comment made by David below the main error)
You also have a regression test with it.
I didn't realize there was asynchronicity I uncorrectly considered. When the reviewer is destroyed, the currentCard should be discarded. However, I didn't realize that the deck picker would start computing before the Reviewer is destroyed. For safety, I tells the Deck Picker to state that the current card does not exists anymore.
This would break if at any point we decide to allow the deck picker and the reviewer to be opened simultaneously. But to be honest, a lot of things would break in the scheduler, so that's not an actual concern.
The discarding is done in …

Discard current card in deck picker

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
AnkiDroid/src/main/res/layout/reviewer_answer_buttons.xml

This pull request addresses the problem of skipping cards when clicking fast enough in card reviewer.
Fixes #7138 
This pull request disables show answer button when ease buttons are enabled and reorders them to be able to press the right buttons when animation has not yet finished.
Ran on Android 9, it was fine. But please test it

Fix double-clicking skipping the cards

---

api/src/main/java/com/ichi2/anki/FlashCardsContract.java

`<pre>` doesn't seem to be happy in a `<p>` (checked in validator and it no longer had errors)

DOCS: Fix JavaDoc compile errors

---

AnkiDroid/src/main/res/layout/reviewer_answer_buttons.xml

Slight visual fix - the buttons faded from answers to "show" when a deck was selected
* Tested on my Android 9

Reviewer: Disable Answer button fade on open

---

AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java

This PR is based onto https://github.com/ankidroid/Anki-Android/pull/7169 . 
It adds a lot more details on `AbstractSched` to explain the various steps of the API. I also remove from AbstractSched the internal method that are actually never required to be used outside of the scheduler. And indicates which methods are in abstract only because it's required to be tested

Comment sched

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java
AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.java
AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
AnkiDroid/src/main/java/com/ichi2/libanki/Models.java
AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
AnkiDroid/src/main/java/com/ichi2/libanki/importer/TextImporter.java
AnkiDroid/src/main/java/com/ichi2/libanki/importer/python/CsvReaderIterator.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java
AnkiDroid/src/main/java/com/ichi2/themes/StyledProgressDialog.java
AnkiDroid/src/main/java/com/ichi2/ui/SlidingTabStrip.java
AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.java
AnkiDroid/src/main/java/com/ichi2/widget/WidgetStatus.java

The change was made by Android studio, but I double checked all of them. I feel like most of the time it actually simplifies the code. In particular when it ensures that I don't believe that a variable contains actual information used outside of the only method where it is set and read.

NF: Remove warning that member could be local variable

---

AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java

Each time getCol is called, a new SystemTime is created and immediately deleted. That's not a real trouble, but still kind create useless object. 
This way, `getCol(Context, T)` will be called only when we actually need to add a Time object, when we don't expect the collection to exists.
This should also simplifies https://github.com/ankidroid/Anki-Android/pull/7005 .

NF: simplifying getCol

---

AnkiDroid/src/main/java/com/ichi2/libanki/sync/HttpSyncer.java

I must admit I don't know why it should be volatile. It does not seems we can do download on multi thread

NF: remove warning "Non-atomic operation on volatile field"

---

AnkiDroid/src/main/java/com/ichi2/anki/Lookup.java

Indeed, since itemValue is not a string, this always returns false, which is probably not expected.
This probably means that this part of the code never worked as expected. Probably worth noting it somewhere.
I don't actually know what it is, so I guess we need someone actually knowing what it is and testing it to check what occurs

Uses contentEquals (correct leo ?)

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TagsDialog.java
AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractDeckTreeNode.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckDueTreeNode.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckTreeNode.java
AnkiDroid/src/main/java/com/ichi2/utils/FilterResultsUtils.java
AnkiDroid/src/main/res/menu/deck_picker.xml
AnkiDroid/src/main/res/values/02-strings.xml

Some users wanted this
Fixes #7116
* `SearchView` and `Filter`
* If a deck matches the search string, then all children are visible
* If a deck matches the search string, then all parents are visible
On my Android 9 with the AnKing deck. Worked as expected. 
* "Create Deck" result is only visible if searched
* Decks which are not visible can be reviewed if the parent is selected.
* Nesting works as expected
* Tested on my Android Emulator
* Keyboard shortcuts no longer get in the way

Add "Search Decks" to Deck Picker

---

AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractDeckTreeNode.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckDueTreeNode.java

There was warning that ">>>32" is useless (at least in 32 bit). And assuming the hash of the list is done in a proper way, then it does not seems to had any security to do more than add the two hashes.

NF: suppres wraning about >>> 32

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtonStatus.java
AnkiDroid/src/main/java/com/ichi2/ui/TvNavigationElement.java
AnkiDroid/src/main/java/com/ichi2/utils/AndroidUiUtils.java
AnkiDroid/src/main/res/layout-television/reviewer.xml
AnkiDroid/src/main/res/layout/reviewer_answer_buttons.xml
AnkiDroid/src/main/res/menu-television/reviewer.xml

Enable TV Support for the reviewer
This is much better than it was, but there's still room for improvement. I'm not sure if this takes it in the right direction as most of this feels hacky.
This is fairly hacky - we use a hidden view to handle the additional nav events to show the nav drawer/options.
~~It feels like there's an extra element, so pressing up to access the menu sometimes does not work. I haven't been able to figure out why.~~
~~We get a crash from the framework when navigating back from an option menu with submenus (flags in the reviewer, for example)~~
Fixes #1643 (reviewer)
Android TV emulator
We shouldn't be using action bars and should write our own UI

Enable TV Support for Reviewer

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java

Opening the Previewer then quickly opening tags showed the dialog on return
Using this dialog crashed.
Fixes #7263
Dismiss dialogs on return to the screen as well
On my Android 9

Fix TagsDialog not attached to Context

---

AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
AnkiDroid/src/main/res/drawable/ic_language_black_24dp.xml

A little out-of-place visually, but helps users change language
API 16 and my Android 9 phone
Works with Dark Mode
I didn't think this would be possible on Android 16 as there was attributes in the `Drawable`, pleasantly surprised

Add Language Icon to Preferences

---

.travis.yml

According to travis:
> root: deprecated key sudo (The key `sudo` has no effect anymore.)

NF: remove sudo from travis

---

AnkiDroid/src/main/res/values/02-strings.xml

This was shown when an async dialog fragment was shown as a notification
It implies that AnkiDroid was closed while the import process occurred.

NF: Improve Import Interrupted Error

---

AnkiDroid/src/main/java/com/ichi2/anki/reviewer/PeripheralCommand.java
AnkiDroid/src/main/java/com/ichi2/anki/reviewer/PeripheralKeymap.java
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerKeyboardInputTest.java
AnkiDroid/src/test/java/com/ichi2/anki/reviewer/PeripheralKeymapTest.java

User requested flag (Ctrl+1) keyboard shortcuts in the reviewer.
Fixes #7140
Gets closer to #6052
* Ensure that Ctrl+'1' doesn't match '1'
* Allows mapping to handle modifier keys
Unit tested and on my phone

Reviewer: Add Flag Shortcuts (Ctrl+1..4)

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
AnkiDroid/src/main/res/values/03-dialogs.xml

This PR is an attempt to implement #7036
Issue #7036 reported the lack of progress indication when deleting media files. The first commit of this PR added that indication, in the form of a progress dialog:
Also, while I was analyzing AnkiDroid's code regarding this problem, I noticed that the original code had the intention to show a result dialog when the deletion process finishes (see method deleteUnused()). However, in reality when I use AnkiDroid, this dialog is not shown. That's why I added a second commit to show this result dialog:
I think a result dialog like above would be helpful in cases where the amount of files to delete was small, only tens or hundreds files for example. In these cases the deletion process would be so fast that the progress dialog might not have a chance to …

Show progress indication when deleting media files (issue #7036)

---

AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.java

Fixes #7285  following upstream rules for counting and undo
we should really indicate somewhere that the preview queue and deck are not related to the preview window

Regression 7285

---

AnkiDroid/src/main/java/com/ichi2/libanki/template/Template.java
AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.java

I added a regression test
This has probably never been a problem, as there is no reason to expect anyone ever used "{{|" in a template.
However, that'll be useful to port new card generation rules

"{{|" was considered as "{{#"

---

.github/workflows/update-gradle-wrapper.yml
gradle/wrapper/gradle-wrapper.properties

In https://github.com/ankidroid/Anki-Android/pull/7182 the Update Gradle Wrapper action has been introduced in order to keep the Wrapper up-to-date automatically.
To avoid Android Studio warnings about `distributionSha256Sum` (which is totally safe to use but still causes such scary warning messages), here we set the action to NOT generate the checksum value on update.
In this changeset we manually remove `distributionSha256Sum` from `gradle-wrapper.properties` and configure the action so that it won't add it back anymore.

Disable distributionSha256Sum in Update Gradle Wrapper workflow.

---

lint-rules/src/main/java/com/ichi2/anki/lint/IssueRegistry.java
lint-rules/src/main/java/com/ichi2/anki/lint/rules/DuplicateTextInPreferencesXml.java
lint-rules/src/test/java/com/ichi2/anki/lint/rules/DuplicateTextInPreferencesXmlTest.java

This PR implements the Lint check requested in #7156 which will prevent a developer to use the same string as both a title and a summary for a preference declared in xml.
Note that I didn't manage to make Android Studio to highlight this issues in the file xml, but this is most likely due to the IDE itself as I saw others having issues with this kind of lint checks(running on resource files) . Even so the rule should still be useful to avoid the issue before making a new release.
I've manually ran the checks against faulty files and the code also has basic unit tests for the code itself in module _lint-rules_.
_Edit by @david-allison-1_
Fixes #7156

Prevent using the same string for the title and summary of a preference

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowser_CardCollectionTest.java

Due to the addition of `CardCache`, the `position` variable was out-of-sync with reality after performing `Collection.reverse()`
Fixes #7286 
* Extract to a structure where this can no longer happen
* Fix the numbers after a `reverse()`
Unit & Integration tested
Tested on my phone briefly
We still need more tests

[BugFix] Card Browser Preview works after sorting

---

AnkiDroid/src/main/AndroidManifest.xml
AnkiDroid/src/main/res/drawable-xhdpi/tv_banner.xml

⚠️  Confirm that this will not submit us to the TV App Store - we're not (and probably never will be) ready. the docs seem ambiguous. It seems to be a Play Console Checkbox - but need to make sure.
Was requested 
Related: #1643 
It's not great - we can't resize bitmaps until API 23
https://developer.android.com/training/tv/start/start#tv-activity

Add Icon for TV Launcher

---

AnkiDroid/src/main/java/com/ichi2/utils/JSONArray.java
AnkiDroid/src/main/java/com/ichi2/utils/JSONObject.java

They have been well tested, seems they are not useful anymore.
Furthermore, they take half of the running time of "Empty cards" which is not acceptable

NF: remove Assert from JSON

---

AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.java
AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java

We've had an uptick in users mentioning syncing errors, this is potentially one of the causes (where our scheduler does not match with the AnkiWeb scheduler)
#6207
⚠️  On my device - I'm not sure if this "Category"/"Action" setup is correct, but it's similar to how we do other analytic events.

Add Analytics event for failing Sanity Check

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java

This was caused as `withEndAction` would not fire if the view was hidden.
Fixes #7294 
We ensure that the action occurs when the answers are displayed
Attempted and failed to get a failing unit test (animations are hard), tested visually on my Android 9
`withEndAction` is only executed if an animation ends normally: https://developer.android.com/reference/android/view/ViewPropertyAnimator#withEndAction(java.lang.Runnable)

BugFix: Ensure all answer buttons are hidden

---

AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.java
AnkiDroid/src/test/java/com/ichi2/testutils/MockTime.java
AnkiDroid/src/test/java/com/ichi2/testutils/MutableTime.java

Regression: We were passing in the primary key as the seconds, rather than the milliseconds
This led to a lot of collisions when answers were performed quickly.
Introduced in 4bee8de (#6930)
Fixes #7305
Use milliseconds instead of seconds
Unit tested, tested on my device

[BugFix] Make Reviews Fast Again: Perf Regression

---

AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java
AnkiDroid/src/main/java/com/ichi2/libanki/Card.java

Before 4bee8def2c6a408ab9311b72ecb1565b1dfd1442, this was a double representing seconds. We never used more than 3
digits, so using MS is more exact. Note that this is only used to save the time taken to answer a card, so rounding to a
second number is probably right anyway
I checked, this and https://github.com/ankidroid/Anki-Android/pull/7314 are the only time where we used the fact that the time, expressed in second, had informations about miliseconds too

NF: mTimerStarted uses MS

---

AnkiDroid/src/main/AndroidManifest.xml
AnkiDroid/src/main/java/com/ichi2/anki/contextmenu/AnkiCardContextMenu.java
AnkiDroid/src/main/java/com/ichi2/anki/contextmenu/CardBrowserContextMenu.java
AnkiDroid/src/main/res/xml/preferences_advanced.xml

I feel 'Anki Card' will get more use
----
Draft as untested and I'm not sure whether this will be accepted.
For existing users, this will enable both of the menu items if they previously viewed the settings, which may not be ideal

Switch 'Anki Card' and 'Card Browser' in System Text Context Menu

---

AnkiDroid/build.gradle
AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java
AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.java
AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.java
AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.java
AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.java
AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java
AnkiDroid/src/main/java/com/ichi2/anki/services/BootService.java
AnkiDroid/src/main/java/com/ichi2/async/Connection.java
AnkiDroid/src/main/java/com/ichi2/libanki/stats/AdvancedStatistics.java
AnkiDroid/src/main/java/com/ichi2/preferences/CustomDialogPreference.java
AnkiDroid/src/main/java/com/ichi2/preferences/NumberRangePreference.java
AnkiDroid/src/main/java/com/ichi2/preferences/StepsPreference.java
AnkiDroid/src/main/java/com/ichi2/preferences/TimePreference.java
AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.java
AnkiDroid/src/main/java/com/ichi2/ui/AutoSizeCheckBoxPreference.java
AnkiDroid/src/main/java/com/ichi2/ui/ConfirmationPreference.java
AnkiDroid/src/main/java/com/ichi2/ui/SeekBarPreference.java
AnkiDroid/src/test/java/com/ichi2/anki/AnalyticsTest.java

**Partially copied the description from https://github.com/ankidroid/Anki-Android/pull/7015**
This PR is a subset of the changes of the above PR which should be stable, but regularly conflict with the lint/refactoring work that we're in the middle of. This will reduce the friction of getting the main API upgrade (https://github.com/ankidroid/Anki-Android/pull/7015/commits/a833b89213c28585f9fb4d18ea9355471b3a6b4e) into the codebase.
I believe moving to the next release of Robolectric will reduce the pain of calling native methods in the Unit Tests (due to the Rust conversion). I see a `UnsatisfiedLinkError` when moving between tests with `LooperMode.LEGACY` and `LooperMode.PAUSED`, Robolectric 4.4.4 should satisfy this as `LooperMode.PAUSED` is now the default, and it's better to move …

API 29 Dependency Updates

---

AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java
AnkiDroid/src/test/java/com/ichi2/libanki/AnkiPackageExporterTest.java
AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.java
AnkiDroid/src/test/java/com/ichi2/utils/InMemorySQLiteOpenHelperFactory.java

Shaves 4/5 minutes off a Robolectric run, about 15 minutes off my unit test run (20mins -> 5 mins)
Test-only
https://developer.android.com/reference/android/arch/persistence/db/SupportSQLiteOpenHelper.Configuration - null name for in-memory.

Use in-memory database for most Robolectric tests

---

AnkiDroid/build.gradle
AnkiDroid/src/main/AndroidManifest.xml
AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
AnkiDroid/src/main/java/com/ichi2/anki/MetaDB.java
AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java
AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.java
AnkiDroid/src/main/java/com/ichi2/libanki/utils/Time.java
AnkiDroid/src/main/java/com/ichi2/utils/JSONObject.java
AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.java
AnkiDroid/src/test/java/com/ichi2/anki/AnalyticsTest.java
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java
AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java
AnkiDroid/src/test/java/com/ichi2/anki/CardTemplatePreviewerTest.java
AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java
AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.java
AnkiDroid/src/test/java/com/ichi2/anki/ReadTextTest.java
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.java
AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java
AnkiDroid/src/test/java/com/ichi2/async/CollectionTaskCheckDatabaseTest.java
AnkiDroid/src/test/java/com/ichi2/utils/ImportUtilsTest.java
AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilsTest.java
AnkiDroid/src/test/resources/robolectric.properties

I'm doing this as part of the Rust conversion, as having two LooperModes causes problems with loading native libraries.
Related: #7107
Adopt the next release of Robolectric, which has a transitive dependency on Android API 29 as compile targets
So this moves us forward to API 29 with associated deprecation notices (fixed in #7332).
There is also a requirement from API 29 in Robolectric to use JDK 9, we'd jump to 11 due to it being a LTS, and this is currently nonstandard in Android Dev, so we continue testing from API 28.
It will be tested in Travis 
Tests have been run against API 28 and 29
Once the known failures are dealt with, could you run this under a custom Android Studio test config which defines "Run tests until failure". A lot of these tests are flaky, and it's been hours of …

Robolectric 4.4: Switch to API 29 and LooperMode.PAUSED

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
AnkiDroid/src/main/res/values/07-cardbrowser.xml

Previously, it showed "Notes Deleted", which is confusing
Knowing the number will ensure that users know that one note may map to several cards
On my phone - total is now displayed

Card Browser: Display cards deleted when deleting notes

---

AnkiDroid/src/main/res/menu/card_template_editor.xml

Now the Save icon is in the toolbar on small screens instead of Preview. Matches the icon order on the previous note editor screen.
Fixes #7341 
Emulator.

Reordered menu items in the card template editor.

---

AnkiDroid/build.gradle
api/build.gradle
api/src/test/resources/robolectric.properties

Standard dependency tracker PR, this one has quite a pile because the robolectric 4.4 / API29 item was so large for AnkiDroid took a while.
This does the same robolectric 4.4 / API29 change for the api module, plus all the items queued up
Let dependabot run on my local fork and merge it's PRs...
Tested locally against API16, 29 and 30 emulators with `./gradlew clean jacocoTestReport` - all seems fine?

Dependency updates 20201004

---

AnkiDroid/lint-baseline.xml
AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.java
AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.java
AnkiDroid/src/main/res/values/06-statistics.xml
AnkiDroid/src/main/res/values/attrs.xml
AnkiDroid/src/main/res/values/colors.xml
AnkiDroid/src/main/res/values/theme_black.xml
AnkiDroid/src/main/res/values/theme_dark.xml
AnkiDroid/src/main/res/values/theme_light.xml

I use templates that produce a lot of siblings, and want to be able to see my current number of buried cards without actually typing in a search. Generally, I do this by using the Statistics view to see my number of "Suspended+Buried" cards at the start of the day. If I remember that number, I can just check "Suspended+Buried" again later in the day to get a sense of how many buried cards I must have. That's kind of silly, though, and ever since I noticed desktop Anki split "Suspended+Buried" into separate "Suspended" and "Buried" stats, I've wanted the Android app to do the same.
I haven't filed an issue to request this feature yet. Should I do that?
This change just extends what AnkiDroid already does to draw the card-types pie chart. It makes the "suspended+buried" subquery specific to …

Split buried/suspended in statistics view

---

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java

While looking at related code, I found this loop which could exit sooner and uses labelled loop to avoid a variable

NF: newCardName break sooner

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/AsyncDialogFragment.java

This is our top crash on play store for 2.13.5
The crash trace indicated that somehow database dialog fragment inflater
was called via an Activity.onCreate call chain, and somehow it was before
Application.onCreate got to the point where sInstance was set.
How? It's only on Huawei phones and they appear to have a separate ActivityThread
so I'm guessing it's a vendor-specific race. In this case resources have fallback
access via the Dialog inheritance chain so I implement a fallback
This seems like a major violation of lifecycle order of operations so I'm not
inclined to dive much deeper but we can avoid a crash and provide a reasonable fallback
at least
Unlogged
```
java.lang.RuntimeException: 
at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3303)
at …
```

Fix AnkiDroidApp.sInstance-is-null crash during dialog inflation

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/res/values/02-strings.xml

Previously this would crash the app with no option.
Normally caused by a WebView upgrade, but also visible on API 26 Nexus emulator
Fixes #5794
Android 8.0:

Improve error if WebView load fails

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
AnkiDroid/src/main/res/menu/card_browser.xml
AnkiDroid/src/main/res/values/07-cardbrowser.xml
AnkiDroid/src/main/res/values/strings.xml
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java

Users don't know that they can type: flag:1 etc... this needs a visual item in the Card Browser Action bar - similar to the item in the Reviewer.
Fixes #7118
1. Flag icon is added to card browser menu with ifRoom option. After that change it will replace "Add card button" on most mobile phones, since there is not enough room for both and search icon.
2. When flag is selected, searchTerms are updated to have `flag:N`.
3. If there was already search term looked for by user, selecting flag will prepend `flag:N` to search terms.
4. If user has selected a flag and then wants to switch to other `flag:N` term is replaced with correct flag, without removing existing search terms.
5. Only one flag can be selected at one time, when using Search by flag option.
* Added unit test for checking if my …

Fix #7118: Adding Filter by flag icon to card browser.

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/java/com/ichi2/async/BaseAsyncTask.java
AnkiDroid/src/main/java/com/ichi2/async/CancelListener.java
AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
AnkiDroid/src/main/java/com/ichi2/async/ProgressSender.java
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
AnkiDroid/src/main/res/values/01-core.xml
AnkiDroid/src/main/res/values/03-dialogs.xml
AnkiDroid/src/test/java/com/ichi2/libanki/CardTest.java

On my collection, "empty cards" takes two minutes. No progress indicates where we are. I correct it by adding a number. This is not perfect, because the numerator counts cards that should exists and the denominator counts cards that already exists. So if there are missing cards in the collection, the numerator will become greater than 1. On the other hand, if cards should be deleted, we will never reach the denominator. This is still a good indication on how the process is evolving.
Furthermore, this task is now cancellable.

Empty card progress

---

lint-rules/build.gradle

Missed this in the last batch of dependency updates but it brings the lint-rules space all up to 27.1.0
Signed-off-by: dependabot-preview[bot] <support@dependabot.com>

Bump lint from 27.0.2 to 27.1.0

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/res/values/04-network.xml

Currently, both things can be translated differently and there is no good reason for that. If it were the case, that would just be confusing

NF: remove duplicate "Full sync from server"

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.java
AnkiDroid/src/main/res/values/09-backup.xml

Both are used in the same context. Furthermore "deck" is misleading, since it's an old word for "collection"

NF: remove duplicate ressource "repair"

---

AnkiDroid/src/main/res/layout/widget_small.xml
AnkiDroid/src/main/res/values/08-widget.xml
AnkiDroid/src/main/res/values/10-preferences.xml
AnkiDroid/src/main/res/xml/preference_headers.xml
AnkiDroid/src/main/res/xml/preferences_general.xml

Currently, we translate AnkiDroid only sometime. E.g. the name of the small icon is translated, however, it's not translated the information screen. This increase consistency, assuming we never went it translated (as it's a name).

NF: Use a single "AnkiDroid" ressource

---

AnkiDroid/src/main/AndroidManifest.xml
AnkiDroid/src/main/res/values/01-core.xml

This string was duplicated, and there seems to be no reason for the label of the activity to be didstinct from the label in the menu

NF: remove "Card Browser" duplication

---

AnkiDroid/src/main/res/values-af/01-core.xml
AnkiDroid/src/main/res/values/01-core.xml
AnkiDroid/src/main/res/values/02-strings.xml
AnkiDroid/src/main/res/values/08-widget.xml
AnkiDroid/src/main/res/values/16-multimedia-editor.xml
AnkiDroid/src/main/res/values/17-model-manager.xml

So that translators understand why there is no context. Or that context must be an entire window

NF: add comment on activity's label

---

AnkiDroid/src/main/java/com/ichi2/anki/FieldEditLine.java
AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.java
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/main/res/layout/card_multimedia_editline.xml
AnkiDroid/src/main/res/layout/note_editor.xml

I have a later PR to improve the UX of `EditFieldLine`, and I felt it was best to clean up the code before.
* This makes the label the responsibility of the line, rather than the textbox.
* This also improves the design-time preview of `NoteEditor`
There doesn't seem to be a good `tools:` attribute for the design-time contents of a layout - I wanted a sample EditFieldLine in `note_editor.xml` and this didn't seem feasible after a quick google.
My Android 9 - class works the same as before.

NF: Refactor EditFieldLine

---

AnkiDroid/src/main/res/values/10-preferences.xml
AnkiDroid/src/main/res/xml/deck_options.xml

Seems a bad idea to have two strings. In theory, it could make sens to have a title shorter due to window
constraint. But both names should be related, and we have no way to ensure that translation is consistent

NF: Remove duplicate "restaure default"

---

AnkiDroid/build.gradle
AnkiDroid/src/main/res/layout/card_multimedia_editline.xml
AnkiDroid/src/main/res/layout/note_editor.xml

I mentioned UI improvements and got a few - thanks to /u/NightStruck for this suggestion.
This makes the Text entry for the Note Editor fill the width of the screen
Move the attach button to beside the label
Tested with multiline title
Tested on Android 16 emulator and my Android 9 phone
Before:
After:

Note Editor: Make Field Full Width

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
AnkiDroid/src/main/res/values/07-cardbrowser.xml

If you use tag filter, the search bar is populated by the search query which looks for any of the card with one of the
selected tag. If furthermore you empty the search bar, then the hint change. This hint is misleading, since it seems to
indicate that you should enter tags in some way, while if you enter some text, it will actually be a standard search.

Remove the hint "tags" in card browser

---

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java

This PR is an attempt to fix #7377
Here I'd like to write a more detailed description of the issue, along with a proposed solution
Steps to reproduce this problem:
1. in CardBrowser, tap on the 'add note' button (=> NoteEditor is launched)
2. select a field, tap on the attach button, choose 'add image'
3. choose an image to add to the field (this image can be from Gallery or Camera, this is not important)
4. save the image, and then save the note
5. open the note again in NoteEditor
6. select the same field as above, tap on the attach button
7. tap on the camera button to add another image to the field
8. save the image, and then save the note
Now, the expected result is: the note has 2 images
But the actual result is: image 1 has been deleted, only image 2 remains
I think that the reason …

Fix images deleted after editing (issue #7377)

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/main/java/com/ichi2/utils/TextViewUtil.java
AnkiDroid/src/main/res/layout/card_multimedia_editline.xml
AnkiDroid/src/main/res/menu/note_editor.xml
AnkiDroid/src/main/res/values/02-strings.xml
AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.java

Requested to allow more text on the screen in `NoteEditor` - seemed like a useful feature

Note Editor: Set Font Size Feature

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTest.java
AnkiDroid/src/androidTest/java/com/ichi2/anki/testutil/ThreadUtils.java
AnkiDroid/src/main/java/com/ichi2/anki/FieldEditLine.java
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java

Fixes #7433
Set IDs manually, so we can add a valid tab ordering on IDs for API < 26
API 30 emulator: passed
API 25, and 16 emulators, required different fixes, now pass
CI tests: Failing on API 25 and 30 - worked locally, so ignored.
API 26 introduces navigation clusters which means the layout works out the box with a single `focusForward` change to the layout.
https://developer.android.com/about/versions/oreo/android-8.0#kbnc
Sending input is complex to do correctly over all SDK versions (events can be dropped if an activity is reset).

Note Editor - Fix Tab Order

---

.idea/codeStyles/Project.xml
AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java

Fixes #6288
Previously, if there was a `*` character in the deck name, then exact matching of deck name was skipped over and regex search was applied. So, to fix that, an exact name search is done first, if it doesn't match any deck then we proceed to applying regex searching.
I tested it both with and without the modification on a physical API 29 device. I was able to reproduce the bug and with the modification the card is showing up now.

Fix for cards not showing up inside card browser if deck contains wildcard characters in its name.

---

.travis.yml

* Shaves about 2 minutes off each of our 13 `UNIT_TEST` builds: 5 minutes real time, and ~26 minutes CPI time saved.
* Names the fixed steps in our builds (mostly to stop new users worrying about the lint debug build failing).
Fixes #6532 
Copy into the workspace, save and copy out. Skip the build steps and execute the apk.
Test only
* Gradle `-x` (--exclude-task) flag to skip a task
* https://docs.travis-ci.com/user/using-workspaces

Use Travis Workspaces to cache APK

---

AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.java

There was no test written to check if the Decks with wildcard characters in their names can be searched correctly(first doing an exact match search and if that fails, doing a regex based search). This PR adds a test inside FinderTest.java making sure that a card is visible regardless of the deck containing wildcard characters. 
tl;dr: A test written to make sure issue #6288 doesn't occur.
The issue mentioned above will be fixed by PR #7392 after which this test will stop failing. 
Fixes #7394 
- Created a Deck with the name `"*Yr1::Med2::CAS4::F4: Renal::BRS (zanki)::HY"`
- Saved the `did` for the deck above and created a note inside the deck.
- Opened CardBrowser.java through RoboelectricTest and selected our deck from the drop down menu.
- Asserted that the number of cards in …

Regression Test to check if Decks with wildcard characters in their name can be searched.

---

AnkiDroid/build.gradle
AnkiDroid/src/main/AndroidManifest.xml
AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
AnkiDroid/src/main/java/com/ichi2/anki/CardInfo.java
AnkiDroid/src/main/java/com/ichi2/utils/UiUtil.java
AnkiDroid/src/main/res/layout/card_info.xml
AnkiDroid/src/main/res/menu/card_browser_multiselect.xml
AnkiDroid/src/main/res/values/01-core.xml
AnkiDroid/src/main/res/values/02-strings.xml
AnkiDroid/src/main/res/values/07-cardbrowser.xml
AnkiDroid/src/main/res/values/styles.xml
AnkiDroid/src/test/java/com/ichi2/anki/CardInfoModelTest.java

Anki Desktop contains a card info screen, now we have one
Fixes #7397
API 16 emulator and my phone, with night mode.
ConstraintLayouts are useful
`android:supportsRtl="true"` is required for this screen to be RTL, but we have a long way to go

Add "Card Info" screen

---

AnkiDroid/src/main/java/com/ichi2/libanki/Consts.java
AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java
AnkiDroid/src/test/java/com/ichi2/libanki/UtilsTest.java
api/src/main/java/com/ichi2/anki/FlashCardsContract.java
api/src/main/java/com/ichi2/anki/api/Utils.java

The function split is optimized for splitting around a char. We never used it because instead we used unicode encoding
in regexp. This small change will save plenty of time for all batch processing.
On Empty card, (with profiler), this reduce splitting time from 40 seconds to 18 seconds

NF: Quicker split field

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/FieldEditLineTest.java
AnkiDroid/src/main/java/com/ichi2/anki/FieldEditLine.java
AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.java
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/FieldState.java
AnkiDroid/src/main/java/com/ichi2/utils/MapUtil.java
AnkiDroid/src/main/res/layout/card_multimedia_editline.xml

Refactoring: Encapsulates the rendering of components into the view, rather than having them handled by the activity.
This slightly reduces the complexity of the activity
Obtain the data from instance state ourselves, using techniques from https://speakerdeck.com/cyrilmottier/deep-dive-into-android-state-restoration
On my device - preview and exiting the app still work
https://speakerdeck.com/cyrilmottier/deep-dive-into-android-state-restoration - mostly, plus learning about `android:viewHierarchyState` and `android:views`
A view needs an ID to have data saved
Android really makes having dynamic views difficult
An exception thrown when creating a bundle does not crash - and the data is not marked as corrupt in the debugger.

Note Editor: Use View Instance State for state restoration

---

.travis.yml
AnkiDroid/build.gradle

These were missed in the forward port to API29 which caused non-retry
downloads of build tools and android platform SDK during build instead
of before the build
updating the old API28 download to be the needed 29 ones and commenting
build.gradle to note the cross-dependency for next time

NF: update Travis CI build toold / platform to 29

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
AnkiDroid/src/main/java/com/ichi2/libanki/Models.java
AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java

This is an answer to https://github.com/ankidroid/Anki-Android/pull/7453#discussion_r510957882
Models#get calls a hashmap, so it actually uses a Long. Sometime we have the Long and so using `long` is just uselessly inneficient. This correct this.
Note that this is not something that I found out to be actually significant in the profiler (but I never tried the profiler on the import method either)

NF: Models.get takes a Long

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTabOrderTest.java
AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java
AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java

IDE-based lint warning on comparing using == rather than `.equals()`
Please check 9674085 when reviewing - it appeared incorrect, but maybe I missed the context of the code.
Fixes #7467 
Fixes #7470

Fix Build failures:  testAnki2Updates and testTabOrder

---

AnkiDroid/src/main/java/com/ichi2/libanki/Card.java
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
AnkiDroid/src/main/java/com/ichi2/libanki/Models.java
AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java
AnkiDroid/src/main/java/com/ichi2/libanki/importer/NoteImporter.java

Cards with a lot of siblings takes time to be displayed. I never noticed because those cards also have a lot of fields, so I assumed it was the cause of the problem. Indeed, it used to be, but card generation was improved enough that it is not the bottleneck anymore. The bottle neck is very silly: to know whether a card is empty, we compute the list of non-empty cards of the note, and then check whether the card belongs to this set... That is entirely useless, since it consider all siblings in a process where siblings data is immediately discarded.
This PR change that, by splitting the method availOrds in three. One part deal with clozed note (this part is already efficient), one part deal with with standard note, and from this part I exctracted the part which deals with each card …

NF: Reviewer check whether a card is empty more quickly

---

AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.java
AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java

When doing undo and then reviewing again, the lrn queue was emptied and elements were not added back until the queue was empty (i.e. all elements added in the queue after undo left the queue)
This means that if we add card 1 to learning queue and then undo later, card 1 won't be seen again until the end of the review. This test show it's corrected.

Regression 6898 2

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java

Checking the profiler, I see that some significant amount of time is spent enqueuing various update. (To be more specific, this time become significant when all the remaining optimization are merged. Otherwise, it's not the main factor at all)
Maybe one second is too big a delay, there is a clear loss in fluidity. But on the other hand, I believe that one update by second gives a correct amount of information

Empty card: update at most once by second

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.java
AnkiDroid/src/main/res/values/10-preferences.xml
AnkiDroid/src/main/res/xml/deck_options.xml
AnkiDroid/src/test/java/com/ichi2/anki/DeckOptionsTest.java

Hard Factor is an option of V2 Scheduler, but it is not possible to modify it from Deck Options.
Fixes #7115
* Modified DeckOptions to include hardFactor and added selection field to Deck Options / Reviews tab.
* Hard Factor can be modified irrespective of user using SchedV1 / SchedV2, but this option is set in general preferences not in deck options. I'm not sure how to make it disabled if SchedV1 is used.
* Tested on emulated device - Pixel 3A. SDK 29.
* Added unit test that tests if value is not set for newly created deck and returns correct value after value is modified.
Hard Factor is described here: https://anki.tenderapp.com/discussions/ankidesktop/31735-what-does-hard-interval-mean
_edited by @david-allison-1_

Fix to #7115: Allow setting "hardFactor"

---

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java

Currently, avail traverse the list uselessly. This ensure that we get the speed of random access
On my collection, it reduces the time spent in `_tmplsFromOrds` from 30 seconds to 11 seconds

NF: _tmplsFromOrds quicker

---

AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
AnkiDroid/src/main/java/com/ichi2/libanki/Models.java
AnkiDroid/src/main/java/com/ichi2/libanki/Note.java
AnkiDroid/src/main/java/com/ichi2/libanki/importer/NoteImporter.java

Each time gen card is called, all notes have the same note type. So it's useless to look for it in the database. It's
even more useless to redo some computation.
Note that the replace function does not become more costly. Mostly because it's dead code that is only called in test
Things go so quickly today that I got a conflict while submitting the PR

NF: optimize genCard

---

AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java

I'd find this timber useful to understand search and its speed

NF: Timber result of query compilation during search

---

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java

I guess that would please @david-allison-1 , removing CollectionTask from libanki

NF: Use interface instead of CollectionTask in libanki

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
AnkiDroid/src/main/java/com/ichi2/libanki/Models.java
AnkiDroid/src/main/java/com/ichi2/libanki/Note.java
AnkiDroid/src/main/java/com/ichi2/libanki/Tags.java
AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
AnkiDroid/src/main/java/com/ichi2/libanki/importer/NoteImporter.java
AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.java

There are quite a few conversion that are useless. `long` to `long[]` to array joined by comma. `List<long>` to `long[]` to array joined by comma... In all of those cases, the end result is always longs joined by comma. I removed useless conversions to save time

Remove useless conversions

---

.github/pull_request_template.md

This occurred a few time recently because of the Card Info window. So I think this check box is worth adding even if it probably won't be needed very often. 
If we ask translators to do twice the same job, we should explain them why. Especially, if we expect a string to be translatable in two distinct ways, we should let them know which context is which. We have screenshot, but if crowdin close we loose screenshot, while we don't loose comments in ressources. And those comments would also help ensure that screen shots are correctly annotated

Action to check for string ressources

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/CustomToolbarButton.java
AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.java
AnkiDroid/src/main/res/drawable/ic_add_equation_black_24dp.xml
AnkiDroid/src/main/res/drawable/ic_add_toolbar_icon.xml
AnkiDroid/src/main/res/drawable/ic_format_bold_black_24dp.xml
AnkiDroid/src/main/res/drawable/ic_format_font_size_24dp.xml
AnkiDroid/src/main/res/drawable/ic_format_italic_black_24dp.xml
AnkiDroid/src/main/res/drawable/ic_format_title_black_24dp.xml
AnkiDroid/src/main/res/drawable/ic_format_underlined_black_24dp.xml
AnkiDroid/src/main/res/drawable/ic_horizontal_rule_black_24dp.xml
AnkiDroid/src/main/res/layout/note_editor.xml
AnkiDroid/src/main/res/layout/note_editor_toolbar.xml
AnkiDroid/src/main/res/layout/note_editor_toolbar_add_custom_item.xml
AnkiDroid/src/main/res/menu/popupmenu_multimedia_options.xml
AnkiDroid/src/main/res/values/02-strings.xml
AnkiDroid/src/main/res/values/11-arrays.xml
AnkiDroid/src/main/res/values/constants.xml
AnkiDroid/src/main/res/values/styles.xml

Was widely requested that we add an editing toolbar for the Note Editor - This allows quick access to a set of commands
Fixes #7124
Related: #1377 
Reverts: #7126
Reverts: #6497
Add a toolbar
Allow the user to add their own commands. These are saved in SharedPreferences
API 16, 21 and 29 emulator
HorizontalScrollView does not work well with centered content.

Add Note Editor Toolbar

---

AnkiDroid/src/main/java/com/ichi2/anki/FieldEditLine.java
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/main/java/com/ichi2/ui/AnimationUtil.java
AnkiDroid/src/main/res/drawable/ic_expand_less_black_24dp.xml
AnkiDroid/src/main/res/drawable/ic_expand_more_black_24dp_xml.xml
AnkiDroid/src/main/res/layout/card_multimedia_editline.xml
AnkiDroid/src/main/res/layout/note_editor.xml

Includes animation. Base requested on Reddit - seemed sensible
API 16, 19, and 30 emulator.
Huawei Honor Physical phone displayed different animation behavior than the emulators.
Animations are really hard to get right as it's near impossible to test
My normal vector compat usage didn't work for `DeckAdapter.java`, so I used a resource suffixed with `_xml`

NoteEditor: Expand/Collapse Field Content

---

AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java

This problem does not exists in Python since there is no type. In java, it ensures that types is fully specified

NF: improve typing by stating recursiveness explicitly

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/main/res/layout/note_editor_toolbar.xml

* Ensures the Cloze Button appears on API 16
* Centers the Note Editor Toolbar on API 16

Note Editor: API 21 fixes: cloze & centering

---

AnkiDroid/src/main/java/com/ichi2/anki/FieldEditLine.java
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/main/res/layout/card_multimedia_editline.xml

Fixes  #7539
API 16, 25 and 29
`ConstraintLayout.setConstraintSet` broke animations, `ConstraintSet.applyTo(ConstraintLayout);` worked

Note Editor: Fix Tab Order

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java

This follow @david-allison-1 's idea in https://github.com/ankidroid/Anki-Android/pull/7516#pullrequestreview-517240860
It saves the current search, so that it's not done a second time. Current search is deleted when the data is emptied.
It reduces computation time from 20 seconds to 16.5 seconds on a deck

NF: save current search to avoid doing it twice

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiFont.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/LocaleSelectionDialog.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TagsDialog.java
AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/beolingus/parsing/BeolingusParser.java
AnkiDroid/src/main/java/com/ichi2/anki/stats/OverviewStatsBuilder.java
AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.java
AnkiDroid/src/main/java/com/ichi2/libanki/DB.java
AnkiDroid/src/main/java/com/ichi2/libanki/Deck.java
AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
AnkiDroid/src/main/java/com/ichi2/libanki/Media.java
AnkiDroid/src/main/java/com/ichi2/libanki/Model.java
AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java
AnkiDroid/src/main/java/com/ichi2/utils/DatabaseChangeDecorator.java
AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.java
AnkiDroid/src/main/java/com/ichi2/utils/JSONObject.java

Travis state that US and no information should be avoided. Instead I use root for internal (sql, comparing deck name, checking whether an
extension is apkg, anki2, ....) and getDefault() for everything facing the user, such as title of section, media file

Remove travis warning about upper/lower char

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.java
AnkiDroid/src/main/java/com/ichi2/utils/ViewGroupUtils.java
AnkiDroid/src/main/res/layout/note_editor_toolbar.xml

Including Ctrl+1..0 for custom items
We do this via a tag.
'L' already opens the Card Template Editor
Related #7124 
Android 9 phone

Note Editor Toolbar: Add Keyboard Shortcuts

---

AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.java
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/main/java/com/ichi2/utils/FileUtil.java
AnkiDroid/src/main/res/values/02-strings.xml
AnkiDroid/src/test/java/com/ichi2/utils/FileUtilTest.java

User wanted to be able to paste into fields on a Chromebook
This can be tested via inserting gifs via gboard.
Limited to 1MB.
Fixes #7566
Override `onCreateInputConnection` and send the image to be pasted
Android 9 phone - probably not enough.
https://stackoverflow.com/questions/56525255/image-keyboard-selecting-rich-contentgif-stickers-reopens-activity
Can be tested with the GBoard gif keyboard

Note Editor: Allow pasting images into fields

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/main/java/com/ichi2/utils/KeyUtils.java

User Request: `Ctrl+[Num]` would switch fields, we already have `Ctrl+[Num]` so use `Ctrl+Shift+[Num]`
Fixes #7573
My Android 9
https://stackoverflow.com/questions/14997165/fastest-way-to-get-a-positive-modulo-in-c-c

Note Editor: Ctrl+Shift+Num to switch fields

---

AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java

`parents` does not keep track of the returned list. So using it directly works correctly

NF: avoid a useless copy

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.java
AnkiDroid/src/main/res/values/01-core.xml

I like the idea to get a link opening directly the reviewer, as suggested in #6995. So you can long click on a deck, and add a shortcut opening the reviewer directly to here.
Fixes #6995
Uses https://developer.android.com/guide/topics/ui/shortcuts/creating-shortcuts#java
Open deck picker, long click on a deck, click on "Create shortcut", add it on android, open another deck, close ankidroid, click on the new icon, see that the correct deck is directly opened.

Direct icon to deck

---

AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java

It seems that 11e837336359ba50da637e09a8cc7e3933532d70 and 359fe6b6875661a748269d8bc4aaedb7d49ff7d9 were incorrectly merged. It corrects this.

NF: Correcting a bad merge conflict

---

AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.java
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.java

* A user wants to be able to paste images via Ctrl+V or the context menu
* image/jpeg wasn't supported
* Images weren't deduplicated when pasted (as the timestamp was added to the image).
Fixes #7566
Fixes #7626
* onTextContextMenuItem
* Add jpeg
* Add a cache while the activity is open
Android 9 device - works as expected. Including "Don't Keep Activities"
This exception can occur, all tested apps ignore this. Works again if image is copied again.
<details><summary>Exception</summary>
```
java.lang.SecurityException: Permission Denial: opening provider org.chromium.chrome.browser.util.ChromeFileProvider from ProcessRecord{f1583aa 17356:com.ichi2.anki/u0a455} (pid=17356, uid=10455) that is not exported from UID 10057
at android.os.Parcel.createException(Parcel.java:1953)
at …
```

Image Paste: Handle Context Menu & Deduplicate

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
AnkiDroid/src/main/java/com/ichi2/anki/CardInfo.java
AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateBrowserAppearanceEditor.java
AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/java/com/ichi2/anki/Info.java
AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.java
AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java
AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java
AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java
AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.java
AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java
AnkiDroid/src/main/res/values/02-strings.xml
AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupMetaTest.java
AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupUnderBackupTest.java
AnkiDroid/src/test/java/com/ichi2/testutils/ActivityList.java
AnkiDroid/src/test/java/com/ichi2/testutils/EmptyApplication.java

If the app is restored from a backup, then `Application.onCreate` is not called. This lead to a lot of crashes as this was assumed to always happen.
Fixes #7630 
* On each activity `onCreate`
* Detect if the failure occurred
* Show a message
* Kill the app so it starts normally.
My Android 9 
Test via: `.\adb shell bmgr restore com.ichi2.anki`
https://stackoverflow.com/questions/57211036/why-backup-related-process-might-cause-applications-oncreate-is-not-executed

Handle Backup restoration-related crashes

---

AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java
AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java

Importing my main deck takes 6'24''. This PR' reduces it to 6'01''. Not exactly game changing, but still some noticeable progress.
It saves time by:
* Avoiding to query from the database some values that are never used
* Avoiding to convert multiple time between int/long and Int/Long (One last conversion is needed, because sql always takes Object[] which is actually a huge loss of time)
As a benefits, it becomes more clear, since instead of an array of Object, each variable has a readable name. 
It was tested by importing back my deck in a fresk ankidroid collection and seeing that everythnig seems to be alright

Import simplified

---

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java

Ensure that it can be known what is undone in the reviewer. It should also help get more diverse screenshot.

Undo in reviewer state what will be undone

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.java

When you modify some of the deck options like Reviews/Easy Bonus or Reviews/Interval wrong value is displayed.
For example if you modify Easy Bonus to 130 the actual value that is shown in the UI is 129%. This only happens for some values and must be related to some rounding issue.
Fixes #7466
Fixes #4448
* Changing  Integer.toString() method to String.format("%.0f", ...) that rounds Double values into nearest number without decimals.
* Emulated device Pixel 3a SDK 29.

Fix #7466: Round Doubles when displaying Deck Options

---

AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
AnkiDroid/src/main/java/com/ichi2/libanki/Media.java
AnkiDroid/src/main/java/com/ichi2/utils/ExceptionUtil.java
AnkiDroid/src/test/java/com/ichi2/libanki/CheckMediaTest.java

For some reason, some users were missing the meta table.
This meant that both syncing and Check Media failed.
Now, only syncing fails, and the error is recoverable.
Fixes #7421
If the meta table does not exist, delete the media database and recreate it
Unit tested

Check Media: Recreate database on schema error

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java

Cause: 2d96e47e9e3f7d72c019d1231aa3df7fe060f9c1 - partially reverted
Fixes #7649
Unit tested
`TreeMap.values()` does not support `.add()`
https://docs.oracle.com/javase/7/docs/api/java/util/TreeMap.html#values()
> Returns a Collection view of the values contained in this map. The collection's iterator returns the values in ascending order of the corresponding keys. The collection is backed by the map, so changes to the map are reflected in the collection, and vice-versa. If the map is modified while an iteration over the collection is in progress (except through the iterator's own remove operation), the results of the iteration are undefined. The collection supports element removal, which removes the corresponding mapping from the map, via the Iterator.remove, Collection.remove, …

BugFix: confirmDeckDeletion crash

---

AnkiDroid/build.gradle
build.gradle
lint-rules/build.gradle

Standard dependency update PR with notable item:
- R8 workaround to fix the release minify bug we started seeing with AGP4.1.x (upstream has fixes already)
Fixes #7558 
Related / unblocked #7587 
I added a couple new repositories that allow access to pre-release / standalone R8 tool builds, and found a version that works for us when layered on to the android gradle plugin 4.1.x. This is standard in the google issue tracker when troubleshooting / resolving R8 problems.
The version I chose is the one that will go live with AGP4.2.x I believe, you can see the tags here in case the 2.2.x branch moves on and we need to track a new one, prior to AGP4.2.x release https://r8.googlesource.com/r8/
When AGP4.2.x comes out, there's a note in the code that we can remove the temporary blocks
`./gradlew …

Dependency updates 20201111

---

AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.java

From beta feedback: this wasn't a great experience.
Related: #7124

Note Editor Toolbar: Insert "<hr>" before cursor

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/MissingImageHandler.java
AnkiDroid/src/main/res/values/02-strings.xml
AnkiDroid/src/main/res/values/constants.xml

Protocol relative URLs didn't work:
Fixes #6102
We add a snackbar to warn the user and explain how to fix this.
In Anki, protocol-relative URLS are converted to https://
In AnkIDroid, they're converted to file://
file:// fails to load the image - we can't redirect from `shouldInterceptRequest`
Loading synchronously is not viable, so all we can do is use a snackbar.
On my phone and API 19 emulator
⚠️ Issue: https://github.com/ankidroid/Anki-Android/issues/7665
* HTTP 300s aren't supported by `shouldInterceptRequest`
* Section links seem broken on some phones.
* https://github.com/ankidroid/Anki-Android/wiki/FAQ#why-do-my-images-need-a-protocol

Warn on Protocol-relative URLs

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/MediaTest.java
AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.java
AnkiDroid/src/main/java/com/ichi2/libanki/Media.java
AnkiDroid/src/main/java/com/ichi2/libanki/exception/EmptyMediaException.java
AnkiDroid/src/test/java/com/ichi2/libanki/AnkiPackageExporterTest.java

A 0 byte file causes sync errors - these are handled and shown to the user: 2e3d1168a89e7d4b6627b379453fa2399c0bead2
But better to stop them at the source to reduce errors in ACRA and improve UX.
Fixes #7662
Added instrumented test, they didn't start on my machine (emulator or Device) - so let CI handle it.

Disallow adding 0 byte files to Media

---

AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
AnkiDroid/src/main/res/values/10-preferences.xml
AnkiDroid/src/main/res/xml/preferences_advanced.xml

No longer necessary now we have the note editor toolbar.
Related: 43151b618758c80b2bd4b7134f498a56f5b27170
Fixed By: #7124

Remove MIUI Keyboard Hack Preference

---

AnkiDroid/src/main/java/com/ichi2/anki/CardInfo.java
AnkiDroid/src/main/res/values/07-cardbrowser.xml

Removed: `card_info_cannot_load`
The user knows they're opening the info screen - so we can show a generic error

NF: Remove Specific Error String

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java

Reverts 23f9d804f22cb87af322c279db7804b943f8d503
Actions such as adding a new card no longer update the view
Fixes #7676
Tested on my Android 9
-----

Revert: "NF: save current search to avoid doing it twice"

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java

* Pressing "Reschedule/Reposition/Reset Cards" did not bring up the "undo" item
* These items and Undo did not update the data in the grid
Fixes #7674 
Obtain the cards, reset them and make the grid refresh
Android 9, and some unit tests - some were flaky
We need more tests

Card Browser: Fix "Undo" not appearing and stale data

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java

getItemId return `int`, so no need to encapsulate

NF: always int

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
AnkiDroid/src/main/java/com/ichi2/anki/VideoPlayer.java
AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/MissingImageHandler.java
AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java

I feel we've reduced missing image support complaints due to #7009
We now do the same for sounds.
We'll want to move to a builder pattern to handle autoplay - as the parameter list for `playSounds` is already probably too complex.
Related #7009
Handle the error - check if the file exists, and if it doesn't, show a snackbar.
Android 9 phone

Show Card Content Error on missing Sound

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/Shared.java

Test-only
`dir` can exist, but `listFiles()` can return null if there are too many
file descriptors open
Discovered during testing of Rust implementation

TEST: Handle EMFILE (too many files)

---

AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java

It previously read "Rename note type" while renaming a field
Fixes #7695 
Not at all :)
- [x ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x ] Your code follows the style of the project (e.g. …

 Change rename field string

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/FieldEditLineTest.java
AnkiDroid/src/main/java/com/ichi2/anki/FieldEditLine.java
AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.java
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/FieldState.java
AnkiDroid/src/main/res/values/10-preferences.xml
AnkiDroid/src/main/res/xml/preferences_advanced.xml

Many user complaints that some cards are handled incorrectly. If a card from Anki Desktop with a newline (not a `<br>`) is added, this this gets converted to a `BR`, which changes formatting.
Fixes: #3304
Related: #7124 (toolbar)
Add a **persistent** (reviewers: note) flag to see if newlines should be converted to HTML and vice-versa.
If this is selected, then fields are reloaded from the database
Android 10 emulator
```
AAA<br/>
AAA
```
now appears as HTML

Note Editor: Option to replace newline with HTML

---

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java

The snackbar did not appear as the activity was closed.
Instead, a toast works
Tested on an API 25 emulator

Fix invalid snackbars

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java

After creating a new deck and opening a dialog menu by long tapping on the recently created deck, then tapping "Custom Study" option on the menu and tapping "Review ahead" option on the newly opened menu and then typing a number greater than 1 as days and tapping "OK" button, an alert dialog with text message "Rename the existing custom study deck first" appears but immediately gets obscured at the back of an another dialog menu.
Fixes #7680 
Show a Toast message converting Dialog to Toast.
Android 9

Deck Picker: Convert the dialog to a Toast

---

AnkiDroid/src/main/res/values/attrs.xml
AnkiDroid/src/main/res/values/styles.xml
AnkiDroid/src/main/res/values/theme_black.xml
AnkiDroid/src/main/res/values/theme_dark.xml
AnkiDroid/src/main/res/values/theme_light.xml
AnkiDroid/src/main/res/values/theme_plain.xml

this is more of an issue report than a pull request, but the attached changes fix the problem for me
i did **NOT** test this on any other devices or android versions
this removes changes introduced by @hssm in 448ea4fb5b04f9e1e83063a69c469ea92c569f16 so perhaps they might want to review this
when the overflow menu is animated in, instead of it simply sliding into place, in that place a static rectangle appears with the same color as the menu, and then the menu slides into that. this looks pretty bad on my device (nearly pure android). also the resulting menu lacks rounded colors.
either everyone else is not annoyed by this (unlikely) or it only happens for me (likely)
removed the background for the menu target area along with the relevant elements
the menu has its own background. the …

Fix overflow menu background

---

AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
AnkiDroid/src/main/java/com/ichi2/libanki/Undoable.java

I added a few Null indication when investigating https://github.com/ankidroid/Anki-Android/issues/7723 and tried to make clear that no null element is sent to `markUndo`

Undo direct

---

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java

There appears to be a race condition in `LinkedList.unlinkFirst`
We can't use a `synchronizedList` here, as we want the Linked List
specific methods, so use a lock.
Fixes #7723
Waiting for #7727

"Undo" feature: Fix race condition

---

.github/pull_request_template.md
lint-rules/src/main/java/com/ichi2/anki/lint/IssueRegistry.java
lint-rules/src/main/java/com/ichi2/anki/lint/rules/DuplicateCrowdInStrings.java
lint-rules/src/main/java/com/ichi2/anki/lint/utils/Constants.java
lint-rules/src/main/java/com/ichi2/anki/lint/utils/StringFormatDetector.java
lint-rules/src/test/java/com/ichi2/anki/lint/rules/DuplicateCrowdInStringsTest.java

We had a step in our "Pull Request" template to check for duplicate strings.
Automation > Process, so we get rid of this and convert it to a lint check
Fixes #7582
We copy some AOSP classes:
* `StringCasingDetector.kt`
* `StringFormatDetector.java`
Then convert `StringCasingDetector` to only handle:
* /values/ - ignore any language-specific 
* Ignore strings if all have a "comment=" attribute
Finally, turn it on and remove it from the PR template
Test only - CI should tell us

Remove Duplicate String check from PR Template

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java

Currently, showing search result in the browser takes time. On my collection, showing a big deck with subdecks takes 20 seconds. I thought that it could be possible to first show the first cards, and then show the full result. The number of cards I chose is exactly the number of precomputed cards we were already calculating. This lead to showing a part of the result in 7 seconds, while the whole result still takes 20 seconds to show.
The progress bar is still displayed to indicate that the result is not yet fully present.  
Since the card we must show is not yet necessarily in the list, I wait until the full list is  computed to scroll to it.
The collection task sends a progress update with the partial result.
We may also want to regularly send partial result, so that the list grow and …

Show partial result in browser before showing all

---

AnkiDroid/src/main/res/menu/deck_picker.xml

I was originally concerned that menu items may be hidden if there are too many.
Sync is most important, so it should be at the "top" of the priority list,
which makes it on the left.
But, as we're using "always show", this shouldn't be a problem
Fixes #7737

Move "Sync" to right of action bar

---

AnkiDroid/src/main/java/com/ichi2/libanki/Note.java

Broken in 95af4ee if the sort field was changed
IMO, no point in regression testing this
Fixes #7746
Tested on my Android 9 phone

[BugFix] dupe or empty

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java

onPrepareOptionsMenu bug
`menu.findItem(R.id.action_undo)` would return null on Android 8
Cause unknown. This should work around the issue.
Fixes #7755
Stop using `onPrepareOptionsMenu`
Android 9  - couldn't repro on Android 8 emulators
https://github.com/wordpress-mobile/WordPress-Android/issues/9748

[BugFix] Android 8: Fix Missing menu items

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/main/java/com/ichi2/utils/ContentResolverUtil.java
AnkiDroid/src/test/java/com/ichi2/utils/ContentResolverUtilTest.java

Obtaining the filename for a pasted image could throw a `SQLiteException`.
Fixes #7748 
* Obtain the MIME type
* If this throws, the throw - it's caught, and we get the logcat of both the old and new exception
Unit tested - new code works on my Android 9
https://stackoverflow.com/questions/8589645/how-to-determine-mime-type-of-file-in-android

Note Editor Image Paste: Handle invalid filename

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
AnkiDroid/src/main/java/com/ichi2/utils/ExceptionUtil.java
AnkiDroid/src/test/java/com/ichi2/utils/ExceptionUtilTest.java

An InvocationTargetException had no message, but the nested exception did
Fixes #7739
Walk the tree to get all the messages
Unit tests

WebView Exception: show nested exceptions

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.java

Note: this will conflict due to double addition of getFieldForTest
It's better if paste pastes at the cursor
This also raised a bug in the Multimedia edit implementation if a selection was made where start > end
Fixes #7770
* Insert at cursor, or replace if selection
* Insert at end if field is not selected
Unit tested

Note Editor: Paste image at cursor

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java

Java has fall-through case statements
Fixes #7771

BugFix: NoteEditor: stop "C" opening preview

---

AnkiDroid/src/main/java/androidx/drawerlayout/widget/ClosableDrawerLayout.java

For now, the handling of blocking the animation was buggy, so keep showing animations even if Safe Display Mode is on.
Tapping on the left side of the navigation drawer caused it to partially pop out, closing it made the entire UI unresponsive.
I had a few tries, but both of these meant that the drawer closed immediately when it was swiped open.
We might need to copy the navigation drawer code and recode it.
Fixes #7344
Related #7119
Related #7114
Disable the offending code
API 19 emulator

BugFix: Safe Display - Don't block nav drawer

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java

Fixes `onPageFinished` in JavaScript being run multiple times unneccessarily.
https://github.com/ankidroid/Anki-Android/issues/7790
It checks that `onPageFinished` runs agains the viewers main url, without any anchors.
I made sure, that `onPageFinished` within JavaScript is only ever executed once.

Add check that onPageFinished runs on the viewer url

---

AnkiDroid/src/main/res/values/11-arrays.xml

We want to move away from `string-array` as it causes problems when adding items in the middle (the array controls both the strings and the positions).
These strings are the ones which do not already have duplicates defined
This will require some manual follow-up work to copy from the existing language files to the new strings, but I'm happy to take this on.
Follow up steps:
* Language sync
* Copy from `string-array` to `string` for each language file
* Move `gestures_labels` to constants.xml
Related: #7794

Arrays: Extract gestures_labels strings

---

AnkiDroid/src/main/assets/scripts/card.js
AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java

Implement the onUpdateHook and onShownHook in AnkiDroid. These two hooks have existed in [the Anki codebase](https://github.com/ankitects/anki/blob/master/qt/aqt/data/web/js/reviewer.ts#L56) for some time now.
I recently updated them to be able to return promises. This allows users to have async functions synchronize with the rendering of MathJax.
No issue.
`onUpdateHook` and `onShownHook` are two arrays, which exist to the user, while the card is being rendered.
The user can utilize them in note fields, or the card template, and can push actions to them. 
This will cause those actions to be synchronized with the rendering of MathJax.
1. `onUpdateHook` is run before MathJax
1. `onShownHook` is run after MathJax finished completely
These functions can optionally return promises, which lets …

Add onUpdateHook and onShownHook in card.js

---

AnkiDroid/src/main/assets/scripts/card.js
AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java

This is an alternative approach to handling the lack of hiding before `onUpdateHook` on AnkiDroid, implemented in #7791.
It avoids adding two new symbols, but slightly changes the semantic of another symbol.
This would could let you use the following CSS to hide the content:
```javascript
.android .card:not(.mathjax-rendered) {
visibility: hidden;
}
```
This is a trade-off, rather than an improvement:
1. The previous approach introduced two new symbols
2. This one slightly changes the semantic of one existing symbol
I could not really find any sign of use for the `mathjax-rendered` CSS class anywhere, so it might be better to take the slight change in meaning. What's also nice about this is that the CSS selector is pretty self-explanatory.

Alternative approach to handling hiding regarding onUpdateHook

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/main/res/menu/note_editor.xml
AnkiDroid/src/main/res/values/02-strings.xml

Some users were unhappy about the reduction in screen real estate
Fixes #7785
This adds a "Show Toolbar" menu item, defaulting to "true"
API 19 emulator 
* Initial state matches the preference
* Changing state changes both the toolbar and the checkbox

Note Editor: Add Toolbar Toggle

---

AnkiDroid/src/main/res/values/11-arrays.xml
AnkiDroid/src/main/res/values/constants.xml

We convert it to string references, then move it from a translatable file
This lets us change the order of, and add items without affecting CrowdIn
* English (default) - works
* esperanto - deleted strings from 11-arrays - works
* French - Translated Strings remain in 11-arrays - works
Related: #7794 (fixes `gestures_labels`)
This is where strings are deleted and we diverge from 2.14.2

Move gestures_labels to constants.xml

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.java

Tested on API 30 - still works
And API 25 emulator - still doesn't work, it seems that the launcher must be able to handle the intent, and the default emualtor launcher doesn't do this.
Fixes #7744

Create Shortcut: Use compat class

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java

We were using the wrong type for `CREATOR`
Surprisingly this worked before the code change.
Maybe Fixes #7822
API 30 emulator - still works

BugFix: Help Menu - "FunctionItem" serialization

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java

For discussion:
It's not necessary to search with few decks, and I expect that users may feel it means "search for a shared deck"
Slightly improves the "new user" flow

DeckPicker: Hide "search" for new users

---

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java

Decks ids are long and not int. This is corrected. In particular `queryScalar` return an int, so part of the returned value is missing.
That was never a problem because  `parameterDid` is ALWAYS 0. There is not a single time where it's set to anything else. So int or long does not matter.
`getNewLinkedCard` is used in two cases. When creating a new card, the query does not return any result since the card does not exists yet it can't be find in the db. When the card is previewed, the wrong deck can be seen only if the card uses `{{Deck}}`
I just realized by the way that previewing a card does not work currently on my phone. Don't know why. This means that I can't test

NF: deck ids are long and not int

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.java
AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java
AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java
AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.java
AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java
AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.java
AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.java

Getting the first card when you select a deck is a long process (at least when you have a big deck collection). This is because before actually getting the first card, AnkiDroid computes the number of new card/review card you need to see. Once it's done, it finally loops over all deck and look for a card to learn.
This PR simply reverse the process. It split reset in two parts, which both can be used or ignored. A part which computes the number of cards to see and a part which reset all queues and list of decks to consider. When reset should be done in `getCard`, it first runs the important part of `reset` (i.e. resetting queues), then look for a card, then finally, in background, computes the numbers of cards.
Ideally, I would just separate `reset` in a pair of functions. I prefer to …

Get first card quicker during reviews

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
AnkiDroid/src/main/java/com/ichi2/async/Connection.java
AnkiDroid/src/main/java/com/ichi2/libanki/sync/CustomSyncServerUrlException.java
AnkiDroid/src/main/java/com/ichi2/libanki/sync/FullSyncer.java
AnkiDroid/src/main/java/com/ichi2/libanki/sync/HttpSyncer.java
AnkiDroid/src/main/java/com/ichi2/libanki/sync/MediaSyncer.java
AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java

Sync (and login) are very complex. Some of the complexity may be unavoidable because a lot of things may break during a
sync. However, I tries at least to reduce it.
In particular, one of the main problem it has is that the state is transmitted using an array of objects whose first
object is the status as a string.
I decided to do multiple change. In a single commit because they are so linked together that I don't see how else to do
it.
Instead of strings, I use an enum for all the different cases that existed. It allows to have a full list of the
potential return value of sync. Some still lack comments, for example, it would be nice to have a clear explanation of
why there are GENERIC_ERROR and ERROR, but I don't understand the whole process well enough to be sure that they are not …

NF: Simplifies Sync by using an enum

---

AnkiDroid/src/main/java/com/ichi2/libanki/utils/Time.java

Either we should uses local, or we should explicite the local

NF: remove linter warning SimpleDateFormat

---

AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java
AnkiDroid/src/main/java/com/ichi2/async/CancelListener.java
AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java

On tablet, clicking on the deck open an extra tab. This tab computes counts. This means that if you click on many deck without really thinking about it, you add a lot of computation in background. It also means that when you open the deck picker, there is a deck selected by default, whose counts is being computed uselessly, and this delay the opening of the deck you actually care about.
So I add the possibility to cancel those counts.
I should note that I pay close attention not to cancel the counts when we go to reviewer, because in this case those are the very same counts we need to use, and the computation will be useful. (At least until the PR to get a first card faster is merged)

NF: Study option fragment computation can be cancelled

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardTemplate.java
AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/CardTemplateTest.java

The code's been bugging me for a while due to the multiple `.replace` calls.
This is faster, but enforces an order on `card_template.html`. As this is controlled by us, I felt it was worth the risk.
I have confirmed that unit tests break if `card_template.html` is invalid.
```
java.lang.Exception: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(getMainLooper()).idle() call.
at org.robolectric.android.internal.AndroidTestEnvironment.checkStateAfterTestFailure(AndroidTestEnvironment.java:502)
at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:581)
at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:263)
at …
```

Speed up Card Template Generation

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java

It's counterIntuitive to use `answerCard` most of the time without card.
In AnswerCard it's valid to assume card is non null, since it's called only from reviewer when it already has got a card.
The try/catch was introduced in c12bac38d4096373dfdcb1b8c9b4e89542979f09, and while it may have been useful in 2011, I don't see any reason to assume a bug here specially with current wok.
I can't figure out how to check for a specific message in acralyzer, but if we find any "doInBackgroundAnswerCard" then I was wrong and this should be rejected.

Split AnswerCard

---

AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java

Otherwise, the search for the field is done once by note
Note that it's important, findDupe is only used in tests right now

NF: ordForMid also save when a field name is absent

---

AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.java
AnkiDroid/src/main/res/menu-television/reviewer.xml
AnkiDroid/src/main/res/menu/reviewer.xml
AnkiDroid/src/main/res/menu/study_options_fragment.xml
AnkiDroid/src/main/res/values/02-strings.xml
AnkiDroid/src/main/res/xml/preferences_custom_buttons.xml

***WARNING**: although i tested this to the best of my understanding of the app, it has many menus and functionality that i personally don't use so i might have missed something. particularly, i don't have a tablet*
the new strings "Deck options" and "Study options" replace the string "Options" that is ambiguous andd can be confused with "Settings".
the word "options" ("preferences", "settings") when used by itself usually means global settings. i think it helps to clarify the intent behind it otherwise
created new strings for "Deck options" and "Study options". the string "Options" (`study_options`) remains as a preference category. as per the wiki i did not rename its key, but i changed the comment. (i think it'd be nice to rename the key also.) in StudyOptionsFragment, the string for …

Replace menu string “Options” with either “Deck options” or “Study options”

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.java
AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.java
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.java
AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java
AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java
AnkiDroid/src/main/java/com/ichi2/anki/UIUtils.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java
AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
AnkiDroid/src/main/java/com/ichi2/async/Connection.java
AnkiDroid/src/main/java/com/ichi2/async/TaskManager.java
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
AnkiDroid/src/main/java/com/ichi2/libanki/importer/Importer.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java
AnkiDroid/src/test/java/com/ichi2/async/AbstractCollectionTaskTest.java
AnkiDroid/src/test/java/com/ichi2/libanki/CheckMediaTest.java

This is a small part of https://github.com/ankidroid/Anki-Android/pull/7045 . It splits CollectionTasks in two. One part is `TaskManager`; the manager is in charge of adding new task, removing them, keeping track of the queue of tasks.... and `CollectionTask` keep everything that is related to actually executing a task. I believe those are distinct enough to justify being in two classes. Furthermore, it will simplify the PR #7045 by ensuring that this PR change only the files related to managing tasks and won't have to change the remaining of the code base.

NF: Split collection task

---

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java

A quick search in git history shows that the method `previewCards` was introduced in 2012 in 2f3ea8868ce37534b1d3b7fee1c7f0c9fb1edbfa and has never been used since. I can't find a single time where `previewCards(` appears in the code base, appart when I did some changes such as replacing ints by constant.
As far as I understand, this is unrelated to previewing as we consider it today (it would be hard, in 2012). It returns instead the card that should be shown to the user if they asked to preview cards. If the user was creating a card, then it would show all cards generated. If the user was asking to edit the cards it would show already existing cards. If the user was trying to edit a note type, it would show all card types.
David called my attention on the fact that it's not used in …

Delete a method never used

---

AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.java

According to Mike:
> lots of devices crashing in the automated robotest from google on the alpha release
> > FATAL EXCEPTION: Thread-6
> > Process: com.ichi2.anki, PID: 9642
> > java.lang.NullPointerException: Attempt to invoke virtual method 'com.ichi2.libanki.Decks com.ichi2.libanki.Collection.getDecks()' on a null object reference
> >     at com.ichi2.anki.widgets.DeckAdapter$DeckFilter.<init>(DeckAdapter.java:4)
> >     at com.ichi2.anki.widgets.DeckAdapter$DeckFilter.<init>(DeckAdapter.java:1)
> >     at com.ichi2.anki.widgets.DeckAdapter.getFilter(DeckAdapter.java:1)
> >     at com.ichi2.anki.DeckPicker.__renderPage(DeckPicker.java:21)
> >     at com.ichi2.anki.DeckPicker$UpdateDeckListListener.actualOnPostExecute(DeckPicker.java:9)
> >     at …

NF: correct automated google test creating deck adapter too soon

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
AnkiDroid/src/main/java/com/ichi2/async/TaskManager.java
AnkiDroid/src/main/java/com/ichi2/utils/BooleanGetter.java

The very wrong line was
```java
private static class UpdateCardHandler<Result extends BooleanGetter> extends
ListenerWithProgressBarCloseOnFalse<Pair<Card, String>, Result> {
```
`UpdateCardHandler` should not have taken a parameter, and especially, no variable of this type should have been
declared without parameters. This stopped typechecking to work, and lead to #7862.
The remaining changes are the one detected by the correction of this first line.
The irony is that the whole point of using Task was to ensure type safety
Fixes #7860
Fixes #7864

correct typing of tasks

---

AnkiDroid/src/main/java/com/ichi2/async/Connection.java

Each time in Connection a generic error is returned, it is quite similar.
Furthermore, 38ab1ea7ad9878223313e2aab2fb4c4462568dc5 moved result to resultType, which was mostly correct. However, for
the sake of consistency, it should have left a 0-length array in result. This repair it
However, I do not believe this is the cause of #7863 , because the problem would have been the same with an array of size 0

Add a method `returnGenericError` to factorize code

---

AnkiDroid/src/main/java/com/ichi2/async/Connection.java
AnkiDroid/src/main/java/com/ichi2/libanki/sync/MediaSyncer.java

For some reason I don't get, in 38ab1ea7ad9878223313e2aab2fb4c4462568dc5, a string was not replaced by the enum value. And since `.equals(Object)` is valid even when it's obviously false, it was not detected by type system

Correct media sync

---

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
AnkiDroid/src/main/java/com/ichi2/libanki/sync/FullSyncer.java
AnkiDroid/src/main/res/values/10-preferences.xml
AnkiDroid/src/main/res/xml/preferences_reviewing.xml
AnkiDroid/src/test/java/com/ichi2/anki/WhiteboardDefaultForegroundColorTest.java

Removes "Black strokes" setting (deprecated in #6550) and slight UI fix for pen colors 
Fixes #7836
- Removed "black strokes" refs in xml files, UI, and associated Preference vars in other files
- Removed monochrome check for foregroundColor
- Set visibility for black/white pen colors based on Night mode
- Updated Whiteboard Foreground Test 
Tested on emulator & passed unit tests

Remove legacy Whiteboard settings

---

AnkiDroid/src/main/java/com/ichi2/async/Connection.java
AnkiDroid/src/main/java/com/ichi2/libanki/sync/FullSyncer.java
AnkiDroid/src/main/java/com/ichi2/libanki/sync/HttpSyncer.java
AnkiDroid/src/main/java/com/ichi2/libanki/sync/RemoteServer.java
AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java

For some reason, a lot of variable has type `HttpSyncer` while there type where always the same more specific type. I thus moved them to the specific type.
There were methods in `HttpSyncer` that always returned null, or 0, and were not redefined in all descendant, because this method makes sens for a single descendant. So I removed the method and left here only where it is actually used instead of having a method whose meaning is not even properly defined.
In my opinion, it leads to code which is quite easier to read, since I know as soon as I read a variable what kind of server I'm connected too, what I am expected to be able to do, and I don't have to wonder what could be the sanity check of a media server, e.g.

NF: varible has a specific server class

---

AnkiDroid/src/main/assets/scripts/card.js

Fix a bug caused by using `card` outside of the MathJax callback. Was introduced in #7807 .
Put it outside of scope of MathJax callback.
Error message is no longer raised in WebView Inspector

Put card outside of scope of MathJax callback

---

AnkiDroid/src/main/java/com/ichi2/utils/DiffEngine.java
AnkiDroid/src/test/java/com/ichi2/utils/DiffEngineTest.java

Some Polytonic Greek characters did not display within the WebView when shown as HTML entities rather than unicode characters
Fixes #7896 
* Only escape dangerous HTML characters (as we did before API 16)
* This leads to a non-context free escaping (quote characters are now escaped)
Unit tested
* Please see unit tests and commit messages
* Explanation in #7896 
* https://stackoverflow.com/questions/35104032/whats-the-difference-between-androids-html-escapehtml-and-textutils-htmlencode

Typed Answer: Fix Polytonic Greek Characters

---

AnkiDroid/src/main/res/values/theme_dark.xml
AnkiDroid/src/main/res/values/theme_light.xml

This ensure that the contrast is good enough for accessibility standard, the scanner's warning gets removed.

Move button color from blue 700 to 800

---

AnkiDroid/robolectricDownloader.gradle

When #7843 went in, I adjusted the robolectric tests that use SDK brackets to use API21 vs API16 but I had not bumped the robolectric cache warmer / SDK download task to download the different set of robolectric android.jar implementations required
- Remove all the Android 4.x robolectric android.jar implementation entries from possible download list
- Uncomment the API21 robolectric android.jar implementation so it is downloaded now
It is literally made of tests. But I will visually verify also.
If you don't occasionally read your test execution output, you will slowly succumb to entropy.

Alter robolectric pre-download task for minSdkVersion 21

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
AnkiDroid/src/main/res/values/10-preferences.xml
AnkiDroid/src/main/res/xml/preferences_advanced.xml
AnkiDroid/src/test/java/com/ichi2/utils/DiffEngineTest.java

In older WebViews, using a monospace font meant that some Polytonic Greek characters did not display
This applied to `<pre>` and `<code>`, a `<span>` worked best to fix this.
Replicated on an API 28 emulator - will take a long time to remove this.
Fixes #7896
* Add a preference, use a `<span>` tag if set

Add Preference to disable monospace font usage

---

.github/workflows/lint.yml
.github/workflows/tests_emulator.yml
.github/workflows/tests_unit.yml
AnkiDroid/build.gradle
api/build.gradle
build.gradle

- github actions workflows still not running when I like
- build system had a Travis-specific toggle which was really a generic CI toggle
- API project had stale compileSdkVersion
- we still had an old setting in build system from non-accelerated emulator days
Fixes #7852 
switch to `CI` env var for generic CI detection, remove adb options, bump api compileSdk, alter workflow paths
It is literally made of tests :-), but also visual inspection
- It appears all CI providers set the 'CI' environment variable to 'true'
- for paths to hit in path matching you must include a glob or it is an exact match

Various Build / CI cleanups

---

AnkiDroid/build.gradle
AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java

This PR should be seen with a grain of salt: I never worked with Android before, and my last Java experience is ten years back. So see this as a starting point :)
This PR addresses the issue, where the WebView in the reviewer can not load dynamic JavaScript modules via `import("<nameofmodule>")`. This is a really useful pattern in modern JavaScript, because it allows for asynchronous execution.
This is currently not possible on AnkiDroid, because you cannot request modules via the `file` scheme. 
With this PR, the user can use `import('https://appassets.androidplatform.net/<nameofmodule>.js')` to import modules from collection.media; and in fact even use `fetch('https://appassets.androidplatform.net/<nameoffile>')` to dynamically get files from the collection.media directory.
The prefix …

Add experimental support for dynamic import in Reviewer JS

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/main/res/values/01-core.xml

Currently, when you open a card editor, it shows the card current deck. In case of filtered deck, it shows the filtered
deck.  The trouble in my opinion is that there is no way to know what is the usual deck of the card. That's extremely
useful when I need to move a card to a different deck.
The solution I use is to show the current deck and the original deck in parenthesis. This seems to me to be consistent
with anki's browser's deck column.

Editing a card in a filtered deck show both decks

---

AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.java

This made a change only if a deck is collapsed but has no children. This can occurs if you do the following steps:
* On device A, create a deck A::B and sync
* on device B, sync, delete A::B and sync
* On device A, collapse A and sync
The deck A has property collapsed and no subdeck.
This is especially a problem because if you try to click on the arrow to uncolapse, you'll get a message stating there
is no subdeck, and so the "collapsed" sign will remain and can't be removed anymore.
Another solution should be to ensure that each deck without subdeck is uncollapsed.
To be perfectly honest, I only found this bug because I looked at the code and figure out how to reproduce it. I do not
know whether it's a bug for any real user.

Don't add "uncollapse" arrow if there is no subdeck

---

AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.java
AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java

For some reason, in 3e7983670370141b6dc2e1ab3d7a4036c0585def a true was changed to false. Given that the boolean is
never used, it can just be deleted. Instead, if there is a problem, the returned value is null, and that is what should
be checked.
Fixes #7918

Solve #7918

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.java

First, putting the value 0 in intent is useless. getInt returns 0 if the value is absent.
Second, if we are editing a card, we need to put the card ord.
This make me realize there is no way with "Add card" to preview card that are not the first card. This seems to be a
problem.
I tested previwing from browser and from add card. Both work. Fixes #7585

Fixes #7585: previewer get the card's ord

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/main/res/layout/note_editor.xml
AnkiDroid/src/main/res/values/dimens.xml

Padding for the toolbar was added, but wasn't removed when the toolbar was hidden
Fixes #7785
Remove the padding
API 21 emulator

Remove toolbar padding when hiding toolbar

---

AnkiDroid/src/main/java/com/ichi2/anki/reviewer/PeripheralCommand.java
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerKeyboardInputTest.java

I had added filtering for KeyEvents based on whether shift/alt/ctrl was pressed:
7df5008f660ae6c868d34504ccb5a22979161f01
I had not considered the fact that Shift + 8 is `*`
#7140
#7247
Fixes #7840
We no longer filter unicode characters based on whether shift is pressed
We also move many of the commands to use known keys, which makes the
implementation much more robust for when we move to custom key maps.
Android 9 + Keyboard

Fix "star" shortcut for Mark Note

---

AnkiDroid/src/main/java/com/ichi2/libanki/template/Template.java
AnkiDroid/src/test/java/com/ichi2/libanki/template/TemplateTest.java

This does not exists in anki, is not documented anywhere, and will disappear when rust is ported. Fixes #7960

NF: Remove ! special case in field name

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/res/values/01-core.xml
AnkiDroid/src/main/res/values/constants.xml

Change from showing "Help" (linked to Getting Started) to "Add Card"
this lets users more quickly get started
Fixes #7948

Improve Empty Deck UX: "Add Card"

---

AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java

This port https://github.com/ankitects/anki/pull/869
It ensures that #, /  and ^ can't start a field name. It also ensures that :, {, }, " can't be in field name
Currently, the backend also removes them when it meets them. We'll have this when rust is ported. At least, this change ensure that the error can't be entered in the collection, even if we don't correct it.
I should note that I'm not fan of silent correction, so I'm not really pleased by the way anki strip part of field name without warning users. The good point with this PR and the related anki PR is that the change is directly reflected in the field list, so they should see quickly what's going on

Field name

---

AnkiDroid/src/androidTest/java/com/ichi2/libanki/DBTest.java

Just something I want to keep in mind when moving to the Rust DB access

TEST: Ensure database write ahead log is disabled

---

.codecov.yml
.github/workflows/lint.yml
.github/workflows/tests_emulator.yml
.github/workflows/tests_unit.yml

- codecov was not posting expected coverage results
- codecov graphs had useless coloration
- github workflows were not executing on workflow definition changes
Fixes issue noticed by @david-allison-1 that coverage diffs weren't as expected, e.g. https://github.com/ankidroid/Anki-Android/pull/7977#issuecomment-751676625 where root cause appears to be 
>  ->  Issue detecting commit SHA. Please run actions/checkout with fetch-depth > 1 or set to 0
...from https://github.com/ankidroid/Anki-Android/pull/7977/checks?check_run_id=1616994735
- set github checkout action to fetch-depth of 20, that's fairly arbitrary but should cover all our PRs
- set coverage range minimum to 36 so that coloration divergence starts from our current baseline
- add workflow files to the path inclusion list for …

Codecov tuning

---

AnkiDroid/src/main/java/com/ichi2/libanki/sched/LrnCardQueue.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java

The logic is that either the queue is empty and should be filled, or the queue is non-empty and its head is the next element to review.
When we answer a card and it goes to learn mode, it should be added to the learn queue usually. But this breaks the logic if the queue is not yet filled. So I added a variable checking whether the queue is supposed to be filled or not, and in this case I don't add the element in it.
Regression test, and manual testing on emulator. Get a deck with only card in learning, open it, see multiple time

Fixes #7984

---

AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java

Reverting 89d7bd053a9c72806273c96c235a3b36f4d6e630 lead to failure.
As far as I can tell, the reason the test failed the first time I tried was that I didn't use
advanceRobolectricLooperWithSleep and not because I was correctly testing. To correctly test, I need cards to be due in
the past, not in the future. So either I should wait a minute, or set the due date in the past

NF: correct 7984 regression test

---

AnkiDroid/src/main/java/com/ichi2/libanki/Consts.java
AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.java

Upstream has started logging revlog.ease = 0 on manual reschedules from the deck browser
We are not doing that (and still not doing that after this PR) but we do need to ignore them in stats or we get unsightly extra 0 columns and skewed today/overview stats
This adds an 'ease > 0' to all the where clauses, should fix it?
Fixes #8008
Simple SQL where clause addition
Relatively untested but if we generate an alpha it appears that @dummifiedme has a collection that reproduces the issue.
Pays to watch the ankitects/anki repo, which I have not been doing...

Ignore revlog.ease == 0 in stats, Fixes #8008

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
AnkiDroid/src/main/java/com/ichi2/anki/CardInfo.java
AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.java
AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.java
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java
AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java
AnkiDroid/src/main/java/com/ichi2/libanki/Card.java
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
AnkiDroid/src/main/java/com/ichi2/libanki/Consts.java
AnkiDroid/src/main/java/com/ichi2/libanki/Deck.java
AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
AnkiDroid/src/main/java/com/ichi2/libanki/Media.java
AnkiDroid/src/main/java/com/ichi2/libanki/Model.java
AnkiDroid/src/main/java/com/ichi2/libanki/Models.java
AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckDueTreeNode.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
AnkiDroid/src/main/java/com/ichi2/libanki/stats/AdvancedStatistics.java
AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.java

The goal is only to improve readability. Values are only 0 and 1, so rewritting `!= 0` to `== DECK_DYN` is always correct.

NF: Uses constant for decks "dyn" value

---

AnkiDroid/src/main/java/com/ichi2/libanki/template/TemplateFilters.java
AnkiDroid/src/main/res/values/01-core.xml

When a field is not found in a card template, the error message was always in English. I correct that.

"Unknown field" message gets translated

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.java

Previously the message was titled "Media checked" with content "AnkiDroid"
We reverse this to stay consistent with other messages
check_media_acknowledge: "Media checked"
Fixes #8031
Untested

fix: "Media checked" Title

---

AnkiDroid/build.gradle

**This is a non-necessary proposal - happy to see it rejected**
Download Javadoc/Sources for all dependencies
This will help keep a developer in the IDE when coding and looking into the definition of our dependencies.
Swaps an initial one-time download for ease of development
Still builds - one time hit to download docs and sources
https://docs.gradle.org/current/javadoc/org/gradle/plugins/ide/idea/model/IdeaModule.html#isDownloadJavadoc--
https://docs.gradle.org/current/javadoc/org/gradle/plugins/ide/idea/model/IdeaModule.html#isDownloadSources--

Download Javadoc/Sources for all dependencies

---

AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
AnkiDroid/src/main/res/values/04-network.xml

This occurred on my PC due to internet instability. The error message is
much more human readable now

Login: Improve error message on no connection

---

AnkiDroid/src/main/java/com/ichi2/libanki/Models.java
AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.java

This fixes #8030. I add a regression test and ensure that even the absence of text is detected as a valid cloze content. I tested upstream and confirm that this was indeed a difference with upstream.
This code was intoduced in 2015 8d7f08e8e1618b6437a81c1f5b004d1a39153046 and the original requirement of non empty cloze was introduced in 2012 in 5040ef1a3e19d1a60359945bd5dfb4bcce8886fe. I won't state it was a bug, I honestly don't know for how long upstream did accept empty cloze content. This may be worth an update in 2.14 in my opinion, because there is a slight risk that it leads to cards deleted by accident. However, only DAE can tell us how often this is used, since he got the only database with a lot of users.

Empty cloze are detected

---

README.md

Preview: https://github.com/david-allison-1/Anki-Android/blob/readme-open-collective/README.md
We have 4 choices (one of which is per-tier):
Sensible options:
Unsure whether we should optimise for transparency with the total number, or for monthly backers:
Backers was picked, after much hesitation.

Add Open Collective Backer count to README

---

AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java

Run teardown even if collection does not close
Untested

test(RobolectricTest): Improve error recovery

---

AnkiDroid/src/main/java/com/ichi2/libanki/template/ParsedNode.java
AnkiDroid/src/main/java/com/ichi2/libanki/template/Replacement.java
AnkiDroid/src/main/java/com/ichi2/libanki/template/Tokenizer.java
AnkiDroid/src/test/java/com/ichi2/libanki/template/ParserTest.java
AnkiDroid/src/test/java/com/ichi2/libanki/template/TemplateTest.java
AnkiDroid/src/test/java/com/ichi2/libanki/template/TokenizerTest.java

This fixes #8043
When porting template generation rules, I missed a special cases: filter applied to an empty field name. This is now corrected with regression test. Actually there is far more tests because I had to ensure that empty name are accepted, it was raising an uncatched exception in lexing because I assumed that all field names are not empty.
Thanks @thiswillbeyourgithub for the feedback

Fixes 8043

---

AnkiDroid/src/main/AndroidManifest.xml

> For users who choose to share usage statistics and diagnostics with Google, WebView sends usage statistics and crash reports to Google.
Usage statistics contain information such as system information, active field trials, feature usage, responsiveness, performance,
and memory usage. They do not include any personally identifying details.
https://developer.android.com/guide/webapps/webview-privacy
Eww... no
Fixes #7993
Quick test on API 25 emulator 
* https://developer.android.com/guide/webapps/webview-privacy
* https://developer.android.com/guide/webapps/managing-webview#metrics

Opt out of WebView metrics collection

---

AnkiDroid/build.gradle
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
AnkiDroid/src/main/java/com/ichi2/libanki/backend/DroidBackend.java
AnkiDroid/src/main/java/com/ichi2/libanki/backend/JavaDroidBackend.java
AnkiDroid/src/main/java/com/ichi2/libanki/backend/RustDroidBackend.java
AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java

Caused by an issue paging exactly 1000 items by the new database code
Fixes #8055
See:
https://github.com/david-allison-1/Anki-Android-Backend/issues/28
https://github.com/david-allison-1/Anki-Android-Backend/commit/7c5037079bb31f1c80b55a995bd06b5a2fc0381d

fix: Issue returning 1000 results from database

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerNoParamTest.java
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.java

It was frustrating to undo a card while in full screen, and the menu bars did not auto-hide.
This was the same for answering or flipping cards
Fixes #7643 
Add a delayed hide call
My device & unit tests
DelayedHide did not work with a 100ms delay when an options item was selected

UX: Hide full screen after user input

---

AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java
AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTestAnnotationTest.java
AnkiDroid/src/test/java/com/ichi2/testutils/AnkiAssert.java
AnkiDroid/src/test/java/com/ichi2/testutils/AnkiAssertTest.java

Previously:
```
java.lang.IllegalStateException: No instrumentation registered! Must run under a registering instrumentation.
at androidx.test.platform.app.InstrumentationRegistry.getInstrumentation(InstrumentationRegistry.java:45)
```
Now:
```
java.lang.IllegalStateException: Annotate class: 'PreferencesTest' with '@RunWith(AndroidJUnit4.class)'
at com.ichi2.anki.RobolectricTest.getTargetContext(RobolectricTest.java:225)
```

Improve error if test class not annotated

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/RustTest.java

The timeout was too low, we just want to ensure that this test doesn't block
It did originally before the backend was converted to use Rust for DB access
Fixes #8067

TEST: fix flaky test: collectionIsVersion11AfterOpen

---

AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
AnkiDroid/src/main/java/com/ichi2/libanki/Consts.java
AnkiDroid/src/main/java/com/ichi2/libanki/backend/DroidBackend.java
AnkiDroid/src/main/java/com/ichi2/libanki/backend/DroidBackendFactory.java
AnkiDroid/src/main/java/com/ichi2/libanki/backend/JavaDroidBackend.java
AnkiDroid/src/main/java/com/ichi2/libanki/backend/RustDroidBackend.java
AnkiDroid/src/main/java/com/ichi2/libanki/backend/exception/BackendNotSupportedException.java
AnkiDroid/src/main/java/com/ichi2/libanki/backend/model/SchedTimingToday.java
AnkiDroid/src/main/java/com/ichi2/libanki/backend/model/SchedTimingTodayProto.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
AnkiDroid/src/main/res/values/10-preferences.xml
AnkiDroid/src/main/res/xml/preferences_reviewing.xml
AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.java

Anki Desktop has modified their code to better handle timezone changes. See linked issue
Fixes #5805
Copied from Anki at commit https://github.com/ankitects/anki/commit/131d37dca52c29033432e0149052093ab1c79461
Except one line in Collection which accepts data if server == true.
https://github.com/ankitects/anki/blob/131d37dca52c29033432e0149052093ab1c79461/pylib/anki/collection.py
https://github.com/ankitects/anki/blob/131d37dca52c29033432e0149052093ab1c79461/pylib/anki/schedv2.py
* Bumps SYNC_VERSION to 10 if using Rust
* Add local_minutes_west and sched_timing_today to Backend
* Add "New timezone handling" preference: sets `creationOffset`
* Set "localOffset" preference if using SchedV2 under Rust
* Fix SchedV2:_updateCutoff to better handle timezones
We will calculate this information …

Sched: Enable New Timezone Handling Code

---

README.md

Indicate we incorporate AGPLv3 code.
While we don't have to list all licences used from any library, this seems especially relevant because:
* AGPLv3 is seens as a risk by some (e.g. https://opensource.google/docs/using/agpl-policy/ ) and there should be a clear warning I believe
* It can easily be argued that anki backend is very related to ankidroid, and is not just a third-party library. Especially since it seems quite probable that one day we'll need to make some PR to anki backend for our need.

Indicate we incorporate AGPLv3 code.

---

AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.java

Fixed #8092. Thanks @dae. This was the case since 2014, no idea why, and why it started to be a bug
1fbf16e693e6c8787cb00f6a8b00e88f1f76be46
I suggest pushing it to a stable version quickly, since it was creating problem. The problem seems to be because Anki does not accept string anymore and not because of an ankidroid change, but that's still a problem

curDeck is saved as a long.

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.java

Partial correction of #8095. When you long press on a filtered deck, it won't offer to create a subdeck.
It does not stop to create one at all, but at least there is not invite.

Remove "create subdeck" for filtered deck

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java
AnkiDroid/src/main/java/com/ichi2/anki/exception/FilteredAncestor.java
AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java
AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.java
AnkiDroid/src/test/java/com/ichi2/testutils/libanki/FilteredDeckUtil.java

This fixes #8095. However, I strongly consider merging #8101 to #8106 first, since they are all contained here.
Essentially, there are two versions of id and _ensureParents, one which always succeed, up to renaming ancestors; it's useful for imports and checking deck collection, since failing is not allowed, and one version which throws an exception. This exception is then dealt with on UI or in content provider. There are tests ensuring it works as expected.
I also splitted some function, so that the part which does not have to throw exception do not have to be duplicated.

No filtered has child

---

AnkiDroid/src/main/java/com/ichi2/libanki/LaTeX.java
AnkiDroid/src/test/java/com/ichi2/libanki/LaTeXTest.java

This corrects #8121.
The problem was introduced when I added alt text to LaTeX's image. I didn't properly escape the alt text. I escaped it for html but not for the method appendReplacement. This methods considers that $i corresponds to the ith group matched by the regexp, which breaks everything as soon as a LaTeX element starts with a number or an opening curly braces.
I put priority high, because it's a bug introduced since last stable, and I'd consider it to be blocking.
regression tests added with it

Ensure that latex's alt text work with appendReplacement

---

AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.java

Hi guys,
The upcoming desktop version tweaks the v2 scheduler to not cap the selected deck by its parents. This should not cause any problems when syncing between older/new clients, but if users have a parent limit set to a smaller value than a child, their deck list and counts during review may differ between clients, which could be confusing.
Ports https://github.com/ankitects/anki/commit/5f9792392a953271eee21004e3a49b591999b9a7

port parent limit change from desktop

---

AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.java

These unit tests were failing semi-reproducibly locally for me:
SchedV2Test::test_ordcycleV2
SchedV2Test::regression_test_preview
One of them was noted here https://github.com/ankidroid/Anki-Android/pull/8086#issuecomment-775191775
Neither was formally logged
Call the robolectric looper to advance
Just like soylent green, it's made of tests
I learned that gradle really does not want to re-run tests over and over without any changes - you have to force it, so my reproduction run was like:
`./gradlew clean jacocoUnitTestReport --rerun-tasks`

De-flake some unit tests

---

AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java

This PR is to support erasing with S Pen. Other devices may or may not be supported. 
There should be no side effects for anybody who doesn't use a stylus with a button. The will need to use the <kbd>Erase last</kbd> button as before.
Note that due to the lack of devices to test with, `TOOL_TYPE_ERASER` hasn't been implemented.
Fixes #8129 
- added handling for the new `MotionEvent`s
- made the `UndoStack` an `UndoList` so that arbitrary lines/dots can be deleted
- added logic that checks for intersections of lines/dots and eraser, to determine if something should be deleted
- made `interface WhiteboardAction` uglier
Tested on a Samsung Tab S3 (SM-T825) with S Pen.
- _N/A: UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)_

Implement eraser for whiteboard / S Pen

---

AnkiDroid/build.gradle

Gradle deprecated old way of getting ABI split info, use the new way
No issue logged
I carefully inspected (by executing the build script) the object tree available to me on the variant outputs, and what properties they had, along with the source code
https://android.googlesource.com/platform/tools/base/+/master/build-system/gradle-core/src/main/groovy/com/android/build/gradle/api/ApkOutputFile.java#146
And settled on this style to get the ABI in use, and then index into the version shift array for version code override
I was able to successfully generate expected different version codes for each of the APK files resulting from the ABI splits, verifiable via apkanalyzer manifest version-code <apk file> (assuming you have apkanalyzer tool installed)
Google updates documentation slowly some …

Forward-port to new style of getting ABI splits for release APK versioning

---

AnkiDroid/src/main/java/com/ichi2/preferences/IncrementerNumberRangePreference.java
AnkiDroid/src/main/java/com/ichi2/preferences/NumberRangePreference.java
AnkiDroid/src/main/res/values/02-strings.xml
AnkiDroid/src/main/res/xml/deck_options.xml

Feature request was made to add + and - buttons to "New cards/day" preference in Deck options. This PR implements that feature.
Fixes #8024 
Created a new class `com.ichi2.preferences.IncrementerNumberRangePreference` which extends `com.ichi2.preferences.NumberRangePreference` and adds two buttons to the preference, one for increment and one for decrement. This class can be used for other numerical preferences as well.
Emulated on API 29, Android 10.0. Worked as expected.

Added increment/decrement buttons for "New cards/day" preference

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
AnkiDroid/src/main/res/drawable/ic_back_arrow_custom_tab.xml
AnkiDroid/src/main/res/values/attrs.xml
AnkiDroid/src/main/res/values/theme_black.xml
AnkiDroid/src/main/res/values/theme_dark.xml
AnkiDroid/src/main/res/values/theme_light.xml
AnkiDroid/src/main/res/values/theme_plain.xml

The app was not changing the theme of custom tabs with respect to the theme of the app (it was always blue colored theme). In this PR, that issue is fixed. The change is somewhat broader than mentioned in issue as all the themes (light, plain, dark, black) are considered.
After fixing, the output of all 4 themes is in below image.
Fixes #8164 
Firstly, I used reflection to get the current theme value in `int` format (if the reflection throws exception then we will switch to the light mode irrespective of app theme). Then, I had made some changes in `CustomTabsIntent`.
Tested this on real device (Redmi Note 7S and Android SDK 29).
Anyone interested in how custom tabs work can look here at the official [link.](https://developer.android.com/reference/androidx/browser/customtabs/CustomTabsInte …

Fixes #8164 Changed custom tabs theme with respect to app theme

---

AnkiDroid/src/main/java/com/ichi2/anki/Info.java

Change log was always in light mode even when the app is in night mode both in release and debug build.
Also, just reformatted 2-3 lines `(ctrl+alt+L)` .
**Point to note is to test whether this will work in release mode I copied the changelog from the app ( live on playstore). This is to make sure that changelogs does not break in release builds.**
Attaching Screenshot for better refrence.
Fixes #6535 
Used **javascript** to make changes in the colors of `webView` (textColor, backgroundColor and link colors).
Tested on real device (Redmi Note 7S and API 29).
This PR can help you to learn the usage and implementation of javascript in webView for changing themes (day/night mode).

Fixes #6535 ChangeLogs theme with respect to app theme

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/main/res/drawable/ic_popup_menu_item_audio.xml
AnkiDroid/src/main/res/drawable/ic_popup_menu_item_clear.xml
AnkiDroid/src/main/res/drawable/ic_popup_menu_item_editor.xml
AnkiDroid/src/main/res/drawable/ic_popup_menu_item_image.xml
AnkiDroid/src/main/res/drawable/ic_popup_menu_item_record.xml
AnkiDroid/src/main/res/menu/popupmenu_multimedia_options.xml

Added icons to Multimedia menu in Note Editor. (working for all the themes)
Fixes #7526 
Added new vector icons and then used them in Popup Multimedia Menu.
**After the change the menu now looks like this.**
Tested on real device (Redmi Note 7S , API 29) and on emulator also (Pixel 3a , API 21).

Fixes #7526 Added icons to Multimedia menu in Note Editor

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java

It will be easier to know when question is displaying and answer using js api. I am implementing addon sometime card content only need to added to front side and some time to back side. So, there are no api to know the side of card.
1. Using ```JavascriptInterface```
2. Using ```AbstractFlashcardViewer::isDisplayingAnswer()```
1. Tested on Nexus 5 emulator
2. Add following to front/back side of card template to know if card currently displaying answer
```js
console.log(AnkiDroidJS.ankiIsDisplayingAnswer());
```
Return value: ```true``` or ```false```
- [ x ] You have not changed …

JS API to know if answer is displaying or question

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
AnkiDroid/src/main/java/com/ichi2/utils/MaxExecFunction.java
AnkiDroid/src/main/res/values/02-strings.xml
AnkiDroid/src/main/res/values/constants.xml
AnkiDroid/src/test/java/com/ichi2/utils/MaxExecFunctionTest.java

When the user tries to load an external file/image using the unsecure HTTP protocol will result in ``net::err_CLEARTEXT_NOT_PERMITTED`` and the file/image will not load for the user without any explanation.
see: #7231
Fixes #7741
Since we are using a custom ``WebViewClient`` we have the ability to intercept requests that the web view is making. So checking whither the URL scheme is HTTP or not becomes easy.
2 new string were added, one for the snackbar message, and another constant link for the [FQA#external-content](https://github.com/ankidroid/Anki-Android/wiki/FAQ#external-content).
Tested manually by trying to load a card with an HTTP image
Reading the docs of ``WebViewClient.shouldOverrideUrlLoading``. And realizing it won't be running on the Main/UI thread. …

feat: Warn when loading external http content

---

README.md

Previously pointed to jest
Before: https://github.com/ankidroid/Anki-Android/tree/947976d93aa02b05d523796c30daa0feff60915b#github-contributors
Now: https://github.com/david-allison-1/Anki-Android/tree/fix-readme#github-contributors
It's still an interesting order... We've surely had a lot more new contributors after me. Gotta be doing some filtering?

Readme: Fix Contributors Image

---

AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
AnkiDroid/src/main/res/values/10-preferences.xml

This PR enables the option to see change logs in release builds also.
Fixes #8230 
Moved the code out of **if** condition
Cannot test this for release builds.

Fixes #8230 Added change logs for release builds

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java

https://github.com/ankidroid/Anki-Android/issues/8235
fix webView scroll conflict with FullDraggableContainer
Fixes #8235
Respond to internal webview swipe first,If the internal slide of the webview is finished, the external slide is responded to, the key to solving the problem lies in the WebView.onOverScrolled method
working well on my pixel phone

fix card scroll conflict

---

AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java

This makes shuffling your deck (that is, switching deck-ordering between random and in-order-added) faster.
Fixes #8172.
The existing code passes in lots of cards that the subsequent UPDATEs filter out. We can go faster by doing more of this filtering in the initial query.
Stuff I worry about:
1. This isn't consistent with the [desktop implementation](https://github.com/ankitects/anki/blob/a0c47243b648a42f0f1a4a2c10c8b8495a0cfee6/rslib/src/scheduler/new.rs#L165)
2. Maybe I'm missing an important distinction between cards.type = ${CARD_TYPE_NEW} and cards.queue = ${QUEUE_TYPE_NEW}, and it's not safe to assume new cards are in the new queue or vice versa?
3. Maybe I'm missing something else, and we really _do_ need to pass non-new cards into `sortCards` here?
I copied my sqlite3 database …

Speed up randomizeCards and orderCards

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java

Solves the bug of extra space
Before:
After:
"" in progress dialog changed to null
fixes bug ankidroid#8252
Tested on Emulator: Pixel 3a API R

Progress Dialog of NoteEditor Extra Space Remove 

---

AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java
AnkiDroid/src/test/java/com/ichi2/libanki/UtilsTest.java

While working on #8248 I found an inconsistency between the pylib code and ankilib code. When dealing with tags. Also pylib code removes comments and ankilib currently lacks this.
I have also added a test to the pylib util code
https://github.com/TarekkMA/anki/blob/698f7745f3/pylib/tests/test_utils.py#L3-L14
Using tests :)

Add test to ensure Utils.stripHTML behave the same as the upstream

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java

Currently, we do not support drag to select many but it's alternative as suggested and approved here https://github.com/ankidroid/Anki-Android/issues/7910#issuecomment-768767950 is added.
Fixes #7910 
If in multi select mode then added a loop to select all the items between current selected and the one long pressed. 
Attaching the screen recording...
https://user-images.githubusercontent.com/65870389/111865788-0f013c80-898f-11eb-89de-dae23dc65f34.mp4
Tested on real device (Redmi Note 7S and API29)

Fixes #7910 Select many option in Card browser

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java
AnkiDroid/src/test/java/com/ichi2/anki/ReadTextTest.java

TextToSpeech was being released (shutdown) incorrectly due to a race condition.
When AbstractFlashcardViewer is recreated (Ex: through changing themes), the newly created activity initialized a new TextToSpeech. 
The old activity then releases that same TextToSpeech instance from onDestroy()
TextToSpeech will not work until it is re-initialized.
Fixes #8084
https://user-images.githubusercontent.com/16379504/110561114-1fa2ee80-8115-11eb-9a4b-db9f48ae2677.mp4
When TextToSpeech is initialized, a Context is passed in and stored.
That Context is always 'paired' with a single instance of TextToSpeech.
Because the caller that initialized the instance wants to make sure it cleans up when it's done, it attempts to release it.
The instance is stored in a static private field in a different class, …

Release TextToSpeech with a Context

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.java
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java
AnkiDroid/src/main/java/com/ichi2/themes/StyledProgressDialog.java

Removing white space for no title in a StyledProgressDialog dialouge popup
Fixes https://github.com/ankidroid/Anki-Android/issues/8272
I looked over every method using `StyledProgressDialog`  with title being "" and replaced with null
<p float="left">
</p>

Fixes #8272: Removed white space for no title in a StyledProgressDialog dialouge popup

---

AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java
AnkiDroid/src/test/java/com/ichi2/testutils/MockTime.java
AnkiDroid/src/test/java/com/ichi2/testutils/MockTimeTest.java

Instead of using time stamp, I suggest using calendar parameters to create MockTime. It will be easier to debug. I can tell it since I'm having a lot of problem creating regression test for a problem related to time right now.

NF: MockTime takes date parameter

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java
AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
AnkiDroid/src/main/java/com/ichi2/libanki/Models.java
AnkiDroid/src/main/java/com/ichi2/libanki/importer/NoteImporter.java
AnkiDroid/src/test/java/com/ichi2/libanki/ClozeTest.java
AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.java
api/src/main/java/com/ichi2/anki/FlashCardsContract.java

This partially port a change from Anki 2.1.28. Notes with no card are not deleted, instead first card is generated. This also change import of decks. It does not change when cards should be generated from the add card window (this would require a change in UI, so we would need to discuss what we want to do exactly to port this change)
This ensure that "Empty cards" does not delete note with no cards, so no data is lost. 
create a basic and a cloze card.
Edit them to remove front and cloze 1.
Click on "empty card"
See that it does not offer any deletion (i.e. no deletion of note, as in upstream)

Always generate a card

---

api/src/main/java/com/ichi2/anki/FlashCardsContract.java

No idea:
1. why it was not detected by tests (they were passing when merged)
2. I added them here, were they clearly have nothing to do
Fixes #8311

Remove allow_empty from card projection

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java

fixed #8266.Remove unwanted code with browserDeckidFromDeckPicker
REQUEST_BROWSE_CARDS and browserDeckIdFromDeckPicker removed as the animations that were introduced have been deprecated and no longer used
fixed #8266
_How does this change address the problem
REQUEST_BROWSE_CARDS and browserDeckIdFromDeckPicker removed as the animations that were introduced have been deprecated and no longer used
Runs on my device,Samsung SM-013F
_Please, go …

Unwanted else-if with browserDeckidFromDeckPicker and REQUEST_BROWSE_CARDS in DeckPicker removed.

---

AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.java

**Needs Review - Unsure if this is the approach we want to take**
`WebSettings.getDefaultUserAgent(context)` hard crashes the app. Note: diagnosed myself via debugger as the first crash, app worked fine after removal.
Known issue with WebView. Many issues in news about this.
Possible problematic version 89.0.4389.90 (code 438909033)
But, this was updated days ago, so there may be another cause and it didn't feel safe to block a version without knowing for sure that it's the only one causing issues.
Fixes #8319
Don't call `WebSettings.getDefaultUserAgent(context)` - this disables some level of granularity for analytics
* App no longer crashed during initial testing
* ⚠️ I've now reinstalled the WebView and can't repro a crash at all …

HACK: Fix startup crash due to broken WebView

---

AnkiDroid/build.gradle
AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java
AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerCommandTest.java
AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerKeyboardInputTest.java
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerKeyboardInputTest.java

Previously the dependency was implicit, this makes it obvious now and puts the
version under our control
Fragment 1.3.x brings in new APIs and causes deprecation warnings as noted here:
https://github.com/ankidroid/Anki-Android/issues/8293
Ignore the deprecation from now, forward-port tests to use robolectric where needed
for looper / lifecycle management in new Fragment version
Related #8293 - deprecation tracking issue
- adds explicit dependency on the fragment and activity libraries in use
- adds a deprecation tracker issue and notes in the code for forward-porting work
- alters some tests that were implicitly using fragments to run under robolectric so that the Looper is mocked (new fragment library touches it, causing errors without …

Explicit dependency on androidx.fragment/androidx.activity, bump versions

---

AnkiDroid/src/main/java/com/ichi2/libanki/Card.java
AnkiDroid/src/test/java/com/ichi2/libanki/CardTest.java

The main goal of those test is to ensure that the dates are correct. In some cases, having empty string is not ideal and not exactly what is shown upstream anymore, but I guess it'll wait for rust to be ported to get more up to date detailled values

NF: Unit test for nextDue and getDueString

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/main/res/values/colors.xml

Fixes  #7931
Highlight default selection in the pickers of note editor.
Related PRs: https://github.com/ankidroid/Anki-Android/pull/8171 and https://github.com/ankidroid/Anki-Android/pull/8174
`Before change` When the user was in note editor, there is a selector to change the type of note or card's deck, It was not highlighted.
`After change` Now, when the user selects something in this section, the background of the selected one will be highlighted by default to "light gray" color and the text color itself will be "black".
Tested by [Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&utm_source=www.apk4fun.com).
**Screenshots**
<div align="center">
<pre>
</pre>
</div>

Highlight default selection in pickers 

---

AnkiDroid/src/main/java/com/ichi2/anki/Info.java

Added additional and useful debug info -device manufacturer, model, hardware and webview user agent.
Fixes #8234 
Used the android os class `Build.` to extract manufacturer, model and hardware information
Used an anonymous instance of the `Webview` class which is `new WebView(this).getSettings().getUserAgentString()` to extract the webview user agent
Tested on an actual android device which runs on Android 10(API 29)

Added additional debug info (WebView/Hardware)

---

AnkiDroid/src/main/res/values/10-preferences.xml
AnkiDroid/src/main/res/xml/preferences_reviewing.xml

The UX is causing users to get confused with setting time above 24 hours
fixed #8267
Label has been added to specify the range of the hours
Works on my machine

fix:#8267:Correction made in PreferenceReview.

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java

The purpose to not rewrite the text typed in SearchView of Card Browser activity and directly use it when clicking on Add note (overflow menu) if there is no such card present.
Use text from browser search bar as the first field when adding a new note #4925
The approach was to first send the text from the CardBrowser activity on Add Note item click that was done using intent.putExtra and then setting it in first edit field when the focus was being set to it.
Tested on a physical device (Android -9)
https://user-images.githubusercontent.com/46752548/112643128-08c8ff80-8e6a-11eb-8ec9-46eec1e7c7aa.mp4

Use text from browser search bar as first field when adding new note added 

---

.codecov.yml

Most PRs had annotations added on each branch which did not have coverage
This added more noise to the PR, and was not helpful, as we aren't yet going for 100% coverage, it made reviews harder, and probably alienated new contributors
Fixes #8296
Disable the annotations
Untested - let's test in PROD. Looks similar to other files on GitHub
https://docs.codecov.io/docs/github-checks-beta

coverage: disable noisy annotations on PRs

---

AnkiDroid/build.gradle
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java

This should fix the issue related to menu items with icons in RTL locales (https://issuetracker.google.com/issues/146100178).
The new version of `appcompat` did deprecate `startActivityForResult/onActvityResult`, so a suppress warning annotation was added.
Issues specified in https://github.com/ankidroid/Anki-Android/pull/8261#pullrequestreview-622598680
And related to https://github.com/ankidroid/Anki-Android/issues/8259
Manual testing

Bump appcompat to 1.3.0-rc01.

---

README.md

Adds a newline between GPL and AGPL
Before: https://github.com/ankidroid/Anki-Android/tree/2d67ba15e7760aeabc790befecf05bc04e18feae#license
After: https://github.com/david-allison-1/Anki-Android/tree/readme-newline#license

readme: add newline between licences

---

AnkiDroid/src/main/java/com/ichi2/async/Connection.java

Fixed the deprecated NetworkInfo as it was deprecated.
Fixes #7013
By using different methods in APIs greater than or equal to 23.

Fixes #7013 Fixed deprecated NetworkInfo

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.java

Fix #8229 [Bug] {{cloze:Text}} ignores repeated words and just check first of them
Fixes  #[8229](https://github.com/ankidroid/Anki-Android/issues/8229)
In the original file, the project uses `set<String>` to save the correct answer to use for {{type::cloze::NN}} fields (refer to the `private String contentForCloze(String txt, int idx) ` function in AbstractFlashcardViewer.java). In this case, {{cloze:Text}} ignores repeated words because there cannot be duplicate elements in a set. While in the Desktop version, close is handled by:
```python
def _contentForCloze(self, txt: str, idx: int) -> str:
matches = re.findall(r"\{\{c%s::(.+?)\}\}" % idx, txt, re.DOTALL)
if not matches:
return None
def noHint(txt: str) -> str:
if "::" in txt:
return txt.split("::")[0]
return txt
matches = …
```

Fix #8229 [Bug] {{cloze:Text}} ignores repeated words and just check first of them

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/main/java/com/ichi2/ui/FixedEditText.java

Auto Focus on answer field in "type in answer" cards.
Fixes #4699
Added code to open soft keyboard on focus .
Tested on Nokia 6.1+ android 10 stock.
[Stack overflow](https://stackoverflow.com/questions/5105354/how-to-show-soft-keyboard-when-edittext-is-focused/7784904#7784904)

Fixes #4699 "Type in Answer" auto focus for answer field.

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupUnderBackupTest.java

User mentioned that the failure was confusing: it'll occur again, and this needs to be correct to stop crashes, so I've improved the documentation

Improve documentation: activityHandlesRestoreBackup

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.java
AnkiDroid/src/main/res/layout/note_editor.xml
AnkiDroid/src/main/res/values/attrs.xml
AnkiDroid/src/main/res/values/theme_black.xml
AnkiDroid/src/main/res/values/theme_dark.xml
AnkiDroid/src/main/res/values/theme_light.xml
AnkiDroid/src/main/res/values/theme_plain.xml

Added toolbar support for night mode.
Fixes #7832
- I changed the toolbar background color to light grey or dark grey depending on the theme.
- I have created a method that changes the icon color to white or black depending on the theme.
- I have changed the Tint of the existing add custom tag icon depending on the theme.

Toolbar nightmode support

---

AnkiDroid/build.gradle
AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardAppearance.java

This pull request aims to enable java 8 library desugaring.
Fixes [#7052 ](https://github.com/ankidroid/Anki-Android/issues/7052)
The change enables core library desugaring for java 8 libraries.
The changes have been tested on API 22 by adding `import java.time.*`. It is one of the libraries supported by d8 desugaring.  
I explored desugaring and dex compiler, d8 in Android Studio.
I referred to the following:
https://jakewharton.com/d8-library-desugaring/
https://blog.stylingandroid.com/d8-desugaring/
https://github.com/ankidroid/Anki-Android/issues/7052

Enable java 8 library desugaring

---

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.java
AnkiDroid/src/main/res/values/01-core.xml

Fixes #8276
With Current Spinner in add note activity user can select any deck , but
->If number of decks is very big it will be hard for user to search particular deck in spinner .
->Anki-desktop do have search decks feature.
1 Used `DeckSelectionDialog` class to implement search dialog.

search deck in NoteEditor

---

AnkiDroid/build.gradle
AnkiDroid/src/main/res/drawable-v24/ic_launcher_foreground.xml

I was struggling to tell the icons apart in my quick launch as the app name was truncated
None - I do recall an issue for this but can't find it
Extract properties to manifest and use `resValue`
This also affects the resource if not using a rounded icon
`resValue`, mostly trial and error, docs are bad: https://developer.android.com/studio/build/gradle-tips#share-custom-fields-and-resource-values-with-your-app-code

Make launcher icon red in debug mode

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java
AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.java

Removed increase new card limit when no new cards
Fixes #4759
Added a condition check to check if there are no new cards.
Tested on Nokia 6.1+ (physical) , android 10 stock version.

Fixes #4759 'Custom study: Don't show "increase new card limit" when no new cards'

---

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java

The method `getChunk()` in Collection.java, returned zero as SQL window size if the object `db` is an instance of `DatabaseChangeDecorator`. This had to be changed to the default SQL window size. 
Fixes #8421 
In the condition faced in the issue, it should return the value which is calculated considering the default SQL window size. This is because the condition that `db_name` equals to "io.requery.android.database.sqlite.SQLiteDatabase"  will not be satisfied as `db_name` doesn't exist. 

Minor refactorings and SQL window size calculation fixed

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
AnkiDroid/src/main/java/com/ichi2/libanki/Undoable.java
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerKeyboardInputTest.java
AnkiDroid/src/test/java/com/ichi2/libanki/UndoTest.java

The DismissType was extremely redundant. It was only used in switch/case. Those switch where not even exhaustive, they accepted only some specific dismiss types. I believe that we are far better without them, directly instantiating Undo and DismissTasks.
Actually, I thought I already removed it when I redid background tasks, so I was surprised to see them appearing in another PR.
As usual, the goal is to make code simpler to follow and hopefully debug. Instead of using an element of an enum, and then finding where it is used, you can directly read the undo function or the task function

NF: Remove DismissType

---

AnkiDroid/src/main/java/com/wildplot/android/parsing/Atom.java
AnkiDroid/src/main/java/com/wildplot/android/parsing/AtomTypes/FunctionXAtom.java
AnkiDroid/src/main/java/com/wildplot/android/parsing/AtomTypes/FunctionXYAtom.java
AnkiDroid/src/main/java/com/wildplot/android/parsing/AtomTypes/MathFunctionAtom.java
AnkiDroid/src/main/java/com/wildplot/android/parsing/AtomTypes/NumberAtom.java
AnkiDroid/src/main/java/com/wildplot/android/parsing/AtomTypes/VariableAtom.java
AnkiDroid/src/main/java/com/wildplot/android/parsing/AtomTypes/XVariableAtom.java
AnkiDroid/src/main/java/com/wildplot/android/parsing/AtomTypes/YVariableAtom.java
AnkiDroid/src/main/java/com/wildplot/android/parsing/Expression.java
AnkiDroid/src/main/java/com/wildplot/android/parsing/Factor.java
AnkiDroid/src/main/java/com/wildplot/android/parsing/Pow.java
AnkiDroid/src/main/java/com/wildplot/android/parsing/Term.java
AnkiDroid/src/main/java/com/wildplot/android/parsing/TopLevelParser.java
AnkiDroid/src/main/java/com/wildplot/android/rendering/BarGraph.java
AnkiDroid/src/main/java/com/wildplot/android/rendering/DrawableContainer.java
AnkiDroid/src/main/java/com/wildplot/android/rendering/LegendDrawable.java
AnkiDroid/src/main/java/com/wildplot/android/rendering/Lines.java
AnkiDroid/src/main/java/com/wildplot/android/rendering/MultiScreenPart.java
AnkiDroid/src/main/java/com/wildplot/android/rendering/PieChart.java
AnkiDroid/src/main/java/com/wildplot/android/rendering/PlotSheet.java
AnkiDroid/src/main/java/com/wildplot/android/rendering/XAxis.java
AnkiDroid/src/main/java/com/wildplot/android/rendering/XGrid.java
AnkiDroid/src/main/java/com/wildplot/android/rendering/YAxis.java
AnkiDroid/src/main/java/com/wildplot/android/rendering/YGrid.java
AnkiDroid/src/main/java/com/wildplot/android/rendering/graphics/wrapper/ColorWrap.java
AnkiDroid/src/main/java/com/wildplot/android/rendering/graphics/wrapper/FontMetricsWrap.java
AnkiDroid/src/main/java/com/wildplot/android/rendering/graphics/wrapper/GraphicsWrap.java
AnkiDroid/src/main/java/com/wildplot/android/rendering/graphics/wrapper/StrokeWrap.java

It's not worth worrying about the m variable prefix as we're not
going to edit external library code
Fixes 138/384 lint warnings
Related: #8387

Ignore Invalid field naming lint for wildplot

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
AnkiDroid/src/main/java/com/ichi2/async/SingleTaskManager.java
AnkiDroid/src/main/java/com/ichi2/async/TaskManager.java
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
AnkiDroid/src/main/java/com/ichi2/libanki/CollectionGetter.java
AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java
AnkiDroid/src/test/java/com/ichi2/async/ForegroundTaskManager.java

Currently, the biggest problem to generate test are that some code is executed in background. Either I wait until the end of the background task, which is not easy to do, or I the test in OnPostExecute. In this case, I need to actually check whether onPostExecute is executed which lead back to first problem.
Worse, as show https://github.com/ankidroid/Anki-Android/pull/6978 there is difference in background task between machines.
The trouble, according to me, is that those are not difference I actually want to consider in tests. In the example linked above, it just means on some machine the counts will takes more time to be updated than on some other machines. That's not actually a problem as long as counts gets updated.
The trouble is that if I want to do test without task actually in …

NF: Mock Task manager

---

AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
AnkiDroid/src/main/res/xml/preferences_general.xml

the prefs screen can handle SVG drawables directly in API21+
Nothing logged, was just a comment in an area was working in, and the time has come
Remove the Compat API usage, set the drawable directly
Checked day and night mode in API21 and API30 emulator on the general settings preference screen, all good
This was a nice workaround to use the SVG on lower APIs from @david-allison-1 - David you should check it
It's hard to notice all the old API workarounds in one go when bumping minSdkVersion! Possibly could use some sort of clear marking, like an annotation plus lint check or something

chore: remove pre-API21 workaround for language icon in prefs

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/java/com/ichi2/anki/Info.java
AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
AnkiDroid/src/main/java/com/ichi2/utils/ViewGroupUtils.java
AnkiDroid/src/main/res/values/10-preferences.xml
AnkiDroid/src/main/res/xml/preferences_advanced.xml

Android 8/8.1 had something terrible happen in an update, which caused the entire Reviewer UI to disappear #7369 
In order to stop the user outcry of a totally broken app I implemented a quick Layout XML based switch to software render for Android 8/8.1 in #8154 
This caused a separate user outcry because some users then had terrible scroll performance or similar with the software rendering.
Since it's clear we can't make the correct choice for all users, we need to expose the tradeoff / choice to the users as a preference, but with a safe (if low performance) default of software render for Android 8
Fixes #8160 
- add a new advanced preference "softwareRender"
- on startup, if we are Android 8/8.1 and there is no entry for "softwareRender" set, set it to true
- if "softwareRender" is …

Add Hardware render toggle for Reviewer

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.java

Add functionality to auto-focus on the `FixedEditText` field of the dialog when `Create deck` option is selected from `DeckPickerFloatingActionMenu`.
Fixes #8462 
Called `requestFocus()` method on the `FixedEditText` to get focus on that and used `setSoftInputMode()` to bring up the keyboard. 
Verified that the field is getting focused when the dialog is being opened and the keyboard is being displayed.

Set focus on 'Create deck' name field by default

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.java
AnkiDroid/src/main/java/com/ichi2/libanki/backend/DroidBackendFactory.java
AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java
AnkiDroid/src/test/java/com/ichi2/anki/InitialActivityTest.java
AnkiDroid/src/test/java/com/ichi2/testutils/BackendEmulatingOpenConflict.java
AnkiDroid/src/test/java/com/ichi2/testutils/BackendEmulatingOpenConflictTest.java

Due to the Rust DB code, we now lock the database, if two Anki clients are using the same
On startup, we didn't differentiate between DB locked and DB corrupt, which I expect would confuse users, and likely lead some to delete their databases.
Fixes #8075 
* Detect the specific exception (now possible)
* If the exception is thrown, use the "locked" dialog that I added ages ago for check datbase.
Unit tests, and on my device
* Both from a "no permission" and "normal" scenario
* Also a janky unit test to ensure that no ACRA errors are raised

Fix "AnkiDroid database problem" if database is locked 

---

AnkiDroid/src/test/java/com/ichi2/anki/BackupManagerIntegrationTest.java
AnkiDroid/src/test/java/com/ichi2/testutils/BackupManagerTestUtilities.java

This would have been useful for testing the DeckPicker, but I picked a
different strategy. It's still a useful abstraction, even though the
calling test is currently ignored.
N/A
Manually in a unit test which won't make it into the codebase

NF: Add BackupManagerTestUtilities

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java

Fixes #8481
`newCount()` is the currently displayed "new count", not the total
Quick manual test on my phone. Automated tests are blocked on this dialog currently.

fix: Not allowed to increase new cards

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
AnkiDroid/src/main/res/values/10-preferences.xml
AnkiDroid/src/main/res/xml/preferences_advanced.xml

Some users only use the 'type in answer' function occasionally (for example: checking spelling)
When we added the 'always focus type in answer' functionality, this was not a good preference for them, as the keyboard uses a lot of space.
Fixes #8424
Now, we add in a preference: "Focus ‘type in answer’".
We default this to false, as to not change user expectations
This preference does not make sense if the 'Type answer into the card'
feature is set, so disable it if we use an <input> box.
On my phone: 
* Preference is disabled if "type into card" is enabled
* Default is with no keyboard
* Otherwise, keyboard appears
https://stackoverflow.com/questions/3591901/how-to-do-opposite-of-of-preference-attribute-androiddependency

Add preference: Focus ‘type in answer’

---

AnkiDroid/build.gradle

Standard dependency update PR
- turns out the desugaring PR #8361 was using an old dep, thanks dependabot for noticing - verified the new dep will work for us (it had a requirement for a medium-high D8 version but we are already using a D8 that is newer)
- google autoservice libs **finally** went 1.0, so no more rc there :fireworks:

Dependency updates 20210407

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.java

It helps in getting deck name when custom card layout used/designed. The `{{Deck}}` or `{{Subdeck}}` not working when added from js-addons `index.js`. So, it will easier to add deck name to reviewer using JS API.
It is implemented using existing JavascriptInterface
Add following to front/back side of card in `script` tag
```
console.log(AnkiDroidJS.ankiGetDeckName());
```
- [ x ] Your code follows the style of the project (e.g. never …

Get deck name using JS API

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java

If a card auto-advances right as you were answering you can get a weird skip effect, where the card you were trying to answer for is failed, the next card senses that you were holding one of the 4 buttons and since you were just lifting your finger as the next card comes in, it is marked with that answer, and moves to the next card.
Fixes #4631 
A new function has been created with `OnTouch` listener and `ACTION_DOWN` has been used to save the current instance of card. It will ensure that the options which are chosen for a particular card, the changes will be reflected for that card itself. In the `OnClick` listener the saved card will be compared to the current card, if same only then the required actions are performed.
The work has been tested on physical device (Xiaomi redmi note5 …

[Modified]: Action buttons for cards changed to OnTouch.

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java

Slight perf improvement for tests as we don't get the `throw`
And `PackageManager packageManager = getPackageManager();` was unused
Android 11 - App still opens and sets variables

tests: Fix NullPointerException

---

AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java
AnkiDroid/src/main/java/com/ichi2/anki/services/ReminderService.java
AnkiDroid/src/test/java/com/ichi2/anki/services/ReminderServiceTest.java

ReminderService was refactored in a commit which moved `deckDueTree` outside a try..catch
https://github.com/ankidroid/Anki-Android/commit/5128cc2c756ce1434367eb58807650581f26c661#diff-eab9b1b76312c13e47b4f32c7297da450ce522c4f6d15c79e55a8a8a5c51364fR172
This caused a crash
Fixes #8264
We put it back into the try, and add a test to simulate a thrown exception when accessing the collection.
We explicitly test getSched() to target this call
Add in a helper method to CollectionHelper to allow us to simulate
getDb() failures due to closing the collection while syncing
⚠️ Unit tested only

fix crash: NullPointerException while syncing

---

AnkiDroid/src/androidTest/java/com/ichi2/anki/reviewer/PeripheralKeymapTest.java
AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioPlayer.java
AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioRecorder.java
AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioView.java
AnkiDroid/src/main/java/com/ichi2/anki/reviewer/PeripheralKeymap.java
AnkiDroid/src/test/java/com/ichi2/anki/reviewer/KeyboardShortcutIntegrationTest.java
AnkiDroid/src/test/java/com/ichi2/anki/reviewer/PeripheralKeymapTest.java

I added keyboard shortcuts to "Check Pronunciation", but they had a few issues:
* (long time) - shortcuts were on keyUp, not keyDown, this meant Shift + V did the wrong thing if `Shift` was released before `V`
* Pressing the "record" shortcut did work if playing
* Pressing the "play" shortcut did not work if recording
Fixes #7780 
* ⚠️ Shortcuts are now on KeyDown - may need `AbstractFlashcardViewer`/`Reviewer` auditing
* Record stops "Play"
* Play stops "Record"
Also: 
* Abstracted out dependencies from `AudioView` and did end-to-end tests
Unit tested and tested on my phone with keyboard

Fix "Check Pronunciation" Keyboard Shortcut usage

---

AnkiDroid/src/test/java/com/ichi2/libanki/TextCardExporterTest.java

Add unit test for TextCardExporter.
It is noteworthy that upstream does not have such a test.
Comparing outputs of TextCardExporter with expected outputs.
Passed the unit test locally.
I saw there's an ExportingTest.java within the same folder, which looks like it's trying to copy upstream's exporting tests, but the current state has separate tests for different Exporters.

Add unit test for TextCardExporter

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
AnkiDroid/src/main/res/values/02-strings.xml
AnkiDroid/src/main/res/values/03-dialogs.xml

Replaces the timebox notice with a dialog popup.
Fixes #8081.
Replace the themed toast with a material dialog.
I set the time box limit to 1 minute in preference, then opened up any deck, wait for 1 minute and answer. The dialog box shows up as expected.

Replace timebox notice with a popup

---

AnkiDroid/src/main/java/com/ichi2/preferences/IncrementerNumberRangePreference.java

Follow-up to the discussion in #8191. For input stepper elements it's more natural for the minus button to be on the left and the plus button on the right, similar to how the number line works. This is also recommended in these guidelines:
https://www.nngroup.com/articles/input-steppers/
https://material.io/components/sliders#anatomy
Flips the +/- buttons.
Tested in the emulator. 
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
<details>
<summary>For RTL languages, the buttons are still correctly switched.</summary>
</details>
I looked for relevant UI guidelines (linked above).

Flip +/- buttons in IncrementerNumberRangePreference

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.java
AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.java
AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java
AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.java
AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.java
AnkiDroid/src/main/java/com/ichi2/async/Connection.java
AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java
AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java
lint-rules/src/main/java/com/ichi2/anki/lint/IssueRegistry.java
lint-rules/src/main/java/com/ichi2/anki/lint/rules/PrintStackTraceUsage.java
lint-rules/src/main/java/com/ichi2/anki/lint/utils/Constants.java
lint-rules/src/test/java/com/ichi2/anki/lint/rules/PrintStackTraceUsageTest.java

For the "Use Timber for logging" code style rule: Use lint instead of enforcing it manually
**Welcoming**
If we're not nitting the code, it's more welcoming to new contributors, and they should want to contribute more
**Onboarding**
Shows one of our code style rules in a discoverable manner
**Feedback loop**
This reduces the feedback loop for a developer, automated feedback is much faster than manual
**Saves time**
Saves a reviewer's time picking up on a nitpick
**Automated enforcement**
Nothing slips through code reviews
Add a lint check. This also includes AnkiDroid's first "Auto-fix" lint rule
Lint only

Add lint rule: PrintStackTraceUsage

---

AnkiDroid/src/main/java/com/ichi2/utils/ExtendedFragmentFactory.java
AnkiDroid/src/test/java/com/ichi2/utils/ExtendedFragmentFactoryTest.java

- A factory class that enables extending another factory.
- will be very useful when designing modular `FragmentFactory` that can extend/chain to one another.
I have cherrypicked this from #8369, so it can be used to solve this issue #8406 and this class would allow a modular design where activities can "extend" their base `FragmentFactory` with another one, so we would have a chain of small factories.
Unit tests

feat: ExtendedFragmentFactory

---

AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnalyticsConstant.java
AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.java
AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.java

Strings used in analytics must not change. So, CI must be failed if changes are made to those.
Fixes #8287 
Added a custom annotation `@AnalyticsConstant` and fetched the fields via reflection and checked them with hardcoded fields in the unit test.
Ran the test in Android Studio.
• Working with Annotations.
• Working with Java Reflection.
• If anyone wants to learn about Parameterized test then this PR would be helpful.

Fixes #8287 Fail CI if Analytics string constants are changed

---

AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
AnkiDroid/src/main/res/values/03-dialogs.xml

If a user enters incorrect Directory path then a dialog appears with an option to reset the path to default
Fixes #8013 
This has been tested on a Real Device

NF: Adding a reset to default button for setting default directory path

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.java
AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CreateCustomStudySessionListener.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialogFactory.java
AnkiDroid/src/main/java/com/ichi2/utils/FragmentFactoryUtils.java
AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.java
AnkiDroid/src/test/java/com/ichi2/utils/FragmentFactoryUtilsTest.java

Clean `CustomStudyDialog` and refactored to use `FragmentFactory`
All commits should be NF
Fixes #8406
using `FragmentFactory`
~~**TESTS ARE DISABLED FOR `CustomStudyDialog`** I will enable them once I understand them 😅  I have to search about the fragment testing and how these tests are written~~
EDIT:
~~I have migrated `learnAheadCardsRegressionTest` to use the new FragmentFactory, but `increaseNewCardLimitRegressionTest` have some strange exceptions. I have to dig deeper to see what's wrong.~~
EDIT 2: FIXED 🥳

NF: Refactor CustomStudyDialog to use FragmentFactory

---

AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
AnkiDroid/src/main/java/com/ichi2/anki/services/BootService.java
AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.java
AnkiDroid/src/test/java/com/ichi2/anki/PreferencesTest.java

SchedV2 introduced the concept of a "rollover" time. We did read this in SchedV2, but we did not set it in the settings.
We now set this value
⚠️ This also changes the Notification Service: We now default a new day to 4AM instead of Midnight for a notification if:
* there is an error loading the "start of new day"
* "start of new day" was not explicitly set
I chose this because the preference would use the "starts of new day" value if it was set.
Fixes #6203 
* set "rollover" if the scheduler is v2
* Use "rollover" in the BootService if sched v2 is set
Replicating the logic in: https://github.com/ankitects/anki/commit/b17a0552d061af360e35e1cda48b2d228c94b66e
⚠️ This is a change which is hard to test
* minimally tested manually to ensure that it doesn't crash
* some unit tests, 
I don't …

SchedV2: Fix "Start of Day" not being set

---

AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.java

This test is important, because there are chances that constants without the annotation can be added and that may pose problem.
Used reflection to get the field without annotation and then threw a runtime exception with an appropriate message.

Added a test to check all the constants in actions class are annotated

---

AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java
AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.java

AsyncTasks in AnkiStatsTaskHandler are non-static & hold references to View objects. This can lead to potential memory leaks.
Fixes #5404 
- It replaces the strong references to view objects in AsyncTasks with WeakReferences
- Turns the extended AsyncTasks into static inner classes
- Checks if a weakly referenced object isn't null before using. Attempts to update UI only if view objects exist.
-  Tested on SAMSUNG SM-A805F API 29 (Physical Device)
- Pixel 3a XL API 27 (Emulator)
- Pixel 2 API 24 (Emulator)
No UI changes

Fixes #5404: Fix AnkiStatsTaskHandler's AsyncTasks' memory leaks & singleton pattern

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java

Before, there was a bug - when we close the app after changing the display order in Card Browser, and then reopen it again, it was getting set to the default value, it was not getting saved in the DB. Adding just one command ie getCol().flush() solved this issue.
Issue #4199 
Just added `getCol().flush()` in `CardBrowser.java` in the function `changeCardOrder()`. This saves the updated `sortType` field in the database.
1. From the homepage, go to Card Browser.
2. Go to Change Display Order from Options.
3. Select any order.
4. Close the app and remove it from Android History.
5. Reopen the app and go to Card Browser again.
6. The order selected will be seen.
Just find out where the error is originating either by using debugging statements (`Timber`) or anything and then keep using `Ctrl + …

Display Order of Card Browser corrected

---

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java

Avoid possible strange behaviors in `MultimediaEditFieldActvity` deriving from missing calls to Android lifecycle callbacks on `super`. 
Added the missing call to `super#onRequestPermissionResult()` in `MultimediaEditFieldActivity`.

Missing call to super in MultimediaEditFieldActivity#onRequestPermissionResult

---

AnkiDroid/src/test/java/com/ichi2/utils/JSONObjectTest.java

Added a test to check whether a new object is returned by the `deepClone()` method of `JSONObject` class. The test fails if the clone and original object point to the same memory location.

Added test to ensure deepClone() returns a new instance

---

AnkiDroid/src/main/res/layout/homescreen.xml

On Samsung devices, when AnkiDroid is launched for the first time, the splash screen with the AnkiDroid logo doesn't disappear and stays in the background of DeckPicker
Fixes #8227 
For homescreen.xml, copy the xlarge version's android:background attribute placement to the normal version (as an attribute of the root, ClosableDrawerLayout View)
Tested on:
- Samsung Galaxy A80 API 30 (Physical Device) - Solves the issue
- Pixel 4 API 27 (Emulator) - Doesn't change previous, correct behavior
I would love to have any contributors with Samsung devices confirm that this solves the issue!

Don't persist Anki logo in background on startup

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.java
AnkiDroid/src/main/java/com/ichi2/anki/MaterialEditTextDialog.java

Improve dialog usage by setting default focus on EditText
Fixes #8464 
Used utility function for focusing on EditText and opening keyboard when dialog is opened for 'Create deck', 'Rename deck' and 'Create subdeck'.
Verified that the functionality is working.

Improve dialog usage by setting default focus on EditText

---

AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.java

Hard to reproduce this one locally but hopefully this helps, it is our top flake I think in unit test runs
Related #8064 
Just add sleeps to the method as it does things likely asynchronous
This one was a little frustrating. It shows up in CI as noted in related issue and I see it locally *sometimes* but after adding the sleeps I never saw it again either on this branch with these sleeps or (when I attempted to negative test it) when I switched back to main branch and tried to reproduce again.
So results are very inconclusive, however adding sleeps can't really hurt.
Tests and asynchronous things are not delicious together like peanut butter and chocolate.

Attempt to de-flake "regression_test_preview" with sleeps

---

AnkiDroid/src/main/java/com/ichi2/anki/AnkiFont.java
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.java
AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java
AnkiDroid/src/main/java/com/ichi2/anki/UIUtils.java
AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronounciationActivity.java
AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/TranslationActivity.java
AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicTextFieldController.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java
AnkiDroid/src/main/java/com/ichi2/preferences/CustomDialogPreference.java
lint-rules/src/main/java/com/ichi2/anki/lint/IssueRegistry.java
lint-rules/src/main/java/com/ichi2/anki/lint/rules/DirectToastMakeTextUsage.java
lint-rules/src/test/java/com/ichi2/anki/lint/rules/DirectToastMakeTextUsageTest.java

Spare code review time and make the codebase cleaner by suggesting people to use `UIUtils.showThemedToast` instead of the `Toast.makeText`.
Fixes https://github.com/ankidroid/Anki-Android/issues/8576
Implement a custom lint rule.
Unit tests are provided together with the implementation. Also,the lint report has been generated and the IDE provides visual feedback on the working rule.
https://developer.android.com/studio/write/lint
https://proandroiddev.com/implementing-your-first-android-lint-rule-6e572383b292
https://proandroiddev.com/testing-your-first-android-lint-rule-bb78c1f2d2bd

Lint: Disallow direct usages of Toast#makeText

---

AnkiDroid/build.gradle
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/LocaleSelectionDialog.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TagsDialog.java
AnkiDroid/src/main/java/com/ichi2/ui/ButtonItemAdapter.java

Previous `getAdapterPosition()` API was split to be non-ambiguous
`getBindingAdapterPosition()` seems like the correct option to use between
the two new APIs, as the listener appears to be viewed from the adapter context,
not the RecyclerView context (where `getAbsoluteAdapterPosition()` would be correct)
Local `./gradlew jacocoTestReport` plus the API usage was all in card browser saved searches dialog so I made a couple of saved searches then I made sure when I selected them for use or for delete that the correct search was used (or deleted)
The war against bitrot can be won. Also dependabot really helps in that war.

Bump recyclerview to 1.2.0, forward-port deprecated APIs

---

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java

Its usage is discouraged in the Python, and we save a lot of effort by not converting legacy code
We only had one usage. This code no longer exists in Anki's pylib
https://github.com/ankitects/anki/blob/1cc63f9267eb3facc514fab827d4146aaf14d3bb/pylib/anki/decks.py#L51
⚠️  Untested

Deprecate getCol().getDecks().getDecks()

---

AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.java

From Anki commit https://github.com/ankitects/anki/commit/94d369db18c2a6ac3b0614498d8abcc7db538633
I'm tackling converting `Decks.java` to handle the V16 schema. I've ported the decks class, and now I'm looking to consolidate our code (which has been optimised) and the new Python code which calls the backend.
The more code that I make identical to the "new" python, the less code that needs to go into the commit.
Unit tested

confForDid: use default on invalid configuration

---

AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
AnkiDroid/src/main/java/com/ichi2/libanki/backend/DroidBackend.java

The more methods that we make equivalent to the python at the commit of `anki` that we're using, the more seamless that the conversion is.
https://github.com/ankitects/anki/commit/004cc2b5f8260c31b2177b4e544f1554e08f7a33
https://github.com/ankidroid/Anki-Android/blob/d7057d3c979086f2c5712156ac6c564a57cda9cd/AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java#L817-L820
Untested

Decks: refactor restoreToDefault for Rust

---

AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java

Before this change, we performed this check on `onActivityResult`.
This was bad, as we had :
* onCreate -> startCollectionLoading -> onCollectionLoaded
* onActivityResult -> closeCollection -> crash
There was also a bug that `mOldColPath` was not saved via `onSaveInstanceState`, this meant "Don't Keep Activities" would cause accessing the preferences to always reopen the collection
Fixes #8422
Instead, open the Deck Picker immediately after the "advanced" Window has been closed, if the collection path has changed
On-device testing with "Don't keep Activities"

fix: Open DeckPicker if collection path changes

---

AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java

Fixes #8388.
The same string `fieldName` should be used independently of whether there is an exception thrown

Ensures forbidden symbols are removed from new field names

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java
AnkiDroid/src/test/java/com/ichi2/anki/InitialActivityTest.java

Deck Picker crashed on open
Fixes #8610
Move the call after `onCreate`, add test
Regression test: tested DeckPicker open with both permissions and no permissions

Fix DeckPicker crashing showing "analytics opt in"

---

AnkiDroid/jacoco.gradle

+ Enables jacoco reports to be opened automatically after a successful task.
+ Print the report `index.html` location
**NOTE:** for Linux users `linux-html-cmd` proproty must be defined in `local.properties` file.
`open-report` argument flag must be provided for this feature to work:
```
./gradlew jacocoAndroidTestReport -Popen-report
```
Fixes #8240
Manually on macOS

feat: Enable jacoco reports to be opened

---

.github/workflows/lint.yml
.github/workflows/publish.yml
.github/workflows/stale.yml
.github/workflows/tests_emulator.yml
.github/workflows/tests_unit.yml
AnkiDroid/build.gradle

Standard dependency updates PR - each commit has notes
ACRA was tested by me locally (as part of #8629 I checked 5.7.0) and the workflow changes can't be verified until we see them run here...

Dependency updates 20210415

---

AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnkiDroidCrashReportDialog.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java

If the user canceled, they should not be limited in the future
Fixes #8379
Supercedes #8432
- the limiter should have the best source of info for rate limiting, not an internal static timestamp thing
- the limiter stores report timestamps when generated, not approved though, so clear on cancel
- I snuck in some access limitation changes to de-lint AndroidStudio in the area
Currently doing something distasteful in order to access the limiter data but it I have positive confirmation from upstream that the next version of ACRA allows it with no reflection:
https://github.com/ACRA/acra/issues/843#issuecomment-820784697
```java
long mostRecentTimestamp = LimiterData.load(this).getReportMetadata().stream()
.filter(report -> report.getExceptionClass().equals(UserSubmittedException.class.getName() …
```

Clear ACRA on cancel, use ACRA data for rate limit

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
lint-rules/src/main/java/com/ichi2/anki/lint/IssueRegistry.java
lint-rules/src/main/java/com/ichi2/anki/lint/rules/DirectSnackbarMakeUsage.java
lint-rules/src/test/java/com/ichi2/anki/lint/rules/DirectSnackbarMakeUsageTest.java

The methods to use Snackbars must be from UIUtils class rather than using them directly (Snackbar.make(...)).
None
Added a lint rule to check this. And, removed the currently used Snackbar.make(....).
This screenshot is fix for the existing lint errors (related to this PR).
Unit tests passing and `gradlew lintRelease` successful.

Lint: Lint rule for use of UIUtils.showSnackbar instead of Snackbar.make

---

AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.java

ensure that mTextView is not null
After installing a new version of ankidroid from master and syncing, I got the message
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference
at com.ichi2.anki.stats.AnkiStatsTaskHandler$DeckPreviewStatistics.onPostExecute(AnkiStatsTaskHandler.java:275)
at com.ichi2.anki.stats.AnkiStatsTaskHandler$DeckPreviewStatistics.onPostExecute(AnkiStatsTaskHandler.java:220)
at android.os.AsyncTask.finish(AsyncTask.java:755)
at android.os.AsyncTask.access$900(AsyncTask.java:192)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:237)
at …
```

Repair a crash on tablet

---

AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
AnkiDroid/src/test/java/com/ichi2/async/AbstractCollectionTaskTest.java
AnkiDroid/src/test/java/com/ichi2/async/CollectionTaskSearchCardsTest.java

Main issue: we weren't duplicating the list, leading to prefetched cards bring added twice
The other issue was an off-by-one error in the count of cards to pre render. This didn't matter too much, but we returned one more than was requested
Fixes #8547
Clone the list, and use the correct comparison
Unit tested and tested on-device

Fix: Duplicate cards shown in Card Browser

---

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/TranslationActivity.java
AnkiDroid/src/main/res/layout/activity_translation.xml

convert from `ProgressDialog` to `StyledProgressDialog`
Fixes #5020
Move to `com.afollestad.materialdialogs.MaterialDialog`.
Manually in the emulator

NF: Progress dialog deprecation

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.java
AnkiDroid/src/test/java/com/ichi2/anki/ReviewerKeyboardInputTest.java

Fixing gestures with answer buttons not working on the latest alpha release.
Fixes #8527 
Fixes #8572.
Completely removing the usage of `performClickWithAction`, opting to `answerCard`, since only touching actions on buttons are registered now.
Tested on my physical device.

Fixing gestures with answer buttons not working

---

.github/workflows/lint.yml
AnkiDroid/build.gradle
AnkiDroid/jacoco.gradle
AnkiDroid/src/amazon/AndroidManifest.xml
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java
AnkiDroid/src/main/java/com/ichi2/utils/CheckCameraPermission.java
tools/parallel-package-release.sh
tools/release.sh

Different flavors added for Amazon App store and Google Play store (we cannot use default here). And, I tried to hide the camera related options in amazon flavor.
Fixes #8151
Added the flavors in gradle. Created a class to get all the permissions to find out whether camera permission is present in manifest or not. If not present. hide the camera related options from menu's.
4 Build variants are generated now (amazonDebug, amazonRelease, playDebug, playRelease)
Tested on real device (Redmi Note 7S and API 29).

Fixes #8151 Build flavors for Amazon Appstore and Google Playstore

---

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronounciationActivity.java
AnkiDroid/src/main/res/layout/activity_load_pronounciation.xml
AnkiDroid/src/main/res/layout/activity_translation.xml
AnkiDroid/src/main/res/layout/progress_bar_layout.xml

This is a continuation of #8633
convert from `ProgressDialog` to an embedded `ProgressBar` view.
Fixes #5020
Manually in the emulator

NF: Progress dialog deprecation (Part 2)

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.java
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.java
AnkiDroid/src/main/res/menu/deck_picker_dialog_menu.xml
AnkiDroid/src/main/res/values/01-core.xml
AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CreateDeckDialogTest.java

With Current Spinner in add note activity user can select any deck , but
1 if user don't found particular deck in list then user have to go back to main activity to create that deck and then user have to create note and select that particular deck , it is lengthy process.
We can implement add new create deck function at top left corner of `DeckSelectionDialog` box,so that if any user don't found deck , then user can directly create new deck from there without aborting whole process to create new deck.
Fixes #8275 
- [✔️ ] Extracted Add Deck Dialog from DeckPicker class to separate CreateDeckDialog class,
- [✔️] Added add deck function to DeckSelection class in NoteEditor activity,
- [✔️] Removed Unused Resource `R.string.create`
1 Add Deck Video
2 Add Sub Deck Video

Implement Create New Deck Function In Add Note Activity

---

AnkiDroid/build.gradle

This finishes the migration from jcenter for us after sqlite-android ingested my jitpack work - we can use the "official" repository again, instead of jitpack-test-fork of the repo
Related #8632 
Local `./gradlew clean jacocoTestReport --rerun-tasks` agains an API30 emulator
jitpack is pretty easy to work with even if you have an NDK package...

Dependency updates 20210422

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java

From #8468. fixed in prep for 2.15
> ## Purpose / Description
> App should not crash on long pressing an already selected card in the card browser.
>  
> ## Fixes
> Fixes #8467 
> 
> ## Approach
> `getChildAt()` method of `ListView` is wrongly used since it concerns the visible items and not the complete list of items. The approach followed to fix this is to make use of the `mCheckedCards` list. While iterating through the cards to select them, the `mCheckedCards` list is being updated and `onSelectionToggle()`  is being called to update the checked state of the list items.
> 
> ## How Has This Been Tested?
> 
> Verified that the mentioned issue does not occur after this change.
> 
> ## Checklist
> 
> - [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
> - …

Fix: Prevent crash on long pressing at end of card browser

---

AnkiDroid/src/main/res/layout/deck_item.xml
AnkiDroid/src/main/res/values/01-core.xml
AnkiDroid/src/main/res/values/03-dialogs.xml

There is an accessibility problem, which I believe to be a problem related to unexpected behaviour, so this is a bad fix.
Clicking on the counts in the deck picker has an action, which I find surprising. There is no way to know what clicking will do, and it should be described for accessibility. I believe to be honest that it should actually be removed and if options are actually that useful, a more natural way to get to them should be used.
Is there a way to know the number of deck option page opened in ankidroid on small screen ? I.e. the number of cases where it's opened in it's own page, and not only because it's a mandatory step up to the reviewer?

Counts picker

---

AnkiDroid/src/main/res/xml/cram_deck_options.xml
AnkiDroid/src/main/res/xml/deck_options.xml
AnkiDroid/src/main/res/xml/preferences_reviewing.xml

Implementing  com.ichi2.preferences.IncrementerNumberRangePreference instead of com.ichi2.preferences.NumberRangePreference for Preferences (preferences_reviewing.xml), DeckOptions (deck_options.xml) and FilteredDeckOptions (cram_deck_options.xml)
There are some inconsistencies of input fields. For small distances between min and max the instance of com.ichi2.preferences.NumberRangePreference is useful
Fixes #8647
I tested it with the emulator and made changes via the IncrementerNumberRangePreference

Implementing instances of com.ichi2.preferences.IncrementerNumberRangePreference

---

.github/workflows/lint.yml

The conversion to variants in #8151 meant AnkiDroid did not have a valid
lintRelease target anymore so it was not running in CI as expected
Fixes #8669`
Using the variant-specific name makes it work, and splitting the checks into
specific ones for each sub-module should make it obvious in the future if any
further variant-related work happens
Run `./gradlew lintRelease` on the command line locally and see it does not work for AnkiDroid but `:api:lintRelease` is good
Run `./gradlew lintPlayRelease` to reference new AnkiDroid variant name, see it does work
Run `./gradlew :api:lintRelease :AnkiDroid:lintPlayRelease` and see both expected checks run
Open AbstractFlashcardViewer and specifically remove suppression of non constant ids, see it fail locally
Now I'm pushing that up (will remove it …

Run module-specific / variant-specific lint checks

---

AnkiDroid/src/test/java/com/ichi2/anki/stats/AnkiStatsTaskHandlerTest.java

Add regression testing to issue #8626.
Fixes #8631.
An unit test was written with RobolectricRunner, calling AnkiStatsTaskHandler.createReviewSummaryStatistics() method.
The Collection parameter was mocked to return null on Collection.getDb().
Checked out commit 4809c77a4, than wrote the test. When it started failing, checked out master on most recent commit and verified it is now passing.

Add Statistics regression test to #8626

---

AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.java
AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/AsyncDialogFragment.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ConfirmationDialog.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerBackupNoSpaceLeftDialog.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerConfirmDeleteDeckDialog.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerExportCompleteDialog.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerNoSpaceLeftDialog.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DialogHandler.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportDialog.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SimpleMessageDialog.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.java
AnkiDroid/src/main/java/com/ichi2/anki/exception/ConfirmModSchemaException.java
AnkiDroid/src/main/java/com/ichi2/anki/exception/StorageAccessException.java
AnkiDroid/src/main/java/com/ichi2/anki/exception/UnknownHttpResponseException.java
AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckDropDownAdapter.java
AnkiDroid/src/main/java/com/ichi2/anki/widgets/PopupMenuWithIcons.java
AnkiDroid/src/main/java/com/ichi2/async/CollectionLoader.java
AnkiDroid/src/main/java/com/ichi2/compat/customtabs/ServiceConnection.java
AnkiDroid/src/main/java/com/ichi2/compat/customtabs/ServiceConnectionCallback.java
AnkiDroid/src/main/java/com/ichi2/utils/VersionUtils.java

Hey @timrae :-) - we've gotten fairly good at automated lint checks and it's helping us automate things that normally take time during reviews for new contributors, one of those is copyright headers. Before we can enable a copyright header check, we need to add headers for existing files. I added them for you for the files that were git attributed to you - can you approve this?

NF: add timrae copyrights

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java

When the app would start without the Storage Permission, three predictable StorageAccessExceptions would occur in the following methods in DeckPicker:
- ```onResume()```
- ```onPrepareOptionsMenu()```
- ```onCreateOptionsMenu()``` -> ```displaySyncBadge()```
Fixes #8618 
In DeckPicker, we can simply rely on ```colIsOpen()``` to check if Collection is initialized instead of using ```getColSafe()```. ```getColSafe()``` uses ```colIsOpen()``` to check if Collection is initialized, if not, it attempts to lazily initialize it. This step is not required in DeckPicker since DeckPicker's ```handleStartup()``` is responsible for initializing Collection.
More importantly, ```getColSafe()``` throws a ```StorageAccessException``` if the app doesn't have write access to the AnkiDroid directory. Hence, …

Fixes #8618: Add colIsOpen() checks in DeckPicker before executing dependent tasks

---

AnkiDroid/src/main/java/com/ichi2/anim/ActivityTransitionAnimation.java
AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java

The old method of passing information to / starting / receiving results from one Activity to/from another Activity is deprecated in general, here we start refactoring the code to use the new androidx.activity APIs for such communication
Fixes (only partially) https://github.com/ankidroid/Anki-Android/issues/8602
Each `startActivityForResult` and corresponding case in `onActivityResult` is refactored to use the new API.
This PR introduce complementary methods for those to start an activity in `AnkiActivity` to instead "launch" it through an `ActivityResultLauncher`, configuring it with the right transitions and animations. This base methods are then used in `CardBrowser` to manage the communication with other Activities from which a result is expected.
In order to be sure that the style …

Feat: Use androidx activity result api in AnkiActivity

---

AnkiDroid/src/main/java/com/ichi2/async/ProgressSenderAndCancelListener.java
AnkiDroid/src/main/java/com/ichi2/async/SingleTaskManager.java
AnkiDroid/src/main/java/com/ichi2/async/TaskListener.java
AnkiDroid/src/main/java/com/ichi2/async/TaskListenerWithContext.java
AnkiDroid/src/main/java/com/ichi2/async/TaskManager.java
AnkiDroid/src/main/java/com/ichi2/libanki/StdModels.java
AnkiDroid/src/main/java/com/ichi2/libanki/UndoAction.java
AnkiDroid/src/main/java/com/ichi2/libanki/WrongId.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/CardQueue.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckTreeNode.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/LrnCard.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/LrnCardQueue.java
AnkiDroid/src/main/java/com/ichi2/libanki/sched/SimpleCardQueue.java
AnkiDroid/src/main/java/com/ichi2/libanki/template/EmptyNode.java
AnkiDroid/src/main/java/com/ichi2/libanki/template/NegatedConditional.java
AnkiDroid/src/main/java/com/ichi2/libanki/template/ParsedNode.java
AnkiDroid/src/main/java/com/ichi2/libanki/template/ParsedNodes.java
AnkiDroid/src/main/java/com/ichi2/libanki/template/Replacement.java
AnkiDroid/src/main/java/com/ichi2/libanki/template/TemplateError.java
AnkiDroid/src/main/java/com/ichi2/libanki/template/TemplateFilters.java
AnkiDroid/src/main/java/com/ichi2/libanki/template/Text.java
AnkiDroid/src/main/java/com/ichi2/libanki/template/Tokenizer.java
AnkiDroid/src/main/java/com/ichi2/utils/BooleanGetter.java
AnkiDroid/src/main/java/com/ichi2/utils/CardGetter.java
AnkiDroid/src/main/java/com/ichi2/utils/DeckComparator.java
AnkiDroid/src/main/java/com/ichi2/utils/DeckNameComparator.java
AnkiDroid/src/main/java/com/ichi2/utils/NamedJSONComparator.java
AnkiDroid/src/main/java/com/ichi2/utils/PairWithBoolean.java
AnkiDroid/src/main/java/com/ichi2/utils/PairWithCard.java
AnkiDroid/src/main/java/com/ichi2/utils/Triple.java

Some documents listed in #8659 under my name are not actually from me. Indeed, it contains classes that I just moved to
other classes. Original author should be found.
While I technically have copyright over porting Rust's Nom usage in anki to java, it's strange thing to write I'm
copyright holder here

NF: add copyright header for Arthur Milchior with year

---

AnkiDroid/build.gradle
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
AnkiDroid/src/main/java/com/ichi2/libanki/DB.java

This is an experiment. It should not have functional regressions but it may have performance regressions.
Attempting to shrink the final APK for 2.15
Related #8473 
Switches away from requery/sqlite-android dependency and relies on framework sqlite
That shaves almost exactly 1MB from the APK at the cost of unknown performance changes in API21+ (used to be important in Android 2/3/4 days but may not be now...)
Just basic click around - seems to work but @Arthur-Milchior I think is the best stress test of whether this works or not. I'll post a testable APK link in a comment.
The Android CursorWindow has been 2MB forever (I checked).

Use framework / built-in sqlite implementation

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java

Fixes #8466 hopefully (hard to tell since I can't reproduce)
I went over 3e79836 line by line in cardbrowser to check what could have caused the regression.
Here is the full story of the investigation:
Previously, `doInBackgroundCheckCardSelection` took an array of objects. It was called with an array of two elements, and never used the second one. So I intended to remove the second one. Actually, I removed the first one. See https://github.com/ankidroid/Anki-Android/commit/3e7983670370141b6dc2e1ab3d7a4036c0585def#r50222793
I'm all for atomic commits and hate that this touches 1700+ lines of code. Not that I could have done it otherwise, it was a huge pain.
I'll plainly admit, David, that you were right, this commit and PR introduced bug. For some reason it only got notice on some …

Ensure that CheckCardSelection gets only checked cards

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialogFactory.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialogListener.java
AnkiDroid/src/main/java/com/ichi2/utils/ExtendedFragmentFactory.java
AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.java
AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogTest.java
AnkiDroid/src/test/java/com/ichi2/testutils/ParametersUtils.java

#8341 introduced a bug in CustomStudyDialog, it removed the setter for the listener (which is great, since we can't rely on it to be there after a configuration change) but it assumed the fact that getActivity() would return an activity that does implement the interface.
In the case of `CustomStudyDialog`, the interface was implemented on the dialog, not on its hosing activity `StudyOptionsActivity`.
Fixes #8487
By using `ExtendedFragmentFactory`, it was an easy task.
Manually + Unit Tests

Refactor TagsDialog to use FactoryFragment

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java

It was used in a single place, not always needed to initialize it, and its strange that the same listener may be used
for multiple actions while having a state

NF: remove mDismissCardHandler

---

AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java

Checking whether it's one specific class do not seems very elegant.
Ideally, having a method `boolean RequiresTheCollection()` would be ideal. However, I like the simplicity of having a
single method, as it will allow to use lambda in future commit. This keeps the code simple and still cleaner

NF: introduce TaskWithoutCol to simplify code

---

AnkiDroid/src/main/java/com/ichi2/anki/MaterialEditTextDialog.java
AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.java
AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.java

UX - saves a tap on the edit text
Related #8464
On my Android 11

[UX] Material Text Dialogs: Show keyboard when opened

---

AnkiDroid/src/test/java/com/ichi2/async/ForegroundTaskManager.java

I realized for a test that it may be easier to get to execute a task against a listener without involving the whole
manager process. This ensure this feature will be available to any tester when needed even if I don't use it know
That works with the general principles that, as long as a dev don't work on Async Task directly, then they will only see that they need to provide a task, a listener, and can ignore the entire remaining of the framework

NF: Allow to execute task and listener without manager

---

AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.java
AnkiDroid/src/main/res/xml/cram_deck_options.xml

Sched V2 should not display custom study steps on filtered decks
Fixes #8641
Had problems with `getPreferenceScreen().removePreference`
so went with assigning a key to the category and using that
The methods fail on nulls, so null checking is sadly necessary

fixes: no custom study steps on schedv2

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsArrayAdapter.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.java
AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogTest.java

I have reverted to the old way of handling `mFilteredList`.
Fixes #8762
`mFilteredList` will be only set when there is a search filter active, otherwise, it's null and the adapter will use the original full list.
Emulator

fix: added tag doesn't reflect in adapter

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
AnkiDroid/src/main/java/com/ichi2/async/SingleTaskManager.java
AnkiDroid/src/main/java/com/ichi2/async/TaskManager.java
AnkiDroid/src/test/java/com/ichi2/async/AbstractCollectionTaskTest.java
AnkiDroid/src/test/java/com/ichi2/async/ForegroundTaskManager.java
AnkiDroid/src/test/java/com/ichi2/libanki/CheckMediaTest.java

The typing of background tasks element is complex. I sincerely believe that a generic type system is far better than dealing with `Object[]`as we often did last year. However, this led me to think more about it, and I guess that `? extends FOO` has less parameters than introducing extra type variable. So here it is, a version of `CollectionTask` and `launchCollectionTask` with only two parameters.
If this get merged, I'll then remove `Background` suffix from variable type. But this will wait so that this PR remains simple

Remove listener-related generic type

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.java
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.java
AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckDropDownAdapter.java
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java
AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.java

With Current Spinner in card browser,note editor, statistics activity, user can select any deck, but
->If number of decks is very big it will be hard for the user to search a particular deck in the spinner.
->Anki-desktop does have search decks feature in browser activity.
- [✔️ ] Used `DeckSelectionDialog` class to implement search deck dialog In CardBrowser ,Statistics And NoteEditor.
- [✔️] Extracted spinner code from Card Browser, NoteEditor, And Statistics

Card Browser, NoteEditor And Statistics : Improve "Search Deck" UX 

---

AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java
AnkiDroid/src/main/java/com/ichi2/libanki/backend/DroidBackend.java
AnkiDroid/src/main/java/com/ichi2/libanki/backend/JavaDroidBackend.java
AnkiDroid/src/main/java/com/ichi2/libanki/backend/RustDroidBackend.java
AnkiDroid/src/main/res/values/10-preferences.xml
AnkiDroid/src/main/res/xml/preferences_advanced.xml
AnkiDroid/src/test/java/com/ichi2/libanki/StorageTest.java
AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.java

A new era - the V2 scheduler is stable in Anki Desktop
Fixes #8162 
* Use a new string
* Upgrade to v2
* Upgrade to new timezone code
* Unit tests pass
* Tested on my device

Default sched ver to v2 and use new timezone code

---

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
AnkiDroid/src/main/res/layout/card_template_editor_item.xml

* I feel a monospace font is more legible for code
* Adds default text in the android designer
* Fixes accessibility (see commit message)

UX: Card Template Editor: monospace and accessibility

---

AnkiDroid/build.gradle
build.gradle
lint-rules/build.gradle

- remove jcenter (deprecated, thankfully no longer needed)
- remove r8 workaround for previous issue, AGP 4.2.0 has fix built-in
- bump Triple-T / Play Publisher plugin to match AGP 4.2.0
- remove java 1_8 source/target compat annotation, it is default in 4.2
- add noinspection for commons-compress - has to wait until API26
- lint to 27.2.0
- fragment to 1.2.3
No link, but I want to get these in before branch cut. None of them should affect release-2.15 but it will help future cherry-picks to have the build toolchain up to date before the branch peels off
The Play Publisher Plugin is probably the most problematic as it's got different branches for different android gradle plugin versions, but I've been working through that for a while so I already was aware.
The AGP42 transition is nice …

build: android-gradle-plugin 4.2.0 + others

---

AnkiDroid/jacoco.gradle

Our coverage reports appear to have been busted since the implementation of #8427 as they were referencing incorrect class directories
Reference correct directories
I don't have a regression for it, but I bisected to find it - visual inspection shows it's working
We can completely break coverage checks and not know it - I tried to get Jacoco to error if coverage was below what we have and utterly failed - should be this https://docs.gradle.org/current/userguide/jacoco_plugin.html#sec:jacoco_report_violation_rules

Fix jacoco reports w/correct per-flavor class dirs

---

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.java

fixes #8815
Obviously, that was not an order.
I don't know how to make a regression test, as it requires to know how to make the sorting fail. Not obvious. I tried by looking at the code https://android.googlesource.com/platform/libcore/+/fe39951/luni/src/main/java/java/util/Arrays.java and the implementation https://android.googlesource.com/platform/libcore/+/android-6.0.1_r21/luni/src/main/java/java/util/DualPivotQuicksort.java
Sadly I can't even find the error message we got, so maybe it's not even the right implementation.
I can at most say that a sequences of a few ALL_DECK_ID do not suffices to fail. Even a sequence of size 35 (there is a threshold at size 32. Before size 32, it uses a bubble sort!)
By the way, this is wrong any way, because it do not consider that "::" has special …

Ensure SelectableDeck's order is consistent

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java

The first stack trace of #8821 can only be obtained if there is no item to display and if the first item to display is item 0.
Fixes #8821 
I have no idea how this can occur, it seems not to have any meaning to scroll to display 0 elements. But if the browser is closed, I guess it's technically true. Normally, in ths case, the scrolling should not have been triggered in the first place, but if we need to deal with it, this commit accept this nonsense.

Consider scrolling with 0 cards.

---

AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.java
AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java

Multiple functions did not check that `names()` could return null. So I add it. The behavior is the same than on empty jsonArray.
Fixes #8839. This issue should never have occurred, as it's impossible to get no deck at all, but somehow it occured. I've no idea what was going on here. The best I can imagine is someone having fun with the database directly, and checking what would occur if the default deck is removed manually. It's something I could have imagined doing myself just to check.
At least, I hope it's the correct explanation, because the other one would be that someone was able to remove the default deck, which is theoretically impossible, and in this case it's a slightly bigger problem on our side. Sadly, until we find out how to reproduce it, there is nothing I can do.
There is …

Can open collection with no deck

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java

This ensure that we don't get 5 to 10 exception log in acra every hours (with beta users) and allow to get more specific information.
Logging is interesting, but it's really not a bug. We were note satisfying the promise by `onScroll`, its javadoc mention explicitly the case where there is 0 item visible and we didn't take this into account. So this mostly serve us to gather information about why sometime we get the information that there is nothing to display while we have card

More specific exception for useless scroll call

---

AnkiDroid/src/main/java/com/ichi2/preferences/IncrementerNumberRangePreference.java
AnkiDroid/src/main/java/com/ichi2/preferences/NumberRangePreference.java

Fixes #8843
_an error appear when you try to increment limit in deck option from null to sth
added a try catch and put default value 0 for value in "IncrementerNumberRangePreference.updateEditText"
i tried manually
help of a friend

NumberFormatException fixed

---

AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.java

When querying from `revlog` for weekly breakdown in statistics page, the weekday ordinal would always return 0 and so all logs would be shown for Sunday
Fixes #8853
Added a cast in the query in `Stats::calculateWeeklyBreakdown` for weekday

Fixed problem with aggregated data to one day in weeklyBreakdown in stats page

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/java/com/ichi2/async/Connection.java
AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java

Sync `onPostExecute` in `DeckPicker` expect `result[0]` to be Long, but it is provided with Object[]
Fixes #8885
Following the call chain and looking for `Long` and `Object[]` I found that this is the exception trace.
https://github.com/ankidroid/Anki-Android/blob/60476b8331c63f42050d0142342b5c410aaeb11d/AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java#L182-L186
Here the `new Object[] {diff}` is wrapped yet again in another `Object[]`, `data.result = new Object[]{ret.second};`
https://github.com/ankidroid/Anki-Android/blob/60476b8331c63f42050d0142342b5c410aaeb11d/AnkiDroid/src/main/java/com/ichi2/async/Connection.java#L371-L382
And in `DeckPicker` we expect it to be of type `Long`, so we get `Object[] cannot be cast to Long` …

Fix: #8885

---

AnkiDroid/src/main/java/com/ichi2/async/Connection.java

Crash reports from network connection errors are just clutter for us, they are not actionable and we already handle them for the user. This is just shrinking quantity of exception reports in crash database
Fixes #8820 (again)
Ignore non-actionable messages
Untested. But the code path is well tested
I learned nothing from this issue, but that's the way it is sometimes. I learned about 4 other things in the last half hour from other issues so it evens out.

Ignore "connection abort" type errors from network stack

---

AnkiDroid/src/main/java/com/ichi2/utils/JSON.java
AnkiDroid/src/main/java/com/ichi2/utils/JSONArray.java
AnkiDroid/src/main/java/com/ichi2/utils/JSONObject.java
AnkiDroid/src/test/java/com/ichi2/utils/JSONArrayTest.java
AnkiDroid/src/test/java/com/ichi2/utils/JSONObjectTest.java

This port the code from
https://android.googlesource.com/platform/dalvik/+/f2f7880a40aed1c8d9c27db49226e47396556aac/libcore/json/src/test/java/org/json
It adapts it by using junit, `@Test`, changing the deprecated test of equality of double (it adds explicitly the delta=0).
Since we'll move away from org.json in order to use fastxml.jackson, this is an extra security to ensure that we do not
change the behavior while we increase the speed.
This lead to discover that some code throwed RuntimeException instead of JSONException, this is corrected.
Some code from upstream are copied in our classes in order to ensure that all elements of the JSON tree are our kind of JSONObject

NF: copy android's json tests

---

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioClipFieldController.java

App crashes when audio file is selected whose file name is invalid
Fixes #8881 
I have created a method that checks the filename is valid or not
Not tested on a physical device but tested by providing invalid inputs in the filename string.

Fixed crash on file selection

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java

Fix NullPointerException in DeckPicker.
Fixes #8886 
Select the default deck if the selected deck is null.

Fix NullPointerException in DeckPicker

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.java
AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java

There was a little snarl of issues related to getting the deck spinner set to the correct deck if it was adding a new card or editing an existing card.
Adding a new card case was attempted in #8849 and fixed part of the issue but made another part not work with #8855 - this time both are working
Fixes #8855
Very very carefully trace the code while checking both cases, throwing stacks in DeckSpinnerSelection every time it was called to set the spinner position so I could see who was calling it and with what arguments
1) Make sure spinner is correct for current selected deck
Open Deck list and select any deck
Click + to add a note, check deck spinner position
Repeat with other decks to make sure it stays in sync with current selected deck
2) Make sure spinner is correct for cards (including …

De-lint DeckSpinnerSelection and select correct deck on add note or edit card

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.java

CardBrowser was crashing because of an order-of-operations race between initial layout and onCollectionLoaded initializing necessary data
Fixes #8882
Examined other areas that made the same last-call-before-crash and they were protecting access to the unitialized variable with a guard for collection load and null. Replicated that style in this code path and one other I saw using the possibly-unitialized-at-that-moment variable.
Also de-linted prior and de-flaked post in separate commits
It's a race condition, I can't reproduce it but I can see how it would happen.
Ran `./gradlew jacocoTestReport` against an Android S emulator locally
Null is the billion dollar mistake.

2.15 crash fix - card browser crash on uninitialized variable

---

AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
AnkiDroid/src/main/java/com/ichi2/async/Connection.java

Previously these sorts of exceptions were grouped into a general exception
that requested a user send a crash report, even though they are not actionable for us
Now we will detect custom sync server URL exception class specifically and just send
that back to the async listener, where existing user messaging should handle it fine
Fixes #8883 
Use existing messaging handling for user-fixable errors for this specific exception instead of using general handlers
I reproduced this locally by 
1) manually editing the sync URL in prefs to something invalid, that our current UI won't let you enter at all. So it was forcibly bad.
2) going in to settings general and attempting to login - I saw the error report then developed the fix, now it shows a nice dialog just like on DeckPicker if you try to …

fix(login): bubble custom sync server exception up during login

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java

a862073a8f9f52da282b80730cc80f3162ec7814 was merged without third party review. So I guess that nothing is really
obviously correct. We have a method that returns the user's locale. There is no point in indicating a locale if it is
always ROOT.

Uses correct locale

---

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java
AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedUpgradeTest.java

Users reported being upgraded to SchedV2
SchedV1 did not have the 'schedVer' variable set unless a downgrade
was performed. Existing users of SchedV1 did not have this variable set
so they were using SchedV2 without having gone through the upgrade
process.
Therefore they used 'fDefaultSchedulerVersion' which was bumped to 2
Fixes #8926
Now, instead of using the default, we set the value explicitly
Unit tests, and tested on my device:
* 2.14.6 -> 2.15.0 -> stays on V1
* 2.15.0 -> creates as V2
SchedV1 did not have the 'schedVer' variable set unless a downgrade was performed.

fix: SchedV2 was used instead of SchedV1

---

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java

Fix a crash when undo stack had items but then you delete a deck and try to undo after
Fixes #8935
this causes a rebuild of the options menu with the side effect that undo
will be made invisible again - previously it was there even though deck delete
clears the undo queue, which led to crashes
I reproduced the crash on my actual device, inspected code, reproduced crash on API30 emulator, then fixed it and was no longer able to reproduce crash
We probably need to inspect all uses of col.clearUndo() to see which CollectionTasks caused it to happen, and make sure that invalidateOptionsMenu() is called in the postExecute on whatever activity listeners were sent in with the task
But this one is fixed...

fix(DickPicker): invalidate options menu after deck delete

---

AnkiDroid/src/main/assets/card_template.html
AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardTemplate.java
AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/CardTemplateTest.java

User reported that 2.15 was significantly slower, this seems to be due to MathJax 3.
User's cards did not contain MathJax
Fixes #8927
Related: #6410 - didn't add perf metrics, which is bad, but since we have a user in the field, rather than a theoretical slowdown, this seems like the best option.
We only load MathJax JS if we need it.
Manual debugging on my phone:
* Card with no MathJax works
* Card with MathJax works
Note: I couldn't repro the slowdown, so unsure if this is completely correct

perf: only load MathJax if MathJax exists

---

AnkiDroid/src/main/java/com/ichi2/libanki/Models.java
AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.java

req is unused in current clients but that is new enough we'll keep it for
compatibility for now
Fixes #8945
restore some old code from release-2.14 branch - this is copy and paste from release-2.14, just adding comment clarifying the reason the code is back, and pointers to discussion
Visual inspection of JSON generated during model creation on release-2.14, release-2.15 without, and release-2.15 with this code
There are no changes without unintended consequences

fix(model): generate req field for old client compatibility

---

AnkiDroid/build.gradle

Adding a card in Akebi crashed
Fixes #8931
Fixes #8928 (hopefully)
some of the methods on the Cursor for the database
were called internally by Android
These were throwing NotImplementedException
Fixed by upgrading the backend
Changed in the backend code to log a warning: they shouldn't be required as we don't support `.requery()`
Android 11 phone - now can add cards with Akebi
TODO: Add follow on issue

fix ContentProvider/API related crashes

---

AnkiDroid/build.gradle
tools/release.sh

Amazon publish was close, but this was the first time I actually attempted to publish there.
Turns out there were a couple path issues
Related #8151
- Remember to assembleAmazonRelease before publishing, with special "generate universal APK" argument
- Publish to Amazon from the new APK build path
Ran the publish locally and got it to work, it's in review now
Teamwork makes the dream work - thanks @mrudultora we're back on the Amazon app store! It appears about 300 people a month download AnkiDroid from there, so this has to be useful to a growing number of people...

fix(amazon): assemble amazon release w/universal APK, publish correct path

---

AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java

If current deck id didn't exist in DB, wouldn't select Default deck
Fixes #8930
Added a check for existence of selected deck id to the `if` statement in https://github.com/ankidroid/Anki-Android/commit/ef5f7badc5c8b7381f66a1ff4dd5e41f6fa539d6#diff-e576625ef3cb53556ff135a9fc296d94cbb848c62f59d4f065d1595d948310bcR1079-R1081
> You won't be able to test this with the interface - it resets current deck if you delete current deck.
> I think you need to close the app, then directly edit (read as: mess up) the database by setting the current deck pointer to something that does not exist. Then open the app and try a feature that uses current deck to make sure it handles the bad current deck pointer
Did as @mikehardy said above and manually changed curDeck in sqlite database to an invalid number ad …

Set deck to default if selected id doesn't exist

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java

Prevents Automatic Display Answer from occurring when the delay is set to 0, but there is audio present.
No issue existed before, I just came across it and since it irritated me I fixed it.
The default behavior for having the delay set to 0 is to wait indefinitely, so this just makes that more consistent.
I haven't compiled or tested it, because I don't have the SDK installed (sorry about that)
It seems like a pretty simple change though, if it compiles it should work as expected.
Please comment if you have tested it, thanks :)
BTW I'm loving AnkiDroid, it's great :+1:

Fix timing for Automatic Display Answer

---

AnkiDroid/build.gradle
AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.java
AnkiDroid/src/androidTest/java/com/ichi2/anki/testutil/DatabaseUtils.java

We moved to our own backend cursor which did not implement `moveToPostion`, or `getType(int)`. I did not believe this cursor was provided to consumers, but it was provided via our ContentProvider API
Fixes #8957
A new backend version implements those methods
`DatabaseUtils.cursorFillWindow` is used by a real usage of the API but our tests did not use it
We copy it into the project as the methods are marked with `hide`
And ensure the invariants are handled
Unit tested, and Pleco shows duplicates

fix[api]: duplicate checks

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java

`Before` The learner can only replay the audio in notes.
`After` The learner can pause or resume the audio and It works with any number of audio files in the note.
Fixes #6774 
Focusing on the URL of the audio. When the user clicks on another icon ⏯️, I'll work on the current URL not the previous one.
Using a real mobile phone "Xiaomi".
https://user-images.githubusercontent.com/48657780/117230198-d7563300-ae1c-11eb-8ea3-2ea53a007b16.mp4
Related PRs  #8346

Add play/pause audio in notes

---

AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java

This is disappointing: there is a bug in `TabLayout` which means that selecting index[0] before the control has been laid out will position the control at `LEFT`, rather than START (effective result, not actual code)
Fixes #8984
Fix this by detecting the layout event for the control, and then selecting the tab: this uses a scroll animation, which works
Test on my Android 11 Google Pixel 3a, using the dev 'force RTL' option, and without: in both cases 'overview' is selected
Every day, Android disappoints me a little more

fix[stats] start at "Overview" tab in RTL mode

---

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.java

People use this - Anki has it special cased unintentionally due to hooks, but this is in use in AnkiDroid
It wasn't working before this, but the template `{{Front}}{{FrontSide}}` previously rendered as `helloworld{Unknown field FrontSide}` in 2.14.6
Fixes #8951
Define the field on the front
Unit tested and tested on my phone
Anki: https://github.com/ankitects/anki/blob/400254277bdc7b8aab0ac7eefd8f183cf9482e64/rslib/src/template.rs#L409-L417
Our change: 08217da (issue #7980)

fix: "{{FrontSide}}" should be blank on front 

---

AnkiDroid/src/main/java/com/ichi2/anki/Info.java

Follow proper backstack movement in changelog section.
Fixes #8938 
Overridden `onBackPressed()` method to go back in `WebView` if any link has been opened there. Otherwise, go back from the `Open Changelog` section.
Verified the working of the functionality.

Follow proper backstack movement in changelog section

---

build.gradle

F-Droid is struggling to build 2.15.x: https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.ichi2.anki.yml#L715
I was unable to find the build log but @linsui notified us (thanks!)
Fixes #8982 maybe
There were two remnant maven repos from an R8 build workarind in #7558 - I forgot to remove the entire 7758 when upstream resolved their issue
There is one legitimate maven repo definition for api publishing which I restructured to see if it will pass F-Droid scan, but if it does not, then F-Droid will have to do something to allow it, it's a legitimate repo definition based on local files to publish our API module. Perhaps they could ignore the api module and/or build via `./gradlew :AnkiDroid:assemblePlayRelease`
CI will test it sufficiently
Not sure what I learned here, on …

build: remove remnant dirs from r8 failure, restructure api publish repos

---

AnkiDroid/src/main/java/com/ichi2/preferences/StepsPreference.java

`JSONArray` has a `put` method with double input. When we set its input with float variable, it was casted to double and then we may see a number with different value.
Fixes #8995
Change `float` variable to `double`.
Emulated device Samsung A50 SDK 28.

Fix floating point numbers for steps in Deck Options

---

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioClipFieldController.java
AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/fields/BasicAudioClipFieldControllerTest.java

Audio imports of `mp3` files were instead shown as `mpeg`. These are much slower to load
Fixes #9008
Alleviates #9023
Cause: we converted "a.mp3" to "a_mp3" which failed the file type conversion
Allow a dot
Unit tested. Tested on my Android 11
We need more tests on this path

fix[Audio Import]: mpeg converted to mp3

---

AnkiDroid/src/main/java/com/ichi2/anki/UIUtils.java
AnkiDroid/src/main/java/com/ichi2/ui/RtlCompliantActionProvider.java

Fix the issue where undo button becomes difficult to click.
Fixes #9014 
Added padding of 16 dp to top and bottom of the undo icon.
Verified.

Add padding to undo icon

---

AnkiDroid/build.gradle
pre-commit

Add Git pre-commit hook for Ktlint.
If this is installed, then `./gradlew ktlintFormat` will run for Kotlin files and then `git add $file` will run on those files before commit.
Fixes part of #9019 
Added pre-commit file and task to install Git pre-commit hook for Ktlint before build.
Verified with a test commit.
https://medium.com/@alistair.cerio/android-ktlint-and-pre-commit-git-hook-5dd606e230a9
https://emmanuelkehinde.io/setting-up-git-pre-commit-pre-push-hook-for-ktlint-check
Reference for the pre-commit script: https://gist.github.com/echorebel/4246cd4ec42098fce66c169d28aa2812#gistcomment-3734796

Add Ktlint pre-commit hook

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/main/res/values/02-strings.xml

Fixed Bug
Fixes #8973
Fixes #8972 🙌
Removed the part of code which is closing the dialogue boxes when activity is in onPause or in onResume.

Fixed Bug Crash TagsDialog not attached to a Context

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
AnkiDroid/src/main/java/com/ichi2/ui/CardBrowserSearchView.java
AnkiDroid/src/main/res/menu/card_browser.xml

Opening the nav bar moved from the current search to the previous search
Fixes #9010 
We do this with a temporary variable containing the current value
of the search bar.
There was a bug with setting this temporary, which we also fix:
Toggling the navbar called supportInvalidateOptionsMenu
This calls through to SearchView: as follows:
supportInvalidateOptionsMenu => MenuBuilder.clear()
MenuBuilder.clear() => collapseItemActionView(mExpandedItem);
=> onActionViewCollapsed
=> setQuery("", false);
We had a listener on setQuery, which then blanked the temp variable. class: CardBrowserSearchView fixes this, by ignoring these methods if it's triggered by collapse/expand
Unit tests pass, passes on my phone
⚠️ Felt like a significant effort to unit test this so I didn't attempt it. Please request …

fix: open nav menu clears search

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java

Fix for empty search results and wrong card count.
Fixes #8975 
Setting `mRestrictOnDeck` to an empty String and calling `searchCards()` method inside `selectAllDecks()`.
Verified that the bug has been fixed.

Fix for empty search results and wrong card count

---

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java

This PR Fixes the error which occur while opening the card which is having cloze text from card browser. 
Fixes #9005
I Changed the ordinal to 0 for all the cloze cards.

Fixed Cloze Card Preview

---

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java

> This is follow on work for issue #8485
> 
> It was fixed in #8735 but without a test confirming the fix and making sure it doesn't happen again
> 
> This issue tracks creation of a test that verifies the issue before the fix from #8735 and makes sure it is actually fixed
Fixes #8744
After testing different approaches to reproduce the bug, I found that using a deck of about 75 cards minimum would cause the error.
After that I added the method `flagsAreShownInBigDecksTest` in `CardBrowserTest` class in which I selected and flagged a random card, unflagged the card, and in the end selected and flagged all the cards, testing each time that the flags are correct.
Checked out commit 3e798367 and verified that the test failed, then went back to normal branch, verifying the test pass.

Test for card browser changing color when card flag changes

---

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid/src/main/res/drawable/button_background.xml
AnkiDroid/src/main/res/layout/note_editor.xml
AnkiDroid/src/main/res/values/attrs.xml
AnkiDroid/src/main/res/values/theme_black.xml
AnkiDroid/src/main/res/values/theme_dark.xml
AnkiDroid/src/main/res/values/theme_light.xml
AnkiDroid/src/main/res/values/theme_plain.xml
AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.java

Restyled the buttons to give it a feel of button.
Previous buttons:
Fixes #8779
I removed the previous implementation  and  added a AppCompatButton and layer-list in background.
New Buttons:

Enhanced card and tag buttons in Add Note

---

AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java

DeckPicker would restart upon returning to it from Card Browser/Statistics via the Navigation Drawer
Fixes #8598 
Use the following flags while launching the DeckPicker intent from NavigationDrawerActivity
- Intent.FLAG_ACTIVITY_CLEAR_TOP: Finishes activities above DeckPicker in the back stack
- Intent.FLAG_ACTIVITY_SINGLE_TOP: Doesn't relaunch DeckPicker if it's at the top of the back stack
Previously, FLAG_ACTIVITY_NEW_TASK was used which made a new Task on the back stack and forced the target activity of the Intent to be launched. This approach is only suitable for 'launcher' behavior, like that of IntentHandler.
Tested on:
- Samsung Galaxy A80 API 30 (Physical Device)
- Pixel 4 API 27 (Emulator)
- Pixel XL API 21 (Emulator)

Fixes #8598: Pop DeckPicker from back stack on return via Navigation Drawer

---

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java
AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java
AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/OnRenderProcessGoneDelegate.java
AnkiDroid/src/test/java/com/ichi2/anki/TestCardTemplatePreviewer.java
AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/OnRenderProcessGoneDelegateTest.java

On Android 11, OnRenderProcessGone occurred quite a lot for me with basic (sound/image) cards. This was while the app was minimised, sometimes for a long time, and the toast which was displayed was confusing.
One instance of the "OOM" string is seen in a Russian forum
String: `WebView renderer crashed. Cause: Out Of Memory`
Fixes #8459
I feel there's no need to do anything in this case, as the OOM is likely recoverable and non-repeatable while the user is
reviewing, so we avoid doing anything
So, use [lifecycle components](https://developer.android.com/topic/libraries/architecture/lifecycle) and do nothing if the activity isn't after the "STARTED" state.
Mostly unit tested, crashing still appears to work via `AbstractFlashcardViewer.crashWebViewRenderer`
* onRenderProcessGone changed from …

OnRenderProcessGone: do nothing if minimised

---

AnkiDroid/build.gradle

`ktLintFormat` fails if a wildcard was present as the `format` did not fix this, and then the `lint` failed
* Prevents huge changes in imports
Alleviates #9093
Don't worry about wildcards
Cherry-picked from 46324c097f49d7f03a1d435e357f7f02af38d7e2
My branch now passes with this cherry-picked
* alternate solution: https://stackoverflow.com/questions/63354680/ktlint-fails-with-wildcard-import-cannot-be-auto-corrected
* https://github.com/JLLeitschuh/ktlint-gradle#configuration (open `Groovy` section)

ktlint: Disable no wildcard imports rule

---

pre-commit

A user would struggle to determine what the error was if `ktLintFormat` failed
`-q` (error only) is overkill as it removes useful output, but there is a large amount of warnings in the current version of the ktLint plugin
GitHub ref: JLLeitschuh/ktlint-gradle/issues/457
This can be converted to `-w` (warnings only) afterwards
A typical error is:
```
KtLint found code style violations. Please see the following reports:
- C:\\...\ktlintTestSourceSetFormat\ktlintTestSourceSetFormat.txt
```
After adding `-w`, we'd also get the more useful:
```
CriticalExceptionTest.kt:19:1 Wildcard import (cannot be auto-corrected)
```
Fixes #9093
⚠️ Untested, only via commandline not via hook
* https://docs.gradle.org/current/userguide/command_line_interface.html#sec:command_line_logging
* …

fix: Remove noise from ktLintFormat output
