AnkiDroid/src/main/java/com/ichi2/libanki/Models.java
https://github.com/dae/anki/commit/643ec35449f3cb85667d409ccf90a0bad22e0940
I'll merge it right away since there isn't actually any code path in AnkiDroid that uses this. I'm still porting it over just to be consistent.
=> Use alternate pattern match during field changes

AnkiDroid/src/main/res/values/constants.xml
Saves the user a few redirects.
=> Update help and manual links

AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java
http://ankidroid-triage.appspot.com/view_bug?bug_id=5858829749190656
=> Fix NPE when playing video

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
http://ankidroid-triage.appspot.com/view_crash?crash_id=5204903798505472
=> Fix NPE when accessing mCards in Browser

AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.java, AnkiDroid/src/main/res/values/02-strings.xml
Hopefully this will allows us to narrow down the issue a bit more
=> Send exception to server when apkg import fails due to content provider

AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java, AnkiDroid/src/main/res/values/constants.xml
=> Add links for Japanese manual and help page

AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java
See bug ID: 1ab53bb03b317adaf3383044bfe802a3
=> Better fix for issue 2406

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java
As pointed out in the [forum](https://groups.google.com/forum/#!topic/anki-android/YxekHzrgLV0)
=> Fix bug where videos not played when auto-play disabled

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TagsDialog.java
https://code.google.com/p/ankidroid/issues/detail?id=2464
=> Fix issue 2464

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDb.java
I haven't tested this at all, but it's surely going to work better than having the system delete the DB.
@nicolas-raoul 
Do you know how to intentionally corrupt the db? Or does anyone have a corrupt db lying around to test this with?
=> Implement DatabaseErrorHandler.onCorruption

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDb.java
I forgot to add these changes which I implemented while testing #698
=> Minor edit to #698

AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java, AnkiDroid/src/main/res/values/01-core.xml
https://code.google.com/p/ankidroid/issues/detail?id=2378
=> Issue 2378: Show toast when cards due but not ready to be shown

AnkiDroid/src/main/java/com/samskivert/mustache/Mustache.java
Show a card template error on the card itself when *ANY* error occurs in Mustache compile. This is a workaround for [issue 1837](https://code.google.com/p/ankidroid/issues/detail?id=1837)
=> Add global try/catch around compile method in Mustache

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java, AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.java, AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java, AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java, AnkiDroid/src/main/java/com/wildplot/android/rendering/PlotSheet.java
Some minor edits:
* In beta15, ShowcaseView is only shown when the app is first started, so I've moved the part that triggers it to the load counts handler, which is called on every onResume()
* Some of the default options for custom study were inconsistent with desktop, so I fixed them. There are some more significant differences remaining (see [issue 2043](https://code.google.com/p/ankidroid/issues/detail?id=2043)) which I'm not going to address.
* Fix some formatting errors with the new logging system. In the release builds, exceptions caused by formatting errors are handled and ignored, but in the debug builds (i.e. when signed with the debug key) they cause a crash, so one must be a bit careful.
* Fix a bug in the export code. Exporting a deck with scheduling off was taking literally …
=> Beta15 various fixes

AnkiDroid/src/main/java/com/ichi2/libanki/LaTeX.java, AnkiDroid/src/main/java/com/ichi2/libanki/Media.java
I've been looking at some LaTeX issues recently and thought I'd give this class a review and update anything that looks wrong. Turns out it's completely correct as it is. There are no functional changes in this PR, it's just comments, removal of dead code, and an indication that's it's been recently reviewed.
=> Cleanup of LaTeX.java

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
We limit the logcat to 100 lines on crash reports, and all the other junk was taking up too much space, so I limited it to ActivityManager, AnkiDroid, and SQLiteLog tags
=> Only take logs from the logcat with tag = AnkiDroid or SQLiteLog

tools/translation-rates.sh, tools/update-localizations.py
Include the strings from multimedia editor, and gothic language
=> update crowdin scripts

AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.java
Since the core strings have been translated
=> Add gothic language

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java, AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java, AnkiDroid/src/main/java/com/ichi2/async/Connection.java, AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java, AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java
Here is some work to slim down this class and add some comments to it.
I've deleted dead code, moved out parts that didn't belong in it, fixed some warnings, and factored out the AnkiDroid directory creation routines. The idea was to ensure there is exactly one place in the application where we create the AnkiDroid directory and/or check it for write permission to make it easeir later to handle all those crashes we're getting from pointing to inaccessible directories.
This also fixes crashes where the user sets the AnkiDroid directory to a blank string, but not any other kind of inaccessible path.
=> Some cleanup of AnkiDroidApp.java

AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java
This is a quick fix for the most reported crash in 2.4
=> Fix another crash loading statistics

AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java
https://anki.tenderapp.com/discussions/ankidesktop/11713-traceback-error-after-clicking-show-answer
=> Fix a bug introduced in 65deaef

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
```
java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
at java.util.ArrayList.get(ArrayList.java:308)
at com.ichi2.anki.CardBrowser.onPrepareDialog(CardBrowser.java:710)
```
=> Fix IndexOutOfBoundsException in CardBrowser

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
This will hopefully allow the result of the sync to be communicated to the user even if the Activity has somehow been destroyed
=> Attempt at a workaround for issue 2542

AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.java
The logic wasn't quite right...
=> Improve error message again in apkg import code

AnkiDroid/src/main/java/com/ichi2/libanki/Consts.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/RemoteMediaServer.java
Including this at the request of @dae
dae/anki@a0bad7d
=> update media url

AnkiDroid/src/main/java/com/example/android/common/view/SlidingTabStrip.java, AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java, AnkiDroid/src/main/res/layout-v14/styled_dialog.xml, AnkiDroid/src/main/res/layout-xlarge/bottom_button.xml, AnkiDroid/src/main/res/layout-xlarge/deck_picker.xml, AnkiDroid/src/main/res/layout-xlarge/studyoptions_fragment.xml, AnkiDroid/src/main/res/layout/bottom_button.xml, AnkiDroid/src/main/res/layout/card_template_editor_item.xml, AnkiDroid/src/main/res/layout/flashcard.xml, AnkiDroid/src/main/res/layout/info.xml, AnkiDroid/src/main/res/layout/note_editor.xml, AnkiDroid/src/main/res/layout/studyoptions_fragment.xml, AnkiDroid/src/main/res/layout/styled_dialog.xml, AnkiDroid/src/main/res/layout/widget_big.xml, AnkiDroid/src/main/res/menu/activity_edit_text.xml, AnkiDroid/src/main/res/values/13-newfeatures.xml
Now that we can lint without being exposed to all the AppCompat stuff, it's a good time to go through some of the warnings.
Each commit should be carefully reviewed. There will be more coming, so please don't merge yet.
=> Fix some lint warnings

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
Fix for [Issue 2562](https://code.google.com/p/ankidroid/issues/detail?id=2562).
=> Don't include subdecks in total due count

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java, AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckDropDownAdapter.java, AnkiDroid/src/main/res/menu/anki_stats.xml
Currently it's a HUGE PAIN IN THE ASS to check the statistics for subdecks. This fixes that.
Someone please merge if you approve.
=> Add basic deck selector to Statistics

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/java/com/ichi2/libanki/Card.java, AnkiDroid/src/main/res/xml/preferences.xml
Here's the removal of the simple interface. I may have overestimated the amount of code this was taking up, but it's still a lot nicer now.
I have not removed the orphaned string resouces left over by this commit. I was planning on removing all unused strings in another commit later.
=> Remove simple interface

.idea/misc.xml, AnkiDroid/src/main/AndroidManifest.xml, AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.java, AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java, AnkiDroid/src/main/res/xml/preferences.xml
Remove redundant code which was only done on Eclair
Change to Java 7 as recommended by Android Studio
Don't show Hebrew preference on Jellybean and above
Get rid of lint warnings in Preferences
=> Clean up Compat code

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, tools/travis/continuous-test.sh
Try to fix NPE and WindowLeaked exceptions due to progress dialog
=> Fix progress dialog dismiss

AnkiDroid/build.gradle, AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserOrderDialog.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportDialog.java, AnkiDroid/src/main/java/com/ichi2/themes/StyledProgressDialog.java, AnkiDroid/src/main/res/values/themes.xml
Updated the material dialogs API which gives us the progress dialog animation.
Also properly styled the contextual action bar ("edit, copy, paste").
=> Add progress animation, fix contextual action bar

.gitignore, AnkiDroid/build.gradle, AnkiDroid/src/main/AndroidManifest.xml, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/DividerItemDecoration.java, AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java, AnkiDroid/src/main/java/com/ichi2/libanki/Sched.java, AnkiDroid/src/main/java/com/ichi2/themes/Themes.java, AnkiDroid/src/main/res/layout/deck_item.xml, AnkiDroid/src/main/res/layout/deck_picker.xml
Initial RecyclerView with CardViews implementation.
Not done:
- hiding default deck if empty
- new/learn/rev colors
- selectors
- selected deck
- arrow buttons to expand/collapse subdecks
- ellipsizing long deck names/adding spacing to multiline deck names
- general card UI tweaks
=> RecyclerView, CardView in DeckPicker

AnkiDroid/src/main/res/values/01-core.xml, AnkiDroid/src/main/res/values/02-strings.xml, AnkiDroid/src/main/res/values/03-dialogs.xml, AnkiDroid/src/main/res/values/04-network.xml, AnkiDroid/src/main/res/values/05-feedback.xml, AnkiDroid/src/main/res/values/06-statistics.xml, AnkiDroid/src/main/res/values/07-cardbrowser.xml, AnkiDroid/src/main/res/values/08-widget.xml, AnkiDroid/src/main/res/values/09-backup.xml, AnkiDroid/src/main/res/values/10-preferences.xml, AnkiDroid/src/main/res/values/11-arrays.xml, AnkiDroid/src/main/res/values/16-multimedia-editor.xml, AnkiDroid/src/main/res/values/constants.xml
I used the tool from https://github.com/ankidroid/Anki-Android/pull/761 for the most part to remove unused strings. I skipped dimens.xml and colors.xml since they are probably being actively worked on, and I skipped all the translated versions since that should be handled by crowdin.
=> Remove unused strings

AnkiDroid/src/main/res/layout/feedback.xml, AnkiDroid/src/main/res/values/05-feedback.xml
Fixed some string resource definitions and restored the strings that were removed earlier by the lint check.
=> Restore some strings

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.java, AnkiDroid/src/main/java/com/ichi2/async/Connection.java, AnkiDroid/src/main/java/com/ichi2/libanki/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java
For the first commit, the value that was removed was also being shuffled around the place for no reason, so I removed all traces of it.
=> Catch up on libanki changes

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.java, AnkiDroid/src/main/java/com/ichi2/async/Connection.java, AnkiDroid/src/main/java/com/ichi2/libanki/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java, ShowcaseView/library/src/main/java/com/github/amlcurran/showcaseview/ShowcaseView.java
The 2.4.3 hotfix commits merged into develop.
=> 2.4.3cherrypicked

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.java, AnkiDroid/src/main/res/menu/card_browser.xml, AnkiDroid/src/main/res/values/07-cardbrowser.xml
For now, it only shows a list of saved searches in the collection. Not able to add a new search from here.
=> Issue #2571: added menu item My Searches in cardbrowser.

AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java
Porting https://github.com/ankidroid/Anki-Android/pull/804 to the 2.4.3 hotfix branch.
@timrae You think we should release 2.4.3 after merging and testing this? I think we've accumulated enough bug fixes for a release now.
=> Port to hotfix: Handle case where note ID is Integer, not Long

AnkiDroid/src/main/assets/changelog.html, AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/Info.java, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/FullSyncer.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/HttpSyncer.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/RemoteMediaServer.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/RemoteServer.java, AnkiDroid/src/main/java/com/ichi2/utils/VersionUtils.java, AnkiDroid/src/main/res/layout/info.xml
A few changes:
Add actionbar to the Info screen
Add a progress bar to the Webview in Info screen
Only show the changelog for release versions
Load the changelog webpage from assets to prevent overloading server
Refactor the version utilities to a new class
=> Fix Changelog and only show it for release versions

AnkiDroid/src/main/java/com/hlidskialf/android/preference/SeekBarPreference.java
Attributes for this class stopped working since the namespace change.
=> Use correct namespace in SeekBarPreference

AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java
Fix from https://github.com/ankidroid/Anki-Android/pull/741 for apostrophes in sound file name.
=> Use double quotes for sound references

AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java, AnkiDroid/src/main/java/com/ichi2/libanki/hooks/HebrewFixFilter.java
Some small changes from `develop` that I think should go into the next hotfix.
=> Cherry-picked develop commits

AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
Updated ActionBarDrawerToggle from v4 to v7 as it was deprecated and causing the issue
=> side menu item is now a hamburger rather than back arrow

AnkiDroid/src/main/java/com/ichi2/libanki/Sched.java
Fix for [Issue 2581](https://code.google.com/p/ankidroid/issues/detail?id=2581)
=> Fix same-day burying of new card siblings

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.java, AnkiDroid/src/main/java/com/ichi2/async/CollectionLoader.java
An attempt at fixing some of the crashes that have been received in the alphas
=> Fix some crashes

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
See [issue 1459](https://code.google.com/p/ankidroid/issues/detail?id=1459)
=> Allow changing media volume from any AnkiActivity

AnkiDroid/build.gradle, AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/java/com/ichi2/anki/UIUtils.java, AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.java, AnkiDroid/src/main/res/layout/preferences.xml
The new `AppCompatDelegate` in [v22.2 of the support library](http://android-developers.blogspot.co.uk/2015/04/android-support-library-221.html) gives us a proper way to implement ActionBar functionality in a `PreferenceActivity` which fixes issue 2635. There's also a better fix here for [this Android bug](http://code.google.com/p/android/issues/detail?id=4611) and have started to lay the ground work for getting the Toolbar to show in nested preferences.
=> Update to new AppCompat v22.2

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
[Issue 2633](https://code.google.com/p/ankidroid/issues/detail?id=2633)
=> Fix crash accessing schedule when building counts from corrupt col

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
In response to [this thread](https://groups.google.com/forum/#!topic/anki-android/gc4F1Gb-Ojg) on the forums.
Easy to test with the "Don't keep activities" developer option. Since the UI elements are dynamically built to reflect the selected note type (among other things), Android can't maintain state for us.
I'm just using `onSaveInstanceState` (where there was a conveniently placed `TODO`) to save all the editable parts of a note and reloading them when the activity starts again.
=> Maintain and restore NoteEditor state across activity restarts

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java, AnkiDroid/src/main/res/layout/navigation_drawer.xml, AnkiDroid/src/main/res/layout/night_mode_switch.xml, AnkiDroid/src/main/res/menu/navigation_drawer.xml, AnkiDroid/src/main/res/values/constants.xml
I had a go at switching the navigation drawer over to the new [`NavigationView`](https://developer.android.com/reference/android/support/design/widget/NavigationView.html) convenience class in the Android design support library. It works fine, cleans up the `NavigationDrawerActivity` code nicely, and it will be [super easy to add our branding to the top of the drawer](http://stackoverflow.com/questions/26440879/how-do-i-use-drawerlayout-to-display-over-the-actionbar-toolbar-and-under-the-st/30525387#30525387) this way. 
Unfortunately, Google have not given developers the ability to add custom items to the drawer... A developer from Google said "NavigationView is designed to meet the material design guidelines so intentionally breaking the guidelines isn't a use case﻿"... Which, to be …
=> Switch nav. drawer to new NavigationView class (don't merge yet)

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TagsDialog.java, AnkiDroid/src/main/res/layout/tags_dialog.xml, AnkiDroid/src/main/res/layout/tags_dialog_title.xml, AnkiDroid/src/main/res/layout/tags_item_list_dialog.xml, AnkiDroid/src/main/res/values/03-dialogs.xml, AnkiDroid/src/main/res/values/11-arrays.xml
Also, fixed issue 2168: "Make selected tags show up at the top of the tag list".
@timrae I saw the discussion thread about this issue, but couldn't really understand. So, I fixed the issue based on its description.
=> TagsDialog is now independent from StyledDialog.

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TagsDialog.java
* Also, after the user add a tag that was typed in the SearchView, the SearchQuery is set to empty.
=> Fix: allow adding tags with commas.

AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.java
Fix for [Issue 2251](https://code.google.com/p/ankidroid/issues/detail?id=2251).
=> Fix custom steps not being disabled in filtered deck

AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.java
Fix for https://github.com/ankidroid/Anki-Android/pull/871
=> Use correct JSON null value for delays in filtered deck.

AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java
Fix for [Issue 2532](https://code.google.com/p/ankidroid/issues/detail?id=2532). Copied the approach from `taglimit.py`.
=> Quote tags when building tag-based custom study deck

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/res/menu/reviewer.xml, AnkiDroid/src/main/res/values/01-core.xml, AnkiDroid/src/main/res/values/11-arrays.xml, AnkiDroid/src/main/res/values/constants.xml
[Issue 2401](https://code.google.com/p/ankidroid/issues/detail?id=2401)
I also fixed up a few strings in the first commit to be more accurate.
I appended the new gestures to the end of the existing list, so they will appear to be ordered badly, but changing the order would also mean re-mapping the user's preferences on upgrade which seemed more trouble than it was worth right now.
=> Add missing gestures

AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java
Extra test to determine whether [sonud:NN] is a video: Ask  URLConnection to guess the type.
Some systems can play e.g. avi videos, some can’t. This [asks](https://developer.android.com/reference/java/net/URLConnection.html#guessContentTypeFromName%28java.lang.String%29) `URLConnection` if that class thinks a [sound:NN] file is a video along with the old test.
Tested with Android 4.2 (plays .avi as videos with this change) and Android 2.2. (Doesn’t know about AVI. Can’t play (some) AVIs neither as video nor as sound, same as without this change.)
This is in response to [issue 2669](https://code.google.com/p/ankidroid/issues/detail?id=2669).
=> Play more files as video

AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java
[Issue 2662](https://code.google.com/p/ankidroid/issues/detail?id=2662)
=> Fix the up-arrow in the Previewer

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/res/layout/flashcard.xml, AnkiDroid/src/main/res/values/attrs.xml, AnkiDroid/src/main/res/values/themes.xml
Move the setting of colors when night mode enabled into the new `Theme_Dark`
Get rid of some code that wasn't doing anything
=> Clean up the night mode code using themes

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/res/menu/reviewer.xml
Don't show black background on Android 2.x EditText in note editor
Always show mark icon when whiteboard disabled
Don't show icon in multimedia add menu
=> Some small fixes

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
See the [discussion in the forum](https://groups.google.com/forum/#!topic/anki-android/XN11PNdFhOQ)... I think this is currently the best solution on the table.
=> Only do color inversion as fallback when .night_mode not specified in css

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
Fix for [Issue 2683](2683)
If a user logs in by tapping the sync button, we are opening the MyAccount activity then syncing with an AsyncTask in `onActivityResult`, then `onResume` is run right after it. Since syncing closes the database, the work in `onResume` crashes when it tries to use the database.
This commit makes the operations an either-or.
=> Fix database error dialog if syncing from login activity.

AnkiDroid/src/main/res/layout-xlarge/studyoptions_fragment.xml
@ospalh 
This should fix (most of?) [Issue 2682](https://code.google.com/p/ankidroid/issues/detail?id=2682). I haven't looked at the graph, but this fixes the rest of the colours.
=> Fix colors in xlarge layout of studyoptionsfragment

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
=> Correctly show Acra reporting mode in debug mode

AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.java
=> Restart activity on options group change

AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.java, AnkiDroid/src/main/res/layout/deck_item.xml
=> Enhance deck list padding and indenting

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/res/values/10-preferences.xml, AnkiDroid/src/main/res/xml/preferences_gestures.xml
=> Add option to hide answer buttons when using gestures

AnkiDroid/src/main/res/layout/card_browser_item_my_searches_dialog.xml
Still had some hard-coded colours in the Saved Searches dialog which looked wrong in the dark theme.
=> Fix saved searches colors

AnkiDroid/build.gradle, AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/widgets/FabBehavior.java, AnkiDroid/src/main/java/com/ichi2/async/Connection.java, AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java, AnkiDroid/src/main/res/layout/deck_picker.xml, AnkiDroid/src/main/res/layout/floating_add_button.xml, AnkiDroid/src/main/res/layout/tags_dialog_title.xml, AnkiDroid/src/main/res/layout/toolbar.xml, build.gradle
This is #3627 after I [removed all the changes related to the semi-auto-sync](https://github.com/timrae/Anki-Android/commit/859077e1b4307c3ce2b3c703727fb27d76e5b3a6). Auto-sync is going to need some more thinking / work
=> Show SnackBar instead of dialog when sync was successful

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/async/Connection.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/MediaSyncer.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java, AnkiDroid/src/main/res/layout-xlarge/deck_picker.xml, AnkiDroid/src/main/res/values/01-core.xml
Allow the sync to be cancelled. This makes auto-sync a lot more feasible and also allows us to cancel a media sync that's gonna take 2 days to finish. I also removed some old media sync code.
Also fixes #3633 , I can't be bothered making a separate PR
=> Sync cancel

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java, AnkiDroid/src/main/res/layout-xlarge/deck_picker.xml, AnkiDroid/src/main/res/layout/activity_anki_stats.xml, AnkiDroid/src/main/res/layout/anki_progress.xml, AnkiDroid/src/main/res/layout/card_browser.xml, AnkiDroid/src/main/res/layout/deck_picker.xml, AnkiDroid/src/main/res/layout/flashcard.xml, AnkiDroid/src/main/res/layout/floating_add_button.xml, AnkiDroid/src/main/res/layout/note_editor.xml, AnkiDroid/src/main/res/layout/studyoptions_fragment.xml, AnkiDroid/src/main/res/layout/toolbar.xml
The progress bar in the browser would sometimes not disappear properly, so I've replaced them with a proper progress bar in the center of the layout
=> Replace progress bar on toolbar with progress bar in the main layout

AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/ContentProviderTest.java, api/build.gradle, api/src/main/java/com/ichi2/anki/api/AddContentApi.java
remove unnecessary ref to context in some methods
add check for duplicates method
add a build script to make zip for jcenter
=> Small update to API

AnkiDroid/src/main/res/layout/deck_item.xml
=> Fix broken deck name

.travis.yml, AnkiDroid/build.gradle, AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java, AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java
Implement required runtime checks for 'dangerous' permissions on Android M and bump SDK
Continue to use deprecated HTTP client for now
=> Update to SDK 23

.travis.yml, AnkiDroid/build.gradle, api/build.gradle, build.gradle
also drop targetSdkVersion to v22 and use the v21 emulator with Travis to fix the build
=> Update material dialogs version

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.java
=> Don't show empty deck message if the deck has subdecks

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.java
=> Deselect all items in nav drawer in StudyOptions and Reviewer

AnkiDroid/src/main/res/values/11-arrays.xml, AnkiDroid/src/main/res/values/constants.xml
to prevent them from appearing in crowdin
=> Move custom study string references to constants

AnkiDroid/build.gradle, AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java, AnkiDroid/src/main/res/layout/studyoptions_fragment.xml
I'll work on a better fix for #3702, but for now here's a quick fix that at least lets you review with whiteboard / gestures on tablet
=> Quick fix for #3702

AnkiDroid/build.gradle, AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java, AnkiDroid/src/main/res/layout-v14/my_account_register.xml, AnkiDroid/src/main/res/layout/card_template_editor_activity.xml, AnkiDroid/src/main/res/layout/card_template_editor_item.xml, AnkiDroid/src/main/res/layout/model_field_editor.xml, AnkiDroid/src/main/res/layout/multimedia_edit_field_activity.xml, AnkiDroid/src/main/res/layout/my_account.xml, AnkiDroid/src/main/res/layout/my_account_logged_in.xml, AnkiDroid/src/main/res/layout/my_account_register.xml, AnkiDroid/src/main/res/layout/note_editor.xml, AnkiDroid/src/main/res/values-sw600dp/dimens.xml, AnkiDroid/src/main/res/values/dimens.xml
I can't be bothered working on the mini-drawer anymore as it wasn't very popular, and neither was the 600dp tablet content limit
=> Remove mini-drawer and 600dp limit

AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/res/values/10-preferences.xml, AnkiDroid/src/main/res/xml/preferences_advanced.xml
Fixes #3717 as requested by @flerda
=> Add setting to disable access to the AnkiDroid ContentProvider

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
=> Remove debug line

AnkiDroid/src/main/AndroidManifest.xml, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DialogHandler.java, AnkiDroid/src/main/java/com/ichi2/async/Connection.java
See [the wiki](https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-API#sync-intent) for usage details
fixes #3714 fixes #2918
=> Add sync intent for Tasker integration

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DialogHandler.java
and increase minimum sync interval to 2min
=> Fix bug where sync intent doesn't trigger properly

AnkiDroid/build.gradle
Acra 1.7.x is currently non-functional
https://github.com/ACRA/acra/issues/313
=> Fix broken crash reporting

AnkiDroid/build.gradle
=> Revert the support libraries to 23.0.1

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java, AnkiDroid/src/main/java/com/ichi2/libanki/Models.java, AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java, AnkiDroid/src/main/res/layout/anki_progress.xml, AnkiDroid/src/main/res/layout/card_template_editor_activity.xml, AnkiDroid/src/main/res/menu/card_template_editor.xml, AnkiDroid/src/main/res/values/01-core.xml, api/src/main/java/com/ichi2/anki/api/AddContentApi.java
Fix #3746, move card generation to async task, improve efficiency generating new cards due to splitFields(), always expose add/delete template whether or not standard model. A couple of other random fixes as well.
=> Template editor fixes

AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
https://github.com/dae/anki/commit/2f74908b25ec80caf3bf498984d4aa409b4012f4
=> Update Field Searches to match multi-line fields

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
Moved the layout update from displayCardQuestion() to initLayout(), so that it is applied right away.
Fixes #3621.
=> Change answer button size in initLayout().

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java, AnkiDroid/src/main/java/com/ichi2/compat/Compat.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV10.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV16.java, AnkiDroid/src/main/java/com/ichi2/compat/customtabs/CustomTabActivityHelper.java, AnkiDroid/src/main/java/com/ichi2/compat/customtabs/CustomTabsHelper.java
I saw a couple of crash reports on beta2 for a Gingerbread user related to this:
java.lang.NoClassDefFoundError: android.app.ActivityOptions
at android.support.customtabs.CustomTabsIntent$Builder.setStartAnimations(CustomTabsIntent.java:266)
at com.ichi2.anki.AnkiActivity.openUrl(AnkiActivity.java:330)
at com.ichi2.anki.NavigationDrawerActivity.onItemClick(NavigationDrawerActivity.java:235)
=> Don't use any of the customtabs support library methods if below SDK 16

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
=> Update studyoptionsfragment after sync on tablets

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportDialog.java, AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java
=> Fix export dialog

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/libanki/template/Template.java, AnkiDroid/src/main/res/layout/card_browser.xml, AnkiDroid/src/main/res/values/02-strings.xml
This is kind of borderline for the feature freeze but it's something that's been bugging me
Fix #3778
=> Allow the first column in the card browser to show the actual question

AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.java
For crash-free note type adding while types are still being loaded.
=> Add nullcheck to ModelBrowser.

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
=> Fix post-sync crash on tablet (again)

AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.java
which is consistent with Anki Desktop
=> Rebuild filtered decks after options change

AnkiDroid/src/main/res/values/constants.xml
@dae has made a new mobile friendly page for us
=> Update Ankiweb registration URL

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
=> Allow NavigationDrawerActivity to resize with soft keyboard

AnkiDroid/src/main/assets/flashcard.css
Reverts ankidroid/Anki-Android#3828
=> Revert eebe471d59ef3d4f0d9fd639502b344d1d574c10

AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
When using the whiteboard not for writing chinese characters but using latin letters it's hard to write things like "i", "j" or "ä" as the whiteboard only draws paths but no points.
Points on characters are required for some diacritics and distinguish the characters "i" and "ı" both used in the Turkish language. When practicing language you cannot just ignore them.
=> Allowing the user to write dots on the whiteboard.

AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java, AnkiDroid/src/main/res/xml/preferences_reviewing.xml
Merge #3834 and #3837 into 2.5 branch
=> User improvements

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserContextMenu.java
=> Limit length of title in browser context menu dialog to 75

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java, AnkiDroid/src/main/res/values/01-core.xml
=> Fix crash previewing faulty template

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
=> Reload current card in reviewer after previous card deleted in Browser

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
=> Fix crash when adding card from intent with only 1 field

tools/parallel-package-name.sh
I added this script directly to the develop branch a few days ago, but I'll add it here as well and generate a couple of parallel installs
@branch-specific
=> Add parallel install script to release-2.5 branch

AnkiDroid/src/main/res/layout/card_item_browser.xml
=> Add left margin to browser

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/res/layout/flashcard.xml
Closes #3865 and also fixes the issue where immersive mode is briefly released to show the progress dialog. Can someone please test that this doesn't break typing in the answer or anything like that?
=> Fix keyboard shortcuts don't work in immersive mode

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV19.java, AnkiDroid/src/main/res/values/10-preferences.xml, AnkiDroid/src/main/res/values/constants.xml, AnkiDroid/src/main/res/xml/preferences_gestures.xml, AnkiDroid/src/main/res/xml/preferences_reviewing.xml
=> Merge hide answer buttons and fullscreen preference

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java, AnkiDroid/src/main/java/com/ichi2/libanki/Sched.java, AnkiDroid/src/main/res/xml/preferences_reviewing.xml
=> Fix custom study extend limits

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV10.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV19.java, AnkiDroid/src/main/java/com/ichi2/libanki/Sched.java
Finishes fixing #3874 and fixes #3877
=> Fix custom study and fullscreen bugs

AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
=> Remove AnkiWeb registration listener

AnkiDroid/src/main/res/values/colors.xml
=> Make counts bar darker so that colors are more visible

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/res/xml/preferences_general.xml
Fixes #3884 
Also a small edit adding sync subsection header in preferences
=> Fix incorrect clearing of undo

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
=> Force max lines in snackbar to 2 on tablet to match phone

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/res/menu/deck_picker.xml
See #3884
I've also put in a patch for #3898 since that's easy
=> Deck picker undo

AnkiDroid/src/main/java/com/ichi2/libanki/Sched.java
Fix for #3905.
I'll write an explanation of it later today. Should try to get this out ASAP for now since it's going to affect a lot of users.
=> Fix crash when loading decklist

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/res/menu/deck_picker.xml, AnkiDroid/src/main/res/values/02-strings.xml, AnkiDroid/src/main/res/values/03-dialogs.xml
Closes #3919.
Even though I implemented the report that shows the card content about to be deleted, it's still not being used anywhere since there's nowhere to really show that information.
=> Implement empty card removal

AnkiDroid/src/main/AndroidManifest.xml, AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.java, AnkiDroid/src/main/res/layout/deck_item.xml
Fix #3931 and a couple of small changes to the clickable areas in the deck list
=> Transparent intent handler

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/res/layout/studyoptions_fragment.xml
Studyoptions was broken on small screens
Also fix the exit animation in DeckPicker
=> Fix overlapping controls in studyoptions

AnkiDroid/build.gradle, AnkiDroid/proguard-rules.pro, AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
https://code.google.com/p/android/issues/detail?id=78377
=> Workaround for crash on Samsung devices on Android 4.2

AnkiDroid/src/main/AndroidManifest.xml
=> Move transparent tag from Application to Activity

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/res/layout/deck_item.xml, AnkiDroid/src/main/res/layout/studyoptions_fragment.xml
A few minor improvements that have been requested
=> Small tweaks to the GUI

AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java
=> Fix automatic playback of consecutive videos

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/res/values/01-core.xml
=> Add a cancel message while waiting to cancel the sync

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/services/NotificationService.java
Add color to the status bar notifications, and explicitly set the content to public to (hopefully) fix #3527
=> Add color to notifications and make content public

AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java
See https://github.com/dae/anki/pull/114 for discussion
=> Don't export media files to deck apkg unless they really are needed

AnkiDroid/src/main/res/values/02-strings.xml
=> Update empty card suggestion string

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
Undoing my screw-up from before.
=> Revert erroneous changes from previous commit

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
Some time back I went over all the decklist rebuilds and cleared out all the redundancies, but this one remained. I thought the code was too messy to screw around with but I got around to looking into it now. The decklist is rebuilt twice: once in `onResume` and once in `onCollectionLoaded`. Both are triggered when you start a new DeckPicker, even if the collection is already open.
It seems that we use `startLoadingCollection()` even if the collection was already open mainly because of the post-startup work DeckPicker was doing inside `onCollectionLoaded`. I factored out the work inside that and made sure the deck list building only happens once.
I was hoping this would halve the startup time but unfortunately it didn't turn out that way since the progress bars disappear after the first …
=> Avoid building the decklist twice on startup

AnkiDroid/src/main/AndroidManifest.xml
It appears that the latest version of Gmail is now setting the MIME type of apkg files to application/zip so I've added an intent filter for that
=> Let AnkiDroid open zip files

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/NoteEditorRescheduleCard.java
=> Fix max characters on reschedule note dialog

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
=> Fix mark card with gesture not updating action bar

AnkiDroid/src/main/java/com/ichi2/libanki/sync/FullSyncer.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/HttpSyncer.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/RemoteMediaServer.java
=> Fix broken custom sync server url generation

AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
=> Add back custom tabs when opening doc links

AnkiDroid/src/main/res/menu/note_editor.xml, AnkiDroid/src/main/res/values/02-strings.xml
=> Edit Note check mark text changed to "Save"

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java, AnkiDroid/src/main/java/com/ichi2/libanki/Models.java
=> Bold font fix and streamline "Rename" dialogs.

AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.java, AnkiDroid/src/main/java/com/ichi2/anki/stats/StatsMetaInfo.java, AnkiDroid/src/main/java/com/ichi2/libanki/Stats.java, AnkiDroid/src/main/java/com/ichi2/libanki/hooks/AdvancedStatistics.java, AnkiDroid/src/main/java/com/ichi2/libanki/hooks/Hooks.java, AnkiDroid/src/main/res/values/10-preferences.xml, AnkiDroid/src/main/res/xml/preferences_advanced.xml, AnkiDroid/src/main/res/xml/preferences_advanced_statistics.xml
Put all commits from pull-request
https://github.com/ankidroid/Anki-Android/pull/4065/files into one
commit. That pull-request is based on issue
https://github.com/ankidroid/Anki-Android/issues/3619
I did this the stupid way since I couldn't get it working by squashing down to a single commit using git rebase in interactive mode. It asked me to merge again with your "Custom sync server" changes (which I had already done before). And after merging and continuing the rebase, the rebase stopped at the third commit (which is the one with the merge), although I did many commits after that one.
So I just created a new github account (rvanprehn), forked again from the ankidroid/Anki-Android develop branch. Made sure I had the most recent version in my jvanprehn fork. Then copied the changed …
=> Make forecast statistic predictive

AnkiDroid/src/main/AndroidManifest.xml
=> Simplify apkg intent filter and block application/zip with file://

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/res/drawable/footer_button_all_plain.xml
Fixes black theme using the wrong answer button colors when the button count changed. Also changed the border color for the plain theme.
=> Use proper answer button text colors

AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.java, AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.java, AnkiDroid/src/main/java/com/ichi2/anki/stats/InfoStatsBuilder.java, AnkiDroid/src/main/java/com/ichi2/libanki/Stats.java, AnkiDroid/src/main/java/com/ichi2/libanki/hooks/AdvancedStatistics.java, AnkiDroid/src/main/java/com/wildplot/android/rendering/PlotSheet.java, AnkiDroid/src/main/res/values/attrs.xml, AnkiDroid/src/main/res/values/theme_black.xml, AnkiDroid/src/main/res/values/theme_dark.xml, AnkiDroid/src/main/res/values/theme_light.xml, AnkiDroid/src/main/res/values/theme_plain.xml
Using Theme in Statistics fixes
https://github.com/ankidroid/Anki-Android/issues/3622
=> Use Theme in Statistics

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
=> Don't use default deck when deck override set to invalid deck

AnkiDroid/src/main/java/com/ichi2/themes/Themes.java, AnkiDroid/src/main/res/values/11-arrays.xml, AnkiDroid/src/main/res/values/theme_black.xml
- Added a blue accent to the black theme
- Renamed original default themes to "light" and "dark"
=> Make black theme default for night mode

AnkiDroid/src/main/res/layout/deck_item.xml, AnkiDroid/src/main/res/layout/dropdown_deck_item.xml, AnkiDroid/src/main/res/layout/dropdown_deck_selected_item.xml
+ Texts and colors are not included in the compiled APK.
+ See http://tools.android.com/tips/layout-designtime-attributes
=> Use design time layout attributes to preview layouts with example values

.travis.yml, AnkiDroid/build.gradle, build.gradle
I'm going to use this PR to play around with the travis config and sort some things out.
=> Travis config

AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/ContentProviderTest.java
This should fix the failing Travis build
=> Decouple ContentProviderTest from API

AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java, api/src/main/java/com/ichi2/anki/FlashCardsContract.java
Also added content provider run time permission check when calling update() and delete()
=> ContentProvider support for enforcing update/delete permission check

api/src/main/java/com/ichi2/anki/api/AddContentApi.java
The existing method is broken in the situation where:
The modelName exists in the database AND in the shared preferences.
The spec says the modelId from the database should win, but in the current implementation the shared prefs id wins.
=> fixed findModelIdByName()

AnkiDroid/src/main/java/com/ichi2/anki/VideoPlayer.java
=> Keep the screen on while watching video

AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.java
Also add a clause to allow self-calling to pass on debug builds so that unit tests will pass
=> Restrict ContentProvider permissions on Android M and note update/delete

AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java
=> Check for 'rogue clients' that don't declare READ_WRITE_PERMISSION in manifest

api/src/main/java/com/ichi2/anki/api/AddContentApi.java, api/src/main/java/com/ichi2/anki/api/NoteInfo.java, api/src/main/java/com/ichi2/anki/api/Utils.java
return `SparseArray<List<NoteInfo>>` containing *all* duplicates instead of `NoteInfo[]` with an arbitrary duplicate
=> Duplicate refinement

api/src/main/java/com/ichi2/anki/api/AddContentApi.java
For the insert/delete/update methods, it seems standard to throw IllegalArgumentException so I've left those doing just that.
=> Consistent handling of ContentResolver.query() returning null

AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/ContentProviderTest.java, AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java, api/src/main/java/com/ichi2/anki/FlashCardsContract.java, api/src/main/java/com/ichi2/anki/api/AddContentApi.java
Decouple the URIs for libanki style querying vs. direct SQL querying.
This has the advantage of being more intuitive, and less susceptible to SQL injection attacks
=> Add a new URI for direct SQL querying of notes table

api/build.gradle, api/src/main/java/com/ichi2/anki/api/AddContentApi.java
Remove SharedPreferences stuff, this should be handled by the client app as per https://github.com/ankidroid/apisample/commit/cf74c7ff32c7164aab69c78a8a1874dd180096ad
Also remove other deprecated methods and bump version
=> Strip API down to essentials

api/src/main/java/com/ichi2/anki/api/AddContentApi.java, api/src/main/java/com/ichi2/anki/api/NoteInfo.java
* Compat V1 was only adding first duplicate to output array
* Compat V2 now clones NoteInfo objects before adding to multiple positions
* Made NoteInfo final to prevent subclasses breaking encapsulation
* Made NoteInfo constructor private so that it's only used as a container
* Also improved the javadoc and comments in some places
=> Some bug fixes for duplicate checking code

AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java, api/src/main/java/com/ichi2/anki/FlashCardsContract.java
* Throw exception if filtered deck specified in insert() and update() methods
* Throw exception if deck insert for a name that already exists
* Use query() instead of rawQuery() in the notes database
=> A few adjustments to the ContentProvider

AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java
Workaround for the crash in #4035.
=> Disable navigation drawer in Previewer.

AnkiDroid/src/main/res/layout/toolbar.xml
=> Fix toolbar spinner text clipping on rotate

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java
In order to not slow searches down too much, calculate the maximum number of rows needed instead of just using constant of 500
=> Don't render unnecessary cards in browser

build.gradle, gradle/wrapper/gradle-wrapper.properties
Android Studio 2 is now stable and initial impressions are good. Not sure if a PR is right for this sort of thing, but here it is anyway!
=> Update gradle files for Android Studio 2

AnkiDroid/src/main/res/values/10-preferences.xml, AnkiDroid/src/main/res/xml/preferences_appearance.xml
=> Add missing string resources

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
https://github.com/dae/anki/commit/610ca050eb57e0afc8ab4db53bbbb61730e20568
=> Adding new cloze while in filtered deck

AnkiDroid/build.gradle
Also took out the part that turns off the vectorDrawable library since it's been removed.
=> Update support libraries

AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java, api/src/main/java/com/ichi2/anki/FlashCardsContract.java
initially to support counting cards per model.
Should I add any more items to the projection?
=> add provider support for /models/counts (note_count), /decks/counts (card_count), /models/*/template/counts (card_count)

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/res/values/01-core.xml
Improved the dismiss and undo code so we're no longer shuffling magic numbers around and removed some redundancy. Fixes https://github.com/ankidroid/Anki-Android/issues/4190 along the way.
=> Clean up dismiss/undo handling and strings

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
From https://github.com/ankidroid/Anki-Android/pull/4061
Also fix existing templates on upgrade.
=> Fix bad font-family definitons on upgrade

AnkiDroid/src/main/res/xml/preferences_custom_sync_server.xml
=> Fix hardcoded string

AnkiDroid/src/main/java/com/ichi2/themes/Themes.java, AnkiDroid/src/main/res/values/theme_black.xml
@hssm 
I don't think these attributes are actually doing anything anyway??
Closes #4212
=> Fix weird background colors in settings with black theme

AnkiDroid/src/main/AndroidManifest.xml
add adjustpan to CardTemplateEditor's windowSoftInputMode for more convenient editing (shows 2-3 times as many lines at once).
=> Show more lines of edittext when editing in CardTemplateEditor

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java, AnkiDroid/src/main/java/com/ichi2/compat/Compat.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV10.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV19.java, AnkiDroid/src/main/res/layout/reviewer.xml, AnkiDroid/src/main/res/layout/reviewer_flashcard.xml, AnkiDroid/src/main/res/layout/reviewer_fullscreen_1.xml, AnkiDroid/src/main/res/layout/reviewer_fullscreen_2.xml
...and don't draw a line when swiping open the system UI
=> Allow returning to fullscreen when whiteboard enabled

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java, AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.java, AnkiDroid/src/main/java/com/ichi2/anki/stats/OverviewStatsBuilder.java, AnkiDroid/src/main/java/com/ichi2/libanki/Stats.java, AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java, AnkiDroid/src/main/res/values/06-statistics.xml
=> add more anki stats

AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java, AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.java, AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.java, AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartView.java, AnkiDroid/src/main/java/com/ichi2/anki/stats/OverviewStatsBuilder.java, AnkiDroid/src/main/java/com/ichi2/libanki/Stats.java
The first commit fixes the code style issues present in the statistics code. I also fixed most of the warnings and removed some unused stuff.
The second commit makes some changes to the newly added overview screen to fix minor visual issues and to make it more compact. I added comments in the code about which ones are still not yet ported from the desktop client.
=> Stats code style cleanup

AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java, AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.java
=> remove CreateFirstStatisticChooserTask

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
=> Enable drawer swipe when whiteboard / gestures enabled

AnkiDroid/src/main/res/color/prefs_item_dark.xml, AnkiDroid/src/main/res/color/prefs_item_light.xml, AnkiDroid/src/main/res/values/theme_black.xml, AnkiDroid/src/main/res/values/theme_dark.xml, AnkiDroid/src/main/res/values/theme_light.xml, AnkiDroid/src/main/res/values/theme_plain.xml
Fixes https://github.com/ankidroid/Anki-Android/issues/4233
=> Use selector with disabled color for prefs text color

AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.java, AnkiDroid/src/main/java/com/ichi2/libanki/Stats.java
Solves https://github.com/ankidroid/Anki-Android/issues/3506
=> Remove cumulative lines from "Answer Buttons" stats graph

AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.java
Fixes https://github.com/ankidroid/Anki-Android/issues/4279
=> Restart DeckOptions only after listener returns

AnkiDroid/build.gradle, build.gradle
I am going to roll back the support libs to the last known good version to see if it fixes https://github.com/ankidroid/Anki-Android/issues/4217
=> Roll back support libs

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
https://ankidroid.org/couchdb/acralyzer/_design/acralyzer/index.html#/report-details/ankidroid/6c43c374-5e25-4ee5-a383-3a4b63d7cccc
=> Fix NPE in updateScreenCounts()

AnkiDroid/src/main/java/com/ichi2/libanki/hooks/AdvancedStatistics.java
Solves https://github.com/ankidroid/Anki-Android/issues/3619#issuecomment-220856651 and probably also https://github.com/ankidroid/Anki-Android/issues/3619#issuecomment-220860737
=> AdvancedStatistics: take new cards already studied today into account

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
Reverts ankidroid/Anki-Android#4271
=> Revert "Enable drawer swipe when whiteboard / gestures enabled"

AnkiDroid/src/main/res/layout/reviewer_flashcard_fullscreen_1.xml, AnkiDroid/src/main/res/layout/reviewer_flashcard_fullscreen_2.xml, AnkiDroid/src/main/res/layout/reviewer_fullscreen_1.xml, AnkiDroid/src/main/res/layout/reviewer_fullscreen_2.xml
=> Remove margins for whiteboard/gestures when not fullscreen

AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java
Fixes [this](https://groups.google.com/forum/#!topic/anki-android/YZUsGyjOsuI).
=> Fix unclosable deck options on new filtered deck

AnkiDroid/src/main/res/drawable/footer_button_all_black.xml, AnkiDroid/src/main/res/values/theme_black.xml
I've made the currently selected deck and the answer button borders a little brighter.
=> Adjust black theme colors

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioView.java
Saw a couple Play Store reviews mentioning this bug.
=> Fix being unable to replay newly recorded sound

AnkiDroid/src/main/AndroidManifest.xml, AnkiDroid/src/main/res/drawable/footer_button_all_black.xml, AnkiDroid/src/main/res/values/theme_black.xml
Set dev branch to 2.7dev and make black theme colors a little brighter yet again.
=> Version bump and color tweaks

.travis.yml, AnkiDroid/build.gradle, api/build.gradle, build.gradle
Fixes https://github.com/ankidroid/Anki-Android/issues/4330 but reopens https://github.com/ankidroid/Anki-Android/issues/4217.
I'd rather fix the crashes than the minor aesthetic issue.
=> Update support libs and SDK versions

AnkiDroid/src/main/res/values/03-dialogs.xml
Closes https://github.com/ankidroid/Anki-Android/issues/4313
=> Remove donate link

AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java
- Made sure the button colors are the same static colors
- Fixed no buttons to allow flipping when previewing from template editor
- Added some range checks
=> Fix colors and missing buttons in previewer

AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.java
Fixes https://github.com/ankidroid/Anki-Android/issues/4378
=> Fix missing default value in deck options

.travis.yml, AnkiDroid/build.gradle, api/build.gradle, build.gradle
The sooner we test them the better.
=> Update build tools and support libraries

AnkiDroid/src/main/java/com/ichi2/libanki/importer/AnkiPackageImporter.java
This fixes a bug where subsequent apkg imports after the first one fail with  `This isn’t a valid apkg file`. We are leaking a database connection which is preventing the temporary data directory (where the zip data is extracted) from being created on the next run.
I'm honestly stumped by why this started happening. It was only on one of my devices and it was the one I used to extensively test importing while I was in the process of reworking it last time.
=> Fix database connection leak while importing

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
Fix for [this](https://groups.google.com/forum/#!topic/anki-android/NtcqOX_haIk).
=> Improve tag modification check when closing note editor

AnkiDroid/src/main/res/values/10-preferences.xml, AnkiDroid/src/main/res/xml/cram_deck_options.xml
=> Clarify "custom steps" option.

AnkiDroid/build.gradle, AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.java, AnkiDroid/src/main/java/com/wildplot/android/rendering/PieChart.java, AnkiDroid/src/main/java/com/wildplot/android/rendering/graphics/wrapper/GraphicsWrap.java, AnkiDroid/src/test/java/com/wildplot/android/rendering/FloatMatcher.java, AnkiDroid/src/test/java/com/wildplot/android/rendering/PieChartParameterizedTest.java, AnkiDroid/src/test/java/com/wildplot/android/rendering/PieChartTest.java, AnkiDroid/src/test/java/com/wildplot/android/rendering/PieChartTestParametersBuilder.java
Fixes #4319 
- Fix sectors drawing when there are zero values
- Make `PieChart` clients responsible for providing a complete color legend
- Add local unit tests
=> Fix pie chart in statistics

AnkiDroid/build.gradle, AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java, AnkiDroid/src/main/java/com/ichi2/compat/Compat.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV10.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV11.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV15NookHdOrHdPlus.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV16.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/DB.java, AnkiDroid/src/main/java/com/ichi2/libanki/hooks/AdvancedStatistics.java
It's now or never I suppose. I really want to try this out and see how it goes.
See https://github.com/ankidroid/Anki-Android/issues/4332 for more details.
Only real downside I can think of is the added 2MB to the APK.
=> Use SQLite support library

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
=> Show syncMessage when it's present

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerExportCompleteDialog.java, AnkiDroid/src/main/java/com/ichi2/utils/Files.java
=> Fix bugs moving exported apkg from internal to external storage

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerExportCompleteDialog.java, AnkiDroid/src/main/res/values/02-strings.xml
Also updated the error message to fix #4561
=> Show relative path to export directory when possible

AnkiDroid/src/main/res/values/16-multimedia-editor.xml
=> Delete the strings about "Image search activity"

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/res/menu/popupmenu_multimedia_options.xml, AnkiDroid/src/main/res/values/16-multimedia-editor.xml
Second attempt at adding the option to insert clozes. (First attempt [here](https://github.com/ankidroid/Anki-Android/pull/4598))
Fixing issue https://github.com/ankidroid/Anki-Android/issues/2520
=> Add insert cloze option to the paperclip menu

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
I just recreate the menu by calling onCreateOptions menu when the searchView is collapsed.
=> Issue #4579 solved: add icon will not disappear after the search

AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java
Deck id was not set when the statistics for "all decks" was chosen.
=> Fixes #4515: bug fixed

AnkiDroid/src/main/assets/card_template.html, AnkiDroid/src/main/assets/scripts/card.js
=> Hide flashcard title and <hr> tag from TalkBack.

AnkiDroid/src/main/AndroidManifest.xml
Rename the name of the card type editor's checkmark from "OK" to "Save".
Fix #4670.
=> Edit the name of the card type editor's checkmark

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java, AnkiDroid/src/main/res/xml/filepaths.xml
=> Fix crash on add picture from camera on Android 7

AnkiDroid/src/main/assets/card_template.html, AnkiDroid/src/main/assets/scripts/card.js
=> Revert "Hide flashcard title and <hr> tag from TalkBack."

AnkiDroid/src/main/AndroidManifest.xml
It seems recently Google Drive is using this new MIME type
=> Add application/vnd.anki MIME type to manifest

AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.java
=> Avoid creating a new deck when user renames a note type

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronounciationActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/beolingus/parsing/BeolingusParser.java, AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/beolingus/parsing/BeolingusParserTest.java
A single regular expression is worth 50 lines of code.
The newly added test also worked with the old code.
=> Clean up Beolingus parser

AnkiDroid/src/main/AndroidManifest.xml, AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/compat/Compat.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV10.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV23.java
I tried my hands at https://github.com/ankidroid/Anki-Android/issues/4496, but that’s as far as I can get. See commit message for the problem.
Basically I can’t find a way to add the callbacks to the action mode. Also, I have no idea what action mode I’m looking at.
I thought about tracking for long presses, but then the question becomes how to still get the text selection functionality.
@timrae: Maybe you have an idea how to implement this functionality?
=> WIP: Search in Card Browser for highlighted text from Review mode

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
fixes #4691, #4731
editing the template seems to work, so the size limit only appears to
be when reading the column, not writing to it
=> load note types in chunks

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
parameterized new loadModels method from @dae  so it could load any column,
used new parameterized method to load models as before, but also to
load decks, as hinted by @timrae
=> Further work on #4691 / load deck types in chunks

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/NoteEditorRepositionCard.java, AnkiDroid/src/main/res/menu/note_editor.xml, AnkiDroid/src/main/res/values/02-strings.xml, AnkiDroid/src/main/res/values/03-dialogs.xml
Can reposition the card from the note edit context menu
=> Added card repositioning

AnkiDroid/src/main/assets/scripts/card.js
@JLRishe
I think it's ok to revert this now that the webview has been fixed right?
=> Revert "Proposed fix for #4624 - fix scrolling when showing answer

AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java
This occurred on my Nexus 5X sometimes although the operation worked on retries.
Fixed by retrying the operation a set number of times before it fails.
(see issue #4782)
=> Fixed issue where File.createNewFile() sometimes caused an IOException

.idea/codeStyles/Project.xml
I sincerely hope this was a small oversight and is not "the first of many".
My research indicated sharing these files by default works well in practice, but obviously if they get updated all time (generating PRs like this) then it fails in practice for us.
if you're willing to go down the "try it for a while" path a bit farther then please merge this and we'll see if the file stays quiet for a longer period of time afterwards
=> Update codestyle, small addition auto-added by AndroidStudio

AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java
If you attempt to modify the schema in a way that requires a full sync, it will throw an exception unless the user can accept that. This just makes the error message more specific so we don't spend a lot of time responding to API user confusion
Mitigation for Issue #4889 
A real fix would involve a new Intent that gathers user acceptance of the full sync
=> Specify reason for exceptions on schema mods

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/AnkiDroidCrashReportDialog.java
Per [my comment](https://github.com/ankidroid/Anki-Android/pull/4995#issuecomment-425114853) on the merged androidx PR #4995 - I wanted to make sure future people (or just me) were aware of the androidx/ACRA interaction
If a code comment + the wiki is too much that's fine but I wanted to offer it in case
=> Add note about androidx/android.support interaction

AnkiDroid/build.gradle, AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
Upgrade ACRA from 5.2.0 to 5.2.1
Fixes https://github.com/ACRA/acra/issues/703 - a limiter bug related to native crashes that I noticed and logged with them
=> Upgrade ACRA to 5.2.1, more specific limiter clear note

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
See discussion at https://github.com/ankidroid/Anki-Android/commit/090c130f326316a41aa1770357b239274f8639a1#r31096390
=> Fix incomplete startup control flow

AnkiDroid/build.gradle
Continuing to track dependencies pretty quickly while we're in alpha
=> Bump appcompat from 1.0.0 to 1.0.1

AnkiDroid/build.gradle, api/build.gradle
Staying up to date pretty quickly while in alpha - these are all minor bumps
=> Dependency updates (powermock, robolectric, okhttp)

AnkiDroid/build.gradle, api/build.gradle
Weekly updates - still maintaining high tempo during alpha
=> Dependency updates (JUnit 5.3.2, diff-match-patch 1.2)

AnkiDroid/build.gradle
Bumps annotation from 1.0.0 to 1.0.1.
Signed-off-by: dependabot[bot] <support@dependabot.com>
=> Dependency Updates - annotation, mockito-core, requery

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
Ankiweb and Anki Desktop select the text in a Card using the css selector `#qa`, while AnkiDroid previously used `.question` and `.answer` to do the same.
CSS selectors in the AnkiDroid review display differ from CSS selectors on AnkiWeb and Anki Desktop. Users wishing to customize the display of their cards (e.g. large print text) were experiencing different behavior on different Anki platforms.
https://github.com/ankidroid/Anki-Android/issues/4721
Added an ID `qa` to the `div` that contains the questions and answers. Left the `question` and `answer` classes on the divs for backwards compatibility.
Please describe the tests that you ran to verify your changes. Provide …
=> Match Anki lib css selectors on cards, Fixes #4721

AnkiDroid/build.gradle
Point release for okhttp
Bring powermock to release status
These are tested in CI then I merge them unless they are large version changes
=> Dependency updates 20190108

AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/libanki/ImportTest.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/exception/ImportExportException.java, AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.java, AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java, AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/SchedV2.java, AnkiDroid/src/main/java/com/ichi2/libanki/Stats.java, AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java, AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java, AnkiDroid/src/main/java/com/ichi2/libanki/importer/AnkiPackageImporter.java, AnkiDroid/src/main/java/com/ichi2/libanki/importer/Importer.java, AnkiDroid/src/main/res/values/02-strings.xml, AnkiDroid/src/main/res/values/06-statistics.xml
This completes the work for #4905 and brings it to parity with upstream. I will post a note on #4905 that is important for anyone using the new scheduler.
I've done some testing of import and export with V1 and V2 col/apkg and the behavior appears to be in line with the desktop client (with the exception of the .colpkg naming scheme).
=> SchedV2 - Add import/export support, update graphs, db checks, bug fix

AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java, AnkiDroid/src/main/java/com/ichi2/libanki/SchedV2.java
=> Fix schedv2 internal subdeck building

AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/res/xml/preferences_advanced.xml, AnkiDroid/src/main/res/xml/preferences_appearance.xml, AnkiDroid/src/main/res/xml/preferences_general.xml, AnkiDroid/src/main/res/xml/preferences_gestures.xml, AnkiDroid/src/main/res/xml/preferences_reviewing.xml
The font and language preferences were showing XXX instead of the actual value when the default was being used. The XXX's were unnecessary in the first place so I removed them as well.
=> Fix incorrectly displayed preferences

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV19.java, AnkiDroid/src/main/res/values-v21/styles.xml
=> A few minor bug fixes

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/res/xml/preferences_advanced.xml, AnkiDroid/src/main/res/xml/preferences_appearance.xml, AnkiDroid/src/main/res/xml/preferences_general.xml, AnkiDroid/src/main/res/xml/preferences_reviewing.xml
Fixes bugs introduced by #5076 
Reverts changes from #5244 and #5246
Closes #5247  (no longer necessary)
=> Preferences refix

AnkiDroid/build.gradle, api/build.gradle, build.gradle
Just a bunch of minor non-noteworthy updates.
No code changes needed to adapt this time.
Dependabot + Travis helping us with the unglamorous chores...
=> 20190319 Dependency updates

AnkiDroid/build.gradle
Solve incompatibilities issue with Gradle 6, I haven't found solution for last 2 remaining deprecation in the issue, open for discussion
https://github.com/ankidroid/Anki-Android/issues/5238
Change with new methods
running jacoco command as described in the issue
=> Partially Solve #5238: Gradle 5 incompatibilities 

AnkiDroid/src/main/assets/card_template.html
Fix typo in card_template.html
n/a
=> Fix typo in card_template.html.

AnkiDroid/src/main/java/com/ichi2/libanki/SchedV2.java
https://github.com/dae/anki/commit/bcb422beda19e5f411d9364f638de7831677d7a9
=> fix learn steps being assigned on relearn in v2

AnkiDroid/build.gradle
Minor bumps to sqlite-android and the play store uploader
@timrae these seem small but because it involves the play store uploader, and there's a bugfix for sched v2 queued as well, might be a good time to do a alpha bump? Just to make sure I didn't blow up publishing (or if I did I can roll it back before I forget this change was the culprit...)
=> 20190511 Dependency updates

AnkiDroid/build.gradle, build.gradle
Mostly minor bumps, pulling these changes now instead of aggregating further because the gradle-plugin has R8 (the new code shrinker) changes and I'm keen to stay current there since that is fundamental and R8 is relatively new.
=> 20190516 Dependency updates

AnkiDroid/src/main/java/com/ichi2/libanki/SchedV2.java
https://github.com/dae/anki/commit/ef10d76edb86ebc379d3ca195b7e44a952a6da02
=> fix v2 lrn scheduling bug

AnkiDroid/build.gradle
Standard dependency update PR, pooled from dependabot
This will be the last one on a semi-weekly tempo if we go beta shortly as planned, I'll switch to a cadence that is aligned with future alpha/beta plans vs just time periods and favor stability (patches, maybe minors) vs current freshness disposition (majors even if change required)
I rely on travis to prove these out
=> 20190627 Dependency updates (okhttp, junit, analytics)

AnkiDroid/build.gradle, api/build.gradle
Takes appcompat to release candidate status which seems important... 
=> 20190703 Dependency updates

AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java, AnkiDroid/src/main/java/com/ichi2/compat/Compat.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV15.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.java
#5021 
Update compatibility for deprecated `TextToSpeech#speak` method
This is WIP or "pre-review" purpose for @mikehardy 
The TTS functionality works as expected (tested manually) on API 19 and API 28 (emulators)
=> Move Text to speech API

AnkiDroid/src/main/java/com/ichi2/libanki/SchedV2.java
One from yesterday, one from a while ago but didn't feel was very urgent.
=> Schedv2 fixes

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
Add a prompt on upgrading to vote in the icon poll. I'm requesting to merge this directly into the beta branch, and I will revert it before the final release in favor of a link in the release notes.
Following through on my promise to @martindisch in #5110
Ran it on the emulator, should be fine
=> Prompt to vote in icon poll

AnkiDroid/src/main/java/com/ichi2/libanki/Consts.java, AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java, AnkiDroid/src/main/java/com/ichi2/libanki/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/SchedV2.java, AnkiDroid/src/main/java/com/ichi2/libanki/hooks/AdvancedStatistics.java
Follow anki code.
No test. Replacing a literal by a constant doesn't require any. It builds, that's enough for me.
=> use a constant for the starting factor

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java, AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java, AnkiDroid/src/main/res/values/02-strings.xml, AnkiDroid/src/main/res/values/07-cardbrowser.xml
Answer feature request #5542
Adding an option with code similar to the other options
This has been tested by starting Ankidroid, openining the Browser with
a real collection, and checking that I can select interval and see
their values correctly.
=> Add interval as a potential second column in the browser.

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
I don't intend to test this commit. I believe it speaks for itself.
=> Adding missing Throw

AnkiDroid/src/main/java/com/ichi2/libanki/Models.java
dae/anki@fed2f2fa3dca844cd2fdb397930a67d452c9bbce
Mainly following Anki code
Factorize some code which were redundant
In a VM, trying to create a note type basic and reversed, and a note type basic (optional reversed card)
=> Factorize standard model creation

AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.java
This commit simultaneously corrects two problems, in which Ankidroid
differs from Anki.
When a standard model is constructed, Anki add random symbols only if
the model's name is already used in the collection. This is now the
case in Ankidroid too.
When a model of name m is cloned, if "m - copy" already exists, then a
random string is appended. This is now the case in Ankidroid too.
The suggested name is computed first.
If it's clone, then "string.model_clone_suffix" is suffixed.
If it's already a model name, a string is added
This name is then shown to the user.
* Deleting standard note type
* Creating a standard note type. Seeing that there is no random string
* creating the same note type again, seeing there is a random string
* copying twice the same note type. Seeing there is a …
=> New model: more simple and more unique

AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java, AnkiDroid/src/main/java/com/ichi2/libanki/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/SchedV2.java
Keeping up to date with anki.
#5511
By imitating Anki code. Doing the correction of deck outside of dueDeckList
Simply by checking that i can still correctly see the main deck.
I didn't try to reproduce the bug, as I don't want to waste time creating so many faulty decks. Anyway, it's clear there is no recursion anymore
=> Correct deck due list

AnkiDroid/build.gradle
Standard trickle of patches from the outside world.
No reason to publish on stable branch
Still good to feed them in when possible as they arrive to test small changesets
Should have no affect on anything but worth noting that the play publishing plugin appears to be more active now. This is a feature release for them.
=> Dependency updates 20191031

AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java, AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java, AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java, api/src/main/java/com/ichi2/anki/FlashCardsContract.java
When I find typos, I intend to correct them in this branch
Nothing to test here, really. No code change.
=> Typos correction

.travis.yml, AnkiDroid/build.gradle, AnkiDroid/jacoco.gradle, AnkiDroid/src/test/java/com/ichi2/compat/CompatCopyFileTest.java, AnkiDroid/src/test/java/com/ichi2/libanki/UtilsTest.java, build.gradle, tools/upload-codacy-report.sh
Expand Travis testing to run unit tests on all supported dev environments (macOS, linux, windows)
Additionally, optimize travis to run unit tests separately from instrumented tests to increase efficiency
Not sure this was logged anywhere but @sudomain noticed unit tests failed on windows in relation to #5352 / #5460 
I wasn't happy with the pile of jacoco stuff in build.gradle and I split that out to a separate gradle file as well
@sudomain discovered that our unit tests don't work on windows but we couldn't surface it because installing JDKs and getting environments built up in Travis CI was a real pain
@Overflow0xFFFF made it so getting environments set up was easy in #5594 
So I built on #5594 by splitting the testing into just unit or just instrumented test runs in Travis, then added …
=> Support windows as dev environment

AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java
dae/anki@a5b0852360b132c0d04094f5ca8f1933f64d7c7e
As explained in the commit, I can't find how to compress file in Zip, so it's only a partial port of anki's commit. However, it at least follows anki by factorizing this part of the code
As in Anki
gradlew.
In ankidroid, I selected a deck with a card with an image. I exported it.
I took the apkg file in the computer and imported it in anki. It worked perfectly, the image and cards were still here.
=> Porting exporting

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
There's an issue on API access on first access, or maybe if Ankidroid wasn't opened for a while.
#5465
Adjusts creation steps per Hanping.
It has not been tested.
=> Reorder API creation steps to fix accessing models on first access.

AnkiDroid/build.gradle
Weekly batch - this one has another publishing update but I'm gaining confidence in those after they re-started development, no problems...yet
This one alters recyclerview and I manually checked it with lots of scroll on a large deck - it seems fine?
=> Dependency updates 20191202

AnkiDroid/src/main/java/com/ichi2/libanki/SchedV2.java
=> Fix SchedV2 rev limit deck ID overflow

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/java/com/ichi2/anki/services/BootService.java, AnkiDroid/src/main/java/com/ichi2/anki/services/NotificationService.java
Just committing what I did while reviewing #5642
=> Don't use magic numbers for notifications in java code

AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java
Remember the index of cards while screen orientation changed
#5688 
=> Add saving and reloading state in Previewer, fix issue #5688

AnkiDroid/build.gradle, api/build.gradle
Tracking dependencies bit by bit
CI - all semver patch versions so should not be a problem
=> Dependency updates 20200120

AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java, AnkiDroid/src/main/java/com/ichi2/anki/services/ReminderService.java
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/95855f86-64b7-4b29-be03-776c63135b1c
```
java.lang.RuntimeException: Unable to start receiver com.ichi2.anki.services.ReminderService: java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
at android.app.ActivityThread.handleReceiver(ActivityThread.java:3194)
at android.app.ActivityThread.-wrap17(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6494)
at java.lang.reflect.Method.invoke(Native Method)
at …
```
=> Avoid crash if collection closes while reminder is building

AnkiDroid/src/main/java/com/ichi2/compat/customtabs/CustomTabActivityHelper.java
Apparently you can get a SecurityException now when trying to use CustomTabs
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/42d35713-087d-43dd-abfd-e3f7a82ea8f2
```
java.lang.SecurityException: Not allowed to bind to service Intent { act=android.support.customtabs.action.CustomTabsService pkg=com.chrome.canary }
at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1740)
at android.app.ContextImpl.bindService(ContextImpl.java:1650)
at android.content.ContextWrapper.bindService(ContextWrapper.java:705)
at androidx.browser.customtabs.CustomTabsClient.bindCustomTabsService(CustomTabsClient.java:3)
at com.ichi2.compat.customtabs.CustomTabActivityHelper.bindCustomTabsService(CustomTabActivityHelper.java:4)
at …
```
=> Avoid crashing if initialization of CustomTabs fails

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java, AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckDropDownAdapter.java
I just had a problem hard to debug because the original exception was
lost. I correct it globally.
Some exceptions are catched and then throws as runtimeexception. This occurs often a lot with the JSON library where almost every methods throw catchable exception (at least until my PR is accepted)
And in a few case, the coders forgot to resend the original exception. Because of that, it became hard to debug it. I thus correct it.
Throwing the initial exception
I installed this version on my phone. Did the same action, and got the actual exception instead of the runtime one
=> Try catch throw catched exception

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
I was trying to debug a bug in one of those edited code, and decided to clean it. It does help by having slightly less indirections during the debugging process. Not an important PR.
=> replace current().getLong("id") by .selected()

AnkiDroid/build.gradle
This clears out my stack of possible dependency updates, test only on this one
=> Dependency Updates 20200302

AnkiDroid/src/main/res/values/01-core.xml, AnkiDroid/src/main/res/values/02-strings.xml, AnkiDroid/src/main/res/values/17-model-manager.xml
In a few places, Ankidroid did use words which should not be shown to the user. They are the word used in json, in the code, but not in anki's interface. I correct it.
Replacing bad words by good words.
It has not. Those are strings.
=> Removing model word

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java
As explained in #5694 here I ensure that sounds are considered as image in the card browser
=> Card browser: consider sounds as we consider images

AnkiDroid/src/main/java/com/ichi2/libanki/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/SchedV2.java
#Purpose / Description
Avoiding useless code
The variable mBurySiblingsOnAnswer is set to true and then never
changed.
It's tested twice, one where code is executed only if it's
falsy (i.e. never) and once where code is executed if it's
truthy (i.e. always)
I did remove the useless variable, the code never executed, and remove
the test before the code always executed
In a deck where siblings get buried, review. In one where sibling don't get buried, review. In first deck, check that you see a single card by note. In the second that you see two siblings.
=> Removing an unused variable

AnkiDroid/src/main/assets/scripts/card.js, AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
5816  Call Show Answer / displayCardAnswer() funtion from AnkiDroid card webview using javascript
After implementing HanziWriter.js in Ankidroid. Check [Anki-maobi](https://github.com/infinyte7/Anki-maobi) . I came to know that user have to manually click show answer. But I wanted that after completion of drawing stroke of characters, It automatically move to next card or show back side of card.
Also I want to implement showAnswer for Ease_1, Ease_2, Ease_3, Ease_4 as per user done mistake in drawing strokes of characters.
https://github.com/ankidroid/Anki-Android/issues/5816
1. Added the following in card.js in assets folder
```
/* function to show answer using js */
function showAnswer() {
window.location.href = "signal:show_answer";
}
function buttonAnswerEase1() {
window.location.href …
```
=> Add ability to answer cards via javascript in WebView

AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java
There was a NPE assuming that the view was not null. This assumption does not hold.
We also remove an unused method (loading preferences) on View Load. This was removed in #555 (https://github.com/ankidroid/Anki-Android/commit/2da08a086c417acc42de813d2714a3ce7261947f).
Fixes #5506
* Check for null and exit before we perform any view logic.
* Mark variable as nullable so it won't happen again
This is not tested, since I could not replicate the failure condition on my device.
Please see each commit for the logical steps in refactoring.
=> Fix #5506 NullPointerException in StudyOptionsFragment

AnkiDroid/src/main/java/com/ichi2/libanki/Card.java
Correcting https://github.com/ankidroid/Anki-Android/pull/5832#issuecomment-601917182
=> correct MS to S

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DialogHandler.java
Attempting to diagnose issue #5895
N/A
Adds logging
Tested on my device, log output was minimal (as expected).
=> Add logging to DialogHandler

AnkiDroid/src/main/java/com/ichi2/libanki/AbstractSched.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java
There was a collision between two PRs that were created at vastly different times, this just trues them up
=> Fix object-oriented collision of #5860 and #5612

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioClipFieldController.java
Crash due to NPE in `finally` block
Fixes #5903
Auto null check
Untested 🤠
=> Fix NullPointerException on Audio Recording Result

AnkiDroid/src/main/java/com/ichi2/libanki/Sched.java
I was pretty sure I double checked all commits to avoid this kind of error specifically.
Sorry
=> Debug: A constant was in a string by accident. Moved out of the string

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/SchedV2.java, AnkiDroid/src/main/java/com/ichi2/libanki/Stats.java
Fixes a few hardcoded string constants introduced in the large refactoring: #5888.
Performed by an Android Studio Project search for `Consts.` in string constants
Only visual inspection
=> Additional string constants Fixes

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java, AnkiDroid/src/main/java/com/ichi2/anki/VideoPlayer.java, AnkiDroid/src/main/java/com/ichi2/anki/exception/ManuallyReportedException.java, AnkiDroid/src/main/res/values/03-dialogs.xml, AnkiDroid/src/test/java/com/ichi2/anki/AnkiDroidAppTest.java
#5911 raised an unexpected error in VideoPlayer, we log to see how this happened, and attempt to fix it
Fixes #5911 
Null check & Logging
Couldn't reproduce or logically reason through how it happened. 🛑
=> Fix NullPointerException in VideoPlayer

AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/ContentProviderTest.java, AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.java, AnkiDroid/src/main/java/com/ichi2/libanki/Models.java, AnkiDroid/src/main/java/com/ichi2/libanki/StdModels.java, AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java
Anki code contains the comment
> // AnkiDroid doesn't have stdmodels class or model name localization, this could be much cleaner if implemented
One part was fixed in earlier commit: name localization
This one fixes the absence of stdmodels
stdmodels do more here than in Anki, because java is more verbose, because of the way it deals with optional parameters (named parameters in Python). So the class StdModel allows to create new std models, add them to the collection, and contains static StdModel variable for each standard model, and a list of standard model.
This allow to loop over the list of standard models instead of having to add them manually, and this allow to access the resources at a single point. 
Creating a class, whose constructor takes as parameter the default name (as a …
=> Factorize std model

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.java, AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
I'm struggling to make sense of some crash reports due to the lack of information. This adds logging to common user interaction paths.
Also quietens one line in CardBrowser (no flag value for cards)
N/A
Log statements
On my device, logs appear as expected
=> Log User Interactions To Assist Debugging

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
Mostly guided by desires in #5951
=> NF: Logging improvements

AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
Profiling Ankidroid, I realized that ankidroid spent 12 seconds on
startup in the method normalize. That's far too much. I actually have
trouble believing the profiler here. (More precisely it mostly spent
time in "toLowerCase")
Anyway, I added this simple caching method, so that it becomes far
quicker. After all, caching is not context dependant, it always give
the same output to the same input, so we never have any need to empty
the cache, so that's perfect here
Anki startup still takes more than half a minute
Profiling and checking where time is spent
Installing on the phone and using it. Looking at profiler and realizing that the time decreased in this method.
Profilers are hard to use
=> Cache name normalization

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java, AnkiDroid/src/main/res/values/03-dialogs.xml
Logging to diagnose the cause of #5959
Also, displays a crash report rather then crashing.
Fixes #5959 (at least, fixes the crash, but not the cause)
Logging, and an exception report/toast if an issue is found.
On my device, custom study still works
=> Diagnose and avoid crash for deck with no terms

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
Collapsing a deck is an extremely long process (I've more than 200 decks), and it does not need to since there is nothing to recompute. 
It gets quicker
Currently, collapsing a deck calls `updateDeckList`. This methods
recompute the number of cards to review in each deck and subdecks. On
my collection, it's a 30 seconds long operation. This operation is
totally useless when decks get collapsed since this does not change
the deck hierarchy at all.
I just took a part of the postExecute method which updates the view
and put it in an external function `__renderPage`. The method
`__renderPage` is called from `updateDeckList`'s `onPostExecute` and
when a deck is (un)collapsed. This decrease collapsing down to under a
second on my phone.
In order to allow `__renderPage` to do its computation, a …
=> Collapsing a deck get quick

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
Being able to use the debug part of logcat to actually debug
Moving very verbose strings from debug to verbose.
It has not. There is nothing to test here.
=> Long string from debug to verbose

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java, AnkiDroid/src/main/java/com/ichi2/utils/WebViewDebugging.java
I want to use this code in the Visual Editor. 
I also lowkey want to make AbstractFlashCardViewer have less code as it's hard to understand.
Extract method, and add a call on startup.
Printf performance testing, not great, but didn't want to spend too much effort
```
On
2020-04-10 18:14:14.086 14245-14245/com.ichi2.anki V/AbstractFlashcardViewer: WebView Debugging Start
2020-04-10 18:14:14.089 14245-14245/com.ichi2.anki V/AbstractFlashcardViewer: WebView Debugging End
Off
2020-04-10 18:13:21.455 12541-12541/com.ichi2.anki V/AbstractFlashcardViewer: WebView Debugging Start
2020-04-10 18:13:21.456 12541-12541/com.ichi2.anki V/AbstractFlashcardViewer: WebView Debugging End
On+Startup
2020-04-10 18:10:45.411 10258-10258/com.ichi2.anki V/AbstractFlashcardViewer: WebView Debugging Start …
```
=> Factor out WebView Debugging

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java, AnkiDroid/src/main/java/com/ichi2/anki/UIUtils.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java, AnkiDroid/src/main/java/com/ichi2/async/Connection.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java, AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java, AnkiDroid/src/main/java/com/ichi2/libanki/importer/Importer.java
This class was created in 2009. If I understand code history correctly
"Deck" has been renamed to "Collection" and what is called "deck"
today is totally distinct.
This commit was done using android studio, so I am quite confident it
did not miss anything. And I hope it'll make the code slightly less
confusing for newcomers. (I actually lost 5 minutes trying to figure
out where to put an async task for a non deck-related task)
=> Rename DeckTask to CollectionTask

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java, AnkiDroid/src/main/java/com/ichi2/anki/UIUtils.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java
This is a follow up of PR https://github.com/ankidroid/Anki-Android/pull/5989 
I did realize that I should have searched for "DeckTask" every where and replaced it by Collection Task. Otherwise some comments and method names made no sens
=> CollectionTask

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.java
Switching reflection for method invocation.
This was intended to be part of a larger PR significantly speeding up tests in the class, but I need to do more reading about Java TestRunner/Robolectric best practices.
=> TESTONLY: Speed up typeAnsAnswerFilter calls

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
Those are not in upstream and are not called anywhere.
This has not been tested by me; there is nothing to test.
=> remove renderQA

AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.java
This was originally intended to be a lint fix, but raised that we use `intent.getData()` rather than using the provided data URI.
This will both make the lint check in the file green, and should fix some import issues.
Untested 👎
=> Fix Import errors in ImportUtils

AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java, AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java, AnkiDroid/src/main/java/com/ichi2/preferences/NumberRangePreference.java, AnkiDroid/src/main/java/com/ichi2/themes/HtmlColors.java, AnkiDroid/src/main/java/com/ichi2/utils/DeckComparator.java, AnkiDroid/src/main/java/com/ichi2/utils/DeckNameComparator.java, AnkiDroid/src/main/java/com/ichi2/utils/JSONArray.java
Various lint fixes, all automated by Android Studio, but visually confirmed.
=> NF: Lint fixes

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
This PR is similar to the PR "deck" to "collection"; even if this mistake was less confusing since there is no notion of "fact" anymore in anki.
Note that I won't do the same kind of PR for "model" since upstream still uses "model" in the code. However, "fact" is not used anymore (appart in some tests, I admit) so I believe that this PR is beneficial to ankidroid's code quality.
This has not been tested in any particular way, given that I only rename variables (all variables are renamed using android studio, in order to ensure they are replaced everywhere simultaneously)
=> Renaming "fact" to "note"

AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/ContentProviderTest.java, AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.java, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java, AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java, AnkiDroid/src/main/java/com/ichi2/libanki/importer/AnkiPackageImporter.java
Sometime, the file name is given explicitly instead of using a constant. This is corrected in the first commit.
Second commit factorize a code part which appears 13 times identically in all the code.
=> Collection filename / getCol refactor

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
Removing a constructor never called. And a constructor never called appart in the above-mentioned constructor.
=> remove some useless constructors

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
This is equivalent; we simply check whether an ord is negative or at
least equal to the number of element
=> Preparing query in basicCheck

AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
It's a purely syntactic change, that I thought to be necessary while doing more interesting PR.
=> Simplify slightly the code

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
Comment only change. Non-Functional
=> LINT: Remove lint error from Reviewer

AnkiDroid/proguard-rules.pro, AnkiDroid/src/androidTest/java/com/ichi2/ui/ActionBarOverflowTest.java, AnkiDroid/src/main/assets/card_template.html, AnkiDroid/src/main/assets/flashcard.css, AnkiDroid/src/main/assets/scripts/card.js, AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtonStatus.java, AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtons.java, AnkiDroid/src/main/java/com/ichi2/anki/reviewer/CardMarker.java, AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ReviewerUi.java, AnkiDroid/src/main/java/com/ichi2/ui/ActionBarOverflow.java, AnkiDroid/src/main/res/layout/reviewer_topbar.xml, AnkiDroid/src/main/res/menu/reviewer.xml, AnkiDroid/src/main/res/xml/preferences_custom_buttons.xml
* Changes requested in #5806 
* Remove HTML/SVG, and place mark/flag in top bar
* Set Default for "Flag" to "Always", and "Mark" for "If Room"
* Switch the places of Mark and Flag 
EDIT:
* Add logic to remove duplicate icons if visible in the Action Bar.
Fixes #5806 
We switch the HTML/SVG for an icon in the top bar. This icon is invisible if no flag/mark is selected.
On my Android:
* [Vertical](https://user-images.githubusercontent.com/62114487/78401869-89f00c80-75f1-11ea-8366-9ac1110d4a54.png)
* [Horizontal](https://user-images.githubusercontent.com/62114487/78401793-688f2080-75f1-11ea-8b38-9617f90cdf0b.png)
* [With Menu](https://user-images.githubusercontent.com/62114487/78401809-6cbb3e00-75f1-11ea-86af-9f2c28cc9fdf.png)
https://developer.android.com/reference/android/widget/TextView#at …
=> Move Flag/Mark icons to TopBar and reorder Flag

AnkiDroid/build.gradle, build.gradle
Typical feed-in of updates over time - this time it's nothing but gradle plugin and our publishing plugin (which I worked on with upstream to fix a problem, so I know it works)
We're set up really well from a dependency standpoint for a 2.10 branch cut
=> Dependency updates 20200420

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/Consts.java, AnkiDroid/src/main/res/values/02-strings.xml, AnkiDroid/src/main/res/values/03-dialogs.xml, AnkiDroid/src/main/res/values/constants.xml
This fixes any occurrences of #5932 which have already occurred.
And leaves a variable free to perform a notification with
Fixes  #5932
FixIntegrity check
Tested on my personal collection.
Also tested on a corrupt collection, which it fixes.
=> Add integrity check: ensureCardsHaveHomeDeck

AnkiDroid/src/main/java/com/ichi2/libanki/DB.java
.anki was dropped in 2016
This was not tested
Note that I know understand that simple commits should be submitted separately and not with interesting ones
=> correct .anki to .anki2

AnkiDroid/src/main/java/com/ichi2/libanki/template/Template.java
In order to simplify the logic behind https://github.com/ankidroid/Anki-Android/pull/6130#issuecomment-626148172 I thought it would be easier to first consider a PR which does not change anything to the way the code works, but which simplify the code itself.
Normally, you can check each commit. None change anything to the way the code behaves. However, all of them simplify the code.
=> Simplify render

.github/issue_template.md
Suggest that users check the behaviour in the latest alpha before submitting a bug report.
Preview: https://github.com/david-allison-1/Anki-Android/blob/issue-template-beta/.github/issue_template.md
=> Issue template: Suggest checking alpha release before reporting

.travis.yml
There was a failure created by #5566 in combination with #6164 and it is the sort of thing (testing localizations) that individual developers are bad at but a CI system is good at. So this adds our most popular localizations to the Travis config, one per emulator
Related to #5566, #6164
It is not possible to boot an emulator with a given locale but you can switch the locale programmatically post-boot.
On my linux machine manually, then in my personal Travis instance to verify
https://stackoverflow.com/a/41654303/9910298
=> Run various different locales in Travis

AnkiDroid/build.gradle
Keep up to date with dependencies
This one includes appcompat which is always good to get out of the way early in a release cycle
=> Dependency updates 20200505

AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java
Debug logging was drowned out by this statement when diagnosing an issue.
=> LOG: Use Verbose when logging HTML

AnkiDroid/src/main/java/com/ichi2/anki/contextmenu/CardBrowserContextMenu.java
Missed this is my self-review of 2846d760a85abaf78a62ce0a27a2d7b72c4b295c
=> Log Exception: getSystemMenuStatus

AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java
I believe we his a few race conditions around this area, and knowing that we started the operation wasn't sufficient
=> LOG: Log begin and end of setting mCollection

AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
Done in Anki Desktop: Caused too much confusion to new users
https://github.com/ankitects/anki/commit/3b29bf6cba9092b518cf404ee4a5fbd3368c88d1
Fixes #6236
Follow upstream
On my device
I need to get better at isolating variables while debugging. Lots of missteps with the assumption that the name of the collection didn't matter, and assuming that import/replace failed
We need to have some way of tracking/communicating breaking changes upstream.
=> Default Sibling Burying to 'Off'

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java
Feature Request: working combination of auto-advance and text to speech
Fixes #6087
Initialize TTS in AbstractFlashCardViewer.java and set UtteranceProgressListener in this class.
Enable auto-answer cards
Enable TTS
Review a selection of cards
Android version 2.10alpha
=> Use TTS progress listener status in Card Viewer auto-advance delay

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/Info.java, AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java
Small change before I add in the "Browser Appearance" screen.
I was going to put them in together, but it's a fairly large PR by itself, and I'd rather not muddy the waters.
=> NF: Extract Method: enableToolbar

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
Very useful to be able to know what the lifecycle events are.
Straw that broke the camel's back was #6244
=> LOG: Activity Lifecycle Events

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
I found the code which deal with the "undo" button quite ugly. I hope you'll agree with me that this new version is more clear. I removed a lot of code duplication.
Each commit are supposed to be easy to follow, it should be clear nothing is done, with one exception,  https://github.com/ankidroid/Anki-Android/commit/0c37624b5a0d888e573aa8977c80c2ac4ff29e1f is more complex, so the commit message explain why actually, this simplification is valid.
My ultimate goal is to deal with https://github.com/ankidroid/Anki-Android/issues/6119 with a solution which allows the undo button to sometime change its color. I've learned my lesson, I first submit code simplification, and only when it has been accepted do I submit the code which does actual bug correction.
(Normally, the bug will become really …
=> clean code of the undo button

AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java
Ensure logging is not too lenient (logging filenames as 'Info', or likely to spam the logs)
Attempt to diagnose #5142 via adding logging
Phone still plays audio
https://stackoverflow.com/questions/9609479/android-mediaplayer-went-away-with-unhandled-events
=> Sound: Add debug logging and reset to remove log warning

AnkiDroid/src/main/java/com/ichi2/utils/JSONObject.java
Using the correct value of NULL.
I'll put a test soon. Wanted to push the obvious correction asap.
Thanks @dae for pinging me. 
----
_Edit by @david-allison-1_
Fixes #6289
=> Correcting #6289

AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
When enter key pressed after writing password, login is triggered
=> Login  triggered when pressing enter #6322

AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/hooks/ChessFilter.java, AnkiDroid/src/main/java/com/ichi2/libanki/hooks/Hooks.java
Restriction of #6268 restricted to Chess part for simplicity
=> NF: Remove hook chess

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
Restriction of #6268 restricted to mungeFields part for simplicity
=> NF: remove a never called hook

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/LaTeX.java, AnkiDroid/src/main/java/com/ichi2/libanki/hooks/Hooks.java
Restriction of https://github.com/ankidroid/Anki-Android/pull/6268 restricted to LaTeX part for simplicity
=> Remove hook latex

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java, AnkiDroid/src/main/java/com/ichi2/anki/TtsParser.java, AnkiDroid/src/main/java/com/ichi2/libanki/Media.java, AnkiDroid/src/main/java/com/ichi2/libanki/template/Template.java, AnkiDroid/src/main/res/values/02-strings.xml, AnkiDroid/src/test/java/com/ichi2/anki/ReadTextTest.java
Ensure the localisation strategy makes sense
Make TTS pronounce "[...]" in cloze deletions
Fixes #6336
We now perform a find/replace and it says "blank". This is localisable
Unit tests and on my phone.
=> Make TTS pronounce "[...]" in cloze deletions

.github/workflows/stale.yml
Also upgrades to v3 of the actions workflow, as this is required.
🛑 - not tested
Documented: https://github.com/actions/stale/blob/master/action.yml
=> Anki Ecosystem Compatibility: Don't mark as stale

.github/workflows/stale.yml
This reverts commit 5ae2b31a
Last run closed multiple issues unexpectedly
=> Revert "Anki Ecosystem Compatibility: Don't mark as stale"

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
This is another cleaning PR, with the ultimate goal of improving card browser speed. I can't really explain more than what is in the commits
=> NF: Better do in background search cards

AnkiDroid/src/main/java/com/ichi2/libanki/Models.java
Correcting indentation in a separate PR as requested on https://github.com/ankidroid/Anki-Android/pull/6046/files#r435388631
=> NF: correcting some space

AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java, AnkiDroid/src/main/java/com/ichi2/libanki/Models.java, AnkiDroid/src/main/java/com/ichi2/libanki/Tags.java, AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java
Saving any in the collection takes a lot of time, especially because we need to deal with big strings. Saving values in the database is useless when no change occured.
So, in this case, I just uses a boolean to see whether any change did occur, and save only if there is some change.
=> beforeUpload: save only if some change occured

AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java
Related to https://github.com/ankidroid/Anki-Android/issues/6361#event-3409088194
=> NF: correct comment

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
This is a follow up of today's PR. It's actually based on a merge of them.
It does no computation in finder. It computes values for card shown and the few context lines only.
I was expecting to make smaller PR, but this answer https://github.com/ankidroid/Anki-Android/pull/6358#issuecomment-639077416
This was tested by merging it in my "merge" branch, which I run on my phone and just using the browser
=> Improve Card Browser Performance: Time to view first card

AnkiDroid/src/main/res/values/03-dialogs.xml
Credit to Prasanta-Hembram (Rocky_734) on crowdin
=> Fix typo noticed by translator in source strings

AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java
Remove a Java comment related to code which was deleted in #6268.
=> Remove leftover comment overseen in #6268

AnkiDroid/src/main/java/com/ichi2/preferences/StepsPreference.java
This reverts commit 99db5f59 (#6291/#6292)
Blocked space entry on some devices
=> Revert "Custom Steps: Remove Suggestions"

AnkiDroid/build.gradle
Minor version bump to the Gradle Triple-T publisher (it's our automated play store uploader for releases)
=> Dependency updates 20200609

AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.java, AnkiDroid/src/main/res/values-sat/01-core.xml, AnkiDroid/src/main/res/values-sat/02-strings.xml, AnkiDroid/src/main/res/values-sat/03-dialogs.xml, AnkiDroid/src/main/res/values-sat/04-network.xml, AnkiDroid/src/main/res/values-sat/05-feedback.xml, AnkiDroid/src/main/res/values-sat/06-statistics.xml, AnkiDroid/src/main/res/values-sat/07-cardbrowser.xml, AnkiDroid/src/main/res/values-sat/08-widget.xml, AnkiDroid/src/main/res/values-sat/09-backup.xml, AnkiDroid/src/main/res/values-sat/10-preferences.xml, AnkiDroid/src/main/res/values-sat/11-arrays.xml, AnkiDroid/src/main/res/values-sat/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-sat/17-model-manager.xml, AnkiDroid/src/main/res/values-sat/18-standard-models.xml, AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilsTest.java, docs/marketing/localized_description/marketdescription-sat.txt, tools/update-localizations.py
New translation to Santali language, all credit to Prasanta-Hembram (Rocky_734) on crowdin!
=> Add santali language

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/res/values/10-preferences.xml, AnkiDroid/src/main/res/xml/preferences_reviewing.xml
In fullscreen there is no option to hide top bar. So this PR is for that.
Added boolean value in Sharedpreferences with key ```top_bar```
Then accessed that value in AbstractFlashcardViewer, if false then hide else do nothing.
Tested on Android Emulator 
Change setting, check that for showing top bar
```
1. AnkiDroid->Settings->Reviewing->Show Top Bar
2. Now view changes in reviewing
```
https://developer.android.com/reference/android/transition/Visibility
- [ x ] Your code follows the style of the project (e.g. never omit …
=> Show or hide top bar 

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/UIUtils.java
A method requires a parameter it does not uses. I remove it.
=> Remove unused parameter in saveCollectionInBackground

AnkiDroid/src/main/java/com/ichi2/libanki/importer/AnkiPackageImporter.java, AnkiDroid/src/main/res/values/02-strings.xml
Allows better error reporting and logging of import issues
Diagnoses #6419
Untested
=> Add diagnostics to AnkiPackageImporter

AnkiDroid/src/main/assets/flashcard.css
This should solve
https://github.com/ankidroid/Anki-Android/issues/6439. It fails on
emulator, I just don't get it. Report on
https://github.com/ankidroid/Anki-Android/pull/6246#issuecomment-632864445
Tested on my phone, it works perfectly
=> invert tex color in night mode

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/java/com/ichi2/libanki/Card.java, AnkiDroid/src/main/java/com/ichi2/libanki/utils/NoteUtils.java
I made remarks in https://github.com/ankidroid/Anki-Android/pull/6063#pullrequestreview-430257334 and they were deemed not to be relevant for this PR. So I made the changes myself.
There are comments, and I separate as a distinct function in the utils package, a method which change the tags of a note.
I'm testing it by merging in my "merge" branch and doing a simple edit. I'm not doing any complex test here.
=> NF: Set tags in note

AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java, AnkiDroid/src/main/java/com/ichi2/libanki/Card.java, AnkiDroid/src/main/java/com/ichi2/libanki/Note.java, AnkiDroid/src/main/java/com/ichi2/libanki/WrongId.java
In some code, there is some "try/catch(Exception)". This is far too
general. I prefer to have a catch WrongId if we expect an id to be
missing.
I believe also that it would make the code easier to read if it allows to figure out what kind of exception is expected
=> NF: introduce exception WrongId

AnkiDroid/src/main/java/com/ichi2/libanki/DB.java, AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java, AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java, AnkiDroid/src/main/java/com/ichi2/libanki/importer/AnkiPackageImporter.java, AnkiDroid/src/main/res/values-az/03-dialogs.xml, AnkiDroid/src/main/res/values-ti/01-core.xml, AnkiDroid/src/main/res/values/02-strings.xml
This is a continuation of #4622 from @camparijet - his original idea - do partial commits to the database while importing - seemed correct but I could not get it to work at the time.
Now with very large decks being more normal (#6419 #6438 #6435) I was reminded about this and wanted to try it again
Fixes #6419 at least in part
Maybe fixes #4481 #2596
1. Scan a zip before even trying it, tell the user if there is not enough space to decompress
1. During import, commit work and clear scratch space periodically so we don't run out of memory
1. During import if we run out of space, report that to the user nicely
1. Post import, during cleanup, if we run out of space report that to the user nicely
This was tested on an emulator, with each scenario repeating these steps
1. shutdown the emulator …
=> Avoid unhandled out-of-space and OOM on large imports

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java
Fixing a mistake I made when I was new to the project
We should probably have a lint check
=> Remove log.wtf

AnkiDroid/src/main/res/values/09-backup.xml
=> backup_deck_no_space_left: fix typo

AnkiDroid/src/main/java/com/ichi2/utils/JSONArray.java, AnkiDroid/src/main/java/com/ichi2/utils/JSONException.java, AnkiDroid/src/main/java/com/ichi2/utils/JSONObject.java, AnkiDroid/src/main/java/com/ichi2/utils/JSONTokener.java
=> NF: JSON licence

AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java, AnkiDroid/src/main/res/values/01-core.xml
As required on https://github.com/ankidroid/Anki-Android/issues/5829
Note that in case of month and year, I left it as it is, with a
floating point number. Still wishing that we never ever show "1.1
month remaining", because this number is supposed to be the time
required to study today assuming no pause are taken, and that nobody
can ever spend more than a month during a single day !
=> Show two numbers in planification

AnkiDroid/src/main/res/values/01-core.xml
As requested in https://github.com/ankidroid/Anki-Android/issues/6498
=> Using numbered variable in string

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
This corrects https://github.com/ankidroid/Anki-Android/issues/5829#issuecomment-646411753
I don't really know how to factorize correctly, and won't spend time on it as some part may disappear with rust.
=> Using different method for time in deck picker and review

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java
Changes found when trying to reduce our lint errors to 0.
* Two uses of String.format instead of `getString`
* One bad JavaDoc
Untested
=> NF: Inspection fixes

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
Adding this log helped a lot, but it could have been better. 
Would have done this earlier if I'd have known how easy it was in Java.
Very briefly on my phone. `DeckPicker` was in the logs
=> LOG: Add class name to AnkiActivity logs

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.java
Adding nested decks to test. Seems especially useful since it seems they failed and required some change
They seemed to be requested in 
https://github.com/ankidroid/Anki-Android/pull/6526#pullrequestreview-434534141
First: adding a nested deck. Running test. Seeing test fails, and correcting them in a way which makes sens
Running test.
I don't need to understand all matrix and all to run tests
=> Nested decks in pull request

AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
The goal here is to make https://github.com/ankidroid/Anki-Android/pull/6026 simpler by removing its simpler commit and putting it in a stand-alone PR
=> NF: introduce a variable

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java, AnkiDroid/src/main/java/com/ichi2/anki/services/ReminderService.java, AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java, AnkiDroid/src/main/java/com/ichi2/widget/WidgetStatus.java, AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.java
deckDueTreeNode's member become private. That's a start of a change made for https://github.com/ankidroid/Anki-Android/pull/6522, as requested by @david-allison-1 .
I also added a few methods which makes more sens than getter
=> Private deck due tree node

AnkiDroid/src/main/res/drawable/ic_flag_red.xml
=> Update ic_flag_red.xml to match AnkiDesktop

AnkiDroid/src/main/res/drawable/ic_flag_orange.xml
=> Update ic_flag_orange.xml to match AnkiDesktop

AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
While splitting PR in smaller PR and changing it, I guess at some
point I made a mistake and corrected only one of both scheduler. I am
sorry. I expect the main idea of this whole change to still be valid.
=> Correcting #6568

AnkiDroid/src/main/java/com/ichi2/anki/services/ReminderService.java
A comment as indicated in https://github.com/ankidroid/Anki-Android/pull/6572
=> NF: add comment

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java, AnkiDroid/src/main/java/com/ichi2/anki/services/ReminderService.java, AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java, AnkiDroid/src/main/java/com/ichi2/widget/WidgetStatus.java
This will help make https://github.com/ankidroid/Anki-Android/pull/6522 smaller. It will use more correct path for the deck due nodes
=> NF: uses AbstractSched before DeckDueTreeNode (performance)

AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
It seems I totally forgot to ensure that `_checkDeckTree` change the
name map. The main problem here being that it changes name using JSON
operation and not the method `rename`. Actually, using `rename` would
be almost impossible, because `rename` would risk to raise an
exception due to name duplication.
Instead, I simply ensure that the map is created again when there is
any error.
This should solve #6590 and also other potential error later.
As a side note, I am happy that I decided to raise an exception if
byName returns a deck with a wrong name. We would note have found it
otherwise, and it seems quite good to see it here
Tested by adding it to my "merge" deck and ensuring Ankidroid still works
=> Deck tree check deal with name map

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/DBTest.java, AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/HttpTest.java, AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.java, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java, AnkiDroid/src/main/java/com/ichi2/libanki/DB.java, AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java, AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java, AnkiDroid/src/main/java/com/ichi2/libanki/Models.java, AnkiDroid/src/main/java/com/ichi2/libanki/stats/AdvancedStatistics.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java, AnkiDroid/src/test/java/com/ichi2/anki/AnalyticsTest.java
Fixes the "Memory" class of lint errors
Added 2 log lines, rest was automatic Android Studio refactorings
Tested on my Android 9 device
=> Lint Fixes - Static Inner Class and Improve decks.all()/allConf()

AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java, AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.java, AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.java
This test fails with the PR that was wrong. It is correct currently.
I fear that it is not proper unit test style, but I really don't
understand what is going on here, so I'd be happy to get
correction. In particular, how to have the same set of decks in both
kind of test.
=> Test detecting #6544

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.java, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java, AnkiDroid/src/main/res/values/09-backup.xml
This was the old name and is confusing now
=> NF: Renaming Deck to Collection

AnkiDroid/src/main/java/com/ichi2/libanki/Consts.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
Fixes a few lint errors from the introduction of `IntDef`
Untested
=> LINT: Sched - Fix IntDef errors

AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java
task type is not a number anymore
=> Correct formatting error

AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
This is an alternative to https://github.com/ankidroid/Anki-Android/pull/6049
It has no boolean state. Instead only uses null/not null. 
I am going to test it on my phone
=> Defer load model (performance)

AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
While looking at the method parents, I found it more ugly than required and hope this rewriting will be accepted.
Since size is known, array seems more appropriate than list, so I did this change in last commit. I may remove it if you don't like it
=> Parents uses array

AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
Seems during one of the multiple rewrite, some parameter got lost.
=> Add a missing argument in a sql query

AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java, AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.java
I was thinking "in case of problem, we just have to construct the name map again once they are corrected".
I didn't fully grasp that name map was actually used in the deck manager and that `_checkDeckTree` uses the deck manager, E.g. to ensure parents are created. So I need to ensure that the name map stays consistent during the whole computation.
Should fix https://github.com/ankidroid/Anki-Android/issues/6636 
When a deck is renamed (e.g. because blank, because duplicate) the information is directly given to the name map, so that the remaining of the code can find this name. 
Furthermore, we uses a map instead of a set, this way, when we find a duplicate, we also find the original deck and ensure both are in the name map (the original may have been erased when adding the duplicate) …
=> Check deck tree update name map

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.java, AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java
Bugfix - Previously the previous time was shown if Ease4 was unavailable
Fixes #6623
Set the text to an empty string if the button is not available.
⚠️ Unit tested only
=> AnkiDroidJS: display blank if button unavailable

AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
I've found where the missing argument of https://github.com/ankidroid/Anki-Android/pull/6637 went
Fixes #6645
Creating a class to encode this specific data, I was forced to see where the error is.
Not yet
Splitting working PR into atomic PR does not work well
=> mLrnQueue has encoded as a class

tools/release.sh
The previous release text was sort of a "wall of text" and did not properly signal to the different types of users we send to the releases page what they would be interested in
Just tightened up the wording
Example of old text:
----
The builds with letter codes below (A, B, etc) are universal parallel builds. They will install side-by-side with the main APK build for testing, or to connect to a different AnkiWeb account in combination with changing the storage directory in preferences. If you install the main APK below, you should install the version matching your CPU instruction set. If you do not know that information, there are many guides on finding it, for example https://www.howtogeek.com/339665/how-to-find-your-android-devices-info-for-correct-apk-downloads/
----
New text:
---- …
=> Copy-edit the github release text

gradle/wrapper/gradle-wrapper.properties
Patch version change, should have no effect, just tracking upstream.
=> Bump gradle version to 6.5.1

AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
Fixes #6658 
Straightforward once seen
I'll really create a lot of scheduler test soon. I now really understand the need !
=> Correct 6658

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/java/com/ichi2/libanki/Card.java, AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerCommandTest.java
While porting upstream test, I saw a method name was incorrectly ported. I correct it
=> getUserFlag->userFlag

AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
Upstream unit test tests various Unbury. Looking at them, I thought using an enum would be more clear than using string
=> NF: UnburyType is an enum

AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
This is part of https://github.com/ankidroid/Anki-Android/pull/6721. There is a line repeated 37 times. I factorize it. This will mostly be useful when CollectionTasks has subclass, because mContext is private and it will also allow to to avoid importing CollectionHelper and Context in all subclass' file
=> NF: CollectionTask.getCol()

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/java/com/ichi2/anki/stats/OverviewStatsBuilder.java, AnkiDroid/src/main/java/com/ichi2/libanki/Card.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/DB.java, AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java, AnkiDroid/src/main/java/com/ichi2/libanki/Media.java, AnkiDroid/src/main/java/com/ichi2/libanki/Models.java, AnkiDroid/src/main/java/com/ichi2/libanki/Note.java, AnkiDroid/src/main/java/com/ichi2/libanki/Tags.java, AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
This PR is supposed to follow https://github.com/ankidroid/Anki-Android/pull/6697 and is a matter of taste. Only the last commit does not appear in the other PR.
Adding `new Object[]{` after each query decreases readability as far as I'm concerned, so I prefer to remove it. 
Testing on my merge branch
=> NF: No "new Object[]" in queries

AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
We should only uses the factory method to construct it.
=> CollectionTask Constructor private

AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
Make a method public, as requested in https://github.com/ankidroid/Anki-Android/pull/6708/files/7fb841064b6dcac188793a341c1188f3fb5f468f#diff-a5e6c043babd9420c577ceb5248d7610
=> NF: move unburyCardsForDeck(UnburyType) to AbstractSched

AnkiDroid/src/test/java/com/ichi2/libanki/ClozeTest.java, AnkiDroid/src/test/java/com/ichi2/libanki/MathJaxClozeTest.java
Similar to https://github.com/ankidroid/Anki-Android/pull/6708/files/a5909b8f3791133d4d28358eb41b6d465eb3f0ee#diff-161a9c0dc1b9ccee8066dbdc071ae6b8
=> NF: asserts that instead of asserts true

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java, AnkiDroid/src/main/java/com/ichi2/async/TaskData.java
This constant is never read anyway
=> NF: CountModel does not return constant

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.java
Some users (and myself) felt that having a fully opaque selected deck against a custom user background was not ideal
Fixes #6754
We fix this to make the selected deck partially transparent
=> Make selected deck see-through against background image

AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
This is already the case, and this lead to simplifying the readability of the code by ensuring we don't see array when
we expect a single element.
=> NF: Task takes at most one task data

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ConfirmationDialog.java
Fixing a simple TODO. Performed with Android Studio auto-refactorings.
=> NF: ConfirmationDialog convert Runnable to Lambda

AnkiDroid/src/main/res/values/02-strings.xml, AnkiDroid/src/main/res/values/03-dialogs.xml
We allowed users to decrease study limits:
d31c3d19769371cb031bd4280918277c20d52f42
But we didn't tell them about it via the UI. This improves that
Modify strings to better inform users
=> Improve discoverability: Decreasing study limits

AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.java
The previous calculation was incorrect
Fixes #4722
Ported from https://github.com/ankitects/anki/blob/5410321c0e8e623a528deb2541055fef4d2b3bc8/anki/stats.py
Tested on my phone against my personal collection. Now matches Anki Desktop
=> Fix "New Cards Added" Stats

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java, AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java, AnkiDroid/src/main/java/com/ichi2/libanki/Card.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/Consts.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java, AnkiDroid/src/main/java/com/ichi2/libanki/stats/AdvancedStatistics.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java
This ends something I started month ago. Adding labels to constant to indicate which kind of data they represents.
This is as NF as it can be, since it should (almost) not change a single line of the code considered by the compiler
=> NF: Labelling constants

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/RescheduleDialog.java, AnkiDroid/src/main/java/com/ichi2/libanki/Card.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java, AnkiDroid/src/main/res/values/03-dialogs.xml
Rescheduling cards is not well defined - add some more warnings
Fixes #6370
Fixes #5242 
Add text-based warnings
On my phone: is:new, is:learn and is:review
is:learn had no change
=> Reschedule dialog: Add Warnings

AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
This is a part of https://github.com/ankidroid/Anki-Android/pull/6780 whose goal is to factorize some part of the query that appear often. In particular, this allow codes of both sched to be identical in some case, which means that it can then be factorized
=> NF: Factorize query

AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.java
Ignore the test until we get a better solution
#6814
=> Fix CI Failure: SchedV2Test.test_moveVersions

AnkiDroid/src/main/res/layout/card_browser.xml, AnkiDroid/src/main/res/layout/card_item_browser.xml, AnkiDroid/src/main/res/values/attrs.xml, AnkiDroid/src/main/res/values/theme_black.xml, AnkiDroid/src/main/res/values/theme_dark.xml, AnkiDroid/src/main/res/values/theme_light.xml, AnkiDroid/src/main/res/values/theme_plain.xml
Above changes were requested to the UI, I feel this is an improvement, but all UI is subject to personal biases
The main note is that the bottom line of the table has now been removed
Fixes #5707 
* Add vertical line
* Increase padding
* Change vertical and horizontal line colors to white in dark mode
* Make text top align
Dark
=> Improve Card Browser UI: Vertical lines, color, alignment and padding

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java, AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.java
Caused by changing scheduler - which removed our time dependency
Uses code from #6812 
Fixes #6814
Extract method and use it
⚠️  Inconclusive - unit tested, but they passed previously
Time is hard
=> Fix Flaky Test: SchedV2Test.test_moveVersions

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.java, AnkiDroid/src/main/res/values/02-strings.xml
The test client often opens the shared deck page and starts clicking links - this doesn't help testing for app bugs.
This means that the app cannot load URLs or go fullscreen.
This makes it much more likely to find issues.
Added a toast to display to users in case this appears
Not yet - best way will be to see if we pick up more issues
* https://stackoverflow.com/a/43598581/13121290
=> Improve Firebase test quality

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
Listener will only be related to UI. Related to https://github.com/ankidroid/Anki-Android/pull/6775#discussion_r466509977
=> NF: move clearUndo to background

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/libanki/Card.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
Small change, which I hope improve readability. 
This is vaguely related to https://github.com/ankidroid/Anki-Android/pull/6775#pullrequestreview-462635949
=> NF: Incr decr reps

AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
This is part of the bigger scheduler PR I made today. This one simply adds comments warning on each methods that they are overridden, and if possible what is the difference.
Methods overridden by another methods which is identical are not commented
I hope this one will be simple to accept. But I guess you should at least check that comments are accurate.
Some methods simply indicates "Overriden" when the difference is too big for a simple comment. It's still useful because, when debugging schedV1, it tells us whether we need to go look at SchedV1 or not
=> NF: explain difference between scheds

AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
There are three tasks that are never used. This removes them.
=> Remove unused task

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java, AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java, AnkiDroid/src/main/java/com/ichi2/anki/UIUtils.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java, AnkiDroid/src/main/java/com/ichi2/async/TaskListener.java, AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java, AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java
This allow for shorter and more clear line through the code
Separate part of https://github.com/ankidroid/Anki-Android/pull/6775#pullrequestreview-462635949 which would simplify the code difference I believe
=> NF: Listener as separate file

AnkiDroid/build.gradle, AnkiDroid/src/main/java/com/ichi2/utils/DiffEngine.java
Our diff utils for the type answer feature is unmaintained, I want to use a maintained dependency
Fixes #6537 
A pretty straight-forward port to the new library's APIs. 
Tested in API29 emulator, works for fully correct, partially correct, or missing answer parts
I don't think I learned a single thing making this PR.
=> Port to maintained 3rd party diffutils

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
Fixes #6871
Don't log to the file if we can't
Untested
=> Fix NullPointerException in Collection.log

AnkiDroid/build.gradle
jetbrains annotations library update, nothing else at the moment
=> Dependency updates 20200810

AnkiDroid/build.gradle, AnkiDroid/src/main/java/com/ichi2/utils/DiffEngine.java
Two dependency update fixups:
1. the annotations bump in last update was to the resolution strategy but not the actual dependency, fixed
1. the diff library switch in #6537 was inadvertently to an old version of the library, forward-ported to new version
=> Diff patch update

AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckDueTreeNode.java
As requested in https://github.com/ankidroid/Anki-Android/pull/6578/files/038c805d7ad27694a95f54c0e28d6ec2ca44312a#r469802429
=> NF: uses Integer.compare

AnkiDroid/src/main/java/com/ichi2/anki/Info.java
That's the information I always need and always should ask.
=> Add Scheduler version to Debug Info

AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
The PR "split reset" was created before mUndidCard was introduced in the PR. While reviewing recent change I realized
that it should have taken split reset by taking into account that mUndidCard deals both with queue and with count. It is
now separated as two distinct variables.
This is currently NF, because we never reset counts and queue separately.
I also changed variable names to explain more what they represents instead of how it is created
=> NF: Split mUndidCard

AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
This was part of a bigger PR that I splitted. Here I just remove code that is literally the same in both sched. This will avoid me to lose again and again a lot of time looking at both code and trying to figure out the difference between them when I want to debug sched V1
=> NF: remove upstream duplicate

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
A PR merged added a new Object. I didn't check for them in the existing PR when I tried to check for them in the PR removing those new Objects
=> NF: uses a varargs

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java, AnkiDroid/src/main/java/com/ichi2/async/Connection.java, AnkiDroid/src/main/java/com/ichi2/libanki/Card.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java, AnkiDroid/src/main/java/com/ichi2/libanki/Models.java, AnkiDroid/src/main/java/com/ichi2/libanki/StdModels.java, AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java, AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/RemoteServer.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java, AnkiDroid/src/main/java/com/ichi2/preferences/StepsPreference.java, AnkiDroid/src/test/java/com/ichi2/anki/CardTemplatePreviewerTest.java, AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.java
While looking at other part of the code, I saw some `(JSONObject) jo.get("name")` which is kind of ugly, given that "jo" and "ja" are not descriptive and there exists getJSONObject which avoid explicit casting. So I'm correcting both problems.
Given that sometime both errors appear on the same line and that this merge conflict would have no purpose, I make both change in a single PR. 
The second commit used android studio way to rename variable, so there is virtually no risk. There is little risk in the first commit if I got the typing wrong. 
I am testing it in my merge branch
=> NF: clean JSON

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
the variable `card` seems to indicate that it was taking a card, which is false and so confusing
My goal is to preload card as much as possible. This mean pre rendering html before actually needing to show it, in particular mathjax and loading media. This also mean that I need to deal with sound outside of the AbstractFlashCard Viewer. I believe that doing simple cleaning is a good first step to attain this goal easily. 
My point is that I'm not just doing refactoring for the sake of cleaning. I am doing it because I've got a goal in mind and that I expect that this will help reach it. In this case, what I want is simply to know when I've got a view and when I've got an actual card. It's especially important because we use lambda, so type are not clear
=> NF: processCardAction arguments are cardWebView

AnkiDroid/src/main/java/com/ichi2/libanki/sched/CardQueue.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
In this cases, java's library has a method close to what we want to do. I find it also more readable/easier to reason about, since I directly see that it adds the elements just before the first element with due greater than `due`, or at the end of the list
=> NF: uses list iterator

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicControllerFactory.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java
There remained a few use of real time in the code. I thought about them while reviewing https://github.com/ankidroid/Anki-Android/pull/6956 by thinking what way the use could still fail to use time in a proper way
=> NF: Use col's time instead of `new SystemTime`

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
Anki has this functionality
https://github.com/ankitects/anki/blob/9aa3d7867e184f3c8d91e9e5686d2881bc9b2cba/qt/aqt/editor.py#L651-L652
Fixes #6014
Related: #6763
Ctrl+Alt+Shift+C - enter cloze with same number
Manual test on my phone
Always something new to learn
=> Ctrl+Alt+Shift+C - Create Cloze with same number

tools/manage-crowdin.sh
Seems to correspond to the examples of https://support.crowdin.com/api/update-file/
=> Crowdin: add parameter in -F and not in url

AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java
As requested in https://github.com/ankidroid/Anki-Android/issues/5923
This is supposed to ensume unburying would occur before sync
=> Correct 5923

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
I just found the constructor has an obvious bug without any explanation. Sorry
=> NF: correct creation of card cache

AnkiDroid/src/main/res/values-ar/01-core.xml, AnkiDroid/src/main/res/values-es-rAR/02-strings.xml, AnkiDroid/src/main/res/values-es-rES/02-strings.xml, AnkiDroid/src/main/res/values-fr/01-core.xml, AnkiDroid/src/main/res/values-fr/02-strings.xml, AnkiDroid/src/main/res/values-fr/03-dialogs.xml, AnkiDroid/src/main/res/values-fr/04-network.xml, AnkiDroid/src/main/res/values-fr/10-preferences.xml, AnkiDroid/src/main/res/values-fr/17-model-manager.xml, AnkiDroid/src/main/res/values-pt-rBR/01-core.xml, AnkiDroid/src/main/res/values-pt-rBR/02-strings.xml, AnkiDroid/src/main/res/values-pt-rBR/03-dialogs.xml, AnkiDroid/src/main/res/values-pt-rBR/04-network.xml, AnkiDroid/src/main/res/values-pt-rBR/07-cardbrowser.xml, AnkiDroid/src/main/res/values-pt-rBR/10-preferences.xml, AnkiDroid/src/main/res/values-pt-rBR/11-arrays.xml, AnkiDroid/src/main/res/values-pt-rBR/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-pt-rBR/17-model-manager.xml, AnkiDroid/src/main/res/values-ru/02-strings.xml, AnkiDroid/src/main/res/values-zh-rCN/01-core.xml
Two problems at once -
1. The crowdin secret key could leak because of the usage style, github did not "know" the raw string (it was gzipped and ascii armored) so it couldn't mask it, it is not used in original form (it was already ascii) and used as an environment variable so GitHub can mask it better
1. The Russian translation of one string had two `%s` not used positionally, fixed upstream in crowdin and importing now
Plus the regular flow of translation activity
=> Updated strings from Crowdin 20200829

AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.java, AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.java, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.java, AnkiDroid/src/main/java/com/ichi2/anki/services/BootService.java, AnkiDroid/src/main/java/com/ichi2/libanki/CardStats.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java, AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.java, AnkiDroid/src/main/java/com/ichi2/libanki/utils/Time.java
I find some more place where I use real time. Seems it shows not everything was catched by lint.
I moved all functions dealing with time in Time.In particular because Calendar/Date object have real time when they are created, it seems it can't be helped even if we want to have a specific date instead. This way at least, the part of the process where we have real time is encapsulated
=> More non real time 

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
By the way, what is this feature ? I don't understand what's the point
=> NF: mSetLanugageId -> mSetLanguageId

AnkiDroid/src/main/res/values/10-preferences.xml, AnkiDroid/src/main/res/xml/deck_options.xml
Some users missed this option - hopefully a summary will help them
Add a summary
I tried an icon, but if we use this, then all items need spacing or an icon.
=> Deck Options: Add Group Management summary

AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.java
Follow-up from #7010
Note: I'm using an updated email, rather than the one specified in `git log`
=> NF: Add copyright to compat implementations

AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
Adding some @NonNull and @Nullable in the scheduler
=> NF: Add Nullability Annotations to Scheduler

AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java, AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java
=> Correction of 7066

AnkiDroid/src/main/res/values-ar/01-core.xml, AnkiDroid/src/main/res/values-ar/02-strings.xml, AnkiDroid/src/main/res/values-ar/04-network.xml, AnkiDroid/src/main/res/values-ar/07-cardbrowser.xml, AnkiDroid/src/main/res/values-ar/10-preferences.xml, AnkiDroid/src/main/res/values-ar/11-arrays.xml, AnkiDroid/src/main/res/values-es-rAR/01-core.xml, AnkiDroid/src/main/res/values-es-rES/01-core.xml, AnkiDroid/src/main/res/values-uk/01-core.xml, AnkiDroid/src/main/res/values-uk/02-strings.xml, AnkiDroid/src/main/res/values-uk/04-network.xml, AnkiDroid/src/main/res/values-uk/10-preferences.xml, AnkiDroid/src/main/res/values-zh-rCN/02-strings.xml, AnkiDroid/src/main/res/values-zh-rCN/04-network.xml
=> Updated strings from Crowdin 20200913

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
We were using incorrect constants
Fixes #7088
Use the correct constants
None
=> Use "safe display" to disable animations

AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronounciationActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/TranslationActivity.java
Both are web-based activities that we'd rather the monkey ignored
Fixes #7090
Exit out the activities if entered
Untested
We can still do better with the monkey
=> Monkey: Block "Account" and "Translate/Pronounce"

AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.java
=> Fix CI Error: baseDeckName

AnkiDroid/src/main/java/com/ichi2/utils/JSONObject.java
Just makes coding a little bit nicer
=> NF: Add CheckResult to JSONObject

AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckDueTreeNode.java
No idea how to make a unit test in this case, given the simplicity of this method...
=> Allow to review decks containing only learning cards

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioClipFieldController.java
Audio Clip insertion
Fixes #5903
Add more exception handlers and exception reports
Android 9 - attempted to import a wav and it worked
I was previously too conservative with exception reports (maybe it was a sensible move at the time as we were already being spammed by the reports).
=> Audio Clips: Improve Exception Handling

AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
Improves #7122 - uses less memory
Untested, but trivial to see this is correct
=> PERF: Use HashSet instead of HashMap

AnkiDroid/src/main/res/xml/preferences_advanced.xml
=> NF: Fix MIUI Option title string

AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
The returned values are never used. And they are not the same thing at all in both scheduler. So that's more confusing than helping.
I'm commenting more the scheduler, and this can't be commented as the return value differs
=> NF: rebuildDyn don't return

AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java, AnkiDroid/src/test/java/com/ichi2/libanki/CardTest.java, AnkiDroid/src/test/java/com/ichi2/libanki/CollectionTest.java, AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.java
I remove cause of warning that asList with a single element should be replaced by singletonList
=> NF: remove warning asList singleton

AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java, AnkiDroid/src/main/java/com/ichi2/libanki/StdModels.java, AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java, AnkiDroid/src/main/java/com/ichi2/libanki/importer/NoteImporter.java, AnkiDroid/src/test/java/com/ichi2/libanki/CardTest.java, AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.java, AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.java
I believe it gets easier to read this part of the code, because it is clear that it really only create a json object.
Intuitively, I thought that using `newTemplate` would add the template and not only create the object to be added. This
seems more clear to mee this way.
Furthermore, it removes warning
=> NF: uses static access to model method

AnkiDroid/src/main/res/values-ar/04-network.xml, AnkiDroid/src/main/res/values-cs/04-network.xml, AnkiDroid/src/main/res/values-cs/10-preferences.xml, AnkiDroid/src/main/res/values-eo/03-dialogs.xml, AnkiDroid/src/main/res/values-es-rAR/03-dialogs.xml, AnkiDroid/src/main/res/values-fa/03-dialogs.xml, AnkiDroid/src/main/res/values-mk/03-dialogs.xml, AnkiDroid/src/main/res/values-pl/02-strings.xml, AnkiDroid/src/main/res/values-pl/03-dialogs.xml, AnkiDroid/src/main/res/values-pl/04-network.xml, AnkiDroid/src/main/res/values-pl/07-cardbrowser.xml, AnkiDroid/src/main/res/values-pl/09-backup.xml, AnkiDroid/src/main/res/values-pl/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-pt-rBR/01-core.xml, AnkiDroid/src/main/res/values-pt-rBR/02-strings.xml, AnkiDroid/src/main/res/values-pt-rBR/04-network.xml, AnkiDroid/src/main/res/values-pt-rBR/10-preferences.xml, AnkiDroid/src/main/res/values-ru/02-strings.xml, AnkiDroid/src/main/res/values-ru/03-dialogs.xml, AnkiDroid/src/main/res/values-ru/04-network.xml, AnkiDroid/src/main/res/values-ru/10-preferences.xml, AnkiDroid/src/main/res/values-ru/17-model-manager.xml, AnkiDroid/src/main/res/values-sv/03-dialogs.xml, AnkiDroid/src/main/res/values-te/03-dialogs.xml, AnkiDroid/src/main/res/values-zh-rCN/03-dialogs.xml, AnkiDroid/src/main/res/values-zh-rCN/04-network.xml, AnkiDroid/src/main/res/values-zh-rTW/03-dialogs.xml
Standard language translation sync
=> Updated strings from Crowdin 20200920

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.java, AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/MetaDB.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java
Suppress warning and simplifies the code
=> NF: methods allow to use int directly, so remove toString

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/FieldControllerBase.java, AnkiDroid/src/main/java/com/ichi2/async/TaskListenerWithContext.java, AnkiDroid/src/main/java/com/ichi2/libanki/Models.java, AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java, AnkiDroid/src/main/java/com/ichi2/libanki/stats/AdvancedStatistics.java, AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.java, AnkiDroid/src/main/java/com/ichi2/libanki/utils/Time.java
Suppress warning and simplifies the code
=> NF: remove useless semicolons

AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/HttpSyncer.java, api/src/main/java/com/ichi2/anki/api/Utils.java
The warning suggest something that does not work with low API
=> NF: supress warning for charset object

AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
Remove warning and simplifies code
=> NF: replace indexOf != -1 by contains

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.java, AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.java, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java, AnkiDroid/src/main/java/com/ichi2/libanki/Card.java, AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java
Remove warnings related to unboxing uselessly.
=> NF: remove unboxing warning

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
Slightly more efficient and remove a warning
=> NF: replace sting buffer by builder

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
Ecosystem Compatibility
Extract shortcuts and add methods
My Android 9 & Bluetooth keyboard (being careful with multiselect and nothing selected)
=> Card Browser: Initial Keyboard Shortcuts

AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java, AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/CardQueue.java, AnkiDroid/src/main/java/com/ichi2/utils/FunctionalInterfaces.java, AnkiDroid/src/main/java/com/ichi2/utils/Permissions.java, AnkiDroid/src/main/java/com/wildplot/android/parsing/TopLevelParser.java, lint-rules/src/main/java/com/ichi2/anki/lint/utils/LintUtils.java
Those warning makes a lot of sens, but it would lead to "isForbidden" instead of "isAuthorized" which makes little sens
in practice
=> NF: ignore BooleanMethodIsAlwaysInverted

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/libanki/stats/AdvancedStatistics.java
That's the closest to system constant in JAVA
=> NF: make constant static

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractDeckTreeNode.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckDueTreeNode.java, AnkiDroid/src/main/java/com/ichi2/ui/SlidingTabLayout.java
Would probably have detected the bug related to cards in learning badly tested
=> NF: remove rendundant constraints

AnkiDroid/src/main/java/com/ichi2/anki/stats/OverviewStatsBuilder.java, AnkiDroid/src/main/java/com/ichi2/libanki/Tags.java, AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.java
This one require more close consideration. The change is NF, but it may be because it is actually currently buggy.
=> NF: remove collections which are never read or never written

AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
This one require more close consideration. The change is NF, but it may be because it is actually currently buggy.
=> NF: remove warning about Int tested with = instead of equals

AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
This port https://github.com/ankitects/anki/commit/133fe8518b3b19408b693235aca0d55beaada6ac
=> NF: remove mChangedGuids

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java, AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.java, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/Counts.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java, AnkiDroid/src/main/java/com/ichi2/widget/WidgetStatus.java, AnkiDroid/src/test/java/com/ichi2/libanki/UndoTest.java, AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java, AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.java, AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.java
I don't like int[] when we know exactly that they are three elements. Furthermore, counts appear in enough place that it
makes sens to create a class for it. This makes for more readable code
=> NF: represents counts as a class

AnkiDroid/src/main/java/com/ichi2/libanki/importer/python/CsvReaderIterator.java
I'll probably need to find a way to remove the warning globally. Usually there were good reason for empty if
=> NF: add braces on empty if

AnkiDroid/src/main/res/values-zh-rCN/02-strings.xml
Standard Language Sync github action PR
Only one tiny change but the Chinese translation volunteer is *on it*! They already got the string addition from yesterday. Rest are slackers :rofl:
=> Updated strings from Crowdin 20200922

AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/DB.java, AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java
Fixes #7265 
Call `inTransaction` and use a `try...catch`
Only unit tests
=> Ensure closing transaction won't crash

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
=> Fix Dark Icons in Light Mode

AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java, AnkiDroid/src/main/java/com/ichi2/async/CollectionLoader.java
=> LOG: Collection Locking/Loading

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
This corrects the previewCard method. It seems it never should have been card types.
Note it's never used.
=> NF: Preview cards

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ACRATest.java, AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/CollectionTest.java, AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.java, AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/InstrumentedTest.java, AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/LayoutValidationTest.java, AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/NotificationChannelTest.java, AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/ImportTest.java, AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/MediaTest.java, AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/ModelTest.java
Mostly to `InstrumentedTest`, and a few others:
`ContentProviderTest:getContentResolver`
`ACRATest:getSharedPrefs`
`getCol()` is useful for testing Rust
Test-only
=> NF: Extract Helper methods

AnkiDroid/src/main/java/com/ichi2/anki/Info.java, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/res/layout/info.xml
Button brings up a picker containing AppGallery, F-Droid and Google Play Store on my Android 9.
"Continue" is full-width if rating is not available
Fixes #7301
=> Add "Rate AnkiDroid" to changelog

AnkiDroid/src/main/java/com/ichi2/libanki/Models.java, AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.java
As requested by @mikehardy  in https://github.com/ankidroid/Anki-Android/pull/7306#discussion_r496715244
=> NF: Constant for req's string

AnkiDroid/src/main/res/values-ar/03-dialogs.xml, AnkiDroid/src/main/res/values-ar/10-preferences.xml, AnkiDroid/src/main/res/values-sr/01-core.xml, AnkiDroid/src/main/res/values-zh-rCN/03-dialogs.xml
Standard language sync from actions I18N branch
=> Updated strings from Crowdin 20200929

AnkiDroid/src/main/java/com/ichi2/anim/ActivityTransitionAnimation.java, AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.java, AnkiDroid/src/main/java/com/ichi2/anki/Info.java, AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java, AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java
This was detected as a problem with switch and an empty case. But it seems this was more important as far as typing goes
=> NF: use enum for direction

AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java, AnkiDroid/src/main/java/com/ichi2/libanki/exception/UnknownDatabaseVersionException.java, AnkiDroid/src/main/java/com/ichi2/utils/UiUtil.java, AnkiDroid/src/main/res/values/03-dialogs.xml
This is a draft so we can discuss the text and what we want to propose to the user.
This means that the database has been upgraded, and there is currently no way of downgrading from an earlier version
Fixes #7072
Depends on #7073
Check the database version and show a better dialog
Android 9
=> Show useful error when col version is too high

AnkiDroid/src/main/java/com/ichi2/anki/Info.java
Some users were having issues closing the screen.
Fixes #7333
=> Add "Back" to changelog

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java, AnkiDroid/src/main/res/values/constants.xml
See https://github.com/ankidroid/ankidroiddocs/pull/73
=> Add Arabic docs links

AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java
Follow-up from #7343
Even with no SecurityManager you can't write anything in `java.`
=> NF: Remove Failed attempt at JDK 11 conversion

AnkiDroid/src/main/java/com/ichi2/libanki/Models.java, AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
Various refactorings to speed up and improve memory allocations in `importNotes`
Improves #7122 
* StringBuilder
* Presize collections
* NF: Use try with resources
Untested
=> NF: Speed up Import

AnkiDroid/build.gradle, build.gradle, lint-rules/build.gradle
Standard dependency updates pull
Not much interesting here except perhaps Android Studio 4.0.2 is out and this bumps the gradle plugin
=> Dependency updates 20201007

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.java, AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java, AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java, AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java, AnkiDroid/src/main/java/com/ichi2/libanki/Models.java, AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java, AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java, AnkiDroid/src/main/java/com/ichi2/libanki/importer/NoteImporter.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java, AnkiDroid/src/main/java/com/ichi2/preferences/StepsPreference.java, AnkiDroid/src/main/java/com/ichi2/utils/JSONArray.java
https://github.com/ankidroid/Anki-Android/pull/7313 was closed by accident and I can't reopen it. This takes the correction request by @david-allison-1 into account and factorize the first commit
=> Iterate json

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/LaTeX.java, AnkiDroid/src/main/java/com/ichi2/libanki/Media.java
I missed some JSONObject which should have been Model
=> NF: more Model as type

AnkiDroid/src/main/res/layout/widget_small.xml
Fixes #7366
> A RemoteViews object (and, consequently, an App Widget) can support the following layout classes:
https://stackoverflow.com/a/6150129
=> Fix Broken Widget

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.java, AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java
The field was not updated
Fixes #7363 
Unit tests - briefly with physical device
=> [BugFix] Update "Correct" Typed answer after Note Edit

AnkiDroid/build.gradle, AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java, AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java, AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java, build.gradle, lint-rules/build.gradle
Standard dependency updates with 2 fiddly bits:
- Android Gradle Plugin 5 will generate resource files ('R' references) that are non-final, so they can't be used with switch statements or as annotations. I converted the switches to chained ifs per Google guidance but there's no easy transformation for annotations that take R references. I logged an upstream issue: https://github.com/ACRA/acra/issues/810
- Gradle Triple-T publisher (our Play Store plugin) changed it's configuration syntax
=> Dependency updates 20201013

.github/pull_request_template.md
This is particularly important for translation, since new strings must be uploaded to crowdin. But it seems a good rule
in general too when the change is not NF
For some reason, I can't edit the existing branch, so here it is in a new branch
=> Asking for screeshot

gradle.properties
Should speed up incremental builds.
https://docs.gradle.org/6.7/release-notes.html#performance-improvements
https://blog.gradle.org/introducing-file-system-watching
https://docs.gradle.org/current/userguide/gradle_daemon.html#sec:daemon_watch_fs
=> PERF: Enable Gradle File System Watching

AnkiDroid/src/main/java/com/ichi2/async/BaseAsyncTask.java, AnkiDroid/src/main/java/com/ichi2/async/ProgressSender.java
It seems I failed something while introducing interface. No idea what exactly, but I got an exception stating that
Object[] can't be cast to TaskData[]
No idea what to do as regression test.
----
Fixes #7391
=> Correct ProgressSender

AnkiDroid/src/main/java/com/ichi2/libanki/Models.java
Since I'm already dealing a lot with avail ords, let's use switch and simplifies using java's syntax.
=> NF: simplifies Avail ords

AnkiDroid/src/main/res/values/16-multimedia-editor.xml, AnkiDroid/src/main/res/values/18-standard-models.xml
Explain the difference between both texts ressources
=> NF: annotate text

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateBrowserAppearanceEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/IntegerDialog.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.java, AnkiDroid/src/main/res/values/04-network.xml
The original string was used only once in a network related file and in a dialog. So there is no point in this duplication and this makes translation longer
=> NF: replace string cancel by dialog_cancel

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.java, AnkiDroid/src/main/res/values/02-strings.xml, AnkiDroid/src/main/res/values/04-network.xml
Those strings appear in different context but always means the same thing, so probably should get the same translation
=> NF: remove duplicate "help"

AnkiDroid/src/main/java/com/ichi2/libanki/StdModels.java, AnkiDroid/src/main/res/values/18-standard-models.xml
I checked upstream, both uses the same id
=> NF: remove duplicate cloze

AnkiDroid/src/main/res/values/10-preferences.xml, AnkiDroid/src/main/res/xml/deck_options.xml, AnkiDroid/src/main/res/xml/preferences_reviewing.xml
I doubt there is reason for duplicate here
=> NF: Remove duplicate "Automatic display answer"

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java, AnkiDroid/src/test/java/com/ichi2/testutils/IntentAssert.java
Fixes #7420 
Unit tested and on my device
=> Use Card Browser's Selected Deck when adding note 

AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckDropDownAdapter.java, AnkiDroid/src/main/res/layout/dropdown_deck_selected_item.xml, AnkiDroid/src/main/res/values/06-statistics.xml
Those are so similar that the "card browser" one is already used in the statistic window
=> NF: remove duplicate "All decks"

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
Fixes #7438 
Don't close the app
Untested
The "Open Changelog" button on the Advanced Settings wasn't enough
=> Fix App closing after pressing "Back" on changelog

AnkiDroid/src/main/java/com/ichi2/libanki/Models.java
It transform a set into an array, however this array is only ever used for ids2str, which directly accept a set. So this
win some time
=> NF: Models.ids() quicker

AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
None of those change seems to lead to change in the set of deck, so no synchronizatino conflict
=> NF: Avoid useless construction of array

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
I should have done it when changing Long to long
=> NF: add non null

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
This reduce _tmplsFromOrds from 30 seconds to 15 seconds. It clone using the method created for cloning
=> NF: uses clone instead of creating string and reading it

AnkiDroid/src/main/java/com/ichi2/libanki/Models.java, AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.java
Following advice of https://github.com/ankidroid/Anki-Android/pull/7296#discussion_r510550202 I cache the result of a function called multiple time with the same value
=> Cache result of a part of _availClozeOrds

AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java, AnkiDroid/src/main/java/com/ichi2/anki/stats/OverviewStatsBuilder.java, AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.java, AnkiDroid/src/main/res/values/06-statistics.xml
The name should probably be the same in the title of the stats and in the title of the card type activity
=> NF: remove duplicate "Card types"

AnkiDroid/src/main/res/menu/card_template_editor.xml, AnkiDroid/src/main/res/values/01-core.xml
I may imagine some language willhave the word depending on what is deleted. But since delete is already use for note and deck, let's use it also for card type unless someone state we need to differentiate
=> Duplicate delete

AnkiDroid/src/main/res/layout/card_info.xml, AnkiDroid/src/main/res/values/03-dialogs.xml, AnkiDroid/src/main/res/values/07-cardbrowser.xml
I keep to "due". The due date, and the due state of card. I comment to separate them. I removed one of the two due date
=> NF: duplicate due

AnkiDroid/src/main/res/values/03-dialogs.xml
And with this PR I can tell you I'm quite HAPPY that this part of the work is done. There is no more unexplained duplicate string ressources.
=> NF: remove unused resource

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java, AnkiDroid/src/test/java/com/ichi2/libanki/CardTest.java
Same as https://github.com/ankidroid/Anki-Android/pull/7514
=> null->NULL

AnkiDroid/src/main/res/values/01-core.xml, AnkiDroid/src/main/res/values/03-dialogs.xml
I suspect that there may be a difference in some language depending on what you create. So I just comment
=> Duplicate create

AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.java
This was tested by opening stats and seeing the number didn't change
=> NF: simplify a query

AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java
Hopefully fixes #7431
Haven't been able to repro locally, but had 2 Travis failures due to this
=> moveToNonDynamicDeckWorks: Add Sleep to avoid bug

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/res/menu/popupmenu_multimedia_options.xml, AnkiDroid/src/main/res/values/16-multimedia-editor.xml, AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.java
=> Note Editor: Add Clear Field button

AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.java
=> Add sleep for: validEncodingSetsAnswerCorrectly

AnkiDroid/build.gradle
Standard small bumps
contains constraintlayout bump which may have bearing on #7539 @david-allison-1  ?
=> Dependency updates 20201028

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java, AnkiDroid/src/main/res/values/17-model-manager.xml
This PR is intended for discussion: what should we do about logically unreachable strings.
They can theoretically happen via use of the API, but is it worth adding these to the list of strings to translate?
=> Card Template Editor: Remove Unreachable Strings

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java, AnkiDroid/src/main/java/com/ichi2/libanki/Note.java, AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java
Some work is done many time without change. In particular, we need to apply stripHTMLMedia to first field and to sort field. This optimize the case, that I suspect to be usual, where the sort field is the first field. This should save plenty of time in check database in particular
=> stripHTMLMedia

api/src/main/java/com/ichi2/anki/api/AddContentApi.java
This return null if data absent. It's always call with `long`
=> NF: simplify getModelName

AnkiDroid/src/main/java/com/ichi2/libanki/Deck.java, AnkiDroid/src/main/java/com/ichi2/libanki/Model.java, AnkiDroid/src/main/java/com/ichi2/utils/JSONObject.java
=> NF: return directly from deepCloneInto

AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtonStatus.java
Was intended to be `MENU_DISABLED` to match preferences
=> BugFix: Fix Card Info action bar visibility

AnkiDroid/src/main/res/values/styles.xml
This allows a user to search by Note ID, for example
Fixes #7376
=> Card Info: Make data selectable

AnkiDroid/src/test/java/com/ichi2/async/AbstractCollectionTaskTest.java, AnkiDroid/src/test/java/com/ichi2/async/CollectionTaskCheckDatabaseTest.java
And fixes the "unchecked" build warning
=> Fix test: checkDatabaseWithLockedCollectionReturnsLocked

AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
Some preference titles were incorrect
Related: #7537
=> Fix 9-point Gesture Preference titles

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
Removed accidentally in 7bfc313ea25f3ba79f99662795387abed64dfd78
Related: #7571
=> NF: Fix string removal: cancel_sync_confirm

AnkiDroid/src/main/res/values/02-strings.xml
We should use these for accessibility
To be fixed by #7570
Related #7571
=> Mark Navigation Drawer Strings as Used

AnkiDroid/src/main/res/values/03-dialogs.xml
I feel this will be useful in the future
Related: #7571
=> NF: Mark dialog_positive_disable as unused

AnkiDroid/src/main/java/com/ichi2/libanki/DB.java
As requested on https://github.com/ankidroid/Anki-Android/pull/7532#issuecomment-717580859
With a sqlite database, it's not even clear how a null exception could occurs, since type is loose, and so null would be transformed into 0 or empty string
=> NF: remove DB.list

AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.java
This has no side effect and the value is not returned.
=> NF: remove useless function call

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/res/values/constants.xml
Hopefully helps non-techie users get started (font color etc...)
Related: https://github.com/ankidroid/ankidroiddocs/pull/78
=> Note Editor Toolbar: Add Help Button

AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
Constants were not used where they should have been
=> NF: uses constants

AnkiDroid/src/main/java/com/ichi2/anki/MetaDB.java, AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.java, AnkiDroid/src/main/java/com/ichi2/anki/stats/OverviewStatsBuilder.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/Media.java, AnkiDroid/src/main/java/com/ichi2/libanki/Models.java, AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java, AnkiDroid/src/main/java/com/ichi2/libanki/stats/AdvancedStatistics.java, AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java
Simplifying reading code using try ressources. Deleting 272 lines of code in the way
=> NF: Convert to try with resources

AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java, AnkiDroid/src/main/java/com/ichi2/libanki/importer/NoteImporter.java
Nothing is ever added to this list
=> NF: remove useless variable

AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
I can hardy imagine what good there would be
=> NF: remove some unused methods

AnkiDroid/src/main/java/com/ichi2/anki/MetaDB.java, AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java, AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.java, AnkiDroid/src/main/java/com/ichi2/anki/stats/OverviewStatsBuilder.java, AnkiDroid/src/main/java/com/ichi2/libanki/Card.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java, AnkiDroid/src/main/java/com/ichi2/libanki/Media.java, AnkiDroid/src/main/java/com/ichi2/libanki/Models.java, AnkiDroid/src/main/java/com/ichi2/libanki/Note.java, AnkiDroid/src/main/java/com/ichi2/libanki/Tags.java, AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java, AnkiDroid/src/main/java/com/ichi2/libanki/stats/AdvancedStatistics.java, AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java, AnkiDroid/src/main/java/com/ichi2/utils/DatabaseChangeDecorator.java
They were found using
```sql
= ?" ?\+
```
=> NF: uses parametrized query where possible

AnkiDroid/src/main/AndroidManifest.xml
https://github.com/ankidroid/Anki-Android/issues/6726
This PR should fix #6726
Fixes [6726](https://github.com/ankidroid/Anki-Android/issues/6726)
Adding an attribute to the manifest
I've build it and tested it on Samsung Galaxy Tab S6 with Samsung Dex
Adding an attribute makes life easier for users
* https://developer.samsung.com/samsung-dex/modify-optimizing.html
=> feature #6726: make app resizable on Android desktops

AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java
Converting to list is inefficient, at least when there are a lot of decks. Set makes more sens here
=> NF: uses treemap instead of array list

AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
I looked for all strings with a unique unicode symbol and found no other replace with a string with one letter
=> Replace some string by char

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java, AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java, AnkiDroid/src/main/java/com/ichi2/libanki/Tags.java, AnkiDroid/src/test/java/com/ichi2/libanki/CollectionTest.java
Those values without conversion are already usable as-is
=> NF: calls ids2String without useless conversions

AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.java, AnkiDroid/src/main/res/values/styles.xml
=> Editor Toolbar: Handle Night Mode

AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java
=> TEST: Fix selectNoneIsVisibleOnceSelectAllCalled

AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
=> [BugFix]: MyAccount - NullPointerException

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java, AnkiDroid/src/main/java/com/ichi2/utils/JSONArray.java
Following the advice of https://github.com/ankidroid/Anki-Android/pull/7632#discussion_r519949917 and adding an extra function to remove duplicate code
=> Json array >list

AnkiDroid/src/main/java/com/ichi2/anki/Info.java, AnkiDroid/src/main/res/layout/info.xml, AnkiDroid/src/main/res/values/constants.xml
Encourage people to donate to our new OpenCollective
Add a button which links to https://opencollective.com/ankidroid#section-contribute
Android 9 and API 16 emulator
=> Add Donate link to Changelog and About AnkiDroid

.github/FUNDING.yml
https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository
Needs a repo setting change as well: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository#displaying-a-sponsor-button-in-your-repository
=> Add Sponsor button to repo (Open Collective)

AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java, AnkiDroid/src/main/java/com/ichi2/libanki/Note.java, AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java, AnkiDroid/src/main/java/com/ichi2/libanki/utils/NoteUtils.java, AnkiDroid/src/main/java/com/ichi2/utils/CollectionUtils.java
I tried to go through with https://github.com/ankidroid/Anki-Android/pull/7616#issuecomment-723705392 comment and added more addAll, for the cases where values to add are in an iterator or an array
I actually added some more, using essentially filter and/or map, but I'll keep it for when this simpler PR is merged
=> NF: addAll

AnkiDroid/src/main/res/values-ja/01-core.xml, AnkiDroid/src/main/res/values-ja/07-cardbrowser.xml, AnkiDroid/src/main/res/values-sk/01-core.xml, AnkiDroid/src/main/res/values-sk/02-strings.xml, AnkiDroid/src/main/res/values-sk/03-dialogs.xml, AnkiDroid/src/main/res/values-sk/04-network.xml, AnkiDroid/src/main/res/values-sk/06-statistics.xml, AnkiDroid/src/main/res/values-sk/07-cardbrowser.xml, AnkiDroid/src/main/res/values-sk/09-backup.xml, AnkiDroid/src/main/res/values-sk/10-preferences.xml, AnkiDroid/src/main/res/values-sk/11-arrays.xml, AnkiDroid/src/main/res/values-sk/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-sk/17-model-manager.xml, AnkiDroid/src/main/res/values-sk/18-standard-models.xml
standard I18N sync before a release
=> Updated strings from Crowdin 20201111

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportDialog.java, AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java, AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java, AnkiDroid/src/main/java/com/ichi2/libanki/Models.java
I believe it's better to use a constant than -1L everywhere
=> Not found deck id constant

AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java
=> Fix flaky test: confirmDeckDeletionDeletesEmptyDeck

AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java
Hopefully fixes #7565
Related: #7654
Re-push of #7635
=> Fix flaky test: limitAppliedAfterReview

AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.java
Couldn't replicate this bug
Fixes #7658
=> BugFix: Handle null inputConnection

AnkiDroid/src/main/res/values/03-dialogs.xml
Keyboard Hint Selection -> Keyboard Language Selection
"Hint" was a fairly meaningless word
=> NF: Improve string: locale_selection_dialog_title

AnkiDroid/src/main/res/values-eo/01-core.xml, AnkiDroid/src/main/res/values-eo/02-strings.xml, AnkiDroid/src/main/res/values-eo/11-arrays.xml
=> Updated strings from Crowdin 20201112

AnkiDroid/src/main/res/layout/widget_small.xml
Add a few `tools:` attributes to make it look sensible on a 1x1 grid
=> NF: Improve widget in designer

AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
This way it's clear that it's not doing anything special here, anything different than in other functios
=> NF: replace a line by a function doing the same thing

AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java
A small simplification, using sql query to get uniqueness instead of set.
=> NF: Use sql to query distinct directly

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/Undoable.java, AnkiDroid/src/main/res/menu-television/reviewer.xml, AnkiDroid/src/main/res/menu/reviewer.xml, AnkiDroid/src/main/res/values/01-core.xml, AnkiDroid/src/main/res/values/02-strings.xml, AnkiDroid/src/main/res/values/03-dialogs.xml, AnkiDroid/src/main/res/values/10-preferences.xml, AnkiDroid/src/main/res/values/17-model-manager.xml, AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java
Should unblock #7582
Untested (aside from CI)
=> Fix Duplicate Strings lint warnings

AnkiDroid/src/main/res/values-it/02-strings.xml, AnkiDroid/src/main/res/values-it/10-preferences.xml, AnkiDroid/src/main/res/values-zh-rCN/10-preferences.xml
=> Updated strings from Crowdin 20201118

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/java/com/ichi2/libanki/Models.java, AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.java, AnkiDroid/src/main/java/com/wildplot/android/rendering/graphics/wrapper/GraphicsWrap.java, AnkiDroid/src/test/java/com/ichi2/anki/ReviewerKeyboardInputTest.java
This partially deal with the warning that some methods always return the same value. 
There are two many warnings where I miss the context to know what to do with them. Some methods could probably be replaced by static final constants.  Some other methods seems related to work in progress where a more interesting value may be eventually used.
=> Always return same value

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.java
I thought I already removed all of them. I'm confused
=> NF: uses ids2str without conversion

AnkiDroid/src/test/java/com/ichi2/libanki/NoteTest.java
Test only - Robolectric was not used
=> Speed up NoteTest

AnkiDroid/src/main/res/menu/card_browser_multiselect.xml, lint-release.xml
"Card Info" was hardcoded
Fixes #7758
* Fix the string
* Enable linting for CI so this will not happen again
`gradlew AnkiDroid:lintRelease` with the updated config previously failed, now passes.
=> Fix Hardcoded Strings in App ("Card Info")

AnkiDroid/src/main/java/com/ichi2/async/CancelListener.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
Each call to isCancelled first check whether the object is null. This get factorized in a static function
=> NF: isCancelled easier

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.java, AnkiDroid/src/main/res/values/02-strings.xml
* The `shortcutManager.requestPinShortcut` could both throw and return a boolean
* Vivo phones have an app that we can request permission from - special-case this
Fixes #7743
* check the result, catch the exception, and special case the failure case to see if vivo works
Untested - need to confirm with user once the alpha is out
https://developer.android.com/reference/android/content/pm/ShortcutManager#requestPinShortcut(android.content.pm.ShortcutInfo,%2520android.content.IntentSender)
Phone data: https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/reports-browser/user/ae733d56-a5ac-46eb-ba84-1b655fb818d0
Vivo issue: https://www.youtube.com/watch?v=zl3CFjPUKeo.
=> Improve Create Shortcut error handling

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java
We didn't modify our UI state from the crop dialog
Fixes #7768
Tested on my Android 9
=> Fix image crop required twice

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java, AnkiDroid/src/main/java/com/ichi2/anki/Info.java
It's very useful to know this setting to know if it's worth checking ACRA
API 26 emulator
=> Add "Crash Reports Enabled" to debug info

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
Suggested by Md7 on Discord
Unit tests still run & pass
=> Add "Study" and "Delete Note" keyboard shortcuts

AnkiDroid/build.gradle, AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/GestureTapProcessor.java, AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.java, AnkiDroid/src/main/java/com/ichi2/libanki/importer/python/CsvReaderIterator.java
And adds a compiler error if any are added
Fixes #7813
=> LINT: Fix missing fallthroughs

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
The set is absolutely not used. And once removed, both branches are equal
=> Simplify update card in list

AnkiDroid/src/main/java/com/ichi2/libanki/Card.java
Writing is a skill. I've improved
=> NF: Improve comment on dynamic cards

AnkiDroid/src/main/java/com/ichi2/anki/MetaDB.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java, AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardAppearance.java, AnkiDroid/src/main/java/com/ichi2/anki/model/WhiteboardPenColor.java, AnkiDroid/src/test/java/com/ichi2/anki/ReviewerNoParamTest.java, AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.java, AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java, AnkiDroid/src/test/java/com/ichi2/anki/WhiteboardDefaultForegroundColorTest.java
User requested
Fixes #7834 
Persist the value in MetaDB, group by deck/light mode
Unit Tested (including a full run) - brief emulator test
* I'm glad we're better at testing, but it might have added too much friction to this change
* Adding new columns to MetaDB could be much easier - consider an alternate library for the far future.
=> Persist Whiteboard Pen Color 

AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java, AnkiDroid/src/main/java/com/ichi2/libanki/importer/NoteImporter.java
This map is always used with same value. So this is actually just a set.
=> NF: replace a map with single value to set

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.java, AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java, AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java, AnkiDroid/src/main/java/com/ichi2/libanki/Model.java, AnkiDroid/src/main/java/com/ichi2/libanki/Models.java, AnkiDroid/src/main/java/com/ichi2/libanki/importer/NoteImporter.java, AnkiDroid/src/main/java/com/ichi2/utils/JSONArray.java, AnkiDroid/src/test/java/com/ichi2/anki/CardTemplatePreviewerTest.java
This is a previous PR back, slightly differently. Factorize some code by putting together getFieldNames and getTemplateNames, which are both used multiple time
=> NF: get field/template names

AnkiDroid/build.gradle, AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
This will be a standard dependency updates PR but without CI it needs a personal check (by me) and I want to see if we collect any other updates before merging it
=> Dependency Updates 20201125

AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
This remove a warning that CardQueue was returned with UncheckedType... not clear how it improves anything in term of typing, but at least this remove the warning
=> NF: Remove warning about unchecked CardQueue

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
It remains to add a regression test, but I don't know how to create a DeckPicker and get a menu
=> Correct #7846: deck picker don't crash with no folder access

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/RescheduleDialog.java, AnkiDroid/src/main/java/com/ichi2/libanki/Card.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
isDynamic is literally defined as checking whether ODid is non null. So this makes no change, appart from the fact that it gets easier to read
=> NF: using isDynamic when possible for readability

AnkiDroid/src/main/java/com/ichi2/anki/CardInfo.java, AnkiDroid/src/main/java/com/ichi2/anki/stats/OverviewStatsBuilder.java, AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/Media.java, AnkiDroid/src/main/java/com/ichi2/libanki/Tags.java, AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java
This is a second part of https://github.com/ankidroid/Anki-Android/pull/7612, where initialization is a little more costly, because it requires a first call to database to count result set before getting the actual number.
=> NF: init capacity

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java, AnkiDroid/src/main/java/com/ichi2/async/Connection.java
I suspect that only the last commit is the important one, fixes #7863 and probably fixes #7861. In the first commit of #7150 it was done corerctly f8512af52fcae210a92f34c360f9ecb4db33c8ac , but it seems I mis merged it with 
47dd6596f3e4a3da45d145365f739b241c83d1ed
I guess the main question here is how to do a regression test, which probably reduce to "how to mock synchronization"
I tried to sync on my phone, and it works again, even if I sync twice. (I'm testing with https://github.com/Arthur-Milchior/Anki-Android/tree/correct_sync which merges all PR I made today, simplifying Sync )
=> Correcting #7150

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractDeckTreeNode.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
This remove warning that the type `AbstractDeckTreeNode` does not have parameter types.
Solutions are `<?>` when the parameter does not matter, and `<T extends AbstractDeckTreeNode<T>>` when the type matter
=> NF: Add good type parameter to AbstractDeckTreeNode

AnkiDroid/src/main/java/com/ichi2/async/Connection.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/FullSyncer.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/HttpSyncer.java
The pair was useless as second element was always null
=> NF: `download` return ConnectionResultType instead of pair

AnkiDroid/src/main/java/com/ichi2/libanki/Models.java, AnkiDroid/src/main/java/com/ichi2/libanki/Note.java
I only changed the variables that I know. There are a lot other that can be made final, that gives warning in android
studio, but I don't know
=> NF: set some variable to final

AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java
There remain two pairs without bracket, but it's because there are wrong
=> NF: add brackets to pairs

AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
Remove a warning about unchecked type
=> NF: add type parameter to card queue

AnkiDroid/src/main/java/com/ichi2/async/BaseAsyncTask.java, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java, AnkiDroid/src/main/java/com/ichi2/async/ProgressSender.java
This also moves the warning about unchecked from all doProgress to the definition of doProgress
=> NF: doProgress takes a single parameter

AnkiDroid/src/main/java/com/ichi2/libanki/sched/SimpleCardQueue.java
I have no idea why I added it, clearly, this CardQueue is expected to be used in real code
=> NF: remove @VisibleForTesting

AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.java
The `T` is already introduced in the class above
=> NF: remove redundant type introduction

AnkiDroid/src/main/res/values/11-arrays.xml, AnkiDroid/src/main/res/values/constants.xml
Added record and replay voice action for gestures. Commands were already set, but the buttons were not added in the preferences.
Tested using the UI in emulator + phone, using swiping gestures.
Similar to https://github.com/ankidroid/Anki-Android/pull/7923
=> Record and Replay voice gesture actions

api/build.gradle
Bump the gradle version for the API package.
It's been untested (sorry). However this *shouldn't* break anything. The release machinery is what needs actual testing and I'm not capable of testing that :)
Hopefully it all works out.
- Sorry, the github editor added an extra newline but it shouldn't be catastrophic.
=> Bump API to 1.1.0

.github/ISSUE_TEMPLATE/feature_request.md, .github/issue_template.md
https://github.com/ankidroid/Anki-Android/pull/7930 was closed by accident, because I psuhed master in it while correcting
=> Uses github specific feature request/bug report

tools/update-localizations.py
01-core hit 100%, so we can import it for testing
This does not enable it in the UI, but allows a language sync and testing
https://crowdin.com/project/ankidroid/or#
Related: #7850
=> Import 'Odia (India)' language from CrowdIn

AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java
Anki trim field name when they are added/renamed (but not when they already exists). 
Assuming https://github.com/ankitects/anki/pull/869 gets merged, this PR will get more commits, unless it gets merged quickly.
=> Field name
