AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
Trivial change, but this has annoyed me two or three times already. The rename operation already has this.
=> Restrict name of new decks to a single line

AnkiDroid/src/main/res/values/07-cardbrowser.xml
I believe this should be sort field, not search field.
=> Rename search field to sort field in card browser order dialog

AnkiDroid/build.gradle, AnkiDroid/src/main/AndroidManifest.xml, AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/Info.java, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/res/values-v14/styles.xml, AnkiDroid/src/main/res/values/05-feedback.xml, AnkiDroid/src/main/res/values/styles.xml, AnkiDroid/src/main/res/xml/preferences.xml
This PR switches the AnkiDroid error reporting over to ACRA / Acralyzer on ankidroid.org and makes the error reporting occur automatically in the background by default (a toast is shown so the user knows). This is not quite ready to merge as I need to finalize some details about the couchdb authentication with @agrueneberg 
See the [discussion on the forum](https://groups.google.com/forum/#!topic/anki-android/RQqxcITIqYE) for more background info
=> Switch error reporting over to ACRA @ ankidroid.org

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
AnkiDroid accepts the generic Android SEND intent, but it expects the front to be in EXTRA_SUBJECT and the back to be in EXTRA_TEXT. As per [forum thread](https://groups.google.com/forum/#!topic/anki-android/8Tu5tUlZgmI), generic apps like Gmail can send a selected word via SEND, but it sends the single word in EXTRA_TEXT with EXTRA_SUBJECT empty. 
In hindsight, having EXTRA_SUBJECT map to the first field was not an optimal design decision. It makes much more sense to have TEXT map to the first field (which should always be included) and SUBJECT map to the second field (which is optional), but we can't really change it now, so I've implemented this workaround.
=> When using SEND intent with SUBJECT empty, make TEXT the first field

AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/MediaTest.java
Changes introduced in #681 are causing tests to fail. We established that it's because the runner for `AndroidTestCase` is running in a different thread from the main application, and doesn't seem to synchronize to wait for `Application.onCreate()` to finish. This seems like a bug in `AndroidTestCase`, although there is a possibility we're doing something wrong.
A better solution would probably be to use a more advanced testing class that doesn't suffer from this problem, but this hack does the job, so we can use it if nobody is motivated to make a more robust fix
=> Hack to prevent tests failing due to hooks not being initalized

tools/manage-crowdin.py, tools/update-localizations.py
Made the following changes to crowdin scripts:
* Use new folder structure
* When updating master, make the user enter the full name of the file they want to update instead of just the index, as some numbers are missing
* Use `urllib.urlretrieve()` instead of `urlopen()` for getting the zipfile (was throwing error on windows)
* Use `shutil.move()` instead of `os.rename()` for renaming (was throwing error on windows)
=> Update crowdin scripts

AnkiDroid/src/main/java/com/ichi2/libanki/Media.java
Fix for [Issue 2454](https://code.google.com/p/ankidroid/issues/detail?id=2454). It's a small fix so I think it should go into 2.4. This code is used in the exporter as well so I'm assuming exporting decks with latex images could be broken as well without it (haven't tried).
=> Fix for latex fields in media check

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDb.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
Don't try to reopen the database after attempting repair, and do a full force close of the app when "close" button is pressed on DB error dialog.
=> Small modificiations based on feedback from issue 1920

AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.java, AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java
When AnkiDroid is started for the first time, it tries to make a backup of the uninitialized empty collection, which when imported crashes AnkiDroid. This is a workaround for those two bugs, but really we probably shouldn't be doing the backup while the database is open
=> Don't create or import invalid backups

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/Models.java, AnkiDroid/src/main/java/com/ichi2/libanki/hooks/FuriganaFilters.java
A fix for [Issue 2470](https://code.google.com/p/ankidroid/issues/detail?id=2470) and a bunch of other things. I went over the code that handles cloze tag parsing and rendering and found quite a few problems with it, including the related code that handles nesting and ordering of fields with multiple modifiers. This should bring things in line with the desktop client.
In short, nested modifiers in fields will now work correctly. Things like:
`<cloze:furigana:FieldName>`
`<type:cloze:FieldName>`
`<text:cloze:FieldName>`
There is a potential that this change will break something else so if you have any large or complex templates, I would appreciate a test run to see how things go.
=> Correctly parse and render cloze fields and nested modifiers

AnkiDroid/src/main/java/com/ichi2/anki/CramDeckOptions.java
There are eight entries numbered 0 through 7, but my saved preference was an 8, so getEntry returned null, and toString on the null caused a crash.
Quickly after verifying that I no longer crashed on deck options display, I lost the old out of bounds setting. I have not verified if the invalid setting would cause any other issues, and have only handle the deck options initial display crash.
=> Check for invalid order by preference in filtered decks

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
Fix for [Issue 2515](https://code.google.com/p/ankidroid/issues/detail?id=2515). 
I went over this issue with a user over email and this fixed the problem. There is at least one device out there that zooms in a level or two on WebViews for whatever reason, and it makes reviewing difficult since WebViews now don't wrap text when zooming in.
I've witnessed no other side effects of adding this line in my tests so I think it's safe to add for everyone.
=> Load cards in overview mode (zoomed out)

AnkiDroid/src/main/AndroidManifest.xml, AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.java, AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java, AnkiDroid/src/main/res/values/02-strings.xml
When a file is opened via a ContentProvider like the Android Download manager, and there is an error getting the filename, try to import it if it's a valid zipfile
Also:
* Show "import failed" message instead of collection error dialog when an exception occurs during importAdd
* Show a link to the importing section of the manual when the file can't be automatically imported
* The Lollipop native email client seems to use mimetype "application/x-EXTENSION" when trying to open unknown extensions, so support that
=> Try to fix apkg import errors

AnkiDroid/src/main/res/menu/reviewer.xml, AnkiDroid/src/main/res/values/01-core.xml
See #689.
@timrae I removed `menu_edit_card` after checking that there are no further occurrences.
=> Rename "Edit card" to "Edit note"

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
Fix for [issue 2503](https://code.google.com/p/ankidroid/issues/detail?id=2503) and potentially any other crashes that occur because of simple interface.
To be honest, I think we should just remove simple interface entirely... It's not really necessary with the power of modern Android devices, and we could always add it back eventually as a plugin
=> Catch all simple interface exceptions

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
When moving a card, we forgot to call `updateTypeAnswerInfo` to get the correct text for the type answer feature, causing [issue 1499](https://code.google.com/p/ankidroid/issues/detail?id=1499). Maybe something went wrong with cloze deletions without that call, too, but i don't use clozes much.
=> Fix issue 1499

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/AnkiDb.java, AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java, AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.java, AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.java, AnkiDroid/src/main/java/com/ichi2/anki/exception/StorageAccessException.java, AnkiDroid/src/main/java/com/ichi2/async/CollectionLoader.java, AnkiDroid/src/main/java/com/ichi2/async/Connection.java, AnkiDroid/src/main/res/values/01-core.xml
Modified patch for #724... the main differences being:
* `AnkiDroidApp.initializeDirectory()` is called in `AnkiDroidApp.onCreate()` which guarantees that it's called on first app startup, whereas #733 assumes that `AnkiActivity.onCreate()` is called before the path is used.
* `AnkiDroidApp.initializeDirectory()` is additionally called at the time of setting the path in Preferences, which prevents the user from ever setting an incorrect directory
* An ACRA report is sent when `initializeDirectory()` fails on first app startup, as that's an unexpected condition. ACRA reports are not sent on failed attempts to change the path from Preferences
* A few other code cleanups
=> Open preferences to allow user to change directory if currently invalid

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
There seem to be a bunch of Gingerbread users experiencing problems with ShowcaseView.
```
java.lang.IllegalArgumentException: width and height must be > 0
at android.graphics.Bitmap.nativeCreate(Native Method)
at android.graphics.Bitmap.createBitmap(Bitmap.java:695)
at com.github.amlcurran.showcaseview.ShowcaseView.updateBitmap(ShowcaseView.java:189)
at com.github.amlcurran.showcaseview.ShowcaseView.access$300(ShowcaseView.java:46)
at com.github.amlcurran.showcaseview.ShowcaseView$UpdateOnGlobalLayout.onGlobalLayout(ShowcaseView.java:625)
at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:549)
at android.view.ViewRoot.performTraversals(ViewRoot.java:1266)
at android.view.ViewRoot.handleMessage(ViewRoot.java:1991)
at …
```
=> Catch exceptions with ShowcaseView

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
It seems that occasionally `note!=null` even in add note mode which is causing an NPE here:
```
Caused by: java.lang.NullPointerException
at com.ichi2.anki.NoteEditor.setNote(NoteEditor.java:1512)
at com.ichi2.anki.NoteEditor.onCollectionLoaded(NoteEditor.java:515)
```
=> Try to fix NPE in NoteEditor.setNote

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
```
java.lang.RuntimeException: Unable to resume activity {com.ichi2.anki/com.ichi2.anki.CardBrowser}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=null} to activity {com.ichi2.anki/com.ichi2.anki.CardBrowser}: java.lang.NullPointerException
```
=> Fix NPE in Browser

AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
If dconf is an empty object ({}), confarray.names() will return null, so don't loop in this case.
N.B. Files where dconf={} are loaded successfully by desktop Anki.
=> Fix NullPointerException in Decks.java

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
Currently, if the SD card was unmounted during app startup, the only way to get AnkiDroid working is to force close the app. This fixes that bug by checking if the dir is accessible everytime an AnkiActivity is created. We need to retain the `initializeAnkiDroidDirectory()` call in AnkiDroidApp due to the reason mentioned in #733 
I haven't tested whether the app works properly even with manually mounting and unmounting the sdcard, but it's a simple change that's unlikely to introduce any bugs that didn't exist before.
=> Fix bug where preferences editor shown if SD card was unmounted on app startup

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
This fixes two bugs:
1) Changing the note type from a card with `getOrd()>0` to a note type with only one card was causing a [crash](https://ankidroid.org/couchdb/acralyzer/_design/acralyzer/index.html#/report-details/ankidroid/d4ee961f-c991-4454-acc2-0ec793d817c2). It crashes because the card ceases to exist.
2) Changing the deck of a card from the reviewer via the note editor, in such a way that the current card is no longer supposed to be reviewed, would not force an update of the card in the reviewer.
@hssm do you have time to review this?
=> Always reload newest card of stack after performing an operation in note editor

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
Only do sched.reset() when really necessary after closing note editor, and also reload card list in browser when reloadRequired flag is sent
=> Fix bug in #748 where existing card disappears after editing a note

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java
Always do `resetAndRefreshInterface()` in StudyOptionsFragment unless last activity was cancelled. 
I made the `onActivityResult()` code a bit more readable as well while I was in the process, and also fixed a bug where Activity title was incorrect in Reviewer after using navigation drawer.
=> Make sure the card count is always rebuilt in StudyOptionsFragment

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java, AnkiDroid/src/main/java/com/ichi2/preferences/NumberRangePreference.java, AnkiDroid/src/main/java/com/ichi2/preferences/StepsPreference.java, AnkiDroid/src/main/res/xml/cram_deck_options.xml, AnkiDroid/src/main/res/xml/deck_options.xml, AnkiDroid/src/main/res/xml/preferences.xml
Currently the namespace used to store custom XML attributes is hardcoded to `http://schemas.android.com/apk/res/com.ichi2.anki`, which prevents us from changing the [`applicationId`](http://tools.android.com/tech-docs/new-build-system/applicationid-vs-packagename). This PR fixes that by changing to a new namespace separate from the app name
=> Decouple the namespace for custom XML attributes from app name

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/CramDeckOptions.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java, AnkiDroid/src/main/java/com/ichi2/async/Connection.java, AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java, AnkiDroid/src/main/java/com/ichi2/libanki/Sched.java, AnkiDroid/src/main/java/com/ichi2/widget/WidgetStatus.java
I started out wanting to hide the default deck and realised it wasn't simple with the current way we were doing the deck list. The deck still needs to be shown if it has subdecks, and the existing approach didn't retain any relationship between rows in the deck list. After closely looking at the code I realised a lot of the steps to building the deck list were all over the place. This commit cleans up a lot of that, resolves some issues and enhances UI performance.
There are three main parts to this commit:
1 - The data structure used to build the deck list was rewritten to better match the desktop version. This also makes it easier to build the UI portion in a similar way and lets us resolve [Issue 1550](https://code.google.com/p/ankidroid/issues/detail?id=1550). Our version stores row …
=> Re-work deck list building and interface refreshes

AnkiDroid/src/main/java/com/ichi2/libanki/template/Template.java
I managed to miss this case in my tests. It's not a major problem so there's no hurry to rush a fix out for it.
=> Trim whitespace around template tags

AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/ContentProviderTest.java, AnkiDroid/src/main/AndroidManifest.xml, AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java, AnkiDroid/src/main/java/com/ichi2/anki/provider/FlashCardsContract.java
This is a pull request for a content provider as discussed here:
https://groups.google.com/forum/#!msg/anki-android/SitMpj7J6fw/swqcuJKcld8J
It currently supports getting the unprocessed data from the Anki DB using the following URI:
content://com.ichi2.anki.flashcard/flashcards
and fields and cards/decks using
content://com.ichi2.anki.flashcard/flashcards/<note_id>/data
The contract is described in FlashCardsContract.java. I release this file into the public domain so that it can be used by any third party software without any attribution or royalty. I.e. this file (and this file only) is not licensed under GPL.
The content provider currently only supports notes/cards, but not models.
It also only supports the query() function, no insert() or update() yet.
For update() on fields I …
=> Contentprovider

AnkiDroid/src/main/AndroidManifest.xml, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.java, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java
Removed some redundant fragment/activity arguments and renamed extras and methods to something more descriptive, 
Renamed several mentions of "cram" decks to "filtered" decks including the CramDeckOptions class.
This also fixes a bug I introduced earlier where the deck options didn't open when creating a new filtered deck from the menu on the single-panel version (i.e., when StudyOptionsActivity loads the fragment instead of DeckPicker).
=> Cleaner way to signal opening study options on fragment load

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java
@timrae  A couple of crash fixes.
1 - The crash when closing settings from reviewer. There's a race condition between loading the layout elements and handling onKeyUp. I couldn't figure out what is triggering the onKeyUp, so I just chose to check for null and ignore it. The keypress itself was null so we weren't going to handle it anyway. I found references to this crash in acra on 2.4, so it was actually around before the simple interface change, but it's quite rare.
2 - The crash when closing statistics. There were two places that handle the back button press, and the one that adds the extra wasn't being called. I merged them and it works now. Some auto-formatting of imports happened as well.
=> Fix two reviewer crashes

AnkiDroid/src/main/res/layout/studyoptions.xml
Switching to LinearLayout fixes:  Action bar becomes squashed in landscape mode on study options fragment
=>  Fix: Action bar becomes squashed in landscape mode

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.java, AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.java, AnkiDroid/src/main/res/layout-xlarge/deck_picker.xml, AnkiDroid/src/main/res/layout/navdrawer_divider.xml, AnkiDroid/src/main/res/layout/navdrawer_item.xml, AnkiDroid/src/main/res/layout/navigation_drawer.xml
Change Navdrawer from ListView to Linearlayout for easier theming.
Fix issues with selected deck in DeckDropdownWidget, it's now centrally managed in NavigationDrawerActivity whether the whole collection or a deck is selected.
Include Toolbar in DeckPicker layout for large devices.
Show 'Collapse Subdecks' option in DeckPickerContextMenu only when relevant.
=> Fixes for Navdrawer, Actionbar, DeckPickerContextMenu

AnkiDroid/src/main/res/layout-xlarge/deck_picker.xml
Missed the xlarge/deck_picker layout when migrating to RecyclerView from ListView.
This fix adds a RecyclerView to the tablet layout.
=> Fixed RecyclerView crash on Tablet

ShowcaseView/library/src/main/java/com/github/amlcurran/showcaseview/ShowcaseView.java
Here is a fix for a showcaseview bug. It's our 13th most reported crash with 314 reports. ([link](https://ankidroid.org/couchdb/acralyzer/_design/acralyzer/index.html#/reports-browser/ankidroid/bug/057241882460544c212ccf5523d0f3f3)). I managed to reproduce it on an emulator running Android 2.3 after noticing all but one of the crashes on Acra were on that version.
The bug is in the library itself and there are a few [reports about it on its issue page](https://github.com/amlcurran/ShowcaseView/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+width+and+height). Since the bug was first reported 10 months ago it's probably not going to be fixed any time soon so I don't have any qualms about modifying the library code itself.
The code is from [this StackOverflow …
=> Don't try to update showcaseview element if view not drawn yet

AnkiDroid/src/main/java/com/ichi2/libanki/Sched.java
Fix for [this crash](https://ankidroid.org/couchdb/acralyzer/_design/acralyzer/index.html#/reports-browser/ankidroid/bug/6822f3821f58384b05fa97dc949eb934). This is the 10th most common crash with 408 reports. I haven't reproduced this but I'm almost certain I know what the problem is.
I've fixed a number of these `queryScalar` bugs in the past, so this isn't new to me. For some reason we have a parameter to *choose* whether we want an exception or not if there are no results to the query. I can't imagine a valid use case for this and I don't think we use it anywhere. I'm going to remove the option completely on the dev branch.
Anyway, this crash, for some reason, stems from a widget call every time. The widget was always doing funny stuff and the particular method that leads up to this is …
=> Don't throw exception on query with no results

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDb.java, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/Media.java, AnkiDroid/src/main/java/com/ichi2/libanki/Models.java, AnkiDroid/src/main/java/com/ichi2/libanki/Note.java, AnkiDroid/src/main/java/com/ichi2/libanki/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java, AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java
Every intsance opted to not have an exception thrown. Queries that forgot to opt out and passed in queries that resulted with no rows returned threw an exception instead of returning 0 which is not the expected behaviour.
=> Remove optional exception throw on number-based queries

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
Bug description copied from the doc file:
>Dialog which does importing of apkg doesn’t work properly (probably due to changing the target SDK?). Instead of confirmation dialog appearing when you select an apkg, you get kicked back to the previous dialog.
I don't know exactly why, but calling ```executePendingTransactions()``` just after the  ```transaction.commit() ``` seems to have solved the issue.
I haven't seen any problems in other dialogs because of this method call and I think there will be no problems, ```executePendingTransactions()``` is just (according to [here](http://developer.android.com/guide/components/fragments.html))
> for the UI thread to immediately execute transactions submitted by commit().
=> bug fix: kicked back to import dialog after selecting apkg file.

AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java
Fix for the issue raised earlier about increasing daily limits not refreshing the StudyOptionsFragment anymore. I copied the approach used in TagsDialog for the listener.
=> Refresh studyoptions if daily limits extended

AnkiDroid/src/main/java/com/ichi2/widget/WidgetStatus.java
Not certain when this started happening but AnkiDroid behaves very badly everywhere if you have a widget enabled on the dev branch since it's closing the collection with every update. Removing this fixes the problem.
=> Don't close the collection on every widget update

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
Description of the problem (from [here](https://github.com/ankidroid/Anki-Android/pull/800#issuecomment-90987130)):
> if you recall a search like "deck:default foo" while you have any deck other than the default selected then no cards will appear.
=> Fix: correct search if using search term "deck:".

AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java
NOTE: I wasn't able to test (or even compile) this change because I don't have Android Studio set-up.
When syncing my collection, I'm getting this error:
W/System.err(17831): java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
W/System.err(17831): 	at com.ichi2.libanki.sync.Syncer.mergeNotes(Syncer.java:881)
W/System.err(17831): 	at com.ichi2.libanki.sync.Syncer.applyChunk(Syncer.java:566)
W/System.err(17831): 	at com.ichi2.libanki.sync.Syncer.sync(Syncer.java:182)
[...]
So sometimes the note ID is an Integer rather than a Long.
Using Long.valueOf(((Number) foo).longValue()) will work for both Longs
and Integers.
=> Handle case where note ID is Integer, not Long

AnkiDroid/src/main/java/com/ichi2/compat/CompatV12.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV8.java
It seems [some devices crash when trying to enable cookies](https://code.google.com/p/ankidroid/issues/detail?id=2510). A fix has been pushed into 2.4.3 a while ago, this adds it to 2.5
=> Catch runtime exceptions when trying to enable cookies

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
Cherry-picked from develop branch
Crash when item pressed inbetween clearing cards and DeckTask finishing
Bug where search always cancelled prematurely under some situations
Too many cards getting rendered in background thread
=> Fix 3 browser bugs

AnkiDroid/build.gradle
We should always keep up-to-date the Material Dialogs.
=> Updated MaterialDialogs version to 0.7.1.3

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
I was getting a crash on this line when I clicked on the "Cards"
section of the "Edit Note" dialog. After this change, it no longer
crashes.
N.B. I'm using the new (2.5) UI.
=> Only call hide progressBar if it isn't null

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
- treat data: URL like file URL
- don't rely on the java URL parser to check for malformed URLs
- catch ActivityNotFoundException exceptions, rather than crashing
Signed-off-by: Peter Ross <pross@xvid.org>
=> Support Custom URLs

AnkiDroid/build.gradle
Update Material Dialogs again. Older build is no longer available and breaks our build.
=> Update Material Dialogs to 0.7.3.1

AnkiDroid/src/main/java/com/ichi2/libanki/hooks/HebrewFixFilter.java
A fix for an issue brought up in [Issue 1734](https://code.google.com/p/ankidroid/issues/detail?id=1734) where the Hebrew Fix filter was modifying text even when it's in a media reference, breaking media playback by altering the file name.
This commit records the media regions and skips an impending change if it falls within those regions.
=> Skip regions containing media in hebrewfix filter

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/libanki/Card.java
Hey guys,
I needed a way to get the pure answer of a card and saw that getPureAnswerForReading was already supposed to do pretty much that.
But on some decks it didn't work for me, and I found out that these decks did not put the two new lines after &lt;hr id=answer>.
Also @hssm [pointed out](https://github.com/ankidroid/Anki-Android/pull/823#discussion_r30011834) that the name should be changed to make it more universal.
=> Name change and bugfix of getPureAnswerForReading

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java, AnkiDroid/src/main/java/com/ichi2/ui/SeekBarPreference.java, AnkiDroid/src/main/java/com/ichi2/ui/SlidingTabLayout.java, AnkiDroid/src/main/java/com/ichi2/ui/SlidingTabStrip.java, AnkiDroid/src/main/res/layout/activity_anki_stats.xml, AnkiDroid/src/main/res/layout/card_template_editor_activity.xml, AnkiDroid/src/main/res/xml/preferences.xml
Moved ..
com.example.android.common.view
com.hlidskia.android.preference
..to..
com.ichi2.ui
as I couldn't find a reason they should be in rogue packages. Perhaps we should start to migrate packages/classes to 'com.ichi2.anki' ?
=> Refactored 2 packages

AnkiDroid/src/main/java/com/ichi2/libanki/hooks/HebrewFixFilter.java
https://github.com/ankidroid/Anki-Android/pull/826 actually broke the build, but for some convenient reason there wasn't a travis build to catch it.
The `develop` branch is using a newer version of the Java language than our hotfix branch so we have to be careful when backporting commits from it, or this happens.
=> Fix newer Java language feature from develop breaking the build

AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java
Import card count was always 0. I broke this with the deck counts update where I thought the extra parameters weren't needed.
=> Fix not passing correct import card count

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
Background: In the past I had added a decrement of the rep count in the scheduler at the start of every review session in order to result in an accurate number for the timebox feature. The reason being that AnkiDroid is always 1 rep ahead because of the way it loads the next card. That is, they are loaded when a card is answered and the very first answer is a fake card just to get the process going, but the rep is still counted.
I realised today that this interferes with the decision of when to show a new or review card. It's incredibly minor and has no appreciable impact on reviewing behaviour and it only applies to the "mix new cards and reviews" setting. In practice, it means it will (for example) show a new card every 3 reps starting from review 4 instead of every 3 reps starting from …
=> Decrement timebox label count instead of scheduler rep count

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
Cards with queue type 3 (learn cards that fall into the next day) were not getting underlined in the remaining card count indicator thing.
=> Fix cards with queue type 3 not being underlined

AnkiDroid/src/main/res/values/11-arrays.xml, AnkiDroid/src/main/res/values/constants.xml
[Issue 2622](https://code.google.com/p/ankidroid/issues/detail?id=2622)
The *relative overdueness* ordering for filtered decks is already implemented but we never exposed it to the user in the selection list. I've added that here.
=> Expose "relative overdueness" ordering for filtered decks

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
My intention in removing the preference ([issue 1537](https://code.google.com/p/ankidroid/issues/detail?id=1537)) was always to have the fade enabled for API 8+ but it seems I may have done the exact opposite
@hssm
ok to merge?
=> Make scrollbars fade

AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/ContentProviderTest.java, AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java, AnkiDroid/src/main/java/com/ichi2/anki/provider/FlashCardsContract.java
In order to allow reviews from other apps and devices (especially Android Wear Smartwatches) I extended the CardContentProvider and FlashCardsContract with methods and classes that allow external apps to:
-request a list containing the name and id of the users decks
-request the next scheduled card
-request which deck is selected right now
-update the ease of a card (answer the card)
-update the selected deck (choose a deck)
=> Scheduler and Deck info through ContentProvider

AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java, AnkiDroid/src/main/java/com/ichi2/anki/provider/FlashCardsContract.java, AnkiDroid/src/main/java/com/ichi2/libanki/Card.java
Hey guys,
a user of my app noted, that with the current implementation the statistics get falsified because of the missing "time taken" information.
I figured the easiest fix is pass the timeTaken to the ContentProvider. The ContentProvider then manually sets the "mTimerStarted" variable (to now()-timetaken) before answering the card.
=> Added "time taken" to pass on to the ContentProvider when answering a card

AnkiDroid/src/main/res/values/16-multimedia-editor.xml
A while ago i made some string translatable: 3797ce725.
It looks like for two i accidentally copy-and-pasted an extra quotation mark.
This fixes that error.
These two texts are used only by screen readers (somewhat like the original idea for HTML’s alt attribute for images).
=> Fix error added when two strings were made translatable

AnkiDroid/build.gradle, AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java, AnkiDroid/src/main/java/com/ichi2/themes/StyledProgressDialog.java, AnkiDroid/src/main/res/layout/my_account.xml, AnkiDroid/src/main/res/layout/my_account_logged_in.xml, AnkiDroid/src/main/res/layout/my_account_register.xml
The new Android design support library gives a MaterialDesign snackbar builder which are like toasts but can have an action and can be swiped off screen. We should make good use of these in removing the old StyledDialogs
=> Replace StyledDialogs with Snackbars in MyAccount

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
One annoyance that I only realized after implementing the `addToCur` code (a loooong time ago, sorry) is that the deck that was selected using the deck selector is reset to the current deck after a new card is added. This change pulls out the part in `setNote` that sets `mCurrentDid` so that later calls to `setNote` (e.g. after adding a note or changing the note type) will not overwrite the deck that was previously set. This is useful for adding many cards to the same deck (or less frustrating, rather), and also implemented like that in Anki Desktop.
I'd appreciate a thorough look at this. It has been a while to work with the AnkiDroid codebase and I'm not sure if I have considered all possible side-effects. I did remove `mEditorNote.model().put("did", mCurrentDid);` because this is what …
=> Preserve deck selection by not setting did in setNote

AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java
Workaround for [issue 2594](https://code.google.com/p/ankidroid/issues/detail?id=2594). It seems that a small minority of devices (so far just one) have non-null thumbnails for audio files. This applies an extra check to make sure that the extension is correct as well. The check won't work with .mp4 and .3gp audio files, but it will at least work with .mp3 etc.
I haven't tested it yet; if someone could test it that would be great.
=> Only play videos if supported extension

AnkiDroid/src/main/res/layout/flashcard.xml
This removes the white (black in night mode) border around the flashcard. I guess it was just a remnant from the pre-material design layout.
(What border? I see no border. You only see it when you set the background to something other than white.
See between the blue bar and the beige card background. The card background is also not as wide as the blue bar, with this margin on the left and right.)
With this change the border is gone:
Similarly, this reduces the size of the white (in day *and* night mode) border around the buttons at the bottom:
before:
after:
I think the border around the buttons should either be removed completely or switched to black for night mode. a) I don’t know which one and b) that is a bit more work than this PR.
=> Remove margin around flashcard content

AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/ContentProviderTest.java, AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java
When inserting a note via content provider, all field values are set to “temp”. It's possible to later set the fields to an empty value through the update method. But it is a problem if the fields triggers the creation of a conditional card like the “Add Reversed” in the “basic (optional reversed card)” note type.
The default value “temp” was introduced, because some fields are required to have a non-empty value. According to @timrae in #725 this probably applies only to the first field of a note.
=> Default value for first field when inserting notes through ContentProvider

AnkiDroid/src/main/res/values/01-core.xml, AnkiDroid/src/main/res/values/02-strings.xml, AnkiDroid/src/main/res/values/03-dialogs.xml, AnkiDroid/src/main/res/values/04-network.xml, AnkiDroid/src/main/res/values/05-feedback.xml, AnkiDroid/src/main/res/values/06-statistics.xml, AnkiDroid/src/main/res/values/07-cardbrowser.xml, AnkiDroid/src/main/res/values/09-backup.xml, AnkiDroid/src/main/res/values/10-preferences.xml, AnkiDroid/src/main/res/values/11-arrays.xml, AnkiDroid/src/main/res/values/styles.xml, AnkiDroid/src/main/res/values/themes.xml
Clean up of screen texts.
Mostly replacing " and ' when used as quotation marks with “, ”, and ' with ’ when used as apostrophes.
From the [style guide](https://www.google.com/design/spec/style/writing.html#writing-capitalization-punctuation):
> Never use the generic quotes ", ' (…). These are never right for quotation marks, apostrophes, or primes.
There was also a mix of double quotes \"like this\" and single quotes \'like this\'. Use only double quotes.
Also use a few more contractions, (… not → …n’t), by the [style guide](https://www.google.com/design/spec/style/writing.html#writing-capitalization-punctuation) again.
Replace a few !s. I dare you to exclaim “Non-developers can also help, for instance by translating AnkiDroid, updating the wiki and screenshots, donating to Anki Desktop, …
=> Clean up quotes ("…" → “…”), apostropes (x's → x’s ) and more

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
Look like you can stop the reviewer before `mSched` is set up. Don’t try to access it then.
Should fix [issue #2661](https://code.google.com/p/ankidroid/issues/detail?id=2661).
=> Fix for 2661.

AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java, AnkiDroid/src/main/res/layout-xlarge/studyoptions_fragment.xml, AnkiDroid/src/main/res/layout/studyoptions_fragment.xml
Fix for [Issue 2201](https://code.google.com/p/ankidroid/issues/detail?id=2201). We were not showing an unbury button for filtered decks, even though the completion text was saying there was such a button to click on.
=> Expose unbury button for filtered decks

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/res/layout/flashcard.xml
Fix for [issue 2640](https://code.google.com/p/ankidroid/issues/detail?id=2640).
The new Material Design-like answer buttons have a fixed layout height, so change the layout parameters instead of the size of the elements inside.
=> Set the answer button height for the new style buttons

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/compat/Compat.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV12.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV8.java
The ShowcaseView text was very hard to read on Android 2.x due to not setting the alpha of the DeckPicker Views. I found a workaround and put it in the Compat class
=> Dim the DeckPicker behind ShowcaseView properly pre-Honeycomb

AnkiDroid/src/main/AndroidManifest.xml, AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/java/com/ichi2/compat/Compat.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV11.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV12.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV8.java
Instead of booting back to the deck picker every time night mode is toggled, stay on the same activity and try to recreate the backstack.
Only works on Android 3.0+ and the backstack is recreated from the hierarchy so for example if the user does the following:
Start from deck picker -> tap on default deck -> press study button -> open browser via navigation menu -> toggle night mode -> press hardware back button
They will be taken back to the deck picker instead of the reviewer. I can't see any simple way to avoid this unfortunately.
=> Recreate the backstack when night mode is toggled

AnkiDroid/src/main/java/com/ichi2/libanki/Media.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/FullSyncer.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/HttpSyncer.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/MediaSyncer.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/RemoteMediaServer.java
This commit cleans up some of the media syncing code and addresses a couple of the TODOs left in there.
1 - The temporary files (`tmpSyncToServer.zip` and `tmpSyncFromServer.zip`) are now properly deleted when we are done with them. They weren't really causing any problems but they clutter up the AnkiDroid directory and in general it's better to clean up after ourselves.
2- Better try/finally usage for stream management. As an extension to this, I've also updated comments to be more explicit about how streams are being used .
3 - Better exception handling. Don't catch-all or swallow exceptions.
4 - Removed some duplicate logging lines.
Extra:
I've removed the comment about investigating in-memory zip performance since I've effectively done just that in …
=> Purge temporary media sync files and improve stream management

.idea/encodings.xml
In at least two files, [one](https://github.com/ankidroid/Anki-Android/blob/develop/AnkiDroid/src/main/java/com/ichi2/anki/Lookup.java#L109) still [sort-of](https://code.google.com/p/ankidroid/issues/detail?id=2676) in use, it is not just in comments.
@timrae: Could you please check if this is a help for Android Studio on Windows by looking if the mojibake at [this](https://github.com/ankidroid/Anki-Android/blob/develop/AnkiDroid/src/main/java/com/ichi2/anki/Lookup.java#L109) or [this](https://github.com/ankidroid/Anki-Android/blob/develop/AnkiDroid/src/main/java/com/ichi2/anki/provider/FlashCardsContract.java#L535) line goes away?
=> Use UTF-8 as project encoding

AnkiDroid/build.gradle, AnkiDroid/src/main/res/layout/floating_add_button.xml, AnkiDroid/src/main/res/values/colors.xml
...as [suggested on the forum](https://groups.google.com/forum/#!topic/anki-android/LKtLiC0OMos). 
I also updated the design support library version which seems to have fixed the white text on grey background issue when using a hardware menu button
=> Change color of floating add button to blue

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/res/values/10-preferences.xml, AnkiDroid/src/main/res/xml/preferences_general.xml
See [issue 1062](https://code.google.com/p/ankidroid/issues/detail?id=1062)
Trying to sync at `onResume()` or `onPause()` didn't work. While the synchronization is taking place I get an error "Collection not opened", "An error occurred while accessing your collection", so this is just for when the user presses back button on `DeckPicker` interface.
Originally I recorded last sync time and the auto-sync would only occur if the last sync is more than 10 minutes ago. However I later removed it. 1. This is consistent with the behavior on desktop version 2. I don't think the user would exit the app that often 3. So as to not confuse the user with complexity. If that functionality is deemed necessary I will add it back.
I'm not that proficient in Android development so excuse me if I wrote some …
=> Added auto sync on start/exit

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/SearchImageActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/web/HttpFetcher.java
The timeout of HttpURLConnection and Apache HttpClient is 0, which means the request would never return if either connection or read timeouts.
This patch set explicit timeout value (5s for connection timeout and 10s for read timeout), so the code would catch and handle timeout exceptions as you would expect.
=> Add timeout for Http requests

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/UIUtils.java, AnkiDroid/src/main/java/com/ichi2/compat/Compat.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV19.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV8.java
Fixes #2916.
KitKat introduced [Immersive Mode](https://developer.android.com/training/system-ui/immersive.html) for better full screen support. This commit makes use of the Sticky Immersive mode on devices that support it when the full screen reviewing option is enabled.
It looks quite nice with the recent slimming down of the interface.
=> Use Sticky Immersive mode for fullscreen reviewer on KitKat+

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
We weren't correctly printing out the contents of `long` arrays to our log file (specifically, the `buryCards` and `forgetCards` methods).
=> Fix logging long[]

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/res/values/03-dialogs.xml
Fixes #2808.
- Provide an appropriate warning when attempting to delete the default
deck instead of doing nothing.
- Don't show a warning when deleting an empty deck. The user might think
we are showing a warning because they are about to lose data, which is
not the case.
- Show the number of cards about to be deleted since we are already
calculating it. It's useful, and the desktop client shows it as well.
=> Improve deck deletion messages

AnkiDroid/src/main/java/com/ichi2/async/Connection.java
Our existing check for online status is making use of [isConnectedOrConnecting](http://developer.android.com/reference/android/net/NetworkInfo.html#isConnectedOrConnecting%28%29). The documentation states:
>This is good for applications that need to do anything related to the network other than read or write data. For the latter, call isConnected() instead, which guarantees that the network is fully usable.
Since reading and writing data sounds a lot like what we are doing, I've taken their advice and used `isConnected()` instead (and a couple other useful checks).
This *may* reduce syncing errors that occur from sync attempts that begin because the network was connecting and never made it all the way.
=> Improve check for online status

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
Fixes #2458.
Add a period of time to ignore button presses for the "show answer" and ease buttons in the reviewer.
200 milliseconds seemed like a good start. We can tweak it if needed, but it's hard to intentionally get this low without spamming your fingers (or your name starts with X and you review 10 cards in that amount of time harr harr).
=> Add delay to prevent accidental double-tap

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
@timrae
Our Snackbar colour problem is exactly the same as [this SO thread](http://stackoverflow.com/questions/31061474/how-to-set-support-library-snackbar-text-color-to-something-other-than-androidt).
I copied the accepted answer. Is the hardcoded colour too lazy? Should I make a new attribute for it?
=> Apply text colour to Snackbars

AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java, AnkiDroid/src/main/res/drawable/shadow_left.xml, AnkiDroid/src/main/res/layout-xlarge/studyoptions_fragment.xml, AnkiDroid/src/main/res/layout/studyoptions_fragment.xml
Fixes #3553. I've toned down the gradient a bit since the screenshots that appear on the issue.
I had to make some changes to the layout to make the gradient work, and little by little I found myself fixing up everything else I found wrong with it. I've mostly removed redundant layouts and fixed up most of the warnings. Some were performance suggestions but I doubt they're the noticable kind. Only some RTL warnings remain.
The xlarge and normal layout are almost identical now except for the gradient and the graph. I think in the future we can factor out our layouts and [`<include>`](http://developer.android.com/training/improving-layouts/reusing-layouts.html) them, but that's for another time.
And yes I tested the rotation and overflow on tiny screens to make sure they still work.
=> Add gradient and remove redundancies from studyoptions layouts

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.java, AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java, AnkiDroid/src/main/java/com/ichi2/anki/UIUtils.java, AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java, AnkiDroid/src/main/res/values/01-core.xml
Fixes #3598.
1 - DeckTasks are queued up and executed in sequence.
2 - When a sync is finished, the collection is closed and reopened (I don't remember why we do this). 
If DeckTasks are queued up *before* a sync finishes and run *after* the sync finishes, they will be using stale references to the Collection since we pass in a Collection object for them to use. This commit changes all DeckTasks to use the CollectionHelper to get a current reference to the collection.
I did a bit of a cleanup of DeckTask while fixing this issue. I've removed any dead code, unused methods, and redundant parameters/TaskData things.
=> DeckTask cleanup

AnkiDroid/src/main/java/com/ichi2/anki/Info.java, AnkiDroid/src/main/res/values/03-dialogs.xml, AnkiDroid/src/main/res/values/constants.xml
- Make the About dialog use theme colours so it looks good in the dark
theme.
- Updated links to point to their new GitHub locations.
- Improved the text in the About dialog and removed a redundant link.
---
Also, there was a link to a font that was hosted on Google Code which isn't available any more. I uploaded it as a release on GitHub and changed the link to that.
=> Add theming to About dialog and update links

AnkiDroid/src/main/res/layout-xlarge/deck_picker.xml
Use “android:fitsSystemWindows="true"” for the xlarge deck picker as well so we get white on blue instead of white on white symbols/text in the status bar.
This has bugged my since i got myself a 20cm tablet and put Android 5 on it.
The status bar was white-on-white on the deck picker (+ study options) screen.
Before:
How late is it? How much battery have i left? No idea. That gray smudge to the top left of the “sync” button is the “data in” marker in the wlan symbol. 
Looks like the fix is to simply set ` android:fitsSystemWindows="true"`, [as it is done](https://github.com/ospalh/Anki-Android/blob/develop/AnkiDroid/src/main/res/layout/deck_picker.xml#L7) in the non-`xlarge` version of `deck_picker.xml`.
After:
This is a fix for #3552.
=> Fix white-on-white status bar.

AnkiDroid/src/main/AndroidManifest.xml, AnkiDroid/src/main/java/com/ichi2/async/Connection.java
A likely fix for #3574.
With this commit, we acquire and release a wake lock before and after syncing to ensure the device remains awake during sync so that the sync isn't interrupted.
I'm surprised we weren't doing this already. I suppose syncing doesn't really take that long, and for most users it completes before the device is put into sleep mode (which, as I understand, can vary between devices and user settings), so it isn't a common occurrence.
=> Use a wake lock during syncing

AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java
Fix for the problem reported [here](https://github.com/ankidroid/Anki-Android/issues/3326#issuecomment-125635018)
@timrae this fixes the problem for me. Performance might suffer though for notes with huge amounts cards, since we'd now have to compare all cards of a note to find the one with the right ord.
=> ContentProvider: Fix for wrong "IllegalArgumentException"

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/services/NotificationService.java, AnkiDroid/src/main/java/com/ichi2/libanki/Sched.java
* Get rid of deprecated `notification.setLatestEventInfo()` for Android M compatibility
* Fix calculation of total cards due for notification and widget (closes #3500)
* Put the cards due in the title (closes #3594)
=> Fix the notification and widget counts

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
Also ignore attempts to rename deck to the same name. This saves us
from showing an error when there really wasn't anything wrong.
=> Dismiss context menu after deck rename

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java, AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
#3648 wasn't working due to some broken logic in cancelling DeckTasks. Specifically we were setting `sLatestInstance` too early when a new DeckTask was started. This new code seems to be working well so far, but we'll need to test it thoroughly out in the wild.
=> Fix broken DeckTask cancel logic

AnkiDroid/src/main/java/com/ichi2/anki/AnkiFont.java, AnkiDroid/src/main/java/com/ichi2/anki/reviewer/CustomFontsReviewerExt.java
We were using !important in the actual CSS font definitions which is wrong. E.g. `@font-face {font-family: "kochi-mincho-subst" !important; font-weight: normal !important; font-style: normal !important; src: url("file:///sdcard/AnkiDroid/fonts/kochi-mincho-subst.ttf");}`.
`!important` should only go in the class:
`BODY, .card, * { font-family: "kochi-mincho-subst" !important; font-weight: normal !important; font-style: normal !important; }`
Older versions of Android/Webview may have supported this, but the latest version of Chrome Desktop / Webview does not. This probably closes #3581
=> Fix broken font override behavior

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/libanki/Card.java, AnkiDroid/src/main/java/com/ichi2/libanki/Sched.java, AnkiDroid/src/main/res/values/attrs.xml, AnkiDroid/src/main/res/values/colors.xml, AnkiDroid/src/main/res/values/theme_dark.xml, AnkiDroid/src/main/res/values/theme_white.xml
The timer displayed during review will now stop counting up when it
reaches the maximal answer time and will be highlighted red to indicate
that it has reached its limit (the desktop client does both).
This commit also changes the technique used to account for a card's true
review time after a pause and resume of the reviewer. The new technique
shifts back the *current* time by the elapsed interval instead of trying
to shift the original start time by the elapsed time.This prevents clock
changes from impacting the elapsed time.
This resolves the long-standing negative review time bug for which
there was a workaround in place, and thus removed in this commit.
--
Edit: I've updated the commit to make the paragraph below invalid.
The review time stored internally was wildly inaccurate when …
=> Fix review time counting and max timer display

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java, AnkiDroid/src/main/res/layout/deck_picker.xml, AnkiDroid/src/main/res/values/01-core.xml
Highlight selected deck properly on tablet (closes #3666)
Don't show "congratulations" message or graph when deck is empty
Offer the user some help if they click on an empty deck
Fix issue where FAB wasn't rising above SnackBar
=> Fix some issues with deck picker and study options

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.java, AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.java, AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java, AnkiDroid/src/main/res/layout/studyoptions_fragment.xml, AnkiDroid/src/main/res/layout/styled_custom_study_details_dialog.xml, AnkiDroid/src/main/res/menu/deck_picker.xml, AnkiDroid/src/main/res/menu/reviewer.xml, AnkiDroid/src/main/res/values/01-core.xml, AnkiDroid/src/main/res/values/02-strings.xml, AnkiDroid/src/main/res/values/11-arrays.xml
The idea behind this PR is to avoid showing the ugly and confusing "study options" screen whenever possible by skipping directly to the reviewer for ordinary non-filtered decks, and using SnackBars to give hints to the user on how to do custom study when the scheduler isn't putting out any new cards.
Custom study can now be accessed via the long tap context menu in the deck picker, and unbury can be accessed from the main overflow menu in the deck picker. The old "study options" screen can also be accessed from the reviewer to aid those that don't know about the long click menu.
In the case of tablet layout and filtered decks, the study options screen is continued to be used as before.
There are still a few minor TODOs for this, for example:
* Long clicking on a filtered deck will give …
=> Bypass StudyOptions screen when possible using hint SnackBars

AnkiDroid/build.gradle, AnkiDroid/src/main/res/values-v14/styles.xml
@ospalh I'm not sure when or why but it looks like the style that set the Acra dialog was deleted somewhere in the v2.5 branch.
=> Update Acra version and fix #3570

AnkiDroid/src/main/res/values/02-strings.xml, AnkiDroid/src/main/res/values/17-model-manager.xml
Tweak two other strings. These would not need re-translating. (This separation is according to a request with respect to PR #3583.)
* Fix reference to “Unbury”. No longer a button.
* Use an n-dash for number range (“1–12” instead of “1 - 12”)
=> Tweak to two strings. (No re-translation.)

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java, AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.java, AnkiDroid/src/main/java/com/ichi2/anki/stats/InfoStatsBuilder.java, AnkiDroid/src/main/java/com/ichi2/libanki/Stats.java
Also remember the last selected deck in the browser until a new deck is selected (#3319)
and show the number of cards found in a search via a snackbar when the SearchView is expanded (#3592)
=> Fix browser spinner always set to "all decks"

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
When i added the “`autocomplete=\"off\" `” for #3730, i changed too much too quickly.
I didn’t test the old style enough, and got the logic wrong.
With this the type prompt is again shown when typing is on and not shown when off.
=> Fix a typo. Hide the type prompt when typing is off, show when on

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
With night mode enabled the screen flickers white for a little bit when the reviewer is first opened. Setting the webview to be transparent appears to make that flicker be grey until the card background itself is loaded, which is less stressful on the eyes. You can get rid of the flicker entirely by [setting the background color of your cards in night mode to `#303030`](https://github.com/ankidroid/Anki-Android/wiki/FAQ#how-to-customize-the-colors-used-with-night-mode)
=> Get rid of flicker with night-mode enabled

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.java
- Update the widget after sync (in case sync finishes in background)
- Launch the correct activity when the widget is clicked. Make it
behave like our normal launcher icon.
=> Minor widget enhancements

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/res/values/01-core.xml
Replaced literal string with resource. This dialog is a bit tricky, because the positive dialog action would be "Cancel", which normally cancels the dialog. Therefore I used "OK" and "Continue sync" to avoid any ambiguity.
Fixes #3761.
=> Update "cancel sync" dialog strings.

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/VideoPlayer.java, AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java
There was a bug posted on the forum about the wrong sounds being played if you go Reviewer -> Previewer -> Back to Reviewer and replay the audio on the card. The problem is due to the Sound class having everything inside it as static and the state being overridden when you open the Previewer.
I've made it so the class can be used through instances which fixes the problem. I couldn't find a good reason for it to be all static anyway. @timrae the class has your name on it so maybe you remember. Give it a quick look to make sure it's not breaking anything.
While testing this with video I found out that video sounds continue to play even after you go back. There's a small fix in this commit for that as well.
=> Use instances of Sound class instead of statics

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.java, AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java, AnkiDroid/src/main/res/values/06-statistics.xml, AnkiDroid/src/main/res/xml/deck_options.xml, AnkiDroid/src/main/res/xml/preferences_advanced.xml
Necessary because creating a custom session uses the current did, not the context menu did. Also refresh the deck list then, so that:
* clicking a deck which no cards to study moves the focus bar (it was already made current).
* the focus bar doesn't jump when going back to the deck picker after changing decks.
=> Pass deck id to custom study context menu.

AnkiDroid/build.gradle, AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/NoteEditorRescheduleCard.java
These changes allow the rendering of browser items to occur while the user is scrolling instead of having to stop scrolling completely to wait for the rendering to begin.
I also fixed a couple of minor bugs
=> Allow some rendering of browser items while scrolling

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
Crash from acra.
My earlier change to update the fragment after sync on tablets made it crash if you close the Activity and let the sync finish in the background. Here's a fix for that.
=> Fix post-sync crash on tablet

AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
Fixes #3801. I tested it alongside the desktop client and both produced the same values.
@eginhard Do you think I'm missing something with this?
=> Fix start of next day setting breaking creation time

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDb.java, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/java/com/ichi2/compat/Compat.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV10.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV11.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV16.java, AnkiDroid/src/main/res/values/10-preferences.xml, AnkiDroid/src/main/res/xml/preferences_advanced.xml
I noticed in the logcat from the crash in #3794 that AnkiDroid was having trouble changing from WAL mode to ROLLBACK. Presumably the wal file became corrupted or too big or something. This prompted me to check if there was any performance difference when reviewing on my device, and I didn't find any.
So I propose disabling WAL by default and adding a setting to re-enable it if people are actually finding AnkiDroid slower without it. If nobody finds any significant difference then we could remove the setting before releasing.
I'd like to hear opinions on this change
=> Disable WAL by default

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
Unlike in the StudyOptionsFragment, the DeckPicker never lets you open a deck that doesn't have cards to be reviewed, so it's inappropriate to show the "no cards due yet" message.
This was causing #3799 and #3762
=> Don't show "no cards due yet" message in deck picker

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java, AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/res/xml/preferences_advanced.xml, AnkiDroid/src/main/res/xml/preferences_general.xml
A user recently got confused, thinking this was the path where they need to put apkg files to import. This preference really belongs in advanced, as normal users shouldn't be touching it.
I also disabled sending exception reports when the dir fails to initialize for custom paths
=> Move collection path to advanced preferences

AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java
Should avoid all crashes like [this](https://ankidroid.org/couchdb/acralyzer/_design/acralyzer/index.html#/reports-browser/ankidroid/bug/1e2b0b3d76de349d94d493e5b40b559a)
=> Abort all DeckTasks if Col can't be opened to avoid NPE

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
There was no case to handle an undo of a *Bury card* action. It resulted in [this crash](https://ankidroid.org/couchdb/acralyzer/_design/acralyzer/index.html#/report-details/ankidroid/5e9ff583-674a-42d4-b1b1-d10aa475258a) which alerted me to it.
=> Fix undo bury card having no effect

AnkiDroid/src/main/assets/flashcard.css
@ospalh Someone on the forum complained about the tiny input box so I'm making it bigger. I agree that it's too small as well. I don't use typing fields myself so I'm basing this on the default sizes when you add a typing field on the desktop.
On the desktop, the size of the input box in the *reviewer* is determined by the `Editing Font` field setting, which seems counter-intuitive but that's how it is. I think by default it's 20px which is also the font size in the default template.
Anyway, we don't use this value in AnkiDroid at the moment so I'm just making it arbitrarily bigger by 50%. It's a little larger but still smaller than what I get on the desktop.
=> Increase height of input box in reviewer

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java
Fix #3762 by opening the study options screen whenever the learn ahead limit is preventing cards from getting shown in the deck picker.
=> Make learn ahead limit behavior more consistent with Anki Desktop

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
Fixes a bug where the count which would be shown in the study options was being loaded from the previously selected deck
=> Reset the schedule on deck selection in deck picker

AnkiDroid/build.gradle
v23.1.1 includes quite a few bug fixes (including the one that was causing #3739) so I think it's worth updating. Hopefully there aren't any regressions, or if there are then we can pick them up pretty quickly with the beta testing.
=> Update support library versions to 23.1.1

AnkiDroid/build.gradle, AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/NoteEditorRescheduleCard.java, AnkiDroid/src/main/java/com/ichi2/compat/Compat.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV10.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV11.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV19.java
I finally got something working after the discussion in #3850
It was a real pain to figure it out... You have to add an extra padding to the toolbar when fullscreen is enabled. It took me hours to figure this out. The behavior appears to be a "feature" rather than a bug in the MaterialDrawer library. We should probably just switch back to the design support library at some point.
=> Hide action bar together with system status bar in fullscreen mode

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDb.java, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/java/com/ichi2/compat/Compat.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV10.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV11.java, AnkiDroid/src/main/res/values/10-preferences.xml, AnkiDroid/src/main/res/xml/preferences_advanced.xml
@hssm 
There's no evidence of any issues obviously caused by changing the rollback mode in the crash logs, and I haven't noticed any performance degradation (nor has anyone complained of one), so I propose that we go ahead and just gut the WAL stuff if there are no objections. 
I'm pretty confident that it won't cause any issues, and going back over the git logs it seemed that it was just introduced because it "might" improve performance. I haven't seen any benchmarks (or even anecdotal evidence) to justify having it, and IMO it just adds one extra level of complexity that we don't need (i.e. in switching it on and off every time we open the DB) .
I'll wait for a review on this change and the other PR, and maybe we can call the next beta RC1
=> Completely remove WAL

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java, AnkiDroid/src/main/java/com/ichi2/libanki/Tags.java
This PR is mainly looking to fix https://github.com/ankidroid/Anki-Android/issues/3791.
Some issues I discovered along the way:
1. Tags seem to be quite weird. I have a deck that has tags separated with space. I'm not sure how anki wants to differentiate through tags(I'm guessing anki uses spaces and the author wanted to use tags containing spaces). They do get saved properly in the database, but I am unable to create a deck from them. If anki does not allow spaces in tags I guess it's just a limitation that the author wasn't aware of, if not, this might be a bug.
2. I'm trying to use `activity.getCol().getDecks().selected();` to get the current deck id, but it doesn't seem to work properly. I need to start reviews in a deck for it to be considered selected. 
For example:
- Make reviews …
=> Limit tags in custom study dialog to those in the selected deck

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
We were using two caller codes for the same thing, and only one of them had the logic we needed for properly handling a card add when it comes from an intent. I've merged them into one.
=> Fix note editor not closing on save when coming from intent

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
A user on the forum complained about visible progress bars in the middle of the card when answering. I noticed it as well, so I'm removing them in this commit. I think card answering is fast enough that this isn't warranted.
=> Don't show progress bar on card answer

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/res/values/10-preferences.xml, AnkiDroid/src/main/res/xml/preferences_advanced.xml
For those that griped (#3912) about the input tag or otherwise don’t like it.
The switch is a “workaround”, and that prefs category is always shown with this.
(I decided against using the old input field automatically when the white board is on. I for one am OK with an input tag that i can’t get to because of the white board. I may use the box on desktop Anki, but am happy to write with the finger in AnkiDroid.)
(edit: i missed the “against” at first.)
=> A switch to turn off the input tag write answer

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.java, AnkiDroid/src/main/res/layout/deck_item.xml
With this change, clicking on the counts section of the deck picker goes to the deck overview page instead of directly to the Reviewer, as per #3920
=> Make deck picker counts clickable

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
I've noticed there are times when a blank activity is shown with really big collections
=> Show progress bars when loading count tree in deck picker

AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.java
With the intent handler activity set to transparent we can actually make the opening animation look consistent with every other app in the launcher now.
=> Use up animation to open deck picker

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
@hssm I could reproduce the issue you mentioned on a physical device, and it's pretty annoying so I went ahead and fixed it
=> Don't show the progress bar when DeckPicker is resumed

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.java
As suggested on the forum, this makes the behavior of filtered decks vs ordinary decks more consistent when clicked.
=> Make filtered and ordinary deck click behavior consistent

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java
A user recently complained that with the new tap zone in the deck picker, the number of taps to get back to the deck picker depends on where they launched the reviewer from, which confuses the brain.
=> Always go back to deck picker upon finishing reviewing

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicTextFieldController.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/TextField.java
Behaviour is now the following:
* Text from text fields is always passed in (not only when editing notes).
* For text fields, the previous text is completely replaced.
* For fields with focus, media are inserted at the cursor position.
* For fields without focus, media are inserted at the end.
* Removed the " - " that was inserted when changing to a text field.
Fixes #3669
=> Insert media at cursor position in note editor.

AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
As per the discussion in #3969, Anki Desktop doesn't allow the undoing of note edits, so here I've unexposed this functionality to bring AnkiDroid in line with Anki Desktop. I've kept it there as we might want to allow undo of edits from the browser, although Anki Desktop doesn't do that either.
As in #3969, I've completely removed the undo mark note functionality as I can't see any valid usage case for that.
=> Don't add edits to undo queue

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
There was some left over stuff still for undoing edits which I removed in the first commit.
The second commit removes the DeckTask for card marking and just does it directly. All the set up and tear down around it is way more work than the actual task itself and I've always found the briefly appearing progress bar annoying.
I think we can safely do the same thing to the other options available in the menu.
=> Remove the rest of edit undo and mark card async

AnkiDroid/build.gradle, AnkiDroid/src/main/AndroidManifest.xml, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/widgets/FabBehavior.java, AnkiDroid/src/main/java/com/ichi2/compat/Compat.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV10.java, AnkiDroid/src/main/res/layout-v14/floating_add_button.xml, AnkiDroid/src/main/res/layout/floating_add_button.xml
The items in the FloatingActionsMenu were still clickable even when the menu was collapsed, probably due to a bug in the animation done by the NineOldAndroids library that is used in the version of the floatingactionbutton library that we were using (in order to support Gingerbread).
In this PR I've made it so that we revert to the standard design support library button implementation + context menu below API 14, and use the official floatingactionbutton library on API 14+.
One thing that we need to watch out for in this implementation is that `mActionsMenu` will be null below API 14.
=> Don't use FloatingActionsMenu below API 14

AnkiDroid/src/main/res/layout-v14/floating_add_button.xml
Judging from the comments in the multiple reports saying they can't find the + button over the last week, new users are clearly failing to associate adding a flashcard with the term "Add note" right off the bat, which is kind of obvious really. Anki desktop just uses "Add", so I think we should too.
=> Remove "note" from "Add note" on floating add button

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java, AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.java, AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java
I've noticed that some users continually spam our crash database with thousands of identical crash reports, so here I've added a cache to the shared preferences, which contains the hash of the stack trace of each exception that has been reported for the current version. 
Each time a caught exception is up for reporting, we check if the hash already exists, and if it does we skip sending it to our server. If not, it's added to the cache. Uncaught exceptions are unaffected as that would require modifications to Acra, and it's probably OK to prioritize those crashes anyway.
This should make it easier for us to find crashes, and reduce the frequency that we have to purge crashes before the database becomes unusable.
I've also tightened up the error handling surrounding the opening of the …
=> Don't report duplicate caught crashes

AnkiDroid/build.gradle, AnkiDroid/src/main/AndroidManifest.xml, AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV19.java, AnkiDroid/src/main/res/drawable/launch_screen.xml, AnkiDroid/src/main/res/layout-xlarge/homescreen.xml, AnkiDroid/src/main/res/layout/activity_anki_stats.xml, AnkiDroid/src/main/res/layout/card_browser.xml, AnkiDroid/src/main/res/layout/deck_picker.xml, AnkiDroid/src/main/res/layout/flashcard.xml, AnkiDroid/src/main/res/layout/homescreen.xml, AnkiDroid/src/main/res/layout/navdrawer_header.xml, AnkiDroid/src/main/res/layout/navigation_drawer.xml, AnkiDroid/src/main/res/layout/night_mode_switch.xml, AnkiDroid/src/main/res/layout/studyoptions.xml, AnkiDroid/src/main/res/layout/studyoptions_fragment.xml, AnkiDroid/src/main/res/menu/navigation_drawer.xml, AnkiDroid/src/main/res/values-v21/styles.xml, AnkiDroid/src/main/res/values/colors.xml, AnkiDroid/src/main/res/values/constants.xml, AnkiDroid/src/main/res/values/theme_dark.xml, AnkiDroid/src/main/res/values/theme_white.xml
In v2.4 we "manually" implemented the navigation drawer, only using the `DrawerLayout` view provided in the support library. This was quite messy and hard to extend, so when the design support library was released I switched over to the new `NavigationView` class, which simplified the code and allowed us to add the header image to the top of the drawer, to give a more "material" theme to the app, and increase Anki branding.
In the end we wanted to add a switch for night mode, and `NavigationView` didn't support this. So eventually we switched over to the 3rd party library "material drawer", which allowed custom views. This simplified life somewhat, but it also led to a few hidden bugs that were really painful to solve.
Google ended up releasing a new version of `NavigationView` which …
=> Remove material drawer depenency

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/java/com/ichi2/compat/Compat.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV10.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV11.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/FullSyncer.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/HttpSyncer.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/RemoteMediaServer.java, AnkiDroid/src/main/res/layout/my_account.xml, AnkiDroid/src/main/res/values/04-network.xml, AnkiDroid/src/main/res/values/10-preferences.xml, AnkiDroid/src/main/res/xml/preferences_advanced.xml, AnkiDroid/src/main/res/xml/preferences_custom_sync_server.xml
It looks like they're finally making some progress with https://github.com/dsnopek/anki-sync-server/pull/28, so I've gone ahead and added support for a custom sync server.
Fixes #1057 and supersedes #680
This also makes it clear that AnkiWeb is not affiliated with AnkiDroid in response to the results of the [recent survey](https://docs.google.com/forms/d/1LkA0jw4zb-ye889gzcz8gRBWJqGPfbUpu-QUppbPgHM/viewanalytics).
=> Add ability to use custom sync server

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
From https://github.com/dae/anki/commit/44b83d9bd80a1966842698ea2546216d98db30df
While working on some other stuff I noticed this ancient commit was never ported over. In practice it means those using a somewhat older collection who *also* don't use the desktop client would be seeing the older sibling burying behaviour. It's likely not very many people.
There was also a random call to lock() in the same method which the desktop client doesn't have so I removed it. No idea what the impact of this will be though.
=> switch over to per-day sibling burying

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/MetaDB.java, AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/res/menu/reviewer.xml, AnkiDroid/src/main/res/values/02-strings.xml, AnkiDroid/src/main/res/values/10-preferences.xml
I hope everything is fine, at least it works when I tried it. Would be good if someone could take a look at my sql query in MetaDb.. wouldn't wanna mess up the database ;)
This will ask the user to select language for the current cardside.
Also I suggest we change:
"Reset language assignments (for text to speech and dictionaries) for all decks. Reset specific deck assignments on deck picker."
To
"Reset language assignments (for text to speech and dictionaries) for all decks. Reset specific deck assignments in reviewer."
=> Added set TTS lanuage in context reviewer menu

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java
Makes sure that setting automatic display question/answer times to 0 means infinite also when using gestures.
Fixes #3915
=> Three timer and auto-answer fixes.

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV10.java
As mentioned in #4069. 
The old way of remembering the last selected deck was pretty sloppy to be honest (using a static variable, poor encapsulation, etc.), so I've changed it so that we pass in the default deck ID as an extra, where a value of -1 corresponds to "All Decks". I also pass whether or not all decks was selected as a boolean extra in the result intent, and it's up to the calling Activity to handle that how they want.
I made a new method `openCardBrowser()` which is overridden in DeckPicker and Reviewer to allow the passing in of Activity dependent custom parameters. This is a lot cleaner than the setter method I was using to pass in the current card ID.
Unrelated to the above changes, I also got rid of all the warnings in the Browser class while I was at it, which is in a …
=> Permanently remember last deck in CardBrowser when coming from DeckPicker

AnkiDroid/src/main/res/values/theme_black.xml
Here are colored buttons for the black theme. I used darker colors than the original screenshot. What do you think? For comparison:
=> Colored answer buttons in black theme.

AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.java, AnkiDroid/src/main/res/drawable/footer_button_again.xml, AnkiDroid/src/main/res/drawable/footer_button_all_black.xml, AnkiDroid/src/main/res/drawable/footer_button_all_plain.xml, AnkiDroid/src/main/res/drawable/item_background_selected_pre21_black.xml, AnkiDroid/src/main/res/layout/card_browser.xml, AnkiDroid/src/main/res/layout/note_editor.xml, AnkiDroid/src/main/res/layout/studyoptions_fragment.xml, AnkiDroid/src/main/res/layout/tags_dialog_title.xml, AnkiDroid/src/main/res/layout/toolbar.xml, AnkiDroid/src/main/res/menu/model_browser.xml, AnkiDroid/src/main/res/values/attrs.xml, AnkiDroid/src/main/res/values/styles.xml, AnkiDroid/src/main/res/values/theme_black.xml, AnkiDroid/src/main/res/values/theme_dark.xml, AnkiDroid/src/main/res/values/theme_light.xml, AnkiDroid/src/main/res/values/theme_plain.xml
Some more work on themes and minor color tweaks. The base themes should be identical in their definitions (except for light theme inheriting from light base) and their order which should make them easier to maintain.
- I've factored out the action bar styles so there is only one now. The colors can be grabbed from theme attributes.
- Fixed a bug I introduced with action bar colors (like the long-tap toast)
- Black theme answer button touch feedback is brighter
- Black theme has a brighter accent
- Plain theme anwer button border is thin again. I really didn't like the larger one.
- CAB background colors now use the same color as the action bar
- The default light theme has a darker FAB. I noticed Google apps used the darker primary color, so I copied them.
=> Simplify themes and make them more consistent

AnkiDroid/src/main/AndroidManifest.xml, AnkiDroid/src/main/res/drawable/footer_button_all_black.xml, AnkiDroid/src/main/res/layout/my_account.xml, AnkiDroid/src/main/res/layout/my_account_logged_in.xml, AnkiDroid/src/main/res/layout/studyoptions_fragment.xml, AnkiDroid/src/main/res/values/attrs.xml, AnkiDroid/src/main/res/values/styles.xml, AnkiDroid/src/main/res/values/theme_black.xml, AnkiDroid/src/main/res/values/theme_dark.xml, AnkiDroid/src/main/res/values/theme_light.xml, AnkiDroid/src/main/res/values/theme_plain.xml
- Fixes https://github.com/ankidroid/Anki-Android/issues/4091. I added a comment to explain why that particular base theme is needed so it doesn't get removed again.
- Made black theme button border brighter (should resolve the third point in https://github.com/ankidroid/Anki-Android/issues/4090).
- I removed `Theme_Light_Statistics` which I'm pretty sure is doing nothing (the theme is overridden at runtime, and we have no radio buttons anyway...)
- Created a new style for large buttons. My previous fix to the touch feedback made it so the buttons in the note editor (Tags and Cards) also got given a color which isn't desirable.
=> Theme fixes

.travis.yml, AnkiDroid/build.gradle, api/build.gradle, build.gradle
There's a [new batch](http://developer.android.com/tools/support-library/index.html) of support libraries so we might as well start testing them now.
One of the new libraries was causing us to crash at runtime on API <20 so I turned it off according to the instructions in the release notes. There's a simpler way with Gradle 2.0 which I'll update to when it's out of beta (I'm using it locally for the instant run feature and it seems to work well).
I've tested our main activities on 7 different APIs and all seems to be working well so far.
=> Update to newer support libraries and build tools

AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java, AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.java, AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.java, AnkiDroid/src/main/java/com/ichi2/anki/stats/StatsMetaInfo.java, AnkiDroid/src/main/java/com/ichi2/libanki/Stats.java, AnkiDroid/src/main/java/com/ichi2/libanki/hooks/AdvancedStatistics.java
I've read the code of computing statistics. There is int variable called mType which can have only three values. I decided to create enum called AxisType  and replace  type of mType.
There is method calculateDone in Stats.java. Second method variable is boolean. The function of boolean is not described in javadoc. I decided replace boolean by Chartype and make the method private. Then two public methods will be created: calculateReviewCount and calculateReviewTime. This two new methods will use method calculateDone.
=> Refactoring of statistics

AnkiDroid/src/main/AndroidManifest.xml, AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java, api/src/main/java/com/ichi2/anki/FlashCardsContract.java, api/src/main/java/com/ichi2/anki/api/AddContentApi.java
This is a major performance improvement for inserting large numbers (hundreds or thousands) of Notes.
Added support for bulkInsert() to the content provider as well as the API (addNewNotes). This will work with existing provider but new provider implementation is much faster.
Added support for inserting a new note into a deck with one provider call (instead of three in existing API implementation) to the provider's insert() method. Again, this will work with existing provider, but new provider implementation is about 39% faster.
Added API support for updating an existing note: updateNote() and updateNoteTags(). (This is already supported by existing provider).
Added API support for counting number of notes (with a certain model id) in a deck: countNotes(). I couldn't see a way to count …
=> Added support for bulk insert of Notes: 2000% faster

AnkiDroid/src/main/res/layout-xlarge/homescreen.xml
With the new support libraries, the tablet layout's decklist always anchors to the top on any update or tap. This fixes that.
The changelog for the recyclerview library said something about layout values no longer being ignored, and:
>Note: These lifted restrictions may cause unexpected behavior in your layouts. Make sure you specify the correct layout parameters. 
So I think 0 width counts as an "incorrect" value. Honestly I just guessed stuff until it worked.
=> Use non-zero layout width for xlarge layouts

AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/ContentProviderTest.java, AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java, api/src/main/java/com/ichi2/anki/FlashCardsContract.java, api/src/main/java/com/ichi2/anki/api/AddContentApi.java, api/src/main/java/com/ichi2/anki/api/NoteInfo.java, api/src/main/java/com/ichi2/anki/api/Utils.java
Add support for selection arguments that relate directly to the notes table when querying the db through the Content Provider. The existing `selection` argument that uses `col.findNotes(query)` with the Anki browser syntax can still be used, but if that argument is null then the `findNotes()` call is skipped, which reduces the number of queries to the db from 2 to 1, and should improve the speed by a decent amount.
This change allows searching for specific "csum" and "mid" values with a single sql query, which is useful for duplicate checking in the API. I've also implemented that, and in general brought the duplicate checking in-line with Anki Desktop (doesn't limit duplicates to a specific deck anymore - only the model).
=> Add support for selection args in the notes table in ContentProvider

AnkiDroid/build.gradle, AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
Fix or workaround for https://github.com/ankidroid/Anki-Android/issues/4108
The support libraries were updated again and the problem is still there so I tried to fix it manually. I'll open a bug report for it on google just to see what's up but I have a feeling the change was intended.
As far as I can tell this works and the "up" behaviour isn't broken in things like the studyoptions so I think it's okay.
=> Fix nav drawer not opening with gestures enabled

AnkiDroid/src/main/java/com/ichi2/libanki/sync/RemoteMediaServer.java
Commit 8273eb8e2cb0006af8a37208c08b2b9a5e168c68 fixed a mistake in
the way custom sync server URLs are assembled, but at the same time it
broke the generation of the media server URL.
=> Fix broken custom sync server media server url generation

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java, AnkiDroid/src/main/java/com/ichi2/compat/Compat.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV10.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.java
I encountered a problem that a data saved to Cookies by JavaScript was sometimes to be lost only in the last one. I tried and found out that [CookieManager](http://developer.android.com/reference/android/webkit/CookieManager.html) managed Cookies asynchronously and because of that the changes applied to Cookies after the last synchronization process was lost. Therefore, it is necessary to specify the timings when it to sync Cookies manifestly. I guess calling [`CookieManager.flush()`](http://developer.android.com/reference/android/webkit/CookieManager.html#flush()) in [`onPause()`](https://github.com/ankidroid/Anki-Android/blob/develop/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L905) and [`onDestroy()`](https://github.com/ankidroid/Anki-Android/blob/develop/AnkiDro …
=> Fix an issue that data in Cookies may be lost

AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
A NavigationDrawerActivity that opts to have a back button as the
navigation button will also override the button behaviour to go back.
Fixes https://github.com/ankidroid/Anki-Android/issues/4136
=> Fix activity with back icon not going back

AnkiDroid/src/main/assets/flashcard.css, AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java
Make the replay button scale up for large text, but use a minimum size for small text, and make the button vertically align.
Fixes #4162 
Although i am not sure about the shape of the touch feedback. I couldn’t reproduce that, it looks good on the several devices where it tested it.
Images (See #4162 for “before”):
Also tested with Gingerbread, there the PNG naturally gets blurry when you scale it up, but otherwise it looks basically the same.
=> Tweaks for the inline replay button

AnkiDroid/src/main/AndroidManifest.xml, AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java
1) Allow use of provider by com.ichi2.anki via `checkCallingOrSelfPermission()`
The only difference between `checkCallingOrSelfPermission()` and `checkCallingPermission()` is that the latter has [this additional check](http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android/4.3_r2.1/android/app/ContextImpl.java#1549):
```java
int pid = Binder.getCallingPid();
if (pid != Process.myPid()) {
return checkPermission(permission, pid, Binder.getCallingUid());
}
return PackageManager.PERMISSION_DENIED;
```
so using `checkCallingOrSelfPermission()` (which doesn't have the above check) is essentially doing the same as what was there before in a more reliable way.
My understanding of the warnings in the documentation against using `checkCallingOrSelfPermission()` are …
=> Some minor changes to permissions checking and logging

AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java, AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java, AnkiDroid/src/main/java/com/ichi2/libanki/Sched.java
The old deck overview screen had a progress bar thing that is no longer used. This commit cuts a whole SQL query from building that view so it should speed things up a little.
=> Remove unused totals from deck overview

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
Previously we were calling `TASK_TYPE_RENDER_BROWSER_QA` with the first 1000 cards in the result from `mSearchCardsHandler.onPostExecute()`.
Since the `mRenderQAHandler` does a `notifyDataSetChanged()` for EVERY card in the list as they're updated, this was effectively blocking the long-click listener for the cards, so I moved that initial card rendering code into the first DeckTask and dropped MIN_CARDS_TO_RENDER from 1000 to 500.
I also did a little bit of tidying up like using the List and Map interfaces polymorphically instead of the ArrayList and HashMap implementations.
Fixes #4191
=> Remove latency for long-tap to work in Browser

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/compat/Compat.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV10.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV17.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV19.java
This PR adds a option whether or not permit autoplay on HTML5 media element without a user gesture.
Anki, AnkiMobile and AnkiDroid supports audio/video elements as the special tag. It is very useful for normal use, but the specification of it lacks flexibility. 
For example, there is someone learning something with a large card, containing media elements sparsely, and he want to play a media when it appeared into the screen without a touch. He can not do it with the build-in feature, but can with JavaScript and this option.
=> add a workaround option allowJSMediaAutoPlay

CONTRIBUTING.asc
previous link resolved to https://github.com/ankidroid/Anki-Android/blob/develop/manual.html, which 404-ed
=> fix manual link

AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/ContentProviderTest.java, AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java, api/src/main/java/com/ichi2/anki/FlashCardsContract.java
The purpose of this PR is to support the case when adding a new template because that template may need a corresponding conditional field. The new field is appended to the end of the existing fields so will not conflict with the position (or existence) of existing fields.
=> add provider support for inserting new field (after existing fields) to existing model

AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/ContentProviderTest.java, AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java
If the AnkiDroid process were to be killed after a client app makes insert() or update() calls (i.e. without the user navigating to a screen in AnkiDroid that calls col.save()) then many of the changes are lost. This fixes that problem and also updates the relevant unit tests to check for this issue.
@hssm 
Could you please have a check through this? I'm not sure if we are even calling col.save() in all the right places in the app itself, as the process could be killed at anytime.
=> Flush all changes to the DB after content provider insert() and update()

AnkiDroid/build.gradle, AnkiDroid/testconfig.gradle
This allows unit tests to run properly on an Android M device when calling the tests manually from the command line (i.e. `./gradlew connectedCheck`), and in the future should enable Travis to run the tests. 
I only have access to Android Studio 1.5 on the laptop I'm stuck with at the moment, but it seems that when it internally runs unit tests it doesn't call the gradle task (just builds and runs via adb), so this hack doesn't work in the IDE unfortunately.
The workaround there is to install and grant storage permissions manually before running tests.
=> Allow unit tests to work on SDK23 from command line

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
From https://github.com/ankidroid/Anki-Android/issues/4213
For devices that force use of WAL mode. This will let them do a full sync upload. Should have no effect for everyone else. The desktop client has the same line of code for this.
=> Set journal_mode=delete when closing collection

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
The [documentation](http://developer.android.com/intl/es/reference/android/database/sqlite/SQLiteDatabase.html#execSQL%28java.lang.String%29) actually says that `pragma journal_mode` doesn't work when `enableWriteAheadLogging()` is used, so use the provided `disableWriteAheadLogging()` instead.
=> Use compat method to turn off WAL

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
Following on from [this discussion](https://groups.google.com/forum/#!topic/anki-android/UDKasC1fEAw).
=> Support intent: and android-app: url schemes in templates

AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java
As far as I can tell, all these deck tasks require a col.save() call before the changes to the models are flushed to the DB. None of the other DeckTasks appear to suffer from unflushed changes to the DB.
@hssm what do you think?
closes #4214
=> Add col.save() to the model deck tasks

AnkiDroid/src/main/res/layout/card_browser_item_my_searches_dialog.xml
Fixes https://github.com/ankidroid/Anki-Android/issues/4252
Don't think `layout_centerVertical` was doing anything useful. Before-after:
=> Don't center saved searches list

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java, AnkiDroid/src/main/java/com/ichi2/anki/UIUtils.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TagsDialog.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV19.java, AnkiDroid/src/main/java/com/ichi2/preferences/StepsPreference.java, AnkiDroid/src/main/java/com/ichi2/themes/Themes.java
Fixes https://github.com/ankidroid/Anki-Android/issues/4251
We manually apply a color in our snackbar methods but they are buried inside AnkiActivity so they can't be used anywhere else. I don't think there is a very strong tie between those activities and showing snackbars so I moved it out to the UIUtils class.
=> Move snackbar methods so they are globally accessible

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/res/layout/reviewer.xml, AnkiDroid/src/main/res/layout/reviewer_flashcard.xml, AnkiDroid/src/main/res/layout/reviewer_fullscreen_1.xml, AnkiDroid/src/main/res/layout/reviewer_fullscreen_2.xml, build.gradle
I think this fixes #4259. Hopefully it hasn't introduced other errors elsewhere. I'm looking to get some feedback on how well it works and a few points below before merging.
The PR adds a 20dp margin to all edges of the whiteboard and gesture detector layers. The gesture detector layer already had this margin in the top and bottom, so I just kept the same number arbitrarily. The number seems to basically work, but according to my testing it may need to be slightly increased in some cases. 
0. I'm not sure if there's any standard for how many dp are taken up by these "system swipe zones"...? If there is an official number then we should use it, if not then I guess we could either dig into the source code, use trial and error, or change to a different and more reliable approach (not sure …
=> Whiteboard gesture fix

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java, AnkiDroid/src/main/java/com/ichi2/libanki/Media.java, AnkiDroid/src/main/java/com/ichi2/libanki/Sched.java, api/src/main/java/com/ichi2/anki/api/AddContentApi.java
The `String.format` calls in the API code would fail if someone is using a language with a different set of symbols for numbers (e.g., Arabic). The rest are mostly cosmetic fixes.
=> Explicitly supply locale in string formatting calls

AnkiDroid/src/main/java/com/ichi2/libanki/DB.java, AnkiDroid/src/main/java/com/ichi2/libanki/Note.java
Fixed a query that would never work because the string formatting had no tokens to replace.
Seems to be low-impact from what I understand, making us save data a little more frequently than necessary.
=> Fix query not using selectionArgs

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioView.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioFieldController.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicTextFieldController.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/IFieldController.java
- Fixed audio not saving if recording is terminated with the "Save"
action icon.
- Fixed many cases where the recorder would become unusable after the
first use.
---
Fixes https://github.com/ankidroid/Anki-Android/issues/4254
Also want to close https://github.com/ankidroid/Anki-Android/issues/2669. I've at least fixed the cases where AnkiDroid itself puts it into that state.
=> Fix audio recording not saving and cases where recorder stops

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/java/com/ichi2/compat/Compat.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV10.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV19.java, AnkiDroid/src/main/res/layout/reviewer_flashcard.xml
* The immersive mode layouts should not be used below KitKat
* The layout margins are ignored in Gingerbread without layout_gravity set
* Renamed `isSystemUiVisible()` to make the meaning a bit more clear
=> Fix some bugs with fullscreen mode on old APIs

AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java
Because the parent activity is what receives the result, and the request
code would be modified if the fragment is the one that launches it.
---
From [here](http://stackoverflow.com/questions/10564474/wrong-requestcode-in-onactivityresult). Might fix https://github.com/ankidroid/Anki-Android/issues/4274. Fixes at least the issue I identified with it not working on tablets.
=> Use parent activity of fragment to start activities for result

AnkiDroid/src/main/java/com/ichi2/anki/stats/OverviewStatsBuilder.java, AnkiDroid/src/main/res/values/06-statistics.xml
@timrae 
Remind me again which merge strategy you prefer for the releases. Should PRs target `release-2.6` and rely on the merge script to port everything back to `develop`, or do we just target `develop` and cherry-pick anything we think should go to 2.6 manually? Not really sure what's easier.
--
This commit adds more of the missing stats from https://github.com/ankidroid/Anki-Android/issues/3623, namely the *Forecast* block. I also renamed the "Progress" block to "Added" to match the desktop version which I somehow missed earlier.
There are still a couple of values missing and I've started porting them over but the changes are too big to move into the beta at this point. It might end up as a major re-work of the stats code for the next release instead (the non-charting portion, that …
=> Add forecast to the overview statistics

AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.java, AnkiDroid/src/main/java/com/ichi2/libanki/Stats.java, AnkiDroid/src/main/java/com/wildplot/android/rendering/PieChart.java, AnkiDroid/src/main/java/com/wildplot/android/rendering/PlotSheet.java, AnkiDroid/src/main/res/values/06-statistics.xml, AnkiDroid/src/main/res/values/attrs.xml, AnkiDroid/src/main/res/values/colors.xml, AnkiDroid/src/main/res/values/theme_black.xml, AnkiDroid/src/main/res/values/theme_dark.xml, AnkiDroid/src/main/res/values/theme_light.xml
- Make pieces of the "Cards Types" pie chart start from the same position (12 o' clock, was 3 o'clock) and move in the same direction (clockwise, was anti-clockwise) as in Anki Desktop (solves https://github.com/ankidroid/Anki-Android/issues/3349)
- Make the order of the legend's elements in the statistics charts deterministic (solves https://github.com/ankidroid/Anki-Android/issues/3349)
- Change text of legend item "Suspended" in the "Cards Types" pie chart start to "Suspended+Buried" (solves https://github.com/ankidroid/Anki-Android/issues/3349 and https://github.com/ankidroid/Anki-Android/issues/3562)
=> Make pie chart rotation direction, legend order and legend text consistent with Anki Desktop

AnkiDroid/src/main/java/com/ichi2/anki/stats/OverviewStatsBuilder.java, AnkiDroid/src/main/java/com/ichi2/libanki/Stats.java, AnkiDroid/src/main/res/values/06-statistics.xml
A quick fix to NaN appearing in average calculations in the stats overview.
Also updated a string for consistency.
=> Fix NaN in overview stats calculations

AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.java, AnkiDroid/src/main/java/com/ichi2/libanki/Stats.java, AnkiDroid/src/main/java/com/ichi2/libanki/hooks/AdvancedStatistics.java, AnkiDroid/src/main/java/com/wildplot/android/rendering/PlotSheet.java
- Move "Cram" bar to top in Review Count/Review Time (solves https://github.com/ankidroid/Anki-Android/issues/4277)
- Make order in which legend items are shown consistent with Anki Desktop (reverse order for done & due charts, but keep cumulative as last item)
=> Move "Cram" bar to top in Review Count/Review Time & fix legend order

AnkiDroid/build.gradle, build.gradle
I tried downgrading the support libraries to get around https://github.com/ankidroid/Anki-Android/issues/4217 but the problem seemed to remain even with older versions. I'm thinking that my method to reproduce the problem is a different problem entirely and has always been there. So maybe Google's fix does actually work for the cases we have reported.
I want to try updating the support libs and see if @snowtimeglass can still reproduce it in the next beta.
Also, the Material Dialogs library has [moved back to jCenter](https://github.com/afollestad/material-dialogs/releases/tag/0.8.5.9) so I removed the jitpack repo while I was at it.
=> Update support libraries

api/src/main/java/com/ichi2/anki/api/AddContentApi.java
We need to check for modelUri being null before passing it to
Uri.withAppendedPath().
=> Handle null from ContentResolver insert in API

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
Fixes inconsistencies with the currently selected deck, the currently
highlighted deck in the deck list, and the study options fragment (if
visible).
---
Fixes https://github.com/ankidroid/Anki-Android/issues/4283. Also fixes the problem where tapping on an unreviewable deck keeps the previous deck highlighted in the deck list even though the deck that was just tapped has become the current deck (which is important for things like selecting the deck you wish to add new cards to etc).
=> Correctly update interface after tapping unreviewable deck

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
As identified on the forum, it's annoying when you are undoing whiteboard strokes quickly and accidentally undo the last review.
This changes the behavior slightly so that the undo button becomes disabled when the queue is empty, until the whiteboard is cleared.
=> Don't immediately switch to normal undo on empty whiteboard undo queue

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
Previously, if you swiped down from the status bar with immersive fullscreen enabled to show the action bar, and you did a swipe gesture to answer the card, the card would be answered without going back to immersive mode.
=> Resume immersive mode on swipe in addition to tap

AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.java, AnkiDroid/src/main/java/com/ichi2/libanki/hooks/AdvancedStatistics.java
Solves: https://github.com/ankidroid/Anki-Android/issues/4317
Also fixed bug in AdvancedStatistics which:
- Made it crash if no cards were studied today
- Made it only take into account cards studied today in 1 deck
=> Statistics: right y-axis disappeared on "BREAKDOWN"

AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.java, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/res/values/attrs.xml, AnkiDroid/src/main/res/values/theme_black.xml, AnkiDroid/src/main/res/values/theme_dark.xml, AnkiDroid/src/main/res/values/theme_light.xml
Fixes #4333 and #3943.
This commit changes the way our duplicates look in the note editor. We lose the underline thing on dupes but this is the quickest and easiest way that works on all APIs. I vastly prefer this look over the highlighted underline and it at least looks like the desktop version which is more familiar to our users.
=> Color entire text box for dupes in note editor

AnkiDroid/src/main/assets/flashcard.css, AnkiDroid/src/main/assets/scripts/card.js
Fixes https://github.com/ankidroid/Anki-Android/issues/4343
--
Since card content scrolls vertically it makes sense to still use 90%
for max-height in order to keep some of the card visible (like text
above or below an image).
=> Set max-width of images to 99%

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
@timrae Do you remember exactly why this condition was included? I couldn't understand why it was there and there appear to be no adverse effects of removing it as far as I can tell. It fixes https://github.com/ankidroid/Anki-Android/issues/4339.
=> Don't prevent rendering in browser when scroll at 0

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.java
Fixes https://github.com/ankidroid/Anki-Android/issues/4341
Even if the locale in the `Configuration` is set correctly, it refuses to use it unless explicitly updated. No idea why that is  (Android :camel:), but our condition to skip it was preventing us from re-applying it when returning to an Activity. Someone had actually solved this problem before.
=> Always set locale when returning to Activity

AnkiDroid/src/main/assets/flashcard.css, AnkiDroid/src/main/assets/scripts/card.js
The pre-Chrome engine (Android 4.3 and below) uses the screen's
dimensions to determine the width, so we need to keep that at the
original 90% to avoid horizontal overflow. The Chrome engine uses the
dimensions of the parent element so we safely use 100% without causing
overflow.
=> Adjust max-width image resizing

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
Check the demo: https://youtu.be/dfrWr1FcIfs
As you see, `RecyclerView` works correctly when nested in `SwipeRefreshLayout`.
=> Disable default "swipe to refresh" animation in favor of custom sync dialog

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
@madhead 
I want to increase the threshold for triggering a sync by swiping. I like this feature and have been using it myself but there are still occasions where I trigger it accidentally when I just wanted to scroll up the deck list (this is maybe 95% my own bad habit).
Unlike, say, Gmail, the cost of accidentally starting and cancelling a sync in AnkiDroid is pretty high, so I want to try to decrease the chances of it happening. 
Also a quick fix to a warning in DeckPicker.
=> Increase swipe-to-sync trigger distance

AnkiDroid/src/main/java/com/ichi2/libanki/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java
The previous calculation always truncated to 1.
--
Fixes https://github.com/ankidroid/Anki-Android/issues/4390. Fairly low impact scheduling bug. Learning cards are meant to be randomized within the learn queue, and this bug meant that they were always scheduled in the order that they were introduced.
=> Fix random factor in lrn card scheduling

AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java
Fixes https://github.com/ankidroid/Anki-Android/issues/4395.
I couldn't pinpoint the exact cause of the problem, but removing this method call fixed it. Calling it is completely unnecessary as the rest of the method only copies media files and doesn't require an open collection, so removing it is not a problem.
=> Remove unrequired colleciton reopen in import-replace

api/src/main/java/com/ichi2/anki/api/Utils.java
Duplicate checking code does not pad checksum with leading zeroes as main AnkiDroid code does, causing fields with checksums starting with 0 to fail to match correctly.
=> Fix duplicate checking bug

AnkiDroid/src/main/res/layout/reviewer_fullscreen_2.xml
Fixes #4451 
I have no idea why it was working before... The code assumes the parent of the flashcard layout is a relative layout, but it looks like I accidentally "optimized" out the "unnecessary" RelativeLayout for the total fullscreen mode.
=> Fix crash in Reviewer due to incorrect cast

AnkiDroid/src/main/assets/chess.css
Fixes #4465.
* Always use black font.
* Flip light and dark squares.
* Style more consistently with day mode.
Day mode:
Night mode before:
Night mode after:
=> Improve night mode for chess boards.

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/libanki/LaTeX.java, AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
This fixes #4466.
Don't merge this yet, I want to investigate the impact of this bug with all our other uses of `appendReplacement` when I have time tomorrow.
[This method](https://developer.android.com/reference/java/util/regex/Matcher.html#appendReplacement(java.lang.StringBuffer,%20java.lang.String)) eats up `$` and `\` characters since it treats them as special substitution characters. For whatever reason, the javadocs that show up inside the IDE omit most of the information which shows up in the web link. Would have been nice to have that info!
=> Quote the replacement string when using Matcher#appendReplacement

AnkiDroid/src/main/java/com/ichi2/libanki/sync/MediaSyncer.java
Steps to reproduce:
* Use [`anki-sync-server`-based server software](https://github.com/dsnopek/anki-sync-server) (not tested with AnkiWeb)
* Add a bunch of media files in desktop Anki and sync
* Delete some of the media files on desktop Anki and sync again
* Reset AnkiDroid and try doing a full sync to your sync server
Expected Result:
* Sync succeeds, just like in desktop Anki
Actual Result:
* AnkiDroid will abort media sync (but succeed in database sync), stating an "Internal Server Error" has occurred.
What actually happened:
* Server returned list of media files (including deleted ones), but has set their checksums to `null` (JSON value)
* AnkiDroid parses this JSON string using https://developer.android.com/reference/org/json/JSONArray.html → JSON `null` values become, …
=> Don't mix up JSON `null` and missing last parameters on full media sync

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java, AnkiDroid/src/main/res/values/10-preferences.xml
For front card, delay by the time for audio on the front and back, so
the user could hear the audio, then have time to say or think the
answer.
Required changing min api level to 14 for media file length call. This
loses compatibility with 1.6% of devices according to
https://developer.android.com/about/dashboards/index.html The other
option would be to figure out some older api, or make it conditional on
a newer version if there is none. I don't care, get a newer os,
wikipedia says 4.0 was released in 2011.
=> Delay automatic card advance by auto play audio time

.travis.yml, AnkiDroid/src/main/AndroidManifest.xml, AnkiDroid/src/main/java/com/ichi2/libanki/sync/HttpSyncer.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/MediaSyncer.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/RemoteServer.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java
Previously we were calling sync/finish during abort, which is not supported by the protocol, as discussed in issue #4512. Instead we must use the new abort command. I also removed unnecessary calls to finish() during media sync, and added another check during the main file fetching loop to improve the cancellation speed during media sync.
Closes #4512 
@dae
=> Fix sync cancellation

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java
On Desktop, when creating a Custom Study session "by tag", the cards are rescheduled by default. This configuration is inconsistent in AnkiDroid. This patch aims to solve it, by setting the reschedule option to true on CUSTOM_STUDY_TAGS deck creation.
Fixes Google Code Issue 2043 reported in #2940.
=> Fix CUSTOM_STUDY_TAGS reschedule setting

AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java, AnkiDroid/src/main/java/com/ichi2/libanki/Media.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/MediaSyncer.java
Fixes https://github.com/ankidroid/Anki-Android/issues/4507
This was technically a self-correcting issue, so it's not a big deal, but it is really annoying when triggered because it's slow and resulted in an error. Basically, the sanity check fails because of the differing counts so it wipes the media DB in order to rebuild it on the next sync, which meant scanning every media file once again (thus fixing the discrepancy).
I uncovered a bug in the part that wipes the DB. The `vacuum analyze` command is failing. It's probably because the Android SQLite method it uses can only execute one statement per call, so I split them up onto two lines ([the importer](https://github.com/ankidroid/Anki-Android/blob/develop/AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java#L135) does …
=> Fix media sync comparison and a consequent DB error

AnkiDroid/src/main/java/com/ichi2/anki/services/BootService.java, AnkiDroid/src/main/res/values/17-model-manager.xml
Couple of small fixes.
The first one was causing a crash on device startup if you have dynamic decks.
The second is producing a confusing lint warning which would otherwise be useful for finding broken translation strings that would crash at runtime.
=> Fix boot crash

AnkiDroid/src/main/AndroidManifest.xml, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerExportCompleteDialog.java, AnkiDroid/src/main/java/com/ichi2/utils/Files.java, AnkiDroid/src/main/res/values/02-strings.xml, AnkiDroid/src/main/res/values/04-network.xml, AnkiDroid/src/main/res/xml/filepaths.xml
I just noticed today on my Nexus 5x that the app crashes with a `android.os.FileUriExposedException` on export->email send. The Android documentation says:
> Don’t use Uri.fromFile(). It forces receiving apps to have the READ_EXTERNAL_STORAGE permission, won’t work at all if you are trying to share across users, and in versions of Android lower than 4.4 (API level 19), would require your app to have WRITE_EXTERNAL_STORAGE. And really important share targets, such as the Gmail app, don't have the READ_EXTERNAL_STORAGE, causing this call to fail.
So I set up a FileProvider to send the file in a way that doesn't require the receiving app to have external storage read permission. For this to work, we have to hardcode the list of paths that the FileProvider has access to, which makes it a bit …
=> Fix sending of exported files on Android 6+

AnkiDroid/src/main/java/com/ichi2/libanki/Consts.java
media sync goes through the same domain now, avoiding a slow extra SSL handshake
Closes #4549
=> use sync.ankiweb.net for syncing

AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java
The application crashes when triying to set Data Source for mediaRetriever if the media files are not found.
This happens for example, when the "Automatic Display Answer" feature is activated.
=> Fix Application Crash due to Data Retriever

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ConfirmationDialog.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DialogHandler.java
Android can't instantiate fragments that are anonymous classes. It was somehow working fine until they updated the support library. Here we use Runnables instead. Once we move to Java8 we can make the code much less verbose by using lambdas.
Fixes #4587 
Fixes #4571
=> Fix IllegalStateException crashes with ConfirmationDialog

AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java
I missed several confirmation dialogs in 5c8a309, due to my incorrect assumption that the compiler would catch all of the old usages. This time I grepped to make sure I got them all.
=> Fix the remaining confirmation dialogs

AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
Lag especially noticeable when starting another activity, e.g. startActivity(settingsIntent).
Solution: A pending runnable will be executed after the drawer has been closed.
=> Navigation drawer: lag on older devices

AnkiDroid/src/main/java/com/ichi2/anki/web/HttpFetcher.java
Glosbe are returning "HTTP/1.1 200" which does not contain "OK" in the status line, so the request was getting caught by this if statement. I think checking on the status code should be less fragile. There's also a bunch of deprecated HttpClient stuff in this file, but I'll leave it for now!
Fixes https://github.com/ankidroid/Anki-Android/issues/4502
=> Fix glosbe

AnkiDroid/src/main/res/values/01-core.xml
The permission description was not matching the format intended by google (as described in issue #4619)
=> Corrected Permission Description

AnkiDroid/src/main/java/com/wildplot/android/rendering/graphics/wrapper/GraphicsWrap.java
This fixes issues with the card types graph showing almost everything as black when unseen is 0, except the yellow part for suspended which is drawn afterwards.
The documentation for [Canvas.drawArc][1] says:
> If the sweep angle is >= 360, then the oval is drawn completely.
> Note that this differs slightly from SkPath::arcTo, which treats the
> sweep angle modulo 360. If the sweep angle is negative, the sweep
> angle is treated as sweep angle modulo 360
There's no explicit mention of what happens if the sweep angle is 0, but it looks like in practice it's the same as if it was 360.
Since the operation is going to be a no-op either way, it doesn't hurt to skip it.
[1]: https://developer.android.com/reference/android/graphics/Canvas.html#drawArc(android.graphics.RectF,%20float,%20float,%20 …
=> drawArc/fillArc: Avoid drawing full arcs when arcAngle is 0

AnkiDroid/src/main/java/com/ichi2/libanki/Stats.java
Otherwise this supposedly weekly statistic is skewed by adding 1-2 extra days,
making it somewhat pointless.
=> round days in the weekly breakdown down to whole weeks

AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java
Makes it easier to find out which file causes #3567 on the user's device.
=> Include filename in IOExceptions thrown by Utils.writeToFile()

AnkiDroid/src/main/java/com/ichi2/async/Connection.java
Following on from #4718.
Note that we already have `mediaError = AnkiDroidApp.getAppResources().getString(R.string.sync_media_error);` in the case where the media syncer returns null.
=> Note that there was an error on exception during media sync

AnkiDroid/build.gradle, AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java, AnkiDroid/src/main/java/com/ichi2/anki/TtsParser.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV10.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV15.java
Although a number of workarounds have been proposed in #1463 to make AnkiDroid read only parts of questions and answers using a TTS engine, I think the originally proposed solution, i.e. recognition of `<tts>` elements embedded in the card template, is simpler and more convenient for the user. This is also the approach taken by the AwesomeTTS plugin to the desktop app. This commit makes AnkiDroid recognise `<tts>` elements similar to those accepted by AwesomeTTS.
If the front or back template contains any `<tts>` elements with the `service` attribute set to `android`, then only the text enclosed in these elements is read aloud using the TTS engine. The `voice` attribute can be used to specify the language of the text (details below). If no `<tts service='android'>` elements are present in …
=> #1463 Recognize TTS elements in questions and answers.

AnkiDroid/src/main/java/com/ichi2/libanki/LaTeX.java, AnkiDroid/src/main/java/com/ichi2/libanki/Media.java
As this [pull request](https://github.com/dae/anki/pull/112) was merged into Anki 2.1, LaTeX can now be exported to SVG instead of PNG, by enabling an option in the note type (see [this commit](https://github.com/dae/anki/commit/8cd20f335272e7471a861afc530665591ebab181)).
This works the same way as the current Anki 2.1 code:
- if the note type specifies it, look for an svg file
- otherwise, look for a png one
I'm not sure if it should be done this way or if AnkiDroid should check for both files, ignoring the note type.
=> Use SVG images of LaTeX formulas, when required

AnkiDroid/src/main/java/com/ichi2/libanki/Media.java
Hello,
the reviewer didn't show pictures if they are located in subfolders (e.g., /sdcard/.../collection.media/japanese/hand.jpg). The reviewer activity shows a missing picture symbol. However, when opening the card editor, the image shows without problems.
Ankidroid replaced the "/" with %2F, using japanese%2Fhand.jpg as path. Excluding "/" from URI encoding fixes this problem.
All the best,
Thomas
=> support pictures in subfolders

AnkiDroid/src/main/assets/scripts/card.js
It looks like card.js's current approach of scrolling to the answer by using `window.location.href = "#answer";` is no longer working in newer versions of the WebView for whatever reason. However, it seems that `window.scrollTo()` still works correctly.
So I have come up with a proposed fix that:
- Locates the answer divider element, and if it is present:
- Determines the distance between the answer divider and the top of the HTML page
- Scrolls the window to that Y location using `window.scrollTo()`
This is working on my Nexus 5X with the following specs:
Android 8.0.0
Chrome 62.0.3202.84
=> Proposed fix for #4624 - fix scrolling when showing answer

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
This makes the whiteboard more ergonomic (in my subjective opinion). [Related issue](https://github.com/ankidroid/Anki-Android/issues/4522). Summing up, when keeping one finger on the whiteboard while it is activated, it is now possible to use a second finger to scroll the card behind the whiteboard or tap onto one of its elements.
With respect to documentation in the code files I modified, I have tried to follow the style and extent I found in there. Feel free to criticize or ask for more if anything is unclear!
To make the whiteboard sensitive to multitouch-events, I changed its call to MotionEvent.getAction() into MotionEvent.getActionMasked() and included a check for a second finger being placed on the touch screen. In that case, the current stroke is aborted and the whiteboard goes …
=> pass certain multitouch events through the whiteboard to the card behind it

tools/translation-rates.sh
I was curious of the status of the Spanish language translation, and noticed the translation status tool did not seem to function - it appears crowdin.com altered their generated status page and the tool had not been updated to match? I reworked the string of greps and seds until it appeared to work for me, perhaps this is useful for others? Now to figure out how to get Spanish to 100% translated + approved using crowdin.com...
=> updated translation status tool to correctly scrape current format of crowdin.com

tools/parallel-package-name.sh, tools/parallel-package-release.sh
Hi there - I made one set of small non-functional changes to the parallel build, and one functional change -
I updated sed commands so they were "sed -i ''" vs "sed -i -e", this means the in-line edited files are no longer backed up, but the current combo of MacOS and AndroidStudio was failing to build when there were ".xml-e" (backup) files in the resources directory. Since we have version control for real backups and these builds will never be committed, it seemed an easy decision to remove the backup functionality to proceed with the build
The functional change is the addition of a 'parallel-package-release.sh' tool, that iteratively builds 3 parallel packages (A, B and C, like before) in a way that should make for compatible upgrades to previous users.
This appears to work for me now …
=> Make parallel builds work on current code, add parallel build release tool 

tools/parallel-package-name.sh
@ju-w logged bug #4777 indicating my changes to the renaming script failed on Ubuntu.
Root cause is that the '-i' flag for sed is not POSIX, so is not cross-platform and my change made it work on OS X but is unworkable on Linux (and vice-versa)
The solution I picked was to convert to 'perl -pi -e "s///g"' style from 'sed -i "s///g"' style, and this pull request is the implementation of that simple conversion.
Tested on OS X and the reported Ubuntu version
I also did a full sweep in tools/* and it is worth noting the 'release.sh' script still uses 'sed -i' but that's obviously separate so I will leave it at the mention.
=> in-place sed editing not cross-platform, convert to perl, fixes #4777

AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.java, AnkiDroid/src/main/java/com/ichi2/anki/services/BootService.java
simple change from setInexactRepeating to setRepeating
I say it "may" fix issue #4525 because I am able to see notifications correctly firing at the expected time with and without the fix (on Nexus 5 API 23 stock emulator), but I it is obviously an issue for some
This will obviously need testing from the affected parties, and if it isn't sufficient the only alternative I see in AlarmManager is to implement recurrence in our code and call setWindow() to get closer to exact alarms
=> Change notifications to setRepeating, may fix issue #4525

.travis.yml, AnkiDroid/build.gradle, api/build.gradle
buildtools update from 26.0.2 to 26.0.3 (shouldn't affect anything?) and gson from 2.4 to 2.8.2 - a bigger change but seems to work fine for me?
=> Updating versions for buildtools and gson dependency

AnkiDroid/build.gradle
From the [docs](https://developer.android.com/about/versions/oreo/android-8.0-changes.html): "By default, these restrictions only apply to apps that target O"
That seemed like an easy temporary fix for Issue https://github.com/ankidroid/Anki-Android/issues/4786, so I just tested it, and if we move targetSdkVersion to 25 (vs 26 in upstream/master) this no longer crashes on reboots on my 8.1 emulator where I was able to reproduce this before.
It is obviously not a proper fix but it definitively avoids the problem for now. I will still work on a definitive fix for this and submit a PR but killing a crash bug with a one-digit change is nice if it is acceptable
=> Decrease targetSdkVersion to pre-26 / 8.0, avoids background limits

AnkiDroid/src/main/java/com/ichi2/libanki/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/Stats.java, AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java
The libanki/sched functions such as nextIvl and the libanki/utils function timeQuantity work with intervals in seconds. For intervals longer than 68 years this can't be expressed in a signed 32 bit int, causing an integer overflow and buggy display of interval times under the review ease buttons.
Edit: Also updated timeSpan and roundedTimeSpan which used int seconds as well, used in showing deck statistics.
Recently I started seeing this come up for cards in my decks. When I looked it had been reported by another user last year under issue #4674 (fixed by this patch).
=> Use long type when intervals are handled in seconds

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
Added keyboard shortcuts to NoteEditor and DeckPicker that didn't impact overall usability/UI flow for people using hardware keyboards.
Ignored all but the most common desktop keybindings.  If this is a feature that's wanted could implement the remainder.
=> added common shortcuts from Anki desktop

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.java
I verified nook is api 8, and while nook HD/HD+ are >= API 15, the "isNook()" boolean was targeted exclusively at the api 8 nook, so removing this is safe while we move to api >= 15
=> Remove nook safeDisplay workaround, nook is api 8

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/beolingus/parsing/BeolingusParser.java, AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/beolingus/parsing/BeolingusParserTest.java
Beolingus has switched to HTTPS and they enforce it by sending a 302 / Moved Permanently redirect HTTP response when you try them without TLS. Everything else about the integration appears to be working as originally coded so this was a trivial fix.
=> Use HTTPS to connect to Beolingus now, fixes #4789

AnkiDroid/src/main/res/values/constants.xml
The gradle plugin moved from the AAPT (Android Asset Packaging Tool) v1 to v2 as it went from gradle plugin 2.3+ to 3+
The difference between the two is that AAPTv1 doesn't display duplicated percent signs in the UI from our resources XML strings that have '%%' in them in an attempt to escape the % with a %.
From my reading it may be that when we move to AAPTv2 we will have to update all strings to remove the %% escaping (and just leave %) or we will have to find a workaround, or ?
It appears that AAPTv1 will be around through the end of 2018 and it's a problem either way, no need to make it an urgent problem, right?
I'd say this temporarily fixes the issue so it's not a blocker, but should not *close* Issue #4801
=> Remove % sign escape in constants file for AAPTv2, Fixes issue #4801

.travis.yml, AnkiDroid/build.gradle, api/build.gradle, build.gradle, gradle/wrapper/gradle-wrapper.properties
- upgrade gradle plugin to current stable
- upgrade gradle to 4.5.1 (most current that works seamlessly with gradle plugin)
- new gradle plugin ignores buildtools specification, remove it
- new gradle exposes dependencies with [more granularity](https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration#new_configurations), convert ours
- api module still had a targetSdk of 26 but we backed down to 25 for main module, I don't think these should diverge?
- remove obsolete buildtools from travis, add the current ones (hope this works)
=> Upgrade gradle and gradle plugin, with appropriate migrations, and Travis speedups

api/build.gradle, api/src/main/java/com/ichi2/anki/FlashCardsContract.java, api/src/main/java/com/ichi2/anki/api/AddContentApi.java
I moved the version, which is probably presumptuous but I wanted to generate a test version for Issue #4857 
Other than that, this is 100% javadoc fixups to compile cleanly with Java8's new fail-fast doclint
=> compile with up-to-date toolchain, bump to 1.1.0alpha6, fix #4857

api/build.gradle, build.gradle
- Adding the flag that chooses HTML5 for Java10 while protecting the build in Java < 10
- Semi-unrelated, but the jcenter repositories went 404 on android.arch.common-1.0.0.jar which blew up the Travis build, and the whole internet said put the google repositories before jcenter, so I did that and it works
=> Safely use HTML 5 for Java10; use google repos first

build.gradle
Two changes, both tiny, as separate commits (ideally following your preference):
1- using google repo before jcenter is still necessary but [my previous fix](https://github.com/ankidroid/Anki-Android/commit/a42492795ae88b833d4f241a35a1a20e36edd159#diff-c197962302397baf3a4cc36463dce5ea) was unnecessarily verbose, this implementation is the current way
2- Android Studio updated and that brings a gradle plugin update
=> gradle plugin 3.1.3 update / google repo usage via shortcut

AnkiDroid/src/test/java/com/wildplot/android/rendering/PieChartParameterizedTest.java, AnkiDroid/src/test/java/com/wildplot/android/rendering/PieChartTest.java
I rely on unit tests heavily when I code, and the PieChartParameterizedTest was throwing NPEs fairly frequently
#4873 
After research I think the problem was just that the class wasn't initializing correctly
The previous behavior (NPEs) was observable with AndroidStudio current (as of now) on MacOS current, with repeated executions of "tests in com." to trigger unit test execution. I got an NPE in the PieChart test about 50% of the time, now I never get it
I learned that our unit test infrastructure is very out of date!
=> Init mocks prior to using them to avoid NPEs, Fixes #4873

AnkiDroid/build.gradle, AnkiDroid/src/test/java/com/wildplot/android/rendering/FloatMatcher.java, AnkiDroid/src/test/java/com/wildplot/android/rendering/PieChartParameterizedTest.java, AnkiDroid/src/test/java/com/wildplot/android/rendering/PieChartTest.java
- Junit 4 -> Junit 5 using Vintage Engine
- Mockito -> 1.10.x -> 2.18.x
- Powermock 1.6.x -> Powermock 2.0.x
I think in general if you can upgrade dependencies without too much pain, you should and this wasn't that bad - I implemented this while working on #4873 
This change causes no change in behavior that I can detect, all tests (unit or connected) continue to work after the change
I ran unit tests and connected tests, and my travis context ran things on my local branch and passed
I looked at the project pages and maven repositories for all of our test infrastructure dependencies as well as their getting started pages, and moved everything up to the most current possible stable versions with the exception of powermock - have to use the 2.0 beta there in order to have compatibility with …
=> Upgrade test dependencies and migrate tests to new APIs

.gitignore, .idea/codeStyles/Project.xml, .idea/codeStyles/codeStyleConfig.xml
Someone mentioned having a formatter you could import for code conventions would be good. This implements the conventions by default
Issue #4872 
This solution takes the approach that sharing the conventions by default is a good idea rather than relying on people to import them.
So I installed the IDEA checkstyle plugin since it's new versions allow you to use the plugin to import a checkstyle config to the main Android Studio formatting settings.
Then the style itself was imported to Android Studio from  the file docs/code_conventions/eclipse/ankidroid.checkstyle.xml,
with the only alterations being to implement blank line rules from
/docs/code_conventions/AnkiDroid_code_conventions.html since those weren't really in place but can be added to Android Studio
I re-formatted a few files to …
=> Allow Android Studio formatting settings in git as exception, Fixes #4872

.travis.yml
1- We support Android API >= 15, but we're only CI testing API 16 at the moment.
2- I did a PR for us from Gradle 3.1.1 to 3.1.2, and Travis CI passed but it turns out Gradle 3.1.2 ***could have caused the app to fail on install*** on API 21 and API 22! The exact sort of thing running Travis might help with
Now, Gradle 3.1.3 (which we moved to just now) fixed this specific gradle issue, but I do not want any of my PRs to be responsible for install failures on releases if I can help it, and doing CI on all possible levels seems sensible
So this does as full of an API matrix on Travis as I was able to implement, while also moving us towards the current-recommended "sdkmanager" and "avdmanager" tools, vs the deprecated "android" tool
This takes our CI success report time from 6 minutes …
=> Use more API levels in CI, move to sdkmanager/avdmanager

AnkiDroid/build.gradle, AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java, AnkiDroid/src/test/java/com/ichi2/anki/ProductionCrashReportingTreeTest.java
Our Timber dependency was very old, and newer ones allow support for logging during Unit tests, which would be useful
#4863 
Between direct observation and conversation here, assumed three requirements for the production logger 
- verbose and debug should be ignored
- info gets a fixed log tag
- warn+error get fixed tag + logging classname prepended to message
I then took the default implementation proposed by the current Timber release documentation, as well as the DebugTree classname discovery implementation, and implemented it here to match the three requirements
I looked at live logcat snippets of production releases and debug releases, then made sure with visual inspection they looked similar.
I also implemented a unit test to exercise the new production logger and verify the three …
=> Feature 4863/timber upgrade

api/src/main/java/com/ichi2/anki/api/AddContentApi.java, api/src/main/java/com/ichi2/anki/api/Utils.java, build.gradle
I've been working on the API to stop users from crashing - part of it is the API being clear about error return values and that's implemented here
Also the compiler kept warning me about deprecation and I figured out how to expose that, then investigated the source, noted the problem and suppressed the warning since it isn't important to fix now
#4617 
Better docs should help in conjunction with a more defensive sample app
purely javadoc updates and comments
Finding deprecation is actually difficult. IDEA-FindBugs and IDEA-Checkstyle both failed to do it for me, even with API levels moved up past the deprecation tag showing up. Adding compiler options was the only way to do it that I found
=> Api docs and deprecation

.travis.yml, AnkiDroid/build.gradle, AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/CollectionTest.java, AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/ContentProviderTest.java, AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/libanki/ImportTest.java, AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/libanki/MediaTest.java, AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/libanki/RetryRule.java
It's difficult to test Android things without good test support, and the new ATSL helps a lot... also the new test orchestrator will allow for coverage reports shortly which I have queued in a branch
Fixes automated testing on API>23 out of the box. API24 works in Travis now
This is building towards a fix for #4200 and #4883 
I have a [second branch queued with a working / tested ACRA upgrade](https://github.com/mikehardy/Anki-Android/commits/acra-upgrade) to API>=26 compatible 4.11 but in order to test it I needed the ATSL
- Add ATSL (Android Test Support Library, new from google)
- Upgrade JUnit3+AndroidTestCase to JUnit4 + Annotations
- Fix test permission errors w/@GrantPermissionRule from ATSL!
- …
=> Upgrade instrumented tests to Junit4 / Fix permission errors

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/res/layout/card_item_browser.xml
- [ X] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ X] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ X] You have commented your code, particularly in hard-to-understand areas
- [ X] You have performed a self-review of your own code
So far, in multi-select mode, the cell gets larger when clicked because it needs additional horizontal space for the checkbox. In this PR, this is accommodated by having larger horizontal margins first and then decreasing those margins when transitioning to multi-select mode. Now the cells only jump minimally.
See …
=> Multi-select-mode: prevent cells from jumping out of view

AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.java
A good portion of our acralyzer reports are from a widget using an API15 call on lower than API15 devices.
If we intend to support these devices with multiple APKs I assume they'll be built off the 2.8 series since 2.9 removes support for API<15
#4848 incidentally
[Acralyzer report](https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/823ad9c8-c18e-4ec4-8e18-908aa59eb45c)
This wraps that call in an SDK_VERSION check
Unit and integration tests, plus on API<15 devices I added the widget and it crashed, then when I made this change, it worked. 
Note to test in emulators lower than API 16 (I think) now you need an old tools version (25.0.2 works) or the emulators don’t mount the sdcard. …
=> Fix incorrect API 15 usage widget crash + translation compile fix

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/res/layout/card_item_browser.xml
In the current master branch there's a problem where the selected item position in the card browser jumps around when entering / exiting multi-select mode due to the resizing of the rows. This issue was introduced in #4839 and partially addressed in #4895 by @vrublack, but I found that approach was unreliable.
Reverts #4895 and takes a different approach to solving the problem
When multi-select mode is first entered we find the vertical position of the selected view before the layout is updated, and then post a call to the event queue to scroll back to that same position with a small delay to allow the layout to get updated. We do the same thing on exiting multi-select mode if the originally selected view is still visible.
I tested entering and exiting multiselect mode in the API 27 pixel …
=> Browser scroll position

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
'mAnswerField' was displayed on cards without text input when hitting undo from a card with text input, but shouldn't do this anymore
#4820 
mAnswerField was never set back to invisible through AbstractFlashcardViewer.displayCardQuestion(). This was where I could find that mAnswerField was being set during the undo process so I went ahead and used the existing check for whether the card wanted an answer field to also determine if it didn't want an answer field.
Tested on a Nexus 5X API 27 virtual device. 
Reproduction steps are the same as in #4820 only the expected outcome (mAnswerField is not displayed) occurs now. Those steps are pasted below for convenience.
Reproduction Steps
Create a card without text input in the answer field …
=> Issue 4820

AnkiDroid/build.gradle, build.gradle, gradle/wrapper/gradle-wrapper.properties
Slowly but surely getting our dependencies up to date
Nothing logged, these were all minor.
I've started testing ["dependabot"](https://dependabot.com/) and it automatically generates [pull requests for dependency bumps](https://github.com/mikehardy/Anki-Android/pulls) with ability to mute/ignore/rebase etc from the PR comments which is pretty slick. I packaged a bunch of dependency bumps together as a single PR here, then once we're mostly clear we should integrate it I think
Note the beta android gradle plugin is needed in combo with gradle 4.9,
but it should not have any change on compilation artifacts until R8 is enabled by default in Android Studio 3.3. It did move Java8 de-sugaring from post-compile to post-dex but that only …
=> Update dependencies that required no code changes

AnkiDroid/build.gradle, AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/ACRATest.java, AnkiDroid/src/main/AndroidManifest.xml, AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/AnkiDroidCrashReportDialog.java
ACRA 4.6 was noted to have a problem in #4200
ACRA 4.11 or 5.x is necessary to move to API>=26 as in #4883 
I upgraded the library and our usage of it according to the documentation.
First I went to 4.11 which enforced a much more rigorous use of configuration and is most of the way to 5.x
Then I went to 5.x which separates the ACRA functionality into multiple modules. This requires Java 1.8 but it's still okay with minSdkVersion as low as 14 
The commit messages for each step overview the changes. It's a bit spaghetti unfortunately.
I made an instrumented test that verifies our 4 different configs
- debug
- production but disabled
- production and ask
- production and auto-send
I also set up a test acralyzer instance on cloudant and …
=> ACRA upgrade to 5.1.3

AnkiDroid/build.gradle, AnkiDroid/src/main/java/com/ichi2/libanki/DB.java
Upgrade requery to current version
Fixes #4899 
Requery could not by upgraded as is. They removed a flag in 3.23.1 which they indicate did not matter as it was a no-op prior, and they altered their dependency handling to conform with new gradle requirements in 3.24.0, which should not matter but I have an open question to them:
https://github.com/requery/sqlite-android/issues/71
I've run this through local tests, including manual testing on an emulator with a full sync, and all the usage scenarios I could think (including searching in the card browser and advanced statistics)
The requery issue link above has all the interesting information
=> Requery upgrade

.travis.yml, AnkiDroid/build.gradle, build.gradle
Automate code analysis for pull requests, and integrate the results in an actionable way
Fixes #4914 (codacy integration)
Fixes #3056 (coverity integration, by obsoletion)
Fixes #4588 (reporting valid lint warnings, by obsoletion)
Fixes #2254 (lint continunous integration, by obsoletion)
This PR implements a jacoco report, then generates that report in Travis CI for all APIs and uploads them all to the Codacy servers in a way that Codacy can aggregate them correctly, while using our local checkstyle.
I did the major steps in separate commits but I can squash them if desired.
I tried to do this using Travis resources efficiently by only doing android SDK installs / emulator starts when necessary through the use of Travis build stages …
=> Coverage reports / Codacy integration

AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/NotificationChannelTest.java, AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/NotificationChannels.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DialogHandler.java, AnkiDroid/src/main/java/com/ichi2/anki/services/NotificationService.java, AnkiDroid/src/main/java/com/ichi2/anki/services/ReminderService.java, AnkiDroid/src/main/java/com/ichi2/async/Connection.java, AnkiDroid/src/main/java/com/ichi2/compat/Compat.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV15.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.java, AnkiDroid/src/main/res/values/02-strings.xml
API26 blocks notifications that aren't using notification channels
-  Fixes #4884 
-  **This may require re-translation in 02-strings.xml::reminder_text** The per-deck reminders trigger for total reviews but the text was for new cards - a semantic confusion. I aligned it by altering the text to match the trigger so you don't get "0 new card due" or "1 new cards due", which were possible previously. 
-  Fixes a crash on login on Android 6.0+ where WAKE_LOCK permission needed to be requested even though it is non-dangerous and in the manifest
-  Added a new CompatV26 class that handles channel creation
-  Setup channels on app startup (create, or update translations)
-  Send the notifications to the right channel id
-  Uses translated …
=> Implement API26 Notification Channels

AnkiDroid/build.gradle, AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/ACRATest.java
API28 will silently fail dark-greylisted API usage, or throw exceptions (#4910)
Our core error-reporting library used one so if anyone installed AnkiDroid on API28 we'd never get crash reports
This at least fixes that, though we have other API28 greylist usage as noted in #4910 
I cleaned up the ACRATest after seeing what ACRA re-init actually allowed, then ran tests on emulators. Dependabot already submitted a PR for this on my fork and it all built/tested cleanly in all APIs
=> Update ACRA to 5.2.0, starts API28 work (#4910)

AnkiDroid/build.gradle
Using support libs 27.1.x causes cards to not display after screen off
https://developer.android.com/topic/libraries/support-library/revisions#27-1-0
Hopefully I'll figure out why shortly, but in the meantime, the issue is resolved by downgrading the libs to 27.0.x and making sure ACRA doesn't pull them again via dependency isolation in the gradle build.
=> Revert support libs to 27.0.x, Fixes #4938

AnkiDroid/build.gradle, AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/CollectionTest.java, AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/ContentProviderTest.java, AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/Shared.java, AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/libanki/ImportTest.java, AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/libanki/MediaTest.java, tools/quality-check/codacy-ankidroid.sh, tools/quality-check/old_emulator.sh, tools/quality-check/start_all_emulators.sh, tools/quality-check/stop_all_emulators.sh
CI is currently failing because test dependencies are resolving to conflicting support libraries, this isolates the support library dependencies
This also fixes all AndroidStudio deprecation and lint on the test packages, and adds my local emulator fleet management scripts as well as my local codacy checker
All the test tools are documents in the scripts, the gradle dep isolation is standard
I used emulators API15-28 to verify that jacocoTestReport runs (with no test class deprecation during compile or lint in AndroidStudio), with my emulator fleet tools (i.e., after running start_all_emulators.sh they are all up, then a single ./gradlew clean jacocoTestReport runs it on ALL of them at once, then stop_all_emulators.sh cleans up - you …
=> Isolate support from test / remove test deprecation+lint / emulator fleet mgmt

AnkiDroid/src/main/AndroidManifest.xml
Just saw this over in ACRA-land, and it explains why I was suddenly seeing WAKE_LOCK permission failures. I think it's good I was requesting the permission where I added it, but this fixes up the manifest
https://github.com/ACRA/acra/wiki/Troubleshooting-Guide#wake_lock
```
ACRA is using android.permission.WAKE_LOCK with maxSdkVersion="25". If you need this 
permission also in higher versions, you need to use the following declaration:
<uses-permission android:name="android.permission.WAKE_LOCK" tools:node="replace"/>
```
=> ACRA defines WAKE_LOCK w/maxSdkVersion, replace

AnkiDroid/build.gradle
I noticed that our APK size had ballooned in the latest alphas and I thought it might be my work. Turns out it was - the requery upgrade pulled in 3 more ABIs for their JNI library. Further investigation showed that we could remove not just those but 2 more ABIs that we'd had since we converted to requery, shrinking the APK from the 8.5MB or so 2.8.x had to maybe 7.3MB
Nothing logged, was just something I noticed and after being in the terrible-bandwidth jungles of Belize I'm sensitive to bandwidth needs
I evaluated device support metrics from Google Play Console, and a highly-regarded article on trimming APK size, and came up with a trim of 3MB from current, and 1MB from previous stable:
proposed change, supported 9906 devices, …
=> Reduce APK size by filtering ABIs

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
This is almost a one-liner, but I was testing split-window mode and when I left it apparently the WebView container was already gone when we tried to access it. Adding a null check is a trivial fix 
The stack has moved a little since this was from 2.8.4 on my main install on the phone
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/c31f1217-5928-41b1-aa45-7f546d1da031
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.removeAllViews()' on a null object reference
at com.ichi2.anki.AbstractFlashcardViewer.onDestroy(AbstractFlashcardViewer.java:963)
at android.app.Activity.performDestroy(Activity.java:7259)
at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1266)
at …
=> Check for null before calling View.removeAllViews()

AnkiDroid/build.gradle, AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/ACRATest.java, AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
Limits crash reports of the same stack trace to 1 per device per 7 day period. Should de-clutter things a lot and make the database more useful
#4949 
I just declared the limiter dependency and annotated with parameters as agreed during discussion on the linked issue
I did a local build on emulators and triggered a known crash then examined the contents of the device to make sure the limiter was working, and looked at the debug acralyzer to investigate it there as well. I only got one report on repeated triggers with reporting configured to send. Seems to work
Note that this will not pass jacocoTestReport as submitted, it passed locally until I reverted the gradle dependency isolation changes that are part of #4950 - It was either …
=> Limit same stack to 1 per device, Fixes #4949

AnkiDroid/build.gradle, tools/quality-check/start_all_emulators.sh
Even if unimportant in the grand scheme, would be completely trivial if dependabot was integrated ;-)
Small change to emulator fleet startup script to make it possible to skip the timeout I inserted while using start/jacocoTestReport/stop in an automated loop. This makes it possible to start 10 emulators in about 10 seconds on my machine, very useful to confirm I haven't broken anything in the existing test suite
=> Junit point release

AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.java, AnkiDroid/src/main/java/com/ichi2/widget/WidgetStatus.java
In the API26 background service change I introduced an error where I was using the wrong context to get resources for localization, causing the widget to crash consistently
Fixes #4960 introduced by #4928
Use the resources from the context passed into the call
I was able to reproduce this immediately on an emulator when adding the widget, and verify the fix immediately. Luckily it was a small error
=> Fix widget crash from API26 forward port / Use correct context in getResources()

.github/issue_template.md, .github/pull_request_template.md
These are primarily to help first-time reporters/contributors, and I find they get in the way when I'm creating issues/prs. Moving to the bottom seems like a reasonable compromise to me.
=> Move the checklists in the templates to the bottom

AnkiDroid/build.gradle, AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/async/CollectionLoader.java
Fixes #4938 and is related to #4937 and #4939
Supersedes #4950
The new lifecycle support library makes it pretty easy to build lifecycle aware components, and Loaders have now been deprecated in favor of that library. So instead of using an `AsyncTaskLoader` as the base class, I've used an `AsyncTask` and added some simple logic to ensure that `onCollectionLoaded()` is not called when the `Activity` is stopped.
I was originally considering to use the new `ViewModels` plus `LiveData` approach, but quickly realized that's overkill for the simple task we're trying to achieve here.
In the future I think we should probably refactor the guts of this into a more general `LifecycleAwareAsyncTask` and use that more liberally in our code base.
I did some basic sanity checks on the simulator with a …
=> Use a lifecycle aware async task instead of a loader to open collection

AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java
The new behavior of CollectionLoader is to immediately call `onCollectionLoaded()` if the collection is already open, so `startLoadingCollection()` *must* be called after all the initialization is complete, ideally at the end of `onCreate()`. Also we need to call `super.onCollectionLoaded()` in order for the progress bar to be cleared.
Fixes #4975
=> Make sure startLoadingCollection() is called at end of onCreate

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
The DeckPicker options menu wasn't being initialized correctly
during the first run of the application after install when all
the dialogs popped up.
The correct thing to do is invalidate it, the system will re-init
https://stackoverflow.com/a/41631514/9910298
I started my full-API fleet of emulators and manually did the fresh-install flow and n+1 flow on DeckPicker and it all works now
=> Ask to reinit options menu after permissions, Fixes #4951

AnkiDroid/src/main/java/com/ichi2/libanki/importer/AnkiPackageImporter.java
Importing media collections is fraught because they become corrupt in so many ways. This fixes one of the ways
Fixes #4978 
Calling code handles null return values from IOExceptions (indicating possibly serious corruption) already and silently moves on
Called library method will immediately throw NPE if the requested
entry name doesn't exist, so any media database / file de-synchronization
blocks us from importing otherwise. 
Catching that NPE alongside the IOException allows us to successfully import
exports that have media db / file discrepancies
I successfully recovered a users database (attached to the issue as a test case), and I've been able to import databases I've manually corrupted but I can't reproduce the export of corruption (even when deleting media from sdcard and exporting …
=> Handle all ZipEntry exceptions not just IO, Fixes #4978

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/AnkiDroidCrashReportDialog.java, AnkiDroid/src/main/res/values/05-feedback.xml
Previously I've been relying on a personal collection of
crash bugs to test the crash dialog, but that's a poor testing
experience - now we have an advanced preference area to just crash
During the ACRA upgrade #4893 some branding was already broken, and
the rest was lost, when I finally saw the dialog again with
fresh eyes on my son's tablet it was terrible so this puts the 
icon and title where they belong
No issue logged, just fixed it
This adds a beautiful icon and nice text
I am getting better at UI things so I added an advanced preference to trigger crashes, in debug mode only. I tested the pref was disabled in release builds and then tested the crash - debug/release + pre/post images attached
It does add one Codacy warning because I throw RuntimeException in the trigger
_Please, go …
=> Brand crash dialog, add crash trigger if debug

.travis.yml, AnkiDroid/build.gradle, AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/ActivityTestUI.java, AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/Shared.java, AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java, tools/quality-check/adb_shell_all_emulators.sh, tools/quality-check/disable_animation_all_emulators.sh
We have been crashing on Activity startup a lot, this adds our first UI test that would have caught 2 of the recent crashes, and adds a fix for one of the crashes
Fixes #4977 
Adds Robolectric test, that just clicks into each activity once by View ids so it should not be brittle but it would have caught two recent crashes. We can delete it later if it sucks, but it works on my emulator fleet. I'm filtering it out of Travis though because the flakiness there would be unbearable.
Other than that it just adds a null check but lest you think I was lazy ;-), I checked 27.0.2 to 27.1.1, it was in 27.0.2 also, and I verified that no other Activities seemed to be doing unsafe onCreate()/onCollectionLoaded() access of View items inflated in onCreateOptionsMenu(). So I think this is really the fix …
=> onCreateOptionsMenu() lifecycle crash / UI testing

AnkiDroid/src/main/assets/flashcard.css, AnkiDroid/src/main/assets/scripts/card.js, AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
#4941 made me think we were navigating to data urls and on future versions of Chrome AnkiDroid would simply stop reviewing completely, so I went to investigate
We do support passing a data url through, but we don't use one ourselves. Altering that would alter decks out in the wild so I want to leave that be. So I think we're safe
Edit - dropped this part of the patch per discussion below: That said, we were emitting malformed HTML/CSS so I patched that up while maintaining backwards compatibility with the CardContentProvider.
There is still something going on with some other issues with fonts and memory usage in Chrome so this patch also includes better debugging support
Fixes #4941 - with the debugging support added it's possible to see how the WebView is working and look at the HTML …
=> Add HTML debug aides

AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/ContentProviderTest.java, AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java, api/src/main/java/com/ichi2/anki/FlashCardsContract.java
Allow burying or suspending cards from the API, using the **ReviewInfo** / **SCHEDULE** endpoint.
#4986
Add support for bury/suspend in the **ReviewInfo** / **SCHEDULE** endpoint, using two new write-only fields.
- Added test **ContentProviderTest.testBuryCard()**
- Added test **ContentProviderTest.testSuspendCard()**
- Added test **ContentProviderTest.testUpdateTags()**. this functionality existed in the API previously but was undocumented/untested.
- Added another check in **ContentProviderTest.testAnswerCard()** to ensure bury/suspend support is not breaking regular card reviews.
Updated Javadoc for **FlashCardsContract**
- Example for burying/suspending a card
- Example for updating tags for a note
- Classified FLDS/TAGS fields as read-write
=> add API support for burying and suspending

.travis.yml, AnkiDroid/build.gradle, AnkiDroid/src/main/AndroidManifest.xml, AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/AnkiDroidCrashReportDialog.java, build.gradle, gradle/wrapper/gradle-wrapper.properties
The ACRA report database is very difficult to get signal out of because of repeated exceptions as repeated exceptions clutter it up
Fixes #4949 on API<15 devices for long term support
This limits the same exception to being sent once from each device per 7 day period (we could increase that if it is still too noisy)
I pulled the hotfix-2.8.5 branch, cherry-picked the ACRA upgrade commit #4893 - downgraded that to 5.0.2 (last ACRA upgrade that worked for API<9, and we were API<10 in the 2.8 branch), then added the Limiter configuration
I booted that up in an API15 emulator and used the known crash bug of turning off all background processes and killing activities immediately while you edit card templates, and checked the debug …
=> Cherry-pick ACRA upgrade (downgraded to 5.0.2) and implement Limiter

AnkiDroid/src/main/AndroidManifest.xml, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java
2.9alpha37 was better than 36 on the crash front but the Play Console robot army still found something in the multimedia card / pronunciation interaction. This fixes that crash and also fixes a regression where on API28 pronunciation downloads fail completely because of HTTP cleartext restrictions
Fixes #5002 
The Multimedia field editor defaults to a text state which exposes the record audio action bar button. After loading the pronunciation audio it needed to re-initialize itself as audio so the action bar buttons showed text and image. I just hooked for an action bar reinit when child Activities of multimedia edit return
For the HTTP cleartext thing I added a manifest entry per API docs
Test the reproduction scenario on API27 and API28 emulators, as well as all paths I could think of …
=> Fix Beolingus on API28 / Fix crash after downloading pronunciation

AnkiDroid/build.gradle
Should have been able to remove the ABI filter but requery packaging had a problem:
https://github.com/requery/sqlite-android/issues/78
=> Update requery/sqlite deps

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java
PR #5004 was complaining of an empty if:
https://github.com/ankidroid/Anki-Android/pull/5004/files#diff-097a1b08d60abe4a789cc6394b0dbf27L173
I thought it was collapsible but missed that it was two different objects - this first if
was needed but could return immediately. If you ignore that it was cancelled you'll take a NullPointerException
when you try to access the non-existent image
Noticed this while testing #5005 - went to create some unused media and crashed as I clicked around...
=> Don't ignore ResultCode on image selection

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/Note.java
Fix a crash where CardTemplateEditor corrupts Note.model.templates leaving a reference to a non-existent template in the Note
#5011 
Commit 1 triggers database integrity check with next build because this bug generated persistent corruption that integrity check does fix
Commit 2 adds Logging and ACRA send if integrity check finds problems so we can track that. Only the first 10 (if there are that many) so it's not overwhelming amounts of data to transmit though (just in case)
Commit 3 is the real fix:
CardTemplateEditor edits the model in the database directly, persisting speculative edits even before user clicks save. If user discards a template addition or subtraction, CardTemplateEditor saves a pre-edit backup copy of the model before returning.
Problem is the model.templates state …
=> Reload Note.model from db when returning to NoteEditor from CardTemplateEditor

AnkiDroid/build.gradle, AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/ACRATest.java, AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/CollectionTest.java, AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/ContentProviderTest.java, AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/NotificationChannelTest.java, AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/libanki/HttpTest.java, AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/libanki/ImportTest.java, AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/libanki/MediaTest.java, AnkiDroid/src/androidTest/java/com/ichi2/anki/uitests/ActivityTestUI.java, AnkiDroid/src/androidTest/java/com/ichi2/anki/uitests/CardBrowserPreviewUI.java, build.gradle
There was no avoiding using alpha dependencies for tests on the move to androidx but they went beta just now which freezes their APIs I believe. Some of the APIs moved too, so this mops up that deprecation and everything still works after
deprecation warnings / unstable-ish dependencies
Followed API docs to migrate to new APIs, dependabot showed me that it was time
Automated testing harness still works (with all UI tests working well on API28 emulator)
=> Migrate to beta test APIs from alpha

AnkiDroid/src/main/java/com/ichi2/libanki/Sched.java
There was an infinite recursion crash in Play Console here
No idea why but recursion is always potentially dangerous. I'm logging the contents of the deck name (the recursion break condition) so we could pinpoint it next time maybe
=> Add log message in case where recursion crash can happen

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
If you use the text search intent from the system to reach the card browser, you get stuck there because the intent stays with the activity for it's entire life and we just keep re-checking it. This fixes that so the card browser behaves normally after the initial search
Fixes #5016 
The search mechanism is simple enough, we just check Intent.getAction() and do a search on the included term(s) if it was a search action. To make sure this isn't an infinite loop, I set the Intent action to DEFAULT after initial search
Tested on the same emulators I used to reproduce in the first instance
=> Clear search intent info after retrieving it so we aren't stuck in a loop

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
(the first time I attempted this PR I temporarily removed the one commit and that made github thing it was all merged, so it closed it - re-trying)
If you have enough decks your deck picker scrolls, you'll notice it auto-refreshes even if you fling it to the top, which is not the design idiom used by Chrome or other apps - they only do pull to refresh when idle at the top. This disables pull to refresh unless you are idle at the top of the deck picker
Fixes #4495 
I just add an onScrollListener to the RecyclerView, if the layout manager says we are the top, I enable pull to refresh. In all other cases pull to refresh is disabled.
Flinging around the card browser etc on emulators
We are not the only people that want to do this, that's for sure. StackOverflow is full of this stuff
_Please, …
=> Disable pull-to-refresh if not at top

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/res/values/01-core.xml
Wasn't implemented completely at first so the translation was deleted:
https://github.com/ankidroid/Anki-Android/commit/b6fc27cc0a2d5be358eb6380f9b9e34255e052ca#diff-4bdcb709c17a2fb93c9078605b87b3a7
Fixes #4497 	
I tested this in an emulator, it was trivial and worked as expected
=> Get cloze help from translated resources, Fixes #4497

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
Cherry-pick of the same fix, re-shaped for Java 1.7, from master. Just listens to scroll events, and only enables the swipe layout refresh listener if we are at the top of the recycler view. This prevents syncs when you just fling to the top - you have to do it on purpose. Still easy to do, just not easy to false-trigger.
Fixes #4495 on 2.8 branch
I tested this on an API15 and API28 emulator, behaved the same as master for this use case
=> Disable pull-to-refresh if not at top, Fixes #4495

AnkiDroid/build.gradle
Generally keeping up with upstream here, but this release fixes the upstream bug with MIPs ABI removal that caused us to need an ABI filter - https://github.com/requery/sqlite-android/issues/78
Not an issue, but cleaner now...
=> Update to requery-3.25.2, can remove ABI filter now

AnkiDroid/build.gradle, AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/ACRATest.java, AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/CollectionTest.java, AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/ContentProviderTest.java, AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/NotificationChannelTest.java, AnkiDroid/src/androidTest/java/com/ichi2/anki/uitests/ActivityTestUI.java, AnkiDroid/src/androidTest/java/com/ichi2/anki/uitests/CardBrowserPreviewUI.java
Dependabot notified me there were updates available, and this one resolves a publishing error they had with beta01 where their POMs were actually unusable. Awesome! But we have to stay on this major version as part of androidx conversion so it's nice to see it stabilize.
Affects nothing non-test
=> Update test dependencies, remove deprecated test runner

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.java, AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.java
Android provides a nice file picker for Android 4.4+ / KitKat / API19+ - this change defers to that file picker for package selection and only falls back to our internal "picker" for API<19
Fixes #4932 - the enhancement request
Obsoletes / Fixes #4834 - UI issue with regard to how to display filename
Fixes #3420 - Chromebook import/export (it works!)
3 commits - review them separately for easy review
1. I decomposed the application IntentHandler, which was already charged with ingesting unknown files with the intention of importing them, so that I could re-use all the sanity checking and processing inside it and avoid code duplication in code pathways dealing with external input
1. Then for API19+ if the user chooses to import decks I simply fire a normal file open intent, tuned for …
=> Use system deck picker for package import

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/java/com/ichi2/anki/receiver/SdCardReceiver.java
These are our top crashers in ACRA right now
Unlogged
One is just quietly going away if there's an SdCardReceiver exception on MEDIA_EJECT because the database is likely not there anymore
Another is Bundle.extras() is null in Reviewer - this is a bit more speculative, I'm not sure how that happens but we already have code to handle the case where no deck id is provided so it seems nicer to not crash
Only automated tests
Just looking in ACRA while trying to help other people with different crashes
=> Current crash fixes

AnkiDroid/build.gradle, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.java
- #5050 - app startup failure after analytics addition - really bothered me because it was triggered by a hit that went out *prior* to full initialization, which is a major no-no because it violates privacy expectations. This fixes that
- The prompt for people to enable analytics was no longer happening on upgrade, fix that too
- There is no longer a good way to test hits with 10% sampling in place, plus test hits were polluting the regular usage, this fixes that
1. The one place I had a "default opt-in" - the UsageAnalytics static member variable for opt-in - was the culprit. Switched it to false and didn't fiddle with preferences on startup which cleaned everything up and eliminated the hit during initialization and the opt-in dialog not showing. Only a 2-line change but vital
1. For …
=> Alter startup sequence for analytics, add debug mode

AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java
Most interaction with the TTS object was gated by a check for
successful initialization, but there was one interaction to set a listener
that was performed even onInit if initialization wasn't successfull, despite the API
docs indicating the init listener could be called even if the object didn't initialize
This Fixes #5067 by moving this interaction with the TTS object to a location that
is only executed if the TTS init was successful
I used an emulator and enabled TTS, it still worked after this change, so I didn't break TTS, and the change otherwise seems like a no-brainer. Code inspection shows that if AbstractFlashcardViewer.ttsInitialized() isn't called, the viewer won't interact with the ReadText (and thus TTS) object so this was the only interaction that was un-protected from a …
=> Only interact with TTS object if init was successful

AnkiDroid/build.gradle
AndroidX motion is starting to slow down and stabilize
All of the test dependencies are out of beta now, with only powermock left in RC status.
=> Test dependency updates

AnkiDroid/build.gradle, api/build.gradle, api/src/test/AndroidManifest.xml, gradle.properties
Robolectric is the present and future of android unit testing - it lets you do almost all tests you need even when they rely on logic from android.jar
4.x extends this power to resource loading so you can check different languages, devices etc to execute different test logic based on different device profiles
This PR finishes the migration to a version of Robolectric that can do that
There is one semi-interesting bit in that the test libraries are all minSdk 14 now so for tests only in the API modules we have to allow a library that is minSdk 14 as an override, since we are minSdk 8 (or something very old, I forget) in the API module
=> Robolectric to 4.0.1 - fixes bug that lets use all their new 4.x features

AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.java, AnkiDroid/src/main/java/com/ichi2/anki/web/HttpFetcher.java, AnkiDroid/src/main/java/com/ichi2/compat/Compat.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV15.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.java, AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java, AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.java, AnkiDroid/src/test/java/com/ichi2/anki/TestUtils.java, AnkiDroid/src/test/java/com/ichi2/compat/CompatDefaultTest.java, AnkiDroid/src/test/java/com/ichi2/compat/CompatV26Test.java, AnkiDroid/src/test/java/com/ichi2/libanki/UtilsTest.java
While reviewing package export using file-picker work in #5054 @timrae [mentioned using the java.nio.files.Files.copy() would be nice](https://github.com/ankidroid/Anki-Android/pull/5054#issuecomment-433613088)
That's correct and while it may just be a nice-to-have since it's for API26 and up only right now, when I looked at how file copy was done elsewhere in AnkiDroid it struck me that having a local copy implementation in 5 places wasn't a great idea, and we may be missing performance due to inconsistent and small buffers
So this PR centralizes file copy logic, and uses java.nio.files.Files.copy where the API supports it
Nothing logged, but #5054 will depend on it now
The commits should be viewed individually to best reason about the changes, I think
1.  Implement central file copy …
=> File copy refactor

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerExportCompleteDialog.java, AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.java, AnkiDroid/src/main/res/values/02-strings.xml
File this under "no good deed goes unpunished" ;-)
When I converted the errorMessage return from handleFileImport to null I missed a case returns "" instead of null, causing spurious invalid apkg dialogs to pop up even though importing worked perfectly.
Then when I tested it on Chromebook I noticed that import was perfect (except the popups) but export doesn't work because there are no handlers, we need a SAF export too.
Fixes #3420 - this handles chromebook export well now
It solves the errorMessage problem for the apkg import error by fixing the last "" return
I wrote a system-picker-based exporter that follows SAF style by allowing the user to pick a file name, then we write the file out to the returned ContentProvider. I hooked the same in the export dialog. 
Definitely solves …
=> Storage Access Framework take 2 (export, and import bug fix)

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java, AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.java, AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.java, AnkiDroid/src/main/java/com/ichi2/anki/stats/OverviewStatsBuilder.java, AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java, AnkiDroid/src/main/java/com/ichi2/libanki/Stats.java
For both stats and browser, the deck spinner no longer changes the libanki current deck. Changing the libanki deck was awkward and unintuitive, and we were only doing that to avoid changing libanki (in #766).
When opening the browser for the first time, the current libanki deck is always selected. When the deck is changed via the spinner, we remember the choice and use it next time the browser is opened (as before). Now however, the choice is cleared when the app is first started or a new deck is selected from the deck picker to avoid a seemingly "random" deck getting selected. This memory of the deck id deviates somewhat from Anki Desktop, but IMO it makes sense to deviate here, since users often switch back and forward between the reviewer and the browser while reviewing. This use case …
=> Simplify rules for initially selected deck in stats and browser

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
AbstractFlashcardViewer.restorePreferences() loads a few prefs from the collection but is called from onCreate() not onCollectionLoaded(), so it's touching the database on the UI thread
I just moved the collection-touching items from the restorePreferences() call to a collection-prefs-specific method I call from onCollectionLoaded()
=> Load prefs (which uses Col) post-colIsOpen()

AnkiDroid/build.gradle
The SLF4J-Timber is an upstream fix from me for dependencies I brought in with analytics
Powermock is just slowly working towards real 2.x release
Appcompat bumped yesterday too but there are no release notes available to see why
Intention is to squash merge this but this is sort of a test of my dependabot workflow
=> Dependency updates (SLF4J-Timber, Powermock, Appcompat)

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/res/values/10-preferences.xml, AnkiDroid/src/main/res/xml/preferences_advanced.xml
Fixes #5123 by taking the work from #4979 and making it visible as an
advanced preference instead of as a BuildConfig.DEBUG toggle, this means
the general userbase can debug their own HTML/Javascript items if they want
=> Expose HTML/JS debugging aides in advanced prefs

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
In this commit https://github.com/ankidroid/Anki-Android/commit/9a04d086ee5b9ee83889d03ce9d0cd6bdf69ae8f#diff-f50a1149d9cb92269cbf94c417602c5cL21
...we moved to the "new" framework item decorator that wasn't available when
our custom implementation was written
But during the conversion I didn't correctly set the drawable style, this sets the style
as it was prior
Should Fix #4942
_Links to blog posts, patterns, libraries or addons used …
=> Use divider style attributes for deck item decorator

AnkiDroid/src/main/res/values/02-strings.xml, AnkiDroid/src/main/res/values/10-preferences.xml, AnkiDroid/src/main/res/xml/deck_options.xml
Fixes #4547 by grouping the preference items, and relabeling the context menu entry
Prepared as closely as possible to spec requested here https://github.com/ankidroid/Anki-Android/issues/4547#issuecomment-440807897
Here's what it looks like on an API28 emulator 
(deleted obsolete screenshot - updated version below)
=> Disambiguate deck/deck-group labeling for deck options

.travis.yml, AnkiDroid/build.gradle, api/build.gradle, build.gradle, gradle.properties
- de-couple api + AnkiDroid by making sure all evaluation may be done separately
- fork and incremental compile
- scale concurrent tests by CPU count, mindful of containerization
All of these tested to have only a small positive impact on CI or old/small machines (my 4-core MacBook Pro and 2-core MacBook Air) but on my main dev machine (6 fast cores) this is a 30% speedup that will only grow as we add heavier tests (like Robolectric stuff now that #5103 is in)
There was one recommended optimization that didn't pan out and hammered small machines - setting the heap big enough to dex in process - but other than this is the full suite of recommended gradle optimizations
I will also note that I've worked a lot in the gradle files adding build system features, and while I love the features, …
=> Implement standard gradle build/test optimizations

AnkiDroid/src/main/java/com/ichi2/compat/CompatV15.java, AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java, AnkiDroid/src/test/java/com/ichi2/libanki/UtilsTest.java
Turns out file copy logic was duplicated in 6 places, not just the 5
that I saw in #5093
I noticed this while doing my periodic sweep on Play Console crashes and chasing a Zip import error
This uses the new centralized logic from the #5093 PR while converting
some of it to "try-with-resources" which android back-ported down to API15 even
so allows for much cleaner code while still cleaning up streams/files on exception
Since this touched new code (libanki.Utils) vs the previous PR I added
test coverage to make sure I hadn't done anything stupid.
Also, because the try-with-resources backport uses some dark magic, I wanted to be sure, so I fired up an API15 emulator with valid sdcard mounted (difficult in itself these days), and synced a test deck with media to make sure I hit a code path …
=> Use centralized file copy logic in Utils, extends #5093

AnkiDroid/src/main/java/com/ichi2/utils/VersionUtils.java
I know just catching null pointers isn't the solution, but I can't
figure out how this code is causing a crash, so I'm logging the
object lookup chain parts then logging the NullPointerException that
is our current top crash on Play Console that I haven't fixed yet
=> Catch common Play Console crash, logging for root cause

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/java/com/ichi2/libanki/Card.java, AnkiDroid/src/main/res/values/01-core.xml
These are various CardTemplateEditor fixes, including one crash bug on returning from CardTemplateEditor if the user deleted the template that generated the card the user was on in NoteEditor.
Does not fix the main CardTemplateEditor problem, but that fix will be based off this
1.  add better message-passing communication between the three of NoteEditor, DeckTask, and CardTemplateEditor - this lets them communicate the current card and the action being taken amongst themselves
1.  from NoteEditor, when you go to CardTemplateEditor, it sends the current card now so the right tab is focused (improvement)
1.  in NoteEditor, if we return from a template add, we just reload and go. If we come from a template delete we see if it was the card we were on and if it was we snackbar a notice and …
=> Various CardTemplateEditor fixes

AnkiDroid/build.gradle, AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/libanki/DBTest.java
Bunch of updates for androidx.test today, this incorporates them
This also includes a switch from the upstream/master 'google-analytics-java' to the Java7-compatible 'google-analytics-java7' artifact. That allows me to keep the dependency list clean upstream while still incorporating a pull request that converted the library to fully async Java8 language features that nevertheless work fine with a compatibility library (tested and confirmed working here in our code all the way to the API15 emulator)
Tested with manual usage while watching the analytics console in API18, API15 and API28 emulators - everything works fine. Automated `./gradlew clean jacocoTestReport` run against emulators for *every* API level from 15 to 28 including a Chromebook. Everything's fine.
If you want Java8 …
=> Dependency updates - androidx.test / google-analytics-java7

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
Database checks can take a long time, and the database check dialog published no indication of progress.
We're forcing a check with the next betas and stable release, so this should calm everyone when they hit it.
#5155 
I used the built in ProgressCallback / publishProgress infrastructure from DeckTask - just passing a ProgressCallback through to Collection so it could publish as it worked. The hardest part of the patch was accurately counting the amount of tasks that could happen so I could generate the correct total task count.
I contemplated doing a percentage calculation but I dislike "fake" percentages where the units are of varying duration but each is supposedly 1/100th of the work. With the current / total style it appears more arbitrary what the units are, which fits the …
=> Track and publish database check progress. Fixes #5155

AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/java/com/ichi2/ui/ConfirmationPreference.java, AnkiDroid/src/main/res/xml/preferences_advanced.xml
A single tap to do something incredibly expensive (full sync) without confirm isn't great. The current implementation even has a TODO mentioning a confirmation would be nice.
Fixes #5176 
In order to pop a dialog from preferences (which is not capable of handling dialog fragments apparently) you have to extend some other Preference superclass.
So I extended DialogPreference, following the existing AnkiDroid example of SeekBarPreference, but this time just allowing the ok or cancel buttons to have custom Runnables hooked to them.
Then I hooked a custom ok Runnable that does the full sync marking, leaving the cancel handler with the no-op implementation.
API27 emulator, but it uses the same style as SeekBarPreference and should have no problems elsewhere?
=> Show a confirmation before full sync, Fixes #5176

tools/parallel-package-release.sh
Multiple profiles (#2545) are the reason I started working on AnkiDroid, no joke.
I still haven't implemented the actual feature but I'm very interested in these working, and working acceptably for people if I can make it happen.
A fellow parent wanted more builds for more children, so this just increases the build count to 5 from 3.
Fix? Not so much. But it is the hack that keeps on working.
=> Allow two more parallel build names (5 total now)

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java
My rescheduling PR #5113 was correctly rescheduling, except the part where you have to then get a new card into the Reviewer.
This revises that work so that after performing the rescheduling actions you get a new card as well
Fixes #5167 
The AbstractFlashcardViewer already had an "answer notes" handler with all the infrastructure to display new cards or not based on DeckTask.TaskData values, and there was a "dismiss notes" handler that called in to it.
Since the rescheduling is just a special form of "dismiss notes" everything already lined up well. I just needed to take my "schedule notes" handler and chain in to the existing "dismiss notes"->"answer notes" handlers and everything worked.
I tested it on an API27 emulator only. However, it is using the existing dismiss notes …
=> Fetch new card for review after reschedule, Fixes #5167

build.gradle
Android Studio 3.3 is out, with it's new gradle plugin dependency.
This is a big download so I'll let it sit for a few days while everyone gets a chance to do it at their leisure, then I'll merge - it's only a one-line gradle file change so not hard to hold back personally if you update before this lands on master
=> Update gradle plugin from 3.2.1 to 3.3.0 (implies upgrade to Android Studio 3.3)

AnkiDroid/src/main/res/values/10-preferences.xml, AnkiDroid/src/main/res/xml/preferences_advanced.xml
As suggested in this comment, https://github.com/ankidroid/Anki-Android/pull/5203#issuecomment-457814074
this change introduces a preferences entry which when clicked, opens this page: https://github.com/ankidroid/Anki-Android/wiki/Third-Party-Apps
see prefererences entry:
https://i.imgur.com/wkCKEq0.png
see how the wiki page looks like on a mobile browser:
https://i.imgur.com/xoEAEVr.png
=> add link to third party apps which support AnkiDroid API integration inside preferences ->advanced->plugins

AnkiDroid/build.gradle, api/build.gradle, build.gradle
Updates to Robolectric and JaCoCo - this whole PR is test-related
This continues some work on #5088 as well - where testing doesn't work with JDK>8 but we're not there yet
As these are test-only changes, I'll merge if CI goes green.
=> Dependency updates 20190128 (JaCoCo and Robolectric)

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
There are user reports in issue #5205 of repeatable
production crashes related to logging failures.
The affected code is copied from a section of the logging
library that is intended for debug use, where a crash is
acceptable, but for production the logging code should never
trigger a crash on its own
@timrae - if you look at this one, I'll think you'll agree on the "log code should never crash in production" assertion. I thought about whether I should log the "we might have crashed here" event itself but I didn't want to tempt an infinite logging loop, and I didn't want to go outside of format. I chose to tag these rare occurrences with something obvious instead. And we can't avoid the inlining of the package-private method from upstream without altering how we tag (and then filter + …
=> Avoid production crash for short stack traces

AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java, AnkiDroid/src/main/java/com/ichi2/libanki/SchedV2.java
The improved behaviour of the Scheduler v2 is highly desirable, in particular because of the improved behaviour of subdecks and filtered decks.
This tackles #4905 although this only really covers adding the SchedV2 file, it doesn't cover integration with the existing code.
I've systematically gone through the differences between the two scheduler versions in the Python code and replicated each code change in the java files.
Currently there hasn't been any testing of this new file. As such, I wouldn't advise it to be used as is. I'm open for suggestions on how to test this file in isolation, although I suspect it would be better to test it by replacing the existing scheduler with it in a follow-up PR.
=> Add SchedV2.java class to support Scheduler v2

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/Consts.java, AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java, AnkiDroid/src/main/java/com/ichi2/libanki/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/SchedV2.java
Further work to satisfy #4905. Putting it up here in case anyone wants to pull the branch and give it a try.
I will continue to add to the PR as I work on it, but the core functionality is now complete. You can enable the experimental scheduler on the desktop client and AnkiDroid should now be able to sync it and use it without issue. Syncing worked fine when I bumped the version number so there are no issues with the server rejecting it like I assumed before.
I've used this today to do some reviews, including decks with subdecks and filtered decks + empty/rebuild and it all seems to work fine so far.
The only thing remaining is to add a setting to toggle it on/off and I'll consider this complete.
=> Complete SchedV2 with collection and syncing support

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
Currently it's not possible to preview all cards starting from a given index in the browser. This is pretty unintuitive.
Fixes #5220 
In the case where we have selected only one card we show all cards starting at the selected index. In the case where we have selected multiple cards, we show only those cards (this isn't supported by desktop which instead shows "please select 1 card" when multiple cards are selected).
I also switched from HashSet to LinkedHashSet for the selected card indices so that we correctly maintain insertion order, so that when multiple cards are selected for preview they show up in the correct order.
I ran through it with the emulator to check that it's all good
=> Preview fix

AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/SchedV2.java, AnkiDroid/src/main/res/values/10-preferences.xml, AnkiDroid/src/main/res/xml/preferences_advanced.xml
More work on #4905.
Adds in a scheduler toggle within AnkiDroid. Based on [desktop's preferences screen](https://github.com/dae/anki/blob/master/aqt/preferences.py#L127).
=> Add SchedV2 toggle preference

AnkiDroid/build.gradle
This minor bump altered their parallel concurrency model default and showed me I think I was doing it slightly wrong in the first place and not exploiting available parallelism 
Shaved 20% off ./gradlew jacocoUnitTestReport on a 4-core / hyperthread
MacBookPro, I imagine the results will scale well, without hurting small
machines (like CI)
_Please, go …
=> Bump Junit to 5.4.0, with opt-in concurrency

AnkiDroid/build.gradle, api/build.gradle
Just generally moving things forward while we're still in alpha
- Previous junit bump missed the api module's usage of junit (but dependabot reminded me)
- mockito-core was likewise a dependabot bump but it was lost in my series of force-pushes
as I made secondary alterations based on the minor (vs patch) change for junit
=> 20190210 dependency updates (mockito-core, junit in api module)

AnkiDroid/src/main/java/com/ichi2/anki/services/NotificationService.java, AnkiDroid/src/main/res/values/08-widget.xml
The string contained a variable plural, but did not allow for plurals, which doesn't work well in all languages even if you assume the value will be more than 2
=> Allow for plurals in widget notification, Fixes #5240

AnkiDroid/build.gradle, AnkiDroid/src/test/AndroidManifest.xml, AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java, AnkiDroid/src/test/java/com/ichi2/anki/NullCollectionReviewer.java, AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.java, AnkiDroid/src/test/java/com/ichi2/compat/CompatCopyFileTest.java, api/build.gradle, tools/quality-check/stop_all_emulators.sh
Still keeping dependencies super fresh as we're in alpha, with the help of dependabot.
The only thing of note is that the Robolectric update from 4.1 to 4.2 deprecated our style of starting Activity objects to put them under test. The solution is a net-positive as it moves to using [standard AndroidX APIs](http://robolectric.org/androidx_test/), but it required some work to make my test Activity-subclass function correctly. That work is described in the associated commit message
This was tested on the full fleet of emulators, every API from API15 to API28, locally; plus the diminished but publicly visible set of APIs supported in Travis CI
=> Dependency updates 20190219 - Robolectric, mockito, sqlite-android

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/res/menu/popupmenu_multimedia_options.xml
This pull request adds a cloze deletion button to the floating text selection menu when editing notes.
This is an alternative fix to issue #2520. The previously accepted implementation (#4606) ended up adding the functionality to the paperclip menu.
I am of course biased, but I think that this implementation has much nicer functionality and is more intuitive to access than the one that is available in the paper clip menu:
1. This one will automatically number all the cloze deletions that you add sequentially.
2. After the cloze deletion has been added, the cursor doesn't jump to the beginning of the text field.
This pull request adds cloze deletion to the floating text selection menu by implementing a custom ActionMode.Callback.
I have tested this on my OnePlus 5T running Android Pie (API …
=> Add cloze deletion to floating text selection menu

AnkiDroid/build.gradle
Hopefully this dependency will get a real/stable release before 2.9.x but the auto-service dependency actually changed maven/gradle artifact organization during an RC cycle :man_shrugging:
We must use it because using `@AutoService` annotations is the officially-supported mechanism for extending ACRA, and we extend ACRA just a little with a custom interaction so we get an analytics event hit at the same time ACRA posts to ACRAlyzer
Because correctly referencing the new artifact is in the vital crash reporting pathway I used our new advanced preferences test crash button while all using the advanced prefs dev analytics button to connect to the dev analytics instance with hit logging sampled at 100% to make sure it worked. The crash was correctly registered in analytics after this change so …
=> Dependency updates 20190327 (auto-service used by ACRA analytics interaction)

.travis.yml
Google pushed out a stable emulator version that blew up all the CIs in the world I think.
But their canary emulator works with x86_64 system images so we have access to modern emulators now, which is awesome.
I will squash merge this if it looks like it's working - it's a little speculative right now
=> Fix emulator-28.0.5 emulator regression w/canary, add modern x86_64 emulators

AnkiDroid/build.gradle
Note that CI is fully green for me on these changes as well. Not sure why #5285 is not going green at this point?
Bumps [sqlite-android](https://github.com/requery/sqlite-android) from 3.27.2 to 3.28.0.
- [Release notes](https://github.com/requery/sqlite-android/releases)
- [Changelog](https://github.com/requery/sqlite-android/blob/master/CHANGELOG.md)
- [Commits](https://github.com/requery/sqlite-android/commits)
Signed-off-by: dependabot[bot] <support@dependabot.com>
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, …
=> Bump sqlite-android from 3.27.2 to 3.28.0

AnkiDroid/build.gradle
Standard dependency update PR. These are all minor bumps.
@timrae I'm gratified that my technology choice for these (dependabot) was "correct" in the sense that Github just went ahead and bought them and is now integrating them for free everywhere.
After the build passes I'll do a squash merge on these since they're pretty verbose
=> 20190530 Dependency updates

.travis.yml, tools/upload-codacy-report.sh
Travis CI attempts to upload Codacy coverage artifacts on every successful run. Codacy requires an API token to function correctly. Since we only care about uploading these artifacts from the main repository and because it is not safe to source-control that token in a public repository, I've made a change that allows Travis to skip the upload of coverage artifacts entirely when building from a pull request.
Fixes #5080.
- Move existing upload steps from the `.travis.yml` file into a dedicated shell script.
- Leverage the `$TRAVIS_PULL_REQUEST` environment variable to conditionally upload codacy reports.
1. Fork repo
2. Link fork to Travis and Codacy
3. Create a branch and make a change
4. Push branch to repo
5. Make pull request from the new branch
Travis will begin building the branch …
=> CI: Only attempt Codacy coverage report upload if not a PR

AnkiDroid/src/main/java/com/ichi2/libanki/template/Template.java, AnkiDroid/src/test/java/com/ichi2/libanki/MathJaxClozeTest.java
Mathjax wasn't being rendered inside of cloze replacements.  I tracked it down to clozeText() which was eating the backslashes needed for \\(.
#5323 
Escapes the backslashes.
I created a test to replicate the issue.  It now passes.  The old tests still pass.
=> Fixes Mathjax inside of a cloze replacement.

.travis.yml
https://changelog.travis-ci.com/xenial-as-the-default-build-environment-99476
https://docs.travis-ci.com/user/languages/android/
=> build: travis migrates to xenial but android only works on trusty

AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java, AnkiDroid/src/main/java/com/ichi2/libanki/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/SchedV2.java
Unlimit the displayed review counts, by limiting them to 99999 instead of 1000, as per https://github.com/ankidroid/Anki-Android/issues/5197#issuecomment-452549094
Fixes #5092, #5197 and https://github.com/ankidroid/Anki-Android/issues/5322
I don't know Ankidroid's architecture, and at parts of what I've seen it sounds like it aims to be almost a transcription of the python code, so I've changed as little as possible.
Note that here I think I change the constants limiting both the study counters and the deck list counters. Potentially the slowdown caused by counting all the full deck counters will be a problem, in which case it should be possible to revert the `Sched{,V2}.java` parts of it, I think (or roll them back to “just” 9999, maybe?). This would unfix #5092 and #5197, though, but …
=> Limit the displayed review count to 99999 instead of 1000

AnkiDroid/src/main/res/xml/preferences_general.xml
Even the default in UsageAnalytics class is 'false' the default value in the preferences was set to 'true'. That means analytics was disabled by default but if the user opened the preferences screen it got automatically enabled. This commit fixes this issue by setting the default value in the preferences to 'false'.
=> Fix analytics opt in

.travis.yml
This adds support in Travis to build API 24 with Oracle JDK 11. However, at the current time, only Oracle JDK 8 is in active use on the project. As such, we allow JDK 11 builds to fail without affecting the build status for the project overall.
@mikehardy, I believe the `allow_failures` block for Android APIs `26` and `Q` are fixed (as in Travis could allow them to fail) as a result of these changes, but I left the commented out entries within that block since that isn't the target of this PR. I don't mind adding them here and now if you like, but I figured that would be best saved for another pull request.
Fixes #5115.
I manually defined an extra job that specifically targets the combination of API 24 and Oracle JDK 11, then allowed anything using `oraclejdk11` to fail.
This was tested …
=> CI: Add support for builds with Oracle JDK 11

AnkiDroid/src/main/java/com/ichi2/compat/customtabs/CustomTabActivityHelper.java
CustomTabs.warmup can crash if the underlying system WebView doesn't implement it correctly, but the CustomTabs themselves might be able to work later. So for warmup, we can eat the IllegalStateException and it should be okay (or we'll crash later, but we would have crashed anyway, so at least this way we have a chance)
Deep inspection of the problem on the related issue
#5337 
Ignore IllegalStateException on CustomTabs warmup
I haven't tested it other than to make sure test suites pass. The original issue submitter @nvbln should test this once it is included in a release.
All included on linked issue
=> make CustomTabs warmup crash non-fatal, Fixes #5337

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/AudioClipField.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/AudioField.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/AudioRecordingField.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioClipFieldController.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioRecordingFieldController.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicControllerFactory.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicTextFieldController.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/EFieldType.java, AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.java, AnkiDroid/src/main/res/menu/activity_edit_text.xml, AnkiDroid/src/main/res/menu/popupmenu_multimedia_options.xml, AnkiDroid/src/main/res/values/16-multimedia-editor.xml
This is based entirely on the work from @johndem as seen in [his pull request](https://github.com/ankidroid/Anki-Android/pull/4079)
- I rebased his work to current master, and did minimum fixups to get it to build
- I removed commented out code per suggestion on previous pull request
- I altered it to be a ACTION_GET_CONTENT per suggestion on previous pull request
- I filtered it by CATEGORY_OPENABLE so we don't get ensnared in virtual document stuff
The most important change I did was to implement the audio add using a data copy as it became clear to me that  documents from ACTION_GET_CONTENT may not be directly accessible (you can't get their file name, only a descriptor or an input stream).
This currently builds correctly and generates notes with audio files based on mp3s I have stored …
=> Add Audio Clips from from local file

AnkiDroid/build.gradle, AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java
The linked issue has a direct pointer to a reproduction via an available shared deck (thank you @weirdalsuperfan!) and some excellent sleuthing by @timrae 
The point is that the deck spinner has awful scroll behavior due to an underlying library bug, and upgrading appcompat seems to fix it, so this does the upgrade
Fixes #5262 
Upgrade appcompat to 1.1.0-beta01 and fix the 2 newly deprecated API calls in the fashion documented in the library
I installed the shared deck referenced from the linked issue https://ankiweb.net/shared/info/779483253 - and I was able to see the problem. I upgraded appcompat, and I could no longer see the problem, but `./gradlew jacocoTestReport` continued to run so I think it's okay?
_Links to blog posts, patterns, libraries or …
=> chore: forward-port to new appcompat libraries, should fix #5262

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/AudioField.java
If you add a note, then click the paperclip on either front or back field and choose attach audio clip, then just try to save, you'll crash. This fixes that
#5342 
It is okay to just back out of that screen, with a save attempt even. So just tolerate the empty field to return empty string as it was doing in other cases already
I manually reproduced the crash on emulator API28 with the same stack traces the firebase test lab found on the automated pre-launch test report for alpha72
Then I added this change and could no longer reproduce it
=> handle empty return from audio clip attach

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/res/menu/reviewer.xml, AnkiDroid/src/main/res/menu/reviewer_schedule.xml, AnkiDroid/src/main/res/values/02-strings.xml, AnkiDroid/src/main/res/values/03-dialogs.xml, AnkiDroid/src/main/res/xml/preferences_custom_buttons.xml
Reschedule works a bit different in AnkiDroid compared to Anki Desktop,
in the sense that Anki Desktop pops up a custom dialog for reschedule,
which let the user choose between rescheduling as a new card (reset progress),
or rescheduling as a review card in x days (or rather between x~y days),
whereas we avoid the custom dialog on AnkiDroid because it's quite a lot of work,
and it deviates even further from material design principles than we already do.
Here I've made a few minor changes that make the implementation of the reschedule
function in the AnkiDroid reviewer a little bit closer to the original implementation
of the reschedule function in the Anki Desktop Browser:
1. Remove the "change position" action. This is a totally separate feature from reschedule
in Anki Desktop, and I …
=> Make Reviewer reschedule function closer to Anki Desktop

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/test/AndroidManifest.xml, AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java, AnkiDroid/src/test/java/com/ichi2/anki/TestDeckPicker.java
The application has a version in the preferences right now, and uses that to decide if special activity (migrations, integrity checks etc) need to happen on startup.
It's possible that preferences are backed up and restored from Google though, leaving the current application in an inconsistent state where the database (which is not backed up with google services) may have had different things done to it than the preferences.
This adds an ankidroid version to the Collection configuration, and uses it to decide what to do on startup.
For the special case where we have no version in the database (the first time this code runs, or if there is a new collection), we assume that we need to run a database check and then set the version to current.
#5106
This builds on #5171 which was just …
=> Store a version in the database and use it for database activity on startup

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
Choose your own adventure on this one
Option 1 - keep the reporting so we can check trends, but send to analytics instead
other option will be private only #5349 
final option is "do nothing" this would preserve existing behavior: an ACRA post (which analytics is hooked to as well)
merge or reject at leisure
=> Change database corruption report channel from ACRA to analytics

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java
There is a mis-handled case if the app is not upgrading based on preferences version, but there is a database that does not have our version yet. It causes a NullPointerException and crashes on startup
This can happen if you have already done the 2.9alpha74 / database-version PR, but then do a full sync from a collection in the cloud from before the 2.9alpha74 / database-version PR
This correctly demonstrates the case with a test, and fixes it
#5343 
Code examination / reasoning showed a potential NPE during Long unboxing I hadn't thought about, and when I tried to tickle it with a new unit test I got the same stack I'm seeing in ACRA. I add a null check, and it seems to work.
Unit test failed before I fixed it, passes now
_Links to blog posts, patterns, …
=> Handle null correctly for db w/no version but stable app version

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
#5357 Purpose / Description
In L2338, the closing double quotes for the class attribute for the card type (question/answer) were missing. 
https://github.com/ankidroid/Anki-Android/issues/5356
I havent't tested it
- [x ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x ] You have commented your code, particularly in hard-to-understand areas
=> Added missing \" to close the class attribute

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, api/src/main/java/com/ichi2/anki/api/Basic2Model.java, api/src/main/java/com/ichi2/anki/api/BasicModel.java
To question and answer class tags. Removing the closing quote from the following id tag.
To Basic (Basic2) template cards' id tags
issue: #5356
=> Adds missing quotes to generated html

AnkiDroid/src/main/java/com/ichi2/libanki/sync/HttpSyncer.java
Some requests to the syncing service are malformed. It appears that Ankiweb is fine with it, but Wireshark and other tools show the issue.
Requests from HttpSyncer (and anything that inherits from it) that do not have files attached, namely full sync download requests, are missing the final MIME Multipart boundary of `--Anki-Sync-Server--`.
You can see this using Wireshark.
/meta request from before:
```--Anki-sync-boundary\r\nContent-Disposition: form-data; name="s"\r\n\r\n05daa93b\r\n--Anki-sync-boundary\r\nContent-Disposition: form-data; name="c"\r\n\r\n1\r\n--Anki-sync-boundary\r\nContent-Disposition: form-data; name="k"\r\n\r\nad83aREDACTEDee4f6c9d26\r\n--Anki-sync-boundary\r\nContent-Disposition: form-data; name="data"; filename="data"\r\nContent-Type: …
```
=> Adds missing last MIME Multipart boundary during syncing.

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.java
Sometimes typed answers include \ or $, which must be handled specially in Ankidroid due to the use of Matcher.
https://github.com/ankidroid/Anki-Android/issues/5334
Uses Matcher.quoteReplacement, which is a slick way to have Matcher work around its own restrictions.
I made some cards, tested on an emulator.  I ran the existing tests.  None seemed to touch this.   I added some tests, but they use a private method.  Please let me know if the way I did it is not  acceptable or if it is fine.
Attached is one screenshot, although the test cases test more cases than just this.
=> Fix display of $ and \ in typed answers

AnkiDroid/src/main/assets/mathjax/mathjax.css, AnkiDroid/src/main/assets/scripts/card.js, AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
Mathjax shouldn't show the markup and then rewrite it with the rendered output.  I had set this all up before, having the card template start with a hidden css class, and then removing it when mathjax is done rendering--but I forgot to include the mathjax.css file where I defined it.  This was also creating an ugly message in logcat.
https://github.com/ankidroid/Anki-Android/issues/5377
Make the hidden class actually not show things.
Verified on a device, on Mathjax and non mathjax cards.
=> Adds CSS to hide content until MathJax renders.

AnkiDroid/build.gradle, build.gradle
Most of these are standard but but the analytics/okhttp change is vital to support our remaining users on Android 4.x - I inadvertently snuck in an update to okhttp 4.x which is API19+ only - this fixes it but dropping okhttp back to 3.x-current
@milyukhin noticed it and mentioned this in #5021 (thank you Max!)
test suite in analytics package passed, and test suite here passes as well, and it's a major version of okhttp that was in use before
@timrae note that you seem to have some local changes (related to the 2.9 betas?) that are not reflected in upstream/master? Or maybe my local state is a little off - but I don't seem to have commits that correspond to the tags
=> Dependency updates 20190718

AnkiDroid/build.gradle, api/build.gradle
Standard periodic dependency update
These are minor versions - and the sqlite one has performance improvements but no bugfixes, so it's optional to put it in 2.9. Not expected to cause problems, but not going to fix problems either.
So I would not merge to release-2.9
https://sqlite.org/releaselog/3_29_0.html
=> Dependency updates 20190813

build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties, gradlew, gradlew.bat
[Android Studio 3.5 is now available in the stable channel](https://android-developers.googleblog.com/2019/08/android-studio-35-project-marble-goes.html).
This updates the Android Gradle plugin to `3.5.0`.
=> Update Android Gradle plugin to 3.5.0

AnkiDroid/build.gradle
Bumps com.github.triplet.play from 2.2.1 to 2.3.0.
Signed-off-by: dependabot-preview[bot] <support@dependabot.com>
@timrae This was delayed because it was only compatible with gradle plugin 3.5.0 and higher (!?)
At any rate, it's not that important but similar to #5419 keeping the build/release toolchain current while it's easy helps support release branches later I think. This shouldn't affect code so it either works or it doesn't, thus should be okay to cherrypick?
=> Bump com.github.triplet.play from 2.2.1 to 2.3.0

AnkiDroid/build.gradle
@timrae this takes appcompat from rc1 to general release, and the okhttp is a specific SDK-check to fix a crash bug on Android 4.x devices within our supported SDK range (I checked their diff)
Both seem important. I would merge this and cherry-pick them both (assuming CI agrees with me and goes green)
=> Dependency updates 20190906

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
This PR fixes an issue where the card audio would keep playing after card deletion.
Issue #5391.
All sounds are stopped after the user confirms deletion of the card.
A new deck was created containing a card with an (recorded) audio attachment. Another card with only text was added. The first card was displayed and deleted while audio was still playing.
With the suggested change, the audio stops before the next card is displayed.
This has been tested two times on a physical device.
=> Stop all sounds on card deletion

AnkiDroid/src/main/AndroidManifest.xml, AnkiDroid/src/main/res/xml/network_security_config.xml
For custom sync servers. Fixes #5423; details are there.
The Android documentation acknowledges the problem and suggests a simple fix [here](https://android-developers.googleblog.com/2016/07/changes-to-trusted-certificate.html). I have implemented that fix.
It has not been tested. I currently have no Android development environment. I do not anticipate problems, though, as this is a simple XML fix provided in the Android documentation.
- [ x ] …
=> Allow connections to user-trusted CAs

AnkiDroid/build.gradle, api/build.gradle
Standard slow increments of things
I don't believe there is a single thing controversial in here, likewise I don't think there is anything really important in here, but it does include a bump to the play publishing bit
Not important to merge into 2.9 unless  you want to track patch versions
=> 2019101 Dependency updates

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
Only clear CardBrowser deck when starting app for first time
Fixes #5452 
Clear the last deck in `AnkiDroidApplication` instead of `DeckPicker`
On emulator:
1. Open browser
1. Change deck
1. Go back to deck list via the hamburger icon
1. Open browser again via hamburger icon
--> Previously selected deck is still selected
--> Same behavior when going back to deck list via back button
=> Only clear CardBrowser deck when starting app for first time

AnkiDroid/build.gradle, build.gradle
Standard periodic dependency updates
No need to move these to release-2.9 except maybe cherry-picking the gradle bump to keep the build chain up to date on release-2.9, that became a problem on 2.8
=> Dependency updates 20191009

.idea/codeStyles/Project.xml
@timrae this change is what results from opening the codebase in Android Studio 3.5.x currently
Having this file committed is a long-running experiment to find the balance between code formatting from contributors that is aligned with project standards by default being helpful, and rate of change of the file being irritating.
I think we're still on the helpful side of the balance and I'd merge this and move on, but if you feel differently I believe the other course would be to delete it from git and add it to .gitignore - you're option
=> Commit auto-altered codestyle from Android Studio 3.5.x

AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/ContentProviderTest.java, AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/libanki/ImportTest.java, AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/libanki/MediaTest.java
According to
http://junit.sourceforge.net/javadoc/org/junit/Assert.html , in
assertEquals, the expected value should be given before the value
tested. Otherwise, it leads to messages such as
>Error in testAnki2Updates(com.ichi2.anki.tests.libanki.ImportTest): java.lang.AssertionError: expected:<0> but was:<1>
where the expected value is 1 and the value actually tested is 0.
While it certainly does not change any test result, it makes the
debugging process slightly more complex, since the error messages are
misleading.
I did read the 130 assertEquals found by grep, and changed
the order of arguments when it seems to make sens. More precisely, I
assumed that:
* if one value compared is either a literal, or a constant (as L438 of
ContentProviderTest.java), then it is the expected value
* if …
=> Correct assertEquals parameter order

AnkiDroid/build.gradle
This reverts commit 2cc4c46125223595edbab6c4a24877551dd620e2.
WebView crashes on all Android 5.x versions, and Android 6-7.1 versions with old WebViews and no Play Services when using appcompat-1.1.0
Upstream bug to track is https://issuetracker.google.com/issues/141132133
#5507 - and should be cherry-picked and released as 2.9.1 as soon as possible
Most discussion is here: https://stackoverflow.com/questions/41025200/android-view-inflateexception-error-inflating-class-android-webkit-webview
Workarounds are to:
1. drop appcompat below 1.1.0 (since between rc01 and final they actually made changes, terrible release engineering: https://developer.android.com/jetpack/androidx/releases/appcompat#1.1.0)
2. wrap WebView (we use it in maybe 5 places and it breaks touch actions, a no-go)
3. …
=> Revert "Bump appcompat from 1.1.0-rc01 to 1.1.0"

AnkiDroid/src/main/res/values-hu/03-dialogs.xml
Fixes #5501
I also fixed it on crowdin for future exports https://crowdin.com/translate/ankidroid/7303/en-hu#6534325
This should be cherry-picked for a 2.9.1 as soon as possible
Using an emulator set to hu-HU locale I was easily able to reproduce the exact crash I saw on ACRA by trying to import an .apkg
After fixing the format string (`% %` -> `%%`) it worked great. So I matched the local fix on crowdin and that's it
=> fix format string error in hu-HU import progress string

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
I believe that this pull request corrects issue #3200, issue #3409, #5222 and
issue #5184(this is the best report, it gives a LOT of details) which
seems to be thrice the same trouble.
The note editor contains a list of deck. This allows to select in
which deck to put the cards of the new notes. It also allows to move
the current card if it already exists (i.e. if we edit a card while
reviewing it). The default value finally allows to knows the deck of
the card (assuming the card exists).
The trouble being that the deck of the card is not necessarily in the
list of decks. In this card, the editor believes that we want to
change the deck of the card; which is not the case.
Thus this pull request simply add the deck of the current card to the
list of deck. Note that instead the current deck …
=> Correct edition of card in filtered deck

AnkiDroid/src/main/java/com/ichi2/libanki/SchedV2.java
fix negative due dates in filtered decks ￼
https://anki.tenderapp.com/discussions/ankidesktop/35978-rebuilding-filtered-deck-on-experimental-v2-empties-deck-and-reschedules-to-the-year-1745
this means affected cards will not have the selected ordering applied,
but that seems preferable to the alternatives
dae/anki@d468999
As in Anki
gradlew and travis.
On ankidroid I took a collection with some due cards. Switched to Sched V2. I created a filtered deck without any condition. I emptied it. I then synchronized to my computer and verified in the browser that all due dates are still correct.
I must admit however that I did not try to reproduce the long process described in the link given above. I certainly want that filtered decks …
=> fix negative due dates in filtered decks

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
In theory, problems may occur if an action is cancelled while the scheduler changed. Indeed, it'll send a note in a state which may be invalid in the new scheduler.
As in Anki
gradlew, travis.
In scheduler 1, review a card. Open setting, advanced. Check Experimental V2 Scheduler. Close the advanced window and the setting. Without this commit, you'll see you can cancel the card review. With this commit, you can't.
=> Clears undo before changing schedulers

AnkiDroid/src/main/java/com/ichi2/libanki/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/SchedV2.java
As a personal note, THIS commit is the very reason why I started to learn how to edit ankidroid in the first place. It corrects a bug which is a real pain for my day to day use of anki. 
This commit corrects the following bug:
* Create a note N in an empty deck D of type basic (reverse), with
only some back, no front. Only card 2 will be generated.
* Edit the note, add a front. Card 1 will be generated.
* In the main window, try to learn deck D. In ankidroid, currently, you'll
see Card 2 first. According to the manual, Anki, (and to my common sens),
it should be Card 1 first.
This commit correct this bug, and ensure that new cards are seen
according to their order, and not to their creation date.
It follows commit …
=> New card with same due are shown according to their ord

AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
The factor of new cards is not relevant. It's ignored by the scheduler. However, it's not ignored by the finder. This ensures that if a card is new, it's easiness is ignored.
Note that, normally, if you don't hack anki, there are two factors that a new card can have. 0 and 250. 0 is the default one when a card is created. 250 is the one given to cards which are rescheduled as new.
As in Anki
gradlew and Travis.
Create a collection with five cards created in this order:
* a new card never reviewed
* a card reviewed, and a later day stated to be hard. I.e. it's ease should be <250
* a card, reviewed and rescheduled as new
* a card reviewed, stated to be easy two different day. It's ease should be >250
* a new card never reviewed
In …
=> when sorting by easiness, put new card separately

AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DialogHandler.java, AnkiDroid/src/main/java/com/ichi2/libanki/Card.java, AnkiDroid/src/main/java/com/ichi2/libanki/CardStats.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java, AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java, AnkiDroid/src/main/java/com/ichi2/libanki/Models.java, AnkiDroid/src/main/java/com/ichi2/libanki/Note.java, AnkiDroid/src/main/java/com/ichi2/libanki/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/SchedV2.java, AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java, AnkiDroid/src/main/java/com/ichi2/libanki/Tags.java, AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java, AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java
In order to be consistent with anki code
libanki tries to be as consistent as possible with Anki code. There is at least two functions where the name was changed. 
One change was motivated - I guess - by the fact that "new" is a valid method name in Python and not in Java. The other change seems useless. So in this branch/pull request, I just intend to do a global search/replace to be consistent with anki as far as function name goes.
Gradlew and Travis.
Honestly, there is nothing to test here. It's just a method whose name is changed. The only point is to be consistent with anki code.
=> intNow to intTime

AnkiDroid/src/main/java/com/ichi2/libanki/Card.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/Models.java
This tag was set in anki, not in ankidroid. It's no longer the case
I should note that {{CardFlag}} in anki is replaced by the empty string or by Flagi, with i a number. It's absurd; the flag should be a color, as in the browser. However, I stay close to anki code and keep the absurd action instead of doing sensible thing.
As in Anki
Gradlew. Travis.
I created a new profile on computer. I edited the basic note so that it's front template is:
```HTML
{{Front}}<br/>
Card flag is :{{CardFlag}}
```
I then created 5 cards. In the browser, I set their flags to the four colours. (As far as I know, ankidroid doesn't allow to set flags yet)
I synchronized on a throwaway account on ankiserver. 
On a virtual device, I synchronized with this …
=> support {{CardFlag}}

AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java
dae/anki@27c23c01d6193c4fdae6854f27972956deb0bb12
Theoretical problem in case of upper cap in HTML in fields.
As in Anki
=> some html regexps should be case insensitive

AnkiDroid/build.gradle, build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties
The are [known issues](https://docs.gradle.org/5.6.2/release-notes.html#fixed-issues) in currently used Gradle 5.6.1
Also fix some clumsy Gradle usages:
- duplicate keys in gradle.properties
- casting string jacocoVersion property to string
CI run would be enough
=> Bump Gradle from 5.6.1 to 5.6.3, JaCoCo to 0.8.4

AnkiDroid/src/main/java/com/ichi2/anki/services/BootService.java
There is a state where the application is installed and storage permission is granted, but the collection is not actually initialized with decks
The BootService assumes a collection always has decks, counter to this possible state, and null pointer's attempting to access them and schedule reminders
Fixes #5503 - our top crash by far at the moment for 2.9.x
I inspected the code a bit to see when the "collection accessible, but no decks" state occurs but must admit I didn't see it. At the same time it's clear that it happens a *lot* and reminders are more of an add-on vs having a crash bug on app startup, so it seemed simply acknowledging the state was possible by evidence, and handling it in the same way we handle other "can't schedule reminders yet" states was reasonable
Ran the full …
=> fix crash on app startup with uninitialized collection

AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
https://anki.tenderapp.com/discussions/ankidesktop/35903-bug-find-and-replace-breaks-when-replacing-with-latexmathjax-commands
dae/anki@6b784ae42e767413798acfbff34968d2d984db52
As in Anki
=> escape backslash in find&replace

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
I should note that the initial problem that dae/anki@20ff61e59eae6c32e4671c035a0d5438d169ab2f was supposed to solve exists in ankidroid. However, since ankidroid doesn't used previewCards to preview cards, this PR does not fix the bug. I should also note that my goal is to port anki to libanki, so actually correcting the bug is not something I intend to do in this PR. Even if having previewCards fixed may probably help solving this bug eventually.
As in Anki
gradlew and Travis.
I should note that the method previewCards is not called anywhere in ankidroid code. Therefore, there is no way for me to test any change to previewCards. I have not yet looked at the way cards are previewed in ankidroid.
Regarding _newCard: this method is …
=> Allow for a deck parameter when creating and previewing a card

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
The Cloze deletion floating menu item appeared on all note types, and in an inconsistent position.
#5532 
Fix to always be on the left, and only on Cloze types.
Tested manually on a physical Samsung Galaxy Note 9.
=> Cloze menu

AnkiDroid/src/main/java/com/ichi2/libanki/template/Template.java, AnkiDroid/src/test/java/com/ichi2/libanki/MathJaxClozeTest.java
There's an issue with Mathjax and multi-part clozes.
#5552
I made a small mistake when adapting this function originally, when translating the Python to Java.
I setup both anki desktop and anki-android with similar unit tests, and stepped through them to find the issue.
Created a unit test that shows the issue, fixed the issue, and the test agrees.
=> Fix Mathjax Cloze duplication issue.

AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java, AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/Models.java, AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java, AnkiDroid/src/main/java/com/ichi2/utils/Assert.java
The initial purpose, as stated in Anki's git is to: "ensure the list of note types is not empty". dae/anki@8497da27cf47f395a8288c47d9ff3ba32e95cfc4
I.e. during fixIntegrity, if it is detected that there are no note type, then the standard note types are added. Similarly, during any change to note type (i.e. modelManager), the non-emptiness is also checked. 
I also ensured that adding the standard model would not state that the mod need to be changed. However, standard models should be added when collection is created; in which case a full upload is already required, or when there are no model, which should never occur.
Doing so, I did realize that the type of addField and addTemplate state that an exception may be thrown. Which actually is not the case if either the model is new or the …
=> Add new field template method

AnkiDroid/build.gradle, AnkiDroid/src/main/resources/jacoco-agent.properties, build.gradle
Coverage reports were broken, and jacoco upgrades were failing.
This updates the jacoco plugin, and in the process fixes all the entropy discovered in the area
No logged issue, but if codacy was working I would have noticed coverage went to zero as the reports were no longer referencing build classes (gradle moved them, I think with android studio 3.4 -> 3.5) or referencing instrumented test output (also moved)
Plus jacoco made a breaking change from 0.8.4 to 0.8.5 so it fixes that
I took the opportunity to de-lint the file as well, just taking Android Studio suggestions to quiet warnings as they seemed sensible.
This includes a new resources file in androidTest only, that directs jacoco to not try writing to the filesystem on startup, that fixes the upgrade.
I changed paths in other …
=> JaCoCo coverage upgrade / fixes

AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java, AnkiDroid/src/main/res/values/constants.xml
implement onError() to report a Toast with some hints to the user
in case the TTS engine returns an error.
From API 21 upwards we would also have the error code available
for further details on what happened.
fixes #5468
report a Toast
=> catch and report TTS errors

AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.java, AnkiDroid/src/main/java/com/ichi2/libanki/Models.java, AnkiDroid/src/main/res/values/18-standard-models.xml, tools/manage-crowdin.py, tools/update-localizations.py
In Anki, standard models are localized. More precisely, there are translations of field names, card name and model names. I ported this to ankidroid.
Using resources
Starting anki in a VM, changing the language to French, trying to add a note type, seing that all names are translated to french.
- [] You have commented your code, particularly in hard-to-understand areas
=> Localize standard models

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
This fix issue #5456 (by me). The first commit copies Anki behavior. As I reported, this behavior is bugged, so the second commit fix Anki bug the same way I just fixed it in anki's code. See https://github.com/dae/anki/pull/339
As in Anki (and in my Anki's PR).
Edit: it's not a PR anymore, but it is dae/anki@c2a6c3e47a9d88d28d5dbdd129db97a28f044c49.
I tried to reproduce both bugs in ankidroid, and saw that with this PR, all dues are correct. #5456 did disappear and Anki's bug did not appear.
=> One due by note

.travis.yml, AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/ContentProviderTest.java, AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/libanki/ImportTest.java, AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/libanki/MediaTest.java
Travis has become a bit flaky lately.
In the last round of Travis work, we needed features in the emulator that were only available on their 29.x release series and that was on the canary channel.
It worked well then, but with 29.x released stable, continuing to pull emulator images from canary results in instability.
I have my own Travis fork, and it does CI on my Anki-Android fork. I've been re-running builds on this commit over and over and it hasn't failed yet once, so there may still be some flakiness but it seems worth integrating this now standalone based on current testing
If you rely on pre-release version *streams* (not specific versions) you will eventually ingest unstable change
=> Use stable channel emulator now that 29.x is out

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
Using the alpha version of Anki, I received a null pointer exception and corrected it. 
Here is a silly problem with porting Python code to Java. Sometimes,
it does not work the same way at all. When I committed
504d96a99d31f35cfb48d94af1e7b282603b9bb6 I didn't pay attention to was
the value of dues.get(nid) when nid is not in dues. And actually, the
value is None. Which means that it can't be converted to a long. And
thus raised an exception.
I also realized that the line `due = dues.get(nid);` was present twice
in the code, which makes no sens in the first place. So this second
occurrence is now removed.
Checking whether the value is in the mapping before accessing it.
Trying to edit a note without new cards. Seeing it now works
_Links to blog posts, patterns, libraries or addons used …
=> Correct due of new card whose all siblings are not new

AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
The error was sent in this line:
https://github.com/ankidroid/Anki-Android/blob/7235a5bc667a6c9def934d85764cedc6594814b3/AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java#L857
where searchResult is null.
It's value is the result of col.findCardsForCardBrowser
this method simply returns the  value returned by the Finder#findCardsForCardBrowser
The value returned by the finder itself findCardsForCardBrowser sends
null if the task was cancelled. However, the value returned is still
used by findCardsForCardBrowser. So I ensure that it's not null, but
an empty list.
#5515
Returning empty list is as quick as returning null, and does not lead to null pointer exception.
Searching cards and verifying that it still works.
I didn't try to …
=> Correcting #5515 hopefully

.travis.yml, tools/android-wait-for-emulator.sh
Leverage the nested virtualization capabilities of Travis CI's `bionic` image to speed up the Android emulators we use for testing.
Related to #5583.
To take advantage of some of the new nested virtualization capabilities
of some of the images in Travis, you must be using the newest LTS
release of Ubuntu, 18.04 Bionic Beaver.
However, the Travis image of Bionic does not include support for JDK 8,
which we need to utilize for the Android SDK manager. To circumvent this
issue, we change from the "android" language type to "generic", and take
care of both the JDK and the Android SDK ourselves.
As such, this commit makes the following changes:
* Switch `dist` from `trusty` to `bionic`
* Switch `language` from `android` to `generic`
* Enable the use of `sudo`
* Install libpulse0 for emulator …
=> CI: Use emulator acceleration

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
https://github.com/ankidroid/Anki-Android/blob/bcc13aaf374725af69159bc4c7f68ea0d2fa3ea9/AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java#L101
The tagPattern regexp does not properly handle tags which contain a ">" character within them, such as an HTML comment like ``
Fix #5395
Since HTML is not "regular", trying to fix the regular expression to handle such cases seems futile. Instead, HTML comments are stripped prior to calling `stripHTMLMedia`.
Tested on physical device.
According to the HTML spec, comments cannot contain `-->`, so if somebody writes ` comment -->` we are under no obligation to honor it.
https://www.w3.org/TR/html4/intro/sgmltut.html#h-3.2.4 indicates that the comment closing may contain whitespace, e.g. `--  >`. However the HTML5 spec does not mention that, and …
=> Strip HTML comments in card browser

AnkiDroid/src/main/java/com/ichi2/libanki/importer/AnkiPackageImporter.java
Theoretical risk in case of media name in cards not referring to media folder
As in Anki
I tried to import a deck with an image. it did work.
I didn't check whether it really protects against a deck created especially to hack anki/ankidroid, since I don't even know exactly against which attack this is supposed to protect the user. I don't know how to create a zip file such that the normalized path of a string is above the top level of the folder.
=> catch attempts to write outside the media folder

AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java
Theoretical risk in case of trouble with media folder
As in Anki
gradlew.
I tried to export a deck with a media in it. It did work
I can't really test the problem this is supposed to solve since it's hard to reproduce without hacking a collection. Indeed, it supposes that I succeed in adding a folder in a collection.
Since this prevent exporting a folder, this is not a security risk, as could be allowing to import a deck with a folder in the medias. So I believe that trying to hack ankidroid in unusual way to check how much this correction really corrects entirely the theoretical risk is not worth the time of anyone.
=> make sure exporting ignores subfolders

AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
dae/anki@491b8ea63fdf049dae122a0bc905e0eac3c7451f
Allow to deal with search of tags when there are multiple tags
As in Anki
gradlew.
Create a collection with two notes. one with tag "tag%". One with tag "tag". 
Open the browser. Enter search "tag:tag\%". You'll find only the first note, as in anki.
=> Allow special characters to be escaped

AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
As in Anki
gradlew. 
ordForMid is used only in findDupes. findDupes is used only in other method findDupes. So essentially, this method is not used at all currently.
=> find&replace should not be case sensitive on field

AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java, AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
Some theoretical risk in collision of non normalized name
As in Anki
gradlew. 
I don't know how to have non normalized name on android. I'm not competent enough to test it
=> make sure we normalize deck names on input

AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
incorrect scheduling when importing cards in relearning
As in Anki
Take www.milchior.fr/tmp/due.apkg
It has a card in learning due the 21th of october. If I review it today, pressing good, it'll be due the 28th of october.
I imported it in ankidroid. I then sync on ankiweb. On my computer, I sync to download the imported deck (in a distinct collection, not the original one)
I then click good and check the new due date. It's also 28 of october.
However, if I did the import in a version of anki without this PR, then the due date would be in 2023 instead of being in 2019.
Note that you may have distinct date of course if you do that, because your collection are not created as the same date. And the error this commit corrects is due …
=> fix incorrect scheduling when importing cards in relearning

AnkiDroid/src/main/java/com/ichi2/libanki/Tags.java
Allow wildcard tag deletion
dae/anki@9f37cddfdad8c7c7bab0e60b42e00eb50fd6161b
As in Anki
Gradlew only.
Currently, Tags#bulkRem is never called anywhere in the code. It's not accessible from the GUI. So there is no way to check whether the PR indeed correct this method since anyway this method currently can't be used, even if it's in the codebase.
=> Wildcard tag deletion

AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
The method `parent` as I implemented it, does not deal with names
having ":::" in them. "::::" is impossible, but ":::" is totally
okay. So now it deals with it.
Anki believe that in this case, the first two colons are the
separators, the last one is part of the deck name.
#5603
Trying to reproduce the above-mentionned bug, and failing the reproduction.
I did read the three commits during which the problems did appear, and which were listed by timrae
=> Dealing with ":::" in deck name

.travis.yml
Our lowest supported API - API15 - has been a broken emulator for a long time. Since it's the end of our supported range it's important to verify it works.
But Google's emulator team has been on the job the last year. The improvements have been great.
They've just fixed the last issue I was tracking, and API15 works again in latest canaries
https://issuetracker.google.com/issues/37138030#comment17
I add the ability to specify what emulator channel to pick up in Travis. Default to stable, but for API15 I use the canary to get this enabled.
Travis CI runs on my own fork https://travis-ci.com/mikehardy/Anki-Android/builds/135278687
Still works even with hardware acceleration though the command-line we are using to start the emulator seems to change with the canary, indicating a future …
=> Re-enable CI emulator API15 via canary for that API

.travis.yml
The Google Android Emulator team continues with high velocity and sometimes breaking changes
There were a couple crash bugs that were fixed in recent emulator versions (allowing me to revert two temporary workarounds), but the recent one also collapsed 'emulator-headless' command to 'emulator -no-window', so this converts our emulator usage to the new command syntax
Fixes #5649 
Adopt new command
Tested on personal Travis CI instance connected to my Anki-Android fork
Google Android Emulator team continues to have high velocity, not all good, but I still like it.
=> Update CI for new emulator command lines

gradle/wrapper/gradle-wrapper.properties
Simple patch release. Moves gradle status to "No known issues" according to their release notes.
=> Upgrade gradle from 6.0 to 6.0.1

AnkiDroid/src/main/java/com/ichi2/anki/Info.java, AnkiDroid/src/main/res/values/05-feedback.xml, AnkiDroid/src/main/res/values/constants.xml
When the user wants to rate the app, AnkiDroid launches an intent with a specific market uri and expects the device to handle it. In some situations, however, the intent can't be handled (like in issue #5653). AnkiDroid never assumes this situation and crashes.
This fixes issue #5653.
We use the [Intent.resolveActivity()](https://developer.android.com/reference/android/content/Intent.html#resolveActivity\(android.content.pm.PackageManager\)) function to test whether the intent can be resolved or not.
If the intent can not be resolved, we notify the user using a Toast.
I've tested the fix multiple times using an Android API 28 emulator.
=> Fix crash occurring when trying to open rating activity

AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java
The [Matcher.appendReplacement()](https://docs.oracle.com/javase/7/docs/api/java/util/regex/Matcher.html#appendReplacement\(java.lang.StringBuffer,%20java.lang.String\)) method used when escaping html entities treats backslashes (\\) and dollar signs ($) differently than the rest of the replacement string. Due to the input not being properly escaped, certain sequences (f.i. "&bsop;") lead to crashes.
This fixes issue #5638.
We use the [Matcher.quoteReplacement()](https://docs.oracle.com/javase/7/docs/api/java/util/regex/Matcher.html#quoteReplacement\(java.lang.String\)) helper method to escape the string.
I've tested the fix multiple times using an Android 28 emulator.
=> Fix crash related to escaping html entites

AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java
The img tag detection was incorrect which caused conditional field replacements using just img tags with differently ordered attributes to break the regex. More concretely:
```html
```
This should fix #5166
Similar to the issue linked I updated the regex to match the one used by Anki desktop which doesn't have this issue. The template code still differs from upstream Anki but I thought this was out of scope for the PR.
I admit I haven't tested this but the regex should be correct since I tested it on regex101.com
=> Change the img regex tag to match Anki desktop

AnkiDroid/src/main/java/com/ichi2/libanki/template/Template.java, AnkiDroid/src/test/java/com/ichi2/libanki/MathJaxClozeTest.java
See https://github.com/dae/anki/pull/374 for upstream fix.
I fixed a parsing issue in MathJax with Clozes in upstream Anki, this is a port of the fix to Ankidroid.
See https://github.com/dae/anki/pull/374
Straightforward port of my rewrite of the `_removeFormattingFromMathjax` function in original Python.
CI tests should be sufficient, since this code is covered by unit tests. I am also adding unit tests for my minimum reproduction of the parsing error.
=> Port MathJax-Cloze bugfix from Anki

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java, AnkiDroid/src/main/java/com/ichi2/anki/services/BootService.java, AnkiDroid/src/main/java/com/ichi2/anki/services/NotificationService.java, AnkiDroid/src/main/java/com/ichi2/widget/WidgetStatus.java, build.gradle
An attempt to fix issue "No notifications after update 2.9 and 2.9.1" #5535 
Fix #5535 
From my experience with AnkiDroid, there are 2 types of notifications  in the app:
(1) The general notification which has the form "%d AnkiDroid cards due"  
(2) The reminder (specific to each deck) which has the form "%d cards to review in <DeckName>"  
For convenience, in the following text, I regard (1) as notification, and (2) as reminder.  
I ran some tests. It turned out that the notification only works when the widget is enabled.
Steps to reproduce this phenomenon:
1. Install AnkiDroid.
2. Download and import a shared deck with more than 10 cards.  
3. Enable widget (the AnkiDroid Small Widget).
(by "enable widget" I mean add the AnkiDroid's widget onto the Home Screen of the phone)
4. Choose …
=> Fix "No notifications after update 2.9 and 2.9.1" (#5535)

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java, AnkiDroid/src/main/res/values/01-core.xml
In https://github.com/ankidroid/Anki-Android/pull/5571#issuecomment-569451870 there was two problems mentioned. 
1) is that "Flag red" should have been "Red flag". 
2) updating the "marked" status wasn't reflected anymore in card browser.  
1) It uses the correct string, as in Anki.
2) "Cards" (which are not card objects but map) returned by finder now has a tag "marked" which holds iff the card is marked. This value is updated when some cards are updated in the browser.
I must state that I do not understand the point of the "updatedCardTags" function variable. So I didn't change it and used an extra entry in the map instead of using its entry "tags".
I installed it on my phone. I opened the browser. I marked and unmarked card. I saw that the color update was reflected
Having a lot of …
=> correcting problems from the "Flag" pull request

AnkiDroid/src/main/assets/card_template.html, AnkiDroid/src/main/assets/flashcard.css, AnkiDroid/src/main/assets/scripts/card.js, AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
As requested in https://github.com/ankidroid/Anki-Android/pull/5571#issuecomment-570105143 , anki cards now have flag/marked status as in Anki.
I opened ankidroid. I tried to add the marked status, and a flag. Both did appear. I left the card and reloaded it, the flag and star are still here. I tried to remove them, and they leave. Furthermore, in all cases, the icons are not on top of text.
java is simple. Having correct css is a nightmare.
=> Add flag and mark in top of the reviewer as in anki

AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
I did forgot to add deck names in the name list. Which means that each
subdeck thought they don't have parents.
Parents were not created since _ensureParents founds the parents. And
it didn't made ankidroid really slower. However, it means that
duplicates were not found; and worse, it sent a lot of useless data to
the debugger, making it harder to read than what it was before
Honestly, this branch was created months ago. And it seems I just forgot to transform it into a PR. 
By adding the name into the set of deck name
Started ankidroid, and checked that actually I didn't have timbers related to deck name.
=> Fix _checkDeckTree

AnkiDroid/src/main/java/com/ichi2/libanki/Media.java
Avoid a potential risk when media name added through android are extremly long.
Note that I believe that dae's code itself does not make sens here. Indeed, the same collection can be synchronized on any device. So the same constraints should apply to all devices. Otherwise, we risks to have media which can be used on android and not on windows. 
However, here, I'm only porting anki's code to ankidroid and thus don't intend to correct it
As in Anki
gradlew. 
I fail to test this, because I fail to produce the bug it's supposed to avoid. When I try to use a virtual machine, I can't rename a file to give it more than 1024 characters. Mostly because typing a single character takes seconds. Which means that I can actually have a file …
=> cap filename length when attaching media to cards

AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java
When there are more exporter, allows to factorize code
As in Anki
=> Add method card ids to exporter

AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/libanki/ImportTest.java, AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
Drop supporting anki 1
As in Anki
=> remove dupeOnSchemaChange

AnkiDroid/src/main/java/com/ichi2/async/Connection.java, AnkiDroid/src/main/java/com/ichi2/libanki/Media.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/MediaSyncer.java, AnkiDroid/src/main/res/values/04-network.xml
Theoretical risk in case of corrupted media database
As in Anki
=> Catch corrupt media db fix it in check media

AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.java
Fixes #5091
Use actual deck ID instead of libanki selected deck ID
On VM as per steps in original issue
=> Fix incorrect filtered deck getting rebuilt on long-click

AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java
For some reason, anki decides not to export flags. This PR simply copy this decision
As in Anki
Take a deck with a card with some flag set. Export the deck. Import it into another collection. Remarks that the card is not set anymore.
=> clear flags on export

AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
Anki allows to use flag to search cards, both in Browser and in Filtered deck.
This commit allows to do the same thing.
Fixes #5444
Mostly as in Anki (so, sorry Mike, there is a little bit of binary computation).
With the exception that I had to deal with type conversion as in Java and not as in Python. So I decided to simply check whether the string is "0", "1", "2", "3", or "4" using a switch case. This avoid to try a conversion and deal with a potential exception. 
Creating a deck with a due card with flag 2 (on computer, as you still didn't merge my PR related to flags). Creating a filtered deck with search "flag:2". Emptying the deck. Synchronizing from computer onto ankidroid.  Seing that when I build the filtered deck on ankidroid, it find the above mentionned card and nothing …
=> Allow to search for cards with some flag

AnkiDroid/src/main/assets/flashcard.css
This is a partial solution to #5695. Seems to work on my VM.
CSS hides star by default. That is actually what anki does. But since I didn't see the point (since the star is hidden by JS) I didn't copy this part of the CSS. Now I see the point, thank you
=> Removing flashing of stars/flag

AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.java
Don't duplicate the text in Front EditText after split screen operation (activity destroy/recreate)
Fixes #5660 
Activity recreated after split screen. The code in NoteEditor handles onSaveInstanceState correctly including saving/restoring FieldEditText contents but FieldEditText saves text automatically itself unless you override and cutout the behavior.
manually tested with cases in issue
=> Remove method onSaveInstanceState in FieldEditText, fix #5660

AnkiDroid/src/main/java/com/ichi2/libanki/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/SchedV2.java
Porting ankitects@d9b5a1da891a2b61e7d5b8ba4e4fe59185696a91
Ankidroid had the exact same bug than anki. I didn't actually try to reproduce it on my ankidroid, because that's a long process (see the commit for details). I just checked that, with this trivial change, you can still change order of new cards in a standard deck's option
=> Order by creation of note

AnkiDroid/src/main/java/com/ichi2/async/Connection.java
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/950f7ab5-1e97-44a2-b58a-e56f15d08e72
OkHTTP uses slightly different errors to percolate timeouts and connection interruptions vs the apache-http library, so we are now misinterpreting relatively harmless errors has something we should crash on
I added the two okio (okhttp underlying library) messages to our connection error logic
https://github.com/square/okio/blob/1bed1bc104c19a673ad86fbe7e8eed859131a5ee/okio/src/main/java/okio/Timeout.java#L220-L226
Installed and used on API28 and API29 emulators to do a conflict full sync, a no-op sync, then to sync the results of a small review between them, it all still worked. I also checked interrupting data while a full sync was happening and it threw an error …
=> Okhttp interrupted crash

AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java
It is not documented, but in AOSP source RuntimeException may be
thrown for a variety of reasons while retrieving media metadata
Not logged, but was brought up in play store review and has associated crash UUID URL https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/a572b30b-82d6-454d-b587-4e20b83a5d5e
This fix expands the catch to handle those RuntimeExceptions, even
though we can't really recover from them. The method is only responsible
for returning the duration of the sound, and it will now default to 0
in these cases.
This media duration method itself is only used when AnkiDroid is
configured for auto-advancing review, to calculate the delay correctly.
Since the file is likely inaccessible anyway, waiting for 0 duration in
that case seems correct …
=> Avoid RuntimeException crash in Sound

.gitignore
Screenshots taken with the Android VM appear in a 'captures' folder in the root directory of the project. Git will track there, but there shouldn't be a need to ever version control them.
I didn't create an issue - are they required for pull request?
excludes folder in gitignore
Hides local screenshots I've taken from being tracked by git
- [x ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ x] You have commented your code, particularly in hard-to-understand areas
- [ x] You have performed a self-review of your …
=> Ignore android VM screen capture images

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java, AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
It partially corrects #5694. The browser does not seems to be loading
anymore when the answer is an empty string. (E.g. if the answer
consists only of a music file, or anything else which was deleted
because it can't be rendered)
=> Card browser accepts empty answer string

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
After updating to the latest version my question plays twice on the question side and once on the answer side.
Fixes #5530, #5730 
In the function removeFrontSideAudio only the first occurrence of sound was stripped.
The similar bug occurred and was fixed in 2014 https://github.com/ankidroid/Anki-Android/pull/669 
I've built APK with this fix - after pressing "show answer" button question was not repeated again.
- [*] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [*] You have a descriptive commit message with a short title (first line, max 50 chars).
- [*] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [*] You have performed a self-review of your own code
=> Fix for: Latest update plays audio file twice #5530

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.java, AnkiDroid/src/main/res/values-pt-rPT/10-preferences.xml, AnkiDroid/src/main/res/values/10-preferences.xml, AnkiDroid/src/main/res/xml/deck_options.xml, AnkiDroid/src/main/res/xml/preferences_reviewing.xml
The 'Automatic display answer' settings are very useful for increasing the speed of review. Nonetheless, different decks have different needs and, as a user, I always felt that having a single set of settings for all decks was not enough.  As such, I decided to search for a way to solve this. I did not find a solution, only a related issue. For a while now, I've changing the settings between decks, which is cumbersome.
This commit adds 'Automatic display answer' to the group options, allowing for the user to use either the specific settings of a group or use the general ones.
An issue I found related to this: https://github.com/ankidroid/Anki-Android/issues/3838
This commit adds 'Automatic display answer' to the group options, allowing for the user to use either the specific settings of a …
=> Added review options related to the automatic showing of answer specific to a group of decks

AnkiDroid/src/main/java/com/ichi2/async/Connection.java
OkHTTP has a slightly different way of reporting connection errors than the Apache HTTP library did, and while these don't cause application crashes they do clutter the crash reporting database because we send non-fatal error reports for them.
This adds 3 new string matches to the connection error handling to categorize the matched exception messages as harmless
Difficult to reproduce, but on emulators account syncing still works after these chanes
=> Categorize more okhttp connection errors as harmless

.travis.yml, AnkiDroid/build.gradle, AnkiDroid/src/main/java/com/ichi2/libanki/template/Template.java
The crash database had a good number of crashes like this:
```
java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:309)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NoSuchMethodError: No virtual method group(Ljava/lang/String;)Ljava/lang/String; in class …
```
=> Mathjax wrong api crash

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.java, AnkiDroid/src/main/res/values/02-strings.xml
```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
at androidx.fragment.app.FragmentManagerImpl.checkStateLoss(FragmentManagerImpl.java:2)
at androidx.fragment.app.FragmentManagerImpl.enqueueAction(FragmentManagerImpl.java:1)
at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:12)
at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:1)
at androidx.fragment.app.DialogFragment.show(DialogFragment.java:10)
at com.ichi2.anki.AnkiActivity.showDialogFragment(AnkiActivity.java:5)
at com.ichi2.anki.DeckPicker.showImportDialog(DeckPicker.java:13)
at com.ichi2.anki.dialogs.DialogHandler.handleMessage(DialogHandler.java:6)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:201) …
```
=> Fix ImportDialog IllegalStateException crash

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronounciationActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/TranslationActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/beolingus/parsing/BeolingusParser.java, AnkiDroid/src/main/java/com/ichi2/anki/web/HttpFetcher.java
I noticed a crash in 2.9 related to Apache HTTP client and it led me to discover there was one more Apache HTTP remnant in the HttpFetcher used to download pronunciation and translations.
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/33a4184e-c3d7-4b60-af73-ca68b02fdfbb
```
java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:354)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
at java.util.concurrent.FutureTask.run(FutureTask.java:271)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at …
```
=> Replace apache http remnant / Beolingus parse fix

AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioClipFieldController.java
Add audio clips was a highly requested feature, and it worked structurally but failed when confronted with unexpected audio clip names or unexpected content resolver states (like, no results - it always expected one)
Also the error handling and implementation of file copies were non-standard
Fixes #5509 
Best to review each commit separately as they are discrete and independently useful
1. generalize the ability to show toasts (so we can inform users of audio clip issues)
1. standardize the content file copy and error handling using existing helper function
1. improve content resolver results handling in case results are empty or contain an audio clip with no file extensions
I used an API29 emulator attached to a google play account so I could use my Google Drive as a source of audio …
=> Fix add audio crashes

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.java
ImportDialog was still crashing after #5743 
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/4a0ab280-d1bc-4265-bba5-2fd175004c3d
```
java.lang.IllegalStateException: Fragment ImportDialog{59c7f45 (0ccc9642-1fda-4aed-b165-c4fdd4b1ee02) dialog} not attached to a context.
at androidx.fragment.app.Fragment.requireContext(Fragment.java:2)
at androidx.fragment.app.Fragment.getResources(Fragment.java:1)
at com.ichi2.anki.dialogs.ImportDialog.getNotificationTitle(ImportDialog.java:1)
at com.ichi2.anki.AnkiActivity.showAsyncDialogFragment(AnkiActivity.java:4)
at com.ichi2.anki.AnkiActivity.showAsyncDialogFragment(AnkiActivity.java:1)
at com.ichi2.anki.DeckPicker.showImportDialog(DeckPicker.java:13)
at …
```
=> Use application-level resources for Async fragments

AnkiDroid/src/main/java/com/ichi2/libanki/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/SchedV2.java
In dbf3c09d5b3ebe2a1e734be4d597a0f01e90be67 I made a mistake. I moved
some codes from Sched and SchedV2 to Decks. This code was essentially
in charge of correcting errors in decks (duplicate name, missing parent...)
In the middle of this code was one line which was actually dealing
with scheduling, and which got removed by accident:
`nlim = Math.min(nLim, lims.get(p)[0]);`
This commit simply adds back this line. I should note that this line
is actually present in anki code. pylib/anki/sched.py#L:258
Bug report #5737 
By adding back the line removed by accident
Not, because I don't have the buggy collection (honestly, when you have 300 decks, none on top level, it gets really hard to remark this bug). So hopefully by @terrywallwork who reported the bug and was very helpful in helping to …
=> Applying correctly limit for top level new deck

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioClipFieldController.java
#5755 was a major improvement in audio clip handling but there was still a crash, this time related to my attempt to debug log the mime-type information
Turns out that can be null which will throw an exception in the Android implementation: https://developer.android.com/reference/android/database/Cursor.html#getString(int)
```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=Intent { dat=content://com.mi.android.globalFileexplorer.myprovider/external_files/Download/Cloakroom.mp3 flg=0x1 }} to activity {com.ichi2.anki/com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivity}: java.lang.IllegalStateException: Couldn't read row 0, col 2 from CursorWindow. Make sure the Cursor is initialized correctly before accessing data from …
```
=> Avoid crash on audio clip w/no extension or mime type

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
Something is going on with regard to dynamic decks. At least the ones formed with a filter that is to preview ahead a certain number of days.
They don't contain all the items I would expect in the deck conf
One symptom is #5708 but #5756 is also happening.
I have fixed #5756 here by going to all default arguments if it is a dynamic deck, which is possible because we have sensible defaults for it. But I'm not sure how to fix #5708 yet
Fixes #5756
Carefully attempt to access the decks "rev" object, only if the deck is not dynamic.
I was able to reproduce the google test lab pre-launch report crash by watching the video and clicking along on an API28 emulator.
I was able to avoid the same crash after adding this patch
=> Don't assume dynamic decks have review options

AnkiDroid/build.gradle
Typical batch of dependency updates
In this one we have sqlite, material and jsoup for release changes
The rest are internal testing items (powermock)
They pass CI, and because material could affect visible items I also spot-checked it on an emulator and nothing appears visually different. Should be okay, but still targeting for 2.10 not a 2.9 merge
=> Dependency updates 20200213

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java
There were complaints of camera crashing but I'd never seen it, in working on another issue
that required use of an old emulator I noticed that indeed the camera is crashing on image
capture for Android API <= 21 (maybe 22)!
That's no good. This should fix it in the internet-recommended way.
https://medium.com/@quiro91/sharing-files-through-intents-part-2-fixing-the-permissions-before-lollipop-ceb9bb0eec3a
Related #4871, #4799 - both of those look like they were likely this bug
Pursue any crash I see in testing to it's stackoverflow-directed conclusion, basically. Then test it.
I checked it on API18 emulators (reproducible crash without this patch) and an API28 emulator (worked fine before and after)
I believe the root cause is the conversion to FileProvider for use in Android >= 7, which …
=> Manually grant permissions <= Lollipop to avoid camera crash

AnkiDroid/build.gradle, AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/ContentProviderTest.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.java, build.gradle, gradle/wrapper/gradle-wrapper.properties
Note that ContentProviderTest needed a tweak as Manifest class
is no longer generated correctly, we are using the second method
to handle it, as described here:
https://developer.android.com/studio/releases/gradle-plugin#agp-missing-manifest
Also, lint in 3.6 is apparently a little stricter on NewApi checks.
For the CameraException I verified that the camera enumerated fine
on API18 which is below the API19 warning they emitted where things might
crash just from attempting to touch the class
=> Bump Gradle to 3.6.1 to match Android Studio stable release

AnkiDroid/build.gradle
One more dependency update before generating next alpha - this prevents crashes for 11 preview people
Tested in API16 and API28 emulator via choosing to opt-in for feature sharing then setting analytics to dev mode in advanced preferences and scanning logcat to verify analytics post successes
=> Update google-analytics library for Android 11 compatibility

AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java
Avoid crash on browser QA render if cancelled
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/32165275-1bc3-46d7-8611-5e381d2b7bde
```
java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:354)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
at java.util.concurrent.FutureTask.run(FutureTask.java:271)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:764)
Caused by: …
```
=> Avoid crash on browser QA render if cancelled

AnkiDroid/src/main/java/com/ichi2/anki/services/ReminderService.java
If you delete a deck while building reminders, the app will crash because the scheduler will throw out a NullPointerException if asked to find cards due for a missing deck
If this seems okay, I'll cherry-pick this in 2.9.5 as a targetted crash fix, after marinating on 2.10alpha
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/b772e271-82de-4945-a600-51eca6db7daa
```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.json.JSONObject.has(java.lang.String)' on a null object reference
at com.ichi2.libanki.Decks.confForDid(Decks.java:2)
at com.ichi2.libanki.Sched._deckNewLimitSingle(Sched.java:3)
at com.ichi2.libanki.Sched.deckDueList(Sched.java:8)
at com.ichi2.libanki.Sched.deckDueTree(Sched.java:1)
at …
```
=> Gracefully handle deck deletion while building reminders

AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java, AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java, AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.java
Running out of space on import creates a lot of crash reports and also a fair bit of user support. I investigated and found that the messaging in general is terrible:
1. if we run out of space on cache copy from file provider it says "invalid package" (!)
1. if cache copy works but import runs out of space it silently fails to import media
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/7395b0d7-e9b6-4ae3-a57b-c42b464dc8f1
```
003-02 21:08:45.253 E/AnkiDroid(26719): ImportUtils/ Could not copy file to /data/user/0/com.ichi2.anki/cache/550_Phrasal_Verbs_-_Part_1_Ingls_-_Portugus.apkg103-02 21:08:45.253 E/AnkiDroid(26719): java.io.IOException: write failed: ENOSPC (No space left on device)203-02 21:08:45.253 E/AnkiDroid(26719): at …
```
=> Import out of space fixes

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioView.java
MediaRecorder.stop is documented to throw a RuntimeException on purpose
in the case where stop is hit immediately after start:
https://developer.android.com/reference/android/media/MediaRecorder#stop()
There are a lot of crashes like this: https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/09bef5fb-2f04-4cc8-8856-31f9c78dee9e
```
java.lang.RuntimeException: stop failed.
at android.media.MediaRecorder.native_stop(Native Method)
at android.media.MediaRecorder.stop(MediaRecorder.java:919)
at com.ichi2.anki.multimediacard.AudioView.notifyStopRecord(AudioView.java:2)
at com.ichi2.anki.multimediacard.AudioView$RecordButton$1.onClick(AudioView.java:4)
at android.view.View.performClick(View.java:5661)
at android.view.View$PerformClick.run(View.java:22682)
at …
```
=> Gracefully handle MediaRecorder.stop exceptions

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java
Avoid changing a list used in asynchrone process. Which I believe to be the cause of bug #5516 
And seems to be good practice anyway
#5516 
Instead of changing the content of the list, new lists are created and the variable is set to the new list when they are fixed. 
In the browser, I did try to create a new search. I did delete a card from the browser. I saw that everything worked as expected.
I can't test whether this bug can still occur, because I can't reproduce it easily. As I explained in the LONG commit message, this bug can occurs only by accident, if the list is cleared between two successive test of an if. So there is no way to check this can definitively not occur again 
I should take serious note of my search (as I did in the long commit). Because otherwise I forget some …
=> Correcting5516

AnkiDroid/src/main/java/com/ichi2/anki/services/ReminderService.java
#5748 attempted to gracefully handle database re-init from startup auto-sync while the reminder service was running but did not go far enough
That PR handled IllegalStateException but it turns out NullPointerException can also happen in this case.
This widens the exception handling to all exceptions (we really should never crash the app because the reminder had a problem - it's not core reviewing functionality) and should hopefully finally stabilize this area of the code?
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/4ae96958-29b2-4a24-88d7-d0fdc8facc55
```
java.lang.RuntimeException: Unable to start receiver com.ichi2.anki.services.ReminderService: java.lang.NullPointerException: Attempt to invoke virtual method 'int …
```
=> Gracefully handle any exception while building reminder

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java, AnkiDroid/src/main/res/values/02-strings.xml
It should not be frequent, but it is possible to crash if we try to start an external activity and it does not exist. Now if this happens we will notify the user instead of crashing
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/a070f47e-d8b0-41c3-976a-1e797e4267d7
```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.PICK dat=content://media/external/images/media flg=0x10000 }
at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1809)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1523)
at android.app.Activity.startActivityForResult(Activity.java:4226)
at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:6)
at …
```
=> Avoid crash if unable to delegate to external app

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
When you click on mark/flag in the reviewer but the card is not yet
loaded, this used to lead to a nullPointException. This is now
corrected. 
I believe that it's okay if those button does nothing while
we are waiting for the next card.
Takes a slow phone. Open the reviewer. Press the flag button immediately. There used to be an exception. There is none anymore 
Note that this leaves the related problem: when you review a card and
then click on "mark" on a slow phone, it's not clear which card is
marked; indeed, it depends on whether the value of mCurrentCard did
change or not.
One solution would be to set "mCurrentCard" to null once the button 1, 2, 3 or 4 is pressed, to ensure that nothing occurs until next card is loaded.
=> Correcting: onMark/onFlag raises nullPointException

AnkiDroid/src/main/assets/card_template.html, AnkiDroid/src/main/assets/flashcard.css, AnkiDroid/src/main/assets/scripts/card.js
The Flags in the WebView weren't rendering on API<23
This replaces the partially supported emoji with an inline SVG image
https://github.com/ankidroid/Anki-Android/pull/5768#issuecomment-596112068
There was no font on old APIs that had the unicode support necessary to show the flag emoji
I tested this on 6 emulators - all the ones mentioned in the comment here: https://github.com/ankidroid/Anki-Android/pull/5768#issuecomment-596121839
to make sure I got the compatibility right
Support really old devices is difficult 🤷‍♂
=> Render flag as inline SVG for old API compatibility

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java, AnkiDroid/src/main/java/com/ichi2/async/Connection.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/HttpSyncer.java
Connection error information is largely eaten by the app so users don't have a good chance to help themselves if they configure things wrong or there is a sync problem
This gives users more info they can use to self-help, and categorizes cleartext protocol failures as harmless
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/69ac5da1-bb3f-48cf-ba63-6cef9bc7bf4d
```
java.lang.RuntimeException: java.net.UnknownServiceException: CLEARTEXT communication to 220.208.39.208 not permitted by network security policy
at com.ichi2.libanki.sync.HttpSyncer.req(HttpSyncer.java:62)
at com.ichi2.libanki.sync.HttpSyncer.req(HttpSyncer.java:4)
at com.ichi2.libanki.sync.HttpSyncer.req(HttpSyncer.java:2)
at com.ichi2.libanki.sync.RemoteServer.meta(RemoteServer.java:9)
at …
```
=> Give users more connection error information, handle cleartext failure

AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
It seems when I ported the method from anki to ankidroid, I forgot:
1. to add the name of the deck in the set of name of decks.
Here it is. It'll remove timbers.
2. to save the new names in the deck objects once they were computed.
I should note that this did not create any problem. Indeed, it only
meant that:
* duplicates were not found (unless the first duplicate is a parent of
another deck). This is not really a problem, they should not exists
in the first place, and can always be corrected later.
* some decks were seen as missing, but then anki would try to add
them, and then _ensureParents would find all parents and actually do
no work.
I'm using this version of master (to try to understand another problem actually). So I'm seeing whether it works by checking that there is less …
=> Adding missing line

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
Currently, the conf is corrected only when accessed. Which I believe
may be the cause of bug #5523. Indeed, data is corrected, and then
accessed, while it is theoretically possible that data is changed back
to a faulty value during an asynchrone process after correction and
before access.
With this change, data is changed BEFORE conf' is saved; which means
that the value is never faulty.
This correction should become useless for people using Anki 2.16 or
latter, thanks to dae/anki#347.
I should note that currently, the method we use sends both 0 and 1 to False, instead of only 0. I do believe that setting the browser in the wrong order is not a problem that needs to be repaired, especially since the problem should soon disappear for everyone using anki 2.1.16
Fixes #5523
I only tested …
=> Correct conf' when it's set.

AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java
It is possible to crash on import if the collection isn't found
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/77140843-8f1a-404b-a2ec-2d752b9dde1c
```
java.lang.NullPointerException
at java.util.Objects.requireNonNull(Objects.java:203)
at java.util.Arrays$ArrayList.<init>(Arrays.java:3741)
at java.util.Arrays.asList(Arrays.java:3728)
at com.ichi2.libanki.Utils.getImportableDecks(Utils.java:917)
at com.ichi2.anki.dialogs.ImportDialog.onCreateDialog(ImportDialog.java:88)
at com.ichi2.anki.dialogs.ImportDialog.onCreateDialog(ImportDialog.java:20)
at android.support.v4.app.DialogFragment.getLayoutInflater(DialogFragment.java:312)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1298)
at …
```
=> Avoid crashing on import even if collection not found

AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/libanki/ImportTest.java, AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java, AnkiDroid/src/main/java/com/ichi2/anki/AnkiFont.java, AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.java, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ConfirmationDialog.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java, AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java, AnkiDroid/src/main/java/com/ichi2/anki/reviewer/CustomFontsReviewerExt.java, AnkiDroid/src/main/java/com/ichi2/async/Connection.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.java, AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java, AnkiDroid/src/main/java/com/ichi2/libanki/Media.java, AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/FullSyncer.java, AnkiDroid/src/main/java/com/ichi2/libanki/template/Template.java, AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.java
Codacy rejected a PR because I did `var.equals("constant")`
It explains that I must do `"constant".equals(var)` so that instead of
having a nullPointerException, it justs returns false when var is
null.
I decided to follow this advice and create a script reversing equality everywhere
Ensuring that no catch NullPointerException were surrounding the reversed tests. And installing it on my phone (which means I'm not testing JSON anymore)
=> Adds constant string before equal

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java
There are two frequent crashes that show up when AnkiDroid attempts
to show a dialog but the Activity is no longer there. Both have the same
root cause in that when you attempt to show a dialog you have to check
whether it failed to show, and if it did, either notify user / clean up
or (if not necessary) ignore versus crashing
Fixes #5138
For the ReadText crash (which happens on preview mostly) I just ignore it. If they've moved on they don't care about selecting a TTS language
For the sync dialog crash (which happens on auto-sync on startup as a race, I believe) I cancel the task (better than crashing!) and notify the user it was cancelled. If they want to sync they can take action with the new information, and if they don't then it will try again later as I moved the timestamp update …
=> Gracefully handle dialog show failures

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/beolingus/parsing/BeolingusParser.java, AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/beolingus/parsing/BeolingusParserTest.java
Previously, a search of "hello" failed to find a pronunciation on Beolingus named "Hello". This fixes the issue.
Fixes #5810
`.toLowerCase()` is used to compare both the needle and the haystack when string comparing.
Via Unit Tests
Ran pronunciation searches on my personal Android phone. All successful.
* `text` (to test regression from a previous issue).
* `hello`
* `HELLO`
* `Hello`
* `straße` (German)
- [ x ] You have performed a …
=> Fixes #5810 - Beolingus search case insensitivity

AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java, AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java, AnkiDroid/src/test/java/com/ichi2/anki/StudyOptionsFragmentTest.java
Previously, the android libraries handled converting most HTML into a `Spanned`, but `<script>` and `<style>` displayed their inner text as a string.
Fixes #5715
Now, we Regex replace the two tags out of the HTML before we use the Android libraries to convert the string into a `Spanned`.
This removes the tags and their content to provide a better description.
* Unit Tested
----
* Tested on my local Android against the test string: `a<script>a=1</script>a <span style="color:red">red</span>`
Result: As expected
It's likely that we don't need pure HTML parsing for this and we can reuse the converted regex from Anki Desktop. A `<script>` can't contain `</script>` in a string: https://stackoverflow.com/a/22488867.
- [ x ] You have not changed whitespace unnecessarily (it makes diffs hard to …
=> Fix #5715: Hide style/script tag content in deck description

AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java
Clicking an individual sound file did not abandon audio focus when it completed playing, leading to reduced audio volume if another sound is playing.
Fixes #5141
We have two functions `playSound` and `playSounds`. We did not set a completion listener for `playSound`.
We fix this by adding a new completion listener, which will call `releaseSound()` after the optional user callback has completed.
Tested on my Android.
Played a tone, then clicked a "Play Audio" button on a card.
**Before:** Audio stayed at a decreased level after sound completion.
**After:** Audio returned to its original volume.
- [ x ] Your code …
=> Fix #5141: Release resources on audio completion

AnkiDroid/src/main/java/com/ichi2/libanki/Sched.java
This PR brings in changes in the function at line 695 of the desktop Anki scheduler that aren't in Anki-Android: https://github.com/ankitects/anki/blob/master/pylib/anki/sched.py#L695
In other words, this is a minor code change to fix a scheduling bug where cards would be given a smaller interval than shown on the review buttons. This could occur because having a low maximum interval changes the new ivl level that is updated in the database (despite a different interval being shown to the user on the "again/hard/okay/easy" buttons during review, because the calculation logic is separate).
Fixes #5778
I copied over changes from the desktop Anki repository that updates the card's new Ivl from just being an idealIvl calculation to also checking if the maxIvl sets a different level (else Anki …
=> Fix #5778 - Scheduling doesn't respect max intervals

AnkiDroid/src/main/java/com/ichi2/libanki/hooks/AdvancedStatistics.java
Fixes #5289 
Suspended cards are ignored by prediction algorithm.
=> AdvancedStatistics: disregard suspended, etc. cards

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.java, AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicTextFieldController.java, AnkiDroid/src/main/java/com/ichi2/anki/services/NotificationService.java, AnkiDroid/src/main/java/com/ichi2/utils/IntentTop.java, AnkiDroid/src/main/java/com/ichi2/utils/IntentTopNewTask.java, AnkiDroid/src/main/java/com/ichi2/widget/AddNoteWidget.java
If you click twice clickly on a button which opens an activity, this activity will be opened twice. This is the case for example when clicking on a deck name to review it. When clicking on edit from the editor. When clicking on «add note» from the deck browser window. When clicking on «card browser» on the side menu...
This is a problem in particular when you edit notes, because when you ends editing the note, the activity close, and you'll see the previous activity, which is also card edition, with the data of the previous version of the note. If you simply cancel, nothing is saved, and the actual new version of the note is kept, but it's not clear at all to any normal user.
In other cases, it's not a huge problem, it's just slightly confusing to see again card to review when you clicked …
=> Don't open twice the same activity

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
Update setTextSize to use absolute pixels when scaling font size because that's what getTextSize returns the value as
Fixes #5544 
Verified on Android API 25 and 29 VMs
Confirm in this StackOverflow
https://stackoverflow.com/questions/5032355/android-textview-settextsize-incorrectly-increases-text-size
- [ x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ x] You have commented your code, particularly in hard-to-understand areas
=> Fix card browser text scaling

AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java
Anki desktop allows for the following characters in the names of fields and note types:
' " [ ] ( )
The following characters are allowed for decks:
' [ ] ( )
Ankidroid current strips these characters when creating or renaming fields, note types, and decks. This is somewhat annoying when renaming one of these items: even the "Basic (and reversed card)" note type becomes: "Basic and reversed card" with the parenthesis removed.
#5352 
changes the regex used for replacement of characters in the field names, note type names, and deck names. This goes further than #5460 does.
tested on device: Android 5.0.1 LG L33L.
I looked at what characters are currently replaced by the regex and I tested to see which are valid characters as of Anki desktop version 2.1.15. …
=> allow the following characters for field, note type, and deck names: ' " [ ] ( and )

AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
- Wrap getting current SharedPreferences in a method
- Move applying a night mode change into separate function
- Small reformat of comments and whitespace (automatically done by
Android Studio).
This is the no-op part refactoring part of PR #5686. I'd like to get it
submitted separately so that the PR itself (when finished) is smaller.
I have done a little bit of work on PR #5686, where I'd like to implement following system-level night mode settings in Anki-Droid. When writing the PR, I performed some refactorings to make the PR easier, and this PR is the part of PR #5686 that does not change any functions (merely refactors).
N/A
N/A
CI only.
- [ x ] You have a descriptive commit message with a short …
=> Readability improvements in NavigationDrawerActivity

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/libanki/Card.java, AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.java, AnkiDroid/src/main/res/values/02-strings.xml, AnkiDroid/src/main/res/values/07-cardbrowser.xml
Adding in the browser all columns present in Anki.
I'm pretty sure someone asked for it, and I was mentioned because I did add interval. I can't find it anymore.
As in Anki, with the following twists:
* the method to get due is in Cards.java. In anki it's in aqt/browser.py, but we don't literally have AQT, and anyway, it makes totally sens to decide that this is a method related to the card itself.
* the dates are localized. Anki didn't localize the date; I decided to use java DateFormat and let him localize date in Short format.
Open ankidroid with an existing used collection. Find a few cards (new, due, filtered), and ensure that each columns display the same values in Ankidroid and in Anki (assuming the collections are synchronized on both devices obviously)  …
=> All missing columns in browser

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java, AnkiDroid/src/main/res/values/01-core.xml
When I am late and have a lot of review to due, seeing 907 minutes is less clear than seeing 14 hours. So this PR simply simplifies the message to show hours (or days...) instead.
It does so in the deck picker and in the reviewer. In the deck picker, it can show up to (2 y), but I really hope for every one sanity that it will never occurs to anyone. It's implemented only because I used a function which already exists
In the reviewer, it will show potentially "868 days", instead of "2 years". Not because it's hard to implement, but because I really wish that this code would be useless in the entire future of ankidroid users. 
Using the method Utils.timeQuantity instead of directly showing the number of minutes. And creating as similar method for the reviewer.
Create a collection with a lot …
=> Subtitle in DeckPicker indicates hours if more than 60 minutes

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/res/values/02-strings.xml
Out of Memory issues in the WebView Renderer (e.g. large fonts) were causing the application to crash and restart, going to the deck browser. This was listed as a soft crash in the bug report, but was actually killing the PID.
If a card fails once, we reset the WebView and try to render the card again.
If a card has not been rendered, or if the same card fails twice, we fail gracefully and return to the deck browser. We show a Toast to the user explaining that an OOM occurred.
Fixes #5780
We catch the OOM using `onRenderProcessGone()` (API >= 26) and recreate the WebView to allow the application to continue with minor disruption.
Locally on my Android device (Android 9). Placing `crashWebViewRenderer()` inside `displayCardAnswer()`
* A single failure recreates the WebView
* A second …
=> Gracefully handle WebView Crashes

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/libanki/Card.java, AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.java
This solve
https://github.com/ankidroid/Anki-Android/pull/5592#issuecomment-600314471 (no
Bug report associated as far as I know)
The problem was that the anki function to display time uses uses input
in second while ankidroid uses it in miliseconds. So time was
incorrect.
I now have a function taking seconds and another taking milisecond,
and call the former instead of multiplying by 1000L in a lot of part
of the code
=> Correcting due date of cards in learning

AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java, AnkiDroid/src/main/java/com/ichi2/preferences/PreferenceExtensions.java, AnkiDroid/src/test/java/com/ichi2/preferences/PreferenceExtensionsTest.java, AnkiDroid/src/test/java/com/ichi2/testutils/AnkiAssert.java
This bug has been pervasive for some time, and I logically believe that this change fixes it, although I haven't verified this empirically.
A user accessing "Advanced Settings" would obtain an error: `directory_inaccessible`
This was caused by entering the settings, which set a hardcoded default value `sdcard/AnkiDroid` without validation which did not match `getDefaultAnkiDroidDirectory()`
This immediately kicks the user out the app and leaves them in a crash loop. They don't know what the actual value is meant to be (as they never saw the UI, so they can't easily fix it)
Fixes #5097 
Fixes #5510
Partially Addresses #5346 (option can still be set if somehow preferences is the first entered screen, but I think that's logically impossible)
We fix this by setting the preference when we try …
=> Fix "AnkiDroid directory is inaccessible" Bug

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java, AnkiDroid/src/main/java/com/ichi2/libanki/exception/NoSuchDeckException.java
A dynamic deck with `conf` (Deck Options) defined will crash the reviewer.
A dynamic deck should not have deck options, therefore we want to remove them.
Fixes #5708. But I'd either like to avoid closing the issue, or raise some other issues.
* We can improve the exception thrown in the reviewer
* We should try to track down how this happened
This adds a task to "Check Database" to remove Deck Options from any dynamic decks.
1. Force Sync + Download corrupt collection
2. Select corrupt custom study deck and flip card (FAIL).
3. Select Check Database
4. Select same custom study deck and flip card (PASS)
=> #5708 Fix Dynamic Deck with Options defined

AnkiDroid/src/main/assets/scripts/card.js, AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/libanki/hooks/HintFilter.java, AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.java
* Confirm whether selecting the Text Input Field, rather than "Show Answer" on a note type with both `{{hint:}}` and `{{type:}}` is correct. 
* Normally, a `{{type:}}` field does not have this focus initially.
* But, even with focus on the text input field, `ENTER` displays the new card.
* `_relinquishFocus()` is appropriate in cards.js, named correctly (and marked well as unstable). 
* Whether the extraction of some parsing logic is a good first step in taming the complexity of `filterUrl(String url)`, or if there's a better design.
After clicking on a `{{hint:}}` field with the mouse, the WebView took focus and KeyEvents were not sent to the Activity.
The mouse cursor was stuck as a text entry bar when hovering over the WebView
Fixes #5811
* We define a JavaScript function: …
=> Fix #5811 - Clicking hint field blocks key input

AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java
User complaint that exporting a deck reset the deck options to 1.
This also appears to have been the cause of a dynamic deck having options, and therefore being corrupted. 
Fixes #5253
Fixes #5708
We fix this via an inefficient deep clone.
1. New Collection - created on 2.10alpha46
2. Create New Deck
3. Create new options group and assign to new deck
4. Fails - new deck's option group is set to default
5. Load 2.10alpha51
5. Export
6. Passes - deck is still the same
Also tested with default deck and a custom study deck, both were corrupt (database errors on study).
[stackOverflow: How do I clone an org.json.JSONObject in Java?](https://stackoverflow.com/questions/12809779/how-do-i-clone-an-org-json-jsonobject-in-java)
=> Fix #5253 - Deck Options Corruption on Export

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/IntegerDialog.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/RescheduleDialog.java, AnkiDroid/src/main/java/com/ichi2/libanki/Card.java, AnkiDroid/src/main/java/com/ichi2/preferences/PreferenceExtensions.java, AnkiDroid/src/main/java/com/ichi2/utils/FunctionalInterfaces.java, AnkiDroid/src/main/res/values/03-dialogs.xml, AnkiDroid/src/test/java/com/ichi2/preferences/PreferenceExtensionsTest.java
User requested interval data in dialog to assist them in selecting a new interval
Fixes #5595 
We only handle interval data for review cards in a non-dynamic deck.
We add the interval data unconditionally on review, and if there is a single card selected in the card browser.
<a href="https://user-images.githubusercontent.com/62114487/77094321-3764fc80-6a04-11ea-95dc-40b254c6f365.jpg">Review: Review Queue</a>
<a href="https://user-images.githubusercontent.com/62114487/77094316-3633cf80-6a04-11ea-8bed-5b0a5fc725b1.jpg">Review: Non Review Queue</a>
<a href="https://user-images.githubusercontent.com/62114487/77095974-9297ee80-6a06-11ea-9314-215cf315e048.png">Review: 1 day</a>
<a href="https://user-images.githubusercontent.com/62114487/77094314-359b3900-6a04-11ea-81f6-e5b8e4 …
=> Display Interval on Reschedule Dialog

AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java
Our code intends to find media beginning with "_" and only include it when it's valid in the CSS or a formatted answer. This was devised to ensure that we don't export massive and unused CJK fonts.
See: https://github.com/ankitects/anki/pull/114
This didn't work, as we passed in the index of the model, instead of the model ID, therefore we had a null model, which was assumed to return true.
Fixes #5643 
We use a for loop
Tested on my phone. Custom collection with 2 files, one included in a deck, and one not, but with a leading "_".
Before: Deck export contained 2 files and was 3MB  
After: Deck export contained 1 file and was 400KB
----
Original Anki Code: https://github.com/ankitects/anki/blob/862e2b48f06dadf414d171d2cfdc4ac3ad79e7da/pylib/anki/exporting.py#L270-L276
=> #5643 - Filter Additional Media for Export

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
Previewing a card currently performs `showEaseButtons` which requires an ease calculation. This crashes as there is a discrepancy between the "add deck" and the "libAnki sched deck"
Fixes #5756
But the issue contains another bug report (in Reviewer), which isn't fixed by this
The ease calculation depends on the current deck, and is not necessary in the previewer as we don't show ease buttons, we get a crash as the scheduler is pointed at the wrong deck, so don't calculate either.
Note: This only fixes the crash, it doesn't touch the root cause:
We rely on libAnki to get cards for previews, which relies on the current deck for setting certain data.
This information is neither required, nor correct when previewing.
We can't change the scheduler while previewing as we may be previewing …
=> Fixes #5756 - Crash on Template Preview when adding Note with Dynamic Deck selected

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/res/values/03-dialogs.xml
Some users din't feel comfortable about us requiring access to external storage.
Fixes #5740 
We add a dialog explaining that we don't perform any malicious activities with this in order to hopefully alleviate concerns.
=> #5740 - Add Welcome Dialog Explaining Permissions

.travis.yml
Travis has started having intermittent (but mostly failure) results on osx builds, we need to temporarily ignore them so that CI doesn't fail so frequently requiring manual intervention
Upstream macOS instability issue tracked here:
https://travis-ci.community/t/macos-build-an-error-occurred-while-generating-the-build-script/7684/15
Just allowing the failure for now
I have a personal Travis CI instance I use to develop the CI infrastructure for Anki-Android among others, I checked it and it's working: https://travis-ci.com/github/mikehardy/Anki-Android/builds/154483510
Entropy is inevitable
=> Allow Travis CI macOS failures temporarily

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java, AnkiDroid/src/main/java/com/ichi2/utils/BitmapUtil.java, AnkiDroid/src/main/res/values/02-strings.xml
Sometimes, the `rotateAndCompress` method could fail, causing a crash.
Fixes #5513
Instead, we return the uncompressed image, and display both the file size and a warning that some images may require compression.
We do this, rather than displaying an error, as it's easier for a user to take action.
We unconditionally display the file size as it's a useful attribute.
On my Android, both with a sample failure via the debugger and with a normal image via camera.
Note: Compression increased the image size.
=> Gracefully handle Bitmap Compression Failure

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java, AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioView.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/utils/Permissions.java, AnkiDroid/src/main/java/com/ichi2/anki/services/BootService.java, AnkiDroid/src/main/java/com/ichi2/async/Connection.java, AnkiDroid/src/main/java/com/ichi2/utils/Permissions.java, AnkiDroid/src/main/res/values/03-dialogs.xml
Editing a note, selecting "Record Audio", with denied & remembered permissions would soft crash the app.
Fixes #5407 
Explained in #5407
> Define 3 ***transitions*** (between Multimedia UIs):
>
> * Init - initial load
> * UI - Menu Item is clicked, (changing from "Record Audio" to "Insert Image").
>    * Treat this as cancellable
> * Activity - Pronunciation calls "Record Audio" with a known clip to allow for preview and pronunciation recreation. 
>   * This is invoked by the caller, so there's no way to know whether the previous UI is in a valid state. Treat this is non-cancellable.
>
> ----
>
> * Allow "Record Audio" to fail a transition
>   * UI - Failing will keep the application on the previous multimedia UI.
>     * Requires changes to avoid destroying the previous context until the …
=> Fix permission handling in Multimedia editor

AnkiDroid/src/main/java/com/ichi2/anki/MetaDB.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
This review was borderline "I should split this into commits". If you'd prefer this, please let me know.
I'd also love to hear "You should abstract out the whiteboard logic from `Reviewer` and test it", but I doubt it's considered to be a good use of time. 
----
Previously, the whiteboard visible state depended on the enabled state
This caused problems when switching from Night Mode, as it would forget the Visible setting.
Fixes #5065
We now persist the visible state to the internal database, this still depends on the enabled flag.
Previously it did not work on my device.
Now when switching to night mode, the visible status is saved.
=> Persist Whiteboard Visible State

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java, AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivityTestBase.java, AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldControllerTest.java
Cause: #5849
Added additional UI components, which worked when testing on a new screen, but not when re-editing a field with an image (logic exercising this came before logic initialising the view).
Fixes #5856 
Split UI initialisation and functional methods.
Fixed API errors which were previously hidden by: `@SuppressLint( {"UnsupportedChromeOsCameraSystemFeature", "NewApi"})`. Incorrectly assumed to scope the `NewApi` only to the camera functionality.
On my Android, no longer crashes
=> Fix Crash on Previewing Existing Image

.travis.yml
This reverts commit 17aa22017092ba601aa67759884a996d68706d79.
The upstream issue we were working around has been resolved.
macOS builds are functional again and should be required
=> Revert "Allow Travis CI macOS failures temporarily"

AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.java, AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/utils/FileUtil.java, AnkiDroid/src/main/res/values/03-dialogs.xml
We are having problems with users performing check database with insufficient file space. This causes a crash.
Partially #5852 
We discourage the user from performing check database without enough file space.
Nothing normally. This when I reverse the condition,
* Text - preamble feels too long without explaining the issue.
* UI flows  
* Seeing this when immediately opening the app seems too strong and may scare users. Maybe we want a pre-dialog stating on this case stating that the update fixes some issues and it's advised to run it, rather than forcing a check.
This appears on database error (also used by the manual check database button), and on startup.
=> Add File Space Warning before Check Database

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/Models.java, AnkiDroid/src/main/java/com/ichi2/utils/FunctionalInterfaces.java
We added an additional database check inside `fixIntegrity`, which required that all users perform a database check.
This flagged that there were crash bugs in `fixIntegrity`
Fixes #5852 
We modify each check into tasks, and perform each task in its own transaction, rather than running all in the same transaction.
* Check Integrity still works for me
* Added in an additional task which threw an exception. Exception was caught, logged and the process continued as expected.
=> fixIntegrity Refactor / Instrument+continue if field count fix fails

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/SchedV2.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java
We modified `mReportLimit` in #5326 to allow a user to see how many cards they had if there were more than 1000 in a queue.
This had an impact on calculating the number of cards in the current deck, which is required for a sync to ensure that the server and client are consistent.
This caused an inconsistency (as we calculate the proper value), and this meant that a full sync needed to occur if a dynamic deck with over 1000 cards in a queue was selected or a subdeck of the selected deck.
Fixes #5666 
Fixes #5672
This fixes the issue by instantiating a new scheduler with the correct `mReportLimit` for calculating the number of cards in the selected deck.
I have a test collection (SchedV1).
1. Synced with normal deck from Android - worked.
2. On Desktop - filled dynamic deck with ~1700 cards …
=> Calculate scheduler limits for sync using AnkiWeb limit

AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java, AnkiDroid/src/main/java/com/ichi2/utils/HtmlUtils.java, AnkiDroid/src/test/java/com/ichi2/anki/StudyOptionsFragmentTest.java
Previously, a newline was converted into a space, whereas Anki Desktop handles a newline as a newline.
Fixes #5188
We convert newlines to `<br/>` tags, so `context.fromHtml` converts them to newlines.
Unit tested and tested on my Android.
Before: 
After:
After matches Anki Desktop.
It has a scrollbar if necessary.
=> Deck Description: Handle Newlines

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/ImageField.java, AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/fields/ImageFieldTest.java
We previously used single quotes for inserting images, which caused issues when quoting the output in JavaScript.
Fixes #5237
We use single quotes and no trailing slash, which is the same as AnkiDesktop.
Unit Tests.  
Image insertion still works.
=> Made image HTML identical to AnkiDesktop when inserting

AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/res/values/02-strings.xml, AnkiDroid/src/main/res/xml/preferences_advanced.xml
We've had some crash reports where the user did not have a handler for `ACTION_VIEW` on a URL (wat?).
Fixes #5864
We perform this operation in our code. If an exception is thrown, catch it and display the URL so the user can handle this themselves.
Tested with user-defined crash. Still works normally, and displays the following on failure.
The snackbar has a limit on the text which can go into the message. Therefore we only show the URL with limited text.
Relevant: https://www.youtube.com/watch?v=XczIlID_GPM
=> Fix Preference crash when user has no Browser

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/ImageField.java, AnkiDroid/src/main/java/com/ichi2/utils/BitmapUtil.java, AnkiDroid/src/main/java/com/ichi2/utils/ExifUtil.java, AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldControllerTest.java, AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/fields/ImageFieldTest.java
* The image `src` was not being extracted correctly
* Passing in an invalid image to ImageFieldController started a preview, throwing a FileNotFound Exception, which was logged by ACRA
* Passing a null image to BitmapUtil threw an exception, now returns null
Fixes #5874
* We use JSoup instead of Regex
* We avoid logging to ACRA on a regular `FileNotFound`
Unit tests, now displays images on the test data
=> ImageField: Stop parsing images using Regex

AnkiDroid/src/main/res/values/02-strings.xml
A lint warning was caused by having two `%s` formatters in the same string
Fixes #5876 
Fixes the format string by adding positional arguments.
Tested on my device, string still formats correctly.
=> Fix lint warning on format string

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
* Fixes Gestures being disabled after renderer is regenerated
* Fixes various race conditions when the render ends
* Fixes a dialog box for a renderer error being cancelable, not ending the activity as expected.
Fixes #5879
* Gestures: Insert the view at position 0, rather than position 3 (touches appear to be from lowest to highest).
* Fixes race condition accessing `mCardFrame` via atomic variable replacement
* Fixes race condition accessing `mCardFrameParent` inside `onRenderProcessGone` via extracting the constant reference
* Fixes race condition accessing `mCard` via reader-writer lock
* Made error dialog for render process failure non-cancelable
On my device. I can no longer cause a crash due to mashing the answer buttons/gestures due to a race condition.
There is still an unsolved …
=> Various Renderer Crash Improvements

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/res/menu/card_browser.xml, AnkiDroid/src/main/res/menu/card_browser_multiselect.xml, AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java
The Card Browser could not display "Select All" and "Select None" at the same time
The Card Browser did not display "Select All" when no cards were selected
When "Select None" was clicked, the browser remained in Multi-Select Mode
When no cards are *available*, "Select All" should not be visible. *Edited*
Fixes #5464
We add in additional items in the layout:
* New "Select All" in the unselected mode
* Differentiate "Select All" and "Select None" in mutliselect mode.
We combine all previous state changes into a function which takes the current state into account, and sets the "Selection Buttons" to the correct states.
Both on my device, and via unit test
* 0 item deck
* Normal Decks
* Deleting cards so they become 0 item decks
* Adding items to 0 item decks
* Moving items out of 1 item …
=> CardBrowser: Multiple Selection Fixes

AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.java, AnkiDroid/src/main/res/values/02-strings.xml
A NPE was caused by the file import.
A few stack traces imply that ClipData wasn't being handled correctly, we try to pass this into the content provider API and hope this works.
Fixes #5870
* We explicitly handle null.
* We attempt to extract the URI from the clip data.
* We use [Pokémon Exception Handling](https://wiki.c2.com/?PokemonExceptionHandling) to avoid failure.
Untested. My Android still imports correctly.
* Line 84: We implicitly return null if the intent is unhandled, this seems unintentional
* The crash report logging may log far too many problems, not sure about your opinion on this.
* (optional) Ask me to unit test this
=> Fix FileImport NullPointerExceptions and implement ClipData

AnkiDroid/build.gradle, api/build.gradle
Standard dependency updates - trickle-feeding them in to avoid a big batch at once
Current stack of stable versions we can't merge:
- androidx-browser (requires #5665)
- robolectric (requires some changes in #5151)
- appcompat (requires testing because of #5512 among other issues)
- gradle 6.3 (requires a fix for https://github.com/Triple-T/gradle-play-publisher/issues/797 or move from PKCS12 Google Cloud Platform credentials to JSON, I already pinged @nicolas-raoul about that via email)
=> Dependency updates 20200331

AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java
We fix a few race conditions and clean up the code of RenderBrowserQA
Fixes #5891 
Try-catch-continue
Card Browser still works on my phone. Since we're adding catch statements, there should be
=> Fix RenderBrowserQA Race Condition: Crash on no card

AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/ContentProviderTest.java, AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.java, AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java, AnkiDroid/src/main/java/com/ichi2/libanki/DB.java, AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java
We have many async crashes relating to the collection being null, it'll be useful to understand the underlying reason that the collection is null in these cases.
I'm adding this because I can replicate one crash by changing the AnkiDroid directory whilst calculating stats, but I doubt this is the path which was taken to cause the crash.
N/A
Adding additional string param to method
Anki still works, tests still pass
=> Add Diagnostic Logging to Collection.close

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java, AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java
We fix errors from the "Help" URL for onboarding: selecting a deck with no cards.
We also fix a TTS help URL
N/A
We add a method in AnkiActivity to handle no browser
* Tested on my android
* ⚠️ 
* We use string constants with concatenation rather than formatting, but android ignores trailing spaces in resources.
* The current string constant uses a chinese comma, rather than an English comma. I didn't want to fix this here, seems like a crowdin job.
https://stackoverflow.com/questions/1587056/how-to-keep-the-spaces-at-the-end-and-or-at-the-beginning-of-a-string
Previous PR: #5867
=> Additional "No Browser" fixes and refactorings

AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.java, AnkiDroid/src/main/java/com/ichi2/libanki/Models.java, AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java
This default note type was missing from ankidroid
As in Anki.
The rebase onto main, to take into account last change which did conflict in this PR. In particular 1193ecfaf7f18b03a14e1f897951cde4d64c4521 by myself; because now names are localized.
gradlew/travis.
I started a fresh ankidroid on a virtual machine, checked that «Basic (type in the answer)», created a note, and tested it. It did work.
=> add type-in-the-answer note type

AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/ContentProviderTest.java, AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java, AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java, AnkiDroid/src/main/java/com/ichi2/libanki/AbstractSched.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/SchedV2.java
The initial problem that I had was some automated test having unexpected result. Mostly because there is an empty constructor in Sched. And that actually, what it really meant is that SchedV2 should never have inherited from Sched. Indeed, it reuses absolutly no code and no variable from Sched, and it's not semantically a specific kind of Sched.
It also corrected the name of SchedV2, so that it's the same as in Anki. Which changes nothing as this name is never used here nor there.
I simply created an abstract Sched class, from which both Sched and SchedV2 inherits. This abstract class declare as public abstract all public classes from Sched that are also in SchedV2. This way, we have in a proper java way what we already had in Python: no inheritance between both classes, but being able to …
=> Abstract sched

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
From a crash report: it seems that OnCreate can be called twice, with no resources on the second call. This causes a crash in ACRA init.
Instead, as the logic assumes that onCreate() is only called once. We can just log and return and let Android do its thing.
I presume this is from an uninstall, as from reading, this happens when the resources directory doesn't exist.
Fixes #5887
Check for null resources and return 
None 🤠
=> Don't re-initialise AnkiDroidApp if resources is null

AnkiDroid/build.gradle
This fixes a deprecation noted in the play publishing plugin we use
This will unblock the dependency update of gradle-6.3 as there is an incompatibility between play publisher plugin in PKCS12 credential mode and gradle 6.3
=> Switch to JSON for Google Play credentials

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java, AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java
We get a crash if trying to render a card with no flag in the properties
Fixes #5900
We apply two fixes for this: 
1. Don't crash if we don't have a flag set and assume no flag.
2. If cards cannot be rendered due to them being deleted, remove them from the browser search results and deselect all cards.
Unit tested, browser still works on my phone
##Defects
* It would be ideal to reorder the selections when a note is deleted. This is not implemented as it may add significant latency  (I can easily select 30k cards) and the data strucutres currently in use don't seem appropriate for writing an efficient algorithm.
=> CardBrowser: Fix crash on deleted card

AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.java
Signed-off-by: landinggao <gaoyingjun@xiaomi.com>
On device without system web browser, we don't want user use web browser. But if there some other third part apk for some reason has web browser capability, the restriction on using web browser will be invalide. 
When to check web browser, only when there is system app has web browser capability, we think the device support web browser.
Even there is third party apk has browser capability, can't open external link.
Test on mobile and Xiaomi AI teacher.
=> restrict to use system web browser

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java, AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivityTestBase.java, AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldControllerTest.java, AnkiDroid/src/test/java/com/ichi2/testutils/AnkiAssert.java, AnkiDroid/src/test/java/com/ichi2/testutils/MockContentResolver.java, AnkiDroid/src/test/java/com/ichi2/testutils/MockCursor.java
Crash caused due to being unable to decode the following intent.
```
Failure delivering result ResultInfo{who=null, request=1, result=-1, 
data=Intent { dat=content://com.simplemobiletools.gallery.provider/external_files/data/data/com.simplemobiletools.gallery/files/storage/emulated/0/Pictures/Screenshots/[REDACTED] typ=image/png flg=0x1 }}
to activity {com.ichi2.anki/com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivity}: java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow. Make sure the Cursor is initialized correctly before accessing data from it.
```
Fixes #5909 
We catch any exceptions, or show a toast on known failure
Unit Test. Couldn't repro on my device. Image insert still works correctly
=> Fix Crash on Unreadable Gallery Image

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
Fixes #5518 
Ensuring that the card sent to be updated is the card which has been edited. This is theoretically always the case, unless the user review a card so quickly after the end of edition that onActivityResult is called after nextCardHandler and not before it.
Putting this code in a VM. Opening the reviewer, opening the editor, editing a card, seeing that the change are saved into the collection.
I didn't test that the original problem does not occur again because it seems hard to reproduce it in the first place voluntarily. 
-------------
doInBackgroundUpdateNote is called in a single place, doInBacground,
when the type is TASK_TYPE_UPDATE_FACT. This type is actually used in
two places, both cases in `onActivityResult`. I'll first …
=> Correcting #5518

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/res/menu/card_browser.xml, AnkiDroid/src/main/res/menu/note_editor.xml, AnkiDroid/src/main/res/values/02-strings.xml
The note editor has a "Copy card" option which actually copies the note. Both that option and the "Add note" option use action and string resource names which say "card" instead of "note".
Now with less mess-with-translated-strings action!
Fixes #5553 
Global find/replace of the incorrect action names.
Added a new string resource for "Copy note" text.
Tested on a physical device. Can only confirm correct string for English language.
=> Change copy-related terms from "card" to "note"

AnkiDroid/build.gradle, build.gradle
@david-allison-1 not sure if this is related to #5513 (I think that was one where a ContentResolver cursor failed on a png file?) but it includes a bump to exifinterface 1.2 where they made some noise about similar things https://developer.android.com/jetpack/androidx/releases/exifinterface#1.2.0
This also includes a major change for us - a bump to appcompat library which had problems before (#5526) but should fix #5507 while hopefully not triggering #5512
=> 20200403 Dependency updates

AnkiDroid/src/test/java/com/ichi2/libanki/UtilsTest.java
@Alyxvance was attempting to follow my guidance to patch up PR #5868 but was blocked by a unit test failure on windows in a test I wrote - we exercise windows now so I'm not sure why the CI job didn't catch it but I was able to replicate the problem
Use the built-in path generator from URI to handle all the escaping and quoting necessary on windows, hopefully it works on Linux, CI will tell us
On a local windows 10 environment I had laying around
Always stack overflow, let's admit it
=> Fix windows path issues in UtilsTest

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.java
Changes to make heavy check mark and Down Arrow in type cards styleable
line 740 taken from anki desktop
Fixes 
https://github.com/ankidroid/Anki-Android/issues/4841#issuecomment-604230121
Testet by my own on all aviable versions untill 2.9alpha56 + on Android 7 an 10
- [x ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x ] You have commented your code, particularly in hard-to-understand areas
=> Make heavy check mark and down arrow styleable

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
#Pull Request template
AnkiDroid takse more than a minutes to start on my phone. Actually, profiling show it takes more than a minute to load the note type (I've got note type with >400 card types).
It seems that the maximal cursor size is slightly more than a mega bite. 
https://github.com/ankidroid/Anki-Android/issues/5921
On my phone, it reduces loading from >1 minute to <20 seconds.
I ensured that a megabyte is used, so that the number of query decrease and the speed increase.
I'd be curious to see if any alpha tester get problem (in which case it must be reverted) or if one mb is enough for every body.
Installing on my phone and seeing that I don't need to wait a minute regularly.
I was trying to see how to use sqlite4java in AnkiDroid. It seems more efficient. But I don't fully …
=> Use chunk of 1mb in cursor

AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java, AnkiDroid/src/main/java/com/ichi2/libanki/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/SchedV2.java
My collection contains hundreds of decks and subdecks. Burying the top level deck was a night mare. It literally tooks more than a minute (Checked it while debugging). Burying, undoying, suspending, all recomputed the list of cards, and took over a minute.
This simple change, copied from anki's code, reduce this time to two seconds.
Actually, four seconds, because for some reason, when I click on a deck, the computation of "Sched.reset" is done twice.
Exactly as in anki. Precomputing and saving the atble sending names to the deck object.
By the way, this sohuld probably saved in DeckManager directly, and be discarded each time the collection is reset. But I'm not going to introduce changes that are not in anki and would be non essential. 
Putting it on my phone, and using anki normally.
I …
=> Scheduler reset performance improvement

AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java
`getCol()` is used all over the place, and performs unnecessary IO
Maybe #5938 
We hit `getCol`:
https://github.com/ankidroid/Anki-Android/blob/8a79dd14b6d7e1b865a466d4dc561914ba312f59/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java#L1457-L1459
which is called each time `onPrepareActionMode()` is called.
Don't hit the filesystem unless we need to.
Ran on my Android, still works.
Ran 104 unit tests, all pass
Added in https://github.com/ankidroid/Anki-Android/commit/60d6e07ee61305ab5fbd26036bb8f78fd843faa2#diff-423fd800e2b0faa58e3bfa60cc67b718R88
Implementation: https://github.com/ankidroid/Anki-Android/blob/ad85320486accb900c553ea57d6476f6ffb8e6ac/AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java#L213-L231
=> Speed up getCol(context)

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
When adding cloze references ({{c1::, {{c2::, {{c3::, ... ) in Anki desktop, the reference increments automatically based on the largest reference it finds after searching in every field. AnkiDroid currently only searches in the currently selected field. As explained in #5652, this is annoying when adding cloze references to notes with more than one {{cloze::}} field (which is recommended in the [cloze deletion section of the Anki Manual](https://docs.ankiweb.net/#/editing?id=cloze-deletion) to handle nested cloze references)
Fixes #5652 
The code is largely the same, but instead of performing the search on just the currently selected field, it now iterates through the fields of the current note …
=> Search for cloze references in all fields

.travis.yml
There is a new "LTS" release of Java (1.14) which I'd like to canary for forward-porting
There is also a test release of Android API R/30 which I noticed we currently fail completely on with database access issues, which I would like to start a canary on - it could also show if we have problems with the API restrictions changing per comments in #5918 
I have added instrumented test runs for JDK1.14 and APIR so we can expose problems, both are set to allow failure so it won't affect PR velocity
I have a personal Travis CI instance hooked to my AnkiDroid fork so I can develop things like this: https://travis-ci.com/github/mikehardy/Anki-Android/branches
This should be passing now so I know I won't blow up the project: https://travis-ci.com/github/mikehardy/Anki-Android/builds/159314705
I …
=> Add Android R and JDK1.14 to CI

AnkiDroid/src/main/assets/scripts/card.js, AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/res/values/03-dialogs.xml, AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.java
Previously, only some data was URL Encoded when sent from JS to Java. When an invalid sequence (a single `%`) was entered, then the app would crash due to the decode failure.
Fixes #5944
We both fix this encoding in the JS, and if invalid data comes in for any reason, we show an error.
Unit Tested with data. No longer crashes my Android.
=> CardViewer: Correctly Decode typed text in <input>

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
Improving ankidroid code quality. Shorter code and avoiding useless computation.
selected() returns the id. Current is defined as get(selected()). So
doing current.getLong("id") takes the id, get the deck, and then takes
the id.
Put in my "merged" branch, which I run on my phone with all PR I made
=> current.getLong("id") to selected

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/Models.java
This was first push as the Pull Request
https://github.com/ankidroid/Anki-Android/pull/5929 Given the number of change, I am creating a new branch and a new Pull Request, so if it does not please ankidroid mainteneurs, the previous
work is not lost
My AnkiDroid is really slow to start. According to profiling, the
slowest part is reading the database content. In particular, reading
the json configurations. Those are JSON files which may easily takes
more than a MB and does not fit into the cursor.
Note type are not required to show the GUI. So I ensure they are
loaded asynchronously. Furthermore, since loading is database heavy, I
ensure it get done only once the GUI thread has accessed everything it
needs.
In order to ensure that the models are accessed only once they are
loaded, I create …
=> Loading models after GUI is shown

AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.java, AnkiDroid/src/main/res/values/10-preferences.xml, AnkiDroid/src/main/res/xml/preferences_advanced.xml
This allows 'Cloze Deletion' to be shown in Landscape mode.
Fixes #5533
We pass a flag to the IME to disable the Extended Text UI
On my Android with GBoard
https://stackoverflow.com/a/23367951
=> Add Disable Extended Text UI Preference

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
Loading my top level deck is long on my phone. Ten seconds. I want to improve that. On my collection and my phone, scheduler's reset take 4 seconds, so I want to avoid doing it in a case where it's absolutely not necessary.
Reset is done twice when reviewer is opened from deck picker. This is because:
* to check whether the deck can be reviewer, reset is done to see the
correct number of card
* when reviewer starts, it calls reset to check whether there are
actually cards to review/create the queue
Both actions are useful, but in this case it's a duplicate. Since
starting to review a deck from the list of deck is actually an action
performed often, it's important that it gets optimized, and thus I add
a notion of "reset done" to the intent, to state that reset does not
have to be done …
=> only call Sched.reset() once on scheduler opening

AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
Making ankidroid faster. 
Currently, scheduler's reset spend 1 second and a half in the class sublist iterator. This is entirely useless, as removing it virtually does not increase code complexity and decrease the time of this method.
Creating an explicit loop over indexes instead of using a sublist
Doing it in my "merge" branch, using anki, and ensuring everything works
=> Remove sublist from Decks.parents

AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
First, I want to emphasize that, on my collection, I am spending two
seconds in the method Long.valueOf(long). Of those two seconds, 1.1
are spent in the compare method in _fillLrn. So it's a not a change
for fun, it's a real time saver I want to do here.
Secondly, Long.valueOf().compareTo uses Long.compare if both values
are long. So we are transforming long into Long to immediately
transform them into Long. That's totally pointless. Using the static
method directly is thus quicker
Thirdly, the sorting could be made in sqlite directly for more efficiency. But I don't do it in this PR as it would diverge from upstream anki. Instead I'm doing a PR in anki and I'll do a PR here once the upstream has an answer.
In my merge branch, using ankidroid and ensuring it still works.
=> Make sched fillLrn comparison quicker

AnkiDroid/src/main/java/com/ichi2/anki/stats/OverviewStatsBuilder.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/DB.java, AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java, AnkiDroid/src/main/java/com/ichi2/libanki/Models.java, AnkiDroid/src/main/java/com/ichi2/libanki/Note.java, AnkiDroid/src/main/java/com/ichi2/libanki/Tags.java, AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
When ankidroid scheduler reset, it spends a lot of time in queries. While investigating it, I realized that most queries where not "prepared statements". If my basic notions of database are right, it means that we were loosing uselessly an huge amount of time by compiling each query over and over again and just replacing the deck id.
So, in this PR, I simply transformed each query of sched v1 into prepared statements. And I can confirm that on my phone, it makes ankidroid quite faster. Saving seconds when loading a deck with hundreds of subdecks.
Can you please let me know if there is anything wrong with this approach ? Any problem I missed ? A reason why prepared statements were not used before.
If there are known, then I'll do a similar work on scheduler V2 and on other queries in the …
=> schedv1 prepared queries

AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/ContentProviderTest.java, AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioClipFieldController.java, AnkiDroid/src/main/java/com/ichi2/libanki/Card.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/DB.java, AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java, AnkiDroid/src/main/java/com/ichi2/libanki/Media.java, AnkiDroid/src/main/java/com/ichi2/libanki/Models.java, AnkiDroid/src/main/java/com/ichi2/libanki/Note.java, AnkiDroid/src/main/java/com/ichi2/libanki/Tags.java, AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java, AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.java
Reduce amount of boilerplate code in project
Available on all API levels:
> In addition to the Java 8 language features and APIs above, Android Studio 3.0 and later extends support for try-with-resources to all Android API levels.
https://developer.android.com/studio/write/java8-support
N/A
Automated lint fix from Android Studio (except 1, which involved moving a nullvariable, then an auto fix)
Finally, manual undo of the whitespace changes.
Unit, Android, and tested on my machine
https://developer.android.com/studio/write/java8-support
=> LINT: Replace try..close with try-with-resources

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/java/com/ichi2/libanki/Note.java, AnkiDroid/src/test/java/com/ichi2/libanki/NoteTest.java
I want to access this functionality from the Visual Editor without a reference to FieldEditText.
This also likely improves performance, taking the Regex.Compile from an instance variable into a static.
Paves the way for #1377
Part automatic, part manual refactoring
Tested on my Android, no issues.
Added Unit Tests (all the existing code was good, I incremented the result by 1)
=> Extract and modify: GetNextClozeIndex

AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java
Each test calls AnkiDroidApp.onCreate which plants a Timber config
This causes a lot of log noise, and slows down the tests
Before:
3m19s
3m14s
After:
2m51s
2m52
25 second reduction
https://stackoverflow.com/a/17278496 - no `Application.onDestroy`
=> Speed up tests by 25s

AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/ACRATest.java, AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/NotificationChannelTest.java, AnkiDroid/src/main/java/com/ichi2/utils/WebViewDebugging.java
#5970 requires that `AnkiDroidApp.onCreate` is run on the UI thread. This broke tests.
N/A
Application.onCreate is guaranteed to be run on the UI thread, so this
fixes tests to do this.
Ran tests, they now pass
https://stackoverflow.com/a/30390340
https://stackoverflow.com/a/30390340
=> Fix androidTest on real device

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
Some actions can take more than 15 seconds on my phone. This is mostly
due to a huge number of deck (and a bad way of dealing with a lot of
deck in scheduler)
Buttons are still activated. That can be shown because if you click on
"bury" the list will open once the new card is loaded. The problem is
that it's not clear at all to me (even when I look at the code) on
which card the action are taken. If I press twice on bury, will it
also bury the next card ? is the action ignored ? Does the scheduler
tries to bury/review/suspend... multiple time the same card ?
This is even more worrysome when I click on the undo button, where
I've no clue whether the click is registered or not, and whether
multiple undo will be done...
I remove buttons while they can't be used because the card is not fixed, …
=> Reviewer: Action Bar buttons disabled while DeckTask working

AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ModelEditorContextMenu.java, AnkiDroid/src/main/res/values/17-model-manager.xml
Allows user to enable/disable the "Remember last input" setting of an Anki field. This is known as the "sticky" value in the Anki database structure. This PR adds a button on the "Edit Fields" screen, though there is no visual indication of the current value of the setting. 
Fixes #5353 
When the context menu item is tapped, it checks the current boolean value and changes it to the other. Possible enhancements for this PR:
1. A visual indicator (checkbox? other icon?) could be used to indicate the current value of "sticky"
2. Call toggleStickyField() from the "paperclip menu" that is to the right of a field when adding a field (similar to the "Frozen Fields" add-on on desktop Anki
On device: LG L33L Android 5.0.1
1. [Anki Database …
=> Enable toggle sticky feature on fields in field editor

AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.java, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java, AnkiDroid/src/main/java/com/ichi2/utils/DeckComparator.java, AnkiDroid/src/main/java/com/ichi2/utils/DeckNameComparator.java, AnkiDroid/src/main/java/com/ichi2/utils/NamedJSONComparator.java
There were a lot of duplicate and almost duplicate code in
AnkiDroid. Often the comparator class was put in some random place,
where it could not easily be found to be used again when needed. So I
tried to make this slightly more consistent by creating three
comparators. One for name of deck. One for json objects representing
decks. One for json objects with a name.
I am also correcting a small bug relating to sorting of decks. The
sorting in allSorted was wrong because A::A should appear before A9,
while it sorted it after. (This is because it considered ":" as a
character, and not a separator).
Luckily, this did not cause real trouble since this method is not even
used to sort decks in the deck picker interface.
By putting all comparators together, in utils, so that they can be easily …
=> Uses classes to sort deck names and deck objects

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
When buttons are deactivated, gestures are not. I use the new the new `mControlBlocked` to ensure that gestures are not considered.
If I suspend a card and it takes a second to do it. If durin this second I do a gesture to edit a card, I see that the card opened ni the editor is the card that is not yet loaded. So the action is registered and applied with a card that is not yet seen.
My "merge" branch, and trying to do actions as explained above
=> Deactivate gesture when controls are blocked

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
I'm still trying to reduce card loading time. During loading, there was a function which took .7 seconds (probably because I've got a note type with 400 card types). This function was simply used to check whether the bury/suspend note button should be displayed.
Note that another reasonable approach would be simply to remove this function from the main UI thread, since there is no way it is actually needed on loading time. But decreasing it's computation time (and probably making the code simpler) seems nice too.
I reduced it to something that I can't even see in the profiler by replacing the explicit loop by a really simple sql query. 
The first commit will probably need to be removed. It's useful only because I'm waiting for another PR to be merged, and needed one type change in the …
=> Bury suspend direct query

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java, AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java, AnkiDroid/src/main/java/com/ichi2/utils/DeckNameComparator.java
This PR does multiple very related changes.
* It takes path and basename from upstream, make them public and uses them where possible to make code more readable
* It uses array instead of list for paths. So that we avoid a useless transformation.
* It cache name splitting, which is actually a very time-consuming operation. (7 seconds in loading the list of decks are spent on splitting deck name on my collection. Mostly because in order to sort decks, we must split them first.)
* the methods `_isParent` and `_isAncestor` were wrongly implemented. In particular in cases where the ancestor was longer than descendant, it may return `true`. 
I should note that if and when you merge this PR or https://github.com/ankidroid/Anki-Android/pull/5943 the other will need to be rebased. Because this …
=> Cache deck split

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
DeckDueTree is a long method. And it uses a lot of database access, so even in background, it is costly. Worse, sometime, it is useless. I.e. when the method is executed while the deck picker itself is gone.
I simply ensured that this method can be cancelled; and that leaving the deck picker cancel it.
I had to do some other small change for efficiency. The commits describe them.
I also copied documentation comment from SchedV2 to AbstractSched, because it's more consistent.
On my phone;
* load a deck
* goes to deck picker
* immediately load a deck
In profiler, check that the deck due tree ends sooner (e.g. does not call _groupChildren)
I learned there is no way to force a asynctask to be forced to be killed, I've to check myself for cancellation. Which is not such a big commit actually, …
=> Cancel due tree when possible

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/IField.java, AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.java, AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.java, AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java
Previously, we were using the field values from the existing model in the database when editing fields.
Now, we use the values shown in the UI.
Automated lint fixes were also executed.
Fixes #5992
Pass the field values and the model ID into NoteService, rather than using the model from the card.
Unit Tests
Tested on my device, works as expected.
=> In-Memory Multimedia Editor

AnkiDroid/build.gradle, AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.java, AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java, AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.java, AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java, api/build.gradle, gradle.properties
This involved handling some timer differences, and accessing Context differently
The only troubling part was in AbstractFlashcardViewerTest - there's a thorny timing
issue there which I solved by coarsely hacking in a sleep
@david-allison-1 I'd like to remove that sleep if possible but I couldn't think of a quick way to sort out exactly how, and I didn't want to spend too much time on test-specific work vs app enhancement. This is not a high priority for me to fix, but something for the unconscious to chew on and if you come up with something elegant, awesome. Otherwise even if it's flaky I'm just going to bump up the sleep hack until it's reliable
=> Upgrade to robolectric 4.3.1 with new Looper mode

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/TtsParser.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.java, AnkiDroid/src/main/java/com/ichi2/libanki/Media.java, AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java, AnkiDroid/src/main/java/com/ichi2/libanki/hooks/ChessFilter.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/FullSyncer.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/RemoteServer.java, AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.java
The same idea than a previous commit which put constant before equals instead of after.
I'm actually surprised that it's not signaled as a risk automatically.
(I saw this because I was dealing with equalsIgnoreCase recently, with deck name. Not because I found any actual bug here
=> equalsIgnoreCase constant string before variable

AnkiDroid/src/main/java/com/ichi2/libanki/DB.java, AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
When a deck is picked, the set of decks were saved, while this present no interest. 
I also replace one occurrence of "deck" by collection, and remove another occurrence of Deck in a place where it made no more sens.
I realized that is because upstream was incorrectly ported. `select()` should indicates that the configuration is changed, but there is nothing in the deck collection itself which is changed.
In upstream, saving the deck collection is done thanks to `self.changed` and not `setMod`
Merging in the branch I use to run ankidroid.
=> Save deck in collection

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
Correction two of my mistakes.
Burying note worked in a basic collection, but not when I actually use ankidroid. The difference is that it did work correctly on note type with two cards.
It seems I did two mistakes.
getControlBlocked did disappear from one condition. Probably due to a
rebasing during a conflict of PR.
"count() ... limit 1"  does not limit counting to one element, but the
number of count result to 1. Which is not what I intended. This
version ensure that I indeed get 0 or 1. (The query actually worked on
note type with two card type, as it is the case with basic and reverse
card type, with which tests are done.)
Testing it on note type with more than two cards and with a single card
=> Correct bury/suspend note

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
Unless I don't understand anything about SQL, the query 
```sql
UPDATE col SET mod=mod
```
is entirely useless.
Intuitively, I would assume that the idea was to do
```sql
UDPATE col set mod=?
``` 
with value `mod`.
Except that here, the java variable is a boolean while the sql column
contains an integer.
The other action is also useless: `mod` is read and then put
back. This would maybe make sens if there was synchronicity issue; but
there should be none here. And anyway, `lock` is called only once,
after which `setMode(false)` is called anyway.
It's in my "merge" branch on my phone. No particular test were done here.
=> Removing the method lock which was useless

AnkiDroid/src/main/java/com/ichi2/libanki/sync/HttpSyncer.java
Flagged by Damien a long while back. We currently make a new TCP/IP connection per HTTP(s) request to AnkiWeb. 
Should get a decent perf gain from this, especially for media syncing and chunking.
Fixes #4568 
We reuse the same OkHttpClient
Syncing still works. Took about 2-4 minutes off my sync time (15/17m -> 13m).
Tested using methods described in the PR. Only 3 connections were used.
* `OkHttpClient` isn't closeable, only the response object is.
* https://github.com/ankidroid/Anki-Android/issues/4568#issuecomment-613723018 - how to test.
=> Reuse Connection when Syncing

AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java
The only ponit of this reset was to compute the count. Given that the
count is done again in recalculateCounts, this became useless
I tested it by syncing my collection after putting it in my merge branch
=> Remove full reset in syncer

AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
This will allow to avoid forcing the use of an actual listener when no action are required before/after.
This has not been tested, as this code is not currently used, even if I expect it to be used quite soon
=> Allow listener to be null in collection task

AnkiDroid/build.gradle
Task often hung on machine inside Android Studio. I couldn't replicate by commandline. It was previously only sometimes annoying, but it must have added an hour to yesterday's testing overhead.
BUT: There was no need for it if I was just deploying to my Android, and I don't run tests for coverage yet.
Fixes #6009
I can set a variable in `local.properties`, this felt cleaner architecturally than an environment variable, but the code's not too nice.
Tested with and without variable set via `println`
false - false
true - true
truu - ture
[unset] - true
https://stackoverflow.com/questions/21999829/how-do-i-read-properties-defined-in-local-properties-in-build-gradle
[The hidden cost of code coverage](https://jeroenmols.com/blog/2016/09/01/coveragecost/)
=> Allow optional disable of jacocoDebug

AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/libanki/HttpTest.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/java/com/ichi2/anki/web/CustomSyncServer.java, AnkiDroid/src/main/java/com/ichi2/anki/web/HostNumFactory.java, AnkiDroid/src/main/java/com/ichi2/anki/web/PreferenceBackedHostNum.java, AnkiDroid/src/main/java/com/ichi2/async/Connection.java, AnkiDroid/src/main/java/com/ichi2/libanki/Consts.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/FullSyncer.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/HostNum.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/HttpSyncer.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/RemoteMediaServer.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/RemoteServer.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java, AnkiDroid/src/test/java/com/ichi2/libanki/sync/HttpSyncerTest.java, AnkiDroid/src/test/java/com/ichi2/libanki/sync/RemoteMediaServerTest.java
* https://github.com/ankitects/anki/commit/ae46bfa8d18778a7312828c3fd9b8d6c6e4672d6#diff-be58d55ab11f38bc77a9e44496f1d2a8
* If the hostNum is corrupt, the user can't sync, and we don't currently provide a means to wipe it. How should we handle this?
* A malicious sync server likely can silently rewrite the sync url as we're performing `String.format` on user-provided data going into the URL.
This is only for AnkiWeb, we still do not support this for custom sync servers. 
This is for a few reasons:
* Debate over whether to keep a separate media sync URL, or do Anki did in the linked commit.
* Changing servers - when to reset the hostNum? Much more likely to get into a situation where we have an invalid hostNum and no way to fix it.
Fixes #4921
Careful refactorings and unit tests. Once we …
=> Use AnkiWeb Dynamic Sync Url

AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
I did check that `counts(Card)` is called in a single place, and after cheching that card is not null.
This allows to simplify the code slightly. I believe that it is still a correct way to port upstream, when we take into consideration how java and python differs.
This is still done in order to simplify the "reset" PR, and moving it into simpler PR
=> simplifying counts

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DiscardChangesDialog.java
To be used in the visual editor, just cherry picking off a smaller safe change
----
Note: Could the following wording:  
`Close and lose current input?` be changed to read "Close and lose unsaved changes"? Current input on the template editor implies the whole template to me.
=> NF: Extract DiscardChangesDialog

AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
There were NullPointerExceptions in https://github.com/ankidroid/Anki-Android/pull/6026 which were due to the fact that the list was found to be null instead of empty. Empty list can be dealt with easily; but .isEmpty on a null pointer is a bad idea.
So this PR will ensure that this does not occur again in future improvement. (Or I could also test whether those value are null everywhere, but i don't think it would be really interesting to do)
=> Scheduler's list are empty instead of null at start

AnkiDroid/src/main/res/drawable/ic_cloze_black_24dp.xml, AnkiDroid/src/main/vector_source/cloze_icon.svg
My own work. Created with Inkscape. Intended for the visual editor. 
GPL-3 for this project, but placing this under the public domain.
----
Inkscape: text tool - convert to path - use the measure tool and fix lines to same length via guides. Delete Guides. Center & Align. 
@mikehardy You were right, this was unexpectedly fun to do once I got over the initial hurdle. 
https://github.com/ankidroid/Anki-Android/blob/53c12a3045d8ff460b22dc8500d621f5e3608b41/AnkiDroid/src/main/vector_source/cloze_icon.svg
=> Add Cloze Icon

AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
The variable `sHadCardQueue` was not commented, or documented, and made little sens in the first place since it could be set in a background called and used in another one. That is, the only reason for it to work was that all (but one) call to scheduler's `getCard` went through the CollectionTask. 
So putting instead this variable directly in the scheduler makes far more sens as far as semantic goes. Even better, this variable was already in the scheduler, so we just needed to use it instead of having two redundant variables !
This is, of course, a not subtle way to justify the introduction of `deferReset` in the codebase. (note that I followed your's name advice)
=> Removing `sHadCardQueue`

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.java, AnkiDroid/src/main/java/com/ichi2/libanki/Models.java, AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
I added a method to clone deep an object in our JSON library. It seems I forgot to use it in some place. This is repaired
=> Use deepclone instead of toString/model creation

AnkiDroid/src/main/java/com/ichi2/anki/reviewer/CardMarker.java, AnkiDroid/src/main/res/drawable/ic_star_white_bordered_24dp.xml
Reported in https://github.com/ankidroid/Anki-Android/issues/5806#issuecomment-616482609
>  is it possible to change the color of the star when the button is hidden (i.e. only in the menu)? For me, it is rendering white on a gray background, which makes it difficult to see.
This is visible in the 'Plain Theme'
Before: 
Add a border to the icon used in the topbar
After:
=> Add Border to 'Mark' icon in topbar

AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtonStatus.java, AnkiDroid/src/main/res/xml/preferences_custom_buttons.xml
The reschedule button has an incorrect default from preferences
Fixes #6054
Change the default in prefs xml
Note via code comment where in code things should be in sync
=> Set reschedule app bar button to show never by default

AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
Sched and SchedV2 has some duplicate code. I didn't remove it before because I only looked at deduplication done in upstream. Given that it's not in upstream, I should have looked at it separately
=> remove setReportLimit Duplicate

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.java
Non-functional prep work for #6052
Also removes code from `AbstractFlashCardViewer`, which is a side-goal of mine.
Don't mind if this is squashed, commits are small to ensure they're readable in review.
=> Extract Viewer Commands to ViewerCommand class

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
Caught in the alpha that we're logging file:// and http:// requests from cards to logcat.
This was intended to catch problematic signals used in IPC between the WebView and AnkiDroid (such as the invalid unicode crash on typing answer), not all resources.
=> NF: CardViewer - Only log URLS in debug mode

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java, AnkiDroid/src/main/java/com/ichi2/utils/WebViewDebugging.java
The `onCreate()` code caused exception when clashing with ACRA which used WebView in a
separate process.
We already perform this init before the WebView is needed, this was intended as an optimisation.
Fixes #6070
* Remove the offending code. Add a "here be dragons"
Untested, but worked previously without the code here. 🤠 
Alpha testing is great
Premature optimisation is the root of all evil.
=> Fix Crash: Remove WebViewDebugging in App.onCreate

AnkiDroid/build.gradle
The NDK is only used when assembling releases.
It is used there to strip symbols in binary libraries (like requery) so we generate
APKs that are as small as possible.
This may cause failures if you attempt assembleRelease and don't have
the right NDK version installed.
Also note that if you have 'ndk.dir' in your project local.properties
you should remove it, that is obsolete per Android documentation and
may also cause failures.
=> Bump NDK version

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerKeyboardInputTest.java, AnkiDroid/src/test/java/com/ichi2/anki/ReviewerKeyboardInputTest.java
In preparation for #6052 
One functional change: `answerFieldIsFocused` now returns false if the answer field does not exist. This is because I didn't want to handle UI logic in the tests (at least a 14x reduction in speed by avoiding Android here)
I didn't test the tests 🤠
=> Reviewer: Add Unit Tests for KeyUp/Down Events

AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
As in upstream. For some reason it was not already done. It's a purely syntactic change.
=> use _deckLimit everywhere

AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java, AnkiDroid/src/main/java/com/ichi2/libanki/utils/SystemTime.java, AnkiDroid/src/main/java/com/ichi2/libanki/utils/Time.java, AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java, AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java, AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.java, AnkiDroid/src/test/java/com/ichi2/testutils/MockTime.java
https://github.com/ankitects/anki/commit/5a5be92d099f28985e62631164dc3c0d3f59be35
https://github.com/ankitects/anki/blob/5a5be92d099f28985e62631164dc3c0d3f59be35/anki/schedv2.py#L1175
User report: Lapse intervals were incorrect.
This was caused by two issues: using the wrong delay config (meaning that good wouldn't graduate the card), and missing a change in Anki which added an additional bonus when pressing Easy.
Fixes #6082
TDD. Extract dependencies, get a broken test, and fix it.
Only unit tests
=> SchedV2: Fix incorrect intervals on Lapsed Filtered cards

AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.java, AnkiDroid/src/main/java/com/ichi2/libanki/Card.java, AnkiDroid/src/main/java/com/ichi2/libanki/DeckConfig.java
Value is written (only other grep for "timer"): https://github.com/ankidroid/Anki-Android/blob/5d0eb69ca943b646a1141ba808e7426e443202e5/AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.java#L270
I've previously tested the options, and no other crashes were found on other properties.
Anki 2.1.24 converted this to an boolean, reverted in 2.1.25, but we need to coerce it back to avoid a crash.
Fixes #6089
Fallback to boolean parsing if integer parsing fails. Remove unused method
On my device, both on 2.1.24 collection and my normal collection
=> Handle DeckConfig."timer" as boolean

AnkiDroid/build.gradle, api/build.gradle
Weekly dependency updates.
JUnit is obviously test-only
Okhttp is interesting, the current stable Java8 build introduced a fairly deep change and OkHttp had to respond to it in order to avoid crashes under very specific conditions. Android 10 did likewise causing OkHttp some compatibility pain with how it responds to URLs with underscores.
=> Dependency updates 20200430

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/java/com/ichi2/anki/debug/DatabaseLock.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.java, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/res/values/03-dialogs.xml, AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerCheckDatabaseListenerTest.java, AnkiDroid/src/test/java/com/ichi2/async/AbstractCollectionTaskTest.java, AnkiDroid/src/test/java/com/ichi2/async/CollectionTaskCheckDatabaseTest.java, AnkiDroid/src/test/java/com/ichi2/testutils/CollectionUtils.java
`beginTransaction` was throwing `SQLiteDatabaseLockedException`
This meant that `endTransaction` threw in Check Integrity.
Fixes #6067 
We handle this case in Check Database, and add in a new "Database Error" screen to handle "Database Locked".
Tested on my phone, and unit tests. No longer crashes.
=> Don't crash Check Database when Database is locked

AnkiDroid/src/main/java/com/ichi2/libanki/template/Template.java
this should have been in https://github.com/ankidroid/Anki-Android/pull/6073/commits/2b3d8b54eec5bcc4c3d761367555452228b72f53
This variable is no longer used, so should be removed.
=> remove a useless variable

AnkiDroid/src/main/java/com/ichi2/libanki/template/Template.java
Please accept either this PR or https://github.com/ankidroid/Anki-Android/pull/6107 but not both.
The difference is that the current PR follow anki code (see 
https://github.com/ankitects/anki/commit/9bb0348fdd41b1b50fa07b64405c72c3ff263f98 )
The problem here is that it changes the way ankidroid behaves. Indeed Anki only consider the replacement "{{=<% %>=}}" while AnkiDroid considered any replacement of the form "{{=FOO BAR=}}".
The other PR still accept any replacement, while this PR only accept the very specific replacement accepted by anki. 
I've not yet tested this, mainly because I don't know what is the way we want the feature to be implemented, and so I don't know what is the expected result.
=> Correcting #6103 by following anki

AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java
If Don't Keep Activities was on, the fragment `onCreate` would be called and this would infinitely open the Filtered Deck Options
Fixes #6113
We only set the variable to open the deck options if the activity was created for the first time
On my phone ⚠️ Not with split screen.
=> Fix Filtered Deck Options Infinite loop on Don't Keep Activities

AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java
Previously, `releaseSound()` was called too early, this stopped the third sound from being heard.
Fixes #6111.
We only call `releaseSound()` if the execution is not deferred to a secondary media player
⚠️ This area is extremely hard to test due to using native media players.
So only a note to test has been added rather than unit tests.
Tested on my device manually
=> BUGFIX: Play All Audio on card when viewed

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/res/values/02-strings.xml, AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.java, AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java
**Error Text**
For reference, Anki shows:
```
The input you have provided would make an empty question on all cards.
The first field is empty.
You have a cloze deletion note type but have not made any cloze deletions. Proceed?
```
**Cloze**
Anki displays a dialog asking if the user wants to proceed, from a UX perspective, I'd much rater block the action, even though it is currently permitted by libAnki as it doesn't seem like a logical user action
Fixes #5893
Make the error dialog variable, and block adding cloze deletions
Some very pretty unit tests, if I do say so myself
Also tested on my phone, can no longer add empty cloze notes, and the errors are better.
Adding {{c1::XX}} to the "Extras" field will allow addition of a note. Introduced in #5652, have left an ignored test to ensure …
=> Improve "Error Saving Note" and block adding empty Cloze Deletions.

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.java
#5913 implements a system-app-only requirement for the web browser on restricted learning devices, but implements it in a way that imposes that restriction even for non-restricted browsers
#6109 - non-restricted device could not load web content
This makes the "is the browser a system app?" check only apply on restricted devices
I also added copyright header, fixed whitespace, and changed the variable + method names to contain the feature's intent in the name
- Local `./gradlew jacocoTestReport` on this one after visual inspection a few times
- API28 emulator get shared decks with Chrome installed: worked (correct)
- API28 emulator w/Chrome disabled: got a toast saying no browser (correct)
- API28 emulator w/Chrome disabled, Firefox installed as user: worked (correct)
Nothing special, …
=> Only restricted devices require system browser

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
This reverts commit 029afff7
Fixes #6119 - Eraser was not set to visible after drawing
~~Was asked to revert, but I feel we can get away with just removing line 442, will test.~~
EDIT: From my understanding `.getIcon()` has changed between setting the visibility due to the buttons being disabled, it appears to cache the previous alpha value. Looks good to go.
=> Revert "don't put "undo" to color enabled"

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java, AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.java, AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java, AnkiDroid/src/main/java/com/ichi2/async/Connection.java, AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/FullSyncer.java
in 2.10beta2, we still have issues with the collection being closed, which crashes tasks started by the reviewer, this is probably fixable now, but there's not enough logging to determine why this occurred and I'd rather properly diagnose it, rather than patch around the underling issue.
Ref: 
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/de3c036d-852f-4f19-a3df-15e4ed8851b8 , but this crashes at various points due to the null database.
This additional logging isn't definitive, but should hopefully be sufficient to be able to understand the UI flow from logs.
🤠
=> NF: Added Logging around collection close

AnkiDroid/src/main/java/com/ichi2/libanki/template/Template.java
This is a follow-up to https://github.com/ankidroid/Anki-Android/pull/6108#event-3302478237 , following the advice of https://github.com/ankidroid/Anki-Android/issues/6103#issuecomment-623731205
I should note that, since some variable can never be assigned after initialization anymore, there is no need to keep so many function to deal with the change of values. Actually, a lot of variables can become static and final. 
I don't expect to change the computation time in any way. This won't solve any bug. I just want to simplify the codebase by removing things which became useless.
=> Remove {{=

AnkiDroid/src/main/java/com/ichi2/libanki/template/Template.java, AnkiDroid/src/test/java/com/ichi2/libanki/template/TemplateTest.java
This corrects #6123. See the bug report discussion for more context.
Anki up to 2.1.17 does not deal correctly with a conditional field
containing the same conditional field. AnkiDroid didn't
either. However, it still worked as long as all conditions evaluates
to true, and broke only when a condition evaluates to False. If a
condition evaluated to False, an error message would be raised.
I am copying back this rules. All evaluations to True still products
the same result as before. A conditional evaluated to False produce an
error message.
I personally am not convinced at all that this is relevant. Saying
"you can used a conditional nested in the same conditional only when
all conditionals evaluate to true" is more confusing than saying that
this feature is not supported. However, as I'm …
=> Allow conditional field inside itself

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DialogHandler.java, AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.java, AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java, AnkiDroid/src/test/java/com/ichi2/utils/ImportUtilsTest.java
We URLEncode filenames, and CJK characters are 9x the size when this happens. This allows them to easily blow up when imported with "File path too long"
Fixes #6137 
Truncate the filename before import. We do this at the end, not at the middle.
Unit tests, I can now import `好好好好好好好好好好好好好好好好好好好好好好好好好好好好好好好好好好好好好好好好好好好好.apkg`
=> Allow import of files with long Unicode Names

AnkiDroid/src/main/java/com/ichi2/compat/customtabs/CustomTabActivityHelper.java, AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java, AnkiDroid/src/test/java/com/ichi2/compat/customtabs/CustomTabActivityHelperTest.java
Some CustomTabs implementation will throw: SecurityException: "Binder invocation to an incorrect interface". If we encounter this problem, then we should use the fallback implementation.
Fixes #6142
Try..catch..fail gracefully
Unit Tested 🤠
=> Handle corrupt CustomTabs implementations 

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.java
Previously, imports displayed URL encoded strings instead of the Unicode characters
URLDecode or fallback
Tested on my machine. `好.apkg` now displays after trying to import it
=> Improve display of imported filename

AnkiDroid/src/main/res/layout/my_account.xml
Toggle to show password
Fixes #5825
Suggested feature is not available in stock android, but implemented in
material design library in TextInputLayout and TextInputEditText.
However their behavior details are slightly different from default EditText
(e.g. hint moves to the top of input vs disappearing) so both inputs must
be changed for consistency.
Go to login screen, input password, toggle visibility
Tested on emulator api 16 and 23 (could not download 15) and real device api 29
=> Add password visibility toggle on login screen

AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java, AnkiDroid/src/main/java/com/ichi2/libanki/template/Template.java, AnkiDroid/src/test/java/com/ichi2/libanki/template/TemplateTest.java
Fixes #6149
There's a trivial crash in the template PR we just merged this fixes it
Fixes #6149
This fixes the crash and adds a NotNull annotation to the method crashing so hopefully others won't stub their toe on it
@david-allison-1 kindly provided a bisect and unit test ready to go! Incorporating it showed the bug and proved the fix
Null sucks
=> Avoid crash if conditional is not found

AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java
Fixes a crash when the collections is exported with time data while using V2 scheduler.
When the dummy collection is created, it uses the StdModels. Those are initialised with their field's names being localised with the application's context language. Currently the _addDummyCollection() method, that is used during export, tries to add a single note while using the "Front" field. That field can't be found e.g. on german devices, when StdModels is using e.g. "Vorne" as field name.
Fixes #6145 
Just take the same string that is used during field creation to set the item for the dummy note.
Using the Android Emulator APIs 19 & 25. Imported the collection, that crashed on my phone. Reproduced the crash in the emulators. Applied patch and recompiled. Patched version doesn't crash (neither with …
=> use localised field name during collection export

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/test/AndroidManifest.xml, AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.java, AnkiDroid/src/test/java/com/ichi2/anki/NullCollectionNoteEditor.java
Fix NullPointerException if back is pressed before the collection is loaded
Fixes #6158 
Don't crash
TDD: Red, Green, Commit, Push
=> NoteEditor: Allow Exit before collection load

AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.java, AnkiDroid/src/main/res/values/03-dialogs.xml
A bug occurred where we displayed a import dialog before we requested permissions, which overlapped the dialog. Clicking "Add" crashes, as we had no storage permissions.
Fixes #6157
Block the input, show a toast, and load the `DeckPicker`, which shows the storage dialog, followed by the permissions request.
We could do this better in the `DeckPicker` handler and persist the operation, but we're somewhat constrained for time, it's a complex operation, and asking the user to perform the operation again isn't a huge ask
On my device:
* Launching with permissions shows nothing
* Launching from launcher with no permissions shows no toast, followed by permissions dialog
* Launching from file browser with no permissions shows toast, followed by permissions dialog
* Launching from file browser …
=> Block file import if no storage permissions 

AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/libanki/ImportTest.java, AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/libanki/MediaTest.java, AnkiDroid/src/main/java/com/ichi2/libanki/Note.java
Since #5566, unit tests would fail if run in a non-English locale due to the field names changing
Fix the tests (using field index instead), and improve the error message
Unit tests still pass
=> Use localised field name in Instrumentation Tests

AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
I had a problem with syncing to anki-sync-server. It looked like learning cards, whose date was in the past, weren't counted properly.
Not applicable.
Current fix resets cutoff date and all cards in the past are calculated as learning ones.
I've tested it manually - based on current change and SDK 28. After patch, syncing works as expected.
=> Fixed error with counting card in learn state

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TagsDialog.java
An ACRA crash occurred as the listener was null.
Visually, this should never have occurred as the listener is set on the next line. It might not be possible to trigger by a human, but it's fixable
Fixes #6174
Move the listener from a setter to a constructor parameter
Tested functionality on my phone, no visible change.
Effectively nonfunctional but I'd like to confirm this in an alpha release
=> Remove possibility of TagsDialog NullPointerException

AnkiDroid/src/main/java/com/ichi2/libanki/template/Template.java, AnkiDroid/src/test/java/com/ichi2/libanki/template/TemplateTest.java
Tags in tags weren't rendering correctly, this showed up with a reported bug in expansion of tag that should have turned into a type-answer tag
Fixes #6176
I applied the same transformation applied to section rendering to make it iterative until it determined no new replacements happened
With a test based on user report, used for the original bisect from @david-allison-1, integrated into TemplateTest
Performance changes without a wide ranging test suite are fraught with regression danger.
=> Iteratively render tags

AnkiDroid/build.gradle, AnkiDroid/src/main/java/com/ichi2/utils/Assert.java, annotations/README.md, annotations/android/text/annotations.xml
Contract annotations allow us to write contracts for methods such as: "null -> true" (TextUtils.isEmpty()), this allows further lint warnings on Android framework methods, which should be annotated, but aren't yet.
These should be written inline when possible, but we also include a folder of annotations for our external dependencies
Further instructions for external annotations are detailed in README.md
Should be compile only, All tests pass.
https://www.jetbrains.com/help/idea/contract-annotations.html
https://www.jetbrains.com/help/idea/external-annotations.html
=> Allow JetBrains @Contract annotations

AnkiDroid/src/main/res/values/theme_light.xml, tools/find-broken-strings-variables.sh, tools/lib/increase-version.awk, tools/release.sh, tools/update-localizations.py
The translation and publish release tools (shell and python stuff) were a bit creaky, failing on missing sub-utilities, not handling errors well, and not de-linting known problems with translations
Related to #6160 although it would not have fixed that directly
I de-linted the release shell script thoroughly for modern shell conventions and put some nice error handling in when utilities are missing 
De-lint and fix up the translation error finder and hook it in the python translation update script (while fixing upstream translation issues in crowdin)
After this is merged, translations need a resync and we should do a release soon, as Finnish translation has an error that will likely cause a crash for them until we release a fixed translation
Ran release script with the side-effects of …
=> Publish changes

.travis.yml
forgot to update the fingerprint in the ignore section for API R
but it is still intermittent and it should not fail builds
=> Ignore API R even after adding LOCALE arg

tools/release.sh
The ankidroid changelog is sourced from the ankiddroiddocs repo (with any merged PRs there auto-published to the official ankidroid.org site) but there is a copy in this repo that is shipped with the app
This copy was diverging from the authoritative ankidroiddocs source
Fixes #6197
First I altered the release script to be more robust with regard to verifying that all the required tools were available (github-release requirement might be a surprise for instance, and now asciidoctor would otherwise surprise people)
Then for public releases (the ones that get changelog entries) I verify that the authoritative ankidroiddocs repo is checked out in parallel with Anki-Android as a sibling directory, and that when we render it we get a valid entry for the version you are publishing
Lots of …
=> Render the official changelog for public releases

.travis.yml, AnkiDroid/lint-baseline.xml, lint.gradle
We want to expose when the lint results change vs current baseline, but
we can't hard fail on them because they are subject to false-positive just because
line numbers changed
For the smaller set of things that we classify as release blockers we do want
CI to check and hard fail for
Also updated the current debug baseline
This should help with the CI failure seen on #6138 which was not related to that PR
=> Vary lint config debug vs release, CI allows debug lint

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/res/values/03-dialogs.xml, AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java
Starting the CardBrowser via the 'Card Browser' action item with no permissions would previously crash.
Fixes #5930
Now we show a permissions dialog from the DeckPicker.
Tested via unit tests, and on my device.
I've left a TODO in, because I feel the reduction in code duplication would slightly help maintenance, but `IntentHandler` isn't well tested, and it's a lot of effort in a critical part of the code for a slight gain.
Some unit tests take significantly longer to get right than the code itself.
=> "Card Browser" action item: Display DeckPicker if no Permissions

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/async/Connection.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/FullSyncer.java
Logging for #6208 - my theory is that the decklist didn't get refreshed, but it's also useful to know if the full sync succeeded.
Had a small test, then added some more logs 🤠.
Debug logging doesn't work too well here, as the sync progress logging spams the logs
=> Logging: Full Sync and Deck Picker Refresh

AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java, AnkiDroid/src/main/java/com/ichi2/libanki/utils/SystemTime.java, AnkiDroid/src/main/java/com/ichi2/libanki/utils/Time.java, AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java, AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java, AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.java, AnkiDroid/src/test/java/com/ichi2/testutils/MockTime.java
See: #6083 (previous PR)
Related: #6082
A time dependency in Utils wasn't mocked, causing a unit test to fail. Therefore the previous PR got reverted.
This adds:
https://github.com/ankidroid/Anki-Android/commit/7f4a41b07191a6f4e2fd6cc3d6cd9e784fb57a3d
=> SchedV2: Fix incorrect intervals on Lapsed Filtered cards [Take 2]

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/res/values/10-preferences.xml, AnkiDroid/src/main/res/xml/preferences_gestures.xml
I am accepting a financial contribution for this feature request
A user has requested that link clicks do not trigger the "touch" gestures.
Fixes #6141 
Complex : we can get a `HitTest()` from the browser, but only inside a touch handler.
So, add the touch handler, filter to only the events that we want, and stop gesture processing on events where the `hitTest` was a link or an image with src.
Tested on my phone. Also tested with option off to remove regressions
=> Block Tap/Touch Gesture when hint/linked clicked

.gitattributes, AnkiDroid/build.gradle, lint.gradle
@mikehardy You mentioned that there was a comment above the following lines, but I don't see anything. This needs the line: `NewerVersionAvailable` added to `noinspection`
```yaml
//noinspection GradleDependency 
implementation 'com.squareup.okhttp3:okhttp:3.12.11'
```
Based on a discussion in #6205, we currently have more important issues picked up by lint than performance penalties.
This removes 875 lint warnings. We should eventually re-enable this once we have lint errors close to, or nearer to zero.
I changed my personal config to mark these as 'Weak Warning'
Ran the lint check `./gradlew lintDebug` before and after. Failed less the second time.
=> Remove 'SyntheticAccessor' from lint check

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java, AnkiDroid/src/main/res/values/10-preferences.xml, AnkiDroid/src/main/res/xml/preferences_appearance.xml, AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserNonAndroidTest.java
Many users want the previous behaviour of hiding filenames in the card browser.
Changed in revision: decdc6239ef267d4e8f2c1451c41e301a2479f9d
Fixes #5987
I've defaulted this setting to false (don't show filenames), as this was the default before AnkiDroid 2.10.x
Tested on my phone, works as expected. Also added unit tests.
=> Add Option: Display filenames in card browser

AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java, AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.java
You can unbury cards via the Deck Picker's long-press menu, which does not change the selection.
This goes via method: `unburyCardsForDeck(DeckIds)`, which is not the active deck, our code assumed we wanted to unbury the selected deck
Fixes #6200
Partial revert of e0b5f7bd357978a4ab45faddeb1a6e2045719ab0
Unit tests
=> Allow unbury of non-selected deck

AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.java
A service has no `baseContext`, so `registerReceiver` threw. See linked issue.
Fixes #6214 
Use the application context instead.
Tested on my phone and modified code, can now take the branch without a crash
=> Fix widget crash if external storage not mounted

AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java, AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.java
Handled in Anki Commit: https://github.com/ankitects/anki/commit/13c54e02d8fd2b35f6c2f4b796fc44dec65043b8
> preventing emptying is harder - operations like suspending
don't expect remFromDyn() to fail
Fixes #6228
Follow upstream
Unit Tests
=> SchedV1: Don't filter learn cards

AnkiDroid/src/main/AndroidManifest.xml, AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/java/com/ichi2/anki/contextmenu/CardBrowserContextMenu.java, AnkiDroid/src/main/res/values/01-core.xml, AnkiDroid/src/main/res/values/10-preferences.xml, AnkiDroid/src/main/res/xml/preferences_advanced.xml
This allows the user to disable the card browser context menu.
This commit also changes the menu to make it localizable. This is based on the system language.
Fixes #6226
We can disable the menu via defining an activity alias, then disabling it in the system.
According to StackOverflow, this is persisted until uninstall/reinstall but it's unknown whether this affects updates.
It doesn't matter, as we perform the check on startup.
On my device. Localisation on the context menu item now works
https://stackoverflow.com/questions/14142101/how-to-create-disable-intent-filter-programmatically/14142215#14142215
https://developer.android.com/guide/topics/manifest/activity-alias-element.html
https://stackoverflow.com/questions/22949754/is-packagemanager-getcomponentenabledsettings-persistent-betwee …
=> Add Preference: Disable "Card Browser" context menu

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtonStatus.java, AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ReviewerUi.java, AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerCommandTest.java, AnkiDroid/src/test/java/com/ichi2/anki/ReviewerKeyboardInputTest.java, AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.java
I follow the idea given in https://github.com/ankidroid/Anki-Android/pull/6224 . Given the feedback I received, I don't expect this PR to be accepted, but it was quick to do and to test, so I thought I'd still give it a try.
There are three ways to block buttons. Not blocking (i.e. buttons are
activated), quick blocking and slow blocking. Buttons are grayed only
if we expect the blocking to be slow. I.e. when we need to recompute
the queue because the user decided to undo/bury/suspend or just loaded
the deck. Otherwise, we expect the next card to load quickly, and so
can block the buttons without graying them. This will ensure that the
buttons does not blink.
Note that loading the next card can sometime be slow, so it's still
not a perfect solution.
Users sees buttons blinking/flickering …
=> Trying to remove blink during review

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java
Ability to decrease daily limits in custom study and consistency with desktop
Fixes #5615, #5388 
Allow negative inputs - same as on desktop
This was added to desktop in commit [59b9c361 in anki repo](https://github.com/ankitects/anki/commit/59b9c361ac7e4b7fec269e9372a384e21bd7bed1). This works by
allowing negative numbers in input and effectively the same change is made
in this commit.
A interesting side effect - you can go negative with number of cards to
review. For example if you have 1 new card to review you can decrease
this number by 5. It will display as if you had 0 cards to review, but
to get back to 1 you need to increase number of cards by 5 instead of 1.
Anki desktop behaves same way so I am leaving it as is.
Emulator api 16 and 28
General ideas:
- Increasing works
- …
=> Allow decreasing daily limits in custom study

AnkiDroid/src/main/java/com/ichi2/anki/services/BootService.java
`BootService` would crash if external storage was `ejecting`. We ignore this error and stop execution
Fixes #6239 
Try..Catch
Untested 🐮👦
=> Fix BootService crash if collection is not available

AnkiDroid/src/main/java/com/ichi2/libanki/Media.java
Effectively non-functional, takes a few array copies out of the media check
=> PERF: Improve Media check speed (array size)

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/res/menu/card_browser_multiselect.xml, AnkiDroid/src/main/res/values/07-cardbrowser.xml
It's unintuitive to have one action only on single-press
Since it's the default operation, it didn't seem sensible to have it in the visible action bar - it's very likely to become invisible during the mutliselect phase.
On my phone, happy to add unit tests if you see value in them
=> Card browser: Add "Edit Note" to multiselect

AnkiDroid/src/main/assets/flashcard.css
I was trying to solve https://github.com/ankidroid/Anki-Android/issues/6245
Ideally, I'd love to port
dae/anki@1450d1ca078ed2578defdc54572296bda7cc9267.
It seems that our browser don't recognize the css command "filter";
it's hard to believe as it's far from new, according to
https://www.w3schools.com/cssref/css3_pr_filter.asp but here it is.
Instead, I decided to imitate what LaTeX already does, put a white
background. That's not beautiful, but at least the content can be read.
=> In night mode, add a white background to latex's svg

AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.java, AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilsLanguageRegressionTest.java
Please check the tests to see if you're happy with breakages if the language is changed
I noticed that English was no longer a selectable language
Adds English back in
On my device, and with regression tests.
English is a language
=> Add English back to Language list

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/res/values/07-cardbrowser.xml
Allow a user to search all decks if there was no results for a search
This is makes the 'Card Browser' context menu item much more effective.
Fixes #5159 (I feel it's in a better manner, but your call).
We use a snackbar: 
⛔ Please reject this and ask me to add a few unit tests (in a direction of your choosing).
=> Card Browser: "Search All Decks" button if no results

AnkiDroid/src/main/java/com/ichi2/libanki/LaTeX.java
If you add some LaTeX code to ankidroid and the image is not yet compiled, you just see an error because image is not loaded.
Instead of a broken image, showing the original LaTeX seems to be a good solution.
FIxes #4597
By keeping the LaTeX
Opening ankidroid, creating a card with some LaTeX code `[$]3[/3]` (on a collection which does not already have it, and ensuring that I see "$3$" (which is indeed correct LaTeX) instead of a broken image.
This idea seems straightforward. It would have helped me a lot. But for some reason, I never thought of it before seeing @dreamflasher's idea while I was looking for another bug report.
=> Tex instead of error

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/res/values/02-strings.xml, AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.java
From a user report: They're requested to fill in more fields even if they've filled in them all: https://groups.google.com/forum/#!topic/anki-android/MmJz1XzIyIk
Now, we explain that the card template is likely busted, and how to fix it.
Unit Tested. Quick check on my phone for good luck
=> NoteEditor: Improve error on invalid template

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java, AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.java, AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.java, AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.java
If you currently change the language in AnkiDroid, the change won't really take effect in the GUI. Nearly all strings will still be in the Android system's default language.
With this PR I provide my partially working solution, as I seem to not get any further and want to provide the code so I can get some feedback and/or someone else can have a look at it.
This is also intended as an answer to Mike Hardy, who talked to me in the forums: https://groups.google.com/d/msg/anki-android/m3fhLy2RcZg/2Z-XDNx_BwAJ
Partially fixes #4729 
API levels 24 and lower will be fully localized. The language setting is applied to the whole application.
API level 25 and above will be localized on the main screen (DeckPicker, Settings) but the chosen GUI language won't apply to other activities.
For APIs <= …
=> Fix changing the GUI language from the system default

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
This was mentioned in #6266 and seems like a reasonable action to take
We get a second application launched to perform the sending of ACRA reports, and we don't want this to perform our normal setup code.
Maybe #6266
Don't init the app after analytics/ACRA/Timber if we're launched from ACRA
Tested on my device. No crashes
https://github.com/ankidroid/Anki-Android/issues/6266#issuecomment-633161123
=> Don't perform app init init if launched from ACRA sender

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
sort languages alphabetically, ignoring upper/lower case
add comment on exception handler
Make each language show up in the preference's list in their own language, sorted alphabetically. Also adds a comment for PR #6138 that was merged a little bit quick. :)
Fixes #6251 
Also supersedes/closes #6252 
Gets the display name of each locale, localized with itself.
Changes TreeMap <String, String> to TreeMap <String, List<String>> and change the way the data is stored, so it automatically gets sorted correctly.
Compiled and tested in emulators, APIs 28 and 16. Works
=> display languages in preferences using their own language

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardAppearance.java
Night mode in Anki for Desktop introduces a new CSS class for styling cards incompatible with AnkiDroid. This in turn neccessitates very hacky and verbose CSS for consistent styling of night mode (sometimes impossible), instead of styling for night mode in Anki or for night mode in AnkiDroid.
https://docs.ankiweb.net/#/templates/styling?id=night-mode
This change introduces such compatibility (BC/FC) and only potentially breaks things if users have already tried to hack around the incompatibility for both night modes; nonetheless, in virtually all cases, the resulting CSS should be a lot simpler.
=> Introduce night mode compatibility with desktop Anki
