ankidroid/Anki-Android

AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.java, AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilsTest.java
=> Enable 'Odia' language

lint-rules/src/main/java/com/ichi2/anki/lint/rules/InconsistentAnnotationUsage.java
Minor documentation change
Based on discussion in: https://github.com/ankidroid/Anki-Android/pull/7964#discussion_r549125238
There is also a hierarchy in the inspections panel.
Display this so the developer can find it in the list without the search
Improves on #7020
=> Docs: InconsistentAnnotationUsage: Improve Explanation

AnkiDroid/src/main/java/com/ichi2/libanki/LaTeX.java, AnkiDroid/src/test/java/com/ichi2/libanki/LaTeXTest.java
This Port Anki#d933d7774f4209e497fb912b387ea7adec7ebf42 and should increase accessibility
=> NF: html image gets alt text

AnkiDroid/build.gradle, build.gradle, lint-rules/build.gradle
=> Dependency updates 20210120

AnkiDroid/src/test/java/com/ichi2/libanki/MetaTest.java
=> Test: Ensure test DB access is in memory

.github/workflows/lint.yml
Using the 'lint' job was agreed to be an acceptable solution: https://github.com/ankidroid/Anki-Android/issues/7735#issuecomment-731155219
Fixes #7735
Let's see if CI likes it
=> CI: Run unit tests on Lint Rules

AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java, AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.java
Port of https://github.com/ankitects/anki/commit/ef7b0b1e820ca80a5ddd7c0ba590b6e90184afff
Fixes #7934
Unit tested
=> SchedV2: Allow very small delays

AnkiDroid/src/main/res/values/02-strings.xml
Had this PR done a while back - never submitted. Whoops
Got a reminder on the mailing list
=> NF: Fix typo in email text

AnkiDroid/build.gradle, api/build.gradle
Standard dependabot dependency updates
CI only
=> Dependency updates 20210205

AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.java, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/DeckConfig.java, AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckDueTreeNode.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java, AnkiDroid/src/main/java/com/ichi2/libanki/stats/AdvancedStatistics.java, AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.java, AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.java
This change decks so that dyn/std is used more often as function, for clarity
=> NF: Use isDyn/isStd more

AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java, AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.java
They will be extended in future commits to deal with descendant of filtered decks
=> NF: test _ensureParent

AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.java, AnkiDroid/src/test/java/com/ichi2/libanki/CardTest.java, AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.java, AnkiDroid/src/test/java/com/ichi2/libanki/ExportingTest.java, AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.java, AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java, AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.java, AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.java
#8095 mentions that we don't check for deck descending filtered deck. Doing so require changing the method creating deck. In this case, using the factorizing method in test is going to be REALLY useful
=> NF: uses addDeck and addDynamicDeck more widely in tests

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java, AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.java
For the sake of readability of commits related to #8095, I first factorize plenty of getDecks into decks variable
=> NF: factorize Decks in createCustomStudySession

AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
=> NF: add comment on NameMap

AnkiDroid/build.gradle, lint-rules/build.gradle
=> Dependency updates 20210302

AnkiDroid/src/main/res/values-ar/04-network.xml, AnkiDroid/src/main/res/values-ar/10-preferences.xml, AnkiDroid/src/main/res/values-de/04-network.xml, AnkiDroid/src/main/res/values-de/10-preferences.xml, AnkiDroid/src/main/res/values-eo/10-preferences.xml, AnkiDroid/src/main/res/values-fr/10-preferences.xml, AnkiDroid/src/main/res/values-hu/01-core.xml, AnkiDroid/src/main/res/values-hy/06-statistics.xml, AnkiDroid/src/main/res/values-hy/07-cardbrowser.xml, AnkiDroid/src/main/res/values-hy/10-preferences.xml, AnkiDroid/src/main/res/values-it/04-network.xml, AnkiDroid/src/main/res/values-it/10-preferences.xml, AnkiDroid/src/main/res/values-it/11-arrays.xml, AnkiDroid/src/main/res/values-or/02-strings.xml, AnkiDroid/src/main/res/values-or/10-preferences.xml, AnkiDroid/src/main/res/values-pl/10-preferences.xml, AnkiDroid/src/main/res/values-pl/18-standard-models.xml, AnkiDroid/src/main/res/values-pt-rBR/01-core.xml, AnkiDroid/src/main/res/values-pt-rBR/02-strings.xml, AnkiDroid/src/main/res/values-pt-rBR/03-dialogs.xml, AnkiDroid/src/main/res/values-pt-rBR/06-statistics.xml, AnkiDroid/src/main/res/values-pt-rBR/07-cardbrowser.xml, AnkiDroid/src/main/res/values-pt-rBR/10-preferences.xml, AnkiDroid/src/main/res/values-pt-rBR/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-ru/01-core.xml, AnkiDroid/src/main/res/values-ru/04-network.xml, AnkiDroid/src/main/res/values-ru/10-preferences.xml, AnkiDroid/src/main/res/values-zh-rCN/10-preferences.xml, docs/marketing/localized_description/ankidroid-titles.txt, docs/marketing/localized_description/marketdescription-pt-BR.txt
=> Updated strings from Crowdin 20210302

AnkiDroid/build.gradle, AnkiDroid/proguard-rules.pro, AnkiDroid/src/main/AndroidManifest.xml, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java, AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupMetaTest.java
Crop broke on Android 11, bring in the uCrop library to fix it
Also fix an issue with cropping existing images in the process
Fixes #7232
After much investigation I settled on using an external library, and uCrop is the most widely used.
I attempted to match the uCrop theme colors with ours but that may need polish
I implemented it such that *only* Android 11 will attempt to use this code path, thus it should be safe to cherry-pick to stable for now, since they were already broken completely with crop.
Follow-on work for 2.15.x after cherry-picking this - I will make a new issue for this:
- uCrop widget translations? Can we specify resource ids for the strings?
- dark mode theme color for active widget?
- cover all APIs with it? Not just Android 11, since it is superior
- clean proguard …
=> Fix Android 11 crop

AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
The problem was with progressDialog title which was having space 
Fixes https://github.com/ankidroid/Anki-Android/issues/8192
by changing "" to null 
Before fix
Solved by testing in emulator(After Fix)
Tested on emulator: Pixel 3a API R
=> Fixes Bug ankidroid#8192.

AnkiDroid/src/main/res/values-eo/02-strings.xml, AnkiDroid/src/main/res/values-hi/02-strings.xml
=> Updated strings from Crowdin

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportDialog.java, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java, AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java, AnkiDroid/src/main/java/com/ichi2/utils/BundleUtils.java, AnkiDroid/src/test/java/com/ichi2/libanki/AnkiPackageExporterTest.java, AnkiDroid/src/test/java/com/ichi2/utils/BundleUtilsTest.java
Code cleaning and refactorings to Export classes and the ExportDialog class
=> Code cleaning and refactoring

AnkiDroid/build.gradle, build.gradle, lint-rules/build.gradle
Standard dependency updates from my tracking branch
Nothing major here that I can see
=> Dependency updates 20210319

AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/RecursivePictureMenu.java, AnkiDroid/src/main/res/values/constants.xml, AnkiDroid/src/test/java/com/ichi2/anki/dialogs/RecursivePictureMenuTest.java
This PR adds analytics in Help section (Dialog box) on clicking any item.
Fixes #8210 
As I was bit confused, I followed the approach suggested by David.
https://github.com/ankidroid/Anki-Android/issues/8210#issuecomment-800594220
**Also, there are some whitespaces but they are not intentional. I have properly formatted the classes and that has caused some extra line additions.**
Tested on real device (Redmi Note 7S and API 29). Analytics are logged in logcat and thus showing it's working fine.
This PR changes used abstraction and some more changes.
=> Fixes #8210 Added analytics/metrics to help section

AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java, AnkiDroid/src/main/res/layout/my_account.xml, AnkiDroid/src/main/res/values/02-strings.xml
Some basic changes to UI.
The user would have hardly distinguished before, but this directly gives user a view of their error.
Before:
After:
Dark Mode:
Light Theme:
Android emulator:Pixel 3a API R
=> Added error message if login credential empty

AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
The value was ignored and replaced with null
Raised in #7127
⚠️ Untested - please suggest if required.
=> fix[SchedV2]: use cancelListener param

AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.java
This reverts commit 6c89e5f6
Reviewer was still broken
----
Sorry - was unable to test the reviewer after reinstalling the WebView
=> Revert "HACK: Fix startup crash due to broken WebView"

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java
This help debugging all tasks passing deck study data between background and foreground, ensuring all data are at the
correct place.
=> NF: use a tuple class instead of int[]

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
Select many was not working fine on changing orientation.
Fixes #8294 
Saved and restored variables `mLastSelectedPosition` and `mInMultiSelectMode`
Tested on real device (Redmi Note 7S and API29).
=> Fixes #8294 Fixed select many wrt configuration changes

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TagsDialog.java
A base PR for #8322
Enum instead of ints for the dialog types, and general cleanup.
NF
=> NF: TagsDialog cleanup

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TagsDialog.java
pull request made for this issue were to be reverted and to make a interface based solution
Fixes #6174 
=> interface based solution for TagsDialog

AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java, AnkiDroid/src/main/java/com/ichi2/libanki/Note.java, AnkiDroid/src/main/java/com/ichi2/libanki/TextCardExporter.java, AnkiDroid/src/main/java/com/ichi2/libanki/TextNoteExporter.java, AnkiDroid/src/main/java/com/ichi2/utils/StringUtil.java, AnkiDroid/src/test/java/com/ichi2/libanki/AnkiPackageExporterTest.java, AnkiDroid/src/test/java/com/ichi2/libanki/TextNoteExporterTest.java, AnkiDroid/src/test/java/com/ichi2/utils/StringUtilTest.java
Adding the functionality to export csv/tsv notes/cards to ankilib. Will implement the GUI for this in another PR
Fixes (partially) #1913
=> feat: Add CSV Export to ankilib

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
Added webview information to ACRA crash reports with the help of package manager
Fixes #8142 
Adding a custom field to ACRA report which send the Webview version name and code with the help of Package Manager
This has been tested locally
Adding custom field to ACRA reports
https://stackoverflow.com/questions/34338262/acra-sending-a-custom-data-reportfield
=> Fix:8142 Adding Webview information to crash report

AnkiDroid/build.gradle, api/build.gradle
Standard dependency update PR - nothing notable
=> Dependency updates 20210327

AnkiDroid/src/main/AndroidManifest.xml, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/RecursivePictureMenu.java, AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.java, AnkiDroid/src/main/java/com/ichi2/ui/RtlCompliantActionProvider.java, AnkiDroid/src/main/res/layout/deck_item.xml, AnkiDroid/src/main/res/layout/floating_add_button.xml, AnkiDroid/src/main/res/layout/material_dialog_list_item.xml, AnkiDroid/src/main/res/layout/model_field_editor_list_item.xml, AnkiDroid/src/main/res/layout/note_editor.xml, AnkiDroid/src/main/res/layout/rtl_menu_item.xml, AnkiDroid/src/main/res/menu-television/reviewer.xml, AnkiDroid/src/main/res/menu/card_browser.xml, AnkiDroid/src/main/res/menu/card_browser_multiselect.xml, AnkiDroid/src/main/res/menu/deck_picker.xml, AnkiDroid/src/main/res/menu/reviewer.xml, AnkiDroid/src/main/res/menu/study_options_fragment.xml, AnkiDroid/src/main/res/values-ldrtl/styles.xml, AnkiDroid/src/main/res/values/styles.xml, AnkiDroid/src/test/java/com/ichi2/ui/RtlCompliantActionProviderTest.java
This line of code was causing a lot of visual issues for RTL users. As the direction of the layout was still LTR
Fixes (partially) #8259.
=> Add supportsRtl to AndroidManifest.xml

AnkiDroid/src/test/java/com/ichi2/utils/MapUtilTest.java
Added a unit test for MapUtil.
=> Unit Test for MapUtil

AnkiDroid/build.gradle, AnkiDroid/src/main/java/com/ichi2/anki/web/HttpFetcher.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/CountingFileRequestBody.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/HttpSyncer.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/Tls12SocketFactory.java
Modern versions of OkHttp are available now that we have a minSdkVersion >= 21
Fixes #5223 
Fixes #7465
- I maintained the TLS1.2 workaround, but reduced it to Samsung only as they are the only reported failures with API21, everyone else at API21 works, and this may be removed next minSdkVersion bump
- I did a fair amount of cleaning, in little commits
- I forward-ported to the new APIs - very very simple changes
- I added correct traffic counting of response bodies, and added request/response header length to traffic counts
local androidTest runs (it does exercise the connection actually, plus API21 and API30 emulators with a test collection, it all worked and traffic counts look good now!
It is maybe possible to convert all the counting to a network intercepter but for streaming uploads …
=> Forward port to new OkHttp4 dependency

AnkiDroid/src/main/java/com/ichi2/utils/TextViewUtil.java
Added `@NonNull` to parameter of `getTextSizeSp` in `TextViewUtil` 
Fixes [8398](https://github.com/ankidroid/Anki-Android/issues/8398)
=> Fixes #8398: added @NonNull annotation

AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java, AnkiDroid/src/main/java/com/ichi2/async/TaskManager.java
=> NF: addTasks -> addTask

AnkiDroid/src/test/java/com/ichi2/utils/ArrayUtilTest.java
There was no unit test for ArrayUtil, so added one for this.
=> Unit Test for ArrayUtil

README.md
Updation of Readme badge link to actions page from travis 
Fixes #8382
=> Readme.md: Update "build" to point to GitHub actions on master #8382

AnkiDroid/src/test/java/com/ichi2/testutils/AnkiAssert.java
=> refactor: test param name

AnkiDroid/src/test/java/com/ichi2/utils/ClipboardUtilTest.java
To test `ClipboardUtil.class`
Checks for  null `clipboardManager` and `clipDescription`
=> Unit Test for ClipboardUtil

AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java
The field text can't change after exception, so pos and pos1 are the same variables
=> NF: avoid duplicate work

AnkiDroid/src/test/java/com/ichi2/utils/CollectionUtilsTest.java
=> Unit test for CollectionUtils

AnkiDroid/build.gradle, AnkiDroid/src/main/java/com/ichi2/utils/UniqueArrayList.java, AnkiDroid/src/test/java/com/ichi2/utils/UniqueArrayListTest.java
A base PR for #8322
`UniqueArrayList` is a `List` compliant data structure, that uses an internal `TreeSet` with optional comparator, with `ArrayList`.
The `UniqueArrayList<E>` class is created to be able to do the following:
*  **Maintain the order of the items**
*  **Indexable**: getting index of an element and vice versa
* Needed in recycler view where it requires access to element via index a lot while scrolling.
*  **Sortable**: need a way to sort the array
* Needed when adding tags or loading the Dialog, where checked tags must be shown first
*   **Unique**: maintaining a unique list of items using comparators
* making tags unique with `String.CASE_INSENSITIVE_ORDER`
👎  `ArrayList<E>`: not Unique
👎   `TreeSet<E>`: doesn't maintain the order and no indexing and not sortable
👎 …
=> NF: Add UniqueArrayList data structure

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
Change the formatting issues according to #8370 
Fixes #8387 
Followed #8370, added those changes ran gradlew lintRelease to generate a report of all the issues and solve errors accordingly. 
=> Fix "A PART OF"  Code style for non-public, non-static fields #8387

AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.java, AnkiDroid/src/test/java/com/ichi2/testutils/AnkiAssert.java, AnkiDroid/src/test/java/com/ichi2/utils/ListUtil.java
This way, it uses same tools as array equality and will show descriptive message about the difference
=> NF: Introduce List assertion

AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java
=> NF: correct a typo

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
flagged by Android Studio as a lint / error
No related issue exists, I think
Just call super per hint from AndroidStudio
Untested
=> Call super method in DeckPicker.onRequestPermissionResult

AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.java, AnkiDroid/src/main/res/drawable-v21/fab_label_background.xml, AnkiDroid/src/main/res/drawable/fab_label_background_black_pre21.xml, AnkiDroid/src/main/res/drawable/fab_label_background_pre21.xml, AnkiDroid/src/main/res/values/attrs.xml, AnkiDroid/src/main/res/values/colors.xml, AnkiDroid/src/main/res/values/theme_black.xml, AnkiDroid/src/main/res/values/theme_dark.xml, AnkiDroid/src/main/res/values/theme_light.xml, AnkiDroid/src/main/res/values/theme_plain.xml
Improved UI for the Add Decks Button
Fixes #8223 
I have tested the same on Google Pixel XL Api 30 android device.
=> Improved UI for the Add Decks Button

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/res/values/02-strings.xml
Implemented toast message when back is pressed
Fixes #8226 
I have tested the same on Google Pixel XL Api 30 android device.
=> Implemented toast message when back is pressed

AnkiDroid/build.gradle
Dependency upgrade to fix database related bugs
* rsdroid-testing: diagnose file not found error
* fix OOM via memory limit on DB row results
* Add Java-based exceptions for rust errors
Fixes #8178 (hopefully)
Makes a start on #8075
* Ran unit tests
* Slight test on my phone
* ⚠️ We need some form of performance regression cover - maybe as an issue, maybe I need to write something here. I do feel this will be slightly slower than the previous implementation, I'm not sure if we /need/ to tackle it here, but we need to be aware
https://github.com/david-allison-1/Anki-Android-Backend/compare/0.1.2...0.1.4
=> Upgrade ankidroid backend to 0.1.4

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/LocaleSelectionDialog.java
This avoids use of undeclared transitive dependency on library classes available from
the google-analytics-java library in it's java7 flavor
Related #7056
I examined the API being used, and it created an immutable List from a given Array, and found JDK-native APIs that do the same
local `./gradlew jacocoTestReport` with an API21 emulator running
=> Use JDK-native immutable list implementation for locale list

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.java, AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.java, AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/TypedAnswer.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DialogHandler.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java, AnkiDroid/src/main/java/com/ichi2/libanki/LaTeX.java, AnkiDroid/src/main/java/com/ichi2/libanki/Media.java, AnkiDroid/src/main/java/com/ichi2/libanki/Models.java, AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java, AnkiDroid/src/main/java/com/ichi2/libanki/StdModels.java, AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java, AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java, AnkiDroid/src/main/java/com/ichi2/libanki/template/ParsedNode.java, AnkiDroid/src/main/java/com/ichi2/libanki/template/TemplateFilters.java, AnkiDroid/src/main/java/com/ichi2/libanki/template/Tokenizer.java, AnkiDroid/src/main/java/com/ichi2/utils/BooleanGetter.java, AnkiDroid/src/main/java/com/ichi2/utils/DeckComparator.java, AnkiDroid/src/main/java/com/ichi2/utils/DeckNameComparator.java, AnkiDroid/src/main/java/com/ichi2/utils/NamedJSONComparator.java, AnkiDroid/src/test/java/com/ichi2/libanki/CollectionTest.java, AnkiDroid/src/test/java/com/ichi2/libanki/template/TokenizerTest.java
Should be ALL_CAPS_WITH_UNDERSCORES: https://github.com/ankidroid/Anki-Android/wiki/Code-style#constant-final-variables-names-must-be-all-uppercase-using-underscore-to-separate-words
> Constant (final variables) names must be all uppercase using underscore to separate words.
I did this with a lint check (on `public static final`), this is checked in to a personal branch: `lint_constant_done` and will be added after https://github.com/ankidroid/Anki-Android/issues/8387 is done to avoid problems
=> Code Style: Fix Constant naming

AnkiDroid/src/test/java/com/ichi2/utils/AssetHelperTest.java
Added a test for AssertHelper Util class
Unit Test
=> Added test for AssetHelper util class.

AnkiDroid/src/main/java/com/ichi2/libanki/stats/AdvancedStatistics.java
Change the formatting issues according to #8370 
Fixes some of #8387 
Followed #8370, added those changes ran gradlew lintRelease to generate a report of all the issues and solve errors accordingly. 
=> Fix "A PART OF" Code style for non-public, non-static fields #8387

AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java
=> chore: Add CheckResult annotation

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TagsDialog.java, AnkiDroid/src/test/java/com/ichi2/libanki/TagsTest.java
Adds tests for utility functions in the Tags class.
=> Added tests to the utility functions of the Tags class

AnkiDroid/src/test/java/com/ichi2/utils/JSONObjectTest.java
To increase ```JSONObject.class```'s test coverage
- Checks for correct behavior in the methods ```com.ichi2.utils.JSONObject``` adds extra logic to compared to its super class ```org.json.JSONObject```
- Uses a variety of test JSONObjects with nested JSONObjects and JSONArrays
Passed the Unit Tests locally
=> Unit Tests for JSONObject

AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java, AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java, AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportDialog.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/RecursivePictureMenu.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/TranslationActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/glosbe/json/Response.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/glosbe/json/Tuc.java, AnkiDroid/src/main/java/com/ichi2/anki/reviewer/PeripheralCommand.java, AnkiDroid/src/main/java/com/ichi2/anki/stats/StatsMetaInfo.java, AnkiDroid/src/main/java/com/ichi2/async/TaskManager.java, AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java, AnkiDroid/src/main/java/com/ichi2/libanki/Models.java, AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java, AnkiDroid/src/main/java/com/ichi2/libanki/StdModels.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/Tls12SocketFactory.java, AnkiDroid/src/main/java/com/ichi2/libanki/sync/UnifiedTrustManager.java, AnkiDroid/src/main/java/com/ichi2/preferences/TimePreference.java
Change the formatting issues according to #8370 
Fixes some of #8387 
Followed #8370, added those changes ran gradlew lintRelease to generate a report of all the issues and solve errors accordingly. 
=> Fixes Code style for non-public, non-static fields #8387

AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/UndoAction.java
This name is more descriptive of the actual use of this class
=> NF: rename `Undoable` to `UndoAction`

AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java, AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java, AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java, AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.java
https://github.com/david-allison-1/anki/blob/c9e12052e2c3d6c146f06461abef6f60ef8cca58/pylib/anki/decks.py#L141-L145
Untested - just a rename
=> NF: rename: id_dont_create -> id_for_name

AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
Indeed, it always returned one out of two values. Using false or true is nicer
=> NF: `DismissNotes`'s `actualTask` return whether it succeeded

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
Collection was not initialized after storage permission was newly granted
Fixes #8558 
Made the following changes in DeckPicker
- firstCollectionOpen() is only responsible for checking if the collection can be opened. It isn't responsible for error checking anymore
- handleStartup() initializes collection using firstCollectionOpen immediately if permission granted
- handleStartup() requests for storage permission if it's not granted
- handleStartup() called in onCreate() & after permission granted
- Samsung Galaxy A80 API 30 (Physical Device)
- Pixel 3a XL API 27 (Emulator)
=> Initialize Collection after storage permission granted

AnkiDroid/src/main/java/com/ichi2/libanki/Card.java, AnkiDroid/src/main/java/com/ichi2/libanki/Note.java
While it made a little bit of sens previously, now that upstream moved to rust, it makes even less sens now..
https://github.com/ankitects/anki/commit/7ddaf93f7ac77259f8a17a85dbe4439036d3cdd0
=> NF: Card and Note constructors are not-python like

AnkiDroid/src/test/java/com/ichi2/utils/NamedJSONComparatorTest.java
Add unit tests for `NamedJSONComparator` class.
Fixes #8556 
Added a test to check if the correct value is returned when same names are compared and another test to check if the correct value is returned when the names are different.
=> Add unit tests for NamedJSONComparator class

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java
Simplifies code simply without changing anything
=> NF: PreviewerCard's note is final

AnkiDroid/src/test/java/com/ichi2/preferences/TimePreferenceTest.java
=> test: parsing hours as JUnit parameterized test

AnkiDroid/src/test/java/com/ichi2/utils/StringUtilTest.java
Added a test to check if a string which is stripped is strip it remains same
=> strip does nothing on stripped string

AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.java
I had a test failure when pulling my `master` branch 
* Fix failure
* Refactor code
Unit test only
=> Fix analytics constants tests

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
Only used once, found during Rust conversion
=> NF: Extract helper method from Decks

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java, AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckDropDownAdapter.java, AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java, AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java, AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.java
We shouldn't be enforcing an implementation unless we need it
https://softwareengineering.stackexchange.com/questions/258646/should-i-declare-the-most-specific-type-as-return-type-of-method
=> NF: Convert Deck methods to return List

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java
=> lint: fix build errors

AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java, AnkiDroid/src/main/java/com/ichi2/async/ProgressSender.java, AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
The start of decoupling abstractions from `libAnki`
Also somewhat to get to grips with this part of the codebase
=> NF: Refactor `Finder`

AnkiDroid/build.gradle, AnkiDroid/jacoco.gradle, AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/Shared.java, api/build.gradle, gradle/wrapper/gradle-wrapper.properties, lint-rules/build.gradle
We are about to cut a release branch that will hopefully live for a while but:
- gradle7 is out, we will upgrade but then our build toolchain straddles the release branch which is hard on me
- jcenter is going away forever, so we need to purge those dependencies out if possible
Fixes #5634
Supercedes #8537 
- I purged the api module publish machinery, and rebuilt it from scratch following Medium articles, with testing along the way
- I removed jcenter from everything but AnkiDroid
At this point, gradle 7 was working
- I worked on a fork of the requery/sqlite-android repository so that it was jitpack compatible
- I purged an old espresso test shared utility no one is using because I gave up on espresso long ago
- I got rid of the jcenter repository
So.Many.Builds. Especially focused on …
=> Forward Port to Gradle 7 / remove JCenter dependencies

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
The old method of passing information to / starting / receiving results from one Activity to/from another Activity is deprecated in general, here we start refactoring the code to use the new androidx.activity APIs for such communication
Fixes (only partially) https://github.com/ankidroid/Anki-Android/issues/8602
Each `startActivityForResult` and corresponding case in `onActivityResult` is refactored to use the new API.
This first PR refactors only the communication between `Previewer` and `CardBrowser` in order to be sure that the style looks good before moving to the others.
On emulators: API 30 and API 25.
https://developer.android.com/training/basics/intents/result
=> Refactor: Open Previewer from CardBrowser using new Activity APIs

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CreateCustomStudySessionListener.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialogFactory.java, AnkiDroid/src/main/java/com/ichi2/utils/BundleUtils.java, AnkiDroid/src/test/java/com/ichi2/utils/BundleUtilsTest.java
Add copyright headers to my files
Fixes part of #8659
=> Add copyright headers

AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardAppearance.java, AnkiDroid/src/main/java/com/ichi2/anki/exception/ManuallyReportedException.java, AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtonStatus.java, AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtons.java, AnkiDroid/src/main/java/com/ichi2/anki/reviewer/CardMarker.java, AnkiDroid/src/main/java/com/ichi2/libanki/exception/NoSuchDeckException.java, AnkiDroid/src/main/java/com/ichi2/preferences/PreferenceExtensions.java, AnkiDroid/src/main/java/com/ichi2/ui/ActionBarOverflow.java, AnkiDroid/src/main/java/com/ichi2/utils/FileUtil.java, AnkiDroid/src/main/java/com/ichi2/utils/FunctionalInterfaces.java, AnkiDroid/src/main/java/com/ichi2/utils/HtmlUtils.java, AnkiDroid/src/main/java/com/ichi2/utils/Permissions.java, AnkiDroid/src/main/java/com/ichi2/utils/WebViewDebugging.java
Add copyright to my files which were missing it
Fixes partially #8659
No files were from 2021, I learned good
This casts doubt on the industry advice: "Lines of code removed is a good metric" 😉
=> lint: add missing copyright

AnkiDroid/src/main/res/values/10-preferences.xml, lint-rules/src/main/java/com/ichi2/anki/lint/IssueRegistry.java, lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java, lint-rules/src/main/java/com/ichi2/anki/lint/utils/Constants.java, lint-rules/src/test/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLengthTest.java
A lint rule to ensure that preference text in English does not exceed a limit and Hints for CrowdIn to ensure that our translators do not hit the same issue
Fixes #8534
Looped through all the xml files and stored the data in set and hashmap. Then analyzed the data through if else
not tested on a physical device. Done unit testing and run lint checks on terminal
Android dev submit on Lint: https://www.youtube.com/watch?v=ffH-LD5uP4s&t=808s
Lint explanation in brief (Recommended for a developer who is new to lint ): https://youtu.be/wFe0WZm_xm8
Google GIT Lint Examples : https://android.googlesource.com/platform/tools/base/+/studio-master-dev/lint/libs/lint-checks
=> Lint fixed preferences title length

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
ScheduleCollectionTaskListener was more complex than useful. The first PR is obviously good. The second may be rejected, I would not argue, even if I believe it's an improvement overall
=> Simplify schedule collection task listener

AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
=> [Feature] Implemented Shortcut option for Review Cards, Add Note, Browser Card

AnkiDroid/build.gradle, AnkiDroid/src/main/AndroidManifest.xml, api/build.gradle
I was trying to get rid of the new gradle optimization disables: 
```
> Task :api:lintRelease
Execution optimizations have been disabled for task ':api:lintRelease' to ensure correctness due to the following reasons:
- Type 'LintPerVariantTask' property 'allInputs' cannot be resolved:  Cannot convert the provided notation to a File or URI: annotation-1.2.0.jar (androidx.annotation:annotation:1.2.0). The following types/formats are supported:  - A String or CharSequence path, for example 'src/main/java' or '/usr/include'. - A String or CharSequence URI, for example 'file:/usr/include'. - A File instance. - A Path instance. - A Directory instance. - A RegularFile instance. - A URI or URL instance. - A TextResource instance. Reason: An input file collection couldn't be resolved, making it …
```
=> Gradle preening - take 1

AnkiDroid/src/main/java/com/ichi2/anki/analytics/AcraAnalyticsInteraction.java, AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnalyticsDialogFragment.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerAnalyticsOptInDialog.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/IntegerDialog.java, AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.java
Adding copyright headers for Mike Hardy files
=> NF: add copyrights for Mike Hardy files

AnkiDroid/src/main/java/com/ichi2/ui/SeekBarPreference.java, AnkiDroid/src/main/res/values/10-preferences.xml, AnkiDroid/src/main/res/xml/preferences_reviewing.xml
Mentioned first https://github.com/ankidroid/Anki-Android/issues/8417#issuecomment-816953643
Fixes #8417 
A new view was added for the labels.
Added two string resources in the file
Physical device
=> Labels added to dayOffset preference dialog seekbar

AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.java, AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilsTest.java, tools/update-localizations.py
Fixes #8676  Added malayalam Language support to Ankidroid
=>  Added Malayalam Language

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserOrderDialog.java
As per #8659 this file was added by me (under some other git identity because I didn't know how things work back then), so adding the copyright header here.
=> NF: Add copyright header for Enno Hermann

AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.java, AnkiDroid/src/test/java/com/ichi2/anki/BackupManagerTest.java
I want to test BackupManager because I wanted to understand how it works, in order to add a backup which wasn't in the background for #8529
Add tests and extract
Unit test only
IntelliJ's extract method broke code, this was unexpected.
=> Add Tests: BackupManager 

AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.java
Untested (only failed on CI), my thoughts:
The ConcurrentModificationException occurs because the
object under test is being modified - likely because the action didn't
complete in time
See: issues/8064#issuecomment-826400296
=> Test: Fix ConcurrentModificationException

AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilsTest.java
Very few people adding a language did this correctly. I'm hoping this will help
Consider removing the tests/making them manual if this doesn't work.
It's maintenance effort and adds a barrier to a quick merge for something that is unlikely to occur
=> docs: Add clarification to LanguageUtilsTest

lint-rules/src/main/java/com/ichi2/anki/lint/rules/DuplicateCrowdInStrings.java
Was ambiguous about adding the attribute to just one string
=> docs: improve lint error message

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TagsDialog.java, AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsListTest.java
Related to #4911 
Related to #8327
I decided to clean up and refactor `TagDialog` first and then move on implementing multi note tag edit next.
I implemented a new collection class `UniqueArrayList`, to be able to keep a list with a unique items, while keeping order and to have the ability to sort them
* Manually and using some unit tests
=> Refactoring of TagsDialog 

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
It's really strange to read the previous code, even if correct
=> NF: AnswerCardHandler is child

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
Small code cleaning, avoiding useless extra function
=> NF: avoid a function called only once

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/test/java/com/ichi2/anki/ReviewerKeyboardInputTest.java
This allow to factorize a little bit of code.
=> NF: dismiss return whether the task succeeded

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
=> NF: NextCardHandler is not abstract

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
There is a small overhead since containsKey and getLong have duplicate check for belonging, but its not worth the code complexity
=> NF: simplify selectDeckFromExtra code

AnkiDroid/src/main/res/values-be/01-core.xml, AnkiDroid/src/main/res/values-be/02-strings.xml, AnkiDroid/src/main/res/values-be/18-standard-models.xml, AnkiDroid/src/main/res/values-de/01-core.xml, AnkiDroid/src/main/res/values-fy/01-core.xml, AnkiDroid/src/main/res/values-hu/10-preferences.xml, AnkiDroid/src/main/res/values-ko/01-core.xml, AnkiDroid/src/main/res/values-ml/02-strings.xml, AnkiDroid/src/main/res/values-ru/03-dialogs.xml, AnkiDroid/src/main/res/values-ru/10-preferences.xml, AnkiDroid/src/main/res/values-sk/01-core.xml, AnkiDroid/src/main/res/values-sk/11-arrays.xml, AnkiDroid/src/main/res/values-sl/01-core.xml, AnkiDroid/src/main/res/values-uk/10-preferences.xml, AnkiDroid/src/main/res/values-vi/03-dialogs.xml
Standard I18N sync :crossed_fingers:
=> Updated strings from Crowdin 20210429

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
This just factorize a little bit of code duplication. I find it more clear this way
=> Factorizing dismiss

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.java, AnkiDroid/src/main/res/values/01-core.xml, AnkiDroid/src/main/res/values/04-network.xml, AnkiDroid/src/main/res/values/constants.xml
The wording of "Sync Conflict" was ambiguous and caused our users issues
Fixes #8702
Instead of using "Upload" or "Download", use "AnkiDroid"/"AnkiWeb"
This doesn't take into account custom sync servers, but it's a price worth paying
And have the call to action request what to keep
* Don't use "sync conflict" as it's techy
* Use small sentences to ensure attention
We change the suggested wording from the site from:
`your decks differ and can't be combined`
to
`your decks can't be combined`
We use a new title for the confirmation screen as we show the opposite on the follow-up:
`Which do you want to keep? AnkiDroid` ->`Overwrite Decks -> Confirm overwrite AnkiWeb`
**before**
**after**
Tested on my Andorid 11
Idea obtained from:
https://www.hunternielsen.com/project/04096f2e/AnkiMobile
Many …
=> Improve "Sync Conflict" UX

AnkiDroid/src/test/java/com/ichi2/utils/ExtendedFragmentFactoryTest.java
A new method is introduced to #8577 but without unit testing
=> test: `ExtendedFragmentFactory#attachToFragmentManager`

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java, AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java
Steps to reproduce the bug 
- open the card template editor 
- edit content Front or back.
- change to style 
- again change to front or back
Expected Output 
Edittext should show updated content 
Actual Output 
Editext showing previous version of the content
=> Add Tests for Card Template Editor BottomNavigationView 

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
No point in using regex when a substring will do
=> Speed up card browser

AnkiDroid/build.gradle, AnkiDroid/src/main/java/com/ichi2/anki/AnkiSerialization.java, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/TranslationActivity.java, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java, AnkiDroid/src/main/java/com/ichi2/libanki/importer/AnkiPackageImporter.java
Replace Gson with Jackson which is a more maintained and feature rich json parser
Related to #8668
Gson was already there I just used Jackson the same as gson was used in the codebase
relaying on the existing tests
=> NF: Replace gson with jackson

.github/dependabot.yml, AnkiDroid/build.gradle, AnkiDroid/jacoco.gradle
Historically I've had dependabot running on my fork against branch dependency-updates, where I stage dependency updates then feed them into the main repo via PR
I still want to stage them on a branch but with the new dependency config as a file in-tree I can't really maintain the config separate in the fork and feed them in
So I'm going to put the dependency-updates branch in the main repo now and have the config file live there
This includes a starter config plus a couple test bumps
=> Dependency updates setup on main repo

AnkiDroid/src/main/res/values-be/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-be/17-model-manager.xml, AnkiDroid/src/main/res/values-be/18-standard-models.xml, AnkiDroid/src/main/res/values-eo/02-strings.xml, AnkiDroid/src/main/res/values-eo/10-preferences.xml, AnkiDroid/src/main/res/values-or/10-preferences.xml, AnkiDroid/src/main/res/values-or/17-model-manager.xml, AnkiDroid/src/main/res/values-uk/03-dialogs.xml, AnkiDroid/src/main/res/values-uk/10-preferences.xml
Standard I18N request.
Cherry-pickable to 2.15
=> Updated strings from Crowdin 20210514

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
Fixes #8822 
the crash was occurring at getCurrentTemplate method when the program tried to fetch from index value getter than its json size 
In the below video, I intentionally tried to fetch from index getter than its size, and its works without crashes
=> [Bug Fix] handled JSONException in cardTemplateEditor

AnkiDroid/build.gradle, build.gradle, lint-rules/build.gradle
First batch of updates on dependencies coming from in-repo vs my fork, following the work here #8818 and #8829
=> Dependency updates 20210514

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
=> Show Last Selected Deck In Note Editor Spinner

AnkiDroid/src/main/res/values-ar/01-core.xml, AnkiDroid/src/main/res/values-ar/02-strings.xml, AnkiDroid/src/main/res/values-ar/10-preferences.xml, AnkiDroid/src/main/res/values-be/01-core.xml, AnkiDroid/src/main/res/values-ca/01-core.xml, AnkiDroid/src/main/res/values-de/02-strings.xml, AnkiDroid/src/main/res/values-ko/01-core.xml, AnkiDroid/src/main/res/values-ko/02-strings.xml, AnkiDroid/src/main/res/values-ko/03-dialogs.xml, AnkiDroid/src/main/res/values-ko/10-preferences.xml, AnkiDroid/src/main/res/values-ko/11-arrays.xml, AnkiDroid/src/main/res/values-ko/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-ko/17-model-manager.xml, AnkiDroid/src/main/res/values-ko/18-standard-models.xml, AnkiDroid/src/main/res/values-pl/01-core.xml, AnkiDroid/src/main/res/values-pl/02-strings.xml, AnkiDroid/src/main/res/values-pl/03-dialogs.xml, AnkiDroid/src/main/res/values-pl/10-preferences.xml, AnkiDroid/src/main/res/values-zh-rTW/01-core.xml, AnkiDroid/src/main/res/values-zh-rTW/02-strings.xml, AnkiDroid/src/main/res/values-zh-rTW/03-dialogs.xml, AnkiDroid/src/main/res/values-zh-rTW/04-network.xml, AnkiDroid/src/main/res/values-zh-rTW/10-preferences.xml, AnkiDroid/src/main/res/values-zh-rTW/11-arrays.xml
Standard I18N sync - will cherry-pick to release-2.15
=> Updated strings from Crowdin 20210516

AnkiDroid/src/main/java/com/ichi2/async/Connection.java
every SSL engine uses different error messages but there are many SSL issues
that we can do nothing about. Add Conscrypt-formatted messages to the list
Fixes #8820
We already have a well-established approach, I just added to the list...
Untested
=> fix(sync): ignore new strings from Conscrypt SSL for user socket issues

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
the JSONObject is just created so it cannot be null
merging it sooner will simplify #8817 .
=> unnecessary null check

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java, AnkiDroid/src/main/java/com/ichi2/libanki/Models.java, AnkiDroid/src/test/java/com/ichi2/anki/TemporaryModelTest.java, AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.java, AnkiDroid/src/test/java/com/ichi2/utils/JSONObjectTest.java
the JSONObject is just created so it cannot be null
merging it sooner will simplify #8817 .
=> NF: use proper json

AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java
JSONObject.NULL is defined as org.json.JSONObject.NULL. This PR allow to change its definition later without breaking test
merging it sooner will simplify #8817 .
=> NF: change json null check

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
=> keep selected deck same after changing type of note

AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java
=> set last selected deck Id in statistics

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
BottomNavigation view loses its states after the switch to preview screen.
Fixes #8780
Maintained all pagers editorViewId and ediorViewPostion
=> Card template editor save states

AnkiDroid/src/main/res/values-ko/03-dialogs.xml, AnkiDroid/src/main/res/values-tr/01-core.xml, AnkiDroid/src/main/res/values-tr/02-strings.xml, AnkiDroid/src/main/res/values-tr/03-dialogs.xml, AnkiDroid/src/main/res/values-tr/10-preferences.xml, AnkiDroid/src/main/res/values-tr/18-standard-models.xml, AnkiDroid/src/main/res/values-vi/01-core.xml
=> Updated strings from Crowdin 20210519

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
Handeled IllegalArgumentException occurs while pasting the image from clipboard
Fixes #8880
check the length of the file name if the length is less than 3 then I changed the file name.
Tested manually by pasting different images from clipboard.
=> Fixed Bugs when image is  pasted from clipboard.

AnkiDroid/build.gradle, api/build.gradle, lint-rules/build.gradle
Standard dependency updates
appcompat is the only one that would give pause normally but it's just going from rc01 to stable release after more than a year of rc01 (they finally released it...)
=> Dependency updates 20210522

AnkiDroid/src/main/res/values-ar/10-preferences.xml, AnkiDroid/src/main/res/values-or/02-strings.xml, AnkiDroid/src/main/res/values-pt-rBR/02-strings.xml
=> Updated strings from Crowdin 20210522

AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java
There were crashes recorded in what appear to be tablet mode while returning
from a review session to the study options fragment
mToolbar is null, why? Unknown. Instrumenting the code for analysis, plus
attempting to avoid the crash
Fixes #8913
Related #8293 when this was hanged to the new Activity launcher APIs from androidx
Log everything, including an exception report, null check
I made a new Pixel C tablet emulator and attempted to reproduce. I could hit the same code paths based on logcat from crash reports but I couldn't create the crash even with system developer options / keep activities off
The Activity Result / Launcher APIs may be a bit trickier to deal with than we though.
_Please, go through these checks before submitting the …
=> fix(StudyOptionsFragment): attempt to avert crash returning from review

AnkiDroid/src/main/res/values-ms/01-core.xml, AnkiDroid/src/main/res/values-or/10-preferences.xml, AnkiDroid/src/main/res/values-zh-rTW/01-core.xml, AnkiDroid/src/main/res/values-zh-rTW/02-strings.xml, AnkiDroid/src/main/res/values-zh-rTW/03-dialogs.xml, AnkiDroid/src/main/res/values-zh-rTW/04-network.xml, AnkiDroid/src/main/res/values-zh-rTW/10-preferences.xml
=> Updated strings from Crowdin 20210525

lint-release.xml
These were trigging "UnknownIssueId" lint warnings because they
are no longer valid lint issues
Lint rules change over time
=> lint: remove unknown issues from lint.xml

AnkiDroid/src/main/res/values-bn/01-core.xml, AnkiDroid/src/main/res/values-cs/10-preferences.xml, AnkiDroid/src/main/res/values-cs/11-arrays.xml, AnkiDroid/src/main/res/values-es-rAR/02-strings.xml, AnkiDroid/src/main/res/values-es-rES/02-strings.xml, AnkiDroid/src/main/res/values-hi/01-core.xml, AnkiDroid/src/main/res/values-ko/01-core.xml, AnkiDroid/src/main/res/values-ko/02-strings.xml, AnkiDroid/src/main/res/values-or/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-or/17-model-manager.xml, AnkiDroid/src/main/res/values-ru/01-core.xml, AnkiDroid/src/main/res/values-ru/02-strings.xml, AnkiDroid/src/main/res/values-ru/03-dialogs.xml, AnkiDroid/src/main/res/values-ru/10-preferences.xml, docs/marketing/localized_description/ankidroid-titles.txt
Standard I18N sync
For catching problems with `kn` language: #8979
=> Updated strings from Crowdin 20210528

AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.java, AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilsTest.java, tools/update-localizations.py
Add new language
This requires a translation sync afterwards
Related: #8979
=> language: Add Kannada

AnkiDroid/src/main/res/values-kn/01-core.xml, AnkiDroid/src/main/res/values-kn/02-strings.xml, AnkiDroid/src/main/res/values-kn/03-dialogs.xml, AnkiDroid/src/main/res/values-kn/04-network.xml, AnkiDroid/src/main/res/values-kn/05-feedback.xml, AnkiDroid/src/main/res/values-kn/06-statistics.xml, AnkiDroid/src/main/res/values-kn/07-cardbrowser.xml, AnkiDroid/src/main/res/values-kn/08-widget.xml, AnkiDroid/src/main/res/values-kn/09-backup.xml, AnkiDroid/src/main/res/values-kn/10-preferences.xml, AnkiDroid/src/main/res/values-kn/11-arrays.xml, AnkiDroid/src/main/res/values-kn/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-kn/17-model-manager.xml, AnkiDroid/src/main/res/values-kn/18-standard-models.xml, AnkiDroid/src/main/res/values-ms/01-core.xml, docs/marketing/localized_description/marketdescription-kn.txt
Add Kannada language
Fixes #8979
=> Updated strings from Crowdin 2021-05-29

AnkiDroid/src/main/java/com/ichi2/libanki/template/Tokenizer.java, AnkiDroid/src/test/java/com/ichi2/libanki/template/TemplateTest.java
A firs part of #8987 with really simple changes
=> Clean template

AnkiDroid/src/test/java/com/ichi2/libanki/template/ParserTest.java, AnkiDroid/src/test/java/com/ichi2/libanki/template/TemplateTest.java, AnkiDroid/src/test/java/com/ichi2/libanki/template/TokenizerTest.java
It factorize code from template's tests. It will allow in #8987 to generalize tests on both "new" and "new and legacy" tests
=> Factorize template test

AnkiDroid/src/main/res/xml/preferences_advanced.xml
User wanted more
Fixes #9022
Note: The slider position implies that the user should increase the setting now, unsure if this is wise.
=> increase max backups from 10 to 99

AnkiDroid/src/main/java/com/ichi2/libanki/template/Tokenizer.java, AnkiDroid/src/test/java/com/ichi2/libanki/template/ParserTest.java, AnkiDroid/src/test/java/com/ichi2/libanki/template/TemplateTest.java, AnkiDroid/src/test/java/com/ichi2/libanki/template/TokenizerTest.java
Fixes #8978
I could have factorized legacy_handlebar_token and new_handlebar_token, but I don't think it would have improved
readability a lot, and clearly would not have improved the speed as it would require more parameter/function call.
=> Legacy template

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/Consts.java, AnkiDroid/src/main/res/values/constants.xml
Fix link to help section of cloze deletion.
Fixes #9032 
Updated the link to cloze deletion.
Verified.
=> Fix link to help section of cloze deletion

AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java
Update list when field reposition is done.
Fixes #9035 
Passed `listener` as argument to `launchCollectionTask()` in ModelFieldEditor. 
Verified.
=> Update list when field reposition is done

AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.java, AnkiDroid/src/main/res/layout/floating_add_button.xml
Some users were rightfully confused by this
Fixes #9051
Maybe #8993
* Make labels clickable
* Fix lint errors
Brief test on my Pixel 3A
=> Make FAB Labels clickable

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java, AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java
This also allow to have what I believe to be a better test for searchCardsNumberOfResultCount as it do not require to
test internal state
This is a small part of 8646 so that it gets simpler to consider
=> NF: CardBrowser create numCardsToRender

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java, AnkiDroid/src/main/java/com/ichi2/async/SingleTaskManager.java, AnkiDroid/src/main/java/com/ichi2/async/TaskManager.java, AnkiDroid/src/test/java/com/ichi2/async/ForegroundTaskManager.java
No need to specify "background" anymore since there is no "listener" type anymore
=> NF: remove background suffix from tasks-related classes

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/Gesture.kt, AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/GestureProcessor.java, AnkiDroid/src/main/java/com/ichi2/anki/reviewer/GestureMapper.java, AnkiDroid/src/main/res/values/10-preferences.xml, AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/GestureProcessorTest.java, AnkiDroid/src/test/java/com/ichi2/anki/reviewer/GestureMapperTest.java
This is the first part of extracting #8078 and getting it into the codebase to eventually sort out #6052
Untested aside from unit tests. Should be entirely NF aside from adding a new string. This string is unused for now (used in the code, but not in the UI)
=> NF: Refactor gesture processing

.github/dependabot.yml, AnkiDroid/build.gradle
Periodic PR from the dependency-updates tracking branch
=> Dependency updates 20210622

AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.java, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
this class is going to be in use for editor and David suggested including registerMediaWebView class in new pr 
[comment](https://github.com/ankidroid/Anki-Android/pull/9048/files#r652818204)
=> Created RegisterMediaForWebView class

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
note : these changes were originally made by David in visual editor pr for showing save chances dialog whenever a user clicks on the back button
this method can be overridden and will get invoke whenever user click on back button of activity
=> created onActionBarBackPressed method

AnkiDroid/src/test/java/com/ichi2/preferences/PreferenceExtensionsTest.java
=> nf: fix typo

AnkiDroid/src/test/java/com/ichi2/anki/OnboardingFlagTest.kt
In my opinion, copyright header of `OnboardingFlagTest` should be updated to include @Arthur-Milchior's name as well since it was a collaborative effort.
=> Update copyright header of OnboardingFlagTest

AnkiDroid/src/main/res/values-cs/01-core.xml, AnkiDroid/src/main/res/values-cs/03-dialogs.xml, AnkiDroid/src/main/res/values-cs/10-preferences.xml, AnkiDroid/src/main/res/values-eo/01-core.xml, AnkiDroid/src/main/res/values-eo/03-dialogs.xml, AnkiDroid/src/main/res/values-eo/10-preferences.xml, AnkiDroid/src/main/res/values-eo/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-heb/01-core.xml, AnkiDroid/src/main/res/values-heb/17-model-manager.xml, AnkiDroid/src/main/res/values-heb/18-standard-models.xml, AnkiDroid/src/main/res/values-or/01-core.xml, AnkiDroid/src/main/res/values-or/03-dialogs.xml, AnkiDroid/src/main/res/values-or/10-preferences.xml, AnkiDroid/src/main/res/values-zh-rCN/01-core.xml, AnkiDroid/src/main/res/values-zh-rCN/10-preferences.xml
=> Updated strings from Crowdin 20210627

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.java, AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CreateDeckDialogTest.java
Fixes #9161 
used CollectionHelper class instead AnkiActivty.,
steps to reproduce 
1 sync with menu item
2 then pull refresh and sync 
3 try to create deck
=> dropped mAnkiActivity from CreateDeckDialog

AnkiDroid/build.gradle, AnkiDroid/proguard-rules.pro, AnkiDroid/src/main/AndroidManifest.xml, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java, AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupUnderBackupTest.java, AnkiDroid/src/test/java/com/ichi2/testutils/ActivityList.java
Fixes #8072
Dropped uCrop library and implemented  [Android Image Cropper](https://github.com/CanHub/Android-Image-Cropper)
=> Implemented ImageCropper library

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/InsertFieldDialog.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/InsertFieldDialogFactory.java, AnkiDroid/src/main/res/menu/card_template_editor.xml, AnkiDroid/src/main/res/values/01-core.xml
=> Card Template Editor Appearance: Implemented "Insert Field" In Action Mode Callback 

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/main/java/com/ichi2/anki/services/BootService.java, AnkiDroid/src/main/java/com/ichi2/anki/services/NotificationService.java, AnkiDroid/src/main/java/com/ichi2/themes/Themes.java, AnkiDroid/src/main/java/com/ichi2/widget/WidgetStatus.java, AnkiDroid/src/test/java/com/ichi2/anki/ReviewerNoParamTest.java
Just to improve code clarity. Also fixe a typo noted by David in last similar PR
=> Some more constants

AnkiDroid/build.gradle, AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java, AnkiDroid/src/androidTest/java/com/ichi2/anki/TestUtils.java, AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/InstrumentedTest.java
=> Instrumentation tests for click on counts layout in DeckPicker

AnkiDroid/src/main/res/values-cs/01-core.xml, AnkiDroid/src/main/res/values-cs/10-preferences.xml, AnkiDroid/src/main/res/values-cs/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-eo/01-core.xml, AnkiDroid/src/main/res/values-eo/10-preferences.xml, AnkiDroid/src/main/res/values-eo/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-hi/01-core.xml, AnkiDroid/src/main/res/values-hi/02-strings.xml, AnkiDroid/src/main/res/values-hi/07-cardbrowser.xml, AnkiDroid/src/main/res/values-hi/10-preferences.xml, AnkiDroid/src/main/res/values-km/01-core.xml, AnkiDroid/src/main/res/values-or/02-strings.xml, AnkiDroid/src/main/res/values-or/10-preferences.xml, AnkiDroid/src/main/res/values-zh-rCN/10-preferences.xml
Standard I18N sync, last one before I make picks for 2.15.5
=> Updated strings from Crowdin 20210704

AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java, AnkiDroid/src/test/java/com/ichi2/anki/ReviewerNoParamTest.java
=> fix: Flaky tests failing on my Windows Machine

AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/java/com/ichi2/anki/analytics/Acra.kt, AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerAnalyticsOptInDialog.java, AnkiDroid/src/main/java/com/ichi2/utils/ExceptionUtil.java
Reviewer: These touch analytics, please review harshly
Pruning off refactoring fixes from #9184
=> NF: refactorings for critical exceptions

AnkiDroid/src/main/java/com/ichi2/anki/OnboardingFlag.kt, AnkiDroid/src/main/java/com/ichi2/anki/OnboardingUtils.kt, AnkiDroid/src/test/java/com/ichi2/anki/OnboardingFlagTest.kt
Changes in the base code required for implementing the onboarding feature.
=> Update base code related to onboarding

AnkiDroid/build.gradle, api/build.gradle, build.gradle, gradle.properties
Standard dependency updates PR from dependabot / seasoned on dependency-updates branch
Note the jetifier blacklist of bcprov to get robolectric through
=> Dependency updates 20210713

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/LayoutValidationTest.java, AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/Gesture.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/GestureSelectionDialogBuilder.kt, AnkiDroid/src/main/java/com/ichi2/anki/reviewer/Binding.java, AnkiDroid/src/main/java/com/ichi2/anki/reviewer/GestureMapper.java, AnkiDroid/src/main/java/com/ichi2/ui/GestureDisplay.kt, AnkiDroid/src/main/java/com/ichi2/ui/GesturePicker.kt, AnkiDroid/src/main/java/com/ichi2/ui/OnGestureListener.kt, AnkiDroid/src/main/java/com/ichi2/utils/UiUtil.kt, AnkiDroid/src/main/res/drawable-v25/ic_gesture_swipe.xml, AnkiDroid/src/main/res/drawable/ic_gesture_swipe.xml, AnkiDroid/src/main/res/drawable/ic_gesture_tap.xml, AnkiDroid/src/main/res/drawable/ic_gesture_tap_regular.xml, AnkiDroid/src/main/res/drawable/ic_gesture_tap_selected.xml, AnkiDroid/src/main/res/layout/gesture_display.xml, AnkiDroid/src/main/res/layout/gesture_picker.xml, AnkiDroid/src/main/res/values/10-preferences.xml, AnkiDroid/src/main/res/values/styles.xml, AnkiDroid/src/test/java/com/ichi2/anki/reviewer/BindingAndroidTest.kt
Currently unused: adds `GestureSelectionDialogBuilder`
A screen with visual feedback allowing gesture selection via either user action, or via a spinner
The spinner exists to enhance discoverability of long/double tap gestures
Known Issues:
* Swipe does not appear on <= API 24. A static image is used
* Gesture unicode character not rendered on <= API 22
* Milliseconds of visual latency on taps (due to double tap checking)
Prep for #6052, layouts from #8078 with refactoring
Android 11, API 21, 22, 23, 24 and 25
<details><summary>Screenshots</summary>
API 21: no gesture unicode char, or swipe feedback
</details>
Android UI is still painful, especially so on lower APIs
* Only issue is the text contrast of the "OK" button in night mode
=> feat: Dialog to handle gesture selection

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java, AnkiDroid/src/test/java/com/ichi2/anki/ReviewerNoParamTest.java
Requested refactoring in #9278 was /almost/ correct
Fixes #9267
Unit test and on my phone
* I've strayed a little too far away from automated tests, this is guidance to test more
=> fix: reviewer fullscreen ui

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java, AnkiDroid/src/main/res/values/01-core.xml, AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java
cleared todo: added confirmation dialog before adding cards, same as Anki Desktop
=> confirmation dialog before adding card type

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
Actionbar icon is dissapearing after syncing
Fixes #9081
This is a case when their is no change in collection or if their is a error while scyncing. I have done bit investigation and found out that this issue is occuring after this PR #8666 . !colIsOpen() is turned as true and their is no refreshing of action bar in this perticular case and we are seeing no icons in actionbar.
Samsung Galaxy M51 (API 30)
=> Fixed disappearing Actionbar icon after syncing

AnkiDroid/src/main/res/values-de/01-core.xml, AnkiDroid/src/main/res/values-de/02-strings.xml, AnkiDroid/src/main/res/values-de/03-dialogs.xml, AnkiDroid/src/main/res/values-de/10-preferences.xml, AnkiDroid/src/main/res/values-de/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-fr/01-core.xml, AnkiDroid/src/main/res/values-ka/01-core.xml, AnkiDroid/src/main/res/values-sv/04-network.xml, AnkiDroid/src/main/res/values-sv/06-statistics.xml, AnkiDroid/src/main/res/values-sv/07-cardbrowser.xml, AnkiDroid/src/main/res/values-sv/10-preferences.xml, AnkiDroid/src/main/res/values-sv/11-arrays.xml, AnkiDroid/src/main/res/values-sv/17-model-manager.xml, AnkiDroid/src/main/res/values-uk/01-core.xml, AnkiDroid/src/main/res/values-uk/02-strings.xml, AnkiDroid/src/main/res/values-uk/03-dialogs.xml, AnkiDroid/src/main/res/values-uk/10-preferences.xml, AnkiDroid/src/main/res/values-uk/16-multimedia-editor.xml
Standard I18N sync, but just changed tooling (#9318) so it's kind of exciting that the diff looks right
=> Updated strings from Crowdin 20210728

AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/AudioRecorderTest.java
Added a few unit tests to cover the functions in AudioRecorder. It should be at 100% coverage now according to the report generated by Android Studio.
=> Added unit tests for AudioRecorder

AnkiDroid/src/main/java/com/ichi2/compat/Compat.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.java, AnkiDroid/src/main/java/com/ichi2/utils/FileUtil.java, AnkiDroid/src/test/java/com/ichi2/utils/FileUtilTest.java
Directory I/O methods to be used in later commits that migrate user data to App-Specific directories accessible under Scoped Storage.
Unit test added for each new directory I/O method added
=> Add Directory I/O methods

AnkiDroid/src/test/java/com/ichi2/utils/JSONArrayTest.java, AnkiDroid/src/test/java/com/ichi2/utils/JSONObjectTest.java
It is not a catched exception anymore, and useless for test. A part of org.json I assume
=> NF: remove `throws JSONException`

AnkiDroid/src/main/java/com/ichi2/libanki/Deck.java, AnkiDroid/src/main/java/com/ichi2/libanki/DeckConfig.java, AnkiDroid/src/main/java/com/ichi2/libanki/Model.java
This comes from #8817 from @TarekkMA
=> NF: comment model/deck/deckconfig

AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.java
fixes #9171
code: https://stackoverflow.com/a/31311718/14148406
=> Paste as PNG, if alpha channel exists

AnkiDroid/src/main/java/com/ichi2/libanki/TagsV16.kt, AnkiDroid/src/main/java/com/ichi2/libanki/backend/RustTagsBackend.kt, AnkiDroid/src/main/java/com/ichi2/libanki/backend/TagsBackend.kt, AnkiDroid/src/main/java/com/ichi2/libanki/backend/model/TagUsnTuple.kt, AnkiDroid/src/main/java/com/ichi2/libanki/utils/PythonExtensions.kt
Taken from
https://github.com/ankitects/anki/blob/ef5c38dbc619be4e45315b8ff49f0f7aa2433efa/pylib/anki/tags.py
Also adds a number of extension methods to apply Python-named methods in the Kotlin
Untested, adding for interface compatibility
Related: #8988
Untested aside from running unit tests, unused code
=> feat: Add schema v16 tags class [WIP but ready for merge]

AnkiDroid/build.gradle
Standard dependency updates PR - nothing really interesting
=> Dependency updates 20210805

AnkiDroid/src/main/java/com/ichi2/libanki/DecksV16.kt, AnkiDroid/src/main/java/com/ichi2/libanki/ModelsV16.kt, AnkiDroid/src/main/java/com/ichi2/libanki/PythonTypes.kt, AnkiDroid/src/main/java/com/ichi2/libanki/backend/BackendUtils.kt, AnkiDroid/src/main/java/com/ichi2/libanki/backend/DecksBackend.kt, AnkiDroid/src/main/java/com/ichi2/libanki/backend/ModelsBackend.kt, AnkiDroid/src/main/java/com/ichi2/libanki/utils/PythonExtensions.kt, AnkiDroid/src/main/res/values/01-core.xml
https://github.com/ankitects/anki/blob/c4db4bd2913234d077aa289543da6405a62f53dc/pylib/anki/models.py
Untested, adding for future interface compatibility
Related: #8988
=> feat: Add schema v16 models class

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/ImportTest.java, AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/ModelTest.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/ModelManager.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Models.java, AnkiDroid/src/main/java/com/ichi2/libanki/ModelsV16.kt, AnkiDroid/src/main/java/com/ichi2/libanki/StdModels.java, AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java, AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.java, AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java, AnkiDroid/src/test/java/com/ichi2/libanki/CardTest.java, AnkiDroid/src/test/java/com/ichi2/libanki/CollectionTest.java, AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.java, AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.java, AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java, AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.java, AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.java
First stage of abstracting out `Models.java` and merging it with `ModelsV16.kt`
Related: #8988 
* Introduce `DeckManager` and expose from `Collection`
* Have `Decks` inherit from `DeckManager`
* Pull the methods using `refactor - Pull` until it compiles
* Change the ordering of the methods and the JavaDocs to use the base class
* Tests compile
=> feat: Add public interface for Models.java 

AnkiDroid/src/main/java/com/ichi2/ui/RtlCompliantActionProvider.java, AnkiDroid/src/main/res/layout/rtl_menu_item.xml
I don't know if this is correct, but it matches 2.14.6 on my device in portrait and landscape
----
Methodology:
I checked the android/support library source code, found the line:
```java
mCollapseButtonView = new AppCompatImageButton(getContext(), null,
R.attr.toolbarNavigationButtonStyle);
```
And it seemed reasonable, but even after removing the line of code for padding, it was too wide
changed to `actionButtonStyle` and it worked
I don't fully understand this code, so this is potentially buggy.
Fixes #8970
<details><summary>2.14.6 and dev comparison</summary>
</details>
=> fix: action bar button spacing

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/java/com/ichi2/preferences/ConfirmationPreferenceCompat.java, AnkiDroid/src/main/java/com/ichi2/preferences/CustomDialogPreference.java, AnkiDroid/src/main/java/com/ichi2/preferences/IncrementerNumberRangePreference.java, AnkiDroid/src/main/java/com/ichi2/preferences/IncrementerNumberRangePreferenceCompat.kt, AnkiDroid/src/main/java/com/ichi2/preferences/NumberRangePreference.java, AnkiDroid/src/main/java/com/ichi2/preferences/NumberRangePreferenceCompat.kt, AnkiDroid/src/main/java/com/ichi2/preferences/ResetLanguageDialogPreference.kt, AnkiDroid/src/main/java/com/ichi2/preferences/SeekBarPreferenceCompat.java, AnkiDroid/src/main/java/com/ichi2/ui/ConfirmationPreference.java, AnkiDroid/src/main/java/com/ichi2/ui/SeekBarPreference.java, AnkiDroid/src/main/res/values-sw360dp/values-preference.xml, AnkiDroid/src/main/res/xml/preference_headers.xml, AnkiDroid/src/main/res/xml/preferences_advanced.xml, AnkiDroid/src/main/res/xml/preferences_reviewing.xml
**Note: there is a known follow-up branch, this commit range has been split out to make this easier to review**
See: https://github.com/david-allison-1/Anki-Android/commit/52c3c1fb58ef7d382855daeac2dde6c6452e5e41 for this commit
* `android.preference` is deprecated. `androidx.preference` is different
* `EditTextPreference` no longer exposes an `EditText` for example, the preferences are now decoupled from the view. 
This PR moves us closer to `androidx.preference`, so the "big bang refactor" becomes a "slightly lesser, but still rather big bang"
Related: #5019
* Remove the reference to the legacy `PreferenceScreen` from an interface
* This is better handled by inheritance in the fragments - a few methods have changed, and this made it easier to change functionality
* convert from …
=> Refactorings & partial conversion of Preferences.java to Support Library

AnkiDroid/src/main/java/com/ichi2/libanki/ModelsV16.kt
Incremental progress in getting ModelsV16.kt to match the interface of `ModelManager.kt`
Added a PR as it should be a trivial review, and I was switching branch, and likely not coming back here for a short while
#8988
=> nf: start refactoring ModelsV16 to match ModelManager public API surface

AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/ui/NoteTypeSpinnerUtils.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java, AnkiDroid/src/main/java/com/ichi2/libanki/ModelManager.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Models.java, AnkiDroid/src/main/java/com/ichi2/libanki/ModelsV16.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java, AnkiDroid/src/main/java/com/ichi2/libanki/backend/ModelsBackend.kt
See #9465 #8988
Refactorings and bugfixes, not done yet (one more PR), but there's quite a lot of code to get through, and breaking it up helps
Nonfunctional refactorings only - should be unit testable
Kotlin does not have `throws` (it has an annotation for Java, but checked exceptions don't exist)
=> nf: further refactoring ModelsV16 to match ModelManager public API surface 

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
This might have been unclear for #9471
=> docs: animation[Enabled/Disabled]

AnkiDroid/src/main/java/com/ichi2/libanki/ModelManager.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Models.java, AnkiDroid/src/main/java/com/ichi2/libanki/ModelsV16.kt
#8988 - allows returning a ModelsV16 from the collection, this class interfaces with the Rust Backend and allows us to use the V16 schema
Only unit tests. One more class to go, then we can start breaking things when running the app
=> ModelsV16: Make compatible with ModelManager

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/DeckManager.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java, AnkiDroid/src/main/java/com/ichi2/libanki/DecksV16.kt, AnkiDroid/src/main/java/com/ichi2/libanki/stats/AdvancedStatistics.java, AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.java, AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CreateDeckDialogTest.java, AnkiDroid/src/test/java/com/ichi2/libanki/CardTest.java, AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.java, AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java, AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.java
First stage of abstracting out `Decks.java` and merging it with `DecksV16.kt`
This is going to be a massive project, as Decks.java has a lot of custom logic to deal with filtered decks incorrect naming etc... that `DecksV16` doesn't have.
Related: #8988 
* Introduce `DeckManager` and expose from `Collection`
* Have `Decks` inherit from `DeckManager`
* Pull the methods using `refactor - Pull` until it compiles
* Change the ordering of the methods and the JavaDocs to use the base class
* Untested
=> feat: Add public interface for Decks.java

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java, AnkiDroid/src/main/java/com/ichi2/libanki/DecksV16.kt, AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.java, AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.java
As always, the goal is to be helpful. Being able to have some javadoc near the string that is easily accessible from the IDE, and allowing to easily search for all usage of this string through the app
=> NF: uses string constant for current deck and active decks

AnkiDroid/src/main/res/values-cs/02-strings.xml, AnkiDroid/src/main/res/values-cs/03-dialogs.xml, AnkiDroid/src/main/res/values-cs/10-preferences.xml, AnkiDroid/src/main/res/values-or/03-dialogs.xml, AnkiDroid/src/main/res/values-or/10-preferences.xml, AnkiDroid/src/main/res/values-or/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-ru/02-strings.xml, AnkiDroid/src/main/res/values-ru/03-dialogs.xml, AnkiDroid/src/main/res/values-ru/10-preferences.xml, AnkiDroid/src/main/res/values-sat/01-core.xml, AnkiDroid/src/main/res/values-zh-rCN/03-dialogs.xml, AnkiDroid/src/main/res/values-zh-rCN/10-preferences.xml
Standard I18N sync in prep for an alpha
=> Updated strings from Crowdin 20210904

AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java, AnkiDroid/src/main/java/com/ichi2/libanki/backend/DroidBackend.java, AnkiDroid/src/main/java/com/ichi2/libanki/backend/JavaDroidBackend.java, AnkiDroid/src/main/java/com/ichi2/libanki/backend/RustDroidBackend.java, AnkiDroid/src/test/java/com/ichi2/libanki/NoteWithColTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/StorageRustTest.kt
This is a no-op for now
In V16 - openCollection handles creation of note types
Related: #8988
=> Storage: in V16 - don't add collection data

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/Config.kt, AnkiDroid/src/main/java/com/ichi2/libanki/ConfigManager.kt, AnkiDroid/src/main/java/com/ichi2/libanki/ConfigV16.kt, AnkiDroid/src/main/java/com/ichi2/libanki/backend/BackendUtils.kt, AnkiDroid/src/main/java/com/ichi2/libanki/backend/RustConfigBackend.kt, AnkiDroid/src/test/java/com/ichi2/libanki/ConfigTest.kt
This was the final class we needed for the V16 conversion
Related #8988
Unit Tests only
=> Implement V16 Config class

AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java, AnkiDroid/src/main/java/com/ichi2/libanki/ModelManager.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Models.java, AnkiDroid/src/main/java/com/ichi2/libanki/ModelsV16.kt, AnkiDroid/src/test/java/com/ichi2/libanki/CardTest.java, AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java, AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.java
Comments on the tests should explain the rationales. All changes non-functional. Splitting this off to keep the review load at a reasonable pace
#8988
=> Rust: fixes for unit tests

AnkiDroid/build.gradle, api/build.gradle, build.gradle
=> Dependency updates 20210921

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/test/java/com/ichi2/libanki/ConfigTest.kt
=> fix: get_config: NULL value should return default

AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
Fixes #9563
Unit tests and checked on device 
As much as I dislike the effort involved. The regression test  which caught this was extremely useful.
https://github.com/ankitects/anki/commit/3cccae7a1f048d91cdc4ef4fcd1b919c76791007
=> ecosystem compat: set default rev limit to 200

AnkiDroid/src/main/res/values-be/02-strings.xml, AnkiDroid/src/main/res/values-sat/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-sc/02-strings.xml, AnkiDroid/src/main/res/values-sc/03-dialogs.xml, AnkiDroid/src/main/res/values-sc/10-preferences.xml, AnkiDroid/src/main/res/values-sk/01-core.xml, AnkiDroid/src/main/res/values-sk/02-strings.xml, AnkiDroid/src/main/res/values-sk/03-dialogs.xml, AnkiDroid/src/main/res/values-sk/04-network.xml, AnkiDroid/src/main/res/values-sk/10-preferences.xml, AnkiDroid/src/main/res/values-sk/11-arrays.xml, AnkiDroid/src/main/res/values-sk/16-multimedia-editor.xml
=> Updated strings from Crowdin 20210928

AnkiDroid/src/test/java/com/ichi2/anki/AnalyticsTest.java, AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java, AnkiDroid/src/test/java/com/ichi2/anki/OnboardingFlagTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogTest.java, AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/AudioPlayerTest.java, AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivityTestBase.java, AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.java, AnkiDroid/src/test/java/com/ichi2/libanki/TextNoteExporterTest.java, AnkiDroid/src/test/java/com/ichi2/testutils/BackendEmulatingOpenConflict.java, AnkiDroid/src/test/java/com/ichi2/testutils/MockTime.java
=> lint[tests]: VariableNamingDetector

AnkiDroid/kotlinMigration.gradle
Added example of class name in `kotlinMigration.gradle`.
=> Add class name example in kotlinMigration.gradle

AnkiDroid/src/main/java/com/ichi2/libanki/Note.java, AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt, AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt, AnkiDroid/src/main/java/com/ichi2/libanki/backend/DroidBackend.java, AnkiDroid/src/main/java/com/ichi2/libanki/backend/JavaDroidBackend.java, AnkiDroid/src/main/java/com/ichi2/libanki/backend/RustDroidBackend.java, AnkiDroid/src/main/java/com/ichi2/libanki/backend/RustDroidV16Backend.kt, AnkiDroid/src/main/java/com/ichi2/libanki/backend/model/NoteUtil.kt
Prep for inclusion of Anki's new TTS tags (and other filters)
#5793
No tests, but unused
* https://github.com/ankitects/anki/blob/2.1.34/pylib/anki/template.py
* https://github.com/ankitects/anki/blob/2.1.34/pylib/anki/sound.py
Doing these is a lot more effort than it looks
=> Port Anki sound.py and template.py 

AnkiDroid/kotlinMigration.gradle, docs/kotlin-migration.md
Better to write this than to explain it. Reduces the 🚌 factor.
https://github.com/ankidroid/Anki-Android/pull/9480
Preview this PR: https://github.com/david-allison-1/Anki-Android/blob/c46ac3dd99696527b9d80cdee45e66eb3449f98d/docs/kotlin-migration.md
=> docs: Kotlin Conversion

AnkiDroid/build.gradle, build.gradle
Moved acra version to root build.gradle
Moved acra version to root build.gradle so that any update to to lib version will require change at only one place
=> Moved acra version to root build.gradle

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
When `currentCard` created and assigned the value in class then it does not return correct value. So, `currentCard` directly called from `activity` variable.
Fixes #9730
Removed `currentCard` variable and directly accessed using `activity.currentCard`
Tested using chrome remote debugging on android devices.
=> fix 9730 - Return correct values for current card

docs/kotlin-migration.md
=> docs: Improve Kotlin Migration

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardHtml.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java, AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerSoundRenderTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
Mostly minor refactorings. Won't have a lot of time for forward progress today and this is atomic enough
* Regression Tests
* Conversion to use `SoundOrVideoTag` inside `Sound.java`
* Removed methods from `AbstractFlashcardViewer`
* Fixes a test method
#5793
=> Refactorings to move closer to handling v16 Sound/TTS

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardHtml.kt
This uses `render_content().[question/answer]_av_tags` to obtain the backend data,
instead of manually parsing `[sound:]` tags
Note: Only for sounds, the play buttons from audio and
TTS are unhandled. Content is still mostly from frontend
Fixes tests in `AbstractFlashcardViewerSoundRenderTest` in v16
#5793
=> feat(v16): Load Audio from backend

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java, AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.java, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.java, AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.java
While trying to solve #9755 I found a lot of things that I thought were worth improving in the DeckSpinnerSelection code. So here there are. It's NF, and I hope easier to read
=> NF: Improving spinner code

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/InsertFieldDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/IntegerDialog.kt
https://github.com/ankidroid/Anki-Android/pull/9809#discussion_r744236748
https://github.com/ankidroid/Anki-Android/pull/9807#discussion_r744236183
https://github.com/ankidroid/Anki-Android/pull/9803#discussion_r744230427
Tested each dialog
=> refactor: Kotlin conversion follow ups

AnkiDroid/src/main/java/com/ichi2/libanki/utils/Time.kt
This is a FollowUp cleanup of Time.java migration to Time.kt
1.  Remove Wildcard import.
2.  Resolve import conflict -> Use import alias.
3.  Resolve Warning -> Kotlin's max() instead of Math.max()
=> [Kotlin Migration][Follow-Up] Time

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt, AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPIConstants.kt, AnkiDroid/src/test/java/com/ichi2/anki/AnkiDroidJsAPITest.kt
I have created separated class for JS API constants and added check on API which modify contents in AnkiDroid.
Now it will be easier to add new api.
1. Created a separate class containing for api error code and api name
2. Extracted check on api to a function 
3. Added test on `bury` and `suspend` card and notes
Tested using chrome remote debugging and android devices
=> Refactor JS API and added check on API with test

AnkiDroid/src/main/res/values-be/01-core.xml, AnkiDroid/src/main/res/values-be/02-strings.xml, AnkiDroid/src/main/res/values-be/07-cardbrowser.xml, AnkiDroid/src/main/res/values-be/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-or/01-core.xml, AnkiDroid/src/main/res/values-or/02-strings.xml, AnkiDroid/src/main/res/values-or/03-dialogs.xml, AnkiDroid/src/main/res/values-or/04-network.xml, AnkiDroid/src/main/res/values-or/10-preferences.xml, AnkiDroid/src/main/res/values-or/11-arrays.xml, AnkiDroid/src/main/res/values-or/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-ro/01-core.xml, AnkiDroid/src/main/res/values-uk/01-core.xml, AnkiDroid/src/main/res/values-uk/02-strings.xml, AnkiDroid/src/main/res/values-uk/03-dialogs.xml, AnkiDroid/src/main/res/values-uk/10-preferences.xml, AnkiDroid/src/main/res/values-uk/11-arrays.xml, AnkiDroid/src/main/res/values-uk/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-uz/01-core.xml
=> Updated strings from Crowdin 20211110

AnkiDroid/src/main/res/values-es-rAR/01-core.xml, AnkiDroid/src/main/res/values-or/01-core.xml, AnkiDroid/src/main/res/values-or/02-strings.xml, AnkiDroid/src/main/res/values-or/06-statistics.xml, AnkiDroid/src/main/res/values-or/07-cardbrowser.xml, AnkiDroid/src/main/res/values-or/08-widget.xml, AnkiDroid/src/main/res/values-or/10-preferences.xml, AnkiDroid/src/main/res/values-or/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-or/17-model-manager.xml, AnkiDroid/src/main/res/values-or/18-standard-models.xml, AnkiDroid/src/main/res/values-sk/01-core.xml, AnkiDroid/src/main/res/values-sk/02-strings.xml, AnkiDroid/src/main/res/values-sk/07-cardbrowser.xml, AnkiDroid/src/main/res/values-sk/10-preferences.xml, AnkiDroid/src/main/res/values-sk/11-arrays.xml, AnkiDroid/src/main/res/values-sk/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-sk/18-standard-models.xml
=> Updated strings from Crowdin 20211113

AnkiDroid/src/main/java/com/ichi2/utils/DatabaseChangeDecorator.kt
https://kotlinlang.org/docs/delegation.html
=> refactor: DatabaseChangeDecorator

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java, AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java, AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/SoundPlayer.kt, AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerCommandTest.java, AnkiDroid/src/test/java/com/ichi2/anki/ReviewerKeyboardInputTest.java
Small refactor/perf improvement, untested
Part of a larger plan to combine `TTS` and `Sound`
`getConfigForCurrentCard` hit the database, so this should speed up that aspect
#5793
=> refactor: CardViewer sounds

AnkiDroid/build.gradle, AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/LayoutValidationTest.java, AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogTest.kt, api/build.gradle, build.gradle, lint-release.xml
Dependency updates, get your fresh dependency updates
includes copyright fix and obsolete lint custom check work as well
=> Dependency updates 20211118

AnkiDroid/build.gradle, api/build.gradle, build.gradle
Standard dependency update PR - nothing big in this one that I'm aware of
=> Dependency updates 20211217

AnkiDroid/src/main/res/values-ar/02-strings.xml, AnkiDroid/src/main/res/values-ar/10-preferences.xml, AnkiDroid/src/main/res/values-cs/02-strings.xml, AnkiDroid/src/main/res/values-fr/02-strings.xml, AnkiDroid/src/main/res/values-fr/03-dialogs.xml, AnkiDroid/src/main/res/values-hu/01-core.xml, AnkiDroid/src/main/res/values-ko/02-strings.xml, AnkiDroid/src/main/res/values-or/02-strings.xml, AnkiDroid/src/main/res/values-pt-rBR/02-strings.xml, AnkiDroid/src/main/res/values-pt-rBR/04-network.xml, AnkiDroid/src/main/res/values-pt-rBR/10-preferences.xml, AnkiDroid/src/main/res/values-pt-rBR/11-arrays.xml, AnkiDroid/src/main/res/values-pt-rBR/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-ru/02-strings.xml, AnkiDroid/src/main/res/values-uz/01-core.xml, AnkiDroid/src/main/res/values-zh-rCN/02-strings.xml
Standard I18N sync
the arabic translation with substitutions looked a little suspicious to me but it actually matches the automated suggestion, maybe works?
=> Updated strings from Crowdin 20211231

AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ScopedStorageMigrationDialog.kt, AnkiDroid/src/main/res/layout/scoped_storage_confirmation.xml, AnkiDroid/src/main/res/values/02-strings.xml, AnkiDroid/src/main/res/values/constants.xml, AnkiDroid/src/main/res/values/styles.xml, docs/scoped_storage/README.md, docs/scoped_storage/consent.md
To release on the Play Store, we need to implement scoped storage
Since the migration to scoped storage can take a while, and has a low,
but nonzero chance of data corruption, we want to show a dialog to the
user, ensuring that:
* They understand that we need to do this
* They understand the risks
* They have backed up
* They won't uninstall the app before/during
the migration
We also add a link to https://github.com/ankidroid/Anki-Android/wiki/Storage-Migration-FAQ
to ensure that users are informed.
Since we can set "preserveLegacyExternalStorage", we don't need the
user to immediately migrate, but this stops working if the user
uninstalls, and the directory becomes inaccessible
Issue #5304
[Please see /docs/ changes](https://github.com/david-allison-1/Anki-Android/tree/b60893bf5c73fc089a …
=> feat(scoped-storage): Add consent dialog

AnkiDroid/build.gradle, build.gradle
Standard dependency updates, 2 patch versions, really tiny, but this clears the queue
=> Dependency updates 20220102

AnkiDroid/src/main/java/com/ichi2/themes/HtmlColors.kt
fixes #10121
added missing ecapes in cloze style format 
tested on emulator 
=> Bug Fixed: Added ExpRedundantEscape in HtmlColors.kt

AnkiDroid/src/main/java/com/ichi2/libanki/template/EmptyNode.java
All empty nodes are equal, so constant hash is okay
=> NF: add `hashCode` to EmptyNode

AnkiDroid/build.gradle
Standard dependency updates PR, building towards a release shortly...
=> Dependency updates 20220115

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/Shared.java, AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java, AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java, AnkiDroid/src/main/java/com/ichi2/libanki/CollectionV16.kt, AnkiDroid/src/main/java/com/ichi2/libanki/DB.java, AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java, AnkiDroid/src/main/java/com/ichi2/libanki/backend/DroidBackend.java, AnkiDroid/src/main/java/com/ichi2/libanki/backend/JavaDroidBackend.java, AnkiDroid/src/main/java/com/ichi2/libanki/backend/RustDroidBackend.java, AnkiDroid/src/main/java/com/ichi2/libanki/backend/RustDroidV16Backend.kt, AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java, AnkiDroid/src/main/java/com/ichi2/libanki/importer/Importer.java, AnkiDroid/src/main/java/com/ichi2/libanki/importer/NoteImporter.kt, AnkiDroid/src/main/java/com/ichi2/libanki/importer/TextImporter.java, AnkiDroid/src/test/java/com/ichi2/testutils/BackendEmulatingOpenConflict.java
I followed through each call/assignment, and by induction, it's clear that path
is always non null when used.
=> NF: path is always non null

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ACRATest.java, AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java, AnkiDroid/src/main/res/values/05-feedback.xml
Fixes #10029
String feedback_manual_toast_text has been edited with appropriate message and the reference to it is also updated.
=> String feedback_manual_toast_text and the reference to it has been updated

AnkiDroid/src/test/java/com/ichi2/testutils/AnkiAssertKt.kt, AnkiDroid/src/test/java/com/ichi2/utils/ComputationTest.kt
This makes the method a little less verbose to use
=> assertThrows: convert to reified generic

AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java, AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java
=> docs: document 'deckPath'

AnkiDroid/build.gradle, AnkiDroid/src/main/AndroidManifest.xml, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/PickStringDialogFragment.kt, AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java, build.gradle, gradle.properties, lint-release.xml
This is the same as #10272 was, but this time with a fix for the noted failure in a kotlin file that merged before I made the PR
=> build(deps): bump android-gradle-plugin to 7.1

AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.java
Found during Scoped Storage work.
The `new File` fix is a very minor speedup. The rest removed the yellow errors in the sidebar.
* Fix copyright header
* Fix imports
* Fix "'new File' is redundant"
* Fix erroneous warning saying "deprecated" is redundant
* Add `KotlinCleanup` for ignored return value of `File.delete()`
CI only
All Android Studio lints. I feel the `new File` was new (Android Studio Bumblebee?), and is a minor performance improvement
=> lint: CompatV21

AnkiDroid/build.gradle, AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/LayoutValidationTest.java, build.gradle, lint-rules/src/test/java/com/ichi2/anki/lint/rules/PreferIsEmptyOverSizeCheckTest.java
=> Dependency updates 20220201

AnkiDroid/src/main/java/com/ichi2/compat/Compat.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.java, AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.java
Use `Files.delete` which provides a useful exception if on V26 or later
https://docs.oracle.com/javase/7/docs/api/java/io/File.html#delete()
https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#delete-java.nio.file.Path-
=> feat(Compat): add deleteFile

AnkiDroid/src/main/res/values-ko/10-preferences.xml, AnkiDroid/src/main/res/values-ko/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-nl/10-preferences.xml, AnkiDroid/src/main/res/values-or/03-dialogs.xml, AnkiDroid/src/main/res/values-or/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-or/17-model-manager.xml, AnkiDroid/src/main/res/values-pl/02-strings.xml, AnkiDroid/src/main/res/values-tr/02-strings.xml, AnkiDroid/src/main/res/values-tr/05-feedback.xml
Standard I18n sync
has some issues, opening it now but will need to work on context for cloze deletion at least
=> Updated strings from Crowdin 20220206

AnkiDroid/src/main/java/com/ichi2/utils/NoteFieldDecorator.kt
There are some cases of Note Editing, specifically if you have a 2 field card, and the second field is empty, where you should apply special decoration to the card based on the first field.  Updates and additions to these decorations are occasionally required due to the passage of time. Today is one of those times.
Some effort was spent making sure that the Spanish language in particular was supported and that when considering a 26-letter alphabet, the desired decorations could readily be converted between our chosen storage mechanism and their regular representation with an easily reversible storage encoding by dividing the 26 letters into two 13-letter spaces with a rotating transform.
=> Update special field decoration mode

.github/workflows/lint.yml, AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java, AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTabOrderTest.java, AnkiDroid/src/androidTest/java/com/ichi2/anki/TestUtils.java, AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ACRATest.java, AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.java, AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/NotificationChannelTest.java, AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/DBTest.java, AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/ImportTest.java, AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/MediaTest.java, AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/ModelTest.java, AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/RetryRule.java, AnkiDroid/src/androidTest/java/com/ichi2/ui/ActionBarOverflowTest.java
Fixes lint errors, then fixes `lint.yml` to run `androidTest`
Fixes #10322
=> fix: androidTest lint

AnkiDroid/src/main/java/com/ichi2/anki/model/DiskFile.kt, AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MigrateUserData.kt
I didn't want to block submitting those files just for those comments. Now that
the main part is merged, we can discuss this separately.
=> NF: suggestion of documentation improvement

AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardAppearance.kt, AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardHtml.kt
Fixes #10356 
Tested on emulator (API 29)
=> breaking(css): remove answer and question css classes

AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveFileTest.kt
=> NF: check that MoveFile has no next operation

AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryTest.kt, AnkiDroid/src/test/java/com/ichi2/testutils/FileUtil.kt
as requested by @david-allison
=> NF: test for file/directory created during directory transfer

AnkiDroid/build.gradle
A list of additional compiler arguments
[comment](https://github.com/ankidroid/Anki-Android/pull/10060#discussion_r792913468)
=> freeCompilerArgs in tasks.KotlinCompile

build.gradle
Tiny bumps on dependency updates
=> Dependency updates 20220301

AnkiDroid/src/main/assets/scripts/card.js, AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt, AnkiDroid/src/main/res/values/02-strings.xml
Return list of cards when searched using JS API to callback function. It returns the field name and corresponding fields data in json array to webview. 
Also it uses,
```
com.ichi2.anki.servicelayer.SearchService
com.ichi2.async.CollectionTask.SearchCards
```
So each search query can be used in the following docs
https://docs.ankiweb.net/searching.html
Fixes #9633
I used task delegate to `TaskManager.launchCollectionTask` in background with a new listener class in which `onPostExecute` function pass the results to reviewer webview.
Tested on device.
**Example 1**
```js
<script>
function parseResult(result) { 
for (res of result) {
console.log(res)
}
}
addHook("ankiSearchCard", parseResult)
function someButtonClickFunction() {
AnkiDroidJS.ankiSearchCardWithCallback('study')
}
</script>
``` …
=> Search card and get result in callback function in reviewer

AnkiDroid/src/test/java/com/ichi2/compat/CompatDeleteFileTest.kt, AnkiDroid/src/test/java/com/ichi2/compat/CompatDirectoryContentTest.kt, AnkiDroid/src/test/java/com/ichi2/compat/CompatHasFilesTest.kt
This is the package of package implementation
=> NF: move all Compat tests in same package

lint-rules/src/main/java/com/ichi2/anki/lint/rules/CopyrightHeaderExists.java
Had an unfinished sentence, and I link the class fairly regularly
=> docs(copyright): Improve docs

AnkiDroid/build.gradle, build.gradle
Standard dependency updates, nothing special here
=> Dependency updates 20220308

AnkiDroid/src/main/assets/scripts/card.js, AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java, AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.kt, AnkiDroid/src/main/res/values/11-arrays.xml, AnkiDroid/src/main/res/values/constants.xml, AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/ViewerCommandTest.kt
Fixes #7354
- Insert javascript to toggle hint one by one in `Toggle hint`, assigned to H hotkey
- Insert javascript to toggle all hints in `Toggle all hints`, assigned to G hotkey
Personally, I think the toggle hint js code isn't the most beautiful thing ever ~~as most of javascript~~, but I prefer it because it is easier to understand/mantain.
A shorter version, but somewhat harder to grasp is:
```javascript
[...document.querySelectorAll('a.hint')].every(el=>{ if (el.style.display != 'none') { el.click(); return; } })
```
If necessary, I can exchange them.
On my phone (Samsung Galaxy Note 10 Lite SM-N770F/DS, API 30)
https://user-images.githubusercontent.com/69634269/157347222-21f4f5cc-2000-4a7f-95a4-24b9ac826004.mp4
https://user-images.githubusercontent.com/69634269/157347245-296e001a-e …
=> Add hint gesture/command

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt, AnkiDroid/src/main/java/com/ichi2/utils/ArgumentUtils.kt, AnkiDroid/src/test/java/com/ichi2/utils/ArgumentUtilsTest.kt
- Removed nullability at some places where it wasn't required.
- Used `?.` and `let` instead of `!!`
- Fixed unchecked cast
- Other small changes
https://stackoverflow.com/a/58657456
https://blog.mindorks.com/what-are-reified-types-in-kotlin
https://stackoverflow.com/questions/45949584/how-does-the-reified-keyword-in-kotlin-work
https://kotlinlang.org/docs/inline-functions.html#reified-type-parameters
=> Enhancements in CardBrowserMySearchesDialog.kt

AnkiDroid/build.gradle
Only one at the moment but just keeping the cadence for alpha release
=> Dependency updates 20220311

AnkiDroid/src/main/java/com/ichi2/anki/WhiteboardMultiTouchMethods.kt
com.ichi2.anki.WhiteboardMultiTouchMethods
No rename commit as git detects the rename (will change this if CI fails)
=> Convert WhiteboardMultiTouchMethods.java -> kt

AnkiDroid/src/main/java/com/ichi2/anki/CardUtils.kt
Kotlin Cleanup: renamed `val` to value in CardUtils.kt
Fixes part of [#10489](https://github.com/ankidroid/Anki-Android/issues/10489)
1. Renamed the variable at all occurrences 
Passed all the unit tests and runs as expected on Realme 6i API 31
- [   ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [   ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)
=> Kotlin cleanup

AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContentTest.kt, AnkiDroid/src/test/java/com/ichi2/testutils/FileSystemUtils.kt
It was never actually used as a directory
=> NF: Directory.createTransientDirectory return File

AnkiDroid/src/test/java/com/ichi2/anki/model/DirectoryTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/DeleteEmptyDirectoryTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContentTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryTest.kt, AnkiDroid/src/test/java/com/ichi2/compat/CompatDirectoryContentTest.kt, AnkiDroid/src/test/java/com/ichi2/compat/CompatHasFilesTest.kt, AnkiDroid/src/test/java/com/ichi2/compat/Test21And26.kt
It is used to factorize code repeated 6 times
=> NF: factorize createPermissionDenied

AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.kt
Kotlin Cleanup
Fixes a part of [#10489](https://github.com/ankidroid/Anki-Android/issues/10489)
1. Removed redundant type casts
2. Assigned types for some variables
3. Replaced null comparison with let
1. Passes all unit tests
2. Works as expected on Realme 6i and Pixel 4 Emulator
https://user-images.githubusercontent.com/69595691/158171656-e576be36-2b81-4edb-a27f-23bf2246014f.mp4
- [✓] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [✓] You have a descriptive commit message with a short title (first line, max 50 chars).
- [✓] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [✓] You have commented your code, particularly in hard-to-understand areas
- [✓] You have performed a self-review of your own code
- [✕] UI …
=> Kotlin Cleanup in DeckPickerFloatingActionMenu.Kt

AnkiDroid/src/main/java/com/ichi2/anki/DrawingActivity.kt
User asked how to access this screen. Seemed sensible to document it.
=> docs: Drawing Activity

AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
=> refactor(preferences): improve editing (Kotlin)

AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.java
Makes for an easier Kotlin conversion
=> fix(compat): Add Nullability annotations

AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.java
Remove dependency on deprecated code
Fixes a part of #8602
Passes unit tests and worked as expected on Realme 6i API 31
* https://user-images.githubusercontent.com/69595691/158311235-e0240a88-8202-4a53-adc4-c528af54b642.mp4
* https://user-images.githubusercontent.com/69595691/158311219-46df391e-b854-4250-864d-50853f82c0e8.mp4
=> migration from startActivityForResult to new API in ModelBrowser.java

AnkiDroid/src/main/res/values/11-arrays.xml
This maps them to their previous positional values to make it easier to re-apply translations
ref: d7858d57416211071837663892c02c742cb9f02a ([#10556](https://github.com/ankidroid/Anki-Android/pull/10556))
=> nf: reorder strings

AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.kt
Incomplete display of statistical charts
Fixes #10518
bug is due to if and else statement is not correct in kotlin
android Device :Redmi y3
=> [bug fix]-Incomplete display of statistical charts

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ContextMenuHelper.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt, AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.kt
Reviewing all `@KotlinCleanup` annotations from `CustomStudyDialog.kt` and refactoring them in order to improve code quality.
Related to #10489.
9439fea5bed0a23fdffec6e24a87dcc1da2c81fe (Most annotations in the file are fixed here) should be an easy review and (in my belief) does not raise any questions.
cc397f26b264ae76bb62d2e53b20489543703fb7 (only about this bit: `@KotlinCleanup("Map dialogID to enum to make exhaustive")`) It's quite a lot and I'm not fully convinced, that it is an improvement.
local testing
=> [Kotlin Cleanup] CustomStudyDialog

AnkiDroid/src/test/java/com/ichi2/compat/CompatSoundTest.kt
Remove `AnkiDroidApp` dependency
=> refactor(CompatSoundTest): Speed up

AnkiDroid/src/main/res/layout/model_browser.xml, AnkiDroid/src/main/res/layout/model_field_editor.xml, AnkiDroid/src/main/res/layout/multimedia_edit_field_activity.xml, AnkiDroid/src/main/res/layout/studyoptions.xml, lint-release.xml
Enable RedundantNamespace Lint
Fixes #10480 
issue id="RedundantNamespace" severity="ignore" 
Change ignore to fatal
fix the below issues
=> [lint] enable-redundantNamespace-lint

AnkiDroid/src/test/java/com/ichi2/utils/ArgumentUtilsTest.kt, AnkiDroid/src/test/java/com/ichi2/utils/BundleUtilsTest.java, AnkiDroid/src/test/java/com/ichi2/utils/ContentResolverUtilTest.java, AnkiDroid/src/test/java/com/ichi2/utils/HtmlUtilsTest.java, AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilsTest.java, AnkiDroid/src/test/java/com/ichi2/utils/MaxExecFunctionTest.java
Use `EmptyApplication`/Remove `RunWith`
Let's see if we can get to 7:XX on the CI test run, save some 🌳🌳
=> refactor(tests): Improve performance

AnkiDroid/src/test/java/com/ichi2/anki/reviewer/AnswerTimerTest.kt
Added message explanations to tests in AnswerTimerTest.kt (package com.ichi2.anki.reviewer)
Partially Fixes #10385  
Tests were re-run and no error occurred
=> Added message explanations

AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt
By following `@KotlinCleanup` annotation, removed few possible null pointer exceptions && renamed `in` to inputStream in ImportUtils.kt.
Contributes to [#10489](https://github.com/ankidroid/Anki-Android/issues/10489)
By replacing `!!` operator to elvis operator, two possible NPEs are handled. Additionally, `in` was renamed to `inputStream`
Ran all the tests, mentioned in [Development Guide](https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#running-automated-tests), but the most crucial one is `ImportUtilsTest.java` that was successful.
This PR seems like a band-aid to a problem that is not solved fully. Methods `sendShowImportFileDialogMsg` && `validateZipFile` should not accept nullable parameters, instead, in method `handleContentProviderFile`, line 172, `val tempOutDir` …
=> [Kotlin Cleanup] ImportUtils.kt Polish

AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt
=> Cleanup: CompatHelper

AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/TypeAnswer.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioPlayer.kt, AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ReviewerCustomFonts.kt, AnkiDroid/src/main/java/com/ichi2/async/ProgressSender.kt, AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt, AnkiDroid/src/main/java/com/ichi2/utils/StringUtil.kt
Untested, trivial cleanups to remove code
=> Kotlin Cleanups

AnkiDroid/src/main/java/com/ichi2/utils/Threads.kt
Refactoring/Kotlin Cleanup
* remove unused methods
* make `isOnMainThread` private
Untested - IDE suggested refactorings
=> refactor: Threads

AnkiDroid/src/main/java/com/ichi2/upgrade/Upgrade.kt
kotlinCleanUp of upgrade.kt
Fixes part of  #10489
Android Device :redmi y3
Run all the unit test
=> [kotlinCleanUp] Upgrade.kt

.github/workflows/label.yml, .github/workflows/milestone.yml
fix `Resource not accessible by integration`
Fixes #10410
It needs to be `pull_request_target` not `pull_request`.
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target
https://github.com/interledger/rafiki/pull/280/files
=> Fix auto label and milestone to PR

README.md
There was a `</p>` tag without a preceding `<p>` tag before it.
N/A
Removes the isolated tag for proper syntax.
Stops Android Studio from declaring a syntax error.
N/A
=> Remove unopened </p> tag

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java, AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/CustomToolbarButton.kt, AnkiDroid/src/main/res/layout/note_editor_toolbar_edit_custom_item.xml, AnkiDroid/src/main/res/values/02-strings.xml, AnkiDroid/src/main/res/values/03-dialogs.xml
Adding edit feature to custom toolbar button in Add Note screen.
Fixes #10436
- Added "Edit" button to the remove dialog and changed its text slightly to suggest the feature. 
- On clicking "Edit" button a dialog similar to create item appears with "Create" button replaced with "Save"
- On clicking "Save" saved the changes to the button
Tested it manually.
https://user-images.githubusercontent.com/54733471/157710110-2563733b-9cdf-49f4-a7cc-ef19bb61ebff.mp4
=> Edit feature added to custom toolbar button

AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
kotlinCleanUp of ModelFieldEditor.kt
Fixes part of #10489 
Remove Hungarian notation
Use scope functions
Android Device: Samsung a03s
Run all the unit test
=> [kotlinCleanUp] ModelFieldEditor.kt

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioRecorder.kt, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioView.kt, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioRecordingFieldController.kt, AnkiDroid/src/main/java/com/ichi2/anki/stats/StatsMetaInfo.kt, AnkiDroid/src/main/java/com/ichi2/libanki/stats/AdvancedStatistics.java, AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.java
**kotlincleanUp of AudioRecorder.kt,AudioView.kt,StatsMetaInfo.kt**
Fixes some of #10489 
=> [kotlin cleanUp]  AudioRecorder.kt,AudioView.kt,StatsMetaInfo.kt

.github/workflows/label.yml
I have created PR earlier to the same task but that does not fix. I have used official github script in this PR. 
Fixes #10410
Used [github-script](https://github.com/actions/github-script) to remove labels.
There are not api remove labels in bulk. Only two API available remove all labels or remove single label.
I used API to fetch the list of label added to merged PR, then used remove single label API in loop to remove the specific labels.
I have tested it on my repository it works there but it needs to tested here.  …
=> fix: Remove specific labels from merged PR

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt, AnkiDroid/src/test/java/com/ichi2/anki/AnkiDroidJsAPITest.kt
=> lint: Flashcard Viewer

AnkiDroid/src/main/java/com/ichi2/themes/Themes.kt
=> style: fix emails

AnkiDroid/src/main/java/com/ichi2/anki/Info.kt, AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/TypeAnswer.kt, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronounciationActivity.kt, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/beolingus/parsing/BeolingusParser.java, AnkiDroid/src/main/java/com/ichi2/libanki/DB.java, AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/CardTemplateTest.java, AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/TypeAnswerTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/beolingus/parsing/BeolingusParserTest.java
Makes things looks better in the IDE. I thought this fixed typos, but there are still some issues.
=> style: Add language attributes

AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupMetaTest.java
It was removed in 9d12f5d5b06f6377b073a1530189f69f658774fd
=> NF: remove "yalantis" word from test

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateBrowserAppearanceEditor.java, AnkiDroid/src/main/res/drawable/ic_tune_white.xml, AnkiDroid/src/main/res/menu-television/reviewer.xml, AnkiDroid/src/main/res/menu/reviewer.xml
Add an icon to the item of "Deck options" on Actionbar of Study screen
Fixes #10731 
Just go into drawable folder & add ic_tune_white.xml, then go into menu folder & edit (i.e. add icon to menu) reviewer.xml
Run project via android studio on emulator as well as real device
I got whole codebase of Anki-Android & started exploring it deeply.
=> An icon added to the item of "Deck options" on Actionbar

.github/workflows/milestone.yml
Add merged PR to current milestone.
Fixes #10410
I have used permission to solve `Resource not accessible by integration`.  Additional permission `issues: write` added.
```
permissions:
contents: read
issues: write
pull-requests: write
```
Tested on local repository. It needs to test here. Hope it will work now.
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
=> fix: add merged pr to milestone

AnkiDroid/src/main/res/values-nl/01-core.xml, AnkiDroid/src/main/res/values-nl/02-strings.xml
This might be the smallest I18N sync ever. Or at least really close.
=> Updated strings from Crowdin 20220409

.github/workflows/milestone.yml
`curl` was used to send request for adding milestone to merged PR. But now GitHub actions script used to do the same task. It is cleaner and better than previous implementation. 
Fixes #10749
Used [github-script](https://github.com/actions/github-script) to add milestone
Tested on my repository
https://github.com/actions/github-script
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
=> enhancements: add merged pr to milestone

build.gradle
Standard dependency updates, mainly to get android studio to stop prompting me to upgrade gradle plugin...
=> Dependency updates 20220411

AnkiDroid/src/main/java/com/ichi2/ui/AutoSizeCheckBoxPreference.kt
[KotlinCleanup] file AutoSizeCheckBoxPreference.kt
Kotlin cleanup of file AutoSizeCheckBoxPreference.kt
Part of #10489
Using lint removed all the unnecessary error
By mannualy bulding the project
=> [@KotlinCleanup] file AutoSizeCheckBoxPreference.kt

AnkiDroid/src/main/res/values-cs/10-preferences.xml, AnkiDroid/src/main/res/values-heb/01-core.xml, AnkiDroid/src/main/res/values-heb/02-strings.xml, AnkiDroid/src/main/res/values-heb/03-dialogs.xml, AnkiDroid/src/main/res/values-ja/01-core.xml, AnkiDroid/src/main/res/values-ja/02-strings.xml, AnkiDroid/src/main/res/values-ja/03-dialogs.xml, AnkiDroid/src/main/res/values-pt-rBR/02-strings.xml
Standard I18N request, not too large, LGTM ?
=> Updated strings from Crowdin 20220412

.github/workflows/tests_unit.yml
Updated to run tests with matrix for Windows, macOS, and Linux
Fixes #10658
Matrix runs it for Windows, Mac, and Linux.
Timeout had to be increased because when testing windows would be very slow sometimes.
Latest windows uses powershell and not bash so I had to change running 2 commands from "&&" to "|" for multi line commands.
Run unit tests for all 3 systems on GitHub actions.
- ✓ You have not changed whitespace unnecessarily (it makes diffs hard to read)
- ✓ You have a descriptive commit message with a short title (first line, max 50 chars).
- ✓ Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- ✗ You have commented your code, particularly in hard-to-understand areas
- ✓ You have …
=> Test Matrix

lint-rules/src/main/java/com/ichi2/anki/lint/rules/JUnitNullAssertionDetector.kt
* kotlin.test is better if we use assertNull/assertNotNull without a message
Improve some strings
Ran unit tests
https://kotlinlang.org/api/latest/kotlin.test/kotlin.test/assert-null.html
https://kotlinlang.org/api/latest/kotlin.test/kotlin.test/assert-not-null.html
https://kotlinlang.org/api/latest/kotlin.test/kotlin.test.junit/-j-unit-asserter/
=> docs: improve JUnitNullAssertionDetector message

AnkiDroid/src/test/java/com/ichi2/anki/CardBrowser_CardCollectionTest.kt
=> fix build: conflicted conversion of CardBrowser

AnkiDroid/src/test/java/com/ichi2/anki/PreferencesTest.kt
The property of instance object is set using scope function
part of #10489 
Using apply and lazy implementation.
By running on my own physical device : Realme 8i
=> [KotlinCleanUp] PreferencesTest

AnkiDroid/src/main/java/com/ichi2/utils/FileUtil.kt, AnkiDroid/src/test/java/com/ichi2/utils/FileUtilTest.java
For use in Scoped Storage Migration
Unit tested
=> Function to get `File` size

AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserCardCollectionTest.kt
At the moment the build fails because of some errors in this class. I fixed the `@KotlinCleanup` issues to make the code build.
Edit: I will rebase my changes after #10844 is merged to fix any merge conflicts.
Ran the usual tests
=> Resolve @KotlinCleanup and fix build for CardBrowser_CardCollectionTest.kt

AnkiDroid/src/test/java/com/ichi2/anki/reviewer/KeyboardShortcutIntegrationTest.kt
Kotlin cleanup
part of #10489 
Physical device : Realme 8i
=> [KotlinCleanUp] KeyboardShortcutIntegrationTest

AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonData.kt, AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonModel.kt, AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonsConst.kt, AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmUtils.kt, AnkiDroid/src/test/java/com/ichi2/anki/jsaddons/AddonModelTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/jsaddons/NpmUtilsTest.kt, AnkiDroid/src/test/resources/not-valid-ankidroid-js-addon-test.json, AnkiDroid/src/test/resources/valid-ankidroid-js-addon-test.json
This is second PR in JS Addons series. 
Before downloading addon tgz packages, it needs to check if the addon package is valid or not for AnkiDroid using `package.json`.
The validity checked using three fields `addonTitle`, `ankiDroidJsApi` and `ankidroid-js-addon` keyword which are not present in other npm package's `package.json` file. These fields will be used to distinguish it from other npm packages. It is required for addon developer to add these fields to `package.json` file otherwise the packages will not be downloaded and extracted. 
Also it needs to check that name should be valid npm packages. The `validatename` method is implemented to check if name follow the naming convention of npm packages.
Fixes #7959 
1. A class with the fields that may be present in package.json file. …
=> [JS Addons] Map package.json to AddonModel and check if is valid addon package or not

AnkiDroid/src/main/java/com/ichi2/libanki/DeckManager.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
=> Decks: Add JSON highlighting

AnkiDroid/src/main/res/values/02-strings.xml
=> chore: remove completed TODO

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
I wanted to get the class to 0 IDE warnings, then went and fixed the `lateinit`s, aside from one which is a little more tricky.
Unit tested 
Tested on my Android 11 Google Pixel 3a
⚠️ Untested on a tablet
=> Kotlin Cleanup: DeckPicker

AnkiDroid/src/test/java/com/ichi2/utils/JSONObjectTest.kt
Unit test: for catch part of the getBoolean, getInt, getLong, getStrong functions in JSONObject
I have tested by running it on my local machine
=> Unit test: for catch part in JSONObject

AnkiDroid/src/test/java/com/ichi2/anki/AnalyticsTest.kt
=> refactor: AnalyticsTest - Kotlin Cleanup

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateBrowserAppearanceEditor.kt
Just cleaning up Kotlin migration leftovers. 
Addresses #10489.
Manually tested on my OnePlus 8T, Android 11. No issues were found.
=> [Kotlin Cleanup] CardTemplateBrowserAppearanceEditor.kt

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt
untested. Helpful for `CollectionTask` Kotlin migration
=> refactor: DeckPicker nullability

AnkiDroid/src/main/java/com/ichi2/utils/KotlinCleanup.kt
This PR enables `@KotlinCleanup` for local variables which would be helpful to better scope @KotlinCleanup. For example:
```
@KotlinCleanup("use scope function)
val localVariable = Something()
localVariable.stuff1...
localVariable.stuff2...
localVariable.stuff3...
```
versus adding the annotation to the method(sometimes is too broad) or to one of the statements following the local variable declaration.
Nothing really to test here.
=> Enable @KotlinCleanup for local variables

AnkiDroid/src/main/java/com/ichi2/utils/CollectionUtils.kt
There is a unit test conversion PR in flight right now, (#11000) so I didn't delete the class just yet.
=> refactor: prepare CollectionUtils for removal

AnkiDroid/src/main/java/com/ichi2/anki/Statistics.kt
Fixes some warning from running code analysis on the file.
There are a couple outstanding `@KotlinCleanup` items I'd appreciate if anyone could explain or clarify for me.
_line 85_
```
@KotlinCleanup("cleanup: scope function")
```
_line 133_
```
@KotlinCleanup("cleanup: findItem -> isChecked to nested function")
```
Part of #10489 
Removes some `@KotlinCleanup`s and simplifies designated blocks of code
Navigated to "Statistics" section in sidebar (physical device), checked for any irregularities or crashes.
=> [Kotlin Cleanup] Statistics.kt

AnkiDroid/kotlinMigration.gradle, tools/migrate.sh
Test + enable
Tested `DeckPickerTest` - first commit compiles and executes 183 tests.
=> kotlin migration: Enable migrate script for ANDROID_TEST

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ScopedStorageMigrationDialog.kt
=> feat(scoped-storage): let dialog execute migration

AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonData.kt, AnkiDroid/src/test/java/com/ichi2/anki/jsaddons/AddonModelTest.kt, AnkiDroid/src/test/resources/test-js-addon.json
In download/install addon screen, the addons are listed in with addon model info. It needs to parse addon data then addon model from json strings. 
(In next PR mapping [anki-js-addon.json](https://github.com/krmanik/anki-js-addon-json/blob/main/anki-js-addon.json) to view)
Fixes 
1. Created a repository for listing and exporting all valid addons containing `ankidroid-js-addon` keywords from npmjs using GitHub actions
https://github.com/krmanik/anki-js-addon-json
2. There are two json file exported. 
a) `anki-js-addon.json` - will be used in download/install screen, containing all addons with  `ankidroid-js-addon` keywords
b) `test-js-addon.json` - will be used in unit test, containing only two addons info
3. Used this to map json to AddonData list 
```kotlin
val mapper = …
```
=> enhancements: get list of addons model from json containing array of addons data

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt, AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPIConstants.kt, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt, AnkiDroid/src/test/java/com/ichi2/anki/AnkiDroidJsAPITest.kt
Reschedule a card using JS API with x days.
Fixes #9727
Used existing implemented function to reschedule the card.
```kotlin
RescheduleCards(cardIds, days).runWithHandler(scheduleCollectionTaskHandler(R.plurals.reschedule_cards_dialog_acknowledge))
```
Tested on devices and implemented Junit test.
https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-Javascript-API
=> [JS API] Reschedule card with x days

AnkiDroid/build.gradle, AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt
Kotlin cleanup.
Parts of #10489
Just follow the annotations.
I run the unit test file in my own computer. All testcase passed.
=> Kotlin Cleanup: AbstractFlashcardViewerTest.kt

AnkiDroid/build.gradle, build.gradle, lint-rules/build.gradle
Semi-standard dependency updates - leakcanary had big changes on main which I integrated here with rebase merge / conflict resolve, and I made a change to kotlin stdlib dependencies
Everything *seems* fine but of course I/we will be watching...
CI mostly but leakcanary got testing during it's related work
Definitely remember to push main changes to dependency updates branch before making these PRs as the branches do interact between each other sometimes while updates are collecting on the dependencies branch..
=> Dependency updates 20220425

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
Kotlin CleanUp
Part of #10489
Using lint and some code changes which were mentioned in the comments and  required to make the code more reliable
=> [KotlinCleanup] LoadPronunciationActivity.kt

AnkiDroid/src/test/java/com/ichi2/testutils/MockTimeTest.kt
[Kotlin Cleanup] MockTimeTest.kt
=> [Kotlin Cleanup] MockTimeTest.kt

AnkiDroid/src/test/java/com/ichi2/utils/ExtendedFragmentFactoryTest.kt
[Kotlin Cleanup] ExtendedFragmentFactoryTest.kt
=> [Kotlin Cleanup] ExtendedFragmentFactoryTest.kt

tools/migrate.sh
Fixes: #11100 : nit3
Reformat the code with Shell Script formatter
Remove shellCheck warnings
=> [./tools/migrate.sh] remove warnings+reformat

AnkiDroid/src/test/java/com/ichi2/anki/MyAccountTest.kt
added test coverage for the login method of `MyAccount.kt` using instrumentation tests.
Used Espresso to do the tests
=> Test coverage for the login method of `MyAccount.kt`

AnkiDroid/src/test/java/com/ichi2/utils/ContentResolverUtilTest.kt
[Kotlin Cleanup] ContentResolverUtilTest
=> [Kotlin Cleanup] ContentResolverUtilTest

AnkiDroid/src/test/java/com/ichi2/utils/BundleUtilsTest.kt
[Kotlin Cleanup] BundleUtilsTest
=> [Kotlin Cleanup] BundleUtilsTest

AnkiDroid/src/test/java/com/ichi2/utils/AssetHelperTest.kt
[Kotlin Cleanup] AssertHelperTest
=> [Kotlin Cleanup] AssertHelperTest

AnkiDroid/src/test/java/com/ichi2/utils/MapUtilTest.kt
=> [Kotlin Cleanup] MapUtilTest

AnkiDroid/src/test/java/com/ichi2/anki/TestCardTemplatePreviewer.kt
[Kotlin Cleanup] TestCardTemplatePreviewer
=> [Kotlin Cleanup] TestCardTemplatePreviewer

AnkiDroid/src/test/java/com/ichi2/anki/reviewer/AutomaticAnswerTest.kt
Added message explanations to tests in AutomaticAnswerTest.kt (package com.ichi2.anki.reviewer)
Partially fixes #10385 
Tests were re-run and no error occurred
=> Added test message explanations

AnkiDroid/src/test/java/com/ichi2/utils/UniqueArrayListTest.kt
[Kotlin Cleanup] UniqueArrayListTest
=> [Kotlin Cleanup] UniqueArrayListTest

AnkiDroid/src/main/java/com/ichi2/anki/stats/OverviewStatsBuilder.kt
Kotlin CleanUp
Part of [https://github.com/ankidroid/Anki-Android/issues/10489]
Using lint and some code changes which were mentioned in the comments and required to make the code more reliable
=> [KotlinCleanup] OverviewStatsBuilder.kt

AnkiDroid/src/test/java/com/ichi2/utils/ExceptionUtilTest.kt
[Kotlin Cleanup] ExceptionUtilTest
=> [Kotlin Cleanup] ExceptionUtilTest

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
Kotlin CleanUp
Part of [https://github.com/ankidroid/Anki-Android/issues/10489]
Using lint and some code changes which were mentioned in the comments and required to make the code more reliable
=> [KotlinCleanup] AnkiDroidJsAPI.kt

AnkiDroid/src/test/java/com/ichi2/utils/CollectionUtilsTest.kt
[Kotlin Cleanup] CollectionUtilsTest
=> [Kotlin Cleanup] CollectionUtilsTest

AnkiDroid/src/test/java/com/ichi2/utils/DeckNameComparatorTest.kt
[Kotlin Cleanup] DeckNameComparatorTest
=> [Kotlin Cleanup] DeckNameComparatorTest

AnkiDroid/src/test/java/com/ichi2/utils/FileUtilTest.kt
=> [Kotlin Cleanup] FileUtilTest

AnkiDroid/src/test/java/com/ichi2/utils/ResourceLoader.kt
[Kotlin Cleanup] ResourceLoader
=> [Kotlin Cleanup] ResourceLoader

AnkiDroid/src/test/java/com/ichi2/utils/FragmentFactoryUtilsTest.kt
[Kotlin Cleanup] FragmentFactoryUtilsTest
=> [Kotlin Cleanup] FragmentFactoryUtilsTest

AnkiDroid/src/test/java/com/ichi2/anki/IntentHandlerTest.kt
[Kotlin Cleanup] IntentHandlerTest
=> [Kotlin Cleanup] IntentHandlerTest

AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/CardTemplateTest.kt
[Kotlin Cleanup] CardTemplateTest
=> [Kotlin Cleanup] CardTemplateTest

AnkiDroid/src/androidTest/java/com/ichi2/libanki/DBTest.kt
=> [Kotlin Cleanup] DBTest

AnkiDroid/src/test/java/com/ichi2/utils/AssetHelperTest.kt
[Kotlin Cleanup] AssetHelperTest
=> [Kotlin Cleanup] AssetHelperTest

AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/MissingImageHandlerTest.kt
[Kotlin Cleanup] MissingImageHandlerTest
=> [Kotlin Cleanup] MissingImageHandlerTest

AnkiDroid/src/test/java/com/ichi2/testutils/MockContentResolver.kt
[Kotlin Cleanup] MockContentResolver
=> [Kotlin Cleanup] MockContentResolver

AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilsTest.kt
[Kotlin Cleanup] LanguageUtilsTest
=> [Kotlin Cleanup] LanguageUtilsTest

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/RustTest.kt
=> [Kotlin Cleanup] RustTest

AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt, AnkiDroid/src/main/res/values/10-preferences.xml
To display the name of the category on the category setting screen's toolbar
Fixes #11119 
My physical device : Realme 8i
https://user-images.githubusercontent.com/73571511/165958773-0277f5ee-7431-4747-b851-0d09da94e6a7.mp4
=> Category heading on the toolbar of settings section

.idea/dictionaries/davidallison.xml, AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
=> refactor: CardBrowser - IDE Lint

lint-rules/src/main/java/com/ichi2/anki/lint/rules/DirectDateInstantiation.kt
[Kotlin Cleanup] DirectDateInstantiation
=> [Kotlin Cleanup] DirectDateInstantiation

AnkiDroid/src/test/java/com/wildplot/android/rendering/PieChartParameterizedTest.kt
[Kotlin Cleanup] PieChartParameterizedTest
=> [Kotlin Cleanup] PieChartParameterizedTest

AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/GestureProcessorTest.kt
[Kotlin Cleanup] GestureProcessorTest
=> [Kotlin Cleanup] GestureProcessorTest

AnkiDroid/src/main/res/values/01-core.xml, AnkiDroid/src/main/res/values/02-strings.xml, AnkiDroid/src/main/res/values/04-network.xml
MyAccount.java, Reviewer.java & Deckpicker.java were migrated to kotlin but comments in resource files still used the old java extension.
Renamed all the instances of MyAccount.java, Reviewer.java & Deckpicker.java in comments in resource files.
- [ x ] You have commented on your code, particularly in hard-to-understand areas
- [ x ] You have performed a self-review of your own code
- [  ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [  ] UI Changes: You …
=> Renamed files extension to .kt extension in string xmls

lint-rules/src/main/java/com/ichi2/anki/lint/rules/CopyrightHeaderExists.kt
[Kotlin Cleanup] CopyrightHeaderExists
=> [Kotlin Cleanup] CopyrightHeaderExists

AnkiDroid/src/test/java/com/ichi2/libanki/MetaTest.kt
=> [Kotlin Cleanup] MetaTest

AnkiDroid/src/test/java/com/wildplot/android/rendering/PieChartTestParametersBuilder.kt
[Kotlin Cleanup] PieChartTestParametersBuilder
=> [Kotlin Cleanup] PieChartTestParametersBuilder

AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/fields/ImageFieldTest.kt
[Kotlin Cleanup] ImageFieldTest
=> [Kotlin Cleanup] ImageFieldTest

AnkiDroid/src/test/java/com/ichi2/anki/InitialActivityWithConflictTest.kt
[Kotlin Cleanup] InitialActivityWithConflictTest
=> [Kotlin Cleanup] InitialActivityWithConflictTest

AnkiDroid/src/test/java/com/ichi2/anki/CardInfoModelTest.kt
[Kotlin Cleanup] CardInfoModelTest
=> [Kotlin Cleanup] CardInfoModelTest

AnkiDroid/src/test/java/com/ichi2/anki/PreviewerTest.kt
[Kotlin Cleanup] PreviewerTest
=> [Kotlin Cleanup] PreviewerTest

AnkiDroid/src/test/java/com/ichi2/themes/HtmlColorsTest.kt
[Kotlin Cleanup] HtmlColorsTest
=> [Kotlin Cleanup] HtmlColorsTest

AnkiDroid/src/test/java/com/ichi2/testutils/IntentAssert.kt
=> [Kotlin Cleanup] IntentAssert

AnkiDroid/src/test/java/com/ichi2/libanki/LaTeXTest.kt
=> [Kotlin Cleanup] LaTeXTest

lint-rules/src/main/java/com/ichi2/anki/lint/rules/DirectCalendarInstanceUsage.kt
[Kotlin Cleanup] DirectCalendarInstanceUsage
=> [Kotlin Cleanup] DirectCalendarInstanceUsage

AnkiDroid/src/test/java/com/ichi2/anki/reviewer/PeripheralKeymapTest.kt
[Kotlin Cleanup] PeripheralKeymapTest
=> [Kotlin Cleanup] PeripheralKeymapTest

lint-rules/src/main/java/com/ichi2/anki/lint/rules/DirectGregorianInstantiation.kt
[Kotlin Cleanup] DirectGregorianInstantiation
=> [Kotlin Cleanup] DirectGregorianInstantiation

AnkiDroid/src/test/java/com/ichi2/anki/ReviewerNoParamTest.kt
[Kotlin Cleanup] ReviewerNoParamTest
=> [Kotlin Cleanup] ReviewerNoParamTest

AnkiDroid/src/test/java/com/ichi2/anki/BackupManagerIntegrationTest.kt
[Kotlin Cleanup] BackupManagerIntegrationTest
=> [Kotlin Cleanup] BackupManagerIntegrationTest

AnkiDroid/src/main/java/com/ichi2/ui/CheckBoxTriStates.kt
Fixes part of #10489  
My physical device: Realme 8i
=> kotlin cleanup : CheckBoxTriState.kt

api/build.gradle, api/kotlinMigration-api.gradle
Added kotlinMigration script for API project.
Tested by migrating NoteInfo to Kotlin & building the first commit.
- [ x ] You have performed a self-review of your own code
- [  ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [  ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.acce …
=> kotlinMigration for api project.

AnkiDroid/src/main/java/com/ichi2/anki/Previewer.kt
Kotlin CleanUp
Part of #10489
Using lint and some code changes which were mentioned in the comments and required to make the code more reliable
=> [KotlinCleanup] Previewer.kt

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/TranslationActivity.kt
Kotlin CleanUp
Part of [https://github.com/ankidroid/Anki-Android/issues/10489]
Using lint and some code changes which were mentioned in the comments and required to make the code more reliable
=> [KotlinCleanup] TranslationActivity.kt

AnkiDroid/build.gradle, api/build.gradle, build.gradle
Standard dependency updates PR pretty low impact it seems
=> Dependency updates 20220510

AnkiDroid/src/test/java/com/ichi2/async/CollectionTaskCheckDatabaseTest.kt
[Kotlin Cleanup] CollectionTaskCheckDatabaseTest
=> [Kotlin Cleanup] CollectionTaskCheckDatabaseTest

AnkiDroid/src/test/java/com/ichi2/anki/WhiteboardDefaultForegroundColorTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/ClozeTest.kt
[Kotlin Cleanup] WhiteboardDefaultForegroundColorTest, ClozeTest
=> [Kotlin Cleanup] Various

AnkiDroid/src/test/java/com/ichi2/utils/ListUtil.kt
=> [Kotlin Cleanup] ListUtil

AnkiDroid/src/main/java/com/ichi2/annotations/NeedsTest.kt
Explain the impact now: new contributors think about tests, and encourage tests to be written without being overbearing
And future plans: moving to a world with better coverage and better formalizing the requirements for writing a test for GSoC
=> docs: Rationale for `@NeedsTest`

AnkiDroid/src/main/java/com/ichi2/anki/ReadText.kt, AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckDropDownAdapter.kt, AnkiDroid/src/main/java/com/ichi2/compat/customtabs/CustomTabActivityHelper.kt, AnkiDroid/src/main/java/com/ichi2/compat/customtabs/CustomTabsFallback.kt, AnkiDroid/src/main/java/com/ichi2/compat/customtabs/CustomTabsHelper.kt, AnkiDroid/src/main/java/com/ichi2/ui/ActionBarOverflow.kt, AnkiDroid/src/test/java/com/ichi2/compat/customtabs/CustomTabActivityHelperTest.kt
=> Kotlin Cleanup: Various

AnkiDroid/src/test/java/com/ichi2/anki/services/ReminderServiceTest.kt
[Kotlin Cleanup] ReminderServiceTest
=> [Kotlin Cleanup] ReminderServiceTest

AnkiDroid/src/test/java/com/ichi2/testutils/CollectionUtils.kt
[Kotlin Cleanup] CollectionUtils
=> [Kotlin Cleanup] CollectionUtils

AnkiDroid/src/test/java/com/ichi2/utils/JSONArrayTest.kt
[Kotlin Cleanup] JSONArrayTest
=> [Kotlin Cleanup] JSONArrayTest

AnkiDroid/src/androidTest/java/com/ichi2/libanki/DBTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserNonAndroidTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedUpgradeTest.kt
[Kotlin Cleanup] Various Files
=> [Kotlin Cleanup] Various Files

.github/workflows/lint.yml, .github/workflows/tests_unit.yml, AnkiDroid/build.gradle, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/FieldControllerBase.kt, build.gradle, gradle.properties, lint-rules/src/main/java/com/ichi2/anki/lint/rules/ConstantJavaFieldDetector.kt
Not quite a normal dependency update, android gradle plugin 7.2 needed a handful of tweaks to pass lint and stabilize on windows
=> Dependency updates 20220512

AnkiDroid/src/main/java/com/ichi2/libanki/sync/RemoteServer.kt
This PR improves the nullability for the RemoteServer class and also fixes all IDE lint issues in the file.
=> Cleanup for file RemoteServer.kt

tools/migrate.sh
See #11102 for problem statement
Edgecases included:
1. File Renamed instead of deleted+new file
If the changes made to the file after kotlin conversion
are not too different, Git's heuristics identifies the
changelist as a rename directly and "git status" outputs
"renamed :" instead of "deleted:" + "new file:".
2. Files modified:
Let the user confirm whether all modified changes are intended.
Tested locally, please consult this log for demonstration of each case:
```
$ git status
On branch migrateScript_RenameBug
Your branch is ahead of 'origin/master' by 1 commit.
(use "git push" to publish your local commits)
Changes to be committed:
(use "git restore --staged <file>..." to unstage)
modified:   AnkiDroid/src/test/java/com/ichi2/anki/TestUtils.kt
renamed: …
```
=> Include Edgecases in kotlin migration script + Touch ups

AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt, AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.kt, AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt
Second commit of #11418. On top of #11419 , because if we don't deal with the nullability assertions, the compilation fails
=> NF: factorize collection in deck options

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
I found that the same keys and variables name where used with too many different meaning. This should help have less ambiguity
=> Improve card template editor

AnkiDroid/src/main/java/com/ichi2/anki/Info.kt
I believe the result is more readable
=> Info string: using string template instead of append

AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt, AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.kt
First commit of #11418. I believe it should be simple to accept
=> NF: remove duplicate nullability tests

AnkiDroid/src/main/java/com/ichi2/libanki/Tags.kt
=> [Kotlin Cleanup] Tags

AnkiDroid/src/main/java/com/ichi2/anki/Info.kt
To increase slightly readability
=> NF: info use scoped function

AnkiDroid/src/test/java/com/ichi2/libanki/template/ParserTest.kt
=> [Kotlin Cleanup] ParserTest

AnkiDroid/build.gradle, build.gradle
Standard dependency updates PR - all pretty simple here, just rebased on to main for a clean CI run
=> Dependency updates 20220529

AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.kt
Yet another part of https://github.com/ankidroid/Anki-Android/pull/11418 which can be considered separately
=> NF: move preference to lateinit in FilteredDeckOptions

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
=> [Kotlin Cleanup] Cardbrowser pt18

AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/SchedulerService.kt, AnkiDroid/src/main/java/com/ichi2/libanki/UndoAction.kt
=> [Kotlin Cleanup] UndoAction

AnkiDroid/src/test/java/com/ichi2/anki/reviewer/ActionButtonStatusTest.kt
[Kotlin Cleanup] ActionButtonStatusTest
=> [Kotlin Cleanup] ActionButtonStatusTest

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DialogHandler.kt
[Kotlin Cleanup] DialogHandler
=> [Kotlin Cleanup] DialogHandler

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
=> [Kotlin Cleanup] Cardbrowser pt14

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
=> [Kotlin Cleanup] Cardbrowser pt12

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
=> [Kotlin Cleanup] Cardbrowser pt5

AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt, AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.kt, AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt
Yet another part of #11418 which can be considered separately
=> NF: factorize mPrefChanged

AnkiDroid/src/main/java/com/ichi2/libanki/sync/RemoteMediaServer.kt
This PR fixes all issues reported by the IDE and also the @KotlinCleanup for the file. Also improves the nullability in the class constructor.
=> Cleanup for RemoteMediaServer

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
=> [Kotlin Cleanup] Cardbrowser pt17

.github/workflows/update_js_libs.yml, tools/update-js-libs.sh
The jquery and mathjax library should be updated and similar to Anki.
Fixes #11211
1. Used GitHub actions to run bash script
2. Create a new branch for updating the js library then create PR from the branch
3. Use [anki](http://github.com/ankitects/anki) repository to build only for vendor
```sh
cd ~/tmp/anki/qt/aqt/data/web/js/vendor; bazel build vendor
```
4. Then copy jquery to assets dir
```sh
cp ~/tmp/anki/.bazel/bin/qt/aqt/data/web/js/vendor/jquery.min.js AnkiDroid/src/main/assets/jquery.min.js
```
5. Also, remove mathjax dir from assets dir and copy new mathjax dir to assests dir. (It is same as AnkiDesktop)
```sh
rm -rf AnkiDroid/src/main/assets/mathjax
mkdir AnkiDroid/src/main/assets/mathjax
cp -r ~/tmp/anki/.bazel/bin/qt/aqt/data/web/js/vendor/mathjax AnkiDroid/src/main/assets/ …
```
=> Update JS library (jquery & mathjax) using GitHub action

AnkiDroid/src/main/java/com/ichi2/exceptions/AggregateException.kt, AnkiDroid/src/test/java/com/ichi2/exceptions/AggregateExceptionTest.kt
Allows multiple exceptions to be handled
#5304
Unit tested
=> feat: Introduce AggregateException

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
=> Replaced String.format in NoteEditor

AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/ExecutorTest.kt
Avoid writing method specific code thanks to
standard library
=> semaphore executor test

AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt
Added scope function for Canvas object in Whiteboard.kt
used `.apply` scope function for Canvas object
=> Add scope function for Canvas object in Whiteboard.kt

AnkiDroid/src/test/java/com/ichi2/anki/stats/OverviewStatsBuilderTest.kt
[Kotlin Cleanup] OverviewStatsBuilderTest
=> [Kotlin Cleanup] OverviewStatsBuilderTest

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
=> [Kotlin Cleanup] Cardbrowser pt9

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
=> [Kotlin Cleanup] Cardbrowser pt11

AnkiDroid/src/test/java/com/ichi2/testutils/MockTime.kt, AnkiDroid/src/test/java/com/ichi2/testutils/MutableTime.java
I plan to use it to improve solve #11541.
=> Mock time clean-up

AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.kt, AnkiDroid/src/main/java/com/ichi2/libanki/TextCardExporter.kt, AnkiDroid/src/main/java/com/ichi2/libanki/TextNoteExporter.kt
NB: solved the problem that it is a branch from my fork. Still not the message issue
=> clean exporter

AnkiDroid/src/main/java/com/ichi2/anki/ReadText.kt
It becomes late init and its code gets simplified
=> Clean mReviewer

AnkiDroid/build.gradle, build.gradle
Standard dependency update, hopefully no issues...
=> Dependency updates 20220613

AnkiDroid/src/main/java/com/ichi2/anki/MetaDB.kt
Mostly dealing with nullability
=> Cleaning Meta db

AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MigrateUserData.kt
Its essentially a RuntimeException. The goal is to simplify #11567 by ensuring
that we only except MigrationException; also we can easily check whether the
`when`, depending on the type of exception, is missing a case, since it suffices
to search for all types extending MigrationException
=> NF: add MigrationException

AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.kt, AnkiDroid/src/main/java/com/ichi2/anki/reviewer/Binding.kt, AnkiDroid/src/main/java/com/ichi2/anki/reviewer/MappableBinding.kt, AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt, AnkiDroid/src/main/java/com/ichi2/ui/KeyPicker.kt, AnkiDroid/src/test/java/com/ichi2/anki/reviewer/BindingTest.kt
Prep for unifying controls and gestures
1. Removed/Added controls on the app to see if they still work
2. Unit tests/lint
=> [GSoC]  NF: cleanup around controls and bindings

AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
While working on https://github.com/ankidroid/Anki-Android/commit/b0a2bdcdc7f2d834ea936e7660075105fac1038b I've missed that the menu items bury and suspend can be set by the user to always show in the toolbar.
When this happens the system calls the `ActionProvider.onCreateActionView(MenuItem)` and because the previous implementation didn't override this method it used the default implementation which calls `onCreateActionView()` that we set to fail as it's not supposed to be used anymore. To solve this I implemented `ActionProvider.onCreateActionView(MenuItem)` and used code very similar to `RtlCompliantActionProvider.onCreateActionView(MenuItem)`. However, this made the sub menu to not work(even directly returning true from hasSubMenu() doesn't show a sub menu) so I manually implemented …
=> Fix crash for Reviewer menu action providers when set to always show

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.kt, AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/AudioField.kt, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/IField.kt, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/ImageField.kt, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/TextField.kt, AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt, AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.kt, AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt, AnkiDroid/src/main/java/com/ichi2/async/TaskDelegate.kt, AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.kt, AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckTreeNode.kt, AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java, AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
I searched for occurrence of Collection? and `col!!` and removed the one I can justify
=> non null col

AnkiDroid/src/main/res/values-cs/03-dialogs.xml, AnkiDroid/src/main/res/values-cs/10-preferences.xml, AnkiDroid/src/main/res/values-de/02-strings.xml, AnkiDroid/src/main/res/values-de/10-preferences.xml, AnkiDroid/src/main/res/values-de/11-arrays.xml, AnkiDroid/src/main/res/values-de/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-et/01-core.xml, AnkiDroid/src/main/res/values-et/02-strings.xml, AnkiDroid/src/main/res/values-fr/02-strings.xml, AnkiDroid/src/main/res/values-fr/03-dialogs.xml, AnkiDroid/src/main/res/values-fr/10-preferences.xml, AnkiDroid/src/main/res/values-nl/01-core.xml, AnkiDroid/src/main/res/values-nl/16-multimedia-editor.xml, AnkiDroid/src/main/res/values-zh-rCN/10-preferences.xml
I18N sync with nothing but translation changes, prior to #11647 going in with all it's I18n key motion
I'm still surprised by people and their spammy practices, though I should not be.
=> Updated strings from Crowdin 20220617-1

AnkiDroid/src/main/java/com/ichi2/anki/Statistics.kt, AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.kt
_This PR is a continuation of #11556_
AsyncTask to coroutines migration
Replaced the usage of AsyncTask to create and display statistics overview with the suspend function.
Runs as expected on Realme 6i
https://user-images.githubusercontent.com/69595691/173676258-adf8cb58-0889-4da0-99cd-2216bf21575d.mp4
https://user-images.githubusercontent.com/69595691/173676222-c4150036-33c5-4548-89f4-56eade632110.mp4
Use of [Mutex](https://kotlinlang.org/docs/shared-mutable-state-and-concurrency.html#mutual-exclusion) for thread safety on critical sections with suspending functions.
=> [GSoC] migrated AnkiStatsTaskHandler.createStatisticsOverview() to suspend function

AnkiDroid/src/main/java/com/ichi2/ui/ButtonItemAdapter.kt
IDE lint cleanup for ButtonItemAdapter
=> cleanup for ButtonItemAdaptor

AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
Cleanup
Opened the app and clicked the preference
=> [GSoC] NF: Simplify devOptions preference's fragment assignment

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java
=> docs: DeckPicker

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
AsyncTask to Coroutines Migration
Replaced AsyncTask usage with equivalent suspend function. 
Passes all the unit test and android test
=> [GSoC] migrate PerformDowngradeTask to Coroutines

AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt
Whiteboard.kt cleanup by adding scope function
used `.apply{}` scope function for executing code for Paint object
=> Whiteboard Cleanup - scope function

AnkiDroid/src/test/java/com/ichi2/libanki/CheckMediaTest.kt
[Kotlin Cleanup] CheckMediaTest
=> [Kotlin Cleanup] CheckMediaTest

AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.kt
Minor cleanups: replace a utility method with one that we already had and used and also reduce a bit the verbosity of the code.
=> Some small cleanups for the toolbar in NoteEditor

AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt, AnkiDroid/src/main/res/values/02-strings.xml
Some cleanups for the ModelFieldEditor file. This includes fixing @ KotlinCleanups, IDE lint issues or code refactoring. More info is available in the commit messages.
=> Cleanups for ModelFieldEditor

AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MigrateEssentialFiles.kt, AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MigrateUserData.kt, AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/ScopedStorageMigrationIntegrationTest.kt, AnkiDroid/src/test/java/com/ichi2/testutils/FileUtil.kt
* Defines `UserDataMigrationContext`, which allows a decision to be
made based on an exception that is raised, this allows us to stop
execution, for example if 10 exceptions are thrown consecutively
* Defines internal and external retries: We allow the user migration to
be retried 3 times before failing. Internal retries are in addition
to this, for example if a file is added to the original folder while
migrating
* Integration tests are added for all the operations
Once this is done, the service, and the UX remains
#5304
Unit tested
=> scoped storage: Make MigrateUserData a task 

AnkiDroid/src/main/AndroidManifest.xml, AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java, AnkiDroid/src/main/java/com/ichi2/anki/CustomMaterialTapTargetPromptBuilder.kt, AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt, AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardAppearance.kt, AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardHtml.kt, AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/HtmlGenerator.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ScopedStorageMigrationDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/model/WhiteboardPenColor.kt, AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt, AnkiDroid/src/main/java/com/ichi2/themes/Theme.kt, AnkiDroid/src/main/java/com/ichi2/themes/Themes.kt, AnkiDroid/src/main/res/values/constants.xml, AnkiDroid/src/test/java/com/ichi2/anki/ReviewerNoParamTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/servicemodel/PreferenceUpgradeServiceTest.kt, AnkiDroid/src/test/java/com/ichi2/themes/ThemeTest.kt
Most of Themes.kt code is mine and I find it ugly. Since I'm a wiser man now, I'll try to improve it.
Fixes #10619
On the commits (kinda hard to split them, but let me know if anything isn't clear)
On my phone (API 31)
https://user-images.githubusercontent.com/69634269/172143330-90de628c-a12b-45a6-9ee5-0d2a356e0b20.mp4
Upgrading from 2.15.6. Good news is themes aren't becoming corrupted, although I don't know why the previous theme (plain) didn't persist
https://user-images.githubusercontent.com/69634269/172143421-7c7afd8a-5292-4f4e-927f-2b51d14961e1.mp4
=> Refactor themes/fix night mode

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/java/com/ichi2/anki/Statistics.kt, AnkiDroid/src/main/java/com/ichi2/anki/UIUtils.kt, AnkiDroid/src/main/java/com/ichi2/async/CoroutineHelpers.kt
Extracted away repeating code to an extension function and replaced it.
Unit tested and on Realme 6i API 30
https://user-images.githubusercontent.com/69595691/175300791-f893fc22-73c4-4886-b3da-3040a662c43d.mp4
=> [GSoC] enhanced error handling when launching coroutines

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
AsyncTask to Coroutines migration
Runs as expected on Pixel 3a Emulator API 31 and Realme 6i API 30
https://user-images.githubusercontent.com/69595691/175486531-272b16ff-5713-4fdd-bca1-654da9526a27.mp4
https://user-images.githubusercontent.com/69595691/175486304-da932a38-54cc-4c4e-bea3-15178c47c4b6.mp4
=> [GSoC] migrated LoadPronunciationActivity to Coroutines

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
=> Replaced String.format in CustomStudyDialog

AnkiDroid/build.gradle, api/build.gradle
Standard dependency updates
Pretty small batch I think
=> Dependency updates 20220704

AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/IMultimediaEditableNote.kt
Kotlin CleanUp of IMultimediaEditableNote.kt
=> Kotlin CleanUp of IMultimediaEditableNote.kt

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
=> [Kotlin Cleanup] Cardbrowser pt6

AnkiDroid/src/test/java/com/ichi2/anki/servicemodel/UpgradeGesturesToControlsTestNoParam.kt
@BrayanDSO another flaky on - matching the previous one :shrug:
=> test(ci): ignore another flaky test

AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/TTS.kt
=> fix: ide lint in TTS.kt

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
add scope functions for `args` and `dialogOptions` variable
fix: IDE lint
=> cleanup in CustomStudyDialog

AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTabOrderTest.kt
cleanup: NoteEditorTabOrderTest
=> cleanup: NoteEditorTabOrderTest

AnkiDroid/src/main/java/com/ichi2/utils/UniqueArrayList.kt
fix: IDE lint in UniqueArrayList
=> fix: IDE lint in UniqueArrayList

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Continued from #11494 
this commit was missed from #11466
=> [Kotlin Cleanup] Cardbrowser pt20

AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerCheckDatabaseListenerTest.kt
=> [Kotlin Cleanup] DeckPickerCheckDatabaseListenerTest

AnkiDroid/src/main/java/com/ichi2/anki/Statistics.kt, AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.kt, AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.kt
Kotlin Cleanup
Fixes a part of #10489
=> [GSoC] Kotlin Cleanup AnkiStatsTaskHandler

AnkiDroid/src/main/java/com/ichi2/async/CollectionLoader.kt
AsyncTask to Coroutines migration
Passes existing unit tests.
=> [GSoC] migrated CollectionLoader to Coroutines

AnkiDroid/src/main/java/com/ichi2/anki/Info.kt
=> Replaced String.format in Info

AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
Prep commit for notes browser
Add a similar method to `searchCards()` that calls the `findNotes()` function from Collection.
Manually on my phone.
=> [GSoC] Add `SearchNotes()` function

AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt, AnkiDroid/src/main/java/com/ichi2/themes/ThemeUtils.kt
As suggested by David in this [comment](https://github.com/ankidroid/Anki-Android/pull/11713#discussion_r908323915)
> This is repeated a lot and we could get a lot of readability from extracting this to a helper extension method somewhere in the utils package
```kotlin
@ColorInt
fun Fragment.getThemedColor(@AttrRes attribute: Int): Int {
return Themes.getColorFromAttr(
activity,
attribute
)
}
```
=> Add `getThemedColor` helper function

AnkiDroid/src/main/res/layout/floating_add_button.xml, AnkiDroid/src/main/res/menu/card_browser.xml, AnkiDroid/src/main/res/menu/note_editor.xml, AnkiDroid/src/main/res/values/01-core.xml
Replace "Add Note" by "Add" at multiple places as discussed in #10853 
Fixes #11861 
Closes #10853
=> update: Replace string "Add Note" by "Add" at multiple places

AnkiDroid/src/main/java/com/ichi2/libanki/backend/model/SchedTimingToday.kt
=> fix: IDE lint in SchedTimingToday

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
=> [Kotlin Cleanup] Cardbrowser pt16

AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt, AnkiDroid/src/main/res/values/03-dialogs.xml
Bug fix
Fixes #10800
Unit tested and on Realme 6i API 30
https://user-images.githubusercontent.com/69595691/180502839-0d325cfa-6746-46be-85ee-3888c5d18a76.mp4
https://user-images.githubusercontent.com/69595691/180502805-03d28cf0-8db2-48a1-8497-47328592f9dd.mp4
=> fixed automatic creation of deck with name 'All decks'

AnkiDroid/build.gradle, build.gradle
standard dependency update from tracking branch
=> Dependency updates 20220724

AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
some cleanups in Collection.kt
=> some cleanups in Collection.kt

AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
This PR replaces the deprecated onActivityResult() override in NavigationActivity with the newer ActivityResultLauncher.
=> Fix onActivityResult deprecation for NavigationActivity

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
=> [Kotlin Cleanup] Cardbrowser pt19

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateBrowserAppearanceEditor.kt
cleanup: add scope function in CardTemplateBrowserAppearanceEditor
fix: IDE lint
=> cleanup: add scope function in CardTemplateBrowserAppearanceEditor

AnkiDroid/src/main/res/values-cs/03-dialogs.xml, AnkiDroid/src/main/res/values-fr/03-dialogs.xml, AnkiDroid/src/main/res/values-zh-rCN/03-dialogs.xml
Standard translation sync, really tiny this time
=> Updated strings from Crowdin 20220730

AnkiDroid/build.gradle, build.gradle
=> Dependency updates 20220730

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
=> [Kotlin Cleanup] Cardbrowser pt13

AnkiDroid/src/main/java/com/ichi2/async/SingleTaskManager.kt
This deal with null check and ensure we use the same instance during the whole
process.
=> NF: uses Apply on `mLatestInstance`

README.md
Indeed, it will be hard linked in #11803 and changing the name would break the link
=> Add a comment stating not to rename/remove credits

AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
Kotlin Cleanup 
Do I understand correctly that each PR should address a single instance of `@KotlinCleanup` rather than all that are found in a given class?
https://github.com/ankidroid/Anki-Android/issues/10489
Changes if-else sequence to when
Tested on emulator pixel 4 xl, android 12
=> [Kotlin Cleanup] if/elseif... to when in NavigationDrawerActivity.kt

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Fixes #11842
https://user-images.githubusercontent.com/59933477/179100402-4a8c2dfe-cb2d-4ea3-b02a-c5ac247c412e.mov
=> Fix `DeckPicker#searchDecksIcon` flash

AnkiDroid/src/test/java/com/wildplot/android/rendering/PieChartTestParametersBuilder.kt
Replaces a String.format() usage with a template expression
Contributes to  #11449 
Ran all the unit tests
=> Replace use of String.format with a template expression

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt
=> [Kotlin Cleanup] CardBrowser pt4

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
This will ensure linter works again
=> NF: remove unused import

AnkiDroid/src/main/java/com/ichi2/anki/BackendImporting.kt, AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.kt, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt, AnkiDroid/src/main/java/com/ichi2/anki/Statistics.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerConfirmDeleteDeckDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt, AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DeckService.kt, AnkiDroid/src/main/java/com/ichi2/anki/services/ReminderService.kt, AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.kt, AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.kt, AnkiDroid/src/main/java/com/ichi2/anki/stats/OverviewStatsBuilder.kt, AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt, AnkiDroid/src/main/java/com/ichi2/libanki/BackendImportExport.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt, AnkiDroid/src/main/java/com/ichi2/libanki/DecksV16.kt, AnkiDroid/src/main/java/com/ichi2/libanki/PythonTypes.kt, AnkiDroid/src/main/java/com/ichi2/libanki/exception/NoSuchDeckException.kt, AnkiDroid/src/test/java/com/ichi2/anki/dialogs/DeckPickerContextMenuAndroidTest.kt
Those one were found with searcing for "eckId: Long"
=> NF: converting Long to DeckId

AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.kt
This is obviously what was expected to be done. Instead of removing the tags
from the same note over and over again.
Fixes #12014
=> NF: export without scheduling: remove all system tags

AnkiDroid/src/main/res/values-cs/10-preferences.xml, AnkiDroid/src/main/res/values-ka/02-strings.xml, AnkiDroid/src/main/res/values-ka/03-dialogs.xml, AnkiDroid/src/main/res/values-ka/04-network.xml, AnkiDroid/src/main/res/values-ka/06-statistics.xml, AnkiDroid/src/main/res/values-ka/07-cardbrowser.xml, AnkiDroid/src/main/res/values-ka/08-widget.xml, AnkiDroid/src/main/res/values-ka/10-preferences.xml, AnkiDroid/src/main/res/values-ka/11-arrays.xml, AnkiDroid/src/main/res/values-ka/17-model-manager.xml, AnkiDroid/src/main/res/values-ka/18-standard-models.xml, AnkiDroid/src/main/res/values-zh-rCN/10-preferences.xml
Standard I18n sync. small this time. I already see an issue in es locale
=> Updated strings from Crowdin 20220814

AnkiDroid/build.gradle, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/ControlsSettingsFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/DevOptionsFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/HeaderFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/NotificationsSettingsFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/PreferencesSearchView.kt, AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt, AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt, AnkiDroid/src/main/res/menu/preferences.xml, AnkiDroid/src/main/res/values/10-preferences.xml, AnkiDroid/src/main/res/values/preferences.xml, AnkiDroid/src/main/res/xml/preference_headers.xml, AnkiDroid/src/main/res/xml/preferences_accessibility.xml, AnkiDroid/src/main/res/xml/preferences_advanced.xml, AnkiDroid/src/main/res/xml/preferences_advanced_statistics.xml, AnkiDroid/src/main/res/xml/preferences_appearance.xml, AnkiDroid/src/main/res/xml/preferences_custom_buttons.xml, AnkiDroid/src/main/res/xml/preferences_custom_sync_server.xml, AnkiDroid/src/main/res/xml/preferences_dev_options.xml, AnkiDroid/src/main/res/xml/preferences_sync.xml, AnkiDroid/src/test/java/com/ichi2/anki/preferences/SettingsSearchBarTest.kt, AnkiDroid/src/test/java/com/ichi2/testutils/ReflectionUtils.kt
Fixes #8342
- refactored some things to ease the search bar code
1. Add [SearchPreference](https://github.com/ByteHamster/SearchPreference) library
- MIT licensed
- I've contacted the author to question about the lack of updates for ~1 year:
> Hi, Nice to hear that you want to integrate my library. There is not much development going on because it just works. It is integrated into AntennaPod and K-9 Mail and I have not heard of crashes or bugs there, so there is no need to commit anything :) If I get critical bug reports, I do plan to fix the problems. ByteHamster
- edit: I had to send some PRs and they were accepted fairly quickly, so we can conclude that the mantainer is stil active
2. Implement the search bar
- Add …
=> [GSoC] Add a search bar to the settings screen

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/AboutFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/AppearanceSettingsFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/DevOptionsFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/GeneralSettingsFragment.kt, AnkiDroid/src/main/res/layout/about_layout.xml, AnkiDroid/src/main/res/values/02-strings.xml, AnkiDroid/src/main/res/values/constants.xml
cleanup
On the commits
https://user-images.githubusercontent.com/69634269/184417791-506bee3b-b810-477e-b76c-6ae90e65fcfd.mp4
https://user-images.githubusercontent.com/69634269/184417654-4b0e19ef-764f-4707-bed2-7874ff68a256.mp4
https://user-images.githubusercontent.com/69634269/184417628-7476704e-f325-4fe6-a054-783a8d91b6d5.mp4
=> [GSoC] preferences refactors + move "Open changelog" to the "About" screen

AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt, AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/AsyncLayer.kt, AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/SchedulerService.kt, AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/UndoService.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt, AnkiDroid/src/main/java/com/ichi2/libanki/DB.kt
This commit is on top of #12016. I expect it may be used in #11952 to remove a nullability type issue
=> NF: executeInTransaction returns value

AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
Based on top of #12016. Removing a method that is not required anymore thanks to DB migration
=> Query with null selection

AnkiDroid/build.gradle, build.gradle
Standard dependency updates, nothing major in here - I don't think anything required any manual work actually (those are all pending for the moment)
=> Dependency updates 20220816

AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV3.kt
=> Fix time taken in v3 scheduler being capped to maximum

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
This pull request is a precursor of #11952. Changes variable names in AddNote Activity to follow Kotlin style of naming variables. Some of the variables are rename to more descriptive ones.
=> Variable names cleanup

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
Code simplification
Continuation of #12059 and precursor of #11952
=> [GSoC] Simplify add note task

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
cleanup: replace TextUtils for checking empty or null 
https://stackoverflow.com/a/59321544/9062752
=> Cleanup in CardBrowser Part 1

AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt, AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.kt, AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt
Also a part of  #11418.
On top of #11421 because if nullity is not taken into account, compilation fail
=> NF: factorize unmondReceiver creation

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
=> [KotlinCleanup] CardBrowser 

AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt, AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.kt, AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt
Yet another part of https://github.com/ankidroid/Anki-Android/pull/11418 which can be considered separately
It considers the actions that can close preferences
=> Factorize close

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/LayoutValidationTest.kt, AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/NotificationChannelTest.kt, AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/DBTest.kt, AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/MediaTest.kt, AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/ModelTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerCheckDatabaseListenerTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/LegacyDecksTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/UtilsTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.kt, AnkiDroid/src/test/java/com/ichi2/testutils/ActivityList.kt, AnkiDroid/src/test/java/com/ichi2/utils/ContentResolverUtilTest.kt
Part of issue #10489
Test only
=> lint: fix IDE Lint issues

AnkiDroid/src/androidTest/java/com/ichi2/anki/FieldEditLineTest.kt, AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/RetryRule.kt, AnkiDroid/src/main/java/com/ichi2/anki/FieldEditLine.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt, AnkiDroid/src/main/java/com/ichi2/libanki/TextCardExporter.kt, AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.kt, AnkiDroid/src/test/java/com/wildplot/android/rendering/PieChartParameterizedTest.kt, AnkiDroid/src/test/java/com/wildplot/android/rendering/PieChartTest.kt, AnkiDroid/src/test/java/com/wildplot/android/rendering/PieChartTestParametersBuilder.kt
=> NF: Kotlin cleanup

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
UP-FADE, changed as asked in the issue https://github.com/ankidroid/Anki-Android/pull/12115#discussion_r950783644
ActivityTransitionAnimation.slide(activity, UP)
ActivityTransitionAnimation.slide(activity, FADE)
changed the animation style as asked
=> Updated finishActivityWithFade

AnkiDroid/src/test/java/com/ichi2/libanki/StorageTest.kt
This is now a first step for #11913 since it uses JSONObject
=> NF: put storageTest strings as lateinit

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
I believe this version is more readable.
=> NF: browser use two columns explicitly

AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt, AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/AsyncDialogFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SimpleMessageDialog.kt, AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerCheckDatabaseListenerTest.kt
`KotlinCleanup` of `AnkiActivity`, and a small IDE-lint fix in `Preferences`
=> cleanup: AnkiActivity

AnkiDroid/src/main/java/com/ichi2/compat/customtabs/CustomTabsHelper.kt
The !! could not be removed without an error
=> refactor: KotlinCleanup - CustomTabsHelper

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/ImportTest.kt, AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Note.kt, AnkiDroid/src/main/java/com/ichi2/libanki/backend/model/NoteUtil.kt, AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/TextNoteExporterTest.kt
Kotlin Cleanup, useful for Kotlin conversion of `ParsedNode`
=> refactor: make Note Fields non-null

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Recent NF PR causes crashes. Unsure why. Revert fixes, so doing PR for revert
Fixes #12143
This reverts commit c762f1af254e4f1bea1c207a157d5a24c62170ac.
With the commit in place:
- open card browser
- change column 2 to something like Deck
- go to deck list
- go back to card browser
with commit in place, it crashes. with revert, it works
@Arthur-Milchior - Even NF code changes have a cost, not always a crash but sometimes even a crash. Refactor judiciously with an eye towards impact on whole project velocity while we have so much work in flight
=> Revert "NF: browser use two columns explicitly"

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt, AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt
Migrated CollectionTask.AddNote to Coroutines
Fixes a part of #7108 
Extracted the codes from AsyncTask callbacks, into a proper sequence of suspend function calls.
Passes the existing unit tests, runs as expected on realms 6i API 30
=> [GSoC] Migrated CollectionTask.AddNote to Coroutines

AnkiDroid/src/main/java/com/ichi2/ui/CheckBoxTriStates.kt, AnkiDroid/src/main/res/drawable/ic_baseline_check_box_24_inset.xml, AnkiDroid/src/main/res/drawable/ic_baseline_check_box_outline_blank_24_inset.xml, AnkiDroid/src/main/res/drawable/ic_baseline_indeterminate_check_box_24_inset.xml, AnkiDroid/src/main/res/layout/tags_item_list_dialog.xml
Enlarge size of checkbox in Tag Picker dialog as mentioned in #11139 because
>  The clickable region that toggles the checkbox is now shrunk to the checkbox itself only (not true for leaf tags), which endangers misclick.
fixes #11139
As mentioned in the #11139 , it was decided to make the size to `48x48dp`. I tried implementing that to (48x48) and found it a bit odd (can be termed as subjective - also maybe because other icons on screen are not that big) so I tried implementing it to 36x36 which looks better and also fixes the issue of misclick happening. Though it is subjective to make it `48x48` or `36x36` but I am open to any changes further required upon discussion in the comments.
For reference here is the link to images :
24x24 (current)
36x36
48x48
Manually on physical device
=> Enlarge size of checkbox in Tag Picker dialog

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt, AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt, AnkiDroid/src/main/java/com/ichi2/libanki/CollectionV16.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java, AnkiDroid/src/main/java/com/ichi2/libanki/DecksV16.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Note.kt, AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt, AnkiDroid/src/main/java/com/ichi2/libanki/backend/model/NoteUtil.kt
Closes #12054
Probably closes #12155
=> More new schema fixes

AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt, build.gradle, tools/setup-anki-backend.sh
On ARM machine, currently to run tests we need to manually download the dylib file and set environment variables. This script downloads dylib file from ankidroid backend repository and setups the environment variable without needing it to be done manually.
I was personally using it but thought it would be good it comes by default with the repo.
NEED HELP TO DOCUMENT IT PROPERLY
=> Automated backend library setup

AnkiDroid/build.gradle, api/build.gradle, build.gradle
=> Dependency updates 20220825

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
Lots of comments were no longer valid as they were compiler errors (removing `_`)
=> refactor: KotlinCleanup - DeckPicker

AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt, AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.kt, AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt
Most complex part of #11418. Factorizing preference hack as much as possible
=> NF: factorize DeckPreferenceHack

AnkiDroid/src/main/res/values-be/02-strings.xml, AnkiDroid/src/main/res/values-be/03-dialogs.xml, AnkiDroid/src/main/res/values-be/10-preferences.xml, AnkiDroid/src/main/res/values-cs/02-strings.xml
tiny one - cleaning things up before a merge of some string changes from either #12121 or #12033
=> Updated strings from Crowdin 20220826

AnkiDroid/build.gradle, AnkiDroid/src/main/AndroidManifest.xml, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt, AnkiDroid/src/main/java/com/ichi2/anki/IntroductionActivity.kt, AnkiDroid/src/main/java/com/ichi2/anki/LoginActivity.kt, AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt, AnkiDroid/src/main/java/com/ichi2/anki/OnboardingUtils.kt, AnkiDroid/src/main/java/com/ichi2/anki/introduction/SetupCollectionFragment.kt, AnkiDroid/src/main/res/drawable-v24/intro_ankidroid_logo.xml, AnkiDroid/src/main/res/drawable/intro_ankidroid_logo.xml, AnkiDroid/src/main/res/drawable/intro_gradient.xml, AnkiDroid/src/main/res/layout/introduction_layout.xml, AnkiDroid/src/main/res/values/02-strings.xml, AnkiDroid/src/main/res/values/19-onboarding.xml, AnkiDroid/src/main/res/values/attrs.xml, AnkiDroid/src/main/res/values/theme_black.xml, AnkiDroid/src/main/res/values/theme_dark.xml, AnkiDroid/src/main/res/values/theme_light.xml, AnkiDroid/src/main/res/values/theme_plain.xml, AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CreateDeckDialogTest.kt, AnkiDroid/src/test/java/com/ichi2/testutils/ActivityList.kt
If we add an app introduction, we can use this for the 'restore' operation in scoped storage, which allows a user to select a 'safe, but slow' folder to restore from.
The UX of this is not ideal on the Android side, so sadly a 'safe' folder can't be the default. In addition to this, it is significantly slower to perform disk operations, which leads to a large number of complaints about slow sync times.
Emulator on Android 12
* New collection - Get Started
* New collection - Sync from AnkiWeb
* New collection - Sync from AnkiWeb (if already logged in)
* Upgrade
* App Intro is not shown twice
* DeckPicker needs a lot of work - we can't use app results well as the collection init code still is used by the lifecycle
=> feat: App Intro

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/ReadText.kt, AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/TTS.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerConfirmDeleteDeckDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportCompleteDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.kt, AnkiDroid/src/main/java/com/ichi2/utils/MaterialBuilderUtil.kt
Shortens repetitive code
Also removed a few unused parameters (required for compilation).
Fixes #11781
Unit tested
=> refactor: add MaterialDialog.iconAttr

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt, AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.kt, AnkiDroid/src/main/java/com/ichi2/libanki/DeckConfig.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Model.kt, AnkiDroid/src/main/java/com/ichi2/utils/JSONObject.kt, AnkiDroid/src/main/java/com/ichi2/utils/JSONTokener.kt, AnkiDroid/src/test/java/com/ichi2/libanki/StorageTest.kt, AnkiDroid/src/test/java/com/ichi2/utils/JSONObjectTest.kt
I believe it must be squashed.
Please note that on the long term, this will be deleted as soon as all of its calls are done in kotlin, and so we don't have to deal with runtime/non-runtine exception
=> JSONObject nullability cleanup

AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
I saw this issue while reviewing #12199. I believe that simplifying code before
moving it will help review the move
=> NF: simplify UpdateNote

api/src/main/java/com/ichi2/anki/api/Utils.kt
Replaced `Character.toString` java function to `toString` kotlin function.
- Tests
=> [Cleanup] Replaced Character.toString with kotlin function toString

AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerBackupNoSpaceLeftDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt, AnkiDroid/src/main/java/com/ichi2/preferences/PreferenceExtensions.kt, AnkiDroid/src/test/java/com/ichi2/anki/InitialActivityWithConflictTest.kt, AnkiDroid/src/test/java/com/ichi2/preferences/PreferenceExtensionsTest.kt, AnkiDroid/src/test/java/com/ichi2/testutils/BackupManagerTestUtilities.kt
Various small refactorings to reduce the code churn from:
- #12216
=> Kotlin Cleanup: prep for CollectionHelper migration

api/src/main/java/com/ichi2/anki/api/Utils.kt
This is needed to migrate AddContentApi to Kotlin. #11377 
Source: https://github.com/ankidroid/Anki-Android/pull/11377#issuecomment-1229423927
- Tests
- Tested if the app is launching on the emulator.
=> Made joinFields accept not null arr string in list

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/HttpTest.kt, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DialogHandler.kt, AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
broken by 185e6aa792e37bb1903644cc9a36f7eb857cc9d9
=> fix: build

.idea/dictionaries/anki.xml, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt, AnkiDroid/src/main/java/com/ichi2/libanki/CollectionV16.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Note.kt, AnkiDroid/src/test/java/com/ichi2/libanki/CardTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/ClozeTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/MathJaxClozeTest.kt
=> refactor: Kotlin Cleanup: Collection/Note

AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt, AnkiDroid/src/main/java/com/ichi2/anki/web/PreferenceBackedHostNum.kt, AnkiDroid/src/main/java/com/ichi2/libanki/sync/HostNum.kt, AnkiDroid/src/main/java/com/ichi2/libanki/sync/HttpSyncer.kt, AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.kt, AnkiDroid/src/test/java/com/ichi2/anki/web/HostNumFactoryTest.kt
convert from get/set to property
=> refactor: KotlinCleanup - HostNum

AnkiDroid/src/main/java/com/ichi2/anki/TtsParser.kt
nullability improvement
Blocked on #12236
=> refactor: Kotlin Cleanup - TTSParser

AnkiDroid/src/main/res/values-ar/02-strings.xml, AnkiDroid/src/main/res/values-cs/02-strings.xml, AnkiDroid/src/main/res/values-et/08-widget.xml, AnkiDroid/src/main/res/values-et/09-backup.xml, AnkiDroid/src/main/res/values-ja/02-strings.xml, AnkiDroid/src/main/res/values-ja/10-preferences.xml, AnkiDroid/src/main/res/values-ja/11-arrays.xml, AnkiDroid/src/main/res/values-zh-rCN/02-strings.xml
=> Updated strings from Crowdin 20220902

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
Removed "Created deck" toast after tapping OK on filtered deck dialog.
fixes #12284
=> Removed "Created deck" toast after tapping OK on filtered deck dialog

AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
Extracted out the functionality of UpdateMultipleNotes.task to a function doInBackgroundUpdateMultipleNotes. This way it can be reused if required and will facilitate the migration to Coroutines
=> [GSoC] moved doInBackgroundUpdateMultipleNotes to CollectionOperations

AnkiDroid/src/main/AndroidManifest.xml, AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt, AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt, AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ScopedStorageMigrationDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/NotificationsSettingsFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/ReviewingSettingsFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/SettingsFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/services/BootService.kt, AnkiDroid/src/main/java/com/ichi2/anki/services/NotificationService.kt, AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.kt, AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt, AnkiDroid/src/main/java/com/ichi2/widget/WidgetStatus.kt, AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupUnderBackupTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/PreferencesSimpleTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/PreferencesTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/preferences/PreferencesSimpleTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/preferences/PreferencesTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/preferences/SettingsSearchBarTest.kt, AnkiDroid/src/test/java/com/ichi2/testutils/ActivityList.kt, AnkiDroid/src/test/java/com/ichi2/testutils/PreferenceUtils.kt
Keep things organized in packages
- Move the file to `com.ichi2.anki.preferences`
- Fix the imports
CI
=> NF: move Preferences.kt and tests to `com.ichi2.anki.preferences` package

AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
This PR solves all IDE related issues and several @KotlinCleanup for the CardContentProvider class. I used `context!!` because it's safe(after ContentProvider.onCreate() the context is valid) and it also improves the nullability for CollectionHelper.getCol() method.
=> Fix some of the issues with CardContentProvider

AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
Fixes #12053  
Previous discussion can be found here: #12290
=> Fix dialog getting skipped on pressing back

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
=> [Kotlin Cleanup] NoteEditor nullability cleanup

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
Migrated CollectionTask.LoadDeck to Coroutines
A part of #7108
=> [GSoC] Migrated LoadDeck to Coroutines

AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt, AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.kt, AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt
I was looking at #11417 and this led me to find far more duplication than I expected.
If it's too hard to review all at once, I can split. The last commit is the hardest one. 
The first few commits, by removing some nullability thanks to late init, are really nice by themselves. Then many commits are factorizing copy-pasted code and can be considered by themselves (but would conflict with the first ones)
=> Factorize deck pref

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
Migrated CollectionTask.UpdateMultipleNotes to Coroutines
=> [GSoC] Migrated CollectionTask.UpdateMultipleNotes to Coroutines

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
=> [GSoC] Coroutines migration PreloadNextCard

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt
They appeared once the junit error was removed
=> NF: apply ide suggestion on ContentProviderTest

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
Passes existing unit tests and runs as expected on Realme 6i API 30
=> [GSoC] Coroutines migration DeleteMedia

AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
=> [GSoC] Coroutines migration CollectionTask.DeleteModel

AnkiDroid/src/main/java/com/ichi2/anki/ReadText.kt
The changes in this PR order alphabetically the languages in "Set TTS language" dialog. Also refactors and improves the code a bit.
Fixes #12345
Ran the tests, ran the app.
=> Fix languages order in set TTS language dialog

AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt
=> Kotlin Cleanup: scoped functions

AnkiDroid/build.gradle
Standard dependency updates, but moving core-ktx and appcompat may be "interesting". Hopefully  not
=> Dependency updates 20220913

AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
Instructions for dismissing dialog with message:
```
“librsdroid-0-1-11.dylib” can’t be opened because Apple cannot check
it for malicious software.
This software needs to be updated.
Contact the developer for more information.
[Show in Finder] [OK]
```
Tested this a couple of times
I love Apple more and more every day
=> docs: improve docs for Apple Silicon dylib load

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
Fixes a part of #7108 
Unit Tests and Realme 6i API 30
=> [GSoC] Coroutines migration CollectionTask.DeleteDeck

AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
Kotlin Cleanup for Deck Picker Test
=> Kotlin Cleanup for Deck Picker Test

api/src/main/java/com/ichi2/anki/api/AddContentApi.kt
Cleanups for the `AddContentApi` class to remove kotlin cleanups and IDE reported issues. There are several TODOs remaining but those will be fixed in a separate PR as they are related to the type system(possible impact on the public API).
=> Cleanup IDE issues for AddContentApi

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
=> fix(ci): lint was failing

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt, AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DebugInfoService.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt, AnkiDroid/src/main/java/com/ichi2/libanki/LaTeX.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Media.kt, AnkiDroid/src/main/java/com/ichi2/libanki/ModelsV16.kt, AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt, AnkiDroid/src/test/java/com/ichi2/libanki/LaTeXTest.kt
`+` Other small fixes
Closes https://github.com/ankidroid/Anki-Android/issues/12249
Closes #12379
=> Fix LaTeX rendering+Notetype changing

AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
=> [GSoC] Coroutines migration ChangeSortField

AnkiDroid/build.gradle, api/build.gradle, build.gradle
Get the new android studio / gradle plugin release in there
=> Dependency updates 20220917

AnkiDroid/src/main/java/com/ichi2/libanki/sched/LrnCard.kt, AnkiDroid/src/main/java/com/ichi2/libanki/sched/LrnCardQueue.kt
=> Kotlin Cleanup in [LrnCard]

AnkiDroid/src/test/java/com/ichi2/testutils/ActivityList.kt
Kotlin Cleanup [Activity List]
=> Kotlin Cleanup [Activity List]

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt, AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.kt, AnkiDroid/src/main/java/com/ichi2/anki/UIUtils.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
=> [GSoC] Coroutines migration CollectionTask.SaveCollection

AnkiDroid/src/main/res/layout/filter_bottom_sheet.xml, AnkiDroid/src/main/res/values/02-strings.xml
Localised the string "clear"
fixes #12426
Tested on physical device.
=> Localised the string "clear"

AnkiDroid/src/main/java/com/ichi2/preferences/SeekBarPreferenceCompat.kt
I actually didn't want to clean this, but got in the mid of it in order to create some tests
One cleanup per commit
Ran the app and tweaked some seekbar preferences
=> NF: Cleanup of SeekBarPreferenceCompat

AnkiDroid/src/main/res/values-ka/01-core.xml, AnkiDroid/src/main/res/values-ka/02-strings.xml, AnkiDroid/src/main/res/values-ka/03-dialogs.xml, AnkiDroid/src/main/res/values-ka/04-network.xml, AnkiDroid/src/main/res/values-ka/07-cardbrowser.xml, AnkiDroid/src/main/res/values-ka/08-widget.xml, AnkiDroid/src/main/res/values-ka/10-preferences.xml, AnkiDroid/src/main/res/values-ka/17-model-manager.xml, AnkiDroid/src/main/res/values-pl/02-strings.xml
Standard I18N request - attempting to clear translations out for some PRs
I reviewed these in the create PR window and they look pretty good
=> Updated strings from Crowdin 20220918-2

.github/workflows/opencollective_notices.yml
I'm the only person doing OpenCollective monthly notices and payment processing and frankly I was so bogged down I couldn't get it done. It takes maybe a half hour a time to do it, and it backed up about 4 months which means I had a couple hours of budget to automate it, so here we are
Fixes no issue, just a manual process
Inspired by @krmanik's fabulous work in actions, I know I can use javascript in actions now with the github API. Pretty easy really
26 different commits + pushes + workflow runs, building it piece by working piece because the github workflow developer experience is frankly awful, but whatever
final test https://github.com/mikehardy/Anki-Android/actions/runs/3079799321/jobs/4976437491
test result https://github.com/mikehardy/Anki-Android/pull/105#issuecomment-1250538408 …
=> Automate OpenCollective PR notifications

AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
Passes unit tests and on Pixel 4 API 31
HAVEN'T TESTED IT YET ON REAL DEVICE, will update when done
=> [GSoC] Coroutines migration add field

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.kt, AnkiDroid/src/test/java/com/ichi2/anki/stats/AnkiStatsTaskHandlerTest.kt
createReviewSummaryStatistics instead of
* using getCol now uses withCol to handle collection operation
* updating the string to UI it returns the string and Activity updates the UI.
Fixes #12437 
=> Fix: Flaky test testCreateReviewSummaryStatistics

AnkiDroid/src/test/java/com/ichi2/libanki/UndoTest.kt, api/src/main/java/com/ichi2/anki/api/Utils.kt, api/src/test/java/com/ichi2/anki/api/ApiUtilsTest.kt
https://github.com/ankidroid/Anki-Android/issues/10489
=> [KotlinCleanup] use kotlin.test.* for asserting

AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt, AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt, AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt
=> Migrated CollectionTask. ConfReset to Kotlin Coroutines

AnkiDroid/src/main/java/com/ichi2/anki/reviewer/EaseButton.kt
Kotlin Cleanup [EaseButton.kt]
=> Kotlin Cleanup [EaseButton.kt]

.github/workflows/tests_emulator.yml, .github/workflows/tests_unit.yml
=> Don't fail tests GH actions if codecov fails

AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
It's last usage was removed at ee04b0c9 and now this class is used no-where.
=> Removed unused class SearchNotes

AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
Since it's a default value, there seems to be no reason to accept a nullable type here.
=> Replace String? = null by `String = ""`

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt, AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
* Post update flag behaviour has been taken up from FlagCardHandler which is just a subclass, without any additional implementations, of SuspendCardHandler.
* CollectionTask.Flag extends DismissNotes class which provides just a wrapper which allows Flag.actualTask to executeInTransaction. Same functionality has been combined and implemented in function updateSelectedCardsFlag.
IDK why the class is named DismissNotes, really not describes what it does.
Previous implementation of Flag was really messy and very hard to follow unless you've gone line by line code (took me enough time to understand). Currently it is single commit, and I couldn't figure out to break this commit into smaller ones. Will try though, if reviewing becomes harder.  I guess this migration makes it really easy to …
=> Migrated CollectionTask.Flag to Coroutines

AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt, AnkiDroid/src/main/java/com/ichi2/libanki/DecksV16.kt, AnkiDroid/src/main/java/com/ichi2/utils/CollectionUtils.kt, AnkiDroid/src/test/java/com/ichi2/utils/CollectionUtilsTest.kt
=> remove addAll

AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt
=> [Refactor] Replaced null checks with safe calls.

AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
=> [Refactor] NoteService

AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
Kotlin Cleanup [DeckPickerTest.kt]
=> Kotlin Cleanup [DeckPickerTest.kt]

AnkiDroid/src/androidTest/java/com/ichi2/anki/testutil/MockReviewerUi.kt, AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtonStatus.kt, AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ReviewerUi.kt, AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerCommandTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/reviewer/PeripheralKeymapTest.kt
Part of Kotlin cleanup #10489
Part of Kotlin cleanup #10489
=> cleanup: inControlBlocked to property

AnkiDroid/build.gradle, api/build.gradle, build.gradle
Fairly standard dependency updates, rebased the branch against main, re-pushed to get this clean set, and will merge if CI passes
=> Dependency updates 20220929

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt, AnkiDroid/src/main/java/com/ichi2/async/TaskDelegate.kt
=> [GSoC] Migrated RepairCollection to Coroutines

AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Cleanup and refactor toolbar in NoteEditor.kt
=> refactor toolbar in NoteEditor.kt

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/ImportTest.kt, AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Decks.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Finder.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Media.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Models.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Utils.kt, AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.kt, AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.kt, AnkiDroid/src/main/java/com/ichi2/libanki/template/ParsedNode.kt, AnkiDroid/src/main/java/com/ichi2/libanki/template/ParsedNodes.kt, AnkiDroid/src/main/java/com/ichi2/libanki/template/Replacement.kt, AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsListTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/AnkiPackageExporterTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/TextNoteExporterTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.kt, AnkiDroid/src/test/java/com/ichi2/preferences/TimePreferenceTest.kt, AnkiDroid/src/test/java/com/ichi2/utils/JSONObjectTest.kt, AnkiDroid/src/test/java/com/wildplot/android/rendering/PieChartParameterizedTest.kt
=> NF: uses listOf instead of asList

AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt, AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
=> [KotlinCleanup] AbstractFlashCardViewer

AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt, AnkiDroid/src/test/java/com/ichi2/async/CountModelsTest.kt
* getAllModelsAndNotesCount is mapping of CountModels. getAllModelsAndNotesCount is more descriptive than CountModels
* loadModel maps behaviour of LoadingModelsHandler
Unit tests and Pixel 4a API 30 Emulator
=> [GSoC] Migrated CountModels to Coroutines

AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
=> [GSoC] Coroutines migration conf change

AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.kt
=> converted some lines to lambda function and simplified the code

AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/reviewer/Binding.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt, AnkiDroid/src/test/java/com/ichi2/anki/dialogs/utils/RecursivePictureMenuUtil.kt, AnkiDroid/src/test/java/com/ichi2/utils/FileOperation.kt
Ideally we should lint against it, but I can't imagine someone introducing it.
=> NF: replace requireNonNull by !!

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt, AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt
Small improvement found while looking at AnkiDroidApp
=> NF: simplify getting current language

AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.kt
=> [KotlinCleanup] ModelBrowser

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
Unit tests and Pixel 4a API 30 Emulator
=> [GSoC] Coroutines migration CollectionTask.MarkNoteMulti

AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt, AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt, AnkiDroid/src/main/res/values/02-strings.xml
=> [GSoC] Coroutines migration save model

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
=> [GSoC] Migrated CheckCardSelection to Coroutines

AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
Looking at Compat, I found a method on which I wanted to add more details.
=> Comment compat

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/MediaTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
This is a merge of #12600 and #12601 because otherwise we'll never have a PR with all test successful. We need to unblock
=> Media test+unflak

AnkiDroid/build.gradle
Tiny dependency updates PR, just clearing the queue
=> Dependency updates 20221008

AnkiDroid/src/main/res/layout/card_template_editor_activity.xml, tools/parallel-package-release.sh, tools/release.sh
The release script had a silent failure, which is a couple bad things at once, this will hopefully fix it
- cycle the gradle daemon aggressively to stop the failure from happening
- include a lot more information about what step the script is on
- detect failures and help them propagate up so the workflow will fail in the future
While working through other things today I found a tiny warning and I'm including a squash here with a descriptive commit message, it is NF though
Fixes #12594 
Error propagation, workaround for OOM
I won't be able to really test it until I hit the publish button. We'll see! I'll fix whatever though
Kotlin! Because Java wasn't slow and memory hungry enough when it was compiling!
=> Mostly release script fixes, one warning squash

AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
=> [GSoC] Coroutines migration ConfSetSubdecks

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt, AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt, AnkiDroid/src/test/java/com/ichi2/testutils/AnkiAssert.kt
Fixes a part of #7108 
Unit tests and Realme 6i API 30 and Pixel 4a Emulator 
=> [GSoC] Coroutines migration RenderBrowserQA

AnkiDroid/src/main/java/com/ichi2/libanki/Finder.kt
As described in #11450, this PR attempts to replace a single usage of `var`: the local variable `preds` used in `findNotes`  method of `Finder` class defined in `Finder.kt`
doesn't fix any particular issue and lots more changes will be required before #11450 can be closed
`preds` here is set to `res1.first` (just calling it `first`). If `first` was null, the method stops there itself; otherwise, we initialize `preds` using this `first` value and continue with others
additional note: I have also merged `sql` variable declaration and initialization into a single line (located just below `preds`)
After cloning the repo, I did a gradle sync to setup everything. After committing these changes, I tried building it with Android Studio: which succeeded without errors
Kotlin provides a lot of …
=> Cleanup: Refactor Finder.kt and define `preds` as a `val` instead of `var`

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
Realme 6i API 30 [Unit tests remaining]
=> [GSoC] Coroutines migration DeleteNoteMulti

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CreateCustomStudySessionListener.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
Third commit would require more attention. Tried different approaches to tackle this one but one here I found most suitable and understandable. I have kept the callbacks as it is, used the provided callbacks in the suspend function.
Have manually tested the dialog as well. Wasn't able to cover every scenario but yeah, which I tested work. I'd ask to once more test it on real device.
Pixel 4a API 30 and Unit tests
=> [GSoC] Coroutines migration RebuildCram

AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt
=> [KotlinCleanup] DeckOptions

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
=> [GSoC] Coroutines migration SuspendCardMulti

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/ImportTest.kt
Kotlin CleanUp of ImportTest.kt
Tested on a physical device
=> Kotlin CleanUp of ImportTest.kt

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ACRATest.kt, AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt, AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnkiDroidCrashReportDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonData.kt, AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/AddonModel.kt, AnkiDroid/src/test/java/com/ichi2/utils/FileUtilTest.kt, build.gradle
Update to current ACRA versions
@jimrod942 got us most of the way there with #9969
This finishes it with some Kotlin-migration changes related to upstream switching to Kotlin and re-organizing how they did config
Fixes #7805
- Use kotlin-style variable references for 6 of the compile errors (trivial, these ones)
- Proposed patch upstream to open the method we used to override in Java - marking this draft until released in ACRA 5.9.x
- Proposed patch upstream to make default exception handler nullable
- Lots of configuration style changes as upstream config style changed again
Follow the ACRA testing guidelines in our wiki -  https://github.com/ankidroid/Anki-Android/wiki/Crash-Reports#steps-to-test - I just exercised those (and cleaned them up) recently so they should work well
- Kotlin …
=> build(deps): update to ACRA 5.9.x series

AnkiDroid/src/main/java/com/ichi2/libanki/template/Replacement.kt, AnkiDroid/src/main/java/com/ichi2/libanki/template/TemplateFilters.kt, AnkiDroid/src/main/res/values/02-strings.xml
To make it similar to Anki
Fixes #12564
Remove the string
Open a card with a notetype with Hint field
=> Remove "Show" from show hint message

AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/CustomSyncServerSettingsFragment.kt
Replace the platform AlertDialog with MaterialDialog for consistency across the app. There are three more usages of AlertDialog(slightly more complex or maybe could be refactored completely, will be done in another PR). In the first commit there's also a fix for a potential bug, see the commit description.
See images for the three replaced dialogs:
Ran the tests, manually checked the dialogs.
=> Replace some usages of AlertDialog with MaterialDialog

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/AboutFragment.kt, AnkiDroid/src/main/java/com/ichi2/anki/preferences/SyncSettingsFragment.kt
Added snackbar instead of toast and format code
Fixes #12552 
Tested on emulator Ktlint checks passed
=> Added snackbar instead of toast and format code

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt, AnkiDroid/src/main/java/com/ichi2/libanki/CollectionV16.kt, AnkiDroid/src/main/java/com/ichi2/libanki/Note.kt, AnkiDroid/src/test/java/com/ichi2/anki/dialogs/DeckPickerContextMenuTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/ClozeTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.kt
- Ensures tags are registered correctly
- Enables undoing of adds
- Also disables automatic backups when testing under robolectric, since it causes race conditions in the tests.
Closes #12608
=> Use backend for adding notes

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/java/com/ichi2/utils/SyncStatus.kt, AnkiDroid/src/main/res/values/01-core.xml
Only used during migration.
PR created here to speed up review.
=> Add the InMigration sync state

AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ScopedStorageService.kt, AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/DeleteEmptyDirectory.kt, AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MigrateEssentialFiles.kt, AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveConflictedFile.kt, AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectory.kt, AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContent.kt, AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveFile.kt, AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveFileOrDirectory.kt, AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/migrateuserdata/MigrateUserData.kt, AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/migrateuserdata/UserDataMigrationPreferences.kt, AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/DeleteEmptyDirectoryTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/ExecutorTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MockExecutor.kt, AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MockMigrationContext.kt, AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MockMigrationContextTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveConflictedFileTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContentTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveFileOrDirectoryTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveFileTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/OperationTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/ScopedStorageMigrationIntegrationTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/migrateuserdata/MigrateUserDataJvmTest.kt
This PR simply moves Migrate User Data in its own package and so some work to ensure it can be used in Service instead of being used in AsyncTask. 
It's part of scoped storage, and once merged, will be followed by a PR to create a service to migrate those data
=> Move migrate user data

AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/NotificationChannelTest.kt, AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt, AnkiDroid/src/main/java/com/ichi2/anki/NotificationChannels.kt, AnkiDroid/src/main/java/com/ichi2/anki/services/NotificationService.kt, AnkiDroid/src/main/java/com/ichi2/anki/services/ReminderService.kt
I'll use the channel for user data migration. Let's clean it in order to simplify the worker code later.
=> NF: add NotificationChannels enum params

AnkiDroid/src/test/java/com/ichi2/libanki/AnkiPackageExporterTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/TextNoteExporterTest.kt
Kotlin CleanUp of AnkiPackageExporterTest.kt and TextNoteExporterTest.kt
=> [Kotlin CleanUp] AnkiPackageExporterTest.kt and TextNoteExporterTest.kt

AnkiDroid/src/main/res/values-af/01-core.xml, AnkiDroid/src/main/res/values-bn/02-strings.xml, AnkiDroid/src/main/res/values-cs/01-core.xml, AnkiDroid/src/main/res/values-cs/02-strings.xml, AnkiDroid/src/main/res/values-cs/07-cardbrowser.xml, AnkiDroid/src/main/res/values-it/01-core.xml, AnkiDroid/src/main/res/values-it/02-strings.xml, AnkiDroid/src/main/res/values-it/07-cardbrowser.xml, AnkiDroid/src/main/res/values-yue/01-core.xml, AnkiDroid/src/main/res/values-zh-rCN/01-core.xml, AnkiDroid/src/main/res/values-zh-rCN/02-strings.xml, AnkiDroid/src/main/res/values-zh-rCN/07-cardbrowser.xml, AnkiDroid/src/main/res/values-zh-rTW/01-core.xml
Standard real-translations sync (no add/remove strings changes mixed in)
Just prepping for a release
=> Updated strings from Crowdin 20221015

AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt, AnkiDroid/src/test/java/com/ichi2/anki/BackupManagerSimpleTest.kt
Collection used to be named Deck in anki1. We have "deck" in some legacy code. Let's remove it to be less confusing.
=> NF: rename deck to col

AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt, AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.kt, AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt, AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt, AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt, AnkiDroid/src/main/java/com/ichi2/anki/OnboardingUtils.kt, AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt, AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnkiDroidCrashReportDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt, AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.kt, AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt, AnkiDroid/src/main/java/com/ichi2/anki/reviewer/FullScreenMode.kt, AnkiDroid/src/main/java/com/ichi2/preferences/CustomDialogPreference.kt, AnkiDroid/src/main/java/com/ichi2/preferences/PreferenceExtensions.kt, AnkiDroid/src/main/java/com/ichi2/utils/SyncStatus.kt, AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt, AnkiDroid/src/test/java/com/ichi2/anki/InitialActivityTest.kt, AnkiDroid/src/test/java/com/ichi2/anki/OnboardingFlagTest.kt, AnkiDroid/src/test/java/com/ichi2/libanki/sync/RemoteMediaServerTest.kt
=> NF: uses edit with block

AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt, AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt
This is used already in a few part of the code, so refactoring seems nice.
I thought it was going to help scoped storage, but in fact, not
=> NF: introduce a hasSyncAccount method

AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
=> Cleanup in [FieldEditText.kt]

AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt, AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
Unit tests and Pixel 4 AVD API 33
=> Coroutine migration ChangeDeckMulti

AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt
This PR introduces `ToastType` enum that provides the message displayed by a ACRA toast. The text of the message is loaded via a string resource. This will help with translations in the app.
Uses a enum class with a String resource identifier annotated with`@StringRes` to load the string displayed in a Toast message.
I have tested the changes running the branch in a Pixel 6 devices with Android 12. 
Closes #12631
=> refactor: Changed ACRA toastText init to ToastType enum
