ankidroid/Anki-Android

- AnkiDroid/src/main/res/drawable/ic_baseline_email_24.xml
- AnkiDroid/src/main/res/drawable/ic_baseline_lock_24.xml
- AnkiDroid/src/main/res/layout/my_account.xml
See #8355 - copied the implementation with a few minor fixes
Fixes #8347
* ⚠️ There are 3 issues regarding text contrast in "Dark" mode. None related to this change
> feat: Add password & email icon to login form

- AnkiDroid/build.gradle
- AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.java
The backend had an issue where numeric types were not correctly converted from strings.
"2" was converted to 0
This rarely occurred, as most of the time we did the conversion in the SQL
This caused the statistics to show the incorrect value for hours studied
See: https://github.com/david-allison-1/Anki-Android-Backend/pull/111
And https://developer.android.com/reference/android/database/CursorWindow#getLong(int,%20int)
Fixes #8877
⚠️  Unit Tested only
> fix: SQL Cursor string conversion error

- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.java
- AnkiDroid/src/main/res/values/01-core.xml
Add Browse Cards option in Deck Picker's context menu.
Fixes #8187 
Added the option and its functionality to the menu.
Verified.
<details>
<summary>Screenshot</summary>
</details>
> Add Browse Cards option in Deck Picker's context menu

- AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.java
Fix crash on opening StudyOptionsFragment.
Fixes #9054 
Passed correct view to `initNavigationDrawer()` from `StudyOptionsFragment`. 
Verified that StudyOptionsFragment is working fine. Also tested in fragmented mode.
> Fix crash on opening StudyOptionsFragment

- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
- AnkiDroid/src/main/res/values/04-network.xml
Remove boolean check in `onProgressUpdate()` in DeckPicker since `doProgress()` is never called with a Boolean as the first value. That code is unused and was creating problem in the Kotlin conversion of DeckPicker because of a type inference or type conversion kind of issue while assigning values to values[0] and values[1].
> Remove boolean check in onProgressUpdate of DeckPicker

- AnkiDroid/build.gradle
- api/build.gradle
- build.gradle
- lint-rules/build.gradle
Kotlin by default targets JDK 6
This lib allows usage of `AutoCloseable.use { }` instead of just `Closeable.use { }`
Briefly tried it and it seems to work now
* https://stackoverflow.com/a/43269795
* https://mbonnin.medium.com/the-different-kotlin-stdlibs-explained-83d7c6bf293
> Kotlin: enable `AutoCloseable.use { }`

- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
- AnkiDroid/src/main/res/values/01-core.xml
Show total card count in DeckPicker when no cards are due so that users can understand that there cards are still there, just the due count is zero.
If number of due cards is zero, then change the subtitle in the toolbar of the DeckPicker.
Verified the functionality on device.
<details>
<summary>Screenshot</summary>
</details>
> Show total card count in DeckPicker when no cards are due

- AnkiDroid/src/androidTest/java/com/ichi2/anki/reviewer/PeripheralKeymapTest.java
- AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
- AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java
- AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
- AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/Gesture.kt
- AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/GestureProcessor.java
- AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.java
- AnkiDroid/src/main/java/com/ichi2/anki/reviewer/PeripheralCommand.java
- AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerCommandTest.java
- AnkiDroid/src/test/java/com/ichi2/anki/ReviewerNoParamTest.java
- AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/GestureProcessorTest.java
- AnkiDroid/src/test/java/com/ichi2/anki/reviewer/PeripheralKeymapTest.java
#8078 contains a large refactor to our gesture processing which allows arbitrary mapping of key inputs to commands
Currently, we map from Gesture -> Command
And we want to map from `Command -> [Gesture]` after the linked PR is completed
This brings the code closer to this PR, in a series of non-functional commits
The aim is that this change is fairly trivially reviewable, so we get closer to the idea
Unit tested
> NF: Gesture refactor to allow for mappable gestures

- AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
Added the icons in the overflow menu in Actionbar 
Fixes: #8912
I implemented this by Override the menu methods in class. Such as onMenuOpened and onPanelClosed.
> Added Icons in Actionbar overflow menu

- AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
- AnkiDroid/src/main/res/values/10-preferences.xml
- AnkiDroid/src/main/res/xml/preferences_reviewing.xml
- AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.java
- AnkiDroid/src/test/java/com/ichi2/anki/TestCardTemplatePreviewer.java
Add preference for setting double click time interval in study screen.
Fixes #9042 
Added setting to change the time interval.
Verified by changing the time interval and checking.
> Add preference for setting double click time interval in study screen

- AnkiDroid/build.gradle
- build.gradle
Standard dependency updates branch sync
I think I need this for the 2.16alph1 publish I just tried that failed
```
* What went wrong:
Execution failed for task ':AnkiDroid:publishPlayReleaseApk'.
> Querying the mapped value of property(org.gradle.api.file.Directory, property(org.gradle.api.file.Directory, property(org.gradle.api.file.Directory, map(org.gradle.api.file.Directory flatmap(provider(task 'packagePlayRelease', class com.android.build.gradle.tasks.PackageApplication)) check-type())))) before task ':AnkiDroid:packagePlayRelease' has completed is not supported
```
> Dependency updates 20210625

- AnkiDroid/src/main/java/com/ichi2/anki/OnboardingFlag.kt
- AnkiDroid/src/main/java/com/ichi2/anki/OnboardingUtils.kt
- AnkiDroid/src/test/java/com/ichi2/anki/OnboardingFlagTest.kt
Implement preference flags for onboarding to check screen visit status.
> Implement preference flags for onboarding to check screen visit status

- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsArrayAdapter.java
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.java
- AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogTest.java
- AnkiDroid/src/test/java/com/ichi2/testutils/RecyclerViewUtils.java
This PR is based on #8763
Fixes #8764
sorting after the tag is checked
Emulator
> fix: sorting new tag added in `TagsDialog`

- AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
- AnkiDroid/src/main/java/com/ichi2/async/SingleTaskManager.java
- AnkiDroid/src/main/java/com/ichi2/async/TaskDelegate.java
- AnkiDroid/src/main/java/com/ichi2/async/TaskManager.java
- AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java
- AnkiDroid/src/test/java/com/ichi2/async/AbstractCollectionTaskTest.java
- AnkiDroid/src/test/java/com/ichi2/async/ForegroundTaskManager.java
CollectionTask is not supposed to be extended, it would be a bad idea since we want actually to stop using
AsyncTask. Its only constructor can be package private instead of protected.
Task is moved to its own class, so that it's easier to see that it's not dependant of CollectionTask. Its renamed into
TaskDelegate to indicate that it's a delegate. It is not actually a task executed by an executor but its the delegate
that contains actual business logic
This is related to a Discord discussion with David who found the name confusing - a fact which is hard to argue with
> NF: comment and rename Task related classes

- AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/DBTest.java
- AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
- AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java
- AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
Migrating user data to a scoped storage directory (external only for now) in order to preserve access to user data under scoped storage.
Takes a step towards fixing #5304. Fixes #9107.
Uses storage permission (which AnkiDroid already asks for) to access legacy storage and migrates the data to the External App-Specific Directory (given by ```getExternalFilesDir()```)
Migration is done by launching a ```MigrateToScoped``` task  of type ```CollectionTask.Task```
Any file within the AnkiDroid folder can be accessed under Scoped Storage post-migration.
1. Option to choose their default directory (internal or external)
2. Support accessing certain non-app-specific locations - needed in some cases for accessing media (eg: like adding an audio clip to a note which was recorded by some other app, …
> Migrate AnkiDroid folder to External Scoped App-Specific Directory

- AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
The goal here is to ensure that each preference get a comment explaining their purpose. Using a string constant ensure that the javadoc can be found from any place where the constant is used
> Preferences constant

- AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.java
- AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
- AnkiDroid/src/main/res/values/10-preferences.xml
- AnkiDroid/src/main/res/values/16-multimedia-editor.xml
- AnkiDroid/src/main/res/xml/preferences_general.xml
AnkiDesktop have feature of "Paste Clipboard Image As PNG " in the preference window ,
currently AnkiDroid do support to copy and paste image but not have this preference option in app.
Supercedes + Closes #8804 - copied the implementation with fixing lint and minor changes
Fixes #8709
> [Preference] Paste clipboard image as PNG

- AnkiDroid/src/main/java/com/ichi2/anki/reviewer/GestureMapper.java
Should workaround issue with robolectric in CI, Fixes #9173
I regrettably altered real code in order to satisfy some not-quite-reproducible test constraint, which is personally irritating
But works
It needs to pass unit tests in CI, it appears to https://github.com/mikehardy/Anki-Android/runs/2956584797?check_suite_focus=true
Something about the way the RobolectricTestRunner does buildActivity in certain environments means that AnkiDroidApp.sInstance is null it appears - it calls the Activity constructor before calling Application.onCreate, so initialization fails if you use a static initializer that touchs the Application
> test: delay GestureMapper init from static init to runtime

- AnkiDroid/build.gradle
- build.gradle
Standard dependency updates PR, but it looks like google had a big day
Android Studio 4.2.2 is out, so bump gradle plugin
All test deps bumped
Most interestingly, if we use kotlin we should have the -ktx versions of libraries that support it I think, so switching to those deps
> Dependency updates 20210630

- build.gradle
- lint-rules/build.gradle
Reduce GitHub notification spam (previously we get 3 update PRs)
as the library updates in lockstep
Fixes #9179
Only tested via a build
> gradle: consolidate lint library version

- AnkiDroid/src/main/res/values/10-preferences.xml
Accidental inclusion. Reported on CrowdIn
Need to see how this is handled after a translation sync
> fix: remove maxLength on `paste_as_png_summary`

- AnkiDroid/src/main/java/com/ichi2/anki/reviewer/Binding.java
- AnkiDroid/src/main/java/com/ichi2/anki/reviewer/PeripheralCommand.java
Implement part of the "Binding" class from #8078 for PR #6052.
* Bindings are compared (via a HashMap) to find the correct binding and serialised to the preferences.
We do not implement equality or serialisation here. Equality is going to require a harsh review, and serialisation depends on the implementations, so these are deferred.
The linked PR sadly skips the issue that the default in-app bindings need to handle when `*` is mapped on a keyboard with and without a shift key being pressed.
When a user defines these changes in the UI, it won't matter, but is important for sensible defaults
https://github.com/ankidroid/Anki-Android/issues/7840
> Key Binding: Implement Binding class

- AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.java
The hourly stats chart was built in a way that led to user surprise - only hours that had data were populated in the chartbuilder data set, so the chart's X axis was data-dependent and the axis labels themselves were variable and sometimes non-existant
Fixes #8920
Pre-populate all the hours so the chart is consistent every time
Visually on an emulator with some test data
Before
After
> Populate all hours in hourly stats chart

- AnkiDroid/build.gradle
- AnkiDroid/src/main/java/com/ichi2/anki/reviewer/Binding.java
- AnkiDroid/src/main/java/com/ichi2/anki/reviewer/PeripheralCommand.java
- AnkiDroid/src/main/java/com/ichi2/anki/reviewer/PeripheralKeymap.java
- AnkiDroid/src/test/java/com/ichi2/anki/reviewer/BindingTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/reviewer/MappableBindingTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/reviewer/PeripheralKeymapTest.java
So close now! After implementing equality, we need to implement string processing
This isn't an ideal solution (hashcode returning 0, eww), but it allows a `Binding` to be added to a HashMap. This massively improves the ability of someone to perform a `Binding -> Command` lookup, which is what we're looking for.
Taken somewhat from #8078 to help with #6052
A few unit tests, tried it out with my keyboard and it still works.
> KeyBinding: Implement HashMap lookup

- AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerKeyboardInputTest.java
- AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java
- AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.java
- AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java
- AnkiDroid/src/test/java/com/ichi2/anki/RunInBackground.java
- AnkiDroid/src/test/java/com/ichi2/anki/dialogs/RecursivePictureMenuTest.java
- AnkiDroid/src/test/java/com/ichi2/anki/dialogs/utils/HelpDialogTest.java
- AnkiDroid/src/test/java/com/ichi2/async/CollectionTaskCheckDatabaseTest.java
- AnkiDroid/src/test/java/com/ichi2/async/CollectionTaskSearchCardsTest.java
- AnkiDroid/src/test/java/com/ichi2/libanki/CheckMediaTest.java
- AnkiDroid/src/test/java/com/ichi2/testutils/TaskSchedulerRule.java
Requested by Arthur in https://github.com/ankidroid/Anki-Android/pull/8442#issuecomment-873667461
This implements running unit tests in the foreground using a custom scheduler. This should both reduce the flakiness of tests (as there are no race conditions for background tasks) and massively speed up the tests (as we no longer need to `sleep()`).
Original PR had the following comment:
> As requested by @mikehardy on https://github.com/ankidroid/Anki-Android/pull/7005#pullrequestreview-627234122
----
Implementation: Default to new scheduler for methods using `RobolectricTest`
Use a rule to detect `@RunInBackground`, and if it's found, default back to the old scheduler
See: https://github.com/junit-team/junit4/wiki/Rules#custom-rules, or commit messages
Supersedes #8442
----
I'd rather not …
> Run Unit Tests in Foreground

- AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java
- AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java
I'm testing on full gamut of emulators API21-31 including a tablet.
Turns out on a tablet when you run it first time the study options fragment attempts to load and do some complex things with the toolbar that involve collection state
But there's no permission to touch the collection on first run yet, so it crashes the app.
Also when I went to add testing I found that if the backend was locked it would crash.
Unlogged
Mark getCol() nullable and make it exception-tolerant, check getCol() return to see if it's Null and choose sensible defaults if so, to avoid the crash
Reproduced easily with a Tablet running AnkiDroid first time.
Can no longer reproduce after.
Also parameterized the DeckPickerTest which uncovered 4 different ways it could crash, 1 of which is not easily user-testable but …
> Fix tablet deck picker / study options getCol crashes

- AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java
Original PR #9204  worked fine but was in flight at same time as test foreground
work happened, the combination was a failure, this sets the 4 exception case
tests (getCol() returns null or db locked exception) to background mode, where
everything appears to work
I triple-checked actual Pixel C emulator to verify it is still working in
a no-permissions first startup case both with and without a collection present,
it is actually working now where it did actually crash before so this is test-only really
Related #9204
Related #9203 
Just background tests that break in foreground mode
Local unit test run failed on command line and master before the fix
local unit test run passes after
API30 Pixel C works correctly on first startup with no permission still
Parallel development is hard …
> Fix DeckPickerTest tablet special cases to run in background

- AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupUnderBackupTest.java
Fixes issue #9112.
This update gives users (contributors) more information on why the acticityHandlesRestoreBackup test might fail.
Fixes #9112 
Added instructions on a possible fix for the test's failure.
No tests were performed. The documentation was simply updated. I did build and run the app to make sure nothing
was unintentionally broken.
Followed instructions given in the issue description.
- [ x ] You have performed a self-review of …
> Added unit test documentation to ActivityStartupUnderBackupTest

- api/build.gradle
- api/src/main/java/com/ichi2/anki/FlashCardsContract.java
- api/src/main/java/com/ichi2/anki/api/Basic2Model.java
- api/src/main/java/com/ichi2/anki/api/BasicModel.java
Our lint checks are internal and not for consumers.
Added in 018c1db71fc370440fc85e3071fd7bea17303921
Fixes #9214
`lintPublish` publishes the checks into the aar
> Use this configuration to include lint checks you want Gradle to execute when building your project.
`lintChecks` performs the checks for the project
>Use this configuration in Android library projects to include lint checks you want Gradle to compile into a lint.jar file and package in your AAR. This causes projects that consume your AAR to also apply those lint checks. If you were previously using the lintChecks dependency configuration to include lint checks in the published AAR, you need to migrate those dependencies to instead use the lintPublish configuration.
>   ```groovy
>    dependencies {
>      // Executes lint …
```
> Don't publish lint.jar for API project

- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioClipFieldController.java
`URLConnection.guessContentTypeFromName` returns `application/ogg`
instead of `audio/ogg` in Android 8
Fixes #9225 (using the default Android file picker)
We use `EXTRA_MIME_TYPES`, which isn't fully supported
But neither is commas in the `setType` call:
https://stackoverflow.com/questions/1698050/multiple-mime-types-in-android
so it seems like the best option
Tested on an Android 8 emulator
https://stackoverflow.com/questions/1698050/multiple-mime-types-in-android
> fix[Audio Insert]: Allow .ogg on Android 8

- lint-rules/src/main/java/com/ichi2/anki/lint/rules/ConstantFieldDetector.java
- lint-rules/src/main/java/com/ichi2/anki/lint/rules/FieldNamingPatternDetector.java
- lint-rules/src/main/java/com/ichi2/anki/lint/rules/NonPublicNonStaticFieldDetector.java
`ConstantFieldName` lint was triggered by auto-generated Kotlin
companion objects named "Companion" (expected: COMPANION)
Fixes #9223
Unblocks #9222
As these are auto-generated, allow constants called "Companion"
Lint no longer fails on #9222
> fix[lint]: allow Kotlin companion objects 

- AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.java
It appears based on a crash report that via an interaction between review times, day cutoff, and new scheduler timezone handling, attempting to display stats for a full day can generate stats for out of range hours.
Fixes #9230
I think the appropriate change is to mod the hour in the array.set by 24 to make sure it falls in range
I learned again that I can't wait for the stats code to be purged from our codebase.
> fix(stats): set hourly breakdown stats into 0-23 range by modulus

- AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
- AnkiDroid/src/main/res/values/02-strings.xml
- AnkiDroid/src/main/res/values/10-preferences.xml
- AnkiDroid/src/main/res/xml/preferences_advanced.xml
While reviewing I often accidentally hit the back button when answering a question. This is frustrating because it disrupts my studying, especially because after I reopen the deck I get a different card and I have to do the other one again later.
Fixes #9215 
Fixes #9210 
I added an option in the advanced settings to enable this feature. If enabled, you have to press back twice to exit the app and return to the main screen.
Tested on Pixel_API_30
> Add option to press back twice to return to main screen

- AnkiDroid/src/main/java/com/ichi2/anki/reviewer/Binding.java
- AnkiDroid/src/main/java/com/ichi2/utils/StringUtil.java
- AnkiDroid/src/test/java/com/ichi2/anki/reviewer/BindingAndroidTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/reviewer/BindingTest.kt
- AnkiDroid/src/test/java/com/ichi2/utils/StringUtilTest.java
Key Bindings need to be serialized and deserialized from preferences
This brings in the code for #8078 to handle this aspect  of #6052 
Should be non-functional, unit tests lifted from the PR
> implement serde for Key Binding

- AnkiDroid/build.gradle
Lint previously worked through the api module
aae98e787f7bcbcd5235d2e273d8ae6593335ffd removed this
Fix via adding a `lintChecks`
Fixes #9242
> fix: lint was not working in Anki-Android

- AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
- AnkiDroid/src/main/res/values/constants.xml
Add preference for enabling onboarding in debug build.
It can be accessed through 'Advanced' settings.
> Add preference for enabling onboarding in debug build

- AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
- AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.java
- AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.java
- AnkiDroid/src/main/java/com/ichi2/compat/CompatV29.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java
I saw an exception in the logs when playing Audio cards, and wanted to avoid this
Now we display `E/MediaMetadataRetrieverJNI: getEmbeddedPicture: Call to getEmbeddedPicture failed`
Related: #5022
* Use the new API
* Convert string to a path
* Convert `MINI_SIZE` to  sample representation (method now accepts a `Size`)
* Don't use a cancelListener
Android 11 device: no longer has a large stack trace in logs
https://developer.android.com/reference/android/media/ThumbnailUtils#createVideoThumbnail(java.io.File,%20android.util.Size,%20android.os.CancellationSignal)
MINI_SIZE: https://github.com/aosp-mirror/platform_packages_providers_mediaprovider/blob/b430fcafc434c559324732b4296f1146b2f717f8/apex/framework/java/android/provider/MediaStore.java#L1697
> deprecation: fix createVideoThumbnail

- AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
- AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.java
- AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
- AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java
Fix: CardBrowser displays a wrong deck.
Fixes #9013 
The cause of this problem is that: In CardBrowser, onCreate() always loads a deck ID from Collection and then CardBrowser displays this deck (let's call it deck 1). 
Later, when we select deck 2 from the DeckSelectionDialog, although CardBrowser shows cards of deck 2, the ID of deck 2 is not saved to Collection. 
At this moment if we go to Settings and then back to CardBrowser, onCreate() of CardBrowser is called again, so deck 1 is loaded and showed again.
This problem also manifests itself when:
In CardBrowser with deck 1 shown
Switch to deck 2 (by selecting it from the DeckSelectionDialog like above)
Switch to Statistics (using the Navigation Drawer)
Switch back to CardBrowser (using the Navigation Drawer)
Now CardBrowser will …
> Fix CardBrowser shows wrong deck

- AnkiDroid/src/main/java/com/ichi2/anki/reviewer/PeripheralKeymap.java
- AnkiDroid/src/test/java/com/ichi2/anki/reviewer/KeyboardShortcutIntegrationTest.java
**This is a change in functionality from 2.15.5**
We moved to onKeyDown on e439280bf3382a4af4146316f2ada063cce0f8ca
onKeyDown repeats, whereas onKeyUp didn't
So we handle repeats via not counting them as actions
Unit tested and tested with an Apple Keyboard & my Android 11
* onKeyDown repeats
> fix: holding a key should not repeat events

- AnkiDroid/src/main/res/values/10-preferences.xml
All others used "tap" in the key, but "touch" in the string
Added in 78aa1efb506ddf2408d006c8669aab79d5577d39
> rename: tap -> touch

- AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
- AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
- AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
- AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
- AnkiDroid/src/main/java/com/ichi2/anki/reviewer/FullScreenMode.kt
- AnkiDroid/src/main/res/layout/navigation_drawer_layout_fullscreen.xml
- AnkiDroid/src/test/java/com/ichi2/anki/ReviewerNoParamTest.java
When going fullscreen, the reviewer had white/blue borders rather than
filling the content
Cause:
d0d1edd moved to a single xml file for
the navigation drawer, rather than copy/pasting it into each file
Some layouts excluded `android:fitsSystemWindows="true"`, but the new
xml file always included this.
This caused the layout problems
Fixes #9267
* add method: `fitsSystemWindows` and layout without the variable
My Android 11
* I wasted a lot of time learning about `PhoneWindow` on Android Code Search
> fix: borders on fullscreen Reviewer

- AnkiDroid/src/test/java/com/ichi2/anki/stats/OverviewStatsBuilderTest.java
Added some basic unit tests for OverviewStatsBuilder to help cover the code in there, and according to the coverage report generated by Android Studio, around 95% of the lines should be covered by it.
However, the only deck stats the HTML string grabs are 0, so this covers the code, but the tests are not exhaustive. In the future, these could be expanded to include more realistic stats.
> Added unit tests for OverviewStatsBuilder

- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
- AnkiDroid/src/main/java/com/ichi2/async/Cancellable.java
- AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
- AnkiDroid/src/main/java/com/ichi2/async/SingleTaskManager.java
- AnkiDroid/src/main/java/com/ichi2/async/TaskManager.java
- AnkiDroid/src/test/java/com/ichi2/async/AbstractCollectionTaskTest.java
- AnkiDroid/src/test/java/com/ichi2/async/ForegroundTaskManager.java
- AnkiDroid/src/test/java/com/ichi2/libanki/CheckMediaTest.java
This emphasis the fact that - outside of test - CollectionTask is not used anymore. It reduce the available API to
cancel and safeCancel
> NF: launchCollectionTask return Cancellable

- AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java
- AnkiDroid/src/androidTest/java/com/ichi2/anki/TestUtils.java
- different selectors for elements (so it doesn't flake on Android 5)
- keyboard dismiss when entering note editor (so it doesn't flake Android 8)
- note type selection (so it doesn't flake in general)
Related #9073
Running `./gradlew jacocoAndroidTestReport` over and over while API21-API31 phone + API30 Pixel C tablet emulators were up
instrumented tests are subtle, but the error messages aren't too bad to follow towards fixes
> Test: stabilize study options click test

- AnkiDroid/src/main/res/layout/studyoptions_fragment.xml
Fix issue of extra whitespace on top of study options in tablet.
Fixes #9279 
Removed `android:fitsSystemWindows="true"` from `study options_fragment.xml`.
Verified on emulator running Pixel C API 30.
> Fix issue of extra whitespace on top of study options in tablet

- AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/AudioPlayerTest.java
Added unit tests that cover all of the functions found in AudioPlayer. According to the coverage report generated by Android Studio, it should be at 100% coverage now.
Also in testAbruptStop, is it intended behavior for stoppingListener and stoppedListener to not run() when AudioPlayer plays, then immediately stops with stop()?
> Added unit tests for AudioPlayer

- AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
- AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.java
- AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.java
- AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java
Update usage of deprecated stream types in MediaPlayer and AudioManager.
Documentation links:
https://developer.android.com/reference/android/media/MediaPlayer#setAudioAttributes(android.media.AudioAttributes)
https://developer.android.com/reference/android/media/AudioManager#requestAudioFocus(android.media.AudioFocusRequest)
Fixes #9274 
Fixes #5022
Checked that audio functionality is working in note editor and reviewer.
> Update usage of deprecated stream types in MediaPlayer and AudioManager

- AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
- AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.java
- AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.java
- AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java
Add audio ducking back which stopped working in #9280 and use same instance of `AudioFocusRequest` for `requestAudioFocus()` and `abandonAudioFocus()`.
Fixes #9287 
Verified the functionality on device.
https://developer.android.com/guide/topics/media-apps/audio-focus
> Add audio ducking back and use same instance of AudioFocusRequest

- AnkiDroid/build.gradle
- AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java
- AnkiDroid/src/androidTest/java/com/ichi2/anki/TestUtils.java
isCI was returning false on CI as the environment variable wasn't
passed to an emulators
I failed to read/set environment variables working
I failed to get system properties working reliably
Fixes #9293
Use `BuildConfig`
Tested in CI on david-allison-1/Anki-Android
We already use the same code to detect a CI build in our gradle scripts
Tried, but didn't work reliably:
* https://stackoverflow.com/questions/60540510/how-to-set-an-environment-variable-in-android
* https://stackoverflow.com/questions/5095234/how-to-get-root-access-on-android-emulator
* https://stackoverflow.com/questions/9937099/how-to-get-the-build-prop-values
> fix tests: detect CI - use build config

- AnkiDroid/src/main/res/values/constants.xml
Send to a specific page instead of a section of a page
The specific page has much less content and appears more optimised for
contributions
from: https://opencollective.com/ankidroid#section-contribute
to: https://opencollective.com/ankidroid/contribute
Untested
> Improve Open Collective Donate Link

- AnkiDroid/src/main/res/values/attrs.xml
- AnkiDroid/src/main/res/values/colors.xml
- AnkiDroid/src/main/res/values/styles.xml
- AnkiDroid/src/main/res/values/theme_black.xml
- AnkiDroid/src/main/res/values/theme_dark.xml
- AnkiDroid/src/main/res/values/theme_light.xml
AnkiDroid has 2 Night themes: Dark and Black.
Currently in these themes, especially the Black theme, the elevation of the popup menus is not easy to notice, making them look slightly off:
There are 2 places having this problem: The toolbar's overflow menu (above picture) and the spinners' dropdown menu (following picture):
In [Material Design Guideline](https://material.io/design/color/dark-theme.html#properties), they suggest using a lighter background color to indicate elevation in these cases, which I think is appropriate.
Also according to Material Design Guideline, in Day themes (Light and Plain) we don't have this problem because in these themes we can use shadow to express elevation. However, shadow is either not possible or not effective in Night themes, because in these themes …
> Implement elevation for popup menus in Night themes

- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioClipFieldController.java
Audio files were not selectable from the System File Picker while adding an audio clip to a Note.
Fixes #9321.
- No documentation on specifying multiple disjoint MIME types with
```Intent.ACTION_GET_CONTENT```
- ```Intent.ACTION_OPEN_DOCUMENT```'s documentation suggests passing ```*/*``` to
```setType()```, and specifying the desired disjoint MIME types in an array
for the intent extra ```Intent.EXTRA_MIME_TYPE```. This suggestion works for
```Intent.ACTION_GET_CONTENT``` as well & is the one used to make audio
files selectable so that they can be imported while adding an audio
clip.
Tested on:
- Samsung Galaxy S7 API 26 (Physical Device)
- Pixel 4 XL API 30 (Emulator)
Steps:
1. Add Note
2. Add Audio Clip
3. Click on LIBRARY
4. Audio files in the directory being viewed should be …
> fix[Audio Insert]: Make audio files selectable

- build.gradle
- lint-rules/build.gradle
- lint-rules/src/test/java/com/ichi2/anki/lint/rules/CopyrightHeaderExistsTest.java
- lint-rules/src/test/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLengthTest.java
Fix errors which were introduced:
* api is now required
* Unicode Handling changed
* Compilation errors from missing imports were introduced
Bumps `lint_version` from 27.2.2 to 30.0.0.
Updates `lint-api` from 27.2.2 to 30.0.0
Updates `lint` from 27.2.2 to 30.0.0
Updates `lint-tests` from 27.2.2 to 30.0.0
---
updated-dependencies:
- dependency-name: com.android.tools.lint:lint-api
dependency-type: direct:production
update-type: version-update:semver-major
- dependency-name: com.android.tools.lint:lint
dependency-type: direct:production
update-type: version-update:semver-major
- dependency-name: com.android.tools.lint:lint-tests
dependency-type: direct:production
update-type: version-update:semver-major
...
Signed-off-by: dependabot[bot] <support@github.com>
> build(deps): bump lint_version from 27.2.2 to 30.0.0

- AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
Moves away from using direct file path access (using a ```File``` object) to the new DeckPicker background image selected by the user since the image may be in a directory which will not be accessible via direct file path access under Scoped Storage.
The set DeckPicker background feature will now work for all devices once Scoped Storage is enforced.
Currently, ```ContentResolver``` is used to query the ```MediaStore.Images``` collection to obtain the path of the image selected by the user. Then, a ```File``` object (direct file path access) is used to obtain size & open the ```InputStream``` to copy the image.
Instead, the ```MediaStore.Images``` collection can directly be queried for image size, and ```ContentResolver``` can open the ```InputStream``` using the URI of the image selected …
> Use MediaStore instead of direct file path access for DeckPicker background preference

- AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
- AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
- lint-release.xml
This fixes all but one lint error coming from AGP 7
This helps get #9338 closer to completion.
The only missing lint check is pending intent mutability. The constant that we should use was introduced in API 23.
https://developer.android.com/about/versions/12/behavior-changes-12#test-pending-intent
> AGP 7 lint fixes

- AnkiDroid/src/main/res/values/theme_dark.xml
Made the color of the status bar be dark grey instead of black in dark theme
Fixes #9317 
changed `theme_dark_primary_dark` to dark grey from black
> status bar color in dark theme changed to dark grey

- AnkiDroid/src/test/java/com/ichi2/utils/JSONObjectTest.java
The current test was deprecated. When I started editing them, I got a lot of warning. So now we specify that we want exact equality and not approximation
> NF: assert double equals uses Delta

- AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java
- AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java
- AnkiDroid/src/main/java/com/ichi2/utils/FileUtil.java
This change moves away from using direct file path access for the Add/View Image feature for the following reasons:
1.  For apps targeting API 29, unless the ```requestLegacyExternalStorage``` flag is set to ```true```, they will not be able to access media in shared storage using direct file path access (this is why Add Image works right now)
2. For apps targeting API 30+, they will be able to use direct file path access but will have to obtain permission to access media
3. MediaStore is the recommended approach to importing a media file that already exists
4. For apps targeting API 30+, ```WebView``` will not have access to the device filesystem by default. Hence, it won't be able to access the images stored in the AnkiDroid directory, even if AnkiDroid itself has permission to its …
> targetSdk=30 compatibility for Add/View Image feature

- AnkiDroid/build.gradle
- build.gradle
Support JDK16 for development
Fixes #8434 
- update google play publisher plugin to 3.7.0 (just released, works with our new android gradle plugin 7.0 only)
- clean up JDK compatibility message
- clean up usage of variants in gradle file to match current recommended syntax
On linux with JDK11 (this should cover most developers)
On macOS 
```bash
brew install adoptopenjdk16
export JAVA_HOME=$(/usr/libexec/java_home -v16)
export PATH=$JAVA_HOME/bin:$PATH
./gradlew clean jacocoTestReport
```
Bleeding edge is bleeding.
> WIP Java16 support - not working yet / proof-of-concept

- AnkiDroid/src/main/java/com/ichi2/libanki/DecksV16.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/backend/DecksBackend.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/utils/PythonExtensions.kt
This converts decks.py to DecksV16.kt as it was in Anki 2.1.34
To move to the v16 schema, we need to upgrade the classes
associated with the collection columns
These have moved from JSON in a single column to one row per protobuf
After this is merged, we can start migrating Decks.java to use the
same interface and consolidate functionality.
Once the interfaces are the same, we can build a new "Collection" class
with the new table-based classes, flip to opening the collection via
the v16 upgrade mechanism, and then check for bugs.
Some of this functionality is explicitly WIP (`DecksBackend.kt`)
Related: #8988
Not working code - no tests
> SchemaV16: Implement Decks [WIP, but ready for review/merge]

- AnkiDroid/build.gradle
- AnkiDroid/src/main/java/com/ichi2/anki/PromptBackgroundAdapter.kt
- AnkiDroid/src/main/java/com/ichi2/anki/PromptBackgroundInterface.kt
- AnkiDroid/src/main/java/com/ichi2/utils/DimmedPromptBackgroundDecorator.kt
Add onboarding library with support for dimmed background.
https://github.com/sjwall/MaterialTapTargetPrompt.
> Add onboarding library with support for dimmed background

- AnkiDroid/src/main/assets/scripts/card.js
- AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
This continuation of JS API PR to add more functionality and new features to JS API.
Fixes #9231
Added functions to JavaScriptInterface
Use following functions for the API
- To bury current card (`return boolean`)
```js
<button onclick="AnkiDroidJS.ankiBuryCard();">Bury Card</button>
```
- To bury current note (`return boolean`)
```js
<button onclick="AnkiDroidJS.ankiBuryNote();">Bury Note</button>
```
- To suspend current card (`return boolean`)
```js
<button onclick="AnkiDroidJS.ankiSuspendCard();">Suspend Card</button>
```
- To suspend current note (`return boolean`)
```js
<button onclick="AnkiDroidJS.ankiSuspendNote();">Suspend Note</button>
```
- To show Tags dialog for adding tag to current card (`void function`)
```js
<button onclick="AnkiDroidJS.ankiAddTagToCard();">Show Tag …
```
> New JS API for bury & suspend card and bury & suspend note and tag card

- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
- AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
- AnkiDroid/src/main/res/xml/preference_headers.xml
- AnkiDroid/src/test/java/com/ichi2/testutils/PreferenceUtils.java
The first part of fixing preference deprecation is removing the dependency from `Activity -> PreferenceScreen` via `PreferenceContext`, the `PreferenceScreen` should be contained by a fragment, and the containing activity should not need knowledge of this.
Related: #5019 
We pick the `initSubscreen(_, PreferenceContext)` method first. We extract each branch of this method into a separate class, handle navigation to the class, and then finally remove the method in `Preferences`. This allows us to remove one of the two method calls (sadly not the one that we want).
Preferences still work on my Android 11. Using CI to run unit tests as it's getting late.
> NF: Start on Preference deprecation

- AnkiDroid/src/main/AndroidManifest.xml
- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
- AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.java
- AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
- AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
- AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.java
- AnkiDroid/src/main/res/drawable/close_icon.xml
- AnkiDroid/src/main/res/drawable/home_icon.xml
- AnkiDroid/src/main/res/layout/activity_shared_decks.xml
- AnkiDroid/src/main/res/layout/fragment_shared_decks_download.xml
- AnkiDroid/src/main/res/menu/download_shared_decks_menu.xml
- AnkiDroid/src/main/res/values/02-strings.xml
- AnkiDroid/src/test/java/com/ichi2/testutils/ActivityList.java
Implement better download and import system for shared decks.
Fixes #7690
Added new Activity with WebView and used DownloadManager to download along with setting up BroadcastReceiver to check for download completion and import the downloaded deck.
Tested on API 28 and API 30 emulators.
https://user-images.githubusercontent.com/35566748/127007945-ad067e37-457f-4087-a28b-0fcc1c243e58.mp4
> Implement better download and import system for shared decks

- AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
- AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
This is continuation of JS API features. From reviewer using js function/button in one click it will go to CardBrowser and search for cards using query.
Fixes #8109
1. Added a JSInterface function and used intent to call CardBrowser
3. Get string extra in CardBrowser and assign query to `mSearchTerms` then call `searchCards()`
Testesd on devices and emulator 
1. Add a button in card template to call `AnkiDroidJS.ankiSearchCard(query)`
2. Add query like, this query are same as entering in CardBrowser
```
'deck:"deck name" {{front}}'
'deck:"test" flag:2 tag:marked'
'deck:"test" flag:2 tag:marked is:suspended'
'deck:"test" flag:2 tag:marked search text here'
```
3. Click button to run the query
```js
<button onclick="AnkiDroidJS.ankiSearchCard('deck:\"test\" {{hanzi}}')">Search this in Card …
```
> JS API to open card browser and search with query 

- AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
While developing the JS API features, it needs to change the HTML / JS Debugging to true when app reinstalled.
Added if condition in AnkiDroidApp.java and edited prefs
> Make HTML/JS debugging default to true in prefs in DEBUG build

- AnkiDroid/build.gradle
- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
- AnkiDroid/src/main/java/com/ichi2/anki/Info.java
- AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.java
- AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
- AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java
- AnkiDroid/src/test/java/com/ichi2/anki/InitialActivityTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/InitialActivityWithConflictTest.java
- AnkiDroid/src/test/java/com/ichi2/anki/servicemodel/PreferenceUpgradeServiceTest.kt
Due to the version number depending on the processor architecture, we can no longer use this to handle preference upgrades. We need a new mechanism to apply preferences
Fixes #9309 
* Refactor the startup flow to `InitialActivity`
* Define a `PreferenceUpgrade` class and a preference (int) for the preference version
* Each subclass performs one upgrade via an `upgrade()` method
* On each version change, check to see if there are any pending upgrades, and execute them if so
Unit tests and on my phone
> feat: preference upgrades

- lint-rules/src/main/java/com/ichi2/anki/lint/IssueRegistry.java
- lint-rules/src/main/java/com/ichi2/anki/lint/rules/ConstantJavaFieldDetector.java
- lint-rules/src/main/java/com/ichi2/anki/lint/rules/JavaFieldNamingPatternDetector.java
- lint-rules/src/main/java/com/ichi2/anki/lint/rules/NonPublicNonStaticJavaFieldDetector.java
- lint-rules/src/test/java/com/ichi2/anki/lint/rules/JavaConstantFieldDetectorTest.java
- lint-rules/src/test/java/com/ichi2/anki/lint/rules/JavaNonPublicNonStaticFieldDetectorTest.java
We want to move away from AOSP naming for Kotlin
As it makes getters and primary constructors less useful
as the naming conflicts with other policies we want to enforce
AOSP naming is also against Google suggestions
Fixes #9377
> lint: Only enforce variable naming in java

- AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
- AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
- AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.java
- AnkiDroid/src/main/java/com/ichi2/compat/CompatV29.kt
MediaStore has the following advantages over direct file path access and is the recommended approach for saving media files
- MediaStore is more future-proof than direct file path access. For instance, direct file path access does not work for apps targeting API 29 unless they set the requestLegacyExternalStorage flag to true
- MediaStore offers up to 2x faster random read and write speeds
- Use MediaStore's ```insert()``` instead of direct file path access in ```saveWhiteboard()```
- Continue to use File API for API <= 28 since the MediaStore implementation is not available below API 29. Hence, the ```WRITE_EXTERNAL_STORAGE``` permission will need to be requested for phones running API 28 and lower. This is in line with Google's recommendation of continuing to ask for storage permissions …
> Use MediaStore to save whiteboard for API>28

- AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java
App crashes upon an attempt to import a .colpkg collection if the collection being imported uses the V2 Scheduler
Fixes #9386 
- Allow V2 .```colpkg``` collections to be imported by allowing files ending
with ```.anki21``` to be used to initialize the Collection object in
```Storage.Collection()```
- Previously only files ending in ```.anki2``` could be used due to an
assertion
Tested importing .apkg and .colpkg collections which used the V1 or V2 scheduler on the following devices:
- Pixel 4 XL API 30 (Emulator)
- Pixel XL API 26 (Emulator)
> Fix V2 Scheduler .colpkg collection import

- AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.java
- AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.java
The Import Collection feature asks the user to pick a file to import (.apkg/.colpkg). The Uri of the file is returned as the data of the intent. If the scheme of the URI is 'file', ```ImportUtils.handleFileImportInternal()``` uses direct file path access to read from the selected collection. Direct file path access to non-app-specific directories will not work under Scoped Storage.
Remove the direct file path access approach & use the existing ContentResolver approach to open URIs of the 'file' scheme, in addition to any other supported schemes.
As a side effect, this means that no storage permissions are required to Import a collection, hence the check for a Storage Permission grant before ```IntentHandler``` handles the File Import can be removed.
Tested by importing .apkg & .colpkg …
> Ensure Import Collection is functional under Scoped Storage

- AnkiDroid/src/main/java/com/ichi2/anki/OnboardingUtils.kt
- AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
- AnkiDroid/src/main/res/values/constants.xml
- AnkiDroid/src/test/java/com/ichi2/anki/OnboardingFlagTest.kt
This allow all onboarding flags to be reset. It is useful for testing, in order to avoid resetting AnkiDroid data. I also expect it may be useful for users if they want to see again everything, to either show the app to other people or just check whether they can learn new things.
I'd like a review from @ShridharGoel since it's your part of the code.
> Reset onboarding

- AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
- AnkiDroid/src/main/java/com/ichi2/libanki/Note.java
- AnkiDroid/src/main/java/com/ichi2/libanki/TagManager.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/Tags.java
- AnkiDroid/src/main/java/com/ichi2/libanki/TagsV16.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java
- AnkiDroid/src/main/java/com/ichi2/libanki/utils/PythonExtensions.kt
* We want `Collection` to return either a `Tags.java` or a `TagsV16.kt` to allow implementation of the Schema v16 upgrade
Related: #8988 
* Add an abstract class and have both implement the methods 
* Consolidate the interfaces, both on the Java and on the Kotlin
* Don't consolidate implementations, as we plan to remove `Tags.java`
* ⚠️ Untested, draft to ensure unit tests pass
`@JvmOverrides` doesn't work on abstract methods
> feat: add "TagManager" abstract class for V16 upgrade

- AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
- AnkiDroid/src/main/res/values/10-preferences.xml
- AnkiDroid/src/main/res/values/constants.xml
- AnkiDroid/src/main/res/xml/preferences_advanced.xml
Fixes #9265
- removed schedVerPreference from xml and included in java.
- showing schedVerPreference only if user is on V1.
- Added help button in confirmation dialog of v1-> v2 scheduler.
tested on local & emulator devices.
> Don't allow v2 to v1 conversion [Anki Ecosystem]

- AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
- AnkiDroid/src/main/java/com/ichi2/anki/CustomMaterialTapTargetPromptBuilder.kt
- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
- AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
- AnkiDroid/src/main/java/com/ichi2/anki/Onboarding.kt
- AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
- AnkiDroid/src/main/java/com/ichi2/ui/RtlCompliantActionProvider.java
- AnkiDroid/src/main/java/com/ichi2/utils/HandlerUtils.kt
- AnkiDroid/src/main/res/drawable/hand_icon.xml
- AnkiDroid/src/main/res/layout/card_browser.xml
- AnkiDroid/src/main/res/layout/deck_item.xml
- AnkiDroid/src/main/res/values/19-onboarding.xml
- AnkiDroid/src/main/res/values/colors.xml
- AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java
- AnkiDroid/src/test/java/com/ichi2/anki/HandlerUtilsTest.kt
Implement onboarding for new users.
https://user-images.githubusercontent.com/35566748/125170046-abfc1580-e1ca-11eb-948d-892f0053882a.mp4
> Implement onboarding for new users with feature tutorials

- AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java
Fix a bug causing "Add From Gallery" option missing from the note editor on Amazon Build Flavor
Fixes #9323
This has been tested on an emulator
> make "Add From Gallery" visible on Amazon Build Flavor

- AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
- AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
- AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
- AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.java
- AnkiDroid/src/main/java/com/ichi2/compat/CompatV29.kt
we need to access the saved whiteboard file in a drawing activity, but with the new scoped storage implementation we can't return the absolute path, Google doesn't want us to use absolute paths & wants us to use Uris instead.
> CompatV21 & V29 saveImage(): return Uri instead path

- AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupUnderBackupTest.java
In https://github.com/ankidroid/Anki-Android/pull/9130 we had a nullpointerexception in a test. A suggestion was made in the javadoc of the test. This ensure that the suggestion is directly shown if the test fail
> NF: improve activityHandlesRestoreBackup if create lead throws

- AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
- AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
- AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
- AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
- AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
- AnkiDroid/src/main/java/com/ichi2/anki/services/BootService.java
- AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
- AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
- AnkiDroid/src/main/java/com/ichi2/libanki/DecksV16.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
- AnkiDroid/src/main/java/com/ichi2/libanki/Models.java
- AnkiDroid/src/main/java/com/ichi2/libanki/ModelsV16.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
- AnkiDroid/src/main/java/com/ichi2/upgrade/Upgrade.java
- AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java
- AnkiDroid/src/test/java/com/ichi2/anki/DeckOptionsTest.java
- AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.java
- AnkiDroid/src/test/java/com/ichi2/anki/PreferencesTest.java
- AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.java
- AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.java
- AnkiDroid/src/test/java/com/ichi2/libanki/UndoTest.java
- AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java
- AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedUpgradeTest.java
- AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.java
- AnkiDroid/src/test/java/com/ichi2/testutils/AnkiAssert.java
We want to move from a JSONObject-based approach to accessing a table of configuration
Anki uses the following class:
https://github.com/david-allison-1/anki/blob/20432ccecf62f34860c99a24732cf6ba6abba6af/pylib/anki/config.py
To do this, we need an interface to access the collection. Anki uses `get_config` and `set_config`, the problem with these methods is that Anki uses `Any`, and we want strongly typed access.
Related: #8988 
* Define strongly typed methods
* Migrate all of AnkiDroid to use these methods
⚠️ All config changes now call `setMod`. `setMod` will be removed in a later version of Anki Desktop as it's no longer necessary. Since we're not on v16 yet, `setMod` still has an effect, but it's likely the effect that we wanted anyway (mark the collection as modified if a setting is) …
> feat: migrate from col.getConf() to config methods on `col`

- AnkiDroid/src/test/java/com/ichi2/anki/InitialActivityWithConflictTest.java
- AnkiDroid/src/test/java/com/ichi2/testutils/EmptyApplication.java
`EmptyApplication`: reset state so tests fail when run in a batch
This ensures that tests are not flaky
Running a test suite could set static state
This could mean that a test depending on `EmptyApplication` would pass
when run in a batch, but not individually (`testInitialActivityResult`)
Fixes test: `testInitialActivityResult` when run standalone
Fixes #9419
> fix tests[EmptyApplication] Reset static state

- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
crash cause by attend to calling null insertFieldDialogFactory,
because I was initialized insertFieldDialogFactory in only onCreate method of cardtempleteeditor 
and after coming back from the preview page to the editor page onCreate was not again called i.e the dialog factor was null.
Fixes #9442
> CardTemplateEditor: initialize insertFieldDialogFactory inside showInsertFieldDialog method

- AnkiDroid/build.gradle
All of these dependencies have version numbers in lockstep
Noticed from #9446 and #9447
> Use 'kotlin_version' variable for kotlin-reflect

- AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java
- AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.java
```IntentHandler``` wouldn't handle SYNC & REVIEW intents if storage permissions had not been granted to AnkiDroid. However, if the user data is stored in an app-specific directory (for eg: after the upcoming migration to scoped storage feature), then AnkiDroid doesn't need storage permissions to be granted in order to handle intents.
```IntentHandler``` uses ```performActionIfStoragePermission()``` to ensure that storage permissions have been granted before handling an Intent. We can alter the condition applied here so that an Intent is handled if one of the two following conditions are satisfied:
- AnkiDroid is using an app-specific directory to store user data
- AnkiDroid is using a legacy directory to store user data but has access to it since storage permission has been granted (as …
> Handle Intents under Scoped Storage

- AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.java
If AnkiDroid is using a non-app-specific directory to store user data and storage permission hasn't been granted, the Deck Import dialog appears over the DeckPicker startup dialog if an import is requested via an Intent. This allows the user to attempt to import the Deck when AnkiDroid can't access user data in the non-app-specific directory, resulting in a crash.
1. Fresh Install of AnkiDroid
2. Click on a deck from the device's files app
3. Click on Replace (See Image below)
In ```IntentHandler```, only allow the deck to be imported if one of the following two conditions have been met:
- AnkiDroid uses an app-specific directory to store user data which doesn't require storage permission
- AnkiDroid uses a non-app-specific directory to store user data, but has granted permission, and the …
> fix[Deck Import]: Check if storage is accessible before importing deck via Intent

- AnkiDroid/src/main/AndroidManifest.xml
- AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
- AnkiDroid/src/main/java/com/ichi2/anki/DrawingActivity.kt
- AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java
- AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java
- AnkiDroid/src/main/java/com/ichi2/anki/WhiteboardMultiTouchMethods.java
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java
- AnkiDroid/src/main/res/layout/activity_drawing.xml
- AnkiDroid/src/main/res/menu/drawing_menu.xml
- AnkiDroid/src/main/res/values/01-core.xml
- AnkiDroid/src/test/java/com/ichi2/anki/WhiteboardDefaultForegroundColorTest.java
- AnkiDroid/src/test/java/com/ichi2/testutils/ActivityList.java
Fixes #9363 
- created drawing activity
- extracted createInstance in a method of whiteboard
- change WeakReference<AbstractFlashcardViewer> to AnkiActivity in whiteboard to let other activities use whiteboard view.
- added drawing button in BasicImageFieldController
> Implemented Drawing Activity

- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
- AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.java
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.java
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportFileSelectionFragment.kt
- AnkiDroid/src/main/res/values/02-strings.xml
- AnkiDroid/src/main/res/values/03-dialogs.xml
- AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerImportTest.java
- AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.java
Suggested by @mindinsomnia 
Currently, selecting "Import" opens up a file picker, with no indication of what files can be imported.
* Display a dialog, displaying the types of files which can be imported
Tested on my Android 11
The "search" doesn't work on my Pixel - you can't select a deck if you perform a search while in the file picker. Not a regression, I'll add in an issue
> feat: Import file type selection

- AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.java
The bottom icon was a 50 degree rotation, instead of a 45 degree rotation. Visible as the plus was not level
Fixes #9485
> fix: FAB rotation

- AnkiDroid/src/main/res/drawable/ic_bar_chart_black.xml
- AnkiDroid/src/main/res/drawable/ic_equalizer_black.xml
- AnkiDroid/src/main/res/drawable/ic_flashcard_black.xml
- AnkiDroid/src/main/res/drawable/ic_search_black.xml
- AnkiDroid/src/main/res/menu/navigation_drawer.xml
From the issue:
* The 'Card Browser' icon (a magnifying glass) does not necessarily represent what the menu entails.
* The 'Statistics' icon is too thick as compared to every other icon
Fixes #9428
We reverse the 'bar chart' icon to make it closer to the equalizer icon (which will hopefully reduce complaints)
Due to this, it no longer fully matches the material icon
> feat: change nav drawer icons

- AnkiDroid/src/test/java/com/ichi2/anki/HandlerUtilsTest.kt
- build.gradle
also fixes a breaking lint change introduced by this PR regarding the ordering of `is` - going from first to last
Supersedes #9506 
----
Bumps ktlint-gradle from 10.1.0 to 10.2.0.
---
updated-dependencies:
- dependency-name: org.jlleitschuh.gradle:ktlint-gradle
dependency-type: direct:production
update-type: version-update:semver-minor
...
Signed-off-by: dependabot[bot] <support@github.com>
> build(deps): bump ktlint-gradle from 10.1.0 to 10.2.0

- AnkiDroid/src/main/res/drawable/ic_add_deck_filled.xml
- AnkiDroid/src/main/res/drawable/ic_add_note.xml
- AnkiDroid/src/main/res/drawable/ic_folder_white.xml
- AnkiDroid/src/main/res/layout/floating_add_button.xml
The FAB icons currently used do not necessarily represent interacting with a deck of cards (folder and + icon).
Fixes #9499 
The icons now accurately represent the options whenever the user is interacting with them.
This has been tested on the Physical Device - Redmi 9 Prime.
https://user-images.githubusercontent.com/77961530/133031381-15f16e98-41fb-4c41-a5e0-2de2a7f0b14c.mp4
> changed fab option icons to fit more to overall app theme

- AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
- AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.java
- AnkiDroid/src/main/res/values/02-strings.xml
- AnkiDroid/src/main/res/values/constants.xml
- README.md
- api/src/main/java/com/ichi2/anki/FlashCardsContract.java
- api/src/main/java/com/ichi2/anki/api/AddContentApi.java
Replaces all `http://anki*` URLs with HTTPS.
For most, this is simply best practise, but e.g., for the `resetpw`, this could negatively affect a user if the connection is initiated over http.
All URLs are available via `HTTPS`.
HTTP-URLs can be a security issue even if the http URL redirects to https on the server.
If is secure if the connection is already established, the connection is secure (assuming the server and client do not do anything wrong like disabling certificate checks)
But if an attacker is present on the network during the setup, he can just intercept the http-connection-setup, and forward that to their own server. Then you would never see the request on the server. This is not possible if the setup were already over https.
> Update anki URLs to use HTTPS by default 

- AnkiDroid/src/main/java/com/ichi2/anki/OnboardingUtils.kt
- AnkiDroid/src/test/java/com/ichi2/anki/OnboardingUtilsTest.kt
- AnkiDroid/src/test/java/com/ichi2/testutils/ReflectionUtils.kt
Noticed the build warning from Kotlin, investigated and cleaned it up, all non-functional
* public was not necessary
* use `edit { }` for shared preferences
* tests: add missing copyright header
* tests: remove typeof and ExperimentalStdlibApi
* tests: remove unused `ou` variable
* tests: extract "ensure init" to method
* tests: reword assertion
* tests: extract named varialbes for legibility
> refactor: onboarding

- AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
- AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.java
- AnkiDroid/src/test/java/com/ichi2/testutils/JsonUtils.kt
When compared to the V16 schema:
* "return" was missing
* "previewDelay" was 10
* "browserCollapsed" was false
I then ordered the resulting string, as that makes comparisons easier
This doesn't yet fix a unit test, there's one more change which will require a follow-on PR (pending performance discussion)
#8988
One unit test still passes. I'll let CI do the rest
* https://github.com/ankitects/anki/blob/1fe18718f7aa3b0e295b934f2130079635e86780/rslib/src/decks/schema11.rs#L61-L62
* https://github.com/ankitects/anki/blob/514c73f5478c151a65f0fbca3dd69a1d8c1a5631/rslib/src/decks/mod.rs#L61
* https://github.com/ankitects/anki/blob/1fe18718f7aa3b0e295b934f2130079635e86780/rslib/src/decks/schema11.rs#L94-L95
> Dynamic Decks: change properties to match V16 of the Rust

- AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.java
- AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilsTest.java
- tools/update-localizations.py
Issue #9550
Untested. Needs a translation sync before the content is visible in the app
> translations: add 'Sardinian' (ISO 'sc')

- lint.gradle
This lets you see build errors from lint right where you want them
Fixes #9553
Local runs, works
lintOptions are documented pretty well and they have a special stdout mode for text output:
https://developer.android.com/reference/tools/gradle-api/7.1/com/android/build/api/dsl/LintOptions
If you do `textOutput = "stdout"` it does not work. It complains it cannot cast String to File, so it is not recognizing it as the special stdout specifier somehow.
If you do `textOutput "stdout"` it works, because...of course.
> style(lint): report lint errors via text on stdout

- AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
- AnkiDroid/src/main/java/com/ichi2/libanki/CollectionV16.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/DB.java
- AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java
- AnkiDroid/src/main/java/com/ichi2/libanki/backend/DroidBackend.java
- AnkiDroid/src/main/java/com/ichi2/libanki/backend/JavaDroidBackend.java
- AnkiDroid/src/main/java/com/ichi2/libanki/backend/RustDroidBackend.java
- AnkiDroid/src/main/java/com/ichi2/libanki/backend/RustDroidV16Backend.kt
* We introduce a `CollectionV16` class which uses the `V16` classes for models/decks etc...
* We introduce a `RustV2SupportSQLiteOpenHelper` & `RustV2SQLiteOpenHelperFactory` which are Android-based abstractions. 
* The point is to call `openCollection`, which will have functionality changed in the next release to open + upgrade the collection
* This is the same behavior as Anki Desktop
* Introduce `RustDroidV16Backend` to combine the above. This class is unused for now, but will be added to `DroidBackendFactory` once a backend release is made
Related: #8988
> Add V16 collection classes

- AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
- AnkiDroid/src/main/java/com/ichi2/libanki/Models.java
- AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java
- AnkiDroid/src/test/java/com/ichi2/libanki/StorageTest.java
- AnkiDroid/src/test/java/com/ichi2/testutils/JsonUtils.kt
The test is still broken. This is going to require some refactoring work. This is the first stage.
We fix `conf` to match Anki Desktop and extract from an object array to a class
Open to opinions on whether this is a more readable approach
#8988
> compareNewDatabases: fixes for `conf` and `models`

- AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
- AnkiDroid/src/test/java/com/ichi2/anki/AnkiDroidJsAPITest.kt
- lint-rules/build.gradle
- lint-rules/src/main/java/com/ichi2/anki/lint/IssueRegistry.java
- lint-rules/src/main/java/com/ichi2/anki/lint/rules/KotlinMigrationBrokenEmails.kt
The Java -> Kotlin migration converts `<...>` into html tags if the comment is `/**` instead of `/*`
This often catches the copyright header of files, which is bad as it corrupts the emails in the copyright.
Pickup the email `<http:></http:>` and report this
> lint: kotlin conversion corrupting emails

- AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
- AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java
- AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java
- AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/SchedulerService.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
- AnkiDroid/src/main/java/com/ichi2/libanki/CollectionV16.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt
This extracts card rendering to Rust.
* extract return value to `TemplateManager.TemplateRenderContext.TemplateRenderOutput`.
* This now includes CSS, which is cached. This may be faster.
* We don't use `AvTags` which is now returned, this is pending from a follow-up PR
#5793
Fixed the unit tests which broke when using the new code. Neither is "well tested"
> feat(v16): Implement col.render_output via rust

- AnkiDroid/src/main/res/xml/preferences_advanced.xml
Currently, the user has to manually enable the "Focus 'Type in answer'" preference from the settings. We would want this to be a default behaviour. This PR resolves that. 
The layout attribute was changed to default = true.
This was manually tested in API 30. Data was deleted, the app was reinstalled to ensure that the default behaviour focuses on the FixedEditText in the Reviewer.
> [Preferences:Focus type in answer]Enable dy default

- AnkiDroid/src/main/java/com/ichi2/anki/ui/NoteTypeSpinnerUtils.kt
Fixes #9754
The error, I believe, was that the textview was recycled, which mean that we
need to reset the color.
Tested on my device. The problem disappeared. Tested in night and day mode, got
the correct color each time
> Ensure a single note type is highlighted

- AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.java
Currently, the deck spinner view in the Edit Note activity only displays the selected item in a single line.
When the name of the Deck is too long to be displayed in a single line, a part of it is not displayed. 
This means the user can not discern which deck is selected if multiple decks have same prefixes.
This PR fixes the issue by supporting multiline display of the selected item in the spinner's view.
Update: Use multiline_spinner_item instead of android.R.simple_spinner_item
~The getView method of the noteDeckAdapter is overridden to cast the spinner view to a textview, then setSingleLine(false) and return it.~
This was manually tested in API 30: Long Deck Names were selected and the spinner view was inspected to
display them in multiple lines. 
On the layout side, several things …
> [EditNote][DeckSpinner] Display long name

- AnkiDroid/src/main/res/layout/note_editor.xml
Currently, the deck spinner view is unable to display selected deck names which have
length extending beyond 2 lines. This PR fixes that issue and enables the Spinner view to display upto 5 lines, which is sufficient for all practical use cases.
Change spinner layout_height from "@dimen/touch_target" (=48dp) to "wrap_content"
Tested manually on API 30, Spinner View was verified to display selected deck names extending upto 5 lines.
1. After fiddling with multiline_spinner_item, it was concluded that this was not causing the issue. 
2. The fact that a little portion of the 3rd line was also visible indicated that the multiline_spinner_item was visible completely, but just did not have sufficient parent layout height.
3. Spinner layout height was changed to wrap_content, this solved the …
> [EditNote][DeckSpinner] Fix Layout Height

- AnkiDroid/build.gradle
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioRecorder.java
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioView.java
- AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
- AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.java
- AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.java
- AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.java
- AnkiDroid/src/main/java/com/ichi2/compat/CompatV29.kt
- AnkiDroid/src/main/java/com/ichi2/compat/CompatV31.kt
- AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/AudioRecorderTest.java
- AnkiDroid/src/test/java/com/ichi2/anki/reviewer/KeyboardShortcutIntegrationTest.java
- api/build.gradle
I want to unblock some of the dependencies that require minCompileSdk 31
Related #9768
Related #9726
Related #9725
- added new CompatV31 object to compat infrastructure
- handled MediaRecorder() ctor deprecation by threading Context through, adding new Compat method
- handled Context.VIBRATOR_SERVICE deprecation with recommended new APIs in CompatV31 override
Apologies it is all one commit, but it's hard to bump a build version and handle the deprecation in different commits, since the necessary symbols are not available until you bump the compile version, at which point you get a build failure with the deprecation. I suppose I could have marked it as ignore deprecation but seemed small enough to just go for it
Works for me locally with `./gradlew jacocoUnitTestReport :api:lintRelease …
> fix(android, api31): implement compileSdkVersion 31 compatibility

- AnkiDroid/build.gradle
- AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.java
- AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
- api/build.gradle
Not quite a standard dependency updates PR.
dependabot became quite confused on correct tree state for the PRs that needed minCompileSdk 31, despite my efforts on #9774 and push to the dependency updates branch
So I dug in there myself and did the pending / blocked dependency bumps, with two tweaks along the way to make it work
- just bump the versions
- tweak SharedDecksActivity so parameter nullability in method matches superclass so it is an override
- mark InputConnectionCompat deprecation and track in #9775 
Local `./gradlew clean jacocoUnitTestReport lintPlayRelease --rerun-tasks` 
The sun rises and sets every day, with a new deprecation to handle.
> Dependency updates 20211104

- AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
- AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.java
- AnkiDroid/src/main/java/com/ichi2/anki/VideoPlayer.java
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronounciationActivity.java
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/TranslationActivity.java
- AnkiDroid/src/main/java/com/ichi2/themes/Themes.java
- AnkiDroid/src/main/res/values-v29/xiaomi-theme-overlay.xml
- AnkiDroid/src/main/res/values/xiaomi-theme-overlay.xml
Force Dark is an Android 10 feature, which commonly appears on MIUI 12
This forces a dark mode, even if the app doesn't support it.
We have a night mode, so don't need it
This causes many problems, as it does not invert Note Editor icons
causing questions about missing functionality
`android:forceDarkAllowed` fixes this, but is API 29+
To fix this, define a theme overlay, and apply it to all activities
Note: Setting a theme doesn't replace the current theme, just overriding the properties, so a second theme is an overlay
This removes the need to to duplicate the file for `values-29`
Fixes #8150
Redmi 8A. Copied the APK to storage and installed it to test.
https://developer.android.com/guide/topics/ui/look-and-feel/darktheme#force-dark
https://stackoverflow.com/questions/63047806/
Don't …
> fix(miui): disable "force dark" mode

- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.java
The selected deck item of the deck spinner is not highlighted in the deck selection dialog. This is inconsistent from the behaviour of the noteTypeSpinner and a design flaw. This PR fixes that issue by highlighting the aforementioned.
https://user-images.githubusercontent.com/81802035/140179674-ae7948d5-972a-4247-8a57-f64349b46c94.mp4
https://user-images.githubusercontent.com/81802035/140179691-a4c396ea-d8bc-46fb-8dcf-c58bebdc51d2.mp4
1. Retrieve the Spinner text, this is the name of the selected deck item.
2. In the RecyclerView DecksArrayAdapter, override OnBindViewHolder to compare the Spinner Text with the viewHolder's Item name(this would be the deck item in the RecyclerView of the DeckSelectionDialog).
3. If equal, highlight the textView item, else set default colors. 
This was …
> [EditNote][DeckSelectionDialog] Highlight Selected item

- AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
- AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
- AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.java
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsArrayAdapter.java
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.java
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialogListener.java
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsList.java
- AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
- AnkiDroid/src/main/java/com/ichi2/ui/CheckBoxTriStates.java
- AnkiDroid/src/main/java/com/ichi2/utils/TagsUtil.java
- AnkiDroid/src/main/res/drawable/ic_baseline_check_box_24.xml
- AnkiDroid/src/main/res/drawable/ic_baseline_check_box_outline_blank_24.xml
- AnkiDroid/src/main/res/drawable/ic_baseline_indeterminate_check_box_24.xml
- AnkiDroid/src/main/res/layout/tags_item_list_dialog.xml
- AnkiDroid/src/main/res/menu/card_browser_multiselect.xml
- AnkiDroid/src/main/res/values/attrs.xml
- AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogTest.java
- AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsListTest.java
- AnkiDroid/src/test/java/com/ichi2/utils/TagsUtilTest.java
Based on #8766
The final PR of the TagsDialog refactoring series :D, 
Fixes #4911
Tags that are checked in all selected notes will appear as checked, if some notes have a tag but others don't then the tags are classified as indeterminate.
A tristate checkbox ([Like this one in flutter](https://api.flutter.dev/flutter/material/Checkbox/tristate.html)) was needed to display the 3 states the tag can be (checked, unchecked, indeterminate).
I added a `cycleBackToIndeterminate` property on the tristate checkbox, so if the user clicked on the checkbox it doesn't cycle back to an indeterminate state.
Used icons are the provided material ones in android studio
The code used to extract the updated tags from (prev, selected, indeterminate) lists.
is now aware of the concept of indeterminate tags …
> feat: Edit tags of a multiple notes / deck

- AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java
- AnkiDroid/src/main/java/com/ichi2/anki/TtsParser.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt
Allows for inclusion of the libAnki TTS from a card template
Issue #5793
Letting CI handle this one
> refactor(v16): Use libAnki class for TTS

- AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
- AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java
- AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardHtml.kt
- AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/TTS.kt
- AnkiDroid/src/test/java/com/ichi2/anki/ReadTextTest.java
- AnkiDroid/src/test/java/com/ichi2/libanki/TtsParserTest.kt
Splits out the generation and reading of TTS
I have a follow-up commit which implements the Rust TTS tags, but I want it to be heavily unit tested (we currently have an "enable TTS" option, which then allows TTS to work (either read the card, or handle `<tts>` tags), and this interacts questionably with Anki, where TTS is only defined in the card template)
I'd like refactorings to go in before I add the tests.
This also splits out `TtsParserTest.kt`, which should ever so slightly speed up the tests (1ms test runs)
#5793
Trusting CI on this one
> refactor: TTS

- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/IMultimediaEditableNote.java
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioRecordingFieldController.java
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/impl/MultimediaEditableNote.java
- AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.java
- AnkiDroid/src/main/res/values/16-multimedia-editor.xml
* Display text of the fields from the note editor
This allows a user to better know what to say
* Images are not supported, only text
* Scrolling behaviour is incorrect, but unlikely to occur. It's not recommended (and difficult) to handle nested ScrollViews, so we'll need an alternative, probably moving the controls outside the standard linear layout
Fixes #5428
> feat(record-audio): Show Preview of Fields

- AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
- AnkiDroid/src/main/res/layout/my_account.xml
- AnkiDroid/src/main/res/values/04-network.xml
- AnkiDroid/src/main/res/values/constants.xml
Allow user the ability to click a link for instructions on how to find their AnkiWeb Account Email
Fixes #5844
This change adds a button on the login screen for the user to click to open up a web browser with instructions on how to find their AnkiWeb email. 
This was tested on a Pixel3A_API_31_arm64-v8a emulator with  SDK version: Android 12.0 (S)
> Changes for Issue 5844 - Forgotten AnkiWeb e-mail

- AnkiDroid/build.gradle
- AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/LayoutValidationTest.java
fix: androidx.appcompat.resources.R.layout no longer exists
Bumps appcompat from 1.3.1 to 1.4.0.
Fixes #9913 (superseded)
---
updated-dependencies:
- dependency-name: androidx.appcompat:appcompat
dependency-type: direct:production
update-type: version-update:semver-minor
...
Signed-off-by: dependabot[bot] <support@github.com>
> Bump appcompat from 1.3.1 to 1.4.0

- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
This crashes the card browser and statistics screen when changing
the selected deck.
Note: This is the spinner, not "Change Deck" functionality
reverts f96bdfbc1f756e6e7b61d404e50c3acd3f3d7716
Fixes #9914
Reverts #9765
Reopens #9755
> revert: Highlight Selected Deck (f96bdfb)

- AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtons.kt
it appears making them non-nullable is satisfactory for the build and test suite
Related #9921  /  #9926 
Examined class and superclass, superclass needed them non-null, so investigated if simply making them non-null in sub-class worked, it worked, so here we are...
`./gradlew clean jacocoTestReport --rerun-tasks` with an android emulator running
Really need the beta approval from github for the merge queue!
> fix: there was a nullability merge dispute in ActionButtons

- AnkiDroid/src/main/java/com/ichi2/anki/Info.java
- AnkiDroid/src/main/res/values/constants.xml
- There was dead code in the method _getAboutAnkiDroidHtml()_ in the  _`AnkiDroid/src/main/java/com/ichi2/anki/Info.java`_ which remains unused. #9525.
- The <_string name="link_translation">_ in the  _`AnkiDroid/src/main/res/values/constants.xml`_ which acts as a link uses **http** over **https**.
- Updated the method in the codebase _`AnkiDroid/src/main/java/com/ichi2/anki/Info.java`_ and removed the unused string <_string name="link_donation">_ from _`AnkiDroid/src/main/res/values/constants.xml`_  w.r.t #9525 .
- Updated the link in  _`AnkiDroid/src/main/res/values/constants.xml`_ to use **https** over **http** w.r.t #9400 .
Fixes #9525
- Updating the method _getAboutAnkiDroidHtml()_ in the  _`AnkiDroid/src/main/java/com/ichi2/anki/Info.java`_ to remove the dead code and removed the …
> Removed the unused string and updated the used link

- AnkiDroid/build.gradle
- api/build.gradle
_Bump robolectric from 4.7.1 to 4.7.3_
Fixes _https://github.com/ankidroid/Anki-Android/pull/9959_
_The new version(4.7.3) of robolectric jar fixes the issue of test pollution._
The build was successful and local testing.
_Links [to blog posts, patterns, libraries or addons used to solve this problem](https://github.com/robolectric/robolectric/releases)_
- [done ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [done ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [done ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [done ] You have commented your code, particularly in …
> Bump robolectric from 4.7.1 to 4.7.3

- AnkiDroid/src/main/java/com/ichi2/anki/model/WhiteboardPenColor.kt
Make SharedPreferences non-null in WhiteboardPenColor.
> Make SharedPreferences non-null in WhiteboardPenColor

- AnkiDroid/src/main/assets/changelog.html
According to a suggestion by @david-allison-1 over Discord, we can add a comment so that developers know that the actual changelog data is present only in the release branches.
> Add comment informing that the actual changelog is only in release branches

- AnkiDroid/src/main/java/com/ichi2/preferences/SeekBarPreferenceCompat.java
- AnkiDroid/src/main/java/com/ichi2/ui/SeekBarPreference.java
Fixes #9947
On non-touch device (e.g. Android TV), it was not possible to save the parameter value for a seek bar.
Behavior before the fix:
Persist the seek bar value  with onProgressChange instead of onStopTrackingTouch.
Behavior after the fix: 
Tested as in the gifs above, for the seek bars:
- "Card zoom" (in the review settings) to test SeekBarPreferenceCompat
- "Time to show answer" (in the deck options) to test SeekBarPreference
with virtual devices 
- Android TV Android 10
- Pixel 5 Android 11
=> Not needed in my opinion, please let me know if you think otherwise.
=> See the gif above for an example (all the other are similar).
=> There is a suggestion, but unrelated to the change.
> fix: persist seek bar value on change

- AnkiDroid/src/main/java/com/ichi2/anki/web/PreferenceBackedHostNum.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/sync/HostNum.java
- AnkiDroid/src/test/java/com/ichi2/anki/web/HostNumFactoryTest.kt
Cause: 2c63ef387f85f96510db3e8bbd8326491e90333c
Login crashed
Fixes #10102
* Marked `getDefaultHostNum()` as `nullable`: default value is null
* Fix the compile errors this generates in `PreferenceBackedHostNum`
⚠️ Only unit tested
> fix: Login crashing

- AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.java
A silent crash dialog was displayed 
The stack trace points to Context being null here.
Fixes (Maybe) #10108
Use `context` which is passed into the method, rather than `getBaseContext()`
⚠️ Could not reproduce the issue, maybe phone-specific
Installed, used widget and restarted my phone, 
----
> fix(widget): maybe fix displaying crash dialog

- AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.kt
- AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.kt
default is 10f for font so it works as the backup in case of null
Just trying to fix the build - `./gradlew clean jacocoTestReport --rerun-tasks` works locally after this
> fix: param named views, optional, and send collection to newInstance optionally

- AnkiDroid/src/main/java/com/wildplot/android/rendering/DrawableContainer.kt
- AnkiDroid/src/main/java/com/wildplot/android/rendering/interfaces/Drawable.kt
This was obtained by reverting DrawableContainer translation and retranslating
it.  The translation result was different. Probably because Drawable was already
translated.
I believe a general rule here should be that we should not translate a child
class until its parents are translated.
Fixes #10173
> Ensure that both Drawable kt are compatible

- AnkiDroid/src/main/java/com/ichi2/preferences/NumberRangePreference.kt
Caused by bad override of `getPersistedString`. Java was `String` which was nullable
Fixes #10176
I attempted a unit test for this, but there are internal issues. (see #10175). These issues should be resolved after the activity is converted to use the new
Preference Fragment style
Manually, no longer crashes
We need tests on `DeckOptions`
> fix: DeckOptions crash

- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/AudioField.kt
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/IField.java
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/TextField.kt
- AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivityTestBase.java
- AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/fields/BasicAudioClipFieldControllerComplexTest.kt
Crashed when opening screen
Fixes #10179
Nullability issue when converting from Kotlin:
audioPath is nullable in `IField`. Fix this in `IField`
Manual + Unit
> fix: crash when opening audio recording

- AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java
this test is strongly desired - I wish it worked - but it never works locally for me
this is a serious impediment to me doing PR merge + compile checks as an automated series
Just disable the test
Locally - it failed every time locally with `./gradlew jacocoTestReport`, then the full suite passes after disabling it
Tests that depend on layout are really problematic. On device tests in general are really problematic, it's hard.
> test(connected): ignore flaky test completely

- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java
- AnkiDroid/src/main/res/values/02-strings.xml
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplatePreviewerTest.java
In anki desktop when we preview the card Template with all the note fields as null, it shows up card labels as field texts.
Fixes #9696 
A bool variable has been taken which takes care whether the preview is from the note editor or the card template editor.
if the flow is cardtemplate editor -> cardtemplatepreviewer then we add  `(` and `)` before the fields being set as anki desktop does
there were two exceptions the cloze and basic (answer type) so accordingly the fields have been modifies as same as anki desktop.
Tested on my phone only.
https://user-images.githubusercontent.com/46752548/140165774-1db7398b-04a8-4559-91c6-f376c441d351.mp4
> anki_eco: card previewer shows fields labels if all fields are null.

- docs/kotlin-migration.md
Some details were not clear during my first try of this feature.
In particular, I didn't have the "commit" window. Instead I had a different
non-modal window, which did not offer as many option. So I had to explain how to
get the modal window.
I also added instructions about what to do if build fail, at the place where we
expect failure.
I also added sub-sections. This way, if the process fail, it's easier to know
where we are.
> NF: Add more details to Kotlin Migration

- AnkiDroid/src/main/java/com/ichi2/libanki/Consts.java
- AnkiDroid/src/main/java/com/ichi2/libanki/Media.java
- AnkiDroid/src/main/java/com/ichi2/libanki/sync/MediaSyncer.java
Those two constants are from rslib/src/media/sync.rs originally, line 36.
The change will allow for the next developper who want to comparea nkidroid and
anki to find the equivalent constant quickly.
> NF: change constant name for consistency with anki

- AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractDeckTreeNode.java
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckDueTreeNode.java
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckTreeNode.java
This will allow #10148 to migrate to Kotlin with all of the override methods
noted as not null
> NF: withChildren takes `@NonNull`

- AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.java
Creates a test to close the issue #9461. The test exercises the code which caused the issue #9401.
Creates a test noErrorShouldOccurIfSoundFileNotPresent() which exercises the code which cause issue #9401 through the `Reviewer.class`.  
The test adds a name of the  sound file that does not exists, then exercises the code through `Reviewer.class`. 
To test this I removed the changes made in pull request #9407 which fails the test as it should. After adding the changes made in pull request #9407 the test passes as it should.
> Added test noErrorShouldOccurIfSoundFileNotPresent()

- AnkiDroid/src/main/java/com/ichi2/libanki/sched/LrnCardQueue.kt
1. Fix Nullability, non-null instead of nullable
2. Kotlin stdlib sort() instead of Java Collections static sort()
package: com.ichi2.libanki.sched
Migration PR: https://github.com/ankidroid/Anki-Android/pull/10129
> [Kotlin Migration][FollowUp] LrnCardQueue

- AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
I had issues where the collection path for a test did not match
my expected values. I believe that this is due to CollectionHelper
keeping an old instance of the collection around.
This resolves my issues, and maybe fixes a few flaky tests
CI is faster than my machine, so I'll see if this breaks anything
> fix(tests): Ensure tests use new collection

- AnkiDroid/src/main/java/com/ichi2/preferences/ConfirmationPreferenceCompat.kt
- AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt
- AnkiDroid/src/main/java/com/ichi2/preferences/IncrementerNumberRangePreferenceCompat.kt
- AnkiDroid/src/main/java/com/ichi2/preferences/NumberRangePreferenceCompat.kt
- AnkiDroid/src/main/java/com/ichi2/preferences/ResetLanguageDialogPreference.kt
`preference-ktx 1.2.0` adds new nullability annotations which breaks our Kotlin code
Unblocks issue #10278
Letting CI handle this one. Build, but not tests were checked
> fix: nullability of Preference classes

- AnkiDroid/src/test/java/com/ichi2/testutils/FileSystemUtils.kt
From StackOverflow: https://stackoverflow.com/a/13130974/
Used to print a directory tree to the console to allow for easy comparison of directories
Currently has no uses. I use this in scoped storage tests
> feat(tests): printDirectoryTree

- AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
- AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt
enable html/js debugging only for debugging and not for tests
Fixes #9751
check for org.junit.Test class being imported.
All CI's passing in my fork.
used timber logging to verify isDebug is true during normal run in avd and false when running unit/android tests.
[stackoverflow](https://stackoverflow.com/questions/28550370/how-to-detect-whether-android-app-is-running-ui-test-with-espresso)
- [ X ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ X ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ X ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ X ] You have performed a self-review of your own code
> Disable "html_javascript_debugging" for unit/android tests

- AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
Nicer to read + type than `getPreferences().edit { }`
Test-only. Currently unused, to be used in scoped storage changes
> test: add "editPreferences" helper function

- AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
App crashed when showing toast when JS API version not matched.
Fixes #10291 
Call the `showThemedToast` function in `runOnUiThread`
Tested on device.
https://developer.android.com/reference/android/app/Activity#runOnUiThread(java.lang.Runnable)
> fix: error when showing toast

- AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ACRATest.java
- AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/CollectionTest.java
- AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/DBTest.java
- AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/HttpTest.java
- AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/ModelTest.java
- AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/RetryRule.java
#10327 pointed out there were missing copyright headers in androidTest directory, mostly mine
@david-allison-1 we should merge this then you should rebase #10327 on it I think?
- I added my copyright header where missing
- one object was from @timrae but all his other work has been with the headers, seems sensible to add this one
- @Arthur-Milchior had one object (ModelTest) added in 2020 missing header, I copied a different header from him from 2020 and added it
They are code comments
Managing copyright is a PITA
> chore(copyright): add copyright headers to androidTest files

- AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioClipFieldController.kt
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioRecordingFieldController.java
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicControllerFactory.kt
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicMediaClipFieldController.kt
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicTextFieldController.kt
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/EFieldType.kt
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/IFieldController.kt
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/MediaClipField.kt
- AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
- AnkiDroid/src/main/java/com/ichi2/utils/ExceptionUtil.kt
- AnkiDroid/src/main/res/values/16-multimedia-editor.xml
- AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/fields/BasicMediaClipFieldControllerComplexTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/fields/BasicMediaClipFieldControllerTest.java
- AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.java
.mp4s could not be imported
Fixes #10315
* Rename `AudioClip` -> `MediaClip`
* Add button for "Video": accept `video/*`
* Fix bug in extension parsing
* Fix a few `KotlinCleanup`s
I attempted a new controller, but it wasn't easily possible to decide which controller to open if we encounter a field with `[sound:` in it.
Android 11 Pixel 3a
> feat(media-import): Import video

- AnkiDroid/src/main/res/values/10-preferences.xml
- AnkiDroid/src/main/res/xml/preferences_gestures.xml
Replaced with a general keymapping in "Settings - Controls"
Ref: dc6459f84b4c0fceb771a96aa04cdb6a46e13d4a
Fixes #10336
Pixel 3A, setting no longer appears
> remove: Volume Gesture Option (replaced)

- AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
_Fix regression_
Fixes #10339 
- Tried to make sure the buttons were disabled by temporarily hardcoding it -> Android Studio preview showed it correctly, but when emulating it appeared enabled
- Guessed it was a font color/theme problem
- Set the preferences theme when creating it
1. Go to settings -> Gestures
2. Disable gestures
3. See if disabled options are greyed out
> Fix disabled gestures still appearing

- AnkiDroid/src/main/java/com/ichi2/async/Connection.java
- AnkiDroid/src/main/res/values/04-network.xml
An error was shown (fixed in this commit):
`Multiple substitutions specified in non-positional format of string resource string/sync_media_partial.`
Issue #10347 - not fixed
Fixed via adding positional arguments
Update string to force re-translation:
`sync_media_partial` => `sync_media_partial_updated`
Introduced in c905ddbbeb96bde59ad66b3b36d94e2a43b6cd3a
Untested
> fix(strings): missing positional arguments

- AnkiDroid/build.gradle
- AnkiDroid/src/main/java/com/ichi2/anki/model/DiskFile.kt
- AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MigrateUserData.kt
- AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveFile.kt
- AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/model/DiskFileTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MockMigrationContext.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveFileTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/Utils.kt
- AnkiDroid/src/test/java/com/ichi2/testutils/FileSystemUtils.kt
- AnkiDroid/src/test/java/com/ichi2/testutils/FileUtil.kt
- AnkiDroid/src/test/java/com/ichi2/testutils/TestException.kt
When performing a scoped storage migration, we need to move user data in a background task, to ensure that a user will not be incentivised to uninstall the app when a slow migration is taking place.
We need to preempt this operation, for example to display files in the reviewer which have not yet been copied
We are very likely to be copying files across mount points, so `.renameTo` won't work, and we need to perform a manual copy.
This PR produces:
* `DiskFile` - an abstraction over `File` which must exist (and be a file) - name TBC
* `MigrateUserData` - holder for general concepts within user data migration
* `MigrationContext` - Progress reporting, and allows logic based on exceptions occurring during an operation
* `Operation` - An atomic unit of work, these should be small to allow …
> feat(scoped-storage): User data migration infra & safely move file

- AnkiDroid/src/main/assets/flashcard.css
- AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java
SVG types of the audio replay button were different in Anki Desktop and AnkiDroid, thus any CSS style changes made on Anki were not visible on AnkiDroid. 
Fixes #10343 
changed class name of button from `replaybutton` to `replay-button` to be compatible with anki desktop button styling.
changed SVG type from `<polygon>` to `<circle><path>` as defined in anki desktop to be compatible.
This allows any change in CSS styling of the replay button on Anki to be visible on AnkiDroid as well.
Tested on my phone: Xiaomi Redmi Note 8 Pro; Android 9; API 28
```
.replay-button svg {
width: 20px;
height: 20px;
}
.replay-button svg circle {
fill: blue;
}
.replay-button svg path {
stroke: white;
fill: green;
}
```
> Changed SVG type and name of `replaybutton` in order to be desktop compatible

- AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
- AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/CustomToolbarButton.kt
- AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
- AnkiDroid/src/main/res/layout/note_editor_toolbar_add_custom_item.xml
- AnkiDroid/src/main/res/values/02-strings.xml
- AnkiDroid/src/test/java/com/ichi2/anki/servicemodel/PreferenceUpgradeServiceTest.kt
The Note Editor toolbar add new items as number from 1...N, so I created this PR for adding string / single character as icon for the new items. It helps in recognize the button instead of memorizing button action with the number. 
Fixes #9077
> 3. Allow me to change the naming of custom buttons
1. I have added new variable `icon` after `index`. 
2. Earlier buttons saved in SharedPrefs as `index, prefix and suffix`. 
Now when new buttons added it saved to SharedPrefs as `index, icon, prefix and suffix`
Test on Emulator on device
_Links to blog …
> Note editor toolbar new item string as icon

- AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
- AnkiDroid/src/main/res/drawable/ic_popup_menu_item_video.xml
- AnkiDroid/src/main/res/menu/popupmenu_multimedia_options.xml
Adding an explicit `Add video clip` button to the Note Editor popup multimedia menu, which does the same thing as `Add audio clip` button. 
Fixes #10212 
AnkiDroid supports adding video clips to notes, but through the `Add audio clip` button. Adding an explicit button for video clips that does the same thing as `Add audio clip` is the first step in splitting out the functionality between audio and video. 
The approach used was:
1. Creating a vector icon for the button. 
2. Creating a string for `Add video clip` in `AnkiDroid/src/main/res/values/16-multimedia-editor.xml`
3. Adding the button as an item in `AnkiDroid/src/main/res/menu/popupmenu_multimedia_options.xml` with the same ID as `Add audio clip` to get the same functionality.
1. UI change in Note Editor:
2. Video showing …
> Explicitly Add Video Clips in Note Editor [issue #10212]

- AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectory.kt
- AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveFileOrDirectory.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveFileOrDirectoryTest.kt
- AnkiDroid/src/test/java/com/ichi2/testutils/FileSystemUtils.kt
- AnkiDroid/src/test/java/com/ichi2/testutils/FileUtil.kt
In scoped storage migration, we need to move specific directories to a new location in the background.
We need to preempt the operation, breaking it into atomic chunks allows us to do this
#5304 
High-level Operation class, allowing a directory to be recursively moved while handling non-fatal operations and preemption
Unit Tested only
> feat(scoped-storage): MoveDirectory

- AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.java
When pasting into the editor, the text appeared formatted to the user, even though it was being stripped when saved. This is an inconsistency between what is displayed to the user and what is saved. 
Fixes #10349 
IMP: **This approach works only for devices running versions >= M**
I catch the `paste` action using `onTextContextMenuItem()`, and change the action to `pasteAsPlainText` before the pasting is done. This way, the text that is pasted is stripped before it is pasted. 
Tested on my phone: Xaomi Redmi Note 8 Pro API 28 (Android 9)
https://stackoverflow.com/a/45319485
> Text pasted into Note Editor is now plain text by default

- lint-rules/src/main/java/com/ichi2/anki/lint/IssueRegistry.java
- lint-rules/src/main/java/com/ichi2/anki/lint/rules/NonPositionalFormatSubstitutions.kt
- lint-rules/src/main/java/com/ichi2/anki/lint/utils/Aapt2Util.kt
- lint-rules/src/test/java/com/ichi2/anki/lint/rules/NonPositionalFormatSubstitutionsTest.kt
AAPT displayed these issues as build as warnings, but they did not break CI
Fixes #10347
So, add some lint to make sure this occurs.
We take AAPT's C++ code and convert it to Kotlin.
Errors looks like:
```
AnkiDroid\src\main\res\values\04-network.xml:84:
Multiple substitutions specified in non-positional format.
Convert "%s" to "%1$s"
[NonPositionalFormatSubstitutions from com.ichi2.anki.lint]
```
Unit tested
Tested on commit d39249805081d18d1cf05178874608d161ae5a7a (failed)
https://cs.android.com/android/platform/superproject/+/master:frameworks/base/tools/aapt2/util/Util.cpp;drc=fbb7fe0da32896a871dd395845f1f510b075f8d5
> feat(lint): Verify Positional Format Strings

- AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectory.kt
- AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveFile.kt
- AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveFileOrDirectory.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveFileOrDirectoryTest.kt
I know explicitly state that in MoveFile and MoveDirectory, the destination is
the actual new path of the file/directory. (And not the directory where the
copied element will be)
For the sake of consistency, I change MoveFileOrDirectory so that its
destination is also the new path (and not the path of the directory containing
the copied file).
I discovered it while trying to make more specific test, where the
source/destination of elements were asserted. Those test are now committed too.
> NF: MoveFileOrDirectoryTest consistent with other Move

- AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MigrateUserData.kt
- AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveFile.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveFileTest.kt
That used to crash the app/test, because contentEquals require both files to be
either null or actual files (and not directory)
> MoveFile deal with destination which is a directory

- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/DeleteEmptyDirectoryTest.kt
This ensure consistency with other classes.
It was part of #10376. Splitted into its own PR for simplicity of review
> NF: rename context to executionContext in DeleteEmptyDirectoryTest

- AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.kt
- AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
- AnkiDroid/src/test/java/com/ichi2/anki/BackupManagerTest.java
Fixes #8897
1. Remove backup creation in `CollectionTask.java` after backup restoring
2. Remove `BackupManager.kt` `force` parameter since it isn't used anymore
3. Fix `BackupManagerTest.java`
Phone: Samsung Galaxy Note 10 Lite SM-N770F/DS, API 30
https://user-images.githubusercontent.com/69634269/154801101-a3b986d6-ead3-4570-9394-ea302d01fcdf.mp4
> Don't create backup after restore

- AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
- AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.java
- AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.java
- AnkiDroid/src/main/java/com/ichi2/compat/FileStream.kt
- AnkiDroid/src/test/java/com/ichi2/compat/DirectoryContentTest.kt
This method returns an iterator over directory content as File.
Starting at API 26, this uses [Files.newDirectoryStream], ensuring that all
operations are constant time and space. For lower API, it simulates this method
using `listFiles`, whose space and time are linear in the number of file of the directory.
This is a first commit created to factorize more the MoveDirectory operation
> NF: add contentOfDirectory method

- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/DeleteEmptyDirectoryTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveFileOrDirectoryTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveFileTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/OperationTest.kt
It depends on #10382 and #10383 and was originally a part of #10376
It ensures that we have a single implementation for `execute` and that all methods called `execute` do the same thing (at least in this test package)
> Factorize execute

- AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
- AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.java
- AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.java
- AnkiDroid/src/test/java/com/ichi2/compat/DirectoryContentTest.kt
This was the case in #10358 due to a permission issue with newDirectoryStream.
In this case, `listFiles` returned null. In this case, throwing makes more sens,
as it indicates that something was wrong.
UI will need to catch it eventually and ask to contact AnkiDroid developer for
help, because when this occurs there is nothing the app can do anymore.
> `contentOfDirectory` may throw

- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
- AnkiDroid/src/test/java/com/ichi2/anki/dialogs/DeckSelectionDialogTest.kt
As described in #10378, the way decks are currently displayed in the "Deck Search" subscreen is not intuitive nor easy to understand, especially with multiple subdeck levels. This PR aims to make it more user friendly by indenting decks the same way as the main "Deck Viewer" screen.
EDIT: Also added a test for the same. 
I feel the code can be better formatted and commented.
Fixes #10378 
instead of displaying the entire deck path, now only the subdeck name is displayed along with appropriate indentation. Deck and subdeck creation works just like before.
Video showing creation of subdecks:
Video showing search capability:
https://user-images.githubusercontent.com/86671025/155478620-26e90d7c-cab6-4425-93a3-55ee93fd7405.mp4
Emulator:
Pixel 5 API 32
Device:
Xaomi Redmi Note 8 Pro API 28 …
> "Deck Search" display now same as the Deck Viewer

- AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java
- AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java
- AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/GestureProcessor.kt
- AnkiDroid/src/main/res/values/10-preferences.xml
- AnkiDroid/src/main/res/values/constants.xml
- AnkiDroid/src/main/res/xml/preferences_reviewing.xml
- AnkiDroid/src/test/java/com/ichi2/anki/ReviewerNoParamTest.java
Add two options reduce flicker on e-ink devices:
1) Shrink answers bar (50%, 25%, etc)
2) Hide answers bar completely (but keep review count, toolbar, etc. enabled)
1) A smaller bar causes less noticeable flashing (less screen to refresh)
2) No white->black->white flashing at all
Hardware used:
- android emulator (api 31) 
- Onyx Boox Leaf
Tested reducing button height.
Tested hiding answer buttons.
Tested unable to hide buttons if gestures are disabled.
> Additional answer button tweaks (useful for e-ink)

- AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.kt
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportFileSelectionFragment.kt
- AnkiDroid/src/main/res/values/03-dialogs.xml
- AnkiDroid/src/test/java/com/ichi2/anki/BackupManagerTest.java
Backup options were backup name files, which isn't human-readable
Fixes #10362
- Refactor part of `BackupManager.kt` in order to work properly and be more clear
- Other parts of it still need refactoring, but probably are best suited in another PR
- Parse the backup filenames as localizable time strings
- Add a `Choose another` button, so the user can import backups which are not on backups folder
https://user-images.githubusercontent.com/69634269/155613612-830cabeb-343f-4b88-8950-8aa5db3062a1.mp4
https://user-images.githubusercontent.com/69634269/155613828-7c6fca48-3db0-4808-ae91-b8af973e73a6.mp4
> Localize backups date and add Choose another button

- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
- AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java
- AnkiDroid/src/main/java/com/ichi2/async/Connection.java
In some cases, even if user has access to the AnkiDroid server, AnkiDroid says "You are offline" and doesn't allow to connect to the server at all.
Fixes #9961 
Added the `Try Anyway` button just like the one present for syncing, so that AnkiDroid tries to attempt to connect before reporting any failure. 
Also changed variable name from `setAllowSyncOnNoConnection` to `setAllowLoginSyncOnNoConnection` in accordance with the updated implementation. 
https://user-images.githubusercontent.com/86671025/156182520-47d7b10c-98bd-4c94-abbd-d2200990bd85.mp4
Emulator:
Pixel 5 API 32
Device:
Xaomi Redmi Note 8 Pro API 28 (Android 9)
> Added `Try Anyway` button for login screen

- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
- AnkiDroid/src/main/java/com/ichi2/utils/SyncStatus.kt
Fixes #7326, Fixes #10394
- Only add the option if the user is logged in
- Be unlogged
- Use a collection.anki2 with a scheme newer than 11 (from Anki desktop)
- Open the app
Result:
With no backups on backups folder, did the following:
https://user-images.githubusercontent.com/69634269/156079204-ed1e84ef-edde-4204-a429-a1d68ad11428.mp4
Did the same processes logged and the `Full sync from server` option shows accordingly
> Don't show `Full sync` option if not logged on database error dialog

- AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/MediaTest.java
- AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java
- AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/Media.java
- AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.java
Keep the selected images original file names or appends its checksum in it if not unique, like Anki desktop does.
Fixes #9116 
- Most of the descriptions is [here](https://github.com/ankidroid/Anki-Android/issues/9116#issuecomment-1035609316). 
- To update the `<img>` tag I just put the field media import before text formatting, so it's possible to update the `ImagePath` at [importMediaToDirectory()](https://github.com/BrayanDSO/Anki-Android/blob/keepImgNames/AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt#L171) if changed.
- Stopped using [saveMedia()](https://github.com/BrayanDSO/Anki-Android/blob/keepImgNames/AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt#L122) because it doesn't make sense to loop all fields just to save the edited one.
Couldn't …
> Keep image file names

- AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
- AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.java
- AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.java
- AnkiDroid/src/test/java/com/ichi2/compat/DirectoryContentTest.kt
I wanted to ensure that there is a method that check whether we use the expected
exception for absent file depending on the API. So I decided to extend Compat
and CompatHelper for tests and use it to simplify a test. It'll be used again in
other PR which need to deal with missing files, in particular ensuring hasFile raises
> `hasFile` throw FileNotFoundException instead of NoSuchFile

- AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/MediaTest.java
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicMediaClipFieldController.kt
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/MediaClipField.kt
- AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/Media.java
- AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/fields/BasicMediaClipFieldControllerTest.java
- AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.java
Fixes #10419
1. Fix outdated/broken behaviors
- MediaClipField files weren't being deleted
- The illegal chars on media names were outdated
2. Cache temporary audio files (like the ImageField behavior) and keep their names
3. Updated the field preview
- i.e. the text added after confirming the file selection, below the `AUDIO` and `VIDEO` buttons (0:06 on the procedure video)
5. Make tests to guarantee cached temporary files deletion and audio importing with same name
6. Cleaned unused functions/variables
Tested on my phone (Samsung Galaxy Note 10 Lite SM-N770F/DS, API 30)
Procedure:
https://user-images.githubusercontent.com/69634269/156594640-dc006633-a7da-4943-9c17-b3a292687a9d.mp4
_Please, go through these checks before submitting the …
> Do not make a copy when reattaching the same audio or video file

- AnkiDroid/src/main/java/com/ichi2/anki/model/Directory.kt
- AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/DeleteEmptyDirectory.kt
- AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
- AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.java
- AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.java
- AnkiDroid/src/main/java/com/ichi2/compat/FileStream.kt
- AnkiDroid/src/test/java/com/ichi2/anki/compat/CompatHasFilesTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/model/DirectoryTest.kt
The primary goal how this commit is to have a clear way to catch #10358.
This PR depends on #10400 and #10418
It changes the way the method behaves when method assumption are not satisfied;
and raising an exception seems at least as acceptable than returning null. Plus
it will lead to more specific error cause if we care about them.
> `hasFiles` raises exception

- AnkiDroid/src/main/java/com/ichi2/anki/AnkiSerialization.kt
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/TranslationActivity.kt
Return non-nullable `ObjectMapper` from `AnkiSerialization` and utilize Kotlin lazy delegate
Previous tests should be enough.
https://kotlinlang.org/docs/delegated-properties.html
> use lazy delegate to create non-nullable ObjectMapper

- AnkiDroid/build.gradle
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt
- AnkiDroid/src/test/java/com/ichi2/libanki/CardTest.kt
- AnkiDroid/src/test/java/com/ichi2/testutils/AnkiAssertKt.kt
- lint-rules/src/main/java/com/ichi2/anki/lint/IssueRegistry.java
- lint-rules/src/main/java/com/ichi2/anki/lint/rules/JUnitNullAssertionDetector.kt
It was mentioned that we could improve `assertNotNull` to enforce non-nullability in the Kotlin type system via use of contracts.
Fixes #10427
* Depend on `kotlin-test`
* Use either a bare `assertNotNull` or `JUnitAsserter` if there is a `message` argument
* Fix up changes with `JUnitAsserter`
* removed `toLong` calls
Test Only + lint works
https://kotlinlang.org/api/latest/kotlin.test/
* args are in the other order (assertion, THEN the message)
https://kotlinlang.org/api/latest/kotlin.test/kotlin.test.junit/-j-unit-asserter/
* no `AssertFalse`
* `assertEquals` doesn't work between int and longs 
https://www.baeldung.com/kotlin/contracts - unstable, but in use in some libraries, and interesting. I expect it'll be another incremental improvement when stable.
> feat(kotlin-test): assertNotNull

- AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.kt
- AnkiDroid/src/test/java/com/ichi2/testutils/Backup.kt
Allows for testing the migration of backups
Currently only supports a single backup being created
Low-risk test-only code. Not tested (or used) yet.
> feat(tests): Utility to create backup

- AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ScopedStorageService.kt
- AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MigrateUserData.kt
- AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveFile.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/ScopedStorageServiceTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MigrateUserDataJvmTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveFileTest.kt
Pushing things forward more, this adds:
* Preferences which will be stored when a scoped storage background migration is in progress
* Failure cases for these preferences
* Preparing to have `MigrateUserData` inherit from `TaskDelegate - allowing it to be run in the background
#5304 
Unit tested
> feat(scoped-storage): Prefs & Construct MigrateUserData

- AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContent.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContentTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/OperationTest.kt
This PR adds an operation that allow to move the content of a directory.
It's a step toward creating "MoveDirectory" with atomic operations starting on API O. It requires PR ~~#10369, #10372, #10373, #10374~~ (all merged) and #10376
> Operation: Move content of a directory

- AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.java
- AnkiDroid/src/test/java/com/ichi2/compat/DirectoryContentTest.kt
This simulates https://github.com/ankidroid/Anki-Android/issues/10358
I'm not happy with the introduction of `mNewDirectoryStream` but have no other idea to force this method to throw. Any improvement welcomed. Otherwise, when this is merged, I'll ensure that similar tests are used with all methods that indirectly uses `contentOfDirectory` such as `asFile` and `MoveContentOfDirectory`
> NF: add test for contentOfDirectory for file access exception

- AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.kt
- AnkiDroid/src/test/java/com/ichi2/anki/BackupManagerSimpleTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/BackupManagerTest.kt
I aim to use this to obtain the latest backup and store it for safekeeing a the start of scoped storage migration.
I feel splitting functionality like this keeps things moving.
This also includes a perf refactor, shaving 5s off our Unit Test run.
#5304
Unit tests added
> feat(backups): getLatestBackup

- AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectory.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContentTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/OperationTest.kt
This commit ensure that, starting at API 26, Operation uses a stream instead of a list of directory.
It uses the same set of tests than previous `MoveDirectory`.
Edit: it's entirely rewritten. It depends of 10375
> Move file stream

- AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckDueTreeNode.kt
- AnkiDroid/src/test/java/com/ichi2/anki/AnkiDroidJsAPITest.kt
- AnkiDroid/src/test/java/com/ichi2/libanki/CardTest.kt
- AnkiDroid/src/test/java/com/ichi2/libanki/CollectionPersistentTest.kt
- AnkiDroid/src/test/java/com/ichi2/libanki/StorageTest.kt
That was due to porting from java, as previously  it was `getCol`
> NF: remove `val col = col`

- AnkiDroid/src/test/java/com/ichi2/compat/CompatDirectoryContentTest.kt
- AnkiDroid/src/test/java/com/ichi2/compat/CompatHasFilesTest.kt
It depends on #10438
It can already be merged. I plan to do similar test with MoveDirectoryContent once I know how to deal with the fact that it uses compat from compat helper
> Permission exception for `hasFile`

- AnkiDroid/src/test/java/com/ichi2/anki/HandlerUtilsTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/OnboardingUtilsTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/dialogs/DeckPickerContextMenuAndroidTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/dialogs/DeckPickerContextMenuTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/dialogs/RecursivePictureMenuAndroidTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/dialogs/RecursivePictureMenuTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/dialogs/RecursivePictureMenuUtilTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/AudioRecorderAndroidTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/AudioRecorderTest.kt
I check for each robolectric and RunWith AndroidTest which are required and splitted classes when it is possible so that some tests are shorter
I still need to work out the case where AndroidTest can be removed by mocking the compat instead
> Remove android when possible

- AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
- AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java
- AnkiDroid/src/main/java/com/ichi2/libanki/Model.java
- AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.java
Fixes #10434
Check if "did" property in model is not null before trying to get its value
Tested on my device (where the problem first happened) (Samsung Galaxy Note 10 Lite SM-N770F/DS, API 30)
> Fix `setDid()` when did is null

- AnkiDroid/src/test/java/com/ichi2/compat/CompatDirectoryContentTest.kt
Indeed, multiple of those tests uses `hasFile` which require to be tested on
both API
> DirectoryTest for API 21 and 26

- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContentTest.kt
- AnkiDroid/src/test/java/com/ichi2/compat/CompatCopyFileTest.java
- AnkiDroid/src/test/java/com/ichi2/compat/CompatDirectoryContentTest.kt
- AnkiDroid/src/test/java/com/ichi2/compat/CompatHasFilesTest.kt
- AnkiDroid/src/test/java/com/ichi2/testutils/Test21And26.kt
This allow CompatHelper to return V21 and V26. Useful for cases where the only
difference between version is only in Compat.
> NF: introduce Test21And26

- AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
I mentioned some issues via `KotlinCleanup` in: https://github.com/ankidroid/Anki-Android/pull/10456
This fixes most of the `@KotlinCleanup` annotations, and starts the "proper" refactor to idiomatic Kotlin.
Not massive, but I wanted to make a commit today.
Lint on:
* rename variable 
* 'protected' visibility is effectively 'private' in a final class
* Variable is same as 'X' and can be inlined
* Cascade if should be replaced with when
* Fix variable names
* Always returns null type
Then some manual work
Untested, mostly automated refactorings
> refactor(preferences): Post-Kotlin Cleanup

- AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
_As a developer, I would like to know if `{{tts}}` is supported so I can determine whether to use `AnkiDroidJS.ankiTtsSpeak`, or rely on the system TTS_
Fixes #10443
Using JavaScript interface and android TTS `onInit()`
```java
TextToSpeech.SUCCESS
```
Tested on device.
Add following to card template before calling tts api.
```html
<script>
let isTtsOk = AnkiDroidJS.ankiTtsIsAvailable();
if (isTtsOk) {
// call other TTS JS API
}
</script>
```
https://stackoverflow.com/questions/5680248/android-tts-not-working-in-device
https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-Javascript-API
> Check if TTS available on device

- AnkiDroid/build.gradle
- AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.java
- AnkiDroid/src/test/java/com/ichi2/libanki/StorageTest.kt
- AnkiDroid/src/test/java/com/ichi2/libanki/template/TemplateTest.java
- AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilsTest.java
The package name `hamcrest-all` is not used for newer releases of hamcrest.
`hamcrest` 2.x+ packages all classes by default. Because of the name changing, dependabot could not have updated this.
Some relevant new features: [FileMatchers](http://hamcrest.org/JavaHamcrest/javadoc/2.2/) and [ComparatorMatcherBuilder](http://hamcrest.org/JavaHamcrest/javadoc/2.2/org/hamcrest/comparator/ComparatorMatcherBuilder.html)
Useful to #10387
Change the package name and version in build.gradle
Handled deprecations:
- isOneOf -> oneOf
- isEmptyString -> emptyString
- isEmptyOrNullString -> emptyOrNullString
Ran the automated tests
> Update hamcrest-all:1.3 to hamcrest:2.2

- AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java
- AnkiDroid/src/main/res/values/10-preferences.xml
- AnkiDroid/src/main/res/values/constants.xml
- AnkiDroid/src/main/res/xml/preferences_advanced.xml
This option is useful to anyone who wants to know "how many cards did I
study today (in total), and how many cards are due tomorrow (in total)".
In this situation it can save a few clicks and scrolls which can be slow
on e-ink displays.
If using a single "To Review" filtered deck then stats are pretty
meaningless. For instance "Studied 3 cards in 0 minutes today". To
find the real statistics after studying with a filtered deck I have
to select "All decks" and then I correctly see "Studied 491 cards in
25 minutes today".
This option lets you bypass the empty filtered deck stats and go directly to the stats you are interested in (this new behavior is opt-in)
Deploy to android emulator:
- Review a deck, open nav drawer, click stats, see last deck stats
- Enable new "Show statistics for all …
> Add option to show all deck stats by default

- AnkiDroid/src/test/java/com/ichi2/anki/model/DirectoryTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/DeleteEmptyDirectoryTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContentTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryTest.kt
- AnkiDroid/src/test/java/com/ichi2/compat/CompatCopyFileTest.java
- AnkiDroid/src/test/java/com/ichi2/compat/CompatDirectoryContentTest.kt
- AnkiDroid/src/test/java/com/ichi2/compat/CompatHasFilesTest.kt
- AnkiDroid/src/test/java/com/ichi2/compat/Test21And26.kt
This begins with #10439.
It checks that if there is no permission to list directory content, then the exception is not catched in:
* creation of MoveDirectoryContent
* execution of DeleteDirectory
* entire execution of MoveDirectory
* Directory's hasFile
> Permission exception operation

- AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MigrateUserData.kt
- AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectory.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MockExecutor.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MockMigrationContext.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MockMigrationContextTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/OperationTest.kt
If `DeleteEmptyDirectory` fails, we want to perform the `MoveDirectory` that spawned it
This could happen for many reasons, such as a failed file move, or adding a file to `AnkiDroid` during the process
In the real world, this will all be handled in the `ExecutionContext`, we start this off with a mock.
* Mock `ExecutionContext`
* add `retry()`
* Use a decorator to implement `retry()` on an arbitrary `Operation`
Unit tested. Had a bad rebase operation, so small potential for issues.
I need to allocate more time specifically in blocks for scoped storage. Really close to completion now.
> feat(scoped-storage): Retry DeleteEmptyDirectory 

- AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.kt
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerNoSpaceToDowngradeDialog.kt
- AnkiDroid/src/test/java/com/ichi2/anki/BackupManagerTest.kt
related to #10489
This only partly resolves the issue.
It was mostly just removing nullability. However a small change in a Unit test was necessary as well.
It compiles, passes tests and still runs as expected on my Samsung Galaxy S10.
> [Kotlin Cleanup] BackupManager

- AnkiDroid/src/test/java/com/ichi2/anki/ProductionCrashReportingTreeTest.java
- lint-release.xml
Enable  LogConditional lint
Fixes #10478
1.Changed the severity value of the `LogConditional` lint from ignore to fatal
2.Fixed the following problems appearing on running gradlew lint
3.Fixed the problems by adding `@SuppressLint("LogConditional")` on top
> Enable  LogConditional lint

- AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
As the method already used when(), `@KotlinCleanup` was redundant there.
Fixes  a part of [#10489](https://github.com/ankidroid/Anki-Android/issues/10489)
Runs as expected on physical device and emulator.
- [✓] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [✓] You have a descriptive commit message with a short title (first line, max 50 chars).
- [✓] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [✓] You have commented your code, particularly in hard-to-understand areas
- [✓] You have performed a self-review of your own code
- [✕] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [✕] UI Changes: You have tested your change using the [Google Accessibility …
> removed redundant @KotlinCleanup from Preferences.kt

- AnkiDroid/src/test/java/com/ichi2/utils/JSONArrayTest.java
- AnkiDroid/src/test/java/com/ichi2/utils/JSONObjectTest.kt
Shaves 40/50s off test time
Add `EmptyApplication` as these tests don't depend on AnkiDroid
Test-only
> refactor(tests): Improve Performance

- AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt
Kotlin Cleanup
Fixes a part of [#10489](https://github.com/ankidroid/Anki-Android/issues/10489)
1. Removed KotlinCleanup annotation and fixed the addressed issue
2. Gone through warnings and replaced Java util methods with Kotlin equivalents
1. Passes all the unit tests
2. Runs on realme 6i and Pixel 4 emulator API 27,31
- [✓] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [✓] You have a descriptive commit message with a short title (first line, max 50 chars).
- [✓] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [✓] You have commented your code, particularly in hard-to-understand areas
- [✓] You have performed a self-review of your own code
- [✕] UI …
> KotlinCleanup in AnkiDroidWidgetSmall.kt and Java Util methods to kotlin equivalents

- AnkiDroid/src/main/java/com/ichi2/anki/model/RelativeFilePath.kt
- AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ScopedStorageService.kt
- AnkiDroid/src/test/java/com/ichi2/anki/model/RelativeFilePathTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContentTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/OperationTest.kt
- AnkiDroid/src/test/java/com/ichi2/testutils/FileSystemUtils.kt
For use in conflict management in scoped storage.  Once we have a relative path,
we can move it to "/conflict/" + path and properly handle the creation of
directories.
Related #5304
> Relative File Paths

- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContentTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/OperationTest.kt
- AnkiDroid/src/test/java/com/ichi2/testutils/FileSystemUtils.kt
It was confusing to have both `createDirectory` and
`createTransientDirectory`. Plus, we almost never really need a `Directory` but
its underlying `File`.
This remove confusion in which method to use, what are the difference between
them, and it remove even some `.direction`, at the cost of two helpers methods
that encapsulate File in Direction when required
> NF: remove `createDirectory`

- AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
The previous formulation produced lint warnings
> fix(docs): Wrong tag value

- AnkiDroid/src/main/res/layout/activity_drawing.xml
- lint-release.xml
Enabled lint check for "ObsoleteLayouParam", changed "ignore" to "fatal" and took the line above.
Fixes  #10482 
Ran ./gradlew lint and resolved errros in activity_drawing.xml
> Enabled lint check "ObsoleteLayoutParam"

- AnkiDroid/src/test/java/com/ichi2/libanki/StorageTest.kt
FileName : `StorageTest.kt`
Changed variables `actualConf` and `expectedConf` from var to val  
Fixes (partially) #10489
1. Changed the variable from var to val as annotated.
1. Passed all the unit tests and runs as expected on Redmi 6 pro
> KotlinCleanup File-> Storage Test changed var to val

- .idea/codeStyles/Project.xml
- AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
Remove usage of depricated startActivityForResult()
Fixes a part of #8602
1. Remove the `onActivityResult()` method and create an equivalent `ActivityResultLauncher`
2. Replace call to `startActivityForResult()`, call `activityLancher.launch()`
Passes all unit tests and runs as expected on Realme 6i 
https://user-images.githubusercontent.com/69595691/158453132-932f1969-abb2-4f19-9334-aa203f4f47a7.mp4
https://user-images.githubusercontent.com/69595691/158445981-16e8bf8b-5cb7-4b9d-8383-d9ee5730ef9a.mp4
> startActivityForResult migration in Preferences.kt

- .prettierignore
Sample file picked up:
```
AnkiDroid\build\intermediates\assets\amazonDebug\mergeAmazonDebugAssets\jquery.min.js 1203ms
AnkiDroid\build\intermediates\assets\amazonDebug\mergeAmazonDebugAssets\mathjax\a11y\assistive-mml.js 77ms
AnkiDroid\build\intermediates\assets\amazonDebug\mergeAmazonDebugAssets\mathjax\a11y\complexity.js 165ms
AnkiDroid\build\intermediates\assets\amazonDebug\mergeAmazonDebugAssets\mathjax\a11y\explorer.js 213ms
AnkiDroid\build\intermediates\assets\amazonDebug\mergeAmazonDebugAssets\mathjax\a11y\semantic-enrich.js 48ms
AnkiDroid\build\intermediates\assets\amazonDebug\mergeAmazonDebugAssets\mathjax\conf.js 5ms
AnkiDroid\build\intermediates\assets\amazonDebug\mergeAmazonDebugAssets\mathjax\input\tex\extensions\action.js 26ms …
```
> fix(prettier): Ignore 'build' folder

- AnkiDroid/src/main/res/values/11-arrays.xml
- AnkiDroid/src/main/res/values/constants.xml
If we changed array ordering, CrowdIn corrupted the ordering of strings
To fix this: define a fixed order in constants.xml, and use
translatable strings from `11-arrays`
Fixes #7794
Fixes #10554
> fix(translations): make arrays constant

- .prettierrc
On Windows, conflict between git's CRLF normalization and prettier's was generating EOL diff
To solve it, this changes `endOfLine` to `auto`, which does:
`Maintain existing line endings (mixed values within one file are normalised by looking at what’s used after the first line)`
Add `endOfLine: "auto"` to .prettierrc
Made a commit and checked if there was EOL diffs
Prettier EOL options: https://prettier.io/docs/en/options.html#end-of-line
> Change .prettierrc endOfLine to auto

- AnkiDroid/src/main/res/menu/download_shared_decks_menu.xml
- AnkiDroid/src/main/res/values/01-core.xml
FileNames : `download_shared_decks_menu.xml` and `01-core.xml`
changing value for avoiding ambiguity while accessing two features.
Fixed #10178
Introduced a new string and diverged one of the features to it to avoid conflict/ ambiguity while accessing these features.
1. Passed all the unit tests and runs as expected on Redmi 6 pro
> search_deck ambiguity resolved.

- lint-release.xml
Enable  ImplicitSamInstance lint 
Fixes #10504
Add `<issue id="ImplicitSamInstance" severity="fatal" />` to lint-release.xml
And run gradlew lint and their are no issue with this lint
> [lint ] enable_implictSamInstance_lint

- AnkiDroid/build.gradle
- AnkiDroid/src/test/java/com/ichi2/compat/Test21And26.kt
This makes for much easier mocking of Kotlin Objects/statics
This dependency will be used when migrating `CompatHelper`
Unblocks #10578
https://stackoverflow.com/questions/37977320/how-to-mock-a-kotlin-singleton-object
https://stackoverflow.com/questions/49762409/mock-static-java-methods-using-mockk
> feat(tests): Add Mockk dependency

- AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
- AnkiDroid/src/main/java/com/ichi2/anki/JavaScriptTTS.kt
- AnkiDroid/src/main/java/com/ichi2/anki/LanguageUtils.kt
FileName : `LanguageUtils.kt`
Changed the format of expression involving variable `localeCode` to a standard Kotlin one as annotated  
Fixes (partially) #10489
1. Changed the format of expression to a standard Kotlin one as annotated.
1. Passed all the unit tests and runs as expected on Redmi 6 pro
> KotlinCleanup : (localeCodeStr)

- AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
- AnkiDroid/src/main/java/com/ichi2/themes/Themes.kt
We were using the `Activity` context before `super.onCreate()` was called
This meant that `AnkiDroidApp.getSharedPrefs(context)` returns null
Fixes #10584
* Use Application Context
* Then a refactoring commit I noticed
Manually - Google Pixel 3A, Android 11
We have 2 usages of setting the legacy theme, this requires upgrading the Preferences library: #5019
> fix: Crash opening Deck Options

- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java
Fixes #10598
Sets title on activity creation
Manually on my device (Samsung Galaxy Note 10 Lite SM-N770F/DS, API 30)
System in portuguese, anki in japanese
> Fix translation of MultimediaEditFieldActivity title

- AnkiDroid/src/main/java/com/ichi2/anki/CardInfo.java
Window title was not translated
Fixes #10591
> fix: translation of "Card Info" Title

- AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
- AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.java
- AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.java
- AnkiDroid/src/test/java/com/ichi2/utils/FileUtilTest.java
Removing the function copyDirectory
Fixes #10458
Removes copyDirectory in Compat interface and its inheritors
> Removed copyDirectory and inheritors

- AnkiDroid/src/test/java/com/ichi2/anki/model/DirectoryTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/DeleteEmptyDirectoryTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryContentTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryTest.kt
- AnkiDroid/src/test/java/com/ichi2/compat/CompatCopyFileTest.java
- AnkiDroid/src/test/java/com/ichi2/compat/CompatDirectoryContentTest.kt
- AnkiDroid/src/test/java/com/ichi2/compat/CompatHasFilesTest.kt
- AnkiDroid/src/test/java/com/ichi2/compat/Test21And26.kt
I wanted to use the tests, but didn't feel the structure was ideal, and tests took 100ms longer than expected to execute (**each**), so I fixed them
* Use `@Parameterized.Parameter`
* Use `@SuppressLint`
* Move the mocking to `.cctor`, rather than `.ctor`, 
It is tests
See approach
* `abstract` stops a test class being attempted to be run
> chore(tests): Cleanup Test21And26

- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.kt
Made mCardList lateinit as per KotlinCleanup and removed the annotation.
#10489
Made mCardList lateinit variable and initialized it to empty array if the value derived from parameters is null.
Runs as expected on physical device and emulator.
> Kotlin cleanup for CardTemplatePreviewer.kt

- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/IntegerDialog.kt
Open keyboard when Rescheduling a Card
Fixes Issue #10476
Made the use of _displayKeyboard()_ function from **MaterialEditTextDialog.kt** and instead of directly returning the **MaterialDialog** to the _onCreateDialog()_ function of **IntegerDialog.kt** , I passed the variable `show` as a parameter to the _displayKeybaord()_ function
This feature has been tested on Physical Android Device and Android Studio emulator.
Device Model : Asus Zenfone Max Pro M2 (X01BDA)
Android Version : 9
https://user-images.githubusercontent.com/40427461/159292389-2db1e009-6262-4dfa-8f8b-074a670309f8.mp4
(https://play.google.com/store/apps/details?id=com.google.android.app …
> open keyboard when rescheduling a card

- AnkiDroid/build.gradle
- AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
Changed the ACRA initialization from annotations to a builder style. This is necessary for updated the project from ACRA 5.7 to 5.8. Did not change build.gradle line 9 to actually update ACRA from 5.7.0 to 5.8. Let me know if that is necessary at this point.
Related #7805 
The annotation initialization will not work with future releases of ACRA, so it needed to be changed to a builder style. This is done in onCreate() when mAcraCoreConfigBuilder is first initialized.
Passes all 7 test when running the androidTest ACRATest
Researched builder styles, fluent APIs, and the ACRA documentation
https://dzone.com/articles/fluent-builder-pattern
https://github.com/ACRA/acra/wiki/BasicSetup#2-configuration
> (#7805) updated ACRA initialization to build style

- AnkiDroid/build.gradle
- AnkiDroid/src/main/java/com/ichi2/anki/ReadText.kt
- AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/AsyncDialogFragment.kt
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
- AnkiDroid/src/main/java/com/ichi2/anki/reviewer/PeripheralKeymap.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/DecksV16.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/ModelsV16.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/backend/DecksBackend.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/utils/PythonExtensions.kt
- AnkiDroid/src/main/java/com/ichi2/utils/JSONException.kt
- AnkiDroid/src/main/java/com/ichi2/utils/JSONTokener.kt
- lint-rules/build.gradle
Bump underlying version of ktlint in order to access this memory fix: https://github.com/pinterest/ktlint/issues/1216
Fixes #10242 (well, should fix it for real, can reopen I guess, if not)
spacing changes were produced automatically using the new version on the
command line with `-F` argument to auto-fix spacing to conform with new
version of the tool. 
It has to be changed at same time as the version since ktlint actually changed it's behavior
I ran ktlint a few times from the command line and it seemed fine?
I verified via `./gradlew :AnkiDroid:dependencies |grep ktlint` that it was pullingn 0.42.1 before this change and is getting 0.45.1 now.
Allowing version overrides on transitive dependencies is really helpful if you make things transitively dependent on consumers of your project. …
> chore(ktlint): bump ktlint to 0.45.1 / spacing changes w/new version

- AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
Input connection createWrapper current implementation is deprecated in function onCreateInputConnection in AnkiDroid/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt.
Fixes #9775 
As suggested in [documentation](https://developer.android.com/reference/androidx/core/view/inputmethod/InputConnectionCompat#createWrapper(android.view.inputmethod.InputConnection,%20android.view.inputmethod.EditorInfo,%20androidx.core.view.inputmethod.InputConnectionCompat.OnCommitContentListener)), i have used createWrapper(View,InputConnection,EditorInfo) and ViewCompat.setOnReceiveContentListener with implementation of OnReceiveContentListener interface.
I have not reimplemented the request read uri permission part alone because its documentation states read uri permission is granted by …
> [Deprecation] create wrapper deprecation api change

- AnkiDroid/build.gradle
- AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
- build.gradle
`anki-android-backend-testing` contains pre-compiled Rust code so Robolectric can load it and run natively.
We can't currently include an Apple Silicon (AS) dylib inside `anki-android-backend-testing `(`cross` doesn't compile AS code yet)
Fixes https://github.com/ankidroid/Anki-Android-Backend/issues/164
But, we can compile an AS dylib on an AS Mac and reference it.
So we include the `dylib` in the releases folder of `Anki-Android-Backend` and add functionality to specify an environment variable to load this `dylib` from disk, instead of from the `.jar`
**Instructions (for 0.1.10):**
Download librsdroid-arm64.dylib from https://github.com/ankidroid/Anki-Android-Backend/releases/tag/0.1.10
And add the following environment variables:
one to the path and one for the version
```
export …
```
> feat(tests): Apple Silicon Support

- AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.java
It defaulted to system language instead of Anki's
Fixes #10623
Sets title on ModelBrowser activity creation
Manually on my phone (Samsung Galaxy Note 10 Lite SM-N770F/DS, API 30)
> Fix ModelBrowser Activity title

- AnkiDroid/src/test/java/com/ichi2/compat/CompatDirectoryContentTest.kt
Error:
```
com.ichi2.compat.DirectoryContentTest > ensure_absolute_path[21] FAILED
java.lang.AssertionError: Paths should be canonical
Expected: "/private/var/folders/tq/7kbhnvh9675drxzzyvpk0n840000gq/T/13587878100631967865/zero"
but: was "/var/folders/tq/7kbhnvh9675drxzzyvpk0n840000gq/T/13587878100631967865/zero"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at com.ichi2.compat.DirectoryContentTest.ensure_absolute_path(DirectoryContentTest.kt:49)
com.ichi2.compat.DirectoryContentTest > ensure_absolute_path FAILED
java.lang.AssertionError: Paths should be canonical
Expected: "/private/var/folders/tq/7kbhnvh9675drxzzyvpk0n840000gq/T/8221483500880813673/zero"
but: was "/var/folders/tq/7kbhnvh9675drxzzyvpk0n840000gq/T/8221483500880813673/zero"
at …
```
> fix(tests): Fix tests on Apple Silicon

- AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectory.kt
- AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
- AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.java
- AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.java
- AnkiDroid/src/test/java/com/ichi2/compat/CreateDirectoriesTest.kt
This allows a "human readable" exception when creating a directory
And a fast result if the directory already exists.
mkdirs() is nice, but:
* The return value only gives us a boolean pass/fail
* It "fails" if the directory already exists
This will be used in MoveConflictedFile
Supersedes #10571
> feat(compat): createDirectories

- .github/workflows/tests_emulator.yml
- AnkiDroid/robolectricDownloader.gradle
Make sure we only download the bits we need in CI via the robolectric pre-downloader (which itself is just there to do the download in a retry loop to avoid flaky network failures during tests if the jars are downloaded on-demand during testing)
Also it turns out that the task that runs this `robolectricSdkDownload` was not actually called in CI, so no de-flaking was happening. Haven't seen this flake in a while but it definitely used to happen, and the code works (or should - CI will bear it out)
No issue logged
Here is the output from my diagnostic jar search to detect current versions:
```
mike@bistromath:/mnt/c/Users/micro/.m2$ find . |grep android-all |grep '.jar$'
./repository/org/robolectric/android-all-instrumented/10-robolectric-5803371-i3/android-all-instrumented-10-robolectric-5 …
```
> test(robolectric): update robolectric jars list to match currently used

- AnkiDroid/src/test/java/com/ichi2/anki/jsaddons/TgzPackageExtractTest.kt
- AnkiDroid/src/test/java/com/ichi2/testutils/BackupManagerTestUtilities.java
- AnkiDroid/src/test/java/com/ichi2/testutils/ShadowStatFs.kt
`IOException: There is not enough space to import the package.`
Cause: `TgzPackageExtractTest` - `ShadowStatsFs` fails to use the canonical path
But: The non-canonical path is required by `BackupManagerTestUtilities`
Fixes #10651
* define a method which uses both canonical and regular paths `registerStats`
Ran tests - now pass
* Macs are hard yo, but it's nice to be able to reasonably run tests locally
* ShadowStatFs needs BOTH canonical and non-canonical path
> Fix tests on macOS+ refactoring

- AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/TgzPackageExtract.kt
- AnkiDroid/src/main/res/values/02-strings.xml
Strings format for size and number of files in tar archive
Fixes #10451
Used `%1$s` and `%2$d` instead of hardcoded values
JUnit test
> Strings format for size and number of files in tar archive

- AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.kt
- AnkiDroid/src/main/java/com/ichi2/annotations/NeedsTest.kt
`commit` called `listener.onSharedPreferenceChanged(this@DeckPreferenceHack, null)` which crashed due to the null 'key'
Fixes #10661
Make parameter nullable
On device - no longer crashes
Added a `NeedsTest` annotation, as otherwise this information would be lost
> fix crash opening FIlteredDeckOptions

- AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java
`menu.add` crashes if a resource identifier is passed in.
Hopefully fixes #10644
Pass in a string instead
Untested
https://github.com/K1rakishou/Kuroba-Experimental/commit/bcaf2d5f55e7f3bf5f3ffc7e0148a2060c69e6c3
> fix(NoteEditor): MIUI Android 12 Crash

- lint-rules/src/main/java/com/ichi2/anki/lint/IssueRegistry.java
- lint-rules/src/main/java/com/ichi2/anki/lint/rules/InvalidStringFormatDetector.kt
- lint-rules/src/test/java/com/ichi2/anki/lint/rules/InvalidStringFormatDetectorTest.kt
The main issue was an invalid format string: https://github.com/ankidroid/Anki-Android/pull/10548/files which caused a crash.
We want to ensure that a string on the left is caught by the lint-rules project, and fails the CI. We want this both for plurals and standard strings (this may be a plural only issue).
Fixes #10604 
Added a new lint rule to check for such errors. 
Added a test for the rule as well.
> added New Lint rule for Detecting invalid string formats.

- .github/workflows/label.yml
- .github/workflows/milestone.yml
For each merged PR, it needs to manually add milestone and remove labels. So, this PR will help in adding milestone to PR and removing all labels using GitHub actions.
Removes following labels for merged PR
```
Pending Merge
Waiting For Feedback
Needs Review
Review High Priority
Needs Second Approval
```
Currently it adds to `2.16 release` milestone
Fixes #10410
I have used this two GitHub actions repository
- https://github.com/zoispag/action-assign-milestone
- https://github.com/andymckay/labeler
For milestone, release milestone string is hardcoded. 
Tested in private repository
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target
> Add merged PR to milestone and remove specific labels

- AnkiDroid/src/main/java/com/ichi2/anki/model/RelativeFilePath.kt
- AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MigrateUserData.kt
- AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MoveConflictedFile.kt
- AnkiDroid/src/test/java/com/ichi2/anki/model/RelativeFilePathTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MockMigrationContext.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveConflictedFileTest.kt
This handled the 'conflicted file' edge case when performing a scoped storage migration:
A file `AnkiDroid/A.txt` is wanted to be moved to `scoped directory/A.txt`, but `A.txt` already exists in the destination AND is different.
Related: #5304
Move the file to `AnkiDroid/conflict/A.txt` or ... `AnkiDroid/conflict/A (99).txt` if there are internal conflicts.
* Fail if (99) is also a conflict (too many conflicts)
* Fail if the move fails on an exception other than a file conflict
Unit tested
> feat(scoped-storage): Move conflicted file

- AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.java
- AnkiDroid/src/main/java/com/ichi2/ui/SeekBarPreference.kt
Opening DeckOptions Crashes
Cause:
Kotlin Migration
49907c76e7fd800c3109b385bd1911f3898a014c
Fixes #10687
Fix crash
Android 11 - no longer crashes
#5019 would be useful here
> fix: crash opening DeckOptions

- AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardAppearance.kt
- AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardHtml.kt
- AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/CardAppearanceTest.kt
Clean out a [TODO](https://github.com/ankidroid/Anki-Android/blob/cadcc3ddf7d277f350a04c5fc44f5a238317c619/AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardAppearance.kt#L31) on CardAppearance. 
Before, `hasUserDefinedNightModeTest()` was returning true if card css had a class like `.night_mode_old`
1. Used a regex to match night mode classes
- It can be tested on https://regex101.com/r/iQtXKo/3
- Note: commented classes are still being matched. Haven't covered because it would need a overkill regex/function and wasn't sure if it would be accepted
2. Built a unit test
- Moved `hasUserDefinedNightModeTest()` to companion object in order to test it with more ease
Unit tests and on my device (Samsung Galaxy Note 10 Lite SM-N770F/DS, API 30) …
> Do not match unrelated classes on `hasUserDefinedNightMode()`

- AnkiDroid/src/main/res/layout/feedback.xml
This small PR adds the missing `inputType` flag as mentioned in the [documentation](https://developer.android.com/reference/android/widget/TextView#attr_android:minLines).
Fixes #10688
> Add missing inputType flag for crash reporting dialog

- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
Crash Fix
Fixes #10698
`@Parcelize`
On my Android 11 - no longer crashes
> fix(deck-selection): don't keep activities crash

- AnkiDroid/src/test/java/com/ichi2/anki/BackupManagerSimpleTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.java
My body itched when I saw a PR which used io.Filematchers and I remembered some tests I built before the matchers introduction could use them
Helps #10387
Use hamcrest filematchers instead of junit asserts
Unit tests
Hamcrest docs: http://hamcrest.org/JavaHamcrest/javadoc/2.2/
> refactor: Use file matchers on BackupManagerSimpleTest and NoteServiceTest

- AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
Change the name of the val d - previous name was meaningless without context, new name is meaningful
Fixes  part of  #10489 
Changed the name of the variable
> Kotlin Cleanup of StudyOptionsFragment.kt

- AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.java
Double ripple effect was occurring in Deck screen.
Fixes [#10634](https://github.com/ankidroid/Anki-Android/issues/10634)
Setting the listener for deckExpander to null in DeckAdapter.onBindViewHolder() solved this issue:
Emulator: Pixel 4 XL API 27
Physical Device: Xiaomi Poco x2.
It is my first pull request on github. The issue which I fixed was not very complex. 
But the feeling is really great. And much excited in journey of open source, contribution.
https://user-images.githubusercontent.com/63647613/161525750-6bfc4793-33a3-4ce5-a180-aeac927a65b6.mp4
https://user-images.githubusercontent.com/63647613/161524531-c624a7c0-b7af-4d6c-a854-b7518795b4e0.mp4
(https://play.google.com/store/apps/details?id=com.google.android.apps.access …
> Solved double ripple effect.

- AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
- AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
- AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java
- AnkiDroid/src/test/java/com/ichi2/testutils/AnkiActivityUtils.kt
Fixes #10674 and closes #10681
1. Made deckSelectionListener variable instead of val, so it can be set on other places
2. Reused deckSelectionDialog on changeDeckDialog
3. Fixed tests
On my device (Samsung Galaxy Note 10 Lite SM-N770F/DS, API 30)
https://user-images.githubusercontent.com/69634269/161401513-36b30335-8c17-42ea-9df1-638d07f65b56.mp4
> Use `DeckSelectionDialog` on change deck

- AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
- AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt
Double back pressed to exit feature wasn't working properly.
Fixes #10638 
The variable storing the number of back pressed wasn't getting reset when we were moving to the next activity. So I reset the variable in the onPause function of the activity.
Physical Device: Realme 8i
In the video, I have demonstrated that it requires two back presses to exit the app and then in the next turn I went to a different activity and came back to the original and still it took two back presses not one which was the issue I resolved
https://user-images.githubusercontent.com/73571511/161382224-d1eadb3a-ad47-40ed-b989-58b47da6c197.mp4
> Setting the time constraint in double back press to exit/return feature of DeckPicker and AbstractFlashCardViewer

- AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
- AnkiDroid/src/main/java/com/ichi2/utils/HandlerUtils.kt
- AnkiDroid/src/test/java/com/ichi2/anki/HandlerUtilsTest.kt
Follow up to #10679
* Move lambda param to last to allow Kotlin to lift lambda out of params
* Speed up tests
* Use `HandlerUtils` function
Untested
> Cleanup: HandlerUtils

- .github/workflows/milestone.yml
Fix, add merged PR to milestone. 
Fixes #10410 
I have tried many implementation and only implementation in this PR works. I have used `curl` to send POST request using GITHUB_TOKEN to assign milestone to merged PR. I have used `pull_request` instead of `pull_request_target` because only that work. 
It works on my repository but it needs to tested here. 
https://docs.github.com/en/rest/guides/getting-started-with-the-rest-api
> fix: add merged pr to milestone

- AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
The color of "Reschedule" icon on "︙"  menu in Review actiivity isn't same as one of other icons
Fixes #10703
Change the color of reschedule icon
Android Device:Redmi y3
> [Bug] reschedule icon color isn't same as one of other icons

- AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
Whenever we used to select the screen which we were used to be already on through Nav Drawer. The Nav Drawer used to remain inactive and no interaction used to be observed.
Now, The Nav drawer closes in case you select the same screen you are already on
#10738 
called the closeDrawer() function on item.isChecked true condition
Instrumental testing on device : Realme 8i
https://user-images.githubusercontent.com/73571511/162423384-35dce5a1-a78e-41df-a968-315868b55fcf.mp4
> Close the Nav Drawer if same screen selected which was already opened

- AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
The shortcut for studying cards used a slightly misleading word, `Reviews,` which has been changed to use the existing `Study` string.
Fixes #10728.
Updated the wording to `Study,` which matches the `Study` button used elsewhere.
Hold down on the app icon to launch the shortcut and note that the `Reviews` option now says `Study` and still launches the study option successfully.
n/a
> Rename the Reviews shortcut option to Study for clarity

- AnkiDroid/src/main/java/com/ichi2/utils/KotlinCleanup.kt
Enables the annotation to be used multiple times
Code only - no user impact
> feat: Make Kotlin Cleanup Repeatable

- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/LocaleSelectionDialog.kt
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsArrayAdapter.kt
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt
- AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.java
- AnkiDroid/src/main/java/com/ichi2/utils/TypedFilter.kt
I cargo-culted this implementation, and should have spent time improving the implementation
Fixes #10715
* Define `TypedFilter`: a strongly typed `Filter`
* Use `TypedFilter`: use the `results` variable in `publishResults` rather than a local
* Some Kotlin Cleanup
Unit tested, and tested on my device
> Fix: filters usage

- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
They broke `menu.add`
Caught this in ACRA
Reference: Issue #10644
Untested
> fix: MIUI on Android 12 crash

- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
There exists a resource string/translation issue on the current builds of AnkiDroid such that when the user switches between 2 languages, the time indicator of the action bar does not translate over. This can be alleviated by restarting AnkiDroid.
Fixes #10772.
Switching the context passed into the Util method from Application to Activity context seemed to resolve the issue.
This was manually tested on my OnePlus 8T, running Android 11. Switching between English and Japanese (and vice-versa) now produces the correct behavior. Attached is a video of the new, expected behavior.
https://user-images.githubusercontent.com/13594022/162661738-779693e5-00df-41ee-b12e-5e517edb6a9c.mp4
In addition to the manual testing, the suite of unit tests that exists for DeckPicker.java was run to ensure that …
> Minor Fix for DeckPicker Translation/String Resource Issue

- AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
Signed-off-by: Kshitij Patil <kshitijpatil98@gmail.com>
Recently, in #10720, we added `OnPageFinishedCallback` to be used by a `WebViewClient` indicating the load is finished. This is currently used by `CardViewerWebClient` and is expected to provide a hook for all the subclasses of `AbstractFlashcardViewer`. Currently, we're not using this callback as there's is a missing `this` parameter here
Android/blob/bcae6dc760bc981c7c74ce77490d1445849577b2/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt#L1021
Added `this` parameter while constructing the instance of `CardViewerWebClient`
By manually running it on a physical device (Pixel 4a)
> Add missing argument for the `onPageFinishedCallback`

- .idea/dictionaries/davidallison.xml
- AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java
- AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
- AnkiDroid/src/main/java/com/ichi2/anki/model/Directory.kt
- AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ScopedStorageService.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java
- AnkiDroid/src/test/java/com/ichi2/anki/model/DirectoryTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/DeleteEmptyDirectoryTest.kt
- AnkiDroid/src/test/java/com/ichi2/libanki/StorageLockingTest.kt
- AnkiDroid/src/test/java/com/ichi2/testutils/FileSystemUtils.kt
I want to add a "Migrate Essential Files" PR, and smaller refactorings and Storage locking makes this a smaller PR when it goes in.
Associated with #5304
* `isLegacySotrage`: move to ScopedStorageService, fix & refactor
* Add `Storage.lockCollection`
* Make it easier to create a `Directory`
Unit Tested, the end result is tested on my Android 11
FileChannel.lock did not lock an Anki Database on macOS
> feat(scoped-storage): Refactorings and Storage Locking

- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
After creating a subdeck, the parent deck's menu is displayed again
Fixes #10632 
Android Device:Redmi y3
> [Bug] After creating a subdeck, the parent deck's menu is displayed again

- tools/parallel-package-name.sh
Parallel Builds are not identifiable at all after install
Fixes #10188
https://github.com/ankidroid/Anki-Android/commit/50de2d21bd4a9061150e9cd16354cb364794877e#diff-90245b3aabb697f90a867f2dfd56e526ff1167b17b9c66b414e4ac044a55259aR24  added a comment to the `app_name` constant which broke the following line:
https://github.com/ankidroid/Anki-Android/blob/f7cf613c6e126941396c1a6fc8d18e9a99f8eb80/tools/parallel-package-name.sh#L16
This fixes it by changing the Regex. Removed `OLD_NAME`variable because it wasn't necessary anymore
Running the script then compiling the app
I didn't know anything about PERL
https://www.tutorialspoint.com/perl/perl_regular_expressions.htm
> Fix: app name now shows parallel name for parallel packages

- AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
- AnkiDroid/src/main/res/xml/preferences_advanced.xml
- AnkiDroid/src/main/res/xml/preferences_advanced_statistics.xml
- AnkiDroid/src/main/res/xml/preferences_appearance.xml
- AnkiDroid/src/main/res/xml/preferences_custom_sync_server.xml
- AnkiDroid/src/main/res/xml/preferences_general.xml
- AnkiDroid/src/main/res/xml/preferences_gestures.xml
- AnkiDroid/src/main/res/xml/preferences_reviewing.xml
- AnkiDroid/src/test/java/com/ichi2/anki/PreferencesTest.kt
Converting all the Checkbox in the Preference section into Toggle Switches
Fixes #10776 
CheckBox and Switch are two custom selection elements provided by the preference library and they have an identical implementation, its just CheckBox has CheckBoxPreferences and Switch has SwitchPreferences, and the two elements being two-option having elements have identical possible states as well.
Tested by my physical device: Realme 8i
https://user-images.githubusercontent.com/73571511/163495066-f607e85e-0278-4d1f-bd82-3ce3b31104df.mp4
> Converting all the Checkbox in Preference section into Toggle Switches

- AnkiDroid/src/main/AndroidManifest.xml
https://developer.android.com/reference/android/R.attr#preserveLegacyExternalStorage
https://developer.android.com/training/data-storage/use-cases
Note: If you set `preserveLegacyExternalStorage` to true, the legacy
storage model remains in effect only until the user uninstalls your
app.
If the user installs or reinstalls your app on a device that runs
Android 11, then your app cannot opt out the scoped storage model,
regardless of the value of preserveLegacyExternalStorage.
> Android: enable `preserveLegacyExternalStorage`

- AnkiDroid/build.gradle
- tools/release.sh
As noted in the commits, sometimes I (as main release engineer) am all eagerly running a release while merging PRs, and if you merge a PR while releasing then the release script fails to push the version increment and the tag.
So now I'm eagerly pushing them, before the build succeeds even. Balance of risks is tilted towards burning more version numbers than actually release vs not pushing the build increment that really did release.
Just move the git commit / tag / push to before the build step, to minimize the window where something else may merge
Untested but I'm about to run a release...that'll test it.
If you do something long enough, you hit corner cases frequently. 3rd time this has happened to me
> fix: eagerly push release version / fix 2.16alpha58

- AnkiDroid/build.gradle
- AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java
This is causing a lot of test failures. Best to ignore for now.
I like the addition of the `NeedsTest` annotation, it removes the chance of an issue to add tests going stale, and adds good 'TODOs' for onboarding.
> CI: ignore flaky test on Windows [version16CollectionOpen]

- .idea/dictionaries/davidallison.xml
- AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java
- AnkiDroid/src/main/java/com/ichi2/anki/exception/RetryableException.kt
- AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ScopedStorageService.kt
- AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MigrateEssentialFiles.kt
- AnkiDroid/src/test/java/com/ichi2/anki/exception/RetryableExceptionTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MigrateEssentialFilesIntegrationTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MigrateEssentialFilesTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/Utils.kt
- AnkiDroid/src/test/java/com/ichi2/testutils/CollectionDBCorruption.kt
We want to get the user up and running in a scoped storage directory as soon as possible
Related: #5304
COPIES essential files to a scoped location. Locking the collection
to prevent corruption.
This is a fast operation, and is designed to block the foreground with
a spinner while it occurs.
This exists to move 'deckPath' quickly, so a user can continue under a
scoped location while a 'MoveUserData' executes in the background
This only copies:
* collection.anki2 + journal
* collection.media.ad.db2 + journal
* collection.log
* .nomedia
Unit Tested
> feat(scoped-storage): Migrate Essential Files

- AnkiDroid/src/main/res/xml/preferences_custom_buttons.xml
This added two additional choices of 'Always Show' and 'Show if room' for deck options
Fixes #10815 
I used the 
@array/custom_button_labels and @array/custom_button_values
instead of
@array/custom_button_labels_menu_and_disabled and @array/custom_button_values_menu_and_disabled
for entry and values array of customButtonDeckOption List Preference
I have tested this on my device
UI changes is as described in images of #10815
> Added more choices for customButtonDeckOption Preference

- AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java
- AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
- AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ScopedStorageService.kt
- AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java
For the context, long ago "deck" were called "collection" in anki. Then a
collection could have many decks, and the difference became important.
I don't want to change the value, because it would be hard to do properly and
have no interest. But I clearly want to change the constant name because "DECK"
makes no sens today
> NF: rename PREF_DECK_PATH to PREF_COLLECTION_PATH

- AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
Don't hide minibar flags/marked icon on fullscreen mode
Fixes #10882
Add a check for fullscreen mode on flag and marked minibar methods
On my phone (Samsung Galaxy Note 10 Lite SM-N770F/DS, API 31, One UI 4.0)
https://user-images.githubusercontent.com/69634269/163674889-80c4080f-4a9f-44a5-b08a-d72ad9875cd0.mp4
> Don't hide flag and marked icons from minibar on fullscreen

- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
- AnkiDroid/src/main/java/com/ichi2/anki/services/ReminderService.kt
- AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
- AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractDeckTreeNode.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckDueTreeNode.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckTreeNode.java
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/TreeNode.kt
- AnkiDroid/src/main/java/com/ichi2/widget/WidgetStatus.kt
- AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java
- AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.java
- AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.java
I'm sorry this is so big. There is a lot of coupling and it's difficult to reduce this.
I'm open to additional commits to change the name of:
* TreeNode (added by this PR)
* AbstractDeckTreeNode (no longer a TreeNode)
* DeckTreeNode (no longer a TreeNode)
* DeckDueTreeNode (no longer a TreeNode)
I needed to convert `DeckPicker` for the Kotlin migration, and the recursive + inherited nature of `AbstractDeckTreeNode` seemed infeasible to pass through the type system after some trying.
AbstractDeckTreeNode has two responsibilities: as a base class for deck display data, and as a tree.
The combination of the two led to the recursive structure:
```kotlin
AbstractDeckTreeNode<T : AbstractDeckTreeNode<T>?>
```
which is difficult to express in Kotlin.
As well as breaking the SRP, and being a …
> refactor: extract TreeNode from AbstractDeckTreeNode

- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.kt
Using `CollectionGetter` allows `DeckPicker` to be converted to Kotlin
> refactor: SyncErrorDialogListener: collection access

- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java
- AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.kt
When pulling up the keyboard to search, the FAB did not disappear, which resulted in unexpected behavior when interacted with.
Fix #10797 
I set the fab to disappear when the SearchItem toolbar is opened and reappear when it is closed.
This was manually tested on the latest alpha using the emulator for Pixel 5 API 31.
I looked into a unit test, but I faced the following issue: https://stackoverflow.com/questions/36793404/checking-android-fab-visibility-always-returns-visible-from-robolectric-test-cas
This SO post can be applied to converting the code to kotlin when the time comes: https://stackoverflow.com/questions/57712498/how-to-hide-fab-when-user-click-on-searchview-and-keyboard-opens
https://user-images.githubusercontent.com/71997294/163465158-6dd476f0-8837-46c2-b820-628e62b18609.mp4
> Update when FAB should close or hide while navigating the app

- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
App crashed if checkmedia was done after an update from v2.15.6
Fixes #10892 
Added `READ_EXTERNAL_STORAGE` permision to the permissions list in `DeckPicker::requestStoragePermission`
> Fixed "CheckMedia" causing crash

- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicTextFieldController.kt
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/IField.java
`ImageField` overrides `getText` and `getHtml` to return null
Don't change the setters: non-null params are always used
Untested
> refactor: IField - add nullability annotations

- AnkiDroid/src/test/java/com/ichi2/utils/JSONObjectTest.kt
A variable was named as object which as a key word, so I replaced that with testObject
Part of #10489 
Checked by running all the test on my local machine
> JSONObjectTest.kt : changing the variable name from Object to testObject

- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.kt
App would crash if "Don't keep Activities" was ON and you did as [this video](https://github.com/ankidroid/Anki-Android/issues/10944#issuecomment-1101689732) shows
Fixes #10944 
Added `@JvmField` for all `CREATOR`s in `HelpDialog`
https://user-images.githubusercontent.com/59933477/164052808-151a285b-ef92-4c64-a035-ef7ab9403b7a.mov
> Fixed "don't keep activities" crash on HelpDialog

- AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.kt
- AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
- AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicMediaClipFieldController.kt
- AnkiDroid/src/main/java/com/ichi2/compat/Compat.java
- AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.java
- AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.java
- AnkiDroid/src/main/java/com/ichi2/preferences/TimePreference.kt
- AnkiDroid/src/main/java/com/ichi2/utils/FileUtil.kt
- AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt
[Kotlin Pre-Migration] Compat 
package com.ichi2.compat
Add NonNull/Nullable annotations to the java file before converting it to Kotlin in a subsequent PR. 
Reason: Complex call heirarchy, minimse the chances of breakage post conversion
> [Kotlin Pre-Migration] Compat 

- AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java
- AnkiDroid/src/main/java/com/ichi2/async/SingleTaskManager.java
- AnkiDroid/src/main/java/com/ichi2/async/TaskDelegate.kt
- AnkiDroid/src/main/java/com/ichi2/async/TaskManager.java
- AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
- AnkiDroid/src/test/java/com/ichi2/async/ForegroundTaskManager.java
When moving to Kotlin, we have a large number of tasks which require a non-null collection, and a small number which require a nullable collection.
We use the type system to split these out, which will allow an easier, and more correct conversion to Kotlin.
This splits out TaskDelegate into:
* TaskDelegateBase - what TaskDelegate was
* `task()` is renamed to `execTask()`
* `execTask` accepts a Collection?
Move all task executions to use `TaskDelegateBase` in preparation for a `UnsafeTaskDelegate`
* Use `UnsafeTaskDelegate` to allow a null collection in the type system
* Remove overrides of `requiresOpenCollection`
* Handle this in the base class
> refactor: Introduce 'UnsafeTaskDelegate'

- AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
- AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.kt
- AnkiDroid/src/main/res/values/constants.xml
- AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/ViewerCommandTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/reviewer/MappableBindingTest.kt
There was a Add Note app bar button, but not a gesture
Fixes #10976
Hook the gesture and command with the appropriate methods
Note: `A` is the default hotkey for adding notes on Anki, so reused here
On my phone (Samsung Galaxy Note 10 Lite SM-N770F/DS, API 31, One UI 4.0)
<details><summary>Screenshot</summary>
</details>
> Implement `Add note` gesture

- lint-rules/src/main/java/com/ichi2/anki/lint/IssueRegistry.java
I saw this compile warning and I don't like warnings.
```
> Task :api:lintAnalyzeDebug
com.ichi2.anki.lint.IssueRegistry in /home/mike/work/AnkiDroid/Anki-Android-Upstream/lint-rules/build/libs/lint-rules.jar does not specify a vendor; see IssueRegistry#vendor
```
So I fixed it
Implement required method override
`./gradlew lint` should compile without this warning, it does now
The lint stuff for custom rules is pretty terribly documented but it's also not that hard to manage
> chore(lint): fix lint compile warning re: missing Vendor

- AnkiDroid/jacoco.gradle
- api/build.gradle
I want `./gradlew clean jacocoTestReport ktlintCheck lint` to run as clean as possible
Several gradle deprecation errors (if you turn on `--warning-mode all` on the gradle command line you see them)
Following instructions to use new APIs, fairly easy
Lots of command line runs of the above gradle command
In groovy, `destinationDirectory <something>` is not the same as `destinationDirectory = <something>`
The `=` is important
> fix: forward-port to non-deprecated gradle properties

- lint-rules/src/main/java/com/ichi2/anki/lint/rules/DuplicateCrowdInStrings.java
Cleans up a deprecation warning on compile
Trawl through kotlin source etc and trial and error
Compile with and without this, errors are gone with this
> fix: forward-port to non-deprecated APIs in DuplicateCrowdInStrings rule

- AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
- AnkiDroid/src/main/java/com/ichi2/anki/LeakCanaryConfiguration.kt
This PR creates a helper object to hold the code related to initialization of Leakcanary happening inside of AnkiDroidApp. I've taken the liberty of simplifying the code a bit, for example by removing the empty list that was being passed in and replacing it with a todo for when the class is migrated to kotlin. 
I can migrate the class directly to kotlin if needed.
Fixes #11006 
> Move code related to LeakCanary outside of AnkiDroidApp

- .github/workflows/lint.yml
- .github/workflows/tests_emulator.yml
- .github/workflows/tests_unit.yml
these did not exist prior, and cancel-workflow has worked well for us,
but built-in is better when it is available
Determined via trial and error what the best naming was for the concurrency group, via work in Anki-Android-Backend
Tested on Anki-Android-Backend - it works! But only on the second-or-after runs because the name has to be stable starting with the first one
> refactor(ci): use built-in concurrency features

- AnkiDroid/build.gradle
- lint-rules/build.gradle
these do not need to be included by themselves, and if they are
Android Studio actually emits a warning (which prompted the investigation)
https://kotlinlang.org/docs/gradle.html#dependency-on-the-standard-library
from https://stackoverflow.com/questions/49956051/warning-kotlin-plugin-version-is-not-the-same-as-library-version-but-it-is
Just remove the dependencies
API21 / API24 / API31 emulators up, run `./gradlew jacocoTestReport ktlintCheck lint` it all passes
Kotlin moves a bit faster than it appears...in DX as well as language features
> build(deps): kotlin stdlib deps are implicit now

- lint-rules/src/main/java/com/ichi2/anki/lint/rules/NonPositionalFormatSubstitutions.kt
quiets a build warning
Tested by compiling with it and without it
> fix: nonPositionalFormatSubstitution rule should use same param name as super

- tools/migrate.sh
Once actual code migration is done, once the code compiles correctly, tests
passes, and before any commit is done, run `tools/migrate.sh`. This will create the
two commits, as we want them in the migration process.
I tested it with PR #10780
It only partially solves #10573, since I consider that an intelliJ add-on would be better. But this should save frustrating repetitive work already.
> Add a tools/migrate.sh file for Kotlin migration

- lint-rules/build.gradle
- lint-rules/kotlinMigration-lint.gradle
I want to migrate `DuplicateCrowdInStrings`, because https://github.com/ankidroid/Anki-Android/pull/11015 raised an issue with it, and I want to use Kotlin to resolve it.
changes from `AnkiDroid/kotlinMigration`:
* remove `android { }` wrapper around `ktlint { }`
Due to this change, we use a new file
We use the -lint suffix to imply to reviewers that this is a different file type
I tested this before the file rename to `-lint` on `DuplicateCrowdInStrings`, and it compiled on the 'rename' commit.
> feat: Allow Kotlin Migration on lint-rules

- AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java
- AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.java
- AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.java
When create a deck with empty parents name will cause a bug, which make multiple "blank" decks created.
Fixes #11026
Check whether the parents' name is blank, and replace them to "blank" if so.
Run the automated tests through `./gradlew jacocoTestReport`. And manually test it simulator.
Think things through. In this issue I learned the basic process of deck creation.
> Fix a bug about multiple decks created when tapping `::xxx` on deck's name

- AnkiDroid/src/main/res/values/attrs.xml
- AnkiDroid/src/main/res/values/colors.xml
- AnkiDroid/src/main/res/values/constants.xml
- AnkiDroid/src/main/res/values/dimens.xml
- AnkiDroid/src/main/res/values/fonts.xml
- AnkiDroid/src/main/res/values/leakcanary.xml
- AnkiDroid/src/main/res/values/preferences.xml
- AnkiDroid/src/main/res/values/strings.xml
- AnkiDroid/src/main/res/values/styles.xml
- AnkiDroid/src/main/res/values/theme_black.xml
- AnkiDroid/src/main/res/values/theme_dark.xml
- AnkiDroid/src/main/res/values/theme_light.xml
- AnkiDroid/src/main/res/values/theme_plain.xml
- AnkiDroid/src/main/res/values/xiaomi-theme-overlay.xml
- lint-rules/src/main/java/com/ichi2/anki/lint/rules/DuplicateCrowdInStrings.kt
- lint-rules/src/test/java/com/ichi2/anki/lint/rules/DuplicateCrowdInStringsTest.java
fix: Don't apply strings lint to non-strings file
`DuplicateCrowdInStrings` applies to only the /values/ folder but there are other files in the values folder aside from translatable strings (resources, constants, etc...)
Refactor
As lint does not currently have a good way to exclude files from linting
So instead we use `tools:ignore` to do this
Unit tested
We need a guide to teach someone how to 'refresh' a lint rule so `gradlew lint` picks it up
> Fix: preferenceKeys detected as duplicate strings

- .github/workflows/tests_emulator.yml
- tools/emulator_performance/.gitignore
- tools/emulator_performance/analyze_emulator_performance.js
- tools/emulator_performance/fetch_workflow_jobs_json.sh
- we have lots of flakes right now #10672 / #10601 
- we no longer have a multi-API test matrix for emulators, we used to have it on travis
- CI can be a bit slow
This PR updates our CI emulator infrastructure to use a community emulator runner that everyone else uses, to do caching a lot more strictly so that branches can't evict our main cache as easily, to cache emulator snapshots and gradle a bit better for speed, and to run on our lowest and highest supported APIs
Fixes #10672 (by making it not necessary to warn, it shouldn't flake now)
Fixes #10601 by making it not flake
- switch from my custom mostly anti-flake until recently emu startup stuff to react-circus's community-choice android runner
- carefully enable caching for the AVD on main branch
- switch to community consensus …
> perf(ci, emulator): community emulator action / AVD caching / gradle caching

- lint-rules/src/main/java/com/ichi2/anki/lint/rules/DuplicateCrowdInStrings.kt
- lint-rules/src/test/java/com/ichi2/anki/lint/rules/DuplicateCrowdInStringsTest.java
tools:ignore ignores the outcome, but still processed the file
This caused a bug as it found a duplicate key in an ignored file
and flagged it as an error on the non-ignored file
Pulled https://github.com/ankidroid/Anki-Android/pull/11015 and made it pass
* tools:ignore only ignores the outcome, it doesn't stop the processing
* Issues with the unit test framework
> fix: Don't apply lint to ignored file

- .github/workflows/lint.yml
- .github/workflows/tests_emulator.yml
- .github/workflows/tests_unit.yml
- AnkiDroid/build.gradle
- AnkiDroid/jacoco.gradle
- api/build.gradle
- build.gradle
- lint-rules/build.gradle
Each commit here does a thing in our build scripts - 
1- a simple jacoco version update (dependabot doesn't see these for whatever reason)
2- using gradle-build-action in all our workflows (I trialed it in emulator tests, works well, Fixes #11080)
3- hamcrest is used in multiple modules, extract version, update it in lagging module
4- extract our build best practices so lint-rules gets `-Werror` compiler arg "for free" (Fixes #11083)
5- post-process androidTest XML to make sure non-zero # of tests ran (Fixes #11078)
Linked above
I tested the -Werror / "extract build common practices" by doing `git revert a70c0f6a381b31ad205388d4b5e3d6e1f3198f15` then running the build - :heavy_check_mark: got the expected error 
```
mike@bistromath:~/work/AnkiDroid/Anki-Android (batch-of-build-work) % …
```
> build(deps): fix build issues

- AnkiDroid/src/androidTest/java/com/ichi2/anki/reviewer/PeripheralKeymapTest.java
- AnkiDroid/src/main/java/com/ichi2/anim/ActivityTransitionAnimation.kt
- AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
- AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java
- AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
- AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/GestureProcessor.kt
- AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.kt
- AnkiDroid/src/main/java/com/ichi2/anki/reviewer/PeripheralKeymap.kt
- AnkiDroid/src/main/res/anim/slide_down_in.xml
- AnkiDroid/src/main/res/anim/slide_down_out.xml
- AnkiDroid/src/test/java/com/ichi2/anki/ReviewerKeyboardInputTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/GestureProcessorTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/reviewer/PeripheralKeymapTest.kt
Fixes #11094
1. Rename the `DOWN` direction to `DEFAULT` since it was meant to follow the default animation and the default animation (at least on my phone) doesn't come from down
2. Add right and left transitions
3. Created a new down transition (equivalent inverse of the current UP transition)
4. Pass the used gesture to `executeCommand()`
5. Map swipe gestures to animations with `FADE` as default
6. Pass the mapped animation transitions to the gestures which opens other activities (i.e. Edit card, Card Info and Add Note)
On my phone (Samsung Galaxy Note 10 Lite SM-N770F/DS, API 31, One UI 4.0)
https://user-images.githubusercontent.com/69634269/165154680-fcea43ee-6447-4bf7-a836-7e6e2242083b.mp4
- Learned a little about android XML animations by reading the existing ones
_Please, go …
> Make animation transitions use the same direction of used swipe gesture

- AnkiDroid/src/main/java/com/ichi2/preferences/AutoFocusEditTextPreference.kt
- AnkiDroid/src/main/java/com/ichi2/preferences/IncrementerNumberRangePreference.kt
- AnkiDroid/src/main/java/com/ichi2/preferences/NumberRangePreference.kt
- AnkiDroid/src/main/java/com/ichi2/preferences/StepsPreference.kt
- AnkiDroid/src/main/java/com/ichi2/utils/AndroidUiUtils.kt
- AnkiDroid/src/main/res/xml/deck_options.xml
Made All Focusable DeckOptions Classes AutoFocus
Fixes #11053 
Added an AutoFocusable interface and a AutoFocusEditTextPreference and extended all focusable preferences from them.
Tested by running on emulator
https://user-images.githubusercontent.com/59933477/165082712-8b6eb6c9-72bd-47e0-93a0-5565609fff17.mov
> Made Focusable DeckOptions Preferences Auto-Focus

- tools/migrate.sh
"refactor: Convert fileName to Kotlin"
instead of
"refactor: Convert fileName.kt to Kotlin"
Tested by migrating a file locally
> Fix #11100 : migrate.sh should give changed commit msg

- AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
- AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.kt
- AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
- AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java
- AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
It was asked if it was possible to remove the `!!`s on` supportActionBar`
Manually
enableToolbar:
* returns the ActionBar which is created
* now throws if provided an invalid view
* Does not accept a `null` view
> refactor: simplify enabling toolbar

- AnkiDroid/src/main/res/values/preferences.xml
- AnkiDroid/src/main/res/xml/preferences_gestures.xml
- AnkiDroid/src/main/res/xml/preferences_reviewing.xml
I wanted more safety on dealing with some preferences keys
Helps #10423
Add constants to `gestures` and `gestureCornerTouch` and add some uses of the existing `timeoutAnswer` constant
Lint passes
> refactor: Use constants on some preferences keys

- .idea/codeStyles/Project.xml
Android Studio Bumblebee | 2021.1.1 Patch 3
From an IDE message:
`Update your Kotlin code style settings to the recommended ones?`
This should stop the review comment of "revert changes to `Project.xml`"
> chore: use recommended Kotlin code style settings

- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioRecordingFieldController.kt
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicMediaClipFieldController.kt
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicTextFieldController.kt
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/FieldControllerBase.java
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/IFieldController.kt
This fixes the @KotlinCleanup for the IFieldController.kt file. Based on the research I've done for the cleanup I also improved the nullability for other classes related to IFieldController. This will make the transition to kotlin smoother for java files in the `com.ichi2.anki.multimediacard` package.
> Fix @KotlinCleanup for IFieldController

- AnkiDroid/src/test/java/com/ichi2/utils/StringUtilTest.kt
[Kotlin Cleanup] StringUtilTest
> [Kotlin Cleanup] StringUtilTest

- AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/OnRenderProcessGoneDelegateTest.kt
[Kotlin Cleanup] OnRenderProcessGoneDelegateTest
> [Kotlin Cleanup] OnRenderProcessGoneDelegateTest

- lint-rules/src/main/java/com/ichi2/anki/lint/rules/NonPositionalFormatSubstitutions.kt
- lint-rules/src/main/java/com/ichi2/anki/lint/utils/Aapt2Util.kt
- lint-rules/src/main/java/com/ichi2/anki/lint/utils/DomExtensions.kt
- lint-rules/src/test/java/com/ichi2/anki/lint/rules/NonPositionalFormatSubstitutionsTest.kt
`%d Total cards imported: %d`
should be
`%1$d Total cards imported: %2$d`
We already had the code, just apply it to plurals -> item elements
We also have a more complex case:
* one (valid) plural with one non-positional element: "%s"
* one (valid) plural with two positional elements: "%1$s, %2$s"
But together, this implies that the plural is given two strings
so the first should be positional
Fixes #11072
* extend `verifyJavaStringFormat` to return more information
* extend `NonPositionalFormatSubstitutions` to accept plurals 
* extract obtaining string from `visitElement` + handle plurals
* filter for two issues:
* The original:  where `verifyJavaStringFormat` returns false
* A second (plural only): where some format strings are not positional inside the `<plurals>` element
Unit tested, …
> lint: verify plural positional format strings

- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
- AnkiDroid/src/main/java/com/ichi2/anki/DeckPickerFloatingActionMenu.kt
- AnkiDroid/src/main/java/com/ichi2/anki/ui/DoubleTapListener.kt
- AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerFloatingActionMenuTest.kt
- AnkiDroid/src/test/java/com/ichi2/testutils/ViewUtils.kt
I liked the UX concept in Discord's "upload file" - a fast path for the common action
Fixes #11084
* Create `DoubleTapListener`
* use `DoubleTapListener`
* Extract `context` to allow for testing
* Test
Unit test and tested on my device, bit sluggish under a debugger (as the note editor takes 1 second to open). This was the same as the normal method, but the single 'double tap' made me more latency sensitive.
Outside a debugger: I love it
* Double tapping: Awesome, 
* Unit tests... UGH
* My approach was 'just get it working' then refactor, it's still a bit of a mess, it was a lot worse before
* I went through ~5 methods of how to double-tap a button in a test, the final result was a combination of all of them, then giving up and writing my own (with the `MotionEvent` method modified from …
> feat: Double tap FAB to add note 

- AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
This PR fixes the `Parcelable.Creator` implementation for `FieldEditText.SavedState` by appending the @JvmField annotation. This makes the implementation to match the expected contract.
At the moment there are two other classes which are written in kotlin and have a CREATOR field without @JvmField: `RecursivePictureMenu.ItemHeader` and` HelpDialog.ExceptionReportItem`. They are most likely responsible for #10942 .
Fixes #10939 
Ran the usual tests
> Fix NoteEditor crash when restoring state

- AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
- AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPIConstants.kt
- AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
- AnkiDroid/src/test/java/com/ichi2/anki/AnkiDroidJsAPITest.kt
In Anki there is option to add `!` to reset card due. So, I have enhanced the implemented JS API to do the same. Also the JS API will have input 0 for due setting for current day.
Fixes
1. First used boolean in JS API function parameters
2. Using the boolean reset card using existing function
```
ResetCards(cardIds).runWithHandler(scheduleCollectionTaskHandler(R.plurals.reset_cards_dialog_acknowledge))
```
1. Added unit test 
2. Tested on device using chrome dev tools
> (feat:js-api) reset card progress js api and enhance set due js api

- AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
Fixes the problem of using system's language instead of AnkiDroid's
Set title on SharedDecksActivity creation 
On my phone (Samsung Galaxy Note 10 Lite SM-N770F/DS, API 31, One UI 4.0)
> Fix translation of `SharedDecksActivity`'s title

- AnkiDroid/build.gradle
- AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/BackupManagerSimpleTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/TemporaryModelTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/CardAppearanceTest.kt
- AnkiDroid/src/test/java/com/ichi2/testutils/AnkiAssertKt.kt
- AnkiDroid/src/test/java/com/ichi2/utils/StringUtilTest.kt
- api/build.gradle
- build.gradle
- lint-rules/build.gradle
- lint-rules/src/main/java/com/ichi2/anki/lint/rules/JUnitNullAssertionDetector.kt
Fixes #11201 
1. Extract JUnit version to a constant, so all 3 testImplementations uses the same version
2. Add JUnitPlatform use to `build.gradle`
3. Fix imports to `kotlin.test.junit5.JUnit5Asserter`
4. Fix `AbstractFlashcardViewerTest.getSignalFromUrlTest`
- It is currently the only parameterized test that uses jupiter-params. It wasn't being discovered before, so it haven't raised any exception.
- Now that it's discovered, it needed to be fixed
gradlew lint+ jacocoUnitTestReport
https://docs.gradle.org/current/userguide/java_testing.html#using_junit5
https://stackoverflow.com/a/68934967
Android JUnit isn't officially updated yet (links taken from a [3rd party Android JUnit5 repo](https://github.com/mannodermaus/android-junit5#official-su …
> Use JUnit5 on tests

- AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
- AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.kt
This is necessary to kotlin migration of NavigationDrawerActivity
Rename params to be the same name of NavigationDrawerActivity
Lint
> NF: Use same param names on NavigationDrawerActivity inheritors

- AnkiDroid/build.gradle
- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java
Updates the material library dependency to the lastest version, 1.6.0. The update saw the deprecation of one of the methods used which I replaced in the PR with a call to the proper method.
Closes [dependabot's update PR](https://github.com/ankidroid/Anki-Android/pull/11240)
Ran the tests.
Also ran the application on several emulators with different API levels and manually used the app to check for issues.
> Update the material library dependency to 1.6.0

- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateBrowserAppearanceEditor.kt
It wasn't being set before, so it defaulted to system's language instead of AnkiDroid's
Fixes #10737 and Closes #10748
Set title on activity creation
On my phone (Samsung Galaxy Note 10 Lite SM-N770F/DS, API 31, One UI 4.1)
> Fix CardTemplateBrowserAppearanceEditor title

- AnkiDroid/src/main/AndroidManifest.xml
Meta-data elements are only needed for versions lower than 4.1. As we don't support Android 4.1 there is no need for these meta-data elements.
Tested on 
- Android 6.0 virtual device.
- Android 12 physical device.
- [ x ] You have commented on your code, particularly in hard-to-understand areas
- [ x ] You have performed a self-review of your own code
- [ x ] UI changes: include screenshots of all affected screens (in particular showing any new or changed …
> Removed metadata elements from AndroidManifest.xml

- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsArrayAdapter.kt
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt
- AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogTest.kt
Long-click a tag in the tag picker dialog now opens the add tag dialog with `$current_tag + ::` as the prefilled input.
* Long-click a tag in `FILTER_BY_TAG` dialog does nothing.
* Long-click a tag in `EDIT_TAGS` dialog opens the add tag dialog.
Fixes #11138 
* Set `onLongClickListener` to open the add tag dialog for each tag item in `TagsArrayAdapter`.
* The real tag content is passed by setting `View.tag`.
* Prefill the prefix tag by `EditText.setText()`.
Tested on a physical device, Huawei P40 Pro.
* Long-click a tag in `EDIT_TAGS` dialog opens the add tag dialog:
1. In note editor, open the tag dialog.
2. Long-click an existing tag `root`.
3. The add tag dialog shows up, with `root::` prefilled.
* Long-click a tag in `FILTER_BY_TAG` dialog does nothing:
1. In Card browser, choose …
> Implement the long-click feature.

- AnkiDroid/src/main/res/values/10-preferences.xml
- AnkiDroid/src/main/res/xml/preference_headers.xml
#11165 introduced a new name for the first preferences category and added it to the appBar, but not to the category title, so it kept using the app name as title. So it should be updated to be coherent with the appBar title
Use the correct string for the category
Went to the preferences initial screen on my device (Samsung Galaxy Note 10 Lite SM-N770F/DS, API 31, One UI 4.1)
<details><summary>Before</summary>
_See the difference between the category name and the app bar after opening it_
</details>
<details><summary>After</summary>
</details>
> Update general category title

- AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/AudioField.kt
- AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/fields/MediaClipTest.kt
Fixes #11280
Fixes handling of `audioPath` nullability and add tests
On my phone (Samsung Galaxy Note 10 Lite SM-N770F/DS, API 31, One UI 4.1)
> Fix crash if no video or audio is selected on NoteEditor

- AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
Fixed Change in overflow menu icon colors if screen orientation changed
Fixes #11060 
Fixes #11017 
https://user-images.githubusercontent.com/59933477/164968847-3578e565-d8b0-43ac-ab7c-b5634576bd37.mov
> Fix Overflow Icon Color Change on Config Change (Orientation Change)

- lint-rules/src/main/java/com/ichi2/anki/lint/rules/DuplicateCrowdInStrings.kt
- lint-rules/src/main/java/com/ichi2/anki/lint/rules/InvalidStringFormatDetector.kt
- lint-rules/src/main/java/com/ichi2/anki/lint/rules/NonPositionalFormatSubstitutions.kt
lint 30.2.0 auto-converts XML text nodes to CDATA
This uncovered a few bugs in our lint checks where we did not check
CDATA nodes
Unblocks #11298
Unit tested on #11298
> fix: Lint handling of CDATA elements

- .github/workflows/lint.yml
- .github/workflows/tests_emulator.yml
- .github/workflows/tests_unit.yml
Just fail fast if setup fails while fetching external resources (cache etc)
That's a simple solution that match the observed low frequency of the flake (so far)
Fixes #11301
Checked on my fork, did not corrupt the yaml, so I think it works...
If it runs often enough, and relies on external resources, it will fail in CI.
> test(ci): add tight timeout to gradle setup step

- AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
- AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
- AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt
- AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
- AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
supportInvalidateOptionsMenu is deprecated
- Change it to equivalent `invalidateOptionsMenu`.
- Removed it from `MyAccount` because it isn't necessary there
AppCompatActivity source code:
```java
@Override
public void supportInvalidateOptionsMenu() {
getDelegate().invalidateOptionsMenu();
}
@Override
public void invalidateOptionsMenu() {
getDelegate().invalidateOptionsMenu();
}
```
> Fix `supportInvalidateOptionsMenu` deprecation

- lint-rules/src/main/java/com/ichi2/anki/lint/IssueRegistry.kt
- lint-rules/src/main/java/com/ichi2/anki/lint/rules/ConstantJavaFieldDetector.kt
- lint-rules/src/main/java/com/ichi2/anki/lint/rules/DirectGregorianInstantiation.kt
- lint-rules/src/main/java/com/ichi2/anki/lint/rules/DirectSnackbarMakeUsage.kt
- lint-rules/src/main/java/com/ichi2/anki/lint/rules/DirectSystemCurrentTimeMillisUsage.kt
- lint-rules/src/main/java/com/ichi2/anki/lint/rules/DirectSystemTimeInstantiation.kt
- lint-rules/src/main/java/com/ichi2/anki/lint/rules/DirectToastMakeTextUsage.kt
- lint-rules/src/main/java/com/ichi2/anki/lint/rules/DuplicateCrowdInStrings.kt
- lint-rules/src/main/java/com/ichi2/anki/lint/rules/DuplicateTextInPreferencesXml.kt
- lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.kt
- lint-rules/src/main/java/com/ichi2/anki/lint/rules/InconsistentAnnotationUsage.kt
- lint-rules/src/main/java/com/ichi2/anki/lint/rules/InvalidStringFormatDetector.kt
- lint-rules/src/main/java/com/ichi2/anki/lint/rules/JUnitNullAssertionDetector.kt
- lint-rules/src/main/java/com/ichi2/anki/lint/rules/JavaFieldNamingPatternDetector.kt
- lint-rules/src/main/java/com/ichi2/anki/lint/rules/KotlinMigrationBrokenEmails.kt
- lint-rules/src/main/java/com/ichi2/anki/lint/rules/KotlinMigrationFixLineBreaks.kt
- lint-rules/src/main/java/com/ichi2/anki/lint/rules/NonPositionalFormatSubstitutions.kt
- lint-rules/src/main/java/com/ichi2/anki/lint/rules/NonPublicNonStaticJavaFieldDetector.kt
- lint-rules/src/main/java/com/ichi2/anki/lint/rules/PreferIsEmptyOverSizeCheck.kt
- lint-rules/src/main/java/com/ichi2/anki/lint/rules/PrintStackTraceUsage.kt
- lint-rules/src/main/java/com/ichi2/anki/lint/rules/VariableNamingDetector.kt
- lint-rules/src/main/java/com/ichi2/anki/lint/utils/Constants.kt
- lint-rules/src/main/java/com/ichi2/anki/lint/utils/ImportStatementDetector.kt
Fixes all `@KotlinCleanup` but the 'Remove this rule once there's no more Java' cleanups
> refactor(lint-rules): Kotlin Cleanup

- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportFileSelectionFragment.kt
Allow only importing single files when .colpkg option is selected in the import dialog as mentioned [here](https://github.com/ankidroid/Anki-Android/pull/10851#pullrequestreview-965378466).
Added an optional flag to ImportFileSelectionFragment to enable or disable multiple file selection. 
Tested on: 
- A physical device with Android 12
- Virtual Device with Android 7.0
> Allow only single imports on the .colpkg option.

- AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Commit c33e7ea8a introduced a regression:
_From DeckPicker, select a deck -> from the toolbar menu, select edit note -> select multimedia(the clip icon) edit for a text field -> use one of the options there like clear or clone -> select done menu item from the toolbar -> expected to see the changes in the note editor, instead the change is ignored._
This is happening because, when returning to NoteEditor, there's a check if the media references are null which shouldn't happen for text fields.
> Ignore image and audio paths check for text based fields

- AnkiDroid/build.gradle
- AnkiDroid/src/test/AndroidManifest.xml
Due to https://issuetracker.google.com/issues/37001185 we were defining`manifest.srcFile` for `debug` instead of for `test`. This is because manifest merging previously occurred only with build variants
Was required for robolectric. Apparently fixed in AGP 0.13.0: https://issuetracker.google.com/issues/37001185
It seems we can manifest merge based on `test` and `androidTest`, so remove the `debug` sourceSet.
This caused a bug on Android Chipmunk, as we included `test` in the `main` source set due to a change in how sourceSets were processed
Fixes #11291
Remove `debug` sourceSet
Robolectric passes on Bumblebee and Chipmunk
Main comments: https://issuetracker.google.com/issues/232007221
https://issuetracker.google.com/issues/220326930
https://issuetracker.google.com/issues/37001185
_Please, …
> fix: invalid sourceSets for Android Chipmunk

- AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.kt
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ModelBrowserContextMenu.kt
Fix a leak reported by LeakCanary for ModelBrowser. It was happening because ModelBrowser was holding a reference to its ModelBrowserContextMenu to dismiss it. 
Instead I used the FragmentManager to dismiss the context menu and I removed its reference.
> Fix ModelBrowser leaking its ModelBrowserContextMenu reference

- AnkiDroid/src/main/java/com/ichi2/preferences/AutoFocusEditTextPreference.kt
- AnkiDroid/src/main/java/com/ichi2/preferences/NumberRangePreference.kt
- AnkiDroid/src/main/java/com/ichi2/preferences/StepsPreference.kt
Fix bug
Fixes #11332 
as `onBindView` would be called when Back button was pressed, changed `onBindView` to `onBindDialogView` which wasn't
https://user-images.githubusercontent.com/59933477/168155147-18a62245-59ca-4697-b9fe-9c4cfc045c0a.mov
> Fix AutoFocus EditText Preferences Back/Return Button Bug

- build.gradle
M1 Macs don't have SMT, so there's no need to halve the processors when running tests
Before:
BUILD SUCCESSFUL in 3m 1s
BUILD SUCCESSFUL in 2m 57s
After:
BUILD SUCCESSFUL in 2m 08s
BUILD SUCCESSFUL in 1m 53s
Note: Scenario was unit test runs inside Android Studio, had similar speedup with `./gradlew clean jacocoUnitTestReport --rerun-tasks`
All tests
We may want to do this based on physical CPUs if there is a good platform-agnostic method.
```
davidallison@Davids-MBP optilingo_mobile_app_v2 % sysctl -n hw.physicalcpu                                         
10
davidallison@Davids-MBP optilingo_mobile_app_v2 % sysctl -n hw.ncpu                                 
10
```
> feat: Speed up tests on Apple Silicon and CI

- .github/workflows/tests_unit.yml
looks like windows file locking strikes again, with the gradle daemon
locking files in a way that makes caching them not work, leading to
persistent underperformance on windows runners
https://github.com/ankidroid/Anki-Android/runs/6476348351?check_suite_focus=true#step:16:17
Stopping the gradle daemon will release the file locks
I'm not sure I can even test this until it's merged into main since cache is read only on all branches
Gradle-related issues turned up via search described the locks getting in the way, and people reported that either turning off the daemon or stopping it at the end released locks
Also, the windows filesystem is lame and always has been.
> test(ci, windows): stop gradle daemon to unlock files for caching

- AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserNonAndroidTest.kt
[Kotlin Cleanup] CardBrowserNonAndroidTest
> [Kotlin Cleanup] CardBrowserNonAndroidTest

- AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/MediaTest.java
- AnkiDroid/src/main/java/com/ichi2/libanki/Media.java
This follows upstream, so the media contained on these tags won't be deleted
Fixes #10324 and Fixes #10034
- Updates the regexes to follow upstream
- reference: https://github.com/ankitects/anki/blob/b403f20cae8fcdd7c3ff4c8d21766998e8efaba0/pylib/anki/media.py#L34-L45
- Build some tests
On my phone (Samsung Galaxy Note 10 Lite SM-N770F/DS, API 31, One UI 4.1)
https://user-images.githubusercontent.com/69634269/169420453-671bcc61-0fc6-47de-9082-24bad54dc638.mp4
> Add support to `<audio>` and `<object>` tags

- AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.kt
- AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
- AnkiDroid/src/main/java/com/ichi2/anki/Statistics.kt
To improve type safety this PR refactors code in the onCollectionLoaded() callbacks to use the non null Collection received as a parameter instead of the getCol() method call from the super class which can be nullable. There's a also a `!!` addition which is safe because the method where it happens it's called from onCollectionLoaded() where we know that the Collection is valid.
> Refactor to use Collection parameter in onCollectionLoaded callback

- AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
If a card is open in reviewer, its flag and mark should be updated if we change them by navigating to card browser and going back
Fixes #11396 
Set `reloadRequired` in `CardBrowser` to true if `reviewerCardId` is in the list of selected cards to set Flag or Mark of
Emulator:
https://user-images.githubusercontent.com/59933477/169697989-4a1834e0-06dc-4004-aa3c-cc8d46eddeac.mov
> Fixed Reviewer not updating after changing card in Browser

- AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
`localStorage` is implemented in Anki 2.1.50 and later version. So using webview settings the dom storage enabled for AnkiDroid also. 
It is not required to enable dom storage for `sessionStorage`, but it does not persist data during review or after restarting of app so `localStorage` will be helpful here.
Fixes #11268
Fixes #6971
Enabled dom storage in webview
```kotlin
webView.settings.domStorageEnabled = true
```
Tested on device
1. Add js script to front side of card
```html
<script>
localStorage.setItem("Anki", "Droid");
</script>
```
2. Check the set value in back side of card
```html
<script>
console.log( localStorage.getItem("Anki") );
</script>
```
https://developer.android.com/reference/android/webkit/WebSettings?hl=en#setDomStorageEnabled(boolean) …
> feat: enable dom storage in webview for localStorage

- AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt
- AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.kt
this method can only be called once, during the only creation, and the
unmontReceiver is necessarily null at this step.
Part of #11418
> NF: remove redundant nullity check

- AnkiDroid/build.gradle
- AnkiDroid/src/main/AndroidManifest.xml
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt
- AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldControllerTest.kt
This PR updates the Android-Image-Cropper dependency to its latest version(4.2.1 at this time). The code related to cropping was migrated to the newer ActivityResultLauncher apis used by the library in its newer versions.
Closes #10710 
> Update image cropper library dependency to 4.2.1

- AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt
A small cleanup of a var inside the Whiteboard class, part of #11450 . This type of code with a declared var which gets incremented and used inside a while loop could be added as an example to the mentioned issue.
> Cleanup of var inside Whiteboard

- AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
- AnkiDroid/src/main/res/values/preferences.xml
- AnkiDroid/src/main/res/xml/preferences_dev_options.xml
Move options exclusive to debug builds to its own category from the bottom of advanced category. 
1. Create a XML layout with the previous debug options
2. Extract the debug options from the advanced category to the new one
https://user-images.githubusercontent.com/69634269/171644357-8adf8cf9-bd03-4f4d-b124-ffcb66fd3286.mp4
> [GSoC] Add `Developer options` category

- AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
Fix some deprecations on `Preferences.kt`
On the commits
> [GSoC] NF: Fix deprecations on `Preferences.kt`

- AnkiDroid/build.gradle
- AnkiDroid/src/main/java/com/ichi2/anki/ActionProviderCompat.kt
- AnkiDroid/src/main/java/com/ichi2/anki/CardInfo.kt
- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
- AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/UndoAction.kt
- AnkiDroid/src/main/java/com/ichi2/ui/RtlCompliantActionProvider.kt
- AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt
This PR update the core-ktx dependency to the latest version(1.8.0 at this moment). This update produces some build errors due to some changes into the declared nullability in the library api:
- ActionProvider declares now onCreateActionView() as returning a non null value, I changed all the overrides to throw an error(to catch any issues now) which should be safe as the platform uses the version which takes a MenuItem
- IconCompat.createWithResource() now requires a non null Context which can be provided safely from where the method was used(DeckPicker.createIcon -> DeckPickerContextMenu)
- ConfigurationCompat.getLocales().getLocale() is declared now to return a nullable value, I added `!!` to keep the current code intact
- MenuItemCompat declares getActionProvider() now as returning a …
> Update androidx.core:core-ktx dependency to 1.8.0

- AnkiDroid/build.gradle
- AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
- AnkiDroid/src/main/java/com/ichi2/anki/services/NotificationService.kt
- AnkiDroid/src/main/java/com/ichi2/widget/WidgetStatus.kt
This PR removes the LocalBroadcastManager which was deprecated and replaces it with LiveData. So instead of the old system, now the application class has a LiveData field on which other parts of the code(WidgetStatus) can send an event to indicate that a notification should be shown.
The NotificationService was refactored to extract the code from onReceive into a method(no changes here just basic copy to a new method) so it can be called by the application class directly when a notification should be shown.
Closes #10185 
Closes #10183 
Ran the usual tests, and notifications seem to appear like normal. Keep in mind that I don't use the notification system at all with AnkiDroid so take extra care with reviewing.
> Remove deprecated LocalBroadcastManager

- AnkiDroid/src/main/java/com/ichi2/anki/LanguageUtils.kt
- AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
- AnkiDroid/src/main/res/values/01-core.xml
- AnkiDroid/src/main/res/values/10-preferences.xml
- AnkiDroid/src/main/res/values/preferences.xml
- AnkiDroid/src/main/res/xml/preference_headers.xml
- AnkiDroid/src/main/res/xml/preferences_advanced.xml
- AnkiDroid/src/main/res/xml/preferences_general.xml
- AnkiDroid/src/main/res/xml/preferences_sync.xml
- AnkiDroid/src/test/java/com/ichi2/anki/PreferencesSimpleTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/PreferencesTest.kt
Create a separate preferences category for the sync preferences
On the commits
<details><summary>On my phone</summary>
</details>
> [GSoC] Extract sync preferences to a new category

- AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/MigrateUserData.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/ExecutorTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MockMigrationContext.kt
An executor allows execution of a list of operations and preemption
Primarily to ensure that the reviewing experience is not delayed if the scoped storage migration is going on the background.
This allows a single folder to be specified, removing any additional code complexity in the reviewer, and instead taking it on in the migration path: via prioritizing a 'reviewer initiated file copy'
#5304
Unit tested
> Scoped Storage: Execution of a list of Operations + preemption

- lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.kt
> Replaced String.format in FixedPreferencesTitleLength

- AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
- AnkiDroid/src/main/res/layout/activity_load_pronounciation.xml
- AnkiDroid/src/main/res/layout/reviewer_flashcard.xml
- AnkiDroid/src/main/res/layout/reviewer_flashcard_fullscreen.xml
- AnkiDroid/src/main/res/layout/reviewer_flashcard_fullscreen_noanswers.xml
- AnkiDroid/src/main/res/layout/reviewer_fullscreen_noanswers.xml
- lint-release.xml
This PR enables the MergeRootFrame lint check. There were some violations:
- activity_load_pronunciation.xml  I suppresed this violation as it will become invalid in the future. At this moment LoadPronunciationActiviy creates some views in its onCreate() method and then adds them to this layout, those views can and should be added directly to the layout which will make the current violation invalid
- reviewer_*.xml switched to using the merge tag. The replaced FrameLayout had the role of taking placement layout rules according to the user settings, after replacing it with the merge tag I replicated taking those layout rules for each of the child views.
Closes #10502 
Closes #10550 
Ran the usual tests. I tested the reviewer layouts and the functionality seems the same.
> Enable MergeRootFrame lint check

- AnkiDroid/src/main/AndroidManifest.xml
- AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
- AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
- AnkiDroid/src/main/java/com/ichi2/themes/Themes.kt
Beta is coming, time to pay for my sins and fix my errors.
Fixes #10619
On learning ↓
https://user-images.githubusercontent.com/69634269/172047099-361b80e6-3e25-4c4e-9519-1c2afa398be8.mp4
If you want to create a light/dark theme, you just need to use one of the `.DayNight` theme variantes as your theme's parent, then create a `values-night` (even Google is inconsitent with `light/dark` and `day/night` naming) folder where you should put your dark variant of the theme, which should have the same name of the light one.
Then use https://developer.android.com/reference/androidx/appcompat/app/AppCompatDelegate#setDefaultNightMode(int) to tell if you want to follow system, always light or always dark
This works quite well if you ***DON'T want to mix themes***, i.e. your light theme will always …
> Fix `follow system dark mode` on custom/auto schedule

- AnkiDroid/build.gradle
- AnkiDroid/src/main/res/values-ldrtl/styles.xml
- AnkiDroid/src/main/res/values/styles.xml
Material's FAB replaced it a long time ago and the its style settings, so it doesn't have a use and should be removed
Remove the related code
Emulator on API 25
https://user-images.githubusercontent.com/69634269/172067969-64ddb46e-2066-49ab-bac6-a5fe0272c14f.mp4
https://user-images.githubusercontent.com/69634269/172067971-bf19aa9f-e4c4-491f-b0d2-45a5ac3fd477.mp4
> NF: Remove getbase:floatingactionbutton dependency

- AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Remove the need for a var variable in two locations inside NoteEditor.
Part of #11450 
> Remove some vars in NoteEditor

- AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
- AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
- AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt
When using a [shortcut](https://developer.android.com/guide/topics/ui/shortcuts) for review, we may need to inform the user when exiting the activity:
- If we successfully completed the review (otherwise the user is surprised of the sudden exit #10841)
- If there's nothing to review (otherwise the user doesn't understand why the app just opens and closes #10840)
The shortcuts were recently introduced with #8648.
Fixes #10841: display a message when the review is completed
fixes (partially) #10840: display a message when no card to review (but ideally the message should be "no cards to review" rather than "review finished")
As suggested [here](https://github.com/ankidroid/Anki-Android/issues/8648#issuecomment-822581182), use a Toast to inform the user.
#10840 and #10841 suggested to return …
> fix: exit message when using the review shortcut

- build.gradle
- gradle.properties
Building the app was slow if with `in_process` as compiler strategy, but we need `in_process` for CI builds
Fixes #11575
- Set the compiler strategy only on CI builds, as written [here](https://github.com/ankidroid/Anki-Android/issues/11575#issuecomment-1151239413)
- Compare times before and after the change by this fix (8x speed improvement)
- Build the app on Android Studio
- Create a comment just to change anything and build the app again
To test CI, I've run CI on my fork and checked if Windows unit-test don't timeout (I suppose that was the problem without `in_process`
https://github.com/BrayanDSO/Anki-Android/runs/6843632189?check_suite_focus=true#step:7:19
https://github.com/BrayanDSO/Anki-Android/runs/6843502303?check_suite_focus=true#step:7:19 …
> Use IN_PROCESS compiler strategy only on CI builds

- build.gradle
Ingest the latest version of anki-android-backend
Includes one actual functional fix to counts (related to #11599) and otherwise a huge pile of dependency updates: https://github.com/ankidroid/Anki-Android-Backend/releases/tag/0.1.11
This moves closer to unblocking #11599
Just bumping the dependency after publishing it to maven-central and testing it locally
API31 and API25 (the lowest that works, sadly) emulator locally, `./gradlew clean jacocoTestReport --rerun-tasks`
If you open the collection with the V16 test code and leave the collection in /sdcard/AnkiDroid, you will get some bizarre errors like https://github.com/protocolbuffers/protobuf/issues/8956 and as far as I know, there is known good resolution, which is frustrating and vague to figure out.
_Please, go through these checks …
> build(deps): use anki-android-backend:1.1.11

- AnkiDroid/build.gradle
Makes it clearer that a testImplementation is also required
> Clarify instructions in backend library requirements

- AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java
- AnkiDroid/src/main/java/com/ichi2/libanki/backend/DroidBackendFactory.kt
Original fix attempt and discussion at https://github.com/ankidroid/Anki-Android-Backend/issues/193
~~Depends on https://github.com/ankidroid/Anki-Android/pull/11581~~
> Switch sqlite temp storage to disk; fix failures in V16

- AnkiDroid/src/main/AndroidManifest.xml
- AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
- AnkiDroid/src/main/res/values/04-network.xml
To keep consistency.
`Settings` is the best option because it is a 01-core.xml's string and therefore more translated
Fixes #11608, fixes #11267
> Use `Settings` string instead of `Preferences`

- AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
At the moment the _Scroll Toolbar_ menu item in note editor doesn't properly follow its backing preference. You can see this by going to the note editor, unchecking/checking this menu item, leaving the editor and then coming back. This PR fixes this bug by updating the menu item's check status from the preferences when setting up the toolbar menu.
> Fix NoteEditor "Scroll toolbar" menu item sync bug

- AnkiDroid/src/main/java/com/ichi2/anki/Statistics.kt
- AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.kt
AsyncTask to coroutines migration
Replaced the usage of AsyncTask to create a chart with the suspend function. Since with coroutines we can easily switch context between the main and background thread, there is no need for a callback-based approach. 
Runs as expected on Realme 6i
https://user-images.githubusercontent.com/69595691/172148243-bd5180e7-a201-4816-9695-61a68c84d2f8.mp4
https://user-images.githubusercontent.com/69595691/172148207-af2cdad3-ef88-46dd-8d37-c0db10433265.mp4
Use of [Mutex](https://kotlinlang.org/docs/shared-mutable-state-and-concurrency.html#mutual-exclusion) for thread safety on critical section with suspending functions.
> [GSoC] migrated AnkiStatsTaskHandler.createChart() to suspend function

- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/SyncErrorDialog.kt
SyncErrorDialog: remove multiple type declarations after `_`
> SyncErrorDialog: remove multiple type declarations after `_`

- AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.kt
All instances of CollectionUtils.getLastListElement() needs to be replaced with last() for cleanup.
Look at [this](https://github.com/ankidroid/Anki-Android/pull/11388/files#r877560222) comment to know why this needs to be replaced.
> Replaced CollectionUtils.getLastListElement() with last() in FinderTest.

- AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
- AnkiDroid/src/main/java/com/ichi2/anki/preferences/NotificationsSettingsFragment.kt
- AnkiDroid/src/main/res/values/preferences.xml
- AnkiDroid/src/main/res/xml/preference_headers.xml
- AnkiDroid/src/main/res/xml/preferences_general.xml
- AnkiDroid/src/main/res/xml/preferences_notifications.xml
Extract notifications preferences to a new category
1. Extract them from `General`
2. Create a new fragment
3. Build a summary based on them
> [GSoC] Extract notifications preferences to a new category

- AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
- AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.kt
This PR extracts the strings used as preferences keys in NoteEditor to constants for easier usage and to avoid bugs.
> Extract NoteEditor preferences strings as constants

- AnkiDroid/src/androidTest/java/com/ichi2/anki/reviewer/PeripheralKeymapTest.kt
- AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
- AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
- AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/Gesture.kt
- AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/GestureProcessor.kt
- AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.kt
- AnkiDroid/src/main/java/com/ichi2/anki/reviewer/AnswerButtons.kt
- AnkiDroid/src/main/java/com/ichi2/anki/reviewer/AutomaticAnswer.kt
- AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
- AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt
- AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerCommandTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerSoundRenderTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/ReviewerNoParamTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/GestureProcessorTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/reviewer/AnswerButtonsTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/reviewer/AutomaticAnswerActionTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/reviewer/PeripheralKeymapTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicemodel/UpgradeVolumeButtonsToBindingsTest.kt
They were redundant as the class is a Enum called ViewerCommand
And avoids wasting processing when building the preferenceKey
Unit tests (especially https://github.com/ankidroid/Anki-Android/blob/main/AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/ViewerCommandTest.kt#L26)
> [GSoC] NF: Remove COMMAND_ prefix from ViewerCommand

- AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AbstractFlashcardViewer: remove multiple type declarations after `_`
> AbstractFlashcardViewer: remove multiple type declarations after `_`

- .idea/dictionaries/anki.xml
- AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Removing all warnings from the sidebar. IDE suggestions mostly
* Redundant SAM-constructor
* onActivityResult overrides deprecated member but not marked as deprecated itself.
* 'getCurrentMultimediaEditableNote' always returns non-null type
* Explicitly given type is redundant here
* Function "getFieldByIndex" is never used
* Function "previewNextClozeDeletion" is never used
* Class "Field" is never used
* Unnecessary non-null assertion (!!) on a non-null receiver
* Boolean literal argument without a parameter name
* Cascade 'if' should be replaced with 'when'
* Use of setter method instead of property access syntax
* Replace negated 'isEmpty' with 'isNotEmpty'
* Should be replaced with Kotlin function
* Can be joined with assignment
* Local variable names should not contain underscores
* …
> lint: Note Editor

- AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/stats/AnkiStatsTaskHandlerTest.kt
- lint-release.xml
Adds in lint check and fixes error message
Previous Error was:
```
java.lang.UnsatisfiedLinkError: 'long net.ankiweb.rsdroid.NativeMethods.openBackend(byte[])'
at net.ankiweb.rsdroid.NativeMethods.openBackend(Native Method)
...
```
The `Error` is only thrown in the case that Robolectric is used
> fix: Improve error if super.setUp() not called

- AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
- AnkiDroid/src/main/res/drawable/ic_code.xml
- AnkiDroid/src/main/res/drawable/ic_notifications.xml
- AnkiDroid/src/main/res/drawable/ic_touch.xml
- AnkiDroid/src/main/res/values/attrs.xml
- AnkiDroid/src/main/res/values/theme_black.xml
- AnkiDroid/src/main/res/values/theme_light.xml
- AnkiDroid/src/main/res/values/theme_plain.xml
- AnkiDroid/src/main/res/xml/preference_headers.xml
Icons are pretty
- Add some icons
- Add their colors (textColor for light, dark and black; primary for plain)
Gestures category not updated because it will be removed with #11647
> [GSoC] Add categories icons

- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
- AnkiDroid/src/main/res/layout/activity_load_pronounciation.xml
LoadPronunciationActivity was extending Activity before & I don't really see why it should not be using AnkiActivity.
> LoadPronunciationActivity now extends AnkiActivity

- AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
- AnkiDroid/src/main/java/com/ichi2/anki/preferences/AccessibilitySettingsFragment.kt
- AnkiDroid/src/main/res/drawable/ic_accessibility_24.xml
- AnkiDroid/src/main/res/values/10-preferences.xml
- AnkiDroid/src/main/res/values/preferences.xml
- AnkiDroid/src/main/res/xml/preference_headers.xml
- AnkiDroid/src/main/res/xml/preferences_acessibility.xml
- AnkiDroid/src/main/res/xml/preferences_appearance.xml
- AnkiDroid/src/main/res/xml/preferences_reviewing.xml
1. Move `New time zone handling` and `Double tap time` to a subcategory called `Advanced`
2. Rename `behavior` subcategory to `scheduling`
3. Remove Whiteboard stroke width preference
4. Create a new subcategory called `Accessibility` on Appearance and move some of the reviewing preferences there
5. Create a new subcategory called `Reviewer` on Appearance and move some of the reviewing preferences there
6. Build Reviewing category from other strings
https://user-images.githubusercontent.com/69634269/174076398-4c62ad02-a4a0-4dc7-bcbb-13d951e68d25.mp4
> [GSoC] Reorganize reviewing preferences

- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
fix: `setOnNavigationItemSelectedListener` deprecation in CardTemplateEditor
https://stackoverflow.com/a/68412210/9062752
> Fix:  deprecation in CardTemplateEditor

- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/beolingus/parsing/BeolingusParser.kt
Fixed: `toLowerCase` deprecation in BeolingusParser
used `lowercase` instead of `toLowerCase`
> fix: `toLowerCase` deprecation in BeolingusParser

- AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
fix: `setBackgroundDrawable` deprecation in FieldEditText
Following this approach : https://stackoverflow.com/a/18844271/9062752
> fix: deprecation in FieldEditText

- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/ImageField.kt
change the way strings are formatted to improve code quality
Part of #11449 
change ```String.format("%s",file.name)``` to ```${file.name}```
Passed all the test done by  "./gradlew jacocoUnitTestReport"
> replaced the format in ImageFilled.kt

- AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
- AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt
- AnkiDroid/src/main/res/values/preferences.xml
- AnkiDroid/src/main/res/xml/preferences_controls.xml
Part of the process of getting rid of `setTargetFragment` deprecation
On the commits
Used the control preferences on the app
> [GSoC] NF: clean ControlPreference.kt

- AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
- AnkiDroid/src/main/java/com/ichi2/anki/CardInfo.kt
- AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
The sole purpose of the deprecation is to force to use `finishWithAnimation` our `finishWithoutAnimation`, methods which create the possibility of disabling the animations on E-ink devices
But this didn't block uses of `requireActivity().finish()` or `(x as Activity).finish()`, some animations would show regardless of the E-ink setting
Removing the deprecation and setting it to use the default animation fixes the problem while keeping `finish()` default behavior
Emulator on SDK 25.
1. Enable safer display mode on Advanced
2. Change theme
3. (no animation should appear)
> NF: Remove AnkiActivity.finish() deprecation

- AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartView.kt
- AnkiDroid/src/main/java/com/wildplot/android/rendering/graphics/wrapper/GraphicsWrap.kt
- lint-release.xml
This PR enables the DrawAllocation lint check. There were violations in ChartView.onDraw(), I moved the instantiations outside the method and  setup the objects to be reset every onDraw call. I changed GraphicsWrap's constructor to have the constructor properties as lateinit, this should be fine as the class is only used from onDraw() and it's also stateless.
Closes #10488 
Closes #10499
> Enable DrawAllocation lint check

- AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java
- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
- AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CreateDeckDialogTest.kt
Search Decks Icon would not change (show or unshow) if deck count was changed (added or deleted) unless app was restarted
Fixes #11112
Since after DeckList was changed, `renderPage()` will be called, added a deckcount check there and if deckcount was 9 or 10 it would invalidate options menu. Also added the visibility update to `onPrepareOptionsMenu`.
https://user-images.githubusercontent.com/59933477/165406059-c0a6c3d9-4da0-483b-9534-1747f4baee35.mov
> Fixed SearchDecks Icon visibility not updating if DeckCount changed

- AnkiDroid/src/main/java/com/ichi2/libanki/ModelManager.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/Models.java
- AnkiDroid/src/main/java/com/ichi2/libanki/ModelsV16.kt
Create a function to return the names of all the note models being used
Create a new function to return a list of names of all the models
TODO
> [GSoC] Filter Sheet: Create function to retrieve names of all models

- .github/workflows/stale.yml
- .github/workflows/sync_translations.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: nathannaveen <42319948+nathannaveen@users.noreply.github.com>
> chore: Set permissions for GitHub actions

- AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
- AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
Changing dark mode would restart the activity on the initial screen instead of the the one the user was at
+ cleanups
On the commits
On my phone by changing configuration (e.g. dark mode)
> [GSoC] Refactor preferences fragments initialization

- AnkiDroid/src/main/java/com/ichi2/themes/Themes.kt
`TypedArray.getColor` is defined as returning `ColorInt`
We can't do this for the overload which returns an array
> chore: add ColorInt annotation

- AnkiDroid/src/main/res/drawable/ic_flag_blue.xml
- AnkiDroid/src/main/res/drawable/ic_flag_green.xml
- AnkiDroid/src/main/res/drawable/ic_flag_orange.xml
- AnkiDroid/src/main/res/drawable/ic_flag_pink.xml
- AnkiDroid/src/main/res/drawable/ic_flag_purple.xml
- AnkiDroid/src/main/res/drawable/ic_flag_red.xml
- AnkiDroid/src/main/res/drawable/ic_flag_turquoise.xml
- AnkiDroid/src/main/res/values/colors.xml
- AnkiDroid/src/main/res/values/theme_black.xml
- AnkiDroid/src/main/res/values/theme_dark.xml
To make the text on flagged cards more readable
Fixes #11671 
Choose shades of colors that pass the accessibility scanner
> Change flag colors for light and dark themes for better accesibility 

- AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java
- AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt
- AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.kt
- AnkiDroid/src/main/res/xml/preferences_appearance.xml
Fix some details on follow system night mode
On the commits
On the commits
If anyone knows another important activity that doesn't inherit from AnkiActivity, let me know
On my phone
onConfigurationChanged is only triggered in the top activity. Probably the current approach wouldn't be necessary if the app used an main activity for with fragments for most screens.
> Night mode fixes

- AnkiDroid/src/main/res/layout/reviewer_fullscreen.xml
Make fullscreen reviewer occupy system bars
There are two fullscreen modes:
* Hide system bars
* Hide system bars and answer buttons
Both of these hide the system bars. However, the former, unlike
the latter, wasn't occupying the space liberated by those.
Fixes #11747
~~I had to add 13 new classes and a custom annotation processor~~ One xml attribute removed.
Tested on my devices running Android 11 and Android 7. Before & after
> Make fullscreen reviewer occupy system bars

- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Remove extra whitespace in collection synchronized dialog. You see this dialog a lot when syncing with Anki's sync server, as it does not support syncing media yet.
Reverted the statement to what it was before being converted to Kotlin.
Tested on my device running Android 11. Before & after
> Remove extra whitespace in collection synchronized dialog

- AnkiDroid/src/main/java/com/ichi2/async/Connection.kt
Fix error
Fixes #11760
As @oakkitten mentioned, the error was fixed by setting `Companion.isCancelled` to `false` at the start of sync
Emulator:
https://user-images.githubusercontent.com/59933477/177013232-da508b13-265b-4382-8577-16d3a7ac3709.mov
> Fix Sync Cancel causing error on resync

- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.kt
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/RecursivePictureMenu.kt
Help Dialog would crash if "Don't keep activities" was on and anki was minimized and expanded
Fixes #10942 
Same as #10964
Emulator:
https://user-images.githubusercontent.com/59933477/177012633-391d3492-2cd4-4f28-b61c-e475a786f7df.mov
> help dialog crash dont keep activity

- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/LoadPronunciationActivity.kt
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/beolingus/parsing/BeolingusParser.kt
- AnkiDroid/src/main/res/values/16-multimedia-editor.xml
In Pronunciation, If a string with more than one word was entered, the proper error toast wouldn't show up
Fixes #11748 
Added toast in LoadPronunciationActivity::DownloadFileTask for if `source` is more than one word
> Add Toast for "max one word" pronunciation

- lint-release.xml
Added in edaf6febd0aaf4c2ce6baea52d7f0a3912b39381
Forgot to remove the 'ignore'
> fix: remove duplicate "TextFields" lint

- AnkiDroid/build.gradle
- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
- AnkiDroid/src/main/java/com/ichi2/anki/Statistics.kt
- build.gradle
I've extracted the version number for the fragments library into the main build to make it easier to upgrade the two connected artifacts. To fix the deprecation in the new version I used the recommended approach [from the docs](https://developer.android.com/jetpack/androidx/releases/activity#1.4.0-alpha01)(moving the current code from the old platform methods onCreateOptionsMenu/onOptionsItemSelected to the methods in MenuProvider).
In Statistics the setHasOptionsMenu() calls  were useless as the fragments didn't contribute to the menu with any items.
Closes #11742 
Closes #11743 
Ran the usual tests, checked the menus.
More info about the new APIs in [this video](https://io.google/2022/program/c9085b18-4e8e-4183-b303-1d1716b0c070/) from Google IO.
> Bump fragments library dependency to 1.5.0

- AnkiDroid/src/test/java/com/ichi2/utils/TagsUtilTest.kt
cleanup: Converting all Arrays.asList() functions to listOf() functions in TagsUtilTest
> Cleanup: TagsUtilTest

- AnkiDroid/src/test/java/com/ichi2/misc/LintReleaseFileTest.kt
Adds a small test to check for duplication in _lint-release.xml_ by parsing the lint release file directly.
Closes #11769 
Ran the tests and duplicated some lint issues in lint-release.xml to check. Also caught the duplication in #11768 as I wrote the code before the fix.
> Add test to check for duplication in lint-release.xml

- AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
- AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
- AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt
- AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt
Pasting plain text from samsung native browser into note fields wouldn't work.
Fixes #11574
rewrote `FieldEditText::onTextContextMenuItem` to paste as plain text using `coerceToText` in `primaryClip.getItemAt(0).coerceToText(context)`.
Tested on real device:
https://user-images.githubusercontent.com/59933477/174403631-6412f7dc-07a6-4d67-9b02-7132795fd2b0.mp4
> Fix paste from browser into note field not working

- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.kt
The update of the material dialogs library to the latest version introduced a bug which triggered an incorrect action in response to user selection in DeckPicker's context menu. The previous code used the index of the item selected from the context menu dialog against a list of known actions, this will not work as the list of actual options used in the content menu is dynamic.
Fixes #11786 
Verified that the correct action is done in response to user selection in DeckPicker's context menu.
> Fix context menu selection for DeckPicker

- AnkiDroid/src/main/java/com/ichi2/libanki/sched/Counts.kt
- AnkiDroid/src/test/java/com/ichi2/anki/InitialActivityTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/CardTemplateTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/dialogs/utils/HelpDialogTest.kt
- AnkiDroid/src/test/java/com/ichi2/libanki/CardTest.kt
- AnkiDroid/src/test/java/com/ichi2/utils/JSONObjectTest.kt
- lint-release.xml
Stemmed from a code review where `.count()` was unnecessarily called
Realised that Kotlin didn't check `@CheckResult` by default, and we hadn't enabled the lint
Then did some cleanup on `Counts()`
> lint: enable CheckResult & Kotlin Cleanup on `Counts`

- AnkiDroid/src/main/java/com/ichi2/anki/ReadText.kt
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserOrderDialog.kt
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardSideSelectionDialog.kt
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportDialog.kt
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/IntegerDialog.kt
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ModelBrowserContextMenu.kt
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ModelEditorContextMenu.kt
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ScopedStorageMigrationDialog.kt
- AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/Toolbar.kt
- AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt
At the moment running `lint` over the main branch fails because of `@ CheckResult`  for code related to material dialogs(the new version of material dialogs library added `@ CheckResult` to most of its methods and David enabled this check recently). I went over the failures and added `@ SupressLint` to the methods or, when possible, to dialog declared variables.
Lint checks succeed.
> Fix code style checks failures due to @CheckResult

- AnkiDroid/src/test/java/com/ichi2/anki/servicemodel/PreferenceUpgradeServiceTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicemodel/UpgradeGesturesToControlsTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicemodel/UpgradeGesturesToControlsTestNoParam.kt
This PR fixes the initialization of the tests related to preferences by properly binding them to the RobolectricTest superclass initialization. Hopefully, this would fix the flakiness of these tests, if not the last commit can be reverted to mark the tests as ignored. I'll be monitoring the PRs for failures related to this, if you see a failure please ping me(if they do fail I want to try something else as I have another theory why they fail).
Ran the unit tests.
> Fix tests related to preferences

- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
Fixes the context menu in CustomDialog's context menu.This happened because the index of the user selected option wasn't properly mapped to a valid option in the source code.
Fixes #11801 
Ran the tests, checked that the menu works.
> Fix context menu in CustomStudyDialog

- AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Fixes the missing functionality in NoteEditor's toolbar options. Also adds the `horizontalPadding` attribute for the dialog's  customView to match the previous(before the material library update) UI.
Fixes #11806 
Ran the tests, manually checked the menus that they work.
> Fix functionality for dialogs of NoteEditor toolbar

- AnkiDroid/src/androidTest/java/com/ichi2/anki/FieldEditLineTest.kt
refactor: make `fieldEditLine` as a function in FieldEditLineTest
> refactor: make `fieldEditLine` as a function in FieldEditLineTest

- AnkiDroid/src/androidTest/java/com/ichi2/ui/ActionBarOverflowTest.kt
\## Purpose / Description
Kotlin cleanup: `is` -> `equalTo` in ActionBarOverflowTest
> cleanup: ActionBarOverflowTest

- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt
Some custom views used inside MaterialDialogs didn't properly set their vertical padding. In another PR I'm going to review this issue with padding for material dialogs to fix any other problems.
Before & after tags dialog:
Before & after move dialog:
Fixes #11804
Checked the UI and the padding is no more.
> Fix some of the issues with material dialogs vertical padding

- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportDialog.kt
Fixes #11810 
add `allowEmptySelection = true` to the MaterialDialog builder to enable it
> ExportDialog "ok" button disabled fix

- AnkiDroid/src/main/java/com/ichi2/libanki/DecksV16.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/ModelsV16.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/importer/BackendCsvImportV16.kt
New `Import CSV` UI will be used for importing `csv/tsv` file. So, `getNotetypeNamesRaw`, `getDeckNamesRaw`, and `getCsvMetadataRaw` needed in V16 backend (newBackend).
For each `backend` function wrapped in function with input of type ByteArray and return type of ByteArray.
No test added for it but I have tested locally using this PR https://github.com/krmanik/Anki-Android/pull/23
https://github.com/krmanik/Anki-Android/pull/23
> Implementation for getting data for import csv

- AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
Replaces usages of `SharedPreferences.edit().apply()` with the newer kotlin friendly `SharedPreference.edit{}` extension for consistency in PreferencUpgradeService class.
> Refactor PreferenceUpgradeService to use prefs.edit{} extension

- AnkiDroid/src/test/java/com/ichi2/anki/servicemodel/UpgradeGesturesToControlsTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicemodel/UpgradeGesturesToControlsTestNoParam.kt
Reverting commit 7752cf62 as the tests are still failing.
> Revert "Enable the preferences tests which were ignored for being flaky"

- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
Small tweak to the incompatible database version dialog to allow direct selection for its list items.
Fixes #11811 
Ran the tests, checked that the dialog works.
> Fix selection in incompatible database version dialog

- AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.kt
- AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/LocaleSelectionDialog.kt
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
Fix padding issues for dialogs after the update of the material dialogs library. This follows the padding that existed before the library update.
Custom study dialogs before and after:
LocalSelectionDialog before and after:
ModelBrowser dialog:
ModelFieldEditor dialogs:
Ran tests, checked the menus
> Fix padding for material dialogs

- README.md
I also renamed it to "code contributor", as I feel it's a more exact description. Github is technically true, but not really interesting. Also, technically, translations also ends on github, and the authors are not listed
> Removing duplicate "contributor"

- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/beolingus/parsing/BeolingusParser.kt
cleanup: remove comment in BeolingusParser.kt
removing the comment as the `.toLowerCase()` is not used in BeolingusParser anymore. Instead it is now being handled in `LoadPronunciationActivity` itself.
> remove extra comment in BeolingusParser

- AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
`col.buildSearchString` was getting an empty node, thus raising the error. This takes care of it by returning early if the search is empty.
Side Note: Should `buildSearchString` handle empty nodes?
Fixes #11872 
This takes care of it by returning an empty string early if the search is empty, so `buildSearchString` is not called
Manually on my phone
https://user-images.githubusercontent.com/86671025/179385476-99fa997d-e242-474e-b113-a8abf151d195.mp4
_Please, go through …
> Fix Apply button crashing on no selection

- AnkiDroid/src/main/res/values/preferences.xml
- AnkiDroid/src/main/res/xml/preference_headers.xml
- AnkiDroid/src/main/res/xml/preferences_advanced.xml
- AnkiDroid/src/main/res/xml/preferences_appearance.xml
- AnkiDroid/src/main/res/xml/preferences_controls.xml
- AnkiDroid/src/main/res/xml/preferences_custom_buttons.xml
- AnkiDroid/src/main/res/xml/preferences_custom_sync_server.xml
- AnkiDroid/src/main/res/xml/preferences_general.xml
- AnkiDroid/src/main/res/xml/preferences_sync.xml
Biggest part of #10423. Only the keys of Deck Options remain
Lint
> [GSoC] NF: Move all preferences keys to constants on preferences.xml

- AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
- AnkiDroid/src/main/res/drawable/ic_flag_transparent.xml
`ic_flag_transparent.xml` was already being used for the flag icon on the app bar, and using it for the  `No flag` option in the filter sheet broke it.
Fixes #11868 
Revert `ic_flag_transparent.xml` to its original state, and use a different drawable resource for the `No flag` option
> Fix Flag Colors on App Bar

- AnkiDroid/src/main/res/xml/preferences_custom_buttons.xml
~~On top of #11866. Only the last commit is new. I'll rebase once that is merged~~
I forgot to add the summary providers for the custom buttons screen when I did the XXX summary replacement PRs
> [GSoC] Fix App bar buttons screen summaries

- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
This dialog shows a list of backups from which the user can choose and a button("Choose another") to select a backup from the file system. Using `listItemsSingleChoice` disables the positive button if initialSelection is not set.
Fixes #11883 
Checked the availability of the button in the dialog.
> Fix disabled "Choose another" button in the restore backup dialog

- AnkiDroid/src/main/AndroidManifest.xml
- AnkiDroid/src/main/res/layout/deck_picker_dialog.xml
- AnkiDroid/src/main/res/layout/deck_picker_dialog_list_item.xml
We fix the default theme, then fix a single screen which was flagged as being bad
Maybe #11878 - reviewer's choice
API 31 emulator
Comments from: https://github.com/ankidroid/Anki-Android/issues/11878#issuecomment-1186546310
https://developer.android.com/guide/topics/manifest/application-element#theme
* `layout/toolbar` means we can't set the preview for title/menu, it may not be a worthwhile abstraction (and we may want a custom `View` instead)
> fix: Android Studio Designer + deck_picker_dialog

- AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java
Allow to improve card browser's note mode by ensuring that one card by note is
directly queried.
This is temporary code, since back-end will ensure we get this feature
efficiently in Rust.
> NF: findOneCardByNote

- AnkiDroid/src/main/java/com/ichi2/libanki/stats/BackendStats.kt
The `setGraphPreferencesRaw` should return `ByteArray`
Updated existing implementation
> Change return type for `setGraphPreferencesRaw` to bytetarray

- AnkiDroid/src/main/res/color/prefs_item_dark_secondary.xml
- AnkiDroid/src/main/res/color/prefs_item_light_secondary.xml
- AnkiDroid/src/main/res/values/theme_black.xml
- AnkiDroid/src/main/res/values/theme_dark.xml
- AnkiDroid/src/main/res/values/theme_light.xml
- AnkiDroid/src/main/res/values/theme_plain.xml
Preferences textColorSecondary used the same color as the primary
1. Add a selector for secondary color for light and dark themes
2. Change light themes secondary color to material gray 700 because it was barely distinguishable from the textColorPrimary
> Fix styles textColorSecondary

- .idea/dictionaries/usernames.xml
- AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt
- AnkiDroid/src/main/java/com/ichi2/utils/TypedFilter.kt
- AnkiDroid/src/test/java/com/ichi2/anki/DeckAdapterFilterTest.kt
Fixes issue where search bar was not filtering properly and crashing the app.
Fixes [#11877](https://github.com/ankidroid/Anki-Android/issues/11877)
Creates a copy of the list of decks before filtering. The error was caused by using the same list in filtering as in the UI. I also made a small optimization of the containsFilterString method as well as added error catching in TypedFilter in case error happens again.
Reproduced error using process described in the issue before and after code changes. Screenshot of results after code changes:
[Stack overflow post that helped me narrow the issue](https://stackoverflow.com/questions/41316886/concurrentmodificationexception-inside-publishresult-arrayadapter)
> Fix crash during deck filtering

- AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.kt
Bug fix- Sync fail due to NPE. I think this bug was introduced as a result of Kotlin Migration #11864 of Syncer.java and wasn't picked up by test.
May be a part of #11891, not sure.
Instead of retuning null from `useLim` return an empty array.
Unit tested and on Realme 6i API 30
After any change, make sure to test on real-device from your own side. Automated tests are not always enough. 🥲
https://user-images.githubusercontent.com/69595691/180387511-e4d1ac96-6ff0-4ceb-921d-2ae09003844c.mp4
> fixed NPE during sync

- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
In order to prevent the user navigating around the app with a null collection and then potentially crash the app
Fixes #11894
Add `.cancelOnTouchOutside(false)` to the database error dialog
On my phone
1. Replace `collection.anki2` with a empty file with the same name
2. Open the app
3. Try to cancel the dialog by touching outside it
> fix: Make the database error dialog not cancelable by outside touches

- AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
- AnkiDroid/src/main/java/com/ichi2/anki/preferences/NotificationsSettingsFragment.kt
- AnkiDroid/src/main/java/com/ichi2/preferences/NumberRangePreferenceCompat.kt
- AnkiDroid/src/main/res/xml/preferences_notifications.xml
~~On top of #11866. I should rebase once that is merged.~~
Preferences initialization was a bit messy. Every screen ran [initAllPreferences](https://github.com/ankidroid/Anki-Android/blob/abd1f8bfc316cdf11aba51af7bda7f5b05c493d7/AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt#L205) and [initPreference](https://github.com/ankidroid/Anki-Android/blob/abd1f8bfc316cdf11aba51af7bda7f5b05c493d7/AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt#L225) multiple times, making things quite hard to follow. 
To keep things tidy, concise, and keep the preferences' configuration responsability on themselves and on their screens, I've done some refactors on the preferences activity
1. Extract the preferences initialization to their screens on the `Init X preference individually` commits
- The …
> [GSoC] Refactor preferences initialization

- AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
- AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
- AnkiDroid/src/main/java/com/ichi2/anki/contextmenu/AnkiCardContextMenu.kt
- AnkiDroid/src/main/java/com/ichi2/anki/contextmenu/CardBrowserContextMenu.kt
- AnkiDroid/src/main/java/com/ichi2/anki/contextmenu/SystemContextMenu.kt
- AnkiDroid/src/main/java/com/ichi2/anki/preferences/AccessibilitySettingsFragment.kt
- AnkiDroid/src/main/java/com/ichi2/anki/preferences/NotificationsSettingsFragment.kt
- AnkiDroid/src/main/java/com/ichi2/anki/preferences/PreferenceUtils.kt
- AnkiDroid/src/main/res/values/10-preferences.xml
Continuation of #11873
Updating preferences was problematic, with [updatePreference](https://github.com/ankidroid/Anki-Android/blob/abd1f8bfc316cdf11aba51af7bda7f5b05c493d7/AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt#L438) being ran every time any preference is changed. Also, the preferences activity had the responsability of mananing methods of specific preferences, which isn't a good design (e.g. [this](https://github.com/ankidroid/Anki-Android/blob/abd1f8bfc316cdf11aba51af7bda7f5b05c493d7/AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt#L280))
To keep things tidy, concise, and keep the preferences' configuration responsability on themselves and on their screens, I've done some refactors on the preferences activity
1. Extract the preferences update to their screens on the …
> [GSoC] Refactor preferences update

- api/src/test/java/com/ichi2/anki/api/ApiUtilsTest.java
Related to bug #11917. It does not fix it as it do not ensure the API gets tested by CI.
I believe removing the tests is the good solution, as I don't believe any of the tested method should accept a nullable input today and that none of its usage expect a nullable answer
> Ensure unit test of API build and succeed

- AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
> Fix Answer Buttons Pos "None" hiding everything else

- AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Fixes #11848 
Set MenuItem's check to `isTruncated` in `CardBrowser#onCreateOptionsMenu`
https://user-images.githubusercontent.com/59933477/179094976-59350126-76d9-46f7-9fff-74c4b712215f.mov
> CardBrowser truncate check update on change deck

- AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
Fixes #11865
Fixed return of `FieldEditText#onTextContextMenuItem` to be `super` call rather than false
https://user-images.githubusercontent.com/59933477/180474860-44234a7b-fa50-48d4-8c63-46220f42303b.mov
> Fix FieldEditText context menu items not working

- AnkiDroid/src/main/java/com/ichi2/anki/preferences/SettingsFragment.kt
As I've commented on #9452:
Currently, the only place setTargetFragment is used is on Preferences.kt
It is necessary to use it, because AndroidX PreferenceDialogFragmentCompat calls getTargetFragment(). If this happens without setTargetFragment getting called before, it leads to a crash, which means that we can't exchange it to [setFragmentResultListener](https://developer.android.com/reference/androidx/fragment/app/FragmentManager#setFragmentResultListener(java.lang.String,androidx.lifecycle.LifecycleOwner,androidx.fragment.app.FragmentResultListener)) as well.
This is definitely a upstream problem, and the current best course of action is to suppress the warning and give a +1 to these issues on Google issue tracker:
https://issuetracker.google.com/issues/181793702 …
> [GSoC] NF: Add a comment explaining setTargetFragment deprecation suppression

- AnkiDroid/src/main/java/com/ichi2/anki/Statistics.kt
It was used a single time, so no need to keep it as a member. It even avoid requiring lateinit.
> NF: make Local mSlidingTabLayout

- AnkiDroid/src/main/java/com/ichi2/anki/preferences/AccessibilitySettingsFragment.kt
- AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt
- AnkiDroid/src/main/java/com/ichi2/anki/preferences/AppearanceSettingsFragment.kt
- AnkiDroid/src/main/java/com/ichi2/anki/preferences/GeneralSettingsFragment.kt
- AnkiDroid/src/main/java/com/ichi2/anki/preferences/HeaderFragment.kt
- AnkiDroid/src/main/java/com/ichi2/anki/preferences/PreferenceUtils.kt
- AnkiDroid/src/main/java/com/ichi2/anki/preferences/SettingsFragment.kt
- AnkiDroid/src/main/res/values/10-preferences.xml
- AnkiDroid/src/main/res/values/constants.xml
- AnkiDroid/src/main/res/xml/preference_headers.xml
- AnkiDroid/src/main/res/xml/preferences_accessibility.xml
- AnkiDroid/src/main/res/xml/preferences_advanced.xml
- AnkiDroid/src/main/res/xml/preferences_appearance.xml
- AnkiDroid/src/main/res/xml/preferences_dev_options.xml
- AnkiDroid/src/main/res/xml/preferences_general.xml
~~On top of #11919~~
This is the last preferences reorganization PR I want to do for GSoC. Previously I'd thought about moving all the preferences from Advanced to the other screens, but after thinking a while, I've come to the conclusion that the it's best to keep it as a bucket of "Things most users won't need or are really advanced, therefore they shouldn't dispute space with the relevant ones".
As an example we have `Simple typed answer formatting`, only useful if typed answer is used AND the typed answer uses Polytonic Greek characters AND older webviews are being used (see #7901 if you are curious).
Other preferences there will be gone some day (e.g. `Replace newlines with HTML` when the visual editor is implemented). Others can be moved to the activities they impact (e.g. `Default …
> [GSoC] Reorganize some preferences + refactors

- AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/TextNoteExporter.kt
- AnkiDroid/src/main/java/com/ichi2/utils/StringUtil.kt
- AnkiDroid/src/test/java/com/ichi2/utils/StringUtilTest.kt
Useless now that Kotlin's .trim() can be used
Exchange it with .trim()
Unit tests
> NF: Remove StringUtil.strip()

- AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
- AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt
- AnkiDroid/src/main/java/com/ichi2/anki/preferences/DevOptionsFragment.kt
- AnkiDroid/src/main/res/values/10-preferences.xml
- AnkiDroid/src/main/res/xml/preferences_advanced.xml
- AnkiDroid/src/main/res/xml/preferences_dev_options.xml
- The V16 pref is useful to testing in case the dev forgot to set `legacy_schema=false` on `local.properties` while not having to re-enable every time the app is reopened.
A tiny bit of #6772
On the commits
Emulator SDK 25
[untitled.webm](https://user-images.githubusercontent.com/69634269/183134062-0567319e-86a3-4bf0-ad59-d61f066f9273.webm)
(not so sure why Android Studio recording is getting dark, maybe I should buy a faster computer)
> [GSoC] Add `Use new backend` (persistent) preference

- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
- AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
- AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt
- AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.kt
It automatically commits on the end of the code block, similar to what `.edit{}` does with sharedPreferences
cleanup
Hasn't
From androidx.app.FragmentManager
```kotlin
/**
* Run [body] in a [FragmentTransaction] which is automatically committed if it completes without
* exception.
*
* The transaction will be completed by calling [FragmentTransaction.commit] unless [allowStateLoss]
* is set to `true` in which case [FragmentTransaction.commitAllowingStateLoss] will be used.
*/
public inline fun FragmentManager.commit(
allowStateLoss: Boolean = false,
body: FragmentTransaction.() -> Unit
) {
val transaction = beginTransaction()
transaction.body()
if (allowStateLoss) {
transaction.commitAllowingStateLoss()
} else {
transaction.commit()
}
}
``` …
> NF: Exchange `.beginTransaction` for `.commit`

- AnkiDroid/src/main/java/com/ichi2/anki/preferences/AccessibilitySettingsFragment.kt
- AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedStatisticsSettingsFragment.kt
- AnkiDroid/src/main/java/com/ichi2/anki/preferences/ReviewingSettingsFragment.kt
- AnkiDroid/src/main/java/com/ichi2/preferences/NumberRangePreferenceCompat.kt
- AnkiDroid/src/main/java/com/ichi2/preferences/SeekBarPreferenceCompat.kt
- AnkiDroid/src/main/res/xml/preferences_accessibility.xml
- AnkiDroid/src/main/res/xml/preferences_advanced_statistics.xml
- AnkiDroid/src/main/res/xml/preferences_reviewing.xml
It's better to keep the UI configuration as much as possible on the XMLs, so this is a step toward this goal.
On the commits
Ran the app and saw if everything was the same way as before
For some unknown reason (I've discovered by chance), getAttributeResourceValue only works for the custom namespace if "http://schemas.android.com/apk/res-auto" is set as namespace too.
Actually we should declare attributes on `attrs.xml` and get rid of the custom namespace everywhere. But I'm not doing this today (nor in the near future, as this envolves fixing DeckOptions and FilteredDeckOptions's prefs too)
> [GSoC] refactor: Migrate preferences formatted summaries configuration to the XMLs

- AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
It is set to a String in both constructors. This is the only case currently where DB may receive a null value. Ensuring its lateinit remove this constraint, freeing DB.java conversion
> `data` in Card is lateinit

- pre-commit
Fixes #9390
Replaced the old runKtlint() code with the one generated by `./gradlew addKtlintFormatGitPreCommitHook`
for reference, see https://github.com/JLLeitschuh/ktlint-gradle#additional-helper-tasks, and for the implementation, https://github.com/JLLeitschuh/ktlint-gradle/blob/master/plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/GitHook.kt
The idea came from https://github.com/ankidroid/Anki-Android/issues/9390#issuecomment-950353851
https://user-images.githubusercontent.com/69634269/183875558-937f7fc7-a4a6-4178-ad20-cb597f11de31.mp4
> Make possible to commit hunks on Kotlin again

- AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
- AnkiDroid/src/main/java/com/ichi2/anki/preferences/HeaderFragment.kt
- AnkiDroid/src/main/java/com/ichi2/preferences/HeaderPreference.kt
- AnkiDroid/src/main/java/com/ichi2/preferences/NumberRangePreferenceCompat.kt
- AnkiDroid/src/main/java/com/ichi2/preferences/SeekBarPreferenceCompat.kt
- AnkiDroid/src/main/res/values/attrs.xml
- AnkiDroid/src/main/res/values/constants.xml
- AnkiDroid/src/main/res/xml/preference_headers.xml
- AnkiDroid/src/main/res/xml/preferences_accessibility.xml
- AnkiDroid/src/main/res/xml/preferences_advanced_statistics.xml
- AnkiDroid/src/main/res/xml/preferences_controls.xml
- AnkiDroid/src/main/res/xml/preferences_reviewing.xml
- AnkiDroid/src/test/java/com/ichi2/anki/PreferencesSimpleTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/PreferencesTest.kt
Use style attributes the way Android intends to and simplify some preferences' constructors to improve Android Studio's layout previews
On the commits
1. See if the summaries are looking right on Android Studio's layout previewer now that this is possible
2. Run the app and do the same thing on it 
Android's documentation has its fair limits, so I went to the source code to see how they handled preferences internally
https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:preference/preference/res/values/attrs.xml
https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:preference/preference/src/main/java/androidx/preference/ListPreference.java?q=listpreference
> [GSoC] refactor preferences style attributes

- AnkiDroid/src/main/java/com/ichi2/anki/CardInfo.kt
- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
- AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/ModelManager.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/ModelsV16.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/PythonTypes.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/importer/NoteImporter.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/BaseSched.kt
It's used upstream. It was defined in notes.py, but since Notes.java may not get
converted, consts is the most relevant place to put it.
Those ones were found by searching for "nodeId: Long", "NoteId: Long" and "nid:
Long".
> NF: uses NoteId instead of Long

- AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/NotificationChannelTest.java
On my local emulators, the android tests are frequently false-negative because of a previous testing session leaving LeakCanary channels laying around after being auto-created
This PR alters the success criteria of the notification channels test to allow these auto-created LeakCanary tests to exist without failing for having the wrong number of expected channels
Any notification channel with "LeakCanary" in it is considered acceptable by adding it to the expected channel count
Re-ran the test locally with the changes
> test: LeakCanary channels are auto-created / okay to have

- AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
- AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
- AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
- AnkiDroid/src/main/java/com/ichi2/anki/CardInfo.kt
- AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
- AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
- AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/OnRenderProcessGoneDelegate.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/PythonTypes.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/CardQueue.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/LrnCardQueue.kt
- AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/OnRenderProcessGoneDelegateTest.kt
CardId is defined in cards.py upstream. Since Cards.java may not be converted,
Consts.kt may be the better place for it.
Values were found by searching "cid: Long" and "ardId: Long".
> NF: replace Long by CardId

- AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.kt
There was unnecessary rebuild of filtered deck after opening filter deck options 
Fixes #10767 
The getString method tries to commit the default value which further notifies the listeners to rebuild the deck .Since the value is only required if second filter is enabled  I put a condition so that it is called only when it is needed.
Tested on my personal device oppo a52
> fixing unnecessary rebuild of filtered deck  after opening filter deck option

- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
- AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
- AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.kt
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/impl/MultimediaEditableNote.kt
- AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
- AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/ModelManager.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/ModelsV16.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/PythonTypes.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.kt
NotetypeId is defined upstream in models.py.
Since we may not convert Models.java, defining it in consts.kt seems the better
place
Those variables were found by searching for "mid: Long" and "odelId: Long".
> NF: replace Long by NotetypeId

- AnkiDroid/src/main/res/values/deck_options.xml
- AnkiDroid/src/main/res/values/filtered_deck_options.xml
- AnkiDroid/src/main/res/xml/cram_deck_options.xml
- AnkiDroid/src/main/res/xml/deck_options.xml
- AnkiDroid/src/main/res/xml/preferences_custom_sync_server.xml
- lint-rules/src/main/java/com/ichi2/anki/lint/IssueRegistry.kt
- lint-rules/src/main/java/com/ichi2/anki/lint/rules/HardcodedPreferenceKey.kt
- lint-rules/src/test/java/com/ichi2/anki/lint/rules/HardcodedPreferenceKeyTest.kt
Fixes #10423
For the key extractions, just used a regex to replace the strings for keys, searching for `android:(?:key|dependency)="([^@].*?)"`. Deck options keys were replaced by `deck_options_KEYNAME_key` and filtered deck options were replaced by `filtered_deck_KEYNAME_key`. This way the change was easy to do and probably will be easy to review.
Ran lint and the unit tests created
> [GSoC] Add a lint rule to use string resources for preferences keys + extract deck options/filtered deck options keys

- AnkiDroid/src/main/java/com/ichi2/libanki/ModelManager.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/Models.java
- AnkiDroid/src/main/java/com/ichi2/libanki/ModelsV16.kt
- AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.kt
+ make the field/card map non-null, as null values were not being used
outside tests
Closes #12049
> Fix crash in new schema when user tries to change notetype of card

- AnkiDroid/src/main/java/com/ichi2/anki/preferences/ReviewingSettingsFragment.kt
- AnkiDroid/src/main/java/com/ichi2/preferences/NumberRangePreferenceCompat.kt
The app crashes if you delete all text on a NumberRangePreference , e.g. Timebox time limit + if sent a text with leading zeroes, the summary would have the leading zeroes as well, e.g. "0050"
Make a check at `onDialogClosed`
1. Settings > Reviewing > Timebox time limit
2. Erase all text
3. Confirm
4. See if the new value is 0
---
1. Settings > Reviewing > Timebox time limit
2. Write "0050"
3. Confirm
4. See if the new value is 50
> Fix crash if NumberRangePref value is empty on close

- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt
The current code in CardBrowser does some setup for its dialogs if they show a list of items. However the dialog for the save search card doesn't show a list of items and using this option triggers a crash(no RecyclerView). This PR fixes this by attempting to retrieve the RecyclerView of the dialog(if not found it throws a IllegalStateException) and doing the work only if the call succeeds. This follows the code used before the material library update which checked for null when retrieving the RecyclerView from the dialog before using it.
Fixes #12057 
Ran the tests.
> Fix save search in CardBrowser when dialog has no list

- AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.java
`wait` uses Object.wait which depends on `notify`, we wanted `Thread.join()`.
This is useful before the Kotlin migration as Kotlin no longer has Object.wait
Test only
> perf: testAnswerCard

- AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/CollectionV16.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.kt
Modify SearchNotes to be able to use both legacy and V16 functions
Add support for using new backend method `searchNotes()`
By checking the schema version, the newer function is used on using V16. The newer `searchNotes()` function includes a parameter for sorting, which is not supported in legacy.
`findNotes()` function is modified in `Collection` so that V16 can be used when enabled
On my phone by enabling V16 backend in settings.
> Modify `findNotes()` to use V16 `searchNotes()` function

- AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.kt
- AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
This PR removes the deprecated  onActivityResult from StudyOptionsActivity. The method was only used to log calls so I moved the logging call to the places from this activity where a result is expected from another activity, which are found in StudyOptionsFragment.
> Fix onActivityResult deprecation for StudyOptionsActivity

- AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
- AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.kt
- AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
- AnkiDroid/src/main/java/com/ichi2/anki/Statistics.kt
Filtered study decks don't show in the card browser's deck search dialog.
Fixes [#10684](https://github.com/ankidroid/Anki-Android/issues/10684)
The problem is caused by the `displayDeckSelectionDialog` function. In this function, only non-dynamic decks will be displayed in the dialog. I changed the filter requirements to display all the decks in the card browser's deck search dialog. This function is called by `setSpinnerListener` and `onKeyUp` in `com/ichi2/anki/NoteEditor.kt`. I create another two functions `setSpinnerListenerForNoteEditor` and `displayDeckSelectionDialogForNoteEditor`, so the behavior of the deck search dialog in the card browser is fixed and the behavior in the note editor screen is not affected.
It was manually tested on the emulator (Pixel 2 API 29).
The deck …
> Fixed the bug that filtered study decks don't show in Card browser

- AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/importer/NoteImporter.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/BaseSched.kt
This is useful before converting 'Utils.java'
**Collection:**
* setUserFlag
* genCards
* cardCount
* emptyCardReport
* updateFieldCache
**BaseSched:**
* remFromDyn
**Anki2Importer:**
* _writeDstMedia
Unit tested
> refactor: Kotlin - fix nullability

- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CardBrowserMySearchesDialog.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/TreeNode.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/sync/RemoteMediaServer.kt
- AnkiDroid/src/main/java/com/ichi2/utils/ExtendedFragmentFactory.kt
- AnkiDroid/src/main/java/com/ichi2/utils/FragmentFactoryUtils.kt
- AnkiDroid/src/main/java/com/ichi2/utils/UniqueArrayList.kt
- AnkiDroid/src/test/java/com/ichi2/testutils/RecyclerViewUtils.kt
This can be done simply by reifying types, which itself requires inlining the
function.
This can't be done when the uncheckd is due to the fact that we cast to a type
with type parameters, for recursive function, and when the function has state effect.
> NF: remove unchecked cast when possible

- AnkiDroid/src/main/res/layout-xlarge/homescreen.xml
- AnkiDroid/src/main/res/layout/preferences.xml
It's now Android's preferred container for fragments (https://developer.android.com/jetpack/androidx/releases/fragment#version_120_3)
And as it extends FrameLayout (https://developer.android.com/reference/androidx/fragment/app/FragmentContainerView) there shouldn't be a problem
1. Ran the app on a SDK 25 Tablet emulator to see if the deck picker study options fragment was being shown correctly
2. Open the preferences' screen
> NF: Replace FragmentLayout with FragmentContainerView as the container for fragments

- AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt
- AnkiDroid/src/main/java/com/ichi2/anki/preferences/AppearanceSettingsFragment.kt
- AnkiDroid/src/main/java/com/ichi2/anki/preferences/DevOptionsFragment.kt
- AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt
More or less the same reason of #12040
On the commits
Opened the settings screens and tapped the changed preferences (Reset language, Select backgorund, etc)
> Use snackbars instead of toasts on the Settings fragments

- AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
- AnkiDroid/src/main/java/com/ichi2/anki/workarounds/FullDraggableContainerFix.kt
The option Full screen navigation drawer allows opening the navigation drawer by swiping right anywhere on the screen. It has an issue in that it will intercept all rightwards swipes, even if a view inside it also wants these events. This fixes it.
Closes #11588.
Createad a workaround subclass. See code comment for details.
Tested on my device running Android 11. I can not run emulator, so this was **NOT** tested on other devices. This is is the kind of thing that can vary between OS versions and device manufacturers, so it would be **VERY NICE** if this was tested on at least some devices.
If you are going to test it, make a note of issue #11813.
> Fix Full screen navigation drawer overtaking child view gestures

- AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java
- AnkiDroid/src/main/java/com/ichi2/libanki/SoundKt.kt
'Sound.kt' blocks conversion of Sound.java to Kotlin as we can't have different files with the same name
> rename: Sound.kt -> SoundKt.kt

- .github/pull_request_template.md
These items are now handled by lint checks + pre-commit hooks for Kotlin-based code
We have very little Java code, and I feel it's very unlikely that new users will be modifying this before we remove the remainder
This streamlines the process of submitting a PR, which hopefully encourages new contributors to participate in the repo
> Remove whitespace and code style checklist items

- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
- AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.kt
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportFileSelectionFragment.kt
- AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt
- AnkiDroid/src/main/res/values/02-strings.xml
- AnkiDroid/src/main/res/values/03-dialogs.xml
- AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.kt
- AnkiDroid/src/test/java/com/ichi2/utils/ImportUtilsTest.kt
This just adds the option, not the actual text/csv import implementation. which will be the next PR
As the CSV importer will require the new backend, the options is only shown if the new backend is enabled
On the commits
1. Enable the new backend
2. Tap the three dot menu on the Deck picker > Import
3. Choose "Text file (.txt, .csv)
4. Select a text file
5. See if the "CSV importer is not implemented yet" is shown
> [GSoC] Add option to import text files

- AnkiDroid/src/main/res/color/drawer_item_text_dark.xml
- AnkiDroid/src/main/res/values/colors.xml
- AnkiDroid/src/main/res/values/theme_black.xml
- AnkiDroid/src/main/res/values/theme_dark.xml
- AnkiDroid/src/main/res/values/theme_light.xml
- AnkiDroid/src/main/res/values/theme_plain.xml
Fixes #10909
Fixes #12020
Closes #11043
On the commits
1. Go to one of the Settings categories
2. On light theme: see if switches are blue
3. On dark theme: see if pass accessibility scanner
4. On black theme: see if pass accessibility scanner
Good old stack overflow: https://stackoverflow.com/questions/11253512/change-on-color-of-a-switch
> Make switch color blue on `Light` theme + Fix `colorAccent` low contrast on dark themes

- AnkiDroid/src/main/AndroidManifest.xml
- AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Open card browser from another app with search query 
Fixes #11885
1. Create intent-filter in Cardbrowser activity with `scheme="anki"`, `host="x-callback-url"` and `path="/cardbrowser"`
2. Get intent data using `getQueryParameter`
Tested using chrome and https://krmanik.github.io/deeplinks-intent-test/
1. Load the page on chrome browser on android device
2. Input the fields to make intent like this for searching `test`
```
intent://x-callback-url/cardbrowser?search=test#Intent;scheme=anki;package=com.ichi2.anki;end
```
3. The webpage creates `a` tag and href value with above intent
a) Searching nid
```
<a href="intent://x-callback-url/cardbrowser?search=nid:1658178059263#Intent;scheme=anki;package=com.ichi2.anki;end">Search nid </a>
```
b) Searching `some text`
```
<a …
```
> open card browser and search using deep links

- .github/workflows/tests_emulator.yml
Our emulator tests have all the sudden become very flaky.
Proximate cause appears to be OutOfMemory death spiral in emulator processes.
Root cause is hypothesized to be a race between correct (sufficient) memory sizing and zygote init in boot sequence
This should work around that
Details here https://github.com/ankidroid/Anki-Android/issues/11091#issuecomment-1221325800
Unlogged general flakiness in tests_emulator.yml
Warm reboot the emulator by restarting the zygote process
The sleep 5 / sleep 10 are just rough guesses that a) time to settle is needed b) that time is sufficient
It is in testing, adb logcat should show a zygote with something *other* than -Xmx16m
Ideally we see a -Xmx16m at start then a -Xmx"not 16m" later in zygote / art init arguments
It may take a couple runs (my guess …
> fix emulator OutOfMemory by forcing zygote init race win via warm reboot

- AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.kt
- AnkiDroid/src/test/java/com/ichi2/anki/dialogs/utils/HelpDialogTest.kt
This PR fixes some bugs related to code around the `Rate` menu item from the help/support dialogs. Changes:
- removes the code related to `Rate` from `HelpDialog.createInstance()` because the option is not used at all in the help menu. This also allows the simplification of the method by removing its `context` parameter.
- fixes a bug related to `Rate` from `HelpDialog.createInstanceForSupportAnkiDroid()` which made the `Rate` menu option to appear even if the application to handle it is not present on the device. See the before and after picture below on a device which doesn't have the play store app installed:
On the majority of devices with the store application available there are no changes and the `Rate` menu option is available:
- fixes the …
> Fix Rate menu item availability in help/support dialogs

- AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
- AnkiDroid/src/main/java/com/ichi2/anki/workarounds/AppLoadedFromBackupWorkaround.kt
To be used in the App Intro which can't inherit from `AnkiActivity`
So we need this functionality extracted.
`Activity.onCreate` is protected so can't be called except from an inheritor
> refactor: extract 'showedActivityFailedScreen'

- AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
Closes #12040
On the commits
1. Start reviewing
2. Suspend/Bury/Delete a card > see if a snackbar with a "Undo" button appears
3. Tap undo on the snackbar
4. Tap the normal undo button
note: With the new backend, the snackbar is shown with `!backendUndoAndShowPopup()`, which currently shows on top of the answer buttons (if at bottom). Left a TODO there
> Use snackbars instead of toasts on the reviewer's actions

- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
- AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
- AnkiDroid/src/main/java/com/ichi2/anki/preferences/CustomSyncServerSettingsFragment.kt
- AnkiDroid/src/main/java/com/ichi2/anki/preferences/SyncSettingsFragment.kt
- AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
- AnkiDroid/src/main/java/com/ichi2/anki/web/CustomSyncServer.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/sync/HttpSyncer.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/sync/RemoteMediaServer.kt
- AnkiDroid/src/main/res/values/preferences.xml
- AnkiDroid/src/main/res/xml/preferences_custom_sync_server.xml
- AnkiDroid/src/test/java/com/ichi2/anki/servicemodel/PreferenceUpgradeServiceTest.kt
- AnkiDroid/src/test/java/com/ichi2/libanki/sync/HttpSyncerTest.kt
There's a few issues with custom sync servers. One of the settings is not consistent with the other and with what Anki expects; when using backend, custom sync servers and some other settings are not respected. Please see the commits for the list of changes. 
**Edit**: emulator tests [did pass](https://github.com/oakkitten/Anki-Android/actions/runs/2890274724) in my fork.
One of the preferences was upgraded to match Anki. Environmental variables are set to make the backend use the custom servers. A new argument `syncMedia` is added to a few backend sync methods.
I tried splitting the first commit into several, but the result was just harder to understand, so. A few identifiers could have better names, but I opted for a smaller diff & consistency with surrounding identifiers.
One …
> Fix a few issues with Custom sync server

- AnkiDroid/src/test/java/com/ichi2/libanki/ClozeTest.kt
- AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.kt
- AnkiDroid/src/test/java/com/ichi2/libanki/template/ParserTest.kt
- AnkiDroid/src/test/java/com/ichi2/libanki/template/TokenizerTest.kt
- AnkiDroid/src/test/java/com/ichi2/utils/JSONArrayTest.kt
- AnkiDroid/src/test/java/com/ichi2/utils/JSONObjectTest.kt
It was not corrected in `testToJSONArrayNull` because the test should fail (but since the author didn't actually add `fail()` in it, it was not detected)
> NF: uses assertThrows instead of try{expectToFail}catch{}

- AnkiDroid/build.gradle
- api/build.gradle
Just a compile SDK bump, there were no deprecations noted
Unblocks #12165 which requires compileSdkVersion >= 32
Bumped it in the two files it exists in
Local run of all CI targets
> build: bump compileSdkVersion to 32

- AnkiDroid/build.gradle
- AnkiDroid/src/main/AndroidManifest.xml
- AnkiDroid/src/main/java/com/ichi2/anki/BackendImporting.kt
- AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
- AnkiDroid/src/main/java/com/ichi2/anki/pages/AnkiServer.kt
- AnkiDroid/src/main/java/com/ichi2/anki/pages/CsvImporter.kt
- AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt
- AnkiDroid/src/main/java/com/ichi2/anki/pages/PageWebViewClient.kt
- AnkiDroid/src/main/java/com/ichi2/anki/pages/PagesActivity.kt
- AnkiDroid/src/main/res/layout/page_activity.xml
- AnkiDroid/src/main/res/layout/page_fragment.xml
- AnkiDroid/src/test/java/com/ichi2/testutils/ActivityList.kt
On top of #12072
Closes #6772
Closes #9437
This implements the base for using upstream's HTML/Js pages directly on AnkiDroid.
I've used https://github.com/krmanik/Anki-Android/pull/23 as base of this PR. I wouldn't have managed to do it without all the previous work of Mani and Damien, so I thank them very much.
As discussed on https://github.com/krmanik/Anki-Android/pull/23, to use an Anki HTML page, we should be able to intercept POST requests. After some proof of concepts made by Mani, the conclusion was that hosting a local server, like the desktop application, may be most suitable approach.
To create the local server, I've used the same approach of https://github.com/krmanik/Anki-Android/pull/23 and added NanoHTTPD, a java server library, as dependency. I don't have experience with …
> [GSoC] Implement the CSV importer

- AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
- AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
- AnkiDroid/src/main/java/com/ichi2/anki/pages/CardInfo.kt
- AnkiDroid/src/main/java/com/ichi2/anki/pages/PagesActivity.kt
Upstream has a HTML page for card info, which we can get for free
Fixes #12167 (i think)
- Add the new page
- Eval the same JS of upstream (https://github.com/ankitects/anki/blob/678c354fed4d98c0a8ef84fb7981ee085bd744a7/qt/aqt/browser/card_info.py#L66-L72)
- Put it as the default if the new backend is being used
For a very brief moment, this screen shows up, but it is probably an upstream issue as it appears on Anki Desktop too (see 
https://github.com/ankidroid/Anki-Android/issues/6772#issuecomment-1208395273 for the discussion)
- Use the new backend
- Card browser
- Select a card
- Card info
---
- Use the new backend
- Enable "Card info" app bar button on settings
- Reviewer
- Card info
> Add Anki's new CardInfo page

- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportFileSelectionFragment.kt
to do it, an "extraMimes" param is added to openImportFilePicker, which can be passed to the intent wish a "EXTRA_MIME_TYPES" as extra.
ref: https://stackoverflow.com/questions/27367272/how-can-i-setup-an-android-intent-for-multiple-types-of-files-pdf-office-imag
- Enable the new backend
- Import > Text file
- See if you can select .csv, .tsv and .txt
> [GSoC] Make the CSV importer accept .csv and .tsv extensions

- AnkiDroid/src/main/java/com/ichi2/anki/CardInfo.kt
- AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
- AnkiDroid/src/main/java/com/ichi2/anki/Statistics.kt
- AnkiDroid/src/main/java/com/ichi2/anki/pages/PagesActivity.kt
- AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
- AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt
Anki has a pretty statistics screen that we can use, and the best part is that we can get it for free!
- Add the screen
- Show it instead of the old one if the new backend is enabled
- What to do with `Default deck when opening statistics` preference, as it doesn't work with the new screen
- What to do with `Advanced statistics` preference, as it doesn't work with the new screen
- Enable the new backend
- Go to statistics
> Add Anki's new Statistics page

- AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
- AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
- AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
When updating a single card, it is not required to show continuous progress since it a short task and user can be notified after the task has been finished. So instead of using onProgressUpdate callback, it is good to use onPostExecute for UI updates after the card has been updated.
THIS PR WILL HELP MIGRATING UPDATENOTES TO COROUTINE
Passes existing tests and runs as expected on Realme 6i API 30 and Pixel 4a AVD API 31
> [GSoC] Simplified UpdateNote asynctask callbacks

- AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
- AnkiDroid/src/main/java/com/ichi2/utils/NetworkUtils.kt
- AnkiDroid/src/main/res/values/03-dialogs.xml
- AnkiDroid/src/main/res/values/10-preferences.xml
- AnkiDroid/src/main/res/values/preferences.xml
- AnkiDroid/src/main/res/xml/preferences_sync.xml
Internet may be expensive 💵💰💲💸
Fixes #10706
- Clean things a bit
- Create a "Advanced" category under "Sync", so things get a little more organized with the increasing number of preferences
- Add a preference to allow sync on metered connections (off by default)
- If not allowed, auto sync under metered connections won't occur + the user will be warned if they trigger a manual sync under a metered connection
- I'm quite open to string changes
https://user-images.githubusercontent.com/69634269/185769043-30b76c32-5e89-4b27-93b2-156638e26204.mp4
> [GSoC] Add preference to allow/warn if using metered connections

- AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/CollectionV16.kt
- AnkiDroid/src/main/res/values/10-preferences.xml
- AnkiDroid/src/main/res/values/preferences.xml
- AnkiDroid/src/main/res/xml/preferences_advanced.xml
Help people test, and test and test and test and test all night long
- extract part of the logic of `_loadScheduler()` into CollectionHelper.isV3Enabled
- add a new experimental preference called "Use the v3 scheduler"
- it's dependent on the new backend, i.e. the user can only enable it if the new backend is being used
- Sync the collection
- Enable v3 on AnkiDroid -> sync -> see if it was enabled on another device
- Disable v3 on AnkiDroid -> sync -> see if it was disabled on another device
- Enable v3 on another device -> sync -> see if it was enabled on AnkiDroid
- Disable v3 on another device -> sync -> see if it was disabled on AnkiDroid
> Add option to enable the v3 scheduler

- AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
Last usage of this class has been removed in #11952. So it is being used no more. Should had been deleted there only but I forgot.
> Deleted unused CollectionTask.AddNote

- AnkiDroid/src/main/java/com/ichi2/anki/Statistics.kt
- AnkiDroid/src/main/java/com/ichi2/async/CoroutineHelpers.kt
My understanding is that this method will often be called either on fragments,
and using the fragment's activity. So it seems to make sense to simplify it,
ensuring that we avoid a parameter that will probably never change.
Actually, since activities are also LifecycleOwner, it may be possible to ensure
this method is even simpler, by defining it on activities instead of defining it
on LifecycleOwner. Unless we have a reason to use an activity distinct from the
LifecycleOwner.
Also cleaning from function I viewed at the same time
> NF: simplify catchingLifecycleScope

- .github/workflows/label.yml
Automate process of adding `strings` label when values dir changed.
1. Run git diff on res/values dir 
2. Use the result to run the github actions script
Tested on this PR
https://github.com/krmanik/Anki-Android-Copy/pull/1
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
> Add `strings` label when res/values dir changes

- AnkiDroid/jacoco.gradle
Our code coverage only showed Java files, not the Kotlin files we're migrating to.
Fixes #9432
Instructions from:
https://medium.com/jamf-engineering/android-kotlin-code-coverage-with-jacoco-sonar-and-gradle-plugin-6-x-3933ed503a6e
This PR is most of the testing
* Checked the report for standard unit tests: 42% coverage
* Checked the combined report: 44% coverage
> feat: Include Kotlin files in code coverage

- AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.kt
- AnkiDroid/src/main/java/com/ichi2/anki/Statistics.kt
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
fix: deck search not scrolling to current deck in statistics
Fixes #9935 
1.Passed the current deck Id as argument to the dialog fragment
2.found the position of the deck in recycler view
3.Scroll to that position
Tested on my personal device.
> fixed: deck search not scrolling to current deck in statistics

- .codecov.yml
- .idea/dictionaries/android.xml
Our code coverage fluctuates, meaning that CI is often shown as failed even on no-op operations
This is bad for our developer experience: we can't trust CI status to be reporting correctly, and this slows fixing actual issues
So, we mark codecov as 'informational' so only 'real' CI failures are shown to users
> If `true` is specified the resulting status will pass no matter what  the coverage is or what other settings are specified. Informational mode is great to use if you want to expose codecov information to other developers in your pull request without necessarily gating PRs on that information.
https://docs.codecov.com/docs/commit-status#informational
Related issue: #12227 - fixing the flakiness in other ways
This PR is the test - I want to see if the checks are removed, or marked as …
> ci: stop codecov from failing CI

- AnkiDroid/src/main/java/com/ichi2/anki/TtsParser.kt
- AnkiDroid/src/test/java/com/ichi2/libanki/TtsParserTest.kt
resolves ankidroid/Anki-Android#12233
#12233
Fixes #12233
Adds `replace` to another line of code which handles text within a `tts` tag.
Added a test for the `<tts service="android">` tag. It fails without the fix, passes with the fix.
> fix: replace cloze with blank within <tts> tag

- AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
Reason: The leading string in `Timber.e("caught: %s %s", exc, extraInfo)` caused  stack trace to be suppressed.
Fixes #12238
https://user-images.githubusercontent.com/69595691/187378845-4a4b2198-4f1f-4c72-a862-beabe6f35665.mp4
> fix: suppressed stack trace when error in coroutine occurs.

- AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
- AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
When updating a multiple notes, it is not required to show continuous progress since it a short task and user can be notified after the task has been finished. So instead of using onProgressUpdate callback, it is good to use onPostExecute for UI updates after the notes has been updated.
Passes existing tests and runs as expected on Realme 6i API 30 and Pixel 4a AVD API 31
> [GSoC] Simplified UpdateMultipleNotes asynctask callbacks

- AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
I've messed up and Card info couldn't be opened from the deck picker anymore
Assign the intent variable properly
- Be sure that "Card info" app bar button isn't disabled
- Start reviewing
- Tap Card info
> Fix Card info on the legacy schema if opened from the deck picker

- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
- AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DeckService.kt
- AnkiDroid/src/main/res/values/02-strings.xml
- AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CreateDeckDialogTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/dialogs/utils/MaterialDialogUtils.kt
When a deck was created, there was little visual feedback on success/failure:
* When a deck was invalid, the dialog just closed
* When a deck was created/renamed, the user was not informed
* Fixes #10528
* Solves part of #11668: deck creation
* toasts are used when a success occurs, 
* validation on the form is used if a deck couldn't be created
* The OK button is greyed out 
* A message is shown if the name is used
> feat: improve deck creation/rename UX

- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Snackbars should be preferred. Similar to #12093 and #12092
- Enable the "Press back to exit" setting
- Press back on the deck picker
> Use snackbar on `Press back to exit`

- AnkiDroid/src/main/java/com/ichi2/async/SingleTaskManager.kt
Simplifies code in `SingleTaskManger.kt`
Contributes to #10489 
- Ran the app after making the commits
- Ran the tests
- Flaky tests are tests that do not give consistent results
- These are generally annotated with `@Ignore` which means they get skipped
> Simplify SingleTaskManager.kt

- .github/workflows/label.yml
Add comments when PR opened and on branch other than `i18n_sync`
Fixes #12265
Fixes #12266
https://github.com/krmanik/Anki-Android-Copy/pull/14
https://github.com/krmanik/Anki-Android-Copy/pull/16
https://octokit.github.io/rest.js/v18
> Add comments when PR opened and on branch other than i18n_sync

- AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
- AnkiDroid/src/main/java/com/ichi2/async/Connection.kt
- AnkiDroid/src/main/java/com/ichi2/utils/NetworkUtils.kt
The "You have no internet collection - Sync anyway" snackbar should be shown instead
Fixes #12258
Add a method to check if the user is connected to the internet
https://user-images.githubusercontent.com/69634269/187761689-f59bedb8-2b0c-4ddb-a418-3ebd1de3dbd1.mp4
> Fix metered sync warning being shown if the user has no internet

- AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/InitialActivityWithConflictTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt
- AnkiDroid/src/test/java/com/ichi2/testutils/PermissionUtils.kt
I was investigating the flaky unit tests, and wanted to see what was going on
I could not reproduce the test failure, but a few frustrations occurred:
* Legacy code before `Robolectric.startActivity` was introduced
* `@KotlinCleanup`s
* `@RunInBackground` was used, which is pending for removal
* Some bad unit test asserts
* One issue with `revokeWritePermissions` not being reset, which may have caused test failures
I fixed all of these, and introduced `advanceRobolectricUiLooper` to allow for further migration away from `@RunInBackground`
I then added another `advanceRobolectricUiLooper` after creating the `Activity`, and the problems went away
#11091
Test only - tests run about 2 seconds faster expected - we shave 4*500ms off tests
* `advanceRobolectricUiLooper` is still required - …
> refactor: CardBrowserTest + fix flaky tests

- .github/workflows/lint.yml
- .github/workflows/publish.yml
- .github/workflows/tests_emulator.yml
- .github/workflows/tests_unit.yml
According to the [docs](https://github.com/marketplace/actions/setup-java-jdk#supported-distributions)
> Adopt OpenJDK got moved to Eclipse Temurin and won't be updated anymore. It is highly recommended to migrate workflows from adopt to temurin to keep receiving software and security updates. See more details in the [Good-bye AdoptOpenJDK post](https://blog.adoptopenjdk.net/2021/08/goodbye-adoptopenjdk-hello-adoptium/).
Fixes #11992 
Replaced all uses of `adopt` with `temurin`
Tested by running actions several times in my fork [here](https://github.com/RSBat/Anki-Android/actions?query=branch%3Ajdk-temurin++).
I found it by accident, so I have no ideas how to track such deprecations. AnkiDroid already uses dependabot for GitHub actions, but it didn't do anything either.
For an overview of …
> Switch JDK in GitHub Actions from adopt to temurin

- AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
- AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
- AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt
- AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
- AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/PreviewerTest.kt
Migrated CollectionTask.UpdateNote to Coroutines
A part of #7108
- Moved the functionality of CollectionTask.UpdateNote to CollectionOperations.updateNote
- CardBrowser: Previous implementation of UpdateCardHandler starts a progressBar in onPreExecute, updates the card-list from onPostExecute and **closes the CardBrowser with RESULT_DB_ERROR** (not good way). The newer implementation handles progressBar using withProgress{}, updated the card after the process and Error is handled by LaunchCatchingTask which **properly shows the error message without abruptly closing the CardBrowser**.
- AbstractFlashcardViewer: Similar to CardBrowser, just there is set of operations that is being done onPostExecute which has been replicated into onCardUpdated function.
> [GSoC] Migrated CollectionTask.UpdateNote to Coroutines

- tools/release.sh
The universal APK has not been uploading on release lately
Fixes #11746
It never fails all APKs, just the first one or first few. So perhaps a delay will help
we won't know until a release is attempted
Nothing is simple, and nothing stays working, without effort. Do the work
> build(release): add 30s sleep after release creation

- AnkiDroid/src/main/java/com/ichi2/async/BaseAsyncTask.kt
- AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
- AnkiDroid/src/main/java/com/ichi2/async/Connection.kt
No idea why it was added to always be potentially nullable.
Now it transmits its nullability status like everything else.
> NF: async task result is not necessarily nullable

- AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt
- AnkiDroid/src/main/java/com/ichi2/anki/pages/CardInfo.kt
- AnkiDroid/src/main/java/com/ichi2/anki/pages/CsvImporter.kt
- AnkiDroid/src/main/java/com/ichi2/anki/pages/PagesActivity.kt
- AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
- AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt
- AnkiDroid/src/main/java/com/ichi2/anki/preferences/CustomButtonsSettingsFragment.kt
- AnkiDroid/src/main/java/com/ichi2/anki/preferences/SettingsFragment.kt
- AnkiDroid/src/main/java/com/ichi2/utils/ReflectionUtils.kt
- AnkiDroid/src/test/java/com/ichi2/testutils/PreferenceUtils.kt
Simplify the code around getting the initial fragment for PagesActivity and Preferences
On the commits
Run the app and open the current Anki HTML pages with the new backend (Statistics, csv importer and card info)
> NF: simplify PagesActivity and Preferences fragment configuration

- .github/workflows/label.yml
Add post merge commits to `strings` label PR. 
Fixes #12267
Using GitHub scripts, when PR merged, the remove label search for labels to remove. If label match with `strings` then add comments.
Tested on local repository
https://github.com/krmanik/Anki-Android-Copy/pull/2
https://octokit.github.io/rest.js/
> add post merge comments on strings labelled PR

- AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
As described by Arthur in this [comment](https://github.com/ankidroid/Anki-Android/pull/12145#issuecomment-1230825051):
>But, if it's not to hard, I believe it'll be easier to read the history if you make classes internal first (potentially in a first PR that can be reviewed quickly) and then add the new feature. This way, this will avoid to add and remove parameters, and add code to move it immediately after
Make `FlagsAdapter` an inner class so that it can access variables created in `FilterSheetBottomFragment`, and also removes the need to have a separate listener, and other useful refactors.
> [GSOC] Convert `FlagsAdapter` to Inner Class

- build.gradle
We linked to a permalink (commit reference), change to the live file
As of writing, the library was 0.43.2: override is still needed
> fix(docs): fix link to remove ktlint override

- AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
- AnkiDroid/src/main/java/com/ichi2/anki/preferences/PreferencesSearchView.kt
- AnkiDroid/src/test/java/com/ichi2/anki/preferences/SettingsSearchBarTest.kt
On the 2.3.0 version of SearchPreference, the visibility of SearchConfiguration is now protected instead of private.
This allows saving and setting the search bar configuration instead of recreating it every time the menu is recreated, which happens when any fragment is opened
And about the search history: It was disabled before because the saved entries weren't good (see https://github.com/ByteHamster/SearchPreference/issues/25)
On the commits
Settings > Tap the search icon > search something and tap an option > tap the search icon again > see the history
> [GSoC] Optimize preferences search bar configuration + enable search history

- AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BrowserOptionsDialog.kt
- AnkiDroid/src/main/res/layout/browser_options_dialog.xml
- AnkiDroid/src/main/res/menu/card_browser.xml
- AnkiDroid/src/main/res/values/02-strings.xml
- AnkiDroid/src/main/res/values/06-statistics.xml
- AnkiDroid/src/main/res/values/07-cardbrowser.xml
- AnkiDroid/src/main/res/values/theme_black.xml
- AnkiDroid/src/main/res/values/theme_dark.xml
- AnkiDroid/src/main/res/values/theme_light.xml
- AnkiDroid/src/main/res/values/theme_plain.xml
- AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
Add the functionality to see only one card per note when enabled, following upstream Anki Note mode of the Browser. Especially helpful when you have for example a lot of cloze deletions in one note, with this feature you can choose to see only one card instead of all of them.
Fixes #7939 
By creating a variable to keep track of whether the browser is currently in Cards mode or Notes mode, different `Search` functions (committed earlier) are called accordingly. Part 1 of this commit just introduces the feature to view one card by note, further commits will include accommodating the column headers and their values (eg: avg. ease) to correctly display the values accordingly.
https://user-images.githubusercontent.com/86671025/185841802-0512a40c-e7c2-4bc5-9865-e5f71247c1ab.mp4
_Please, go …
> [GSoC] Add ability to browse one Card per Note in Browser

- AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
- AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/preferences/PreferenceUtils.kt
- AnkiDroid/src/test/java/com/ichi2/anki/preferences/PreferencesTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/reviewer/ActionButtonStatusTest.kt
Depending on the changes, a preferences fragment throws on creation, which sould be only seen while running the app, so here's a test for it
On the commits
this is a test
Use `.commitNow` if you are looping fragments, as `commit` is async
> tests: check if all preferences fragments don't throw on creation

- AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
This fixes the type nullability for the "pasteAsPlainText" menu item when retrieving it with  `menu.findItem()`(which can return null).
Fixes #12316 
Ran the tests.
> Fix nullable type bug with NoteEditor menu item

- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioPlayer.kt
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/MediaPlayer.kt
Fixed bug by preventing the call to `MediaPlayer::prepare` from happening while in `STARTED` state
Fixes #11363 
Based on [the native Android `AudioPlayer`'s State Diagram](https://developer.android.com/reference/android/media/MediaPlayer#state-diagram) `mPlayer.prepare` cannot be called while in `STARTED` state.
[Android MediaPlayer docs](https://developer.android.com/reference/android/media/MediaPlayer)
[MediaPlayer State Numbers](https://stackoverflow.com/a/29036185/12725405)
Emulator (Doesn't throw `IllegalStateException`)
Real Device (All the functions of start, stop, pause and resume working properly)
> Fixed AudioPlayer giving IllegalStateException on stop

- AnkiDroid/src/main/java/com/ichi2/anki/FilterSheetBottomFragment.kt
- AnkiDroid/src/main/res/layout/filter_bottom_sheet.xml
The current functionality for filters does not allow them to stay persistent, i.e, if I select some filters, apply them, and open the sheet again, those filters get reset. This PR improves on that and allows filters to stay persistent unless explicitly cleared.
Minor refactoring has also been performed.
By passing in the `flagSearchItems` list to the `FlagsAdapter` class, It can check whether a filter is selected or not during the view binding, and depending on that, the selected/unselected look is set.
https://user-images.githubusercontent.com/86671025/186949439-7d82618f-f380-4ad0-b280-fe33308c8c33.mp4
> [GSoC] Make Filters persistent in Filter Sheet

- .github/workflows/stale.yml
GitHub introduced 'not_planned' as a close reason for stale issues:
https://github.blog/changelog/2022-05-19-the-new-github-issues-may-19th-update/
docs: https://github.com/actions/stale#close-issue-reason
⚠️ Untested
docs: https://github.com/actions/stale#close-issue-reason
Added in https://github.com/actions/stale/releases/tag/v5.1.0
https://github.blog/changelog/2022-05-19-the-new-github-issues-may-19th-update/
> ci: mark Stale issues as 'not_planned'

- AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
The title of the note-adding screen should have already be replaced with "Add" as a conclusion of the discussion in #10853, but it is still "Add note".
fixes #12335
1. Build an APK file and install it in my device
2. Open the app
3. Tap the floating action button ("+")
4. Tap "Add"
5. Check if the title of the screen is changed
The counterpart screen of Anki Desktop
> Replace the title of the note-adding screen ("Add note") with "Add"

- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerContextMenu.kt
NeedsTest for regression fixed in #11788
- Fixes #11790 - transforms to `NeedsTest` - better to not have individual issues to add tests to functionality as it unnecessarily cogs up GitHub
> docs: add NeedsTest for onCreateDialog

- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
- AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
No need to handle cancellation explicitly as the suspend function is launched from lifecycleScope
> [GSoC] Migrated LoadCollectionComplete to Coroutines

- AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
The name of the note-adding shortcut should have already be replaced with "Add" as a conclusion of the discussion in https://github.com/ankidroid/Anki-Android/pull/10853, but it is still "Add note".
fixes #12347
- Replace the strings of "menu_add_note" with "menu_add" on NavigationDrawerActivity.kt
- Replace their comment ("Add Note Shortcut") with "Add Shortcut"
1. Build an APK file and install it on my physical device
2. Open the app
3. [GET STARTED]>[OK]>[ALLOW]
4. Close the app
5. Long press the app's icon (then, the app's shortcuts are shown)
6. Check if the name of the note-adding shortcut has been changed
> fix: Replace the name of note-adding shortcut ("Add note") with "Add"

- AnkiDroid/build.gradle
Following https://stackoverflow.com/a/55218573/414269 It ensures the IDE don't show error on `import kotlin.test.junit.JUnitAsserter.assertNotNull`
> Adding kotlin-test-junit to androidTestImplementation

- AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
- AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
- AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
- AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
- AnkiDroid/src/main/java/com/ichi2/utils/CollectionUtils.kt
- AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.kt
Follow up to #12035. User can now switch to showing just one card per note, but, the columns still show data for the card alone. As mentioned in the Anki Docs [here](https://docs.ankiweb.net/browsing.html#columns), a few columns display slightly different data in notes mode. This PR tackles displaying avg ease.
Create a function for a `Card` to return the average ease of its note, and if `inCardsMode` is not true, (i.e. browser is in notes mode), we return the avg ease to the column header.
Manually on mobile device, Unit test added as well
> [GSoC] Show Avg Ease in note mode

- AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
`CancellationException` needs to be thrown again in `runCatchingTask`.
Also added comment to explain the reason for this.
> Re-throw CancellationException in runCatchingTask

- AnkiDroid/build.gradle
This ensures that the IDE don't complain about missing imports in classes such as BackupManagerSimpleTest.kt
> NF: depends of junit5

- api/src/main/java/com/ichi2/anki/api/Basic2Model.kt
This class was package protected from its creation and not part of the public API(see the last commit before being migrated to kotlin: 66b7ea6) so I set its visibility to _internal_(the two properties were also package protected initially). 
Note that the interoperability related to internal is not great and this will end up as public in the java code.
We could move the properties of this object in `AddContentApi` as there's a single usage of `Basic2Model` in `addNewBasic2Model()`.
Nothing really to test.
> Set Basic2Model as internal to follow original visibility

- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
- AnkiDroid/src/main/res/values/01-core.xml
Replace the string of "This deck is empty" snackbar action ("ADD CARD") with "ADD" to keep a consistency with the other note-adding strings 
Replace `R.string.empty_deck_add_note` with `R.string.menu_add` on DeckPicker.kt
Build an app and check it on my physical device
> Rename the string of "This deck is empty" snackbar action 

- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
- AnkiDroid/src/main/java/com/ichi2/compat/Compat.kt
- AnkiDroid/src/main/java/com/ichi2/compat/CompatHelper.kt
- AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.kt
- AnkiDroid/src/main/java/com/ichi2/compat/CompatV31.kt
- AnkiDroid/src/main/java/com/ichi2/compat/CompatV33.kt
deprecation: compileSdk 33 issues #12364
Added compatv33 file and made required changes in the other files
> added CompatV33

- AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
- AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
Continuation of #12035. Show total lapses of the note in notes mode
Show sum of lapses of all cards in notes mode.
Manually on device.
> [GSoC] Show total lapses of note of card in notes mode (follow up to #12035)

- AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
- AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
- AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.kt
Continuation of #12035. Adds functionality to see average interval of note in notes mode of browser.
Create a function to average the intervals of non-new and non-learning cards
Unit Test added and tested on device.
> [GSoC] Show Avg Interval in Notes Mode (follow up to #12035)

- AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Continuation of #12035. Following upstream, show date of when note was last changed in notes mode.
Use `note().mod` in notes mode
physically on device.
> [GSoC] Show date of last changed card of given note in notes mode (follow up to #12035)

- AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
Continuation of #12035. Follow upstream to show number of cards on the `Card` option of browser.
use `note().numberOfCards` to show number of cards for that note
Manually on device.
> [GSoC] Show number of cards in Notes Mode (follow up to #12035)

- api/src/main/java/com/ichi2/anki/api/NoteInfo.kt
Cleanup the NoteInfo class for new API release. I added the `public` visibility modifiers which will be required once #12334 is merged.
Note: The static method `buildFromCursor` was package protected (see last java commit for class f04b4f7) so I set its visibility to `internal`. This will still make it appear in the public API but the compiler will change its name(adds a sufix) to deter users from using it.
> Cleanup NoteInfo for api release

- AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
At one point we had two `CoroutineHelpers` files. In ad95d569f0 we removed one of the implementations(which was sending error reports), unfortunately the code in the  file remaining didn't send error reports. This PR fixes this.
With my changes, when an error happens, the user will see a dialog and when that dialog is dismissed(in any way) he will see the error reporting dialog(if it is enabled in settings).
Ran the checks, verify that the app prepares an error report when this is permitted in settings.
> Enable again sending error reports from launchCatchingTask

- api/src/main/java/com/ichi2/anki/api/AddContentApi.kt
More cleanups for AddContentApi:
- fixed the todos inside the class by removing them, they were not aplicacable as the requested annotation is not needed.
- added the proper visibility modifiers for the class methods and properties following the original code(this is in anticipation of enabling `explicitApi` mode for this module). Plus on @ JvmStatic to replicate a static method from the original java code.
See how the file looked in the last commit as a [java file](https://github.com/ankidroid/Anki-Android/blob/f39b7fa10f9ecbd080f0beb33617308137fb27bb/api/src/main/java/com/ichi2/anki/api/AddContentApi.java). 
There's one todo left about the nullability in the methods signatures.
Ran checks.
> More cleanups for AddContentApi

- api/build.gradle
- api/src/main/java/com/ichi2/anki/FlashCardsContract.kt
- api/src/main/java/com/ichi2/anki/api/AddContentApi.kt
Part of #12310.
This cleanup includes:
- fixing ide lint issues
- adding extra `@JvmField` annotations to replicate the initial static fields in java, the targets were `Uri`s and the projection arrays(without the annotations these would have ended in the final bytecode as private static field + getter method)
- as I said when I migrated the class, I enabled the [explicit api mode](https://kotlinlang.org/docs/whatsnew14.html#explicit-api-mode-for-library-authors) as this is a library project and I think would be a good addition going forward. I made the violations as warnings for now( to be able to suppress them for the other api classes) and fixed them for `FlashCardContract`. When we finish cleaning up the api module we should move from warning to strict.
This included specifying the …
> Cleanup FlashCardContract for new api release

- build.gradle
Since we have completely shifted to Kotlin, this can be removed from build.gradle.
> Remove config for JavaCompile in gradle

- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/DecksV16.kt
Only possible on the new backend
AnkiDroid filtered deck default name scheme does not follow upstream current behavior.
Fixes #10622
Deck picker > Three dot menu > Create filtered deck > see if the dialog follows `Filtered deck HH:mm`
- Which method to use for this: https://github.com/ankidroid/Anki-Android/issues/10622#issuecomment-1234898146
- Can't be used with the old schema because it throws a SQlite error
> Use upstream's new filtered deck name pattern

- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportCompleteDialog.kt
- AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
- AnkiDroid/src/main/res/values/02-strings.xml
- AnkiDroid/src/test/java/com/ichi2/anki/stats/AnkiStatsTaskHandlerTest.kt
The usage of neutral buttons in `ExportCompleteDialog`'s is not recommended by Material Design
Part of #11780 
Removed the "Send Email" and "Save to file" buttons and added a "Share" button which opens a sharepicker
https://user-images.githubusercontent.com/59933477/177500000-5d370aa0-dcaa-402b-a732-acb2f80dd46c.mp4
> Fixed `ExportCompleteDialog`'s neutral buttons deprecation

- .github/workflows/opencollective_notices.yml
Based on the review from @david-allison (thank you!)
- documented input parameters
- documented parts of the code that may be non-obvious
- carefully note the considered non-solution on issue comment labeling errors + re-throw
No issue logged - I wanted to do the first batch of notices ASAP so merged, but also wanted feedback and to improve it, so here's a follow-on
Almost entirely comments.
Only functional change is to re-throw the error if there are "could not add a comment" errors, explicitly opening us to maybe double-commenting if you re-run it after fixing error, but definitely not no-commenting.
re-ran it on my fork https://github.com/mikehardy/Anki-Android/pull/105#issuecomment-1251011689 …
> OpenCollective automation documentation / fail-fastness

- api/build.gradle
- api/src/test/java/com/ichi2/anki/api/ApiUtilsTest.kt
After all visibility modifiers were added to the classes in the api module this PR enables strict mode(moving from warnings to errors). Also had to make `ApiUtilsTest` as internal as the api mode applies to all classes in that module.
Ran checks.
> Move to strict for explicit api mode in api module

- AnkiDroid/build.gradle
- AnkiDroid/src/test/java/com/ichi2/anki/AnkiActivityTest.kt
Night mode changing is broken by https://github.com/ankidroid/Anki-Android/pull/12343. This PR is going to fix it by bumping `appcompat` to [appcompat:1.6.0-rc01](https://developer.android.google.cn/jetpack/androidx/releases/appcompat#1.6.0-rc01).
fix https://github.com/ankidroid/Anki-Android/issues/12404#issuecomment-1252331711
> Fix night mode by bumping appcompat to 1.6.0-rc01

- AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
- AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
Resuming the app would trigger a redraw of the counts, and this probably coincided with a card being automatically answered.
Closes #12453
> Fix crash due to probable race condition

- AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.kt
Make the "Card marked as leech" a snackbar instead of a toast #12487
toast replaced with snackbar
> snackbar for leech

- AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.kt
The continue statement appears to have been lost in the Kotlin conversion.
Closes #11845
> Fix legacy importer

- AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
Removed pin option from edit note 
fixes #12475 
> Removed pin option from edit note 

- AnkiDroid/src/main/res/layout/card_multimedia_editline.xml
`ic_attachment_black_24dp` was added as `tools:background` in e7dc7d3d but the file never existed in the codebase. This resulted in an error which prevented the `card_multimedia_editline` layout to render in the IDE's design panel. Fixed it by using the actual icon used by the ImageButton.
Verified that the layout is rendered in the design pane in the IDE.
> Fix layout preview rendering for card_multimedia_editline.xml

- AnkiDroid/src/test/java/com/ichi2/libanki/UndoTest.kt
cleanup : use `with` scope function for col property
> Kotlin Cleanup [UndoTest.kt]

- AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
- AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt
- AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
Unit tests and Pixel 4a API 30 Emulator and Realme 6i API 30
try-catch from the updateValuesFromDeck  is left as it was because the same function is still being used by EmptyCram  and RebuildCram. Once they are also migrated we can let launchCatchingTask to handle this.
> Coroutines migration UpdateValuesFromDeck

- AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
Last usage was removed in https://github.com/ankidroid/Anki-Android/pull/12522, forgot to remove it there.
> [GSoC] Removed unused class UpdateValuesFromDeck

- AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt
- AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
Return from the ConfRemove is not required because anyway ConfChangeHandler don't used it as well. Any exceptions will be handled by CoroutineExceptionHandler.
Unit tests
> [GSoC] Migrated ConfRemove to Coroutines

- AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
- AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt
- AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivityTestBase.kt
I realized that three values are always saved and loaded together, and all sets or non sets in the extras together.
So I grouped them, so that typing indicates that they should appear together as far as nullability is concerned, which allows them to become lateinit
> MultimediaEditFieldActivity cleaning

- AnkiDroid/src/main/java/com/ichi2/anki/Info.kt
- AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.kt
- AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardAppearance.kt
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/AudioField.kt
- AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/template/TemplateFilters.kt
- AnkiDroid/src/main/java/com/ichi2/utils/ContentResolverUtil.kt
- AnkiDroid/src/main/java/com/ichi2/utils/NoteFieldDecorator.kt
- api/src/main/java/com/ichi2/anki/api/AddContentApi.kt
- lint-rules/src/main/java/com/ichi2/anki/lint/rules/DuplicateCrowdInStrings.kt
Replaced basic usages of String.format with Kotlin string templates
Fixes #11449 
Replace `String.format("%s", x)` with `"$x"`
Passed all unit tests
> Replace usages of String.format in with string templating

- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
- AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
- AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
Both implementations run the task within withProgress and run post-operation tasks from their respective handlers from previous implementations.
Unit tests and pixel 4a API 30 Emulator
> [GSoC] Migrated EmptyCram to Coroutines

- AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
- AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
> [KotlinCleanup] Made card arg in onCardEdited not null.

- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DialogHandler.kt
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/MediaCheckDialog.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/BackendMedia.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/Media.kt
It's always a triple. That's similar to tuples as Python has.  Right now, anyway, upstream uses neither tuple nor list but a protobuf.
I may have used a dataclass but don't want to be far from how upstream used to be.
(I also ensured there is no import changes)
> NF: check media is a triple

- AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt
- AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
Since the launch is taking place from inside a AppCompatPreferenceActivity which is not a lifecycleOwner. And launchCatchingTask can only happen from a lifecycleOwner, so a custom CoroutineScope implementation is required which cancels any job (launched from this activity) when the activity gets destroyed and that is achieved by extending 'AppCompatPreferenceActivity: CoroutineScope by MainScope' and calling cancel in onDestroy.
MainScope delegates the CoroutineScope implementation with having Main dispatcher as default for launch{} calls. This is the reason why coroutine is launched using launch{} instead of launchCatchingTask{}
Reference: https://github.com/ankidroid/Anki-Android/pull/12534
> [GSoC] Migrated CollectionTask.Reorder to Coroutines

- AnkiDroid/src/main/java/com/ichi2/anki/FieldEditLine.kt
- AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.kt
- AnkiDroid/src/main/java/com/ichi2/ui/CheckBoxTriStates.kt
this even follow the parameter name of the class it extends
> NF: replace `in` by source for Parceleable

- lint-rules/src/main/java/com/ichi2/anki/lint/utils/LintUtils.kt
Similar to #12593 
Ended up reducing the function to a one-liner with the power of kotlin
```kotlin
fun isAnAllowedClass(classes: List<UClass>, vararg allowedClasses: String): Boolean {
var isInAllowedClass = false
for (i in classes.indices) {
val className = classes[i].name!!
for (allowedClass in allowedClasses) {
if (className == allowedClass) {
isInAllowedClass = true
break
}
}
}
return isInAllowedClass
}
```
ends up as 
```kotlin
fun isAnAllowedClass(classes: List<UClass>, vararg allowedClasses: String): Boolean {
return classes.any { it.name!! in allowedClasses }
}
```
and for more readability, you can write it as
```kotlin
fun isAnAllowedClass(classes: List<UClass>, vararg allowedClasses: String): Boolean {
return classes.any { uClass -> uClass.name!! in allowedClasses }
}
``` …
> Cleanup: Refactor `LintUtils.isAnAllowedClass` to not use `var`

- AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.kt
- AnkiDroid/src/main/java/com/ichi2/async/CollectionOperations.kt
- AnkiDroid/src/test/java/com/ichi2/async/CountModelsTest.kt
Fixes the issue that the function would keep continuing even if the coroutine was cancelled.
This is a continuation to the PR where cancellation had got removed unnoticed https://github.com/ankidroid/Anki-Android/pull/12541
Made the function suspend and use withCol{} internally whenever collection access is required.
YET_TO_BE_DONE
https://developer.android.com/kotlin/coroutines/coroutines-best-practices#coroutine-cancellable
> Fix: getAllModelsAndNotesCount is now cancelled co-operatively

- AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.kt
- AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt
- AnkiDroid/src/main/java/com/ichi2/anki/IntroductionActivity.kt
When I started AnkiDroid, it showed a crash report dialog
Fixes #12156
* Supply a `reportException` parameter, and pass in `false` if starting up
When I committed, I got slowed down by 6 IDE 'warnings', so I fixed the lint warnings (and then a few IDE 'weak warnings' in `CollectionHelper.kt`). Most of these were documentation-related, and a few were dead code.
* Manually on my S21 (Android 12(
* We need more tests
* We need to check ACRA more
- x ] You have performed a self-review of your own code
> fix: don't show crash report dialog on first run

- AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
- AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/RescheduleDialog.kt
* Open Reviewer
* Select "Reschedule - Reschedule in X Days"
* Close the dialog
* Close the reviewer
* Memory leak
```
┬───
│ GC Root: Thread object
│
├─ android.os.HandlerThread instance
│    Leaking: NO (PathClassLoader↓ is not leaking)
│    Thread name: 'queued-work-looper'
│    ↓ Thread.contextClassLoader
├─ dalvik.system.PathClassLoader instance
│    Leaking: NO (RescheduleDialog↓ is not leaking and A ClassLoader is never
│    leaking)
│    ↓ ClassLoader.runtimeInternalObjects
├─ java.lang.Object[] array
│    Leaking: NO (RescheduleDialog↓ is not leaking)
│    ↓ Object[138]
├─ com.ichi2.anki.dialogs.RescheduleDialog class
│    Leaking: NO (a class is never leaking)
│    ↓ static RescheduleDialog.INSTANCE
│                              ~~~~~~~~
╰→ …
```
> fix: 'RescheduleDialog' memory leak

- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
- AnkiDroid/src/main/res/values/03-dialogs.xml
Due to Scoped Storage, we will no longer need this dialog It was added because people were complaining about the storage permission prompt, and this will no longer be shown
We remove this now to remove the burden on translators and a step for developers to test a new version of the app.
Later, we'll remove this function entirely.
See: issue #5304 - scoped storage
* On-device: S21 (Android 12). Cleared data, deleted `/AnkiDroid` and ran the app
* Unit tests pass
* Didn't try instrumented/lint tests. CI ahoy!
> chore: remove 'welcome dialog'

- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportCompleteDialog.kt
- AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
- AnkiDroid/src/main/res/values/02-strings.xml
This bug appeared in 8f18dc3d1 which fixed the deprecation of the neutral button. The code tried to present to the user in the same intent chooser both an activity to save the file(Intent.ACTION_CREATE_DOCUMENT) and activities to share the file(Intent.ACTION_SEND). This doesn't work because the Intent.ACTION_CREATE_DOCUMENT expects to be called with `startActivityForResult` as it returns the uri to the newly created empty(0 bytes) file and expects the caller to actually write to that handle(while ACTION_SEND is more of a fire and forget type).
My changes fix this by providing to the user two options when it's finally time to handle the exported collection:
- Select where to save file
uses Intent.ACTION_CREATE_DOCUMENT to create and write to a file in a location selected by the user
- …
> Fix 0 bytes file output when exporting collection

- AnkiDroid/src/main/res/menu/reviewer.xml
To group the audio-related items at the lower position (as on Anki Desktop) and to place "Deck options" at the bottom of the menu
n/a
Change the order of the items on reviewer.xml
Checked on my physical device
n/a
> Change the order of audio-related items on action menu of study screen

- AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.kt
otherwise the API33 "post notifications" permission dialog pops up and screen measurements fails
Unlogged, but running `./gradlew jacocoTestReport` locally while verifying other PRs was failing for me because I happened to have an API33 emulator up at the time
Conditionally grant the permission
Failed before the change, re-ran the tests, passed after the change
> fix(test): we need notification permission on tests that measure screen

- AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt
@divyansh-dxn 
While looking at #12592 I realized some code were repeated a lot. I'd love your opinion about this refactoring.
Once this last PR is merged, we can even remove the pre/post parts and just keep a single function there. 
Actually, I realize that if we had done it first, it would have made PR even simpler to review, since in this case, the launchCollectionTask would be replaced by a more or less similar call, with something that does the UI and then inside does the background change
> NF: refactor DeckOption conf change handler

- tools/test-commits.sh
TIL that you can still kill a machine with 64GB+64GB RAM+Swap if you run enough Kotlin on it. Thanks gradle.
Nothing logged, but my laptop definitely knew it
```
Oct 13 13:58:43 bistromath systemd-oomd[6489]: Killed /user.slice/user-1000.slice/user@1000.service/app.slice/app-org.gnome.Terminal.slice/vte-spawn-0eaf5a40-aeed-40d9-92fd-28a19a40d3fa.scope due to memory pressure for /user.slice/user-1000.slice/user@1000.service being 76.59% > 50.00% for > 20s with reclaim activity
Oct 13 13:58:43 bistromath systemd-oomd[6489]: Killed /user.slice/user-1000.slice/user@1000.service/app.slice/app-org.gnome.Terminal.slice/vte-spawn-32aaa1a7-320f-46f8-afb9-49c2447a2b2a.scope due to memory pressure for /user.slice/user-1000.slice/user@1000.service being 65.84% > 50.00% for > 20s with reclaim activity …
```
> test(perf): avoid OOM while running big batches of commit tests

- AnkiDroid/src/main/java/com/ichi2/anki/BackendImporting.kt
- AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportDialog.kt
- AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
- AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/CardService.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/BackendImportExport.kt
- AnkiDroid/src/main/res/menu/card_browser_multiselect.xml
- AnkiDroid/src/main/res/values/02-strings.xml
- AnkiDroid/src/main/res/values/07-cardbrowser.xml
Add functionality to be able to select cards/notes in the browser and export them from the browser themselves
Fixes #8045
With the new backend (see https://github.com/ankidroid/Anki-Android/pull/8159#issuecomment-1186151840), exporting selected cards and notes is supported. This PR handles the UI of exporting selected cards, and adds this case to utilise the functionality being provided by collectionV16.
https://user-images.githubusercontent.com/86671025/192843998-dce39526-6bc3-4358-96cc-3a20f287e1f1.mp4
https://user-images.githubusercontent.com/86671025/192843979-3e780d71-76fb-4ca7-9da9-6222aebde173.mp4
> Export selected cards from Browser

- AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/scopedstorage/migrateuserdata/MigrateUserData.kt
- AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/ScopedStorageMigrationIntegrationTest.kt
When using a Worker or a thread, we won't have a task listener as argument. 
That may not be entirely ideal, but that 's a good compromise, I believe, between avoiding to rewrite too much, and ensuring that moving to a worker remains simple
> NF: MigrateUserData limit its use of TaskListener

- AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/NotificationChannelTest.kt
Channels are never deleted. So if this test is run on an AnkiDroid version that has more channels in previous installation, the test fails. It is very rare, because it requires that you add a channel and then remove it. However, this can occur:
* during development time, when you regularly change branch
* when doing bisect
> Correct `testChannelCreation`

- AnkiDroid/src/main/java/com/ichi2/utils/FileUtil.kt
- AnkiDroid/src/test/java/com/ichi2/utils/FileUtilTest.kt
Indicating a number of files in notification may speak more than a number of bytes.
> NF: FileUtil returns more information about folder content

- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
- AnkiDroid/src/main/java/com/ichi2/anki/export/ExportListener.kt
- AnkiDroid/src/main/java/com/ichi2/async/TaskListenerWithContext.kt
First part of #12659 and of another PR to come. Which needs to improve nullability for ease of creating notification from scoped storage migration
> Task non null

- AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
We didn't handle the user cancelling the file selection(like hitting back) when trying to export the collection.
Fixes #12676
Minor change.
> Fix crash when user aborts file selection while exporting

- AnkiDroid/src/main/java/com/ichi2/compat/CompatV26.kt
Note that NoSuchFileException is a descendant of IOException, so this rewriting is equivalent
> NF: cleanup compatV26

- AnkiDroid/src/main/res/menu/reviewer.xml
On action menu of Study screen, the group of whiteboard-related item is divided by the other items. This PR is to fix it.
Fixes #12672
Change the order of the items on [AnkiDroid/src/main/res/menu/reviewer.xml](https://github.com/snowtimeglass/Anki-Android/pull/7/commits/ba1549dec3d6e44a9b32fc27477ecc2ca0784903#diff-7bbb2a2db563216b3008620948f5af3cf4d4c702426a2719159a115258790484) as follows.
- Move "Undo ~" above "Clear whiteboard"  (i.e. move "Undo ~" to the top of the menu)
- Move "Save whiteboard" and "Disable/Enable whiteboard" above "Flag card" (i.e. move "Flag card" item below the group of whiteboard-related items)
Checked on physical device
> Make whiteboard related items grouped

- AnkiDroid/src/main/res/values-ru/01-core.xml
- AnkiDroid/src/main/res/values-ru/02-strings.xml
- AnkiDroid/src/main/res/values-ru/07-cardbrowser.xml
- AnkiDroid/src/main/res/values-zh-rTW/02-strings.xml
Cleaning "real translation" queue out to merge some add/removes in #12367
> Updated strings from Crowdin 20221017-1

- AnkiDroid/src/main/java/com/ichi2/anki/preferences/CustomSyncServerSettingsFragment.kt
- AnkiDroid/src/main/java/com/ichi2/anki/preferences/SettingsFragment.kt
- AnkiDroid/src/main/java/com/ichi2/anki/preferences/SyncSettingsFragment.kt
- AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt
- AnkiDroid/src/main/java/com/ichi2/anki/web/CustomSyncServer.kt
- AnkiDroid/src/main/java/com/ichi2/preferences/HtmlHelpPreference.kt
- AnkiDroid/src/main/java/com/ichi2/preferences/IncrementerNumberRangePreferenceCompat.kt
- AnkiDroid/src/main/java/com/ichi2/preferences/NumberRangePreferenceCompat.kt
- AnkiDroid/src/main/java/com/ichi2/preferences/PreferenceUtil.kt
- AnkiDroid/src/main/java/com/ichi2/preferences/SeekBarPreferenceCompat.kt
- AnkiDroid/src/main/java/com/ichi2/preferences/VersatileTextPreference.kt
- AnkiDroid/src/main/java/com/ichi2/preferences/VersatileTextWithASwitchPreference.kt
- AnkiDroid/src/main/res/layout/preference_widget_switch_with_separator.xml
- AnkiDroid/src/main/res/values/10-preferences.xml
- AnkiDroid/src/main/res/values/attrs.xml
- AnkiDroid/src/main/res/values/constants.xml
- AnkiDroid/src/main/res/values/preferences.xml
- AnkiDroid/src/main/res/xml/preferences_custom_sync_server.xml
- AnkiDroid/src/test/java/com/ichi2/anki/servicemodel/PreferenceUpgradeServiceTest.kt
- AnkiDroid/src/test/java/com/ichi2/libanki/sync/HttpSyncerTest.kt
- AnkiDroid/src/test/java/com/ichi2/libanki/sync/RemoteMediaServerTest.kt
This implements my own suggestion from the point 2 in Remaining issues in #12112 nearly verbatim, except I added a note about Sync url preference expecting the full URL as discussed in #12269. @dobefore What do you think?
https://user-images.githubusercontent.com/1710718/189485733-83b66dcf-eb76-43d5-b062-9910e4b25b17.mp4
As usual, please see the commits for individual changes.
Note that in the first commit there's a link to the fragment https://docs.ankidroid.org/#_custom_sync_server which doesn't exist yet. I suppose the docs will have to be amended for the new release, and this section could be added later.
Also note that Accessibility scanner complains about two things; not sure if this is actionable.
* Help preference summary: Link text. Consider using more descriptive text in the …
> Make custom sync server preferences easier to understand

- AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt
Fix `@KotlinCleanup` tag for better code styling.
Related to #10489 
~This code changes from using a variable representation to a scoped function. This helps to enhance readability. The variable is referenced within scope by `it`.~
Originally, the intention was to switch from a variable representation to a scoped function. Further suggestions have instead favored switching to `useHashMapOf` to make things more Kotlin-like.
`getResourceString` is favored over `targetContext.getString` for its simplicity.
This has been tested both as an individual test file and as part of the entire gradle test suite, including testing with incorrect values to ensure they are caught:
- `./gradlew AnkiDroid:testPlayDebugUnitTest --tests com.ichi2.anki.DeckPickerTest.verifyCodeMessages`
- `./gradlew …
> Kotlin Cleanup: Changed to scope function in DeckPickerTest

- AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
`showError` could crash if the activity was destroyed. 
In this case, we don't have much we can do, so we ignore the error.
Fixes #12718
Ignore the exception
Untested
> fix: crash showing error if activity is  destroyed

- AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt
Replaced basic usages of String.format with Kotlin string templates
Related to https://github.com/ankidroid/Anki-Android/issues/11449
Replace `String.format("%s", x)` with `"$x"`
Passed all unit tests
> Replaced String.format() with string template in Collection

- AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.kt
Replaced basic usages of String.format with Kotlin string templates
Fixes https://github.com/ankidroid/Anki-Android/issues/11449
Replace `String.format("%s", x)` with `"$x"`
Passed all unit tests
> Replaced String.format() with string template in Anki2Importer

- AnkiDroid/src/main/java/com/ichi2/anki/preferences/ReviewingSettingsFragment.kt
[Bug] app (2.16alpha88) crashes on review change #12739
changed any to string then integer
> fixes crash caused by cast exception

- .github/workflows/tests_emulator.yml
1) emulator tests have become pretty flaky (again): https://github.com/ankidroid/Anki-Android/actions/workflows/tests_emulator.yml
2) the desugar library is giving me trouble but works if you clear gradle cache #12665 
I believe the emulator can be optimized a bit by doing the zygote race workaround only during snapshot generation, and I think a fresh snapshot could help (it doesn't ever sit for the required "github caches expire after a week of no access" week where it would be a cache miss and refresh.
And I believe a gradle cache clean would allow the desugar library bump to go in
So I want a way to purge those caches and get fresh cache contents
Related #12665 (or 12164)
This should have no effect after this is merged *until you run the emulator test on main manually with cache clear …
> GitHub cache clear

- .github/workflows/tests_emulator.yml
missed the inclusion of the new optional manual input var to recreate after deleting
Work on workflow files, push them and test after merging a PR because you can't test locally really, and it's all really slow
You can't. But I'm testing after the fact by watching the automated runs, and the manual runs with the box ticked, and the manual runs without the box ticked
yaml / github expression syntax is arcane
> fix(test): correctly rebuild AVD snapshot if we cleared it

- .github/workflows/tests_emulator.yml
- previous cache key was generating empty final var every run, so was useless anyway
- new key will be empty nearly all the time (when not specified) so matches previous behavior
- new key will have a value when clearing cache, so will generate new caches for AVD
Caches are immutable, so if a primary cache key is a hit, **the cache will not be updated**
This was failing the final testing scenario of the work to allow AVD cache clear / rebuild - the rebuild was happening when I did a manual run with the input to clear cache, but it was not actually uploading the fresh AVD snapshot because of a primary key hit.
I can't without merging it to main, then running it
It's all subtle, this CI / cache business.
Here's your cache update link: …
> fix(test): ensure we can have a non-primary cache hit when clearing cache

- .github/workflows/lint.yml
- .github/workflows/tests_unit.yml
with these, I may be able to get desugar PR through CI since it passes locally now after deleting my local caches
Related #12749 (test results etc)
Same approach as the other cache clearing work, but this time I do not have to worry about cache key stuff (that was only for the emulator snapshot, which is not in play here)
Can't really test, we'll see when it runs...
github workflows are great but developing them is slow
> fix(test): allow cache clearing in lint + unit test workflows as well

- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.kt
This PR fixes an issue which causes the app to crash when adding images that exceeded the size limit(1MB)
Fixes #12730 
Moving the call of `MultimediaEditFieldActivity::done()` to somewhere after FileCropDialog is created.
The fix has been tested on OnePlus 7 Pro with Android 11 without issue.
To perform a test, add an image that exceeds 1MB to the card and select crop in the crop suggesting dialog and observe if the app crashes.
> Fixed a crash on images exceed 1MB

- AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
An attempt to fix issue #12675, on the emulator and lower versions devices it works. Don't have access to a Samsung device with the mentioned api version(12). Ideally this would be merged before a new alpha release so it can be tested.
If this doesn't work I'll revert the commit and look at other options. 
I'll manually close issue #12675, if working.
Ran the tests, manually verified the flow on an emulator.
> Fix permission missing crash when sharing exported collection

- build.gradle
JDK14 and JDK16 where interim releases before the JDK17 LTS, no need to support them since 17 works fine. 18 appears to work fine as well.
https://en.wikipedia.org//wiki/Java_version_history#Release_table
Nothing logged, just looking at build/CI/release infra
Tested JDK 11, 17 and 18 locally with
`/bin/nice -n 19 ./gradlew clean jacocoTestReport :api:lintRelease :AnkiDroid:lintPlayRelease ktlintCheck lint-rules:test`
I've been doing Java long enough I'm still sort of surprised to see their version numbers (finally!) shake loose and development continue. But I guess we're on Kotlin so :shrug: :laughing: 
> build: support JDK11 and JDK17 (the two LTSs) and JDK18

- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ExportDialog.kt
- AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt
We save MOD and date. We intend to take it into account if sync is not activated.
MOD because if there was no change since last export, it's clear we don't risk loosing data.
Actual time because that will ensure we can know how much time of review/card creation can be lost.
> NF: save last successful export

- AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt
There's a visibility issue in DeckOptions, although the mOptions field is assigned a new value, in confChangeHandler the old value(before the assignment) appears. I'm not sure exactly why this happens(I'm assuming this has something to do with the generated java lambdas under the hood).
I fixed it by moving the mOptions assignment inside the lambda(also makes sense as the required Collection reference is in scope there).
Fixes #12622
Ran the checks, manually verified the app.
> Fix options group not updating in deck options

- .idea/dictionaries/davidallison.xml
- AnkiDroid/src/main/AndroidManifest.xml
- AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt
- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
- AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt
- AnkiDroid/src/main/java/com/ichi2/anki/notetype/NotetypeAdapter.kt
- AnkiDroid/src/main/java/com/ichi2/anki/notetype/NotetypeUiModel.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/ModelsV16.kt
- AnkiDroid/src/main/res/layout/activity_manage_note_types.xml
- AnkiDroid/src/main/res/layout/dialog_new_note_type.xml
- AnkiDroid/src/main/res/layout/item_manage_note_type.xml
- AnkiDroid/src/test/java/com/ichi2/testutils/ActivityList.kt
This PR enables the new backend for viewing and changing notetypes. With the new implementation:
- add new activity for new backend implementation, ManageNotetypes(the old activity ModelBrowser would be deleted when the new backend becomes the default)
- full support for coroutines(and with progress) with all backend calls
- improve UI for the notes types list by using CardView(ideally we would use the material cards but we don't currently inherit from the material themes)
- fix some of the UX reported issues, like providing a uniform add action(by using the platform FloatingActionButton) and stop using the hard to discover context menu in favor of in layout actions for each item
- enable some checks for the notes types names when renaming or adding new entries
- introduce some UI model …
> Implement new backend for note types activity

- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
- AnkiDroid/src/main/res/values/02-strings.xml
It suspend during the important part of the migration and then call a function to start the service. This one is TODO for the moment.
We'll need this as a separate function since we'll need to start the service also if the service is not working and we still have work to do
> Add `migrate` in DeckPicker

- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
- AnkiDroid/src/main/java/com/ichi2/anki/pages/AnkiServer.kt
- AnkiDroid/src/main/java/com/ichi2/anki/pages/CardInfo.kt
- AnkiDroid/src/main/java/com/ichi2/anki/pages/CsvImporter.kt
- AnkiDroid/src/main/java/com/ichi2/anki/pages/DeckOptions.kt
- AnkiDroid/src/main/java/com/ichi2/anki/pages/PageChromeClient.kt
- AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt
- AnkiDroid/src/main/java/com/ichi2/anki/pages/Statistics.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/BackendDeckOptions.kt
Free screen + spare a lot of work migrating DeckOptions.kt to use fragments and the androidx.Preference
- Add the CollectionV16's deck options methods on BackendDeckOptions.kt
- Add the new page
- Use it if the new backend is enabled
https://user-images.githubusercontent.com/69634269/186731680-548ff459-7c7d-46e3-a973-b12d6124a46f.mp4
> Add Anki's new Deck Options page

- AnkiDroid/src/main/java/com/ichi2/anki/MediaRegistration.kt
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/AudioField.kt
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/AudioRecordingField.kt
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioRecordingFieldController.kt
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicMediaClipFieldController.kt
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicTextFieldController.kt
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/IField.kt
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/ImageField.kt
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/MediaClipField.kt
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/TextField.kt
- AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/NoteService.kt
- AnkiDroid/src/test/java/com/ichi2/anki/services/NoteServiceTest.kt
demand -
1. replace setHasTemporaryMedia(), hasTemporaryMedia() to property
modify -
1. replace with `var hasTemporaryMedia:Boolean` in IField.kt, and the following class relay on this property
1. A small step towards getting #10489 out of the way
2. Limit the mutability of `currentHasTemporaryMedia` in `AudioField`, exposing multiple mutable point might cause unexpected result.
Refactored the code to be more Kotlin-y.
Since changing interface affects on its children classes, I simply choose
`./gradlew jacocoTestReport`
to check all the tests works fine.
> [KotlinCleanup] - turn set/hasTemporaryMedia into a property

- AnkiDroid/build.gradle
image cropper was going out of date because publishing coordinates change, move coordinates, get up to date
> build(deps): new coordinates for image cropper / bump to 4.5.0

- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
fix "yes" and "no" actions in Empty Cards alert dialog which appears to be switched.
Fixes #12790
> fix "yes" and "no" actions in Empty Cards alert dialog

- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
- AnkiDroid/src/main/res/values/01-core.xml
- AnkiDroid/src/main/res/values/03-dialogs.xml
Capitalize the first letter of ”yes” of alert dialog button of "Empty cards" feature
Fixes #12788
- Create a new string of "Yes" for alert dialog on 03-dialog.xml
- Replace the current string ("yes") with the new one above ("Yes") on Deckpicker.kt
- Remove the current string ("yes") on 01-core.xml
> Capitalize the first letter of ”yes” of alert dialog button

- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerBackupNoSpaceLeftDialog.kt
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckPickerNoSpaceLeftDialog.kt
- AnkiDroid/src/main/res/values/03-dialogs.xml
- AnkiDroid/src/main/res/values/04-network.xml
- AnkiDroid/src/main/res/values/09-backup.xml
As intended, I have followed the first preference as suggested by @mikehardy  and @Arthur-Milchior  and made the following changes.
Changes include creating new keys for the strings as follows:
<string name="backup_deck_no_space_left">Backup not saved. Not enough space left on SD card. Lower the backup depth or remove some other files.</string>
<string name="sd_space_warning">Less than %d MB space on your SD card left.\nFree some space to avoid data loss.</string>
<string name="sync_write_access_error">The downloaded file couldn’t be saved to the SD card. Either the card is mounted read-only or there isn’t enough space.</string>
<string name="sd_card_full_title">SD card full</string>
<string name="sd_card_almost_full_title">SD card almost full</string>
The term "SD Card" is now Storage …
> Remove "SD cards" from strings Fix #12777

- AnkiDroid/build.gradle
- build.gradle
Had to untangle a transitive dep collision for androidx.test:core between fragment-testing and the regular testing deps
Solved it by first parameterizing the versions (so the change was easier to see), then excluding the core test dep from fragment-testing's dependency
Works with the previous androidx.test:core versions, works with the new/current ones
See https://github.com/android/android-test/issues/1587
> Dependency updates 20221111

- AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
- AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
- AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
- AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/Undo.kt
- AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
- AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.kt
Moves the nonTaskUndo() method from CollectionTask to eliminate unrelated code and make it easier to delete the class. Also deletes the UndoService wrapper class for Undo as it was unused and not really needed.
Ran the tests.
> Move unrelated code from CollectionTask

- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt
Preventing the report generation due to the crop Exception that was generated when back was pressed.
This PR will fix the report generation issue that was arising due to Canhub's `CropException` . The report was generated when we used to enter the crop image option and pressed back without doing anything. This issue was reported by some user and I found it on ACRA and then reproduced it, also the same was reported by other users as well. The reports are of no action to take on as the Exception is put by Canhub Dev. and can be countered by catching it, they have knowingly put it there but it is of no relevance to us
Fixes #12768
After committing the changes the exception is no more reported
Please describe the tests that you ran to verify your changes. Provide instructions so we can …
> CropException fix

- AnkiDroid/src/main/java/com/ichi2/libanki/sched/BaseSched.kt
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.kt
AnkiDroid takes minutes to start on my collection. That's because `unburyCards` iterate over each deck and unbury in them one by one instead of just doing a single unbury query.
I'd love your review @dae, since you introduced this implementation in 3c32c7669a95d03b23566e359e3c5e65d4c9a3e4 , removing the more efficient implementation in schedV1 and V2. If there was a reason to do so, I fail to see them, so I may be breaking some things I don't know about.
Also, I'm confused about why the comment states " Only used for tests." which is false as can indicate android studio.
I'm only doing the correction for V2, since I don't have access to V3. But I'd clearly appreciate for V3 not to do an explicit loop, otherwise this will be very slow again.
Simultaneously, I'm adding comment on unbury …
> Unbury without loop

- AnkiDroid/src/main/res/drawable/horizontal_gradient_separator.xml
- AnkiDroid/src/main/res/layout/introduction_layout.xml
- AnkiDroid/src/main/res/values/colors.xml
From #12588 
_Even worse, with current main as of 20221114 at least, on a fresh install on Android 6 emulator it just crashed for me with a problem doing a linear gradient in the view XML_
The issue was introduced in f4cd5c06d01f930ed5d37d89d4d214a42d17fece. Surprisingly it works on a lower version but not marshmallow. I simply reverted the commit as the UI changes from that commit, although nice, affect app startup which is critical.
Manually verified the app startup on lollipop, marshmallow and the latest versions.
> Fix regression on marshmallow due to gradient usage

- AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
Leftover work from fixing issues with the suspend and bury menu items in the reviewer. The reschedule menu item was changed to use the proper method when being setup. The menu item now appears:
Fixes #12843
Ran the tests, manually verified the app on lollipop and the latest version.
> Fix menu item crash when Reschedule set to appear in toolbar

- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
- AnkiDroid/src/main/java/com/ichi2/ui/BadgeDrawableBuilder.kt
~~Built on top of #12840 to make the app able to start on marshmallow to actually test things.~~
The sync button badge was not showing in marshmallow(I presume it wasn't showing in upper versions, like nougat but I didn't test it). The issue was that the badge drawable was loaded through VectorDrawableCompat but the drawable itself wasn't a vector drawable(it's a simple ShapeDrawable). Reverted to use the ContextCompat.getDrawable() to initialize the normal, non vector badge drawable.
Fixes #12825
Manually verified that the badge appears in marshmallow, also API levels 31 and 33.
> Fix missing sync menu item badge in marshmallow

- AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
- AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
Part of #7108. The minimum amount of work to migrate this task to coroutine to remove it from CollectionTask. There's no need for extra refactoring or TODOs as the enclosing class, ModelFieldEditor, will be removed in the future.
Ran the tests, manually verified the app.
> Migrate the DeleteField task to coroutine

- AnkiDroid/src/main/java/com/ichi2/anki/DrawingActivity.kt
The title of Drawing screen is written in the system language even if the language of AnkiDroid settings is changed to another one. This PR is to fix it.
Fixes #12856
> Make the title of Drawing screen translated

- AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/MediaTest.kt
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/ImageField.kt
Used `"""` instead of " to avoid `\" `
Bug #11451 
> Used """ instead of " to avoid \"

- AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.kt
Remove `init` and initialise the properties directly
> Remove `init` and initialise directly

- AnkiDroid/src/main/java/com/ichi2/utils/FileUtil.kt
- Made URI argument not null
- Removed explicit type argument for fixing warning
- Tests
> [KotlinCleanup] FileUtil

- AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.kt
KotlinCleanup
replaced is with equalTo function
> KtCleanup replaced `is` with equalTo 

- AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
- AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.kt
~~Blocked by #12781 so the task hander could also be deleted(first two commits are from that PR).~~
Part of https://github.com/ankidroid/Anki-Android/issues/7108. The minimum amount of work to migrate this task to coroutine to remove it from CollectionTask. There's no need for extra refactoring or TODOs as the enclosing class, ModelFieldEditor, will be removed in the future.
Ran the tests, manually verified the app.
> Migrate the RepositionField task to coroutine

- AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.kt
- AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt
- AnkiDroid/src/main/java/com/ichi2/ui/RtlCompliantActionProvider.kt
The Undo button in `StudyOptionsFragment` does not work. This issue occurred after creating `RTLActionProvider`, which allows icons to be mirrored for right-to-left languages. This fix makes this undo button work as expected. However, it still does not allow the user to undo the last card in a deck from `StudyOptions`. 
Fixes #12277, I wouldn't say "fixes" because I know this is not an ideal code change. **[Edit: I'm saying it fixes it - Mike H]**
I struggled to fix this problem for a long time, and finally threw in the towel on being able to solve it "correctly". I understand my code is not exactly desirable, but I wanted to share my findings and the things I tried to help save others time if they make a cleaner fix in the future.
The Undo button is inflated from `StudyOptionsFragment`, …
> Make undo button work in StudyOptions

- AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
The estimated studying time on Reviewer screen is translated on language change.
Fixes #12888
Switching the context passed into the Util method from Application to Activity context seemed to resolve the issue.
https://user-images.githubusercontent.com/76740999/204138731-d8b2e8c0-1c72-47dc-bbd6-357f48b2a604.mp4
> Fix for the translation issue of the estimated studying time on Reviewer screen

- AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
Use just "Undo" instead of "Undo %s" for the item of "Undo" if there is no string of undone target.
https://github.com/ankidroid/Anki-Android/blob/9ac9e6e3047184d79a4044129254f2ee96a4f8bc/AnkiDroid/src/main/res/values/01-core.xml#L76
https://github.com/ankidroid/Anki-Android/blob/9ac9e6e3047184d79a4044129254f2ee96a4f8bc/AnkiDroid/src/main/res/values-ja/01-core.xml#L92
https://github.com/ankidroid/Anki-Android/blob/9ac9e6e3047184d79a4044129254f2ee96a4f8bc/AnkiDroid/src/main/res/values/01-core.xml#L74
https://github.com/ankidroid/Anki-Android/blob/9ac9e6e3047184d79a4044129254f2ee96a4f8bc/AnkiDroid/src/main/res/values-ja/01-core.xml#L90
Fixes #12853
Separate cases by presence/absence of string of undone target on Reviewer.kt
_Please, go through these checks …
> Use "Undo" instead of "Undo %s" for the item of "Undo" if there is no string of undone target

- pre-commit
idk why, but prettier is always being runned even if there isn't a javascript file being edited so it got my commits cancelled repeatedly
Fixes #12850
try catch the error
trying a commit with no internet and without prettier installed (but with npx installed)
> Fix prettier throwing errors

- .github/workflows/tests_unit.yml
- AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt
- AnkiDroid/src/test/java/com/ichi2/anki/dialogs/DeckPickerContextMenuTest.kt
Also fixes a failing unit test with the new schema, and adds the new schema to CI. I originally had the Ubuntu runner checking both new and old schemas, but that makes it run slower, so I've switched it so that the Ubuntu one only checks new schema, and the other two check legacy.
> Fix hang when syncing media with new schema

- AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
- AnkiDroid/src/test/java/com/ichi2/anki/AnkiActivityTest.kt
See
https://github.com/ankidroid/Anki-Android/issues/12617
Fixes #12617
The initial issue was that when the back button is pressed to exit the app, the application calls the onDestroy method. This prevents the onConfigurationChanged method from being called when resuming the application after the system theme has been updated, since the activity has been destroyed. I have proposed a change when a simple check of the system theme and update of the theme is done in the on create of AnkiActivity (copied from AnkiDroidApp.kt line 190)
Ran this on a physical device running the latest version of the main branch. Used the following steps to reproduce from the initial issue
1. have day mode in the mobile
2. in Ankidroid, settings - appearance - …
> [Bug] day/night mode is not switched when AnkiDroid closed by the back button

- AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
Fixes #12914
Fundamentally reverts the changes made on 5d09acfd99971de58029d2bab19d0a1d7792301b. I have tried some approaches to avoid casting, like using in, out, and where operators, but always had to cast something 
1. Have decks with subdecks
2. Open the deck picker
> Fix expanders not appearing

- AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
Fixes #12910
Return early if the deck does not exist anymore (col.decks.select(did) was doing the crashes)
1. Long press a deck
2. Create shortcut
3. Delete the deck
4. Open the shortcut
5. Don't see any crashes
Reviewer.kt is too big and clumped, if I may say so, to me to deal with it right now so I left some TODOs. Not crashing is already some progress to me 😁
> Fix app crashing if deck from shortcut does not exist anymore

- .github/workflows/sync_translations.yml
- tools/update-localizations.py
`macos-latest` will become macos-12 shortly and I don't think this will have any effects other than to alter the python interpreter (as I discovered in other repos...) so just making sure we resolve to python3 as that is required for our i18n work
No fix, but related: https://github.com/ankidroid/Anki-Android/pull/12927#issuecomment-1337441422
- For local machines use the `#!/usr/bin/env python3` she-bang style to resolve pyrhon3 from PATH
- For CI use the `python` interpreter directly to call script as documented by setup-python action
Untested! But github actions are like that ;-) - hard to test them. Change it tiny though and I will repair it if it breaks when I do an i18n sync
https://unix.stackexchange.com/questions/12736/how-does-usr-bin-env-know-which-program-to-use/12751#12751 …
> Forward-port github workflows to macos-12

- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt
Fix position of buttons in change deck dialog.
> Fix position of buttons in change deck dialog

- .github/workflows/tests_unit.yml
- AnkiDroid/src/test/java/com/ichi2/libanki/CollectionPersistentTest.kt
Introduces a new matrix variable for jobs so we get to test the old code as well as run tests for the new backend. At the moment I enabled the new backend just for Ubuntu. Also because this PR introduces two different configurations for Ubuntu CI runner, I changed the name of the job to mention both the os and the legacy schema value so reviewers/contributors can see more easily  in which situations the PR fails.
Fixes #12920 
Ran on my fork.
> Enable extra CI checks using  the new backend

- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt
Avoid use of var
Replaces a var declaration in CustomStudyDialog.kt with a "val" declaration instead
Since the code was checking if some args were null, I instead set to a val and checked the value using the ?: operator. 
Unit tests, sdk version 29
> change var null check with elvis operator
